- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/src/CosmosClient.ts
- sdk/cosmosdb/cosmos/test/functional/client.spec.ts
When initializing the client with an invalid endpoint, we currently default to localhost which causes unexpected failures that aren't related to an invalid endpoint. We now parse the endpoint as a URL to immediately throw an error that gives an immediate understanding of the failure.
Closes https://github.com/Azure/azure-sdk-for-js/issues/4822
> [Cosmos] Throws when connection endpoint is invalid in client init

- sdk/eventhub/event-hubs/src/index.ts
- sdk/eventhub/event-hubs/test/receiver.spec.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
> [Event Hub] formatting

- sdk/sql/arm-sql/package.json
- sdk/sql/arm-sql/src/sqlManagementClientContext.ts
Override sendOperationRequest to always set Accept header to workaround issue  #10004
Closes #10004
> [arm-sql] Override sendOperationRequest to always set Accept header

- sdk/cognitiveservices/cognitiveservices-anomalydetector/LICENSE.txt
- sdk/cognitiveservices/cognitiveservices-anomalydetector/README.md
- sdk/cognitiveservices/cognitiveservices-anomalydetector/package.json
- sdk/cognitiveservices/cognitiveservices-anomalydetector/src/anomalyDetectorClient.ts
- sdk/cognitiveservices/cognitiveservices-anomalydetector/src/anomalyDetectorClientContext.ts
- sdk/cognitiveservices/cognitiveservices-anomalydetector/src/models/index.ts
- sdk/cognitiveservices/cognitiveservices-anomalydetector/src/models/mappers.ts
This is for the issue: https://github.com/Azure/sdk-release-request/issues/573 
1. Regenerated AnomalyDetector SDK
2. Changes TS Sample to JS Sample
3. Validated both JS & HTML Samples. Working fine
**Version change**
There are no breaking changes except one line. `granularity` is set `nullable:false` in this change. It did not have that property previously. 
But, even without this `nullable` property set to false, in the previous code, we cannot send in a Request with no granularity or null/undefined granularity. The service will throw an error with the message `granularity` is required. I have validated this with the previous SDK. 
There is a possibility that if the service is updated now for throwing the error. But, I doubt that is the case. The Azure portal still mentions this as …
> Regenerate Cognitive Services Anomaly Detector SDK 

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
> [Service Bus] Move scheduledMessageCount to TopicRuntimeProps from SubscriptionRuntimeProps

- sdk/keyvault/keyvault-certificates/src/index.ts
- sdk/keyvault/keyvault-certificates/test/public/list.spec.ts
- sdk/keyvault/keyvault-certificates/test/public/lro.delete.spec.ts
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-secrets/src/index.ts
> [Key Vault] formatting

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
- sdk/textanalytics/ai-text-analytics/swagger/README.md
This changes the `text` property, of the output type `SentenceSentiment`, to be no longer optional. This mirrors the latest fix to the specs for v3.0 stable: https://github.com/Azure/azure-rest-api-specs/pull/10179. I agree with @bterlson that this change should not be considered breaking because it is to an output type.
> [Text Analytics] Regenerating the SDK using the most recent and fixed version of swagger v3.0

- eng/pipelines/templates/stages/cosmos-sdk-client.yml
- eng/pipelines/templates/steps/cosmos-integration-public.yml
This PR addresses https://github.com/Azure/azure-sdk-tools/issues/778 where the logic to start the Cosmos DB emulator had diverged across JS, Python and Java. With this change the start logic is the same.
> Use the common Cosmos DB template to start the emulator.

- sdk/cosmosdb/cosmos/src/client/Item/Item.ts
- sdk/cosmosdb/cosmos/src/client/Item/Items.ts
- sdk/cosmosdb/cosmos/src/common/helper.ts
- sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
- sdk/cosmosdb/cosmos/test/functional/client.spec.ts
> [CosmosDB] formatting

- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/git-hooks/pre-commit
This hook will run on every commit to run `prettier` on the staged changes only (not whole files). The prettier configuration file used is https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/.prettierrc.json. More details about the hook can be found [here](https://github.com/Azure/azure-sdk-for-js/pull/10219#issuecomment-663737624).
To install the hook, run `rush update`.
> Adding git pre commit hook for formatting staged changes

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/test/internal/receiverInit.spec.ts
- sdk/servicebus/service-bus/test/renewLockSessions.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
- sdk/servicebus/service-bus/test/utils/testUtils.ts
A service-side change made it so setting the partition id and session id to different values an error in some cases where, before, it would have been incorrect but harmless.
This fixes our test data so we don't run afoul of that rule. I've filed an issue (#10326) to deal with two problems that came out as a result of this.
> [service-bus] Fix issue with live tests failing on session-based tests

- sdk/textanalytics/ai-text-analytics/package.json
- sdk/textanalytics/ai-text-analytics/test/apiKey.spec.ts
- sdk/textanalytics/ai-text-analytics/test/pipelineOptions.spec.ts
- sdk/textanalytics/ai-text-analytics/test/textAnalyticsClient.spec.ts
- sdk/textanalytics/ai-text-analytics/test/util.spec.ts
- sdk/textanalytics/ai-text-analytics/test/utils/resultHelper.ts
- Lints tests. Fixes #10170,
- Lints `package.json` but not `tsconfig.json` (see below). Partially fixes #10172. No changes needed in `api-extractor.json`.
- Updates `package.json` to drop the html report created by the `lint` script and adds the script to the `build` one. Fixes #10173.
`tsconfig.json` extends a base one in `../../../tsconfig` which satisfies the linter but it is not smart enough to look at that file instead. I suggest to update the linter to follow the extension chain or at least be optimistic and fail gracefully if there is an `extends`.
> [Text Analytics] Linting

- sdk/.prettierignore
It was reported that `prettier` produces valid YAML files for Azure Pipelines templates yet Azure DevOps could not process them. This PR is conservative and stops prettying all YAML files for now. I opened #10353.
> [Git Hook] Ignore YAML files

- sdk/cosmosdb/cosmos/src/queryExecutionContext/headerUtils.ts
We're currently checking if the partition key is a property of `headerQueryMetrics` but not if the value is valid so we have the potential of unhandled exceptions.
See https://github.com/Azure/azure-sdk-for-js/issues/10275 for more detail
> [Cosmos] Attempts to add correct undefined check for header merge

- .gitattributes
The new Prettier-based formatting commit hook is incompatible with Windows CRLF line endings so enforce Unix LF everywhere.
The .gitattributes prior to this change causes these conversions even if core.autocrlf is false. This configuration, in contrast, works irrespective of the global git configuration. It also prevents files from being committed with Windows line endings accidentally.
* Git 2.10 (release 2016-09-03) or later required
* Earlier versions of git will incorrectly apply eol=lf to binary files unless explicitly called out as binary in .gitattributes
* Existing working copies on Windows will not have their existing line endings corrected, and you will get `warning: CRLF will be replaced by LF in <file>` when you edit them.
* To convert all of the files in an existing working …
> Use UNIX LF line endings everywhere, even on Windows

- sdk/cognitiveservices/cognitiveservices-customvision-prediction/README.md
- sdk/cognitiveservices/cognitiveservices-customvision-prediction/package.json
- sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/predictionAPIClientContext.ts
Fix CustomVision Prediction Example to use ApiKeyCredentials
Related to #10362 , the prediction client example is using the wrong credentials
> Fix CustomVision Prediction Example to use ApiKeyCredentials

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/queryExecutionContext/SqlQuerySpec.ts
For the `QuerySpec JSONArray`, we're okay to accept any type of array and not force users to coerce types to a rigid `Array` type
See: https://github.com/Azure/azure-sdk-for-js/issues/10354
> Changes Array JSONArray type to ArrayLike

- sdk/keyvault/keyvault-keys/rollup.base.config.js
This PR fixes the rollup script to avoid the below warning
> [Keyvault] Fix warning on unresolved dependencies

- sdk/monitor/opentelemetry-exporter/README.md
Opentelemetry looks like newly migrated into our repo and doesn't have the samples/ examplesfolder yet. Let's avoid adding links to non-exisiting folders that happened as a result of this PR - https://github.com/Azure/azure-sdk-for-js/pull/10104 - cc: @markwolff @xirzec
> examples folder is not present and gives bad link

- sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
This test occasionally fails only on macOS.
Being investigated at #10053 
Skipping the test until the issue is fixed to unblock unrelated merge-able PRs.
> [Service Bus] Skip the flaky schedule test until we find the fix

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/defaultAzureCredential.browser.ts
- sdk/identity/identity/src/credentials/defaultAzureCredential.ts
- sdk/identity/identity/src/credentials/visualStudioCodeCredential.browser.ts
- sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
- sdk/identity/identity/src/index.ts
Renamed the VSCodeCredential to VisualStudioCodeCredential.
Fixes #10418
> [Identity] Renamed the VSCodeCredential to VisualStudioCodeCredential

- sdk/core/core-amqp/package.json
Fixes #9313 
I tested this by running the event hubs live tests (uses rollup) and the event hubs browser sample (uses webpack).
/cc @HarshaNalluru This can wait until after the impending core-amqp release to be merged, there's no rush.
> [core-amqp] remove stream-browserify dependency

- sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
Issue - https://github.com/Azure/azure-sdk-for-js/issues/10144
> [Service Bus] ATOM API: Retain the status code in the response from the service for MessageEntityNotFoundError

- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/core/messageSender.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
Creating of receivers and senders can fail due to OperationTimeoutError from `rhea-promise` which gives error messages like `Unable to create the amqp receiver 'queuename-a979a00f-0fae-3745-bb4a-3c9acabd6ead' on amqp session 'local-1_remote-1_connection-1' due to operation timeout.` See #9775
Creating of session receivers can pass, but fail to get lock on sessionId we want. The error message in this case can be improved as well. See #7618
This PR attempts to improve error messages in both these cases
> [Service Bus] Improve err msg when failing to senders and receivers

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
As reported in #10395, we have inconsistent errors being returned to the user when settling a deferred message in Receive And Delete mode.
There are 2 different root causes here
- When trying to settle, the client fails to identify that the message was received in ReceiveAndDelete mode
- The service sets a lock token on messages received in ReceiveAndDelete mode (which it should not) if the entity in question is partitioned.
The solution being proposed in this PR is
- The client sets the `lockToken` on the message to `undefined` if the message was received in ReceiveAndDelete mode.
- The absence of the `lockToken` is then taken to be the indicator of the ReceiveAndDelete mode when settling, and a consistent error is thrown
> [Service Bus] Better errors for settling deferred msg in ReceiveAndDelete mode

- sdk/cosmosdb/cosmos/src/queryIterator.ts
The query iterator should only go down the cross partition code path if its querying items. Other resources should re-throw the error returned by the backend. For example, upcoming features will throw when querying offers and the iterator was incorrectly going to fetch a query plan.
Again like I said in https://github.com/Azure/azure-sdk-for-js/pull/7333, QueryIterator probably needs to be split up. Items are a special case.
> Only fetch query plan for item queries

- sdk/textanalytics/ai-text-analytics/package.json
with https://github.com/Azure/azure-sdk-for-js/pull/10359 merged, the TA build started to fail.
(CC @jonathandturner )
> [ai-text-analytics] Lower-case azure keyword in package.json

- sdk/core/abort-controller/package.json
- sdk/core/core-amqp/package.json
- sdk/core/core-auth/package.json
- sdk/core/core-client/package.json
- sdk/core/core-http/package.json
- sdk/core/core-https/package.json
- sdk/core/core-tracing/package.json
- sdk/core/logger/package.json
- sdk/cosmosdb/cosmos/package.json
- sdk/identity/identity/package.json
- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-secrets/package.json
- sdk/schemaregistry/schema-registry/package.json
- sdk/schemaregistry/schema-registry/samples/javascript/README.md
- sdk/servicebus/service-bus/package.json
- sdk/storage/storage-blob-changefeed/package.json
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-queue/package.json
- sdk/tables/azure-tables/package.json
- sdk/template/template/package.json
- sdk/textanalytics/ai-text-analytics/package.json
The linter enforces the existence of certain keywords and for them to be lower case. This PR lower case all keywords in `package.json` files across packages that are not doing that already.
> Lower case keywords in package.json across packages

- sdk/core/core-auth/CHANGELOG.md
As we are not releasing core-auth for August cycle.
This reverts commit 3b19404a0976baa77832974cb53df71b8e97db83.
> Revert core auth changelog

- sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
- sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
- sdk/keyvault/keyvault-certificates/src/index.ts
- sdk/keyvault/keyvault-certificates/test/internal/serviceVersionParameter.spec.ts
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/src/keysModels.ts
- sdk/keyvault/keyvault-keys/test/internal/serviceVersionParameter.spec.ts
- sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
- sdk/keyvault/keyvault-secrets/src/index.ts
- sdk/keyvault/keyvault-secrets/src/secretsModels.ts
- sdk/keyvault/keyvault-secrets/test/internal/serviceVersionParameter.spec.ts
This PR is to align with other languages and packages on using `serviceVersion` instead of `apiVersion` to refer to the parameter that specifies the version of the service.
The `apiVersion` parameter has only been introduced in the preview version of the Key Vault packages, so I believe this should be fine.
Please let me know if I'm missing something.
> [Key Vault] apiVersion parameter to serviceVersion

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/defaultAzureCredential.ts
This PR is to align with .Net,
but this comes mainly from the feedback I got from Scott on the Identity README PR: https://github.com/Azure/azure-sdk-for-js/pull/10506/files#r467472978
Feedback appreciated 🌻
> [Identity] managedIdentityClientId optional parameter on the DAC options

- sdk/search/search-documents/src/serialization.ts
- sdk/search/search-documents/test/serialization.spec.ts
I've updated the regex to match the entire string, not just a part of the string, meaning that fields that contain ISO8601 dates within them aren't treated as dates themselves.
See #10486 for more info.
Edit:
With this patch, the output of the replication steps provided in #10486 are:
```
$ node .
true
{ id: '1', name: 'Example 2019-09-18T01:08:36.393Z' }
```
> [search-documents] Fix ISO8601 date regex

- sdk/servicebus/service-bus/src/clientEntityContext.ts
- sdk/servicebus/service-bus/src/connectionContext.ts
- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/core/messageSender.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/log.ts
- sdk/servicebus/service-bus/src/modelsToBeSharedWithEventHubs.ts
- sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/src/util/concurrentExpiringMap.ts
- sdk/servicebus/service-bus/src/util/crypto.ts
- sdk/servicebus/service-bus/src/util/errors.ts
- sdk/servicebus/service-bus/src/util/runtimeInfo.browser.ts
- sdk/servicebus/service-bus/src/util/semaphore.ts
- sdk/servicebus/service-bus/src/util/tracing.ts
- sdk/servicebus/service-bus/src/util/utils.ts
Many un-exported interfaces/functions/classes are ending up in the generated docs since they don't have the `@internal`/`@ignore` tags on them. This PR attempts to clean the ref docs by fixing the issue.
> [Service Bus] @internal @ignore tags for the methods/interfaces that aren't exported

- sdk/cosmosdb/cosmos/CHANGELOG.md
Looks like changelog dates now fail with single digits, e.g., 2020-8-10 should be 2020-08-10
> [Cosmos] fix dates in changelog to be 2 digits

- sdk/identity/identity/CHANGELOG.md
This adds a few top-level bullets for users coming from the 1.0 full release to the 1.1 release. This isn't meant to be exhaustive, but instead point out some of the improvements on the 1.0 experience as well as cases where behavior has changed from how 1.0 worked.
> [Identity] Add some additional changelog lines for 'since 1.0'

- sdk/storage/storage-file-share/README.md
Fix https://github.com/Azure/azure-sdk-for-js/issues/10249
Add a summary of examples
> Modify storage-file-share/README.md

- common/git-hooks/pre-commit
The hook is a shell script but was using bash features. This replaces the bash expression with a shell one.
> [Pre-commit hook] Fix the hook

- sdk/keyvault/keyvault-certificates/README.md
- sdk/keyvault/keyvault-keys/README.md
- sdk/keyvault/keyvault-secrets/README.md
Now that we've moved to service version 7.1, and since we moved from apiVersion to serviceVersion, we should have this updated too before we release.
> [Key Vault] Spotted a remaining reference to 7.1-preview and apiVersion on the READMEs

- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-certificates/rollup.base.config.js
- sdk/keyvault/keyvault-certificates/src/index.ts
- sdk/keyvault/keyvault-certificates/test/internal/userAgent.spec.ts
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-keys/rollup.base.config.js
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/test/internal/userAgent.spec.ts
- sdk/keyvault/keyvault-secrets/package.json
- sdk/keyvault/keyvault-secrets/rollup.base.config.js
- sdk/keyvault/keyvault-secrets/src/index.ts
- sdk/keyvault/keyvault-secrets/test/internal/userAgent.spec.ts
By loading the package.json in the test files, the dist-esm folder was including a copy of the package.json, breaking the whole folder (thus also source maps, etc).
> [Key Vault] Fixing bad dist-esm folders on the resulting artifacts

- sdk/sql/arm-sql/package.json
- sdk/sql/arm-sql/src/sqlManagementClientContext.ts
We were setting by default the accept header on `sendOperationRequest` however LRO operations call directly `sendRequest` which resulted in LRO poll to get XML responses.
Moving the accept header injection lower in the stack to `sendRequest` fixes the problem since `sendOperationRequest` also calls it.
Fixes #10350
/cc: @qiaozha
> [arm-sql] Add accept header on sendRequest

- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/test/internal/userAgent.spec.ts
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/test/internal/userAgent.spec.ts
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/test/internal/userAgent.spec.ts
When I tried to release these packages, the build failed with the following:
```
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/2e50d22d-8ff5-4439-b7fb-95f92dfe83e4.ps1'
Found the following change log entry for version '4.1.0' in [/home/vsts/work/1/s/sdk/keyvault/keyvault-secrets/CHANGELOG.md].
-----
-----
Confirm-ChangeLogEntry: /home/vsts/work/1/s/eng/common/scripts/Verify-ChangeLog.ps1:40
Line |
40 |  … ChangeLog = Confirm-ChangeLogEntry -ChangeLogLocation $PackageProp.pk …
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Entry has no content. Please ensure to provide some content of
| what changed in this version.
##[error]PowerShell exited with code '1'.
```
Here's my attempt to fix this.
Also, nightly builds were …
> [Key Vault] Build fixes

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- Accidentally removed this in the PR - https://github.com/Azure/azure-sdk-for-js/pull/9216
- May have caused this time's release docs to have invalid links
> add relative link conversion to git tags back

- sdk/test-utils/recorder/tsconfig.json
so that bundled storage browser tests can run on IE11
> [test,recorder] Change to target es5

- .github/CODEOWNERS
Set codeowners for [`sdk/monitor`](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/monitor)
/cc @xirzec
> monitor: add to codeowners

- sdk/tables/azure-tables/review/tables.api.md
- sdk/tables/azure-tables/src/TableClient.ts
- sdk/tables/azure-tables/src/TableServiceClient.ts
- sdk/tables/azure-tables/src/generatedModels.ts
- sdk/tables/azure-tables/src/index.ts
- sdk/tables/azure-tables/src/models.ts
- sdk/tables/azure-tables/src/odata.ts
- sdk/tables/azure-tables/test/odata.spec.ts
This PR adds:
* Better interface to set a select filter in queries. Select now takes an array of strings instead of a comma-separated string.
* odata helper that enables users to use interpolated strings in query filter. This helper also takes care of adding quotes when needed
> [Tables] Helper functions for Query options

- sdk/monitor/opentelemetry-exporter/src/export/exporter.ts
- sdk/monitor/opentelemetry-exporter/src/platform/nodejs/httpSender.ts
- sdk/monitor/opentelemetry-exporter/src/types.ts
- sdk/monitor/opentelemetry-exporter/test/platform/nodejs/httpSender.test.ts
Convert `httpSender.ts` to use async/await instead of callback pattern
> [Monitor] refactor httpSender.ts to use async/await

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/core/messageSender.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/linkentity.unittest.spec.ts
This PR is a follow up to the refactoring done in #10578 where the concept of closing "linkOnly" vs "permanently" was introduced on the `LinkEntity`. This PR covers the below
- Add a close() to the `LinkEntity` class that would denote the close "permanently" scenario. This is when we do not expect to re-use the `LinkEntity` instance
- Move the code to delete sender/receiver from cache into the above new method
> [Service Bus] Add LinkEntity.close()

- sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
- sdk/formrecognizer/ai-form-recognizer/README.md
- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/formrecognizer/ai-form-recognizer/src/constants.ts
- sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts
- version number is now 3.0.0
- updated CHANGELOG to reflect GA status
- minor changes to wording in README
- added a couple more links to service docs/samples for info on setting up data sets
> [ai-form-recognizer] Change version number for GA, minor README changes

- common/config/rush/pnpm-lock.yaml
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/README.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/src/util/constants.ts
Updating amqp-common to 1.0.0-preview.16 to get the fixes for:
* #10641 (management link timing out when sending parallel requests)
* #9287 (management client not properly clearing timer, causing app to hang on exit)
Fixes #10641
> [service-bus] Update to amqp-common 1.0.0-preview.16

- sdk/core/core-http/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-http/test/policies/bearerTokenAuthenticationPolicyTests.ts
- sdk/formrecognizer/ai-form-recognizer/recordings/node/aad_formrecognizerclient_nodejs_only/recording_recognizes_content_from_a_pdf_file_stream.js
- sdk/formrecognizer/ai-form-recognizer/recordings/node/aad_formrecognizerclient_nodejs_only/recording_recognizes_content_from_a_url.js
- sdk/formrecognizer/ai-form-recognizer/recordings/node/aad_formrecognizerclient_nodejs_only/recording_recognizes_receipt_from_a_url.js
PR https://github.com/Azure/azure-sdk-for-js/pull/10085 had a bug that prevented any caching from happening. The recordings in that PR should have helped us see the issue, but I didn't go through why we needed the recording changes. @HarshaNalluru had a similar issue with other recordings after this PR was merged, and from there we were able to spot the bug.
I'm really glad this wasn't released 😁
~The recording changes of this PR undo the recording changes in: https://github.com/Azure/azure-sdk-for-js/pull/10085/files 
I did so by checking out these files to the commit hash present on master before this PR was merged. The commit hash being: e76133f41d075451bc29bdac32027120ebc1de0b~ I couldn't use the older recordings because form recognizer was recently updated.
We also spotted that now …
> [core-http] The previous core-http change had a bug

- sdk/formrecognizer/ai-form-recognizer/README.md
- sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
These are the last changes to docs that I'm making before GA, closing the final docs issues in this milestone for FR.
- documented requirement to do URL-encoding of paramters given to FromUrl method variants
- Added some blurbs to readme about the function of the samples, reordered the sections to be like Python's README
- documented where to find `resourceId` and `resourceRegion` in Azure portal
- Fixed a sample in the README not having `fs` imported
- Added a pointer to the snippets from the key concepts section
closes #9641 
closes #8942
> [ai-form-recognizer] Final docs changes pre-GA

- sdk/servicebus/service-bus/samples-v1/javascript/README.md
- sdk/servicebus/service-bus/samples-v1/javascript/advanced/sessionState.js
- sdk/servicebus/service-bus/samples-v1/javascript/package.json
- sdk/servicebus/service-bus/samples-v1/javascript/servicePrincipalLogin.js
- sdk/servicebus/service-bus/samples-v1/typescript/README.md
- sdk/servicebus/service-bus/samples-v1/typescript/package.json
- sdk/servicebus/service-bus/samples-v1/typescript/src/advanced/sessionState.ts
- sdk/servicebus/service-bus/samples-v1/typescript/src/servicePrincipalLogin.ts
- sdk/servicebus/service-bus/samples-v1/typescript/src/useProxy.ts
- sdk/servicebus/service-bus/samples-v1/typescript/tsconfig.json
- sdk/servicebus/service-bus/samples/javascript/usingAadAuth.js
- sdk/servicebus/service-bus/samples/typescript/src/usingAadAuth.ts
There were several breakages:
- The track 1 samples weren't compiling properly (several issues) and the proxy sample was broken even after fixing compile errors
- We'd swapped the token and client id fields in the AAD samples in both track 1 and track 2.
- The sessionState samples were using a variable that didn't exist (looks like a partial rename that didn't get propagated)
Fixes #10733
> [service-bus] Fixing service bus samples for track 1 and track 2

- sdk/formrecognizer/ai-form-recognizer/README.md
- sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
The contentType parameter was moved to `BeginRecognizeReceiptsOptions` 
Resolves: #10742
The second mentioned issue in #10742 (about `doc.documentName` -> `doc.name`) is already solved in PR #10685.
> Fix readme for form recognizer

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/recordings/node/blobserviceclient/recording_verify_custom_endpoint_without_valid_accountname.js
- sdk/storage/storage-blob/src/Clients.ts
- sdk/storage/storage-blob/src/utils/utils.common.ts
- sdk/storage/storage-blob/test/blobclient.spec.ts
- sdk/storage/storage-blob/test/blobserviceclient.spec.ts
- sdk/storage/storage-blob/test/containerclient.spec.ts
- sdk/storage/storage-blob/test/utils.spec.ts
- sdk/storage/storage-file-datalake/src/utils/utils.common.ts
- sdk/storage/storage-file-datalake/test/utils.spec.ts
- sdk/storage/storage-file-share/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_custom_domain.json
- sdk/storage/storage-file-share/recordings/browsers/utility_helpers/recording_isipendpointstyle.json
- sdk/storage/storage-file-share/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_custom_domain.js
- sdk/storage/storage-file-share/recordings/node/utility_helpers/recording_isipendpointstyle.js
- sdk/storage/storage-file-share/src/utils/utils.common.ts
- sdk/storage/storage-file-share/test/directoryclient.spec.ts
- sdk/storage/storage-file-share/test/fileclient.spec.ts
- sdk/storage/storage-file-share/test/shareclient.spec.ts
- sdk/storage/storage-file-share/test/utils.spec.ts
- sdk/storage/storage-queue/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_custom_domain.json
- sdk/storage/storage-queue/recordings/browsers/utility_helpers/recording_isipendpointstyle.json
- sdk/storage/storage-queue/recordings/node/queueserviceclient/recording_verify_custom_endpoint_without_valid_accountname.js
- sdk/storage/storage-queue/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_custom_domain.js
- sdk/storage/storage-queue/recordings/node/utility_helpers/recording_isipendpointstyle.js
- sdk/storage/storage-queue/src/QueueClient.ts
- sdk/storage/storage-queue/src/utils/utils.common.ts
- sdk/storage/storage-queue/test/queueclient.spec.ts
- sdk/storage/storage-queue/test/queueserviceclient.spec.ts
- sdk/storage/storage-queue/test/utils.spec.ts
Support custom domain which targets to solve #9896 and #10520 .
> [Storage] Custom domain support.

- sdk/cosmosdb/cosmos/src/client/Container/Containers.ts
Fixing typos of `contaienrs` to `containers`
> Quick Fix: Typos

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/client/Item/Items.ts
- sdk/cosmosdb/cosmos/src/index.ts
- sdk/cosmosdb/cosmos/src/queryIterator.ts
- sdk/cosmosdb/cosmos/src/utils/batch.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/murmurHash.ts
- sdk/cosmosdb/cosmos/test/functional/client.spec.ts
- sdk/cosmosdb/cosmos/test/functional/database.spec.ts
- sdk/cosmosdb/cosmos/test/functional/item.spec.ts
- sdk/cosmosdb/cosmos/test/unit/hashing/v1.spec.ts
- sdk/cosmosdb/cosmos/test/unit/hashing/v2.spec.ts
Closes #10721 by adding a BulkOperationType usable when building an operation list to use when invoking `items.bulk`
Closing #10706 for the functional pieces, but still need to supplement bulk with docs detailing that errors will not necessarily be raised and may instead be contained in the response array of operation results.
> [Cosmos] Adds BulkOperationType enum and autogens ID for create ops

- sdk/servicebus/service-bus/src/log.ts
Found this while testing out docs for #10491
> [Service Bus] Add @ignore tag for a const that showed up in the docs generated with typedoc

- sdk/cosmosdb/cosmos/test/functional/item.spec.ts
This was leftover cleanup from the Bulk PR. Bulk tests create expensive containers so we want to make sure to delete those databases when the tests are done.
> [Cosmos] Delete databases after bulk tests

- sdk/monitor/ci.yml
- sdk/monitor/opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/opentelemetry-exporter/package.json
Monitor opentelemetry-exporter package is missing:
- Changelog
- sdk-type in package.json
- ESlint error is not skipped (Separate issue to file for ESlint errors)
- pack command is missing
> Fix monitor ci failures

- sdk/identity/identity/package.json
Linting has non trivial overhead and can substantially increase the runtime for `rush build` for no good reason, so we are taking it off from the `build` script and will rely on CI lint step in analyze to fail in case of linting errors.
@sadasant ^
> [Identity] Remove linting from build

- sdk/textanalytics/ai-text-analytics/package.json
Linting has non trivial overhead and can substantially increase the runtime for `rush build` for no good reason, so we are taking it off from the `build` script and will rely on CI lint step in analyze to fail in case of linting errors.
> [Text Analytics] Remove linting from build

- sdk/formrecognizer/ai-form-recognizer/package.json
Linting has non trivial overhead and can substantially increase the runtime for `rush build` for no good reason, so we are taking it off from the `build` script and will rely on CI lint step in analyze to fail in case of linting errors.
> [Form Recognizer] Remove linting from build

- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-secrets/package.json
Linting has non trivial overhead and can substantially increase the runtime for `rush build` for no good reason, so we are taking it off from the `build` script and will rely on CI lint step in analyze to fail in case of linting errors.
> [Key Vault] Remove linting from build

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/index.ts
- sdk/cosmosdb/cosmos/src/utils/batch.ts
- sdk/cosmosdb/cosmos/test/functional/item.spec.ts
Addresses a customer reported issue that a `deleteOperation` wasn't working or reporting an error. We fixed the issue around errors not being reported in a previous PR but they were still able to pass an object with invalid keys, `delete` requires `id` but the type accepted `resourceBody`. This makes the operatoin input more rigid again.
> [Cosmos] Adds single partition delete spec and makes OperationInput more rigid

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
We have learnt from the service team that requiresPreprocessing and compatibilityLevel are not properties they expect to be set on rules by the user. This PR cleans them up
> [Service Bus] Remove requiresPreprocessing, compatibilityLevel

- sdk/anomalydetector/ai-anomaly-detector/api-extractor.json
- sdk/anomalydetector/ai-anomaly-detector/package.json
- sdk/anomalydetector/ai-anomaly-detector/samples/javascript/package.json
- sdk/anomalydetector/ai-anomaly-detector/samples/typescript/package.json
- sdk/anomalydetector/ai-anomaly-detector/src/AnomalyDetectorClient.ts
- sdk/anomalydetector/ai-anomaly-detector/test/anomalydetector.spec.ts
- sdk/anomalydetector/ai-anomaly-detector/test/testData.ts
Types file was generated with an incorrect name `template.d.ts` so it was not included in the package. Renaming it to `ai-anomaly-detector.d.ts` will match the entry in package.files and will include it in the package.
Also: 
* Fixing some leftover `template` strings in the samples package
* Enable linter when building
* Fix linting errors
> [Anomaly Detector] Fix missing types in package

- sdk/template/template/package.json
Make lint script actually fail if there were any Lint errors. This will allow Analyze to fail in CI with any lint errors.
Also fixing a couple of lint errors in this project
> [Template] Allow CI Analyze when there are lint errors

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/test/utils/testUtils.ts
As part of the investigation at https://github.com/Azure/azure-sdk-for-js/issues/9850#issuecomment-670773548, it seems "number", "boolean", "string", and Date are the only types allowed for values in the properties on the message.
> [Service Bus] Values for props on the message only supports some types

- sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
Fixes #10922
Throws if the TenantID is `adfs` both as an input parameter, or after reading the VSCode configuration.
> [Identity] Sovereign Clouds don't support the VSCode credential

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/samples/javascript/advanced/processMessageFromDLQ.js
- sdk/servicebus/service-bus/samples/typescript/src/advanced/processMessageFromDLQ.ts
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/serviceBusClient.ts
- sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/invalidParameters.spec.ts
- sdk/servicebus/service-bus/test/propsToModify.spec.ts
- sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/utils/testutils2.ts
This PR shows an alternative to having a dedicated method to create dead letter receivers. 
As explained in https://docs.microsoft.com/azure/service-bus-messaging/service-bus-dead-letter-queues, we have another kind of dead letter queue called the "transfer dead letter queue". 
This PR introduces the concept of "sub queues" as described in Proposal 3 in https://gist.github.com/richardpark-msft/628f65c667dd44c5b748523655fe49fa
Other unrelated changes in this PR:
- Tweaked the error message for invalid receiveMode to list out valid values to match the pattern used for invalid subQueue
- Removed the try/catch `extractReceiverArguments` as I could not see a need for it. The only potential error from this method is the one for invalid receiveMode which should bubble up as is.
> [Service Bus] Use subQueue for deadLetterReceiver

- sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
This PR replaces reference to http status codes information in https://docs.microsoft.com/dotnet/api/system.net.httpstatuscode?view=netframework-4.8 with a generic statement on REST API errors. 
This is a follow up from the discussion in https://github.com/Azure/azure-sdk-for-js/pull/10646#discussion_r471147023
I don't feel strongly about this either way, but if we were to remove this link then the change in this PR is what I would recommend
> [Service Bus] Avoid using dotnet links for status codes

- sdk/eventhub/event-hubs/README.md
Based on the code at https://github.com/Azure/azure-sdk-for-js/blob/%40azure/event-hubs_5.2.2/sdk/eventhub/event-hubs/src/partitionPump.ts#L117-L124, it is clear that the user provided `processClose()` is only called if the error encountered is not retryable. This PR clarifies this point in the readme
> [Event Hubs] Note that on retryable errors, processClose will not be called

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/tools/versioning/set-dev.js
- sdk/template/template/CHANGELOG.md
- sdk/template/template/package.json
- Use alpha instead of dev
- Use beta instead of preview
Updating versioning logic to match guideline update in Azure/azure-sdk#1536.
PTAL @ramya-rao-a @xirzec @praveenkuttappan
> Change prerelease versioning

- sdk/keyvault/keyvault-admin/src/generated/keyVaultClient.ts
- sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
- sdk/keyvault/keyvault-admin/swagger/README.md
The generated backup LROs are incompatible with the expected API. We'll be working to improve that next month.
For: https://github.com/Azure/azure-sdk-for-js/issues/10799
> [Key Vault Admin] No LROs on the generated code for now

- sdk/core/core-http/src/url.ts
- sdk/core/core-http/test/urlTests.ts
The '=' character is valid in query parameter values. There are
scenarios where a query parameter value is base64 encoded (e.g., a
continuation token that is opaque to users) and '=' is very common in
base64 encoded strings. Currently we treat query parameter values
containing '=' as invalid and any parameter name/value pair with '='
in value is ignored thus we lose those key-value pairs after parsing
URLs.
I have verified that both NodeJS and browsers' URL types allow '=' in
their `searchParameter` values.
This change remove the invalidation of this case in `URLQuery.parse()`
so that our parsing behavior is consistent with NodeJS and browsers'
URL types.
Fixes #11014
> [core-http] Treat '=' in query parameter values as valid

- sdk/tables/data-tables/CHANGELOG.md
- sdk/tables/data-tables/package.json
We have decided to use `beta` instead of `preview` going forward. (ref: https://github.com/Azure/azure-sdk/blob/d8c70b795c0c364d29d3c66bfb0e9d3ce163acef/docs/policies/releases.md#package-versioning)
I think since we have not released any previous previews of this package, we can adopt the new term now, which looks like what is being done for some other new packages we are releasing this sprint.
> [Tables] Change prerelease tag

- sdk/tables/data-tables/review/data-tables.api.md
- sdk/tables/data-tables/src/TableClient.ts
- sdk/tables/data-tables/src/models.ts
- sdk/tables/data-tables/src/serialization.ts
- sdk/tables/data-tables/test/unit/serialization.spec.ts
Serializartion didn't play nice when trying to send entities with `null` or `undefined` properties.
This PR includes: 
- Fix so that serialization works with null and undefined properties.
- Adda missing `queryOptions` property for the `listTables` operation
- Remove ifMatch for upsert operation
> [Tables] Tables serialization fixes

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/serviceBusClient.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/test/auth.spec.ts
- sdk/servicebus/service-bus/test/backupMessageSettlement.spec.ts
- sdk/servicebus/service-bus/test/batchReceiver.spec.ts
- sdk/servicebus/service-bus/test/deferredMessage.spec.ts
- sdk/servicebus/service-bus/test/internal/receiver.spec.ts
- sdk/servicebus/service-bus/test/invalidParameters.spec.ts
- sdk/servicebus/service-bus/test/managementClient.spec.ts
- sdk/servicebus/service-bus/test/propsToModify.spec.ts
- sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
- sdk/servicebus/service-bus/test/renewLock.spec.ts
- sdk/servicebus/service-bus/test/renewLockSessions.spec.ts
- sdk/servicebus/service-bus/test/retries.spec.ts
- sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
- sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/sessionsRequiredCleanEntityTests.spec.ts
- sdk/servicebus/service-bus/test/sessionsTests.spec.ts
- sdk/servicebus/service-bus/test/smoketest.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
- sdk/servicebus/service-bus/test/utils/misc.ts
- sdk/servicebus/service-bus/test/utils/testUtils.ts
- sdk/servicebus/service-bus/test/utils/testutils2.ts
Based on the suggestion in https://github.com/Azure/azure-sdk-for-js/issues/10802#issuecomment-683996165, this PR adds the `ServiceBus` prefix to the `ReceivedMessage` and `ReceivedMessageWithLock` interfaces.
This does make the names way too long, so we can use this opportunity to discuss how we want to move forward
> [Service Bus] Add ServiceBus prefix to ReceivedMessage

- sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
- sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
This PR adds example code in jsdocs for the key methods in the producer and consumer client
Related to #4868
> [Event Hubs] Add examples in jsdocs

- sdk/template/template/CHANGELOG.md
- sdk/template/template/package.json
Kick off the pipeline of template to test the release tag default setting. All passed, but release tag 1.0.9-beta.2 has been used. Bump to a new one to 1.0.9-beta.3.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=525026&view=results
> Bump the template version for JS

- sdk/servicebus/service-bus/README.md
- sdk/servicebus/service-bus/samples-v1/README.md
- sdk/servicebus/service-bus/samples/README.md
> [Service Bus] Browser bundling

- .prettierignore
- common/autoinstallers/rush-prettier/package.json
- common/autoinstallers/rush-prettier/pnpm-lock.yaml
- common/config/rush/command-line.json
- common/config/rush/common-versions.json
- common/git-hooks/pre-commit
In this PR:
- I follow the more recent guidance from the rush team on how to write a precommit hook: https://rushjs.io/pages/maintainer/enabling_prettier/. Fixes #11076.
- The `prettier` wrapper is switched from [`precise-commits`](https://www.npmjs.com/package/precise-commits) to [`pretty-quick`](https://www.npmjs.com/package/pretty-quick). The main difference between the two is that the latter works on whole files instead of changed regions only, so no more bizarre formattings. Furthermore, `.prettierignore` is picked up correctly and is used to filter out staged files that we do not want to run `prettier` on. Fixes https://github.com/Azure/azure-sdk-for-js/issues/10770 and fixes https://github.com/Azure/azure-sdk-for-js/issues/11077.
Epic: #11105.
> Improve the precommit hook

- sdk/servicebus/service-bus/src/core/managementClient.ts
The listeners for sender_error, receiver_error were added when the management link is initialized.
`managementClient._init` is being called for each of the management requests irrespective of the link being active/inactive.
As a result, listeners are being added for each request without cleaning up the older ones and hence blowing up the max limit (10).
The fix in this PR is to call the _init only if the link is not open. This prevents from adding too many listeners.
(This I feel is the missing part from the refactoring at https://github.com/Azure/azure-sdk-for-js/pull/10807)
> [Service Bus] Fix MaxListenersExceededWarning by avoiding adding too many listeners

- sdk/core/amqp-common/src/requestResponseLink.ts
Recently came across this issue (#10943) where our code is accessing .address and causing a TypeError.
Looking through the rhea it appears the only way this can fail is if `.source` is undefined, which only appears to happen if `.attach()` hasn't been called for the link. This is a really narrow window of time - this means the receiver has been created but we haven't been through the normal negotiation and initialization that would happen with the link.
There is more investigation to do here, however, because all of this code is guarded, in our code, by checking to see if the link is open, which should have insulated us from these issues.
> [amqp-common] Using .address field can result in a TypeError

- sdk/servicebus/service-bus/README.md
Updating the migration guide to preview.6 version(hardcoded the commit) to be released.
> [Service Bus] Migration guide link to point preview-6

- eng/pipelines/templates/stages/archetype-js-release.yml
This is a follow up step of master link replacement work.
Tested in template: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=530882&view=logs&j=ef505d45-100b-5890-ec9f-7c3786c71051&t=8bcf9df7-7eb7-51ec-7060-817ed374a684
Retrieved release tag successfully:
> Enable master link replacement feature for js

- eng/pipelines/templates/stages/archetype-js-release.yml
Added feature of enable/disable DocMs step per artifact level.
Issue:https://github.com/Azure/azure-sdk-tools/issues/922
> Allow skip publish DocMS or Github IO for each artifact

- sdk/eventgrid/eventgrid/tests.yml
Removed reference to azure-sdk-build-tools and azure-sdk-tools repos. 
@ellismg  Is there any specific reason to reference these tools repo for eventgrid tests?
> Aggregate report generation is failing due to ref to tools repo

- common/tools/eslint-plugin-azure-sdk/.eslintrc.json
Recent updates to the file [ts-versioning-semver.ts](https://github.com/Azure/azure-sdk-for-js/blob/071ce6890278feae206adf75e80a34fdbf636c12/common/tools/eslint-plugin-azure-sdk/src/rules/ts-versioning-semver.ts) file makes use of regular expressions. The particular usage causes the file to fail the [no-magic-numbers](https://eslint.org/docs/rules/no-magic-numbers) linting rule .
This PR updates the linter rule to ignore the array index as this is a normal use of String.match() outputs
> Fix linting errors in the eslint plugin

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/abortSignal.spec.ts
Check the abort signal in sessionReceiver.subscribe().
Fixes #4375
(finally)
> [service-bus] Check abortSignal in SessionReceiver.subscribe()

- sdk/monitor/monitor-opentelemetry-exporter/test/common/assert.ts
Remove unnecessary returns that are blocking some of the build machines.
> [Monitor] remove unnecessary returns

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/constructorHelpers.ts
- sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
Fixes #11223 and https://github.com/Azure/azure-sdk-for-js/issues/10710
Websocket info is not being passed in the token-credential-path resulting in an incomplete connection config, this PR updates the code related to the generating connection context with expected websocket info in the config similar to the connection-string-path.
With this, methods on the SBClient should work fine in the browser when used AAD for auth.
> [Service Bus] Bug Fix: Incorrect connection-config in the token credential path

- sdk/anomalydetector/ai-anomaly-detector/CHANGELOG.md
- sdk/anomalydetector/ai-anomaly-detector/README.md
- sdk/anomalydetector/ai-anomaly-detector/package.json
- sdk/anomalydetector/ai-anomaly-detector/src/generated/generatedClientContext.ts
> [AnomalyDetector] Update AnomalyDetector README

- sdk/anomalydetector/ai-anomaly-detector/CHANGELOG.md
- sdk/anomalydetector/ai-anomaly-detector/README.md
Adding sample snippet to README.md
> [Anomaly Detector] Add sample snippet to README

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/src/serializer.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-client/test/testMappers.ts
- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/serializer.ts
- sdk/core/core-http/src/serviceClient.ts
- sdk/core/core-http/src/util/utils.ts
- sdk/core/core-http/test/serviceClientTests.ts
- sdk/core/core-http/test/testMappers.ts
OpenAPI supports xml namespace and prefixes ([link](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-22)). However `core-http` serializer doesn't honor them.
[ServiceBus swagger](https://github.com/Azure/azure-rest-api-specs/tree/sb_dataplane_namespace/specification/servicebus/data-plane), for example, uses XML namespaces.
Here are some samples on the expected output given a mapper:
```javascript
const stringMapper = {
serializedName: "testNode",
xmlNamespace: "https://microsoft.com",
type: {
name: MapperType.String
}
}
```
**Current**
```xml
<?xml version="1.0" encoding="UTF-8" ?><testNode>body value</testNode>
```
**Expected**
```xml
<?xml version="1.0" encoding="UTF-8" ?><testNode xmlns="https://microsoft.com">body value</testNode>
``` …
> [Core-http] Support xml namespaces

- sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
As part of investigating #11316 we found it was non-obvious that we would be using the checkpoint store when closing. 
The reason we use it is when we close the subscription we also mark, in the checkpoint store, that the partitions are abandoned. This lets other consumers more quickly pick up abandoned partitions rather than forcing them to wait for an expiration interval and discover it.
Fixes #11316
> [event-hubs] Update doc for subscription.close() to mention checkpoint store updating.

- sdk/search/search-documents/src/odata.ts
- sdk/search/search-documents/test/odata.spec.ts
For the October release, one of the tasks was to  add odata expression helpers and keep in sync with .NET. When I started testing it, I found we are already doing almost everything that .NET does. I added the code related to null and added all the testcases from .NET [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/tests/Serialization/SearchFilterTests.cs)
> Add testcases for handling odata

- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/deviceCodeCredential.ts
If I'm reading .Net's PR correctly: https://github.com/Azure/azure-sdk-for-net/pull/15266
This PR should be about providing a default way to low the user code through the DeviceCodeCredential.
If so, then this is exactly the solution.
I could be missing something! Feedback appreciated.
If reviewed, approved and merged,
Fixes #10229
> [Identity] Idea for the Device Code Credential Use Console Feature

- common/tools/eslint-plugin-azure-sdk/src/utils/metadata.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/9888.
> [Eslint Plugin] Fix docs link in suggestions

- sdk/storage/storage-blob-changefeed/package.json
Smoke test is not working for storage-blob-changefeed. Disabling smoke test for this package temporarily until issue is resolved.
> Disable smoke test for storage-blob-changefeed

- sdk/servicebus/service-bus/package.json
Resolves #9283
Based on the investigation in #10425, we know that Event Hubs does not need `stream-browserify`.
The same can be extended to Service Bus as the two have same set of dependencies apart from the ServiceBusAdministrationClient needing `@azure/core-http`.
So, removing this dependency from Service Bus.
> [Service Bus] Remove stream-browserify dependency

- sdk/servicebus/service-bus/samples/javascript/receiveMessagesLoop.js
Error spotted in sample where we're using the old setting (maxWaitTimeInSeconds) rather than maxWaitTimeInMs. 
Spotted by @lilyjma.
> [service-bus] Fixing broken option - we renamed maxWaitTimeInSeconds to maxWaitTimeInMs

- sdk/communication/communication-administration/sample.env
- sdk/communication/test-resources.json
Cleans up and fixes config to create a Communication test resource for live test
> Communication: fix test-resources config

- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/pipelineOptions.ts
- sdk/core/core-http/src/policies/ndJsonPolicy.ts
- sdk/core/core-http/src/serviceClient.ts
- sdk/core/core-http/test/policies/ndJsonPolicyTests.ts
- sdk/core/core-https/review/core-https.api.md
- sdk/core/core-https/src/index.ts
- sdk/core/core-https/src/pipeline.ts
- sdk/core/core-https/src/policies/ndJsonPolicy.ts
- sdk/core/core-https/test/ndJsonPolicy.spec.ts
A common format for streaming endpoints is [NDJSON ](http://ndjson.org/) since it avoids having to parse an incomplete outer array. Even though we don't support streaming (yet), Monitor would like to be able to send payloads as NDJSON.
This change adds a new pipeline option that reformats payloads from JSON array literals into NDJSON. It's not as efficient as it could be, since ServiceClient always wants to serialize the body before the pipeline is invoked. This seems like something we could address as part of #8617 with the goal is moving serialization **into** the pipeline, instead of being part of `sendOperationRequest`.
Fixes #11150
> [core-http] Add NDJSON support

- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/generated/models/index.ts
- sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
- sdk/eventgrid/eventgrid/src/index.ts
- sdk/eventgrid/eventgrid/src/predicates.ts
- sdk/eventgrid/eventgrid/src/systemEventDecoders.ts
- sdk/eventgrid/eventgrid/swagger/README.md
This change adds typings for the new events sent by the Azure
Communication Services
> [EventGrid] Add Azure Communication Service Events

- sdk/cosmosdb/cosmos/src/utils/batch.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/encoding/number.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/encoding/prefix.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/encoding/string.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/v1.ts
- sdk/cosmosdb/cosmos/src/utils/hashing/v2.ts
- sdk/cosmosdb/cosmos/src/utils/offers.ts
- sdk/cosmosdb/cosmos/test/unit/hashing/v1.spec.ts
- sdk/cosmosdb/cosmos/test/unit/hashing/v2.spec.ts
This PR adds the missing copyright headers in the source files in the cosmos package with an intention to reduce noise for when #10776 is picked up
> [Cosmos] Adding missing copyright headers

- sdk/identity/identity/package.json
Testing now cleans the previously built files first. Similar to what we do in other packages: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-keys/package.json#L63-L65
> [Identity] Testing now cleans

- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
- sdk/schemaregistry/schema-registry/package.json
This PR has changes from running the lint:fix script on the Schema Registry packages with hopes of reducing the noise when someone wants to work on #10779
This also removes tsconfig.json from being linted as per reasons in #10361
> [Schema Registry] Stop linting tsconfig, run lint:fix

- sdk/formrecognizer/ai-form-recognizer/package.json
There are no linting errors in the Form Recognizer package. Therefore, it does not need the exit 0 anymore. Future linting errors are expected to break the build
> [Form Recognizer] lint script does not need exit 0

- sdk/eventgrid/eventgrid/CHANGELOG.md
We are doing an off-cycle release today to ship the definitions of the system events for Azure Communication Services.
> [EventGrid] Prepare for 3.0.0-beta.2 release

- sdk/core/ci.yml
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-https/CHANGELOG.md
- sdk/core/core-https/package.json
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/core-xml/package.json
This will allow us to test nightlies of these packages against Autorest.TypeScript.
> [core] Mark core 2.0 packages as publishable

- sdk/search/search-documents/package.json
- sdk/search/search-documents/src/searchClient.ts
- sdk/search/search-documents/test/odata.spec.ts
- sdk/search/search-documents/test/utils/setup.ts
- sdk/search/search-documents/test/utils/setupIndex.ts
This PR has changes from running the `lint:fix` script on the Search package with hopes of reducing the noise when someone wants to work on #10780
> [Search] Run lint:fix script

- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
- sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
- sdk/keyvault/keyvault-keys/src/generated/models/index.ts
- sdk/keyvault/keyvault-keys/src/generated/models/mappers.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/swagger/README.md
- sdk/keyvault/keyvault-keys/test/public/crypto.spec.ts
This PR only adds the new algorithms from v7.2.
I'll add the tests as part of another PR. I'll keep track of that through this issue: https://github.com/Azure/azure-sdk-for-js/issues/11396
Closes: https://github.com/Azure/azure-sdk-for-js/issues/11260
> [Key Vault Keys] Add new algorithms

- sdk/core/core-client/src/serializer.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-client/test/testMappers.ts
- sdk/core/core-http/src/serializer.ts
- sdk/core/core-http/test/serviceClientTests.ts
- sdk/core/core-http/test/testMappers.ts
When serializing object using mappers with references to other mappers, core-http doesn't look at the referenced mapper for `additionalProperties` it only looks for it in the source mapper.
Sample of a referenced mapper:
```typescript
export const MonitorBase: CompositeMapper = {
type: {
name: "Composite",
className: "MonitorBase",
modelProperties: {
baseType: {
serializedName: "baseType",
type: {
name: "String"
}
},
baseData: {
serializedName: "baseData",
type: {
name: "Composite",
className: "MonitorDomain" // this is a reference to MonitorDomainMapper
}
}
}
}
};
export const MonitorDomain: CompositeMapper = {
type: {
name: "Composite",
className: "MonitorDomain",
additionalProperties: { type: { name: "Object" } },
modelProperties: {
test: {
serializedName: "test",
type: {
name: …
```
> [core-http] Find additionalProperties in referenced mapper

- common/tools/eslint-plugin-azure-sdk/docs/rules/ts-naming-options.md
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-naming-options.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-naming-options.ts
Currently `ts-naming-options` expects the type of the options parameter to the constructor of a client class to be named `ConstructorOptions`, but I think a more reasonable behavior would be to expect `<class name>Options` instead and this PR implements this. Suggestions for alternative behaviors are welcome!
> [Eslint Plugin] Update ts-naming-options rule to expect a more reasonable name for constructor options

- sdk/core/logger/api-extractor.json
- sdk/core/logger/package.json
- sdk/core/logger/review/logger.api.md
- sdk/core/logger/rollup.base.config.js
- sdk/core/logger/src/debug.ts
- sdk/core/logger/src/index.ts
- sdk/core/logger/src/log.browser.ts
- sdk/core/logger/src/log.ts
- sdk/core/logger/test/debug.spec.ts
- sdk/core/logger/test/logger.spec.ts
Switching the eslint configuration file used for `logging` to use the newer one in the root of the repository and fixing all the linting problems. Furthermore, enforce the absence of linting errors in CI.
> [Logger] Cleaning up and fixing linting

- sdk/cosmosdb/cosmos/.eslintrc.json
We are planning on removing `.eslintrc.old.json` file and this PR removes its use in `cosmos` package. See https://github.com/Azure/azure-sdk-for-js/issues/11256.
> [Cosmos] Does not use .eslintrc.old.json

- sdk/test-utils/perfstress/.eslintrc.json
- sdk/test-utils/perfstress/package.json
- sdk/test-utils/recorder/package.json
Switching the eslint configuration file to use the newer one in the root of the repository. See https://github.com/Azure/azure-sdk-for-js/issues/11256.
> [Test Utils] Use our ESLint plugin

- sdk/eventgrid/eventgrid/README.md
Update the link to include the "next" tag in the URL, so we link to a
page for the beta package instead of the released one.
When 3.0.0 goes GA, we'll change this back to the root of the package on
NPM.
> [EventGrid] Update npm link in README.md

- sdk/tables/data-tables/src/TableClient.ts
- sdk/tables/data-tables/src/TableServiceClient.ts
Now that https://github.com/Azure/azure-sdk-for-js/pull/11403 has been merged, we can get rid of a few ignoring comments of `ts-naming-options` linting rule.
> [Tables] Remove some of the ignoring comments of ts-naming-options

- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/policies/proxyPolicy.ts
- sdk/core/core-http/src/util/constants.ts
- sdk/core/core-http/src/util/utils.ts
- sdk/core/core-http/test/policies/proxyPolicyTests.node.ts
Add the NO_PROXY and ALL_PROXY to constants, and update the proxyPolicy to support env vars for NO_PROXY and ALL_PROXY Azure/azure-sdk-for-java#5967
> Update the proxyPolicy and constants

- sdk/storage/test-resources-post.ps1
Updated post deployment pwsh script to create SAS with new permissions that are not supported by SRP deployment now.
> Added post deployment step to create SAS with additional permission

- sdk/eventgrid/eventgrid/samples/javascript/src/sendCloudEvent.js
- sdk/eventgrid/eventgrid/samples/typescript/src/sendCloudEvent.ts
The samples were duplicates of the ones which sent events using the
event grid schema. Update them to call the correct API as well as the
shape of the event we send (so that the event actually matches the Cloud
Event schema)
Fixes: #11497
> [EventGrid] Fix Cloud Event samples

- sdk/storage/storage-blob/samples/javascript/iterators-blobs.js
- sdk/storage/storage-blob/samples/javascript/iterators-containers.js
Response returns "continuationToken" as opposed to "nextMarker"
> Fixed iterator marker key in JavaScript sample

- sdk/search/search-documents/review/search-documents.api.md
- sdk/search/search-documents/src/generated/data/models/index.ts
- sdk/search/search-documents/src/generated/data/models/mappers.ts
- sdk/search/search-documents/src/generated/data/models/parameters.ts
- sdk/search/search-documents/src/generated/data/operations/documents.ts
- sdk/search/search-documents/src/generated/service/models/index.ts
- sdk/search/search-documents/src/generated/service/models/indexersMappers.ts
- sdk/search/search-documents/src/generated/service/models/mappers.ts
- sdk/search/search-documents/src/index.ts
- sdk/search/search-documents/src/indexModels.ts
The Swaggers for search documents have been updated. I have regenerated Search Documents SDK based on the swagger. For Data.md regeneration, there was minimal amount of custom code to be added. For Service.md, no custom code addition is required. 
> Regeneration of search-documents SDK

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
- sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
- sdk/textanalytics/ai-text-analytics/swagger/README.md
- sdk/textanalytics/ai-text-analytics/test/collections.spec.ts
- sdk/textanalytics/ai-text-analytics/test/textAnalyticsClient.spec.ts
The feature crew agreed on removing the `length` property from output types because it is redundant to the `.text.length` one. This change is potentially getting released on 10/02.
> [Text Analytics] Removes the length property from output types

- common/tools/eslint-plugin-azure-sdk/README.md
The `README.md` file instructs the users that they need to create a local `.eslintrc.json` file which is not necessary.
> [ESLint plugin] Update the README.md file

- sdk/communication/communication-administration/CHANGELOG.md
- sdk/communication/communication-administration/package.json
- sdk/communication/communication-administration/src/communicationIdentity/generated/src/generatedCommunicationIdentityClientContext.ts
- sdk/communication/communication-administration/swagger/CommunicationIdentity.md
- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-chat/src/generated/src/chatApiClientContext.ts
- sdk/communication/communication-common/CHANGELOG.md
- sdk/communication/communication-common/package.json
- sdk/communication/communication-sms/CHANGELOG.md
- sdk/communication/communication-sms/package.json
- sdk/communication/communication-sms/src/generated/src/smsApiClientContext.ts
Replaces auto-generated https://github.com/Azure/azure-sdk-for-js/pull/11387
In addition to the generated version bump, this PR increments package-version for autorest and fixes the dependencies.
> Increment version for communication releases

- sdk/core/core-auth/src/tokenCredential.ts
- sdk/identity/identity/src/credentials/chainedTokenCredential.ts
Since some of our customers have started to work with our credentials directly, we've agreed that we should let them know that if they decide to work with the `getToken` methods themselves, they will need to figure out caching and token refreshing.
Fixes #11343
The specific message the team wants to add is [this one](https://github.com/Azure/azure-sdk-for-js/issues/11343#issuecomment-698623222):
```
// This method is called automatically by Azure SDK client libraries. You may call this method
// directly, but you must also handle token caching and token refreshing.
```
The main change here is an extra comment on both `ChainedTokenCredential` and `TokenCredential` to help users see this if they decide to use any of both directly. `DefaultAzureCredential` gets automatically handled by …
> [Identity] Clearer message on the getToken methods

- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/textanalytics/ai-text-analytics/package.json
This change was made to the template as part of the shared rollup configuration, but wasn't applied to TA or FR. I noticed this when the TA pipeline failed this morning.
> Fixed globs in TA/FR integration-test:node scripts

- eng/pipelines/templates/jobs/archetype-sdk-integration.yml
- sdk/eventhub/event-hubs/tests.yml
Last triggered pipeline - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=552802&view=results
With this PR, our test subscription (preview) creates the event-hubs resources in the canary regions for testing ('Central US EUAP' and 'EAST US 2 EUAP' regions as suggested by the service team).
Many thanks to @danieljurek!! 
JAVA - https://github.com/Azure/azure-sdk-for-java/pull/15345 
.NET - https://github.com/Azure/azure-sdk-for-net/pull/15265
> [EventHubs] Canary support for event-hubs live tests

- sdk/cosmosdb/cosmos/README.md
- Merging of PR https://github.com/Azure/azure-sdk-for-js/pull/11063/ that had a relative link caused pipeline failures. This PR uses absolute link for the relative link that was merged in
- The new updated checks do not allow relative links for the readme - refer link guidelines -  https://aka.ms/azsdk/guideline/links
> Use absolute link for samples as relative links are not allowed

- sdk/identity/identity/CHANGELOG.md
This is an experiment. It's a separate PR with the changelog entry for this previous PR: https://github.com/Azure/azure-sdk-for-js/pull/11355
I'm trying to separate the code changes from the changes related to documentation etc. I'm wondering if it is easier to review this this way or if I should always add the changelog entry as part of the PR with the code changes.
> [Identity] Changelog entry for the recent DeviceCodeCredential change

- sdk/servicebus/service-bus/README.md
During the UX study we realized we don't actually have a code snippet in the readme to show how to construct the ServiceBusClient (there were links, but no actual code).
I fixed that and added in a bit more explanatory text showing how to use `DefaultAzureCredential`.
> [service-bus] Update readme to contain an actual snippet of code showing the constructor

- sdk/communication/communication-administration/test/utils/recordedClient.ts
- sdk/communication/communication-chat/sample.env
- sdk/communication/communication-chat/test/utils/recordedClient.ts
- sdk/communication/communication-chat/tests.yml
Also some cleanup. The `testEnv` proxy isn't needed because `createRecorder` overrides the environment in playback mode already with the replace variables. (Which gave me lots of headaches until I realized that)
> [Communication] Add pipeline for Chat live tests

- sdk/servicebus/service-bus/test/sendBatch.spec.ts
From https://github.com/Azure/azure-sdk-for-js/pull/11576
> [Service Bus] Fix test failure in the canary region

- sdk/keyvault/keyvault-keys/CHANGELOG.md
This is an experiment. It's a separate PR with the changelog entry for this previous PRs that have changed the Key Vault packages.
This includes only the changes relevant to our customers. Therefore, the following PRs:
- [Key Vault Keys] Add new algorithms, remote only #11260
- Add oct-HSM support #11027
Notes:
- Even though we did update all the packages to the latest swagger, the only public API change was on Key Vault Keys: https://github.com/Azure/azure-sdk-for-js/pull/11370/files#diff-91e6187853dc6c6c676058faaa81d8e2R212
I'll add more as we go through the remaining budget for this upcoming release.
Feedback appreciated ✨
> [Key Vault] All of the Key Vault changelog entries for the upcoming release

- sdk/servicebus/service-bus/tests.yml
Similar to what we did for event-hubs... https://github.com/Azure/azure-sdk-for-js/pull/11318
Java - https://github.com/Azure/azure-sdk-for-java/pull/15844
.NET - https://github.com/Azure/azure-sdk-for-net/pull/15592
> [Service Bus] Run live tests in the canary region

- sdk/search/search-documents/package.json
- sdk/search/search-documents/review/search-documents.api.md
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushSizeBased.ts
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushTimerBased.ts
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/manualFlush.ts
- sdk/search/search-documents/samples/typescript/src/utils/interfaces.ts
- sdk/search/search-documents/samples/typescript/src/utils/setup.ts
- sdk/search/search-documents/src/index.ts
- sdk/search/search-documents/src/indexModels.ts
- sdk/search/search-documents/src/searchClient.ts
- sdk/search/search-documents/src/searchIndexingBufferedSender.ts
@xirzec
This PR is to add fancy batch supporting for the search-documents SDK.
> Initial Commit for Advanced Batching

- sdk/keyvault/keyvault-certificates/README.md
Removed the following link since it lead nowhere:
```md
- [List all versions of a certificate](#list-all-versions-of-a-certificate).
```
Thank you @zzhxiaofeng !
Fixes #11492
> [Key Vault Certificates] Fixed bad reference in the README

- sdk/keyvault/keyvault-keys/README.md
The readme sample for the `sign` method of the CryptographyClient was using `signData`.
Fixes #11493
@zzhxiaofeng thank you!
Reviews appreciated.
> [Key Vault Keys] Fixed wrong method in a readme sample

- sdk/anomalydetector/ai-anomaly-detector/review/ai-anomaly-detector.api.md
- sdk/anomalydetector/ai-anomaly-detector/src/AnomalyDetectorClient.ts
- sdk/anomalydetector/ai-anomaly-detector/src/index.ts
Now that https://github.com/Azure/azure-sdk-for-js/pull/11403 has been merged, we can get rid of a few ignoring comments of `ts-naming-options` linting rule. Furthermore, we were ignoring `ts-naming-options` in other places for no good reason as far as I can tell so I did the fix and re-enabling the rule in those places again.
> [Anomaly Detector] Does not ignore ts-naming options

- sdk/schemaregistry/schema-registry-avro/README.md
- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
- sdk/schemaregistry/schema-registry/README.md
1. Use 1.0.0.beta.2 for schema-registry-avro -> schema-registry so we are building and testing against what will go out in next release.
2. Remove comment about the serialization format changing, decision has been made to keep this through GA
3. Use reference doc links for links between packages
Contributes to #10950
> [schema registry] Minor follow-up

- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendcloudeventschemaevents/recording_enriches_events_with_distributed_tracing_information.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendcloudeventschemaevents/recording_sends_a_single_event.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendcloudeventschemaevents/recording_sends_multiple_events.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendcustomschemaevents/recording_sends_a_single_event.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendcustomschemaevents/recording_sends_multiple_events.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendevents/recording_sends_a_single_event.json
- sdk/eventgrid/eventgrid/recordings/browsers/eventgridpublisherclient_sendevents/recording_sends_multiple_events.json
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendcloudeventschemaevents/recording_enriches_events_with_distributed_tracing_information.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendcloudeventschemaevents/recording_sends_a_single_event.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendcloudeventschemaevents/recording_sends_multiple_events.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendcustomschemaevents/recording_sends_a_single_event.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendcustomschemaevents/recording_sends_multiple_events.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendevents/recording_sends_a_single_event.js
- sdk/eventgrid/eventgrid/recordings/node/eventgridpublisherclient_sendevents/recording_sends_multiple_events.js
- sdk/eventgrid/eventgrid/src/cloudEventDistrubtedTracingEnricherPolicy.ts
- sdk/eventgrid/eventgrid/src/eventGridClient.ts
- sdk/eventgrid/eventgrid/src/generated/generatedClient.ts
- sdk/eventgrid/eventgrid/src/tracing.ts
- sdk/eventgrid/eventgrid/test/cloudEventDistrubtedTracingEnricherPolicy.spec.ts
- sdk/eventgrid/eventgrid/test/eventGridClient.spec.ts
- Create spans for each of the send operations on
`EventGridPublisherClient`
- When sending events in the Cloud Events schema, if we have a
traceparent or tracestate and an event we are sending does not have
any distributed tracing metadata (per the Cloud Events distributed
tracing spec) we add this metadata associating the events with the
span representing the HTTP operation that sends the event to the Azure
Event Grid Service.
Fixes: #11056
> [EventGrid] Distributed Tracing for EventGrid

- sdk/servicebus/service-bus/src/log.ts
- sdk/test-utils/recorder/CHANGELOG.md
- sdk/test-utils/recorder/src/utils.ts
- sdk/test-utils/recorder/test/node/utils.spec.ts
@ljian3377 came up with an issue where the response has Partial Content(Success code - 206), the hex value is not decoded for such responses.
This PR adds all the successful status codes to be allowed to filter to decode the binary responses.
> [Recorder] Followup of #10009 - Allow all successful status codes while decoding hex values into binary

- sdk/metricsadvisor/ai-metrics-advisor/README.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/alertingConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/dataFeed.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/detectionConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/hooks.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/alertingConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/detectionConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/hooks.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/index.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/mappers.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/swagger/README.md
- sdk/metricsadvisor/ai-metrics-advisor/test/adminclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/hookTests.spec.ts
- Rename `*id` to just id for get/update/delete methods
- also shorten `*ConfigurationId` to `*ConfigId`
- Improve README
- Swagger transform to add ref docs for `Metric` and `Dimension`
- Swagger transform to remove `hook` prefix from `hookId` and `hookName`
- Replace all `*DataFeedSourcePatch` types with a mapped type
- Add missing DataFeed.creator property
- Use mapped type for input of `create*()` methods instead of multiple ordered parameters.
- Replace configuration patch types with mapped types from their full result types.
See #11593 for discussions.
> Address some CR feedback to #11593

- sdk/keyvault/keyvault-certificates/tests.yml
- sdk/keyvault/keyvault-keys/tests.yml
- sdk/keyvault/keyvault-secrets/tests.yml
by default there is no limit and we've seen builds timed out 6 hours later which
is wasting of resources.
> [Keyvault] Set timeout limit of 90 for live test pipelines

- sdk/identity/identity/CHANGELOG.md
Setting up the release date for Identity as Tomorrow just to give me some range of action.
I also added some changelog entries that were missing. Feedback appreciated! ✨
> [Identity] Changelog updates before releasing

- sdk/tables/data-tables/README.md
- sdk/tables/data-tables/samples/javascript/src/createAndDeleteEntities.js
- sdk/tables/data-tables/samples/javascript/src/createAndDeleteTable.js
- sdk/tables/data-tables/samples/javascript/src/queryEntities.js
- sdk/tables/data-tables/samples/javascript/src/queryTables.js
- sdk/tables/data-tables/samples/javascript/src/updateAndUpsertEntities.js
- sdk/tables/data-tables/samples/typescript/src/authenticationMethods.ts
- sdk/tables/data-tables/samples/typescript/src/createAndDeleteEntities.ts
- sdk/tables/data-tables/samples/typescript/src/createAndDeleteTable.ts
- sdk/tables/data-tables/samples/typescript/src/queryEntities.ts
- sdk/tables/data-tables/samples/typescript/src/queryTables.ts
- sdk/tables/data-tables/samples/typescript/src/updateAndUpsertEntities.ts
Closes https://github.com/Azure/azure-sdk-for-js/issues/11489
- As the issue states, there are some unneeded exports in the Javascript samples for Azure Tables that have been removed.
- As reported by @joheredi , the following replacements in the `README.md` have been done (identified as a bug): `entity.PartitionKey` to `entity.partitionKey` and `entity.RowKey` to `entity.rowKey`.
- Also a little typo in the `README.md` in the same section has been fixed.
> Fix typos in README.md and Javascript samples for Azure Tables

- sdk/keyvault/keyvault-keys/CHANGELOG.md
After testing the samples and everything that could come to mind from the source, I think I'm confident to trigger the release build based on the commit from this PR.
> [Key Vault Keys] Changelog release date

- sdk/servicebus/service-bus/CHANGELOG.md
This PR adds the release date for Service Bus preview 7 and re-orders the "new features" in the order of relevance
> Add release date, re-order features in changelog

- sdk/servicebus/service-bus/samples/javascript/advanced/sessionRoundRobin.js
- sdk/servicebus/service-bus/samples/javascript/advanced/sessionState.js
- sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts
* Swap to using the session queue name from the .env file rather than pointing to QUEUE_NAME
* sessionState.js was incorrect and didn't match the typescript one (using old stuff).
> [service-bus] Sample fixes (stale usage of API and use the proper env variable name)

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
This PR simplifies the options being used for the subscribe() method post the changes in #11658
> [Service Bus] Simplify options for subscribe()

- sdk/schemaregistry/schema-registry-avro/tests.yml
- sdk/schemaregistry/schema-registry/tests.yml
This is a prereq for getting live nightly tests working for schema registry.  The change is trivial, adding two vanilla tests.yml files.
Tests won't pass yet, but these files need to be present to create the pipelines on the backend. Once the pipelines are set-up, I will iterate on the tests using a draft PR. test-resources.json and any test changes needed will be part of that draft PR, and once I get a green run on that, I'll open the draft up for review to actually have nightly live tests working.
> Add tests.yml for schema-registry

- sdk/cognitiveservices/cognitiveservices-computervision/package.json
- sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
- sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
Based on request from @lmazuel (Issue: https://github.com/Azure/sdk-release-request/issues/797) , I have regenerated the Cognitive Services Computer Vision TS SDK in this PR. Command Used:
```
autorest --reset && autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.4 --package-version=7.1.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/ComputerVision/readme.md
```
As you can see from the PR, only the service version info changed. Other than that, the only other information is 2 new comments. Updated the version 7.0.1 -> 7.1.0. 
@lmazuel FYI
@ramya-rao-a Please review and approve.
> Regenerated Computer Vision SDK

- sdk/schemaregistry/schema-registry-avro/karma.conf.js
- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry-avro/rollup.base.config.js
- sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts
- sdk/schemaregistry/test-resources.json
Get nightly live tests of schema-registry and schema-registry-avro running.
* Add test-resources.json to provision service
* Update schema-registry-avro tests to use real service in live test mode rather than its usual mocking.
> [schema registry] live tests

- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
We have a scenario to rename a data feed so the listing by the
"js-test" prefix would only return one result thus break listing
tests' assumption of at least two results.
Fixed by moving listing to after creating three data feeds so we still
have two data feeds with "js-test" prefix.
> [MetricsAdvisor,test] Fix listing datafeed live tests

- sdk/storage/storage-blob/karma.conf.js
- sdk/storage/storage-blob/recordings/node/blobclient/recording_lastaccessed_returned.js
- sdk/storage/storage-blob/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_blob_version_delete.js
- sdk/storage/storage-blob/sample.env
- sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
- sdk/storage/storage-blob/test/blobclient.spec.ts
- sdk/storage/storage-blob/test/blobserviceclient.spec.ts
- sdk/storage/storage-blob/test/blobversioning.spec.ts
- sdk/storage/storage-blob/test/node/sas.spec.ts
- sdk/storage/storage-blob/test/utils/index.ts
- sdk/storage/storage-blob/test/utils/testutils.common.ts
- sdk/storage/storage-blob/tests.yml
- sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_for_directory_should_work_for_permissions_m_e_o_p.js
- sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_should_work_with_agentobjectid_preauthorizedagentobjectid.js
- sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_should_work_with_correlationid.js
- sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_directory_sas/recording_generatedatalakesasqueryparameters_for_file_should_work_for_permissions_m_e_o_p.js
- sdk/storage/storage-file-datalake/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_file_for_20191212.js
- sdk/storage/storage-file-datalake/src/sas/DataLakeSASSignatureValues.ts
- sdk/storage/storage-file-datalake/test/node/sas.spec.ts
- sdk/storage/storage-file-datalake/test/serviceclient.spec.ts
- sdk/storage/storage-file-datalake/test/utils/index.ts
- sdk/storage/storage-file-datalake/tests.yml
- sdk/storage/storage-file-share/test/fileclient.spec.ts
- sdk/storage/storage-file-share/test/fileserviceclient.spec.ts
- sdk/storage/storage-file-share/tests.yml
- sdk/storage/storage-queue/tests.yml
- sdk/storage/test-resources-post.ps1
- sdk/storage/test-resources.json
> [storage][stg74] test coverage improvement

- eng/pipelines/templates/stages/archetype-js-release.yml
- sdk/template/template/CHANGELOG.md
- sdk/template/template/package.json
Copy artifact step in release stage is using pattern <artifact-name>-*.tgz to copy artifact into publish folder. This is causing issue when two packages has same prefix. for e.g. storage-blob and storage-blob-changefeed.
Fix here is to ensure we are looking for package with artifact name followed by version format to ensure we pick only required artifact.
> Updated regex to pick correct package artifact

- common/tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-files-required.md
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-files-required.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-files-required.ts
- sdk/storage/storage-datalake/package.json
~This change updates the `ts-package-json-files-required` rule to check for the absence of `src` and `dist-esm` in the `files` list in `package.json` since sourcemaps now have the sources embedded. It is based on discussion with @xirzec here https://github.com/Azure/azure-sdk-for-js/pull/11273#discussion_r492975784. Related issue: https://github.com/Azure/azure-sdk-for-js/pull/7615.~
~TODO in this PR: update every package's `package.json` to conform to the final rule before merging.~
After discussion with @willmtemple, @bterlson, and @xirzec here, this PR updates the eslint plugin to make sure `dist-esm` is included and `src` is not in `package'json`'s `files` list.
> [ESLint Plugin] Enforce inclusion of dist-esm and exclusion of src in files field in package.json

- sdk/digitaltwins/digital-twins/src/digitalTwinsClient.ts
From what I can see, this issue (#11555) can be fixed by reordering the parameters passed to the underlying REST client. The continuation token is expected to be the second parameter (rather than the first).
> Fix ADT relationship paging (#11555)

- .gitignore
- common/smoke-test/.gitignore
- common/smoke-test/Initialize-SmokeTests.ps1
- common/smoke-test/README.md
This PR contains some quick doc updates that aim to clarify a few things I was initially confused by when trying to execute and understand how the smoke test initialization/run process worked.
I've also updated the .gitignore to ignore changes to the auto-generated files. I've also considered the possibility of using `git update-index --assume-unchanged` for auto-gen changes to package.json, but I'm thinking it's not worth adding the git dependency to Initialize-SmokeTests.ps1.
https://github.com/Azure/azure-sdk/issues/1879
> Elaborate on smoke test initialize logic in docs and script. Update .gitignore.

- sdk/batch/batch/package.json
- sdk/batch/batch/sample.env
- sdk/batch/batch/test/batchClient.spec.ts
- sdk/batch/batch/test/sample.env
Fix compile errors in the batch test suite after regenerating using the latest swagger. The test suite runs all green now.
> [Batch] update tests

- sdk/communication/communication-administration/samples/javascript/README.md
- sdk/communication/communication-administration/samples/javascript/issueToken.js
- sdk/communication/communication-administration/samples/javascript/revokeTokens.js
- sdk/communication/communication-administration/samples/javascript/sample.env
- sdk/communication/communication-administration/samples/typescript/README.md
- sdk/communication/communication-administration/samples/typescript/sample.env
- sdk/communication/communication-administration/samples/typescript/src/issueToken.ts
- sdk/communication/communication-administration/samples/typescript/src/revokeTokens.ts
- sdk/communication/communication-sms/package.json
- sdk/communication/communication-sms/samples/javascript/README.md
- sdk/communication/communication-sms/samples/javascript/sample.env
- sdk/communication/communication-sms/samples/javascript/sendSms.js
- sdk/communication/communication-sms/samples/typescript/README.md
- sdk/communication/communication-sms/samples/typescript/sample.env
- sdk/communication/communication-sms/samples/typescript/src/sendSms.ts
The smoke tests are failing because the env variable override in test-resources.json injects a value for COMMUNICATION_CONNECTION_STRING, but most of the samples call for `process.env["CONNECTION_STRING"]`. This PR updates all samples and README docs to reference the longer, scoped connection string environment variable.
https://github.com/azure/azure-sdk/issues/1934
> Match connection string variable to test-resources override for communication samples

- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/src/fetchHttpClient.ts
- sdk/core/core-http/src/policies/redirectPolicy.ts
- sdk/core/core-http/test/policies/redirectPolicy.spec.ts
- sdk/core/core-https/src/policies/redirectPolicy.ts
- sdk/core/core-https/test/redirectPolicy.spec.ts
`core-http` has been using fetch without explicitly specifying a redirect behavior which defaults to `follow`. This caused our `redirectPipeline` to never actually execute.
In this PR I'm setting redirect to `manual` so that our pipeline handles redirects. Unfortunately there doesn't seem to be a way to set manual redirect handling for `XMLHttpRequest`, so browsers will keep the default behavior.
I'm also fixing the redirect logic to align with the [tests in Autorest Test Server ](https://github.com/Azure/autorest.testserver/blob/5eba43116b366969466663be449efc017c9f5a34/legacy/routes/httpResponses.js#L470)and be consistent with the other languages
Fixes #10103
> [core-http] Redirect pipeline

- .github/CODEOWNERS
This PR updates the CodeOwners file to add the `Mgmt` label to PRs for the management packages
> Add Mgmt label to PRs for arm packages

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/docker-debian.sh
- .devcontainer/library-scripts/git-lfs-debian.sh
This PR adds the ```.devcontainer``` configuration files needed to enabled Codespaces for the JS repository. I created this using VSCode locally to configure for remote dev containers, but selected the universal container for codespaces. We'll try to have all of the repos use this one container, but change if we need to.
This initial configuration is as is - including running Oryx. Unfortunately Oryx doesn't appear to detect Rush so it riggers NPM automatically. I'll do a subsequent PR which disables Oryx and runs a script/command that primes the container for development using the toolchains that we've set up ... but I wanted to lay down this basic OOB experience first.
> Initial Codespaces configuration

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/deserializationPolicy.ts
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/test/deserializationPolicy.spec.ts
- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/package.json
- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/operationResponse.ts
- sdk/core/core-http/src/policies/deserializationPolicy.ts
- sdk/core/core-http/src/util/constants.ts
- sdk/core/core-http/test/policies/deserializationPolicyTests.ts
This PR is to address the issue https://github.com/Azure/azure-sdk-for-js/issues/8881
@joheredi Please review and approve
Note: I have set the release date for 2020-10-16. Let me know of I need to change it.
> [core-http] Allow defining multiple error responses for Operations

- sdk/metricsadvisor/ai-metrics-advisor/README.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/alertingConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/dataFeed.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/detectionConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/hooks.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/incidentsAndAlerts.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/seriesData.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/alertingConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/detectionConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/hooks.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/incidentsAndAlerts.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/seriesData.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/advisorclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/hookTests.spec.ts
- Rename names that are too generic
- Rename `admins` to `adminEmails` and `viewers` to `viewerEmails`
- Remove `-List` suffix from array property names
- Use DimensionKey where a dimension identification is needed
This is more consistent with other APIs.  We might decide to remove
the wrapping `dimension` property around `Record<string, string>` in
the future but for all should have it.
Also rename properties of `DimensionKey` type to `seriesKey`.
> [MetricsAdvisor] better names

- common/smoke-test/Initialize-SmokeTests.ps1
This PR makes two changes:
1. Refactors `common/smoke-test/Initialize-SmokeTests.ps1` to be more readable, by moving all logic into functions.
2. Parallelizes the resource deployment logic. This reduces our total smoke test pipeline duration by 25-35 minutes, which is a roughly 50% reduction in total pipeline duration.
```
$ Measure-Command { ./Initialize-SmokeTests.ps1 -Verbose @subscriptionConfiguration }
...
Minutes           : 3
Seconds           : 31
...
```
Due to the refactoring, reviewing the parallelization logic may be annoying. All that logic can be reviewed in isolation in the [second commit](https://github.com/Azure/azure-sdk-for-js/commit/39ee0ae5bc1561b90a922bf0bf7e37810cacaea3)
> Parallelize smoke test resource deployments. Improve script readability.

- common/smoke-test/smoke-tests.yml
This PR adds a new entry to the smoke test matrix to add a public cloud test against a Canary/EUAP region (specifically eastus2euap), and to cover multiple node versions across the matrix.
Version coverage across the matrix taken from [here](https://github.com/Azure/azure-sdk-for-js/issues/9462)
Azure/azure-sdk#1879
> Add canary region and node LTS coverage to smoke test matrix

- sdk/core/core-https/src/nodeHttpsClient.ts
Node 14 changed how streams propagate errors so that they're always async. This revealed some issues in how we use streams for upload/download reporting during error conditions.
Fixes #11919
> [core-https] Fix some issues with streams in `NodeHttpsClient`

- eng/pipelines/mgmt-ci.yml
- eng/pipelines/mgmt-pr.yml
These pipelines only test npm related checks with no other pipeline template dependencies. Reduce the false negative rate by not running them for unrelated changes.
> Exclude eng directory from npm ci/pr gates

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build.yml
- sdk/template/ci.yml
Prevent template pipeline run triggered by eng/common changes.
Auto close update version Pull Requests for template pipelines.
Switch from TestPipeline variable to parameter
This includes some of the changes from https://github.com/Azure/azure-sdk-for-js/pull/11944 as other changes on that PR will take longer to complete.
> Switch from Testpipeline variable to parameter

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/serviceBusClient.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/utils/testutils2.ts
This is a follow up for the changes in the PR #11962
In #11926 we decided not to have the overloads for `createReceiver`, `acceptSession` and `acceptNextSession` methods that would allow us to hide the message settlement methods if a TypeScript  user is using ReceiveAndDelete mode. This PR removes the said overloads that are remnants of #11962
> Remove receiver overloads meant to hide settlement methods when using ReceiveAndDelete mode

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/test/utils/testUtils.ts
Removing `userId` from the top level ServiceBusMessage
- It will still be present in the `ServiceBusReceivedMessage._amqpAnnotatedMessage.properties`
- Since this property is something not present on the top level interface/object from the beginning, this is being removed
> [Service Bus] Remove userId on the top level message

- sdk/eventgrid/eventgrid/test/eventGridClient.spec.ts
- sdk/formrecognizer/ai-form-recognizer/test/public/node/formrecognizerclient.spec.ts
- sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/adminclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/advisorclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/hookTests.spec.ts
- sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
- sdk/test-utils/recorder/CHANGELOG.md
- sdk/test-utils/recorder/GUIDELINES.md
- sdk/test-utils/recorder/README.md
https://github.com/Azure/azure-sdk-for-js/pull/10013 updated the stop() method that is exported with the recorder to return a promise to make sure certain heavy recordings were recorded properly in the browser, @jeremymeng had updated all the packages to `await recorder.stop()`. 
However, some of the tests missed this update. This PR attempts to fix the rest of the tests and any of the `md` files that are outdated w.r.t this change.
Please make sure the call is awaited from now on. Thanks to @willmtemple for pointing out!
> [Recorder] Fixing the missed await for `recorder.stop()` in the tests in all the packages 📝

- sdk/tables/data-tables/review/data-tables.api.md
- sdk/tables/data-tables/src/TableClient.ts
- sdk/tables/data-tables/src/models.ts
- sdk/tables/data-tables/src/serialization.ts
- sdk/tables/data-tables/test/integration/tableclient.spec.ts
When querying table entities the result includes 4 System properties:
- odata.etag: Always returned
- Timestamp: Can be omitted by setting a select query filter
- PartitionKey: Can be omitted by setting a select query filter
- RowKey: Can be omitted by setting a select query filter
This PR contains 2 changes to make the UX better when querying entities
1. Rename `odata.etag` -> `etag` and `Timestamp` -> `timestamp` we already do this for PartitionKey and RowKey
2. Add a return type for query operations to describe that a return type can contain the properties listed above
> [Tables] Rename etag and timestamp system properties

- sdk/core/core-client/src/deserializationPolicy.ts
- sdk/core/core-client/test/deserializationPolicy.spec.ts
- sdk/core/core-http/src/policies/deserializationPolicy.ts
- sdk/core/core-http/test/policies/deserializationPolicyTests.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/unit/platform/nodejs/httpSender.test.ts
Currently, if we receive an un expected HTTP status code (not defined in the operation spec) we'll try to use the `default` mapper. However there are cases when a default mapper is not defined, in this case we are treating it as a success.
This PR makes sure that the unexpected status code is handled as an error by throwing the parsedResponse in the scenario where the deserializer is not provided with a mapper, this aligns with what other languages are doing for unexpected status codes and no default mapper
As an example, with the current behavior, the following operation will return a success response with a 400 status code:
https://github.com/Azure/autorest.testserver/blob/23eb8f04399596f2efea1a8828f080946edfc049/swagger/httpInfrastructure.quirks.json#L2746
With the changes in this PR …
> [core-http] Throw on unexpected status code and no default mapper

- sdk/servicebus/service-bus/test/batchReceiver.spec.ts
By observation, this fix seems to have made all the entries in the matrix to be green and never failed in 1000 iterations. Hence, going with that and aborting the investigation.
Fixes #12000
> [Service Bus] Fix the flaky failure by increasing the max_wait_time

- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/messageProperties.ts
- sdk/core/core-amqp/test/message.spec.ts
- sdk/servicebus/service-bus/test/internal/serviceBusMessage.spec.ts
As seen in https://github.com/amqp/rhea/issues/323, `user-id` is wrongly typed in rhea.
This PR removes userId from the AMQP message properties in `@azure/core-amqp` package for now.
We will add it back once the type for `user-id` is settled on and rhea releases an update
> [Core AMQP] Remove userId until its type is fixed in rhea

- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/test/deferredMessage.spec.ts
- sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
This PR ensures we do an early exit when input is empty array to methods that take an array as input
This closes #12095 which was logged for the `receiveDeferredMessages()` method and also fixes the same for `scheduleMessages()` and `cancelScheduledMessages()` calls
> [Service Bus] Empty array validation

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/serviceBusClient.ts
- sdk/servicebus/service-bus/test/invalidParameters.spec.ts
- sdk/servicebus/service-bus/test/propsToModify.spec.ts
- sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/utils/testutils2.ts
Unlike other languages, we don not use enums and use string literals instead. For the `subQueue` property, this opens up a potential confusion for people if they think they can pass in queue names. To help with this, in this PR we
- rename the option `subQueue` to `subQueueType`
- inline the string literals instead of exporting an explicit type
> [Service Bus] subQueue -> subQueueType

- sdk/core/core-client/src/urlHelpers.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-http/src/serviceClient.ts
- sdk/core/core-http/test/serviceClientTests.ts
When serializing `multi` format query parameters, if the collection is empty we should omit the query parameter.
For context, a collection with multi format would be serialized as
Collection: [1,2,3]
Serialized Url: http://example.com?q=1&q=2&q2
So when the collection is empty: []
We should skip the parameter otherwise the service would interpret it as a collection with a null element i.e. [nul]
For an empty collection: []
**Current behavior**
http://example.com?q=
**Expected**
http://example.com
> [core-http] Do not serialize empty multi collection param 

- common/smoke-test/smoke-tests.yml
There is still some SDK work to get these working. In the meantime, we'd like to keep the smoke test pipeline passing so it can be used for PRs and to locate when regressions happen.
> Disable sovereign cloud smoke tests

- sdk/core/core-client/src/deserializationPolicy.ts
- sdk/core/core-client/test/deserializationPolicy.spec.ts
- sdk/core/core-http/src/policies/deserializationPolicy.ts
- sdk/core/core-http/test/policies/deserializationPolicyTests.ts
- sdk/storage/storage-blob/test/appendblobclient.spec.ts
- sdk/storage/storage-blob/test/blockblobclient.spec.ts
- sdk/storage/storage-blob/test/pageblobclient.spec.ts
- sdk/storage/storage-queue/test/queueserviceclient.spec.ts
Currently we check `parsedBody.error` or `parsedBody` for `code` and
`message` to use in the `RestError` to be thrown. However, we do this
on the raw object from parsing XML.
In the example added to the test, without this fix, the `parsedBody`
from xml parsing is
```js
{ Code: "ContainerAlreadyExists", Message: "The specified container already exists." }
```
but we are accessing the properties with lowercase `code` and `message`.
We should check on the object after de-serializing when we have error
object properly mapped already.
> [core-http] de-serialize before checking internalError

- sdk/cognitiveservices/cognitiveservices-qnamaker/package.json
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/index.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/knowledgebaseMappers.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/mappers.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/parameters.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/alterations.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/endpointSettings.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/knowledgebase.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/operations.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/qnAMakerClient.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/src/qnAMakerClientContext.ts
- sdk/cognitiveservices/cognitiveservices-qnamaker/swagger/readme.md
This is to address the Issue: https://github.com/Azure/sdk-release-request/issues/923 
**Command Used**
```
autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.typescript@4.2.2 --package-version=4.0.0 swagger\readme.md
AutoRest code generation utility [cli version: 3.0.6247; node: v12.18.4, max-memory: 2048 gb]
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
Loading AutoRest core      'C:\Users\sarajama\.autorest\@microsoft.azure_autorest-core@2.0.4417\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4417)
Loading AutoRest extension '@microsoft.azure/autorest.typescript' (4.2.2->4.2.2)
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51) …
```
> [data-plane] JS: 'Release for QnA Maker 2020-11-02'

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/transforms.spec.ts
instead of Minutely and Secondly
> [MetricsAdvisor] Use PerMinute and PerSecond in granularity type

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/serviceBusError.ts
Next core-amqp release will be v2, updating files accordingly so that we can close #12266
Service Bus preview 8 is using core-amqp v2.0.0-beta.1 which has `MessageErrorCodes` and not `MessagingErrorCodes`. Updating SB to use `MessageErrorCodes` for now. Once SB preview 8 is released, we will update it to use v2.0.0 of core-amqp and revert this change
> Increment version for core-amqp v2

- sdk/core/core-http/src/serializer.ts
Fixes #11758
When uploading files on Safari 5.0, An exception `body must be a string, Blob, ArrayBuffer, ArrayBufferView, or a function returning NodeJS.ReadableStream.` will thrown.
> [core-http] fix An exception thrown on Safari 5.0

- sdk/servicebus/service-bus/README.md
- sdk/servicebus/service-bus/migrationguide.md
- sdk/servicebus/service-bus/src/modelsToBeSharedWithEventHubs.ts
- sdk/servicebus/service-bus/src/receivers/shared.ts
> [Service Bus] Fix readme and typedoc for preview.8 ⚓

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
This addresses one of the Arch Board review feedback. I still keep the
timestamps in MetricSeriesData and MetricEnrichedSeriesData as Date
type because their most common usage is plotting because keeping them as Date
make it easier to use year/month/date in x-axis labels.
This fixes #11832
> [MetricsAdvisor] change timestamps type from Date to number

- common/config/rush/common-versions.json
- sdk/servicebus/service-bus/package.json
Pick older core-http(~~1.1.6~~ 1.1.9) for service-bus preview.8 since 1.2.0 is not released.
This will be reverted once the service-bus preview.8 is released.
> [Service Bus] Pick older core-http for service-bus preview.8 🏁

- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/coreHttp.ts
- sdk/core/core-http/src/policies/deserializationPolicy.ts
- sdk/core/core-http/src/serializer.ts
- sdk/core/core-http/src/serviceClient.ts
- sdk/core/core-http/src/util/serializer.common.ts
- sdk/core/core-http/src/util/utils.ts
- sdk/core/core-http/src/util/xml.browser.ts
- sdk/core/core-http/src/util/xml.common.ts
- sdk/core/core-http/src/util/xml.ts
- sdk/core/core-http/src/webResource.ts
- sdk/core/core-http/test/policies/deserializationPolicyTests.ts
- sdk/core/core-http/test/serviceClientTests.ts
- sdk/core/core-http/test/xmlTests.ts
Currently our xml parser uses hard-coded `_` as key to access parsed
xml element content. This causes issue like storage customer getting
errors listing blobs when they use `_` as Blob metadata key.
This PR adds support to allow customizing the xml parser char key via
options. Currently `xmlCharKey` option is supported, with room for
other options (e.g., attr key for accessing parsed xml attributes).
> [core-http] Support overriding xml parser char key via options

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/README.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/alertingConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/detectionConfig.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/alertingConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/detectionConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/adminclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/advisorclient.spec.ts
- [Breaking] Rename method for listing alerts
- `listAlertsForAlertConfiguration(alertConfigId, startTime, endTime, timemode, options)` to `listAlerts(alertConfigId, startTime, endTime, timemode, options)`
- [Breaking] Rename feedback methods :
- `listMetricFeedbacks()` to `listFeedback()`
- `getMetricFeedback()` to `getFeedback()`
- `createMetricFeedback()` to `createFeedback()`
- [Breaking] Rename detection configuration methods:
- `createMetricAnomalyDetectionConfiguration(anomalyConfig)` to `createDetectionConfig(anomalyConfig)`
- `getMetricAnomalyDetectionConfiguration(detectionConfigId)` to `getDetectionConfig(detectionConfigId)`
- `createMetricAnomalyDetectionConfiguration(config)` to `createDetectionConfig(config)`
- `updateMetricAnomalyDetectionConfiguration(configId, patch)` to …
> [MetricsAdvisor] Rename methods

- sdk/servicebus/service-bus/test/atomManagement.spec.ts
This test was unintentionally checked-in as part of a huge PR, I meant to remove it but left it since it was harmless.
Just cleaning it up now to reduce the false positives in [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=606570&view=logs&j=073ebbf1-9390-59a1-0ff8-08c656576bcd&t=428931fe-c351-55db-0604-c27a1c97620f).
> [Service Bus] This test is doesn't test anything

- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/alertingConfig.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
and fix TypeScript sample build errors
This resolves #11957
> [MetricsAdvisor] Add an alias type for createDateFeed feed parameter

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/partitionPump.ts
- sdk/eventhub/event-hubs/test/node/disconnects.spec.ts
Fixes #12278 
This PR adds a check within the `PartitionPump`'s receive events loop to determine whether the receiver has been closed. If the receiver has been closed, it will create a new receiver using an event start position that matches the last event seen by the pump.
The receiver is explicitly closed when a disconnected event is received on the underlying AMQP connection, which causes calls to `receiveBatch` to immediately return any events it had collected up to this point. Note that once the receiver is closed, the receiver's onAmqpMessage handler is removed so it won't receive any additional events.
I manually tested the changes in this PR against the sample code in the linked issue.
I also updated the existing `disconnect` test to confirm that
- the `maxWaitTimeInSeconds` is …
> [event-hubs] fixes issue where processEvents ignores maxWaitTime after retryable disconnect event

- sdk/identity/identity/README.md
This should align the README with other languages.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/10945
> [Identity] Readme updates

- sdk/cdn/arm-cdn/package.json
- sdk/cdn/arm-cdn/src/cdnManagementClientContext.ts
- sdk/cdn/arm-cdn/src/operations/customDomains.ts
As issue #11567 says, there is an issue with enabling HTTPS for custom domains in the CDN. This is caused by the API requiring a customDomainHttpsParameters parameter. However, in the current version, this property is optional, causing problems.
This PR adds a hopefully reasonable default value if the property has not been set. This should make it usable if left out, and make it backwards compatible to v4.2 where it worked without providing it.
> Added default customDomainHttpsParameters value

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/samples/javascript/iothubConnectionString.js
- sdk/eventhub/event-hubs/samples/javascript/receiveEvents.js
- sdk/eventhub/event-hubs/samples/typescript/src/iothubConnectionString.ts
- sdk/eventhub/event-hubs/samples/typescript/src/receiveEvents.ts
Noticed that the samples weren't compiling when running `npm run build:samples` so I fixed the issues.
Note that `https-proxy-agent` was made a devDependency in the root event-hubs package since the dev tool doesn't actually install sample dependencies.
/cc @HarshaNalluru
> [event-hubs] prepare 5.3.1 release

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/metricsadvisoradministrationclient_datafeed_datafeed/recording_creates_unknown_data_feed.json
- sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/metricsadvisoradministrationclient_datafeed_datafeed/recording_updates_data_feed_to_have_an_unknown_data_source_type.json
- sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/metricsadvisorclient/recording_lists_alerts_for_alert_configuration_by_page.json
- sdk/metricsadvisor/ai-metrics-advisor/recordings/node/metricsadvisoradministrationclient_datafeed_datafeed/recording_creates_unknown_data_feed.js
- sdk/metricsadvisor/ai-metrics-advisor/recordings/node/metricsadvisoradministrationclient_datafeed_datafeed/recording_updates_data_feed_to_have_a_different_data_source_type.js
- sdk/metricsadvisor/ai-metrics-advisor/recordings/node/metricsadvisoradministrationclient_datafeed_datafeed/recording_updates_data_feed_to_have_an_unknown_data_source_type.js
- sdk/metricsadvisor/ai-metrics-advisor/recordings/node/metricsadvisorclient/recording_lists_alerts_for_alert_configuration_by_page.js
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/incidentsAndAlerts.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/incidentsAndAlerts.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/advisorclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/transforms.spec.ts
- Error handling for listing new data feed source types -( porting changes from this PR -  https://github.com/Azure/azure-sdk-for-js/pull/12158/)
- Adding tests to test that error handling
- Added recordings for the tests
- Updated the samples where we missed previous renaming changes - https://github.com/Azure/azure-sdk-for-js/pull/12231
> Handle listing of new data feed source types

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/adminclient.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/transforms.spec.ts
to be consistent with JS libraries' convention.
> [MetricsAdvisor] rename createTime property to createdOn

- sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
- sdk/metricsadvisor/ai-metrics-advisor/README.md
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/dataFeed.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
- sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
- sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
and remove the wrapping `options`. We were putting into it all the
rest of optional settings that don't fit into any of groupings but
it's not necessary.
> [MetricsAdvisor] Flatten DataFeedOptions in data feed

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/serviceBusMessage.spec.ts
In #12216, we moved the code to settle a message and renew its lock from the ServiceBusMessageImpl to the ServiceBusReceiver. After this move, the only dependency left on the ConnectionContext in the ServiceBusMessageImpl is for the DataTransformer. This PR updates the ServiceBusMessage constructor to take the DataTransformer instead of the ConnectionContext and thus remove this dependency altogether. 
This closes #9944 as we no longer need to track the context or the receiver on the message.
This closes #10620 as well. Since the context is not being tracked on the message anymore, it does not matter that the data transformer is tracked on the context.
> [Service Bus] Remove Connection Context from ServiceBusMessage

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
- sdk/core/core-amqp/test/config.spec.ts
- sdk/core/core-http/CHANGELOG.md
- sdk/servicebus/service-bus/src/constructorHelpers.ts
- sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/8105 and https://github.com/Azure/azure-sdk-for-js/issues/11155
> [Core AMQP] Do not stringify entityPath for `undefined` 

- sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/constants.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/fabricMsi.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
This PR:
- Updates the versions used for Arc and Fabric.
- Throws if a ClientId is provided to Azure Arc. This is only on getToken and not on validation, as discussed in a recent meeting.
- Disables Fabric from the public list of available MSIs, since turns out that Service Fabric only provides self-signed certificates, which our core-https library does not yet support.
> [Identity] Cleanups after end-to-end testing and meetings

- sdk/communication/communication-chat/test/chatClient.spec.ts
Remove the validation from chat unit tests to avoid the unstable results caused by the delays
> Remove validation from chat list unit tests

- sdk/servicebus/service-bus/README.md
> [Service Bus] Mention "CORS not supported" in readme

- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/receivers/shared.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/util/errors.ts
- sdk/servicebus/service-bus/test/backupMessageSettlement.spec.ts
- sdk/servicebus/service-bus/test/batchReceiver.spec.ts
- sdk/servicebus/service-bus/test/deferredMessage.spec.ts
- sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
- sdk/servicebus/service-bus/test/renewLock.spec.ts
- sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
This PR updates the client side validation as per #12312 for settling messages and renewing locks.
Additionally, this PR 
- removes the `isSettled` on the message. This does not work for deferred messages today, and so would be misleading to users.
- throws the usual errors when trying to settle message or renew lock after the receiver or the client is closed
- removes the check on renewMessageLock for whether the message is already settled. We expect the service to throw appropriate error here
- split the checks on `ServiceBusReceivedMessage` vs `ServiceBusMessageImpl` based on which parts of the message is being used for the checks
> [Service Bus] Update client side validation for settling msg, renewing locks

- sdk/identity/identity/samples/ClientSideUserAuthentication.md
This PR adds samples about how to use the `InteractiveBrowserCredential` and the `DeviceCodeCredential`. This is based on .Net's [ClientSideUserAuthentication.md](https://github.com/Azure/azure-sdk-for-net/blob/feature/identity/140/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md).
This PR is intended to account for the following:
Fixes #11852
Closes #11861
Fixes #11851
Closes #11921
> [Identity] Client side authentication Markdown sample

- sdk/storage/storage-blob/README.md
- sdk/storage/storage-file-datalake/README.md
- sdk/storage/storage-file-share/README.md
- sdk/storage/storage-queue/README.md
Following the bundling guide: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob#special-bundling-notes-for-ie11, running
```bash
tsc --allowJS --target es5 bundled-output.js --outfile final-output.js
```
gave "Unused '@ts-expect-error' directive" error for this line https://github.com/Azure/azure-sdk-for-js/blob/f169ccaee02ff59d0a3589a677272d0732a59a0d/sdk/storage/storage-file-share/src/utils/utils.common.ts#L385
We added this note because the open telemetry library we depend on is not compliled for es5. So we have to recompile it.
But now the bundling seems to work without this step in IE11.
I don't know why we don't have this issue before. Probably not important anyway.
I think we can get rid of the exception note since the old issue is fixed in …
> [storage][doc] remove Special bundling notes for IE11

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
This PR is regarding the serialization/deserialization of int-double-number types in the applicationProps under correlation rule filter and the optimal way to support them in the SDK.
All numbers are treated as "int"
For serialization, numbers are treated as "double".
During deserialization, "int" and "double" are treated as numbers.(To allow interop)
Reference https://github.com/Azure/azure-sdk-for-js/issues/9850#issuecomment-713183518
> [Service Bus] ATOM API: Correlation Filter - `int` and `double` as values under properties

- sdk/servicebus/service-bus/src/sender.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/src/util/errors.ts
- sdk/servicebus/service-bus/test/internal/sender.spec.ts
This PR adds validation checks for when partitionKey and sessionId are set to different values. Closes #12312
> [Service Bus] Throw when partitionKey is not same as sessionId

- sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeBusinessCard.js
When we use very new ES features like Optional Chaining in TS samples, we (using the royal "we" here) have to be careful to make sure that they don't make it into the JavaScript samples, since they are not compatible with Node <14.0.0.
> [ai-form-recognizer] Remove optional chaining operators from JS samples

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/serviceBusError.ts
Fixes #12264 
The goal with this change is to prevent exposing the `AmqpError` type to end-users. To accomplish this, the `err` parameter passed to `isServiceBusError` has been changed to be `unknown`. This doesn't change how the type guard can be used (while it is now more permissive, the end result should be the same.)
I did not add an entry to the changelog for this change since it doesn't change how `isServiceBusError` works, it just allows anything to be passed to it now without a compilation error. If this is a notable change I can add it to the changelog.
> [service-bus] loosens parameter type in isServiceBusError type guard

- sdk/servicebus/service-bus/README.md
It looks like the README.md still had a reference to the
`createSessionReciver` function which was removed in a previous preview.
I removed the reference to this method as the next two paragraphs
describe the two ways to actually create the session.
> [service-bus] Small README.md update for sessions

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/createSpan.ts
- sdk/core/core-client/src/index.ts
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/test/createSpan.spec.ts
- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/src/coreHttp.ts
- sdk/core/core-http/src/createSpan.ts
- sdk/core/core-http/test/createSpan.spec.ts
Add helper to create a span using the global tracer. Many of our Track2 SDKs implement their own createSpan, this helper should remove the need to re-implement it for every SDK
> [core-http] Add createSpan helper

- sdk/communication/communication-administration/src/communicationIdentity/constants.ts
- sdk/communication/communication-administration/src/phoneNumber/constants.ts
- sdk/communication/communication-administration/test/phoneNumberAdministrationClient.mocked.spec.ts
- sdk/communication/communication-chat/src/constants.ts
- sdk/communication/communication-chat/test/chatClient.mocked.spec.ts
- sdk/communication/communication-chat/test/chatThreadClient.mocked.spec.ts
- sdk/communication/communication-sms/src/constants.ts
- sdk/communication/communication-sms/test/smsClient.mocked.spec.ts
We mistakingly used the service api version for constructing the SDK user agent string.
Following the pattern of other services and hard-coding the version string.
> [communication] Fix SDK_VERSION value

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/index.ts
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/test/internal/abortSignal.spec.ts
- sdk/servicebus/service-bus/test/internal/batchingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/messageSession.spec.ts
- sdk/servicebus/service-bus/test/internal/streamingReceiver.spec.ts
When working on #12223, we had a discussion on whether we need the type for ReceiveMode at all since it is also essentially a union of string literals. Having a dedicated type to it does not add any value. Previously, this was useful when ReceiveMode was an enum.
cc @bterlson
> [Service Bus] Remove ReceiveMode from public API surface

- sdk/servicebus/service-bus/README.md
- sdk/servicebus/service-bus/src/dataTransformer.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/sender.ts
- sdk/servicebus/service-bus/src/serviceBusError.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/src/servicebusSharedKeyCredential.ts
- sdk/servicebus/service-bus/src/util/errors.ts
- sdk/servicebus/service-bus/src/util/utils.ts
/cc @HarshaNalluru @richardpark-msft  @ramya-rao-a
> [service-bus] Documentation Review for version 7

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/samples/javascript/advanced/deferral.js
- sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
- sdk/servicebus/service-bus/samples/typescript/src/advanced/deferral.ts
- sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
- sdk/servicebus/service-bus/test/renewLock.spec.ts
- sdk/servicebus/service-bus/test/renewLockSessions.spec.ts
- sdk/servicebus/service-bus/test/sessionsTests.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
This PR renames the option `autoComplete` to `autoCompleteMessages` to provide clarity on its purpose
Closes #12536
cc @JoshLove-msft
> [Service Bus] autoComplete -> autoCompleteMessages

- common/config/rush/pnpm-lock.yaml
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-files-required.ts
- sdk/cosmosdb/cosmos/package.json
- sdk/keyvault/keyvault-common/.eslintrc.json
- sdk/keyvault/keyvault-common/package.json
These changes are necessary so `rush lint` can run error and warning free. Fixes https://github.com/Azure/azure-sdk-for-js/issues/11255.
> Fix rush lint

- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/scripts/Language-Settings.ps1
- eng/tools/analyze-deps/index.js
- eng/tools/dependency-testing/index.js
- eng/tools/generate-static-index/templates/matthews/styles/main.js
- eng/tools/versioning/increment.js
- eng/tools/versioning/set-version.js
- sdk/template/template/CHANGELOG.md
- sdk/template/template/package.json
Support packages in both azure and microsoft scope and allow packages with "azure-" inside pacakge name. for e.g. openetelemetry-azure-monitor"
> Handle packages in Microsoft scopeto support renaming of opentelemetry

- eng/pipelines/templates/steps/test.yml
- eng/tools/rush-runner.js
Currently we build all projects in repo to include transitive dependency which is required to test packages. Currently rush doesn't build transitive dependency even when we pass --from <package-name> flag. This change will build all packages that are required for testing.
> Build transitive dependent packages

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/sender.ts
- sdk/servicebus/service-bus/src/serviceBusError.ts
- sdk/servicebus/service-bus/test/internal/linkentity.unittest.spec.ts
- sdk/servicebus/service-bus/test/internal/shared.spec.ts
- sdk/servicebus/service-bus/test/sendBatch.spec.ts
- sdk/servicebus/service-bus/test/serviceBusError.spec.ts
Fixes #12559 and #12573 
This change updates `ServiceBusError` in 2 ways.
1. Adds a constructor that accepts `message` and `code` directly. This lets us throw `ServiceBusError`s from the client without having to first create a `MessagingError`.
2. Update the constructor so that if a MessagingError's code is translated to `GeneralError`, the MessagingError's code is prefixed in the ServiceBusError message. This should provide additional context to the user on what went wrong.
> [service-bus] Remove public usages of MessagingError and improve ServiceBusError GeneralError messages

- eng/tools/dependency-testing/index.js
Package name is passed as artifact name when running min max testing as part of integration test and this causes an issue when it is converted to package name. This issue was hidden earlier due to hardcoded replace of "azure-" in parameter value which it will never find if package name itself is passed. We have removed this hardcoding to support different scope like @microsoft using regex and this new logic has surfaced incorrect replace issue. Change in this PR is to convert input value only if it's not package name.
> Convert artifact name to package name only if required

- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/test/internal/streamingReceiver.spec.ts
Fixes #12260 
The code that's removed is no longer necessary since the `retry` method is being called in a loop and the loop only calls the user's processError handler after the retries in a single `retry` call are exhausted.
> [service-bus] remove unnecessary wrapper in streaming receiver

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/pipelines/templates/steps/build.yml
- eng/scripts/Language-Settings.ps1
- eng/scripts/SetTestPipelineVersion.ps1
- Move `UpdateParamsJsonJS` from `https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/update-docs-ci.ps1` to LanguageSettings.ps1.
- Rename function to `Update-javascript-CIConfig`
- Add default `$monikerId=$null` argument to help function reuse across the languages.
- Switch from `BuildNumber` to `BuildID` for test release version.
> Updates to Language Settings file

- common/tools/eslint-plugin-azure-sdk/docs/rules/ts-versioning-semver.md
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-versioning-semver.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-versioning-semver.ts
Service Bus is out of preview so AFAICT, no other package uses the old versioning scheme. Fixes https://github.com/Azure/azure-sdk-for-js/issues/10987.
PR passes tests and linting locally. @praveenkuttappan please consider setting up a CI pipeline for the plugin.
> [ESLint plugin] Deprecate support for preview and dev versions

- .github/CODEOWNERS
Since @jonathandturner is going to be shepherding Synapse packages for us, making him the code owner of this folder.
> [synapse] Add Jonathan as code owner

- common/tools/eslint-plugin-azure-sdk/docs/rules/ts-versioning-semver.md
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-versioning-semver.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-versioning-semver.ts
Reverts Azure/azure-sdk-for-js#12606
#12606 caused failures in master because there are still a few packages using the old versioning scheme.
> Revert "[ESLint plugin] Deprecate support for preview and dev versions"

- sdk/core/ci.yml
The `core` pipeline should run on any changes under `common`, with the exception of `common/smoke-test` which has it's own pipeline and should not be able to break the `core` build.
> Add common to core ci.yml

- sdk/servicebus/service-bus/src/models.ts
- sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
- `Create{Entity}Options.lockduration` clarification
- `onMessage` is only applicable for subscribe
> [Service Bus] Improve docs

- sdk/tables/data-tables/CHANGELOG.md
- sdk/tables/data-tables/recordings/browsers/tableclient_createentity_getentity_and_delete/recording_should_createentity_with_date.json
- sdk/tables/data-tables/recordings/browsers/tableclient_createentity_getentity_and_delete/recording_should_createentity_with_datetime.json
- sdk/tables/data-tables/recordings/node/tableclient_createentity_getentity_and_delete/recording_should_createentity_with_date.js
- sdk/tables/data-tables/recordings/node/tableclient_createentity_getentity_and_delete/recording_should_createentity_with_datetime.js
- sdk/tables/data-tables/review/data-tables.api.md
- sdk/tables/data-tables/src/models.ts
- sdk/tables/data-tables/src/serialization.ts
- sdk/tables/data-tables/test/integration/tableclient.spec.ts
- sdk/tables/data-tables/test/unit/serialization.spec.ts
Fixes #12646
Tables service supports ns precision DateTime however JavaScript doesn't. As part of entity deserialization, whenever we get a property with type Edm.DateTime we parse it into a JavaScript Date object, which can lead to losing precision.
To fix this we need to disable the default deserialization for Edm.DateTime and give the user an "edm" object, similar to what we do for Guid and Int64
```typescript
{
partitionKey: "p1",
rowKey: "r1",
blahblah: {type: "DateTime", value:"the date"}
}
```
> [Tables] Don't deserialize DateTime to avoid losing precision

- sdk/formrecognizer/ai-form-recognizer/README.md
This is something that the docs build found. I patched it there  so that the broken link won't go live, but also have to make the same change in the repo for the future.
> [ai-form-recognizer] Fixed a broken link in the README.

- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-admin/rollup.config.js
- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-certificates/rollup.config.js
- sdk/keyvault/keyvault-common/package.json
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-keys/rollup.config.js
- sdk/keyvault/keyvault-secrets/package.json
- sdk/keyvault/keyvault-secrets/rollup.config.js
Fixes #12224
These changes effectively exclude the dist-browser folder from our artifacts. Is this all that is needed?
Since we still run browser tests, I'm thinking I should not actively remove every other use case of dist-browser (like in rollups)
> [Key Vault] Excluding dist-browser from the artifacts

- sdk/core/core-amqp/src/retry.ts
- Add the operationType format specifier for debug logs
The mismatch between the number of format specifiers and the variables
passed in causes `NaN` to show up in the debug output. 
Before: 
```
azure:core-amqp:verbose [connection-1] Attempt number: NaN 1
...
azure:core-amqp:verbose [connection-1] Success for 'sendMessage', after attempt number: 1.
```
After:
```
azure:core-amqp:verbose [connection-1] Attempt number for 'sendMessage': 1.
...
azure:core-amqp:verbose [connection-1] Success for 'sendMessage', after attempt number: 1.
```
Fixes #11798
> [Core AMQP] - Fix debug log output for Retries

- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-tracing/package.json
Updating the version to use `beta` instead of `preview` following our [new semver policy](https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#package-versioning).
> [core-tracing] beta version

- sdk/textanalytics/ai-text-analytics/package.json
This apparently is needed for node8 tests to succeed in https://github.com/Azure/azure-sdk-for-js/pull/12713/.
> [Text Analytics] adding @azure/core-asynciterator-polyfill as a dep

- sdk/core/core-http/package.json
- sdk/core/core-http/src/fetchHttpClient.ts
- sdk/core/core-http/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-http/src/policies/proxyPolicy.ts
- sdk/core/core-http/src/util/serializer.common.ts
- sdk/core/core-http/src/xhrHttpClient.ts
- sdk/core/core-http/test/mockHttp.ts
- sdk/core/core-http/test/policies/proxyPolicyTests.node.ts
- sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
- Enable "no-prototype-builtins" and fix the errors
- Fix any errors found in core-http lint report
- Fail on lint errors
- Fixing the no-prototype rule was punted to a future commit to limit scope
- In passing, I noticed other errors in the lint report
- When all were fixed, I figured it would be helpful to fail with an error so the user can tell where to find the lint report. Otherwise I had to figure out why the lint errors weren't showing up like they do in other projects
Fixes #8972
> [core-http] enable no-prototype-builtins

- sdk/servicebus/service-bus/README.md
* Add docs links for the settlement methods
* Change our api ref to point to docs.microsoft.com now, rather than the blob generated ref docs.
> [service-bus] Readme updates for dead letter queues, point to proper docs

- sdk/textanalytics/ai-text-analytics/src/index.ts
I forgot to do so in https://github.com/Azure/azure-sdk-for-js/pull/12725. Thanks to @jonathandturner for catching this.
> [Text Analytics] Import async iterator polyfill

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/src/retry.ts
- sdk/core/core-amqp/test/retry.spec.ts
Fixes #12610 
This change is pretty straightforward.
If the operation passed to `retry` fails with a `retryable` error __and__ the maximum number of retries allowed has not been reached, `retry` should 'sleep' between operation attempts.
If the operation passed to `retry` fails with a `retryable` error `retry` adds a 'sleep'.
This means that even if the final 'attempt' results in a retryable error being thrown, `retry` still sleeps before yielding the error to the calling code.
Matches the expected `retry` behavior. There is a 'sleep` only _between_ operation attempts, but not after all attempts have been exhausted.
>  [core-amqp] bugfix: updates retry function to return immediately once attempts are exhausted

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-http/package.json
- sdk/core/core-http/review/core-http.api.md
- sdk/core/core-http/rollup.base.config.js
- sdk/core/core-http/src/serviceClient.ts
- sdk/core/core-http/src/url.ts
- sdk/core/core-http/src/util/url.browser.ts
- sdk/core/core-http/src/util/url.ts
- sdk/core/core-http/test/serviceClientTests.ts
Currently, there is no way to specify a custom scope to build the BearerTokenAuthenticationPolicy. So far `core-http` has been using the baseUri to build this scope. This generally works well for management plane libraries. However there are other scenarios where we may need to set a custom scope value, for example Synapse.
This PR introduces a new optional property to `ServiceClientOptions` called `authScope` which if present we'll use it as is for the scope, otherwise we fall back to the current behavior.
> [core-http] Support custom auth scopes

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/src/eventData.ts
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/util/constants.ts
Partly addresses #12701 by recommending setting `EventData.body` to a `Buffer` when the user needs cross-language compatibility between sending and receiving events.
The `@azure/event-hubs` producer will do one of two things to the body depending on the body's type:
- If the body is a buffer, it will send it as is.
- If the body is not a buffer, it will JSON.stringify it before sending the message. When receiving the message using the SDK, the body will be parsed using JSON.parse.
When sending events with this SDK and receiving events using a different solution, we see that the event body is parsed differently. In this type of scenario, event bodies should be sent as Buffers since these will be sent as is rather than have any transformations (in our case, JSON encoding) performed on them.
> [event-hubs][service-bus] updates (EventData|ServiceBusMessage).body documentation

- eng/tools/versioning/increment.js
- eng/tools/versioning/set-version.js
Packagename variable is not declared. This was broken after making changes to support monitor package. Updated to refer package name from package.json instead of package name variable.
> Fix undeclared var issue in versioning tool

- sdk/core/ci.yml
- Continuation of #12636
When I updated core `ci.yml` in #12636, I updated the `pr` section but forgot to update the `trigger` section with the same changes.  In general, both `trigger` and `pr` should use the same path filters.
> Align "trigger" with "pr" in core ci.yml

- common/tools/dev-tool/package.json
- common/tools/eslint-plugin-azure-sdk/package.json
- sdk/core/abort-controller/package.json
- sdk/core/core-asynciterator-polyfill/package.json
- sdk/core/core-http/package.json
- sdk/core/core-paging/package.json
- sdk/core/logger/package.json
- sdk/eventhub/testhub/package.json
- sdk/monitor/opentelemetry-exporter-azure-monitor/package.json
- sdk/test-utils/perfstress/package.json
This PR adds `"echo Skipped."` script placeholders for `build:samples` commands in all packages where they are missing. It will almost always be the case that packages should have a `build:samples` command, so in my opinion using `echo Skipped.` as a placeholder where it is not required is preferable to making this command optional in the rush configuration.
> Add empty build:samples scripts to all packages missing them.

- sdk/anomalydetector/ai-anomaly-detector/samples/typescript/src/sample_detect_change_point.ts
- sdk/anomalydetector/ai-anomaly-detector/samples/typescript/src/sample_detect_entire_series_anomaly.ts
- sdk/anomalydetector/ai-anomaly-detector/samples/typescript/src/sample_detect_last_point_anomaly.ts
- sdk/core/core-lro/samples/typescript/samplesClient.ts
- sdk/eventgrid/eventgrid/samples/typescript/src/sendCloudEvent.ts
- sdk/eventgrid/eventgrid/samples/typescript/src/sendEventGridEvent.ts
- sdk/eventhub/event-processor-host/samples/iothubEph.ts
- sdk/eventhub/event-processor-host/samples/multiEph.ts
- sdk/eventhub/event-processor-host/samples/sendBatch.ts
- sdk/eventhub/event-processor-host/samples/singleEph.ts
- sdk/eventhub/event-processor-host/samples/websockets.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/samples/typescript/src/receiveEventsUsingCheckpointStore.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/samples/typescript/src/receiveEventsWithApiSpecificStorage.ts
- sdk/tables/data-tables/samples/typescript/src/authenticationMethods.ts
- sdk/tables/data-tables/samples/typescript/src/createAndDeleteEntities.ts
- sdk/tables/data-tables/samples/typescript/src/createAndDeleteTable.ts
- sdk/tables/data-tables/samples/typescript/src/queryEntities.ts
- sdk/tables/data-tables/samples/typescript/src/queryTables.ts
- sdk/tables/data-tables/samples/typescript/src/updateAndUpsertEntities.ts
TypeScript samples always need to `export` their main function so that it can be used in the sample harness, which will import and run the `main` function. This PR adds it in the few places it was missing.
The commit formatting hook also ran, changing the appearance of a few lines in the same files.
> Add export to sample main functions where missing

- sdk/identity/identity/rollup.base.config.js
- sdk/identity/identity/test/internal/identityClient.spec.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
- sdk/identity/identity/test/public/node/authorizationCodeCredential.spec.ts
- sdk/identity/identity/test/public/node/azureCliCredential.spec.ts
- sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts
- sdk/identity/identity/test/public/node/environmentCredential.spec.ts
Got some good feedback after #10337 was approved and merged.
I had a first approach here: https://github.com/Azure/azure-sdk-for-js/pull/10968
But I'm closing this since master has changed considerably since I made that PR.
This PR includes:
- Browser tests now run internal and public tests. For tests that could only run in one environment, I'm following Will's guidelines and moving them into a sub-folder called either "node" or "browser" (so, for example: "public/node/test.spec.ts").
- Combined multiple imports from `../../src`, from feedback: https://github.com/Azure/azure-sdk-for-js/pull/10337#discussion_r481345299 (Note that I couldn't find other tests with separate multiple imports from the same file).
The rest of the original feedback is no longer applicable.
In any case, more …
> [Identity] Feedback after #10337 (2)

- sdk/core/core-http/CHANGELOG.md
Updating the changelog for the December release with 2 changes going into the next release:
- Support custom auth scopes [PR 12752](https://github.com/Azure/azure-sdk-for-js/pull/12752)
- Add helper function `createSpan` to help in the creation of tracing spans in Track2 libraries [PR 12525](https://github.com/Azure/azure-sdk-for-js/pull/12525)
> [core-http] Update changelog for December release

- eng/tools/rush-runner.js
This PR extends the `rush-runner` to add a pattern for handling `build` subcommands, specifically `build:samples`.
It also seemed like the pattern of
```typescript
params = flatMap(packages, (p) => [.., p]);
spawnNode(...);
```
was repeated too frequently, so I abstracted it into a small helper function.
> Added build:samples support to rush-runner.js

- sdk/monitor/opentelemetry-exporter-azure-monitor/src/utils/connectionStringParser.ts
Since this package got ported to the repo, it's had a small bug where we'd always log about the connection string being invalid. This PR adjusts the code slightly to only log when there is an invalid connection string.
> [Monitor] Fix incorrect log message when connection string is valid

- sdk/synapse/synapse-spark/README.md
Looks like the sample in the README for Spark was missing an example. Adding one.
> [Synapse] Add back missing Spark example

- sdk/attestation/attestation/sample.env
This file can serve as a guideline for attestation developers on how to configure various environment variables. Simply copy the `sample.env` file into `.env` file with the configurations you want.
> [Attestation] Adding sample.env

- sdk/communication/communication-administration/CHANGELOG.md
- sdk/communication/communication-administration/src/phoneNumber/phoneNumberAdministrationClient.ts
- sdk/communication/communication-administration/test/lro.purchase.spec.ts
- sdk/communication/communication-administration/test/lro.release.spec.ts
- sdk/communication/communication-administration/test/lro.reserve.spec.ts
- sdk/communication/communication-administration/test/utils/recordedClient.ts
We had ignored the `pollInterval` and `resumeFrom` options by accident. Now passing them correctly, and setting pollInterval to 0 in test playback mode.
This brings down our playback LRO tests from ~20sec to 200ms and unblocks #12770
> [communication-administration] fix option passing for LROs and slow playback tests

- sdk/synapse/synapse-access-control/package.json
- sdk/synapse/synapse-artifacts/package.json
- sdk/synapse/synapse-managed-private-endpoints/package.json
- sdk/synapse/synapse-monitoring/package.json
- sdk/synapse/synapse-spark/package.json
Being able to use `rush clean` is blocked on these commands being defined.
> [synapse] Added 'clean' commands.

- sdk/servicebus/service-bus/migrationguide.md
- sdk/servicebus/service-bus/samples/javascript/advanced/deferral.js
- sdk/servicebus/service-bus/samples/javascript/advanced/movingMessagesToDLQ.js
- sdk/servicebus/service-bus/samples/javascript/advanced/sessionState.js
- sdk/servicebus/service-bus/samples/javascript/session.js
- sdk/servicebus/service-bus/samples/typescript/src/advanced/deferral.ts
- sdk/servicebus/service-bus/samples/typescript/src/advanced/movingMessagesToDLQ.ts
- sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionState.ts
- sdk/servicebus/service-bus/samples/typescript/src/session.ts
> [service-bus] Addressing some incorrect samples and missing migrationguide.md section

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
When we went down the 'drain' path with BatchingReceiver we'd actually remove the event listeners. 
With the old code this could happen:
1. message received, debounce timer set
2. debounce timer fires
3. drain is requested (also removed the event listeners!)
4. message arrives (ignored)
5. receiver_drain arrives and resolve's the promise but the message in step 4 is lost.
The simplest way to reproduce this was to just connect over a slower link (created an SB in AU, which is slower than connecting over to something in the US) and send some about 100 messages (I used 2k-ish of text for each one) - this made it more likely that you'd end up with only a partial transfer of messages and have a drain. This became even more obvious once we moved to scheduling the promise resolution with …
> [service-bus] batching receiver was removing event listeners too early

- sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
- sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
The API reference docs for [EventHubConsumerClient ](https://docs.microsoft.com/en-us/javascript/api/%40azure/event-hubs/eventhubconsumerclient?view=azure-node-latest)and [EventHubProducerClient ](https://docs.microsoft.com/en-us/javascript/api/%40azure/event-hubs/eventhubproducerclient?view=azure-node-latest)dont show the description we have in the source code for their constructors. My guess is that the `@constructor` tag causes the doc generating tool (typedoc v0.15.0) to ignore what comes next. It does so for tags like `@member` as well. While #12912 takes us closer to a long term fix, this PR does a quick fix for now
Found during https://github.com/azure/azure-sdk-for-js/issues/12374 by @richardpark-msft
> [Event Hubs] Remove @constructor tags

- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/test/internal/session.spec.ts
- sdk/cosmosdb/cosmos/test/internal/unit/hashing/v1.spec.ts
- sdk/cosmosdb/cosmos/test/internal/unit/hashing/v2.spec.ts
- sdk/cosmosdb/cosmos/test/internal/unit/platform.spec.ts
- sdk/cosmosdb/cosmos/test/public/integration/aggregates/groupBy.spec.ts
- I noticed that the cosmos tests are not actually running any test files after the previous PR merge - https://github.com/Azure/azure-sdk-for-js/pull/12764
- Since the folder structure for tests have been altered, we need to update the test scripts with the correct paths to test files
> [cosmos] modify package.json with the test scripts

- sdk/synapse/synapse-access-control/package.json
- sdk/synapse/synapse-artifacts/package.json
- sdk/synapse/synapse-managed-private-endpoints/package.json
- sdk/synapse/synapse-monitoring/package.json
- sdk/synapse/synapse-spark/package.json
Two `clean` commands were added by two different PRs https://github.com/Azure/azure-sdk-for-js/pull/12870 and https://github.com/Azure/azure-sdk-for-js/pull/12770. This PR removes the addition done by the former.
> [Synapse] Remove duplicate clean command

- sdk/identity/identity/test/manual/README.md
- sdk/identity/identity/test/manual/package.json
- sdk/identity/identity/test/manual/src/index.tsx
This PR upgrades the manual test in the Identity package (located in `test/manual`) to use the latest available API. This PR also provides further details on how to configure the resources and run this test.
Fixes #9404
> [Identity] Manual test fix

- sdk/core/abort-controller/src/AbortSignal.ts
- sdk/core/core-http/src/credentials/accessTokenRefresher.ts
- sdk/core/core-http/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-http/src/policies/ndJsonPolicy.ts
- sdk/core/core-http/test/data/TestClient/src/testClient.ts
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/linkEntity.ts
- sdk/eventhub/event-hubs/src/managementClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
- sdk/keyvault/keyvault-certificates/src/utils.ts
- sdk/keyvault/keyvault-keys/src/localCryptography/algorithms.ts
- sdk/servicebus/service-bus/src/util/crypto.browser.ts
- sdk/servicebus/service-bus/src/util/parseUrl.browser.ts
- sdk/servicebus/service-bus/src/util/parseUrl.ts
- sdk/storage/storage-blob/src/policies/StorageRetryPolicy.ts
- sdk/storage/storage-file-datalake/src/policies/StorageRetryPolicy.ts
- sdk/storage/storage-file-share/src/ShareSASPermissions.ts
- sdk/storage/storage-file-share/src/policies/StorageRetryPolicy.ts
- sdk/tables/data-tables/src/TableBatch.ts
- sdk/tables/data-tables/src/TablesSharedKeyCredential.browser.ts
- sdk/tables/data-tables/src/TablesSharedKeyCredential.ts
- sdk/tables/data-tables/src/TablesSharedKeyCredentialPolicy.ts
- sdk/tables/data-tables/src/utils/connectionString.ts
- sdk/test-utils/recorder/src/baseRecorder.ts
- sdk/test-utils/recorder/src/basekarma.conf.ts
- sdk/test-utils/recorder/src/utils/index.ts
Address feedback for https://github.com/Azure/azure-sdk-for-js/pull/12912.
> Remove @param and @returns tags if they have no description

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/ConnectionContextBase.ts
- sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
- sdk/core/core-amqp/test/context.spec.ts
- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/review/event-hubs.api.md
- sdk/eventhub/event-hubs/rollup.base.config.js
- sdk/eventhub/event-hubs/src/connectionContext.ts
- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/src/models/public.ts
- sdk/eventhub/event-hubs/src/util/constants.ts
- sdk/eventhub/event-hubs/src/util/parseEndpoint.ts
- sdk/eventhub/event-hubs/src/util/url.browser.ts
- sdk/eventhub/event-hubs/src/util/url.ts
- sdk/eventhub/event-hubs/test/client.spec.ts
- sdk/eventhub/event-hubs/test/config.spec.ts
- sdk/eventhub/event-hubs/test/impl/parseEndpoint.spec.ts
- sdk/servicebus/service-bus/package.json
Fixes #12901 
Some users run their applications in a private network that lacks access to public endpoints, such as <namespace>.servicebus.windows.net. Due to these restrictions, these applications are unable to create direct connections to the Azure Event Hubs service using the standard endpoint address and require the ability to specify a custom host name to ensure they route through the proper intermediary for the connection to be made.
I've added tests that verify the connection has been configured with the custom endpoint correctly.
I also manually ran these changes by setting up an Application Gateway in Azure with:
- backend pool with a backend target that points to the FQDN of my Event Hubs Namespace (`<namespace>.servicebus.windows.net`)
- A front-end listener using a HTTPS and a …
> [core-amqp][event-hubs] support specifying a custom endpoint

- sdk/keyvault/keyvault-keys/samples/javascript/README.md
- sdk/keyvault/keyvault-keys/samples/typescript/README.md
- sdk/keyvault/keyvault-secrets/samples/javascript/README.md
- sdk/keyvault/keyvault-secrets/samples/typescript/README.md
* deploy buttons were referring to 'tests-resources.json' rather than 'test-resources.json' (ie, no 's')
* prettier auto-lowercased the purgeAllKeys ref in the md. Cosmetic and harmless.
> [keyvault] MQ docs: minor fixes to the readmes for samples

- sdk/servicebus/service-bus/src/util/utils.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
- sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
Moved the @azure/service-bus library over to the isNode check defined in @azure/core-http to fix an invalid check for Node.
fixes: #12983
> [@azure/service-bus] Fix invalid check for Node

- sdk/servicebus/service-bus/CHANGELOG.md
This PR adds changelog entry for https://github.com/Azure/azure-sdk-for-js/issues/12983
> [Service Bus] Update changelog for 7.0.1

- sdk/keyvault/keyvault-certificates/migration-guide.md
- sdk/keyvault/keyvault-keys/migration-guide.md
- sdk/keyvault/keyvault-secrets/migration-guide.md
This PR updates the migration guides for Key Vault to use npm link instead of github as the latter can point to previews if we were working on previews in the master branch
> Use npm link instead of github for readme

- sdk/textanalytics/ai-text-analytics/package.json
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
- sdk/textanalytics/ai-text-analytics/test/public/pipelineOptions.spec.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
- sdk/textanalytics/ai-text-analytics/test/utils/env.browser.ts
- sdk/textanalytics/ai-text-analytics/test/utils/env.ts
- sdk/textanalytics/ai-text-analytics/test/utils/recordedClient.ts
Use the API Key from the corresponding environment var only after it was read by the recorder. 
Also does the following:
- split `createRecordedClient` into `createRecorder` and `createClient` with better arguments.
- get rid of `testEnv`.
- use `createClient` everywhere.
Fixes #12990 and part of https://github.com/Azure/azure-sdk-for-js/issues/12819.
> [Text Analytics] Tests read env vars only after they were read by the recorder

- sdk/servicebus/service-bus/migrationguide.md
This PR updates the Service Bus migration guide to follow the [template](https://github.com/Azure/azure-sdk/pull/2132) to fix #12366
> [Service Bus] Update migration guide to follow template

- sdk/keyvault/README.md
The service level readme is meant to show all packages available for customers to use for the said service. In case of Key Vault, we do mention the admin package, but do not call out that it is in preview. This PR adds that information
> Callout that the admin package is still in preview

- sdk/test-utils/perfstress/src/index.ts
- sdk/test-utils/perfstress/src/utils.ts
This address the comment at https://github.com/Azure/azure-sdk-for-js/pull/12746#discussion_r546922303 by adding a new `readStream` method in perf framework so that it could be reused.
Inspired from https://github.com/Azure/azure-sdk-for-js/blob/ee733377bd63a7aba6e80b5cc0d895a251cb70e1/sdk/storage/storage-blob/src/utils/utils.node.ts#L118
This new method is meant to be used by the perf tests in various storage packages(in various different versions).
https://github.com/Azure/azure-sdk-for-js/pull/12737 https://github.com/Azure/azure-sdk-for-js/pull/12746 https://github.com/Azure/azure-sdk-for-js/pull/12806
> [Perf Tests] streamToBuffer helper method

- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
- sdk/textanalytics/test-resources.json
Diagnosing why the endpoint has double dots (`https://textanalytics-tebb4f92e457542af..cognitiveservices.azure.com/`) in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=664806&view=logs&j=34d05327-3286-5fd0-44d3-76aebff5d924&t=69f66ec9-cb96-5533-f751-56577de2d134.
EDIT:
According to @danieljurek, we're overriding that default value with a "subscription configuration" secret that's handed to the ARM template. The "subscription configuration" is written as: `"cognitiveServicesEndpointSuffix": ".cognitiveservices.azure.com"`. So with the current way the ARM template is generating URLs you'll get your 2 dots in the URL and that's an error.
> [Text Analytics] Diagnose issue with test resources

- .github/CODEOWNERS
Just discussed this with @xirzec. Should give me better visibility since I'll be working on those projects.
> Add richardpark-msft as CODEOWNER for monitor and core-tracing

- sdk/appconfiguration/app-configuration/src/appConfigCredential.ts
- sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
- sdk/appconfiguration/app-configuration/src/internal/cryptoHelpers.browser.ts
- sdk/appconfiguration/app-configuration/src/internal/cryptoHelpers.ts
- sdk/appconfiguration/app-configuration/src/internal/helpers.ts
- sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts
- sdk/appconfiguration/app-configuration/src/internal/tracingHelpers.ts
- sdk/appconfiguration/app-configuration/src/models.ts
- sdk/appconfiguration/app-configuration/src/policies/throttlingRetryPolicy.ts
- sdk/appconfiguration/app-configuration/test/internal/helpers.spec.ts
- sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
- sdk/appconfiguration/app-configuration/test/internal/package.spec.ts
- sdk/appconfiguration/app-configuration/test/internal/throttlingRetryPolicyTests.spec.ts
- sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
- sdk/appconfiguration/app-configuration/test/public/index.readonlytests.spec.ts
- sdk/appconfiguration/app-configuration/test/public/index.spec.ts
- sdk/appconfiguration/app-configuration/test/public/throwOrNotThrow.spec.ts
- sdk/appconfiguration/app-configuration/tsdoc.json
- Make eslint run clean for typedoc (still has other warnings/errors that I need to get back to)
- Ran eslint auto fix, which got some simple stuff like being able to use 'const' and the copyright header.
Fixes #12948
> [app-configuration] Fixing some lint issues

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/package.json
- sdk/core/core-auth/review/core-auth.api.md
- sdk/core/core-auth/src/index.ts
- sdk/core/core-auth/src/tokenCredential.ts
- sdk/core/core-auth/src/tracing.ts
Fixes #12612.
This PR removes the `@azure/core-tracing` and `@opentelemetry/api` dependencies from `@azure/core-auth`. Instead, `SpanOptions` and `SpanContext` are duplicated and exported from `@azure/core-auth`.
This will allow our older code generation to use `@azure/core-auth` without requiring the `@azure/core-tracing` dependency.
> [core-auth] remove core-tracing dependency

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/test/internal/batchingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/tracing.spec.ts
@HarshaNalluru noted some more cases where we needed to cleanup our event listeners for receiving messages, etc... on the receiver used by the BatchingReceiver.
This PR now sweeps up all the cases by just simply admitting that this clean up check has to happen in all the resolve/reject cases. So I just wrap those functions and now we don't have to worry about it anymore.
Fixes #12922
> [service-bus] Making BatchingReceiver properly cleanup after an abort

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
- sdk/servicebus/service-bus/src/util/utils.ts
- sdk/servicebus/service-bus/test/atomManagement.spec.ts
- sdk/servicebus/service-bus/test/atomRuleFilters.spec.ts
- sdk/servicebus/service-bus/test/internal/atomXml.spec.ts
- sdk/servicebus/service-bus/test/utils/testutils2.ts
https://github.com/Azure/azure-sdk-for-js/issues/13063
The correlation filter with the "subject" set using the `createRule` method doesn't filter the messages to the subscription. However, when we create the rule with the same correlation filter from the service bus explorer, messages get filtered as expected.
The key-value pairs having undefined/null as the values can be present in the request object at any level. They get serialized as empty tags in the XML request for the ATOM management operations.
If such empty tags are present at the top level, the service throws a "Bad Request" error. This was handled by the SDK to make sure that the top-level of the request body doesn't have any empty tags.
If such empty tags are present at the inner levels, the service assigns the empty strings …
> [Service Bus] Bug Fix: Correlation Rule Filter with the "label" doesn't filter the messages

- sdk/monitor/opentelemetry-exporter-azure-monitor/CHANGELOG.md
- sdk/monitor/opentelemetry-exporter-azure-monitor/src/export/trace.ts
- sdk/monitor/opentelemetry-exporter-azure-monitor/test/unit/export/trace.test.ts
Fixes #12904
Python exporter currently retry when there is any exception with HTTP call
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/export/_base.py#L134
Same behavior is in ApplicationInsights Node.js SDK
https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Sender.ts#L164
> OT Exporter retry when there are network issues

- sdk/eventhub/event-processor-host/package.json
/cc @richardpark-msft 
Disables EPH samples from running as part of the automated smoke test runs. EPH functionality has been replaced by the `@azure/event-hubs` v5 package.
> [eph] Skip EPH samples from smoke-test runs

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/abort-controller/package.json
- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/package.json
- sdk/core/core-lro/CHANGELOG.md
- sdk/core/logger/CHANGELOG.md
Same as #12797 except in January!
Note that all of the core packages are just being released so that the published version pulls in tslib 2.x instead of tslib 1.x. This fixes #12631, where it was discovered that using a bundler (e.g. webpack) to generate an application bundle that includes our SDK also pulled in multiple copies of tslib 1.x.
Multiple copies of tslib were pulled in because due to the way node_modules were being resolved, tslib 2.x would be at the root of a package's node_modules directory, and every package that used tslib 1.x had its own copy of tslib that would then be included in the bundle.
> [core] prepare for January 2021 release

- sdk/search/search-documents/package.json
This is to treat any new lint regression as hard failure in CI.
> Treat any new lint regression as hard failure in CI

- sdk/identity/identity/README.md
It is not practical to maintain an entire set of packages that take TokenCredential. Therefore, removing the corresponding section from the readme for `@azure/identity`
> Remove outdated list of packages that support identity package

- sdk/servicebus/service-bus/test/atomRuleFilters.spec.ts
https://github.com/Azure/azure-sdk-for-js/pull/13105 investigates the flakyness.
The reason why the message count in the test can sometimes(5/1000 times) be zero is that the sent messages might not have been filtered into the subscription by the time we call the runtime properties method.
If we call the receiveMessages directly, the inherent delay would help in receiving the messages and should be enough for the test.
> [Service Bus] Remove message count check - flaky rule filter test

- sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_job_metadata.json
- sdk/textanalytics/ai-text-analytics/recordings/browsers/api_key_textanalyticsclient_lros_health/recording_job_metadata.json
- sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_job_metadata.js
- sdk/textanalytics/ai-text-analytics/recordings/node/api_key_textanalyticsclient_lros_health/recording_job_metadata.js
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyze.ts
- sdk/textanalytics/ai-text-analytics/src/analyzeResult.ts
- sdk/textanalytics/ai-text-analytics/src/healthResult.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/poller.ts
- sdk/textanalytics/ai-text-analytics/src/lro/health/operation.ts
- sdk/textanalytics/ai-text-analytics/src/lro/health/poller.ts
- sdk/textanalytics/ai-text-analytics/src/lro/poller.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
The first step to have a proper design for API v3.1-preview.3:
- replaces the redundant `BeginAnalyzeOperationState` with `BeginAnalyzePollState`
- replaces the redundant `BeginAnalyzeHealthcareOperationState` with `BeginAnalyzeHealthcarePollState`
- adds job's meta data to LRO's poller state
- adds an option to `beginAnalyze` for setting the job's display name
- adds a couple of unit tests for the additional stuff in the poller state
> [Text Analytics] [3.1-preview.3 design] Exposing job's metadata as part of the poller state for LROs

- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/src/keysModels.ts
- sdk/keyvault/keyvault-keys/test/internal/serviceVersionParameter.spec.ts
The PR https://github.com/Azure/azure-sdk-for-js/pull/13092 was merged on January 7, 2021. That PR was to migrate Keyvault Keys Package from Old SDK generator to New V6 Code Generator.
As a part of this task, I have exposed KnownApiVersions and ApiVersion properties. Per the SDK, if you look at the definition the KnownApiVersions has only one value (7.2-preview). Though you can pass any value (because it is a string property), it is confusing to the user. Also, we want to restrict the usage so there is no adverse impact. 
So, in this PR I have reverted that change. 
@sadasant Please review and approve.
@ramya-rao-a FYI......
> [Keys] Revert change that introduced enum for API version that had only the latest API version value

- sdk/communication/communication-administration/package.json
- sdk/formrecognizer/ai-form-recognizer/package.json
* Ignore a sample that's clearly intended to only be run with caution and manually in form-recognizer
* Create the first ignore for communication-administration package, just to be helpful (hopefully)
> Getting the smoke testing pipeline green again

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
- sdk/textanalytics/ai-text-analytics/src/healthResult.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/src/lro/health/operation.ts
- sdk/textanalytics/ai-text-analytics/src/util.ts
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
The service returns a list of relationships between pairs of healthcare entities represented as JSON pointers. This PR creates a directed graph out of these relationships. This is an initial design and it is basically the simplest until we hear from the service about concrete user cases and how they consume these relationships information. You can find this design in action in the updated unit test in `apiKey.spec.ts`. This current design is set to be discussed in the arch board meeting scheduled on Jan 7th. This PR is based on https://github.com/Azure/azure-sdk-for-js/pull/13031, so please review that one first before reviewing this.
js api review: https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de?diffRevisionId=2c0a26254a524f45bf18cdfb36479cf8&doc=False
java api …
> [Text Analytics] Organize healthcare entities as nodes in a graph

- sdk/tables/data-tables/test/integration/tableclient.spec.ts
We are getting some random timeouts in live tests when listing all entities. Increasing the timeout for the specific test to make sure it has enough time to list all entities.
> [Tables] Increase timeout for list all test

- sdk/eventhub/event-processor-host/package.json
- sdk/eventhub/event-processor-host/rollup.base.config.js
Uglify was used to ship minified browser builds, but we don't actually ship browser bundles.
> [eventhub] Remove old uglify dependency

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/review/core-auth.api.md
- sdk/core/core-auth/src/azureSASCredential.ts
- sdk/core/core-auth/src/index.ts
- sdk/core/core-auth/test/index.spec.ts
This change adds an interfance and supporting class for use by services
which support authentication used a shared acccess signature.
Fixes #13053
> [core-auth] Add AzureSasCredential

- samples/frameworks/electron/ts/README.md
Link checker fails if it finds "en-us" in links and this is as per azure - sdk readme guidance about links.
> Fix links to remove en-us

- sdk/cosmosdb/cosmos/README.md
This commit makes a minor update to the Cosmos README to use
`keys list` instead of `list-keys` since the latter is deprecated and 
shows a warning on the CLI when ran.
I ran into this in passing when using Cosmos DB.
> [Cosmos] Update README to use non deprecated method

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/index.ts
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/test/serviceClient.spec.ts
This PR introduces a new `OperationOptions` member called `onResponse` that is called with the full HTTP response of each operation. This option replaces the previous behavior of attaching the `FullOperationResponse` as a special non-enumerable `_response` property on the flattened response object.
This PR also makes `sendOperationRequest` generic instead of returning an indexer type that is effectively `any`. This should make it even easier for generated code to properly express the correct return type without extra casting.
This PR is based on #12944, but does not change the header mapping behavior of `sendOperationRequest`.
> [core-client] Switch _response property for callback.

- sdk/eventhub/event-hubs/samples/browserSample/README.md
Fixes #12917
The browser sample was failing in #12917 because the user was accessing the sample using the ip address for local host (127.0.0.1) instead of from `http://localhost`. This causes problems because the address needs to match the reply url used when setting up the app registration, which in our sample uses `http://localhost`.
I added a troubleshooting section that calls out what to do if the user encounters a specific AAD error caused by navigating to the sample via an address other than localhost.
> [event-hubs] Update browser sample with AAD troubleshooting tip

- sdk/tables/data-tables/CHANGELOG.md
- sdk/tables/data-tables/src/TableClient.ts
- sdk/tables/data-tables/src/TableServiceClient.ts
- sdk/tables/data-tables/src/utils/connectionString.ts
Fixes issues #13100, #13118 and ##12753
This PR fixes the issues above enabling support for Azure Storage Emulator and Azurite. The underlying issue is described in #13159 in which core-http's URLBuilder doesn't play nicely with parametrized enpoint + parametrized paths. i.e replacing `{url}/{param1}` drops `param1` if `{url}` value contains any path elements.
However, in the Tables clients, we can explicitly set the `options.endpoint`, doing this the URL is no longer parametrized and the path parameters are not dropped. 
This is why, from the generated client:
Running tests against the emulator and Azurite is tracked by #13164
> [Tables] Support Emulator and Azurite

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeHealthcare.ts
- sdk/textanalytics/ai-text-analytics/src/analyzeResult.ts
- sdk/textanalytics/ai-text-analytics/src/healthResult.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
- sdk/textanalytics/ai-text-analytics/src/lro/health/operation.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
We received great feedback from the arch board meeting and this PR addresses the following issues discussed during the meeting:
- renames `dataSource` to `dataSources` and makes it required. If the list is not returned by the service, we return an empty list instead to conform to how we treat output lists in other parts of the SDK.
- renames `beginAnalyzeHealthcare` to `beginAnalyzeHealthcareEntities`.
- renames `AnalyzeResult` to `AnalyzeBatchTasksResult `.
- renames `relatedHealthcareEntities` to `relatedEntities`.
- simplifies the properties names of `HealthcareEntityDataSource` to just `name` and `id` instead of `dataSource` and `dataSourceId` respectively.
- massages the `CHANGELOG.md`.
> [Text Analytics] Address feedback from the arch board meeting 11/1

- sdk/communication/communication-administration/package.json
- sdk/communication/communication-administration/samples/javascript/README.md
- sdk/communication/communication-administration/samples/javascript/releasePhoneNumbers.js
- sdk/communication/communication-administration/samples/typescript/README.md
- sdk/communication/communication-administration/samples/typescript/src/releasePhoneNumbers.ts
This PR updates the release phone numbers sample so it does not have to be skipped in smoke testing pipeline. See #13111 for context.
> [communication] update release phone numbers sample

- eng/pipelines/templates/steps/build.yml
Disabling step to build sample to avoid npm clean which removes artifacts built in previous step. This is to unblock release.
> Removed step to build samples temporarily

- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-files-required.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-keywords.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-use-promises.ts
PRs for packages that import the plugin will fail because of failures in the plugin test suite after recent upgrades and this PR fixes these issues to some extent.
Two of the failed unit tests were fixed by their respective rule fixer and it is now required that we check the output of the fixer. The other failure is due to an obscure change in behavior after upgrading TS to v4.1.2. I opened https://github.com/Azure/azure-sdk-for-js/issues/13186 to investigate this.
> [ESLint Plugin] Fix failing tests

- sdk/communication/communication-administration/package.json
- sdk/communication/communication-administration/samples/javascript/purchasePhoneNumber.js
- sdk/communication/communication-administration/samples/typescript/src/purchasePhoneNumber.ts
This PR adds the `purchasePhoneNumber.js` sample to the list of skipped samples when smoke testing. The sample is purchasing a real phone number on smoke test runs; we do not want this.
> [communication] skip purchase phone number sample when smoke testing

- sdk/monitor/opentelemetry-exporter-azure-monitor/src/export/trace.ts
core-http return REQUEST_SEND_ERROR as error code when there is a network issue
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/core/core-http/src/fetchHttpClient.ts#L191
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/core/core-http/src/xhrHttpClient.ts#L163
> OpenTelemetry exporter use correct error code when there is a network issue

- common/tools/dev-tool/package.json
- common/tools/dev-tool/test/resolveProject.spec.ts
CI expects `unit-test:node` to exist so this PR adds it to `dev-tool` package. Furthermore, `resolveProject` changed it behavior and this PR updates the unit test for it accordingly.
> [dev-tool] Adds unit-test:node and fix unit test

- sdk/attestation/attestation/CHANGELOG.md
- sdk/attestation/attestation/package.json
- sdk/attestation/attestation/test/public/attestationTests.spec.ts
- sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts
- sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts
- sdk/attestation/attestation/test/public/tokenCertTests.spec.ts
- sdk/attestation/attestation/test/utils/base64url.browser.ts
- sdk/attestation/attestation/test/utils/base64url.ts
- sdk/attestation/attestation/test/utils/decodeJWT.ts
- sdk/attestation/attestation/tsdoc.json
The attestation pipeline failed for various errors (listed below), mainly because some crucial `npm` scripts were missing. This PR adds the standard ones and fixes linting issues in all but `src`.
Link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=682555&view=logs&j=23e2e6de-b7c3-5918-7121-f16b46172e49&t=7bd26578-88b4-5baa-f548-7813777930ca
- `ERROR: The project [@azure/dev-tool] does not define a 'unit-test:node' command`
- `ERROR: The project [@azure/attestation] does not define a 'pack' command`
- failures in the eslint plugin, opened https://github.com/Azure/azure-sdk-for-js/pull/13189 to fix them and rebased
- failures in dev-tool because of an outdated unit test. After fixing this issue , now I get this https://github.com/Azure/azure-sdk-for-js/issues/13202 …
> [Attestation] Adds missing npm scripts and adds tsdoc.json

- common/tools/eslint-plugin-azure-sdk/docs/rules/ts-doc-internal.md
- common/tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-doc-internal.ts
We are no longer using JSDoc's `@ignore` here https://github.com/Azure/azure-sdk-for-js/pull/12963.
> [ESLint Plugin] ts-doc-internal checks for hidden instead of ignore

- sdk/digitaltwins/digital-twins-core/CHANGELOG.md
- sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
- sdk/digitaltwins/digital-twins-core/src/generated/azureDigitalTwinsAPIContext.ts
Add an entry listing a recent bug fix where we did not
ship the renamed type definition file.
> Update CHANGELOG for digital-twins-core

- common/tools/dev-tool/package.json
- eng/pipelines/templates/steps/build.yml
- sdk/storage/storage-blob-changefeed/package.json
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-queue/package.json
- The "npm run clean" script from "build:samples" wipe out the storage artifacts generated by npm pack in the ci pipeline, hence this step needs to be removed
- Also moving the "Build:samples" step before npm pack in the CI pipeline so that the "npm run clean" from the prebuild steps of storage's package.json doesn't wipe out the generated artifacts
> Removing npm clean step from build samples and run step before pack

- sdk/digitaltwins/digital-twins-core/CHANGELOG.md
- sdk/digitaltwins/digital-twins-core/package.json
v1.0.2 did not fix the issue of not including the type declaration file because I just renamed the file name from camel case to use dashes instead (https://github.com/Azure/azure-sdk-for-js/pull/13222) but it turns out the file name changed to `digital-twins-core.d.ts` instead. This PR fixes this issue and makes sure the file name generated by the api extractor tool matches that of the shipped one.
```
dealmaha@dev:~/repo/sdk/digitaltwins/digital-twins-core$ git grep "digital-twins-core.d.ts" .
api-extractor.json:    "publicTrimmedFilePath": "./types/digital-twins-core.d.ts"
package.json:  "types": "types/digital-twins-core.d.ts",
package.json:    "types/digital-twins-core.d.ts",
```
This PR also prepares for release for v1.0.3.
The release fixes the failure the docs team see here: …
> [Digital Twins] Include the correct type declaration file

- sdk/digitaltwins/digital-twins-core/package.json
- sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
- sdk/digitaltwins/digital-twins-core/src/generated/azureDigitalTwinsAPIContext.ts
to v1.0.3 in `package.json` and in `src`. This is the version of the release prepared here: https://github.com/Azure/azure-sdk-for-js/pull/13249.
> [Digital Twins] bump version

- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-http/src/serviceClient.ts
Our friends on the ACS team noticed that we are always setting an "application/json" content type on requests, even when the body is empty. This appears to be some strange codegen where we always set the default type on the client object, which then gets assigned to every request.
As a short-term solution, this PR changes the behavior of when to set the default content-type to only do so if there is a `requestBody` key on the `OperationSpec`.  This should avoid the trouble that ACS ran into as requests without a body will no longer have an incorrect default header applied to them.
In the future we should change codgen to use the "consumes" property on the swagger to set the content type in the OperationSpec instead of relying on a client-wide default.
> [core-http][core-client] Eliminate default content-type on empty requests

- sdk/eventhub/event-processor-host/README.md
- sdk/eventhub/event-processor-host/samples/javascript/iothubEph.js
- sdk/eventhub/event-processor-host/samples/javascript/multiEph.js
- sdk/eventhub/event-processor-host/samples/javascript/sendBatch.js
- sdk/eventhub/event-processor-host/samples/javascript/singleEph.js
- sdk/eventhub/event-processor-host/samples/javascript/websockets.js
- sdk/eventhub/event-processor-host/samples/typescript/src/iothubEph.ts
- sdk/eventhub/event-processor-host/samples/typescript/src/multiEph.ts
- sdk/eventhub/event-processor-host/samples/typescript/src/sendBatch.ts
- sdk/eventhub/event-processor-host/samples/typescript/src/singleEph.ts
- sdk/eventhub/event-processor-host/samples/typescript/src/websockets.ts
Now that we have the new Event Hubs package along with the checkpoint store as a replacement for the `@azure/event-processor-host`, it is time to deprecate it
> Mark @azure/event-processor-host as deprecated

- sdk/communication/communication-common/review/communication-common.api.md
- sdk/communication/communication-common/src/identifierModelSerializer.ts
- sdk/communication/communication-common/src/index.ts
- sdk/communication/communication-common/test/identifierModelSerializer.spec.ts
This is part of our work to replace MRI-formatted ids in our services with an understandable communication identifier object format. Communication services should use this serializer to translate between wire format and SDK model format.
> [communication-common] Add serializer for communication identifiers

- sdk/attestation/attestation/CHANGELOG.md
- sdk/attestation/attestation/review/attestation.api.md
- sdk/attestation/attestation/src/attestationClientContext.ts
- sdk/attestation/attestation/src/models/index.ts
- sdk/attestation/attestation/src/models/mappers.ts
- sdk/attestation/attestation/swagger/readme.md
This is to address the issue https://github.com/Azure/sdk-release-request/issues/1047. This issue was raised on Dec 3, 2020. @deyaaeldeen actually released this package 4 days ago which should be sufficient.
But, when I regenerated the SDK, 3 fields have been marked as optional. This was done recently in swagger. So, the last release did not include these changes. Since, I think this might impact the user experience, I think it is safe to do a release today before a customer/other SDKs raise issue. 
@deyaaeldeen Please review and approve.
> Regenerate and Release Attestation SDK

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/ConnectionContextBase.ts
- sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
- sdk/core/core-amqp/test/context.spec.ts
- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/review/event-hubs.api.md
- sdk/eventhub/event-hubs/rollup.base.config.js
- sdk/eventhub/event-hubs/src/connectionContext.ts
- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/src/models/public.ts
- sdk/eventhub/event-hubs/src/util/constants.ts
- sdk/eventhub/event-hubs/src/util/parseEndpoint.ts
- sdk/eventhub/event-hubs/test/client.spec.ts
- sdk/eventhub/event-hubs/test/config.spec.ts
- sdk/eventhub/event-hubs/test/impl/parseEndpoint.spec.ts
- sdk/servicebus/service-bus/package.json
We had reverted the custom endpoint address changes in #13096 so that we could do a core-amqp release.
This PR reverts that revert and removes the 'beta' moniker from the event hubs version number.
Original PR: #12909
> [event-hubs] re-add support for custom endpoint address

- eng/pipelines/templates/jobs/archetype-sdk-integration.yml
This PR enables the 1ES pools for live testing for Windows and Linux jobs. It adds a ```Pool``` parameter to the matrix entries and adjusts the image names accordingly.
> Enable 1ES pools for live tests.

- sdk/monitor/opentelemetry-exporter-azure-monitor/CHANGELOG.md
- sdk/monitor/opentelemetry-exporter-azure-monitor/api-extractor.json
- sdk/monitor/opentelemetry-exporter-azure-monitor/package.json
- sdk/monitor/opentelemetry-exporter-azure-monitor/src/generated/applicationInsightsClientContext.ts
- sdk/monitor/opentelemetry-exporter-azure-monitor/src/utils/constants/applicationinsights.ts
@azure/opentelemetry-exporter-azure-monitor@1.0.0-beta.1  does not have any typescript definition file and causes the following failure for the docs team: `types/latest/opentelemetry-exporter-azure-monitor.d.ts doesn't exist, which is defined in package.json.`. This PR fixes the issue by including a types declaration file and prepares for the release of version 1.0.0-beta.2.
> [Monitor] Ship type declarations

- sdk/core/core-http/src/fetchHttpClient.ts
- sdk/core/core-https/src/nodeHttpsClient.ts
- sdk/storage/storage-file-share/test/fileclient.spec.ts
Currently our cleanup code removes the abort event listener when the response is
returned. In streaming case even the response is returned, the work is not done
yet. However, with the abort listener removed, we lost the ability to cancel the
streaming.
This change fixes the issue by unregistering the abort listener for
streaming when the stream ends or error happens.
This fixes #12029
> [core-http] Clean up event listener when streaming is done

- sdk/eventhub/event-hubs/test/client.spec.ts
We're seeing a reoccurrence of the EAI_AGAIN error in some of our tests that check behavior against non-existent event hub namespaces again.
Since what we _really_ want to ensure is that the node.js error is surfaced to the user, I loosened the check on `err.code` so that we just make sure `err.code` is defined, and that the message on the error isn't the one we'd expect to see if the test failed.
> [event-hubs] fixes flaky service communication error tests

- sdk/servicebus/service-bus/test/backupMessageSettlement.spec.ts
This test has been failing flakily since yesterday.
This PR is not meant to fix the flakiness, but to report a meaningful error.
> [Service Bus] Flaky Test - Report a meaningful error

- sdk/servicebus/service-bus/test/backupMessageSettlement.spec.ts
- sdk/servicebus/service-bus/test/deferredMessage.spec.ts
Hundreds of iterations of this test succeeded here https://github.com/Azure/azure-sdk-for-js/pull/13325
> [Service Bus] Flaky test - Add delay to make sure the expiry time upon renewlock gets updated

- eng/pipelines/templates/stages/archetype-js-release.yml
artifact name for Opentelemetry-exporter-azure-monitor package is azure-opentelemetry-exporter-azure-monitor. Github docs release step replaces "azure-" to generate package name which is usually present as prefix only. Due to recent naming changes, monitor package has got "azure-" within package name also and this also got replaced which lead to invalid doc name to stage. Fix is to replace only first "azure-"
> Replace only first  azure-  to generate package name

- eng/tools/analyze-deps/index.js
- eng/tools/analyze-deps/package-lock.json
- eng/tools/analyze-deps/package.json
Some deps were out of date. This PR bumps versions and fixes some minor renames in argparse.
> Update dependencies for analyze-deps tool

- eng/pipelines/templates/stages/cosmos-sdk-client.yml
- sdk/keyvault/keyvault-admin/tests.yml
This adds a missing reference to the new windows pool from our 1es hosted agents.
> Add windows pool reference to cosmos ci matrix

- sdk/tables/data-tables/review/data-tables.api.md
- sdk/tables/data-tables/src/generated/generatedClient.ts
- sdk/tables/data-tables/src/generated/generatedClientContext.ts
- sdk/tables/data-tables/src/generated/models/index.ts
- sdk/tables/data-tables/src/generated/models/mappers.ts
- sdk/tables/data-tables/src/generated/models/parameters.ts
- sdk/tables/data-tables/src/generated/operations/service.ts
- sdk/tables/data-tables/src/generated/operations/table.ts
- sdk/tables/data-tables/src/generatedModels.ts
- sdk/tables/data-tables/swagger/README.md
The last V6 SDK version that is used to generate Tables is 6.0.0-dev.20200817.1. This PR is to upgrade the V6 SDK version to the latest 6.0.0-dev.20210121.2 version.
@joheredi Please review and approve.
@ramya-rao-a FYI.......
> Upgrade V6 SDK Generator Version for Tables

- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/generated/generatedClient.ts
- sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/parameters.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/swagger/README.md
The last V6 SDK version that is used to generate Text Analytics is ```6.0.0-dev.20201027.1```. This PR is to upgrade the V6 SDK version to the latest ```6.0.0-dev.20210121.2``` version.
@deyaaeldeen @witemple-msft Please review and approve.
@joheredi @ramya-rao-a FYI.......
> Upgrade V6 SDK Generator Version for Text Analytics

- sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
- sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts
- sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
- sdk/formrecognizer/ai-form-recognizer/src/models.ts
- sdk/formrecognizer/ai-form-recognizer/swagger/README.md
The last V6 SDK version that is used to generate Form Recognizer is ```6.0.0-dev.20201113.1```. This PR is to upgrade the V6 SDK version to the latest ```6.0.0-dev.20210121.2``` version.
@jeremymeng  Please review and approve.
@joheredi @ramya-rao-a FYI.......
> Upgrade V6 SDK Generator Version for Form Recognizer

- sdk/monitor/opentelemetry-exporter-azure-monitor/CHANGELOG.md
- sdk/monitor/opentelemetry-exporter-azure-monitor/package.json
- sdk/monitor/opentelemetry-exporter-azure-monitor/src/utils/constants/applicationinsights.ts
Increment package version after release of azure-opentelemetry-exporter-azure-monitor
Merged the release notes for 1.0.0-preview.5 and 1.0.0-preview.6 into 1.0.0-beta.1 as the preview versions were not released under the current package name.
> Increment version for monitor releases

- sdk/servicebus/service-bus/test/renewLock.spec.ts
- sdk/servicebus/service-bus/test/utils/testUtils.ts
Investigated at https://github.com/Azure/azure-sdk-for-js/pull/13336 to figure out and fix the flakyness.
Sometimes, the service returns zero messages for the peek call and is forcing us to retry the peek operation until we get the message so the test is green.
(We may have other tests that may fail with the same, we can extend this fix to those tests as needed.)
> [Service Bus] Fix flaky test - Peek until we get the message

- common/config/rush/common-versions.json
- sdk/servicebus/service-bus/package.json
Since core-amqp 2.1.0 is not released, reverting to 2.0.0 so that service-bus 7.0.3 can be released.
This PR will be reverted after the 7.0.3 release.
> [Service Bus] Revert core-amqp to 2.0.0

- sdk/quantum/quantum-jobs/package.json
We missed adding "types" folder in the "files" section at #13385 (needed for the published package)
> [Quantum Jobs] Missing "types" in the files included

- sdk/servicebus/service-bus/test/stress/package.json
- sdk/servicebus/service-bus/test/stress/scenarioBatchReceive.ts
- sdk/servicebus/service-bus/test/stress/stressTestsBase.ts
Just updating the version and fixing  related compile errors
> [Service Bus] Stress tests - Migrate to 7.0.0

- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-lro/src/poller.ts
- sdk/core/core-lro/test/utils/testOperation.ts
- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
- sdk/keyvault/keyvault-admin/rollup.base.config.js
- sdk/keyvault/keyvault-admin/samples/javascript/accessControlHelloWorld.js
- sdk/keyvault/keyvault-admin/samples/typescript/src/accessControlHelloWorld.ts
- sdk/keyvault/keyvault-admin/src/accessControlClient.ts
- sdk/keyvault/keyvault-admin/src/accessControlModels.ts
- sdk/keyvault/keyvault-admin/src/backupClient.ts
- sdk/keyvault/keyvault-admin/src/backupClientModels.ts
- sdk/keyvault/keyvault-admin/src/generated/models/mappers.ts
- sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
- sdk/keyvault/keyvault-admin/src/lro/backup/poller.ts
- sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
- sdk/keyvault/keyvault-admin/src/lro/restore/poller.ts
- sdk/keyvault/keyvault-admin/src/mappings.ts
- sdk/keyvault/keyvault-admin/test/internal/logger.spec.ts
- sdk/keyvault/keyvault-admin/test/internal/serviceVersionParameter.spec.ts
- sdk/keyvault/keyvault-admin/test/public/accessControlClient.spec.ts
- sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts
- Fix core-lro stale state bug
- beginBackup and beginRestore now return a *Result object
- Various renames (roleAssignment.type, options)
- Update the sample code
- Reject / bubble up errors when polling for backup / restore operations
- Admin changes line up our public API with other libraries and addresses recent architecture board review feedback
- operation.state can become stale if someone was to modify or splat it out during the `update` call. That can cause a drift between the logic that checks if we resolve the promise and the value we return when we do. This fix ensures that we return the right data.
Resolves #12319
> [KeyVault] - Address arch board feedback for Admin package

- sdk/servicebus/service-bus/README.md
Fix readme to just use '<connectionString>' rather than referencing a variable that doesn't exist.
Fixes #13393
> [service-bus] readme fix to use a string literal rather than 

- sdk/identity/identity/README.md
This PR updates the readme for Identity with details on the different authentication options upfront. This makes it easier to link to this page from #13403 instead of going through the same text there
I have used the Java and .Net readmes for Azure Identity along with #12878 as reference
> Identity readme updates for more clarity upfront

- sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts
- sdk/appconfiguration/app-configuration/src/generated/src/appConfigurationContext.ts
- sdk/appconfiguration/app-configuration/src/internal/helpers.ts
- sdk/appconfiguration/app-configuration/tsdoc.json
Remove the `hidden` attribute for all spots, use `internal` only. Also remove the tsdoc.json as it was only there to allow for the usage of the `hidden` attribute.
NOTE: I've also changed the generated clients. Next time we use the official autorest generator it should generate the exact same thing so this shouldn't be an issue.
Fixes #13445
> [app-configuration] Remove the `hidden` attribute for all spots, use `internal` only

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/batchingReceiver.spec.ts
Renamed `close` to `terminate` to resolve issue #13390.
> service bus internal method rename #13390

- common/config/rush/pnpm-lock.yaml
- dataplane.code-workspace
- sdk/communication/communication-identity/karma.conf.js
- sdk/communication/communication-identity/package.json
karma-remap-istanbul is an undesirable dependency we've been trying to remove from the tree. This PR does the same dance we've performed in other libraries to make it unnecessary.
> [communication-identity] Update karma to not use karma-remap-istanbul

- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts
A single test has been failing sporadically in most of our pipeline runs:
```
EventHubConsumerClient
functional tests
Reinitialize partition processing after error
when subscribed to multiple partitions:
Error: Waited way too long for Wait for subscription1 to recover
```
This test is meant to ensure that a running subscription will recover across all partitions after encountering an error.
The way we do this is to:
- Start subscription __1__
- Wait for subscription __1__ to be reading events from all partitions.
- Start subscription __2__ with an ownerLevel
- The ownerLevel will force subscription __1__ to disconnect from all partitions.
- Wait for subscription __1__ to have _processClose_ called on all partitions.
- Stop subscription __2__.
- This removes the receiver links with …
> [event-hubs] investigate flaky tests

- sdk/identity/identity/src/client/msalClient.ts
Originally reported in https://github.com/Azure/azure-sdk-for-js/issues/13343, Identity had been setting the global Axios setting rather than using a local setting. This could have unintended impacts on other users of Axios in a project.
With this PR, Identity switches to setting the "validate status" setting locally rather than globally.
> [Identity] Move Axios to validate status locally

- sdk/keyvault/keyvault-keys/test/public/crypto.spec.ts
- sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts
This commit changes two things:
- Fix a typo in test expectation
- await on `isRejected` to catch when the expectation isn't met
> [KeyVault] - Fix integration tests

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/review/event-hubs.api.md
- sdk/eventhub/event-hubs/src/index.ts
- sdk/eventhub/event-hubs/src/models/public.ts
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/constructorHelpers.ts
- sdk/servicebus/service-bus/src/index.ts
Fixed #13166
Both `@azure/event-hubs` and `@azure/service-bus` packages use `RetryOptions` from `@azure/core-amqp`. `RetryOptions` has a field - `mode` - that is an enum: `RetryMode`.
We needed to re-export `RetryMode` from the client packages, otherwise a user would need to import it from `@azure/core-amqp` (a package we don't want users to use directly) in order to change the mode from `Fixed` to `Exponential`.
I also noticed that the generated doc pages for our client options were poor in quality since we don't yet support linking across packages, so I spruced up the client options interfaces to better document `RetryOptions`.
> [event-hubs][service-bus] re-export RetryMode

- sdk/servicebus/service-bus/test/stress/runcontainer.js
- sdk/servicebus/service-bus/test/stress/scenarioBatchReceive.ts
- sdk/servicebus/service-bus/test/stress/scenarioCloseOpen.ts
- sdk/servicebus/service-bus/test/stress/scenarioPeekMessages.ts
- sdk/servicebus/service-bus/test/stress/scenarioRenewMessageLock.ts
- sdk/servicebus/service-bus/test/stress/scenarioRenewSessionLock.ts
- sdk/servicebus/service-bus/test/stress/scenarioSend.ts
- sdk/servicebus/service-bus/test/stress/scenarioStreamingReceive.ts
- sdk/servicebus/service-bus/test/stress/stressTestsBase.ts
- sdk/servicebus/service-bus/test/stress/utils.ts
Made it so runContainer.js can run any scenario test, not just scenarioBatchReceiver.ts.
Also made it so the telemetry is queryable by moving the telemetry into properties, rather than just being a trace message.
> [service-bus] Make stress/perf easier to run with separate scripts and improve telemetry

- sdk/search/search-documents/.eslintrc.json
- sdk/search/search-documents/review/search-documents.api.md
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushSizeBased.ts
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushTimerBased.ts
- sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/manualFlush.ts
- sdk/search/search-documents/samples/typescript/src/utils/setup.ts
- sdk/search/search-documents/src/generated/data/searchClient.ts
- sdk/search/search-documents/src/generated/data/searchClientContext.ts
- sdk/search/search-documents/src/generated/service/searchServiceClient.ts
- sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
- sdk/search/search-documents/src/searchIndexingBufferedSender.ts
This PR Contains the following changes:
1. Change ```@hidden``` to ```@internal``` values. 
2. Fix the error ```code``` to ```statusCode```.
3. One new requirement is that in the batch sender before sending in the batch we need to check if there are any duplicates (based on the id retrieval logic  supplied by the user) and move them to the next batch. (It is ok if we send a batch that is less than the threshold size)
4. Change the autoflush to true by default.
> Add Document Key Retriever to Buffered Sender

- common/config/rush/pnpm-lock.yaml
build is failing with following error. 
ERROR: Internal Error: Unable to find dependency chai-as-promised with version 7.1.1 in shrinkwrap.
Rush update to update lock file.
> Update pnpm lock file

- sdk/template/template/README-TEMPLATE.md
- Add a section on setting up CORS and creating a browser bundle to our template readme
CORS is one of the first roadblocks a user will encounter when developing a browser application
using our SDK. As such, we should provide some help in the form of "here's the basics of configuring
CORS support at the service level" in the README.
closes #13149
> Add CORS and Bundling sections to README-TEMPLATE

- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
- sdk/keyvault/keyvault-certificates/src/identifier.ts
- sdk/keyvault/keyvault-certificates/src/index.ts
- sdk/keyvault/keyvault-certificates/test/public/identifier.spec.ts
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
- sdk/keyvault/keyvault-keys/src/identifier.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
- sdk/keyvault/keyvault-secrets/src/identifier.ts
- sdk/keyvault/keyvault-secrets/src/index.ts
- sdk/keyvault/keyvault-secrets/test/public/identifier.spec.ts
- Hide various parse identifier methods
- Make additionalAuthenticatedData readonly
These came out of the recent KV architecture review. I spoke to @sadasant and 
made sure that the other tasks are not applicable to us
The only thing I wasn't sure about is renaming EncryptOptions to EncryptParameters since I
think we already GA'd with EncryptOptions - should I add a new EncryptParameters where iv and aad 
are set?
Partially resolves #13237
> [KeyVault] - Address KeyVault feedback

- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations/recording_can_create_an_oct_key_with_options.json
- sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations/recording_can_create_an_oct_key_with_options.js
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/src/keysModels.ts
- sdk/keyvault/keyvault-keys/test/public/CRUD.spec.ts
- Add `createOctKey` method to support creating keys of type `oct` and `oct-HSM`
- Add `createOctKeyOptions` supporting `hsm` (keySize is already supported at the `createKeyOptions` interface)
- This adds the same convenience layer we have for createEcKey, createRsaKey, etc....
- Decided to use `hsm` to be compatible with the APIs we already shipped. Feel free to let me know if you want this to be hardwareProtected at the cost of being inconsistent with our other create<Type>KeyOptions.
resolves #12457
> Add a createOctKey convenience method and relevant options.

- common/config/rush/pnpm-lock.yaml
- sdk/anomalydetector/ai-anomaly-detector/rollup.base.config.js
- sdk/communication/communication-administration/rollup.base.config.js
- sdk/communication/communication-chat/rollup.base.config.js
- sdk/communication/communication-identity/rollup.base.config.js
- sdk/communication/communication-sms/rollup.base.config.js
- sdk/identity/identity/rollup.base.config.js
- sdk/keyvault/keyvault-certificates/rollup.base.config.js
- sdk/keyvault/keyvault-keys/rollup.base.config.js
- sdk/keyvault/keyvault-secrets/rollup.base.config.js
- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry-avro/rollup.base.config.js
- sdk/schemaregistry/schema-registry/rollup.base.config.js
This resolves a build failure for any PRs that are updating pnpm-lock. It does a full regenerate of pnpm-lock and also adds `rollup-plugin-json` to the identity browser bundle configuration, as it's now required due to an update to msal (this is the source of the build failures).
Also adds plugin-json to every other package that didn't have it before, as it's required for the bundler to accept a JSON file that is now included as part of MSAL.
> [identity] Updated pnpm-lock and added plugin-json to identity browser config

- sdk/core/core-http/src/util/sanitizer.ts
- sdk/core/core-https/src/util/sanitizer.ts
To add ms-cv to list of headers that can be enabled by default for customer logging options so that they can share these for debugging and reporting.
> add ms-cv to list of visible headers

- sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts
Noticed there were some redundant `close()` calls so checking if cleaning those up reduces the `afterEach` failures we sometimes see in test runs.
> [event-hubs] clean up afterEach for client close tests

- sdk/servicebus/service-bus/package.json
Perf tests are being picked up by the mocha command, Updating the test command to not do that.
> [Service Bus] Fix test command to pick non-perf/stress files only (** -> *)

- common/config/rush/common-versions.json
- sdk/servicebus/service-bus/package.json
This reverts commit ba6bbbab05fc132f3dd6d7c06bb4fa020b38b754.
Since the service-bus 7.0.3 is released, we can move to the latest core-amqp.
> Revert "[Service Bus] Revert core-amqp to 2.0.0 (#13401)"

- sdk/core/core-https/review/core-https.api.md
- sdk/core/core-https/src/constants.ts
- sdk/core/core-https/src/nodeHttpsClient.ts
- sdk/core/core-https/src/pipelineRequest.ts
#13266 accidentally flipped a boolean, causing gzip responses to not be properly decoded. This PR fixes the issue and changes the code to make it less convoluted.
Also fixes the version string used by the User-Agent policy and finishes removing some old API surface that #13266 forgot to clean up.
> [core-https] Fix decoding of gzip responses

- sdk/digitaltwins/digital-twins-core/tests.yml
The nightly tests have not been running for the `@azure/digital-twins-core` package as the right package name was not updated in tests.yml file. We had the below error in the build stage:
This PR fixes the build error, but the tests are now failing which needs to be looked at by the Digital Twins team
cc @deyaaeldeen @zolvarga
> Use the right pkg name in tests.yml

- eng/pipelines/mgmt-ci.yml
- eng/pipelines/mgmt-pr.yml
- sdk/digitaltwins/digital-twins/tsdoc.json
After the `digitaltwins` package was renamed to `digital-twins-core`, we had a few clean up items that were missed. Since #13251 which attempted to do the clean up is battling build errors, creating a separate PR and pulling out the safe changes.
https://github.com/Azure/azure-sdk-for-js/pull/13607 that took care of the tests.yml file is already merged
> Clean up after digital twins pkg rename

- sdk/keyvault/keyvault-secrets/rollup.base.config.js
- sdk/keyvault/keyvault-secrets/src/transformations.ts
- sdk/keyvault/keyvault-secrets/test/internal/transformations.spec.ts
- Fix a bug where not all properties were correctly assigned when reading a secret's properties.
- Add a test as a sort of change detector that ensures we don't accidentally miss currently available properties
- @jeremymeng noticed that listing secrets sample wasn't listing anything. This is because `enabled`
wasn't being correctly set.
> [KeyVault] - Include missing properties when reading SecretBundle

- sdk/servicebus/service-bus/test/stress/package.json
- sdk/servicebus/service-bus/test/stress/runContainer.js
- sdk/servicebus/service-bus/test/stress/sample.env
- sdk/servicebus/service-bus/test/stress/scenarioBatchReceive.ts
- sdk/servicebus/service-bus/test/stress/scenarioCloseOpen.ts
- sdk/servicebus/service-bus/test/stress/scenarioLongRunning.ts
- sdk/servicebus/service-bus/test/stress/scenarioPeekMessages.ts
- sdk/servicebus/service-bus/test/stress/scenarioRenewMessageLock.ts
- sdk/servicebus/service-bus/test/stress/scenarioRenewSessionLock.ts
- sdk/servicebus/service-bus/test/stress/scenarioSend.ts
- sdk/servicebus/service-bus/test/stress/scenarioStreamingReceive.ts
- sdk/servicebus/service-bus/test/stress/stressTestsBase.ts
- sdk/servicebus/service-bus/test/stress/tsconfig.json
- sdk/servicebus/service-bus/test/stress/utils.ts
Added in the "long running test" that I had previously written, now ported to @HarshaNalluru's much nicer stress framework. This test is intended to run for long periods of time, sending messages every second (and receiving the entire time). This should complement some of the other tests we have that test more stressful/high perf conditions by allowing us to see how our code handles running long-term.
Also, some other changes for quality of life and others:
* Make tsconfig.json more strict to catch more errors and other "risky" constructs in the stress tests.
* Fix aforementioned risky and erroneous constructs (mostly just using before initialization, assuming falsy, etc..)
* Refactored stressTestBase (not too drastically) to allow for tracking statistics generated from outside of the …
> [service-bus] Add in long-running stress/perf test

- CONTRIBUTING.md
Our link verification step in the `js - aggregate-reports` pipeline has been failing with this warning on link not using https
> Fix warning on insecure link

- sdk/textanalytics/ai-text-analytics/README.md
- sdk/textanalytics/ai-text-analytics/package.json
- sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_action_failures_are_returned.json
- sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_action_failures_are_returned.js
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeBatchActions.js
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeBatchActions.ts
- sdk/textanalytics/ai-text-analytics/src/analyzeBatchActionsResult.ts
- sdk/textanalytics/ai-text-analytics/src/constants.ts
- sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsResult.ts
- sdk/textanalytics/ai-text-analytics/swagger/README.md
- sdk/textanalytics/ai-text-analytics/test/internal/collections.spec.ts
- sdk/textanalytics/ai-text-analytics/test/internal/util.spec.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
The text analytics crew recently agreed on treating action errors in a slightly different way and this PR implements this change. The `beginAnalyzeBatchActions` takes a list of actions (previously known as tasks) as input and apply all of them at once to the input documents and return the results. The results could be a mix of action errors and succeeded action results but the response keeps them separate. This PR combines both types of results into one list of action results (similar to how results on the document level are presented).
Things to note:
- If the service returns failed as a the job status, we used to create an exception out of all errors in the top-level errors list and throw it. Instead, in this PR, I no longer throw an exception and just return those errors as items in …
> [Text Analytics] Integrating action failures and successes into one array

- sdk/eventhub/event-hubs/src/connectionContext.ts
- sdk/eventhub/event-hubs/src/dataTransformer.ts
- sdk/eventhub/event-hubs/src/eventData.ts
- sdk/eventhub/event-hubs/src/eventDataBatch.ts
- sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/eventPosition.ts
- sdk/eventhub/event-hubs/src/eventProcessor.ts
- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/src/eventhubSharedKeyCredential.ts
- sdk/eventhub/event-hubs/src/linkEntity.ts
- sdk/eventhub/event-hubs/src/managementClient.ts
- sdk/eventhub/event-hubs/src/partitionProcessor.ts
- sdk/eventhub/event-hubs/src/receiveHandler.ts
This PR resolves about 150 linter errors around the use of `@property` tag which is not allowed in TSDoc
Related to #12953
> [Event Hubs] Remove use of @property tag in docs

- sdk/eventhub/event-hubs/src/connectionContext.ts
- sdk/eventhub/event-hubs/src/diagnostics/instrumentEventData.ts
- sdk/eventhub/event-hubs/src/eventDataBatch.ts
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/eventPosition.ts
- sdk/eventhub/event-hubs/src/eventProcessor.ts
- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/src/eventhubSharedKeyCredential.ts
- sdk/eventhub/event-hubs/src/inMemoryCheckpointStore.ts
- sdk/eventhub/event-hubs/src/linkEntity.ts
- sdk/eventhub/event-hubs/src/loadBalancerStrategies/loadBalancingStrategy.ts
- sdk/eventhub/event-hubs/src/managementClient.ts
- sdk/eventhub/event-hubs/src/models/private.ts
- sdk/eventhub/event-hubs/src/partitionPump.ts
- sdk/eventhub/event-hubs/src/pumpManager.ts
- sdk/eventhub/event-hubs/src/receiveHandler.ts
- sdk/eventhub/event-hubs/src/util/connectionStringUtils.ts
- sdk/eventhub/event-hubs/src/util/parseEndpoint.ts
- sdk/eventhub/event-hubs/src/util/runtimeInfo.browser.ts
- sdk/eventhub/event-hubs/src/util/runtimeInfo.ts
- sdk/eventhub/event-hubs/test/public/utils/testInMemoryCheckpointStore.ts
This PR removes the below invalid TSDoc tags fixing about 20 linting errors
- `@class`
- `@ignore`
- `@constructor`
Additionally, 
- it removes the `@hidden` tag if  `@internal` is already applied
- it removes the `@hidden` or `internal` tag on a interface/class member if the interface/class itself already has one of the two tags
Related to #12953
> [Event Hubs] Remove invalid tsdoc tags

- sdk/core/core-client/src/base64.browser.ts
- sdk/core/core-client/src/base64.ts
- sdk/core/core-client/src/createSpan.ts
- sdk/core/core-client/src/interfaceHelpers.ts
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/src/operationHelpers.ts
- sdk/core/core-client/src/serializer.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/src/utils.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-https/src/accessTokenCache.ts
- sdk/core/core-https/src/httpHeaders.ts
- sdk/core/core-https/src/interfaces.ts
- sdk/core/core-https/src/nodeHttpsClient.ts
- sdk/core/core-https/src/pipeline.ts
- sdk/core/core-https/src/pipelineRequest.ts
- sdk/core/core-https/src/policies/exponentialRetryPolicy.ts
- sdk/core/core-https/src/policies/logPolicy.ts
- sdk/core/core-https/src/policies/proxyPolicy.ts
- sdk/core/core-https/src/policies/redirectPolicy.ts
- sdk/core/core-https/src/policies/setClientRequestIdPolicy.ts
- sdk/core/core-https/src/policies/systemErrorRetryPolicy.ts
- sdk/core/core-https/src/policies/throttlingRetryPolicy.ts
- sdk/core/core-https/src/policies/tracingPolicy.ts
- sdk/core/core-https/src/policies/userAgentPolicy.ts
- sdk/core/core-https/src/util/helpers.ts
- sdk/core/core-https/src/util/uuid.ts
- sdk/core/core-https/src/xhrHttpsClient.ts
- sdk/core/core-xml/src/xml.common.ts
- sdk/core/core-xml/src/xml.ts
This PR fixes some of the easy to fix linting errors in the new core packages
Related to #12947 and #10775
> Fix linting errors in new core pkgs

- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
- sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
This PR fixes the outstanding linter errors in Schema Registry packages and enables future linter errors to fail the build. Resolves https://github.com/Azure/azure-sdk-for-js/issues/12954
> [Schema Registry] Fix linter errors

- sdk/digitaltwins/digital-twins-core/package.json
- sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
- sdk/digitaltwins/digital-twins-core/src/logger.ts
- sdk/digitaltwins/digital-twins-core/src/tracing.ts
- sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testDigitalTwins.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testRelationships.spec.ts
This PR has the following changes
- Result from running the lint:fix script 
- Updates to fix the docs with the `@param` tag to follow the expected format
- Fix the file name for the lint report
This brings down the linting errors from over 220 to about 85, contributing to https://github.com/Azure/azure-sdk-for-js/issues/12729 and fixes https://github.com/Azure/azure-sdk-for-js/issues/12958
> [Digital Twins] Run lint:fix and fix tsdoc lint errors

- sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
- sdk/appconfiguration/app-configuration/src/internal/helpers.ts
- sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts
- sdk/appconfiguration/app-configuration/src/internal/tracingHelpers.ts
- sdk/appconfiguration/app-configuration/test/internal/helpers.spec.ts
- sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
This PR fixes about 20 linting errors for the App Config package
- redundant use of await
- empty constructors
- no return types
- variables used before being declared
Related to #10774
> [App Config] Simple linting error fixes

- sdk/servicebus/service-bus/package.json
After @KarishmaGhiya's min-max PR and the reorganization, 
We don't have any tests at the top level, hence deleting the `test/*.spec.ts` from the mocha test file inclusion.
> [Service Bus] Fix `integration-test` command

- sdk/synapse/synapse-access-control/README.md
> [Synapse] Use mysynapse instead of personal resource name

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/package.json
Setting the release date for 1.2.0 🌞
Decided to use 1.2.0 since we added some new exports.
> [core-auth] 1.2.0 release date

- sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
- sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
- sdk/metricsadvisor/ai-metrics-advisor/src/createClientPipeline.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
- sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
Use `TokenCredential` from `core-auth` instead of `identity` package so that the latter need not be pulled into dependencies list from devDependencies in #13670
> Use TokenCredential from core-auth than identity

- sdk/test-utils/ci.yml
- sdk/test-utils/perfstress/package.json
- sdk/test-utils/perfstress/src/program.ts
Same change in .NET: Azure/azure-sdk-for-net#18071
> [Perf] Include running average in per-second output 

- common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts
- sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
Disallow `require` imports and ignore its use for keytar in identity after talking to @sadasant. Fixes https://github.com/Azure/azure-sdk-for-js/issues/4361.
> [ESLint Plugin] no require imports

- sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
Now that our docs pipeline respects the `@internal` tag, we don't need to add `@hidden` additionally
> [Form Recognizer] hidden tag not needed when internal is present

- sdk/communication/communication-chat/review/communication-chat.api.md
- sdk/communication/communication-chat/src/models/mappers.ts
- sdk/communication/communication-chat/src/models/models.ts
- sdk/communication/communication-chat/test/chatThreadClient.mocked.spec.ts
The current behavior for the SDK if message sender ID is not populated from service, the SDK will return an empty sender property. This PR is to change that to undefined instead of empty in that situation.
> [Communication]Set the sender as undefined instead of empty when sender id not populated

- sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
Apparently my commit that fixed the date was bizarrely not included, even though it was present in my fork.
> [ai-form-recognizer] Fixed the release date, again.

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/deserializationPolicy.ts
- sdk/core/core-client/src/index.ts
- sdk/core/core-client/src/serializationPolicy.ts
- sdk/core/core-client/src/serializer.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/src/utils.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-https/CHANGELOG.md
- sdk/core/core-https/package.json
- sdk/core/core-https/src/constants.ts
- sdk/core/core-https/src/nodeHttpsClient.ts
- sdk/core/core-https/src/pipeline.ts
- sdk/core/core-https/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-https/src/util/sanitizer.ts
- sdk/core/core-https/src/xhrHttpsClient.ts
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/core-xml/package.json
Among other things this PR is a replacement for #13615 after including changes from running `rush update --recheck`.
Rest of the changes are to fix linter errors in core-client and core-https packages, and enabling further regressions to break the build
Related to https://github.com/Azure/azure-sdk-for-js/issues/10775
> Increment version for new core packages, fix linter errors

- sdk/synapse/synapse-access-control/CHANGELOG.md
- sdk/synapse/synapse-artifacts/CHANGELOG.md
- sdk/synapse/synapse-artifacts/review/synapse-artifacts.api.md
- sdk/synapse/synapse-artifacts/src/artifactsClient.ts
- sdk/synapse/synapse-artifacts/src/index.ts
- sdk/synapse/synapse-managed-private-endpoints/CHANGELOG.md
- sdk/synapse/synapse-monitoring/CHANGELOG.md
- sdk/synapse/synapse-spark/CHANGELOG.md
Gets the changelogs ready for release. Also removes the Library functionality from artifacts at the request of the service team.
> [Synapse] Update changelog, remove Library

- common/config/rush/pnpm-lock.yaml
- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
This PR updates @azure/msal-node to 1.0.0-beta.6, updates the CHANGELOG and sets the release date for Identity's 1.2.3 patch release.
> [Identity] 1.2.3 release and msal-node Axios update

- sdk/anomalydetector/ai-anomaly-detector/package.json
- sdk/communication/communication-administration/package.json
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-common/package.json
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-sms/package.json
- sdk/core/core-client/package.json
- sdk/core/core-http/package.json
- sdk/core/core-https/package.json
- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/package.json
- sdk/eventgrid/eventgrid/src/constants.ts
- sdk/eventhub/event-hubs/package.json
- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/metricsadvisor/ai-metrics-advisor/package.json
- sdk/search/search-documents/package.json
- sdk/servicebus/service-bus/package.json
- sdk/template/template/package.json
- sdk/textanalytics/ai-text-analytics/package.json
- Update version dependency on `@azure/core-auth` to 1.2.0 now that it has released.  We depend on some new surface area from this release.
- Update CHANGELOG.md and version.
> [EventGrid] Prepare for v3.0.0-beta.4 Release

- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-admin/src/constants.ts
- sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-certificates/src/constants.ts
- sdk/keyvault/keyvault-certificates/src/generated/keyVaultClientContext.ts
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-keys/src/constants.ts
- sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/package.json
- sdk/keyvault/keyvault-secrets/src/constants.ts
- sdk/keyvault/keyvault-secrets/src/generated/keyVaultClientContext.ts
azure-sdk bot opened a PR bumping all the versions after release (#13713) 
But something isn't quite right, so while we investigate the issue with engSys I 
am opening this PR where I manually bumped the versions.
> [KeyVault] Bump KeyVault versions after release

- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/keysModels.ts
We define `keySize` in `createRsaKeyOptions` but we don't have to since it's already
defined in `createKeyOptions` which this inherits from. Having it defined in two places
adds confusion (see https://github.com/Azure/azure-sdk-for-js/pull/13522#discussion_r568994010 as an example).
This commit just removes the redefined parameter and updates the base parameter's
doc comment to be clearer.
Fixes #13589
> Remove keySize override from createRsaKeyOptions

- sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testDigitalTwins.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testRelationships.spec.ts
- sdk/digitaltwins/digital-twins-core/test/utils/testAuthentication.ts
This brings down the linter errors in the digital twins package from 84 to 42, mainly focusing on the below kinds
- variable shadowing
- functions with no return types
- == vs ===
Related to #13733
> [Digital Twins] Fix linting errors in test files

- sdk/core/core-https/review/core-https.api.md
- sdk/core/core-https/src/pipeline.ts
@deyaaeldeen pointed out that `httpsClient` doesn't get used in `PipelineOptions` today, since Pipelines are not strongly coupled to their `HttpsClient` (sendRequest takes it as an argument instead.)
This is great, but does clutter our story slightly for using `PipelineOptions` as the base of what client packages extend for providing additional convenience parameters. You can still absolutely pass a custom `httpsClient`, but that is now exclusively done through `ServiceClientOptions`.
I think this is one of those weird places where we did things two different ways previously. Thoughts?
> [core-https] Remove unused parameter

- sdk/eventhub/event-hubs/src/dataTransformer.ts
- sdk/eventhub/event-hubs/src/eventData.ts
- sdk/eventhub/event-hubs/src/eventDataBatch.ts
- sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
- sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/log.ts
- sdk/eventhub/event-hubs/src/util/connectionStringUtils.ts
This PR fixes the remaining TSDoc related linting errors in Event Hubs, thereby reducing the number of total linter problems from 70 to 38. Related to #12953 and #10777
@chradek Of the 38, errors are 18 and warnings are 20. Handing over the rest to your capable hands!
> [Event Hubs] Fix remaining TSDoc linting errors

- sdk/template/template/samples/javascript/package.json
- sdk/template/template/samples/typescript/package.json
This should help resolve the issues we're seeing with Smoke Tests. There's some magic there that only installs packages that are listed as a dependency somewhere in a package.json, and I had forgotten to add those here.
We'll also need to publish a new dev version of @azure/template, which I'll do manually once this is merged and then set up a nightly cycle for it (CC @mikeharder).
> Added @azure/template to its own samples' dependencies.

- sdk/servicebus/service-bus/src/connectionContext.ts
- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/messageSender.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/sender.ts
- sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
- sdk/servicebus/service-bus/src/util/crypto.browser.ts
- sdk/servicebus/service-bus/src/util/sasServiceClientCredentials.ts
- sdk/servicebus/service-bus/src/util/utils.ts
- sdk/servicebus/service-bus/test/public/utils/managementUtils.ts
This PR fixes over 90 linter errors around the `@returns` tag in Service Bus. Related to #10781
- Remove the type info in the `@returns` tag as this is redundant. TS tooling can figure out the typing info without needing us to have it add it here
- Remove the entire tag if it was not adding any information other than the type
> [Service Bus] Fix return tag to follow TSDoc

- sdk/search/search-documents/CHANGELOG.md
I released the search-documents SDK on Feb 11, 2021. The package was published successfully. But, there is one error:
```
Entry has no content. Please ensure to provide some content of what changed in this version.
```
You can see the error here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=732026&view=results
This PR is to fix the issue.
> Modify Changelog of Search Documents SDK

- sdk/monitor/monitor-opentelemetry-exporter/test-opentelemetry-versions.js
OT API keeps getting breaking changes, remoting canary check until OT code is stable, this is causing build issues
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=731707&view=results
> Remove canary check for OpenTelemetry versions

- eng/tools/rush-runner.js
- rush.json
Pass all dependency packages when testing any dependent package as a work around to get non-GA version required project to be built.
> Update rush version to latest to build transitive dependency correctly

- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/log.ts
- sdk/servicebus/service-bus/src/modelsToBeSharedWithEventHubs.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/src/util/connectionStringUtils.ts
This PR fixes the remaining errors around TSDoc 
Resolves #12955
Related to #10781
> [Service Bus] Fix remaining TSDoc errors

- sdk/identity/identity/test/manual/README.md
- sdk/identity/identity/test/manual/package.json
- sdk/identity/identity/test/manual/src/index.tsx
Updates the Identity InteractiveBrowserCredential to work with MSAL 1 and 2, meaning with the Implicit Grant flow and the Auth Code Flow. Also moved it from using Key Vault to use Service Bus, since Key Vault doesn't allow CORS.
Relies on this update: https://github.com/Azure/azure-sdk-for-js/pull/13263
Fixes #13307
> [Identity] Using service-bus for manual test with MSAL 2.0

- eng/ignore-links.txt
As part of https://github.com/Azure/azure-sdk-for-js/pull/13263 I added this link to the list of ignored links to make the build pass. I'm removing it now since it's not necessary anymore.
Fixes #13566
> [Identity] Remove ignored link

- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/rollup.base.config.js
- sdk/core/core-amqp/src/ConnectionContextBase.ts
- sdk/core/core-amqp/src/amqpAnnotatedMessage.ts
- sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
- sdk/core/core-amqp/src/errors.ts
- sdk/core/core-amqp/src/log.ts
- sdk/core/core-amqp/src/messageHeader.ts
- sdk/core/core-amqp/src/messageProperties.ts
- sdk/core/core-amqp/src/requestResponseLink.ts
- sdk/core/core-amqp/src/util/typeGuards.ts
- sdk/core/core-amqp/src/util/utils.ts
- sdk/core/core-amqp/test/browser/websockets.spec.ts
- sdk/core/core-amqp/test/context.spec.ts
- sdk/core/core-amqp/test/node/websockets.spec.ts
Fixes #10775 
Brings existing 19 issues down to 0 and makes lint errors fail CI.
Notable: I had to pull the websockets test out into separate browser and node.js files. This was because previously, we were using `require` to conditionally pull in the `ws` dependency for node.js, but the linter wants us to stop usage of `require`. There are dynamic `import` statements but not with es6 modules (it requires es2020 I believe). Separating the test by runtime let me use ES2015 imports to import `ws` just in node.js.
> [core-amqp] fix remaining eslint errors

- sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
Resolves #13452 
@deyaaeldeen, From what I recall we don't need to add the internal tag on private members anymore. That is what I am fixing here. Other than this there is only 1 occurence of `@internal` tag in digital twins package on the `createSpan` method which is valid
> [Digital Twins] internal tag not needed on private members

- sdk/formrecognizer/ai-form-recognizer/README.md
Closes #12915
Having `contentType` in the README examples isn't necessary because we support file type detection based on file magic.
> [ai-form-recognizer] Remove `contentType` from README examples

- sdk/communication/communication-phone-numbers/package.json
- sdk/communication/communication-phone-numbers/review/communication-phone-numbers.api.md
- sdk/communication/communication-phone-numbers/src/generated/src/models/index.ts
- sdk/communication/communication-phone-numbers/src/generated/src/models/mappers.ts
- sdk/communication/communication-phone-numbers/src/models.ts
- sdk/communication/communication-phone-numbers/swagger/README.md
- sdk/communication/communication-phone-numbers/test/lro.purchase.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.search.spec.ts
- sdk/communication/communication-phone-numbers/test/utils/mockHttpClients.ts
This PR sets `modelAsString` to false for all `x-ms-enum` properties so autorest does not treat them as extensible. This way we retain string unions for these types.
> [communication] disable extensible enums

- sdk/monitor/monitor-opentelemetry-exporter/test-opentelemetry-versions.js
Daily build keeps failing and the error is related to npm install executed in the tests that is conflicting with rush update install in the build machine
Related to #13758
> OpenTelemetry test versions to use specific folder

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/cbs.ts
- sdk/core/core-amqp/src/requestResponseLink.ts
- sdk/core/core-amqp/test/cbs.spec.ts
- sdk/core/core-amqp/test/requestResponse.spec.ts
- sdk/core/core-amqp/test/utils/createConnectionStub.ts
Fixes #9988 and part of #4422.
This PR updates 3 async methods to support cancellation:
- CbsClient.negotiateClaim()
- CbsClient.init()
- RequestResponseLink.create()
Note that I needed to update `RequestResponseLink.create()` to accept an `abortSignal` so that `CbsClient.init()` could be properly cancelled.
Updates to event hubs and service bus will come in a separate PR.
[API View link](https://apiview.dev/Assemblies/Review/ec633b2b71c14c81ba99a896f8af2400)
> [core-amqp] Update async methods to support cancellation

- sdk/core/core-client/package.json
- sdk/core/core-client/src/httpClientCache.ts
- sdk/core/core-https/CHANGELOG.md
- sdk/core/core-https/review/core-https.api.md
- sdk/core/core-https/src/accessTokenCache.ts
- sdk/core/core-https/src/defaultHttpsClient.browser.ts
- sdk/core/core-https/src/defaultHttpsClient.ts
- sdk/core/core-https/src/index.ts
- sdk/core/core-https/src/nodeHttpsClient.ts
- sdk/core/core-https/src/xhrHttpsClient.ts
- sdk/core/core-https/test/browser/xhrHttpsClient.spec.ts
- sdk/core/core-https/test/node/nodeHttpsClient.spec.ts
- sdk/eventgrid/eventgrid/package.json
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/test/perfstress/track-2/core-https.spec.ts
- sdk/tables/data-tables/package.json
Our ACS friends pointed out that we were leaking some implementation details of `HttpsClient`, so this PR cleans up the mess and updates consuming code in master.
> [core-https] Hide client constructors

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/review/event-hubs.api.md
- sdk/eventhub/event-hubs/src/eventProcessor.ts
- sdk/eventhub/event-hubs/src/util/constants.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/CHANGELOG.md
- sdk/eventhub/eventhubs-checkpointstore-blob/package.json
- sdk/eventhub/eventhubs-checkpointstore-blob/review/eventhubs-checkpointstore-blob.api.md
- sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
Resolves #9492 
This PR makes changes to the `@azure/event-hubs` and `@azure/eventhubs-checkpointstore-blob` packages to allow cancelling async methods on CheckpointStore implmenetations.
The `CheckpointStore` interface is defined in `@azure/event-hubs`, so it was updated such that every async method defined by the interface accepts an optional `options` parameter. The type of `options` is the `OperationOptions` exported by `@azure/event-hubs` and currently includes `abortSignal` and `tracingOptions`.
The `BlobCheckpointStore` implementation was updated such that every public async method now accepts the optional `options` parameter defined by the CheckpointStore interface. The `abortSignal` and `tracingOptions` are forwarded to any storage-blob calls that are made.
Per our guidelines, …
> [eventhubs-checkpointstore-blob] Updates CheckpointStore methods to support cancellation 

- sdk/.eslintrc.json
- sdk/eventhub/event-hubs/.eslintrc.json
Otherwise, we will get these errors because linted files must be included in the `tsconfig.json` file:
```
/home/dealmaha/repo/sdk/eventhub/event-hubs/test/perf/track-1/index.spec.ts
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test/perf/track-1/index.spec.ts.
The file must be included in at least one of the projects provided
/home/dealmaha/repo/sdk/eventhub/event-hubs/test/perf/track-1/receive.spec.ts
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test/perf/track-1/receive.spec.ts.
The file must be included in at least one of the projects provided …
```
> [Event Hub] Ignore test/perf/track-1 when linting

- sdk/anomalydetector/ai-anomaly-detector/README.md
- sdk/eventgrid/eventgrid/README.md
- sdk/formrecognizer/ai-form-recognizer/README.md
- sdk/metricsadvisor/ai-metrics-advisor/README.md
- sdk/mixedreality/mixedreality-authentication/README.md
- sdk/search/search-documents/README.md
- sdk/tables/data-tables/README.md
- sdk/textanalytics/ai-text-analytics/README.md
The README.md files in our repository has a link for ```API Reference Documentation```. In some of the SDKs, they are pointing to the docs in github io. This is ok for initial release. But, after the initial release, the link must be updated to the location in msdocs. 
I have updated the links in this PR.
@ramya-rao-a Please review and approve.
> Fix the links of API Reference Documentation

- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/test/perf/track-2/receive.spec.ts
- sdk/eventhub/event-hubs/test/perf/track-2/send.spec.ts
- sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts
With #13826 fixing the promise executor related linter errors, this PR fixes the remaining lint errors in Event Hubs!
> [Event Hubs] Fix remaining lint errors

- sdk/monitor/monitor-opentelemetry-exporter/test/common/scenario/basic.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/functional/trace.test.ts
Fixes some low hanging fruit in the test that's breaking the "js - opentelemetry-exporter-azure-monitor - tests" in the 'functional-tests' stage.
There is still a break where it appears the output structure changed, but I haven't gotten a chance to look into it.
> [monitor] Fix some of the more obvious breakages (CI is still broken afterwards, however)

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/abort-controller/package.json
PR #12793 adds downlevel dts files but didn't pack them. This PR fixed that.
> [core-abort-controller] pack downlevel dts files

- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/test/internal/utils.spec.ts
- sdk/eventhub/event-hubs/test/public/utils/testUtils.ts
Fixes the last error in Event Hubs package and allows future linter errors to break the build.
We need to fix up the checkpoint store package before we can close the related issue #10777
> [Event Hubs] Allow linter errs to break build

- sdk/identity/identity/README.md
This PR is intended to help portray a better message to our customers about the DefaultAzureCredential. This credential is intended to be used to get things started, and not as the universal way to go over time. I took this text from something Charles Lowell sent me on Teams 😁 I loved the phrasing!
Related to: #13799
> [Identity] DefaultAzureCredential clarification

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/interactive-browser-credential.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/defaultAzureCredential.browser.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
- sdk/identity/identity/src/index.ts
This PR:
- Makes the DefaultAzureCredential just throw an error.
- Makes the InteractiveBrowserCredential for browsers to require the clientId.
- Updates the docs accordingly.
> [Identity] InteractiveBrowserCredential for browser requires a client ID

- sdk/servicebus/service-bus/test/internal/batchReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/operationOptionsForATOM.spec.ts
- sdk/servicebus/service-bus/test/internal/renewLock.spec.ts
- sdk/servicebus/service-bus/test/internal/retries.spec.ts
- sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/internal/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/streamingReceiverSessions.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/atomXml.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/autoLockRenewer.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/sender.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/tracing.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/unittestUtils.ts
- sdk/servicebus/service-bus/test/perf/track-2/sbBase.spec.ts
- sdk/servicebus/service-bus/test/public/atomManagement.spec.ts
- sdk/servicebus/service-bus/test/public/invalidParameters.spec.ts
- sdk/servicebus/service-bus/test/public/propsToModify.spec.ts
- sdk/servicebus/service-bus/test/public/renewLockSessions.spec.ts
- sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts
- sdk/servicebus/service-bus/test/public/sessionsTests.spec.ts
- sdk/servicebus/service-bus/test/public/utils/envVarUtils.ts
- sdk/servicebus/service-bus/test/public/utils/managementUtils.ts
- sdk/servicebus/service-bus/test/public/utils/testutils2.ts
This PR fixes about 150 linter errors and warnings in the test files of the Service Bus package.
Use `Hide whitespace changes" option to look at the real impacting changes
Related to #10781
> [Service Bus] Fix linting problems in test files

- sdk/servicebus/service-bus/test/internal/batchReceiver.spec.ts
Was looking at this test to compare the scenario during sessions as part of #8875.
Talked to @richardpark-msft and we agreed to simplify it as shown in the PR with slightly more meaningful comments.
> [Service Bus] Simplifying "disconnect" during drain test - for non-sessions

- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
- sdk/keyvault/keyvault-secrets/src/secretsModels.ts
- sdk/keyvault/keyvault-secrets/src/transformations.ts
- sdk/keyvault/keyvault-secrets/test/internal/transformations.spec.ts
- sdk/keyvault/keyvault-secrets/tsconfig.json
- Deprecate `secretProperties.keyId` and replace it with `secretProperties.certificateKeyId`
- Remove `dom` from tsconfig
`secretProperties.keyId` being a URL is the only reason we need `dom` lib in this library.
Even though it has never been populated we cannot remove it because we might break 
someone's compilation (although it would have never worked at runtime). 
Instead we'll deprecate it, note that it will always be undefined, and make it an any so
we can remove the dependency on `dom`. 
Refer to #9639 for previous work in this area.
Resolves #10726
> [KeyVault] - Replace `keyId: URL` with `certificateKeyId: string` 

- sdk/core/core-client/src/serializer.ts
We've moved from `() => NodeJS.ReadableStream` to `NodeJS.ReadableStream` in `RequestBodyType`. This change updates the
condition for checking this case.
> [Core-client] Update the stream check in serialization

- sdk/core/core-https/CHANGELOG.md
- sdk/core/core-https/src/nodeHttpsClient.ts
There's some difference between the previous `tunnel.HttpsOverHttpsOptions` and
current `HttpsProxyAgentOptions`, in particular the former's `host` property
includes both the protocol and the host parts, while the later have separate
`host` and `protocol` properties.
> [core-https] Fix proxy issue

- common/tools/add-identity-mgmt-lib.js
Adds a script to add support for `@azure/identity` in the management-plane libraries. The script results in changes similar to that in https://github.com/Azure/azure-sdk-for-js/pull/13512. Although the code generator (v4) already can generate libraries with support for `@azure/identity` (the version in the master branch), the goal of this script is to help management plane libraries owners add the identity support immediately without having to use it, so they do not have to worry about finding the exact swagger version used to generate their current libraries.
Example: `node common/tools/add-identity-mgmt-lib.js "../../sdk/iotcentral/arm-iotcentral/"`
> Add a script to add support for identity in mgmt libraries

- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/index.ts
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/src/pipeline.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/eventGridClient.ts
- sdk/tables/data-tables/review/data-tables.api.md
- sdk/tables/data-tables/src/TableClient.ts
- sdk/tables/data-tables/src/TableServiceClient.ts
- sdk/tables/data-tables/src/generated/generatedClientContext.ts
- sdk/tables/data-tables/src/models.ts
The two main changes here:
- Rename `ClientPipelineOptions` to `InternalClientPipelineOptions` to reflect that this extends the quasi-private `InternalPipelineOptions` interface.
- Create a new interface for convenience clients to use as their base options type: `CommonClientOptions`
- Have `ServiceClientOptions` extend `CommonClientOptions` so the two worlds can unify at last
The rest is just updating downstream packages.
> [core-client] Unify PipelineOptions and ServiceClientOptions

- eng/scripts/Language-Settings.ps1
- eng/tools/versioning/VersionUtils.js
This PR fixes the JS script so it can correctly take a
package name and find it as well as update the associated
versions.
Also updated the script to clean-up some of the ouptut
from the changelog script it calls on the behalf of the user.
> Fix Prepare-Release script

- sdk/mixedreality/mixedreality-authentication/tests.yml
- The TestMinMax flag causes a couple of extra jobs to be run that fail due to bad configuration. I don't see most other libraries enabling it, so I'm going to disable it. I don't feel too bad about this since both the min and max jobs appear to run against Node 12, which we already have a test job to validate.
> Disable TestMinMax

- sdk/servicebus/service-bus/src/connectionContext.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/13990
"Number of receivers" returned is not a number. It was not a fatal bug since we only relied on its existence.
> [Service Bus] (minor) Bug Fix: `getNumberOfReceivers` helper method

- common/config/rush/pnpm-lock.yaml
- sdk/mixedreality/mixedreality-authentication/karma.conf.js
- sdk/mixedreality/mixedreality-authentication/package.json
karma-remap-istanbul is an undesirable dependency we've been trying to remove from the tree. This PR does the same dance we've performed in other libraries to make it unnecessary.
I have used https://github.com/Azure/azure-sdk-for-js/pull/13466 as a reference
Thanks @xirzec !
> [MixedReality] Update karma to not use karma-map-istanbul

- sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
- sdk/appconfiguration/app-configuration/src/internal/tracingHelpers.ts
- sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
Updating AppConfiguration to point to core-tracing and remove all code that was attempting to manage span parenting.
This also mean I could finally gut Spanner<T> - it's now down to just being a single trace<> function that wraps calling a function and handling calling .setSpanStatus() on error.
> [app-config] Use createSpan from core-tracing

- sdk/core/core-amqp/src/log.ts
- sdk/core/core-amqp/src/retry.ts
- sdk/core/core-amqp/src/util/checkNetworkConnection.browser.ts
- sdk/core/core-amqp/src/util/checkNetworkConnection.ts
- sdk/core/core-amqp/src/util/runtimeInfo.browser.ts
- sdk/core/core-amqp/src/util/runtimeInfo.ts
- sdk/core/core-amqp/src/util/utils.ts
- sdk/core/core-client/src/base64.ts
- sdk/core/core-client/src/interfaceHelpers.ts
- sdk/core/core-client/src/operationHelpers.ts
- sdk/core/core-client/src/serializationPolicy.ts
- sdk/core/core-client/src/utils.ts
- sdk/core/core-crypto/src/sha256.browser.ts
- sdk/core/core-crypto/src/utils/base64.browser.ts
- sdk/core/core-crypto/src/utils/hex.ts
- sdk/core/core-crypto/src/utils/utf8.browser.ts
- sdk/core/core-http/src/operationSpec.ts
- sdk/core/core-https/src/util/helpers.ts
- sdk/core/core-https/src/util/sanitizer.ts
- sdk/core/core-https/src/util/userAgent.ts
- sdk/core/core-https/src/util/userAgentPlatform.browser.ts
- sdk/core/core-https/src/util/userAgentPlatform.ts
- sdk/core/core-lro/src/poller.ts
- sdk/core/core-tracing/src/tracers/opencensus/openCensusTraceStateWrapper.ts
- sdk/core/logger/review/logger.api.md
- sdk/core/logger/src/index.ts
This PR has the below changes related to #13449
- Remove `@hidden` tag where `@internal` is already used
- Replace `@hidden` with `@internal` for members not exported from index.ts
> [Core] Use internal instead of hidden where applicable

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/abort-controller/src/AbortSignal.ts
- sdk/core/abort-controller/test/aborter.spec.ts
Fixes #13985
See the issue linked above for a RCA on the bug this fixes.
When using the @azure/abort-controller package, attaching event listeners to an abortSignal that remove themselves after being invoked can prevent other listeners attached to the same signal from being invoked.
With this update, when abort() is called, we create a copy of the listeners array that isn't mutated when removeListener() is called on the abortSignal. This ensures that listeners are invoked in the same order they were added.
> [abort-controller] listeners that self-remove from abortSignal when invoked no longer prevent other listeners from being invoked

- eng/scripts/Language-Settings.ps1
- sdk/core/abort-controller/package.json
- sdk/core/abort-controller/review/abort-controller.api.md
Enable API extractor for abort controller and also check API extract file path
> Verify api file path and enable api-extractor for abort-controller

- sdk/storage/storage-blob-changefeed/test/utils/testutils.common.ts
- sdk/storage/storage-blob/test/encrytion.spec.ts
- sdk/storage/storage-blob/test/utils/testutils.common.ts
- sdk/storage/storage-file-datalake/test/utils/index.browser.ts
- sdk/storage/storage-file-datalake/test/utils/testutils.common.ts
- sdk/storage/storage-file-share/test/utils/index.browser.ts
- sdk/storage/storage-file-share/test/utils/testutils.common.ts
- sdk/storage/storage-queue/test/node/emulator-tests.spec.ts
- sdk/storage/storage-queue/test/utils/index.browser.ts
- sdk/storage/storage-queue/test/utils/testutils.common.ts
This PR fixes up the latest linter rule we added to our linter.
Found this when running the `lint:fix` script on the storage packages
More details are in #13873
Related to #10782
> [Storage] Fix the self vs window rule in storage packages

- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
- sdk/textanalytics/ai-text-analytics/src/generated/models/parameters.ts
- sdk/textanalytics/ai-text-analytics/swagger/README.md
Regenerate using the swagger in https://github.com/Azure/azure-rest-api-specs/pull/13209 that makes sure the naming for the `StringIndexType` is consistent between its uses as a method parameter and as an action description property.
> [Text Analytics] Regenerate using an updated swagger for StringIndexType

- sdk/servicebus/service-bus/src/diagnostics/instrumentServiceBusMessage.ts
- sdk/servicebus/service-bus/src/diagnostics/tracing.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/test/internal/unit/tracing.spec.ts
When we were instrumenting spans we wouldn't pay attention to whether we were currently recording or not, which could lead to us creating a bunch of empty/null spans and trying to add them as links to the span for our batches.
Rather than do that I just check (when we instrument) if the span we created is recording and if not don't add it.
Fixes #13049
> [service-bus] Don't create unneeded empty spans when linking in message batches.

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/recordings/node/api_key_textanalyticsclient_lros_health/recording_input_strings.js
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/analyzeHealthcareEntitiesResult.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
The service discovers relationships between healthcare entities and returns them as a list. This PR exposes this list after dereferencing the JSON pointers for healthcare entities.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/14035
> [Text Analytics] Expose healthcare relationships

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeHealthcareEntities.js
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeHealthcareEntities.ts
- sdk/textanalytics/ai-text-analytics/src/analyzeHealthcareEntitiesResult.ts
- sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts
It has been agreed on between the text analytics crew to remove this property. The user can use the new `entityRelations` to get the same information.
> [Text Analytics] Remove relatedEntities property from healthcare entities

- sdk/servicebus/service-bus/test/internal/unit/atomXml.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/testConstants.ts
- sdk/servicebus/service-bus/test/public/atomManagement.spec.ts
- sdk/servicebus/service-bus/test/public/testConstants.ts
CredScan is computing hashes to identify locations of possible sensitive data.
Changes unrelated to the key values can cause the hashes to change. This PR
extracts key values into constants in a separate file so the scan results remain
stable which would make suppression easier.
> [service-bus][test] extract key values into constants

- sdk/attestation/attestation/tests.yml
- sdk/containerregistry/container-registry/tests.yml
- sdk/eventgrid/eventgrid/tests.yml
- sdk/eventhub/event-processor-host/tests.yml
- sdk/mixedreality/mixedreality-authentication/tests.yml
- sdk/schemaregistry/schema-registry-avro/tests.yml
- sdk/schemaregistry/schema-registry/tests.yml
- sdk/storage/storage-blob/tests.yml
- sdk/storage/storage-file-datalake/tests.yml
- sdk/storage/storage-file-share/tests.yml
- sdk/storage/storage-queue/tests.yml
This PR fixes a few gaps I missed in my cross section testing of https://github.com/Azure/azure-sdk-for-js/pull/13886, now that all nightly pipelines have had a chance to run.
> Fix broken live test configurations

- sdk/metricsadvisor/ai-metrics-advisor/test/public/keyRotation.spec.ts
We don't need real key values for testing this functionality.
> [MetrisAdvisor][Test] use simple values in key rotation unit tests

- eng/scripts/Language-Settings.ps1
Add alternative code paths depending on parameters which allows for coming changes to common tools.
This change is solely intended to prevent breaking the build while making changes to common across various repos.
Sample Build https://dev.azure.com/azure-sdk/internal/_build/results?buildId=756241&view=results
> Add Alternative Code Paths Depending on Parameters

- sdk/communication/communication-administration/tests.yml
Another live test that needs to exclude min/max testing, now that it's opt-out.
> Exclude min/max testing for communication-administration live tests

- sdk/communication/communication-identity/samples/javascript/issueToken.js
- sdk/communication/communication-identity/samples/javascript/revokeTokens.js
In #13819, `issueToken` got renamed to `getToken`
While the TS samples were updated, the JS ones were missed
Fixes #14057
> Update JS samples: issueToken() is now getToken()

- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/index.ts
Implements new naming for assertions based on @mssfang suggestions. I am using the prefix Healthcare to conform to the naming for healthcare types. I am also fixing a small issue in the definition for `Certainty` (fixed in the swagger https://github.com/Azure/azure-rest-api-specs/pull/13247).
> [Text Analytics] Better names for assertions

- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/index.ts
This rename is based on the discussion here: https://github.com/Azure/azure-sdk-for-js/pull/14070#discussion_r586739488.
> [Text Analytics] Rename assertion types to not use the healthcare prefix

- sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_single_entities_linking_action.json
- sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_single_entities_linking_action.js
- sdk/textanalytics/ai-text-analytics/src/analyzeBatchActionsResult.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
- sdk/textanalytics/ai-text-analytics/src/util.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
This creates an SDK workaround for a bug in the service that is tracked by https://github.com/Azure/azure-sdk-for-js/issues/14079. The bug is basically the service expects `modelVersion` so we set it implicitly in the SDK if the customer did not do so. A test case is added.
> [Text Analytics] Fix bugs for entity linking actions

- sdk/eventgrid/eventgrid/MIGRATION.md
Forgot to actually add the link to the README.md for the new package in the migration guide. This commit fixes that.
> [EventGrid] Fill in link in MIGRATION.md

- sdk/textanalytics/perf-tests/text-analytics/test/detectLanguage.spec.ts
- sdk/textanalytics/perf-tests/text-analytics/tsconfig.json
Otherwise, ts-node will fail. I also set the default number of documents to 1k.
> [Text Analytics] Fix a compiler option in perf test

- sdk/tables/data-tables/package.json
- sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_handle_sub_request_error.json
- sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_send_a_set_of_create_batch_operations.json
- sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_send_a_set_of_delete_batch_operations.json
- sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_send_a_set_of_update_batch_operations.json
- sdk/tables/data-tables/src/TableBatch.ts
- sdk/tables/data-tables/src/utils/baseBatchHeaders.ts
- sdk/tables/data-tables/src/utils/batchHeaders.browser.ts
- sdk/tables/data-tables/src/utils/batchHeaders.ts
- sdk/tables/data-tables/test/integration/batch.spec.ts
Fixes #11603
`Accept-Charset` and `Connection` headers are marked as `unsafe` in some browsers. Fixing this issue by only adding them if running in Node
> [Tables] Fix and enable Batch browser tests

- eng/tools/versioning/set-dev.js
Alpha version dependency resolves true for beta and preview versions as well. Update dependency to "dev" tag to use latest alpha version.  
Also added changes to avoid updating dependency for private packages and devDependency packages.
> Set dev tag as depenency and update version for published

- sdk/formrecognizer/ai-form-recognizer/src/internalModels.ts
- sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/recognitionPoller.ts
- sdk/formrecognizer/ai-form-recognizer/test/public/node/formrecognizerclient.spec.ts
Closes #13880
This fixes a bug where Form Recognizer wasn't showing error codes for errors that are received during analysis polling and adds assertions to existing tests to make sure it stays that way.
A total fluke of structural typing and optional fields let me apply the wrong return type to the polling function, so I removed that type as well because it's not used.
GA releases of this package are **not** affected, as this was introduced as part of the LRO refactor for the first 3.1.0 beta, so a hotfix is not needed.
> [ai-form-recognizer] Bugfix for error codes not being shown correctly.

- common/config/rush/pnpm-lock.yaml
- rush.json
- sdk/eventgrid/perf-tests/eventgrid/README.md
- sdk/eventgrid/perf-tests/eventgrid/package.json
- sdk/eventgrid/perf-tests/eventgrid/sample.env
- sdk/eventgrid/perf-tests/eventgrid/test/index.spec.ts
- sdk/eventgrid/perf-tests/eventgrid/test/sendCloudEvents.spec.ts
- sdk/eventgrid/perf-tests/eventgrid/tsconfig.json
The EventGrid library is a fairly lightweight wrapper over the
service, but we would like to have a least one performance test so we
have a baseline to compare things with going forward.
This test just sends events using the CloudEvents schema to an
endpoint. This operation was choosen because it has the most work
being done by the SDK (there's a small level of translation that needs
to be done to adapt the user facing model to what the service expects
on the wire).
> [EventGrid] Add Performance Test

- sdk/core/logger/CHANGELOG.md
- sdk/core/logger/rollup.base.config.js
- sdk/core/logger/src/log.browser.ts
- sdk/core/logger/test/browser/logger.spec.ts
Use the corresponding console log functions for each log level when using the default log function.
Fixes #14099
> [logger] Split up logging in the browser

- sdk/keyvault/keyvault-admin/sample.env
- sdk/keyvault/keyvault-admin/samples/javascript/README.md
- sdk/keyvault/keyvault-admin/samples/javascript/sample.env
- sdk/keyvault/keyvault-admin/samples/typescript/README.md
- sdk/keyvault/keyvault-admin/samples/typescript/sample.env
- sdk/keyvault/keyvault-admin/test/README.md
- sdk/keyvault/keyvault-certificates/test/README.md
- sdk/keyvault/keyvault-keys/samples/javascript/README.md
- sdk/keyvault/keyvault-keys/samples/typescript/README.md
- sdk/keyvault/keyvault-keys/test/README.md
- sdk/keyvault/keyvault-secrets/samples/typescript/README.md
- sdk/keyvault/keyvault-secrets/test/README.md
- sdk/test-utils/recorder/README.md
To line up well with other services, and because Managed HSM has a different
URI pattern (but same client library) as KeyVault we started using KEYVAULT_URI
instead of KEYVAULT_NAME.
This commit just cleans up some of the documentation and instructions and removes
the now obsolete KEYVAULT_NAME.
> [KeyVault] Replace KEYVAULT_NAME with KEYVAULT_URI in docs

- sdk/mixedreality/mixedreality-authentication/package.json
This PR temporarily removes mixed reality from the global smoke test samples tests, as the underlying azure resources for these samples require a region different from the default one used, and currently there is no mechanism to support region overrides. Once region override support is added, we can re-include these samples.
See https://github.com/Azure/azure-sdk-for-js/issues/14059
> Skip mixed reality samples temporarily until region overrides are supported

- sdk/textanalytics/ai-text-analytics/CHANGELOG.md
- sdk/textanalytics/ai-text-analytics/README.md
- sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_statistics.json
- sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_statistics.js
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeBatchActions.js
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeBatchActions.ts
- sdk/textanalytics/ai-text-analytics/src/analyzeBatchActionsResult.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
- sdk/textanalytics/ai-text-analytics/src/util.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
This PR fixes several issues:
- when the user asks for statistics, they did not get it because the request parameter did not make it to the status endpoint. This PR fixes this issue by sending the `includeStatistics` parameter to the status endpoint
- removes statistics from the top-level response because the service does not return it. See issue:https://github.com/Azure/azure-sdk-for-js/issues/14139
- the LRO's onProgress function was broken because the input callback was only applied when the LRO finished which defeats the purpose
- the new core lib parameters (e.g. `onResponse`) were not being handled correctly
- updates the samples with the includeStatistics parameter
> [Text Analytics] Fix a bug for returning stats for analyze

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/rollup.base.config.js
- sdk/identity/identity/src/credentials/defaultAzureCredential.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
- sdk/identity/identity/test/authTestUtils.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
Take notice that the target branch for this PR is: hotfix/identity_1.2.4.
This PR intends to update the code available at the Identity release 1.2.3 to include two bug fixes:
- "[Identity] DefaultAzureCredential should properly handle the managedldentityClientId optional parameter #13973", which fixed customer issue #13894
- "[Identity] ManagedIdentityCredential fix #13919", which fixed customer issue #13872
I'm only concerned because the latest beta was 1.2.4-beta.1, and this hotfix is 1.2.4. So I'm guessing I'll need to mention that the beta changes were moved to 1.2.5-beta.1?
I've set the release date for this hotfix to be: 2021-03-08, let me know if that's ok.
In any case, feedback appreciated!
> [Identity] Hotfix 1.2.4

- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
Because this parameter is not currently supported by the service in analyze and we as the crew decided to disable it. It also fixes the casing for the certainty enum to match what we get from the service.
> [Text Analytics] Disable pii categories for analyze

- sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_operation_metadata.json
- sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_operation_metadata.js
- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
- sdk/textanalytics/ai-text-analytics/src/lro/analyze/poller.ts
- sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
- sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
I can not remember why I took it out here: https://github.com/Azure/azure-sdk-for-js/pull/13933. This PR adds the option `displayName` back to `beginAnalyzeBatchActions`.
> [Text Analytics] Add displayName back for analyzeBatchActions

- sdk/textanalytics/ai-text-analytics/README.md
The healthcare endpoint doesn't respect the value passed in under the `model-version` query param, it only uses value "latest". Service-side issue: https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/9479280.
> [Text Analytics] Adding the model version issue to known issues section

- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-admin/recordings/node/keyvaultaccesscontrolclient_role_definitions_upsertroledefinition/recording_errors_when_name_is_not_a_valid_guid.js
- sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
- sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
- sdk/keyvault/keyvault-admin/src/lro/selectiveRestore/operation.ts
- sdk/keyvault/keyvault-admin/test/public/accessControlClient.spec.ts
- sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts
- Use the status field instead of presence of errors for determining whether the LRO failed
- Unpend the "failed if custom role not guid" test
- Pend the full restore test in live mode
- Using the status field is more reliable and should be the field to decide whether there's an error. The actual error _might_ come in under statusDetails but the status field should be accurate
- There's a service-issue affecting restores and it's impacting our live test pipeline.
Resolves #13632
> [KeyVault] - Use status field for LRO error conditions

- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/karma.conf.ts
- sdk/core/core-http/src/credentials/accessTokenRefresher.ts
- sdk/core/core-http/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-http/test/policies/bearerTokenAuthenticationPolicyTests.ts
PR Azure/azure-sdk-for-js#13736 introduced a bug that ai-form-recognizer tests catch. Multiple parallel requests when there is no token or when the token has expired will result in request failures. I made a PR to fix this: https://github.com/Azure/azure-sdk-for-js/pull/14140 but while we discuss approaches, ai-form-recognizer should be unblocked.
> Revert "[core-http] Token refresher fix"

- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/package.json
- sdk/core/core-rest-pipeline/src/constants.ts
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/core-xml/package.json
- sdk/eventgrid/eventgrid/package.json
- sdk/storage/perf-tests/storage-blob/package.json
- sdk/storage/storage-blob/package.json
- sdk/tables/data-tables/package.json
- sdk/textanalytics/ai-text-analytics/package.json
This PR updates core v2 libraries' version number to 1.0.0 and update the release date in CHANGELOG files.
> [core v2] prepare for GA release

- common/config/rush/pnpm-lock.yaml
- sdk/communication/communication-phone-numbers/karma.conf.js
- sdk/communication/communication-phone-numbers/package.json
karma-remap-istanbul is an undesirable dependency we've been trying to remove from the tree. This PR does the same dance we've performed in other libraries to make it unnecessary.
I have used https://github.com/Azure/azure-sdk-for-js/pull/13466 as a reference
> [Communication] Update karma to not use karma-map-istanbul

- sdk/eventgrid/perf-tests/eventgrid/package.json
- sdk/textanalytics/perf-tests/text-analytics/package.json
Perf test projects for eventgrid and text-analytics are depending on a released version of the packages.
This PR updates it to depend on the versions on master instead.
> Perf projects should depend on the versions present in master branch

- sdk/storage/perf-tests/storage-blob/package.json
- sdk/storage/perf-tests/storage-file-datalake/package.json
- sdk/storage/perf-tests/storage-file-share/package.json
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
- sdk/storage/storage-file-datalake/src/generated/src/operations/pathOperations.ts
- sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/review/storage-queue.api.md
- sdk/storage/storage-queue/src/generated/src/models/index.ts
- sdk/storage/storage-queue/src/generated/src/models/parameters.ts
- sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
- sdk/storage/storage-queue/src/generatedModels.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
Upgraded REST API version to 2020-06-12 in storage-queue/storage-file-share.
Updated package versions and change logs to prepare for release.
> Preparing storage packages GA release for STG 76 features

- sdk/core/core-client/src/serializationPolicy.ts
If the body contains just false, this check will confuse it with the body being non existent. This PR fixes this issue.
> [core-rest-pipeline] Fix serialization of body of false

- sdk/cosmosdb/cosmos/package.json
The package.json for the project needs to have the identity package
within its dependencies, not the dev dependencies, or else it will
cause problems when building in TypeScript projects.
This:
- moves the package from dev deps to deps
- moves a types package from deps to dev deps
Note, there is reference to a library called @azure/dev-tool that
is not published, so I am unable to run tests.
See also:
- https://github.com/Azure/azure-sdk-for-js/issues/13202
- https://github.com/Azure/azure-sdk-for-js/issues/14236
> Cosmos: project depends on azure/identity

- sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
- sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
This change is needed to match the current service's response. The swagger is being updated in https://github.com/Azure/azure-rest-api-specs/pull/13361.
> [Text Analytics] Use camel case in assertion response strings

- common/smoke-test/Initialize-SmokeTests.ps1
If there are no javascript samples detected, the Initialize-SmokeTests.ps1 script does not handle this gracefully:
```
VERBOSE: Detecting samples...
Deploy-TestResources: /home/ben/sdk/azure-sdk-for-js/common/smoke-test/Initialize-SmokeTests.ps1:271
Line |
271 |    $configs = Deploy-TestResources $deployManifest
|                                    ~~~~~~~~~~~~~~~
| Cannot bind argument to parameter 'deployManifest' because it is null.
```
This is failing the cosmosdb release pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=778657&view=logs&j=6264c357-0dbd-550f-f8cc-1728c68e778a&t=964ac695-12eb-5bfc-a6f5-7011b6c06592
> Avoid null error when no samples are found

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/CosmosClientOptions.ts
Related to #14236 
/cc @zfoster 
The `@azure/core-auth` package exposes the `TokenCredential` type that `@azure/identity` credentials implement. We try to avoid depending on `@azure/identity` in our packages directly because:
1. User's should depend on it in their own projects directly so they can instantiate the credentials they want to use. This way they can also use the version of identity they want versus what our package pulls in.
2. Many packages offer an alternative auth mechanism, or a customer may have a custom TokenCredential implementation that doesn't need identity, so this avoids pulling in identity unnecessarily.
This change moves identity back as a dev dependency (we still want it for testing!) and depends on core-auth for the TokenCredential instead.
> [cosmos] use TokenCredential from core-auth instead of identity

- sdk/textanalytics/ai-text-analytics/package.json
- sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeHealthcareEntities.js
- sdk/textanalytics/ai-text-analytics/samples/javascript/recognizePii.js
- sdk/textanalytics/ai-text-analytics/samples/typescript/package.json
- sdk/textanalytics/ai-text-analytics/samples/typescript/src/recognizePii.ts
- sdk/textanalytics/ai-text-analytics/samples/typescript/tsconfig.json
This PR does the following:
- updates samples so the typescript ones can run with `node8` with no issues by setting the compilation target to `ES6`.
- fixes the recognize PII sample where a the behavior for the protected healthcare information parameter changed in the service. This PR updates the input text used with this parameter to one that does not have protected healthcare information according to the new update. More information can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/named-entity-types?tabs=personal#government-and-countryregion-specific-identification). Also, this is the output of the updated sample:
```
Running recognizePii sample
The redacted text is "My phone number is ********" and found the following PII entities
- …
```
> [Text Analytics] Fix samples

- sdk/core/core-client/test/serializationPolicy.spec.ts
Adds a test case for a JSON body that is
- false
- null [according to the spec](https://www.json.org/json-en.html)
Those tests were missed in https://github.com/Azure/azure-sdk-for-js/pull/14218.
> [core-client] Add a test case for serializing a false body

- sdk/core/core-client/src/urlHelpers.ts
- sdk/core/core-client/test/urlHelpers.spec.ts
This is caught by autorest typescript tests that it is a valid scenario to send
requsts with query parameters having empty values. This PR changes the behavior
to match core-http's.
> [core-client] Allow setting empty query parameter values

- eng/tools/versioning/set-dev.js
Version requirement was set to `dev` tag to use latest daily dev version for dependency packages but this has caused an issue when there is a breaking change from last published dev version. Tag also refers package in npm and this causes additional issue if dev version package is not yet available on npm.
Ideal solution is to pin correct alpha version instead of version range. This PR is to revert current changes to resolve CI failures.
> Revert set dev version code

- sdk/communication/communication-phone-numbers/review/communication-phone-numbers.api.md
- sdk/communication/communication-phone-numbers/src/lroModels.ts
- sdk/communication/communication-phone-numbers/src/phoneNumbersClient.ts
- sdk/communication/communication-phone-numbers/test/lro.purchase.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.release.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.search.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.update.spec.ts
This PR removes the `pollInterval` and `resumeFrom` lro options as they are not currently supported by the generated poller.
> [communication] remove unsupported lro options

- common/tools/add-identity-mgmt-lib.js
The script as is hardcodes the operation name in the sample in the readme file to be `apps.get` which is not available in every package. This PR updates the script so that it detects the operation name from the package's existing README.md file.
> [Mgmt identity script] Detect operation name

- sdk/communication/communication-administration/package.json
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-common/package.json
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-phone-numbers/package.json
- sdk/communication/communication-sms/package.json
This PR updates the packages under `sdk/communication` to use the same formatting script as other packages in this repo. 
This is needed for us to complete the work in #13983 so that unformatted files are caught during build rather than via the git commit hook
cc @deyaaeldeen, @KarishmaGhiya
> [Communication] Use the standard format script

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-rest-pipeline/package.json
- sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
- sdk/core/core-rest-pipeline/src/interfaces.ts
- sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- sdk/core/core-rest-pipeline/src/pipelineRequest.ts
- sdk/core/core-rest-pipeline/src/xhrHttpClient.ts
- sdk/core/core-rest-pipeline/test/browser/xhrHttpClient.spec.ts
- sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts
Add new option to allow insecure connections and support calling HTTP URLs, including calling through proxies.
This also adds security checks in the browser version for parity.
> [core-rest-pipeline] Add opt-in HTTP support

- eng/pipelines/templates/steps/use-node-test-version.yml
msal-node-extension has native dependency in the same way keytar package has. So this package needs to be reinstalled before running test. PR modified current native dep install code to support more dependency.
> Update native dependency install to install msal-node-extensions

- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/tools/eslint-plugin-azure-sdk/package.json
The linter test suite fails using node8 in this PR: https://github.com/Azure/azure-sdk-for-js/pull/13162. ESLint v7.15 supports node10.12.0 and up only.
> [ESLint plugin] Upgrade node to v10

- sdk/communication/communication-phone-numbers/CHANGELOG.md
- sdk/communication/communication-phone-numbers/review/communication-phone-numbers.api.md
- sdk/communication/communication-phone-numbers/src/models.ts
- sdk/communication/communication-phone-numbers/src/phoneNumbersClient.ts
- sdk/communication/communication-phone-numbers/src/utils/logger.ts
- sdk/communication/communication-phone-numbers/src/utils/tracing.ts
- sdk/communication/communication-phone-numbers/test/utils/index.ts
- sdk/communication/communication-phone-numbers/test/utils/mockHttpClients.ts
- sdk/communication/communication-phone-numbers/test/utils/recordedClient.ts
https://apiview.dev/Assemblies/Review/317956c6833a462aa5478ade5dbde602?diffRevisionId=9c050fb29d0349ca9844fd53d86d4971&doc=False&diffOnly=False
Introduces named `PurchasePhoneNumbersResult` and `ReleasePhoneNumberResult` interfaces to allow API evolution if we want to return a final result for LROs in the future.
Also lint fixes.
> [communication-phone-numbers] Replaced VoidResult and lint fixes

- sdk/communication/communication-phone-numbers/package.json
This PR updates the sample config of the phone numbers library to skip its samples. Samples are causing the smoke test pipeline to fail because the samples need more configuration.
Resolves #14312
> [communication] skip phone number samples

- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts
Apparently Node marks HTTP requests as `finished` extremely aggressively, which meant we weren't able to timeout/abort slow HTTP responses. 
This fix removes the check we were doing to not abort a finished request, which doesn't seem to cause any problems in my testing, and does resolve the issue @zfoster was seeing with timeouts not working properly.
> [core-rest-pipeline] Fix an issue where timeout was ignored on Node

- sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts
- sdk/keyvault/keyvault-admin/test/utils/authentication.ts
- sdk/keyvault/keyvault-certificates/test/utils/testAuthentication.ts
- sdk/keyvault/keyvault-keys/test/utils/testAuthentication.ts
- sdk/keyvault/keyvault-secrets/test/utils/testAuthentication.ts
This PR updates the existing LRO tests for KV admin with the ability to serialize & resume an existing LRO in order to both 
demonstrate and test the scenario of resuming from a serialized poller.
In passing, add trailing slashes to the recorder replacements for URIs since that's the default format of ARM template outputs.
Resolves #11183
> [KeyVault] - Demonstrate querying an existing LRO

- sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
- sdk/keyvault/keyvault-secrets/src/secretsModels.ts
- Changes the type of `SecretProperties.keyId` from `unknown` to `never`
Had a conversation with @witemple-msft about this, and this would be the better type since we can narrow but not expand this server-populated type. Given that it's already never set at runtime this seemed appropriate. In passing, updated the doc comment to reflect Ramya's review from the last change.
> change keyId from unknown to never

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/diagnostics/tracing.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/test/internal/sendBatch.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/serviceBusMessage.spec.ts
Expanding the types for applicationProperties to allow `null` (and not `undefined`).
`null` and `undefined` both get mapped to 'null' if you round-trip through JavaScript. Sending through .net will properly map to null as well. 
Fixes #14329
> [service-bus] Allow null as a type for applicationProperties

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/package.json
- sdk/core/core-auth/review/core-auth.api.md
- sdk/core/core-auth/src/azureNamedKeyCredential.ts
- sdk/core/core-auth/src/index.ts
- sdk/core/core-auth/test/index.spec.ts
Resolves #14303 
This PR adds the `AzureNamedKeyCredential` class and `NamedKeyCredential` interface to the `@azure/core-auth` pacakge.
Details are listed in the linked issue, but the TL;DR is:
When using a shared key for authorization, some services require the name of the key be used as part of the algorithm to form the authorization token.
Since `AzureKeyCredential` and `AzureSasCredential` only track a single value, we've added `AzureNamedKeyCredential` that lets us track 2 values! (Let's hope there's never 3 values needed!)
This credential will be used by the event hubs and service bus packages to start.
> [core-auth] Add AzureNamedKeyCredential class and NamedKeyCredential interface

- sdk/core/core-client/src/utils.ts
- sdk/core/core-client/test/serviceClient.spec.ts
- sdk/core/core-client/test/utils/serviceClient.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/12009.
When the service does not return a body ([Example in our test server](https://github.com/Azure/autorest.testserver/blob/4b994be5fd68b3ac009af30399ad6b817630dbc8/legacy/routes/dictionary.js#L24)).
Response will be `null` if the mapper says it is `nullable`.
Response is an empty object or array ([Example](https://github.com/Azure/autorest.typescript/blob/c8e68b845ccc3780d8c4be3787eb2c5e74272697/test/integration/bodyArray.spec.ts#L21)).
Implements the expectation by doing case analysis and adds test cases.
> [Core v2] Return null when the response is empty and nullable

- sdk/identity/identity/src/credentials/azureCliCredential.ts
Looking at the code, it seems that we are doing a pretty good job of making sure scopes can't escape out into the shell, so I don't think there is currently an issue here. However, since `exec` can be very tricky to use diligently, this PR hardens the code a little to use the somewhat safer `execFile` which doesn't invoke an entire shell by default.
> [identity] Replace use of `child_process.exec` with `execFile`.

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/request/SharedOptions.ts
Release failed, rerunning with new date
> [cosmos] 3.10.4 release

- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
- sdk/identity/identity/src/credentials/azureCliCredential.ts
- sdk/identity/identity/src/credentials/chainedTokenCredential.ts
- sdk/identity/identity/src/credentials/defaultAzureCredential.browser.ts
- sdk/identity/identity/src/credentials/environmentCredential.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
- sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
- sdk/identity/identity/test/public/node/environmentCredential.spec.ts
This PR removes the `null` return type on the `getToken()` of the Identity credentials.
Identity credentials extend TokenCredential, which continues to have `null` as a possibility.
While TokenCredentials may return null, Identity does not need to return null since it will throw at least a `CredentialUnavailable` error instead of returning null.
This decision doesn't necessarily need to impact the the base type TokenCredential because other TokenCredential implementations may use `null` reasonably outside of Identity.
It also does not necessarily need to impact the rest of our codebase since outside of Identity we compare the credential against the TokenCredential base class, which means that the null possibility exists if we ever decide to implement credentials outside of Identity, as we …
> [Identity] Removing the null return type on getToken()

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build.yml
Run API review create step before publishing artifact to support rerunning build job. Current rerun fails if initial failure is due to pending API approval since it tries to republish which is currently not supported.
> Run create API review step before publishing artifacts

- eng/pipelines/templates/stages/archetype-sdk-tests.yml
This trims down the number of canary live test runs to 1, as we are only trying to catch service regressions with these runs.
> Add MatrixReplace parameter to tests, only run single test case for canary

- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/deviceCodeCredential.ts
- sdk/identity/identity/test/internal/identityClient.spec.ts
- sdk/identity/identity/test/internal/node/deviceCodeCredential.spec.ts
- sdk/identity/identity/test/public/node/deviceCodeCredential.spec.ts
DeviceCodeCredential stopped having required parameters a while ago, when we started completing the values for tenant ID and client ID by default. However, even though our guidelines establish that we should group all of the optional parameters in option bags, the signature of this constructor never changed.
As part of my recent Identity changes, I've made it so the DeviceCodeCredential constructor could also accept only receiving the optional parameters. The intention there was to not do a breaking change initially, but since we're targeting a major version release, having this constructor overload feels unnecessary.
This PR makes it so DeviceCodeCredential only accepts an options bag as the first parameter, without overloads.
While doing these changes, I was able to spot a bug I …
> [Identity] DeviceCodeCredential constructor unification

- sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
- sdk/core/core-rest-pipeline/src/index.ts
- sdk/core/core-rest-pipeline/src/interfaces.ts
- sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- sdk/core/core-rest-pipeline/src/policies/proxyPolicy.ts
On NodeJS it's often useful to be able to control the agent used to make a request.
This change adds support for setting a custom agent on a per-request basis and also refactors ProxyPolicy to be in charge of proxy agents.
> [core-rest-pipeline] Add support for custom agents.

- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/modelsToBeSharedWithEventHubs.ts
When I restored the legacy option I didn't restore the option for the caller to pass in `null` as well.
> [service-bus] Adding back null type for tracing

- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
- sdk/keyvault/keyvault-secrets/src/secretsModels.ts
- sdk/keyvault/keyvault-secrets/src/transformations.ts
- sdk/keyvault/keyvault-secrets/test/internal/transformations.spec.ts
- sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts
- Deprecates `recoveryId`, `scheduledPurgeDate`, and `deletedOn` from a deleted secret's property bag
- Adds and populates the same three properties on the top level of a deleted secret
- These were supposed to be at the root level but we missed it the first time around
- This aligns us with keyvault certs and with dotnet's secrets 
Resolves #12768
> [KeyVault] - added top level properties for a deleted secret

- sdk/communication/communication-identity/README.md
Fixes #13997 
The samples don't need fixing as they don't use `DefaultAzureCredential`
> [communication-identity] fix missing import in README

- eng/tools/versioning/VersionUtils.js
- This is to allow me add `ChangelogPath` argument to the `Update-Changelog.ps1` script.
> Pass ReleaseDate by argument name to allow addition of more arguments

- sdk/servicebus/service-bus/CHANGELOG.md
Since we release hotfixes for v1 Service Bus from hotfix branches, the changelog entries never made it back to the master branch. This PR fixes this problem by copying over contents from the [changelog for 1.1.10 update](https://github.com/Azure/azure-sdk-for-js/blob/%40azure/service-bus_1.1.10/sdk/servicebus/service-bus/CHANGELOG.md)
> [Service Bus] v1 changelog

- common/tools/dev-tool/src/commands/samples/tsToJs.ts
The dev-tool ts-to-js pretty transpilation system uses this kind of hack-ish system to compensate for the fact that the TypeScript compiler strips out whitespace in its emit (basically we just replace empty lines with `//@@TS-MAGIC-NEWLINE@@` and then un-replace them when writing the output file.
The current implementation doesn't handle CRLF correctly (https://github.com/Azure/azure-sdk-for-js/pull/14488#discussion_r600946994), so this PR fixes that.
> [dev-tool] Fix newline sigil in ts-to-js to accept CRLF

- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/rollup.base.config.js
- sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts
Our cosmos friends noticed that if multibyte characters happened to occur along a chunked response boundary, we were not properly reconstituting the response body as text.
This PR uses buffer magic to properly re-assemble a string that faithfully represents the body text.
> [core-rest-pipeline] Fix issue with multibyte characters in chunked responses

- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-chat/src/constants.ts
- sdk/communication/communication-chat/src/generated/src/chatApiClientContext.ts
- sdk/communication/communication-identity/CHANGELOG.md
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-identity/src/constants.ts
- sdk/communication/communication-identity/src/generated/src/identityRestClientContext.ts
- sdk/communication/communication-identity/swagger/README.md
- sdk/communication/communication-phone-numbers/CHANGELOG.md
- sdk/communication/communication-phone-numbers/src/generated/src/lro/azureAsyncOperationStrategy.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/bodyPollingStrategy.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/locationStrategy.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/lroPolicy.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/lroPoller.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/models.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/operation.ts
- sdk/communication/communication-phone-numbers/src/generated/src/lro/requestUtils.ts
- sdk/communication/communication-phone-numbers/src/generated/src/models/index.ts
- sdk/communication/communication-phone-numbers/src/generated/src/operations/phoneNumbers.ts
- sdk/communication/communication-phone-numbers/src/generated/src/phoneNumbersClientContext.ts
- sdk/communication/communication-phone-numbers/src/utils/constants.ts
- sdk/communication/communication-phone-numbers/swagger/README.md
- sdk/communication/communication-sms/CHANGELOG.md
- sdk/communication/communication-sms/package.json
- sdk/communication/communication-sms/src/constants.ts
- sdk/communication/communication-sms/src/generated/src/smsApiClientContext.ts
* PhoneNumbers will be shipped as preview
* Everything else moves to GA (1.0.0)
> [Communication]: Updated versions for GA release

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/tools/publish-to-npm.ps1
tag is not optional now to publish a package to npm. This causes an issue when a hotfix package is required to be released. So this version get released as latest and then manually needs to adjust the tag to flip it back to actual latest version. This PR is to support publishing package to npm without any tag. I have another issue in backlog to support setting latest and next tag automatically. This issue will be taken care separately.
> Make tag as optional

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/package.json
We recently began importing { AbortSignal } as a type https://github.com/Azure/azure-sdk-for-js/pull/14433/files
which means we need users to have `node-abort-controller` v1.2.0 https://github.com/southpolesteve/node-abort-controller/blob/master/CHANGELOG.md
> [Cosmos] Pins abort controller version since we depend on it with 3.10.4

- sdk/formrecognizer/perf-tests/ai-form-recognizer/package.json
- sdk/formrecognizer/perf-tests/ai-form-recognizer/test/custom.spec.ts
Because perf tests should not use our eslint plugin. This PR applies the approach done here https://github.com/Azure/azure-sdk-for-js/pull/14322 to the newly added perf tests package for form recognizer.
Failure this PR fixes: https://dev.azure.com/azure-sdk/public/_build/results?buildId=806529&view=logs&j=58292cae-3c74-5729-4cfd-9ceee65fe129&t=3f037b94-2b49-5715-3208-309f8588a4cd
> [Form Recognizer] Use internal configs for linting perf tests

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/src/errors.ts
- sdk/core/core-amqp/test/errors.spec.ts
Fixes #14499 
This PR updates the `translateError` function in `@azure/core-amqp` to handle non-error parameter types.
With this change, if a scalar parameter (string, number, boolean) is passed to `translateError`, an `Error` will be created with that parameter as its message.
So if you called `translateError("foo");`, you'd get back an `Error` where `error.message` equals "foo".
Throughout the service-bus and event-hubs code bases, we call `translateError` to transform AMQP errors into `MessagingErrors`, and determine if they are retryable. However, JavaScript allows you to throw _anything_; you may not get something that extends `Error`.
We _could_ add a conditional check around each `translateError` callsite to ensure we're passing an object to `translateError`, but this is an easy …
> [core-amqp] improve translateError to handle non-error types

- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-client/src/utils.ts
Updates the changelog with the work done in https://github.com/Azure/azure-sdk-for-js/pull/14366 and renames `isPrimitiveType` to `isPrimitiveBody`.
EDIT: I also refactored `flattenResponse` further so it now has just one call to `handleNullableResponseAndWrappableBody`.
> [Core v2] Update changelog and rename isPrimitiveType

- common/tools/dev-tool/src/commands/samples/tsToJs.ts
The import path isn't quite correct and `ts-to-js` throws.
> [dev-tool] Fix relative import of prettier options.

- sdk/communication/communication-chat/test/chatClient.spec.ts
- sdk/communication/communication-chat/test/chatThreadClient.spec.ts
- sdk/communication/communication-identity/test/communicationIdentityClient.spec.ts
- sdk/communication/communication-identity/test/communicationIdentityClientWithToken.spec.ts
- sdk/communication/communication-phone-numbers/src/utils/tracing.ts
- sdk/communication/communication-phone-numbers/test/ctor.spec.ts
- sdk/communication/communication-phone-numbers/test/get.spec.ts
- sdk/communication/communication-phone-numbers/test/headers.spec.ts
- sdk/communication/communication-phone-numbers/test/list.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.purchase.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.release.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.search.spec.ts
- sdk/communication/communication-phone-numbers/test/lro.update.spec.ts
This PR fixes all the places where the linter rule `no-invalid-this` fails in the communication packages
Related to #13723
> [Communication] Fix no-invalid-this linter errors

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/review/core-auth.api.md
- sdk/core/core-auth/src/azureNamedKeyCredential.ts
- sdk/core/core-auth/src/azureSASCredential.ts
- sdk/core/core-auth/src/index.ts
- sdk/core/core-auth/src/typeguards.ts
- sdk/core/core-auth/test/index.spec.ts
Based on feedback here:
https://github.com/Azure/azure-sdk-for-js/pull/14423#discussion_r602616375
> [core-auth] add isNamedKeyCredential and isSASCredential typeguards

- common/tools/dev-tool/test/samples/tsToJs.spec.ts
This should make sure that this system keeps working by continuously validating that the template package was transpiled correctly and would be transpiled correctly in the future if we make changes to the transpilation stack within dev-tool.
> [dev-tool] Add test to validate continued functionality of the transpilation system.

- eng/pipelines/templates/steps/build.yml
- eng/pipelines/templates/steps/test.yml
- eng/tools/rush-runner.js
- rush.json
Upgrade rush version to latest rush version to build all dependent packages. Latest version of rush identifies transitive dependency when --from flag is used.
I will wait until March release is over to merge this change.
> Upgrade rush version to 5.40.7

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/README.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/defaultAzureCredential.ts
- sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
`DefaultAzureCredential` in other languages uses `InteractiveBrowserCredential` as a last measure. This PR aims to bridge the gap and enable `InteractiveBrowserCredential` in `DefaultAzureCredential`.
Fixes #14445
> [Identity] DefaultAzureCredential to use InteractiveBrowserCredential

- common/tools/dev-tool/src/commands/samples/publish.ts
- common/tools/dev-tool/src/util/sampleConfiguration.ts
This adds a little feature to the samples publication system that both Event Hubs and Form Recognizer need. It allows us to copy extra files into the output directory using an `extraFiles` field in the sample configuration.
`extraFiles` is a `Record<string, string[]>` that specifies a map from source file to an array of destinations to which that file should be copied. For example, if you have an extra sample directory (for browser samples or any other special use case), you can specify it like this:
```javascript
{
"//sampleConfiguration": {
...,
"extraFiles": {
"./samples-browser": ["browser"]
},
...
}
}
```
or to copy static assets:
```javascript
{
"//sampleConfiguration": {
...,
"extraFiles": {
"./assets": ["javascript/assets", "typescript/assets"]
},
...
}
}
```
> [dev-tool] Added declarative spec for extra files

- sdk/core/core-client/src/urlHelpers.ts
- sdk/core/core-client/test/urlHelpers.spec.ts
There's an issue in appending to path when the value to append
contains `?`. For example,
```ts
const parsedUrl = new URL("https://example.com");
parsedUrl.pathname = "/path?abc%3Ddef";
```
will cause the question mark to be encoded, then `parsedUrl.toString()`
would give us unexpected `'https://example.com/path%3Fabc%3Ddef'`
This PR fixes the issue by appending path and search part separately
when `?` is included in the value to append to path.
> [core-client] Fix `appendPath()` issue when path value to append contains `?` 

- sdk/servicebus/service-bus/test/perf/track-1/package.json
- sdk/servicebus/service-bus/test/perf/track-1/sbBase.spec.ts
- sdk/servicebus/service-bus/test/perf/track-1/sendBatch.spec.ts
- sdk/servicebus/service-bus/test/perf/track-2/README.md
- sdk/servicebus/service-bus/test/perf/track-2/sbBase.spec.ts
- sdk/servicebus/service-bus/test/perf/track-2/sendBatch.spec.ts
- Imports v7 in the v1 tests to allow creating the resources
- Makes sender static in both v1 and v7
> [Service Bus] Update perf tests to use a single sender for all instances

- eng/pipelines/templates/jobs/smoke-tests.yml
The smoke test initialization script generates a manifest containing paths to all samples code to be tested. In case people need this information to see what paths were generated, it doesn't cost us anything to log the contents of the file.
> [smoke test] Print run manifest in pipeline for debugging

- sdk/identity/identity/test/manual/package.json
Small tweaks on the manual folder. I use `dotenv` in some scripts in this folder, and a recent PR switched Identity back to 1.0.0, but this folder needs 2.0.0-beta.1 to work.
> [Identity] Small fixes on the manual tests

- sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
Upon inspection, it seems like the parameters to `sendTelemetry()` were supplied in the wrong order. This PR corrects that.
> Fix order of parameters supplied to sendTelemetry

- eng/tools/publish-to-npm.ps1
Package files are read using Get-Content without `-Raw` so string matching to replace version is not finding version properly. We have seen similar issue with Get-Content in similar place and reading content as Raw is the best option to pattern match within the content.
> Read dev files as raw to replace versions properly

- sdk/eventgrid/eventgrid/README.md
Now that the library has GA'd, we can remove the query parameter and
point at the latest docs.
> [EventGrid] Update documentation link

- sdk/core/core-tracing/review/core-tracing.api.md
- sdk/core/core-tracing/src/index.ts
- sdk/core/core-tracing/src/interfaces.ts
- sdk/core/core-tracing/src/tracerProxy.ts
- sdk/core/core-tracing/src/tracers/noop/noOpTracer.ts
- sdk/core/core-tracing/src/tracers/opencensus/openCensusTracerWrapper.ts
- sdk/core/core-tracing/src/tracers/test/testSpan.ts
- sdk/core/core-tracing/src/utils/cache.ts
Some of the types for the core-tracing API were just being re-exported from opentelemetry/api (directly, not copied). `@opentelemetry/api` uses some constructs that aren't available in TypeScript 3.1, which causes problems for consumers of core-tracing.
This PR fixes that by duplicating the types, which should cut off any compiling/importing of the opentelemetry types by consumers of core-tracing.
> [core-tracing] Updating surface to be clean of constructs that won't work in TS 3.1

- sdk/identity/identity/recordings/node/interactivebrowsercredential_internal/recording_throws_an_expected_error_if_no_browser_is_available.js
- sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts
- sdk/identity/identity/test/internal/node/interactiveBrowserCredential.spec.ts
This PR adds a way to handle throws coming form the `open` dependency. One way this dependency will throw is if the are no browsers available. One quick way to test this is to install `open` in a Linux VM and to run this Node code: 
```js
const open = require("open");
(async () => open("http://sadasant.com/", { wait: true }))()
.then(console.log)
.catch(e => console.log("open() error", { message: e.message }));
```
Which will cause this error:
```
open() error { message: 'spawn xdg-open ENOENT' }
```
This effectively means that InteractiveBrowserCredential  will throw if there are no browsers available. This could be useful if we ever want to provide a backup to DeviceCode on those cases.
Though this issue is not blocking the release, introducing InteractiveBrowserCredential tests to our …
> [Identity] InteractiveBrowserCredential should handle open() throws

- sdk/servicebus/service-bus/src/util/utils.ts
setTimeoutArgs is only used internally.
> [Service Bus] This internal type setTimeoutArgs is showing up in the (Typedoc) docs - removing

- common/tools/dev-tool/src/config/rollup.base.config.ts
The rollup commonJS plugin associates our manually namedExports to an ID, which typically is a package ID.
Due to the fact that the opentelemetry/api project can enter into the node_modules from multiple locations (either from an older dependency, like identity prior to our centralization, or a release version of core-tracing) we have to explicitly _name_ the path to the package, not just the package name.
> [core-tracing] The rollup commonjs plugin needs extra "hinting" to handle opentelemetry/api versions

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/msal/browserFlows/browserCommon.ts
- sdk/identity/identity/src/msal/browserFlows/msalAuthCode.ts
- sdk/identity/identity/src/msal/errors.ts
- sdk/identity/identity/src/msal/nodeFlows/msalClientCertificate.ts
- sdk/identity/identity/src/msal/nodeFlows/msalClientSecret.ts
- sdk/identity/identity/src/msal/nodeFlows/msalDeviceCode.ts
- sdk/identity/identity/src/msal/nodeFlows/msalUsernamePassword.ts
- sdk/identity/identity/src/msal/nodeFlows/nodeCommon.ts
- sdk/identity/identity/src/msal/utils.ts
To align with other languages, this PR adds properties `scopes` and `getTokenOptions` to the AuthenticationRequired error. For that purpose, some other utility functions had to change to pass these values through.
Fixes #14585
> [Identity] AuthenticationRequired API alignment

- sdk/identity/identity/README.md
This small PR just removes an `await` call that doesn't make sense outside of async functions. Using a client is also not necessary to demonstrate how to create one.
Resolves #14002
> [Identity] - Remove `await` from README

- eng/pipelines/templates/jobs/archetype-sdk-integration.yml
- eng/pipelines/templates/stages/platform-matrix.json
- eng/pipelines/templates/variables/globals.yml
- sdk/keyvault/keyvault-keys/platform-matrix.json
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/keysModels.ts
- sdk/keyvault/keyvault-keys/test/internal/aesCryptography.spec.ts
- sdk/keyvault/keyvault-keys/test/internal/challengeBasedAuthenticationPolicy.spec.ts
- sdk/keyvault/keyvault-keys/test/internal/serviceVersionParameter.spec.ts
- sdk/keyvault/keyvault-keys/test/public/CRUD.hsm.spec.ts
- sdk/keyvault/keyvault-keys/test/public/CRUD.spec.ts
- sdk/keyvault/keyvault-keys/test/public/crypto.hsm.spec.ts
- sdk/keyvault/keyvault-keys/test/public/crypto.spec.ts
- sdk/keyvault/keyvault-keys/test/public/import.spec.ts
- sdk/keyvault/keyvault-keys/test/public/list.spec.ts
- sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts
- sdk/keyvault/keyvault-keys/test/public/lro.delete.spec.ts
- sdk/keyvault/keyvault-keys/test/public/lro.recoverDelete.spec.ts
- sdk/keyvault/keyvault-keys/test/public/recoverBackupRestore.spec.ts
- sdk/keyvault/keyvault-keys/test/utils/testAuthentication.ts
- sdk/keyvault/keyvault-keys/test/utils/utils.common.ts
- Adds support for live testing multiple service versions
- Adds the matrix config and plumbing to pass service version as an environment variable
- Adds a helper method to support skipping tests when the service version isn't supported
KeyVault currently supports three service versions: 7.0, 7.1, and 7.2. Being able to ensure our
live tests run against previous service versions is a way to future proof ourselves and allow us
to ensure continued support.
After a bit of discussion we agreed that it would be worthwhile to add the indirection of passing
the service version as an environment variable and avoid having to run all service versions tests
in sequence.
> [KeyVault] - Add multi-version tests for KeyVault Keys

- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/src/policies/bearerTokenAuthenticationPolicy.ts
- sdk/core/core-rest-pipeline/src/util/tokenCycler.ts
- sdk/core/core-rest-pipeline/test/bearerTokenAuthenticationPolicy.spec.ts
@willmtemple just finished a rewrite of the bearerTokenAuthenticationPolicy on the old core: PR #14223
We also want to have this same update in the new core, so I've copied the changes he did into core-rest-pipeline.
This PR closes an early draft I did some time ago: #13832
For this PR I've decided, similar to Will's PR on the old core, to not alter the public API of `core-rest-pipeline`. We can keep this refresher configuration private until customers ask for this. These are also private in other languages.
Feedback always appreciated 🙏
Related to #13369
> [core-rest-pipeline] Token refresher update, based on the latest design by Will

- sdk/deviceupdate/iot-device-update/samples/javascript/README.md
- sdk/deviceupdate/iot-device-update/samples/typescript/README.md
- sdk/monitor/monitor-opentelemetry-exporter/samples/@azure/storage-blob/javascript/README.md
- sdk/monitor/monitor-opentelemetry-exporter/samples/@azure/storage-blob/typescript/README.md
There are a couple of problems with the samples that are apparently blocking publication across our repo.
- monitor-opentelemetry-exporter has some samples that have the same `urlFragment` as the real storage samples, so I've commented them out for now
- deviceupdate has an invalid product
> [samples] Fix issues identitfied by docs team

- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-admin/test/internal/challengeBasedAuthenticationPolicy.spec.ts
- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/test/internal/challengeBasedAuthenticationPolicy.spec.ts
- sdk/keyvault/keyvault-common/src/challengeBasedAuthenticationPolicy.ts
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/test/internal/challengeBasedAuthenticationPolicy.spec.ts
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/test/internal/challengeBasedAuthenticationPolicy.spec.ts
- sdk/keyvault/keyvault-secrets/test/utils/testAuthentication.ts
This PR fixes an issue where the original request body is not restored in the event a downstream policy throws and we retry.
It's a small change, and I don't _love_ having the test duplicated in three places, but we currently do that for the other challenge based authentication tests and I didn't think this was the time to refactor that, especially given we will be moving to core-auth in the near future.
Fixes #14590
> [KeyVault] - Ensure we restore the request body correctly

- common/tools/dev-tool/src/commands/samples/publish.ts
- common/tools/dev-tool/src/util/sampleGenerationInfo.ts
This is a little oversight when analyzing the sample files' imports. Relative path imports need to be filtered out when considering dependencies. We were already filtering node builtin modules, so I abstracted the logic to a helper function `isDependency`.
It's difficult to support _absolute_ path imports in the samples without doing a lot more work involving simulating node module resolution and adding a lot more logic to the output structure for TS and JS. Plus, I'm not convinced that absolute path imports make a lot of sense within the sample code anyway. So, relative path imports need to start with one or two dots and a forward slash, i.e. the regexp `/^\.\.?\//`.
I also made the dependency diagnostic error refer to the possibility that "./" is missing for relative imports.
We found …
> [dev-tool] Allow relative-path imports in sample files.

- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/cryptography/models.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts
This PR removes LocalSupportedAlgorithmName. It is no longer used internally and not needed for customers, so this removes it from the public API and the codebase.
> [KeyVault] - Remove LocalSupportedAlgorithmName

- sdk/eventhub/eventhubs-checkpointstore-blob/package.json
- sdk/eventhub/eventhubs-checkpointstore-blob/src/log.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/src/util/error.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/utils/testUtils.ts
Resolves #10777 by addressing the last outstanding item.
With this change, `@azure/eventhubs-checkpointstore-blob` now no longer has eslint errors.
> [eventhubs-checkpointstore-blob] fixes eslint errors

- sdk/identity/identity/README.md
In #14646, we removed the details on different credentials from the top part of the readme. Adding pointer to the new examples file instead. This is very useful instead of making the user scroll to the bottom
> [Identity] Add pointer to examples upfront

- sdk/communication/communication-chat/test/chatClient.spec.ts
- sdk/communication/communication-chat/test/utils/mockClient.ts
- sdk/communication/communication-chat/test/utils/recordedClient.ts
Fixes the linter errors around missing return types in communication chat package
Related to https://github.com/Azure/azure-sdk-for-js/issues/13723
> [Communication Chat] Fix missing return type linter errs

- sdk/communication/communication-chat/test/utils/recordedClient.ts
- sdk/communication/communication-identity/test/utils/recordedClient.ts
Fixes the linter errors around the rule `no-useless-escape` in the communication packages
Related to #13723
> [Communication] Fix errs from linter rule no-useless-escape

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
- sdk/servicebus/service-bus/test/public/atomManagement.spec.ts
The ordering of properties in the XML requests to the Service Bus ATOM API is significant and changing it can have side effects.
In this instance, the ordering issues caused us to appear to have setup forwarding properly for a queue but forwarding was NOT actually enabled. Our previous testing missed this because this data actually round-trips properly through the API but it doesn't trigger whatever actual setting needs to happen to cause forwarding to happen.
This PR reconciles our queue, topic and subscription entities ordering against the .net layer, which acts as the de-facto authority.
Fixes #14539
> [service-bus] AdminClient: ForwardTo wasn't applying on update due to bad property ordering in XML

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
- sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
- sdk/servicebus/service-bus/src/util/constants.ts
- sdk/servicebus/service-bus/test/public/atomManagement.spec.ts
AdminClient: ForwardTo wasn't applying on update due to bad property ordering in XML (#14692)
The ordering of properties in the XML requests to the Service Bus ATOM API is significant and changing it can have side effects.
In this instance, the ordering issues caused us to appear to have setup forwarding properly for a queue but forwarding was NOT actually enabled. Our previous testing missed this because this data actually round-trips properly through the API but it doesn't trigger whatever actual setting needs to happen to cause forwarding to happen.
This PR reconciles our queue, topic and subscription entities ordering against the .net layer, which acts as the de-facto authority.
Fixes #14539
> [Service Bus] Porting 14692 to the patch version

- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/index.ts
- sdk/keyvault/keyvault-keys/test/internal/crypto.spec.ts
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/src/index.ts
- sdk/keyvault/keyvault-secrets/src/lro/delete/poller.ts
- sdk/keyvault/keyvault-secrets/src/lro/recover/poller.ts
- If we can remote, and a local crypto operation fails, then we remote the call.
- In hybrid mode we want to be able to continue supporting crypto operations even if for unknown reasons the local provider fails. This ensures that we can defer to the remote provider if possible. 
- In local-only mode, we surface the original error to be handled by user code.
Resolves #14713
> [KeyVault] - remote calls in hybrid mode if local crypto errors

- sdk/search/search-documents/review/search-documents.api.md
- sdk/search/search-documents/src/generated/service/models/index.ts
- sdk/search/search-documents/src/generated/service/models/mappers.ts
- sdk/search/search-documents/src/index.ts
- sdk/search/search-documents/src/searchClient.ts
- sdk/search/search-documents/src/searchIndexClient.ts
- sdk/search/search-documents/src/searchIndexerClient.ts
- sdk/search/search-documents/src/serviceModels.ts
- sdk/search/search-documents/src/serviceUtils.ts
- sdk/search/search-documents/swagger/Service.md
Two new requests have come for search-documents SDK. 
1. There is a bug in the current swagger. This should be fixed before next release. In the meantime, we need to add a swagger transform and handle the bug. The issue is detailed [here](https://github.com/Azure/azure-sdk-for-net/pull/20078#discussion_r606518341)
2. This issue is regarding passing a different version to the search clients constructors. It has already been communicated to the customers that there might be additional fields coming up due to version changes and to the service team that there should not be any compatibility changes. This design will be dicussed in detail before next release. But for this release, we wanted to try this design of multi api support. 
@xirzec Please review this PR
> Code changes to add muli api support

- sdk/containerregistry/container-registry/CHANGELOG.md
- sdk/containerregistry/container-registry/README.md
- Align with .NET README structure
- Add one example to README
- Improve CHANGELOG slightly
> [ContainerRegistry] README and CHANGELOG for beta.1

- sdk/digitaltwins/digital-twins-core/README.md
close #13295 
Updated README to use `@azure/identity` for authentication rather than `@azure/ms-rest-nodeauth` and `@azure/ms-rest-browserauth`. Made some other miscellaneous tweaks as well to match more closely to the template README.
> Update readme.md to use @azure/identity for authentication

- sdk/tables/data-tables/CHANGELOG.md
- Update open-telemetry dependency to 1.0.0-rc.0 [#14208](https://github.com/Azure/azure-sdk-for-js/pull/14208)
- Update @azure/core-client and @azure/core-rest-pipeline dependencies to 1.0.0 [#14318](https://github.com/Azure/azure-sdk-for-js/pull/14318)
> [Tables] Update changelog for April 2021 release

- sdk/keyvault/keyvault-keys/recordings/node/cryptographyclient_for_managed_hsm_skipped_if_mhsm_is_not_deployed_with_aes_crypto_algorithms/recording_encrypts_and_decrypts_using_aescbc.js
- sdk/keyvault/keyvault-keys/test/public/CRUD.hsm.spec.ts
- sdk/keyvault/keyvault-keys/test/public/crypto.hsm.spec.ts
- sdk/keyvault/test-resources-post.ps1
- Adds `Managed HSM Crypto Officer` and `Managed HSM Crypto User` role assignments to test user when deploying MHSM.
Recent RBAC changes for MHSM recently went live which impact how existing permissions are defined. In order to access key operations the Administrator role is no longer sufficient. To keep our tests running we need to add the Crypto Officer and Crypto User role assignments to our test application after the managed HSM is activated.
> [KeyVault] - Update setup script to include additional role assignments for MHSM

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/tools/publish-to-npm.ps1
- This change appears to cause all packages to be published with no tags
- This reverts commit 74a61620d00e35001bc722cc809e0de02d4cbb9f.
Publish template with current master: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=828494&view=results
Publish template with #14427 reverted: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=828505&view=results
> Revert "Make tag as optional (#14427)"

- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/amqpAnnotatedMessage.ts
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/review/service-bus.api.md
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/messageSender.ts
- sdk/servicebus/service-bus/src/dataTransformer.ts
- sdk/servicebus/service-bus/src/sender.ts
- sdk/servicebus/service-bus/src/serviceBusMessage.ts
- sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
- sdk/servicebus/service-bus/src/util/errors.ts
- sdk/servicebus/service-bus/test/internal/amqp.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/amqpUnitTests.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/batchingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/dataTransformer.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/sender.spec.ts
Adding in support to send AmqpAnnotatedMessage and also to control where the body is encoded in the sent message (via the `bodyType`) field.
> [service-bus] Add support for sending AmqpAnnotatedMessage (and control destination section of body)

- sdk/identity/identity/CHANGELOG.md
Adding the 1.3.0 changelog into the master changelog.
Do we use to merge hotfix branches into master? I don't remember. Doing that would be very messy since we had to disable a bunch of things on 1.3.0's hotfix branch.
> [Identity] 1.3.0 changelog entry sync

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/msal/utils.ts
I had some instances of `instanceof`, which is causing issues once @azure/msal-common gets updated, since @azure/msal-node hasn't been released with the latest version of @azure/msal-common.
For background: instanceof will not match for two different class definitions with the same name loaded on runtime. They can look similar, but if they're not the same exact class definition, instanceof won't match. This dependency mismatch causes instanceof to fail, since both versions of a same dependency are being loaded, causing the runtime to have two classes with the same name.
I know that checking for `error.name` is the way to go, but I had forgotten to remove these before.
After this, there are no further instances of `instanceof` in Identity's code.
This will fix the `rush update --full` PRs.
> [Identity] Getting rid of instanceof

- eng/pipelines/templates/stages/archetype-sdk-client.yml
The Azure Pipelines hosted macOS pools are currently experiencing severe capacity issues, which is causing a lot of bottlenecks for our PR/CI and release pipelines. This PR overrides all CI/client/release tests that run on mac to run on our managed ubuntu pool instead. Live tests are unaffected and will still run on the mac pool.
See https://status.dev.azure.com/_event/233282345 for details on the underlying issue.
> Temporarily replace macOS CI tests with ubuntu CI tests

- .github/CODEOWNERS
Owners were not pinged for "communication" at https://github.com/Azure/azure-sdk-for-js/pull/14792
As @ramya-rao-a suggested, reverting #13809 until the group alias is fixed. 
This reverts commit 67dc66b81db953927f75c7cbc653872bf70a290c.
/cc @meeraharidasa
> Revert "Update CODEOWNERS (#13809)"

- sdk/cognitiveservices/cognitiveservices-computervision/LICENSE.txt
- sdk/cognitiveservices/cognitiveservices-computervision/package.json
- sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClient.ts
- sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
- sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
- sdk/cognitiveservices/cognitiveservices-computervision/src/models/mappers.ts
- sdk/cognitiveservices/cognitiveservices-computervision/src/models/parameters.ts
This PR is to regenerate and release Cognitive Services Computer Vision 3.2 JS SDK. 
**Command Used**
```
autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.4 --package-version=8.0.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/ComputerVision/readme.md
AutoRest code generation utility [cli version: 3.0.6339; node: v14.15.4, max-memory: 4096 MB]
There is a new version of AutoRest available (3.1.4).
> You can install the newer version with with npm install -g autorest@latest
NOTE: AutoRest core version selected from configuration: ~2.0.4413. …
```
> Regenerated Computer Vision SDK 3.2

- sdk/test-utils/recorder/CHANGELOG.md
- sdk/test-utils/recorder/src/utils/index.ts
- sdk/test-utils/recorder/test/browser/utils.spec.ts
@maorleger came up with a case where `maskAccessTokenInBrowserRecording` was throwing an error because the response wasn't JSON though the content type is "application/json; charset=utf-8".
Example
```js
{
method: "GET",
url: "https://managed_hsm.azure.net/keys/cryptography-client-test1e909341f12eab0",
query: { "api-version": "7.2" },
requestBody: "",
status: 401,
response: "OK",
responseHeaders: {
"content-security-policy": "default-src 'self'",
"content-type": "application/json; charset=utf-8",
"strict-transport-security": "max-age=31536000; includeSubDomains",
"x-ms-server-latency": "0"
}
}
```
This PR attempts to fix such cases by not doing anything when the response is not JSON parsable.
> [Recorder] Mask access_token from browser recordings - relaxing for non json parsable content

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/chainedTokenCredential.ts
- sdk/identity/identity/src/msal/errors.ts
- sdk/identity/identity/test/public/chainedTokenCredential.spec.ts
`AuthenticationRequiredError` (introduced in 2.0.0-beta.1) now doesn't extend `CredentialUnavailableError`.
- `AuthenticationRequiredError`, besides being useful to express when a manual authentication with `authenticate()` is required, it also shares a similarity with `CredentialUnavailableError` in which both were designed to tell `ChainedTokenCredential` to move ahead and try another credential.
- Because of how prone to errors is `instanceof`, we intentionally want to focus on asserting errors through the `error.name` property of each error.
- Since each error writes its own name, the proper way to check for both errors is to check for both error names, thus making inheritance unnecessary for that use case.
Besides the code change, this PR also extends a current test with a simple …
> [Identity] Decoupling CredentialUnavailableError from AuthenticationRequiredError

- sdk/communication/communication-chat/package.json
- sdk/communication/communication-chat/src/models/mappers.ts
- sdk/communication/communication-chat/test/chatClient.spec.ts
- sdk/communication/communication-chat/test/chatThreadClient.mocked.spec.ts
- sdk/communication/communication-chat/test/chatThreadClient.spec.ts
- sdk/communication/communication-chat/test/utils/mockClient.ts
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-identity/test/communicationIdentityClient.mocked.spec.ts
- sdk/communication/communication-identity/test/utils/mockHttpClients.ts
This PR addresses the final lint errors in the `communication-chat` and `communication-identity` libraries. Also updates the `lint` script in each package as per #13723.
@ramya-rao-a there are still a few warnings related to unused variables (all when destructuring objects), will these cause build breaks?
> [communication] address lint errors

- sdk/core/core-lro/CHANGELOG.md
v1.0.4 compiled artifacts use cjs modules and this release corrects this by switching to es6 modules instead.
> [Core Lro] Release 1.0.5

- sdk/communication/communication-chat/samples/javascript/package.json
Fixes #14820 
For some reason this was missed, typescript sample has the dependency
> [communication-chat] add missing communication-identity dependency in JS sample

- sdk/identity/identity/recordings/node/devicecodecredential/recording_allows_setting_disableautomaticauthentication.js
- sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_and_allows_the_customization_of_the_prompt_callback.js
- sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_with_default_values.js
- sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_with_provided_values.js
- sdk/identity/identity/recordings/node/devicecodecredential/recording_supports_tracing.js
- sdk/identity/identity/recordings/node/devicecodecredential_internal/recording_authenticates_silently_after_the_initial_request.js
- sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_accepts_tokencachepersistenceoptions.js
- sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_allows_passing_an_authenticationrecord_to_avoid_further_manual_authentications.js
- sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_authenticates_silently_with_tokencachepersistenceoptions.js
- sdk/identity/identity/test/msalTestUtils.ts
This PR fixes the recordings (and the recorder settings) to reduce the DeviceCodeCredential intervals from 5 seconds to 0.1 seconds (I tried 0 seconds, but that didn't work).
Fixes #14375
Fixes #14267
> [Identity] Reducing DeviceCodeCredential intervals

- .github/CODEOWNERS
Because it is currently left without owners.
> [Attestation] Update code owners

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/credentials/chainedTokenCredential.ts
- sdk/identity/identity/src/util/logging.ts
- sdk/identity/identity/test/internal/node/chainedTokenCredential.spec.ts
Fixes to the ChainedTokenCredential logging. It now documents what credential succeeds.
Also added a test.
Fixes #6769
> [Identity] ChainedTokenCredential logging fix

- eng/pipelines/templates/jobs/ci.yml
There is nothing currently in the build job that is a pre-requisite for the Analyze and Test jobs in our CI pipelines. The only reasoning I can think of for why we would want to make these jobs sequential is to save agent time when the build or analyze step fails, but digging through the data this is not a common scenario (looking at the last week of failure analysis, I think ALL the failures are from the unit test jobs, not the build/analyze jobs).
Removing `DependsOn` here will allow PR authors to get signal on test failures anywhere from 5-20 minutes faster, which I think will significantly improve the dev loop in cases where test signal from CI is necessary (e.g. for cross-OS tests the dev can't run locally).
> Kick off all CI jobs in parallel instead of waiting on build

- sdk/communication/communication-sms/test/smsClient.spec.ts
We are temporarily disabling the error code check. We are expecting it to always return a 401.
Currently it is always returning 404 and flakily 401. 
We are disabling until the service team makes the appropriate change.
> [Communication] temporarily disable sms error code assertion for unauthorized phone number

- common/config/rush/pnpm-lock.yaml
- sdk/attestation/attestation/package.json
The new version addresses https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-30246
> [attestation] upgrade `jsrsasign` to v10.2.0

- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/retry.ts
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/src/core/messageReceiver.ts
- sdk/servicebus/service-bus/src/core/streamingReceiver.ts
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/receivers/receiverCommon.ts
- sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
- sdk/servicebus/service-bus/src/serviceBusClient.ts
- sdk/servicebus/service-bus/src/session/messageSession.ts
- sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/messageSession.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/receiverCommon.spec.ts
- sdk/servicebus/service-bus/test/public/utils/testUtils.ts
This was the source of a few live test pipeline failures - it was not resilient against network failures.
RequestResponseLink retries will come in a separate PR as that's a bit more involved.
(also, renamed receiver/shared.ts to receiver/receivercommon.ts, just to reduce file naming confusion amongst multiple shared.ts files)
Partly related to #13796
> [service-bus] Retries implemented for settling messages on the receiver link.

- eng/pipelines/templates/steps/analyze.yml
This PR removes the use of the verify-samples.yml template until we can dig into the underlying cause of errors.
/cc @heaths
> Disable verify samples until issue can be resolved.

- sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts
- sdk/servicebus/service-bus/test/public/sessionsRequiredCleanEntityTests.spec.ts
One of my previous PRs merged earlier than the live test execution. Fixing some issues that were remaining:
- the ServiceBusClient in the test wasn't being closed after each test (sessionsRequiredCleanEntityTests.spec.ts is special in that it has to recreate new entities for each test). This is responsible for the current 3+ hour test executions happening in master for SB.
- Removed a stray console.log statement I left in the test.
> [service-bus] Fixing some issues I introduced in an early merge

- common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-name.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-name.ts
- sdk/core-rest/core-client/CHANGELOG.md
- sdk/core-rest/core-client/package.json
- sdk/core-rest/core-client/src/clientHelpers.ts
- sdk/core-rest/core-client/src/common.ts
- sdk/core-rest/core-client/src/constants.ts
- sdk/core-rest/core-client/src/getClient.ts
- sdk/core-rest/core-client/src/index.ts
- sdk/core-rest/core-client/src/keyCredentialAuthenticationPolicy.ts
- sdk/core-rest/core-client/src/pathClientTypes.ts
- sdk/core-rest/core-client/src/sendRequest.ts
- sdk/core-rest/core-client/src/urlHelpers.ts
- sdk/core-rest/core-client/test/clientHelpers.spec.ts
- sdk/core-rest/core-client/test/sendRequest.spec.ts
- sdk/core-rest/core-client/test/urlHelpers.spec.ts
- sdk/documenttranslator/ai-document-translator-rest/.eslintrc.json
- sdk/documenttranslator/ai-document-translator-rest/CHANGELOG.md
- sdk/documenttranslator/ai-document-translator-rest/package.json
- sdk/documenttranslator/ai-document-translator-rest/samples/v1/javascript/README.md
- sdk/documenttranslator/ai-document-translator-rest/samples/v1/typescript/README.md
- sdk/documenttranslator/ai-document-translator-rest/src/constants.ts
- sdk/documenttranslator/ai-document-translator-rest/test/public/utils/recordedClient.ts
- sdk/metricsadvisor/perf-tests/ai-metrics-advisor/test/listAnomalies.spec.ts
- sdk/metricsadvisor/perf-tests/ai-metrics-advisor/test/listIncidents.spec.ts
- sdk/metricsadvisor/perf-tests/ai-metrics-advisor/test/rootCauses.spec.ts
- sdk/search/perf-tests/search-documents/test/core/searchDocumentsBase.spec.ts
* Update package metadata for @azure-rest/ai-document-translator
* Fix lint errors
* Update lint rule to allow @azure-rest 
* Fix lint errors in search and  metricsadvisor
> [Document Translator] Update package metadata

- sdk/communication/communication-identity/.vscode/launch.json
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-identity/rollup.base.config.js
- sdk/communication/communication-identity/test/public/communicationIdentityClient.mocked.spec.ts
- sdk/communication/communication-identity/test/public/communicationIdentityClient.spec.ts
- sdk/communication/communication-identity/test/public/communicationIdentityClientWithToken.spec.ts
- sdk/communication/communication-identity/test/public/utils/mockHttpClients.ts
- sdk/communication/communication-identity/test/public/utils/recordedClient.ts
- sdk/communication/communication-identity/test/public/utils/testCommunicationIdentityClient.ts
This addresses [this github issue](https://github.com/Azure/azure-sdk-for-js/issues/13816) for the communication identity package.
There's also a workaround that's been added due to an issue with module resolution for min-max testing. It's being investigated
> [Communication] communication-identity test separation for min/max testing

- sdk/servicebus/service-bus/test/internal/batchReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/serviceBusReceiverUnitTests.spec.ts
- sdk/servicebus/service-bus/test/public/utils/testUtils.ts
There were two live tests that were basically exercising a small segment of validation code to make sure you can't try to receiveMessages() and subscribe() at the same time. These tests have been flaky in the past, and were really only testing logic so I just migrated them to unit tests instead.
> [service-bus] Converting `parallel receive` live tests to unit tests

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/steps/common.yml
- common.yml should call verify-agent-os.yml, to verify OS in any pipeline using common.yml
- bypass-local-dns.yml is now called from verify-agent-os.yml
- Removed duplicate calls to verify-agent-os.yml in pipelines already calling common.yml
> Remove duplicate calls to bypass-local-dns.yml

- eng/pipelines/templates/jobs/live.tests.yml
This PR enables live tests to use multiple subscription configurations per cloud instead of one. Currently there are some services that need to manage their own cloud-specific values in a keyvault they control (e.g. acs, storage), but also need to use some shared values that only Azure SDK engineering systems can have access to, like service principal credentials.
This change takes advantage of a [recent update](https://github.com/Azure/azure-sdk-tools/pull/1560) to enable merging multiple subscription configurations together before passing the value to the ARM template deployment job.
> Support multiple subscription configuration options

- sdk/communication/communication-identity/test/public/utils/recordedClient.ts
- sdk/communication/communication-identity/tests.yml
this removes the filter, and enables min-max testing
https://devblogs.microsoft.com/azure-sdk/testing-semver-dependency-ranges/
> [communication] identity enable min-max testing

- eng/pipelines/templates/stages/archetype-js-release.yml
This reverts commit 64668dca74f22a4e5cb817bce8a753f18710a1aa. Unfortunately the SetDevVersion variable was never working correctly, so removing the duplicated conditions in the expressions broke nightly package publishing. To get nightly publishing unblocked for the JS repo I've reverted the commit for now. A subsequent commit will tidy up the expression after I've got the variable plumbed across.
> Revert "Revise stage condition. (#14851)"

- eng/pipelines/templates/stages/archetype-js-release.yml
This enables the retain runs template on the JS repo.
> Enable retained runs.

- common/tools/add-identity-mgmt-lib.js
`add-identity-mgmt-lib.js` is the script that can be used on auto-generated mgmt plane packages to make them support the credentials from the `@azure/identity` package
We had feedback regarding the updated readme that the use of `DefaultAzureCredential` requires set up while the older readme used interactive credential from ms-rest-nodeauth which did not require any set up and so was easy to get started.
In all the data plane packages that use the new Identity package across all languages, we have been using `DefaultAzureCredential` in our examples and getting started guides. If we are to change our getting started story, that would involve a larger effort cross languages and cross packages. 
In order to unblock the current efforts to have the mgmt plane packages support Azure Identity, …
> Improve mgmt readme for identity support

- sdk/communication/communication-common/karma.conf.js
- sdk/communication/communication-identity/karma.conf.js
- sdk/communication/communication-phone-numbers/karma.conf.js
- sdk/communication/communication-sms/karma.conf.js
Running tests without this setting is causing issues in some machines.
Adding this configuration will also allow tests to work in container environments as well.
`communication-chat` package already uses this setting, so now all communication packages use the same configuration.
> Add karma --no-sandbox config

- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/review/core-client.api.md
- sdk/core/core-client/src/interfaces.ts
- sdk/core/core-client/src/serviceClient.ts
- sdk/core/core-client/test/serviceClient.spec.ts
in `ServiceClientOptions` and `OperationRequestOptions` to allow operation requests to HTTP endpoints
> [core-client] expose allowInsecureConection

- sdk/documenttranslator/ai-document-translator-rest/.eslintrc.json
- sdk/documenttranslator/ai-document-translator-rest/api-extractor.json
- sdk/documenttranslator/ai-document-translator-rest/package.json
During pre-release validation I realized that there was a miss match in the typings file name between package.files and api-extractor config. This causes the package to not include any type definitions file.
> [Document Translator] Fix typedef file name

- eng/pipelines/templates/jobs/smoke.tests.yml
This PR switches the smoke test jobs and utility jobs to use the 1es hosted agents for windows and ubuntu runs.
> Use 1es hosted pools for smoke tests

- sdk/identity/identity/test/manual-integration/AzureArc/INSTRUCTIONS.md
- sdk/identity/identity/test/manual-integration/AzureArc/index.ts
- sdk/identity/identity/test/manual-integration/AzureArc/package.json
- sdk/identity/identity/test/manual-integration/AzureArc/tsconfig.json
This commit adds instructions on how to setup and run an identity smoke test in Azure Arc using managed identity to our collection of manual-integration tests.
Tested manually using a Linux VM
Resolves #11724
> [Identity] - Add instructions for running Identity test in Azure Arc

- sdk/web-pubsub/web-pubsub-express/api-extractor.json
It was emitting `index.d.ts` and therefore not getting packed into the package.
> Fix d.ts filename for web-pubsub-express

- eng/pipelines/templates/stages/archetype-sdk-tests.yml
I missed one place in https://github.com/Azure/azure-sdk-for-js/pull/14933 where we need to plumb the `SubscriptionConfigurations` parameter through to the live test config.
> Pass SubscriptionConfigurations parameter through to live test job

- sdk/communication/communication-phone-numbers/tests.yml
- sdk/communication/communication-sms/tests.yml
While working through documentation for live testing we found this env var `AZURE_SUBSCRIPTION_ID` that didn't seem to be in use.
> [Communication] - TESTS - removing unused value in test.yml 

- sdk/communication/communication-phone-numbers/test/public/lro.search.spec.ts
removed skip after PSTN team re-enabled toll free search
> [communication] re-enable skipped phone number search test

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/linkEntity.ts
- sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/15002
`@azure/event-hubs` 5.5.0 introduced a bug where a `TypeError` could be thrown from `EventHubProducerClient.sendBatch` if the connection was disconnected between the points where the sender link was initialized and the events were sent to the service.
This was because the logic to initialize the sender link and the logic to actually send events across the link were separated into separate retriable operations. When a connection `disconnected` event is encountered after the link is initialized, the existing link is closed. However, the sending of events can be retried. Since the link was closed, we'd get our version of a null pointer error when trying to interact with the link.
This PR does 2 things to fix the issue and prevent …
> [event-hubs] fixes sendBatch race condition causing TypeError to be thrown

- common/config/rush/common-versions.json
- sdk/anomalydetector/ai-anomaly-detector/package.json
- sdk/attestation/attestation/package.json
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-phone-numbers/package.json
- sdk/communication/communication-sms/package.json
- sdk/digitaltwins/digital-twins-core/package.json
- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-secrets/package.json
- sdk/metricsadvisor/ai-metrics-advisor/package.json
- sdk/quantum/quantum-jobs/package.json
- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry/package.json
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-file-datalake/package.json
- sdk/synapse/synapse-artifacts/package.json
- sdk/template/template/package.json
- sdk/textanalytics/ai-text-analytics/package.json
Currently, the master branch has the identity package in v2 and requires any consuming package to re-record their recordings due to us relying on the msal libraries for our credential implementation.
In #14909, we have laid out the plan to release a v1 update for Identity instead. 
Simply changing the version in Identity package will break tests in playback mode for all packages that use Identity in their recordings. 
Since re-recording would take considerable amount of time, we want to unblock the work needed to ship v1 of Identity. Therefore, this PR updates the dev dependencies on identity such that the master branch can stay in a state where tests can remain green in the playback mode.
The issue https://github.com/Azure/azure-sdk-for-js/issues/14581 tracks the work needed to update …
> Pin minor version of identity dev dependency to avoid re-recording

- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/src/connectionContext.ts
- sdk/eventhub/event-hubs/src/eventHubReceiver.ts
- sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts
This PR fixes a race condition that can occur when the connection to the service is disconnected, or the connection is explicitly closed via `(EventHubConsumerClient|EventHubProducerClient).close()`. The race condition manifests as an UnhandledPromiseRejectionWarning when attempting to close senders or receivers in the `disconnected` event handler due to trying to close a resource that doesn't exist.
Prior to this PR, the `disconnected` event handler grabbed the list of receiver/sender names from the `connectionContext`, then serially closed the receiver/senders.
https://github.com/Azure/azure-sdk-for-js/blob/13e6508b63d1b819d9d86392856e76b15e61c913/sdk/eventhub/event-hubs/src/connectionContext.ts#L333-L346
Whenever a sender/receiver is closed, it removes itself from the …
> [event-hubs] fix race condition preventing connection recovery during connection disconnect

- sdk/keyvault/keyvault-certificates/README.md
- sdk/keyvault/keyvault-certificates/migration-guide.md
- sdk/keyvault/keyvault-keys/README.md
- sdk/keyvault/keyvault-keys/migration-guide.md
In #15023 we moved to samples to the V2 flow, but some links were still pointing to the old URL.
This commit updates the links that were reported broken in [ADO](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=867335) to point to the right sample.
> [KeyVault] - Fix broken sample links

- sdk/communication/communication-sms/karma.conf.js
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_can_send_an_sms_message.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_can_send_an_sms_message_to_multiple_recipients.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_can_send_an_sms_message_with_options_passed_in.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_sends_a_new_message_each_time_send_is_called.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_aad_when_sending_sms/recording_throws_an_exception_when_sending_from_an_invalid_number.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_can_send_an_sms_message.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_can_send_an_sms_message_to_multiple_recipients.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_can_send_an_sms_message_with_options_passed_in.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_sends_a_new_message_each_time_send_is_called.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.json
- sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_throws_an_exception_when_sending_from_an_invalid_number.json
- sdk/communication/communication-sms/test/internal/smsClient.internal.spec.ts
- sdk/communication/communication-sms/test/public/smsClient.spec.ts
- sdk/communication/communication-sms/test/public/utils/recordedClient.ts
Using the ClientSecretCredential enables us to run these live tests in the browser so we no longer have to skip them :)
This is a companion to the same changes for the communication-identity package
> [communication] SMS enable aad browser tests

- sdk/core/core-http/package.json
to fix build error:
[!] Error: Cannot find module '@rollup/plugin-replace'
This plugin is used in rollup.config.base.js.
> [core-http] add missing dev dependency @rollup/plugin-replace

- sdk/communication/communication-chat/test/public/utils/recordedClient.ts
- sdk/communication/communication-identity/test/public/utils/recordedClient.ts
- sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts
- sdk/communication/communication-sms/test/public/utils/recordedClient.ts
Remove condition that would not log the ms-cv header if the network request was successful
> Log ms-cv header for every request during tests

- sdk/keyvault/keyvault-admin/README.md
- sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
- sdk/keyvault/keyvault-admin/src/backupClient.ts
- sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
- sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
- sdk/keyvault/keyvault-keys/src/keysModels.ts
- sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts
- KeyVaultBackupClient constructor: pipelineOptions -> options
- CryptographyClient: keyId -> keyID
- createKeyOptions: +hsm
As part of pre-GA architecture feedback with @chradek we discovered a few things that we would want to address
before we GA the KeyVault packages in May. This PR is meant to collect all the various items and keep track of what
was changed.
> [KeyVault] - Address various architecture feedback

- sdk/mixedreality/mixedreality-authentication/src/util/jwt.ts
- sdk/mixedreality/mixedreality-authentication/test/jwt.spec.ts
JWT expiry values are in seconds-since-epoch whereas JS Dates are in milliseconds-since-epoch.
> Ensure AccessTokens are interpreted as milliseconds-since-epoch values.

- common/tools/dev-tool/src/templates/sampleReadme.md.ts
- sdk/keyvault/keyvault-admin/samples/v4/typescript/README.md
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/README.md
- sdk/keyvault/keyvault-keys/samples/v4/typescript/README.md
- sdk/keyvault/keyvault-secrets/samples/v4/typescript/README.md
- Always use `.js` extension in samples README
Our README assumes that TS samples will be compiled to JS and that the users run the JS files in either case, the only 
difference between the run commands in our README is where the JS file will be run from. Since these are now generated,
it required a fix in dev-tool.
Fixes #15073
> [dev-tool] [KeyVault] - Fix TypeScript sample README

- sdk/keyvault/keyvault-admin/samples-dev/backupRestoreHelloWorld.ts
- sdk/keyvault/keyvault-admin/samples-dev/backupSelectiveRestore.ts
- sdk/keyvault/keyvault-admin/samples/v4/javascript/backupRestoreHelloWorld.js
- sdk/keyvault/keyvault-admin/samples/v4/javascript/backupSelectiveRestore.js
- sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupRestoreHelloWorld.ts
- sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupSelectiveRestore.ts
- sdk/keyvault/keyvault-admin/test/README.md
- sdk/keyvault/keyvault-admin/test/internal/serviceVersionParameter.spec.ts
- sdk/keyvault/keyvault-admin/test/utils/authentication.ts
- sdk/keyvault/keyvault-certificates/karma.conf.js
- sdk/keyvault/keyvault-keys/test/README.md
- sdk/keyvault/keyvault-secrets/karma.conf.js
- sdk/keyvault/keyvault-secrets/test/utils/testAuthentication.ts
1. Add some information about deploying, testing, and using a Managed HSM for KV Admin and KV Keys
2. Replace KEYVAULT_URI with AZURE_MANAGEDHSM_URI in KV Admin
3. Remove any remaining traces of KEYVAULT_NAME env var
1. Deploying a Managed HSM is a more involved process but one that is required for any KV Admin tests and some KV Keys tests. A bit of documentation helps there
2. KV Admin only supports AZURE_MANAGEDHSM_URI so it makes sense to make that explicit
3. We can no longer use KEYVAULT_NAME because it's always expected that the URI will be https://<name>.vault.azure.net
We removed most of the KEYVAULT_NAME usages in prior commits, but this just cleans up the remaining for (3)
Resolves #15095 
Resolves #15064
> [KeyVault] - Add Managed HSM contributing docs and remove KEYVAULT_NAME

- sdk/eventgrid/eventgrid/README.md
When events are sent using the Cloud Event schema, and distributed
tracing is used (so `traceparent` and `tracestate` are added as
headers on an http request) the SDK automatically ads this information
to the events as they are sent, using the distributed tracing
extension properties, as documented by the CNCF, if they are not
already present.
Add a small note about this to the README.md
Fixes #12036
> [EventGrid] Document Distributed Tracing extension

- common/config/rush/common-versions.json
- sdk/anomalydetector/ai-anomaly-detector/package.json
- sdk/attestation/attestation/package.json
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-phone-numbers/package.json
- sdk/communication/communication-sms/package.json
- sdk/digitaltwins/digital-twins-core/package.json
- sdk/keyvault/keyvault-secrets/package.json
- sdk/metricsadvisor/ai-metrics-advisor/package.json
- sdk/quantum/quantum-jobs/package.json
- sdk/schemaregistry/schema-registry-avro/package.json
- sdk/storage/storage-blob/package.json
- sdk/synapse/synapse-artifacts/package.json
- sdk/template/template/package.json
Reverting d79b27726e0aeb96629e9de87ded8da17b8067aa since we are now no longer pinning to 1.3.0.
But we still have multiple Identity versions in-flight, so we need the common-versions config
This will resolve https://dev.azure.com/azure-sdk/internal/_build/results?buildId=873579&view=results
As per https://github.com/Azure/azure-sdk-for-js/issues/14909#issuecomment-827980215 we no longer need to prep a v1 update to identity so we can standardize on ^1.1.0 (as there will be no changes in v1 that will force re-recording)
> Revert "Pin identity dev dependency to avoid re-recording"

- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/src/utils.ts
- sdk/core/core-client/test/serviceClient.spec.ts
This PR adds back a missing condition during the refactoring in #14387
> [core-client] wrap response body for more mapper types

- common/tools/dev-tool/src/commands/samples/publish.ts
- common/tools/dev-tool/src/config/rollup.base.config.ts
- common/tools/dev-tool/src/templates/sampleReadme.md.ts
- common/tools/dev-tool/src/util/fileTree.ts
- common/tools/dev-tool/src/util/sampleGenerationInfo.ts
Some samples have nested directory structures. For example, service bus has an `advanced` folder, and cognitive search has many subfolders. This PR teaches dev-tool to handle these nested sample directory structures correctly.
In addition, it introduces another `azsdk` JSDoc tag: `@azsdk-util`, which indicates that a sample should be omitted from the sample index in the README files. This is useful for utility modules that we still want to copy into the sample output directory, but don't want to be added to the list of sample files in the READMEs. Simply add `@azsdk-util` or `@azsdk-util true` to a JSDoc comment at the top of the file (per a great suggestion from @maorleger, the handler for `@azsdk` tags now assumes that if a tag is specified with _no_ value, that is the same as the value …
> [dev-tool] Enable sample folders to use nested directory structures.

- sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
- sdk/core/core-rest-pipeline/src/policies/bearerTokenChallengeAuthenticationPolicy.ts
Azure Container Registry allows anonymous pull access, in which case,
TokenCredential is not required for its challenge-based auth
flow. This PR makes `credential` optional in the bearer token
challenge auth policy options so that an `undefined` value is allowed.
ACR SDK library would send an unauthorized initial request to ACR Api
endpoint, get a challenge back then continue to handle the challenge.
> [core-rest-pipeline] make CAE policy options' `credential` optional

- .vscode/cspell.json
- eng/pipelines/templates/steps/analyze.yml
Example spelling error warning: 
Adding this in does not block the build or turn the build yellow/red. Additional information at: https://aka.ms/azsdk/engsys/spellcheck
> Add spellcheck to analysis

- sdk/identity/identity/README.md
This PR has the below changes
- Removed note on the persistent cache feature as the feature was reverted in #15041
- Add note on the last version of the `@azure/identity` package that is guaranteed to work in Node.js v8
- Add note on the min Node.js version that the package does support
The messaging has been reviewed offline by @bterlson, @xirzec, @chradek  and @elraikhm 
cc @schaabs, @joshfree
> [Identity] Add note on Node.js support

- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/samples/SasToken/SasTokenAuth.ts
- sdk/cosmosdb/cosmos/src/client/SasToken/PermissionScopeValues.ts
- sdk/cosmosdb/cosmos/src/client/SasToken/SasTokenProperties.ts
- sdk/cosmosdb/cosmos/src/common/constants.ts
- sdk/cosmosdb/cosmos/src/tsconfig.strict.json
- sdk/cosmosdb/cosmos/src/utils/SasToken.ts
- sdk/cosmosdb/cosmos/src/utils/headers.ts
- sdk/cosmosdb/cosmos/test/internal/unit/sasToken.spec.ts
(Experimental) Shared access signatures provide secure delegated access to CosmosDB resources. With SAS, you have control over how a client can access your data. Users can create SAS tokens externally or inside the SDK. When a request includes a SAS token, CosmosDB utilizes the key to grant access. These are experimental operations available via JS SDK.
* The payload is composed of the following:
* {@literal
*    user\n
*    userTag\n
*    resourcePath\n
*    BASE64_ENCODED_PartitionKeyValues_CommaSeparated\n
*    epochStartTime\n
*    epochExpiryTime\n
*    keyKind\n
*    shortAsHexControlPlaneReaderScope\n
*    shortAsHexControlPlaneWriterScope\n
*    intAsHexDataPlaneReaderScope\n
*    intAsHexDataPlaneWriterScope\n
* }
*
* @return the permission configuration payload.
> (SAS) Grant access to CosmosDB resources using shared access signatures (experimental)

- sdk/communication/CONTRIBUTING.md
- sdk/communication/communication-phone-numbers/karma.conf.js
- sdk/communication/communication-phone-numbers/test.env
- sdk/communication/communication-phone-numbers/test/README.md
- sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts
- sdk/communication/communication-sms/karma.conf.js
- sdk/communication/communication-sms/test.env
- sdk/communication/communication-sms/test/README.md
- sdk/communication/communication-sms/test/public/utils/recordedClient.ts
This change only renames `AZURE_COMMUNICATION_LIVETEST_CONNECTION_STRING` to `COMMUNICATION_LIVETEST_STATIC_CONNECTION_STRING` to comply with other languages.
Will have an upcoming change for updating dynamic connection string for chat and identity.
> Renaming to standard static EV

- sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/README.md
- sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/tsconfig.json
- sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
- sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts
- sdk/schemaregistry/schema-registry/README.md
- sdk/schemaregistry/schema-registry/review/schema-registry.api.md
- sdk/schemaregistry/schema-registry/samples-dev/schemaRegistrySample.ts
- sdk/schemaregistry/schema-registry/samples/v1/javascript/package.json
- sdk/schemaregistry/schema-registry/samples/v1/javascript/schemaRegistrySample.js
- sdk/schemaregistry/schema-registry/samples/v1/typescript/README.md
- sdk/schemaregistry/schema-registry/samples/v1/typescript/package.json
- sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
- sdk/schemaregistry/schema-registry/samples/v1/typescript/tsconfig.json
- sdk/schemaregistry/schema-registry/src/models.ts
- sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
- sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts
Fix #15130 
This turns 404 into undefined for SchemaRegistryClient.getSchemaId and SchemaRegistryClient.getSchemaById.
Note, however, that the higher level avro serializer still throws on not found. While it feels natural enough when you're interacting directly with the schema registry to say "can I have a schema that matches this description or id" and get back undefined for "sorry no such schema", there is no natural return value for when you try to serialize/deserialize with a schema that is not found in the registry, so I think this should remain an exception, but I'm open to different design ideas.
>  [schema registry] Return undefined for not found

- sdk/core/core-http/CHANGELOG.md
- sdk/core/core-http/src/policies/tracingPolicy.ts
- sdk/core/core-http/test/policies/tracingPolicyTests.ts
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts
- sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts
- Call `span.setStatus` in both the happy path and the error path
- When handling an error, add the message and the http error code
I noticed in passing that the core http spans had a status of UNSET which is a recent change in OpenTel. As a fix, added
code to ensure we set the status correctly. 
I debated whether a 400-ish status code is an error or not, since we technically did make a successful HTTP call, but my 
reasoning for setting all errors as trace errors is that as a developer if I _only_ had this data (without any convenience layer
spans) I would want to see where this error originated. 
This is a smallish change, but one that will help add consistency in our tracing data.
Resolves #15045
> [core] - Ensure Tracing Spans have the correct status
