Azure/azure-sdk-for-js

swagger_to_sdk_config.json

@daschult This is why you get no PR. Bot generates in the wrong folder, and then git has nothing to commit in it's scope.

Fix output folder

---

packages/@azure/arm-consumption/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4239

[AutoPR consumption/resource-manager] Back out bad merge in Go config file

---

packages/@azure/arm-automation/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4247

[AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.

---

packages/@azure/arm-features/package.json
packages/@azure/arm-links/package.json
packages/@azure/arm-locks/lib/models/index.ts
packages/@azure/arm-locks/lib/models/mappers.ts
packages/@azure/arm-locks/package.json
packages/@azure/arm-managedapplications/lib/models/index.ts
packages/@azure/arm-managedapplications/lib/models/mappers.ts
packages/@azure/arm-managedapplications/package.json
packages/@azure/arm-policy/lib/models/index.ts
packages/@azure/arm-policy/lib/models/mappers.ts
packages/@azure/arm-policy/package.json
packages/@azure/arm-resources/lib/operations/resourceGroups.ts
packages/@azure/arm-resources/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4297

[AutoPR resources/resource-manager] added to description of allowed characters for resource group name

---

packages/@azure/arm-servicebus/lib/models/index.ts
packages/@azure/arm-servicebus/lib/models/mappers.ts
packages/@azure/arm-servicebus/lib/models/namespacesMappers.ts
packages/@azure/arm-servicebus/lib/operations/namespaces.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4254

[AutoPR servicebus/resource-manager] ServiceBus : Added namespace Migrate API reported in ARMs Fundamental dashboard

---

packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/mappers.ts
packages/@azure/arm-containerservice/lib/models/parameters.ts
packages/@azure/arm-containerservice/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4322

[AutoPR containerservices/resource-manager] ACS multiapi for Python

---

packages/@azure/arm-consumption/lib/models/index.ts
packages/@azure/arm-consumption/lib/operations/marketplaces.ts
packages/@azure/arm-consumption/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4327

[AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level

---

packages/@azure/arm-servicebus/README.md
packages/@azure/arm-servicebus/package.json

Created to accumulate context: servicebus/resource-manager

[AutoPR] servicebus/resource-manager

---

packages/@azure/arm-consumption/README.md
packages/@azure/arm-consumption/lib/models/index.ts
packages/@azure/arm-consumption/lib/operations/marketplaces.ts
packages/@azure/arm-consumption/package.json

Created to accumulate context: consumption/resource-manager

[AutoPR] consumption/resource-manager

---

packages/@azure/arm-apimanagement/lib/apiManagementClientContext.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4384

[AutoPR apimanagement/resource-manager] Move version 2018-01-01 to stable folder

---

packages/@azure/arm-reservations/README.md
packages/@azure/arm-reservations/lib/azureReservationAPIContext.ts
packages/@azure/arm-reservations/lib/models/index.ts
packages/@azure/arm-reservations/lib/operations/reservation.ts
packages/@azure/arm-reservations/lib/operations/reservationOrder.ts
packages/@azure/arm-reservations/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4370

[AutoPR reservations/resource-manager] Reservations RP 2018-06-01 Preview: Add new reserved resource type RedHat

---

packages/@azure/arm-apimanagement/lib/apiManagementClientContext.ts
packages/@azure/arm-apimanagement/package.json

Created to accumulate context: apimanagement/resource-manager

[AutoPR] apimanagement/resource-manager

---

packages/@azure/arm-containerregistry/README.md
packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
packages/@azure/arm-containerregistry/lib/models/index.ts
packages/@azure/arm-containerregistry/lib/models/mappers.ts
packages/@azure/arm-containerregistry/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4389

[AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step

---

packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4383

[AutoPR cognitiveservices/data-plane/VisualSearch] [Visual Search API] Update encoding format documentation per PM request

---

packages/@azure/arm-datamigration/lib/dataMigrationServiceClientContext.ts
packages/@azure/arm-datamigration/lib/models/index.ts
packages/@azure/arm-datamigration/lib/models/parameters.ts
packages/@azure/arm-datamigration/lib/operations/files.ts
packages/@azure/arm-datamigration/lib/operations/operations.ts
packages/@azure/arm-datamigration/lib/operations/projects.ts
packages/@azure/arm-datamigration/lib/operations/resourceSkus.ts
packages/@azure/arm-datamigration/lib/operations/services.ts
packages/@azure/arm-datamigration/lib/operations/tasks.ts
packages/@azure/arm-datamigration/lib/operations/usages.ts
packages/@azure/arm-datamigration/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4400

[AutoPR datamigration/resource-manager] Fix Version value to fix Ruby SDK Generation

---

packages/@azure/cognitiveservices-face/README.md
packages/@azure/cognitiveservices-face/lib/faceClientContext.ts
packages/@azure/cognitiveservices-face/lib/models/index.ts
packages/@azure/cognitiveservices-face/lib/operations/face.ts
packages/@azure/cognitiveservices-face/lib/operations/faceListOperations.ts
packages/@azure/cognitiveservices-face/lib/operations/largeFaceListOperations.ts
packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupOperations.ts
packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupPerson.ts
packages/@azure/cognitiveservices-face/lib/operations/personGroupOperations.ts
packages/@azure/cognitiveservices-face/lib/operations/personGroupPerson.ts
packages/@azure/cognitiveservices-face/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4438

[AutoPR cognitiveservices/data-plane/Face] FaceAPI Split Python conf in it's own file

---

packages/@azure/arm-network/lib/models/index.ts
packages/@azure/arm-network/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4443

[AutoPR network/resource-manager] Make NIC VM ref readonly

---

packages/@azure/arm-appservice/lib/models/index.ts
packages/@azure/arm-appservice/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4453

[AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model

---

packages/@azure/cognitiveservices-autosuggest/README.md
packages/@azure/cognitiveservices-autosuggest/lib/autoSuggestClient.ts
packages/@azure/cognitiveservices-autosuggest/lib/autoSuggestClientContext.ts
packages/@azure/cognitiveservices-autosuggest/lib/models/index.ts
packages/@azure/cognitiveservices-autosuggest/lib/models/mappers.ts
packages/@azure/cognitiveservices-autosuggest/lib/models/parameters.ts
packages/@azure/cognitiveservices-autosuggest/package.json
packages/@azure/cognitiveservices-autosuggest/rollup.config.js
packages/@azure/cognitiveservices-autosuggest/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4490

[AutoPR cognitiveservices/data-plane/AutoSuggest] Description of Autosuggest usage needs improvement.

---

packages/@azure/arm-network/lib/models/index.ts
packages/@azure/arm-network/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4497

[AutoPR network/resource-manager] Fixes the missing array for the header actions

---

packages/@azure/arm-cosmosdb/README.md
packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClient.ts
packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
packages/@azure/arm-cosmosdb/lib/models/index.ts
packages/@azure/arm-cosmosdb/lib/models/mappers.ts
packages/@azure/arm-cosmosdb/lib/models/parameters.ts
packages/@azure/arm-cosmosdb/lib/operations/collection.ts
packages/@azure/arm-cosmosdb/lib/operations/collectionPartition.ts
packages/@azure/arm-cosmosdb/lib/operations/collectionPartitionRegion.ts
packages/@azure/arm-cosmosdb/lib/operations/collectionRegion.ts
packages/@azure/arm-cosmosdb/lib/operations/database.ts
packages/@azure/arm-cosmosdb/lib/operations/databaseAccountRegion.ts
packages/@azure/arm-cosmosdb/lib/operations/databaseAccounts.ts
packages/@azure/arm-cosmosdb/lib/operations/operations.ts
packages/@azure/arm-cosmosdb/lib/operations/partitionKeyRangeId.ts
packages/@azure/arm-cosmosdb/lib/operations/partitionKeyRangeIdRegion.ts
packages/@azure/arm-cosmosdb/lib/operations/percentile.ts
packages/@azure/arm-cosmosdb/lib/operations/percentileSourceTarget.ts
packages/@azure/arm-cosmosdb/lib/operations/percentileTarget.ts
packages/@azure/arm-cosmosdb/package.json
packages/@azure/arm-cosmosdb/rollup.config.js
packages/@azure/arm-cosmosdb/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4513

[AutoPR cosmos-db/resource-manager] typo: cosmos-db/resource-manager/Microsoft.DocumentDB/cosmos-db.json

---

packages/@azure/arm-appservice/README.md
packages/@azure/arm-appservice/lib/models/index.ts
packages/@azure/arm-appservice/lib/models/mappers.ts
packages/@azure/arm-appservice/lib/models/parameters.ts
packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/certificates.ts
packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
packages/@azure/arm-appservice/lib/operations/diagnostics.ts
packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/domains.ts
packages/@azure/arm-appservice/lib/operations/provider.ts
packages/@azure/arm-appservice/lib/operations/recommendations.ts
packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
packages/@azure/arm-appservice/lib/operations/webApps.ts
packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
packages/@azure/arm-appservice/package.json
packages/@azure/arm-appservice/rollup.config.js
packages/@azure/arm-appservice/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4504

[AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json

---

packages/@azure/arm-appservice/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4527

[AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments

---

packages/@azure/arm-storage/lib/models/index.ts
packages/@azure/arm-storage/lib/operations/storageAccounts.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4549

[AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage

---

packages/@azure/arm-datafactory/README.md
packages/@azure/arm-datafactory/lib/dataFactoryManagementClient.ts
packages/@azure/arm-datafactory/lib/dataFactoryManagementClientContext.ts
packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
packages/@azure/arm-datafactory/lib/models/index.ts
packages/@azure/arm-datafactory/lib/models/mappers.ts
packages/@azure/arm-datafactory/lib/models/parameters.ts
packages/@azure/arm-datafactory/lib/operations/activityRuns.ts
packages/@azure/arm-datafactory/lib/operations/datasets.ts
packages/@azure/arm-datafactory/lib/operations/factories.ts
packages/@azure/arm-datafactory/lib/operations/integrationRuntimeNodes.ts
packages/@azure/arm-datafactory/lib/operations/integrationRuntimes.ts
packages/@azure/arm-datafactory/lib/operations/linkedServices.ts
packages/@azure/arm-datafactory/lib/operations/operations.ts
packages/@azure/arm-datafactory/lib/operations/pipelineRuns.ts
packages/@azure/arm-datafactory/lib/operations/pipelines.ts
packages/@azure/arm-datafactory/lib/operations/rerunTriggers.ts
packages/@azure/arm-datafactory/lib/operations/triggerRuns.ts
packages/@azure/arm-datafactory/lib/operations/triggers.ts
packages/@azure/arm-datafactory/package.json
packages/@azure/arm-datafactory/rollup.config.js
packages/@azure/arm-datafactory/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4536

[AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory/entityTypes/LinkedService

---

packages/@azure/arm-resources/lib/models/index.ts
packages/@azure/arm-resources/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4501

[AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup

---

packages/@azure/arm-security/README.md
packages/@azure/arm-security/lib/models/index.ts
packages/@azure/arm-security/lib/models/mappers.ts
packages/@azure/arm-security/lib/models/parameters.ts
packages/@azure/arm-security/lib/operations/advancedThreatProtection.ts
packages/@azure/arm-security/lib/operations/alerts.ts
packages/@azure/arm-security/lib/operations/allowedConnections.ts
packages/@azure/arm-security/lib/operations/autoProvisioningSettings.ts
packages/@azure/arm-security/lib/operations/compliances.ts
packages/@azure/arm-security/lib/operations/discoveredSecuritySolutions.ts
packages/@azure/arm-security/lib/operations/externalSecuritySolutions.ts
packages/@azure/arm-security/lib/operations/informationProtectionPolicies.ts
packages/@azure/arm-security/lib/operations/jitNetworkAccessPolicies.ts
packages/@azure/arm-security/lib/operations/locations.ts
packages/@azure/arm-security/lib/operations/operations.ts
packages/@azure/arm-security/lib/operations/pricings.ts
packages/@azure/arm-security/lib/operations/securityContacts.ts
packages/@azure/arm-security/lib/operations/settings.ts
packages/@azure/arm-security/lib/operations/tasks.ts
packages/@azure/arm-security/lib/operations/topology.ts
packages/@azure/arm-security/lib/operations/workspaceSettings.ts
packages/@azure/arm-security/lib/securityCenter.ts
packages/@azure/arm-security/lib/securityCenterContext.ts
packages/@azure/arm-security/package.json
packages/@azure/arm-security/rollup.config.js
packages/@azure/arm-security/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4562

[AutoPR security/resource-manager] rename folder paths for autorest code generation

---

packages/@azure/arm-datafactory/lib/models/index.ts
packages/@azure/arm-datafactory/lib/operations/integrationRuntimes.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4573

[AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory

---

packages/@azure/arm-storagesync/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4565

[AutoPR storagesync/resource-manager] Microsoft.StorageSync - Fix Issue 4559 and other known problems with preview version

---

packages/@azure/arm-appservice/README.md
packages/@azure/arm-appservice/lib/models/index.ts
packages/@azure/arm-appservice/lib/models/mappers.ts
packages/@azure/arm-appservice/lib/models/parameters.ts
packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/certificates.ts
packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
packages/@azure/arm-appservice/lib/operations/diagnostics.ts
packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/domains.ts
packages/@azure/arm-appservice/lib/operations/provider.ts
packages/@azure/arm-appservice/lib/operations/recommendations.ts
packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
packages/@azure/arm-appservice/lib/operations/webApps.ts
packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
packages/@azure/arm-appservice/package.json
packages/@azure/arm-appservice/rollup.config.js
packages/@azure/arm-appservice/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4502

[AutoPR web/resource-manager] typo: Fix AppServiceCertificateOrders.json

---

packages/@azure/arm-resources/lib/models/deploymentsMappers.ts
packages/@azure/arm-resources/lib/models/index.ts
packages/@azure/arm-resources/lib/models/resourceGroupsMappers.ts
packages/@azure/arm-resources/lib/models/resourcesMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4600

[AutoPR resources/resource-manager] Fix the ARM R2062 error for Microsoft.Resources

---

packages/@azure/arm-resources/lib/models/deploymentsMappers.ts
packages/@azure/arm-resources/lib/models/index.ts
packages/@azure/arm-resources/lib/models/resourceGroupsMappers.ts
packages/@azure/arm-resources/lib/models/resourcesMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4618

[AutoPR resources/resource-manager] Revert "Fix the ARM R2062 error for Microsoft.Resources"

---

packages/@azure/arm-containerregistry/README.md
packages/@azure/arm-containerregistry/lib/containerRegistryManagementClient.ts
packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
packages/@azure/arm-containerregistry/lib/models/index.ts
packages/@azure/arm-containerregistry/lib/models/mappers.ts
packages/@azure/arm-containerregistry/lib/models/parameters.ts
packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
packages/@azure/arm-containerregistry/lib/operations/operations.ts
packages/@azure/arm-containerregistry/lib/operations/registries.ts
packages/@azure/arm-containerregistry/lib/operations/replications.ts
packages/@azure/arm-containerregistry/lib/operations/runs.ts
packages/@azure/arm-containerregistry/lib/operations/tasks.ts
packages/@azure/arm-containerregistry/lib/operations/webhooks.ts
packages/@azure/arm-containerregistry/package.json
packages/@azure/arm-containerregistry/rollup.config.js
packages/@azure/arm-containerregistry/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4506

[AutoPR containerregistry/resource-manager] [ACR] Add empty resource group name validation, minor cleanup

---

packages/@azure/arm-apimanagement/lib/models/index.ts
packages/@azure/arm-apimanagement/lib/operations/apiDiagnosticLogger.ts
packages/@azure/arm-apimanagement/lib/operations/apiIssue.ts
packages/@azure/arm-apimanagement/lib/operations/apiIssueAttachment.ts
packages/@azure/arm-apimanagement/lib/operations/apiIssueComment.ts
packages/@azure/arm-apimanagement/lib/operations/diagnosticLogger.ts
packages/@azure/arm-apimanagement/lib/operations/property.ts
packages/@azure/arm-apimanagement/lib/operations/reports.ts
packages/@azure/arm-apimanagement/lib/operations/subscription.ts
packages/@azure/arm-apimanagement/lib/operations/tagDescription.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4602

[AutoPR apimanagement/resource-manager] Added example for template params

---

packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
packages/@azure/arm-cosmosdb/lib/operations/databaseAccounts.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4665

[AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB

---

packages/@azure/cognitiveservices-entitysearch/README.md
packages/@azure/cognitiveservices-entitysearch/lib/entitySearchAPIClient.ts
packages/@azure/cognitiveservices-entitysearch/lib/entitySearchAPIClientContext.ts
packages/@azure/cognitiveservices-entitysearch/lib/models/index.ts
packages/@azure/cognitiveservices-entitysearch/lib/models/mappers.ts
packages/@azure/cognitiveservices-entitysearch/lib/models/parameters.ts
packages/@azure/cognitiveservices-entitysearch/lib/operations/entitiesOperations.ts
packages/@azure/cognitiveservices-entitysearch/package.json
packages/@azure/cognitiveservices-entitysearch/rollup.config.js
packages/@azure/cognitiveservices-entitysearch/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4651

[AutoPR cognitiveservices/data-plane/EntitySearch] typo: cognitiveservices/data-plane/EntitySearch

---

packages/@azure/arm-billing/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4632

[AutoPR billing/resource-manager] typo: Microsoft.Billing

---

packages/@azure/cognitiveservices-imagesearch/README.md
packages/@azure/cognitiveservices-imagesearch/lib/imageSearchAPIClient.ts
packages/@azure/cognitiveservices-imagesearch/lib/imageSearchAPIClientContext.ts
packages/@azure/cognitiveservices-imagesearch/lib/models/index.ts
packages/@azure/cognitiveservices-imagesearch/lib/models/mappers.ts
packages/@azure/cognitiveservices-imagesearch/lib/models/parameters.ts
packages/@azure/cognitiveservices-imagesearch/lib/operations/imagesOperations.ts
packages/@azure/cognitiveservices-imagesearch/package.json
packages/@azure/cognitiveservices-imagesearch/rollup.config.js
packages/@azure/cognitiveservices-imagesearch/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4652

[AutoPR cognitiveservices/data-plane/ImageSearch] typo: cognitiveservices/data-plane/ImageSearch

---

packages/@azure/cognitiveservices-newssearch/README.md
packages/@azure/cognitiveservices-newssearch/lib/models/index.ts
packages/@azure/cognitiveservices-newssearch/lib/models/mappers.ts
packages/@azure/cognitiveservices-newssearch/lib/models/parameters.ts
packages/@azure/cognitiveservices-newssearch/lib/newsSearchAPIClient.ts
packages/@azure/cognitiveservices-newssearch/lib/newsSearchAPIClientContext.ts
packages/@azure/cognitiveservices-newssearch/lib/operations/newsOperations.ts
packages/@azure/cognitiveservices-newssearch/package.json
packages/@azure/cognitiveservices-newssearch/rollup.config.js
packages/@azure/cognitiveservices-newssearch/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4654

[AutoPR cognitiveservices/data-plane/NewsSearch] typo: cognitiveservices/data-plane/NewsSearch

---

packages/@azure/arm-links/lib/models/index.ts
packages/@azure/arm-resources/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4755

[AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources

---

.scripts/commandLine.ts
gulpfile.ts

Related to https://github.com/Azure/azure-sdk-for-node/issues/4231.

Add ignore-version to gulp pack

---

packages/@azure/arm-recoveryservices-siterecovery/lib/models/index.ts
packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationJobs.ts
packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationStorageClassificationMappings.ts
packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationvCenters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4749

[AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices

---

packages/@azure/arm-deviceprovisioningservices/README.md
packages/@azure/arm-deviceprovisioningservices/lib/iotDpsClient.ts
packages/@azure/arm-deviceprovisioningservices/lib/iotDpsClientContext.ts
packages/@azure/arm-deviceprovisioningservices/lib/models/index.ts
packages/@azure/arm-deviceprovisioningservices/lib/models/mappers.ts
packages/@azure/arm-deviceprovisioningservices/lib/models/parameters.ts
packages/@azure/arm-deviceprovisioningservices/lib/operations/dpsCertificate.ts
packages/@azure/arm-deviceprovisioningservices/lib/operations/iotDpsResource.ts
packages/@azure/arm-deviceprovisioningservices/lib/operations/operations.ts
packages/@azure/arm-deviceprovisioningservices/package.json
packages/@azure/arm-deviceprovisioningservices/rollup.config.js
packages/@azure/arm-deviceprovisioningservices/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4684

[AutoPR deviceprovisioningservices/resource-manager] typo: Microsoft.Devices

---

packages/@azure/arm-storagesync/lib/operations/serverEndpoints.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4787

[AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync

---

packages/@azure/arm-security/lib/models/index.ts
packages/@azure/arm-security/lib/operations/alerts.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4763

[AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security

---

packages/@azure/arm-hanaonazure/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4773

[AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96

---

packages/@azure/arm-servicemap/README.md
packages/@azure/arm-servicemap/lib/models/index.ts
packages/@azure/arm-servicemap/lib/models/mappers.ts
packages/@azure/arm-servicemap/lib/models/parameters.ts
packages/@azure/arm-servicemap/lib/operations/clientGroups.ts
packages/@azure/arm-servicemap/lib/operations/machineGroups.ts
packages/@azure/arm-servicemap/lib/operations/machines.ts
packages/@azure/arm-servicemap/lib/operations/maps.ts
packages/@azure/arm-servicemap/lib/operations/ports.ts
packages/@azure/arm-servicemap/lib/operations/processes.ts
packages/@azure/arm-servicemap/lib/operations/summaries.ts
packages/@azure/arm-servicemap/lib/servicemapManagementClient.ts
packages/@azure/arm-servicemap/lib/servicemapManagementClientContext.ts
packages/@azure/arm-servicemap/package.json
packages/@azure/arm-servicemap/rollup.config.js
packages/@azure/arm-servicemap/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4764

[AutoPR service-map/resource-manager] typo: service-map/resource-manager/Microsoft.OperationalInsights

---

packages/@azure/arm-appinsights/lib/models/index.ts
packages/@azure/arm-appinsights/lib/operations/webTests.ts
packages/@azure/arm-appinsights/lib/operations/workItemConfigurations.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4713

[AutoPR applicationinsights/resource-manager] chore: Rename microsoft.insights to Microsoft.Insights

---

packages/@azure/arm-servicefabricmesh/lib/models/index.ts
packages/@azure/arm-servicefabricmesh/lib/operations/secretValueOperations.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4779

[AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh

---

packages/@azure/arm-servicebus/README.md
packages/@azure/arm-servicebus/lib/models/index.ts
packages/@azure/arm-servicebus/lib/models/mappers.ts
packages/@azure/arm-servicebus/lib/models/parameters.ts
packages/@azure/arm-servicebus/lib/operations/disasterRecoveryConfigs.ts
packages/@azure/arm-servicebus/lib/operations/eventHubs.ts
packages/@azure/arm-servicebus/lib/operations/migrationConfigs.ts
packages/@azure/arm-servicebus/lib/operations/namespaces.ts
packages/@azure/arm-servicebus/lib/operations/operations.ts
packages/@azure/arm-servicebus/lib/operations/premiumMessagingRegionsOperations.ts
packages/@azure/arm-servicebus/lib/operations/queues.ts
packages/@azure/arm-servicebus/lib/operations/regions.ts
packages/@azure/arm-servicebus/lib/operations/rules.ts
packages/@azure/arm-servicebus/lib/operations/subscriptions.ts
packages/@azure/arm-servicebus/lib/operations/topics.ts
packages/@azure/arm-servicebus/lib/serviceBusManagementClient.ts
packages/@azure/arm-servicebus/lib/serviceBusManagementClientContext.ts
packages/@azure/arm-servicebus/package.json
packages/@azure/arm-servicebus/rollup.config.js
packages/@azure/arm-servicebus/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4626

[AutoPR servicebus/resource-manager] added new API for NetworkRuleSet

---

packages/@azure/arm-timeseriesinsights/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4810

[AutoPR timeseriesinsights/resource-manager] typo: timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights

---

packages/@azure/arm-appservice/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4813

[AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.CertificateRegistration

---

packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
packages/@azure/arm-datafactory/lib/models/index.ts
packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
packages/@azure/arm-datafactory/lib/models/mappers.ts
packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
packages/@azure/arm-datafactory/lib/models/triggersMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4780

[AutoPR datafactory/resource-manager] Add support for HDIinsight cluster with Enterprise Serurity Package

---

packages/@azure/arm-labservices/lib/models/globalUsersMappers.ts
packages/@azure/arm-labservices/lib/models/index.ts
packages/@azure/arm-labservices/lib/models/mappers.ts
packages/@azure/arm-labservices/lib/operations/globalUsers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4797

[AutoPR labservices/resource-manager] [LabServices] Fix typo, remove required from optional param

---

packages/@azure/arm-logic/lib/models/index.ts
packages/@azure/arm-logic/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4769

[AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API

---

packages/@azure/arm-resourcehealth/README.md
packages/@azure/arm-resourcehealth/lib/microsoftResourceHealth.ts
packages/@azure/arm-resourcehealth/lib/microsoftResourceHealthContext.ts
packages/@azure/arm-resourcehealth/lib/models/index.ts
packages/@azure/arm-resourcehealth/lib/models/mappers.ts
packages/@azure/arm-resourcehealth/lib/models/parameters.ts
packages/@azure/arm-resourcehealth/lib/operations/availabilityStatuses.ts
packages/@azure/arm-resourcehealth/lib/operations/operations.ts
packages/@azure/arm-resourcehealth/package.json
packages/@azure/arm-resourcehealth/rollup.config.js
packages/@azure/arm-resourcehealth/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4830

[AutoPR resourcehealth/resource-manager] typo: resourcehealth/resource-manager/Microsoft.ResourceHealth

---

packages/@azure/arm-appservice/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4814

[AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.DomainRegistration

---

packages/@azure/servicefabric/lib/models/index.ts
packages/@azure/servicefabric/lib/operations/meshSecretValue.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4834

[AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric

---

packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts
packages/@azure/cognitiveservices-visualsearch/lib/visualSearchClientContext.ts
packages/@azure/cognitiveservices-visualsearch/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4829

[AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch

---

packages/@azure/arm-containerservice/README.md
packages/@azure/arm-containerservice/lib/containerServiceClient.ts
packages/@azure/arm-containerservice/lib/containerServiceClientContext.ts
packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/mappers.ts
packages/@azure/arm-containerservice/lib/models/openShiftManagedClustersMappers.ts
packages/@azure/arm-containerservice/lib/models/parameters.ts
packages/@azure/arm-containerservice/lib/operations/containerServices.ts
packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts
packages/@azure/arm-containerservice/lib/operations/operations.ts
packages/@azure/arm-containerservice/package.json
packages/@azure/arm-containerservice/rollup.config.js
packages/@azure/arm-containerservice/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4597

[AutoPR containerservices/resource-manager] ContainerServices - OpenShift - Add new routes and update

---

packages/@azure/arm-containerregistry/lib/models/index.ts
packages/@azure/arm-containerregistry/lib/models/mappers.ts
packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4895

[AutoPR containerregistry/resource-manager] [ACR] Add IP rules

---

packages/@azure/arm-containerinstance/README.md
packages/@azure/arm-containerinstance/lib/containerInstanceManagementClient.ts
packages/@azure/arm-containerinstance/lib/containerInstanceManagementClientContext.ts
packages/@azure/arm-containerinstance/lib/models/index.ts
packages/@azure/arm-containerinstance/lib/models/mappers.ts
packages/@azure/arm-containerinstance/lib/models/parameters.ts
packages/@azure/arm-containerinstance/lib/operations/containerGroupUsage.ts
packages/@azure/arm-containerinstance/lib/operations/containerGroups.ts
packages/@azure/arm-containerinstance/lib/operations/containerOperations.ts
packages/@azure/arm-containerinstance/lib/operations/operations.ts
packages/@azure/arm-containerinstance/lib/operations/serviceAssociationLink.ts
packages/@azure/arm-containerinstance/package.json
packages/@azure/arm-containerinstance/rollup.config.js
packages/@azure/arm-containerinstance/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4643

[AutoPR containerinstance/resource-manager] New APIs for container instance

---

packages/@azure/arm-sql/lib/models/index.ts
packages/@azure/arm-sql/lib/models/mappers.ts
packages/@azure/arm-sql/lib/operations/managedDatabases.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4907

[AutoPR sql/resource-manager] Updating managed database swagger

---

packages/@azure/arm-appservice/README.md
packages/@azure/arm-appservice/lib/models/index.ts
packages/@azure/arm-appservice/lib/models/mappers.ts
packages/@azure/arm-appservice/lib/models/parameters.ts
packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/certificates.ts
packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
packages/@azure/arm-appservice/lib/operations/diagnostics.ts
packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
packages/@azure/arm-appservice/lib/operations/domains.ts
packages/@azure/arm-appservice/lib/operations/provider.ts
packages/@azure/arm-appservice/lib/operations/recommendations.ts
packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
packages/@azure/arm-appservice/lib/operations/webApps.ts
packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
packages/@azure/arm-appservice/package.json
packages/@azure/arm-appservice/rollup.config.js
packages/@azure/arm-appservice/tsconfig.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4505

[AutoPR web/resource-manager] typo: Fix web/resource-manager/Microsoft.Web/service.json

---

packages/@azure/arm-labservices/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4926

[AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices

---

packages/@azure/batch/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4918

[AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch

---

packages/@azure/arm-network/lib/models/applicationSecurityGroupsMappers.ts
packages/@azure/arm-network/lib/models/index.ts
packages/@azure/arm-network/lib/operations/applicationSecurityGroups.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4951

[AutoPR network/resource-manager] Exposing PATCH for Application Security Group (ASG)

---

packages/@azure/arm-storage/lib/models/index.ts
packages/@azure/arm-storage/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4938

[AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName

---

packages/@azure/arm-hanaonazure/lib/models/hanaInstancesMappers.ts
packages/@azure/arm-hanaonazure/lib/models/index.ts
packages/@azure/arm-hanaonazure/lib/models/mappers.ts
packages/@azure/arm-hanaonazure/lib/operations/hanaInstances.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4949

[AutoPR hanaonazure/resource-manager] Add PATCH API example to hanaonazure

---

packages/@azure/arm-containerservice/LICENSE.txt
packages/@azure/arm-containerservice/lib/models/parameters.ts
packages/@azure/arm-containerservice/lib/operations/containerServices.ts
packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4979

[AutoPR containerservices/resource-manager] [AKS] add empty resource group validation

---

packages/@azure/arm-containerservice/LICENSE.txt
packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/parameters.ts
packages/@azure/arm-containerservice/lib/operations/containerServices.ts
packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4948

[AutoPR containerservices/resource-manager] [AKS]: Remove 200/OK response from reset SP/AAD api

---

packages/@azure/arm-containerservice/LICENSE.txt
packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/parameters.ts
packages/@azure/arm-containerservice/lib/operations/containerServices.ts
packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4980

[AutoPR containerservices/resource-manager] [AKS] add missing description fields

---

packages/@azure/arm-apimanagement/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5000

[AutoPR apimanagement/resource-manager] OpenAPIv3 support documented

---

packages/@azure/arm-servicebus/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4989

[AutoPR servicebus/resource-manager] Updated as per review comments from ARM Team for Eventhub swagger

---

packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
packages/@azure/arm-datafactory/lib/models/index.ts
packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
packages/@azure/arm-datafactory/lib/models/mappers.ts
packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
packages/@azure/arm-datafactory/lib/models/triggersMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5007

[AutoPR datafactory/resource-manager] [Datafactory] Add Webhook Activity to Azure Data Factory 

---

packages/@azure/arm-sql/LICENSE.txt
packages/@azure/arm-sql/lib/operations/longTermRetentionBackups.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5025

[AutoPR sql/resource-manager] Fix set LTR policy example

---

packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
packages/@azure/arm-datafactory/lib/models/index.ts
packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
packages/@azure/arm-datafactory/lib/models/mappers.ts
packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
packages/@azure/arm-datafactory/lib/models/triggersMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5019

[AutoPR datafactory/resource-manager] [DataFactory]Support schema property for dataset

---

packages/@azure/eventgrid/LICENSE.txt
packages/@azure/eventgrid/lib/models/index.ts
packages/@azure/eventgrid/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5027

[AutoPR eventgrid/data-plane] Add MediaJobOutputProgressEventData in Media Services EventGrid swagger

---

packages/@azure/arm-cognitiveservices/LICENSE.txt
packages/@azure/arm-cognitiveservices/lib/models/index.ts
packages/@azure/arm-cognitiveservices/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5035

[AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.

---

packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/movingMessagesToDLQ.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/topicFilters.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesLoop.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/scheduledMessages.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/session.ts

- Fixed samples, simplified few others as discussed offline.
- Testing done:- Individually executed samples, found and filed bug reports
- #43

Refactor samples for Service Bus

---

packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
packages/@azure/servicebus/data-plane/lib/serviceBusMessage.ts
packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts

Session id was missing in Amqp message body when sending a request for deferral messages.

Resolved - Error when settling a deferred msg in a session enabled queue in Service Bus

---

packages/@azure/servicebus/data-plane/lib/queueClient.ts
packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts

Updated some un-noticed errors in the comments corresponding to the Docs

[ServiceBus] - Minor errors in comments corresponding to the Docs

---

packages/@azure/arm-features/LICENSE.txt
packages/@azure/arm-links/LICENSE.txt
packages/@azure/arm-locks/LICENSE.txt
packages/@azure/arm-managedapplications/LICENSE.txt
packages/@azure/arm-policy/LICENSE.txt
packages/@azure/arm-resources/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4971

[AutoPR resources/resource-manager] Adding ResourceGroup example

---

packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts

Pass maxAutoRenewDurationInSeconds parameter from subscription client.

[Service Bus] Enable AutoLockRenewal for subscription client

---

packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts

Refactoring  -  Streaming Receiver With Sessions
No issues at all. All the tests are working fine.

[Service Bus] - Refactor tests - Streaming Receiver With Sessions

---

packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5101

[AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property

---

packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
packages/@azure/servicebus/data-plane/lib/core/streamingReceiver.ts
packages/@azure/servicebus/data-plane/lib/queueClient.ts
packages/@azure/servicebus/data-plane/lib/receiver.ts
packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts

Doc updates as per feedback provided in https://github.com/Azure/azure-sdk-for-js/pull/1002

[Service Bus] Doc updates as per feedback

---

packages/@azure/servicebus/data-plane/package-lock.json

Update the package-lock.json file after the package version change.

---

packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts

Please look at issue #1023 and https://github.com/Azure/azure-sdk-for-js/issues/1023#issuecomment-458765825 for more context

Fix tests to set purge option to false for DLQs

---

packages/@azure/arm-resourcehealth/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5116

[AutoPR resourcehealth/resource-manager] Resourcehealth events response

---

.azure-pipelines/client.test.live.yml
package.json
packages/@azure/servicebus/data-plane/package-lock.json
packages/@azure/servicebus/data-plane/package.json
packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts

Verification build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3708

Create pipeline to run tests in live azure

---

packages/@azure/servicebus/data-plane/lib/clientEntityContext.ts
packages/@azure/servicebus/data-plane/lib/index.ts
packages/@azure/servicebus/data-plane/lib/queueClient.ts
packages/@azure/servicebus/data-plane/lib/receiver.ts
packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
packages/@azure/servicebus/data-plane/test/renewLockSessions.spec.ts
packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts

Issue:
https://github.com/Azure/azure-sdk-for-js/issues/1011
Reference:
ramya-rao-a@14dff08

[Service Bus] - SessionReceiver - Abstraction layer for sessions 

---

packages/@azure/servicebus/data-plane/.gitignore
packages/@azure/servicebus/data-plane/api-extractor.json
packages/@azure/servicebus/data-plane/package-lock.json
packages/@azure/servicebus/data-plane/package.json

Enabling manual run of api-extractor as per https://github.com/Azure/azure-service-bus-node/issues/200

[Service Bus] Enable manual run of api-extractor

---

packages/@azure/servicebus/data-plane/lib/connectionContext.ts
packages/@azure/servicebus/data-plane/lib/util/constants.ts

Update User Agent as per guidance:
`azure-sdk-for-js/azure-<package-name>/<package-version> (NODE-VERSION <node-version>; <os-type> <os-version>)`

[Service Bus] Update User Agent as per guidance

---

packages/@azure/servicebus/data-plane/rollup.base.config.js

[Service Bus] Update the rollup config to mark 'os' as external dependency

---

packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts

**Issue:**
https://github.com/Azure/azure-sdk-for-js/issues/1071
Tests to cover the features `getState` and `setState` in Session enabled Queues/Subscriptions with partitioned/unpartitioned variations.

[Service Bus] Testing GetState-SetState for sessions

---

packages/@azure/arm-containerservice/lib/models/index.ts
packages/@azure/arm-containerservice/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5150

[AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"

---

packages/@azure/servicebus/data-plane/examples/README.md
packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/movingMessagesToDLQ.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/processMessageFromDLQ.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/sessionState.ts
packages/@azure/servicebus/data-plane/examples/advancedFeatures/topicFilters.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/browseMessages.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesLoop.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesStreaming.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/scheduledMessages.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/sendMessages.ts
packages/@azure/servicebus/data-plane/examples/gettingStarted/session.ts

This PR updates our samples to use the published package of Service Bus instead of source code

[Service Bus] Update samples to use published package

---

.azure-pipelines/client.test.live.yml

- Expect tests to take about 60 minutes
- A good timeout is typically 2x expected
Diff without whitespace: https://github.com/Azure/azure-sdk-for-js/pull/1094/files?w=1
Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3817

Set job timeout to 120 minutes

---

packages/@azure/servicebus/data-plane/README.md

[Serivce Bus] Update README to point to the right repo for examples

---

packages/@azure/arm-authorization/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5154

[AutoPR authorization/resource-manager] Removed "x-ms-pageable" from the elevateAccess API

---

packages/@azure/arm-policyinsights/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5168

[AutoPR policyinsights/resource-manager] typo: aliase -> alias

---

packages/@azure/arm-keyvault/LICENSE.txt
packages/@azure/arm-keyvault/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5172

[AutoPR keyvault/resource-manager] add description of access policies required condition

---

packages/@azure/arm-operationalinsights/LICENSE.txt

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5182

[AutoPR operationalinsights/resource-manager] Add gateways API

---

packages/@azure/servicebus/data-plane/lib/clientEntityContext.ts
packages/@azure/servicebus/data-plane/lib/queueClient.ts
packages/@azure/servicebus/data-plane/lib/serviceBusMessage.ts
packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
packages/@azure/servicebus/data-plane/test/renewLockSessions.spec.ts

This PR tracks  changes, fixes related to handling of Session Lock Lost scenarios.
Refer to https://github.com/Azure/azure-sdk-for-js/pull/1128,
https://github.com/Azure/azure-sdk-for-js/issues/1051#issuecomment-460853986, https://github.com/Azure/azure-sdk-for-js/issues/1051#issuecomment-461264529 and https://github.com/Azure/azure-sdk-for-js/issues/1051#issuecomment-461287666 for more context.

[Service Bus] Surface Session Lock Lost error to the user

---

packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts

This PR fixes the test failure reported in #1205

[Service Bus] Dont clear rules on default description 

---

packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts

Error message for invalid correlation filters as per https://github.com/Azure/azure-service-bus-node/issues/184

[Service Bus] Error message for invalid correlation filters

---

packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
packages/@azure/servicebus/data-plane/test/renewLock.spec.ts
packages/@azure/servicebus/data-plane/test/renewLockSessions.spec.ts
packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts
packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
packages/@azure/servicebus/data-plane/test/testUtils.ts

This PR implements the changes as described in #1158

Use unique test messages across tests

---

packages/@azure/eventhubs/client/package-lock.json
packages/@azure/eventhubs/client/package.json
packages/@azure/eventhubs/processor/package-lock.json
packages/@azure/eventhubs/processor/package.json

as it is used when running tests in the engineering system builds.

[Event Hub] Add dev dependency to mocha-junit-reporter

---

packages/@azure/servicebus/data-plane/test/testUtils.ts

Updated AAD env var, 
Removed SERVICEBUS_NAMESPACE var
https://github.com/Azure/azure-sdk-for-js/issues/1196#issuecomment-464936486

[Service Bus] Update AAD env var, remove SERVICEBUS_NAMESPACE var

---

.azure-pipelines/client.test.live.yml
packages/@azure/servicebus/data-plane/package-lock.json
packages/@azure/servicebus/data-plane/package.json

- Provides real-time log of test progress
- Helps identify hanging tests
- Fixes #1081
Verification build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5592

Write live test results to console

---

.azure-pipelines/client.test.live.yml
.azure-pipelines/client.yml

Standardize indention and publishing

---

packages/@azure/arm-network/lib/models/index.ts
packages/@azure/arm-network/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5243

[AutoPR network/resource-manager] Network: fix descriptions & remove unused/duplicate definitions

---

packages/@azure/servicebus/data-plane/examples/javascript/advancedFeatures/deferral.js
packages/@azure/servicebus/data-plane/examples/javascript/advancedFeatures/movingMessagesToDLQ.js
packages/@azure/servicebus/data-plane/examples/javascript/advancedFeatures/sessionState.js
packages/@azure/servicebus/data-plane/examples/javascript/gettingStarted/receiveMessagesLoop.js
packages/@azure/servicebus/data-plane/examples/javascript/gettingStarted/receiveMessagesStreaming.js
packages/@azure/servicebus/data-plane/examples/javascript/gettingStarted/scheduledMessages.js
packages/@azure/servicebus/data-plane/examples/javascript/gettingStarted/session.js
packages/@azure/servicebus/data-plane/examples/typescript/advancedFeatures/deferral.ts
packages/@azure/servicebus/data-plane/examples/typescript/advancedFeatures/movingMessagesToDLQ.ts
packages/@azure/servicebus/data-plane/examples/typescript/advancedFeatures/sessionState.ts
packages/@azure/servicebus/data-plane/examples/typescript/gettingStarted/browseMessages.ts
packages/@azure/servicebus/data-plane/examples/typescript/gettingStarted/receiveMessagesLoop.ts
packages/@azure/servicebus/data-plane/examples/typescript/gettingStarted/receiveMessagesStreaming.ts
packages/@azure/servicebus/data-plane/examples/typescript/gettingStarted/scheduledMessages.ts
packages/@azure/servicebus/data-plane/examples/typescript/gettingStarted/session.ts

[Service Bus] Update the receive samples in gettingStarted with a note on session usage

---

packages/@azure/arm-containerservice/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5310

[AutoPR containerservice/resource-manager] mark the new features as PREVIEW in description 

---

packages/@azure/arm-network/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5317

[AutoPR network/resource-manager] Add support for Local Sku

---

.azure-pipelines/client.test.live.yml

- Fixes #1156 
CC: @Azure/azure-sdk-eng

Add linux to live test matrix

---

packages/@azure/eventhubs/client/tests/receiver.spec.ts

Improve reliability of QuotaExceededError test

---

packages/@azure/arm-monitor/lib/models/index.ts
packages/@azure/arm-monitor/lib/models/mappers.ts
packages/@azure/arm-monitor/lib/models/parameters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5378

[AutoPR monitor/resource-manager] fix package tag for new API version

---

packages/@azure/arm-mediaservices/LICENSE.txt
packages/@azure/arm-mediaservices/README.md
packages/@azure/arm-mediaservices/lib/models/accountFiltersMappers.ts
packages/@azure/arm-mediaservices/lib/models/assetFiltersMappers.ts
packages/@azure/arm-mediaservices/lib/models/assetsMappers.ts
packages/@azure/arm-mediaservices/lib/models/contentKeyPoliciesMappers.ts
packages/@azure/arm-mediaservices/lib/models/index.ts
packages/@azure/arm-mediaservices/lib/models/jobsMappers.ts
packages/@azure/arm-mediaservices/lib/models/liveEventsMappers.ts
packages/@azure/arm-mediaservices/lib/models/liveOutputsMappers.ts
packages/@azure/arm-mediaservices/lib/models/mappers.ts
packages/@azure/arm-mediaservices/lib/models/mediaservicesMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingEndpointsMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingLocatorsMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingPoliciesMappers.ts
packages/@azure/arm-mediaservices/lib/models/transformsMappers.ts
packages/@azure/arm-mediaservices/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5340

[AutoPR mediaservices/resource-manager] Add filter to StreamingLocator and Streaming presets.

---

.azure-pipelines/client.yml
.docsettings.yml

* Enabling Content Verification
* Adding all the existing presence and content issues as known issues. 
* Removing "*/data-plane/*" exception in favor of real issues. 
* Cleaning up `analyze` step of job to remove wonky sudo usage.

Enabling Content Verification

---

packages/@azure/graph/lib/models/applicationsMappers.ts
packages/@azure/graph/lib/models/index.ts
packages/@azure/graph/lib/models/mappers.ts
packages/@azure/graph/lib/models/parameters.ts
packages/@azure/graph/lib/operations/applications.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5417

[AutoPR graphrbac/data-plane] Add service principals by app id microsoft.graph rbac

---

.docsettings.yml

Until we have a discussion with management team to determine what's up with this.

Omit Cognitive Services From Readme Checks

---

packages/@azure/arm-mediaservices/LICENSE.txt
packages/@azure/arm-mediaservices/README.md
packages/@azure/arm-mediaservices/lib/models/accountFiltersMappers.ts
packages/@azure/arm-mediaservices/lib/models/assetFiltersMappers.ts
packages/@azure/arm-mediaservices/lib/models/assetsMappers.ts
packages/@azure/arm-mediaservices/lib/models/contentKeyPoliciesMappers.ts
packages/@azure/arm-mediaservices/lib/models/index.ts
packages/@azure/arm-mediaservices/lib/models/jobsMappers.ts
packages/@azure/arm-mediaservices/lib/models/liveEventsMappers.ts
packages/@azure/arm-mediaservices/lib/models/liveOutputsMappers.ts
packages/@azure/arm-mediaservices/lib/models/mappers.ts
packages/@azure/arm-mediaservices/lib/models/mediaservicesMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingEndpointsMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingLocatorsMappers.ts
packages/@azure/arm-mediaservices/lib/models/streamingPoliciesMappers.ts
packages/@azure/arm-mediaservices/lib/models/transformsMappers.ts
packages/@azure/arm-mediaservices/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5413

[AutoPR mediaservices/resource-manager] Add preset enum ContentAwareEncodingExperimental

---

.azure-pipelines/client.yml

Add variable to enable/disable npm audit

---

packages/@azure/arm-storage/lib/operations/storageAccounts.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5453

[AutoPR storage/resource-manager] Added feature revoke user delegation key

---

packages/@azure/keyvault/examples/secrets.pipeline.ts
packages/@azure/keyvault/examples/singleSecret.ts
packages/@azure/keyvault/tests/pipeline.test.ts
packages/@azure/keyvault/tests/secrets.test.ts

Remove example code that assumes existing secret

Clean up tests

---

packages/@azure/eventhubs/client/changelog.md
packages/@azure/eventhubs/client/package-lock.json
packages/@azure/eventhubs/client/package.json

[Event Hubs] updated changelog for 2.0.0

[Event Hubs] updated changelog for 2.0.0

---

packages/@azure/eventhubs/client/changelog.md
packages/@azure/eventhubs/client/package.json

[Event Hubs] Update homepage in package.json

[Event Hubs] Update homepage in package.json

---

packages/@azure/servicebus/data-plane/README.md

Update README as per [guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/README-TEMPLATE.md).

[Service Bus] Update README as per guidelines

---

sdk/servicebus/service-bus/src/queueClient.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/subscriptionClient.ts

[Service Bus] peek messageCount -> maxMessageCount

---

sdk/servicebus/service-bus/test/batchReceiver.spec.ts

Fix typos in test code

---

sdk/servicebus/service-bus/CONTRIBUTING.md
sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/package.json

Links updated for new repo structure for servicebus in following files:
- readme.md
- Contributing.md
- package.json
@ramya-rao-a

update links for servicebus

---

packages/@azure/arm-appservice/lib/models/deletedWebAppsMappers.ts
packages/@azure/arm-appservice/lib/models/diagnosticsMappers.ts
packages/@azure/arm-appservice/lib/models/index.ts
packages/@azure/arm-appservice/lib/models/mappers.ts
packages/@azure/arm-appservice/lib/models/recommendationsMappers.ts
packages/@azure/arm-appservice/lib/models/resourceHealthMetadataOperationsMappers.ts
packages/@azure/arm-appservice/lib/models/topLevelDomainsMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5542

[AutoPR web/resource-manager] Add Managed Identity envelope to SitePatchResource

---

sdk/eventhub/event-hubs/samples/README.md
sdk/eventhub/event-processor-host/samples/README.md
sdk/servicebus/service-bus/CONTRIBUTING.md

- Broken paths fixed for  servicebus and eventhub
@jeremymeng

Broken paths fixed for  servicebus and eventhub

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/deferredMessage.spec.ts
sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
sdk/servicebus/service-bus/test/renewLock.spec.ts
sdk/servicebus/service-bus/test/renewLockSessions.spec.ts
sdk/servicebus/service-bus/test/sendSchedule.spec.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
sdk/servicebus/service-bus/test/stress/stress_fixedNumberOfClientsMultipleQueues.ts
sdk/servicebus/service-bus/test/stress/stress_fixedNumberOfClientsSingleQueue.ts
sdk/servicebus/service-bus/test/stress/stress_messageRandomDisposition.ts
sdk/servicebus/service-bus/test/stress/stress_messageRandomDispositionOnSession.ts
sdk/servicebus/service-bus/test/stress/stress_singleClient.ts
sdk/servicebus/service-bus/test/stress/stress_singleMessageComplete.ts
sdk/servicebus/service-bus/test/testUtils.ts
sdk/servicebus/service-bus/test/topicFilters.spec.ts

Function renames as per conclusions made in #1729

[Service Bus] Last set of function renames for better ux

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json

Fixed the path for the test:node in package.json for Storage-file package, as a result of recent restructuring
@HarshaNalluru

[Stoarge-file] updated path for test files

---

sdk/servicebus/service-bus/test/topicFilters.spec.ts

Testing done:
Verified all topicFilter spec tests pass (twice in a row)

Add test for #1916

---

packages/@azure/arm-features/LICENSE.txt
packages/@azure/arm-features/README.md
packages/@azure/arm-features/package.json
packages/@azure/arm-links/LICENSE.txt
packages/@azure/arm-links/README.md
packages/@azure/arm-links/package.json
packages/@azure/arm-locks/LICENSE.txt
packages/@azure/arm-locks/README.md
packages/@azure/arm-locks/package.json
packages/@azure/arm-managedapplications/LICENSE.txt
packages/@azure/arm-managedapplications/README.md
packages/@azure/arm-managedapplications/package.json
packages/@azure/arm-policy/LICENSE.txt
packages/@azure/arm-policy/README.md
packages/@azure/arm-policy/package.json
packages/@azure/arm-resources/LICENSE.txt
packages/@azure/arm-resources/README.md
packages/@azure/arm-resources/lib/models/index.ts
packages/@azure/arm-resources/lib/models/mappers.ts
packages/@azure/arm-resources/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5529

[AutoPR resources/resource-manager] Backfilling Microsoft.Resources and subscriptions Swagger specs up to 2019-03-01 API version

---

sdk/servicebus/service-bus/test/stress/stress_messageLockRenewalBatchingThenStreaming.ts

Missed out a local commit from merge on 4/19.

[Service Bus] Stress test fix - stress_messageLockRenewalBatchingThenStreaming.ts

---

sdk/cognitiveservices/cognitiveservices-luis-authoring/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5747

[AutoPR cognitiveservices/data-plane/LUIS/Authoring] Refactor enum list of /definitions/ReadableType

---

sdk/servicebus/service-bus/changelog.md
sdk/servicebus/service-bus/package-lock.json
sdk/servicebus/service-bus/package.json

changelog for preview 3 for service bus

[Service Bus] changelog for preview 3

---

sdk/compute/arm-compute/lib/models/index.ts
sdk/compute/arm-compute/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5740

[AutoPR compute/resource-manager] Add hyperVGeneration enum property to ImageProperties

---

sdk/cognitiveservices/cognitiveservices-luis-runtime/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5798

[AutoPR cognitiveservices/data-plane/LUIS/Runtime] typo: cognitiveservices/data-plane/LUIS/Runtime

---

sdk/servicebus/service-bus/test/perf/rhea-promise/send.ts

- Hosts different than *.servicebus.windows.net
- Env var SERVICE_BUS_ALLOW_UNAUTHORIZED to allow untrusted server certs

Add more options to rhea-promise perf test

---

sdk/containerservice/arm-containerservice/lib/models/index.ts
sdk/containerservice/arm-containerservice/lib/models/mappers.ts
sdk/containerservice/arm-containerservice/lib/models/parameters.ts
sdk/containerservice/arm-containerservice/lib/operations/agentPools.ts
sdk/containerservice/arm-containerservice/lib/operations/containerServices.ts
sdk/containerservice/arm-containerservice/lib/operations/managedClusters.ts
sdk/containerservice/arm-containerservice/lib/operations/operations.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5819

[AutoPR containerservice/resource-manager] Update list-orchestrator for api spec 2019-04-01

---

sdk/containerservice/arm-containerservice/lib/models/index.ts
sdk/containerservice/arm-containerservice/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5841

[AutoPR containerservice/resource-manager] Revert node public ip support from 2019-04-01 model.

---

sdk/cosmosdb/cosmos/samples/MultiRegionWrite/package.json

- Prevents publishing to npmjs

Add private:true to cosmos MultiRegionWrite sample

---

.docsettings.yml
sdk/core/amqp/Contributing.md
sdk/core/amqp/package.json

For more context refer to #2704

Update AMQP version and README and regex in .docsettings.yml

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json

Update package.json to have "sideEffects" set to false as per [Typescript guidelines](https://azuresdkspecs.z5.web.core.windows.net/TypeScriptSpec.html).
>Side effects refer to modifications to the runtime environment of the program as a result of including a module. For example, including a polyfill library is a sideEffect as it mutates the global environment and later code depends on its presence. Side effects make it harder for tools to optimize your build and should be avoided.

[Event Hubs] [EPH] Update package.json to have "sideEffects" set to false

---

sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/src/subscriptionClient.ts

Fixing documentation before the final release!
Fixes #2739

[Service Bus] Doc updates

---

sdk/cdn/arm-cdn/lib/models/index.ts
sdk/cdn/arm-cdn/lib/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5893

[AutoPR cdn/resource-manager] make "name" optional in DeliveryRule

---

sdk/cdn/arm-cdn/lib/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5897

[AutoPR cdn/resource-manager] add premium_chinaCdn to CDN sku

---

sdk/appservice/arm-appservice/src/operations/webApps.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5942

[AutoPR web/resource-manager] Add Api-version 2018-11-01 for WebApps Collection

---

sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5908

[AutoPR hanaonazure/resource-manager] Added new SKUs

---

sdk/mixedreality/arm-mixedreality/README.md
sdk/mixedreality/arm-mixedreality/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5909

[AutoPR mixedreality/resource-manager] Update of Mixed Reality Azure Resource Management

---

sdk/compute/arm-compute/src/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5936

[AutoPR compute/resource-manager] Add an example json for using toBeDetached flag for data disks

---

sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/samples/javascript/basic.js
sdk/storage/storage-queue/samples/typescript/basic.ts
sdk/storage/storage-queue/src/MessageIdClient.ts
sdk/storage/storage-queue/src/MessagesClient.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/test/aborter.spec.ts
sdk/storage/storage-queue/test/messageidclient.spec.ts
sdk/storage/storage-queue/test/messagesclient.spec.ts
sdk/storage/storage-queue/test/node/messageidclient.spec.ts
sdk/storage/storage-queue/test/node/messagesclient.spec.ts
sdk/storage/storage-queue/test/node/queueclient.spec.ts
sdk/storage/storage-queue/test/node/sas.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts
sdk/storage/storage-queue/test/queueserviceclient.spec.ts
sdk/storage/storage-queue/test/retrypolicy.spec.ts

with default value of Aborter.none.

[Storage-queue] Make Aborter parameter optional

---

sdk/cognitiveservices/arm-cognitiveservices/src/models/accountsMappers.ts
sdk/cognitiveservices/arm-cognitiveservices/src/models/index.ts
sdk/cognitiveservices/arm-cognitiveservices/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6009

[AutoPR cognitiveservices/resource-manager] Add NetworkRuleSet Support.

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

- Continuation of PR https://github.com/Azure/azure-sdk-for-js/pull/2986/

update archetype to install npm version 6.9

---

sdk/eventgrid/eventgrid/src/models/index.ts
sdk/eventgrid/eventgrid/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5913

[AutoPR eventgrid/data-plane] Add new Event Grid event type for SignalR Service

---

sdk/devtestlabs/arm-devtestlabs/README.md
sdk/devtestlabs/arm-devtestlabs/package.json
sdk/devtestlabs/arm-devtestlabs/src/devTestLabsClientContext.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6033

[AutoPR devtestlabs/resource-manager] chore: jsonfmt devtestlabls

---

sdk/edgegateway/arm-edgegateway/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6059

[AutoPR edgegateway/resource-manager] chore: jsonfmt edgegateway

---

sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6079

[AutoPR hanaonazure/resource-manager] chore: jsonfmt hanaonazure

---

sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

- As suggested opened a new PR for the member ordering rule 
Referencing PR https://github.com/Azure/azure-sdk-for-js/pull/3005
@Azure/azure-sdk-eng @bterlson @ramya-rao-a

[Servicebus] Eslint member ordering

---

sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
sdk/hanaonazure/arm-hanaonazure/src/operations/hanaInstances.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5945

[AutoPR hanaonazure/resource-manager] Add Create HanaInstance API

---

sdk/mariadb/arm-mariadb/README.md
sdk/mariadb/arm-mariadb/package.json
sdk/mariadb/arm-mariadb/src/models/index.ts
sdk/mariadb/arm-mariadb/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6045

[AutoPR mariadb/resource-manager] MariaDB intelligent performance

---

sdk/storage/storage-blob/src/TelemetryPolicyFactory.ts
sdk/storage/storage-file/src/TelemetryPolicyFactory.ts
sdk/storage/storage-queue/src/TelemetryPolicyFactory.ts

https://azuresdkspecs.z5.web.core.windows.net/#general-telemetry

[Storage] Update telemetry string - storage packages

---

sdk/cognitiveservices/cognitiveservices-computervision/package.json
sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClient.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6056

[AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Fix bugs in OCR swagger file

---

sdk/batch/batch/src/batchServiceClient.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6135

[AutoPR batch/data-plane] Updated spec path

---

sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6144

[AutoPR cosmos-db/resource-manager] CosmosDB add Availability Zone option for locations

---

sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
sdk/hanaonazure/arm-hanaonazure/src/operations/hanaInstances.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5976

[AutoPR hanaonazure/resource-manager] Microsoft.HanaOnAzure: Add Delete HanaInstance API

---

sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6172

[AutoPR cosmos-db/resource-manager] Cosmos Python

---

sdk/template/template/package.json
sdk/template/template/tsconfig.json

Related to: https://github.com/Azure/azure-sdk-for-js/pull/3322
Is this all? I feel I'm missing something.

Moving typings to types in the template package

---

sdk/postgresql/arm-postgresql/package.json
sdk/postgresql/arm-postgresql/src/models/index.ts
sdk/postgresql/arm-postgresql/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6175

[AutoPR postgresql/resource-manager] Enable PG 11

---

sdk/batch/batch/src/batchServiceClient.ts
sdk/batch/batch/src/batchServiceClientContext.ts
sdk/batch/batch/src/models/accountMappers.ts
sdk/batch/batch/src/models/index.ts
sdk/batch/batch/src/models/mappers.ts
sdk/batch/batch/src/models/parameters.ts
sdk/batch/batch/src/operations/account.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6113

[AutoPR batch/data-plane] [Batch] Add new data plane verison 2019-06-01

---

sdk/resourcegraph/arm-resourcegraph/package.json
sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6148

[AutoPR resourcegraph/resource-manager] [Resource Graph] result format option added

---

sdk/privatedns/arm-privatedns/README.md
sdk/privatedns/arm-privatedns/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6211

[AutoPR privatedns/resource-manager] chore: jsonfmt privatedns

---

sdk/netapp/arm-netapp/src/models/index.ts
sdk/netapp/arm-netapp/src/models/mappers.ts
sdk/netapp/arm-netapp/src/models/parameters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6086

[AutoPR netapp/resource-manager] Essential corrections to R4 standard swagger for GA

---

sdk/eventgrid/arm-eventgrid/README.md
sdk/eventgrid/arm-eventgrid/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6215

[AutoPR eventgrid/resource-manager] EventgridL fixed package namespace, added java readme file

---

sdk/eventhub/arm-eventhub/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6216

[AutoPR eventhub/resource-manager] EventHub-2018-01-01 Preview : update the API name

---

sdk/redis/arm-rediscache/README.md
sdk/redis/arm-rediscache/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6225

[AutoPR redis/resource-manager] chore: jsonfmt redis

---

sdk/mixedreality/arm-mixedreality/README.md
sdk/mixedreality/arm-mixedreality/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6183

[AutoPR mixedreality/resource-manager] chore: jsonfmt mixedreality

---

sdk/storage/arm-storage/src/models/index.ts
sdk/storage/arm-storage/src/models/mappers.ts
sdk/storage/arm-storage/src/models/parameters.ts
sdk/storage/arm-storage/src/operations/blobContainers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6243

[AutoPR storage/resource-manager] [SRP] Default value change for account property supportsHttpsTrafficOnly

---

sdk/mediaservices/arm-mediaservices/package.json
sdk/mediaservices/arm-mediaservices/src/models/accountFiltersMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/assetFiltersMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/assetsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/contentKeyPoliciesMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/index.ts
sdk/mediaservices/arm-mediaservices/src/models/jobsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/liveEventsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/liveOutputsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/mappers.ts
sdk/mediaservices/arm-mediaservices/src/models/mediaservicesMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/streamingEndpointsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/streamingLocatorsMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/streamingPoliciesMappers.ts
sdk/mediaservices/arm-mediaservices/src/models/transformsMappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6145

[AutoPR mediaservices/resource-manager] typo: mediaservices/resource-manager/Microsoft.Media

---

sdk/netapp/arm-netapp/src/models/index.ts
sdk/netapp/arm-netapp/src/models/mappers.ts
sdk/netapp/arm-netapp/src/models/parameters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6187

[AutoPR netapp/resource-manager] chore: jsonfmt netapp

---

sdk/core/amqp-common/src/retry.ts

Added retry operation type for receiving messages.

[amqp-common] Add retry opreation type for receive messages

---

common/config/rush/pnpm-lock.yaml
rush.json
sdk/storage/storage-datalake/package.json
sdk/storage/storage-datalake/rollup.config.js

Onboarding storage-datalake to rush
@Azure/azure-sdk-eng @HarshaNalluru

onboard Storage-datalake to rush

---

sdk/eventhub/event-hubs/test/receiver.spec.ts

The reason some integration tests were failing was due to state leakage between tests. Specifically, we weren't closing all of the `receivers` after each test, and this caused a variety of issues.
This change does depend on #3494 to pin the version of rollup that's used. To test this PR, I built this commit on top of the changes in #3494 .

[Event Hubs] fixes integration tests

---

sdk/apimanagement/arm-apimanagement/src/models/index.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6249

[AutoPR apimanagement/resource-manager] Custom properties were updated to reflect all the possible values

---

sdk/storage/arm-storage/src/models/blobContainersMappers.ts
sdk/storage/arm-storage/src/models/blobServicesMappers.ts
sdk/storage/arm-storage/src/models/index.ts
sdk/storage/arm-storage/src/models/managementPoliciesMappers.ts
sdk/storage/arm-storage/src/models/mappers.ts
sdk/storage/arm-storage/src/models/parameters.ts
sdk/storage/arm-storage/src/models/storageAccountsMappers.ts
sdk/storage/arm-storage/src/operations/blobContainers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6250

[AutoPR storage/resource-manager] [SRP] Remove azureFilesAadIntegration and add AzureFilesIdentityBased Authentication in storage account properties

---

sdk/resourcegraph/arm-resourcegraph/package.json
sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6235

[AutoPR resourcegraph/resource-manager] chore: jsonfmt resourcegraph

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/eventPosition.spec.ts
sdk/eventhub/event-hubs/test/eventdata.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/iothub.spec.ts
sdk/eventhub/event-hubs/test/misc.spec.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts

Also depends on #3494 
This ports the tests from the master branch, and makes a few changes based on API updates.

[Event Hubs] ports tests from master to track2

---

sdk/mariadb/arm-mariadb/README.md
sdk/mariadb/arm-mariadb/package.json
sdk/mariadb/arm-mariadb/src/models/index.ts
sdk/mariadb/arm-mariadb/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6288

[AutoPR mariadb/resource-manager] MariaDb: updated readme and added java readme

---

sdk/labservices/arm-labservices/README.md
sdk/labservices/arm-labservices/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6127

[AutoPR labservices/resource-manager] chore: jsonfmt labservices

---

sdk/storage/arm-storage/README.md
sdk/storage/arm-storage/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6296

[AutoPR storage/resource-manager] Move Storage to Py v4.x

---

sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts

This change finishes plumbing the `abortSignal` through the management API calls.

[Event Hubs] Support abortSignal for management apis

---

sdk/containerregistry/arm-containerregistry/README.md
sdk/containerregistry/arm-containerregistry/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6300

[AutoPR containerregistry/resource-manager] ACR with Autorest for Python 4

---

sdk/batch/batch/src/batchServiceClient.ts
sdk/batch/batch/src/batchServiceClientContext.ts
sdk/batch/batch/src/models/accountMappers.ts
sdk/batch/batch/src/models/index.ts
sdk/batch/batch/src/models/mappers.ts
sdk/batch/batch/src/models/parameters.ts
sdk/batch/batch/src/operations/account.ts
sdk/batch/batch/src/operations/application.ts
sdk/batch/batch/src/operations/certificateOperations.ts
sdk/batch/batch/src/operations/computeNodeOperations.ts
sdk/batch/batch/src/operations/file.ts
sdk/batch/batch/src/operations/job.ts
sdk/batch/batch/src/operations/jobSchedule.ts
sdk/batch/batch/src/operations/pool.ts
sdk/batch/batch/src/operations/task.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6179

[AutoPR batch/data-plane] Fixed SpecPath batch

---

sdk/features/arm-features/README.md
sdk/features/arm-features/package.json
sdk/links/arm-links/README.md
sdk/links/arm-links/package.json
sdk/locks/arm-locks/README.md
sdk/locks/arm-locks/package.json
sdk/managedapplications/arm-managedapplications/README.md
sdk/managedapplications/arm-managedapplications/package.json
sdk/policy/arm-policy/README.md
sdk/policy/arm-policy/package.json
sdk/resources/arm-resources/README.md
sdk/resources/arm-resources/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6237

[AutoPR resources/resource-manager] chore: jsonfmt resources

---

sdk/servicebus/arm-servicebus/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6247

[AutoPR servicebus/resource-manager] chore: jsonfmt servicebus

---

sdk/storage/storage-blob/samples/javascript/advanced.js
sdk/storage/storage-blob/src/policies/LoggingPolicy.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/utils.spec.ts
sdk/storage/storage-file/samples/javascript/advanced.js
sdk/storage/storage-file/src/policies/LoggingPolicy.ts
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-file/src/utils/utils.common.ts
sdk/storage/storage-file/test/utils.spec.ts
sdk/storage/storage-queue/samples/javascript/basic.js
sdk/storage/storage-queue/src/policies/LoggingPolicy.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/src/utils/utils.common.ts
sdk/storage/storage-queue/test/utils.spec.ts

Sensitive info in request is masked with `*****` before logging.
Add console logger to some javascript samples.

Log requests and response headers

---

sdk/cosmosdb/arm-cosmosdb/README.md
sdk/cosmosdb/arm-cosmosdb/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6320

[AutoPR cosmos-db/resource-manager] chore: jsonfmt cosmos-db

---

sdk/keyvault/keyvault-secrets/.gitignore
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/tests/CRUD.tests.ts
sdk/keyvault/keyvault-secrets/tests/list.test.ts
sdk/keyvault/keyvault-secrets/tests/recoverBackupRestore.test.ts

Full list of tests for keyvault-secrets, as described in #3643 
Fixes #3643

[JS] [KeyVault] Full list of tests for keyvault-secrets

---

sdk/eventhub/arm-eventhub/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6352

[AutoPR eventhub/resource-manager] Add missing multi-api EventHub

---

sdk/hdinsight/arm-hdinsight/package.json
sdk/hdinsight/arm-hdinsight/src/models/index.ts
sdk/hdinsight/arm-hdinsight/src/models/mappers.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6287

[AutoPR hdinsight/resource-manager] [HDInsight] Fix syntax error in description of subDomainSuffix parameter

---

sdk/apimanagement/arm-apimanagement/src/models/index.ts
sdk/apimanagement/arm-apimanagement/src/models/parameters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6373

[AutoPR apimanagement/resource-manager] Remove restriction on groupId

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/samples/usingAadAuth.ts
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts

This PR addresses all the comments of this PR https://github.com/Azure/azure-sdk-for-js/pull/3889
- Comment out aad tests because there are some Identity rollup issues

[Event Hubs] Code cleanup for support for Azure Identity Creds when creating EventHubClient

---

sdk/cosmosdb/arm-cosmosdb/README.md
sdk/cosmosdb/arm-cosmosdb/package.json
sdk/cosmosdb/arm-cosmosdb/src/models/parameters.ts

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6312

[AutoPR cosmos-db/resource-manager] Regex validation for Cosmos DB Accounts

---

sdk/mariadb/arm-mariadb/README.md
sdk/mariadb/arm-mariadb/package.json

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6180

[AutoPR mariadb/resource-manager] chore: jsonfmt mariadb

---

sdk/servicebus/service-bus/test/sendSchedule.spec.ts

For more context refer to #2546

Test on received messages vs peeked

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

This further improves the README based on feedback from @kaerm

Update README based on feedback

---

sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/keyvault/keyvault-secrets/src/index.ts

Addresses only the second point in #3030

[JS] [KeyVault] backupSecret signature fix

---

sdk/eventhub/event-hubs/README.md

Update the README with content for the first preview of Track-2.
NOTE: Since js docs are not updated in the microsoft docs portal, added `(link)` instead of actual link.

[Event Hubs] Track 2: Update README

---

sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/sender.ts

For more context refer to conversation at #2312

[Service Bus] Set isClosed flag at start of close() call

---

sdk/core/core-amqp/rollup.base.config.js
sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/connectionConfig/index.ts
sdk/core/core-amqp/src/connectionConfig/iothubConnectionConfig.ts
sdk/core/core-amqp/src/index.ts

For  more context refer to #3515 
This PR is for porting the fixes to master (for core-amqp)

[core-amqp] Fix 2 build warnings

---

sdk/keyvault/keyvault-keys/tests/utils/recorder.ts
sdk/keyvault/keyvault-secrets/tests/utils/recorder.ts
sdk/storage/storage-blob/test/bloburl.spec.ts
sdk/storage/storage-blob/test/containerurl.spec.ts
sdk/storage/storage-blob/test/node/pagebloburl.spec.ts
sdk/storage/storage-blob/test/serviceurl.spec.ts
sdk/storage/storage-blob/test/utils/recorder.ts
sdk/storage/storage-blob/test/utils/testutils.common.ts
sdk/storage/storage-file/test/fileurl.spec.ts
sdk/storage/storage-file/test/serviceurl.spec.ts
sdk/storage/storage-file/test/utils/recorder.ts
sdk/storage/storage-file/test/utils/testutils.common.ts
sdk/storage/storage-queue/test/messageidurl.spec.ts
sdk/storage/storage-queue/test/node/sas.spec.ts
sdk/storage/storage-queue/test/serviceurl.spec.ts
sdk/storage/storage-queue/test/utils/recorder.ts
sdk/storage/storage-queue/test/utils/testutils.common.ts

[JS] [Storage] Replaced sleep and wait with a delay function that doesn't run on playback

---

sdk/eventhub/event-hubs/test/receiver.spec.ts

[Event Hubs] improve consumer tests

---

sdk/eventhub/event-hubs/src/receiver.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts
sdk/eventhub/event-hubs/test/sender.spec.ts

[Event Hubs] harden tests and update error messages

---

sdk/core/amqp-common/package.json
sdk/core/amqp-common/rollup.base.config.js
sdk/core/amqp-common/src/ConnectionContextBase.ts
sdk/core/amqp-common/src/connectionConfig/index.ts
sdk/core/amqp-common/src/connectionConfig/iothubConnectionConfig.ts
sdk/core/amqp-common/src/index.ts

For more context refer to #3515 
This PR is targeted to port fix for amqp common preview,6 release

[amqp-common] Fix build warnings

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json

Issue - https://github.com/Azure/azure-sdk-for-js/issues/4018
cc: @daviwil

[Storage] Updating test scripts to run `npm run clean`

---

sdk/eventhub/event-hubs/tests.yml

- Add environment variables for event-hubs live tests

add env variables for event-hubs livetests

---

sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file/package.json
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/utils/constants.ts

so we have room for bug fixes for `preview.1` if any.

[Storage] Update versions to preview.1.0

---

sdk/storage/storage-blob/test/utils/recorder.ts
sdk/storage/storage-file/test/utils/recorder.ts
sdk/storage/storage-queue/test/utils/recorder.ts

Required for enabling playback [ #4047 ]

[Storage] provide dummy values for conn.string during playback

---

sdk/eventhub/event-hubs/tests.yml

- ENDPOINT is the additional env variable, rearranged all env variables in alphabetical order in yaml
- @Azure/azure-sdk-eng

added env var for eventhubs

---

sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file/package.json
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/utils/constants.ts

This reverts commit dbc2195bcef3847ab4474d8432030856826cdb0c.

Revert "[Storage] Update versions to preview.1.0 (#4049)"

---

sdk/core/core-amqp/package.json
sdk/core/core-amqp/samples/cbsAuth.ts
sdk/core/core-amqp/samples/eventHubSendUsingAAD.ts
sdk/core/core-amqp/samples/eventhubReceive.ts
sdk/core/core-amqp/samples/eventhubSend.ts
sdk/core/core-amqp/samples/receive.ts
sdk/core/core-amqp/samples/send.ts
sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/auth/iotSas.ts
sdk/core/core-amqp/src/auth/sas.ts
sdk/core/core-amqp/src/auth/token.ts
sdk/core/core-amqp/src/cbs.ts
sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
sdk/core/core-amqp/src/connectionConfig/eventhubConnectionConfig.ts
sdk/core/core-amqp/src/connectionConfig/iothubConnectionConfig.ts
sdk/core/core-amqp/src/dataTransformer.ts
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/index.ts
sdk/core/core-amqp/src/log.ts
sdk/core/core-amqp/src/messageHeader.ts
sdk/core/core-amqp/src/messageProperties.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/retry.ts
sdk/core/core-amqp/src/shims.d.ts
sdk/core/core-amqp/src/util/constants.ts
sdk/core/core-amqp/src/util/utils.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/packageInfo.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts

* The -preview.1 version updated to -preview.1.0
* Added copyright text in the beginning of each file
```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
```

[Event Hubs] [Preview 1] Version and copyright updates

---

sdk/storage/CONTRIBUTING.md
sdk/storage/RecordAndPlayback.md

[Storage] Guidelines for record and playback

---

sdk/core/core-asynciterator-polyfill/package.json
sdk/core/core-paging/package.json

Allow packages to be published

Unprivate packages so we can publish

---

sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-file/karma.conf.js
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-queue/karma.conf.js
sdk/storage/storage-queue/src/QueueServiceClient.ts

and add Symbol polyfill in karma config.

Import core paging to get async iterator polyfill

---

sdk/eventhub/testhub/package.json

As discussed - removing this from the build.

Muted testhub.

---

sdk/eventhub/event-hubs/README.md

Updates the `@azure/event-hubs` README to point to the links in GitHub.io.

[Event Hubs] update readme

---

sdk/identity/identity/package.json

This fixes a missed version change in PR #4048.

Set @azure/identity version to 1.0.0-preview.1

---

sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json

Removing @azure/core-paging from dev dependency list which is already in the dependency list

[Storage] Cleaning duplicated dev dependency

---

sdk/core/core-amqp/README.md
sdk/core/core-amqp/changelog.md

This PR updates the README for core-amqp in order to
- generate clarity
- fix broken samples
and adds a Changelog

[core-amqp] Improved README and Changelog 

---

sdk/core/core-amqp/README.md

Updates samples based on new APIs.

[Core AMQP] update samples in readme

---

sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-queue/ChangeLog.md

Copied from https://github.com/Azure/azure-sdk-for-js/pull/4118/files

[Storage] release notes and more information

---

sdk/eventhub/event-hubs/changelog.md

This PR adds a changelog for the upcoming 5.0.0-preview.1 release.
The link https://aka.ms/azure-sdk-preview1-js right now doesnt go to the right place, but will be updated appropriately soon

Changelog for Event Hubs Preview 1

---

sdk/eventhub/event-hubs/changelog.md

This PR adds links to classes/functions that are new in Track 2 in the Changelog

[Event Hubs] Add links in changelog

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

This updates a couple bad links in the READMEs

Update some bad links in the READMEs

---

common/scripts/generate-doc.js
eng/pipelines/docs.yml

Updates for the support:
- generate-docs node script updated to accept inclusion OR exclusion list args, 
- pipeline updated to accept build args to node script

Support doc generation for "feature" branches other than master

---

sdk/keyvault/keyvault-keys/LICENSE.TXT
sdk/keyvault/keyvault-secrets/LICENSE.TXT

Took the changes and the recommendations from
https://github.com/Azure/azure-sdk-for-js/pull/4012
and added them in a new PR, taken from my personal fork of this repo!
Let me know what you think.
Fixes #3842

[JS] [KeyVault] Fixed the LICENSE files

---

sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts

Bumps the version ahead of our next push to npm

Bump versions to .2

---

sdk/core/amqp-common/package.json
sdk/core/amqp-common/rollup.base.config.js
sdk/core/amqp-common/src/ConnectionContextBase.ts
sdk/core/amqp-common/src/connectionConfig/index.ts
sdk/core/amqp-common/src/connectionConfig/iothubConnectionConfig.ts
sdk/core/amqp-common/src/index.ts

This PR is to bring over fix made for #3515 to the "amqp-common-preview-6" branch
For more context refer to #3976

[amqp-common] Cherry-pick fix for #3515

---

sdk/core/amqp-common/src/auth/aad.ts

For more context refer to #3971

[amqp-common] Bug fix for incorrectly set 'resource' parameter on credentials

---

sdk/core/amqp-common/src/auth/aad.ts

For more context refer to #3972

[amqp-common] Update docs about token lifetime

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json

For more context refer to #3976

[amqp-common] Preview 6 release

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

Apply build tag to nightlies

---

sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/src/index.ts

[KeyVault] Using the proxy only if isNode

---

sdk/core/amqp-common/changelog.md

Add in missed out change details.
Follow-up for #3976

[amqp-common] Fix changelog.md

---

sdk/core/ci.yml
sdk/cosmosdb/ci.yml
sdk/eventhub/ci.yml
sdk/identity/ci.yml
sdk/keyvault/ci.yml
sdk/servicebus/ci.yml
sdk/storage/ci.yml
sdk/template/ci.yml

This PR adds feature branch triggers. Triggering on feature branches should be rare but we want to support governing these branches with both CI and PRs.

Add feature branch triggers.

---

sdk/storage/storage-queue/package.json

https://github.com/Azure/azure-sdk-for-js/commit/b0aecfe70baf6252d1d9495932e98e102685134e#diff-4d7ed1e8443ff76244b610845a484658 
Updates old links in package.json

[Storage] Update storage-js to sdk-for-js

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/identity/identity/package.json
sdk/servicebus/service-bus/package.json
sdk/template/template/package.json

Verified no changes in generated source code

Update dev dependency "rollup-plugin-json" to latest

---

packages.md

@KarishmaGhiya can you take a look at the `profile` packages? Stuff that looks like `@azure/arm-storage-profile-2019-03-01-hybrid`
Is that a real package? Should we omit these from the index?

Update package index for repo restructure

---

sdk/servicebus/service-bus/changelog.md
sdk/servicebus/service-bus/package.json

For more context refer to #4177

[Service Bus] Version update 1.0.3

---

sdk/servicebus/service-bus/test/sessionsTests.spec.ts

Errors on CI seem to be giving unhelpful messages inspite of prior updates as part of #3870

Improve message logging

---

sdk/core/core-auth/README.md

@daviwil feel free to close this PR by updating it in any other PRs if you have for core-auth.

[Core Auth] (minor) typo

---

sdk/eventhub/event-hubs/rollup.base.config.js
sdk/eventhub/event-hubs/src/batchingReceiver.ts
sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventPosition.ts
sdk/eventhub/event-hubs/src/iothub/iothubClient.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/receiver.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/src/streamingReceiver.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/eventPosition.spec.ts
sdk/eventhub/event-hubs/test/eventdata.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/iothub.spec.ts
sdk/eventhub/event-hubs/test/misc.spec.ts
sdk/eventhub/event-hubs/test/packageInfo.spec.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts
sdk/eventhub/event-hubs/test/sender.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts

This PR formats the `@azure/event-hubs` package by running the `format` NPM script found inside its package.json.

[Event Hubs] format source files with prettier

---

common/config/rush/command-line.json
common/config/rush/pnpm-lock.yaml
rush.json

Update rush and pnpm to latest

---

sdk/identity/identity/README.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

- Updated the merged readme of identity and keyvault packages for the error

remove duplicate 'the'

---

README.md

- From "azure-sdk-for-js - client" to "js - client - ci"

Update client status badge

---

.azure-pipelines/js-mgmt-ci.yml
.azure-pipelines/js-mgmt-pr.yml

- Running npm audit on management plane to check the security vulnerabilities of dependencies
- Enabling audit only on CI so that PR s are not blocked
- @Azure/azure-sdk-eng

run npm audit on management plane lib

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

rectified the correct variable to run rush, bumped the PublishPipelineArtifact task to V1

---

sdk/storage/storage-queue/test/utils/recorder.ts

There is no test-suite with "messagesurl" name in the feature branch and the record and playback works fine for that particular test in "messagesclient"

[Storage] Update skip list

---

sdk/keyvault/keyvault-keys/README.md

Sample update on keyvault-keys readme

---

sdk/eventhub/event-processor-host/changelog.md

This PR formats the changelog for 2.0.0 release.

[EPH] Format changelog for 2.0.0 release

---

sdk/core/abort-controller/package.json
sdk/core/core-arm/package.json
sdk/core/core-http/package.json
sdk/identity/identity/package.json

Added minor documentation changes to fix the broken links in the package.json. Probably could go with next release. 
@daviwil Could you please approve the PR?
@ramya-rao-a FYI......

Fix Broken Homepage links in package.json for 3 packages

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/test/sender.spec.ts

This PR adds support for cancellation token in Create Batch.
Note: This PR only adds support for cancellation, I will create a separate PR for adding support for retries

{Event Hubs] Add support for cancellation token in Create Batch

---

sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/sender.ts

In this PR, createBatch() function respects the retry options set on the EventHubProducer.

[Event Hubs] Add support for retry in Create Batch

---

rush.json

Verified all published packages are identical

Update rush to latest

---

sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/keyvault/keyvault-secrets/src/index.ts
sdk/keyvault/keyvault-secrets/tests/CRUD.test.ts

[keyvault-secrets] getDeletedSecretFromDeletedSecretBundle

---

rush.json

No changes in published packages

Update pnpm to latest

---

sdk/core/core-http/ThirdPartyNotices.txt
sdk/core/core-paging/ThirdPartyNotices.txt

Found some minor typos while working.. Fixing it here. Please approve.

Fix Minor Typos

---

sdk/authorization/arm-authorization/tsconfig.json

Added dom to tsconfig in auth

---

.github/CODEOWNERS

This PR updates codeowners file for this repo

Update codeowners file for js

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-arm/package.json
sdk/core/core-http/package.json

- Remove unused dependency from core-arm

Update dev dependency ts-loader to latest

---

sdk/kusto/arm-kusto/package.json
sdk/kusto/arm-kusto/src/kustoManagementClientContext.ts

- https://github.com/Azure/ms-rest-azure-js/pull/124
- https://github.com/Azure/ms-rest-js/pull/369

update min version of runtime so that the sdk does not choke on LRO delete for data connection

---

.docsettings.yml
eng/tools/analyze-deps/deps.html.hbs
eng/tools/analyze-deps/index.js
eng/tools/analyze-deps/package-lock.json
eng/tools/analyze-deps/package.json

Resolves #2574
Example output is here: https://bl.ocks.org/bsiegel/raw/b3390e877ec666743eb9e9b8cb0ee0a4/

Add dependency analysis script

---

.github/CODEOWNERS

Looking at the other management plane entry in this file I've added @michaeljqzq to the `/**/arm-*/` expression.

add additional management plane rules

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-arm/package.json
sdk/core/core-http/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json

- Add dev dependency to abort-controller
- Script "unit-test:node" depends on ts-node

Update dev dependency ts-node to latest

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

- Prevent build breaks caused by resolve@1.12.0
Verified no changes to shipping packages

Pin resolve to 1.11.1

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

I don't see any breaking changes in either the release notes or source diff:
https://github.com/karma-runner/karma-chrome-launcher/blob/master/CHANGELOG.md
https://github.com/karma-runner/karma-chrome-launcher/compare/v2.2.0...v3.0.0

Update dev dependency karma-chrome-launcher to latest

---

sdk/identity/identity/package.json
sdk/identity/identity/src/client/errors.ts
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.browser.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/clientSecretCredential.spec.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/usernamePasswordCredential.spec.ts

This change adds device code authentication as described in the AAD OAuth documentation:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code
Resolves #4311.

[Identity] Add DeviceCodeCredential implementation

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

- added a default value for packageGlobFilter 

default value for packageGlobFilter

---

sdk/core/core-amqp/test/retry.spec.ts

For more context refer to https://github.com/Azure/azure-sdk-for-js/issues/4369#issuecomment-517517477
*It seems like retry tests were not even running. Needed to update the for each check and structure a bit.

[core-amqp] Add test for abort on retry

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md

This PR updates the api markdown file for keyvault

Update keyvault api report

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/README.md
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts

Updating documentation and release notes for `1.0.0-preview.2` of `@azure/identity`.

[Identity] Update README.md and add CHANGELOG.md

---

sdk/core/core-amqp/changelog.md

Updated changelog for version 1.0.0-preview.2.0

[core-amqp] Update changelog

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/samples/sendEvents.ts
sdk/eventhub/event-hubs/src/checkpointManager.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts

This PR updates Event Hubs samples, README, changelog and JSDocs

 [Event Hubs] Update samples, README, changelog and JSDocs

---

sdk/storage/README.md
sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/samples/javascript/withConnString.js
sdk/storage/storage-blob/samples/typescript/withConnString.ts
sdk/storage/storage-file/BreakingChanges.md
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/README.md
sdk/storage/storage-file/samples/javascript/withConnString.js
sdk/storage/storage-file/samples/typescript/withConnString.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/samples/javascript/withConnString.js
sdk/storage/storage-queue/samples/typescript/withConnString.ts

Changes in the PR
- Updated changelog with the recent PRs in feature/storage branch 
- Updated NPM install references in the readmes - preview 1 to preview 2
- Coming soon in changelog with proper date
- Updated samples - mainly conn. string
- Removed aka.ms link since it points to V10

[Storage] Update Changelog, Readme, samples

---

README.md

New releases in the root Readme points to the master branch, this PR updates that to feature branch.

[Storage] update new releases in root readme to point to feature/storage branch

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

Changes for both keyvault-keys and secrets

[KeyVault] 4.0.0-preview.3 CHANGELOG.md update

---

sdk/eventhub/event-processor-host/changelog.md

This PR updates the release date in changelog for EPH

[Event Processor Host] Update release date in changelog

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/servicebus/service-bus/review/service-bus.api.md

Updates the API extractor reports to latest

Update API reports

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/eventhub/event-hubs/package.json

Update version now that we have released preview 2

[core-amqp] Update version now that we have released preview 2

---

sdk/eventhub/event-hubs/src/util/constants.ts

Needed to be updated when we changed the version in package.json.

[Event Hubs] updates version constant

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-arm/package.json
sdk/core/core-http/package.json
sdk/core/core-tracing/package.json

These packages were released earlier this week, bumping the version number for development.

[core] updates core-arm/http/tracing version numbers

---

sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

[KeyVault-Secrets] Added missing types to the current release

---

sdk/keyvault/keyvault-secrets/CHANGELOG.md

4.0.0-preview.4's CHANGELOG.
Feedback appreciated! 🌞

[KeyVault-Secrets] 4.0.0-preview.4's CHANGELOG

---

sdk/keyvault/keyvault-keys/package.json

[KeyVault-Keys] Cleaned up published types

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/package.json

Fixes #4746 
Fixes #4745 
Fixes #4744

[KeyVault-Keys] Fixes to recent feedback

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/src/eventPosition.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/receiver.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts

This PR has the below improvements
- Update docs to include details on individual options where ever options are used
- eventHubPath -> eventHubName
- Update docs on constructors when we dont want them to be used.

[Event Hubs] Doc updates based on ux study

---

sdk/keyvault/keyvault-certificates/README.md

Simple README update.
Fixes #4658

[KeyVault-Certificates] README update

---

sdk/servicebus/service-bus/review/service-bus.api.md

[Service Bus] Fix build warning

---

sdk/cognitiveservices/cognitiveservices-formrecognizer/README.md
sdk/cognitiveservices/cognitiveservices-formrecognizer/package.json
sdk/cognitiveservices/cognitiveservices-formrecognizer/rollup.config.js
sdk/cognitiveservices/cognitiveservices-formrecognizer/src/formRecognizerClient.ts
sdk/cognitiveservices/cognitiveservices-formrecognizer/src/formRecognizerClientContext.ts
sdk/cognitiveservices/cognitiveservices-formrecognizer/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-formrecognizer/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-formrecognizer/src/models/parameters.ts
sdk/cognitiveservices/cognitiveservices-formrecognizer/tsconfig.json

**Changes included in the PR**
1. Regenerated the Form Recognizer SDK with Latest OpenAPI Swagger Files in the specs repository. 
```
autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/saranganrajamanickam/Projects/azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.2 --package-version=2.0.0 https://github.com/Azure/azure-rest-api-specs/blob/80999f09c12d49c5920edc9ec3afc4a8e803335a/specification/cognitiveservices/data-plane/FormRecognizer/readme.md
AutoRest code generation utility [version: 2.0.4283; node: v10.15.1]
Loading AutoRest core      '/Users/saranganrajamanickam/.autorest/@microsoft.azure_autorest-core@2.0.4387/node_modules/@microsoft.azure/autorest-core/dist' …
```

Release Form Recognizer SDK

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file/README.md
sdk/storage/storage-queue/README.md

https://github.com/Azure/azure-sdk-for-js/issues/4758

[Storage] Typo - `compete` -> `complete`

---

sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

[KeyVault] Added the browser folder to the package files

---

sdk/servicebus/service-bus/changelog.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/constants.ts

This PR is to prep the release 1.0.4 for Service Bus for the customer issues we have

[Service Bus] Changelog for release 1.0.4

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/azure-pipelines.yml
sdk/cosmosdb/cosmos/changelog.md
sdk/cosmosdb/cosmos/consumer-test.js
sdk/cosmosdb/cosmos/dev.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/samples/BulkUpdateWithSproc.ts
sdk/cosmosdb/cosmos/samples/QueryThroughput/queryThroughput.js
sdk/cosmosdb/cosmos/samples/package.json
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/common/logger.ts
sdk/cosmosdb/cosmos/src/globalEndpointManager.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/Aggregators/MinAggregator.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/defaultQueryExecutionContext.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/documentProducer.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/orderByDocumentProducerComparator.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContext.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContextBase.ts
sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/src/request/SharedOptions.ts
sdk/cosmosdb/cosmos/test/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/functional/client.spec.ts
sdk/cosmosdb/cosmos/test/functional/databaseaccount.spec.ts
sdk/cosmosdb/cosmos/test/functional/globalEndpointManager.spec.ts
sdk/cosmosdb/cosmos/test/integration/crossPartition.spec.ts
sdk/cosmosdb/cosmos/test/unit/defaultQueryExecutionContext.spec.ts
sdk/cosmosdb/cosmos/test/unit/helper.spec.ts

This PR migrates the latest commits in azure-cosmos-js repo after the repo move - https://github.com/Azure/azure-sdk-for-js/pull/4759.

[Cosmos] Migrate latest commits from azure-cosmos-js repo

---

sdk/kusto/arm-kusto/package.json
sdk/kusto/arm-kusto/src/kustoManagementClientContext.ts
sdk/kusto/arm-kusto/src/models/index.ts
sdk/kusto/arm-kusto/src/operations/clusters.ts

fix createOrUpdate in clusters missing in 3.0.0

generate mgmt package: kusto

---

sdk/servicebus/service-bus/changelog.md

Update changelog for 1.0.4 release of Service Bus

[Service Bus] Update changelog for 1.0.4

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

- karma-cli updated from 1.0.1 to 2.0.0

update karma-cli 1.0.1 to 2.0.0

---

sdk/appconfiguration/app-configuration/package.json

- We'll monitor if this PR fixes the weirdness we see in diff report for app-config

update sdk-type for app-configuration

---

sdk/storage/storage-queue/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.json
sdk/storage/storage-queue/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.json
sdk/storage/storage-queue/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.js
sdk/storage/storage-queue/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.js
sdk/storage/storage-queue/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_endpoint_suffix.js
sdk/storage/storage-queue/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_explicit_endpoint.js
sdk/storage/storage-queue/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_complete_service_endpoint_for_each_service.js
sdk/storage/storage-queue/src/utils/utils.common.ts
sdk/storage/storage-queue/test/node/utils.spec.ts
sdk/storage/storage-queue/test/utils.spec.ts

Adding support for the custom connection strings in the following link.
https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-for-an-explicit-storage-endpoint
_TO DO - More tests to be added._

[Storage] Support for Custom connection strings 

---

sdk/storage/storage-file/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.json
sdk/storage/storage-file/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.json
sdk/storage/storage-file/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.js
sdk/storage/storage-file/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.js
sdk/storage/storage-file/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_endpoint_suffix.js
sdk/storage/storage-file/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_explicit_endpoint.js
sdk/storage/storage-file/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_complete_service_endpoint_for_each_service.js
sdk/storage/storage-file/src/utils/utils.common.ts
sdk/storage/storage-file/test/node/utils.spec.ts
sdk/storage/storage-file/test/utils.spec.ts

Custom connection strings for storage-queue - https://github.com/Azure/azure-sdk-for-js/pull/4789.
This PR adds similar support for storage-file.

[Storage] Support for Custom connection strings - storage-file

---

sdk/appconfiguration/ci.yml

This PR sets up the app-configuration package for unified pipelines.

Setup app-configuration for unified pipelines.

---

sdk/storage/storage-blob/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.json
sdk/storage/storage-blob/recordings/browsers/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.json
sdk/storage/storage-blob/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.js
sdk/storage/storage-blob/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_endpoint_suffix.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_explicit_endpoint.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_complete_service_endpoint_for_each_service.js
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/node/utils.spec.ts
sdk/storage/storage-blob/test/utils.spec.ts

Custom connection strings for storage-queue - #4789.
This PR adds similar support for storage-blob.

[Storage] Support for Custom connection strings - storage-blob

---

sdk/core/core-http/lib/coreHttp.ts

Reference - https://github.com/Azure/azure-sdk-for-js/pull/5009

[core-http] export ProxySettings from core-http

---

sdk/eventhub/event-hubs/samples/eventProcessor.ts
sdk/eventhub/event-hubs/samples/receiveEventsLoop.ts
sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
sdk/eventhub/event-hubs/samples/sendEvents.ts

This PR tweaks the samples for Event Hubs in preparation for the upcoming preview update

[Event Hubs] Samples improvements

---

sdk/core/core-auth/Changelog.md
sdk/identity/identity/CHANGELOG.md

Adds changelog updates for preview 3 for identity and core-auth

Add changelog to identity and core-auth for preview 3

---

sdk/core/core-paging/changelog.md

Adds changelog and entry for upcoming release.

[core-paging] adds changelog

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/tests-resources.json

[KeyVault-Certificates] Public API documentation

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/CosmosClient.ts
sdk/cosmosdb/cosmos/src/CosmosClientOptions.ts
sdk/cosmosdb/cosmos/src/common/platform.ts
sdk/cosmosdb/cosmos/test/unit/platform.spec.ts

Add userAgentSuffix to CosmosClient constructor options

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/README.md

[KeyVault] README updates for 5.0.0-preview.5

---

sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/tests.yml

For more context refer to #5099

[Service Bus] Fix time unit

---

sdk/eventhub/event-hubs/tests.yml
sdk/eventhub/event-processor-host/tests.yml
sdk/keyvault/keyvault-certificates/tests.yml
sdk/keyvault/keyvault-keys/tests.yml
sdk/keyvault/keyvault-secrets/tests.yml
sdk/servicebus/service-bus/tests.yml
sdk/storage/storage-blob/tests.yml
sdk/storage/storage-file/tests.yml
sdk/storage/storage-queue/tests.yml

adding back service connections to fix broken live tests

---

sdk/storage/storage-blob/samples/README.md
sdk/storage/storage-file/samples/README.md
sdk/storage/storage-queue/samples/README.md

Issue - https://github.com/Azure/azure-sdk-for-js/issues/5080

[Storage] Update samples readme with `npm init -y`

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/typedoc.json

[KeyVault-Certificates] Fixed the types path

---

sdk/storage/storage-blob/README.md

based on the feedback from the UX study
- add version
- use bullet point for links at the top and move Samples to the second one
- consistent `let i = 1;`
- Minor word tweaks

[Storage][Blob] More improvements to README.md

---

sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-file/recordings/browsers/directoryclient/recording_listhandles_should_work.json
sdk/storage/storage-file/recordings/node/directoryclient/recording_listhandles_should_work.js
sdk/storage/storage-file/rollup.base.config.js
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/utils/utils.common.ts
sdk/storage/storage-file/src/utils/utils.node.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/node/highlevel.node.spec.ts

instead of fs.stateSync() to improve performance
Resolves #5056

[Storage] use async version fs.stat()

---

CONTRIBUTING.md

Document use of wrapper script in place of global Rush install

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json

[app-configuration] Updating package.json to point to the right typings file

---

sdk/cosmosdb/ci.yml

This PR allows the ```js - cosmos``` pipeline to deploy ```@azure/cosmos``` package.

Add @azure/cosmos package to the set of artifacts we can ship.

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json

Fixing issue #5217 and also prepping branch for release for preview.3

[app-configuration] Reference the correct .d.ts file in package.json

---

eng/pipelines/templates/steps/cosmos-integration-public.yml
sdk/cosmosdb/cosmos/azure-pipelines.yml
sdk/eventhub/.openpublishing.build.ps1

Addresses [azure-sdk/issues/529](https://github.com/Azure/azure-sdk/issues/529)

Update to Powershell 6, and Add retries to Invoke-WebRequest

---

sdk/template/template/package.json

- testing latest scripts and release process and unified pipelines

releasing preview 2 template

---

sdk/cosmosdb/cosmos/rollup.config.js
sdk/cosmosdb/cosmos/src/client/Script/Scripts.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/headerUtils.ts
sdk/cosmosdb/cosmos/src/queryMetrics/clientSideMetrics.ts

This PR attempts to fix the rollup warnings of cosmos during the build step.

[Cosmos] Fix rollup warnings

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

[KeyVault] Deploy to azure button

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

Fixes #5193
Fixes #5194 
Fixes #5195
Fixes #5196
TODO: Make sure to confirm that the changes proposed [here by @tzhanl](https://github.com/Azure/azure-sdk-for-js/pull/5248) are included as part of this PR.

[KeyVault] README fixes

---

sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/storage/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/samples/README.md
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file/README.md
sdk/storage/storage-file/package.json
sdk/storage/storage-file/samples/README.md
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/samples/README.md
sdk/storage/storage-queue/src/utils/constants.ts

[Storage] Update version to preview.4

---

sdk/test-utils/recorder/src/index.ts
sdk/test-utils/recorder/src/recorder.ts

We don't have CI properly set for this repo. Once merged to master, the issue became clear.

[recorder] Fixed a bad reference

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file/README.md
sdk/storage/storage-queue/README.md

- Ensure each code snippet declares variables.
- Mention the selective imports as it works with the snippets followed.
- Other minor tweaks

[Storage] Improve README files

---

.vscode/extensions.json

Remove unnecessary recommendations that are more personal preference.
This addresses some feedback from @ramya-rao-a on #5284 after being merged.

Address feedback on VS Code recommended extensions

---

sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_rethrows_error_from_getproperties.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_returns_false_on_nonexisting_blob.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_returns_true_on_an_existing_blob.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_works_with_customer_provided_key.json
sdk/storage/storage-blob/recordings/browsers/containerclient/recording_exists_returns_false_on_nonexisting_container.json
sdk/storage/storage-blob/recordings/browsers/containerclient/recording_exists_returns_true_on_an_existing_container.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_exists_rethrows_error_from_getproperties.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_exists_returns_false_on_nonexisting_blob.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_exists_returns_true_on_an_existing_blob.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_exists_works_with_customer_provided_key.js
sdk/storage/storage-blob/recordings/node/containerclient/recording_exists_returns_false_on_nonexisting_container.js
sdk/storage/storage-blob/recordings/node/containerclient/recording_exists_returns_true_on_an_existing_container.js
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/containerclient.spec.ts

 [Storage-blob] Add exists() functions to blob and container clients 

---

sdk/storage/storage-file/recordings/browsers/directoryclient/recording_verify_sharename_and_dirpath_passed_to_the_client.json
sdk/storage/storage-file/recordings/browsers/fileclient/recording_verify_sharename_and_filepath_passed_to_the_client.json
sdk/storage/storage-file/recordings/browsers/shareclient/recording_verify_accountname_and_sharename_passed_to_the_client.json
sdk/storage/storage-file/recordings/node/directoryclient/recording_verify_sharename_and_dirpath_passed_to_the_client.js
sdk/storage/storage-file/recordings/node/fileclient/recording_verify_sharename_and_filepath_passed_to_the_client.js
sdk/storage/storage-file/recordings/node/shareclient/recording_verify_accountname_and_sharename_passed_to_the_client.js
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/ShareClient.ts
sdk/storage/storage-file/src/StorageClient.ts
sdk/storage/storage-file/src/utils/utils.common.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-file/test/node/sas.spec.ts
sdk/storage/storage-file/test/shareclient.spec.ts

Adds 
- filePath, shareName on FileClient 
- dirPath, shareName on DirectoryClient 
- shareName on ShareClient
- accountName on StorageClient
- and the code to parse them from the URL
- and some tests

[Storage] Name properties on clients - storage-file

---

sdk/core/core-amqp/changelog.md
sdk/core/core-arm/Changelog.md
sdk/core/core-http/Changelog.md
sdk/core/core-tracing/Changelog.md

This PR adds changelog entries for the below packages
- core-amqp
- core-http
- core-tracing
- core-arm

changelogs for core packages

---

sdk/core/core-tracing/lib/tracers/opencensus/openCensusSpanWrapper.ts
sdk/core/core-tracing/lib/tracers/opencensus/openCensusTracerWrapper.ts
sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/rollup.base.config.js

Small bugfix to make our wrapper compatible with the @opencensus/nodejs

Update open census wrapper

---

sdk/eventhub/event-hubs/changelog.md

[Event Hubs] update changelog for preview 4

---

sdk/core/ci.yml

/cc @mitchdenny 
It looks like it already has `sdk-type: client` :)

[logger] adds logger to ci

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/README.md
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/helloworld.ts
sdk/appconfiguration/app-configuration/samples/helloworldWithLabels.ts
sdk/appconfiguration/app-configuration/samples/index.ts
sdk/appconfiguration/app-configuration/samples/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/samples/setReadOnlySample.ts

* Fixing samples to add in more of the advanced scenarios that have some up in preview.4
* Trimming readme so the sample code is "above the fold" and not hidden behind several paragraphs of text
* Made the sample in the readme include the two common calls (get/set) and be immediately Javascript compatible.

[app-configuration] Document and samples update for preview.4

---

sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-queue/ChangeLog.md

[Storage] Changelog for name properties on clients

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/src/index.ts

This fixes a few of the issues noted in #5419 and #5420 for readability, consistency, and flow.  This cleans up a few of the issues in the typedoc output as well, namely extraneous text in the documentation.

Fixes some README and API docs issues

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/src/index.ts

keyvault-certficates documentation fixes

---

sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/eventhub/eventhubs-checkpointstore-blob/samples/eventProcessor.ts

[Event Hubs] prepare eventhubs-checkpointstore-blob release

---

sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/models/serviceMappers.ts
sdk/storage/storage-blob/src/generated/src/operations/service.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file/BreakingChanges.md
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-file/src/generated/src/models/index.ts
sdk/storage/storage-file/src/generated/src/models/mappers.ts
sdk/storage/storage-file/src/generated/src/models/serviceMappers.ts
sdk/storage/storage-file/src/generated/src/operations/service.ts
sdk/storage/storage-file/swagger/README.md
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/generated/src/models/index.ts
sdk/storage/storage-queue/src/generated/src/models/mappers.ts
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/models/serviceMappers.ts
sdk/storage/storage-queue/src/generated/src/operations/service.ts
sdk/storage/storage-queue/swagger/README.md

- Renaming StorageServiceProperties to {Blob|File|Queue}ServiceProperties
- Renaming StorageServiceStats to {Blob|Queue}ServiceStatistics

[Storage] add autorest transformations

---

sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-file/src/utils/utils.common.ts

This is done for blob in https://github.com/Azure/azure-sdk-for-js/pull/5405#discussion_r332277145.
Doing it for the rest in this PR.

[Storage] decodeURIComponent to get the decoded version of the contents like container name/ directory name

---

sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-file/BreakingChanges.md
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-file/test/fileserviceclient.spec.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/test/queueserviceclient.spec.ts

[Storage] Change include type array to boolean flags

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

Update changelog for packages that need re-release
- app config
- 3 keyvault packages

Update changelog for packages that need re-release

---

sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md

UserDelegationKey changes are for blob, not queue.

[Storage] Fix change logs

---

sdk/keyvault/keyvault-keys/src/cryptographyClient.ts

Cleans up the cryptography client by:
* Removing IV, auth data and auth flag
* Giving each action its own Options type so we can evolve them as the service grows
Fixes #5509

[KeyVault] Remove IV, auth data and auth tag

---

sdk/cosmosdb/cosmos/package.json

Move node-abort-controller to production dependencies

[Cosmos] 3.3.6

---

sdk/eventhub/event-hubs/src/eventDataBatch.ts
sdk/eventhub/event-hubs/src/eventHubClient.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/src/util/error.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobPartitionManager.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/util/error.ts

[event-hubs] Include function name in thrown error for simpler diagnostics

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/core/models/index.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/keyvault/keyvault-secrets/src/secretsModels.ts

This is a PR to cover the API changes requested as part of #5510 (though only the API changes and not the docs changes)

[KeyVault] Updates to SDK based on #5510

---

sdk/storage/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-file/README.md
sdk/storage/storage-queue/README.md

The new links should redirect to correct locales.

[Storage] Remove zh-cn from CORS links

---

sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/abort.test.ts
sdk/core/core-lro/test/testClient.test.ts
sdk/core/core-lro/test/utils/testTokenCredential.ts

[core-lro] renamed stop as stopPolling

---

.github/CODEOWNERS

Update CodeOwners file.

---

sdk/storage/storage-blob/samples/typescript/iterators-blobs.ts
sdk/storage/storage-blob/samples/typescript/iterators-containers.ts
sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/operations/container.ts
sdk/storage/storage-blob/src/generated/src/operations/service.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobserviceclient.spec.ts

[Storage][Blob] renames leftovers

---

sdk/storage/storage-queue/samples/javascript/iterators.js
sdk/storage/storage-queue/samples/typescript/iterators.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/SASQueryParameters.ts
sdk/storage/storage-queue/src/generated/src/models/index.ts
sdk/storage/storage-queue/src/generated/src/models/mappers.ts
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/operations/messageId.ts
sdk/storage/storage-queue/src/generated/src/operations/messages.ts
sdk/storage/storage-queue/src/generated/src/operations/queue.ts
sdk/storage/storage-queue/src/generated/src/operations/service.ts
sdk/storage/storage-queue/src/policies/LoggingPolicy.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md
sdk/storage/storage-queue/test/messageidclient.spec.ts
sdk/storage/storage-queue/test/messagesclient.spec.ts
sdk/storage/storage-queue/test/node/emulator-tests.spec.ts
sdk/storage/storage-queue/test/node/messageidclient.spec.ts
sdk/storage/storage-queue/test/node/messagesclient.spec.ts
sdk/storage/storage-queue/test/node/queueclient.spec.ts
sdk/storage/storage-queue/test/node/sas.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts
sdk/storage/storage-queue/test/queueserviceclient.spec.ts
sdk/storage/storage-queue/test/utils/index.ts

[Storage][Queue] renames from API review

---

sdk/core/core-lro/src/poller.ts

For clients that might not want to expose a Poller class.
Read the thread: https://github.com/Azure/azure-sdk-for-js/pull/5609#discussion_r336598384

[core-lo] Poller interface

---

sdk/core/core-lro/src/poller.ts

[core-lro] these options can be undefined

---

sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/testClient.test.ts

[core-lro] getResult should be usable before the poller finishes

---

sdk/storage/storage-blob/src/PageBlobClient.ts
sdk/storage/storage-blob/src/PageBlobRangeResponse.ts
sdk/storage/storage-blob/src/index.browser.ts
sdk/storage/storage-blob/src/index.ts
sdk/storage/storage-blob/test/pageblobclient.spec.ts

Fixes #5454 by using Range in convenience layer

[Storage][Blob] Consolidate PageRange and ClearRange using Range

---

sdk/core/logger/package.json
sdk/identity/identity/package.json
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/src/util/logging.ts
sdk/identity/identity/test/identityClient.spec.ts

[Identity] Add logging for critical points within the identity package

---

sdk/storage/storage-blob/samples/typescript/advanced.ts
sdk/storage/storage-blob/src/AppendBlobClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-blob/src/PageBlobClient.ts
sdk/storage/storage-blob/src/utils/RetriableReadableStream.ts
sdk/storage/storage-blob/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-file/samples/javascript/advanced.js
sdk/storage/storage-file/samples/typescript/advanced.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/utils/RetriableReadableStream.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-file/test/node/highlevel.node.spec.ts

Rename progress to onProgress in Blob and File

[Storage] rename progress to onProgress

---

sdk/storage/storage-blob/package.json

[Storage][Blob]Disable extract-api

---

sdk/storage/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/samples/README.md
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file/README.md
sdk/storage/storage-file/samples/README.md
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/samples/README.md
sdk/storage/storage-queue/src/utils/constants.ts

Fixes #5511 
Can be merged just before the release.

[Storage] Update versions to 12.0.0-preview.5

---

sdk/core/core-lro/src/index.ts
sdk/core/core-lro/src/pollOperation.ts
sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/abort.test.ts
sdk/core/core-lro/test/testClient.test.ts
sdk/core/core-lro/test/utils/testClient.ts
sdk/core/core-lro/test/utils/testNonCancellablePoller.ts
sdk/core/core-lro/test/utils/testOperation.ts
sdk/core/core-lro/test/utils/testPoller.ts
sdk/core/core-lro/test/utils/testServiceClient.ts
sdk/core/core-lro/test/utils/testTokenCredential.ts
sdk/core/core-lro/test/utils/testWebResource.ts

Corrected copyright headers in core-lro

---

sdk/storage/storage-file/review/storage-file.api.md
sdk/storage/storage-queue/review/storage-queue.api.md

Updating API surface files to reflect changes from #5613

[Storage] Update API surface with latest changes

---

sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/generated/src/models/index.ts
sdk/storage/storage-file/src/generated/src/models/mappers.ts
sdk/storage/storage-file/src/generated/src/models/parameters.ts
sdk/storage/storage-file/swagger/README.md

This PR adds transforms as per https://github.com/Azure/azure-sdk-for-js/pull/5677#issuecomment-544339939

Rename model fileHTTPHeaders to fileHttpHeaders

---

sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobLeaseClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/index.browser.ts
sdk/storage/storage-blob/src/index.ts
sdk/storage/storage-blob/test/blobbatch.spec.ts
sdk/storage/storage-blob/test/leaseclient.spec.ts

[Storage][Blob] Rename LeaseClient -> BlobLeaseClient

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json
sdk/core/core-lro/review/core-lro.api.md
sdk/core/core-lro/src/pollOperation.ts
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-secrets/package.json

Everything seems to build and work fine.
Fixes #5754

[core-lro] Less permissive PollOperation

---

sdk/storage/storage-queue/README.md

listContainers was wrongly referenced.

[storage-queue] listContainers to listQueues

---

sdk/identity/identity/test/node/environmentCredential.spec.ts

Here's a fix :) It's hard being green! 😓 ❌➡💚

[identity] build fix

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/core/ci.yml

adding doc directory variable

---

sdk/core/core-auth/src/tokenCredential.ts

[core-auth] Improve documentation strings in core-auth

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/storage/storage-blob/review/storage-blob.api.md

This PR updates the output of the api extractor tool for Keyvault & Storage

Updated api extractor output in Keyvault & Storage

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/rollup.config.js
sdk/cosmosdb/cosmos/src/common/platform.ts
sdk/cosmosdb/cosmos/src/utils/user-agent.browser.ts
sdk/cosmosdb/cosmos/src/utils/user-agent.ts

[Cosmos] Remove universal-user-agent

---

.github/CODEOWNERS

Since I think I have the most context on these packages now, I would like to be included on reviews to them. 
Apologies if this isn't the right way to accomplish this. 😅

CODEOWNERS: Add `xirzec` to tracing and logger

---

eng/tools/generate-doc/index.js

temporary point to lib folder for two packages

---

sdk/storage/storage-file-share/package.json

https://github.com/Azure/azure-sdk-for-js/pull/5866#issuecomment-546829104

[Storage] Add `fs` : false to storage-file-share package.json browser mapping

---

sdk/core/abort-controller/changelog.md
sdk/core/core-amqp/changelog.md
sdk/core/core-arm/Changelog.md
sdk/core/core-asynciterator-polyfill/changelog.md
sdk/core/core-auth/Changelog.md
sdk/core/core-http/Changelog.md
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-paging/changelog.md
sdk/core/logger/Changelog.md

[core] update changelogs for GA

---

sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

Just some things that were pointed out to me as part of our dogfooding
exercise, as well as a few small things I noticed myself.

storage: Small copy editing to README.md's

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/README.md

[Identity] Update README.md and CHANGELOG.md for 1.0!

---

sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/queueClient.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/src/subscriptionClient.ts
sdk/servicebus/service-bus/src/util/utils.ts

For more context refer to #2896

[Service Bus] Refactor associatedLinkName handling

---

sdk/identity/identity/README.md

update the github.io links in the README to point to where they should after docs releases

update the github.io links in the README to point to correct doc links

---

samples/SmokeTest/KeyVault.ts
sdk/keyvault/keyvault-keys/samples/javascript/cryptography.js
sdk/keyvault/keyvault-keys/samples/javascript/helloWorld.js
sdk/keyvault/keyvault-secrets/samples/javascript/backupAndRestore.js
sdk/keyvault/keyvault-secrets/samples/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-secrets/samples/javascript/helloWorld.js
sdk/keyvault/keyvault-secrets/samples/javascript/listOperations.js

[KeyVault] Fixed JavaScript and Smoke samples

---

sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobPartitionManager.ts

Updates the package to use the latest version of storage-blob.

[eventhubs-checkpointstore-blob] update storage-blob dependency

---

sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

This PR doesn't add any new code snippet, I just validated all the existing snippets and made sure that they are aligned with the new API for storage packages.

[Storage] Improve code snippets in JS Docs

---

sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/StorageBrowserPolicyFactory.ts
sdk/storage/storage-queue/src/StorageClient.ts
sdk/storage/storage-queue/src/StorageRetryPolicyFactory.ts
sdk/storage/storage-queue/src/TelemetryPolicyFactory.ts
sdk/storage/storage-queue/src/credentials/AnonymousCredential.ts
sdk/storage/storage-queue/src/credentials/StorageSharedKeyCredential.ts
sdk/storage/storage-queue/src/policies/CredentialPolicy.ts
sdk/storage/storage-queue/src/policies/StorageSharedKeyCredentialPolicy.ts

Changes:
- Added links to types in the storage-queue package where I could find them
- Added samples from README to corresponding related doc comments
- fixed occasional typos as I noticed them

[storage-queue] Links, examples, and some doc fixes

---

sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/src/index.ts

[KeyVault] TokenCredential parameter documentation fixed

---

common/config/rush/pnpm-lock.yaml
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts
sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts

Packages 
- keyvault-secrets
- keyvault-keys
- storage-blob
- storae-queue

Update versions for GA packages 

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

[KeyVault] Keys and Secrets changelogs fixed

---

sdk/core/core-tracing/README.md
sdk/core/logger/README.md

Updating the README.md for tracing to include install instructions and a few light examples.

[core-tracing] Update README to have some basic examples

---

sdk/storage/storage-blob/src/BlobBatch.ts
sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/StorageClient.ts
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

[Storage] Fix token credential docs related to @azure/identity in storage packages

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

Removes the README warnings about the modules being preview

[KeyVault] Remove the preview warnings

---

sdk/storage/storage-blob/README.md

- Added Key Concepts
- Made it match the formatting given by #5936 (storage-queue) and its
reviews
- Removed locales from URLs
- Remove package version strings and changelog info
- Made samples runnable
- reordered some sections

[storage-blob] README style check

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts

For more context refer to #4748

[Service Bus] Update documentation for batching receiver

---

sdk/cognitiveservices/cognitiveservices-luis-runtime/package.json

fix build CI failure due to 'cognitiveservices-luis-runtime' test

---

sdk/keyvault/keyvault-secrets/README.md

[KeyVault-Secrets] Bad certificate reference in the README

---

sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/core/keyVaultBase.ts

[Keyvault] Remove member tag as it messes up doc rendering

---

sdk/keyvault/keyvault-certificates/package.json

Now that keys and secrets are released, update their dependencies in certificates to point to the correct new versions.

[KeyVault-Certificates] Update certificate's dependencies on other KV packages

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/index.ts

[KeyVault-Certificates] Removed pipeline and credentials from the class properties

---

sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-keys/karma.conf.js
sdk/keyvault/keyvault-secrets/karma.conf.js
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-queue/karma.conf.js
sdk/test-utils/recorder/GUIDELINES.md

[Common Recorder] Import recordings only in playback mode

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/samples/javascript/backupAndRestore.js
sdk/keyvault/keyvault-certificates/samples/javascript/contacts.js
sdk/keyvault/keyvault-certificates/samples/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-certificates/samples/javascript/helloWorld.js
sdk/keyvault/keyvault-certificates/samples/javascript/issuers.js
sdk/keyvault/keyvault-certificates/samples/javascript/listCertificates.js
sdk/keyvault/keyvault-certificates/samples/javascript/mergeCertificate.js
sdk/keyvault/keyvault-certificates/samples/javascript/operations.js

[KeyVault-Certificates] Fixed all the samples

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md

[KeyVault-Certificates] CHANGELOG update

---

sdk/cosmosdb/cosmos/changelog.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/common/statusCodes.ts
sdk/cosmosdb/cosmos/src/retry/retryUtility.ts
sdk/cosmosdb/cosmos/test/integration/failover.spec.ts

[Cosmos] Regional failover fixes

---

.github/CODEOWNERS

I want to get pings when this file updates so I can keep on top of dependency changes.

CODEOWNERS: Add bterlson to pnpm-lock.yaml

---

sdk/servicebus/service-bus/rollup.base.config.js

For more context to issues leading to these changes refer to #5983

[ServiceBus] Remove dedupe of buffer in rollup script

---

eng/tools/generate-static-index/index.js
eng/tools/generate-static-index/service-mapper.json

- added a check if the service name mapping doesn't exist
- update service names as discussed @scbedd

[EngSys] check for existing service name

---

sdk/servicebus/service-bus/src/log.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
sdk/servicebus/service-bus/src/util/sasServiceClientCredentials.ts
sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/atomXml.spec.ts

For more context refer to #5926

[Service Bus] Update error messages

---

sdk/storage/storage-queue/src/QueueServiceClient.ts

[Storage Queue] Update new helper methods with tracing

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/samples/javascript/issuers.js
sdk/keyvault/keyvault-certificates/samples/typescript/issuers.ts
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/test/CRUD.test.ts

Part of #5972, this renames setIssuer to createIssuer.

Rename setIssuer to createIssuer

---

common/config/rush/pnpm-lock.yaml
common/scripts/install-run.js
rush.json

Update rush and pnpm

---

sdk/keyvault/keyvault-certificates/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-keys/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-secrets/test/utils/recorderUtils.ts

[KeyVault-Certificates] dotenv fix

---

sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/lro/create/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/delete/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/operation/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/src/secretsModels.ts

[KeyVault] Removed all the @interface instances

---

eng/tools/generate-doc/index.js
eng/tools/generate-static-index/index.js
eng/tools/generate-static-index/service-mapper.json

- refactored file traversal code
- updated service name for storage sync

refactored file traversal code

---

sdk/keyvault/keyvault-certificates/test/CRUD.test.ts
sdk/keyvault/keyvault-certificates/test/list.test.ts
sdk/keyvault/keyvault-certificates/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-certificates/test/utils/utils.common.ts

[KeyVault-Certificates] Added timeout tests

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts

Fix made originally by @xirzec here: https://gist.github.com/sadasant/338cf54b2db2493775da5aeb0a4413be
Related to #5972

[KeyVault-Certificates] Contact and Contacts type fixed thanks to Jeff

---

sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-secrets/src/secretsModels.ts

[KeyVault] Simplified the documentation of optional properties

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

[KeyVault] Have separate examples with poll and pollUntil done

---

sdk/appconfiguration/app-configuration/package.json

- Missing dependencies were masked by Rush configuration which merges dependencies across packages

[app-configuration] Add missing dev dependencies

---

sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/src/index.ts

Some doc updates to address https://github.com/azure/azure-sdk-for-js/issues/5420
Fixes https://github.com/azure/azure-sdk-for-js/issues/5420

[KeyVault] API doc updates

---

sdk/cosmosdb/cosmos/test/integration/crossPartition.spec.ts

[Cosmos] Fix broken test on master

---

sdk/storage/storage-file-share/test/fileclient.spec.ts

[Storage File Share] Update the error check of a (previously) flaky error

---

common/config/rush/pnpm-lock.yaml
rush.json
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/streamingReceiver.ts

[Event Hubs][hotfix] Adds try/catch statements around user callback to receive

---

.docsettings.yml
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/test/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/test/README.md
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/test/README.md

[KeyVault] READMEs for the tests

---

sdk/core/core-tracing/package.json

[core-tracing] Add sources to package

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/samples/javascript/contacts.js
sdk/keyvault/keyvault-certificates/samples/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-certificates/samples/javascript/listCertificates.js
sdk/keyvault/keyvault-certificates/samples/typescript/deleteAndRecover.ts
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts

Related to https://github.com/Azure/azure-sdk-for-js/issues/5489

[KeyVault-Certificates] Fixed the samples

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts

Fixes for subject and subject alternative names.
Fixes #6205 
Related to: #6198

[KeyVault-Certificates] Subject and subject alternative names

---

sdk/eventhub/event-hubs/changelog.md

Updates changelog date.
/cc @ramya-rao-a

[event hubs] update changelog (2.x)

---

sdk/cosmosdb/cosmos/review/cosmos.api.md

Merging from master didn't catch this.

[cosmos] Update typings file that was missed in #6110

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml
sdk/keyvault/keyvault-certificates/tests-resources.json
sdk/keyvault/keyvault-keys/tests-resources.json
sdk/keyvault/keyvault-secrets/tests-resources.json

[KeyVault] Small cleanup on the tests-resources

---

sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
sdk/servicebus/service-bus/src/util/constants.ts

For more context refer to #5858

[Service Bus] Add docs for time duration related properties

---

sdk/cosmosdb/cosmos/changelog.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/GroupByEndpointComponent.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/GroupByValueEndpointComponent.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/emptyGroup.ts
sdk/cosmosdb/cosmos/test/functional/globalEndpointManager.spec.ts
sdk/cosmosdb/cosmos/test/integration/aggregates/groupBy.spec.ts

[Cosmos] Wait for all results to start returning aggregates in query pipeline

---

sdk/servicebus/service-bus/test/atomManagement.spec.ts

For more contect refer to #6325

[Service Bus] Disable browser run

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/samples/receiveEvents.ts
sdk/eventhub/event-hubs/samples/receiveEventsUsingCheckpointStore.ts
sdk/eventhub/event-hubs/src/eventDataBatch.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/partitionProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/partitionPump.spec.ts
sdk/eventhub/event-hubs/test/sender.spec.ts
sdk/eventhub/event-hubs/test/utils/receivedMessagesTester.ts
sdk/eventhub/event-hubs/test/utils/subscriptionHandlerForTests.ts
sdk/eventhub/eventhubs-checkpointstore-blob/samples/receiveEventsUsingCheckpointStore.ts

* Batching is back! (processEvent => processEvents)
* Renamed 'startPosition' to 'startingPosition' (including associated methods)
* processError is now a mandatory callback
* Other minor renames/hiding of fields

[event-hubs] Changes from the feature team API review

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/sample.env
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/test/auth.spec.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/samples.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts

[app-config] Adding in TokenAuthentication support for App Configuration

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

[KeyVault] Changelogs for Keys and Secrets

---

sdk/core/core-auth/Changelog.md
sdk/core/core-http/Changelog.md
sdk/core/core-tracing/Changelog.md

This PR updates the release dates in the changelog for the core packages being released in December

[Core] Update release date in changelog

---

sdk/identity/identity/CHANGELOG.md

This PR updates the release date in the changelog for patch update 1.0.1 of the identity package

[Identity] Update release date in changelog

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/src/index.ts

Just small fixes! Please review <3

[KeyVault-Certificates] Fixes on the README code and the index.ts comments.

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md

This updates the CHANGELOG to point to the api alignment changes, poller changes, and open telemetry update.

[KeyVault-Certificates] Get CHANGELOG ready for preview 10

---

sdk/keyvault/keyvault-secrets/README.md

Some typos I found in one of readme files.

[Docs] Update README.md

---

sdk/keyvault/keyvault-certificates/samples/javascript/contacts.js

Fix some leftover code from the API change.

[KeyVault-Certificates]Fix bug in js contacts sample

---

sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-file-share/BreakingChanges.md
sdk/storage/storage-file-share/ChangeLog.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-queue/ChangeLog.md

[Storage] update file-share package version

---

sdk/storage/README.md
sdk/storage/storage-file-share/samples/README.md

and from the npm install example

[Storage] remove the preview version tag from file-share NPM link

---

sdk/servicebus/service-bus/review/service-bus.api.md

This got missed out from PR for #5757

[Service Bus] Update api.md file

---

sdk/core/abort-controller/src/aborter.ts

angular prod build is giving an issue because of /// in aborter.js

changed /// to // in aborter.ts

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/samples/typescript/gettingStarted/atomManagementApi.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts

Revert "[Service Bus] Ensure master branch is shippable (#6320)"
This reverts commit cf0c4bc079f5890d520124aad92af6630e5a1966.

[Service Bus] Prepare the feature branch for atom management API

---

sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
sdk/servicebus/service-bus/src/util/parseUrl.browser.ts
sdk/servicebus/service-bus/src/util/parseUrl.ts

For more context refer to #6141 
Manually verified the changes by installing Node 8 on local

[Service Bus] Browserify parseUrl functionality

---

sdk/eventhub/event-processor-host/tests.yml

event-processor-host: Update IoTHub connection string

---

sdk/core/amqp-common/changelog.md

[amqp-common] prepare preview 9 release

---

sdk/core/ci.yml

- Changes under folder "common/config/rush" could impact any package

Add rush config to core path triggers 

---

sdk/keyvault/keyvault-certificates/src/index.ts

This isn't intended to be a thorough review of the documentation. We'll be doing that next week. I just spotted these mistakes and I wanted to do something about it 🌞

[KeyVault Certificates] Some documentation fixes

---

.github/CODEOWNERS

I am Lin Jian. My work alias is lijian2. I need this to merge code.

[Storage]add Lin Jian as a owner of the /sdk/storage code

---

sdk/core/core-auth/rollup.base.config.js
sdk/core/core-auth/rollup.config.js
sdk/core/core-lro/rollup.base.config.js
sdk/core/core-tracing/rollup.base.config.js
sdk/core/core-tracing/rollup.config.js
sdk/identity/identity/rollup.base.config.js
sdk/identity/identity/rollup.config.js
sdk/keyvault/keyvault-certificates/rollup.base.config.js
sdk/keyvault/keyvault-keys/rollup.base.config.js
sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/servicebus/service-bus/rollup.base.config.js
sdk/servicebus/service-bus/rollup.config.js
sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-blob/rollup.config.js
sdk/storage/storage-file-datalake/rollup.base.config.js
sdk/storage/storage-file-datalake/rollup.config.js
sdk/storage/storage-file-share/rollup.base.config.js
sdk/storage/storage-file-share/rollup.config.js
sdk/storage/storage-queue/rollup.base.config.js
sdk/storage/storage-queue/rollup.config.js
sdk/template/template/rollup.base.config.js
sdk/template/template/rollup.config.js
sdk/test-utils/recorder/rollup.base.config.js
sdk/test-utils/recorder/rollup.config.js

As we no longer ship browser bundle of our libraries.

Remove rollup of browser minification

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/src/lro/operation/operation.ts

Part of https://github.com/Azure/azure-sdk-for-js/issues/6567 - this PR aligns a few of our APIs to better match what other languages are doing for this service.

More alignment with API changes

---

sdk/storage/storage-blob/samples/javascript/iterators-without-await.js
sdk/storage/storage-blob/samples/typescript/iterators-without-await.ts

[Storage] Add samples of listing blobs without using await

---

sdk/eventhub/event-hubs/samples/sample.env
sdk/eventhub/event-hubs/samples/usingAadAuth.ts
sdk/servicebus/service-bus/samples/javascript/gettingStarted/loginWithAzureAccount.js
sdk/servicebus/service-bus/samples/javascript/gettingStarted/servicePrincipalLogin.js
sdk/servicebus/service-bus/samples/typescript/gettingStarted/loginWithAzureAccount.ts
sdk/servicebus/service-bus/samples/typescript/gettingStarted/servicePrincipalLogin.ts
sdk/servicebus/service-bus/test/README.md

For more context refer to #5239

[Service Bus] [Event Hubs] Update access control related docs

---

eng/pipelines/templates/steps/common.yml

This PR fixes (or will fix) the macOS broken test runs.

Fix macOS test runs which are failing due to NPM installation.

---

eng/New-TestResources.cmd
eng/New-TestResources.ps1
eng/Remove-TestResources.cmd
eng/Remove-TestResources.ps1

FYI @heaths -- adding in the current scripts in master for .NET so we can move the process forward with the ARM templates we have.

add test resource provisioning scripts

---

sdk/storage/storage-blob/samples/javascript/advanced.js
sdk/storage/storage-blob/samples/javascript/basic.js
sdk/storage/storage-blob/samples/javascript/iterators-blobs-hierarchy.js
sdk/storage/storage-blob/samples/javascript/iterators-blobs.js
sdk/storage/storage-blob/samples/javascript/iterators-without-await.js
sdk/storage/storage-blob/samples/javascript/readingSnapshot.js
sdk/storage/storage-blob/samples/typescript/src/advanced.ts
sdk/storage/storage-blob/samples/typescript/src/basic.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-blobs-hierarchy.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-blobs.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-without-await.ts
sdk/storage/storage-blob/samples/typescript/src/readingSnapshot.ts
sdk/storage/storage-blob/test/blobbatch.spec.ts

[Storage][Samples] create clients directly when possible

---

sdk/keyvault/keyvault-certificates/samples/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-certificates/samples/javascript/issuers.js
sdk/keyvault/keyvault-certificates/samples/javascript/listCertificates.js
sdk/keyvault/keyvault-certificates/samples/typescript/deleteAndRecover.ts
sdk/keyvault/keyvault-certificates/samples/typescript/issuers.ts

This fixes the broken issuers JS samples. I also go ahead and clean up a few other samples.

Fix issuers js and clean up a few other samples

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/samples/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-certificates/samples/javascript/issuers.js
sdk/keyvault/keyvault-certificates/samples/javascript/listCertificates.js
sdk/keyvault/keyvault-certificates/samples/typescript/deleteAndRecover.ts
sdk/keyvault/keyvault-certificates/samples/typescript/issuers.ts
sdk/keyvault/keyvault-certificates/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/core/utils/constants.ts

This bumps the version of certificates to preview12 and then adds a changelog entry for the release.

Bump version add changelog

---

sdk/servicebus/service-bus/test/utils/envVarUtils.ts

For more context refer to #6682

[Service Bus] Use a different entity name for partitioned topic-subscription

---

sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
sdk/servicebus/service-bus/src/util/constants.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/atomXml.spec.ts

For more context refer to #6055

[Service Bus] Update error handling for atom based management apis

---

sdk/storage/README.md

- trim down by removing blob-specific sample code
- remove compatibility section
- add data lake links

[Storage] update sdk/storage/README.md

---

sdk/appconfiguration/app-configuration/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-tracing/CHANGELOG.md
sdk/core/core-tracing/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/textanalytics/cognitiveservices-textanalytics/package.json

and update CHANGELOG files for core-http and core-tracing

[Core-tracing] bump version to 1.0-preview.8

---

sdk/storage/storage-blob/samples/javascript/basic.js
sdk/storage/storage-blob/samples/javascript/errorsAndResponses.js
sdk/storage/storage-blob/samples/javascript/iterators-blobs-hierarchy.js
sdk/storage/storage-blob/samples/javascript/iterators-blobs.js
sdk/storage/storage-blob/samples/javascript/iterators-without-await.js
sdk/storage/storage-blob/samples/javascript/readingSnapshot.js
sdk/storage/storage-blob/samples/typescript/src/basic.ts
sdk/storage/storage-blob/samples/typescript/src/errorsAndResponses.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-blobs-hierarchy.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-blobs.ts
sdk/storage/storage-blob/samples/typescript/src/iterators-without-await.ts
sdk/storage/storage-blob/samples/typescript/src/readingSnapshot.ts
sdk/storage/storage-file-share/samples/javascript/basic.js
sdk/storage/storage-file-share/samples/javascript/iterators-files-and-directories.js
sdk/storage/storage-file-share/samples/typescript/src/basic.ts
sdk/storage/storage-file-share/samples/typescript/src/iterators-files-and-directories.ts

[Storage][Sample]remove confusion around "string".length vs byte length: upload use byte length

---

sdk/servicebus/service-bus/tests.yml

- Created a new namespace for servicebus browser tests and added connection string as env variable

[service bus] added env variable for browser connection string

---

sdk/core/core-http/CHANGELOG.md

[core-http] Add new entry in CHANGELOG for v1.0.4

---

sdk/servicebus/service-bus/karma.conf.js
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/utils/aadUtils.ts
sdk/servicebus/service-bus/test/utils/envVarUtils.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts
sdk/servicebus/service-bus/test/utils/testUtils.ts

For more context refer to #6739

[Service Bus] Use browser specific connection string

---

sdk/core/core-http/karma.conf.ts
sdk/core/core-http/package.json

for testing Edge and Firefox browsers.

[Core-http][Test] add more karma launcher dev dependencies

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/core/utils/constants.ts

[KeyVault-Certificates] Moving certificates out of preview

---

eng/pipelines/doc-index.yml
eng/tools/generate-static-index/Generate-DocIndex.ps1

Move Doc Index into separate ps1 file

Cleanup Doc Index

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContextBase.ts

- maxDegreeOfParallelism should not default to 1
- maxItemCount should default to undefined

[Cosmos] Fix bugs in parallel query defaults

---

sdk/keyvault/keyvault-certificates/src/index.ts

The provider change is specifically because "Preview" will fail and "Test" will not fail.

[KeyVault-Certificates] Fixed inline samples

---

sdk/appconfiguration/app-configuration/samples/typescript/package.json
sdk/appconfiguration/app-configuration/samples/typescript/tsconfig.json

* Fixed issue with the tsconfig including the async iterable
which was causing compilation issues.
* For good measure added in an explicit target (ES6) as well.
* Updated @azure/app-configuration dependency to ~1.0.0 now that
it's actually being released!

[app-configuration] Update samples now that we're going GA!

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/samples/javascript/README.md
sdk/keyvault/keyvault-certificates/samples/typescript/README.md

Thanks to the recent review. Also, reviews to this PR appreciated!

[KeyVault-Certificates] Fixes to the docs

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/README.md
sdk/core/core-amqp/package.json
sdk/eventhub/event-hubs/package.json

Updates the logging section of core-amqp and updates the package/changelog versions.

[core-amqp] update readme and changelog

---

sdk/core/core-amqp/README.md
sdk/core/core-amqp/src/dataTransformer.ts
sdk/eventhub/event-hubs/README.md

[event-hubs] document logging

---

sdk/storage/storage-file-share/test/fileserviceclient.spec.ts

Fix #6740 
Somehow the first List Shares returned no share item, but just a continuation token.
Continue the List Shares with the continuation token will be able to traverse all the shares.

[storage-file-share] list shares may return empty shareItems even when there are still shares remaining to list

---

sdk/cosmosdb/cosmos/__snapshots__/groupBy.spec.js
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/test/common/MockClientContext.ts
sdk/cosmosdb/cosmos/test/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/functional/authorization.spec.ts
sdk/cosmosdb/cosmos/test/functional/container.spec.ts
sdk/cosmosdb/cosmos/test/functional/item.spec.ts
sdk/cosmosdb/cosmos/test/functional/offer.spec.ts
sdk/cosmosdb/cosmos/test/functional/permission.spec.ts
sdk/cosmosdb/cosmos/test/functional/query.spec.ts
sdk/cosmosdb/cosmos/test/functional/sproc.spec.ts
sdk/cosmosdb/cosmos/test/functional/trigger.spec.ts
sdk/cosmosdb/cosmos/test/functional/udf.spec.ts
sdk/cosmosdb/cosmos/test/functional/user.spec.ts
sdk/cosmosdb/cosmos/test/integration/aggregateQuery.spec.ts
sdk/cosmosdb/cosmos/test/integration/changeFeed.spec.ts
sdk/cosmosdb/cosmos/test/integration/crossPartition.spec.ts
sdk/cosmosdb/cosmos/test/integration/failover.spec.ts
sdk/cosmosdb/cosmos/test/integration/queryMetrics.spec.ts
sdk/cosmosdb/cosmos/test/integration/retry.spec.ts
sdk/cosmosdb/cosmos/test/integration/session.spec.ts
sdk/cosmosdb/cosmos/test/integration/sslVerification.spec.ts
sdk/cosmosdb/cosmos/test/tsconfig.json
sdk/cosmosdb/cosmos/test/unit/defaultQueryExecutionContext.spec.ts
sdk/cosmosdb/cosmos/test/unit/inMemoryCollectionRoutingMap.spec.ts
sdk/cosmosdb/cosmos/test/unit/smartRoutingMapProvider.spec.ts

- Enables noUnusedLocals in test files
- Fixes a few tests and setup a special build command for running Cosmos internal staging sign offs

[Cosmos] No unused locals in tests

---

sdk/cosmosdb/cosmos/src/client/Container/Container.ts

Resolves https://github.com/Azure/azure-sdk-for-js/issues/6850

Make partitionKey optional, clarify verbiage

---

sdk/eventhub/eventhubs-checkpointstore-blob/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/review/eventhubs-checkpointstore-blob.api.md
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/index.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/log.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/util/error.ts

Updates the `@azure/eventhubs-checkpointstore-blob` package to use `@azure/logger`.

[eventhubs-checkpointstore-blob] use core logger

---

sdk/eventhub/event-hubs/README.md

Discovered an issue in 2 of the snippets while manually testing them. I've already checked `eventhubs-checkpointstore-blob` as well.

[event-hubs] fix readme samples

---

sdk/textanalytics/ai-text-analytics/README.md
sdk/textanalytics/ai-text-analytics/package.json

Of course I found a couple more minor issues after merging the last PR. 😅

A couple more minor tweaks to the Text Analytics README

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-amqp/rollup.base.config.js
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/rollup.base.config.js
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/rollup.base.config.js
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/rollup.base.config.js

- update rollup-plugin-inject to @rollup/plugin-inject since former is deprecated

Update rollup inject

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
sdk/servicebus/service-bus/test/README.md
sdk/servicebus/service-bus/test/atomManagement.spec.ts

For more context refer to #6846 
This PR replaces PR #6847 for purposes of reviewing all changes and finalizing commits to feature branch.
Once final, the merge to master branch can be done.

[Service Bus] Preparing atom management API feature for merge to master branch

---

sdk/servicebus/service-bus/package.json

Context: https://github.com/Azure/azure-sdk-for-js/pull/6893#discussion_r365462513

[Service Bus] Fix npm script

---

sdk/servicebus/service-bus/test/utils/testUtils.ts

Update feature branch with master and apply fix from master for #6682

[Service Bus] Update with fix from master

---

common/config/rush/pnpm-lock.yaml

One failure in storage live tests is a known flaky test.

Update pnpm-lock.yaml (full)

---

sdk/servicebus/service-bus/test/packageInfo.spec.ts
sdk/servicebus/service-bus/test/samples.spec.ts

For more context refer to #6930

[Service Bus] Update file path references

---

sdk/appconfiguration/ci.yml
sdk/applicationinsights/ci.yml
sdk/batch/ci.yml
sdk/cognitiveservices/ci.yml
sdk/core/ci.yml
sdk/cosmosdb/ci.yml
sdk/eventgrid/ci.yml
sdk/eventhub/ci.yml
sdk/graphrbac/ci.yml
sdk/identity/ci.yml
sdk/keyvault/ci.yml
sdk/operationalinsights/ci.yml
sdk/servicebus/ci.yml
sdk/servicefabric/ci.yml
sdk/storage/ci.yml
sdk/template/ci.yml
sdk/test-utils/ci.yml
sdk/textanalytics/ci.yml

This PR disables feature CI builds.

Disable feature CI builds.

---

sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/utils/testUtils.ts

For more context refer to #6738 thread

[Service Bus] Update EntityNames enum usage

---

sdk/servicebus/service-bus/test/README.md

PR to update stale README content in tests folder for Service Bus.

[Service Bus] Update tests README

---

sdk/hdinsight/arm-hdinsight/LICENSE.txt
sdk/hdinsight/arm-hdinsight/src/models/index.ts
sdk/hdinsight/arm-hdinsight/src/models/mappers.ts

1. Add minSupportedTlsVersion to cluster.json
2. Add example about minSupportedTlsVersion
3. Fixed some resource group name in previous examples

Generated from ad0c3f96660205d67ebb9920555493a108b3606e

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

These got bad after I rearranged things during the tasks for the MQ goals.
Certificates is fine 👍

[KeyVault] Fixed the deploy button

---

eng/New-TestResources.ps1
eng/Remove-TestResources.ps1
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

Relates to azure/azure-sdk-tools#326

Update test resource scripts and jobs

---

sdk/cosmosdb/cosmos/samples/QueryThroughput/alterQueryThroughput.ts

With this PR I'd like to add a sample how to alter throughput on a existing collection/database as discussed with @southpolesteve in https://github.com/Azure/azure-sdk-for-js/issues/6925

Add sample to alter throughput

---

sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/queueClient.ts
sdk/servicebus/service-bus/src/subscriptionClient.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/perf/rhea-promise/receive.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts

This PR has changes resulting from running `npm format` for the Service Bus package.
The intention is to avoid noise in PRs that are meant for actual features and bug fixes.

[Service Bus] Run npm format

---

sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-keys/karma.conf.js
sdk/keyvault/keyvault-secrets/karma.conf.js
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-file-datalake/karma.conf.js
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-queue/karma.conf.js
sdk/test-utils/recorder/GUIDELINES.md

**Description**
Fix typo/invalid import
This invalid import had broken the pipeline to generate the recordings in the browser.
**Hope**
I wish for an eslint plugin to detect invalid imports.
Thanks to @sadasant for finding the bug!!

[Recorder] jsonRecordingFilter -> jsonRecordingFilterFunction

---

sdk/storage/storage-blob/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-file-datalake/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-file-share/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-queue/src/policies/StorageRetryPolicy.ts

[Storage]Fix #7018: retry on EPIPE error

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

Use common template for SetDevVersion

---

eng/pipelines/templates/variables/globals.yml

Upgrading the java repo to use doc-warden 0.5.0.

Upgrade doc-warden to 0.5.0.

---

common/scripts/install-run.js
rush.json

- The standard files in the "common/scripts" folders need to be updated for this Rush version
- Fixes #7110
Verification Build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=243878&view=results

Update rush to 5.19.1

---

common/config/rush/pnpm-lock.yaml
sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/src/baseRecorder.ts
sdk/test-utils/recorder/src/utils.ts
sdk/test-utils/recorder/test/utils.test.ts

Please review.
Let me know if you can think of other test cases.
Fixes #6539

[recorder] Tested fix to filterSecrets

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/README.md
sdk/core/core-lro/review/core-lro.api.md
sdk/core/core-lro/src/pollOperation.ts
sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/utils/testOperation.ts
sdk/core/core-lro/test/utils/testPoller.ts

Please review.
Besides documentation, this PR adds information to the upcoming version, 1.0.1, in the CHANGELOG.
Fixes #6952

[core-lro] Better documentation

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/request/ResourceResponse.ts
sdk/cosmosdb/cosmos/test/functional/item.spec.ts

[Cosmos] Fix incorrect return type of response request charge

---

eng/.docsettings.yml

Update .docsettings yml to account for nested samples

---

sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/test/blobclientpollers.spec.ts

when the operation completes in the first request.
Address part of #5852

[Storage-blob][doc] describe beginCopyFromURL() onProgess behavior

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

- added dump flag for dependency step in ci to generate data.js as part of artifacts

add the dump flag

---

sdk/storage/storage-blob/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_and_file_endpoints.js
sdk/storage/storage-blob/recordings/node/utility_helpers/recording_extractconnectionstringparts_parses_sas_connection_string_with_queue_endpoint.js
sdk/storage/storage-blob/recordings/node/utility_helpers/recording_sanitizeheaders_redacts_sas_token.js
sdk/storage/storage-blob/recordings/node/utility_helpers/recording_sanitizeurl_redacts_sas_token.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_endpoint_suffix.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_an_explicit_endpoint.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_parses_connection_string_with_complete_service_endpoint_for_each_service.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_when_passed_an_invalid_connection_string_with_typo.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_when_passed_an_invalid_protocol_in_the_connection_string.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_with_empty_accountkey_in_the_connection_string.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_with_empty_accountname_in_the_connection_string.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_with_empty_defaultendpointsprotocol_in_the_connection_string.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only/recording_extractconnectionstringparts_throws_error_with_empty_endpointsuffix_in_the_connection_string.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only_readstreamtolocalfile/recording_rejects_when_the_filepath_is_a_directory.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only_readstreamtolocalfile/recording_rejects_when_the_readstream_emits_an_error.js
sdk/storage/storage-blob/recordings/node/utility_helpers_nodejs_only_readstreamtolocalfile/recording_writes_a_readable_stream_into_a_file.js
sdk/storage/storage-blob/test/node/utils.spec.ts
sdk/storage/storage-blob/test/utils.spec.ts

- Tests do not make live HTTP requests, so recordings were empty and unnecessary

[Storage] Remove unnecessary recordings from util tests

---

sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts

Based on conversation - https://github.com/Azure/azure-sdk-for-js/pull/6825#issuecomment-582572864

increment app-config version

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/samples/browserSample/README.md
sdk/eventhub/event-hubs/samples/browserSample/index.html
sdk/eventhub/event-hubs/samples/browserSample/package.json
sdk/eventhub/event-hubs/samples/browserSample/src/configuration.js
sdk/eventhub/event-hubs/samples/browserSample/src/index.js
sdk/eventhub/event-hubs/samples/browserSample/src/receiveEvents.js
sdk/eventhub/event-hubs/samples/browserSample/src/sendEvents.js
sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/util/runtimeInfo.browser.ts
sdk/eventhub/event-hubs/src/util/runtimeInfo.ts

This change addresses some of the feedback from #7248 
It also adds a sample that shows how to send and receive events in a browser app.

[event-hubs] user-agent fixes and browser sample

---

README.md
eng/pipelines/templates/jobs/aggregate-dependencies.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/tools/analyze-deps/index.js

Here's the pipeline set up for testing purposes - https://dev.azure.com/azure-sdk/internal/_build?definitionId=1394&_a=summary

Dependency Graph Pipeline

---

sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClientContext.ts

ci pr: https://github.com/Azure/azure-sdk-for-js/pull/7288

bump version

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/constants.ts

Updates package version and changelog.

[service-bus] prepare for release 1.1.3

---

common/config/rush/pnpm-lock.yaml
sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json

Updates the amqp-common dependency to preview 10.

[service-bus] update amqp-common dep

---

sdk/eventhub/event-hubs/CHANGELOG.md

[event-hubs] update changelog date

---

sdk/textanalytics/ai-text-analytics/package.json
sdk/textanalytics/ai-text-analytics/src/constants.ts
sdk/textanalytics/ai-text-analytics/src/generated/textAnalyticsClientContext.ts

[ai-text-analytics] fixed constants and added constant metadata for preview 3

---

sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-keys/karma.conf.js
sdk/keyvault/keyvault-secrets/karma.conf.js

Recent changes to these files (that I did) missed the proper formatting.
To do these changes, I just ran `rushx format` in each folder.

[KeyVault] Formatting the karma.conf.js files

---

sdk/servicebus/service-bus/src/core/linkEntity.ts
sdk/servicebus/service-bus/src/core/messageSender.ts

[Service Bus] Use AwaitableSender from rhea-promise to send messages 

---

sdk/containerservice/arm-containerservice/LICENSE.txt
sdk/containerservice/arm-containerservice/README.md
sdk/containerservice/arm-containerservice/package.json
sdk/containerservice/arm-containerservice/src/containerServiceClientContext.ts
sdk/containerservice/arm-containerservice/src/models/agentPoolsMappers.ts
sdk/containerservice/arm-containerservice/src/models/containerServicesMappers.ts
sdk/containerservice/arm-containerservice/src/models/index.ts
sdk/containerservice/arm-containerservice/src/models/managedClustersMappers.ts
sdk/containerservice/arm-containerservice/src/models/mappers.ts
sdk/containerservice/arm-containerservice/src/models/openShiftManagedClustersMappers.ts
sdk/containerservice/arm-containerservice/src/models/parameters.ts
sdk/containerservice/arm-containerservice/src/operations/agentPools.ts
sdk/containerservice/arm-containerservice/src/operations/managedClusters.ts
sdk/containerservice/arm-containerservice/src/operations/operations.ts

Related swagger readme:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/readme.md
PRs are: 
https://github.com/Azure/azure-rest-api-specs/commit/3245f640b9c7908ca0918171c3560a2b54f5adc2#diff-379bd052a1d1dd6e383002fd886fb84a
https://github.com/Azure/azure-rest-api-specs/commit/a7375936288e1203587027def5a90b8744db7edf#diff-379bd052a1d1dd6e383002fd886fb84a

release arm-containerservice v10.1.0

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateblobsasqueryparameters_should_work_for_blob_with_blob_sas_using_access_policy.js
sdk/storage/storage-blob/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateblobsasqueryparameters_should_work_for_blob_with_container_sas_using_access_policy.js
sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/test/node/sas.spec.ts

This is fix for [issue 7115](https://github.com/Azure/azure-sdk-for-js/issues/7115). Original problem is that resource is only assigned properly when permission field is provided. And fix is parsing resource field in independent logic branch.

Fix logic for generating a blob SAS using a stored policy.

---

sdk/keyvault/keyvault-certificates/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-keys/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-secrets/test/utils/recorderUtils.ts

Finally fixed the path to the .env file.
Fixes #6732

[KeyVault] Fixing the .env path

---

sdk/storage/storage-blob/src/Clients.ts

This PR targets to optimize example for appendBlock method, and solve requirement related to [7270](https://github.com/Azure/azure-sdk-for-js/issues/7270).

[Storage] Optimize appendBlock's example.

---

sdk/core/core-paging/README.md

Even though the example in core-paging README is not complete running code, it is still nice to align with current API.

[core-paging] Update code snippets in README

---

sdk/core/core-lro/CHANGELOG.md

[core-lro] Setting a release date for version 1.0.1

---

sdk/core/core-paging/README.md
sdk/core/core-paging/types/corePaging.d.ts
sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/keyvault/keyvault-secrets/src/index.ts

We don't really need type inference here.

[core-paging] set PageT default to T[]

---

sdk/cosmosdb/cosmos/README.md

Update @azure/cosmos README

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/README.md

Updates the changelog and README based on feedback.

[event-hubs] prepare for 5.0.2 release

---

sdk/search/search/CHANGELOG.md
sdk/search/search/README.md

Small update to CHANGELOG
Also a few minor README updates to fix issues found in testing

Set release date for search

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/src/index.ts

While checking all of the inline samples, I found some things to fix from changes prior to the changes relevant to the march release. Please review.
I only found these issues in keyvault-keys and keyvault-secrets. No issues in certificates.

[KeyVault] Inline sample fixes

---

sdk/appconfiguration/test-resources.json

Now that AppConfig is real you're limited to a single free AppConfig resource per subscription. Changing over to Standard as the default.

[app-configuration] Add in SKU to arm template 

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json

As far as I can tell, these packages are no longer used. They were dragging in some stuff to our graph that is pretty old too.

Remove unused dependencies

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json

Datalake 12.0.0 GA; Blob/File 12.1.1; Queue 12.0.4

[storage] Updated version for the March release

---

sdk/identity/identity/CHANGELOG.md

Adds a line for the Azure CLI credential preview

[Identity] Add 1.1 preview 1 to changelog for identity

---

sdk/identity/identity/CHANGELOG.md

Remove the (released) header as recommended by @jeremymeng

[Identity] Update identity changelog

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

This PR sets the release date for version `4.1.0-preview.1`. I will use the commit hash of this PR to trigger the release pipeline.

[KeyVault] Defined a release date for 4.1.0-preview.1

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-datalake/karma.conf.js
sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/karma.conf.js

[storage] fix #7745 add polyfill

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/package.json
sdk/textanalytics/ai-text-analytics/src/constants.ts
sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts

- Closing this PR https://github.com/Azure/azure-sdk-for-js/pull/7746 since it didn't update correctly as the metadata paths were incorrect and it exited with ENOENT error in pipeline due to ncorrect file location(s)

Increment version for textanalytics

---

eng/tools/generate-static-index/static-files/main.js

New Versioning Should Apply to Index as Well

---

sdk/servicebus/service-bus/CHANGELOG.md

Commit 1 - cherrypicked from master to fix the typedoc issue
Commit 2 - changes from the hotfix branch
Commit 3 - resolved merge conflicts and merged

[Service Bus] Merge 'hotfix/service-bus-1.1.4-increase-timeout' into master

---

sdk/policyinsights/arm-policyinsights/LICENSE.txt
sdk/policyinsights/arm-policyinsights/src/models/index.ts
sdk/policyinsights/arm-policyinsights/src/models/mappers.ts
sdk/policyinsights/arm-policyinsights/src/operations/policyStates.ts
sdk/policyinsights/arm-policyinsights/src/policyInsightsClientContext.ts

Generated from 93b740901ffff1df0fe936b9c6a2d9d83961df1d

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml
sdk/eventhub/event-processor-host/tests.yml

Update `macOS-10.13` image to `macOS-10.15`
Cherry-picked from master - 560a9fb

Update macOS.10.13 to macOS.10.15 (#7662)

---

sdk/identity/identity/src/client/errors.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.browser.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.browser.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/manual-integration/Kubernetes/index.ts
sdk/identity/identity/test/manual-integration/Kubernetes/run_test.ts
sdk/identity/identity/test/mockAzureCliCredentialClient.ts
sdk/identity/identity/test/node/azureCliCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

Running the formatter to avoid noise in PRs that contain non-formatting changes

Run formatter on identity

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/index.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/src/policies/throttlingRetryPolicy.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/typedoc.json

Running the formatter to avoid noise in PRs that contain non-formatting changes

Run formatter on AppConfig

---

sdk/core/core-amqp/CHANGELOG.md

/cc @richardpark-msft I'm assuming there are no changes needed for service bus this time around.

[core-amqp] update changelog for v1.1.1

---

sdk/servicebus/service-bus/README.md

[service-bus] add api docs link for v1 library

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/typescript/src/advanced/deferral.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/movingMessagesToDLQ.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/processMessageFromDLQ.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionState.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/topicFilters.ts
sdk/servicebus/service-bus/samples/typescript/src/browseMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/typescript/src/scheduledMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/sendMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/session.ts
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/samples/typescript/src/usingAadAuth.ts

This PR updates the Readme and samples to call out the fact that this a preview more prominently

[Service Bus] Call out preview usage more prominently

---

eng/pipelines/templates/stages/archetype-js-release.yml

Switch relative path reference to absolute path

Switch from relative to Absolute paths

---

.azure-pipelines/client.yml
common/config/rush/pnpm-lock.yaml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-tests.yml
eng/pipelines/templates/jobs/node6-test-sdk-client.yml
rush.json
sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/rollup.base.config.js
sdk/core/amqp-common/src/auth/aad.ts
sdk/core/amqp-common/test/node/aadProvider.spec.ts

This is the first PR to fix #8041, will need to follow up with making a similar change to service bus once this is released.

[amqp-common] remove ms-rest-nodeauth dep

---

sdk/servicebus/service-bus/README.md

[service-bus] Track2 readme updates based on review

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-js-release.yml

- fixes issue https://github.com/Azure/azure-sdk-for-js/issues/8135

addressing missing working directory

---

common/smoke-test/KeyVault.ts
common/smoke-test/smoke-tests.yml
common/smoke-test/test-resources.json

* Adds ability to specify authority host with `AZAURE_CLOUD`
* Uses dynamic resource allocation
* Adds Azure China Cloud to test matrix

Smoke tests use dynamic test resources

---

sdk/identity/identity/CHANGELOG.md

Adds the release date for the April release to the changelog.

[Identity] Add release date to changelog

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/migrationguide.md

Simple migration guide for people interested in trying out our latest SB preview.

[service-bus] Track2 - quick-start migration guide.

---

sdk/search/search/README.md

[search] Update README for preview 2

---

sdk/servicebus/service-bus/src/sender.ts

This PR doesn't do much but seems appropriate.

[Service Bus] Long.Long -> Long

---

sdk/eventgrid/arm-eventgrid/package.json
sdk/eventgrid/arm-eventgrid/src/eventGridManagementClientContext.ts
sdk/eventgrid/arm-eventgrid/src/models/domainTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/domainsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/eventChannelsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/eventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/extensionTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/index.ts
sdk/eventgrid/arm-eventgrid/src/models/mappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerNamespacesMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerRegistrationsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerTopicEventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/privateEndpointConnectionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/systemTopicEventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/systemTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/topicTypesMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/topicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/operations/eventChannels.ts
sdk/eventgrid/arm-eventgrid/src/operations/partnerTopicEventSubscriptions.ts
sdk/eventgrid/arm-eventgrid/src/operations/privateEndpointConnections.ts
sdk/eventgrid/arm-eventgrid/src/operations/systemTopicEventSubscriptions.ts

swaggerPR: https://github.com/Azure/azure-rest-api-specs/pull/8880

Sdk automation/@azure arm eventgrid

---

sdk/search/ci.yml
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchServiceClient.ts

Also update ci pipeline file with rename.

[search] Update changelog for release

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

I don't think this is used anymore now that we have karma.

[core-http] Remove mocha-chrome dependency

---

sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts

Tested with a messageIterator sample, that's working for node 8.

[Service Bus] import @azure/core-asynciterator-polyfill for node 8

---

sdk/search/search-documents/README.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchServiceClient.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts

This PR includes the code changes for the following APIs:
1. Indexer - List
2. Indexer - Create
3. Indexer - Get
4. Indexer - Create/Update
5. Indexer - Delete
6. Indexer - Get Status
7. Indexer - Reset
8. Indexer - Run
All the APis have been tested. Samples have been added to Readme (Except for reset/run which are just one liners)
@xirzec  Please review and approve the PR. 

Code changes for Indexer Operations in Search Service

---

sdk/eventhub/event-hubs/migrationguide.md
sdk/eventhub/event-hubs/samples/javascript/README.md
sdk/eventhub/event-hubs/samples/javascript/receiveEvents.js
sdk/eventhub/event-hubs/samples/typescript/README.md
sdk/eventhub/event-hubs/samples/typescript/src/receiveEvents.ts

Fix broken links for checkpointstore sample in the Event Hubs samples & readmes

[Event Hubs] Fix broken links for checkpointstore sample

---

sdk/search/search-documents/README.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchServiceClient.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts

This PR includes APIs related to datasources and service statistics. @xirzec Please review and approve. 

Search Service - Datasources & Service Statistics API

---

sdk/cosmosdb/cosmos/CHANGELOG.md

[Cosmos] Add docs to changelog about removal of partitionKey option

---

sdk/identity/identity/src/credentials/vscodeCredential.ts
sdk/identity/identity/test/identityClient.spec.ts

Should fix the root cause of #8331

[Identity] Correctly pass through the options

---

sdk/formrecognizer/ai-form-recognizer/swagger/README.md

There's no changes in generated code after re-running code generator.

[FormRecognizer] Use swagger json from api specs master branch

---

sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/serviceClientTests.ts

Related to [Issue: 4244](https://github.com/Azure/azure-sdk-for-js/issues/4244). 
@ramya-rao-a Please review and approve

Encode query parameters in an array before joining them

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/rollup.base.config.js
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/poller.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formrecognizerclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formtrainingclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/node/setup.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/util/trainingContainer.ts

- Training, form recognition
- content/receipt recognition
Part of #7440.

[FormRecognizer] add live tests

---

sdk/formrecognizer/ai-form-recognizer/README.md

- remove TypeScript type
- fix copy paste error

[FormRecognizer] fix README code snippets

---

sdk/core/core-lro/CHANGELOG.md

Hi! Let me know how this looks.

[core-lro] 1.0.2 Release date

---

sdk/search/search-documents/src/generated/service/models/index.ts
sdk/search/search-documents/src/generated/service/models/mappers.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/swagger/Service.md

Code to fix https://github.com/Azure/azure-sdk-for-js/pull/8154

Code to change maximumPageLength to maxPageLength

---

sdk/formrecognizer/ai-form-recognizer/samples/javascript/README.md
sdk/formrecognizer/ai-form-recognizer/samples/typescript/README.md

after preview.1 release available on npmjs

[FormRecognizer] add sample metadata to enable auto-publishing

---

sdk/template/template/README-TEMPLATE.md
sdk/template/template/README.md

Include a more complete README.md example so new libraries using `template` as a start point could better follow the README guideline.

Update template readme

---

sdk/keyvault/keyvault-certificates/.eslintrc.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/test/CRUD.test.ts
sdk/keyvault/keyvault-certificates/test/list.test.ts
sdk/keyvault/keyvault-certificates/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-certificates/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-certificates/test/utils/testAuthentication.ts
sdk/keyvault/keyvault-certificates/test/utils/testClient.ts
sdk/keyvault/keyvault-certificates/tsconfig.eslint.json

[KeyVault-Certificates] Updating eslint

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-auth/CHANGELOG.md
sdk/core/core-tracing/CHANGELOG.md

Set a date for the next core release.

[core] Update release date for core packages

---

sdk/search/search-documents/README.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/searchServiceClient.ts

Related to https://github.com/Azure/azure-sdk-for-js/issues/8525 

SearchServiceClient should expose a getSearchIndexClient

---

sdk/keyvault/keyvault-secrets/.eslintrc.json
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/index.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/test/list.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-secrets/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-secrets/test/utils/testAuthentication.ts
sdk/keyvault/keyvault-secrets/test/utils/testClient.ts
sdk/keyvault/keyvault-secrets/test/utils/utils.common.ts

Good, up to date eslint on Key Vault Secrets.
Fixes #7148

[KeyVault-Secrets] Eslint should be good now

---

sdk/core/core-auth/CHANGELOG.md

as it's causing github release api to return 400 Bad Request

[core-auth] Replace the NO BREAK SPACE with normal space

---

sdk/keyvault/keyvault-certificates/package.json

As discussed, we should be fine making this script unforgiving.

[KeyVault-Certificates] Bad eslint should break CI

---

sdk/keyvault/keyvault-keys/.eslintrc.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-keys/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-keys/test/utils/testAuthentication.ts
sdk/keyvault/keyvault-keys/test/utils/testClient.ts
sdk/keyvault/keyvault-keys/test/utils/utils.common.ts

Good, up to date eslint on Key Vault Keys.
Fixes #7147

[KeyVault-Keys] Eslint should be good now

---

sdk/textanalytics/ai-text-analytics/README.md

[ai-text-analytics] Updated README logging section

---

sdk/servicebus/service-bus/README.md

After meeting to discuss our readme it looks like our Key Concepts section wasn't as fleshed out as all the other readmes. This brings us up to code.
Also, adding in a "All samples" link to the TOC just to make it even simpler for users to find them.

[service-bus] Track2 - Updating readme with feedback about key concepts

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/src/connectionConfig/connectionConfig.ts
sdk/core/amqp-common/test/config.spec.ts

Porting the fix from track 2 for amqp-common - https://github.com/Azure/azure-sdk-for-js/pull/8278

[AMQP Common] Relaxing the scheme check

---

sdk/identity/identity/CHANGELOG.md

Add changelog for the @azure/identity 1.1.0-preview.3 release.

Identity changelog updates for 1.1.0-preview.3

---

sdk/formrecognizer/ai-form-recognizer/README.md

to fix the az cli command to create a Form Recognizer resource

[FormRecognizer] Update README.md

---

sdk/eventhub/event-hubs/README.md

This PR addresses the readme feedback in
- #5355 Add link to generic EPH docs
- #8323 Code snippets should use the earliest event position and have a timer to allow receiving of events
- #8565 
- TS section should be under Pre-requisites
- Clarify the connection string with entity path confusion

[Event Hubs] Readme updates based on feedback

---

sdk/search/search-documents/README.md

This PR is for 2 purposes:
1. Based on the feedback from the Readme Doc review meeting on Monday
2. https://github.com/Azure/azure-sdk-for-js/issues/8356 
Feedback from Readme Doc Review meeting:
1. Change the location of Node JS requirement
2. Remove numbering from Installation step
3. Make authentication a heading
4. Change the Key Concepts to the same as one found in Java/Python SDKs 
5. Keep only the important examples. Rest of the example can be added to the samples (which will be done in the Add More Samples task).

Readme content of Azure Search Documents is unclear

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/serviceClientTests.ts

The reason for this PR has been explained in detail in the gist https://gist.github.com/sarangan12/ddcec9a5789984dba777713855634166. 
@joheredi Please review and approve

Code change to check if delimiter is tabs-spaces & value is null/undefined

---

sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/mappers.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/train/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/swagger/README.md
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts

having the same name 'FormRecognizerClient'.  It cause the docs of both to be merged as described in 
#8531

[FormRecognizer] Fix doc issue caused by generated client

---

sdk/eventhub/event-hubs/CHANGELOG.md

[event-hubs] update changelog for 5.2.0 release

---

sdk/core/core-auth/.eslintrc.json
sdk/core/core-auth/package.json
sdk/core/core-auth/src/azureKeyCredential.ts
sdk/core/core-auth/src/index.ts
sdk/core/core-auth/src/tokenCredential.ts
sdk/core/core-auth/test/index.spec.ts

Related to #8345
I have fixed all of the eslint errors for core-auth as part of this PR.

[core-auth] Upgrade to @azure/eslint-plugin-azure-sdk@^3.0.0

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json

Pre-requisite of https://github.com/Azure/azure-sdk-for-js/pull/8403

[AMQP Common] version bump preview.14

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/impl/eventHubClient.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/test/sender.spec.ts

[event-hubs] send span peer.address maps to fully qualified namespace

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/test/partitionPump.spec.ts

[event-hubs] add enqueueTime to process span links

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/utils/digest.browser.ts
sdk/cosmosdb/cosmos/src/utils/globalCrypto.ts
sdk/cosmosdb/cosmos/src/utils/hmac.browser.ts

[Cosmos] Support browser crypto in Internet Explorer

---

sdk/core/core-http/CHANGELOG.md

We didn't end up shipping this on Friday, so let's ship it today!

[core-http] Bump changelog date for patch release

---

sdk/core/core-tracing/.eslintrc.json
sdk/core/core-tracing/package.json
sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/index.ts
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracerProxy.ts
sdk/core/core-tracing/src/tracers/noop/noOpSpan.ts
sdk/core/core-tracing/src/tracers/noop/noOpTracer.ts
sdk/core/core-tracing/src/tracers/opencensus/openCensusSpanWrapper.ts
sdk/core/core-tracing/src/tracers/opencensus/openCensusTraceStateWrapper.ts
sdk/core/core-tracing/src/tracers/opencensus/openCensusTracerWrapper.ts
sdk/core/core-tracing/src/tracers/test/testSpan.ts
sdk/core/core-tracing/src/tracers/test/testTracer.ts
sdk/core/core-tracing/src/utils/browser.d.ts
sdk/core/core-tracing/src/utils/cache.ts
sdk/core/core-tracing/src/utils/global.browser.ts
sdk/core/core-tracing/src/utils/global.ts
sdk/core/core-tracing/src/utils/traceParentHeader.ts
sdk/core/core-tracing/test/interfaces.spec.ts
sdk/core/core-tracing/test/traceParentHeader.spec.ts

Related to #8345
I have fixed all of the eslint errors for core-tracing as part of this PR.

[core-tracing] Upgrade to @azure/eslint-plugin-azure-sdk@^3.0.0

---

sdk/servicebus/service-bus/samples/javascript/advanced/sessionRoundRobin.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts

In track 1 we added in some nicer abortSignal handling so the process properly exits. 
This just ports it over to track 2.

[service-bus] Update the sessionroundrobin with the abortSignal/graceful exit from track 1

---

rush.json

Updating pnpm to the version 4.12.5 since that is the most recent version that works in our repo successfully. Also ran rush update and rush build locally and it succeeded.

update pnpm version - 4.12.5

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts

[Service Bus] "fullyQualifiedNamespace" on SBC

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts

[Service Bus] `isClosed` for receiver

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts

[Service Bus] EntityPath for the sender

---

sdk/servicebus/service-bus/CHANGELOG.md

Adding missing changelog updates for 1.1.7 release of Service Bus

[Service Bus] Changelog update for 1.1.7 release

---

sdk/servicebus/service-bus/test/batchReceiver.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/pull/8552#discussion_r424096720

[service-bus] fix drain test

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts

Followup from https://github.com/Azure/azure-sdk-for-js/issues/8677#issuecomment-627457561

[Service Bus] Updating comments for token provider and proxy sample

---

sdk/keyvault/keyvault-certificates/package.json

KeyVault-Keys is doing nothing here.

[KeyVault-Certificates] Removing keyvault-keys from the dependencies

---

sdk/appconfiguration/app-configuration/rollup.base.config.js
sdk/core/abort-controller/rollup.base.config.js
sdk/core/core-amqp/rollup.base.config.js
sdk/core/core-auth/rollup.base.config.js
sdk/core/core-http/rollup.base.config.js
sdk/core/core-https/rollup.base.config.js
sdk/core/core-lro/rollup.base.config.js
sdk/core/core-tracing/rollup.base.config.js
sdk/core/logger/rollup.base.config.js
sdk/eventhub/event-hubs/rollup.base.config.js
sdk/eventhub/event-processor-host/rollup.base.config.js
sdk/eventhub/eventhubs-checkpointstore-blob/rollup.base.config.js
sdk/formrecognizer/ai-form-recognizer/rollup.base.config.js
sdk/identity/identity/rollup.base.config.js
sdk/keyvault/keyvault-certificates/rollup.base.config.js
sdk/keyvault/keyvault-keys/rollup.base.config.js
sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/search/search-documents/rollup.base.config.js
sdk/servicebus/service-bus/rollup.base.config.js
sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-file-datalake/rollup.base.config.js
sdk/storage/storage-file-share/rollup.base.config.js
sdk/storage/storage-queue/rollup.base.config.js
sdk/template/template/rollup.base.config.js
sdk/test-utils/recorder/rollup.base.config.js
sdk/textanalytics/ai-text-analytics/rollup.base.config.js

The replacement should be in the argument object, instead of nested in `values` property.
Fixes #7243

Fix the option object to rollup-replace plugin

---

.github/CODEOWNERS

Helping maintain Cosmos JS SDK, cc @southpolesteve

Adds zfoster to Cosmos JS SDK Codeowners

---

sdk/core/logger/README.md

I found two typos in logger 🌞
I was able to detect these by using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) on VSCode.

[logger] Fixing typos

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts

[Service Bus] Porting `Fulfill promise when disconnect occurs after drain is requested` from track 1

---

eng/tools/generate-static-index/service-mapper.json

update service name for form recognizer. ensure github.io reflects nicely

Update github.io Service Name for formrecognizer

---

sdk/appconfiguration/app-configuration/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-https/package.json
sdk/core/core-lro/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json
sdk/test-utils/recorder/package.json
sdk/textanalytics/ai-text-analytics/package.json

- Newer versions cause build breaks in our repo

Pin @rollup/plugin-commonjs to 11.0.2

---

sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/trainLabeledModel.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/trainUnlabeledModel.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/trainLabeledModel.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/trainUnlabeledModel.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts

Change the relationship of the two clients. Now we get form recognizer client
off form training client.
Fixes #9029

[FormRecognizer] getFormRecognizerClient() on FormTrainingClient

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-arm/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-https/package.json
sdk/core/core-lro/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json
sdk/test-utils/recorder/package.json
sdk/textanalytics/ai-text-analytics/package.json

New major has a few breaking changes but all builds are green so it seems they don't impact us:
https://github.com/rollup/plugins/blob/master/packages/node-resolve/CHANGELOG.md#v800

Update dev dependency "@rollup/plugin-node-resolve"

---

sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts

for FormRecognizerClient instance created in getFormRecognizerClient().

[FormRecognizer] Share the same client options

---

sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/trainUnlabeledModel.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/trainUnlabeledModel.ts
sdk/formrecognizer/ai-form-recognizer/src/common.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/mappers.ts
sdk/formrecognizer/ai-form-recognizer/src/index.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/train/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/swagger/README.md
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts

- Add pageNumber to FieldText
- CustomFormSubModel => CustomFormSubmodel
- TrainModelOptions => TrainingFileFilter
- ContentType => FormContentType
- Models `createdOn` => `requestedOn`, `lastModified` => `completedOn`
- FormText => FieldText

[FormRecognizer] Address design issue for preview.3

---

common/config/rush/pnpm-lock.yaml

- Adds changes missing from #9059

rush update

---

sdk/core/core-amqp/CHANGELOG.md

/cc @richardpark-msft @HarshaNalluru

[core-amqp] prepare for 1.1.3 release

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/indexDocumentsBatch.ts
sdk/search/search-documents/src/searchClient.ts

This PR is related to https://github.com/Azure/azure-sdk-for-js/issues/9242.

Delete - Seach API Changes

---

sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeReceipt.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeReceiptFromUrl.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeReceipt.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeReceiptFromUrl.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/internalModels.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/contentPoller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/customFormPoller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/receiptPoller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/train/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/test/browser/formrecognizerclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formrecognizerclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts

While at it I also did some refactoring around `FormField`.

[FormRecognizer] Remove US receipts

---

sdk/search/search-documents/CHANGELOG.md

Modified changelog for the June Release

Modified changelog for the June Release

---

sdk/formrecognizer/test-resources.json

This is to avoid busy region like westus2

[FormRecognizer] Update live test resource region

---

common/smoke-test/smoke-tests.yml
eng/pipelines/templates/steps/common.yml
eng/pipelines/templates/steps/use-node-test-version.yml
eng/pipelines/templates/steps/use-node-version.yml

- Also update smoke tests to use common template (which verifies OS)

Verify node version after install

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/auth.ts
sdk/cosmosdb/cosmos/src/utils/globalCrypto.ts
sdk/cosmosdb/cosmos/test/functional/authorization.spec.ts
sdk/cosmosdb/cosmos/test/unit/auth.spec.ts

- Fixes #9110
- Fixes unfiled bug where Cosmos was not able to find `globalThis` in the IE browser

[Cosmos] 3.7.1 Fixes null authToken for deleting items and IE browser crypto bug

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/test/functional/client.spec.ts

[Cosmos] Fix bug where abort signal was being called immediately if passed by the user

---

sdk/search/search-documents/src/searchIndexerClient.ts

This is related to Issue https://github.com/Azure/azure-sdk-for-js/issues/9594 

[search-documents] Add sentinel value to connection string

---

sdk/search/search-documents/README.md

This PR is to modify TS/JS SDK search-documents Readme close to .NET Readme.
@xirzec Please review and approve. 
@ramya-rao-a FYI........

Modified Readme file similar to .NET Readme

---

sdk/search/search-documents/README.md

The search API signature in the Readme sample is fixed with this PR.
@xirzec Please approve

Change Readme sample

---

sdk/core/core-amqp/CHANGELOG.md
sdk/servicebus/service-bus/CHANGELOG.md

[Service Bus] Add changelog for recent service bus PRs

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/README.md

Fixes #9684 and prepares for the 5.2.2 release.

[event-hubs] prepare for 5.2.2 release

---

sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/search/search-documents/package.json
sdk/textanalytics/ai-text-analytics/package.json

for the ES5 compatibility fix.

Bump core-auth dependency version to 1.1.3

---

sdk/cognitiveservices/cognitiveservices-textanalytics/package.json

Reverting incorrect version that accidentally changed from previous PR https://github.com/Azure/azure-sdk-for-js/commit/32611f8e8d2da4c7facdaec9ac6d71253d1c924c

reverting incorrect version in PR #6856
