sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts

This PR reworks the AzurePowerShellCredential's logic to remove the `useLegacyPowerShell` option. I also cleaned up some of the terms around PowerShell branding, specifically replaced all instances of "powershell", "power shell", "Powershell" and "Power Shell" with "PowerShell".
I also updated the CHANGELOG and set the release date (for tomorrow). There will be one final PR with some changes to samples and the README.
- Removed option `useLegacyPowerShell`
- Use `pwsh`/`pwsh.exe` by default, fall back to `powershell.exe` on Windows.
- Added CHANGELOG entry for AzurePowerShellCredential
- Added release information to CHANGELOG.
- Reworked tests to account for new behavior.

[identity] Rework AzurePowerShellCredential fallback sequence

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/src/lro/delete/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/recover/operation.ts
sdk/keyvault/keyvault-certificates/test/internal/lroUnexpectedErrors.spec.ts
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/test/internal/lroUnexpectedErrors.spec.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/test/internal/lroUnexpectedErrors.spec.ts

Recently we found that if Azure had unexpected errors, they wouldn't properly bubble up in these Key Vault pollers. This PR ensures the errors bubble up.

[Key Vault] Fixed pollers that wouldn't bubble up unknown errors to end users

---

sdk/communication/communication-phone-numbers/test/public/get.spec.ts
sdk/communication/communication-phone-numbers/test/public/list.spec.ts
sdk/communication/communication-phone-numbers/test/public/lro.purchaseAndRelease.spec.ts
sdk/communication/communication-phone-numbers/test/public/lro.search.spec.ts

This PR adds a baseline 1 minute timeout to phone number tests we do not expect to throw, and 1:30 seconds timeout to tests we know will take a little longer. This is an attempt to stabilize the phone numbers pipeline after the recent changes to have INT pipeline runs.

[communication][phone-numbers] increase test timeouts

---

sdk/identity/identity/CHANGELOG.md

Since `@azure/msal-node-extensions` is removed, this changelog entry is now outdated and should be removed 😅

[Identity] This changelog entry should not be here

---

sdk/identity/identity/interactive-browser-credential.md
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts

This PR is to clarify when to use what kind of Redirect URI in the Azure App Registrations used to authenticate via Node or Browsers with the InteractiveBrowserCredential.

[Identity] InteractiveBrowserCredential redirect URI clarifications

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

@types/chalk is deprecated. Updating chalk dependency since latest version of chalk has typings included, so no need for the @types package. This was opened in response to the following warning  as part of weekly updates -

Update chalk dependency and remove @types/chalk

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/src/util/constants.ts
sdk/servicebus/service-bus/src/util/errors.ts
sdk/servicebus/service-bus/test/internal/amqp.spec.ts
sdk/servicebus/service-bus/test/internal/unit/amqpUnitTests.spec.ts
sdk/servicebus/service-bus/test/public/amqpAnnotatedMessage.spec.ts

Re-enabling the AMQP body type encoding feature. We disabled this temporarily when we released 7.1.0 and are now re-enabling this in time for our new preview: 7.2.0-beta.1

[service-bus] Re-enabling the AMQP body type encoding feature.

---

sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
sdk/keyvault/keyvault-admin/src/accessControlModels.ts
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/backupClientModels.ts
sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
sdk/keyvault/keyvault-admin/src/lro/backup/poller.ts
sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/restore/poller.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveRestore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveRestore/poller.ts
sdk/keyvault/keyvault-admin/test/public/accessControlClient.spec.ts
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
sdk/keyvault/keyvault-keys/src/identifier.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/test/public/crypto.hsm.spec.ts

- Admin client operations prefixed with KeyVault
- AesGcmDecryptParameters' authenticationTag is required
- Rename KeyVaultKeyId to KeyVaultKeyIdentifier
- Rename beginRestore's blobStorageUri to folderUri
- Rename beginSelectiveRestore's blobStorageUri to folderUri
- Collapse KeyVaultRoleAssignmentPropertiesWithScope to KeyVaultRoleAssignmentProperties
- These tasks are the result of cross-language API unification for KeyVault
Resolves #15186
Resolves #15210
Resolves #15212

[KeyVault] - Admin and Keys API unification

---

common/config/rush/pnpm-lock.yaml
sdk/quantum/quantum-jobs/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-datalake/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md

[storage-blob]Support version 2020-08-04 in storage-blob and storage-file-datalake package.

Support version 2020-08-04 in storage-blob and storage-file-datalake package.

---

eng/tools/versioning/set-dev.js

- Use "semver.eq()" (which includes prerelease tags) instead of comparing major, minor, and patch
Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=896939&view=results

Include prerelease tag when updating dev versions

---

sdk/tables/ci.yml
sdk/tables/data-tables/review/data-tables.api.md
sdk/tables/data-tables/samples-dev/workingWithBigInt.ts
sdk/tables/data-tables/samples-dev/workingWithInt64.ts
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/src/models.ts
sdk/tables/data-tables/src/serialization.ts
sdk/tables/data-tables/test/internal/serialization.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts

* Support bigint on entities creation and retrieval.
Working with bigint
```typescript
await client.createEntity({partitionKey: "p1", rowKey: "1", foo: BigInt(12345678)});
const entity = await client.getEntity("p1", "1");
// You can do arithmetic operations with big int
const fooPlusOne = entity.foo + BigInt(1);
// 12345679
```
* Add an option to disable automatic deserialization. If this option is true, when retreiving entities all the properties will be in the "metadata" from. For example:
Entity by default
```typescript
// Foo is a number
console.log(entity.foo);
// 123
```
Entity with disableDeserialization
```typescript
// Foo is a number
console.log(entity.foo);
// {value: 123, type: "Int32"}
```

[Tables] Support bigint

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/tests.yml

Node8 Validation was dropped for Tables CI. Live tests need to drop Node8 validation as well as it is not compatible with bigint

[Tables] Skip Node8 for Live Test Validation

---

sdk/core/core-http/src/util/sanitizer.ts
sdk/core/core-rest-pipeline/src/util/sanitizer.ts

Looking at the MDN doc about Accept-Encoding, it doesn't contain sensitive information.
"The Accept-Encoding request HTTP header advertises which content encoding, usually a compression algorithm, the client is able to understand."
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding
This PR adds it to the allowed header name list so its value is not sanitized in logging.

[core] allow logging of Accept-Encoding header value

---

sdk/core/core-asynciterator-polyfill/package.json
sdk/core/core-http/package.json
sdk/core/core-http/rollup.base.config.js
sdk/core/core-http/tsconfig.es.json

- .map files are now included
- change the esm output directory of core-http to dist-esm to align with other
client libraries in this repository
Fixes #15254

[core] Fix core-http and core-asynciterator-polyfill packaging issue

---

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/core/core-rest-pipeline/src/policies/redirectPolicy.ts
sdk/core/core-rest-pipeline/test/node/getBodyLength.spec.ts

This PR is to fix the issues reported at:
1. https://github.com/Azure/azure-sdk-for-js/issues/15312
2. https://github.com/Azure/azure-sdk-for-js/issues/15313
@xirzec Please review and approve the PR.

Fix UTF-8 String len & DELETE Request Body

---

SUPPORT.md

GitHub issues should not be the last thing we mention in the support doc after community resources.
This PR re-orders the resources in the order that we expect people to use

Update order of resources in the support.md

---

sdk/tables/data-tables/package.json
sdk/tables/data-tables/test/internal/serialization.spec.ts
sdk/tables/data-tables/test/internal/sharedKeyCredential.spec.ts
sdk/tables/data-tables/test/internal/utils.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts
sdk/tables/data-tables/test/public/transaction.spec.ts
sdk/tables/data-tables/test/testUtils.ts
sdk/test-utils/test-utils/src/index.ts
sdk/test-utils/test-utils/src/utils.ts

core - ci was failing for the following two tests in node 8 since bigint is being used.
Talked to @joheredi and decided to skip these tests in node 8 to unblock.

[Tables] Fix core-ci <=> skip int64 tests in node 8

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
sdk/keyvault/keyvault-admin/samples-dev/backupRestoreHelloWorld.ts
sdk/keyvault/keyvault-admin/samples-dev/backupSelectiveRestore.ts
sdk/keyvault/keyvault-admin/samples/v4/javascript/backupRestoreHelloWorld.js
sdk/keyvault/keyvault-admin/samples/v4/javascript/backupSelectiveRestore.js
sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupRestoreHelloWorld.ts
sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupSelectiveRestore.ts
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/backupClientModels.ts
sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
sdk/keyvault/keyvault-admin/src/mappings.ts
sdk/keyvault/keyvault-admin/test/public/backupClient.abort.spec.ts
sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts

Besides what Maor did:
- Renamed `beginRestore`'s `blobStorageUri` to `folderUri`.
- Removed `folderName` from `beginRestore`. Now the folder name will be inferred from the `folderUri`.
- Renamed `beginSelectiveRestore`'s `blobStorageUri` to `folderUri`.
- Removed `folderName` from `beginSelectiveRestore`. Now the folder name will be inferred from the `folderUri`.
- Reordered the parameters of `beginSelectiveRestore` to `keyName`, `folderUrl`, `sasToken`, `[options]`.
- Renamed `KeyVaultBackupResult`'s `backupFolderUri` to `folderUri`.

[Key Vault Admin] API Alignment

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

Support fetching the built artifact from CI directly instead of downloading it first. Related to the third item in https://github.com/Azure/azure-sdk-for-js/issues/14234.

[Dev tool] Support artifact URL

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

So we do not get the log of that command in red color which could indicate something is wrong going on.
Related to the first item in https://github.com/Azure/azure-sdk-for-js/issues/14234.

[Dev tool] Hide docker pull output

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

Samples v2 uses a directory structure like this `samples/v<some package version>` instead of the good old `samples`. Furthermore, it is not guaranteed that the package version is the most recent major one because a package author can decide to change it to another number. This PR adds logic to handle both samples v1 and v2 and make sure to use the appropriate corresponding path. If there is more than one samples v2 directory, the command will run the samples in the directory with the largest version number.

[Dev tool] Support samples v2 directory structure in check node versions command

---

sdk/web-pubsub/web-pubsub-express/test/ctor.spec.ts

as in the latest version of node the input url has been removed from the message:
https://github.com/nodejs/node/commit/417c31b69a2ee63649600ece471d9e1a5bba9f55

[web-pubsub][test] verify just the prefix of ERROR_INVALID_URL message

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts
common/tools/dev-tool/src/util/findSamplesDir.ts

renames `findSamplesDir` to `findSamplesRelativeDir` and moves it to its own module so we have a uniform way for samples directory discovery. It also updates the `artifact-path` arg docs to reflect that it can also be a URL to the built artifact.

[Dev tool] Clean doc for artifact-path

---

sdk/communication/communication-sms/package.json
sdk/communication/communication-sms/sample.env
sdk/communication/communication-sms/samples-dev/sendSms.ts
sdk/communication/communication-sms/samples-dev/sendSmsWithOptions.ts
sdk/communication/communication-sms/samples-dev/usingAadAuth.ts
sdk/communication/communication-sms/samples/v1/javascript/README.md
sdk/communication/communication-sms/samples/v1/javascript/package.json
sdk/communication/communication-sms/samples/v1/javascript/sample.env
sdk/communication/communication-sms/samples/v1/javascript/sendSms.js
sdk/communication/communication-sms/samples/v1/javascript/sendSmsWithOptions.js
sdk/communication/communication-sms/samples/v1/javascript/usingAadAuth.js
sdk/communication/communication-sms/samples/v1/typescript/README.md
sdk/communication/communication-sms/samples/v1/typescript/package.json
sdk/communication/communication-sms/samples/v1/typescript/sample.env
sdk/communication/communication-sms/samples/v1/typescript/src/sendSms.ts
sdk/communication/communication-sms/samples/v1/typescript/src/sendSmsWithOptions.ts
sdk/communication/communication-sms/samples/v1/typescript/src/usingAadAuth.ts
sdk/communication/communication-sms/samples/v1/typescript/tsconfig.json

This PR refactors the sms samples and stops skipping them in pipeline runs.

[communication][sms] run sms samples in pipeline

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

This is a copy from .Net's https://github.com/Azure/azure-sdk-for-js/pull/15342
The links use a direct reference to the target URI since that's how we've been doing links these READMEs.

[Key Vault] Update READMEs with links to RBAC

---

eng/pipelines/templates/stages/archetype-sdk-client.yml

This reverts commit 5a3c2d84f275b66f134b3819cda368cc0d6e3b4d.
Azure Pipelines macOS agent capacity seems to be restored now (https://status.dev.azure.com/_event/233282345).

Revert "Temporarily replace macOS CI tests with ubuntu CI tests (#14785)

---

common/tools/add-identity-mgmt-lib.js

The issue appears in the updated readme file here where the `list` operation gained extra arguments even though it should not: https://github.com/Azure/azure-sdk-for-js/pull/15362.

Fix Add Identity script to detect operation arguments

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/auth.ts
sdk/cosmosdb/cosmos/src/utils/checkURL.ts
sdk/cosmosdb/cosmos/test/internal/unit/utils/checkURL.spec.ts

We were passing unsanitized URLs to fetch the AAD credentials for RBAC data plane, like leaving in the :443 port and trailing slashes. This should fix and give the correct endpoint

[Cosmos] Sanitizes AAD dataplane RBAC URL

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/transformations.ts
sdk/keyvault/keyvault-keys/test/internal/transformations.spec.ts

A customer recently found an issue with our output values: https://github.com/Azure/azure-sdk-for-js/issues/15353
Once we reach an exit strategy, we'll need to make a hotfix out of this PR.
A while ago I made a PR showcasing how we could use the spread operator less ([PR link](https://github.com/Azure/azure-sdk-for-js/pull/12697)). That PR got reviewed and approved as usual, but it had some deep issues that didn't become obvious to the reviewer, nor raised any issues during tests. I find that reasonable, but I regret it.
What happened in detail was that, because of:
- The use of "any".
- Not having structural tests.
Because this being an instance of both cases, we couldn't:
- Trust our types.
- Trust our tests.
So, besides solving the underlying issue, we should take this opportunity to …

[Key Vault Keys] Fixed bad references.

---

sdk/communication/communication-network-traversal/CHANGELOG.md

Updating the communication-network-traversal changelog date to reflect Public beta release.

Updating Network Traversal change in CHANGELOG

---

sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts

We always send messages via the 'batch' version of the method now, so the original array-based version with `sendMessages` is no longer used.

[service-bus] Remove dead code in MessageSender.sendMessages

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/test/internal/unit/messageSender.spec.ts

getMaxMessages had an edge case where the link being closed just after open would cause us to access a link that was undefined and throw a non-retryable exception.
This PR fixes that by checking that the link is defined, and throwing a retryable exception if it is not.
Fixes #15398

[service-bus] getMaxMessages needs to retry if link doesn't initialize

---

sdk/core/core-http/src/util/sanitizer.ts
sdk/core/core-http/src/util/utils.ts
sdk/core/core-http/test/sanitizerTests.ts
sdk/core/core-rest-pipeline/src/util/helpers.ts
sdk/core/core-rest-pipeline/src/util/sanitizer.ts
sdk/core/core-rest-pipeline/test/sanitizer.spec.ts

JSON.stringify can't handle recursive data structures, so when we use it internally inside Sanitizer.sanitize, we need to be smart enough to cut not re-visit objects we've already seen.
Fixes #15402

[core] Improve the sanitizer to handle recursive objects

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/samples-dev/recognizePii.ts
sdk/textanalytics/ai-text-analytics/samples/v5/javascript/recognizePii.js
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/recognizePii.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

This change has been proposed by .NET architect and discussed by the TA crew. The motivation is to shorten it a bit.

[Text Analytics] Rename PiiEntityDomainType to PiiEntityDomain

---

sdk/servicebus/service-bus/samples-dev/browseMessages.ts
sdk/servicebus/service-bus/samples-dev/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples-dev/sendMessages.ts
sdk/servicebus/service-bus/samples-dev/session.ts
sdk/servicebus/service-bus/samples/v7/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/v7/javascript/receiveMessagesLoop.js
sdk/servicebus/service-bus/samples/v7/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/v7/javascript/session.js
sdk/servicebus/service-bus/samples/v7/typescript/src/browseMessages.ts
sdk/servicebus/service-bus/samples/v7/typescript/src/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples/v7/typescript/src/sendMessages.ts
sdk/servicebus/service-bus/samples/v7/typescript/src/session.ts

- Show the right way to restart your receiver when using sessions (which
don't do automatic retries like non-sessions).
- Some of the samples printed almost too little console output to indicate what
they were doing or didn't demonstrate the right techniques (asking for multiple
messages at a time, etc..). Those have been updated as well.
Fixes #14531

[service-bus] Updating samples to fix a few issues:

---

eng/pipelines/templates/jobs/live.tests.yml

When testing with multiple clouds, it can be hard to tell from the coverage view which failures come from which cloud and/or job.

Update test results titles to include service directory and cloud names

---

sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/migration-guide.md

In a previous commit (f77c21842c2b8244f76641b454768aa1a3c9f415) we cleaned up some duplicated
samples that were left behind. Unfortunately, we still had a few links pointing to the old samples - mainly
the README and migration guide for secrets.
This PR cleans that up and points to the new sample folder, which should make the [link verification check](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=920933) happy again.

[KeyVault] - Update broken links for Key Vault Secrets

---

sdk/keyvault/keyvault-keys/tests.yml

KeyVault Keys tests have been timing out on Managed HSM. Looking at the runs, it does look like we are _just_ on the edge of timing out but a few recent test additions have put us over the edge.
There are N Key Vault tests + M Managed HSM specific tests, so only the Managed HSM runs started timing out. I think bumping to 90 minutes is a reasonable strategy here as I didn't see any large changes in the trends.

[KeyVault] - Bump Keys timeout to 90 minutes

---

sdk/keyvault/keyvault-admin/recordings/node/keyvaultbackupclient_beginbackup/recording_returns_the_correct_backup_result_when_fails_to_authenticate.js
sdk/keyvault/keyvault-admin/recordings/node/keyvaultbackupclient_beginbackup/recording_throws_when_polling_errors.js
sdk/keyvault/keyvault-admin/recordings/node/keyvaultbackupclient_beginrestore/recording_throws_when_polling_errors.js
sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveKeyRestore/operation.ts
sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts

- Use `error.code` to check if there's an error (not just the presence of error)
- Unpend the Admin LRO tests
- Consistency with other languages
- We used to require using StatusDetails or status because the AAD errors were not populated in the error object, now that this is fixed we can use the error object.
- Even on a successful response `error` will still get sent over the wire, so we need to check the presence of `code` as well. This service-side issue will be fixed, but for now all languages will guard against this.
Fixes #15448

[KeyVault] - Use error object for LRO errors

---

sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_send_multiple_transactions_with_the_same_partition_key.json
sdk/tables/data-tables/recordings/node/batch_operations/recording_should_send_multiple_transactions_with_the_same_partition_key.js
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TablePolicies.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/src/utils/constants.ts
sdk/tables/data-tables/src/utils/internalModels.ts
sdk/tables/data-tables/src/utils/transactionHelpers.ts
sdk/tables/data-tables/test/public/transaction.spec.ts

Fixes #15403
Sending more than one transaction had an unexpected behavior, sending empty transaction bodies after the first request.
This PR refactors the way we build the transaction request so that there is less state to keep track of and make sure we reset the remaining state and pipeline policies before starting to build a new Transaction Request

Refactor SubmitTransaction to fix multiple send issue

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/package.json
sdk/monitor/monitor-query/src/generated/logquery/src/azureLogAnalyticsContext.ts
sdk/monitor/monitor-query/src/generated/metrics/src/monitorManagementClientContext.ts
sdk/monitor/monitor-query/src/generated/metricsdefinitions/src/metricsDefinitionsClientContext.ts
sdk/monitor/monitor-query/src/generated/metricsnamespaces/src/metricsNamespacesClientContext.ts

Normal release updates - changelog date and adjusting package.json metadata so the generated file's user agent version are also updated.

[monitor-query] Prepping monitor-query for first beta release.

---

sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

Here’s a build with this issue: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=925971&view=ms.vss-test-web.build-test-results-tab&runId=19921706&resultId=100040&paneView=debug
There aren’t clear indicators of what could be causing the issue.
~This PR attempts to keep the environment untouched while we run our tests. We were generally doing it, but we forgot to do it for this environment variable referenced in these changes.~
~If this isn’t the fix I would be comfortable skipping this for now.~
I’m skipping this test now.

[Identity] Attempting to fix an issue with CI testing

---

sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
sdk/keyvault/keyvault-admin/src/generated/models/index.ts

- Use a plain enum instead of a const enum
- const enums should not be used as they are removed at compilation. While this works well for TypeScript users it leaves JavaScript users with a type that can be understood by IntelliSense but not actually exist at runtime. 
- Since our guidelines prefer regular enums instead I changed this in the generated code and filed an issue in https://github.com/Azure/autorest.typescript/issues/1013 to discuss longer term changes.

[KeyVault] - Avoid `const enum` for extensible enums

---

common/tools/add-identity-mgmt-lib.js

Fix the capitalization of the word `Node.js` in the script that adds identity language to management-plane readmes.

[Add Identity Script] node.js -> Node.js

---

sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/lro/analyze/operation.ts
sdk/textanalytics/ai-text-analytics/src/lro/analyze/poller.ts
sdk/textanalytics/ai-text-analytics/src/lro/health/operation.ts
sdk/textanalytics/ai-text-analytics/src/lro/health/poller.ts
sdk/textanalytics/ai-text-analytics/src/lro/poller.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

Makes some of the LRO state properties required to exactly follow the swagger.
The only one that is not at the moment is the `expiresOn` one according to the swagger. @suhas92 do you know why it is not required?

[Text Analytics] Makes LROs state properties required

---

eng/tools/dependency-testing/templates/package.json
sdk/core/abort-controller/package.json
sdk/core/logger/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/synapse/synapse-access-control/package.json
sdk/synapse/synapse-artifacts/package.json
sdk/synapse/synapse-managed-private-endpoints/package.json
sdk/synapse/synapse-monitoring/package.json
sdk/synapse/synapse-spark/package.json
sdk/test-utils/perfstress/package.json
sdk/test-utils/test-utils/package.json

The right field to use is `engines` not `engine`. See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines
All of the files updated in this PR except 1 listed both engines and engine

Use engines not engine in package.json files

---

common/tools/dev-tool/src/commands/samples/publish.ts

Fixes #15575
The `dev-tool samples publish` command generates the JS and TS projects based on samples in the samples-dev folder as described in https://github.com/Azure/azure-sdk-for-js/wiki/Samples-v2-Migration-Guide. In the generated package.json files we use the `engine` field instead of `engines` which is what this PR fixes.
See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

Use engines not engine in generated package.json file for samples

---

eng/.docsettings.yml

We expect the readme files in each of the packages to follow a particular template. 
The docsettings.yml file is where we have added exceptions for this rule.
The `omitted_paths` is for those readmes that intentionally do not follow this rule
The `known_content_issues` is for those readmes that we believe should follow the rule and so there is a tracking issue to update it
The `known_presence_issues` is for those readmes that dont exist but should
This PR cleans up this file as follows:
- Add Track 1 packages into the omitted path list. Since these are auto generated, they will not be following the rule
- Add service level readmes into the omitted path list. /sdk/*/README.md
- Use glob patterns when possible
- Sort alphabetically

Clean up entries in docsettings.yml

---

eng/pipelines/templates/jobs/smoke.tests.yml

Smoke test pipeline is using incorrect path to import azmodules script

Update path to Impor-AzModules script

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/src/utils/exports.ts

This updates our deps and fixes a type error in `eslint-plugin-azure-sdk` that was causing it to fail to build with some newer types.

Run rush update --full

---

.scripts/common.ts

Skip all projects in @azure-tests org from gulp pack. These are perf test framework projects for track1 and should not be included in gulp pack

Skip track1 perf projects from gulp pack

---

README.md
SUPPORT.md

This PR updates our support policy regarding dropping support for non LTS versions of Node.js

Add note on dropping support for non LTS versions of Node.js

---

sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/Clients.ts

Fixed bug where ShareFileClient.download may corrupt data when source is changing.

[storage-file-share]Fixed bug where ShareFileClient.download may corrupt data when source is changing.

---

.scripts/common.ts

Fix Azure/azure-sdk-for-js#15436 because it leads to all pipeline runs failed, and it has a bug:
```
.scripts/common.ts(111,9): error TS2532: Object is possibly 'undefined'.
```

fix bug in 15436

---

sdk/search/perf-tests/search-documents/package.json
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts

Today (06/08/2021), We have released [`@azure/search-documents - 11.2.0` ](https://www.npmjs.com/package/@azure/search-documents/v/11.2.0) from the [feature](https://github.com/Azure/azure-sdk-for-js/tree/release/azure-search-documents_11.2.0) branch.
After the release, this PR is to update the version of the SDK (and Changelog) in the master branch. The next release would be `11.3.0-beta.1`.

Update Version in Search Documents SDK

---

sdk/keyvault/keyvault-admin/samples-dev/backupRestoreHelloWorld.ts
sdk/keyvault/keyvault-admin/samples-dev/backupSelectiveKeyRestore.ts
sdk/keyvault/keyvault-admin/samples/v4/javascript/backupRestoreHelloWorld.js
sdk/keyvault/keyvault-admin/samples/v4/javascript/backupSelectiveKeyRestore.js
sdk/keyvault/keyvault-admin/samples/v4/javascript/package.json
sdk/keyvault/keyvault-admin/samples/v4/typescript/package.json
sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupRestoreHelloWorld.ts
sdk/keyvault/keyvault-admin/samples/v4/typescript/src/backupSelectiveKeyRestore.ts

This PR just updates the KeyVault admin samples to provide some context around what is happening, restore the 
console logging of backup / restore results, and provide a helper method to ensure URIs are well-formed.

[KeyVault] - Update KeyVault Admin samples

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-queue/package.json

Remove identity dependencies on packages that don't use identity, upgrade versions for those that use identity
- Upgrade for storage-queue
- Remove for core-amqp, storage-blob-changefeed

Remove or upgrade identity dependencies on packages

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/constants.ts

This release will expose the AMQP body type encoding (value, data or sequence!) to users of the package.

[service-bus] Updating changelog with proper date and features for 7.2.0 GA release

---

eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/platform-matrix.json

As stated in https://github.com/Azure/azure-sdk-for-js/issues/7022#issuecomment-857281424, we are dropping support for Node.js 8 in our JS SDK libraries.
This PR removes v8.x from our build pipeline run matrix.

Remove Node v8 from run matrix

---

sdk/servicebus/service-bus/src/models.ts

Updating doc comment for autoComplete, indicating that it will abandon() if an error is thrown.
The prior text made it sound like it would call completeMessage() no matter what happened, which was confusing.
Fixes #15519

[service-bus] Fix autoCompleteMessages help to indicate that it'll both completeMessage() and abandonMessage()

---

sdk/cosmosdb/cosmos/src/retry/retryUtility.ts

`core-rest-pipeline` has an `ENOTFOUND` message but throws with `REQUEST_SEND_ERROR` code. Fetch throws with `ENOTFOUND` code.

[Cosmos] Adds REQUEST_SEND_ERROR exception to failover codes

---

sdk/tables/data-tables/src/TableTransaction.ts

Adding check to make sure we always have only one forward slash (`/`) added to the end of the URL.

Fixes #15664

---

sdk/servicebus/service-bus/test/internal/atomE2ETests.spec.ts

We had some abandonMessage() calls in atomE2E.ts that were not being await'd on, which meant when they did ultimately fail, it would happen in an unrelated test.
I'm a bit unsure why but it appears that mocha was attributing these failures to these tests, even though they weren't started or a part of them.
As an example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=943479&view=logs&j=07f0c2bc-806a-58d0-ca0d-069f605ef81d&t=fd27c4cf-da6b-5a51-aa3d-cd45c93f6ef8
(there are other failures in that same build that I'm not entirely are are related, but this part is definitely incorrect and can be fixed).

[service-bus] Flaky test fix - un-awaited abandonMessage() calls cause unrelated tests to fail

---

swagger_to_sdk_config.json

v4.7 is the most recent one that generated readmes with [our updated node support policy](https://github.com/Azure/azure-sdk-for-js/blob/master/SUPPORT.md#microsoft-support-policy): https://www.npmjs.com/package/@microsoft.azure/autorest.typescript/v/4.7.0

Bump the code generator version used for management-plane packages

---

sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/test/internal/unit/logsQueryClient.unittest.spec.ts

This PR makes it so you can pass in a custom endpoint and custom scopes for authentication. Without these you can't properly connect to government-based clouds.
Example usage:
```typescript
const dac = new DefaultAzureCredential({
authorityHost: AzureAuthorityHosts.AzureGovernment
});
const client = new LogsQueryClient(dac, {
endpoint: "https://api.loganalytics.us/v1",
scopes: "https://api.loganalytics.us/.default"
});
```
Fixes #15663

[monitor-query] Allowing for passing a custom endpoint and custom authorization scopes.

---

sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts

The Log Analytics service has a bug where it sometimes returns the batch query output encoded twice. 
The issue is still under investigation (https://github.com/Azure/azure-sdk-for-js/issues/15688) but in the meantime this workaround will enable people to use the API, which is critical since we're in preview.
Mitigation for #15688

[monitor-query] Work around the double-JSON encoding bug

---

sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
sdk/keyvault/keyvault-admin/src/lro/backup/poller.ts
sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/restore/poller.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveKeyRestore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveKeyRestore/poller.ts
sdk/keyvault/keyvault-certificates/src/lro/create/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/create/poller.ts
sdk/keyvault/keyvault-certificates/src/lro/delete/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/delete/poller.ts
sdk/keyvault/keyvault-certificates/src/lro/operation/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/operation/poller.ts
sdk/keyvault/keyvault-certificates/src/lro/recover/operation.ts
sdk/keyvault/keyvault-certificates/src/lro/recover/poller.ts
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/delete/poller.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/poller.ts
sdk/keyvault/keyvault-secrets/samples-dev/backupAndRestore.ts
sdk/keyvault/keyvault-secrets/samples-dev/deleteAndRecover.ts
sdk/keyvault/keyvault-secrets/samples/v4/javascript/backupAndRestore.js
sdk/keyvault/keyvault-secrets/samples/v4/javascript/deleteAndRecover.js
sdk/keyvault/keyvault-secrets/samples/v4/javascript/package.json
sdk/keyvault/keyvault-secrets/samples/v4/typescript/package.json
sdk/keyvault/keyvault-secrets/samples/v4/typescript/src/backupAndRestore.ts
sdk/keyvault/keyvault-secrets/samples/v4/typescript/src/deleteAndRecover.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/poller.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/poller.ts

- Remove unnecessary `export` from KV samples
- Fix circular dependency in KV pollers
I noticed today that the keyvault-secrets samples were failing to run due to 
```
SyntaxError: Unexpected token 'export'
```
There's an existing bug against dev-tool (#15724) which when fixed will address this, but in order to make sure
our samples are working it's perfectly fine not to export these functions.
Fixing the circular dependencies is a good thing to do before we go out.

[KeyVault] - Fix JavaScript samples and poller circular references

---

sdk/attestation/attestation/api-extractor.json
sdk/attestation/attestation/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/15727. The declaration file should be created under `types/latest`.

[Attestation] Fix types path

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/proxyAgent.ts
sdk/core/core-http/test/proxyAgent.node.ts
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/proxyPolicy.ts
sdk/core/core-rest-pipeline/test/node/proxyPolicy.spec.ts

It turns out that in some enterprise customer the proxy auth settings include a
username, but not a password: https://github.com/microsoft/AzureStorageExplorer/issues/4430
This change allows password-less auth settings to be passed to the underlying agent.
It's unclear whether it's a real scenario when a proxy auth has a password, but not username so 
this PR doesn't consider this scenario.
Resolves #15720.

[core] Allow password-less proxySettings

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-admin/swagger/README.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/constants.ts
sdk/keyvault/keyvault-keys/src/cryptography/remoteCryptographyProvider.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/swagger/README.md

-Ensure all imports to keyvault-common go through the src directory
We noticed that rollup failed to find imports from keyvault common when we updated our test dependencies to use the published KV Keys version. 
This is not an issue when we were using the version of KV Keys on master because of the way rush would use symlinks; however,
this is an issue in a certain edge case and therefore should be fixed,
Longer term we'd like to run at least one of our packages against the published version to find issues like this sooner.

[KeyVault] - Fix incorrect paths to keyvault-common

---

sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/samples-dev/logsQuery.ts
sdk/monitor/monitor-query/samples-dev/logsQueryBatch.ts
sdk/monitor/monitor-query/samples/v1/javascript/logsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryBatch.js
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQuery.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryBatch.ts

Some tidying of the readme and samples:
- Fix all the documentation links to point to docs.microsoft.com, now that it's active.
- Fixing the .ts samples so they don't use "advanced" JS features (currently we're targeting node 14 when doing transpilation in devtool).

[monitor-query] Fixing issues in the readme and samples

---

sdk/attestation/attestation/CHANGELOG.md

After https://github.com/Azure/azure-sdk-for-js/issues/15727 has been fixed.
If you think there is no need for this release, feel free to close the PR.
More info about the problem: The typescript compiler will not be able to find the type definitions. See this doc for the resolution algorithm: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson
In the currently released package, the `types` key in package.json points to types/latest/attestation.d.ts but the file actually exists in types/attestation.d.ts.

[Attestation] Prepare for release v1.0.0-beta.4

---

sdk/iot/iot-modelsrepository/package.json
sdk/iot/iot-modelsrepository/src/modelsRepositoryClient.ts
sdk/iot/iot-modelsrepository/src/modelsRepositoryServiceClient.ts
sdk/iot/iot-modelsrepository/src/utils/constants.ts
sdk/iot/iot-modelsrepository/test/node/unit/constants.spec.ts

Per convos with @ramya-rao-a, following the style of data-tables to have the SDK_VERSION inserted in the package.json. I am not positive but I assume this somehow ensures the constants.ts file is also updated during version bumps.

Add SDK_VERSION to package.json 

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

We removed 8.x from the test matrix in an earlier PR. As a result, cosmos tests
have not been running since then due to the 8.x version under the MatrixFilters.
This change enables running tests on our minimum supported version of 10.x.

[cosmos][test] set NodeTestVersion to 10.x

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/urlHelpers.ts
sdk/core/core-client/test/urlHelpers.spec.ts

This PR Fixes the issue reported in Issue: https://github.com/Azure/autorest.typescript/issues/1035
What is the problem?
In an LRO Operation, first the URL is set as `https://management.azure.com/subscriptions/subscription-id/resourceGroups/rg2/providers/Microsoft.Network/virtualNetworks/samplename?api-version=2020-08-01`. Now, during the polling operation, the same `api-version=2020-08-01` is being appended to this URL. That results in the URL of `https://management.azure.com/subscriptions/subscription-id/resourceGroups/rg2/providers/Microsoft.Network/virtualNetworks/samplename?api-version=2020-08-01&api-version=2&api-version=0&api-version=2&api-version=0&api-version=-&api-version=0&api-version=8&api-version=-&api-version=0&api-version=1` which is causing issues. 
Now, while I was trying …

Append the Query Parameters Correctly

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md

- Added dates to changelog to make sure they are sorted correctly.

Fix up changelogs for Storage packages

---

eng/.docsettings.yml
sdk/keyvault/keyvault-common/README.md

This PR adds a very basic README to the keyvault-common package.
Since this package isn't published, isn't meant for consumption by users or even other packages (besides Key Vault), and is relatively small I went _really_ basic here - enough to satisfy the dotsettings requirements and enough to get from it to a Key Vault library.
Resolves #15587

[KeyVault] - Add README for keyvault-common

---

sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_with_specific_permissions.js
sdk/identity/identity/test/public/node/deviceCodeCredential.spec.ts

Specifying permissions has always worked on Identity. However, it may be confusing because it’s not allowed as part of the client credential flows. This isn’t up to us, really. I’m adding this test to make sure we have some use case that can help us remember when this will work and when it may not work in the future, in case we forget.
Closes #15230

[Identity] Adding one test to confirm that specifying permissions works

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

As part of #14809 we added documentation and a sample demonstrating how to use XML consuming client libraries in web workers. 
Since web workers do not have access to the DOM APIs certain polyfills are necessary to make these libraries work.
This change just adds some of that information to the various storage libraries that support browsers and provides a link to the sample.
Resolves #15608

[Storage] - Add information about web worker compatibility

---

eng/pipelines/mgmt-ci.yml
eng/pipelines/templates/jobs/ci.yml
sdk/storage/test-resources-post.ps1
sdk/tables/test-resources-post.ps1

Change remaining default branch name

Change default branch name to main

---

sdk/keyvault/keyvault-keys/recordings/browsers/challenge_based_authentication_tests/recording_authentication_should_work_for_parallel_requests.json
sdk/keyvault/keyvault-keys/recordings/browsers/challenge_based_authentication_tests/recording_once_authenticated_new_requests_should_not_authenticate_again.json
sdk/keyvault/keyvault-keys/recordings/browsers/challenge_based_authentication_tests_parsewwwauthenticate_tests/recording_should_skip_unexpected_properties_on_the_wwwauthenticate_header.json
sdk/keyvault/keyvault-keys/recordings/browsers/challenge_based_authentication_tests_parsewwwauthenticate_tests/recording_should_work_for_known_shapes_of_the_wwwauthenticate_header.json
sdk/keyvault/keyvault-keys/recordings/node/challenge_based_authentication_tests/recording_authentication_should_work_for_parallel_requests.js
sdk/keyvault/keyvault-keys/recordings/node/challenge_based_authentication_tests/recording_once_authenticated_new_requests_should_not_authenticate_again.js
sdk/keyvault/keyvault-keys/test/internal/challengeBasedAuthenticationPolicy.spec.ts
sdk/keyvault/test-resources-post.ps1
sdk/keyvault/test-resources.json

This PR makes three changes to our deployment template:
- Add networkAcls to the Managed HSM properties
- Remove the 60 second sleep after activation
- Speed up challenge auth tests for KV Keys by using methods that don't require creating and deleting keys.
The first is now needed, and without it deployment will fail.
The second is no longer needed, since it looks like the az cli appropriately waits before coming back.
Finally, the third is something I noticed - there's no reason to create and purge keys which takes a long time in order to test CAE.

[KeyVault] - Add networkAcls to MHSM ARM template

---

sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/export/trace.test.ts

Adding support for 307 response and try to send telemetry immediately instead of putting it in disk when redirect is triggered

[AzureMonitorExporter] Adding support for temporary redirect

---

sdk/core/core-lro/package.json
sdk/core/core-lro/rollup.base.config.js

This dependency was only needed for tests and was causing trouble for corev2 packages who would wind up with a copy of `core-http` if they used `core-lro`
Fixes #15880

[core] Remove `core-lro` runtime dependency on `core-http`

---

sdk/identity/identity/README.md

Moved Extensions title to be h2, and fixed one link that had a wrong markdown syntax.

[Identity] README.md: Bigger title for Extensions and a markdown fix

---

sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__featureflag_featureflag_configuration_setting/recording_can_add_and_get_featureflag.js
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__featureflag_featureflag_configuration_setting/recording_can_add_and_update_featureflag.js
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__featureflag_featureflag_configuration_setting/recording_can_add_list_and_update_multiple_featureflags.js
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__featureflag_serializeasconfigurationsettingparam/recording_unexpected_value__as_feature_flag_value.js
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__featureflag_serializeasconfigurationsettingparam/recording_unexpected_value_hello_world_as_feature_flag_value.js
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/src/featureFlag.ts
sdk/appconfiguration/app-configuration/src/internal/jsonModels.ts
sdk/appconfiguration/app-configuration/test/public/featureFlag.spec.ts

[App Config] Add display_name to FeatureFlag

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-tracing/CHANGELOG.md

I forgot the changelogs. I always forget the changelogs 🤷

[core] - added changelog entries for recent changes

---

eng/pipelines/aggregate-reports.yml

automatic rush update should not run against PR

Skip rush update when running using pull request

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/package.json

This version unpins the `keytar` dependency, resolving build issues for some developers, and allowing keytar 7.7.0 (which uses NAPI, reducing prebuild complexity).

Move to @azure/msal-node-extensions 1.0.0-alpha.7

---

common/tools/eslint-plugin-azure-sdk/ci.yml
eng/pipelines/docindex.yml
eng/pipelines/mgmt-ci.yml
eng/pipelines/mgmt-pr.yml
eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/archetype-js-release.yml
eng/pipelines/templates/stages/platform-matrix.json
eng/pipelines/templates/variables/globals.yml

Update to
- MMSUbuntu20.04
- Ubuntu 20.04
- ubuntu-20.04

Update ubuntu VM image

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/stages/archetype-sdk-tests.yml

The live test timeout is currently set to infinite. I think that with our prior use of the hosted agents, this ended up defaulting to the hosted agent timeout. Since we're on self-hosted agents now, there is no timeout, and occasionally we end up with zombie jobs that we would rather time out.

Default live test timeout to 60 minutes

---

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts

NodeJS does not support directly passing typed arrays or ArrayBuffers to `http.ClientRequest` streams. This means we must correctly wrap these types in a `Buffer` for them to be serialized correctly.

[core-rest-pipeline] Fix handling of typed arrays in request bodies

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/linkEntity.ts
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/internal/unit/linkentity.unittest.spec.ts

Today we cache any opened links in the connectionContext. These links should be removed when the link itself is closed but, due to a mismatch in the values, we weren't. 
I've fixed this by just making an abstract method in LinkEntity (the base for all the link types) and just having each link properly remove itself from the cache.
Fixes #15890

[service-bus] Fixing issue where links were not removed from our internal cache

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

- Version bump for some storage packages.
- This is required due to an issue with the automation.

Bump up version for storage packages

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/tables/data-tables/src/utils/computeHMACSHA256.browser.ts
sdk/tables/data-tables/src/utils/isCosmosEndpoint.ts

Fixes #15921 
There were 2 issues related to browsers:
1. In one of the util files we are importing "url" instead of the util "./url" which causes URL not to be present in browsers.
2. Missing browser mapping for  `computeHMACSHA256`. Tables don't support NamedKey authentication on browsers for security reasons (risky to have the keys in the browser).
* Added a shim function that throws if it is attempted to be used in browser. All entry points to this function are already throwing
* Note: I looked into using `@azure/core-crypto` however I wasn't able to use it because it exposes an async function and the public API that consumes this is synchronous 😢

[Tables] Add missing browser mappings

---

dataplane.code-workspace

This greatly improved my first open experience on my laptop. The only tradeoff is `node_modules` folders won't appear in the file tree of VS Code, but I think this is a pretty uncommon place to browse into manually.

Tweak workspace settings for VS Code startup perf

---

sdk/containerregistry/container-registry/README.md
sdk/containerregistry/container-registry/samples-dev/deleteImages.ts
sdk/containerregistry/container-registry/samples/v1/javascript/deleteImages.js
sdk/containerregistry/container-registry/samples/v1/typescript/src/deleteImages.ts

to delete tags before deleting the image as this is the recommended best
practice for the service.
Part of #15792

[ContainerRegistry] Update delete image sample

---

sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/public/node/clientSecretCredential.spec.ts

Test improvements on Identity. Mostly properly using Sinon timers and avoiding to test unnecessary stuff. Details in comments.

[Identity] Test improvements

---

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/identity/identity/test/internal/node/interactiveBrowserCredential.spec.ts
sdk/test-utils/perfstress/src/policy.ts

As part of #7022, we will be moving the version of `@types/node` from 8 to 12
This PR has the changes required to fix the build errors that occurred when trying out this change
- The [Agent](https://nodejs.org/docs/latest-v12.x/api/http.html#http_class_http_agent) class in Node.js 12 has an extra property `maxTotalSockets`. The docs say there is a default value for this, but it it is still marked as a mandatory property in the types. We use our own interface for this class for the purposes of user providing their own custom agent. Am casting it in this PR to the expected type. If anyone has better ideas here, am all ears :)
- `global.URL` is not a thing as per the types for Node.js 12. We needed this to support Node.js 8
- Fixing the types for `port` in the parsed url
The actual move to …

Prepare to move to @types/node v12

---

sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts

remove _response from the returned response types

remove _response from response types

---

sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-common/src/BufferScheduler.ts
sdk/storage/storage-file-datalake/src/utils/BufferScheduler.ts
sdk/storage/storage-file-datalake/src/utils/utils.node.ts
sdk/storage/storage-file-share/src/utils/BufferScheduler.ts
sdk/storage/storage-file-share/src/utils/utils.node.ts

As part of #7022, we will be moving the version of `@types/node` from 8 to 12
This PR has the changes required to fix the build errors that occurred in the Storage packages when trying out this change.
The net changes are:
- Use BufferEncoding in the storage packages as the `encoding` in `Buffer.from(string, encoding)` overload is not a string, but a union of string literals called `BufferEncoding` in Node.js 12 & above
- The promisfied `fs.stat()` returns `Promise<unknown>` for non node case. Updated to ignore the case when isNode is false as the entire file is only used in node due to there being a separate utils file for the browser

Prepare Storage packages to move to @types/node v12 

---

eng/tools/rush-runner.js

Change to include track2 management package in rush runner script.

Support track2 management packages

---

sdk/core/core-client-paging-rest/package.json

This PR updates the newly added `@azure-rest/core-client-paging` package to use the same version of `@azure/core-rest-pipeline` that the other packages use.
We recently GA'd (on main, not released yet) version 1.1.0 of `@azure/core-rest-pipeline` and want to keep everyone on the latest version.

[core-rest] - Update core-client-paging-rest to use the latest core-rest-pipeline

---

sdk/appconfiguration/perf-tests/app-configuration/test/listSettings.spec.ts

Follow up for #16046 to fix the resulting linter errors

Fix linter errors in app config perf tests

---

sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/dataFeed.ts
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/dataSourceCredential.ts
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/javascript/README.md
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/README.md
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/dataFeed.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/dataSourceCredential.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts

- Removing the redundant response types

update the redundant responses

---

sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts

While we stopped using node-fetch on core-rest-pipeline, core-http does use it. Node fetch takes above 2 seconds to begin sending network requests in some environments. We’re able to reproduce this issue in Kubernetes pods, but it could be present elsewhere.
This PR increases the timeout to 3 seconds.
I believe this should be ok as a temporary solution, since in many cases, we will get a response (any response) before that time.
For Identity. we should be able to solve this as soon as we move Identity to core-rest-pipeline: https://github.com/Azure/azure-sdk-for-js/issues/15595 We’re planning to do this during July. However, that won’t solve the issue in core-http.
This issue is related to: https://github.com/Azure/azure-sdk-for-js/issues/15935
It won’t fix …

[Identity] node-fetch takes above 2 seconds to send the request on some environments

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

This PR adds support for Bridge to Kubernetes to ManagedIdentityCredential.
Based on: https://github.com/Azure/azure-sdk-for-net/pull/21942
Fixes #15799

[Identity] Add support for Bridge to Kubernetes to ManagedIdentityCredential

---

sdk/synapse/synapse-access-control/rollup.config.js
sdk/synapse/synapse-managed-private-endpoints/rollup.config.js
sdk/synapse/synapse-monitoring/rollup.config.js
sdk/synapse/synapse-spark/rollup.config.js

- Adds warning filter to ignore known rollup warnings that are safe to ignore
- Ignore `this has been rewritten to undefined` in synapse
- Ignore circular dependencies in synapse
These are both known warnings, are safe to ignore, and add noise to the build output unnecessarily. 
The first is totally safe to ignore:
```
var __spreadArray = (this && this.__spreadArray) || function (to, from) {
```
Is emitted from TypeScript in the OTel ESM and is safe to use.
The second is a known issue in OTel 1.0.0 that is not harmful at runtime.

[synapse] - Ignore known rollup warnings

---

CONTRIBUTING.md

The watchful eyes of @vishnureddy17 found that we still have reference to Node.js 8 in our Contributing Guide!!
This PR fixes that.
Related to #7022

Update contributing guide to reflect Node.js support

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/src/generated/logquery/src/azureLogAnalyticsContext.ts
sdk/monitor/monitor-query/src/generated/metrics/src/monitorManagementClientContext.ts

Updating changelog with date and feature added and running PrepareRelease.

[monitor-query] Updating changelog with date and feature added

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json

See #16094 for details. This PR just updates core-client to 1.2.1 so I can release it

update core-client version to 1.2.1

---

sdk/core/core-http/CHANGELOG.md

Remove the empty section since it prevents the release pipeline from succeeding

fix core-http changelog

---

eng/pipelines/mgmt-ci.yml
eng/pipelines/mgmt-pr.yml

In the period of track2 sdk preview, we are going to use branch `feature/v4` to continue the release of track1 sdk.
Besides this PR, I will also change the the [release pipeline](https://dev.azure.com/azure-sdk/internal/_release?_a=releases&view=mine&definitionId=42) to trigger in branch `feature/v4`

update pipeline to releae/track1

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/tools/versioning/set-dev.js

Added alpha in file name filtering for dev version

Ensure word alpha is present in dev build

---

sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_analyze/recording_single_pii_entities_recognition_action_with_categories_filtered.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_lros_analyze/recording_single_pii_entities_recognition_action_with_categories_filtered.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_analyze/recording_single_pii_entities_recognition_action_with_categories_filtered.js
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_lros_analyze/recording_single_pii_entities_recognition_action_with_categories_filtered.js
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/src/util.ts
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

And fixing a bug along the way! It turned out `categoriesFilter` was not being renamed to `piiCategories` that the service expects.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/15615.

[Text Analytics] Add test for categories filter

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/13792. Very happy to see this out and finish this milestone!

[Text Analytics] Update CHANGELOG with release date

---

eng/pipelines/templates/steps/build.yml
sdk/core/core-client-paging-rest/package.json

Update sdk-type for @azure-rest/core-client-paging to client. This is currently blocking alpha releases for core packages.

Update sdk-type for core-client-paging

---

sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
sdk/metricsadvisor/ai-metrics-advisor/README.md
sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/hooks.ts
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/javascript/hooks.js
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/javascript/quickstart.js
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/hooks.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/datafeed.spec.ts

rename adminEmails to admins
rename viewerEmails to viewers 
Since these represent UUId too not just email addresses
- admins in NotificationHook is not readonly anymore

rename adminEmails and viewerEmails

---

sdk/metricsadvisor/ai-metrics-advisor/README.md
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts

The `dataSourceParameter` property has been flattened in latest Api.
Fixes #16105

[MetricsAdvisor] Fix readme data feed creation example

---

sdk/template/template/api-extractor.json
sdk/template/template/package.json

Attempt to fix an issue uncovered in the docs build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=229991&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=525
Given that farther down in the file is a line: 
```
"build:types": "downlevel-dts types/latest types/3.1",
```
I'm not sure if this change is complete.

Fix path for template types in package.json

---

sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.json
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.js
sdk/communication/communication-network-traversal/test/public/utils/recordedClient.ts
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__get_phone_number_aad/recording_can_get_a_purchased_phone_number.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__get_phone_number_aad/recording_errors_if_phone_number_not_found.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lists_aad/recording_can_list_all_purchased_phone_numbers.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lro__purchase_and_release_aad/recording_can_purchase_and_release_a_phone_number.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lro__search_aad/recording_can_search_for_1_available_phone_number_by_default.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lro__search_aad/recording_throws_on_invalid_search_request.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lro__update_aad/recording_can_update_a_phone_numbers_capabilities.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__lro__update_aad/recording_update_throws_when_phone_number_isnt_owned.json
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__get_phone_number_aad/recording_can_get_a_purchased_phone_number.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__get_phone_number_aad/recording_errors_if_phone_number_not_found.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lists_aad/recording_can_list_all_purchased_phone_numbers.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lro__purchase_and_release_aad/recording_can_purchase_and_release_a_phone_number.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lro__search_aad/recording_can_search_for_1_available_phone_number_by_default.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lro__search_aad/recording_throws_on_invalid_search_request.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lro__update_aad/recording_can_update_a_phone_numbers_capabilities.js
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__lro__update_aad/recording_update_throws_when_phone_number_isnt_owned.js
sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts

So that we can suppress CredScan errors using one common value from eng/CredScanSuppression.json.
Similar to PR #15591 but for different libraries.

[communication][test] Update client secret replacement to common one

---

sdk/appconfiguration/app-configuration/test/internal/node/throttlingRetryPolicy.spec.ts
sdk/appconfiguration/app-configuration/test/internal/throttlingRetryPolicyTests.spec.ts

This is meant to unblock AppConfig GA release.
I can port to a browser/node test after the release https://github.com/Azure/azure-sdk-for-js/issues/16230
Fixes https://github.com/Azure/azure-sdk-for-js/issues/16231

[App Config] Put node test in a node only file

---

common/tools/dev-tool/src/commands/samples/publish.ts

Needed to allow the dev-tool to fix https://github.com/Azure/azure-sdk-for-js/issues/15666.
This change updates the `dev-tool samples publish` command so that it pulls in any `@types/*` packages that are in the SDK's package.json that are associated with a runtime package.
__service-bus/package.json__
```json
{
"dependencies": {
"@azure/abort-controller": "^1.0.0",
"@azure/core-amqp": "^3.0.0",
"@azure/core-asynciterator-polyfill": "^1.0.0",
"@azure/core-http": "^2.0.0",
"@azure/core-tracing": "1.0.0-preview.12",
"@azure/core-paging": "^1.1.1",
"@azure/core-auth": "^1.3.0",
"@azure/logger": "^1.0.0",
"@types/is-buffer": "^2.0.0",
"@types/long": "^4.0.0",
"buffer": "^5.2.1",
"is-buffer": "^2.0.3",
"jssha": "^3.1.0",
"long": "^4.0.0",
"process": "^0.11.10",
"tslib": "^2.2.0", …
```

[dev-tool] update samples publish to populate @types/* devDeps

---

sdk/servicebus/service-bus/samples/v7/javascript/README.md
sdk/servicebus/service-bus/samples/v7/javascript/package.json
sdk/servicebus/service-bus/samples/v7/typescript/README.md
sdk/servicebus/service-bus/samples/v7/typescript/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/15666
It also turns out the samples depended on the `next` tag for service-bus, which is no longer published on NPM, so this update fixes that issue by depending on the `latest` tag.

[service-bus] add @types/ws to TypeScript samples package.json

---

sdk/quantum/quantum-jobs/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-file-datalake/package.json

We recently discovered an issue caused by bumping core-http by a major version (#15925) where if a transitive dependency
is still allowing an older version we would end up with two versions of core-http / core-lro.
This is a problem for two reasons:
- bundle size
- incompatibility of enums between two versions
This was discovered via failed nightly tests and while some of this was fixed by #16180, we still need to audit all the packages
and ensure that:
For every package that moved to core-http@2.0.0, all other dependencies of that package are pinned to a min-version that also
uses core-http@2.0.0
Luckily that is a very small number of packages - mainly communication (fixed) and storage (this PR)

[storage] - bump minimum versions of packages that depend on storage-blob

---

.github/CODEOWNERS

Reason: The ACS SDKs (including Identity) are being handed over to the respective service teams.

Updating CODEOWNERS for ACS Identity

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/generated/data/models/index.ts
sdk/search/search-documents/src/generated/data/models/mappers.ts
sdk/search/search-documents/src/generated/data/models/parameters.ts
sdk/search/search-documents/src/generated/data/operations/documents.ts
sdk/search/search-documents/src/generated/data/searchClient.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/models/index.ts
sdk/search/search-documents/src/generated/service/models/mappers.ts
sdk/search/search-documents/src/generated/service/searchServiceClient.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/indexModels.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/swagger/Data.md
sdk/search/search-documents/swagger/Service.md

This PR is for the July release of the search-documents SDK. Basically, this PR does 2 things:
1. Regenerate SDK based on latest swaggers (and update the custom layer as required)
2. Add `TokenCredential` to the constructor. 
Updating the SDK to latest version of generator has been moved to next release. 
@xirzec Please review and approve the PR.

July Release Search SDK Code Changes

---

common/config/rush/common-versions.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json

- Updates @azure/eventhubs-checkpoint-blobstore min version to the latest @azure/eventhubs 
This resolves the build error when set-dev-version is run, ensuring that the @azure/core-tracing versions are compatible.

[eventhubs] - Update checkpointstore to latest version of event-hubs

---

sdk/keyvault/keyvault-keys/CHANGELOG.md

Update the changelog to reflect that the signData and verifyData fix was backported into 4.2

[KeyVault] - Update changelog after 4.2.2

---

sdk/metricsadvisor/ai-metrics-advisor/samples-dev/detectionConfig.ts
sdk/metricsadvisor/ai-metrics-advisor/samples-dev/seriesData.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/javascript/detectionConfig.js
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/javascript/seriesData.js
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/detectionConfig.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/v1/typescript/src/seriesData.ts

- detectionConfig
RestError: Invalid parameter. suppress number should be less than or equal to 14.
- `?.` not supported in NodeJS v12
Fixes #16234
Fixes #16105

[MetricsAdvisor][Sample] fix sample runtime errors

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/scripts/Language-Settings.ps1

A couple packages have been failing in Docs CI since their release. This is a first cut at creating an exclusion list pattern for JS and other docs onboarding business logic. 
This version excludes packages by name and doesn't have other configuration for package exclusion (e.g. version exclusion or version pinning).

JS Package Exclusions

---

sdk/formrecognizer/ai-form-recognizer/src/azureKeyCredentialPolicy.ts
sdk/formrecognizer/ai-form-recognizer/src/constants.ts
sdk/formrecognizer/ai-form-recognizer/src/formTrainingClient.ts
sdk/formrecognizer/ai-form-recognizer/src/internalModels.ts
sdk/formrecognizer/ai-form-recognizer/src/logger.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/contentPoller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/recognitionPoller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/copy/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/train/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/tracing.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/src/utils/utils.node.ts

[ai-form-recognizer] Added @internal to documentation strings as appropriate.

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/README.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/public/node/authorizationCodeCredential.spec.ts
sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/public/node/environmentCredential.spec.ts

Includes an update of core-http on Identity to v2. I will update this after core-http is released with the 305 fix.
After this is merged, I will rename the base branch `hotfix/identity_1.3.1` to `hotfix/identity_1.4.0` before triggering the release build.

[Identity] [Hotfix] 1.4.0 increased the IMDS MSI default timeout

---

common/config/rush/common-versions.json
sdk/cosmosdb/cosmos/package.json
sdk/remoterendering/mixed-reality-remote-rendering/package.json

In #15923, we updated the version of core-rest-pipeline in the dependencies of all packages except cosmos which had a recurring build/test failure which has since been fixed.
This PR updates the version of core-rest-pipeline in cosmosdb package as well as the new remoterendering package.
Resolves #15928

Remove ^1.0.3 from common-versions for core-rest-pipeline

---

sdk/cosmosdb/cosmos/README.md

As recommended in MicrosoftDocs/azure-docs-sdk-node#1255

Update Cosmos Readme

---

sdk/identity/identity/CHANGELOG.md

Just released: https://www.npmjs.com/package/@azure/identity/v/1.4.0

[Identity] Updated the main changelog after releasing 1.4.0

---

.scripts/automation_generate.sh
.scripts/automation_init.sh
swagger_to_sdk_config.json

This PR is used to integrate track2 js mgmt codegen to swagger pipeline. After it's merged, I will create a PR to make changes in swagger repository.
When codegen is in peview, we specify the verison of codegen.
When codegen is GA, we will always use the latest codegen.

support track2 codegen in swagger pipeline

---

sdk/digitaltwins/digital-twins-core/review/digital-twins-core.api.md
sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts

Unfortunately, there is a typo in a method name that is exposed to the user. This PR attempts to correct this. Let me know if there's a better way to address this.

[digital-twins-core] address typo in method name

---

common/config/rush/pnpm-lock.yaml

When [updating the `@azure/identity` dependency for digital twins core](https://github.com/Azure/azure-sdk-for-js/pull/16106), I did not update the `pnpm-lock.yaml`. This PR fixes that.

update pnpm-lock.yaml due to dependency change for digital twins core

---

sdk/containerregistry/container-registry/karma.conf.js
sdk/containerregistry/container-registry/sample.env
sdk/containerregistry/container-registry/samples/v1/javascript/sample.env
sdk/containerregistry/container-registry/samples/v1/typescript/sample.env
sdk/containerregistry/container-registry/test/utils/utils.ts
sdk/containerregistry/container-registry/tests.yml
sdk/containerregistry/test-resources-post.ps1
sdk/containerregistry/test-resources.json
sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/index.ts
sdk/test-utils/recorder/src/utils/msalAuth.node.ts

- Update test resource deployment
- Update test utils to pass authorityHost and authenticationScope
- Update recorder to allow handling different tenant id than default AZURE_TENANT_ID

[ContainerRegistry][Test] Add weekly tests for USGov Cloud and China Cloud

---

sdk/identity/identity/src/client/identityClient.ts

The lack of the reference makes this property a bit confusing. The reference does make it clearer.

[Identity] Referencing the type related to authorityHost

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/utils.ts
sdk/core/core-client/test/serviceClient.spec.ts
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/nodeHttpClient.ts

This is to fix the issue reported in https://github.com/Azure/autorest.typescript/issues/1037. Originally, it was returning the correct values. But, with PR https://github.com/Azure/azure-sdk-for-js/pull/14366, this was changed to not return the `body` value. 
With this PR, I am bringing it back.
@deyaaeldeen @xirzec Please review and approve.

Code to fix return value for HEAD HttpMethod

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

Fix failures in running storage samples
It reports following error in storage pipeline when running samples:
`
Trace: [Internal Error] Error: ENOENT: no such file or directory, stat 'D:\a\_work\1\s\sdk\storage\storage-file-datalake\dist-samples\typescript\dist\storage-file-datalake\dist-samples\typescript\src'
at D:\a\_work\1\s\common\tools\dev-tool\src\index.ts:10:11
The script failed with exit code 1
##[error]Cmd.exe exited with code '1'.
`
This PR is to fix the error.

Fix failures in running storage samples

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/README.md
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/constants.ts
sdk/eventgrid/eventgrid/src/eventGridClient.ts

This change adds support for using Azure AD to authenticate when send
events using `EventGridPublisherClient`.

[EventGrid] Support TokenCredential

---

sdk/test-utils/perfstress/CHANGELOG.md
sdk/test-utils/perfstress/src/options.ts
sdk/test-utils/perfstress/src/program.ts
sdk/test-utils/perfstress/src/tests.ts
sdk/test-utils/perfstress/test/exception.spec.ts
sdk/test-utils/perfstress/test/noop.spec.ts
sdk/test-utils/perfstress/test/options.spec.ts
sdk/test-utils/perfstress/test/setupCleanup.spec.ts

##Issue  https://github.com/Azure/azure-sdk-for-js/issues/13209
As we only ever offer async methods for our APIs through the SDKs unlike other languages, it makes sense to remove the "run" method and related code.
Reference - https://github.com/Azure/azure-sdk-for-js/pull/13125#discussion_r554159841

[Perf framework] Remove run method - cleaning up

---

sdk/eventhub/event-hubs/src/diagnostics/instrumentEventData.ts

The live tests for event hubs currently have 3 test failures due to some changes introduced in core-tracing preview 13. The changes to core-tracing cause EventData to be instrumented (via Diagnostic-Id) with invalid span context data.
This change adds a check to ensure the span context is valid before instrumenting the EventData to be sent to the service.
Note: I didn't add a changelog entry because from a user's point of view, nothing has changed, since this issue did not exist in the previously released version of the event-hubs package.

[event-hubs] prevent invalid spans from instrumenting EventData

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/documents/ConnectionPolicy.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

By specifying the `retryOptions` defaults specifically in the defaultConnectionPolicy to comply with types in the 3.12.0 release, we erroneously changed the default fixedRetry interval to 100ms. This returns to let our retryPolicy handle 429 throttling retries on its own

[Cosmos] Return default fixedRetry interval to 0

---

eng/scripts/Language-Settings.ps1

Daily docs will fail in cases where packages do not have a `dev` tagged version in NPM. This checks with NPM for the version and uses that version directly instead of the tag. This has the [added benefit of showing the published dev version in the README content](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/daily/2021-07-20/docs-ref-services/preview/storage-blob-readme.md). 
docindex pipeline running and succeeding -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1006534&view=results 
Outputs from docindex in daily branch -- https://github.com/MicrosoftDocs/azure-docs-sdk-node/commit/1a5568f794f29beda8028a02511d8c115c5ffe95 ... Note that dev versions are only expanded for the `storage` service which had its daily pipeline executed against this branch. other …

Daily docs exclude packages which have no 'dev' tags

---

sdk/identity/identity/package.json

Drop the word "service" from the name

replace legacy MSI name in package.json keywords

---

common/config/rush/pnpm-lock.yaml
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-datalake/package.json
sdk/storage/perf-tests/storage-file-share/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md

Now that `@opentelemetry/api` has gone GA, we have more users attempting to try it. The latest stable releases for storage packages still use an older version of `@azure/core-tracing` that depends on 1.0.0-rc version of `@opentelemetry/api`. This results in problems like the one seen in #16447
Moreover, our recent move to use 2.0.0 of `@azure/core-http` in `@azure/identity` results in different versions of core-http being used in cases like #16389 and failing builds even when the user does not use tracing.
We were hoping that the next storage updates would resolve this as we have already done the work to move to the latest tracing packages in the main branch, but unfortunately the storage packages in the main branch are looking at a beta release
To resolve such issues in the near term, we …

[Storage] Update minor version to allow an update for tracing

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/tsconfig.json
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/tsconfig.json
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/tsconfig.json
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/tsconfig.json

As mentioned in #16497, we need to ship a stable version of our storage packages after updating them to use the latest core-tracing and core-http packages. Since the latest core packages have dropped support for Node.js 8 and IE11, this PR makes the minimum changes to reflect the same in the hotfix branch before @maorleger sends out a PR to make the change to move to the latest core-tracing.
Please note that these changes are being made against the hotfix branch and not the main branch.

[Storage] Drop Node.js 8 and IE 11 support

---

sdk/tables/data-tables/test/public/accessPolicy.spec.ts

Live tests are failing because of a clock mock that had been set up. This causes the Authorization header to no longer be valid in live tests.
The clock mock is no longer needed as the signature is being replaced in the Recordings. To fix this issue, we just need to remove the clock mock.

[Tables] Fix live tests

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1
eng/scripts/validate-docs-package.ps1

This eliminates the class of problems where `npm install` does not succeed. `validate-docs-package.ps1` can be extended to support other steps like running `typedoc` etc. 
There is at least one interesting edge case which logging attempts to address: packages which are not tracked in our metadata CSV, in the `metadata` folder after release failing validation. In that case we still remove the package but later versions of the package which successfully install will not be re-added because they are not tracked in metadata. Since we log that the package was removed and the problems associated with the package we will have a history explaining why the package was removed.

Docs CI pre-validation: Exclude packages which fail npm install

---

sdk/communication/communication-chat/CHANGELOG.md

Looks like 1.0.1 for communication-chat was never released. Merging its changelog with the one for 1.1.0-beta.1

Combine changelog for unreleased versions

---

sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub-express/review/web-pubsub-express.api.md
sdk/web-pubsub/web-pubsub-express/samples-dev/server.ts
sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/src/cloudEventsProtocols.ts
sdk/web-pubsub/web-pubsub-express/src/utils.ts
sdk/web-pubsub/web-pubsub-express/src/webPubSubEventHandler.ts
sdk/web-pubsub/web-pubsub-express/test/connect.spec.ts
sdk/web-pubsub/web-pubsub-express/test/user.spec.ts

For feature request: https://github.com/Azure/azure-webpubsub/issues/156
Spec described here: https://github.com/Azure/azure-webpubsub/pull/172
Sample: 
```js
const handler = new WebPubSubEventHandler("chat", ["https://xxx.webpubsub.azure.com"], {
handleConnect(req, res) {
// You can set the state for the connection, it lasts throughout the lifetime of the connection
res.setState("calledTime", 1);
res.success();
},
handleUserEvent(req, res) {
var calledTime = req.context.states.calledTime++;
console.log(calledTime);
// You can also set the state here
res.setState("calledTime", calledTime);
res.success();
}
});
```

Supporting reading and setting connection state

---

sdk/keyvault/keyvault-keys/test/public/crypto.spec.ts

After a month of not being able to run live tests due to a service performance issue, we have finally been able to run live Key Vault
tests. The live test run showed a single failure, which is caused by a test purging a key which later is purged by the afterEach hook 
as well. The second purge would fail, since the key doesn't exist.

[KeyVault] - Fix double-purge of the same key in test

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/utils/batch.ts
sdk/cosmosdb/cosmos/test/internal/unit/utils/batch.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

Fixes: https://github.com/Azure/azure-sdk-for-js/issues/16445
Bulk was failing to correctly create each set of operations per partition for nested object partition key values, this should fix it.

[Cosmos] Adds deep object find for bulk partition key value path finding

---

eng/tools/versioning/set-dev.js

Alpha version is not created for management packages but we need to publish alpha versions for track2 management packages.

Create alpha version for track2 management packages

---

sdk/search/search-documents/test/public/node/searchClient.spec.ts

The Semantic Test is enabled only for certain subscriptions and could not be executed now in CI (which causes the test failures). So, skipping it for now. 

Skip Semantic Test

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableTransaction.ts

In #15938 we exposed the `allowInsecureConnection` option to allow
connections to the service over HTTP instead of HTTPS. However, even
if a table client was created allowing insecure connections, we would
still require a secure connection when submitting a batch transaction,
since the implementation of batch operations interact with the
pipeline directly. We now record if the client was created allowing
insecure connections and thread that information along when creating
requests for batch operations.
With this change, you can now submit batch transactions to storage
emulators, which commonly run over HTTP instead of HTTPS.
Fixes #15854

[Tables] Fix batch operations against emulators

---

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts

@LarryOsterman reached out regarding the issue with recording the attestation tests.
Some of the tests are hanging forever, some are saving incorrect recordings.
We(with @LarryOsterman) observed that there is a race condition in processing the responses. While the live test is fine, the test in record mode either drops part of the initial response or loses the response completely and hangs. This points fingers towards nock which we use to record tests in node.
On the other hand, with a simple binary search, we realized that https://github.com/Azure/azure-sdk-for-js/pull/16372 made this problem visible.
So, it was either that PR caused the issue or the PR uncovered some problem that existed always.
Upon more investigation, it was indeed nock doing things incorrectly. …

[core-rest-pipeline] Unblock recording new tests

---

sdk/attestation/attestation/CHANGELOG.md
sdk/attestation/attestation/README.md
sdk/attestation/attestation/package.json
sdk/attestation/attestation/samples-dev/utils/cryptoUtils.ts
sdk/attestation/attestation/src/attestationAdministrationClient.ts
sdk/attestation/attestation/src/attestationClient.ts
sdk/attestation/attestation/src/constants.ts
sdk/attestation/attestation/src/generated/generatedClientContext.ts
sdk/attestation/attestation/swagger/readme.md
sdk/attestation/attestation/test/utils/cryptoUtils.ts

Prepare the attestation SDK for GA.

Prepare for GA release

---

eng/pipelines/templates/stages/archetype-js-release.yml

Install package artifact locally using npm and ensure all dependency packages are available npm. This is to ensure packages are released in order.

Add step to install package to be published

---

eng/scripts/Language-Settings.ps1

Underlying issue has been resolved. Tracking bugs closed: 
* https://github.com/Azure/azure-sdk-for-js/issues/16476
* https://github.com/Azure/azure-sdk-for-js/issues/16474

Readd packages for whom Docs CI has been fixed

---

sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/src/constants.ts
sdk/eventgrid/eventgrid/src/eventGridClient.ts
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/accessControlClient.ts
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/remoterendering/mixed-reality-remote-rendering/package.json
sdk/schemaregistry/schema-registry/package.json
sdk/textanalytics/ai-text-analytics/package.json
sdk/textanalytics/ai-text-analytics/src/constants.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/web-pubsub/web-pubsub/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/16623
@ramya-rao-a noticed in https://github.com/Azure/azure-sdk-for-js/pull/15777#discussion_r653112105 that we could end up with duplicate versions in the agent-string header in our requests in packages that migrated to use core v2 because the code generator became smarter and now generates code that handles that for us. I noticed the same thing happening in attestation as well in https://github.com/Azure/azure-sdk-for-js/pull/16619#discussion_r678591391.
This PR fixes this issue for all data-plane packages that migrated to use core v2.
Note that 
- I intentionally left out tables because it needs to be regenerated with a later version of the code generator first so that it gets the auto-generated handling of the agent-string. I …

Fix agent-string in packages migrated to use core v2

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-admin/swagger/README.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/constants.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts

We released @azure/keyvault-admin@4.1.0 and @azure/keyvault-keys@4.3.0 off of a hotfix branch because we already had
betas out for the next release. 
So what this PR does is port over all the CHANGELOG entries from the hotfix branch as well as update the version numbers to reflect the new betas.

[KeyVault] - Porting changelog entries and updating versions after release

---

eng/scripts/Language-Settings.ps1

Excluding these packages from being onboarded when they release to daily feed (and are onboarded in daily docs), ship a new version to preview, or ship a new version to GA. 
Existing entries will remain. This change only prevents new versions from updating the existing onboarding entries.

Exclude packages failing daily docs.ms build

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/test/public/keyClient.hsm.spec.ts

- Update `getRandomBytes` to return a model instead of the raw bytes
This came up from an architecture feedback, where we are deviating from the guidelines by returning the raw bytes.
Returning the model instead conforms to our guidelines, is consistent with other operations, and is extensible.

[KeyVault] - Update getRandomBytes to return a model

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/16657
The default value for `--node-version` is the empty string so if the caller did not provide it, they will end up with an empty string in the list of node versions to test and because no such docker image exists, the command will fail. This PR fixes this issue by filtering out empty strings and non-numerical inputs.

fix check-node-versions command

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

#16529 has the changes to ship stable versions of storage packages as part of a hotfix
This PR has the following changes in the main branch
- changelog updates in the main branch to include the changes from the hotfix
- version update for storage-queue as that package is also being shipped along with the others in the hot fix branch.
- update the release dates
cc @maorleger 
@EmmaZhu, This PR is not a blocker for you to release the storage beta packages from the main branch. If you do merge this before before the beta releases, you get the advantage of the changelogs having the right entries when someone looks at the git tags corresponding to the beta release

[Storage] Updates in main branch to reflect changes from hotfix branch

---

sdk/eventgrid/eventgrid/test/public/generateSharedAccessSignature.spec.ts

This would help reduce the noise in the cred scan report by striking off one complaint from the list of complaints.
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1394&_a=summary

[Cred Scan] Generate fake key instead of putting directly in the test file

---

rush.json

https://dev.azure.com/azure-sdk/internal/_build?definitionId=2765&_a=summary has been failing to publish nightly dev packages for iot-modelsrepository due to a missing entry in rush.json file
Thanks to @praveenkuttappan for helping to root cause this

Enable nightly dev releases for iot-modelsrepository

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations/recording_can_update_a_keys_properties_for_a_specific_version.json
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations/recording_can_update_a_keys_properties_without_specifying_a_version.json
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations_for_managed_hsm_releasekey/recording_can_update_a_keys_release_policy.json
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations/recording_can_update_a_keys_properties_for_a_specific_version.js
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations/recording_can_update_a_keys_properties_without_specifying_a_version.js
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations_for_managed_hsm_releasekey/recording_can_update_a_keys_release_policy.js
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/test/public/keyClient.hsm.spec.ts
sdk/keyvault/keyvault-keys/test/public/keyClient.spec.ts

- Add `releasePolicy` to `UpdateKeyPropertiesOptions`
- Add an overload to `updateKeyProperties` that does not take a key version
While you are unable to update the exportable attribute of a key once it's been created, you should be able to update the 
release policy of an exportable key; however, we have a bug in the GA version of KV Keys where `updateKeyProperties` requires a 
version. While that has not come up from customers yet, and a workaround is to pass something falsy for key version, it feels 
incorrect that we are requiring an argument that is functionally optional.
This wasn't necessary until now, but version _must_ be omitted when updating a key's release policy, so this is now a requirement.
Normally, the version is part of the `<operation>Options` bag, but in this case an …

[KeyVault] - Add releasePolicy to UpdateKeyProperties

---

sdk/eventgrid/eventgrid/test/public/generateSharedAccessSignature.spec.ts

In #16700 we updated our tests to generate the key we used for testing
by doing a base64 conversion of a fixed string so we didn't have something that looked like a key embedded in source which was upsetting some static analysis tools.
This causes a build break in the min/max testing where `btoa` can't be found when building the test. Since we have the correct runtime behavior in the test to only call `btoa` when we are not in a node-context we simply reference the dom library to appease the compiler.

[EventGrid] Fix Test Compilation Errors

---

sdk/core/core-amqp/CHANGELOG.md

@chradek says that there are no changes to core-amqp as part of  https://github.com/Azure/azure-sdk-for-js/pull/15989, so updating changelog

Remove false changelog entry for core-amqp

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/serializer.ts
sdk/core/core-client/test/browser/serializer.spec.ts
sdk/core/core-rest-pipeline/CHANGELOG.md

At some point during the creation of core-client we changed the validation logic for Blobs in a way that was not inclusive of `File` objects, which should be treated as Blobs in the browser.
This PR restores the previous detection we were doing in `core-http` (that is confirmed working) and adds a test to prevent regression.
Fixes #16754

[core-client] Fix Serializer issue where File didn't count as a Blob

---

sdk/tables/data-tables/recordings/browsers/tableclient_sasconnectionstring_createentity_getentity_and_delete/recording_should_createentity_with_primitive_int_and_float_without_automatic_type_conversion.json
sdk/tables/data-tables/recordings/browsers/tableclient_tokencredential_createentity_getentity_and_delete/recording_should_createentity_with_primitive_int_and_float_without_automatic_type_conversion.json
sdk/tables/data-tables/recordings/node/tableclient_sasconnectionstring_createentity_getentity_and_delete/recording_should_createentity_with_primitive_int_and_float_without_automatic_type_conversion.js
sdk/tables/data-tables/recordings/node/tableclient_tokencredential_createentity_getentity_and_delete/recording_should_createentity_with_primitive_int_and_float_without_automatic_type_conversion.js
sdk/tables/data-tables/src/serialization.ts
sdk/tables/data-tables/test/internal/serialization.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts

**Context:**
When querying the Tables service we have an option to disable automatic type conversion. This means that we would give users an object similar to what the service sends us. For example, an object with a Date property will be received like this, with an `@odata.type` metadata property
```json
{
"PartitionKey": "1",
"RowKey": "1",
"dateValue": "2020-09-17T00:00:00.111Z",
"dateValie@odata.type": "Edm.DateTime"
}
```
The SDK's automatic type conversion would use the metadata to give users a primitive Date type so the user would get the following object
```javascript
{
partitionKey: "1",
rowKey: "1",
dateValue: new Date("2020-09-17T00:00:00.111Z")
}
```
If `disableTypeConversion` is true in the list or get operations the sdk returns the Edm object instead of a primitive type …

[Tables] Infer EDM types for properties with no Type metadata

---

sdk/core/core-rest-pipeline/CHANGELOG.md

Apparently the release pipeline now validates this:
##[error]The changelog entry has the following sections with no content (Bugs Fixed, Breaking Changes, Other Changes). Please ensure to either remove the empty sections or add content to the section.

[core-rest-pipeline] Remove empty changelog sections

---

sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-phone-numbers/CHANGELOG.md
sdk/communication/communication-sms/CHANGELOG.md
sdk/digitaltwins/digital-twins-core/CHANGELOG.md
sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventhub/event-hubs/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/search/search-documents/CHANGELOG.md
sdk/servicebus/service-bus/CHANGELOG.md
sdk/tables/data-tables/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/CHANGELOG.md

This PR adds missing changelog entries for the times we
- updated tracing dependencies to use the GA version of OpenTelemetry
- updated to target ES2017

Add missing changelog entries for tracing and ES2017 updates

---

sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/src/index.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/16528
Exports `KnownSerializationType` so customers can refer to known enum values in their code.

[Schema Registry] Export a known enum

---

eng/tools/dependency-testing/templates/package.json
sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-certificates/test/public/list.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.create.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.delete.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.operation.spec.ts
sdk/keyvault/keyvault-certificates/test/public/mergeAndImport.spec.ts
sdk/keyvault/keyvault-certificates/test/public/recoverBackupRestore.spec.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/test/internal/challengeBasedAuthenticationPolicy.spec.ts
sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-secrets/test/public/list.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.delete.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.recover.spec.ts
sdk/keyvault/keyvault-secrets/test/public/recoverBackupRestore.spec.ts

- Bump the timeout of integration tests for KV Secrets and Certificates
- Bump the timeout of min/max testing to work around #16731 
- Delete extra cleanup methods 
Due to an ongoing performance regression on the service side our tests have been timing out. The performance has gotten better but after talking to the service team it sounds like the recommendation is to avoid waiting on deletes / purges if you
are latency sensitive. 
However, not all our tests are just cleaning up, there are valid tests that exercise cleaning / purging certificates so bumping the 
timeout a bit feels appropriate. This works fine for tests except that min/max testing uses a hardcoded number for test timeouts
so need to update that as well (or add timeouts everywhere in our code). Since certificates and …

[KeyVault] - Increase timeout for KeyVault certificates and secrets

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/samples-dev/logsQuery.ts
sdk/monitor/monitor-query/samples-dev/logsQueryBatch.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/src/models/publicLogsModels.ts
sdk/monitor/monitor-query/test/internal/unit/modelConverters.unittest.spec.ts
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts

- add additional workspaces parameter, moved it to options
- Moved other optional params to options
- rename workspace to workspaceId
Update: 
- This PR doesn't fix the tests.
- (Tried to increase timeout. Figured this fix will not work for CI. )
-_Change the tests to last 2 days to combat slower ingestion times._

Monitor query align the request bodies

---

.scripts/common.ts

@azure/graph package got released accidentally from feature/v4 branch. This shouldn't have been released from feature/v4. We have setup a new pipeline for track1 dataplane packages so gulp script should not consider any track1 packages when running on feature/v4 branch to avoid this issue in future due to version conflict on main and feature/v4 branch.

Skip all non arm packages when packing packages from feature/v4

---

sdk/identity/identity/README.md

Nikitha Udaykumar pointed out to us that, since the `@azure/identity` package can be used for more than Azure SDKs, we should be a bit more open with our introductory definition in the README.
What do you think about the definition I’m proposing here?
If this looks correct, I can make issues in the other languages before moving this out of draft.

[Identity] README: Identity can be used with more than Azure SDKs

---

sdk/keyvault/keyvault-secrets/karma.conf.js

In abf3de05c9f7e99c7fc0cc1a45096abf0aaea1f7 we increased the timeouts for live tests in KV. I didn't update karma config for 
secrets (I did for certificates).
This PR just updates the browser tests' timeout as well

[KeyVault] - Extend Karma timeout for Key Vault Secrets

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/BlobBatchClient.ts

- change BlobBatchSubmitBatchOptionalParams to no longer extend CommonOptions
- remove the declaration of `abortSignal` in BlobBatchSubmitBatchOptionalParams
BlobBatchSubmitBatchOptionalParams already extends coreHttp.OperationOptions indirectly through ServiceSubmitBatchOptionalParams and does not need to pull tracingOptions from CommonOptions anymore. It also doesn't need to re-declare abortSignal as it gets that from OperationOptions as well.
So nothing changes, but we also know that enums which come in from tracingOptions are compatible but not identical, so when extending both TS will throw an error if core-tracing versions are different. See #15285
This change resolves the above in the only known case of this in our repo, cleans up the unnecessary duplication, and does not change …

[storage] -  Remove unnecessarily extending CommonOptions 

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/samples-dev/logsQueryBatch.ts
sdk/monitor/monitor-query/samples-dev/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/samples/v1/javascript/README.md
sdk/monitor/monitor-query/samples/v1/javascript/logsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryBatch.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryMultipleWorkspaces.js
sdk/monitor/monitor-query/samples/v1/typescript/README.md
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQuery.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryBatch.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/src/models/publicLogsModels.ts
sdk/monitor/monitor-query/test/internal/unit/modelConverters.unittest.spec.ts
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts

Monitor query readme

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/StorageClient.ts
sdk/storage/storage-blob/src/credentials/Credential.ts
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/Pipeline.ts

Looking into the code for this, the subclass of `Pipeline` in `storage-file-datalake` simply repeats the same behavior in `storage-blob`'s `Pipeline` class: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/src/Pipeline.ts
This was apparently done to work around an `instanceof` check in `ContainerClient`. Since `instanceof` checks are strongly discouraged, I have altered `storage-blob` to take an interface instead.
If this is not desired, I believe that `storage-file-datalake` could import `storage-blob`'s Pipeline class instead of declaring its own.

[storage-file-datalake][storage-blob] Allow storage-blob to accept Pipeline instances from other storage packages

---

common/tools/eslint-plugin-azure-sdk/src/configs/index.ts
common/tools/eslint-plugin-azure-sdk/src/rules/index.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-sdktype.ts
common/tools/eslint-plugin-azure-sdk/tests/plugin.ts
sdk/core/core-client-lro-rest/CHANGELOG.md
sdk/core/core-client-lro-rest/package.json

We were using the wrong type `core` which prevented its release

Fix core-client-lro-rest `sdk-type`

---

sdk/operationalinsights/loganalytics/package.json
sdk/operationalinsights/loganalytics/src/logAnalyticsClientContext.ts

Credentials from the latest version of `@azure/ms-rest-nodeauth` will only work with the auto generated packages that depend on v2 and higher of `@azure/ms-rest-js`. This is the root cause for #16811
We have seen this issue in many of the mgmt plane packages as well. There, we regenerated the package use the latest v4 code generator and released a major version update.
But this package will be soon deprecated in favor of the new Monitor Query package and has been on ice since 2 years.
Therefore, to fix the issue with the minimum changes, I am only updating the dependency in this PR
I have chosen `^2.4.0` as that is the min version required if anyone wants to use the credentials from `@azure/identity`, use the adapter from `@azure/ms-rest-js` to create ServiceClientCredentials and then use …

Update ms-rest-js dependency to allow use of latest ms-rest-nodeauth with loganalytics

---

eng/tools/rush-runner.js

Do not skip perf projects when rush-runner identifies the eligible project to trigger the command.

Include perf tests in rush jobs like lint and foramt

---

common/config/rush/common-versions.json
sdk/textanalytics/ai-text-analytics/package.json

min/max testing is failing for text analytics because of not using the correct core-paging version there. Since it is a release week and core-paging@1.2 was not released yet, I am coding it as an exception for now and then will merge https://github.com/Azure/azure-sdk-for-js/pull/16856 next week.

[Text Analytics] bump core-paging dep version

---

sdk/batch/batch/package.json

The location of the type declarations changed after batch updated their tsconfig.json file. This PR uses the new location in package.json's files list and types entry. Fixes https://github.com/Azure/azure-sdk-for-js/issues/16809

[Batch] Include types in shipped package

---

sdk/batch/batch/README.md
sdk/batch/batch/package.json
sdk/batch/batch/src/batchServiceClient.ts
sdk/batch/batch/src/batchServiceClientContext.ts
sdk/batch/batch/test/utils/recordedClient.ts

Batch has been advertising using shared keys as their primary way of authentication in their docs. https://github.com/Azure/azure-sdk-for-js/pull/16679 added support for `TokenCredential` authentication but it turned out that batch is not compatible with the support for token credentials in `@azure/ms-rest-js` because the [latter assumes a scope that only works with management-plane libs](https://github.com/Azure/ms-rest-js/blob/702088850b339804fc7b178407d0c7e0117701ed/lib/credentials/azureIdentityTokenCredentialAdapter.ts#L22).
If we want to fix the support for AAD, we will have to add support for custom scopes in `@azure/ms-rest-js` so we can pass the batch scope `https://batch.core.windows.net//.default` to it and also update `azureTokenCredential` as follows:
```ts …
```

[Batch] Rollback the support for TokenCredential

---

sdk/identity/identity/README.md

Some of the clarity around support policy did not get added to the Identity readme like they were added in other packages. This PR fixes that problem

Clarify support policy in Identity readme

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/README.md
sdk/identity/identity/src/credentials/managedIdentityCredential/constants.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

This PR is intended to release Identity hotfix 1.5.1, which:
- Fixes how we verify the IMDS endpoint is available. Now, besides skipping the `Metadata` header, we skip the URL query. Both will ensure that all the known IMDS endpoints return as early as possible.
- Adds support for the `AZURE_POD_IDENTITY_AUTHORITY_HOST` environment variable. If present, the IMDS endpoint initial verification will be skipped.
It took us a while to figure out why sometimes IMDS pings couldn’t be fulfilled on time. While it was under our assumptions that requests to the IMDS endpoint would immediately fail if they were sent without a `Metadata` header, turns out that this is not the case: Some IMDS endpoints, like the one used by the Pod Identity service, won’t necessarily fail if this header is missing. …

[Identity] Hotfix 1.5.1: IMDS ping fixes

---

sdk/cosmosdb/cosmos/package.json

Closes https://github.com/Azure/azure-sdk-for-js/issues/15793

[Cosmos] Adds reporter to cosmos tests

---

sdk/cosmosdb/cosmos/CHANGELOG.md

we fixed an issue in bulk for operations missing partitionKeys at the top level when implementing transactional batch, this adds it to the changelog

[Cosmos] Adds changelog entry for bulk bugfix

---

sdk/servicebus/service-bus/test/stress/Dockerfile
sdk/servicebus/service-bus/test/stress/test-resources.bicep
sdk/servicebus/service-bus/test/stress/test-resources.json

This fixes the Dockerfile directory/ADD syntax to work with more versions of docker (it was failing in the pipeline due to no trailing slash). It also simplifies the ARM template to remove unnecessary resources that were copied from the parent template in the root service-bus directory, as well as migrates the template to be generated from a bicep file.

[stress testing] Improve dockerfile and ARM template for service bus

---

sdk/core/README.md

This documentation PR adds information to core readme about Application Insights for JS and links to getting started with Application Insights
Resolves #15420
Related: https://github.com/Azure/azure-sdk-for-net/pull/22542

[core] - Add information about Application Insights

---

sdk/core/core-paging/review/core-paging.api.md
sdk/core/core-paging/src/getPagedAsyncIterator.ts
sdk/core/core-paging/src/models.ts
sdk/core/core-paging/test/getPagedAsyncIterator.spec.ts

some services use continuation tokens to point to pages which do not have to be strings, so this PR makes the link type a generic with a default to a string.

[core-paging] make the page link type generic

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/tools/eng-package-utils/update-samples.js

Update samples after package release so samples are refreshed using latest code. This will be later used by samples publishing automation.

Update samples after a package release

---

sdk/servicebus/service-bus/test/stress/Chart.lock
sdk/servicebus/service-bus/test/stress/Chart.yaml

Bumping the [stress-test-addons](https://github.com/Azure/azure-sdk-tools/tree/main/tools/stress-cluster/cluster/kubernetes/stress-test-addons) chart version dependency:
- Uses correct ISO8601 format `DeleteAfter` tags for resource groups
- Does not print resource deployments to stdout (in case of secrets in ARM template)

[stress testing] Update stress-test-addons chart version

---

sdk/servicebus/service-bus/test/stress/app/src/scenarioLongRunning.ts

Fixes #16887 
Our long running stress test had an issue where a memory leak would occur when sending to a namespace that existed when the client was created but was then deleted. This was because any time the sender encountered an error, a new sender was created to send future messages.
This update simply causes the send messages loop to always use a single sender, even if an error occurs. I'm not sure what the motivation was around creating a new sender anytime an error was encountered while sending messages...though I'd argue that if our sender can't come back online after a transient issue, we should detect that in our stress tests rather than ditch the sender right away.
I ran the test locally before and after this change and with this change the garbage collector is able to reclaim …

[service-bus] update long running stress test to use single sender

---

sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts

Fixes #16797
Most of our tests have been updated to use a `startPosition` that equals the last enqueued sequence number for each partition. This is preferred over using `latestEventPosition` since any flakiness with the consumer before a message is received can cause the tests to time out.
`latestEventPosition` will receive any events that the event hub receives _after_ the consumer establishes a receiver link, so if the producer ends up sending an event prior to that link being established, our tests can fail as they'll never see the event round-tripped.
This PR updates a few more tests to use the last enqueued sequence number instead of the `latestEventPosition`, since none of the tests are specifically testing that `latestEventPosition` works.

[event-hubs] fix flaky consumer tests

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md

So we release today. I did not know that it depends on a hard coded version for `azure/schema-registry` so we will need to make a release even though nothing else changed.

[schema-registry-avro] Prepare release

---

sdk/containerregistry/container-registry/tests.yml

It was added for testing purpose when creating weekly pipeline and applied to
nightly pipeline runs as well, which is not desired. This PR limits the filter to weekly
pipeline.

[ContainerRegistry][Test] Apply MatrixFilters.Pool for weekly only

---

sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/index.ts

Because we use `orderBy` everywhere.

[Text Analytics] Rename sortby to orderby

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md
sdk/keyvault/keyvault-admin/src/accessControlModels.ts
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-admin/src/generated/models/index.ts
sdk/keyvault/keyvault-admin/swagger/README.md
sdk/keyvault/keyvault-admin/test/internal/serviceVersionParameter.spec.ts
sdk/keyvault/keyvault-certificates/test/internal/serviceVersionParameter.spec.ts
sdk/keyvault/keyvault-secrets/test/internal/serviceVersionParameter.spec.ts

- Regenerate KeyVault Admin using 7.3-preview
- Remove the duplicated enums in accessControlModels
- In order to add support to the latest data actions for RBAC
- Now that generated code is not a `const enum` we can just re-export it directly instead of copying code
Resolves #16563

[KeyVault] - Regenerate KeyVault Admin using 7.3-preview

---

sdk/schemaregistry/schema-registry/recordings/browsers/schemaregistryclient/recording_schema_with_whitespace.json
sdk/schemaregistry/schema-registry/recordings/node/schemaregistryclient/recording_schema_with_whitespace.js
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts

To make sure https://github.com/Azure/azure-sdk-for-js/issues/15131 is fixed.

[Schema Registry] Add a whitespace in schema test case

---

sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/README.md
sdk/schemaregistry/schema-registry/samples/v1/javascript/package.json
sdk/schemaregistry/schema-registry/samples/v1/typescript/README.md
sdk/schemaregistry/schema-registry/samples/v1/typescript/package.json
sdk/schemaregistry/schema-registry/src/generated/generatedSchemaRegistryClientContext.ts
sdk/schemaregistry/schema-registry/swagger/README.md

After we made a release for beta.2 yesterday. The release pipeline failed to run the post release bot for some reason: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1052303&view=results
However, it ran fine for the avro package here: https://github.com/Azure/azure-sdk-for-js/pull/16961
cc @praveenkuttappan

[Schema Registry] bump versions

---

sdk/appconfiguration/perf-tests/app-configuration/package.json
sdk/core/perf-tests/core-rest-pipeline/package.json
sdk/eventgrid/perf-tests/eventgrid/package.json
sdk/formrecognizer/perf-tests/ai-form-recognizer/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/package.json
sdk/identity/perf-tests/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/perf-tests/keyvault-certificates/package.json
sdk/keyvault/perf-tests/keyvault-keys/package.json
sdk/keyvault/perf-tests/keyvault-secrets/package.json
sdk/metricsadvisor/perf-tests/ai-metrics-advisor/package.json
sdk/search/perf-tests/search-documents/package.json
sdk/storage/perf-tests/storage-blob-track-1/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-datalake/package.json
sdk/storage/perf-tests/storage-file-share-track-1/package.json
sdk/storage/perf-tests/storage-file-share/package.json
sdk/tables/perf-tests/data-tables/package.json
sdk/test-utils/perfstress/package.json
sdk/test-utils/perfstress/tsconfig.json
sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/tsconfig.json
sdk/test-utils/test-utils/package.json
sdk/textanalytics/perf-tests/text-analytics/package.json

- Our convention now is to use `types`.
- Some packages output type definition files into `types` directory but the `clean` scripts still use `typings`.

Update `typings` to `types` in clean NPM scripts

---

sdk/core/core-client-paging-rest/review/core-client-paging.api.md
sdk/core/core-client-paging-rest/src/paginate.ts
sdk/core/core-client-paging-rest/test/paginate.spec.ts

According to the Swagger `x-ms-pageable` extension, `itemName` and `nextLinkName` are the properties where a pageable response body contains the page and link to the next page respectively.
There are many swaggers that would use different names for these properties across the swagger. This change allows us to pass a set of "known" names that the paging helper can try in the response body to find the `page` and `nextLink`.
In the generator we'd generate a wrapping class that passes this to the `paginateResponse` function:
```typescript
export function paginate<TReturn extends PathUncheckedResponse>(
client: Client,
initialResponse: TReturn
): PagedAsyncIterableIterator<
PaginateReturn<TReturn>,
PaginateReturn<TReturn>[]
> {
return paginateResponse<PaginateReturn<TReturn>>(client, …
```

[REST Paging] Allow setting different `itemName` and `nextLinkName`

---

sdk/appconfiguration/app-configuration/test/public/index.spec.ts

This test occasionally hits 429 error (throttling) since we are making 100s of requests in the test to create, get and delete keys.
To avoid hitting the service with too many requests, skipping the test in live.
More details at https://github.com/Azure/azure-sdk-for-js/issues/16743
Remove the following line if you want to hit the live service.
`if (isLiveMode()) this.skip();`
Fixes #16743

[App Config] Skip live testing for byPage to avoid throttling in the CI

---

.devcontainer/Dockerfile

to have more recent versions of development tools.

Bump devcontainer docker image version to 1-linux

---

eng/scripts/Language-Settings.ps1

Re-add package now that a superseding version fixes the issue in https://github.com/Azure/azure-sdk-for-js/issues/16932

Re-add @azure/arm-appservice

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/retry/RetryContext.ts
sdk/cosmosdb/cosmos/src/retry/retryUtility.ts
sdk/cosmosdb/cosmos/src/retry/sessionRetryPolicy.ts
sdk/cosmosdb/cosmos/test/internal/session.spec.ts

In high throughput scenarios with multiple regions, replication lag can sometimes cause a session to not be available. A client will write a document to Region A, and later attempt to read it from Region B. But the session token from region A has not yet been replicated to Region B. This results in Error 404, substatus 1002: Session Not Found.
In these cases the SDK is supposed to retry the request on other regions and if still unsuccessful retry the request again with no session token establishing a new session token. This code was not working correctly. This PR fixes the logic and and adds a test that simulates an out of date session token in a single region scenario.
1. Add session token test simulating 404/1002 condition
2. Properly increment retryCount
3. Instantiate retryCount to 0. …

[Cosmos] Fix retry handling for Session Not Found errors

---

rush.json

to have security fix for tar@6.1.0 (see https://github.com/pnpm/pnpm/releases/tag/v5.18.10 for details)

Bump pnpm version to 5.18.10

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

as recommended by
```
 WARN  deprecated @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
```

[Cosmos] remove deprecated @types/fast-json-stable-stringify dependency

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/samples-dev/iothubConnectionString.ts
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionString.ts

Fixes #16666 
This PR fixes a couple issues found in the linked issue.
1. `@azure/identity` was set to an unreleased beta version. This has been updated to depend on the GA version of `@azure/identity`.
2. Updates `import rheaPromise from "rhea-promise"` to `import * as rheaPromise from "rhea-promise"`, which fixes the `rheaPromise is undefined` issue.
3. `@types/ws` is now included as a dev dependency.

[event-hubs] fix IoT Connection string sample

---

sdk/servicebus/service-bus/src/receivers/receiver.ts

Fixes #16618
There are 2 issues with the existing docs for `getMessageIterator`:
1. > If the iterator is not able to fetch a new message in over a minute, `undefined` will be returned.
This isn't actually true. We only return actual messages. I believe this doc is a carry-over from when this was a preview feature. The `abortSignal` can be used to exit a `for...await` loop.
2. maxWaitTimeInMs is documented. This was a carry-over from when this feature was in preview and `undefined` was returned if no events were received within the `maxWaitTimeInMs` interval. Since we no longer return `undefined` for this scenario, we also stopped accepting `maxWaitTimeInMs`. Note: Technically, you could pass `maxWaitTimeInMs` and the code would honor it, but the behavior you see wouldn't change.

[service-bus] fix getMessageIterator docs

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/request/RequestContext.ts
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/src/request/request.ts

Dev build to test for https://github.com/Azure/azure-sdk-for-js/issues/16971
Gives a credential object to core-rest-pipeline which handles token cycling and caching for us. We were mistakenly refetching the AAD token per-request

[Cosmos] Adds pipeline to requestContext for AAD auth reuse

---

eng/CredScanSuppression.json

This suppresses a CredScan warning that comes from a non-secret devcert
necessary for using the new test proxy. (See related Python PR at
https://github.com/Azure/azure-sdk-for-python/pull/20324)

Suppress CredScan warnings for test proxy dev cert

---

sdk/identity/identity/samples/manual/README.md

In this PR I’m fixing a broken link. It pointed to a feature branch, and it correctly routed to it while we were developing the feature, but after merging an deleting that branch, the link is now broken! (reasonably so). Let’s clean it up!
Thank you, @jeremymeng for letting me know about this.

[Identity] Fix broken link

---

sdk/core/core-http/src/policies/tracingPolicy.ts
sdk/core/core-http/test/policies/tracingPolicyTests.ts
sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts
sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts

- If a span is not recording, return early and avoid doing any more work
- Update some missed test setup
When tracing is either not configured or the newly created span is not sampled this information would get dropped from both 
telemetry and request headers (since the serialized span context will not be valid).
We can return early in that case. It'll have several benefits:
1. Less instances of the Span#context / Span#spanContext rename issues (since we won't get there)
2. We can avoid some processing overhead, although for a non recording span it is probably (but not surely) very lightweight anyway.
Being able to avoid creating the span (and the URIBuilder overhead) is currently not possible for multiple reasons:
1. The OTel API does not provide a way to check whether tracing is …

[core] - return early if span is not recording

---

.github/CODEOWNERS

As discussed in https://github.com/Azure/azure-sdk-tools/issues/1099, usage of glob patterns does not work for our bot. So adding codeowner for each of the mgmt plane package. I copied the list from https://github.com/Azure/azure-sdk-for-js/blob/feature/v4/eng/pipelines/mgmt-ci.yml

Update CODEOWNERS for every mgmt package

---

sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/parameters.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

Regeneration using the swagger in https://github.com/Azure/azure-rest-api-specs/pull/15736#pullrequestreview-735691760. I noticed that the `LoggingOptOut` parameter is missing and I left a comment about this in the swagger PR.
Please note that I created a feature branch and this PR targets it, so please ignore the CI failures.

[Text Analytics] Regenerate using v3.2-preview.2 swagger

---

.github/CODEOWNERS

Update CODEOWNERS for Application Insights

---

sdk/core/core-tracing/test/interfaces.spec.ts

We have a few tests that ensure core-tracing remains compatible with core-auth's OperationTracingOptions.
Since `spanOptions` is now effectively deprecated we can safely ignore that as well, but we need to specifically ignore
it in our test because of the versioning mismatch in nightly builds.
Fixes the nightly build (see https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1067749)

[core] - Ignore spanOptions in core-tracing tests

---

eng/pipelines/templates/steps/analyze.yml

Link check is always performed in main branch and this causes failure for valid links in hotfix branch but invalid on main branch.

Skip link check for hotfix branch

---

sdk/monitor/monitor-query/src/logsQueryClient.ts

Addresses https://github.com/Azure/azure-sdk-for-js/issues/17066
Make it clear that the LogsQueryClient "query" methods except Kusto queries. This came up as a source of confusion in the Beta 4 UX study when participants switched from using the MetricsQueryClient, where Kusto isn't used.

Clarify LogsQueryClient query parameter description

---

eng/scripts/cleanup-npm-next-tag.ps1

Cleanup tag script is failing when a new package is getting published for the first time. We should ignore npm errors in getting tags  and continue docs publishing step.

Do not fail cleanup tags when a package is published for the first time

---

common/config/rush/pnpm-lock.yaml
sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/constants.ts
sdk/keyvault/keyvault-certificates/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-certificates/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/generated/models/index.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/swagger/README.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/constants.ts
sdk/keyvault/keyvault-secrets/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-secrets/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/src/generated/models/index.ts
sdk/keyvault/keyvault-secrets/swagger/README.md

- Regenerate certificates and secrets against the 7.3-preview swagger
- Update certificate and secrets package versions to beta of next minor
Although there are no changes in these packages, we should still offer support and default to the latest swagger version which 
will be 7.3. 
Since we'll be GAing in October, it makes sense to have a beta in September.

[KeyVault] - Regenerate secrets and certificates using 7.3-preview

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

The first request of the Arc MSI, which retrieves the file path where the basic authentication value is, generally happens through HTTP endpoints, so `allowInsecureConnection` should be set to true.

[Identity] Arc MSI fix

---

sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsAction.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

After regenerating with latest version of the swagger in https://github.com/Azure/azure-rest-api-specs/pull/15736

[Text Analytics] Make project and deployment names required

---

sdk/identity/identity/src/client/identityClient.ts

I’m too used to the automated checks :) we missed the user agent update on 1.5.1. I’m making sure we don’t miss this for 1.5.2

[Identity] Hotfix 1.5.2 - Updated the user agent

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/tsconfig.json

Required to unblock @qiaozha the CI for codegen for management packages.

[Recorder] Fix types in the published package

---

sdk/identity/identity/samples/AzureIdentityExamples.md

This PR comes after the feedback here: https://github.com/Azure/azure-sdk-for-js/pull/16687
Since there’s a very simple way to satisfy the `TokenCredential` interface, we can help users who want to provide their custom credentials by pointing them to this approach through our docs. Here’s an idea of how we can phrase these docs :)
Feedback appreciated 👍

[Identity] Simplest possible credential sample

---

sdk/agrifood/agrifood-farming-rest/package.json
sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/core/core-client-lro-rest/package.json
sdk/core/core-client-paging-rest/package.json
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/package.json
sdk/core/core-client-rest/src/clientHelpers.ts
sdk/core/core-client-rest/test/clientHelpers.spec.ts
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts
sdk/core/core-rest-pipeline/src/index.ts
sdk/core/core-rest-pipeline/src/pipeline.ts
sdk/documenttranslator/ai-document-translator-rest/package.json
sdk/purview/purview-account-rest/package.json
sdk/purview/purview-catalog-rest/package.json
sdk/purview/purview-scanning-rest/package.json

We want more control on which pipelines to add in RestClients. Switching from `createPipelineFromOptions` to `createEmptyPipeline` and explicitly adding policies.
Initially, this PR removes tracing policy, Open for discussion on which policies to keep or remove.

[Rest clients] Explicitly set pipeline policies

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

This PR does the same as the hotfix PR: https://github.com/Azure/azure-sdk-for-js/pull/17362
Thinks look a bit different because the tests are a bit different from that version to this version, but the behavior is the same. If we undo the source fix but keep the test changes, the related test will fail.
Reviews appreciated 👍

[Identity] Update after Hotfix 1.5.2: Enabling insecure connection requests on the Arc MSI

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

I'm unsure how this went through with ^1.1.0 when it's missing challengeCallbacks, I had bumped it but incidentally must have checked in an old package.json

[Cosmos] Bump core-rest-pipeline version

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

#17106 requires us to update the version of proxy-agent being used in the cosmosdb package to the latest major version.
Found that this package is no longer being used. The [test case that did use it is now commented out](https://github.com/Azure/azure-sdk-for-js/blob/d3647f86a9f8e29f6376ef1e04015dd5e94d63a7/sdk/cosmosdb/cosmos/test/public/integration/proxy.spec.ts).
So, choosing to remove the dependency altogether.
When the cosmosdb team plans to add the test case back, they can test it with the latest version of proxy-agent and add that dependency back
Fixes https://github.com/Azure/azure-sdk-for-js/issues/17106
_Regarding the changes to the lock file:_
I tried running `rush update --recheck` to ensure proxy-agent gets removed from the lock file, but that did not work out. So, resorted …

Remove unused dependency on proxy-agent

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/util/constants.ts

Unfortunately the [automation build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1077922&view=logs&j=e48a6a5a-3932-594b-dbbd-1adab0f233bc&t=3f58f8b2-03ca-5a9d-677f-c6fa3fac06c6) failed 
due to an error in the Update samples step. 
I manually ran the command `node ./eng/tools/versioning/increment.js --artifact-name azure-core-http --repo-root .`

Increment version after release of core-http

---

.github/CODEOWNERS

@kushagraThapar Anyone else you would like to add here? This entry controls who gets added as code reviewers on a PR that touches any of the files in the cosmos JS SDK

Update code owners for cosmos

---

sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/schema-registry-avro.shims.d.ts
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/src/utils/buffer.browser.ts
sdk/schemaregistry/schema-registry-avro/src/utils/buffer.ts
sdk/schemaregistry/schema-registry-avro/tsconfig.json

`deserialize` took only `Buffer` as input before and this PR makes it also support browser's `Blob` and `Uint8Array`.

[schema-regitry-avro] deserialize supports Blob

---

sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/samples-dev/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/models.ts
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts

According to what the crew and the service team agreed on since `getSchemaId` returns the schema version and the serialization type in addition to the ID.

[Schema Registry] Rename getSchemaId to getSchemaProperties

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry/package.json

https://github.com/Azure/azure-sdk-for-js/pull/17421#issuecomment-910923108 explains that we should start from the leaves when upgrading the api-extractor so this PR does so for schema registry and event hubs.

[Schema Registry & Event Hubs] Upgrade api-extractor to v7.18

---

sdk/core/core-tracing/README.md

- Update the core-tracing README's examples
- Add a Compatibility matrix section in core-tracing
- Add a troubleshooting section for Span#context -> Span#spanContext rename
- The samples are outdated as we no longer require `setTracer` to enable tracing and support automatic span propagation where possible
- We've been seeing more and more issues with compatibility between core-tracing, OpenTelemetry, and applicationinsights and it was suggested by one of our customers to add a compatibility matrix to aid in resolving such issues
- FInally, Span#context -> Span#spanContext rename was particularly painful as it's used in TracingPolicy - a perfect storm of changes put us in a position where this error might keep coming up. 
I should note that even without any changes on our side, the above …

[core] - core-tracing compatibility matrix and README updates

---

README.md

In the main README.md, there was a small typo 8).

Rewrite typo libraies -> libraries in README.md

---

eng/tools/eng-package-utils/update-samples.js

Not all packages has samples-dev folder and samples update script fails with error if it is not present. PR adds check to gracefully exit the step if samples-dev is not present.

Skip updating samples if samples-dev is not present

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts
sdk/core/core-rest-pipeline/src/policies/bearerTokenAuthenticationPolicy.ts
sdk/core/core-rest-pipeline/test/bearerTokenAuthenticationPolicy.spec.ts

We have a guard in `bearerTokenAuthenticationPolicy` to make sure that the authorization header is not added when the endpoint is not `https`.
However we have a `PipelineRequestOptions` property that users can set to allow insecure connections. If this is not set core-rest-pipeline would refuse to send the request, however, if this option is true, the request is allowed.
`bearerTokenAuthenticationPolicy` doesn't take this option into account, this PR allows adding the authorization header when the option is set to true.
This problem surfaced when updating the CodeGen dependency on core-rest-pipeline as it runs against a local http server instance
Note: Python seems to have a similar check ([link](https://github.com/Azure/azure-sdk-for-python/blob/d27b0f6a49afa85d99994f052188d192a10c5f02/sd …

Add authorization header when allowInsecureConnection

---

common/config/rush/common-versions.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/quantum/quantum-jobs/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

1. Upgrade storage packages versions.
2. Update API version for storage-queue to 2020-10-02

Prepare for stg78 GA 

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/lroEngine/azureAsyncPolling.ts
sdk/core/core-lro/src/lroEngine/bodyPolling.ts
sdk/core/core-lro/test/utils/router/routesProcesses.ts

Currently, we are trying to call toLowerCase() on a response body.status. However, it is possible that the body has a status property that is not a string, and we crash.
This problem was surfaced when adding tests in the CodeGen

[core-lro] Check for string type before calling toLowerCase()

---

sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts
sdk/monitor/test-resources-post.ps1

- Turn off data ingestion tests using opentelemetry exporter till - https://github.com/Azure/azure-sdk-for-js/issues/17556 is resolved.

Monitor query test optimization

---

sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts

`serialize` currently returns a `Buffer` which is a NodeJS only thing. This PR changes this return type to `Uint8Array` instead because it is a standard JS type that will work anywhere. Note that under the hood we return a buffer because this package depends on `avsc` which is a NodeJS only package so we have to work with buffers internally anyway. However, we use the `Uint8Array` for the type here so that we are ready to jump to a Buffer-less avro implementation should one be available in the future and to be able to work with other JS platforms.
There is still a question on whether we should add extra serialize methods for other types as well but I will leave that to concrete customer asks for now.

[schema-registry-avro] serialize into JS's standard Uint8Array instead of Buffer

---

sdk/core/core-http/src/nodeFetchHttpClient.ts
sdk/core/core-http/test/defaultHttpClientTests.node.ts

The problem is that we only ever create one proxy agent and cache it, despite that different requests
could have different proxy settings.  This PR fixes the issue by using a cache of a map of <string, AgentCache>, 
with the string representation of proxy settings as the key.
Issue #16418

[core] fix incorrect caching of proxy agents

---

sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/context/context.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts

Fixes #17556
Remove AiApplicationVer as is not in spec yet.
Add hardcoded SDK ver to avoid issues where SDK package.json is not in expected location, added test to ensure value is updated when releasing new version.
Fix issue where Azure EventHub internal events type was not populated correctly

OpenTelemetry Exporter Fix issue loading SDK version

---

sdk/keyvault/test-resources.json

Updated test-resources.json as necessary to support Azure/azure-sdk-tools#1983.

[KeyVault] - Add provisioner OID to initial MHSM admins

---

eng/CredScanSuppression.json

in file sdk/communication/communication-common/README.md
The decoded jwt token doesn't contain any secrets:
```js
{"header": {"alg":"HS256","typ":"JWT"}, "payload": {"exp":3600}}
```
I had considered using `"<user token>"` or similar in the README samples but
still prefer the fake test token as customer can understand easily what is
expected in the code sample:
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/communication/communication-common/README.md#create-a-credential-with-a-static-token

[credscan] suppress fake test token  communication-common README

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/CHANGELOG.md
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/CHANGELOG.md
sdk/identity/identity-vscode/package.json
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/monitor/monitor-query/package.json

New PR, smaller than the big one I made: https://github.com/Azure/azure-sdk-for-js/pull/17580
This PR:
- Changes the Identity package versions to the next beta (meaning, from 1.0.0-beta.2 to 1.0.0-beta.3 and to 2.0.0-beta.6 t o 2.0.0-beta.7).
- Sets some packages to use 2.0.0-beta.7 of Identity. Namely: The Identity package, the Key Vault packages and the Monitor Query (I’ve asked @maorleger and @KarishmaGhiya for permission 😄).

[Identity] Version changes after the releases

---

eng/CredScanSuppression.json
sdk/storage/storage-blob/recordings/node/blobbatch/recording_deleteblobs_should_work_for_batch_delete.js
sdk/storage/storage-blob/recordings/node/blobbatch/recording_setblobsaccesstier_should_work_for_batch_set_tier.js
sdk/storage/storage-blob/test/utils/testutils.common.ts

The affected tests are still skipped due to dynamic GUIDs in blob batch requests
but this PR does the work to replace shared keys with a place holder which is
suppressed in credscan.

[credscan] add placeholder for blob batch test secrets

---

sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts

Related issue: https://github.com/Azure/azure-sdk-for-js/issues/17697
Let's throw instead of returning an undefined in `getSchema` and `getSchemaProperties`, since the [avro package will throw anyway](https://github.com/Azure/azure-sdk-for-js/blob/aced21f84bf4ac6c735b01a44e56022e096cc18e/sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts#L167-L170) and to be consistent with other languages.

[Schema Registry] No longer return an undefined and throw instead

---

sdk/appconfiguration/app-configuration/README.md

Adding `AZURE_AUTHORITY_HOST` and authentication to sovereign clouds in the readme as suggested by @ramya-rao-a. 
(As a followup of #17583)
Mostly copied from Container registry.

[App Config] Add AZURE_AUTHORITY_HOST in the readme

---

eng/scripts/Language-Settings.ps1
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/types/schema-registry-avro.shims.d.ts

Issue: https://github.com/Azure/azure-sdk-for-js/issues/17550
> @deyaaeldeen -- The docs system requires that the types .d.ts file be inside a folder. Example here: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/schemaregistry/schema-registry/package.json#L9
> Putting the types file inside a folder should unblock this part of the docs build.
This PR addresses this issue by moving the shim file to the `types` directory.

[Schema Registry Avro] Move the shim file to types

---

sdk/applicationinsights/applicationinsights-query/README.md
sdk/eventhub/mock-hub/samples/typescript/readme.md
sdk/operationalinsights/loganalytics/README.md
sdk/servicefabric/servicefabric/README.md
sdk/template/template/README-EXAMPLE.md

Now that we have a support policy around Node.js versions, issues were logged as part of a sweep of all the documentation to ensure we don't mentioned specific Node.js versions and instead point to the support policy. This PR does the needful for a handful of packages. Similar changes are needed for some arm packages that will be managed by the mgmt plane team. Another issue for Track 1 cognitive services is #17603 which will be handled separately
Fixes #17632
Fixes #17650
Fixes #17663
Fixes #17668
Fixes #17678

Remove references to specific Node.js versions in readmes

---

eng/pipelines/docindex.yml

This PR requires changes to eng/common -- https://github.com/Azure/azure-sdk-tools/pull/1852/files
Example of successful queuing of a pipeline -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1019544&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=dc056dfc-c0cf-5958-c8c4-8da4f91a3739

Use default branch when queueing build in docindex

---

sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/src/index.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/src/models/publicLogsModels.ts
sdk/monitor/monitor-query/src/models/publicMetricsModels.ts

- Make error types publicly exported
- make only one copy of function - "getMetricByName" in the interface

[monitor-query] fix what is publicly exported and make only one copy of function

---

sdk/schemaregistry/schema-registry-avro/samples-dev/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedSerializer.ts
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/samples-dev/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/samples/v1/javascript/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/schemaRegistrySample.js
sdk/schemaregistry/schema-registry/samples/v1/typescript/package.json
sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/conversions.ts
sdk/schemaregistry/schema-registry/src/index.ts
sdk/schemaregistry/schema-registry/src/models.ts
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts

Issue: https://github.com/Azure/azure-sdk-for-js/issues/17697
These renames were requested by the archboard.

[Schema Registry] Apply Archboard requested renames

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/bearerTokenAuthenticationPolicy.ts
sdk/core/core-rest-pipeline/test/bearerTokenAuthenticationPolicy.spec.ts

Re-enable HTTPS enforcement in bearerTokenPolicy

[core-rest-pipeline] Enforce HTTPS at `bearerTokenPolicy`

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts

[Identity] Removing null from the AzurePowerShellCredential getToken

---

sdk/monitor/monitor-query/README.md

Link to the service's docs on throttling/rate limiting instead of including the guidance in the Monitor Query SDK's README.

Link to Log Analytics throttling guidance from Monitor Query README

---

sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_can_read_cancel_and_delete_a_certificates_operation.json
sdk/keyvault/keyvault-certificates/recordings/node/certificates_client__create_read_update_and_delete/recording_can_read_cancel_and_delete_a_certificates_operation.js
sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts

- Automatically retry a certificate test that is known to be flaky up to 2 times (so 3 times total)
- Use the recorder.getUniqueName instead of the test name for the certificate name
- This test has been flaky for quite some time, and is known to fail when the service does not pick up the cancel operation job fast enough. This is both known and expected and the client should be resilient to such things. But in this case we are explicitly testing the error case and I did not want to remove that bit of safety
- Switching to using the recorder is IMO a preferred approach - and I have been doing that every time I re-record a test.
Resolves #17737 
Resolves #17599

[KeyVault] - Retry flaky test

---

eng/pipelines/templates/stages/archetype-js-release.yml

- Remove the need for safeName and let Devops generate a unique identifier since we only ever use the display name. This allows us to stop setting safeName in all our artifact lists, of course that clean-up is a separate set of work.
- When you are trying to queue a manual run DevOps sets Build.Reason to empty which blocks the full generation of stages in the stage selection UI. To work around this we check for Build.Reason empty or Manual. This allows for teams to uncheck a release stage for any packages that they don't plan to release.

Enable release stage selection at queue time

---

.github/CODEOWNERS
sdk/remoterendering/mixed-reality-remote-rendering/CHANGELOG.md

We haven't push an initial package for JS until now. We were waiting to push it at the same time as Python, but that has been delayed yet again, so let's just push this out, since we just pushed packages for Java and .net.

Prepare for an initial release of Azure Remote Rendering beta package

---

common/smoke-test/Initialize-SmokeTests.ps1

this fixes the issue with packages blocked for release due to not having samples folder for smoke tests.
===Edit===
No samples directory:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1107050&view=logs&j=66d14cf6-6122-58f9-3fdb-c50d455b9823&t=d0e17a21-7b52-5788-da92-bac4253f8e0f&l=162
With samples directory:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1107042&view=results

Accounting for packages without samples

---

sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/analyzeActionsResult.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

I edited the swagger to match most of the runtime responses we get now to get going with testing in [here](https://github.com/deyaaeldeen/azure-rest-api-specs/blob/textanalytics/v3.2-preview.2-patched/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.2-preview.2/TextAnalytics.json). 
- rename `projectName` to `project-name` in inputs
- rename `deploymentName` to `deployment-name` in inputs
- ~rename the input property `customSingleClassificationTasks` to `customClassificationTasks`~
~However for custom entities, there is a significant change and I did not attempt to resolve this yet in the swagger. For some reason, the service groups entities in the `matches` property by their category but it should flatten that into a list of entities instead.~

[Text Analytics] Add tests for Custom Text

---

sdk/keyvault/keyvault-keys/README.md

[Key Vault] - Add Key Rotation quickstart section

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/analyzeActionsResult.ts
sdk/textanalytics/ai-text-analytics/src/classifyDocumentMultiCategoriesResult.ts
sdk/textanalytics/ai-text-analytics/src/classifyDocumentMultiCategoriesResultArray.ts
sdk/textanalytics/ai-text-analytics/src/classifyDocumentSingleCategoryResult.ts
sdk/textanalytics/ai-text-analytics/src/classifyDocumentSingleCategoryResultArray.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/src/recognizeCustomEntitiesResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizeCustomEntitiesResultArray.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

API View: https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de?diffRevisionId=1d6eefc1d5554d08bbc44593306c97b2&doc=False&diffOnly=True
Updates the proposed names as follows:
- `customRecognizeEntities` to `recognizeCustomEntities`
- `customClassifyDocumentSingleCategory` to `classifyDocumentSingleCategory`
- `customClassifyDocumentMultipleCategories` to `classifyDocumentMultipleCategories`
That was based on the following arguments:
- custom as a prefix would improve the intelligence experience for finding all Custom Text capabilities. However, we agreed that the typical customer would like to try one particular action at a time so we hypothesize that the first thing they will type is `classify` or `recognize` instead of `custom`.
- we prefer …

[Text Analytics] Refine proposed API View

---

sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts
sdk/schemaregistry/schema-registry/test/utils/recordedClient.ts

Otherwise, the variables in the .env file will be loaded and their original values used instead of being rewritten to the dummay ones. Thanks @HarshaNalluru for helping investigating this!
Also, no need to call dotenv in the tests since the recorder does that for us.

[Schema Registry] Load tests env vars after recorder initialization

---

eng/pipelines/templates/stages/archetype-js-release.yml

Test build for integration stage: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1112714&view=results

Make PublishDocsToNightlyBranch depend on PublishPackages

---

.github/CODEOWNERS

Ownership is transitioning to a new team.

Update CODEOWNERS for Digital twins

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/src/transformations.ts
sdk/keyvault/keyvault-keys/test/internal/transformations.spec.ts

- Add `key_ops` to `JsonWebKey` model
- Mark `keyOps` as deprecated in `JsonWebKey`
As per [IETF rfc7517](https://datatracker.ietf.org/doc/html/rfc7517#section-4.3) the correct name for this field is `key_ops`... our TypeScript codegen will of course camelCase this
but snake_case is the expected convention.
I am only marking `keyOps` as deprecated in the JWK, and of course we will continue to populate it for 4.x, but this will
allow anyone to take the key material and use it where a JWK is expected without any conversions.
Resolves #17721

[KeyVault] - Add key_ops to JWK and deprecate keyOps

---

sdk/monitor/monitor-query/README.md

Update README file in response to changes introduced in https://github.com/Azure/azure-sdk-for-js/pull/17873

Apply Monitor Query README file updates

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
sdk/identity/identity/src/msal/browserFlows/browserCommon.ts
sdk/identity/identity/src/msal/nodeFlows/nodeCommon.ts
sdk/identity/identity/src/util/validateMultiTenant.browser.ts
sdk/identity/identity/src/util/validateMultiTenant.ts
sdk/identity/identity/test/internal/node/utils.spec.ts
sdk/identity/identity/test/internal/utils.spec.ts

Architects have decided that multi-tenant auth should be disabled by default, with two small caveats: If the environment variable `AZURE_IDENTITY_DISABLE_MULTITENANTAUTH` is provided, or if the original tenant is `adfs`.
Fixes #17913

[Identity] Removed allowMultiTenantAuthentication

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/samples-dev/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedSerializer.ts

Related issue: https://github.com/Azure/azure-sdk-for-js/issues/17697
Makes schema group optional since it is only needed to call `serialize` but not needed for `deserialize`.

[Schema Registry Avro] make schema group optional

---

sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts

https://github.com/microsoft/common-schema/pull/282
https://github.com/microsoft/common-schema/pull/285
https://github.com/microsoft/common-schema/pull/286/

[OpenTelemetry Exporter] Update AI mapping with latest spec changes

---

sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts

The docs have been moved
- from `https://github.com/Azure/AppConfiguration/blob/master/docs/REST/consistency.md`
- to `https://docs.microsoft.com/azure/azure-app-configuration/rest-api-consistency`
(Found by tracking the history in app-config repo.)
Fixes #16120

[App Config] update sync-token docs url from 404 to a valid url

---

sdk/identity/identity/test/manual/nodeTest.js
sdk/identity/identity/test/manual/nodeTestSilent.js
sdk/identity/identity/test/manual/package.json

The newer version of these packages cause new errors, so I’m sticking with the older ones just to have a more consistent experience over time. I’m also adding the new persistent cache plugin.

[Identity] Small improvements to the InteractiveBrowserCredential live tests

---

sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub-express/src/utils.ts
sdk/web-pubsub/web-pubsub-express/test/connect.spec.ts
sdk/web-pubsub/web-pubsub-express/test/user.spec.ts

Fix https://github.com/Azure/azure-sdk-for-js/issues/17300

Fix eslint for wps express

---

sdk/identity/identity/test/manual-integration/Kubernetes/package.json
sdk/identity/identity/test/manual-integration/Kubernetes/run_test.ts

Recently, a customer identified a build issue in our Kubernetes manual test. You can see their feedback here: https://github.com/Azure/azure-sdk/issues/814#issuecomment-927577042
This happens because we forgot to specify the typescript version we used to compile this project originally.
In this PR I’m fixing the TypeScript version to the latest one available, and I’m also fixing the types. In the future, this specific problem will not happen.
Feedback always appreciated 🙏

[Identity] Fixing types on the Kubernetes manual test

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/samples-dev/logsQuery.ts
sdk/monitor/monitor-query/samples-dev/logsQueryBatch.ts
sdk/monitor/monitor-query/samples-dev/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/samples/v1/javascript/logsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryBatch.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryMultipleWorkspaces.js
sdk/monitor/monitor-query/samples/v1/javascript/metricsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/package.json
sdk/monitor/monitor-query/samples/v1/typescript/package.json
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQuery.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryBatch.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/metricsQuery.ts
sdk/monitor/monitor-query/src/index.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/src/metricsQueryClient.ts
sdk/monitor/monitor-query/src/models/publicLogsModels.ts
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts

- Using a similar approach to Python by returning different types of result objects for each case
- The service team is concerned that if the user forgets to use the flag, how will they be notified that this is a partial failure case and not continue to blindly read the data from the result object. 
- This approach forces the user to be aware of the type of success scenario for the query as well as get the partial data by not just blindly "throwing" the error from the partial failure scenario.
Other changes:
- Updated the user agent to be same for both clients

update the error handling for Logs Query and Logs Query Batch

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

The canary cloud test matrix filters were created with the intent to only run a single test job for canary. The filter was a little too specific, and broke when [this change](https://github.com/Azure/azure-sdk-for-js/commit/072f7ab0b8bb3ba656071a3b3282c0b95576d519#diff-6d57a4119ae22b0fede4d3aab5dff565cee910416d4eaa647d83e1d749c9b559) updated the matrix such that there was no longer a matching entry for ubuntu+node10.
Since there is only one matching ubuntu entry with this filter anyway, remove the restrictive node 10 filter so it's more future proof.
CC @praveenkuttappan

Remove canary test matrix node verison filter

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/applicationCredential.browser.ts
sdk/identity/identity/src/credentials/applicationCredential.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.browser.ts
sdk/identity/identity/src/credentials/azureCliCredential.browser.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/src/credentials/azurePowerShellCredential.browser.ts
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.browser.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.browser.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.browser.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/onBehalfOfCredential.browser.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/credentials/visualStudioCodeCredential.browser.ts
sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
sdk/identity/identity/src/msal/nodeFlows/msalAuthorizationCode.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts

I’m re-ordering some of the comments to make things friendly for users exploring our API with their editors.
I also found a bug in the Azure CLI credential. I have added a unit test that verifies the fix.
Feedback always appreciated 🙏

[Identity] Fixes after manual tests

---

sdk/keyvault/keyvault-keys/test/README.md

In order to support Secure Key Release live tests we needed to deploy a mock attestation service that can be used to generate
and later verify test attestation tokens.
This commit just adds a bit of information to our tests README file in order to ensure some of that setup is documented.
While there, I also went ahead and cleaned up some of the existing docs.
Resolves #16919

[KeyVault] - Add information about SKR live tests

---

sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
sdk/schemaregistry/schema-registry/src/utils.ts
sdk/schemaregistry/schema-registry/test/public/schemaRegistry.spec.ts

Reverts https://github.com/Azure/azure-sdk-for-js/pull/17700 based on https://github.com/Azure/azure-sdk-for-js/pull/17700#issuecomment-922936430 so that we give the archboard more time to consider their ask to throw instead given the context of the customer request.

[Schema Registry] Return undefined on 404 codes

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/clientCertificateCredentialOptions.ts
sdk/identity/identity/src/credentials/clientSecretCredentialOptions.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/src/msal/nodeFlows/nodeCommon.ts
sdk/identity/identity/test/internal/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/internal/node/clientSecretCredential.spec.ts
sdk/identity/identity/test/public/node/clientSecretCredential.spec.ts

This PR removes regional authority support in a way that it is easy to add right after the GA.

[Identity] Disabling regional authority support

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/README.md

Prepares for release today by updating the changelog.

[Schema Registry] Update changelog

---

sdk/core/abort-controller/package.json

This PR re-enables the use of api extractor in the build step for the abort-controller package.
I no longer see the problems reported in #10320 
Fixes #10320

Re-enable api extractor when building abort-controller

---

sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/schemaRegistrySample.js
sdk/schemaregistry/schema-registry/samples/v1/typescript/package.json
sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/generated/generatedSchemaRegistryClientContext.ts

The release pipeline [failed](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1128167&view=logs&j=67f17e9b-03b6-51c5-9bc4-da06f41c4a76&t=67f17e9b-03b6-51c5-9bc4-da06f41c4a76) on smoke tests so I had to create the PR myself. The failure happened because the samples were not published but the post automation PR was supposed to do that and this PR does this. 
I talked to @praveenkuttappan about this.

[Schema Registry] Post release automation

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

After carefully reviewing the `ManagedIdentityCredential` code, I spotted that some of the changes made on 1.5.1 needed to be applied on v2. Specifically, the changes to the initial request to the IMDS MSI, which were made to v1.5.1 through this commit: https://github.com/Azure/azure-sdk-for-js/commit/e32af7d2a6e100af8d4eb5f1aed7e0888be39278
This PR includes a test change that verifies the fix.

[Identity] Caught up with POD Identity fix added on 1.5.1

---

common/tools/dev-tool/register.js

I upgraded dev-tool to use TypeScript 4.4.0, but this introduced a really weird issue where dev-tool would try to use a different version of TypeScript in its transforms than when it parses code, so samples running might not work if the package's TypeScript version was different from dev-tool's (the `kind` fields of syntax nodes are not stable, so for example an `ImportDeclaration` might be identified by `kind: 261` in one version of TypeScript and `kind: 260` in an older one if a new node was introduced, and so the parser and transforms have to agree about these IDs).
This change makes the dev-tool register.js module loader use the host package's TypeScript version.
@deyaaeldeen

[dev-tool] Use host package's TypeScript in module loader.

---

rush.json

- The fix in https://github.com/pnpm/pnpm/pull/3768 might address the mac build reliability issues we've been seeing

Update rush and pnpm

---

sdk/textanalytics/ai-text-analytics/samples-dev/customText.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsAction.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts

Add links to https://aka.ms/azsdk/textanalytics/customfunctionalities in Custom Text docstrings and sample.

[Text Analytics] Add links to Custom Text service docs

---

eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/platform-matrix.json
sdk/keyvault/keyvault-admin/platform-matrix.json
sdk/keyvault/keyvault-keys/platform-matrix.json

Similar to #7022 where we dropped support for Node.js 8, it is now time to drop support for Node.js 10
For more on this, please see our [support policy](https://github.com/Azure/azure-sdk-for-js/blob/master/SUPPORT.md#microsoft-support-policy)

Remove Node.js 10 from test matrix

---

sdk/batch/batch/package.json

Solves https://github.com/Azure/azure-sdk-for-js/issues/18428
Given that batch is a track 1 SDK and this script had caused problems before, as [mentioned here](https://github.com/Azure/azure-sdk-for-js/pull/18398#discussion_r738854204), `generate:client` has been removed from the package.json
CC: @deyaaeldeen

Remove generate:client script

---

sdk/containerregistry/container-registry/package.json
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

Related to #14581
In https://github.com/Azure/azure-sdk-for-js/pull/18463, we updated all samples to use GA of Identity v2
In https://github.com/Azure/azure-sdk-for-js/pull/18470, we updated devDependencies of Identity v2 beta to use Identity v2 GA
This PR removes the dependency overrides put in place for the reason (am guessing) that we wanted tests to use the beta v2 Identity, but not samples
Now that the samples are using v2, we no longer need the dependency overrides

Remove dependency overrides for Identity

---

sdk/communication/communication-callingserver/package.json
sdk/communication/communication-callingserver/recordings/browsers/delete_live_tests/recording_delete.json
sdk/communication/communication-callingserver/recordings/browsers/delete_live_tests/recording_invalid_file_delete.json
sdk/communication/communication-callingserver/recordings/browsers/delete_live_tests/recording_unauthorized_delete.json
sdk/communication/communication-callingserver/recordings/node/delete_live_tests/recording_delete.js
sdk/communication/communication-callingserver/recordings/node/delete_live_tests/recording_invalid_file_delete.js
sdk/communication/communication-callingserver/recordings/node/delete_live_tests/recording_unauthorized_delete.js
sdk/communication/communication-callingserver/review/communication-callingserver.api.md
sdk/communication/communication-callingserver/src/ContentDownloader.ts
sdk/communication/communication-callingserver/src/callingServerClient.ts
sdk/communication/communication-callingserver/src/models.ts
sdk/communication/communication-callingserver/src/utils/utils.ts
sdk/communication/communication-callingserver/test/public/deleteContent.spec.ts

Recording delete APIs in CallingServerClient

Recording delete APIs in CallingServerClient

---

sdk/keyvault/keyvault-keys/tests.yml

1. These changes enable key vault keys to run live tests against Public, UsGov and China.
2. Fix https://github.com/Azure/azure-sdk-for-js/issues/18414
3. Update file: keyvault-keys/tests.yml
Update to manage HSM tests in sovereign clouds
Pipeline results:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1167620&view=results
@benbp, @ramya-rao-a, @AlexGhiondea, @maorleger for notification.

Update key vault keys to enable live testing in sovereign clouds for multiple services

---

common/config/rush/pnpm-lock.yaml
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/samples-dev/keyRotation.ts
sdk/keyvault/keyvault-keys/src/index.ts

- Use Day.js in the Key Rotation sample
- Update the doc comments for Key Rotation
We discussed adding updating the API of Key Rotation to take an object instead
of a raw string for ISO8601 durations; however, with Temporal adding support for
Durations we want to avoid duplicating the type for now. Instead, we decided to
demonstrate interop with an existing 3rd party library. I chose Day.js for this
sample as it has a nice clean API.

[KeyVault] - Update duration sample and doc comments

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
sdk/core/core-rest-pipeline/src/interfaces.ts
sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/core/core-rest-pipeline/src/pipelineRequest.ts
sdk/core/core-rest-pipeline/src/xhrHttpClient.ts
sdk/core/core-rest-pipeline/test/browser/xhrHttpClient.spec.ts
sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts

In preparation to adding support for handling streams manually in @azure-rest/core-client, this PR adds an option to PipelineRequest to always get the raw stream

[core-rest-pipeline] Allow specifying any status response to get stream

---

sdk/identity/identity/test/manual/package.json
sdk/identity/perf-tests/identity/package.json

Related to #14581
A few cases of beta dependencies were missed in #18470 as they were not pinned as expected. This PR covers these cases and updates the Identity dependencies to use the GA versions

Update remaining beta dependencies on identity

---

sdk/search/search-documents/tests.yml

We are running into deployment issues with the search RP and deletion metadata. This switches our search deployments to a working region/subscription until their fix rolls out

Use working region/subscription for search deployments

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/recordings/browsers/tableserviceclient_sasconnectionstring_listtables/recording_should_list_a_specific_page_with_continuationtoken.json
sdk/tables/data-tables/recordings/browsers/tableserviceclient_tokencredential_listtables/recording_should_list_a_specific_page_with_continuationtoken.json
sdk/tables/data-tables/recordings/node/tableserviceclient_sasconnectionstring_listtables/recording_should_list_a_specific_page_with_continuationtoken.js
sdk/tables/data-tables/recordings/node/tableserviceclient_tokencredential_listtables/recording_should_list_a_specific_page_with_continuationtoken.js
sdk/tables/data-tables/review/data-tables.api.md
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/src/models.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts

This PR exposes continuation token to the PageResult when listing Tables with `TableServiceClient.listTables().byPage`. This change is similar to what we did in #18179 for `TableClient.listEntities`
This change is simpler than the one in `listEntities` because we just have a single continuationToken so we don't nee to encode the pair as we did for `listEntities`

[Tables] Expose continuation token on TableServiceClient.listTables

---

common/tools/dev-tool/src/commands/samples/publish.ts

@maorleger pointed out that dev-tool wasn't handling deep imports in samples. So for example with `dayjs`, the following wouldn't work:
`import duration from "dayjs/plugin/duration";`
The tool was only looking at the full module specifier and assumed it was the same as the package name, but for deep imports it's not the case. This PR teaches dev-tool to resolve these module specifiers to package names.

[dev-tool] Added support for deep imports in samples

---

sdk/agrifood/agrifood-farming-rest/package.json
sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/documenttranslator/ai-document-translator-rest/package.json
sdk/purview/purview-scanning-rest/package.json
sdk/synapse/synapse-access-control-rest/package.json

Last PR some had 2.0.0 and some 2.0.1. Updating so all of them depend on ^2.0.1

Make identity dependencies consistent across RLCs

---

sdk/core/core-rest-pipeline/CHANGELOG.md

Data was in the incorrect format, fixing it for release

[core-rest-pipeline] Fix Changelog date

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/connectionContext.ts

so that closing requests are fired immediately.

[ServiceBus] Use `Promise.all()` when closing connection context.

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1
eng/scripts/validate-docs-package.ps1

We plan to wrap the CI build command into docker image and use it to validate packages in docker. 
The PR is to replace the sanity check first. Will have a follow up PR for creating issues whenever the package got filtered out.
Here is the testing pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1174856&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739
Test on no image id:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1180723&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=bfb6cede-7671-5504-0a11-79b13ef63703

Use docker to validate packages in js docindex

---

sdk/web-pubsub/web-pubsub-express/README.md
sdk/web-pubsub/web-pubsub-express/samples/v1/javascript/server.js
sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/test/connect.spec.ts

Since now the service requires explicit "AllowAnonymous" set, there is no need for the SDK side to 401 connect request

Update connect event logic

---

sdk/identity/identity/test/public/node/caeARM.spec.ts

Before the PR with the CAE test was merged, I accidentally commented this line.

[Identity] The CAE test should only run in playback mode for now

---

common/tools/dev-tool/package.json
common/tools/eslint-plugin-azure-sdk/package.json
eng/tools/rush-runner.js
sdk/test-utils/perf/package.json
sdk/test-utils/recorder/package.json
sdk/test-utils/test-utils/package.json
sdk/test-utils/testing-recorder-new/package.json

Issue #18401 
`js - test-utils - ci` is not building/running tests for `sdk/test-utils/test-utils` and `sdk/test-utils/recorder-new`.
This PR 
- adds "utility" sdk-type check in the rush-runner to allow building/testing these packages, 
- distinguishes the packages under `sdk/test-utils` as "utility"
Fixes #18401

Adding "sdk-type": "utility" for `sdk/test-utils/*` packages

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/review/core-http.api.md
sdk/core/core-http/src/httpHeaders.ts
sdk/core/core-http/test/httpHeadersTests.ts
sdk/core/core-http/test/proxyAgent.node.ts

Porting fix from core-rest-pipeline #18517
- Add an option to `HttpHeaders.toJson()` allowing keeping the original header
key casing
- Fix `HttpHeaders.rawHeaders()` to preserve header key casing

[core-http] preserve header key casing

---

eng/pipelines/docindex.yml

The docindex pipeline failed at 60 min limitation.
Extend the timeout for short term solution.
For long term run, will try to install only non-existing packages.

Extend the timeout to 90 mins.

---

common/config/rush/pnpm-lock.yaml
sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/generated/generatedClientContext.ts
sdk/tables/data-tables/src/odata.ts
sdk/tables/data-tables/swagger/README.md
sdk/tables/data-tables/test/public/specialCharacters.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts

Across languages in the Tables SDK, [a bug was reported](https://github.com/Azure/azure-sdk-for-python/issues/20301) which causes round-tripping issues for table entities where the `PartitionKey` or `RowKey` values contain a single quote character.
This bug impacts any API where the partition/row key is used to format the URL - i.e. upsert, update and delete (note: not​ create, where these values only live in the payload).
For more information on the issue please see Azure/azure-sdk#3356
This fix introduces a runtime **breaking change** as the way we construct request URL when single quotes are present in the `partitionKey` or `rowKey`. Hence bumping the major version

[Tables] Fix quote encoding for Filter expressions in the URL

---

sdk/keyvault/keyvault-keys/tests.yml
sdk/keyvault/keyvault-secrets/tests.yml

1.These changes enable key vault secrets to run live tests against Public, UsGov and China.
2.Update file: sdk/keyvault/keyvault-secrets/tests.yml
Update to enable key vault secrets to run live tests against UsGov and China.
Pipeline results:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1167867&view=results
@benbp, @ramya-rao-a, @AlexGhiondea, @maorleger for notification.

Update key vault secrets to enable live testing in sovereign clouds for multiple services

---

sdk/formrecognizer/ai-form-recognizer/MIGRATION-v3_v4.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts

Caught this stuff running through the release checklist. It changes references to 4.0.0-beta.1 either to generic references to version 4 or references to 4.0.0-beta.2 as appropriate in the text and generated code.

[ai-form-recognizer] Remove/update direct references to beta.1

---

eng/common/scripts/Save-Package-Properties.ps1
eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/steps/test.yml
sdk/test-utils/ci.yml

Doing similar to what has been done in GO.

[In Progress] TestProxy with a switch to start

---

sdk/eventgrid/eventgrid/README.md

The CNCF moved some files around in their specs repository, which
broken this link. Use a versioned URL instead of pointing at their
main development branch so this doesn't happen again in the future.

[EventGrid] Fix link in README.md

---

sdk/schemaregistry/schema-registry/samples-dev/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/generated/models/index.ts
sdk/schemaregistry/schema-registry/src/generated/models/mappers.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schema.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schemaGroupsOperations.ts
sdk/schemaregistry/schema-registry/swagger/README.md
sdk/schemaregistry/schema-registry/test/public/schemaRegistry.spec.ts

- Regenerate using the swagger in https://github.com/Azure/azure-rest-api-specs/pull/16738
- Update samples so the schema name does not include `.`s, as enforced by client-side validation specified by the swagger

[Schema Registry] Regenerate with improved swagger

---

sdk/tables/data-tables/review/data-tables.api.md
sdk/tables/data-tables/src/index.ts

This adds the `RestError` class that can be thrown by the library to the exports so that consumers can more easily catch and perform `instanceof` checks on thrown errors.
This is the convention with [@azure/storage-blob](https://github.com/Azure/azure-sdk-for-js/blob/681c9b9e364d9bc2cbc7a7cbf418165bde02fc84/sdk/storage/storage-blob/src/index.ts#L59) and [@azure/storage-queue](https://github.com/Azure/azure-sdk-for-js/blob/681c9b9e364d9bc2cbc7a7cbf418165bde02fc84/sdk/storage/storage-queue/src/index.ts#L28)

[tables] Add RestError export

---

sdk/core/core-client/src/urlHelpers.ts

@qiaozha has recently reported that during the testing of `beginCreateOrUpdateAndWait` operation in the `@azure/arm-iothub` library. During the testing, the code is erroring out with the message:
```
(node:17412) UnhandledPromiseRejectionWarning: TypeError: value is not iterable
at appendQueryParams (C:\Users\sarajama\Projects\temp\node_modules\@azure\core-client\dist\index.js:1343:40)
```
On analysis, I found that the value is undefined which is causing the error. Adding a check resolves the issue. 
@xirzec Could you please review and approve the PR? TIA

Check is value is undefined in appendQueryParams

---

sdk/tables/data-tables/CHANGELOG.md

Update release date in Changelog

[Tables] Update changelog date

---

common/config/rush/pnpm-lock.yaml

I felt the need to open this PR because all the identity version updates done previously aren't reflected in the pnpm-lock file. The single command `rush update` is not updating the pnpm lock file with the correct dependency version even after dependency's major version upgrade

rush update --recheck since rush update is broken

---

sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/schemaRegistrySample.js
sdk/schemaregistry/schema-registry/samples/v1/typescript/package.json
sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/generated/generatedSchemaRegistryClientContext.ts
sdk/schemaregistry/schema-registry/swagger/README.md

v1.0.0 went out but the post automation PR was not created because of an expected failure related to versioning in the serializer package so I created it manually.

[Schema Registry] Post-release stuff

---

sdk/keyvault/test-resources.json

Moving the Managed HSM to the same location as our resource group now that the
limits have been expanded.

[KeyVault] - Move MHSM to resource group location

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/batchingPartitionChannel.ts
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/src/impl/awaitableQueue.ts
sdk/eventhub/event-hubs/src/impl/partitionAssigner.ts
sdk/eventhub/event-hubs/src/impl/patitionKeyToIdMapper.ts
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/src/util/getPromiseParts.ts
sdk/eventhub/event-hubs/test/internal/impl/awaitableQueue.spec.ts
sdk/eventhub/event-hubs/test/internal/impl/mapPartitionKeyToId.spec.ts
sdk/eventhub/event-hubs/test/public/eventHubBufferedProducerClient.spec.ts
sdk/eventhub/event-hubs/test/public/hubruntime.spec.ts
sdk/eventhub/event-hubs/tsconfig.json
sdk/eventhub/mock-hub/src/services/eventHubs.ts

Merging the feature branch into main.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/17699

[Event Hubs] Merge feature branch for buffered producer

---

sdk/eventhub/event-hubs/CHANGELOG.md

I will be releasing today after I talked with @ramya-rao-a. I will merge this PR after https://github.com/Azure/azure-sdk-for-js/pull/18590.

[Event Hubs] Prepare release

---

eng/tools/rush-runner.js

Identity pipeline is timing out after 1 hour since it tries to build and test every packages in the repo.

Build and test predefined set of packages only in identity pipelines

---

sdk/cosmosdb/ci.yml

#18667 damaged this file, and this PR restores it. The cosmosdb data-plane CI currently cannot run.
CC @colawwj @qiaozha

[cosmosdb] Restore damaged ci.yml

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry/CHANGELOG.md

To release a patch that does not have client-side validation of schema names. See https://github.com/Azure/azure-sdk-for-js/pull/18666/ for more details.

[Schema Registry] Prepare patch release

---

sdk/test-utils/recorder-new/package.json
sdk/test-utils/recorder/package.json
sdk/test-utils/testing-recorder-new/package.json

Resolving [this comment](https://github.com/Azure/azure-sdk-for-js/pull/18707#discussion_r750815462) from PR #18707.
Minor change in @types/mock-fs dependency version, changing `~4.13.1` to `^4.13.1`.

Nit: Change ~ to ^ in @types/mock-fs dev dependency version

---

eng/pipelines/templates/stages/platform-matrix.json

Solves https://github.com/Azure/azure-sdk-for-js/issues/18447
Added `17.x` to the `NodeTestVersion` array.
Creating this PR to ensure that all the tests pass

Add NodeJS version 17.x to test matrix

---

sdk/keyvault/test-resources.json

- Remove access permissions from ARM template
- Switch to RBAC based permission model for KV
Due to a recent permission that was added on the service side, our nightly tests
started failing as the ARM template has not been updated with the new
permission. Instead of adding the permissions, Heath noticed that we can switch
to RBAC roles now and avoid having to chase these things are they're added.
This commit just ports that over to Azure SDK for JS.

[KeyVault] - Use RBAC for permissions

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/options/FormRecognizerClientOptions.ts

This changes `FormRecognizerCommonClientOptions` to inherit from `CommonClientOptions` instead of `PipelineOptions`. This gives us a couple more options in the client constructor that were missing.

[ai-form-recognizer] Use CommonClientOptions

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

This PR updates the version for `json-schema` to fix the dependabot alert

Fix dependabot alert for json-schema

---

common/tools/eslint-plugin-azure-sdk/tests/plugin.ts

`ts-no-namespaces` has been deleted so this PR removes it from the list of the rules to be tested.

[ESLint Plugin] Fix list of rules

---

sdk/appconfiguration/app-configuration/samples-dev/secretReference.ts
sdk/appconfiguration/app-configuration/samples/v1/javascript/secretReference.js
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/secretReference.ts
sdk/appconfiguration/app-configuration/test/public/secretReference.spec.ts

The main change is that the `secretId` in the sample is updated from `random_string` to `https://vault_name.vault.azure.net/secrets/random_string`
- Updated the generated samples too
- Leveraging `parseKeyVaultSecretIdentifier` to parse the `secretId` to get the name and vault url
- This makes the sample consistent with .NET
- Did some refactoring as the sample became huge

[App Config] Secret reference sample update

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json

~What if we release @azure/core-client 1.3.3 tomorrow? 🙂~
Changed this PR to upgrade the version of core-client to 1.4.0 since CAE support is a new thing entirely, not a patch to something already in this package.

[core-client] Version to 1.4.0

---

sdk/identity/identity/package.json

Our internal tests will only pass if we point to 1.4.0
The caveat of this PR is that we won’t be able to release Identity before @azure/core-client, but that should be fine according to our plans anyway.
Please let me know if I’m wrong. Feedback always appreciated!

[Identity] Update core-client to ^1.4.0

---

sdk/core/core-client/CHANGELOG.md

Updating the Changelog to include query param check changes.
@sadasant @deyaaeldeen @ramya-rao-a @jeremymeng Please review and approve the PR. Thanks

Update Changelog to include query param check

---

sdk/cognitiveservices/cognitiveservices-face/package.json
sdk/cognitiveservices/cognitiveservices-face/src/faceClientContext.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/faceListOperationsMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/largeFaceListOperationsMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/largePersonGroupOperationsMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/largePersonGroupPersonMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/parameters.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/personGroupOperationsMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/models/personGroupPersonMappers.ts
sdk/cognitiveservices/cognitiveservices-face/src/operations/face.ts
sdk/cognitiveservices/cognitiveservices-face/src/operations/faceListOperations.ts
sdk/cognitiveservices/cognitiveservices-face/src/operations/largeFaceListOperations.ts
sdk/cognitiveservices/cognitiveservices-face/src/operations/largePersonGroupOperations.ts
sdk/cognitiveservices/cognitiveservices-face/src/operations/personGroupOperations.ts

A new `data-plane` SDK release request for the Face SDK has been created at https://github.com/Azure/sdk-release-request/issues/2251. This PR is to support that request. 
The following command has been used to generate the SDK:
```
autorest --version:2.0.4417 --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=. --use=@microsoft.azure/autorest.typescript@4.2.2 --package-version=5.0.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/b280ba25a2cc02d8174b43ed6a84ea1953a83f27/specification/cognitiveservices/data-plane/Face/readme.md
AutoRest code generation utility [cli version: 3.0.6339; node: v14.15.4, max-memory: 4096 MB]
There is a new version of AutoRest available (3.5.1).
> You can install …
```

Release For Face Recognition Quality Score

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/common/logger.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/defaultQueryExecutionContext.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContextBase.ts
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts

- Removed old logging
- Implement Azure core logging coverage for
-ClientContext logging
-ParallelQueryExecutionContextBase logging
-RequestHandler logging

Removed old logging and implement Azure core logging coverage

---

common/tools/dev-tool/package.json
common/tools/dev-tool/src/commands/index.ts
common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts
common/tools/dev-tool/src/commands/samples/prep.ts
common/tools/dev-tool/src/commands/samples/publish.ts
common/tools/dev-tool/src/commands/samples/run.ts
common/tools/dev-tool/src/commands/samples/tsToJs.ts
common/tools/dev-tool/src/commands/test-proxy/start.ts
common/tools/dev-tool/src/commands/test-proxy/waitForProxyEndpoint.ts
common/tools/dev-tool/src/config/rollup.base.config.ts
common/tools/dev-tool/src/framework/CommandModule.ts
common/tools/dev-tool/src/templates/sampleReadme.md.ts
common/tools/dev-tool/src/util/checkWithTimeout.ts
common/tools/dev-tool/src/util/findMatchingFiles.ts
common/tools/dev-tool/src/util/sampleConfiguration.ts
common/tools/dev-tool/src/util/testProxyUtils.ts
common/tools/dev-tool/src/util/testUtils.ts
common/tools/dev-tool/test/framework.spec.ts
common/tools/dev-tool/test/samples/skips.spec.ts

This fixes #17826 for `common\tools\dev-tool`.
I basically fixed errors such as `missing return type`, `unused escape character`, etc. for `ts` files in `common\tools\dev-tool`.
However, I didn't manage to fix [Forbidden non-null assertion](https://github.com/typescript-eslint/typescript-eslint/blob/v4.19.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md) warnings in `src\commands\samples\publish.ts` and `src\util\testProxyUtils.ts`. I try to mute the warning by doing type checking `object !== undefined` according to [TSLint](https://palantir.github.io/tslint/rules/no-non-null-assertion/) but to not avail. May I get help on this?
I will remove the required snippet `-f html -o <package name>-lintReport.html || exit 0` from `package.json` once the above-mentioned warning is …

[Issue 17826] Fix ES Lint errors in common\tools\dev\tool

---

sdk/test-utils/recorder-new/CHANGELOG.md
sdk/test-utils/recorder-new/package.json
sdk/test-utils/recorder-new/src/index.ts
sdk/test-utils/recorder-new/src/recorderAADCredential.ts
sdk/test-utils/testing-recorder-new/karma.conf.js
sdk/test-utils/testing-recorder-new/package.json
sdk/test-utils/testing-recorder-new/recordings/browsers/noop_credential_with_tables/recording_should_create_new_table_then_delete.json
sdk/test-utils/testing-recorder-new/recordings/node/noop_credential_with_tables/recording_should_create_new_table_then_delete.json
sdk/test-utils/testing-recorder-new/test/noOpCredentialTest.spec.ts

If the AAD credentials don't take the recorder httpClient option, the AAD traffic won't be recorded.
In this case, we'll need to bypass the AAD requests with no-ops in playback(since there are no recorded requests to match).
This PR provides the No-op AAD credential for playback as part of recorder-new.
The current plan is to provide both ways of recording the AAD tests - with and without recording AAD traffic
- NoOp credential  https://github.com/Azure/azure-sdk-for-js/pull/18896 - where the services/SDKs don't care about the AAD traffic
- .NET and Python follow this model for all their services/SDKs 
- RecorderHttpClient for AAD - https://github.com/Azure/azure-sdk-for-js/pull/18898 - for the Services/SDKs that would want to see the AAD traffic in their tests
- We had seen some value in …

[Unified Recorder] NoOp AAD Credential in playback

---

sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/instrumenter.ts
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracingClient.ts
sdk/core/core-tracing/test/instrumenter.spec.ts
sdk/core/core-tracing/test/tracingClient.spec.ts
sdk/core/core-tracing/test/tracingContext.spec.ts
sdk/instrumentation/instrumentation-opentelemetry/src/instrumenter.ts
sdk/instrumentation/instrumentation-opentelemetry/src/transformations.ts
sdk/instrumentation/instrumentation-opentelemetry/test/public/instrumenter.spec.ts

- Add a type for PackageInformation
- Pass namespace and packageInformation as positional params to createTracingClient
- Pass packageInformation as a positional param to `Instrumenter#startSpan`
When we discussed the API design for this, @lmolkova mentioned that ideally we'd require information about the package 
invoking the trace to ensure that data is passed along correctly to AZ Monitor. It was originally optional, and as part of the 
options bag for `createTracingClient` function.
But I accidentally made it "optionally required" on the Instrumenter level. Example:
```ts
instrumenter.startSpan("name") // OK
instrumenter.startSpan("name", {}) // Error: missing required packageInformation or something like that
```
Correcting this now. Also, required params should be positional right? …

[core] - Ensure package information is provided for traces

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-table/package.json

Remove assert dev dependency from Event Hubs

---

sdk/servicebus/service-bus/package.json

Remove assert dev dependency from Service Bus

---

sdk/web-pubsub/web-pubsub-express/package.json

Remove assert dev dependency from Web-pubsub

---

sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/package.json

Remove assert dev dependency from Identity

---

sdk/appconfiguration/app-configuration/package.json

Remove assert dev dependency from App Configuration

---

sdk/communication/communication-chat/package.json
sdk/communication/communication-common/package.json
sdk/communication/communication-identity/package.json
sdk/communication/communication-network-traversal/package.json
sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-short-codes/package.json
sdk/communication/communication-sms/package.json

Remove assert dev dependency from Communication

---

sdk/tables/data-tables/README.md
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TablePolicies.ts
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/src/logger.ts
sdk/tables/data-tables/src/models.ts
sdk/tables/data-tables/src/sas/accountSasSignatureValues.ts
sdk/tables/data-tables/src/sas/generateAccountSas.ts
sdk/tables/data-tables/src/sas/generateTableSas.ts
sdk/tables/data-tables/src/sas/sasQueryParameters.ts
sdk/tables/data-tables/src/sas/tableSasSignatureValues.ts
sdk/tables/data-tables/src/serialization.ts
sdk/tables/data-tables/src/tablesNamedCredentialPolicy.ts
sdk/tables/data-tables/src/tablesSASTokenPolicy.ts
sdk/tables/data-tables/src/utils/continuationToken.ts
sdk/tables/data-tables/src/utils/errorHelpers.ts
sdk/tables/data-tables/src/utils/internalModels.ts
sdk/tables/data-tables/src/utils/isCredential.ts
sdk/tables/data-tables/test/internal/serialization.spec.ts
sdk/tables/data-tables/test/internal/sharedKeyCredential.spec.ts
sdk/tables/data-tables/test/internal/utils.spec.ts
sdk/tables/data-tables/test/public/accessPolicy.spec.ts
sdk/tables/data-tables/test/public/createTable.spec.ts
sdk/tables/data-tables/test/public/specialCharacters.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts
sdk/tables/data-tables/test/public/transaction.spec.ts
sdk/tables/data-tables/test/public/utils/recordedClient.ts

This PR fixes 3 issues around `createTable`
* Adds documentation noting that `createTable` doesn't throw on `TableAlreadyExists` response. And document a sample on how to check for such a response.
* `onResponse` callback was not executed when handling `TableAlreadyExists`
* `TableBeingDeleted` errors were sneaking into the `TableAlreadyExists` handling. Explicitly check for error code and statusCode to make sure we only no-throw for `TableAlreadyExists`
Related to #18865

[Tables] Call onResponse when handling TalbeAlreadyExists response

---

sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts

- Add comment about CertificateProperties#version which can only be populated by
the service
- Add explanation for updating the latest version of a certificate using an
empty version string
When updating some of our samples, Dina noticed a few things that can lead to
confusion. 
The first is that `version` is both a positional param _and_ part of
the `CertificateProperties` param. It's not clear which to use and its due to us
using the same model for both input and output types here.
The second is that version is technically required but not really - a user can
pass an empty string to update the latest version of a certificate. This is
common across all KV APIs but we did not make it truly optional.
Since these would be breaking changes, and no customers have yet to complain
about this, …

[KeyVault] - Clarify certificate version properties

---

sdk/core/core-client/package.json

**TL;DR** - Nightly builds are broken because core-client now depends on a property not existing in the latest published in NPM. Updating the dependency on core-rest-pipeline so that nightly ci links to the same alpha version of core-rest-pipeline.
**Details**
Core pipeline nightly builds are failing with the following error:
> src/authorizeRequestOnClaimChallenge.ts(67,37): error TS2339: Property 'logger' does not exist on type 'AuthorizeRequestOnChallengeOptions'.
test/authorizeRequestOnClaimChallenge.spec.ts(383,7): error TS2345: Argument of type '{ getAccessToken(scopes: string[], getTokenOptions: GetTokenOptions): Promise<{ token: string; expiresOnTimestamp: number; }>; scopes: never[]; response: { ...; }; request: PipelineRequest; logger: any; }' is not assignable to parameter of …

[core-client] Fix Core client nightly

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/tokenExchangeMsi.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

A customer recently reported that their AKS application was failing because the token being used became expired after a while. After inspecting their code and logs, I thought that perhaps it was that the expiration date that we were providing from Identity to the HTTP pipelines was wrong.
The `tokenExchangeMsi` is special because it first reads from `AZURE_FEDERATED_TOKEN_FILE`’s in order to retrieve an assertion that then gets used to retrieve a token from AAD. While developing this MSI, I assumed the expiration date would come similarly to other MSIs, however other MSIs retrieve the tokens from the MSI service, which is different from the AAD service.
- Other MSIs, like the `imdsMsi`, use the IMDS endpoint https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/src/cred …

[Identity] Fixing wrong expiration date on the tokenExchangeMsi

---

eng/pipelines/aggregate-reports.yml

Moving https://github.com/Azure/azure-sdk-for-js/pull/19004 to a branch off the main repo. 
The `aggregate-reports.yml` pipeline restricts usage of some service connections and will fail if not run from a branch off the main repo.

Fix aggregate-reports.yml

---

.github/CODEOWNERS

Updating the contacts for the Cosmos + Service Attention label pairing without disrupting the assignments for pull requests.

CODEOWNERS:  Updating Cosmos Contacts

---

sdk/core/core-lro/src/lroEngine/azureAsyncPolling.ts
sdk/core/core-lro/src/lroEngine/bodyPolling.ts
sdk/core/core-lro/src/lroEngine/lroEngine.ts
sdk/core/core-lro/src/lroEngine/operation.ts
sdk/core/core-lro/src/lroEngine/stateMachine.ts
sdk/core/core-lro/test/abort.spec.ts
sdk/core/core-lro/test/engine.spec.ts
sdk/core/core-lro/test/testClient.spec.ts
sdk/core/core-lro/test/utils/coreRestPipelineLro.ts
sdk/core/core-lro/test/utils/router.ts
sdk/core/core-lro/test/utils/router/paramRoutes.ts
sdk/core/core-lro/test/utils/router/routesProcesses.ts
sdk/core/core-lro/test/utils/router/routesTable.ts
sdk/core/core-lro/test/utils/router/utils.ts
sdk/core/core-lro/test/utils/testClient.ts
sdk/core/core-lro/test/utils/testNonCancellablePoller.ts
sdk/core/core-lro/test/utils/testOperation.ts
sdk/core/core-lro/test/utils/testPoller.ts
sdk/core/core-lro/test/utils/testServiceClient.ts
sdk/core/core-lro/test/utils/testTokenCredential.ts
sdk/core/core-lro/test/utils/testWebResource.ts

In this PR, I have fixed all files under ```sdk/core/core-lro```.

[sort-imports] update ```core-lro``` with respect to ```sort-imports``` rule

---

sdk/core/core-crypto/test/internal/browser/base64.spec.ts
sdk/core/core-crypto/test/public/browser/webworker-runner.spec.ts
sdk/core/core-crypto/test/public/sha256.spec.ts

This PR is working in conjunction with other PRs to fix individual sections of the azure codebase with respect to the new ```sort-imports``` rule, as indicated in #9252 
In this PR, I have fixed all files under ```sdk/core/core-crypto```.

[sort-imports] update ```core-crypto``` with respect to ```sort-imports``` rule

---

sdk/core/core-tracing/src/createSpan.ts
sdk/core/core-tracing/test/createSpan.spec.ts
sdk/core/core-tracing/test/interfaces.spec.ts
sdk/core/core-tracing/test/traceParentHeader.spec.ts
sdk/core/core-tracing/test/util/testSpan.ts
sdk/core/core-tracing/test/util/testTracer.ts

This PR is working in conjunction with other PRs to fix individual sections of the azure codebase with respect to the new ```sort-imports``` rule, as indicated in #9252 
In this PR, I have fixed all files under ```sdk/core/core-tracing```.

[sort-imports] update ```core-tracing``` with respect to ```sort-imports``` rule

---

sdk/core/core-paging/src/getPagedAsyncIterator.ts

In this PR, I have fixed all files under ```sdk/core/core-paging```.

[sort-imports] update ```core-paging``` with respect to ```sort-imports``` rule

---

sdk/core/core-util/test/browser/isNode.spec.ts
sdk/core/core-util/test/delay.spec.ts
sdk/core/core-util/test/node/isNode.spec.ts

In this PR, I have fixed all files under ```sdk/core/core-util```.

[sort-imports] update ```core-util``` with respect to ```sort-imports``` rule

---

sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TablePolicies.ts
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/src/models.ts
sdk/tables/data-tables/src/sas/accountSasSignatureValues.ts
sdk/tables/data-tables/src/sas/generateAccountSas.ts
sdk/tables/data-tables/src/sas/generateTableSas.ts
sdk/tables/data-tables/src/sas/sasQueryParameters.ts
sdk/tables/data-tables/src/sas/tableSasSignatureValues.ts
sdk/tables/data-tables/src/serialization.ts
sdk/tables/data-tables/src/tablesNamedCredentialPolicy.ts
sdk/tables/data-tables/src/tablesSASTokenPolicy.ts
sdk/tables/data-tables/src/utils/accountConnectionString.browser.ts
sdk/tables/data-tables/src/utils/accountConnectionString.ts
sdk/tables/data-tables/src/utils/connectionString.ts
sdk/tables/data-tables/src/utils/errorHelpers.ts
sdk/tables/data-tables/src/utils/internalModels.ts
sdk/tables/data-tables/test/internal/odata.spec.ts
sdk/tables/data-tables/test/internal/serialization.spec.ts
sdk/tables/data-tables/test/internal/sharedKeyCredential.spec.ts
sdk/tables/data-tables/test/internal/tableTransaction.spec.ts
sdk/tables/data-tables/test/internal/utils.spec.ts
sdk/tables/data-tables/test/public/accessPolicy.spec.ts
sdk/tables/data-tables/test/public/createTable.spec.ts
sdk/tables/data-tables/test/public/specialCharacters.spec.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts
sdk/tables/data-tables/test/public/transaction.spec.ts
sdk/tables/data-tables/test/public/utils/recordedClient.ts

In this PR, I have fixed all files under ```sdk/tables/data-tables```.

[sort-imports] update ```data-tables``` with respect to ```sort-imports``` rule

---

sdk/textanalytics/ai-text-analytics/samples-dev/modelVersion.ts
sdk/textanalytics/ai-text-analytics/samples/v5/javascript/README.md
sdk/textanalytics/ai-text-analytics/samples/v5/javascript/modelVersion.js
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/README.md
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/modelVersion.ts

@assafi asked for a sample to set model versions so this PR adds one.

[Text Analytics] Add a sample for model versions

---

sdk/test-utils/recorder-new/recordings/browsers/proxy_tool/recording_sample_response.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_bodykeysanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_bodyregexsanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_continuationsanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_generalregexsanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_headerregexsanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_removeheadersanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_uriregexsanitizer.json
sdk/test-utils/recorder-new/recordings/browsers/proxy_tool_sanitizers/recording_urisubscriptionidsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool/recording_sample_response.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool/recording_sample_response_with_random_string_in_path.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_bodykeysanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_bodyregexsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_continuationsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_generalregexsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_headerregexsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_removeheadersanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_uriregexsanitizer.json
sdk/test-utils/recorder-new/recordings/node/proxy_tool_sanitizers/recording_urisubscriptionidsanitizer.json
sdk/test-utils/recorder-new/test/testProxyTests.spec.ts

Resolves #18220
Do we need additional tests beyond this one? Let me know and I can add them.

[Unified Recorder] Re-enable ContinuationSanitizer tests

---

sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts

As seen in #18506, we point to docs for update-queue and update-topic APIs that are now deprecated. This PR removes pointers to these to avoid confusion

Avoid pointing to docs that are misleading about API deprecation

---

eng/pipelines/templates/stages/archetype-js-release.yml

We have added basic validation before release doc in release pipeline and unified pipeline.
The PR is to use docker image for full validation.
Testing pipeline:
release: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1241072&view=results
unified: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1241077&view=results

Add docker on release pipeline and unified pipeline

---

sdk/core/logger/src/log.ts
sdk/core/logger/test/debug.spec.ts

In this PR, I have fixed all files under ```sdk/core/logger```.

[sort-imports] update ```logger``` with respect to ```sort-imports``` rule

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/tables/data-tables/src/sas/generateTableSas.ts
sdk/tables/data-tables/src/sas/tableSasSignatureValues.ts
sdk/tables/data-tables/test/internal/browser/generateSas.browser.spec.ts
sdk/tables/data-tables/test/internal/node/generateSas.spec.ts

When creating a SAS token with using a `signedIdentifier` the access policy is stored in the service making `expiresOn` and `permissions` optional.
**Problem**
As reported in #18985, we are always setting default values for these, plus we were setting an invalid value for table level permissions "rl".
**Fix**
Only set defaults if the values were not provided and `signedIdentifier` was not provided either

[Tables] Honor expiresOn and permissions optionality

---

sdk/keyvault/keyvault-admin/src/accessControlClient.ts
sdk/keyvault/keyvault-admin/src/accessControlModels.ts
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/challengeAuthenticationCallbacks.ts
sdk/keyvault/keyvault-admin/src/lro/backup/operation.ts
sdk/keyvault/keyvault-admin/src/lro/backup/poller.ts
sdk/keyvault/keyvault-admin/src/lro/keyVaultAdminPoller.ts
sdk/keyvault/keyvault-admin/src/lro/restore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/restore/poller.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveKeyRestore/operation.ts
sdk/keyvault/keyvault-admin/src/lro/selectiveKeyRestore/poller.ts
sdk/keyvault/keyvault-admin/src/mappings.ts
sdk/keyvault/keyvault-admin/src/tracingHelpers.ts

In this PR, I have fixed all files under ```sdk/keyvault/keyvault-admin```.

[sort-imports] update ```keyvault-admin``` with respect to ```sort-imports``` rule

---

sdk/core/abort-controller/src/AbortController.ts
sdk/core/abort-controller/test/aborter.spec.ts

This PR is working in conjunction with other PRs to fix individual sections of the azure codebase with respect to the new ```sort-imports``` rule, as indicated in #9252 
In this PR, I have fixed all files under ```sdk/core/abort-controller```.

[sort-imports] update ```abort-controller``` with respect to ```sort-imports``` rule

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/test/public/functional/client.spec.ts

The only notable difference in the new versions of `node-abort-controller` is around the default imports. See the [changelog](https://github.com/southpolesteve/node-abort-controller/blob/master/CHANGELOG.md)
Resolves #17779

Update node-abort-controller version

---

sdk/storage/storage-blob/MigrationGuide.md
sdk/storage/storage-file-share/MigrationGuide.md
sdk/storage/storage-queue/MigrationGuide.md

Add migration guide from v2 to v12 storage packages: @azure/storage-blob, @azure/storage-file-share, @azure/storage-queue.

[storage] Add migration guide for storage packages

---

eng/pipelines/weekly_automation.yml
eng/scripts/check-external-dependency.ps1

New task in weekly automation pipeline to find and file issues for any external package dependency.

Automate filing issues for any external package dependency 

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

Extending https://github.com/Azure/azure-sdk-for-net/pull/25589 to other repos.

Remove canary from default weekly live testing clouds

---

sdk/eventhub/ci.yml
sdk/eventhub/event-processor-host/package.json

This is a follow up from https://github.com/Azure/azure-sdk-for-js/pull/19250
A clean up was needed in ci.yml file and the removal of sdk-type so that CI does not try to find event-processor-host

Remove event-processor-host from ci.yml and the sdk-type

---

sdk/appconfiguration/app-configuration/rollup.base.config.js
sdk/appconfiguration/app-configuration/test/internal/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
sdk/appconfiguration/app-configuration/test/internal/package.spec.ts
sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
sdk/appconfiguration/app-configuration/test/public/auth.spec.ts
sdk/appconfiguration/app-configuration/test/public/etags.spec.ts
sdk/appconfiguration/app-configuration/test/public/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/public/index.spec.ts
sdk/appconfiguration/app-configuration/test/public/throwOrNotThrow.spec.ts
sdk/appconfiguration/app-configuration/test/public/utils/testHelpers.ts

This is a follow up for https://github.com/Azure/azure-sdk-for-js/pull/18930 and solves issue https://github.com/Azure/azure-sdk-for-js/issues/17110
There were test files in which `assert` was being imported even that is no longer a dependency. This PR replaces those imports with `{ assert } from "chai"`.
For this package, `assert` was also deleted from the rollup.base.config.js file.
Some tests were also modified due to undefined types, by catching unrecognized errors, or casting a var to a specific type.

Replace assert imports with chai in AppConfiguration

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-short-codes/package.json
sdk/communication/communication-short-codes/review/communication-short-codes.api.md
sdk/databricks/arm-databricks/package.json
sdk/extendedlocation/arm-extendedlocation/package.json
sdk/logic/arm-logic/package.json
sdk/logic/arm-logic/review/arm-logic.api.md
sdk/notificationhubs/arm-notificationhubs/package.json
sdk/operationalinsights/arm-operationalinsights/package.json
sdk/operationsmanagement/arm-operations/package.json
sdk/postgresql/arm-postgresql/package.json
sdk/quota/arm-quota/package.json
sdk/security/arm-security/package.json
sdk/videoanalyzer/arm-videoanalyzer/package.json

Some of the packages in the repo had pinned their dependency on api-extractor to version 7.7.11
This stops us from getting fixes to security vulnerabilities from the transitive dependencies that come via the api-extractor.
This PR updates the version being used to `^7.18.11` to match with what we do for rest of the packages in this repo

Unpin api-extractor dependency

---

sdk/keyvault/keyvault-common/src/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-common/src/tracingHelpers.ts

In this PR, I have fixed all files under ```sdk/keyvault/keyvault-common```.

[sort-imports] update ```keyvault-common``` with respect to ```sort-imports``` rule

---

sdk/communication/communication-short-codes/package.json
sdk/containerregistry/arm-containerregistry/package.json
sdk/mysql/arm-mysql/package.json
sdk/synapse/synapse-access-control-rest/samples/v1/javascript/package.json
sdk/synapse/synapse-access-control-rest/samples/v1/typescript/package.json

A handful of packages were still using v2 beta of the identity package. This PR updates such cases to use `^2.01` instead

Update Identity dependency to v2 from v2 beta

---

sdk/keyvault/keyvault-secrets/platform-matrix.json
sdk/keyvault/keyvault-secrets/test/internal/challengeBasedAuthenticationPolicy.spec.ts
sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-secrets/test/public/list.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.delete.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.recover.spec.ts
sdk/keyvault/keyvault-secrets/test/public/recoverBackupRestore.spec.ts
sdk/keyvault/keyvault-secrets/test/utils/testAuthentication.ts
sdk/keyvault/keyvault-secrets/test/utils/utils.common.ts
sdk/keyvault/keyvault-secrets/tests.yml

- Add support for multi-version testing for keyvault-secrets
Our commitment is to support the last N versions of the KeyVault service. To ensure neither we nor the service introduce breaking changes to prior versions, multi-version test support was added. We ported keys over and have already reaped the benefits of version based filtering.
This commit adds the same support for keyvault-secrets
Resolves #17892

[KeyVault] - Enable multi-version tests for KV secrets

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts
sdk/core/core-rest-pipeline/src/index.ts
sdk/core/core-rest-pipeline/src/interfaces.ts
sdk/core/core-rest-pipeline/src/policies/throttlingRetryPolicy.ts
sdk/core/core-rest-pipeline/test/throttlingRetryPolicy.spec.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
sdk/textanalytics/ai-text-analytics/src/util.ts
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
sdk/textanalytics/ai-text-analytics/test/public/utils/recordedClient.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/18941
Sometimes, we get rate limit reached error responses from the service that exceed the default number of retrys in the throttling retry policy.
For context, this particular API supports running multiple Text Analytics actions from one request, so the service does not like getting many successive requests for it. I also confirmed with their engineering team that the test suite is a bit too big.
To fix this, the test suite could be trimmed down but I am afraid that will affect the current coverage. Instead, I updated the retry policy for the test client to retry more.

[Text Analytics] Fix rate limit reached issue

---

sdk/eventhub/event-processor-host/test/eph.spec.ts
sdk/eventhub/event-processor-host/test/iothub.spec.ts
sdk/eventhub/event-processor-host/test/negative.spec.ts

Resolves #19360
This PR cleans up the logs in the test files in the `@azure/event-processor-host` package to address the concerns brought up in #19360 around `>>>>>` being the same as git conflict markers.
I am using the prefix `Test logs` instead to differentiate these logs from the logs coming from the actual client code unless we are logging errors
Please note that the `@azure/event-processor-host` package is actually deprecated at this moment

[EPH] Clean up logs that use >>>>

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

Resolves #19166 by updating the version of `@types/prettier` being used in `dev-tool`
Running `rush update` after changing from ~ to ^ didnt make any changes to the lock file. So went with `rush update --full` instead
@witemple-msft, Do you remember why you chose to go with ~ instead of ^ here in the first place?

Update version for types/prettier

---

sdk/identity/identity-vscode/src/index.ts
sdk/identity/identity-vscode/test/public/node/visualStudioCodeCredential.spec.ts

In this PR, I have fixed all files under ```sdk/identity/identity-vscode```.

[sort-imports] update ```identity-vscode``` with respect to ```sort-imports``` rule

---

sdk/storage/storage-blob/src/ContainerClient.ts

The ref docs for `listBlobsByHierarchy` under the [Methods](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/containerclient?view=azure-node-latest#methods) are causing the entire table to be too wide. This is because the code snippets used here do not wrap
While this should ideally be fixed by the reference doc rendering platform, this PR updates the ref docs to not have too long lines to see if this fixes the issue
- removed the printing of last modified as it does not add any value to us showing of async iterator works
- formatted one of the code snippets to span across multiple lines

Reduce page width for code snippets in ref docs

---

sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts

- Fixes - #19411
- I have also updated the current aka.ms link to point to the same troubleshoot link so that customers don't face this issue

fix the link to vscode cred troubleshoot aka.ms

---

sdk/test-utils/test-utils/src/index.ts
sdk/test-utils/test-utils/src/tracing/chaiAzureTrace.ts

In #18910 we created a chai plugin for supporting tracing validation. Because the base branch was stale, we weren't able to export this without _also_ suppressing chai warnings that are already being suppressed on main.
This commit just exports the plugin after fetching the latest changes from main.

[test-utils] Export chai plugin

---

sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts
sdk/servicebus/service-bus/tests.yml

The test messages we create have `scheduledEnqueueTimeUtc` set. Most of the time
messages received from the service have "active" state, but occasionally have
"scheduled" state due to the set property, thus failing the assertion.
This PR updates the verification to check for either "active" or "schedule". In
addition, a test is added for "active" state where the `scheduledEnqueueTimeUtc`
property is removed before sending the message.
Also shown in the failing pipeline that after this test failed, the message wasn't
removed because `receiver.completeMessage()` was not called. The lingering
message caused the next test to fail. While fixing I also moved the
cleanup step before assertions so the messages are always removed.

[ServiceBus][Test] fix unstable tests that verify message state

---

sdk/core/core-amqp/src/retry.ts

Add a small optimization that only computes the delay if we are retrying.

[core-amqp] only compute retry delay when retrying

---

common/tools/dev-tool/src/commands/about.ts
common/tools/dev-tool/src/framework/command.ts
common/tools/dev-tool/test/framework.spec.ts

Merely adding `--` args wasn't enough. Dev-tool's argument parsing is recursive, and it achieves this by passing the remainder of a branching-command's `args` back through the arg parser until a leaf-command is reached. Unfortunately, that means that if `--` args are parsed at the first step of the process, they aren't passed back into further subcommands' arguments. This meant that `--` had to be used by the first command. This change updates the argument passing behavior of `subCommand` to make it so that branching commands pass `--` arguments to their children.
I had previously tested to make sure that argument parsing worked as expected, but now I've also added a test to validate that `--` options are received by child commands.
@HarshaNalluru

[dev-tool] Handle passthrough of -- args

---

sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
sdk/appconfiguration/app-configuration/test/public/utils/testHelpers.ts

Fixes: https://github.com/Azure/azure-sdk-for-js/issues/19355
Removing the type validation for the errors since they are not needed with the current typescript version and they were introduced in PR:  https://github.com/Azure/azure-sdk-for-js/pull/19245

Removing type validation for errors

---

eng/guardian-tools/policheck/PolicheckExclusions.xml

- Add `*generated*` folders to Policheck exclusions
Because generated code is generated directly from the swagger we should not flag
it as Policheck terms as that would be noisy, the upstream service swagger as
presumably already validated their terms, and really the service team owns the
terms here.
While we should continue to validate our codebase for global readiness, limiting
our checks to hand-authored and/or API review files only makes sense. Similar to
our recordings (which are also excluded). I spoke to @chidozieononiwu offline 
about this as well.

[engSys] - Add generated folders to policheck exclusions

---

sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/test/internal/tableTransaction.spec.ts
sdk/tables/data-tables/test/public/transaction.spec.ts

**Problem**
Within the transaction, we are creating a new service client to send the custom transactional batch request. However, we are dismissing any client options passed to the table client.
**Fix**
Pass the client options to `InternalTableTransaction` constructor and then in `submitTransaction` build the serviceClient with these options
Reported in #19243

[Tables] Honor custom HTTP client in transactions

---

sdk/test-utils/recorder/CHANGELOG.md

And as discussed here, https://github.com/Azure/azure-sdk-for-js/pull/19446#discussion_r771725207, I'm planning to delete the old recorder and call the new recorder 2.0.0 since the old recorder is already published and the existing packages/tests remain functioning the same way they do right now.
I'll make a new PR to delete once #19446  is merged.
Any change to the old recorder would go in as a hotfix from now on.
There is one unreleased item in the changelog, this PR is to release that.

[Recorder] Changelog

---

sdk/eventhub/event-hubs/src/diagnostics/instrumentEventData.ts
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/impl/awaitableQueue.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/loadBalancingStrategy.ts
sdk/eventhub/event-hubs/src/log.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/pumpManager.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-table/src/tableCheckpointStore.ts

This PR removes the use of `@hidden` tags from Event Hubs packages as described in #13455
- `@hidden` is not needed on members of a class when the class itself is marked as internal
- `@hidden` is not needed if `@internal` is already added
Resolves #13455

Fix use of hidden tag in Event Hubs packages

---

common/config/rush/pnpm-lock.yaml
sdk/attestation/attestation/karma.conf.js
sdk/attestation/attestation/package.json
sdk/attestation/attestation/samples-dev/attestEnclaves.ts
sdk/attestation/attestation/samples-dev/setAttestationPolicy.ts
sdk/attestation/attestation/samples-dev/utils/cryptoUtils.ts
sdk/attestation/attestation/src/attestationAdministrationClient.ts
sdk/attestation/attestation/src/attestationClient.ts
sdk/attestation/attestation/src/index.ts
sdk/attestation/attestation/src/models/attestationPolicyToken.ts
sdk/attestation/attestation/src/models/attestationResult.ts
sdk/attestation/attestation/src/models/attestationSigner.ts
sdk/attestation/attestation/src/models/attestationToken.ts
sdk/attestation/attestation/src/models/index.ts
sdk/attestation/attestation/src/models/policyResult.ts
sdk/attestation/attestation/src/tracing.ts
sdk/attestation/attestation/src/utils/base64.browser.ts
sdk/attestation/attestation/src/utils/base64.ts
sdk/attestation/attestation/test/browser/attestationTests.browser.spec.ts
sdk/attestation/attestation/test/public/attestationTests.spec.ts
sdk/attestation/attestation/test/public/attestationTokenTests.spec.ts
sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts
sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts
sdk/attestation/attestation/test/public/tokenCertTests.spec.ts
sdk/attestation/attestation/test/utils/cryptoUtils.ts
sdk/attestation/attestation/test/utils/recordedClient.ts

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages in `sdk/attestation`.
Updated `prettier` dev-dependency version from `^1.19.1` to latest (`2.5.1`).
Files were re-formatted as well. Only format changes in this PR.

Update prettier dev-dependency to v2.5.1 in Attestation

---

common/tools/dev-tool/src/util/samples/generation.ts
common/tools/dev-tool/src/util/samples/processor.ts
common/tools/dev-tool/src/util/samples/syntax.ts
common/tools/dev-tool/src/util/samples/transforms.ts
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/javascript/index.js
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/src/index.ts
common/tools/dev-tool/test/samples/files/inputs/cjs-forms/index.ts
sdk/template/template/samples-dev/getConfigurationSetting.ts
sdk/template/template/samples/v1-beta/typescript/src/getConfigurationSetting.ts

This was a little bit of an oversight in the recent dev-tool changes that I quickly discovered when working on cosmosdb samples.
The issue is that because of `esModuleInterop`, the TypeScript compiler treats `import x from "y"` as if it could either be a default import or a namespace import. When designing the default import solution, I only had relative modules in mind, but this was causing dev-tool to do things like `const path = require("path").default;`, even though the `"path"` builtin module doesn't have a `default` property (it is synthesized by esModuleInterop).
This PR adds a syntax rule that will reject default imports from _external_ modules (dependencies) in samples. It will still allow you to use the default import syntax for node builtins and for relative modules, but not …

[dev-tool] Don't allow external default imports

---

common/config/rush/pnpm-lock.yaml
sdk/agrifood/agrifood-farming-rest/package.json

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages in `sdk/agrifood`.
Updated `prettier` dev-dependency version from `^2.2.1` to latest (`2.5.1`).
Ran `npm run format`, but no changes were made by this command.

Update prettier dev-dependency to v2.5.1 in AgriFood

---

common/config/rush/pnpm-lock.yaml
sdk/anomalydetector/ai-anomaly-detector/package.json
sdk/anomalydetector/ai-anomaly-detector/samples-dev/sample_detect_change_point.ts
sdk/anomalydetector/ai-anomaly-detector/samples-dev/sample_detect_entire_series_anomaly.ts
sdk/anomalydetector/ai-anomaly-detector/samples-dev/sample_detect_last_point_anomaly.ts

csv-parser is a dev dependency used in samples for `ai-anomaly-detector`. Updating to the latest version. The only breaking change that hit us is that parse is now a named export, so I had to change the import to a named import
Fixes #19215

Update csv-parser version

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/src/timespanConversion.ts
sdk/monitor/monitor-query/test/internal/unit/modelConverters.unittest.spec.ts

- Fixes #17502 
- Added unit tests for `convertTimespanToInterval` and `convertIntervalToTimeIntervalObject`
- Bug fix - Fixed the `timeInterval` field of `MetricsQueryResult`object to correctly return all the fields of `QueryTimeInterval` object

update the unit-tests for TimeIntervalObject

---

sdk/core/core-client/package.json

while we may want to handle setting dev versions better, this unblocks the
nightly build pipeline similarly to what PR #18977 did.

[core] fix nightly core build pipeline

---

eng/tools/dependency-testing/index.js
eng/tools/dependency-testing/package.json
eng/tools/dependency-testing/templates/package.json
eng/tools/dependency-testing/templates/tsconfig.json
sdk/communication/communication-chat/tests.yml
sdk/identity/identity/tests.yml

- Update logic to update azure package dependencies from outside the repo too
- Update logic to run min-max testing on third party dependencies
- Update integration-test - node script to take the timeout from the package's package.json - Fixes https://github.com/Azure/azure-sdk-for-js/issues/16731
- Verify logic working or not on identity and communication-chat package
- Fixes https://github.com/Azure/azure-sdk-for-js/issues/14950
- Verification run - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1258044&view=results (If you see one failing test, it's because that one test is failing on ubuntu - unrelated to min-max)

Min max npm

---

common/config/rush/pnpm-lock.yaml
sdk/confidentialledger/confidential-ledger-rest/package.json

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages under `sdk/confidentialledger`.
Issue https://github.com/Azure/autorest.typescript/issues/1270 keeps track of making this change on the codegen side.

Update prettier dev-dependency to v2.5.1 in Confidential-Ledger

---

sdk/communication/communication-sms/samples-dev/sendSms.ts
sdk/communication/communication-sms/samples-dev/sendSmsWithOptions.ts
sdk/communication/communication-sms/samples-dev/usingAadAuth.ts
sdk/communication/communication-sms/samples/v1/typescript/src/sendSms.ts
sdk/communication/communication-sms/samples/v1/typescript/src/sendSmsWithOptions.ts
sdk/communication/communication-sms/samples/v1/typescript/src/usingAadAuth.ts

On PR https://github.com/Azure/azure-sdk-for-js/pull/19489 there is the following error when building the samples for communication-sms:
```
samples-dev/sendSms.ts:28:9 - error TS-AZURE: unsupported ES2020 "OptionalChain" syntax
28     to: process.env.TO_PHONE_NUMBERS?.split(",") || [process.env.AZURE_PHONE_NUMBER!] || [
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Suggestion: try `process.env.TO_PHONE_NUMBERS.split && process.env.TO_PHONE_NUMBERS.split(",")` if it does not affect runtime behavior, or use an explicit `if` block to handle the nullish case
[publish] Cannot read properties of undefined (reading 'kind')
[dev-tool] Errors occured. See the output above.
The script failed with exit code 1
```
This error is also present on main.
In this PR I changed the optional chain to `if` blocks …

Fixing error in samples build from Communication-SMS

---

eng/guardian-tools/policheck/PolicheckExclusions.xml

In #19454 we added generated folders to the Policheck exclusion list, but it's actually not quite right. This commit fixes that issue and correctly adds generated folders to the exclusions patterns.

[engSys] - Fix Exclusion patterns

---

sdk/storage/storage-file-datalake/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/leaseclient.spec.ts
sdk/storage/storage-file-datalake/test/node/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/node/highlevel.node.spec.ts
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/node/sas.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/retrypolicy.spec.ts
sdk/storage/storage-file-datalake/test/serviceclient.spec.ts
sdk/storage/storage-file-datalake/test/specialnaming.spec.ts

1. File system client creating/deleting may fail due to retrying, change to use createIfNotExists and deleteIfExists to avoid the failure.
2.  A lease case may fail when lease is expired, set a longer duration to try to mitigate the failure.
3. Data lake file uploading should only care about content, change a case to only validate content instead of checking Blob instance properties.

Fix test case failures in data lake package

---

sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts

for non-existing queue.
Detailed logs show that when this test is running on China Cloud on a Mac build agent, it gets the
expected error except that it takes a little more than 3 seconds for the error to come back.
This PR increases the timeout to 5 seconds.
Fixes #17928

[ServiceBus][TestReliability] Increase timeout when expecting an error

---

sdk/test-utils/recorder-new/CHANGELOG.md
sdk/test-utils/recorder-new/src/index.ts
sdk/test-utils/recorder-new/src/sanitizer.ts
sdk/test-utils/recorder-new/src/utils/delay.ts
sdk/test-utils/recorder-new/src/utils/utils.ts
sdk/test-utils/recorder-new/test/sanitizers.spec.ts
sdk/test-utils/recorder-new/test/testProxyClient.spec.ts
sdk/test-utils/recorder-new/test/testProxyTests.spec.ts
sdk/test-utils/recorder-new/test/utils/utils.ts
sdk/test-utils/testing-recorder-new/test/core-v2-test.spec.ts
sdk/test-utils/testing-recorder-new/test/noOpCredentialTest.spec.ts

Fixes #19559 
Fixes #19560
- Allows passing `undefined` as keys in the sanitizer options so that devs don't have to add additional checks if a certain env variable exists in playback.
- Exports `delay`
- waits for expected time in record/live modes
- no-op in playback
- Tests
- Restructuring tests so that we do not bloat up the files
- Changelog

[Unified Recorder] Allow passing undefined to sanitizers and other minor changes

---

sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

With `@types/long` min version of `4.0.0` we got compilation error
```
Namespace 'Long' has no exported member 'Long'.
```
version `4.0.1` fixes this.

[ServiceBus][Test] Fix Min-Max test build failure

---

common/config/rush/pnpm-lock.yaml
sdk/purview/purview-account-rest/package.json
sdk/purview/purview-account-rest/src/parameters.ts
sdk/purview/purview-administration-rest/package.json
sdk/purview/purview-administration-rest/src/account/parameters.ts
sdk/purview/purview-catalog-rest/package.json
sdk/purview/purview-catalog-rest/src/parameters.ts
sdk/purview/purview-scanning-rest/package.json
sdk/purview/purview-scanning-rest/src/parameters.ts
sdk/synapse/synapse-access-control-rest/package.json
sdk/synapse/synapse-access-control/package.json
sdk/synapse/synapse-artifacts/package.json
sdk/synapse/synapse-managed-private-endpoints/package.json
sdk/synapse/synapse-spark/package.json

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages under `sdk/purview` and for `sdk/synapse`
Issue https://github.com/Azure/autorest.typescript/issues/1270 keeps track of making this change on the codegen side.

Update prettier dev-dependency to v2.5.1 in rest packages

---

sdk/storage/test-resources.json
sdk/tables/test-resources.json

instead of hard-coded one which has expired and failed test resource deployments

[storage,tables] Update `signedExpiry` to computed value

---

common/config/rush/pnpm-lock.yaml
sdk/iot/iot-modelsrepository/karma.conf.js
sdk/iot/iot-modelsrepository/package.json
sdk/iot/iot-modelsrepository/src/dtmiConventions.ts
sdk/iot/iot-modelsrepository/src/fetcherFilesystem.ts
sdk/iot/iot-modelsrepository/src/fetcherHTTP.ts
sdk/iot/iot-modelsrepository/src/modelsRepositoryClient.ts
sdk/iot/iot-modelsrepository/src/modelsRepositoryServiceClient.ts
sdk/iot/iot-modelsrepository/test/browser/browserTest.spec.ts
sdk/iot/iot-modelsrepository/test/node/integration/index.spec.ts
sdk/iot/iot-modelsrepository/test/node/unit/constants.spec.ts
sdk/iot/iot-modelsrepository/test/node/unit/dtmiConventions.spec.ts

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages under `sdk/iot`.

Update prettier dev-dependency to v2.5.1 in IoT

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts

to v12.20.40.
This PR reacts to changes in `@types/node` where the return type of `destroy()`
has been updated to `this`.  See
DefinitelyTyped/DefinitelyTyped#57473 for details.

[core-rest-pipeline] Fix build error after upgrading @types/node 

---

sdk/test-utils/recorder/CHANGELOG.md

> And as discussed here, [#19446 (comment)](https://github.com/Azure/azure-sdk-for-js/pull/19446#discussion_r771725207), I'm planning to delete the old recorder and call the new recorder 2.0.0 since the old recorder is already published and the existing packages/tests remain functioning the same way they do right now.
> 
> I'll make a new PR to delete once #19446 is merged.
> 
> Any change to the old recorder would go in as a hotfix from now on.
> 
> There are two unreleased items in the changelog, this PR is to release them.
This PR is same as https://github.com/Azure/azure-sdk-for-js/pull/19474, but adds one more unreleased item.

Release recorder 1.0.2

---

common/config/rush/pnpm-lock.yaml
sdk/digitaltwins/digital-twins-core/karma.conf.js
sdk/digitaltwins/digital-twins-core/package.json
sdk/digitaltwins/digital-twins-core/samples-dev/dt_component_lifecycle.ts
sdk/digitaltwins/digital-twins-core/samples-dev/dt_digitaltwins_lifecycle.ts
sdk/digitaltwins/digital-twins-core/samples-dev/dt_models_lifecycle.ts
sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
sdk/digitaltwins/digital-twins-core/src/index.ts
sdk/digitaltwins/digital-twins-core/src/tracing.ts
sdk/digitaltwins/digital-twins-core/test/internal/digitalTwinsClient.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testDigitalTwins.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testEventRoutes.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testRelationships.spec.ts
sdk/digitaltwins/digital-twins-core/test/utils/recorderUtils.ts
sdk/digitaltwins/digital-twins-core/test/utils/testAuthentication.ts

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages under `sdk/digitaltwins`.

Update prettier dev-dependency to v2.5.1 in Digital Twins

---

sdk/identity/identity-cache-persistence/src/index.ts
sdk/identity/identity-cache-persistence/src/platforms.ts
sdk/identity/identity-cache-persistence/src/provider.ts
sdk/identity/identity-cache-persistence/test/internal/node/clientCertificateCredential.spec.ts
sdk/identity/identity-cache-persistence/test/internal/node/clientSecretCredential.spec.ts
sdk/identity/identity-cache-persistence/test/internal/node/deviceCodeCredential.spec.ts
sdk/identity/identity-cache-persistence/test/internal/node/usernamePasswordCredential.spec.ts

In this PR, I have fixed all files under ```sdk/identity/identity-cache-persistence```.

[sort-imports] update ```identity-cache-persistence``` with respect to ```sort-imports``` rule

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/index.ts
sdk/core/core-tracing/src/instrumenter.ts
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracingClient.ts
sdk/core/core-tracing/src/tracingContext.ts
sdk/core/core-tracing/test/instrumenter.spec.ts
sdk/core/core-tracing/test/interfaces.spec.ts
sdk/core/core-tracing/test/tracingClient.spec.ts
sdk/core/core-tracing/test/tracingContext.spec.ts
sdk/instrumentation/instrumentation-opentelemetry/karma.conf.js
sdk/instrumentation/instrumentation-opentelemetry/package.json
sdk/instrumentation/instrumentation-opentelemetry/src/instrumentation.browser.ts
sdk/instrumentation/instrumentation-opentelemetry/src/instrumentation.ts
sdk/instrumentation/instrumentation-opentelemetry/src/instrumenter.ts
sdk/instrumentation/instrumentation-opentelemetry/src/transformations.ts
sdk/instrumentation/instrumentation-opentelemetry/test/public/instrumenter.spec.ts
sdk/instrumentation/instrumentation-opentelemetry/test/public/util/testSpan.ts
sdk/instrumentation/instrumentation-opentelemetry/test/public/util/testTracer.ts
sdk/test-utils/test-utils/src/tracing/mockInstrumenter.ts

- Avoid classes in core-tracing as well as the usage of `this`
- Avoid returning the new context in two places, only return it as part of the updatedOptions
- Avoid `this` magic for callbacks and expect callers to handle `this` correctly
- Upgrade to prettier 2.0
- We should use factory functions where we can. We already do this, but by relying on closure instead of `this` we can avoid a lot of the pitfalls. I left instrumentation package alone for now, and focused on core-tracing
- Ideally there would be a single source of truth here. By returning tracingContext both separately _and_ as the updated options bag it's not clear that it is the same context
- `this` is easy to get wrong, and can be unreliable depending the type of function used. Instead of trying to apply it correctly, just …

[tracing] - Address some of the feedback for tracing changes

---

sdk/core/core-paging/package.json
sdk/core/core-paging/review/core-paging.api.md
sdk/core/core-paging/samples-dev/getPagedAsyncIteratorSample.ts
sdk/core/core-paging/samples/v1/javascript/README.md
sdk/core/core-paging/samples/v1/javascript/getPagedAsyncIteratorSample.js
sdk/core/core-paging/samples/v1/javascript/package.json
sdk/core/core-paging/samples/v1/typescript/README.md
sdk/core/core-paging/samples/v1/typescript/package.json
sdk/core/core-paging/samples/v1/typescript/src/getPagedAsyncIteratorSample.ts
sdk/core/core-paging/samples/v1/typescript/tsconfig.json
sdk/core/core-paging/src/models.ts
sdk/core/core-paging/test/getPagedAsyncIterator.spec.ts
sdk/core/core-paging/tsconfig.json

Relates to https://github.com/Azure/azure-sdk-for-js/issues/19394 (fixes it but we do not want to close it after merging)
Updates the `next` method in the `PagedAsyncIterableIterator` interface to return a promise of `IteratorResult<T>` instead of `IteratorResult<T, T>`. The second parameter (the type of return expressions) will default to `any`. This is not a breaking change because it changes the type of return expressions from `T` to the less precise type `any`.
For context, `IteratorResult` was updated in [v3.6](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#stricter-generators) to take an extra type variable that specifies the type of return expressions. The change in this PR enables older versions of the typescript compiler (<3.6) to compile code that …

[core-paging] Use a TS v3.4-friendly iterator protocol

---

sdk/eventgrid/eventgrid/src/eventGridClient.ts

The cloud event distributed tracing enricher depends on `tracingPolicy` being
applied before it so it can copy the `traceparent` header that is added by
`tracingPolicy` to its event payload. However, it doesn't specify this
dependency and relies on the implicit policy ordering when request pipeline is
created. This happened to work because `tracingPolicy` was not in a phase, and
was added before `cloudEventDistributedTracingEnricherPolicy` which is not in a
phase either. But after refactoring done in PR #19078, `tracingPolicy` is moved
to be after the Retry phase, which comes after policies that are not in a phase.
Now the `traceparent` has not been set when
`cloudEventDistributedTracingEnricherPolicy` is applied. This is not the
expected behavior and caused test failure.
This change …

[eventgrid] fix distributed tracing enricher

---

common/autoinstallers/rush-prettier/package.json
common/autoinstallers/rush-prettier/pnpm-lock.yaml

- update prettier version to `^2.5.1`
- run `rush update-autoinstaller --name rush-prettier`

[engsys] update prettier version for rush-prettier autoinstaller

---

sdk/textanalytics/ai-text-analytics/package.json
sdk/textanalytics/ai-text-analytics/src/dom.d.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/test/public/utils/recordedClient.ts

In before, esnext was needed to be imported because it has definitions for async iterators that @types/node@8 did not have. Now, we support NodeJS v12 and up which includes ES2019 that includes ES2018 that includes the async iterators stuff. Thanks @witemple-msft for pointing that out!
The PR also does the following:
- deletes `src/dom.d.ts`. I am not sure why it exists in the first place but it is not referenced anywhere.
- removes use of `@azure/core-asynciterator-polyfill`. It was needed for older versions of NodeJS that we no longer support.

[Text Analytics] Remove includes of esnext

---

sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/api_key_metricsadvisorclient_feedback/recording_creates_comment_feedback.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/api_key_metricsadvisorclient_feedback/recording_retrieves_comment_feedback.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/api_key_metricsadvisorclient_feedback/recording_creates_comment_feedback.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/api_key_metricsadvisorclient_feedback/recording_retrieves_comment_feedback.js
sdk/metricsadvisor/ai-metrics-advisor/test/public/advisorclient.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/util/recordedClients.ts

- Disabling the feedback creation tests for AAD, as we are seeing these test failures across all languages. Have informed the service team, since it seems like a service-side issue.
- The feedback creation tests work fine with API key, so keeping them enabled
- updated the recorded endpoint variable to not include trailing slash

Disable the feedback creation tests for AAD

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/swagger/README.md

This change pulls in the latest changes from the
`azure-rest-api-specs` repository for system events in Azure.
While no new events have been added with this release, some events now
have additional properties (the service teams which produce these
events now provide additional information in each event).
In addition, it fixes an issue we had with some of the Azure Resource
Manager events. We discovered that the event schemas for these events
was authored incorrectly and said some properties were of type
"string" instead of either a rich object or a map of strings to
strings.
A customer discovered this for .NET and that caused us to do some
investigation with the service team to discover that the specification
was wrong and get it corrected.
This is a breaking change for code which is …

[EventGrid] Update System events and prepare for Jan release

---

package.json

The new released package `colors` has bugs and it's treated as malicious codes in pipeline component detection. So we should use a fixed version.
related issue: https://github.com/Marak/colors.js/issues/285

Use fixed version of colors

---

sdk/formrecognizer/ai-form-recognizer/test/public/training.spec.ts
sdk/formrecognizer/ai-form-recognizer/tests.yml

Form Recognizer tests are ready to move back onto a prod region, and Canada Central is our preferred prod region for testing.

[ai-form-recognizer] Update tests.yml

---

.gitignore

This little `.gitignore` snippet is useful for folks that want to use custom code-workspace configurations for smaller sets of projects. It allows us to create alternative workspace files that will be ignored, while still tracking the default `dataplane.code-workspace` file.
Example: I have a `dev-tool.code-workspace` that only has dev-tool, `@azure/template`, and the eslint plugin in it for when I'm hacking on dev-tool. This will help folks create little workspaces for whatever they're currently working on.
CC @ramya-rao-a and @xirzec

Ignore alternative code-workspace files.

---

.github/pull_request_template.md

It seems github requires the default template under the parent .github folder. So, copying the file under PULL_REQUEST_TEMPLATE directory (similar to the .NET repository)
FIle is ame as https://github.com/Azure/azure-sdk-for-js/pull/19780
@sadasant Could you please approve this PR?

PR Request Template

---

sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/test/public/utils/recordedClient.ts
sdk/search/test-resources.json

This PR is to address the issue [17577](https://github.com/Azure/azure-sdk-for-js/issues/17577). Today, the endpoint is modified for US & China Endpoints within the test code. The test code should not be doing it. 
With this PR, the value is read from the template dynamically and the switch statement is removed.
@xirzec Please review and approve the PR

Update search-documents tests to handle sovereign cloud endpoints dynamically

---

sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/index.ts
sdk/core/core-tracing/src/instrumenter.ts
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracingClient.ts
sdk/core/core-tracing/test/instrumenter.spec.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumenter.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/spanWrapper.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/transformations.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/instrumenter.spec.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/spanWrapper.spec.ts
sdk/test-utils/test-utils/src/tracing/chaiAzureTrace.ts
sdk/test-utils/test-utils/src/tracing/mockInstrumenter.ts
sdk/test-utils/test-utils/src/tracing/mockTracingSpan.ts
sdk/test-utils/test-utils/test/tracing/mockTracingSpan.spec.ts

Taken from https://github.com/Azure/azure-sdk-for-js/pull/19734#discussion_r780539434 - this demonstrates what that might look like
This PR removes `TracingSpanContext` from our public types and relies on TracingContext and runtime checks to serialize and deserialize a TracingSpan

[tracing] - Remove spanContext from our public API

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

In the last minor version release of cosmos, we added `test` and `samples-dev` to the compiler's inputs, raising the root directory by one level. While other paths in the `package.json` were changed to include `src/` in the paths, we missed the browser mappings.
This PR corrects them.
CC @sajeetharan : Once this is merged, we will want to prepare a 3.15.1 hotfix release.
Closes https://github.com/Azure/azure-sdk-for-js/issues/19549

[cosmos] Add src/ to browser path mappings.

---

sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts

- Azure Identity.
We’re seeing min max tests fail for Identity on our nightly CI pipelines. After debugging this, Karishma spotted that our tests were unable to find the fake certificate. This PR skips the test if the certificate can’t be found. It also replaces the HTTP client with a client that will never resolve before the abort signal is aborted.

[Identity] Fixing certificate test inconsistencies, including min-max live tests.

---

sdk/core/core-http/src/policies/tracingPolicy.ts
sdk/core/core-http/test/policies/tracingPolicyTests.ts
sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts
sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/containerclient.spec.ts
sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

- Use `HTTP <METHOD>` for tracingPolicy span names
As per the [spec and guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name), we should ideally use generic, low cardinality
span names for aggregation, analysis, etc.
This PR updates both our policies to conform to the guidelines. While these
tracing policies are going to change very soon, having this in place now (and
the tests) ensures we won't regress this when we change to the new tracing APIs.
Resolves #17973

[core] - Use correct span names for tracing policies

---

sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
sdk/web-pubsub/web-pubsub-express/review/web-pubsub-express.api.md
sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/src/cloudEventsProtocols.ts
sdk/web-pubsub/web-pubsub-express/src/utils.ts
sdk/web-pubsub/web-pubsub-express/test/user.spec.ts

1. When dataType is `json`, the type of `data` is from `JSON.parse(requestBody)` so it can be any type.
2. CloudEvents package failed to handle the JSON body successfully so we parse the request body by our own when the type is `json`

Fix CloudEvent JSON body parser issue and fix JSON api definition

---

sdk/identity/identity/test/httpRequests.browser.ts
sdk/identity/identity/test/httpRequests.ts
sdk/identity/identity/test/httpRequestsCommon.ts
sdk/identity/identity/test/internal/identityClient.spec.ts
sdk/identity/identity/test/internal/node/azureApplicationCredential.spec.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/internal/node/onBehalfOfCredential.spec.ts
sdk/identity/identity/test/public/browser/clientSecretCredential.spec.ts
sdk/identity/identity/test/public/browser/usernamePasswordCredential.spec.ts

Identity.
Fixes #19420
Identity tests rely on some functions that mock the internals of our HTTP clients to extract the outgoing requests and responses, so that we can mock the responses, and later match the network behavior based to our expectations. These functions are rather complex at the moment.
Refactoring in my mind means minimal efforts that slowly reduce technical debt over time.
With that in mind, I think the most immediate way to improve this design is **to move it from a closure to a class**.
Closures are not that common in our SDK, in comparison to classes, which are …

[Identity] Refactoring the HTTP request mocking to be easier to understand in context

---

sdk/synapse/synapse-monitoring/package.json
sdk/synapse/synapse-monitoring/rollup.config.js
sdk/synapse/synapse-monitoring/tsconfig.json

There are a few packaging issues:
* the path of "module" field is incorrect
* the ESM output folder should be `dist-esm` as specified in tsconfig.json
While on this I also updated the compilation target to `es6`, and removed the
`openTelemetryCommonJs()` that is no longer needed.
#17707
No, codegen works expected.  This lib is generated + manual work on top of it.
packaging issue, not applicable.

[synapse-monitoring] Fix packaging issues

---

sdk/communication/communication-phone-numbers/CHANGELOG.md

- azure/communication-phone-number
Adds support for API version `2022-01-11-preview2`
- https://github.com/Azure/azure-sdk-for-js/pull/19805
**Command used to generate this PR:**_(Applicable only to SDK release request …

Prepare release for @azure/communication-phone-numbers

---

common/tools/dev-tool/src/config/rollup.base.config.ts
sdk/communication/communication-chat/rollup.test.config.js
sdk/communication/communication-network-traversal/rollup.test.config.js

It is a workaround for packages that uses older version of core-tracing
libraries. Now it only applies to two packages.  This PR removes the export from
`dev-tool` and have copies of the function in the two communication packages'
test rollup config instead.
Part of #17707

[dev-tool] Remove the `openTelemetryCommonJs()` export

---

sdk/appconfiguration/app-configuration/test/internal/node/package.spec.ts

in PR #19713, this test (package.spec.ts) was moved into `node` sub folder, and the
relative path is updated for the `unit-test` case but not the `integration-test`
case.  The fix wasn't enough, but PR unit-test ended passing because the old relative 
path of `../../../` for integration tests matched for unit-test.
This PR fixes the relative path for both now.

[AppConfig][Test] Fix integration test failure

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/eventgrid/eventgrid/test/public/eventGridClient.spec.ts
sdk/servicebus/service-bus/test/internal/operationOptionsForATOM.spec.ts

**Packages impacted by this PR:** 
@azure/event-grid, @azure/service-bus
In order to conform to the OTel spec and allow for easier aggregations we
updated tracing policy to name the span `HTTP <method>` instead of `<path>`.
Unfortunately we missed a few tests, so this updates those tests to reflect the
core changes.
While editing these tests, I realized I never added CHANGELOG entries for the original
change. This PR addresses that as well.
#19838
Resolves #19887
Resolves #19885

[eventgrid][servicebus] - Update tests to reflect tracingPolicy changes

---

sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts

Even though we merged an update recently to fix min-max tests, https://github.com/Azure/azure-sdk-for-js/pull/19810 which we tested using the pipelines against that PR, nightly min-max tests ended up failing right afterwards. The error received was as follows:
```
node/clientCertificateCredential.spec.ts(93,24): error TS2769: No overload matches this call.
Overload 1 of 2, '(tenantId: string, clientId: string, certificatePath: string, options?: ClientCertificateCredentialOptions | undefined): ClientCertificateCredential', gave the following error.
Argument of type '{ certificatePath: string; }' is not assignable to parameter of type 'string'.
Overload 2 of 2, …
```

[Identity] min-max tests failed because of inconsistent types loaded

---

sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/platform-matrix.json
sdk/keyvault/keyvault-certificates/test/internal/challengeBasedAuthenticationPolicy.spec.ts
sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-certificates/test/public/list.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.create.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.delete.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.operation.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.recover.spec.ts
sdk/keyvault/keyvault-certificates/test/public/mergeAndImport.spec.ts
sdk/keyvault/keyvault-certificates/test/public/recoverBackupRestore.spec.ts
sdk/keyvault/keyvault-certificates/test/utils/testAuthentication.ts
sdk/keyvault/keyvault-certificates/test/utils/utils.common.ts
sdk/keyvault/keyvault-certificates/tests.yml

- Add support for multi-version testing for keyvault-certificates
Our commitment is to support the last N versions of the KeyVault service. To ensure neither we nor the service introduce breaking changes to prior versions, multi-version test support was added. We ported keys over and have already reaped the benefits of version based filtering.
This commit adds the same support for keyvault-certificates
Resolves #17890

[KeyVault] - Enable multi-version tests for KV certificates

---

eng/ignore-links.txt
sdk/deviceupdate/iot-device-update-rest/package.json
sdk/deviceupdate/iot-device-update-rest/samples/v1/javascript/README.md
sdk/deviceupdate/iot-device-update-rest/samples/v1/typescript/README.md

**Command used to generate this PR:**_(Applicable only to SDK release request PRs)_

fix sample link of device update

---

common/tools/eslint-plugin-azure-sdk/.eslintrc.json

This PR reinforces the changes made in #18951 by changing the subdirectory's linting rule to ```"sort-imports": "error"``` rather than ```"sort-imports": "warn"```.
This affects the directory under ```common/tools/eslint-plugin-azure-sdk```.

[sort-imports] enforce ```sort-imports``` rule in ```eslint-plugin-azure-sdk```

---

sdk/appconfiguration/app-configuration/package.json

Skipping the sample since it needs Key Vault and AAD resources as well along with the App Config resource.
It might be too costly to create the resource for just one sample.

[App Config] skip secret reference sample

---

sdk/core/core-util/.eslintrc.json

This PR reinforces the changes made in #19047 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-util```.

[sort-imports] enforce ```sort-imports``` rule in ```core-util```

---

sdk/core/core-crypto/.eslintrc.json

This PR reinforces the changes made in #19036 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-crypto```.

[sort-imports] enforce ```sort-imports``` rule in ```core-crypto```

---

sdk/core/core-http/package.json

update node-fetch version 2.6.7 to fix [CVE-2022-0235](https://snyk.io/vuln/npm:node-fetch)
@azure/core-http
fix [CVE-2022-0235](https://snyk.io/vuln/npm:node-fetch)
**Command used to generate this PR:**_(Applicable only …

fix: :arrow_up: CVE-2022-0235

---

sdk/core/core-tracing/.eslintrc.json
sdk/core/core-tracing/test/instrumenter.spec.ts
sdk/core/core-tracing/test/interfaces.spec.ts
sdk/core/core-tracing/test/tracingClient.spec.ts
sdk/core/core-tracing/test/tracingContext.spec.ts

This PR reinforces the changes made in #19033 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-tracing```.

[sort-imports] enforce ```sort-imports``` rule in ```core-tracing```

---

sdk/core/core-paging/.eslintrc.json

This PR reinforces the changes made in #19046 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-paging```.

[sort-imports] enforce ```sort-imports``` rule in ```core-paging```

---

sdk/core/core-lro/.eslintrc.json

This PR reinforces the changes made in #19038 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-lro```.

[sort-imports] enforce ```sort-imports``` rule in ```core-lro```

---

sdk/keyvault/keyvault-admin/platform-matrix.json
sdk/keyvault/keyvault-admin/test/public/accessControlClient.aborts.spec.ts
sdk/keyvault/keyvault-admin/test/public/accessControlClient.spec.ts
sdk/keyvault/keyvault-admin/test/public/backupClient.abort.spec.ts
sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts
sdk/keyvault/keyvault-admin/test/utils/authentication.ts
sdk/keyvault/keyvault-admin/test/utils/common.ts
sdk/keyvault/keyvault-admin/tests.yml

- Add support for multi-version testing for keyvault-admin
Our commitment is to support the last N versions of the KeyVault service. To ensure neither we nor the service introduce breaking changes to prior versions, multi-version test support was added. We ported keys over and have already reaped the benefits of version based filtering.
This commit adds the same support for keyvault-admin
Resolves #19791

[KeyVault] - Enable multi-version tests for KV admin

---

common/tools/dev-tool/src/util/testProxyUtils.ts
sdk/core/ci.yml

- Resolves #19725 
When running tests using the test proxy, if the proxy tool image fails to start, the tool would exit successfully without outputting a useful error. This could happen if, for example, the Docker daemon is not running (this has happened to me a few times). This PR throws an error when the command to start the proxy tool outputs a nonzero exit code. This error will aid with debugging.

[dev-tool] Throw error when proxy fails to start

---

sdk/search/search-documents/test/public/utils/recordedClient.ts
sdk/search/test-resources.json

https://github.com/Azure/azure-sdk-for-js/issues/17577
This PR addresses the issue of updating search-documents tests to handle sovereign cloud endpoints dynamically. Earlier, this was done by adding 2 different endpoints (one for US and one for China). Ben has suggested a better approach where we can use just one endpoint and choose the suffix dynamically.
No detailed design. This approach is already used in .NET SDK and we are following the same here. 
N/A
**Does this PR needs …

[@azure/search-documents] Change EndPoint in TestResources Json

---

sdk/test-utils/perf/runAllTests.ts
sdk/test-utils/perf/src/options.ts

- Perf tests
- All packages using perf tests
- Fixes #19453 
The current default duration of 10 seconds is quite long. Slowing this down to 1 second should be OK and will make the build faster. If a longer perf test duration is required, the duration option can be specified manually.

[Perf] Decrease default perf test duration to 1 second

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroEncoder.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroEncoder.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20063
The encoder used to return encoded data in a preamble format but that is about to change in the next release where messages will be returned instead with payload contains the pure encoded data. This PR adds support for decoding payloads that have been encoded in the old preamble format.

[Schema Registry Avro] Support backward compatibility for old preamble format

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations_releasekey/recording_errors_when_updating_an_immutable_release_policy.json
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations_releasekey/recording_errors_when_updating_an_immutable_release_policy.js
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/generated/models/index.ts
sdk/keyvault/keyvault-keys/src/generated/models/mappers.ts
sdk/keyvault/keyvault-keys/src/generated/models/parameters.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/swagger/README.md
sdk/keyvault/keyvault-keys/test/public/keyClient.hsm.spec.ts
sdk/keyvault/keyvault-keys/test/public/keyClient.spec.ts

Resolves #19857
Now that this flag has been added we can regenerate code and add support for
immutable key release policies. Once a policy is marked immutable it can no
longer be modified.
Yes, I debated whether I should also add a test case for "create a key, then
update the release policy to be immutable, then try to change it" but it
wouldn't drive any code so I skipped it.
Do note that since MHSM does not currently support this flag I was unable to add
a test for it for MHSM, but I will create an issue to add that in later.

[KeyVault] - Added immutable flag to key release policy

---

sdk/monitor/monitor-query/test/internal/unit/modelConverters.unittest.spec.ts

No issue opened
There was an issue with an internal unit test - `convertTimespanToInterval` where the date conversion to ISO string() made the string to get converted in UTC timezone causing the test to fail locally, since the timezone wasn't specified in the date and it took the local timezone as default. This issue wasn't seen on the CI as the local timezone for CI is UTC.
Not applicable
This fixes the test case.

[Monitor Query] fix the local time zone bug in the test

---

sdk/eventhub/eventhubs-checkpointstore-table/.eslintrc.json

This PR reinforces the changes made in #19066 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/eventhub/eventhubs-checkpointstore-table```.

[sort-imports] enforce ```sort-imports``` rule in ```eventhubs-checkpointstore-table```

---

sdk/identity/ci.yml
sdk/template/ci.yml

Not packages, but pipelines that are running tests with the help of test proxy tool
**Background:**
In the CI/pipelines, mac agents are not capable of installing/using the docker, so we instead go by installing the "dotnet tool" directly in those machines and use the proxy tool without the docker command.
For the pipeline to know that, we use this variable "TestProxy".
Setting it to true means, a job will be added to the pipeline to install/start the proxy tool and dump the logs(For all the OSes).
It is not set to true by default already because not all pipelines are using TestProxy, and running the tool adds an unnecessary cost.
So, setting the TestProxy to true should make failing pipelines green.
Add as is shown here https://github.com/Azure/azure-sdk-for-js/blob/d180f2660a919da80f7dd9f …

Set "TestProxy: true" for template and identity pipelines

---

sdk/eventhub/mock-hub/.eslintrc.json

This PR changes the subdirectory's linting rule to ```"sort-imports": "error"```, and fixes any respective linting errors.
This affects the directory under ```sdk/eventhub/mock-hub```.

[sort-imports] enforce ```sort-imports``` rule in ```mock-hub```

---

sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/index.ts
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracingClient.ts

N/A - created after discussion with some team members
`withSpan` is meant to await some user-provided callback and set the appropriate
status on the created span before closing it. Because we have no way of knowing
whether the callback is sync or async we must promisify it first. Up until now that
meant that the return type of a promise-returning callback was
`Promise<Promise<...>>` which does not reflect the reality that `await` will
recursively unwrap promises. That meant that the consumer must also either
`await` or mark the function as `async` in order to avoid a return-type
mismatch.
The solution here is to introduce an `AwaitedLike` type which is a narrower
version of TypeScript 4.5's `Awaited` type. Because our min-bar is lower we
cannot take advantage of this …

[core-tracing] Fix the return type of withSpan

---

sdk/metricsadvisor/ai-metrics-advisor/test/public/advisorclient.spec.ts

Metrics Advisor
Fixes https://github.com/Azure/azure-sdk-for-js/issues/19546
Creation of changepoint feedback tests with API authentication failing with "Bad request" due to service side issues. Skipping till it gets resolved on the service side. Updated this issue to track this test too - https://github.com/Azure/azure-sdk-for-js/issues/19747
Skipping tests

[Metrics Advisor] skip create changepoint feedback tests due to potential service issues

---

common/config/rush/pnpm-lock.yaml
sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroEncoder.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroEncoder.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedRegistryClient.ts

`@azure/schema-registry-avro`
Fixes https://github.com/Azure/azure-sdk-for-js/issues/20064
Cache could grow unbounded and is a function of the unique schemas seen.
There're many cache designs but the architects recommended using LRU one with 128 max entries.
Yes!
N/A
N/A

[Schema Registry Avro] Use LRU cache policy

---

rush.json

#20087
Updating Rush to version `5.61.2` which is the latest as of today. Going through the changelog, I didn't find any changes that may impact our build process.

Update Rush version to 5.61.2

---

sdk/core/abort-controller/.eslintrc.json

This PR reinforces the changes made in #19212 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/abort-controller```.

[sort-imports] enforce ```sort-imports``` rule in ```abort-controller```

---

sdk/core/core-xml/.eslintrc.json
sdk/core/core-xml/src/xml.ts

This PR changes the subdirectory's linting rule to ```"sort-imports": "error"```, and fixes any respective linting errors.
This affects the directory under ```sdk/core/core-xml```.

[sort-imports] enforce ```sort-imports``` rule in ```core-xml```

---

sdk/core/core-asynciterator-polyfill/.eslintrc.json

This PR changes the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/core-asynciterator-polyfill```.

[sort-imports] enforce ```sort-imports``` rule in ```core-asynciterator-polyfill```

---

sdk/core/logger/.eslintrc.json

This PR reinforces the changes made in #19135 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/core/logger```.

[sort-imports] enforce ```sort-imports``` rule in ```logger```

---

sdk/eventgrid/eventgrid/test/public/eventGridClient.spec.ts

Similar to #19862, we have recently started to see some issues in our
nightly min/max jobs that prevent us from saving the entire Response
object during the `onResponse` callback due to multiple imports of the
"same" type.
Similar to the resolution for #19862, I've decided to just not use
nominal types from `core-client` here and instead just stash away the
parts of the response I need inside the callback and observe the
values after.
Fixes #20014

[eventgrid] Fix nightly Min/Max CI issues

---

sdk/core/core-client/.eslintrc.json
sdk/core/core-client/src/authorizeRequestOnClaimChallenge.ts
sdk/core/core-client/src/deserializationPolicy.ts
sdk/core/core-client/src/interfaceHelpers.ts
sdk/core/core-client/src/interfaces.ts
sdk/core/core-client/src/operationHelpers.ts
sdk/core/core-client/src/pipeline.ts
sdk/core/core-client/src/serializationPolicy.ts
sdk/core/core-client/src/serializer.ts
sdk/core/core-client/src/serviceClient.ts
sdk/core/core-client/src/urlHelpers.ts
sdk/core/core-client/test/authorizeRequestOnClaimChallenge.spec.ts
sdk/core/core-client/test/browser/serializer.spec.ts
sdk/core/core-client/test/deserializationPolicy.spec.ts
sdk/core/core-client/test/serializationPolicy.spec.ts
sdk/core/core-client/test/serializer.spec.ts
sdk/core/core-client/test/serviceClient.spec.ts
sdk/core/core-client/test/urlHelpers.spec.ts
sdk/core/core-client/test/utils/serviceClient.ts

This PR changes the subdirectory's linting rule to ```"sort-imports": "error"```, and fixes any respective linting errors.
This affects the directory under ```sdk/core/core-client```.

[sort-imports] enforce ```sort-imports``` rule in ```core-client```

---

sdk/keyvault/keyvault-admin/.eslintrc.json

This PR reinforces the changes made in #19128 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/keyvault/keyvault-admin```.

[sort-imports] enforce ```sort-imports``` rule in ```keyvault-admin```

---

sdk/keyvault/keyvault-common/.eslintrc.json

This PR reinforces the changes made in #19130 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/keyvault/keyvault-common```.

[sort-imports] enforce ```sort-imports``` rule in ```keyvault-common```

---

common/config/rush/pnpm-lock.yaml
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
sdk/monitor/monitor-opentelemetry-exporter/package.json

Fixes #20135
Fixes #20136
min/max tests were failing with: ` ERR_PNPM_INVALID_PEER_DEPENDENCY 
@rush-temp/azure-opentelemetry-instrumentation-azure-sdk-test:
@opentelemetry/core@1.0.1 requires a peer of @opentelemetry/api@>=1.0.0 <1.1.0
but version 1.1.0 was installed.`
Because @opentelemetry/api released 1.1.0 but the latest version of
@opentelemtry/core is not compatible with it. 
I originally wanted to get a latest version of @opentelemtry/core but this _is_
the latest version unfortunately. Looking at their [compatibility
matrix](https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix)
it looks like their latest version of @opentelemetry/api is not compatible with
anything. So this is …

[opentelemetry] - Tighten up semver ranges

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md
sdk/core/core-rest-pipeline/src/pipeline.ts
sdk/core/core-rest-pipeline/test/pipeline.spec.ts

Also fix a bug where policy order might change when a phase is empty.
core-rest-pipeline
https://github.com/Azure/azure-sdk-for-js/pull/19920#discussion_r794146397
Currently, there is no notion of when signing should occur in the pipeline. This presents a problem for services that require requests to be signed, since certain policies (e.g. test proxy) want to occur post-signing.
This PR also fixes an issue I found whereby policy order might change in certain conditions. For example,
```ts
addPolicy(policy1, { afterPhase: "Retry" });
addPolicy(retry, { phase: "Retry" });
addPolicy(policy2);
```
The above will execute in the order: 2, Retry, 1. However, if there is no retry policy:
```ts
addPolicy(policy1, { afterPhase: "Retry" });
addPolicy(policy2);
```
This now executes in the order 1, …

[core-rest-pipeline] Add new signing phase

---

sdk/iot/iot-modelsrepository/package.json

- `@azure/iot-modelsrepository`
* #19859 
This package's tests don't need the recorder. Removing the dependency.

[iot-modelsrepository] Remove unnecesary dependency on recorder

---

sdk/mixedreality/mixed-reality-authentication/.eslintrc.json
sdk/mixedreality/mixed-reality-authentication/src/mixedRealityStsClient.ts
sdk/mixedreality/mixed-reality-authentication/src/models/auth.ts

This PR reinforces the changes made in #19137 by changing the subdirectory's linting rule to ```"sort-imports": "error"```.
This affects the directory under ```sdk/mixedreality/mixed-reality-authentication```.

[sort-imports] enforce ```sort-imports``` rule in ```mixed-reality-authentication```

---

.github/CODEOWNERS

None
Resolves #18210
Today, vendors create issues and assign them based on a list that I provided
them. The problem is that it can easily get out of sync as nobody would know to
update it. I am working towards making CODEOWNERS the single source of truth for
package ownership. It needs to start with the primary owner listed first, so
that the vendors know who to assign it to.
I am going to be honest, this effort might not go anywhere. But it's not a
harmful thing to do. Besides, there's a bit of a chicken-and-egg problem right
now. CODEOWNER list ordering is not used by the vendors because it's not
ordered, but nobody will want to order it because the order has no impact.
Between this and the efforts engsys is putting in place to parse this file I am
hopeful we can get to a place where …

[CODEOWNERS] - Make primary package owner first

---

sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/servicebus/service-bus/src/core/messageSender.ts

NodeJS would issue warning if the number of disconnected listeners on an event
emitter exceeds 10. When many sessions on a connection are closed but the
removal of the listener hasn't caught up, we will see this warning because the
default limit of 10 in NodeJS is too low. The disconnected listeners DO get
removed eventually in our code.
We already do this for senders created in Service Bus. This PR increase the
limit to 1000 for senders and receivers created off
`ConnectionContextBase.connection` so that the limites apply to both Service Bus
and Event Hubs.
core-amqp, service-bus, event-hub
#12161
- https://github.com/amqp/rhea-promise/pull/78 complicated
- PR #19922 would need changes in both Service Bus and Event Hubs
no functionality changes. covered by stress tests

[core-amqp] set the max listener limit to 1000 for sender and receiver

---

sdk/search/perf-tests/search-documents/package.json
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/models/index.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/models/index.ts
sdk/search/search-documents/src/generated/service/models/mappers.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/swagger/Data.md
sdk/search/search-documents/swagger/Service.md

None
There is a new skill `AzureMachineLearningSkill` added to the search-documents service. The plan is for all the language SDKs to regenerate their SDKs and release a new version with this Skill. 
This is a simple & straightforward regenerate and modification of custom layer.
None. No special test cases are required for this simple addition.
None
1. `autorest --typescript swagger\Data.md`
2. `autorest --typescript swagger\Service.md`
3. `rushx build`
@xirzec Please review and approve the PR

[@azure/search-documents] Adding new skills to the search-documents SDK

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-asynciterator-polyfill/CHANGELOG.md
sdk/core/core-asynciterator-polyfill/package.json
sdk/core/core-asynciterator-polyfill/tsconfig.json

- `@azure/core-asynciterator-polyfill`
- #20167
There are some configuration errors in core-asynciterator-polyfill that this PR addresses:
- Files are output to `dist` instead of `dist-esm`, because this package is one of very, very few that only supports CJS.
- Declarations and declaration maps were disabled, as this package is the only (?) package we ship that does not include type declarations and does not include any API surface.
- I added an override for `target` back to ES5 for this package. It doesn't make much sense to use a higher compiler target for this one package that exists to support older targets without `Symbol.asyncIterator`. (Furthermore, that's what the target was the last time this package was published, so it's more about not changing anything).
- The version was …

[core-asynciterator-polyfill] Add source map to package, fix config

---

eng/common/scripts/Update-DocsMsMetadata.ps1
sdk/template/template/recordings/browsers/aad_configurationclient_functional_tests_getconfigurationsetting/recording_supports_tracing.json
sdk/template/template/test/public/configurationClient.spec.ts

Issue 
While we think of a better solution on how to handle the issue here https://github.com/Azure/azure-sdk-tools/issues/2674, this PR ignores the header matching for the browser test in the template folder.
Read more here https://github.com/Azure/azure-sdk-tools/issues/2674

[Recorder] [Template] Fix browser test failure

---

sdk/communication/communication-network-traversal/CHANGELOG.md
sdk/communication/communication-network-traversal/package.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_identity_and_routetype_any.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_identity_routetype_nearest.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_user_identity.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_without_providing_a_user_identity.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_and_routetype_any.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_routetype_nearest.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_user_identity.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_without_providing_a_user_identity.json
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_identity_and_routetype_any.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_identity_routetype_nearest.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_with_user_identity.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential_without_providing_a_user_identity.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_and_routetype_any.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_routetype_nearest.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_user_identity.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_without_providing_a_user_identity.js
sdk/communication/communication-network-traversal/src/communicationRelayClient.ts
sdk/communication/communication-network-traversal/src/generated/src/models/index.ts
sdk/communication/communication-network-traversal/src/generated/src/models/parameters.ts
sdk/communication/communication-network-traversal/src/generated/src/networkRelayRestClientContext.ts
sdk/communication/communication-network-traversal/src/generated/src/operations/communicationNetworkTraversal.ts
sdk/communication/communication-network-traversal/src/models.ts
sdk/communication/communication-network-traversal/swagger/README.md
sdk/communication/communication-network-traversal/test/public/communicationNetworkTraversalClient.spec.ts
sdk/communication/communication-network-traversal/test/public/utils/mockHttpClients.ts
sdk/communication/communication-network-traversal/test/public/utils/recordedClient.ts

**Command used to generate this PR:**_(Applicable only to SDK release request PRs)_

GA release for NetworkTraversal

---

eng/tools/versioning/package.json

Without this change I was getting the following error every time I ran the release script:
```
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'yargs-parser'
Require stack:
- C:\src\azure-sdk-for-js\eng\tools\versioning\node_modules\yargs\lib\command.js
- C:\src\azure-sdk-for-js\eng\tools\versioning\node_modules\yargs\lib\argsert.js
- C:\src\azure-sdk-for-js\eng\tools\versioning\node_modules\yargs\yargs.js
- C:\src\azure-sdk-for-js\eng\tools\versioning\node_modules\yargs\index.js
- C:\src\azure-sdk-for-js\eng\tools\versioning\set-version.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require …
```

[engsys] Fix release script issue

---

README.md
eng/pipelines/aggregate-reports.yml
eng/tools/analyze-deps/index.js

- Improvements to dependency graph.
- Addition of arcgraph

Improvements to dependency graph

---

sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/src/utils.ts
sdk/web-pubsub/web-pubsub-express/test/connect.spec.ts
sdk/web-pubsub/web-pubsub-express/test/connected.spec.ts
sdk/web-pubsub/web-pubsub-express/test/disconnected.spec.ts
sdk/web-pubsub/web-pubsub-express/test/user.spec.ts

The cloudevents package does redundant parses to the request body and there is no need for this package to. So remove the dependency and parse the request following the reference doc https://docs.microsoft.com/en-us/azure/azure-web-pubsub/reference-cloud-events

[web-pubsub-express] Remove cloudevents dependency

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/swagger/README.md

This change pulls in the latest changes from the
`azure-rest-api-specs` repository for system events in Azure.
It fixes two issues with our typings for events (a property name was
incorrectly cased and another property was typed as a boolean when the
event delivered by the service uses a string (with the value of `true`
or `false`) instead of a boolean as might be expected.
This is a breaking change for code which is written in typescript and
which uses any of these impacted properties because the underlying
type has changed from string to something else. However, any code
which previously was written against the old typings would have
*failed* at runtime with a type error, so in practice anyone who gets
an issue is now correctly discovering a bug in their program at
compile time now …

[EventGrid] Update System events and prepare for Feb release

---

sdk/communication/communication-common/test/communicationTokenCredential.spec.ts

- optimized the fractional backoff test
- added a test for checking that expired token passed via constructor triggers a refresh

[@azure/communication-common] Test improvements

---

sdk/test-utils/recorder/MIGRATION.md

More relevant updates to migration guide

[Recorder] More karma.conf enhancements to MIGRATION.md

---

sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples-dev/readDocument.ts
sdk/formrecognizer/ai-form-recognizer/src/models/ReadResult.ts

- `@azure/ai-form-recognizer`
I updated the README for 4.0.0-beta.3 to add samples for prebuilt-read and also found that it was missing a field. This PR corrects that by updating the README fully and adds the missing field to the `ReadResult` type.
I will update test cases for prebuilt-read in a separate PR.

[ai-form-recognizer] Update README, prebuilt-read result & samples

---

documentation/RLC-quickstart.md
sdk/purview/purview-administration-rest/README.md

No packages but the RLC generation quick start guide.
RLC quickstart guide has some broken links after deprecating @azure-rest/purview-account
Use a different package as an example

[RLC Quickstart] Fix broken links

---

sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/src/containerRegistryClient.ts

- Fixes #20275
This PR makes the container registry client's ClientOptions extend from the correct interface.

[Container Registry] Make ContainerRegistryClientOptions extend from CommonClientOptions

---

sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_and_routetype_any.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_identity_routetype_nearest.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_with_user_identity.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential_without_providing_a_user_identity.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20297
Just re-recording the test seems to have fixed the problem, unsure what the cause was.
I'm not investigating what the issue is.. 
since we'll be moving to the recorder v2 anyways(similar to https://github.com/Azure/azure-sdk-for-js/pull/20278) and we don't intend to record the AAD traffic with that.

[Aggregate Reports] - CredScan complaint - re-recording communication-network-traversal tests

---

sdk/tables/data-tables/package.json

Live tests are failing when running node in Windows. Dev-tool's browser filter doesn't seem to be picked up correctly by windows.
To mitigate the failure I'm adding an explicit exclude for browser tests in the integration-test:node command. On the side I'm investigating why the original filter in dev-tool doesn't work as expected

Exclude browser tests

---

sdk/eventgrid/eventgrid/test/public/eventGridClient.spec.ts

Fixes https://github.com/azure/azure-sdk-for-js/issues/20343
```
[browser-tests]     #send (CloudEvent schema)
[browser-tests]       × sends a single event
[browser-tests]         Chrome Headless 93.0.4577.0 (Windows 10)
[browser-tests]       RestError: {"Message":"Unable to find a record for the request POST https://endpoint/api/events?api-version=2018-01-01\r\nHeader differences:\r\n    \u003CContent-Type\u003E values differ, request \u003Capplication/cloudevents-batch\u002Bjson; charset=utf-8\u003E, record \u003Capplication/cloudevents-batch\u002Bjson; charset=UTF-8\u003E\r\nBody differences:\r\n","Status":"NotFound"}
[browser-tests]           at handleErrorResponse$2 (../../core/core-client/src/deserializationPolicy.ts:254:15 <- dist-test/index.browser.js:18197:20)
[browser-tests] …
```

[Event Grid] Headerless Matcher to not check the dynamic headers

---

sdk/eventhub/eventhubs-checkpointstore-blob/.eslintrc.json
sdk/eventhub/eventhubs-checkpointstore-blob/CHANGELOG.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/review/eventhubs-checkpointstore-blob.api.md
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/index.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/storageBlobInterfaces.ts

@azure/eventhubs-checkpointstore-blob
Issue #13667
Because:
- BlobCheckpointStore's constructor takes a class (ContainerClient) as an argument 
- That class is defined in @azure/storage-blob
- ContainerClient contains private members
You cannot pass what would otherwise be a compatible ContainerClient instance to
BlobCheckpointStore unless it is successfully deduped by NPM, even across minor
versions. 
This causes compatibility issues for anyone who upgrades storage-blob.
I tried to get clever with mapped types, but ran into a few situations (These examples probably have a lot of mistakes, it was hard to keep them all in-place):
```ts
// Doesn't work because `getBlobClient` returns a class with private members as
// well so we need to recursively map return values to Public
type Public<T> …
```

[eventhubs] - pass an interface to BlobCheckpointStore's constructor

---

sdk/test-utils/recorder/MIGRATION.md

The legacy recorder didn't support recording browser calls made through the Fetch API. As a result, when fetch API was introduced in `core-rest-pipeline` a work around was applied to the libraries not yet migrated to the new recorder, this workaround needs to be removed as part of the migration.

Update migration guide to remove XhrHttpClient

---

eng/pipelines/templates/jobs/ci.yml

[engsys] Enable credscan in PR/Ci

---

sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_rethrows_error_from_getproperties.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_exists_works_against_blob_uploaded_with_customer_provided_key.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_exists_works_against_blob_uploaded_with_customer_provided_key.js
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/test/blobclient.spec.ts

Against a blob uploaded with CPK, storage server would return error message of 'BlobUsesCustomerSpecifiedEncryption' for get attributes (without CPK specified) when blob exists. 
BlobClient.exists leverages getAttributes operation to verify blob's existence, based on the above behavior,  it should return true if got error message 'BlobUsesCustomerSpecifiedEncryption' from server.

[storage-blob]Refine behavior of BlobClient.exists

---

.vscode/cspell.json

This PR is related to the cspell tool, and all of the changes are in `.vscode/cspell.json`.
Series of issues regarding spelling errors found by cspell:
- https://github.com/Azure/azure-sdk-for-js/issues/18976
- https://github.com/Azure/azure-sdk-for-js/issues/18975
- https://github.com/Azure/azure-sdk-for-js/issues/18974
- https://github.com/Azure/azure-sdk-for-js/issues/18973
- https://github.com/Azure/azure-sdk-for-js/issues/18972
- https://github.com/Azure/azure-sdk-for-js/issues/18971
- https://github.com/Azure/azure-sdk-for-js/issues/18970
- https://github.com/Azure/azure-sdk-for-js/issues/18968
- https://github.com/Azure/azure-sdk-for-js/issues/18966
- https://github.com/Azure/azure-sdk-for-js/issues/18965
- https://github.com/Azure/azure-sdk-for-js/issues/18961
- …

Fixing cspell errors

---

sdk/eventhub/event-hubs/samples-dev/sendBufferedEvents.ts

The value provided to EVENTHUB_CONNECTION_STRING in the live test pipeline
doesn't contain the event hub name so it's failing with error:
> TypeError: Either provide "eventHubName" or the "connectionString": "***", must contain "EntityPath=<your-event-hub-name>".
This PR passes event hub name too to the client constructor in the same way as
some other tests do.
Fixes #20369

[EventHubs] fix sample issue when running in build pipeline

---

sdk/appconfiguration/app-configuration/tests.yml
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/tests.yml

- Service Bus and Event Hubs live tests used to take much longer time to run but we have
improved significantly since then.
- AppConfig live tests usually finish under 30 minutes.

[Test] Reduce some live tests time out limits

---

sdk/test-utils/recorder/src/sanitizer.ts
sdk/test-utils/recorder/test/sanitizers.spec.ts

Fixes #20392
```ts
createRecordingRequest(
url: string,
sessionFile?: string,
recordingId?: string,
method: HttpMethods = "POST"
)
```
`recordingId` was being passed as `sessionFile` which made the recording-id header to be undefined, which meant the sanitizers that were being added were session-level sanitizers than being just the test level sanitizers.
Pass the recordingId properly
This issue didn't cause any problems in other SDKs that were being migrated to the new recorder because typically the santizers remained the same for all the tests in a package.

[Recorder] Bug Fix - Passing recordingId to the proxy tool as expected

---

sdk/keyvault/keyvault-certificates/test/public/utils/testAuthentication.ts
sdk/keyvault/keyvault-keys/test/public/utils/testAuthentication.ts
sdk/keyvault/keyvault-secrets/test/public/utils/testAuthentication.ts

@azure/keyvault-certificates
@azure/keyvault-secrets
Note: @azure/keyvault-admin is _not_ impacted because it has no browser test.
I noticed that our recorded browser tests were failing in the browser. My good
friend `git bisect` pointed to 9afbe3fc46b63516e88b508911b2b2d4517dd42b as the
commit that introduced this issue.
Digging into it, it looks like this is unique to KeyVault in that it is _still_
on coreV1 but uses Identity which is on coreV2. Not sure about other client
libraries, it looks like they were fixed in the PR itself.
Really we just need to migrate KV to coreV2 and the new recorder... but this
will unblock the tests for now
https://github.com/Azure/azure-sdk-for-js/pull/20201

[KeyVault] - Fix recorded browser tests

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/errors.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

A customer recently reported that the ManagedIdentityCredential takes 5 minutes to retrieve any result in some environments: https://github.com/Azure/azure-sdk-for-js/issues/20308 — in this specific case, the endpoint is answering with a 5XX error, making our pipelines retry with exponential backoff up to 10 times.
As part of the recent change to unify the retry policies, our core retries now go up to 10 attempts by default: https://github.com/Azure/azure-sdk-for-js/pull/19078 — before this change, the maximum number of retries were inconsistent. In some cases, they were 3, in other cases 10. The unification has caused Identity to take too long to make some requests.
Ultimately, Identity should not delegate its max number of retries to the default values, so in this PR I’m specifying the …

[Identity] Maximum retries to 3

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/recordings/browsers/tableserviceclient_statistics/recording_should_getstatistics.json
sdk/tables/data-tables/recordings/node/tableserviceclient_statistics/recording_should_getstatistics.json
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/src/secondaryEndpointPolicy.ts
sdk/tables/data-tables/src/utils/connectionString.ts
sdk/tables/data-tables/test/internal/secondaryEndpointPolicy.spec.ts
sdk/tables/data-tables/test/internal/utils.spec.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts
sdk/tables/data-tables/test/public/utils/recordedClient.ts

#13085
`getStatistics()` operation fails consistently. The problem is that this operation needs to target the secondary URL when geo-replication is enabled for the table service instance. This secondary URL can be calculated by appending a `-secondary` suffix to the account name in the primary URL.
We need to create an additional ServiceClient that targets the secondary endpoint to execute this operation
Yes, an integration and a unit test were added.

[Tables] Fix getStatistics operation

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileAccessControl.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts

Azure OpenTelemetry Exporter
Exporter store data in disk when is unable to reach ingestion endpoint, folder where logs are located must be access protected

Added file access control in Windows for retriable telemetry

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

I removed some errant markdown syntax, added a few periods, and corrected a minor grammar issue. I also added a comment to the top so that there's not an awkward blank line. I think the intent is that the PR description will go at the top and then the questions follow it?
CC @sarangan12 @ramya-rao-a for review.

Some changes to the PR template.

---

common/tools/dev-tool/src/commands/samples/index.ts
common/tools/dev-tool/src/util/samples/convert.ts
common/tools/dev-tool/src/util/samples/generation.ts
common/tools/dev-tool/src/util/samples/processor.ts
common/tools/dev-tool/src/util/samples/syntax.ts
common/tools/dev-tool/src/util/samples/transforms.ts
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/javascript/index.js
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/javascript/package.json
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/package.json
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/src/ambient.d.ts
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/src/index.ts
common/tools/dev-tool/test/samples/files/inputs/cjs-forms/ambient.d.ts
common/tools/dev-tool/test/samples/files/inputs/cjs-forms/config.json
common/tools/dev-tool/test/samples/files/inputs/cjs-forms/index.ts

This PR implements some improvements to the way that the dev-tool sample transpiler handles default imports (`import x from "x";`). Currently, we simply don't allow these imports unless the module specifier refers to a node built-in module (in which case we treat it as if it were a `require` call), or if the module specifier is a relative path (in which case we use the `default` property of the module object).
This PR changes the behavior to emulate `esModuleInterop` at compile-time. When considering a default import, we will simply `require` the module from the host package and check for an `__esModule` property. If one exists, then we will transform the default import into a `const <name> = require("<moduleSpecifier>").default` expression. If one does not exist, then we will omit the …

[dev-tool] Implement `esModuleInterop` for sample transpilation

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/receivers/receiverCommon.ts

When receiving messages in a stream using `receiver.subscribe()`, 
Under certain situation when the underlying connection is closed, we don't respect user request to close the receiver, but keep retrying to recover.
The problem is that we check the connection status and throw an error if it is closed in
`_initAndAddCreditOperation`.  We restart retry cycle because of the error in the
`retryForEver()` function with the same operation, trying to re-establish the connection, then throw the same error again.
User calling `close()` wouldn't help because the place we
check for suspended state then throw `AbortError` is after we check the
connection and throw error.
This PR adds the checking of whether user has suspended the receiver before checking of connection so we
could throw `AbortError` …

[ServiceBus] Respect user request to close receiver when disconnected

---

sdk/core/abort-controller/README.md

Link verification check is failing for the link in this PR. Not sure why it
started failing now but the link certainly isn't valid.

[abort-controller] - Fix broken link

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

Fixed a regression in version 2.0.3 in which providing an options bag, but _not_ a client ID, to the `ManagedIdentityCredential` constructor would discard the `options` parameter.

[Identity] Fixed bug on 2.0.3

---

sdk/communication/communication-phone-numbers/karma.conf.js
sdk/communication/communication-phone-numbers/phone-numbers-livetest-matrix.json
sdk/communication/communication-phone-numbers/test/public/get.spec.ts
sdk/communication/communication-phone-numbers/test/public/lro.update.spec.ts
sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts
sdk/communication/communication-phone-numbers/test/public/utils/testPhoneNumber.ts
sdk/communication/communication-phone-numbers/tests.yml

This implements a simple pool of available phone numbers to use in live test pipelines. This solves an issue with the update capabilities live tests caused when multiple tests attempt to modify the state of a phone number simultaneously. 
In order to make use of this, the following environment variables need to be passed:
- `AZURE_TEST_AGENT` specifies the OS and runtime configuration for the job. It should contain the OS, the OS version and the framework/runtime version separated by underscores; e.g. `windows_2019_node12`.
- `AZURE_PHONE_NUMBER_<AZURE_TEST_AGENT>`, where _`<AZURE_TEST_AGENT>`_ corresponds to the value of the variable described prior; e.g. `AZURE_PHONE_NUMBER_windows_2019_node12`.
Additionally, by setting the `SKIP_UPDATE_CAPABILITIES_LIVE_TESTS` variable to `true`, …

[Communication] - phone-numbers - Implement phone number pool for live testing

---

sdk/core/ci.yml
sdk/core/core-http-compat/README.md
sdk/core/core-http-compat/review/core-http-compat.api.md
sdk/core/core-http-compat/src/extendedClient.ts
sdk/core/core-http-compat/src/index.ts

@azure/core-http-compat
N/A
The Initial Version of the @azure/core-http-compat SDK was done in https://github.com/Azure/azure-sdk-for-js/pull/20034. Two of the comments ([1](https://github.com/Azure/azure-sdk-for-js/pull/20034/files#r808546641) & [2](https://github.com/Azure/azure-sdk-for-js/pull/20034/files#r808530377)) were missed in that PR. They are:
1. Remove one section on generated client in the Readme file
2. Change `ExtendedOptions` to `ExtendedClientOptions`
Also updated the `ci.yml` file to include the new package.
There is no special design concern. It is simple name change.
Not necessary. Existing test cases are sufficient.
https://github.com/Azure/azure-sdk-for-js/pull/20034.

[@azure/core-http-compat] Rename ExtendedOptions to ExtendedClientOptions

---

sdk/digitaltwins/digital-twins-core/package.json
sdk/digitaltwins/digital-twins-core/test/utils/testAuthentication.ts

Tests in digital-twins-core
https://github.com/Azure/azure-sdk-for-js/issues/20493
Unblocks https://github.com/Azure/azure-sdk-for-js/pull/20300
Fixes https://github.com/Azure/azure-sdk-for-js/issues/20493
Requests from the AAD browser tests are hitting the live service in playback mode instead of using the recordings.
My best guess on the cause of the problem is that something has changed at the msal level which kicked in a tenant-id validation and failed for the "12345678-1234-1234-1234-123456789012" fake tenant-id.
Haven't investigated deeper on what is causing the failure, instead using the test-credential which would bypass the AAD traffic in playback mode.

[Digital Twins] Use "@azure-tools/test-credential";

---

sdk/test-utils/recorder/test/utils/utils.ts

Fixes #20511 '
Aims to fix this error.
```
test/utils/utils.ts(32,23): error TS2742: The inferred type of 'makeRequestAndVerifyResponse' cannot be named without a reference to '../../../../../common/temp/node_modules/.pnpm/@azure+core-rest-pipeline@1.5.0/node_modules/@azure/core-rest-pipeline/core-rest-pipeline.shims'. This is likely not portable. A type annotation is necessary.
```

[Recorder] Add return types to test/utils methods

---

sdk/core/core-rest-pipeline/documentation/core2.md
sdk/core/core-rest-pipeline/documentation/pipeline.md

None. This PR adds documentation for Pipeline and PipelinePolicy
#13561
Add documentation for the Pipeline and Policies and how to customize them.

[Core] Documentation for pipeline and policies

---

sdk/core/core-http-compat/CHANGELOG.md
sdk/core/core-http-compat/package.json

@azure/core-http-compat
None
The `core-client` and `core-rest-pipeline` dependency version is causing CI issues in autorest/typescript. I have verified with the versions in this PR, the issue is resolved.
No special design concerns.
None required.
https://github.com/Azure/autorest.typescript/pull/1324/

[@azure/core-http-compat] Update Dependency Versions

---

sdk/communication/communication-common/CHANGELOG.md

Prepare @azure/communication-common 2.0.0 release

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts

N/A
A running PR addressing any and all architect review comments before releasing
keyvault keys.
Changes made so far:
- updateKeyRotationPolicy: rename `name` to `keyName`
- getKeyRotationPolicy: rename `name` to `keyName`

[KeyVault] - Address architecture review comments

---

sdk/synapse/synapse-access-control/package.json
sdk/synapse/synapse-access-control/test/public/utils/recordedClient.ts
sdk/synapse/synapse-managed-private-endpoints/package.json
sdk/synapse/synapse-managed-private-endpoints/test/public/utils/recordedClient.ts
sdk/synapse/synapse-spark/package.json
sdk/synapse/synapse-spark/test/public/utils/recordedClient.ts

@azure/synapse-access-control
@azure/synapse-managed-private-endpoints
@azure/synapse-spark
N/A
Some Synapse sdks haven't been migrated to the new Recorder and browser tests are failing.
Injecting XHR client to work around the issue
Migration is tracked by https://github.com/Azure/azure-sdk-for-js/issues/20594
Current tests

[Synapse] Fix Synapse CI

---

sdk/agrifood/agrifood-farming-rest/package.json
sdk/agrifood/agrifood-farming-rest/test/public/utils/recordedClient.ts

@azure-rest/agrifood-farming
N/A
Agrifood farming hasn't been migrated to the new recorder and it is failing in CI.
To mitigate the failure we need to pass the xhrhttpclient
https://github.com/Azure/azure-sdk-for-js/issues/20592 Tracks the migration
Current test cases verify fix

[Farmbeats] Fix broken browser test

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/policies/StorageSharedKeyCredentialPolicy.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/src/policies/StorageSharedKeyCredentialPolicy.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/policies/StorageSharedKeyCredentialPolicy.ts

Set correct content length in requests for uploading operations to avoid unexpected failure if customized content length is incorrect.

Set correct content length in requests for uploading operations

---

sdk/identity/identity/CHANGELOG.md

[Identity] Preparing release for beta-1 - update changelog

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClient.ts
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/generated/models/parameters.ts
sdk/eventgrid/eventgrid/swagger/README.md

This change updates our Swagger API reference and re-runs the code
generation. There are no new events this sprint, however a new value
was added to an enum used by some `Microsoft.Media` events.
As part of the update, we pulled in changes around a new
`aeg-channel-name` header which was added to support a new Event Grid
feature. It is currently unexposed, but we expect to add support in
the April release.

[EventGrid] Update for March Release

---

sdk/identity/identity/README.md

@scottaddie pointed out to me that we should clarify that the `DefaultAzureCredential` will only try to authenticate with the VSCode credentials if the `@azure/identity-vscode` plugin is installed.

[Identity] Clarification about the VSCode authentication

---

.github/CODEOWNERS

The focus of these changes is to add Sannidhya Glodha to the service contacts for Event Hubs and Service Bus

[CODEOWNERS] Messaging

---

sdk/eventgrid/eventgrid/package.json

In #20273 we moved our `@azure/core-client` reference to `^1.5.1` in
order to pick up some new features we needed for use with the new
recorder. The version of this package has not shipped yet and we'd
like to release EventGrid this release cycle.
Talking with Jose, there's nothing we should need right now newer than
1.5.0, so we'll move our constraint back to that version.

[EventGrid] Use `^1.5.0` for `@azure/core-client`

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/samples-dev/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsBufferedProducerClient.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsConsumerClient.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsProducerClient.ts
sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/src/index.ts
sdk/schemaregistry/schema-registry-avro/src/models.ts
sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/messageAdapter.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedSerializer.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20730
Renaming based on archboard recommendation
N/A
N/A
N/A
N/A

[Schema Registry Avro] Rename Encoder to Serializer

---

eng/pipelines/templates/jobs/ci.yml

Js removes its baseline recently which failed the analysis step.
Failed pipeline: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1420643&view=logs&j=90227089-9f51-5ecc-566c-84e1f2918394&t=7da0f684-6369-5290-bb0b-5d27f59dde66
Remove the baseline file on credscan
Testing pipeline: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1421187&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81

Remove baseline file on credscan

---

common/config/rush/command-line.json

as they are useful for local development. We don't like to lose them without
realizing that `rush reset-workspace` would remove them.  If we want we can
always run `git clean -dfx` directly.

[engsys] exclude .env and launch.json files when `rush reset-workspace`

---

sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-phone-numbers/src/generated/src/phoneNumbersClientContext.ts
sdk/communication/communication-phone-numbers/src/phoneNumbersClient.ts
sdk/communication/communication-phone-numbers/src/utils/customPipelinePolicies.ts
sdk/communication/communication-phone-numbers/swagger/README.md
sdk/communication/communication-phone-numbers/test/internal/customPipelinePolicies.spec.ts
sdk/communication/communication-phone-numbers/test/internal/headers.spec.ts
sdk/communication/communication-phone-numbers/test/internal/phoneNumbersClientPolicies.spec.ts
sdk/communication/communication-phone-numbers/test/public/utils/mockHttpClients.ts

- `@azure/communication-phone-numbers`
- https://github.com/Azure/azure-sdk-for-js/issues/20647
Address pending feedback from https://github.com/Azure/azure-sdk-for-js/pull/20633. More specifically:
- Update the `@azure/core-lro` dependency to version 2.2.4 in order to remove LRO workaround
- Update `package-name` in autorest configuration file, so the user agent of the client is properly generated
- Remove redundant `use-core-v2` property in autorest configuration file
- https://github.com/Azure/azure-sdk-for-js/pull/20633
- https://github.com/Azure/azure-sdk-for-js/pull/20656

[Communication] - phone-numbers - Azure Core V2 migration cleanup

---

sdk/identity/identity/src/credentials/authorizationCodeCredential.ts

This has eluded us for a while 🙂

[Identity] Fixed wrong name in the AuthorizationCodeFlow documentation

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-internal-avro/package.json
sdk/storage/storage-queue/package.json
sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub/package.json

Resolves #19234 
Upgrades puppeteer to the latest version
I looked through the changelog for puppeteer and did not see any major changes between 10 and 13 that should impact us
No, this is a test dependency upgrade so if current tests pass we are good
`rush add -p puppeeteer --dev --caret --make-consistent`

[engSys] - Upgrade puppeteer

---

sdk/eventhub/eventhubs-checkpointstore-table/package.json

to work around an issue in `nyc` v15.  Very similar code is used in checkpointstore-blob and there's no issue there.
Associated issue #20000

[eventhubs-checkpointstore-table][test] run integration tests on .js files

---

sdk/formrecognizer/ai-form-recognizer/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20525
Updates the test command from
> "dev-tool run test:node-ts-input -- --timeout 1200000 --exclude 'test/**/browser/*.spec.ts' \"test/\*\*/\*.spec.ts\""
to
> "dev-tool run test:node-js-input -- --timeout 1200000 --exclude 'dist-esm/**/browser/*.spec.js' \"dist-esm/test/\*\*/\*.spec.js\" \"dist-esm/test/\*\*/node/\*.spec.js\""
Updating the command achieves the following.
- To have all the tests run in all the OSes (Ubuntu and Mac were running only 20 tests instead of 80 tests that were run in Windows.)
- To be consistent with other packages w.r.t to code coverage generation

[Form Recognizer] Fix integration-test:node command to run all tests in all OSes

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/samples-dev/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsBufferedProducerClient.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsConsumerClient.ts
sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsProducerClient.ts
sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/src/models.ts
sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20814
`serializeMessageData` is too long and can be simplified to `serialize`.
N/A
N/A
N/A

[Schema Registry Avro] drop MessageData postfix in method names

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventDataAdapter.ts
sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/src/models.ts
sdk/schemaregistry/schema-registry-avro/src/utility.ts
sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/messageAdapter.spec.ts
sdk/schemaregistry/schema-registry-avro/test/messageContent.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/utils.ts

@azure/schema-registry-avro, @azure/event-hubs
Fixes https://github.com/Azure/azure-sdk-for-js/issues/20879
Renames that has been agreed upon with the architects
Several names were suggested such as BinaryContent but the architects settled on this one.
Yes

[Schema Registry Avro] Rename MessageWithMetadata

---

rush.json
sdk/core/core-http/package.json

and remove unused `babel-runtime` dependency from core-http to address `lodash`
dependabot alert
https://github.com/Azure/azure-sdk-for-js/security/dependabot/2

[engsys] update rush and pnpm versions

---

sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/dummies.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20839
One of the tests is currently failing because the CI resource only allows up to 25 unique schemas per a schema group but that number is exhausted by another test that checks whether the growth of the serializer's internal cache is bounded. This PR reduces the number of schemas registered in the latter so there is enough room for subsequent tests to register their own schemas.
Furthermore, an additional test is added that checks an error case when deserializing with incompatible schema.
N/A
Yes. Also see a successful nightly run in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1439397&view=results
N/A

[Schema Registry Avro] Add an error scenario

---

sdk/test-utils/test-utils/src/tracing/chaiAzureTrace.ts
sdk/test-utils/test-utils/src/tracing/mockInstrumenter.ts

@azure/test-util 
Resolves #20802
Since the instrumenter that is set for tests is global, it can pollute other tests depending on the order in which they are
run. This manifested in what is an otherwise completely unrelated error in event-hubs
We can update the core-tracing API to allow undefined as a value for `useInstrumenter` but I hesitated to do that
since it would otherwise not be needed by anyone

[test-util] - Ensure the global instrumenter is cleared between tests

---

sdk/communication/communication-phone-numbers/CHANGELOG.md
sdk/communication/communication-phone-numbers/karma.conf.js
sdk/communication/communication-phone-numbers/test/public/utils/msUserAgentPolicy.ts
sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts

This change is needed to fix the test pipeline
communication-phone-numbers
Adds a way to mark request as test traffic
--
No new test cases, this updates only unit test code
--
--

[phone number sdk] Adds environment variable AZURE_USERAGENT_OVERRIDE that overrides HTTP header x-ms-useragent during tests

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/retryPolicy.ts
sdk/core/core-rest-pipeline/src/retryStrategies/exponentialRetryStrategy.ts
sdk/core/core-rest-pipeline/test/defaultRetryPolicy.spec.ts
sdk/core/core-rest-pipeline/test/exponentialRetryPolicy.spec.ts
sdk/core/core-rest-pipeline/test/retryPolicy.spec.ts

~This PR confirms that the retry policies by default do not retry on a RestError with status code 416.~
After meeting with @sarangan12 , we were able to narrow down the problem. It wasn’t that the retry policies were not throwing as soon as an error was received, but that the retry policies where not throwing after all the retry steps were exhausted.
Through the autorrest.Typescript tests, we’ve also found that the `exponentialRetryPolicy` was skipping retries if some expected errors were received.
I’ve added tests to confirm these fixes.

[core-rest-pipeline] Fixed bugs introduced on 1.4.0, and added tests

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/src/utils/continuationToken.ts
sdk/tables/data-tables/test/internal/continuationToken.spec.ts

#20913 
When querying entities from a table, the service may respond with a `nextPartitionKey` and no or empty `nextRowKey`. Currently, the library assumes that `nextRowKey` will always be present. When an empty `nextRowKey` is sent to the service, we get a 400 error.
Do not try to use `nextRowKey` if the service didn't send it or sent it empty
Yes added Unit Tests

[Tables] Fix issue handling empty nextRowKey

---

sdk/keyvault/keyvault-keys/src/keysModels.ts

#18400
The service team would like to document the release policy grammar, and as such
has asked us to link to their documentation. While the documentation is not live
yet, I did get the content folks to point it to a valid url so that we can
include it in our doc-comments now.

[KeyVault] - Add release policy grammar links

---

sdk/core/core-rest-pipeline/CHANGELOG.md

[core-rest-pipeline] 1.7.0 release date

---

sdk/core/ci.yml
sdk/template/ci.yml

**Current workflow for eng work:**
For work under `eng/common` like PR: https://github.com/Azure/azure-sdk-tools/pull/2861.
It will trigger 9 PRs like below:
For PR to lang repo, they trigger core pipeline for testing the changes. Like sync PR here: https://github.com/Azure/azure-sdk-for-js/pull/20837
Java has switched to template already and run for a while. The PR is to align with Java trigger branch and path.

Trigger template instead of core for eng/common

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts

@azure/keyvault-certificates
N/A  - architect review
@xirzec noticed that in our effort to move away from `const enum` I forgot one 😄 
This PR fixes that by making it a non-const enum

[keyvault] - KnownKeyUsageTypes should not be a const enum

---

sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/metricsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/shared/testShared.ts

`@azure/monitor-query`
- https://github.com/Azure/azure-sdk-for-js/issues/21005
This PR introduces a small change. The function `getRequiredEnvVar()` is no longer necessary since the new recorder provides a helper method [`assertEnvironmentVariable()`](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/test-utils/recorder/src/utils/utils.ts#L355-L362) that behaves in the same way.
This change was originally proposed in https://github.com/Azure/azure-sdk-for-js/pull/20178#discussion_r804952261

Replace `getRequiredEnvVar` function with `assertEnvironmentVariable` helper from new recorder

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/redirectPolicy.ts
sdk/core/core-rest-pipeline/test/redirectPolicy.spec.ts

- Resolves #20957
When following a redirect, our redirection policy sends the Authorization header from the original request again in the redirected request. This is a potential security risk, and can also cause issues when the resource at the end of the redirect does not support the authorization method initially provided (as I encountered with ACR in #20957).
This PR causes the redirection policy to remove the header before the request is redirected. This approach is in-line with .NET and Python, which were both already removing this header.
Yes, added a test case to make sure the header gets removed.

[core-rest-pipeline] Remove authorization header on redirected requests

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/src/models.ts
sdk/schemaregistry/schema-registry-avro/test/errors.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/assertSerializationError.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20072
@azure/schema-registry-avro depends on avsc, a third party package for Avro encoding, and it throws exceptions in certain cases. If in the future we decide to switch away from avsc to some other library, @azure/schema-registry-avro will be throwing new and different exceptions.
- Wrapping avsc exceptions in @azure/schema-registry-avro exceptions so that the customer experience stays consistent regardless of which Avro library to use. One question remain: should one exception suffice or should fine-grained exceptions provided?
Yes

[Schema Registry Avro] Add AvroSerializationError

---

sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/errors.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/assertSerializationError.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/21046
Live test failed in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1459741&view=results because the test suite attempts to register more than 25 schemas, the maximum number of allowed schemas in the standard-tier resource.
This PR fixes the issue by skipping a test that registers the bulk of the schemas in live mode.
N/A

[Schema Registry Avro] Fix live tests

---

sdk/containerregistry/container-registry/package.json
sdk/containerregistry/perf-tests/container-registry/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/test/public/utils/testAuthentication.ts
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/test/public/utils/testAuthentication.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/test/public/utils/testAuthentication.ts
sdk/test-utils/test-credential/package.json

Identity released version v2.0.4 is not pulling down core-rest-pipeline v1.8.0
because the latter is not released yet, so identity credentials find the new
request body type unexpected.  This RP updates the identity dev dependency
version to v2.1.0-beta.2 which is in the repo and references the new
core-rest-pipeline version in the repo.
while fixing container registry I also move its perf tests to depend on
latest version of container registry instead of a pinned beta version at the time
when the tests were created.

[Tests] fix build failures by upgrading identity dev dependency version

---

.github/CODEOWNERS

The focus of these changes is to add rules for the Communication sub-areas to apply unique labels to better integrate with the team's tooling.

[GitHub Automation] Communication Owners

---

common/config/rush/pnpm-lock.yaml
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/internal/node/instrumentation.spec.ts

Resolves #20980
Now that 1.1.0 is released, and the corresponding SDK as well, we can loosen our dependencies to the allow later OTel versions.
Because of how OpenTelemetry does their version compatibility check, we need to make sure our dependencies are
in-step with their releases, at least until core-rest-pipeline migrates off of a version of core-tracing that depends directly
on opentelemetry.
I noticed this when my integration tests started failing 😄

[opentelemetry] - Loosen OTel dependency range

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts
sdk/core/core-rest-pipeline/src/fetchHttpClient.ts
sdk/core/core-rest-pipeline/src/policies/redirectPolicy.ts

Browsers expect to handle redirects automatically when using fetch, much like XMLHttpRequest's default behavior.
The fact that fetch() lets you set a "manual" mode, isn't intended for common use, but rather for a specific Service Worker scenario. The response sent back is heavily redacted and contains neither the true status or any HTTP headers from the response.
Some more context: https://stackoverflow.com/questions/42716082/fetch-api-whats-the-use-of-redirect-manual/42717388
Since this is blocking redirect scenarios, I think we should release another hotfix after @sarangan12 validates it against our AutoRest collateral.

Fix fetchHttpClient issue with redirects

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts
sdk/core/core-rest-pipeline/src/defaultHttpClient.native.ts
sdk/core/core-rest-pipeline/src/xhrHttpClient.ts

#20787 
After we switch browser HTTP client to based on Fetch api, React-Native scenario is broken because streaming is not supported in React-Native's Fetch implementation. We get empty `bodyAsText` back from the response body.  This PR adds the old `XhrHttpClient` back just for React-Native using the `react-native` mapping in package.json.
We could use Fetch polyfill for React-Native out there: `react-native-fetch-api`, but it involves a bunch of additional polyfills, and requires passing a non-standard option to the Fetch api. https://www.npmjs.com/package/react-native-fetch-api

[core-rest-pipeline] add XhrHttpClient back for React-Native support

---

sdk/identity/identity/TROUBLESHOOTING.md

Doing the same that Xiang Yan did here: https://github.com/Azure/azure-sdk-for-net/pull/27800

[Identity] Add vscode workaround into the troubleshooting guide

---

common/smoke-test/run.js
sdk/eventgrid/eventgrid/samples-dev/consumeEventsFromServiceBusQueue.ts
sdk/eventgrid/eventgrid/samples/v4/javascript/consumeEventsFromServiceBusQueue.js
sdk/eventgrid/eventgrid/samples/v4/typescript/src/consumeEventsFromServiceBusQueue.ts

- previously the runner loads sample modules in `main()` without any error handling so any error would cause
`main()` to exit thus skip the rest of samples. This PR delays sample loading to when they
are executed so errors in loading modules can be caught and reported.
- the `consumeEventsFromServiceBusQueue` sample is calling `process.exit()` upon
completion, causing the runner to exit because it currently runs tests in-proc.
Update the test to exit with code 1 when failing.
None

[engsys] improve smoke test runner 

---

sdk/identity/identity/test/internal/node/clientSecretCredential.spec.ts

We have an issue that’s already tracking similar cases in which sending `tenantId` on getToken on live tests is failing in live mode: https://github.com/Azure/azure-sdk-for-js/issues/21055
This test should’ve been skipped before, but somehow it got through. Skipping now.

[Identity] Skipping test in live mode

---

sdk/core/core-tracing/README.md
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/README.md

#18649
Since we no longer use OpenTelemetry in @azure/core-tracing, this PR just
updates the README to reflect the recent changes. I also made a note about this
library not meant for end-user consumption.
No, it's just a readme update

[core-tracing] - Update README

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json

[AppConfig] add react-native mapping to ESM entrypoint

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/util/xml.browser.ts

- Add the mapping for react-native to ESM entrypoint
- Delay creating XML objects so packages not requiring XML functionality would not fail at module loading time.
@azure/core-http
#20806

[core-http] Address some issues for react-native

---

.github/CODEOWNERS

I'm removing myself from being designated in CODEONWERS as owning schema registry. The library has evolved quite a bit since I started it and I have not been able to keep up with all the changes. I will be more than happy to answer any questions that trace back to my original design or implementation or really any question at all, but I don't think I'm being useful enough to be a reviewer of every PR anymore.
None
N/A
I have not worked on this library in a long time and no longer feel comfortable being desingated as a code owner.
N/A
N/A
N/A
N/A
N/A

Remove nguerrera from schema-registry owners

---

sdk/servicebus/service-bus/test/internal/unit/receiverCommon.spec.ts

The log shows that when the test failed, the wait time is 1999 ms, closed to but
less than the expected 2000 ms. I suspect it is related to precision.
This PR allows a small tolerance of 5 ms when checking the delay.

[ServiceBus][Test] Add error tolerance when check for retry delay

---

samples/web-workers/README.md
samples/web-workers/ts/package.json

N/A
Fixes #20934
A customer reported a few issues:
- At some point when updating our arm-template path we lost a character for
url-encoded / - instead of %2F we only had %2... combined with the followed
character "a" this would end up as the * character instead of the intended
".../a..." character.
- It seems that a recent change in browsers to remove SharedArrayBuffer (see
https://developer.chrome.com/blog/enabling-shared-array-buffer/) has broken
JSDOM's dependencies and by extension JSDOM. This has been fixed upstream. 
For good measure, I just bumped both dependencies.
No, these are just samples

[samples] - Fix web-workers sample

---

sdk/schemaregistry/schema-registry-avro/test/public/errors.spec.ts

@schema-registry-avro
Fixes https://github.com/Azure/azure-sdk-for-js/issues/21175
The test checks if there was a request sent to register a schema even if the serialization of the input value failed. This request should return a schema ID for the registered schema but the test was expecting the schema ID to be undefined.
Successful run with this PR: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1480429&view=results. Note that the failure in min/max testing is expected because of a recent breaking change in Event Hubs that was not released yet (will be released this week).
N/A
N/A
N/A

[Schema Registry Avro] Fix nightly test

---

sdk/tables/data-tables/recordings/browsers/tableserviceclient_listtables/recording_should_list_by_page_with_filter.json
sdk/tables/data-tables/recordings/browsers/tableserviceclient_listtables/recording_should_list_with_filter.json
sdk/tables/data-tables/recordings/node/tableserviceclient_listtables/recording_should_list_by_page_with_filter.json
sdk/tables/data-tables/recordings/node/tableserviceclient_listtables/recording_should_list_with_filter.json
sdk/tables/data-tables/src/TableServiceClient.ts
sdk/tables/data-tables/test/public/tableserviceclient.spec.ts

#21156 
When querying tables using a filter, `byPage` ignores the query filter passed by users in the `listTables` call.
Pass the query filter to the page call, the same way we do this in `listEntities`.
Yes added 2 test cases
N/A
N/A

[Tables] Fix query filter in listTables by page

---

sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-admin/src/tracing.ts
sdk/keyvault/keyvault-admin/test/internal/userAgent.spec.ts
sdk/keyvault/keyvault-certificates/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/test/internal/userAgent.spec.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/test/internal/userAgent.spec.ts
sdk/keyvault/keyvault-secrets/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/test/internal/userAgent.spec.ts

@azure/keyvault-admin 
Resolves #21188
`KeyVaultClientContext` is a generated file that in core v1 included a
non-exported constant `packageVersion`. Because we have a test that depends on
that constant we always have to update the file to re-export it (as the
generated code does not export it).
Even worse, in coreV2 that constant is not even generated anymore, so the test
is outdated.
This PR fixes all of these issues by examining what we _actually_ care about,
which is that our user-agent includes the correct package version.
This way anyone can regenerate the code at any time without getting weird build
errors.

[KeyVault] - Fix user-agent tests in KeyVault Admin

---

sdk/communication/communication-identity/README.md
sdk/communication/communication-network-traversal/README.md
sdk/communication/communication-phone-numbers/README.md
sdk/communication/communication-short-codes/README.md

- just a typo
**Impacted packages:**
- @azure/communication-identity
- @azure/communication-network-traversal
- @azure/communication-phone-numbers

Added a missing space in Azure Communication READMEs

---

sdk/eventhub/event-hubs/test/internal/node/client.spec.ts
sdk/eventhub/event-hubs/test/public/node/client.spec.ts

event-hubs
Fixes #21226
The tracing client test adds an internal reference; however, the test is still
not excluded during min/max due to the nesting of the tracing reference. That
will be fixed separately, but it also makes sense to make this an internal test
as it tests the internals of how we trace.
N/A

[eventhub] - Move tracing spec to internal

---

sdk/schemaregistry/perf-tests/schema-registry-avro/README.md
sdk/schemaregistry/perf-tests/schema-registry-avro/test/deserialize.spec.ts
sdk/schemaregistry/perf-tests/schema-registry-avro/test/index.spec.ts

Related to https://github.com/Azure/azure-sdk-for-js/issues/16983
Missing performance test for deserialize
N/A
N/A
N/A

[Schema Registry Avro] Add perf test for deserialize

---

.github/CODEOWNERS

Excluding myself from owning /common/config/rush/pnpm-lock.yaml, but still owning everything else under /common/.

[CODEOWNERS] Remove @mikeharder from pnpm-lock.yaml

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json

The browser mapping for BufferSchedule.js was not updated/not added during refactoring in #11005.  This PR fixes the issue by updating the mapping paths for blob and adding the mapping for file-datalake.

[storage/blob,file-datalake] Fix browser mappings for BufferScheduler.js

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/README.md
sdk/test-utils/testing-recorder-new/README.md

TODO
Once we plan the work for the public recorder API and eventually release the package, we can remove the note that says "it is not intended for public usage" and update the docs accordingly.

[Recorder] Update readmes and changelog - prep 2.0 release

---

sdk/schemaregistry/schema-registry-avro/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/21288
Min testing is failing because EH is in beta and had breaking changes. Successful run with this PR: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1490234&view=results
N/A
N/A
N/A

[Schema Registry Avro] Update EH dep version

---

sdk/communication/communication-short-codes/swagger/README.md

-- 
The autorest file wasn't referencing the spec file by a commit hash.
The spec file will be removed (see https://github.com/Azure/azure-rest-api-specs/pull/18559) and it will break the builds for this repo. Please be aware that this package is not meant to be used by customers yet. **It is still a private preview release**.
--
--
- https://github.com/Azure/azure-rest-api-specs/pull/18559
- This is the pull request for removing the spec file
- https://github.com/Azure/azure-sdk-for-js/pull/18429
- This is the initial pull request that makes it clear that this package is for internal use only
--

Use a commit hash url when referencing the spec file

---

sdk/schemaregistry/schema-registry-avro/test/public/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/src/constants.ts
sdk/schemaregistry/schema-registry/src/conversions.ts
sdk/schemaregistry/schema-registry/src/generated/generatedSchemaRegistryClient.ts
sdk/schemaregistry/schema-registry/src/generated/index.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schema.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schemaGroupsOperations.ts
sdk/schemaregistry/schema-registry/src/models.ts
sdk/schemaregistry/schema-registry/swagger/README.md
sdk/schemaregistry/schema-registry/test/public/schemaRegistry.spec.ts

@azure/schema-registry
Fixes https://github.com/Azure/azure-sdk-for-js/issues/21294
These properties can help customers register updated versions of schemas based on previously registered ones because `name` and `groupName` are required by `registerSchema`.
N/A
N/A
N/A

[Schema Registry] Include name and groupName in SchemaProperties

---

sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/src/utils/sessionFilePath.ts
sdk/test-utils/recorder/src/utils/utils.ts

`@azure-tools/test-recorder` 2.0 couldn't be published because it depended on `test-utils` which is not public.
The only import is `isNode`, redeclaring and removing the test-utils dependency to go ahead with the release smoothly instead of waiting for `@azure/test-utils` release.
Edit: Getting it from core-utils instead, as suggested by @joheredi

[Recorder] Do not depend on test-utils

---

sdk/core/core-http-compat/CHANGELOG.md

Changelog updates to release the `@azure/core-http-compat` 1.3.0 so that `@azure/app-configuration`  can be released with the core-v2 changes.

[Core] Release 1.3.0 core-http-compat

---

eng/tools/dependency-testing/index.js

There are two changes being made to the script that runs min-max tests :
- Updating the regex that detects the internal references to allow patterns with multiple directories after the `src` folder to be recognized as internal references. Until now, the regex was only detecting patterns with a single directory after the `src` folder as an internal reference.
-  We are not ensuring consistent versioning of dependencies and dev-deps across packages anymore with this change - https://github.com/Azure/azure-sdk-for-js/pull/17587/. Due to this updating the "allowedAlternativeVersions" in the `updateCommonVersions` function is not required anymore. Hence dropping it.
- ALL THE PACKAGES  :D

[Min-max] Script updates to refine regex and remove allowAlternativeVersions step

---

sdk/schemaregistry/schema-registry-avro/test/public/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry-avro/test/public/utils/mockedSerializer.ts

@azure/schema-registry-avro's tests
N/A
[Min max tests](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1491520&view=logs&j=1c9a204a-48a9-5154-5204-230e40dbc42f&t=ef1f7f64-d4f7-5d9c-c677-8688f034a2b8) are failing because `SchemaProperties` interface has evolved and it now contains more things than the versions in older @azure/schema-registry so the mocked schema registry being used in the serializer tests does not type-check correctly.
I am casting objects of that interface to `any` for now to not bother with typechecking in tests between older and new versions. Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1493832&view=results
Alternatively, we can update the semver for the @azure/schema-registry dependency to `^1.1.0` but that will rule …

[Schema Registry Avro] Fix min/max testing

---

sdk/test-utils/recorder/package.json
sdk/test-utils/test-credential/package.json

Pipeline failed because of https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1497447&view=logs&j=5742d1c6-78e5-56de-b8e3-8788f4b41836&t=6c758387-9fbb-54a1-8544-1f7c5bb76fbc.
Unsetting `"private" : "true"` in package.json.
This has to be the last hurdle and should do trick to release

[Recorder] Do not set private to true to be able to release

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/core/core-http-compat/CHANGELOG.md

- Changelog copied from https://github.com/Azure/azure-sdk-for-js/pull/21204
- Followup of https://github.com/Azure/azure-sdk-for-js/pull/21254
- Sets unreleased for core-compat since it wasn't released (didn't create a new PR with an intention to avoid a few build pipelines)

[App Config] Tracing changes followup - update changelog

---

sdk/eventhub/event-hubs/test/internal/diagnostics/tracing.spec.ts
sdk/test-utils/test-utils/src/index.ts
sdk/test-utils/test-utils/src/tracing/mockContext.ts

event-hubs
Fixes eventhubs build
In https://github.com/Azure/azure-sdk-for-js/pull/21264 we updated our
tracing interfaces' startSpan to match runtime behavior of always returning a
context. 
This PR will then match our mocks in eventhubs to align with that behavior.
I originally just used `{ tracingOptions: { tracingContext: {} as TracingContext
} },` which felt brittle. We already have a mock context in test-utils so
exposing it made sense here and for anyone else that needs a TracingContext in
tests...

[eventhubs] - Update mocks to return TracingContext

---

sdk/core/core-tracing/test/tracingClient.spec.ts

For some reason we no longer lint in CI.  This PR fixes linter errors for core-tracing

[core-tracing] Fix linter errors

---

sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/recorder/test/testProxyClient.spec.ts
sdk/test-utils/recorder/test/testProxyTests.spec.ts
sdk/test-utils/recorder/test/utils/server.ts

* `@azure-tools/test-recorder`
* Fixes #21219
When the service returns a redirect response, our test proxy policy would not properly rewrite the second request that is made by the pipeline due to the redirection. This meant that the second request would go to the service directly, instead of via the test proxy, which causes a number of issues.
Until recently, the test proxy has been following redirects before returning responses during record mode. This has been identified as incorrect behavior (see some discussion at https://github.com/Azure/azure-sdk-tools/issues/2982), and a change is in the works to make the test proxy follow redirects by default (although the old behavior will still be configurable -- we'll need this for the browser scenario, since we don't control redirection …

[Recorder] Ensure redirected requests are passed to the recorder in Node

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/test/internal/errorHandling.spec.ts

@Azure/data-tables
#21385
When migrating to the new @azure/core-tracing version we accidentally removed the code that throws when a delete operation returns a non-404 status code
Added back the deleted code
Yes, added test to prevent this regression from happening again
N/A
n/a

Fix error handling in deleteTable

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts

core-rest-pipeline
N/A
We recently narrowed the types in core-tracing to reflect that `updatedOptions.tracingOptions` will always be defined.
Since core-rest-pipeline still depends on core-tracing@^1.0.0 our nightly build runs our code against core-tracing 1.0
causing a compilation failure.
The test using the min dev version is great as it found this issue.

[core-rest-pipeline] - Bump core-tracing min-version to 1.0.1

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/policies/msRestUserAgentPolicy.browser.ts
sdk/core/core-http/src/policies/msRestUserAgentPolicy.native.ts

- Add a react-native mapping to use xml2js for XML parsing/building.
- Add a react-native version of user agent policy to return proper information from the platform.  Without this the browser version is used, which caused run-time error as
`navigator` is not available. Using `require()` so we don't need to pull in `react-native` in our dependency list.

[core-http] fix xml and user agent policy for react-native

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/msal/nodeFlows/msalAuthorizationCode.ts

- Fixes https://github.com/Azure/azure-sdk-for-js/issues/21392
We are fixing two bugs in this PR -
- In the Authorization Code Credential, the public client was not being used. Due to this bug, without passing in the client secret, this credential would fail.
-  In the Authorization Code Credential, the tenant id was not being used. The `common` tenant was the only tenant being used by this credential.

[Identity] authorization code credential bug fixes
