sdk/template/template/sample.env

`sdk/template/template`
- https://github.com/Azure/azure-sdk-for-js/issues/20439
While working on [Migrate Template project to use CoreV2 #19748](https://github.com/Azure/azure-sdk-for-js/pull/19748), I noticed that the `sample.env` file does not provide information on what resource to create in order to run the recordings, tests, and samples.
This PR adds more comments on the `sample.env` file to specify that an App Configuration resource is needed and other env variables too.

[Template] Add more information in sample.env about what resource is needed and where to get the values

---

sdk/storage/storage-file-datalake/test/leaseclient.spec.ts

[storage-file-datalake]Stablize datalake test cases.

[storage-file-datalake]Stablize datalake test cases.

---

sdk/storage/README.md

This PR fixes the link verification failure in aggregate-reports pipeline.

[docs] fix broken link to storage api ref doc overview page

---

sdk/communication/communication-network-traversal/CHANGELOG.md
sdk/communication/communication-network-traversal/src/constants.ts

Mark 1.0.0 version of NetworkTraversal as deprecated

---

sdk/cognitiveservices/cognitiveservices-computervision/LICENSE.txt
sdk/cognitiveservices/cognitiveservices-computervision/package.json
sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts

@azure/cognitiveservices-computervision
None
The `@azure/cognitiveservices-computervision` Services team has requested a new SDK version to be released using the latest SDK. This PR is to regenerate based on their request.
No special design concerns are available.
None required.
N/A
```
autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.4.4 --package-version=8.2.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/3f78f3bc2d2546511853ad1931360ccdd34b0175/specification/cognitiveservices/data-plane/ComputerVision/readme.md
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.4] …
```

[@azure/cognitiveservices-computervision] - Release 8.2.0 of Compter Vision SDK

---

sdk/web-pubsub/test-resources.json
sdk/web-pubsub/web-pubsub/package.json
sdk/web-pubsub/web-pubsub/test.env
sdk/web-pubsub/web-pubsub/test/hubs.spec.ts
sdk/web-pubsub/web-pubsub/test/integration.spec.ts
sdk/web-pubsub/web-pubsub/test/testEnv.ts
sdk/web-pubsub/web-pubsub/tests.yml

webpubsub tests
Fixes https://github.com/Azure/azure-sdk-for-js/issues/20456
Fixes https://github.com/Azure/azure-sdk-for-js/issues/20457
- Setup live test pipeline
- `test-resources.json`
- `tests.yml`
- Add the test.env to show all the environment variables being used in the tests
- Updates tests
- Fixes test commands

[Web PubSub] Test env setup & live test pipeline

---

sdk/communication/communication-chat/README.md

ACS Chat JS readme
N/A
Update ACS Chat JS readme by including instruction to subscribe to connection status of real time notifications
N/A
N/A
https://github.com/Azure/azure-sdk-for-js/pull/18894 
N/A

Add instruction to subscribe to connection status of real time notifications in README

---

sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json

@Azure/communication-chat 
Changelog update

Update ACS Chat changelog

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts

[Identity] Update the identity - beta 1 version

---

common/config/rush/pnpm-lock.yaml
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/CHANGELOG.md
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/LICENSE
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/README.md
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/_meta.json
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/api-extractor.json
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/package.json
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/review/arm-sqlvirtualmachine.api.md
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/rollup.config.js
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/models/index.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/models/mappers.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/models/parameters.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/operations/availabilityGroupListeners.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/operations/operations.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/operations/sqlVirtualMachines.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/operationsInterfaces/operations.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/operationsInterfaces/sqlVirtualMachines.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/src/sqlVirtualMachineManagementClient.ts
sdk/sqlvirtualmachine/arm-sqlvirtualmachine/tsconfig.json
sdk/sqlvirtualmachine/ci.mgmt.yml

release for issue: https://github.com/Azure/sdk-release-request/issues/2463

sqlvirtualmachine-track2

---

sdk/keyvault/TROUBLESHOOTING.md
sdk/keyvault/keyvault-admin/README.md
sdk/keyvault/keyvault-admin/TROUBLESHOOTING.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/TROUBLESHOOTING.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/TROUBLESHOOTING.md
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/TROUBLESHOOTING.md

@azure/keyvault-admin
@azure/keyvault-certificates
@azure/keyvault-secrets
Resolves #20121
Adds troublehshooting guide for KV
Similar to .NET I am including a single TSG inside the service directory and
linking back to it from the individual package's TSGs.
I chose to keep things smallish for now, there aren't many well-known issues
that folks run into for AKV in JS, but I will ensure we add one when folks come
up for any questions. This at least gets the links in place for our READMEs
No, just docs 
https://github.com/Azure/azure-sdk-for-net/pull/26636/files

[Keyvault] - Add TROUBLESHOOTING guides

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] Prepare for 2022 March release

---

eng/pipelines/docindex.yml

Enables ToC generation in the default branch (in addition to the daily branch)

Generate docs ToC in the default branch

---

common/tools/eslint-plugin-azure-sdk/ci.yml
eng/pipelines/templates/steps/run-eslint.yml

Update trigger for ES lint plugin

Enable trigger for es lint pipeline

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts

Prepare release for core-rest-pipeline and core-client-rest

---

sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/CHANGELOG.md

[storage]Revert change for x-ms-encryption-algorithm and update changelog.

[storage]Revert change for x-ms-encryption-algorithm and update changelog.

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_fetch_a_blob_for_disk_with_bearer_token.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_fetch_a_blob_for_disk_with_challenge_bearer_token.js
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/index.ts
sdk/storage/storage-blob/src/models.ts
sdk/storage/storage-blob/src/policies/StorageBearerTokenChallengeAuthenticationPolicy.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
sdk/storage/storage-blob/test/utils/assert.ts

[storage]Added ability to specify Disk Compute audience when initializing blob client instances.

[storage]Added ability to specify Disk Compute audience when initializing blob client instances.

---

sdk/identity/identity/samples/AzureIdentityExamples.md

[Identity] Fixing some links in our Markdown sample

---

sdk/core/core-lro/test/utils/router.ts
sdk/core/core-lro/test/utils/router/paramRoutes.ts
sdk/core/core-lro/test/utils/router/utils.ts

N/A
Parts of the tests were using static variables to model internal state, but that setup is generally a bad practice and makes it awkward to generalize these functions.
This PR rewrites parts of the tests that were using static variables to be proper objects with internal state.
N/A
Will make adding more tests in https://github.com/Azure/azure-sdk-for-js/pull/20656 easier

[core-lro] update tests to support statefulness better

---

sdk/core/core-tracing/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20674
@xirzec, @jeremymeng, @maorleger for notification.

Fix Azure Core Tracing Readme Issues

---

sdk/monitor/monitor-opentelemetry-exporter/README.md
sdk/monitor/monitor-opentelemetry-exporter/samples/v1/javascript/httpSample.js

Update OpenTelemetry code snippets in Azure Monitor Exporter readme

---

sdk/synapse/synapse-artifacts/package.json

Fix the issue mentioned [here](https://github.com/Azure/azure-sdk-for-js/pull/20639/files/41008f847874829e77d23de1fd5b0c107f59cd13#diff-c19306f319094a355fad25e3ad80f7b66379f1ef3738866b1a16e90d2dd26346)

Synapse march release RP and fix the package.json issue

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts

None
Incrementing version of Identity after release of beta-1

update identity version to beta-2

---

sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/swagger/README.md

[storage]Fix issue of always send x-ms-encryption-algorithm header in request.

[storage]Fix issue of always send x-ms-encryption-algorithm header in request.

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[storage]Update change log and version for STG81 GA release.

[storage]Update change log and version for STG81 GA release.

---

sdk/communication/communication-phone-numbers/CHANGELOG.md

- `@azure/communication-phone-numbers`
- https://github.com/Azure/azure-sdk-for-js/issues/20056
- https://github.com/Azure/azure-sdk-for-js/issues/15814
Prepares the `communication-phone-numbers` SDK for release 1.2.0-beta.2 for March 10, 2022.
- https://github.com/Azure/azure-sdk-for-js/pull/20633
- https://github.com/Azure/azure-sdk-for-js/pull/20696
``` powershell
./eng/common/scripts/Prepare-Release.ps1 "@azure/communication-phone-numbers" "communication" "3/10/2022"
```

[Communication] - phone-numbers - Prepare `communication-phone-numbers` for release

---

sdk/schemaregistry/schema-registry-avro/test/clients/eventHubs.ts
sdk/schemaregistry/schema-registry-avro/test/clients/mocked.ts
sdk/schemaregistry/schema-registry-avro/test/clients/models.ts
sdk/schemaregistry/schema-registry-avro/test/messageAdapter.spec.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20779
N/A
Yes
N/A

[Schema Registry Avro] Test with messaging clients

---

sdk/eventhub/event-hubs/CHANGELOG.md

[Event Hubs] Prepare release

---

sdk/synapse/synapse-artifacts/CHANGELOG.md

Update release date for Synapse March Release

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-tracing/CHANGELOG.md
sdk/core/core-tracing/package.json

Resolves #18649
It's happening friends! We are GAing core-tracing 
N/A - just a version change

[core-tracing] - GA core-tracing

---

sdk/identity/identity/README.md

Addresses https://github.com/Azure/azure-sdk-for-net/issues/27263

Add Azure Account extension version requirement to Identity README

---

eng/pipelines/aggregate-reports.yml

No baseline for js. Remove the baseline from yaml
Fixed the failed pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1433901&view=results
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1436935&view=results

Remove the baseline from aggregate-report

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/template/template/package.json
sdk/test-utils/test-utils/package.json

@azure/ai-form-recognizer
@aazure/event-hubs
N/A
Just bumping the version of these packages which depend on core-tracing 1.0.0-preview.14 to instead depend on 1.0.0
#20888 which I am holding off on

upgrade existing libraries to core-tracing 1.0.0

---

common/config/rush/pnpm-lock.yaml
sdk/applicationinsights/arm-appinsights/CHANGELOG.md
sdk/applicationinsights/arm-appinsights/README.md
sdk/applicationinsights/arm-appinsights/_meta.json
sdk/applicationinsights/arm-appinsights/package.json
sdk/applicationinsights/arm-appinsights/review/arm-appinsights.api.md
sdk/applicationinsights/arm-appinsights/rollup.config.js
sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClient.ts
sdk/applicationinsights/arm-appinsights/src/models/index.ts
sdk/applicationinsights/arm-appinsights/src/operations/workbooks.ts
sdk/applicationinsights/arm-appinsights/src/operationsInterfaces/workbooks.ts
sdk/applicationinsights/ci.mgmt.yml

release for issue : https://github.com/Azure/sdk-release-request/issues/2537

applicationinsight-release

---

sdk/schemaregistry/schema-registry-avro/test/clients/eventHubs.ts
sdk/schemaregistry/schema-registry-avro/test/clients/mocked.ts
sdk/schemaregistry/schema-registry-avro/test/clients/models.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20965
Receive Event Hubs messages sent by other languages with serialized payloads and make sure the JS serializer can deserialize them to expected values. The tests passed.
Thanks @swathipil for organizing this exercise. 
N/A
Yes

[Schema Registry Avro] Add cross-language testing

---

eng/pipelines/docindex.yml

No main updates on mainly triggered pipeline.

Don't update main for manually triggered pipeline.

---

eng/tools/analyze-deps/package-lock.json

Bumping some outdated dependencies since the automation doesn't maintain this lockfile.

[engsys] Update lockfile for analyze-deps tool.

---

.github/CODEOWNERS

Doing a bit of cleanup here and taking over some notification rules for Ramya.

Update CODEOWNERS to remove @ramya-rao-a

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

[KeyVault]  - Prepare for release

---

.github/CODEOWNERS

updated according to the [guidance](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1647518325907?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1647518325907&teamName=Azure%20SDK&channelName=General&createdTime=1647518325907)

Use GH aliases

---

sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/clients/mocked.ts
sdk/schemaregistry/schema-registry-avro/test/errors.spec.ts
sdk/schemaregistry/schema-registry-avro/test/utils/isLive.ts
sdk/schemaregistry/schema-registry-avro/test/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry-avro/test/withMessagingClients.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/21008
What is the errors story for the serializer?
N/A
Lots!
N/A

[Schema Registry Avro] Add comprehensive test suite for error scenarios

---

.github/fabricbot.json

The focus of these changes is to add rules for the Communication sub-areas to apply unique labels to better integrate with the team's tooling.

[GitHub Automation] Communication Rules

---

.github/fabricbot.json

The focus of these changes is to add the rule for reacting when the `CXP Attention` rule is applied.

[Fabric Bot] Add CXP Responder

---

sdk/monitor/monitor-query/swagger/logquery.md
sdk/monitor/monitor-query/swagger/metric-definitions.md
sdk/monitor/monitor-query/swagger/metric-namespaces.md
sdk/monitor/monitor-query/swagger/metrics.md

Update the `input-file` values to align with what .NET and Python are already doing. The goal is consistency across Tier 1 languages.

Update Monitor Query Swagger files to use SHA-1 hash

---

sdk/core/core-tracing/CHANGELOG.md

[core-tracing] - Prep for release

---

sdk/communication/communication-identity/CHANGELOG.md

- `@azure/communication-identity`
Related ADO: https://dev.azure.com/azure-sdk/Release/_workitems/edit/9195/

Prepare @azure/communication-identity 1.2.0-beta.2 release

---

sdk/communication/communication-short-codes/CHANGELOG.md

- `@azure-tools/communication-short-codes`
- https://github.com/Azure/azure-sdk-for-js/issues/15814
- https://github.com/Azure/azure-sdk-for-js/pull/19043
``` powershell
.\eng\common\scripts\Prepare-Release.ps1 "@azure-tools/communication-short-codes" "communication" "3/31/2022"
```

[Communication] short-codes - Prepare communication-short-codes for release

---

sdk/test-utils/ci.yml
sdk/test-utils/test-utils/CHANGELOG.md
sdk/test-utils/testing-recorder-new/CHANGELOG.md

Updated CI.yml with all artifacts in test-utils service

Update utils CI to add all artifacts

---

common/config/rush/pnpm-lock.yaml
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/constants.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/swagger/README.md

Looks like I missed updating KeyVault Keys's version in a prior PR. This PR
fixes that.

[KeyVault] - Fix versioning for KV Keys

---

eng/pipelines/aggregate-reports.yml

* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1481335&view=results

Move aggregate-reports to azsdk pool

---

.github/CODEOWNERS

Since I'm working on ACR now, thinking I should probably be on the list here :)

Update CODEOWNERS to add @timovv to ACR

---

sdk/digitaltwins/dtdl-parser/README.md

- dtdl-parser
- #21105
Updates the dtdl-parser README based upon comments from #21105
Made the changes as requested in the issue.
Not necessary as updating the README.
- #21105

Updating DigitalTwins README for #21105

---

sdk/identity/identity/TROUBLESHOOTING.md

https://github.com/Azure/azure-sdk-for-js/issues/21137
- This PR adds the error message and mitigation for the case when an invalid tenant id is passed in the existing Troubleshooting guide.
- This error has been reproduced with the JS SDK.

[Identity] update troubleshooting guide for invalid tenant id scenario

---

sdk/datafactory/arm-datafactory/CHANGELOG.md
sdk/datafactory/arm-datafactory/_meta.json
sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
sdk/datafactory/arm-datafactory/src/models/index.ts
sdk/datafactory/arm-datafactory/src/models/mappers.ts
sdk/datafactory/arm-datafactory/src/operations/dataFlowDebugSession.ts
sdk/datafactory/arm-datafactory/src/operations/integrationRuntimeObjectMetadata.ts
sdk/datafactory/arm-datafactory/src/operations/integrationRuntimes.ts
sdk/datafactory/arm-datafactory/src/operations/triggers.ts
sdk/datafactory/ci.mgmt.yml

release for issue : https://github.com/Azure/sdk-release-request/issues/2608

datafactory-track2-release

---

sdk/schemaregistry/schema-registry-avro/samples/v1-beta/javascript/package.json
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/javascript/schemaRegistryAvroSample.js
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/javascript/withEventHubsBufferedProducerClient.js
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/javascript/withEventHubsConsumerClient.js
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/javascript/withEventHubsProducerClient.js
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/typescript/package.json
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/typescript/src/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/typescript/src/withEventHubsBufferedProducerClient.ts
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/typescript/src/withEventHubsConsumerClient.ts
sdk/schemaregistry/schema-registry-avro/samples/v1-beta/typescript/src/withEventHubsProducerClient.ts

post release automation did not publish the samples so I am publishing them here manually.
Also fixes https://github.com/Azure/azure-sdk-for-js/issues/20664
Related issue: https://github.com/Azure/azure-sdk-for-js/issues/21250

[Schema Registry Avro] Publish samples

---

sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/src/constants.ts
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts

@azure/schema-registry
Related to https://github.com/Azure/azure-sdk-for-js/issues/21199
Tracing was missing and this PR adds it using core-tracing v1.
N/A
N/A
N/A

[Schema Registry] Use tracing

---

eng/scripts/Language-Settings.ps1

Package dependency problem is resolved and local testing in the validation container shows success.

Readd @azure/communication-react

---

sdk/cosmosdb/cosmos/src/documents/DatabaseAccount.ts

None
1
https://github.com/Azure/azure-sdk-for-js/issues/20669
Typo in code

update Consistency level request change

---

sdk/communication/communication-phone-numbers/CHANGELOG.md

@azure/communication-phone-numbers
--
--
--
--
--
eng/common/scripts/Prepare-Release.ps1 "@azure/communication-phone-numbers" "communication" "04/06/2022"

[phone numbers sdk] Release 1.2.0-beta3

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/purview/purview-catalog-rest/CHANGELOG.md
sdk/tables/data-tables/CHANGELOG.md

@azure-rest/purview-catalog
N/A
Update Changelog to prepare for release
N/A
N/A
N/A
N/A

Prepare for release

---

sdk/web-pubsub/web-pubsub/CHANGELOG.md
sdk/web-pubsub/web-pubsub/package.json
sdk/web-pubsub/web-pubsub/recordings/node/hubclient_working_with_a_hub/recording_can_trace_through_the_various_options.json
sdk/web-pubsub/web-pubsub/src/generated/generatedClientContext.ts
sdk/web-pubsub/web-pubsub/src/groupClient.ts
sdk/web-pubsub/web-pubsub/src/hubClient.ts
sdk/web-pubsub/web-pubsub/src/tracing.ts
sdk/web-pubsub/web-pubsub/swagger/README.md
sdk/web-pubsub/web-pubsub/test/hubs.spec.ts

@azure/web-pubsub
#21199
Now that core-tracing has GA'd we can start to migrate packages over. In order
to help folks on the team with upgrades, I am upgrading a few packages that
cover the various scenarios using the new tracing APIs.
Yes

[web-pubsub] - Update to core-tracing 1.0

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json

core-lro
core-client
#21199
Just doing the upgrades here for core-lro and core-client, neither of which uses the behavior changes from
core-tracing, just the types.

[core] - Upgrade core-client and core-lro to core-tracing 1.0

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/test-credential/CHANGELOG.md

The previous release step failed because the changelog is not of the expected format, refer https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1497284&view=results.
Updating to follow the changelog guidelines.

[Recorder] Changelog - follow guidelines

---

sdk/appconfiguration/app-configuration/test/public/tracing.spec.ts
sdk/core/core-rest-pipeline/src/restError.ts
sdk/core/core-rest-pipeline/src/util/helpers.ts

- code changes were merged while our CI failed to run lint command on the PRs.

[core,appconfig] Fix linter errors

---

sdk/quantum/quantum-jobs/package.json

quantum-jobs
Resolves #21281
Just picked this package at random to upgrade to core-tracing 1.0. Because of
the state of the package I decided _not_ to add tracing functionality at this
time, and just upgrade package.json - hence this tiny PR.

[quantum-jobs] - Upgrade to core-tracing 1.0

---

sdk/communication/communication-sms/package.json
sdk/core/core-asynciterator-polyfill/CHANGELOG.md

`@azure/communication-sms`
Fix for CHANGELOG.md / Version issues

Fix up issues related to CHANGELOG.md and Versions

---

sdk/storage/storage-blob-changefeed/recordings/node/change_feed_event_schema_test/recording_event_schema_v1_test.js
sdk/storage/storage-blob-changefeed/recordings/node/change_feed_event_schema_test/recording_event_schema_v3_test.js
sdk/storage/storage-blob-changefeed/recordings/node/change_feed_event_schema_test/recording_event_schema_v4_test.js
sdk/storage/storage-blob-changefeed/recordings/node/change_feed_event_schema_test/recording_event_schema_v5_test.js
sdk/storage/storage-blob-changefeed/review/storage-blob-changefeed.api.md
sdk/storage/storage-blob-changefeed/src/Chunk.ts
sdk/storage/storage-blob-changefeed/src/models/BlobChangeFeedEvent.ts
sdk/storage/storage-blob-changefeed/src/utils/utils.common.ts
sdk/storage/storage-blob-changefeed/test/blobchangefeedclient.spec.ts
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV1.json
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV3.json
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV4.json
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV5.json
sdk/storage/storage-blob-changefeed/test/utils/testutils.common.ts

Add support for change feed schema V3, V4 and V5

Add support for change feed schema V3, V4 and V5

---

sdk/appconfiguration/app-configuration/README.md

- app-configuration
- #20700
Updates the README with a Troubleshooting Guide to talk about enable logging.
This copied the standard `TroubleShooting Section` from other README files and applied it to app-configuration.
Not applicable as adding to the README

Updating AppConfig README with Troubleshooting Section

---

sdk/monitor/monitor-query/TROUBLESHOOTING.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20143
Created a troubleshooting guide with errors for different scenarios for @azure/monitor-query in TypeScript.

[Monitor query] Troubleshooting guide for Support

---

sdk/eventhub/event-hubs/README.md
sdk/servicebus/service-bus/README.md

- add information about required polyfills for browsers
- add webpack example configuration

[Docs][EventHub,ServiceBus] add information about browser polyfills

---

sdk/core/core-client-rest/src/urlHelpers.ts
sdk/eventgrid/eventgrid/src/eventGridClient.ts
sdk/storage/storage-blob-changefeed/src/utils/utils.common.ts
sdk/storage/storage-blob-changefeed/test/utils/testutils.common.ts

while we are investigating why linting wasn't happening in PR pipeline.

[engsys] fixing linter errors

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/quantum/quantum-jobs/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-datalake/package.json
sdk/storage/perf-tests/storage-file-share/package.json
sdk/storage/storage-blob-changefeed/CHANGELOG.md
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob-changefeed/src/utils/utils.common.ts
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV3.json
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV4.json
sdk/storage/storage-blob-changefeed/test/resources/EventSchemaV5.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-file-share/test/fileclient.spec.ts

Change to parse wasSoftDeleted from a string in change feed.
Update changelog and version for storage packages.

Change to parse wasSoftDeleted from a string in change feed.

---

sdk/communication/communication-identity/test/public/utils/mockHttpClients.ts

Communication Identity SDK
This PR fixes BUG https://skype.visualstudio.com/SPOOL/_workitems/edit/2820803. One of the imports in one file was causing live test pipeline to fail.

Fix failing live tests pipeline

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-amqp/review/core-amqp.api.md
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/retry.ts
sdk/core/core-auth/package.json
sdk/core/core-client-rest/package.json
sdk/core/core-client/package.json
sdk/core/core-crypto/package.json
sdk/core/core-http-compat/package.json
sdk/core/core-http/package.json
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-lro/package.json
sdk/core/core-paging/package.json
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/xhrHttpClient.ts
sdk/core/core-tracing/package.json
sdk/core/core-util/package.json
sdk/core/core-xml/package.json
sdk/core/logger/package.json
sdk/core/perf-tests/core-rest-pipeline/package.json

Upgrade typescript from 4.2 to 4.6 for core packages

[core] upgrade `typescript` dev dependency from 4.2 to 4.6

---

sdk/botservice/arm-botservice/CHANGELOG.md
sdk/botservice/arm-botservice/_meta.json
sdk/botservice/arm-botservice/package.json
sdk/botservice/arm-botservice/review/arm-botservice.api.md
sdk/botservice/arm-botservice/samples-dev/channelsUpdateSample.ts
sdk/botservice/arm-botservice/src/azureBotService.ts
sdk/botservice/arm-botservice/src/models/index.ts
sdk/botservice/arm-botservice/src/models/mappers.ts
sdk/botservice/arm-botservice/src/models/parameters.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2662

botservice-release

---

sdk/datafactory/arm-datafactory/CHANGELOG.md
sdk/datafactory/arm-datafactory/_meta.json
sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
sdk/datafactory/arm-datafactory/src/models/index.ts
sdk/datafactory/arm-datafactory/src/models/mappers.ts

release for issue:https://github.com/Azure/sdk-release-request/issues/2690

datafactory-release

---

eng/scripts/Language-Settings.ps1

Add support for $PackageInfos parameter in Validate-javascript-DocMsPackages

Add support for batched DocMS validation

---

sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts

Better approach to match for CLI errors. Better than the approach we did here: #21525 
Related to: #21151

[Identity] Better approach to match more Azure CLI errors

---

sdk/deviceupdate/iot-device-update-rest/package.json
sdk/digitaltwins/dtdl-parser/package.json
sdk/digitaltwins/dtdl-parser/src/parser/modelParserImpl.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json

We removed this for most of packages but missed these.

[engsys] remove typedoc dependencies and docs npm script

---

sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/package.json
sdk/locks/arm-locks-profile-hybrid-2019-03-01/package.json
sdk/monitor/arm-monitor-profile-2019-03-01-hybrid/package.json
sdk/network/arm-network-profile-2019-03-01-hybrid/package.json
sdk/policy/arm-policy-profile-hybrid-2019-03-01/package.json
sdk/resources/arm-resources-profile-hybrid-2019-03-01/package.json
sdk/storage/arm-storage-profile-2019-03-01-hybrid/package.json
sdk/subscription/arm-subscriptions-profile-hybrid-2019-03-01/package.json

Multiple Profile Packages.
None
Version Update to release these profile packages
Nothing specific. Simple Version Update
No.
N/A

Version Update for Profile Packages

---

sdk/test-utils/recorder/src/recorder.ts

- Fixes #20400
Properly handle recorder errors due to mismatches etc., and pretty-print the error messages to make debugging easier.
Old error message format (example):
```
RestError: {"Message":"Unable to find a record for the request 
POST https://fakeaccountname.table.core.windows.net/Tables?st=2021-08-03T08:52:15Z\u0026spr=https\u0026sig=fakesigval\n
Header differences:\n \u003CConnection\u003E is absent in record, value \u003Ckeep-alive\u003E\n
Body differences:\n","Status":"NotFound"}
```
New error message format (different example, but note that it's a lot more legible):
```
RecorderError: Unable to find a record for the request DELETE https://myregistry.azurecr.io/v2/oci-artifact/manifests/sha256%3A70e2ffca8e79adc4bd34b67363a972522d75933e435084826d39a …
```

[Recorder] improve error messages

---

sdk/communication/communication-sms/CHANGELOG.md

Communication-SMS Release 1.2.0-beta.1

---

sdk/core/core-xml/CHANGELOG.md
sdk/core/core-xml/package.json

- for ESM entry point
- and xml building/parsing using `fast-xml-parser`

[core-xml] add `react-native` mapping

---

eng/pipelines/mgmt-ci.yml

Updates mgmt CI pipeline to use global variable template

Use global variable template for track1 mgmt pipeline

---

sdk/videoanalyzer/video-analyzer-edge/CHANGELOG.md
sdk/videoanalyzer/video-analyzer-edge/README.md

@Azure/azure-video-analyzer 
Added deprecation notice to video analyzer data plane sdk
- [x ] Added a changelog (if necessary)

[AVA] Add deprecation notice to Video Analyzer data plane sdk

---

sdk/core/abort-controller/CHANGELOG.md
sdk/core/core-client/CHANGELOG.md
sdk/core/core-http-compat/CHANGELOG.md
sdk/core/core-http/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-tracing/CHANGELOG.md
sdk/core/core-util/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md

[core] prepare for May 2022 release

---

sdk/appconfiguration/app-configuration/CHANGELOG.md

[App Config] 1.4.0-beta.1 release

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/batchingPartitionChannel.ts
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts

Based on feedback in https://apiview.dev/Assemblies/Review/6b9907663c4b45c684ebe419d217324f#@azure/event-hubs!EventHubBufferedProducerClientOptions#onSendEventsErrorHandler:member

[Event Hubs] Buffered Producer error handler to be sync

---

sdk/storage/storage-blob/recordings/browsers/containerclient/recording_listblobsbyhierarchy_to_list_uncommitted_blobs.json
sdk/storage/storage-blob/recordings/browsers/containerclient/recording_listblobsflat_to_list_uncommitted_blobs.json
sdk/storage/storage-blob/recordings/node/containerclient/recording_listblobsbyhierarchy_to_list_uncommitted_blobs.js
sdk/storage/storage-blob/recordings/node/containerclient/recording_listblobsflat_to_list_uncommitted_blobs.js
sdk/storage/storage-blob/samples-dev/advancedRequestOptions.ts
sdk/storage/storage-blob/samples-dev/errorsAndResponses.ts
sdk/storage/storage-blob/samples/v12/javascript/advancedRequestOptions.js
sdk/storage/storage-blob/samples/v12/javascript/errorsAndResponses.js
sdk/storage/storage-blob/samples/v12/typescript/src/advancedRequestOptions.ts
sdk/storage/storage-blob/samples/v12/typescript/src/errorsAndResponses.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/containerclient.spec.ts
sdk/storage/storage-file-datalake/samples/v12/javascript/dataLakeServiceClient.js
sdk/storage/storage-file-datalake/samples/v12/typescript/src/dataLakeServiceClient.ts

Fix issue to expose blob properties in raw response in blob listing methods.

Fix issue to expose blob properties in raw response.

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/TelemetryPolicyFactory.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/src/TelemetryPolicyFactory.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/TelemetryPolicyFactory.ts
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/src/TelemetryPolicyFactory.ts

Refined user-agent value to avoid failure when os information is not available on some platforms.

[storage]Refined user-agent value

---

sdk/communication/communication-job-router/CHANGELOG.md
sdk/communication/communication-job-router/review/communication-job-router.api.md
sdk/communication/communication-job-router/src/generated/src/index.ts
sdk/communication/communication-job-router/src/generated/src/jobRouterApiClient.ts
sdk/communication/communication-job-router/src/generated/src/jobRouterApiClientContext.ts
sdk/communication/communication-job-router/src/generated/src/models/index.ts
sdk/communication/communication-job-router/src/generated/src/models/mappers.ts
sdk/communication/communication-job-router/src/generated/src/models/parameters.ts
sdk/communication/communication-job-router/src/generated/src/operations/jobRouter.ts
sdk/communication/communication-job-router/src/generated/src/operationsInterfaces/jobRouter.ts
sdk/communication/communication-job-router/src/models/options.ts
sdk/communication/communication-job-router/src/models/requests.ts
sdk/communication/communication-job-router/src/models/responses.ts
sdk/communication/communication-job-router/src/routerClient.ts
sdk/communication/communication-job-router/swagger/README.md
sdk/communication/communication-job-router/swagger/swagger.json
sdk/communication/communication-job-router/test/internal/utils/mockClient.ts

Run autorest with latest service code
Update client according to first review feedback
Use whole model update for now instead of partial update for update methods (due to lacking of mergePatch support in sdk)
TODO. wait Worker routes to update in ADO, then update the methods in client for worker routes
https://skype.visualstudio.com/SPOOL/_workitems/edit/2665462

Latest API & Swagger (Update post patch routes, etc)

---

.scripts/automation_generate.sh

use latest codegen

---

sdk/search/search-documents/src/TROUBLESHOOTING.md
sdk/search/search-documents/src/serviceModels.ts

None
All languages are supposed to have a similar troubleshooting guide for search documents SDK. The Java SDK has the following troubleshooting guide - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/TROUBLESHOOTING.md. I have created a similar one for JS SDK.
N/A
N/A Documentation change
N/A
@xirzec @joheredi Please review and approve the PR

[@azure/search-documents] Troubleshooing Guide for Search Documents

---

sdk/schemaregistry/schema-registry/CHANGELOG.md

[Schema Registry] Prepare for May release

---

sdk/eventhub/event-hubs/CHANGELOG.md

[Event Hubs] Prepare for May release

---

sdk/eventhub/event-hubs/samples/v5/javascript/README.md
sdk/eventhub/event-hubs/samples/v5/javascript/iothubConnectionString.js
sdk/eventhub/event-hubs/samples/v5/javascript/iothubConnectionStringWebsockets.js
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/javascript/receiveEvents.js
sdk/eventhub/event-hubs/samples/v5/javascript/sendBufferedEvents.js
sdk/eventhub/event-hubs/samples/v5/javascript/sendEvents.js
sdk/eventhub/event-hubs/samples/v5/javascript/useWithIotHub.js
sdk/eventhub/event-hubs/samples/v5/javascript/usingAadAuth.js
sdk/eventhub/event-hubs/samples/v5/javascript/websockets.js
sdk/eventhub/event-hubs/samples/v5/typescript/README.md
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionString.ts
sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionStringWebsockets.ts
sdk/eventhub/event-hubs/samples/v5/typescript/src/receiveEvents.ts
sdk/eventhub/event-hubs/samples/v5/typescript/src/sendBufferedEvents.ts
sdk/eventhub/event-hubs/samples/v5/typescript/src/websockets.ts

By running `dev-tool samples publish -f`

[Event Hubs] Publish samples

---

sdk/recoveryservicesbackup/arm-recoveryservicesbackup/CHANGELOG.md
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/_meta.json
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/package.json
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/review/arm-recoveryservicesbackup.api.md
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/index.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/mappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/recoveryServicesBackupClient.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2749

recovervicesbackup-track2-release

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/test/internal/node/partitionKeyHashMap.spec.ts

Fix tests by making sure test artificats are copied in both unit-test and integration-test modes.
Failed run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1557237&view=logs&j=b800360f-d572-5e16-3e20-e4f204d3fbd3&t=3b97752f-f53c-5e36-3379-45368efa0b3c
Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1559570&view=results

[Event Hubs] Fix tests

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

Bump version for storage packages.

Bump version for storage packages.

---

.github/CODEOWNERS

It's been a fun adventure friends! Updating the CODEOWNERS file to ensure the right people
are notified of any nightly build errors.
❤️

[CODEOWNERS] - Transfer ownership of keyvault and tracing

---

sdk/digitaltwins/digital-twins-core/CHANGELOG.md
sdk/digitaltwins/digital-twins-core/package.json
sdk/digitaltwins/digital-twins-core/src/constants.ts
sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
sdk/digitaltwins/digital-twins-core/src/tracing.ts
sdk/digitaltwins/digital-twins-core/test/internal/digitalTwinsClient.spec.ts
sdk/iot/iot-modelsrepository/CHANGELOG.md
sdk/iot/iot-modelsrepository/package.json

digital-twins-core
iot-modelsrepository
#21199
Now that @azure/core-tracing has GA'd we are upgrading all our packages to the latest APIs. 
For iot-modelsrepository there was minimal changes as this package isn't even using tracing. For digital-twins 
there were more involved changes to test files and source files.
Not yet, but I will add one for tracing shortly

[digital-twins] - Upgrade to core-tracing 1.0

---

sdk/core/README.md

[core] Fix link in README

---

eng/pipelines/aggregate-reports.yml

Upgrade node version from 10 to 16 in aggregate reports pipeline.

Upgrade version in aggregate reports pipeline

---

eng/pipelines/templates/variables/globals.yml

Update default node version to 16

Update default node version to 16

---

sdk/textanalytics/ai-text-analytics/.nycrc
sdk/textanalytics/ai-text-analytics/LICENSE
sdk/textanalytics/ai-text-analytics/tests.yml
sdk/textanalytics/ai-text-analytics/tsdoc.json

These files were deleted by mistake in the PR that rewrote the text analytics client.

[Text Analytics] Adding missing files

---

sdk/core/core-paging/CHANGELOG.md

[core-paging] Prepare release 

---

sdk/eventgrid/arm-eventgrid/CHANGELOG.md
sdk/eventgrid/arm-eventgrid/_meta.json
sdk/eventgrid/arm-eventgrid/package.json
sdk/eventgrid/arm-eventgrid/review/arm-eventgrid.api.md
sdk/eventgrid/arm-eventgrid/src/eventGridManagementClient.ts
sdk/eventgrid/arm-eventgrid/src/models/index.ts
sdk/eventgrid/arm-eventgrid/src/operations/domainEventSubscriptions.ts
sdk/eventgrid/arm-eventgrid/src/operations/domainTopicEventSubscriptions.ts
sdk/eventgrid/arm-eventgrid/src/operations/topicEventSubscriptions.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2776

eventgrid-track2-release

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

[Text Analytics] update link

---

samples/frameworks/react-native-expo/ts/appconfigBasic/README.md

This PR fixes broken link verification failure in aggregate reports pipeline.

[sample] fix broken link verification failure

---

.github/CODEOWNERS

Updating CODEOWNERS Communication NetworkTraversal

---

sdk/template/template/README-EXAMPLE.md

- Template project
- Fix broken links in the template example README caused by App Config sample regeneration

Fix links in template README

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Prepare @azure/cosmos for release

Bump minor version for release

---

sdk/appconfiguration/app-configuration/samples/v1/javascript/README.md
sdk/appconfiguration/app-configuration/samples/v1/javascript/featureFlag.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/getSettingOnlyIfChanged.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/helloworld.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/helloworldWithLabels.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/listConfigurationSettings.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/listRevisions.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/optimisticConcurrencyViaEtag.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/package.json
sdk/appconfiguration/app-configuration/samples/v1/javascript/sample.env
sdk/appconfiguration/app-configuration/samples/v1/javascript/secretReference.js
sdk/appconfiguration/app-configuration/samples/v1/javascript/setReadOnlySample.js
sdk/appconfiguration/app-configuration/samples/v1/typescript/README.md
sdk/appconfiguration/app-configuration/samples/v1/typescript/package.json
sdk/appconfiguration/app-configuration/samples/v1/typescript/sample.env
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/featureFlag.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/helloworld.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/helloworldWithLabels.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/listConfigurationSettings.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/listRevisions.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/secretReference.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/src/setReadOnlySample.ts
sdk/appconfiguration/app-configuration/samples/v1/typescript/tsconfig.json

It was removed earlier when publishing v1-beta samples.  This PR adds them back.

[appconfig][samples] add back v1 published samples

---

sdk/identity/identity/test/manual-integration/Kubernetes/Dockerfile
sdk/servicebus/service-bus/test/stress/Dockerfile

Update docker files to pass container registry as arg

Update docker registry using args

---

eng/tools/dependency-testing/README.md

Adding debug section to min-max readme

[Min-max] Adding Debug section to min-max readme

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/trace.exporter.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/assert.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts

Export Span events as Message and Exception telemetry

[Azure Monitor Exporter] Export Span events

---

eng/pipelines/docindex.yml

Testing pipeline
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1616714&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=1f8ee413-f298-5146-a47d-631141d8ee72
The docindex pipeline failed at secure supply chain step in their scream testing. Add the global variables to suppress the warning.

Suppress the secure supply chain warning in docindex

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md

[Form Recognizer] Changelog

---

common/config/rush/pnpm-lock.yaml
sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/package.json
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts
sdk/tables/data-tables/CHANGELOG.md

This PR updates CHANGELOGs to prepare for June Releases

Prepare June releases

---

sdk/formrecognizer/ai-form-recognizer/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/21107
@xirzec, @meeraharidasa, @dw511214992 for notification.

Fix Azure Form Recognizer Readme Issues

---

sdk/communication/communication-chat/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20666
@xirzec, @mayurid, @LuChen-Microsoft for notification.

Fix Azure Communication Chat Readme Issue

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/src/models/publicLogsModels.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20644
Provided documentation for getting statistics and visualization information from the logsQuery method and the expected result.

[Monitor query] Adding documentation for statistics and visualization

---

sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts

This PR adds a try-finally block to ensure test clean up in cases of test failing.

[servicebus][test] Ensure test clean up

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/MIGRATION-v3_v4.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples-dev/analyzeIdentityDocument.ts
sdk/formrecognizer/ai-form-recognizer/src/documentAnalysisClient.ts
sdk/formrecognizer/ai-form-recognizer/src/models/documentElements.ts
sdk/formrecognizer/ai-form-recognizer/src/prebuilt/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms/polygon.ts
sdk/formrecognizer/ai-form-recognizer/test/public/node/analysis.spec.ts
sdk/formrecognizer/ci.yml

This is somewhat of a laundry-list PR:
- Update the CHANGELOG to include a few missing entries and specify the release date (today).
- Updated the README and added several deprecation warnings with linkable anchors.
- Updated the migration guide.
- Removed table caption/footnotes from the API, as they are not produced by the service.
- Fixed a broken sample.
- Added a simple test for the presence of `paragraphs`.

[ai-form-recognizer] Prepare release 4.0.0-beta.4

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] prepare for June 2022 release

---

sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts

https://github.com/Azure/azure-sdk-for-js/issues/22134

[web-pubsub-express] fix Event Handler erroneous behavior due to ce-hub header not preserving case

---

.github/CODEOWNERS

Replace Daniel with Karishma
/cc: @KarishmaGhiya @joshfree

Update CODEOWNERS entry for Azure Identity

---

sdk/servicebus/service-bus/test/internal/operationOptionsForATOM.spec.ts
sdk/servicebus/service-bus/test/public/amqpAnnotatedMessage.spec.ts

so it won't impact following tests.

[ServiceBus][Test] resetTracer at the end of tracing test

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts

[identity] Hotfix/identity version bump to 2.0.5

---

documentation/RLC-quickstart.md

Update links in RLC getstarted

---

sdk/storage/storage-file-datalake/src/utils/constants.ts

Add support for partition dns in datalake package.

Add support for partition dns in datalake package.

---

common/config/rush/pnpm-lock.yaml
sdk/storage/storage-blob-changefeed/CHANGELOG.md
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts

Update version and change log for STG83 preview.

Update version and change log for STG83 preview.

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

https://github.com/Azure/azure-sdk-tools/issues/3126
The Pr is to speed up the generate-job-matrix step by minimizing the checkout files.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1647567&view=results

Exclude test recording files.

---

sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

Regenerated using the code gen as updated in https://github.com/Azure/autorest.typescript/pull/1420. This addresses one feedback received earlier.

[Text Analytics] Intersections converted to interfaces

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/MIGRATION-v3_v4.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts

This fixes an issue that was introduced in the code generator support for `api-version`. I've also updated the CHANGELOG, README, etc. for release.

[ai-form-recognizer] Update generated code backend

---

documentation/RLC-quickstart.md

update rlc codegen version in quickstart

---

sdk/digitaltwins/digital-twins-core/package.json
sdk/digitaltwins/digital-twins-core/recordings/browsers/digitaltwins_models__create_read_list_delete_operations/recording_create_models_empty.json
sdk/digitaltwins/digital-twins-core/recordings/node/digitaltwins_models__create_read_list_delete_operations/recording_create_models_empty.js
sdk/digitaltwins/digital-twins-core/test-resources.json
sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts

NA
There is a test issue within the pipeline, specifically the empty model test.
This PR resolves the test issue in the pipeline by changing the assert statement.

Fixing test issue with core-http dependency

---

sdk/test-utils/recorder/README.md

Follow-up from a debugging session with @jasonsandlin.
Showing what to do first and then explaining why.

[Recorder] package.json scripts update in Readme

---

common/config/rush/pnpm-lock.yaml
sdk/analysisservices/arm-analysisservices/CHANGELOG.md
sdk/analysisservices/arm-analysisservices/LICENSE
sdk/analysisservices/arm-analysisservices/README.md
sdk/analysisservices/arm-analysisservices/_meta.json
sdk/analysisservices/arm-analysisservices/api-extractor.json
sdk/analysisservices/arm-analysisservices/package.json
sdk/analysisservices/arm-analysisservices/recordings/node/my_test/recording_sample_test.js
sdk/analysisservices/arm-analysisservices/recordings/node/my_test/recording_sample_test.json
sdk/analysisservices/arm-analysisservices/review/arm-analysisservices.api.md
sdk/analysisservices/arm-analysisservices/rollup.config.js
sdk/analysisservices/arm-analysisservices/sample.env
sdk/analysisservices/arm-analysisservices/src/azureAnalysisServices.ts
sdk/analysisservices/arm-analysisservices/src/models/index.ts
sdk/analysisservices/arm-analysisservices/src/operations/servers.ts
sdk/analysisservices/arm-analysisservices/test/sampleTest.ts
sdk/analysisservices/arm-analysisservices/tsconfig.json
sdk/analysisservices/ci.mgmt.yml

https://github.com/Azure/azure-sdk-for-js/issues/22203

refresh analysissercices package

---

documentation/test-quickstart.md

Resolve Broken Link Issues

---

documentation/RLC-quickstart.md

Update the credential configurations in RLC get started doc

Update reamde credential parts

---

common/config/rush/pnpm-lock.yaml
sdk/storageimportexport/arm-storageimportexport/CHANGELOG.md
sdk/storageimportexport/arm-storageimportexport/README.md
sdk/storageimportexport/arm-storageimportexport/_meta.json
sdk/storageimportexport/arm-storageimportexport/package.json
sdk/storageimportexport/arm-storageimportexport/recordings/node/my_test/recording_sample_test.js
sdk/storageimportexport/arm-storageimportexport/recordings/node/my_test/recording_sample_test.json
sdk/storageimportexport/arm-storageimportexport/review/arm-storageimportexport.api.md
sdk/storageimportexport/arm-storageimportexport/src/models/index.ts
sdk/storageimportexport/arm-storageimportexport/src/storageImportExport.ts
sdk/storageimportexport/arm-storageimportexport/test/sampleTest.ts

https://github.com/Azure/azure-sdk-for-js/issues/22197

refresh storageimportexport package

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-admin/swagger/README.md

(this time from an actual branch)
I am releasing a patch for keyvault-admin this cycle to fix a small bug related to authentication (#22109). This PR adds a CHANGELOG entry and bumps the version accordingly.

[KeyVault] Changelog for keyvault-admin release

---

sdk/keyvault/keyvault-admin/CHANGELOG.md

Forgot to run the Prepare-Release script with the new changelog... this should sort things out properly.

[KeyVault] Prepare-release changes for keyvault-admin

---

common/config/rush/pnpm-lock.yaml
sdk/avs/arm-avs/CHANGELOG.md
sdk/avs/arm-avs/README.md
sdk/avs/arm-avs/_meta.json
sdk/avs/arm-avs/api-extractor.json
sdk/avs/arm-avs/package.json
sdk/avs/arm-avs/recordings/node/my_test/recording_sample_test.js
sdk/avs/arm-avs/recordings/node/my_test/recording_sample_test.json
sdk/avs/arm-avs/review/arm-avs.api.md
sdk/avs/arm-avs/rollup.config.js
sdk/avs/arm-avs/sample.env
sdk/avs/arm-avs/src/azureVMwareSolutionAPI.ts
sdk/avs/arm-avs/src/models/index.ts
sdk/avs/arm-avs/src/operations/addons.ts
sdk/avs/arm-avs/src/operations/authorizations.ts
sdk/avs/arm-avs/src/operations/cloudLinks.ts
sdk/avs/arm-avs/src/operations/clusters.ts
sdk/avs/arm-avs/src/operations/datastores.ts
sdk/avs/arm-avs/src/operations/globalReachConnections.ts
sdk/avs/arm-avs/src/operations/placementPolicies.ts
sdk/avs/arm-avs/src/operations/privateClouds.ts
sdk/avs/arm-avs/src/operations/scriptExecutions.ts
sdk/avs/arm-avs/src/operations/virtualMachines.ts
sdk/avs/arm-avs/src/operations/workloadNetworks.ts
sdk/avs/arm-avs/test/sampleTest.ts
sdk/avs/arm-avs/tsconfig.json
sdk/avs/ci.mgmt.yml

https://github.com/Azure/azure-sdk-for-js/issues/22197

refresh avs package

---

.github/CODEOWNERS

Updating the contacts for Cosmos, by request.

[CODEOWNERS] Update Cosmos Service Owners

---

sdk/monitor/monitor-opentelemetry-exporter/samples-dev/httpSample.ts
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/javascript/httpSample.js
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/typescript/src/httpSample.ts
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/typescript/src/metricsSample.ts

Related to https://github.com/Azure/azure-sdk-for-js/pull/22456

[Azure Monitor Exporter] Build samples to reflect latest changes in dev

---

sdk/search/search-documents/package.json
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/src/searchIndexingBufferedSender.ts
sdk/search/search-documents/src/tracing.ts

https://github.com/Azure/azure-sdk-for-js/issues/21247
Currently, the `@azure/search-documents` package depends on the `1.0.0-preview.13` version of the `@azure/core-tracing` package. The `@azure/core-tracing` has already GA'ed 3 months back and we would like to upgrade this dependency to the latest version.
The design is actually simple and straight forward. It is upgrading the dependency version. The only notable issue is there are breaking changes that I have addressed in this PR.
No. This is just upgrading the dependency version and the existing test cases are sufficient to ensure that there are no regressions.
N/A

[@azure/search-documents] Update Dependency of `@azure/core-tracing` package

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

Releasing a preview of these packages with the Core v2 migration.

[KeyVault] Prepare July preview releases of `keyvault-keys`, `keyvault-certificates` and `keyvault-secrets`

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/samples/v12/javascript/package.json
sdk/storage/storage-queue/samples/v12/typescript/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

azure/storage-blob
azure/storage-file-datalake
azure/storage-file-share
azure/storage-queue

Prepare for STG83 release.

---

eng/pipelines/templates/steps/test.yml
sdk/test-utils/recorder/src/recorder.ts

Got tripped up with 2 failing tests in the recorder. This PR is resolving those.
Resolves #22494

[Recorder] Update `SetRecordingOptions` redirect value, unpin proxy version

---

eng/pipelines/aggregate-reports.yml
eng/pipelines/templates/jobs/perf.yml

- Needed to fix pipeline "js - aggregate-reports"

[Perf] Add ref to azure-sdk-tools repo

---

sdk/networkfunction/arm-networkfunction/CHANGELOG.md

https://github.com/Azure/azure-sdk-for-js/pull/22564

modify date in networkfunction

---

sdk/confidentialledger/confidential-ledger-rest/review/confidential-ledger.api.md
sdk/confidentialledger/confidential-ledger-rest/sample.env
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/clientDefinitions.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/confidentialLedger.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/isUnexpected.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/outputModels.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/paginateHelper.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/parameters.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/responses.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/historicalRangeQuery.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/postTransaction.spec.ts

[Confidential Ledger] Regeneration after Arch Board Review

---

sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_custom/recording_entity_recognition.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_custom/recording_entity_recognition.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalysisclient_analyzebatch_actions_custom/recording_entity_recognition.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalysisclient_analyzebatch_actions_custom/recording_entity_recognition.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/textanalytics/ai-text-analytics/test/public/expectations.ts

Fix failing tests in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1710171&view=logs&j=b800360f-d572-5e16-3e20-e4f204d3fbd3&t=3b97752f-f53c-5e36-3379-45368efa0b3c
EDIT: succeeded run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1711617&view=results
Fixes https://github.com/Azure/azure-sdk-for-js/issues/22543#event-6974761194

[Text Analytics] Update test expectations

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

- ESLint plugin
Upgraded to ~1.0.0

[engsys] Update @types/estree to ~1.0.0

---

sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md
sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/confidentialledger/confidential-ledger-rest/review/confidential-ledger.api.md
sdk/confidentialledger/confidential-ledger-rest/src/confidentialLedger.ts
sdk/confidentialledger/confidential-ledger-rest/src/generated/src/confidentialLedger.ts
sdk/confidentialledger/confidential-ledger-rest/swagger/README.md

[Confidential Ledger] package version update

---

sdk/monitor/monitor-ingestion/CHANGELOG.md

[Monitor Ingestion] update changelog for b1 release

---

sdk/core/core-xml/CHANGELOG.md
sdk/core/core-xml/package.json

- [core-xml]
Updates the latest version to 1.3.0 after the CDATA changes.
N/A

[core] Update @azure/core-xml version

---

sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-identity/package.json

Azure Communication Services support Teams identities GA release - 1.1.0

Azure Communication Services support Teams identities GA release

---

.github/CODEOWNERS

None
None
Fixed CODEOWNERS for attestation.
N/A
N/A
N/A
N/A

Fixed JS codeowners for Attestation SDK

---

sdk/core/core-client/src/serializer.ts
sdk/core/core-client/test/serializer.spec.ts
sdk/core/core-client/test/testMappers1.ts

@azure/core-client 
https://github.com/Azure/autorest.typescript/issues/1395
After the code generator side fix, we will need to fix the find discriminator serializer mapper in the core-client side

Find the right discriminator index

---

sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts

[KeyVault] Add disclaimers regarding CBC and CBCPAD operations

---

sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-identity/package.json
sdk/communication/communication-identity/src/constants.ts
sdk/communication/communication-identity/src/generated/src/identityRestClientContext.ts
sdk/communication/communication-identity/swagger/README.md

Post-release changes to increment the version

Increment package version after @azure/communication-identity release

---

sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/samples-dev/extractiveSummarization.ts
sdk/cognitivelanguage/ai-language-text/samples-dev/healthcare.ts
sdk/cognitivelanguage/ai-language-text/samples/v1-beta/javascript/extractiveSummarization.js
sdk/cognitivelanguage/ai-language-text/samples/v1-beta/javascript/healthcare.js
sdk/cognitivelanguage/ai-language-text/samples/v1-beta/typescript/package.json
sdk/cognitivelanguage/ai-language-text/samples/v1-beta/typescript/src/extractiveSummarization.ts
sdk/cognitivelanguage/ai-language-text/samples/v1-beta/typescript/src/healthcare.ts
sdk/cognitivelanguage/ai-language-text/src/generated/generatedClient.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/mappers.ts
sdk/cognitivelanguage/ai-language-text/src/lro.ts
sdk/cognitivelanguage/ai-language-text/src/models.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

- renames `operationId` to `id`
- renames `lastModifiedOn` to `modifiedOn`
- fix docstrings

[Language Text] Apply minor updates

---

swagger_to_sdk_config.json

only show error log in sdk automation pipeline

---

.github/CODEOWNERS

Remove owners that no longer are part of the Azure organization.

Address CODEOWNERS errors

---

sdk/monitor/monitor-query/README.md

Related to https://github.com/Azure/azure-sdk-for-net/pull/29883

Add TokenCredential implementation as a prereq

---

sdk/core/core-client/CHANGELOG.md

@azure/core-client
release 1.6.1 of @azure/core-client

add-changelog-for-core-client-1.6.1-release

---

.scripts/automation_init.sh

latest rush cannot be installed

use fixed rush version

---

sdk/communication/communication-common/CHANGELOG.md

Prepare @azure/communication-common 2.1.0 release

---

sdk/communication/communication-common/README.md

Updated broken link

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] prepare for 2022 Aug release

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/samples/AzureCacheForRedis/ioredis.md
sdk/identity/identity/samples/AzureCacheForRedis/node-redis.md
sdk/identity/identity/src/constants.ts

https://github.com/Azure/azure-sdk-for-js/issues/21059
https://github.com/Azure/azure-sdk-for-js/issues/21058

Feature beta 3 branch - Redis samples

---

sdk/notificationhubs/notification-hubs/package.json

- Core paging latest not released.

[notification hubs] updating core dependencies

---

sdk/cognitivelanguage/ai-language-text/README.md

by using samples-dev folder for now.

[language-text] fix broken link to unpublished samples folder

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md

[Language Text] Prepare release

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-text/samples-dev/customMultiLabelClassification.ts
sdk/cognitivelanguage/ai-language-text/samples-dev/customSingleLabelClassification.ts

- Fix samples to use the correct env vars
- Delay release to Thursday

[Language Text] Delay release

---

sdk/communication/communication-rooms/CHANGELOG.md
sdk/communication/communication-rooms/src/generated/src/roomsApiClient.ts
sdk/communication/communication-rooms/src/generated/src/roomsApiClientContext.ts
sdk/communication/communication-rooms/swagger/README.md

Communication-Rooms
Wrong version for lib in swagger
No, no code change

Update version number in swagger

---

sdk/communication/communication-short-codes/CHANGELOG.md

--
**NOTE: This is a private SDK intended for internal use only. This SDK will not be officially supported**
This prepares the short codes SDK for the beta 4 release.
--
--
--

Prepare release of the Short Codes SDK for beta 4

---

sdk/communication/communication-alpha-ids/package.json
sdk/communication/communication-chat/package.json
sdk/communication/communication-identity/package.json
sdk/communication/communication-short-codes/package.json

- communication-short-codes
- communication-identity
- communication-chat
- communication-alpha-ids

Bump the version of communication-common to 2.1.0

---

sdk/monitor/monitor-ingestion/package.json
sdk/monitor/monitor-ingestion/test/public/logsIngestionClient.spec.ts
sdk/monitor/test-resources.json

- `@azure/monitor-ingestion`
Creating test resources for the live tests. Using this template, live tests run fine on my machine, but might need to tweak environment variable names slightly to run on CI.
Fixes #22941

[Monitor Ingestion] Test resources for live tests

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md

Update released date in change log for STG84 public preview release

Prepare STG84 release.

---

sdk/identity/identity/CHANGELOG.md

[Identity] update changelog for identity v3 beta-1 release

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/src/auth/hmacSha256.browser.ts
sdk/notificationhubs/notification-hubs/src/utils/constants.ts

- #22999 
Fixes the `signKey` method by encoding the output using `encodeURIComponent`
N/A

[notification hubs] Update browser signkey method

---

sdk/apimanagement/api-management-custom-widgets-scaffolder/CHANGELOG.md
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/_shared/src/styles/app.scss
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/react/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/react/src/app/index.tsx
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/react/vite.config.ts.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/typescript/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/typescript/src/index.html.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/typescript/tsconfig.json
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/vue/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/vue/src/components/app/index.vue
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/_shared/src/styles/app.scss
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/react/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/react/src/app/index.tsx
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/react/vite.config.ts.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/typescript/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/typescript/src/index.html.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/typescript/tsconfig.json
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/vue/package.json.mustache
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/vue/src/components/app/index.vue

@azure/api-management-custom-widgets-scaffolder
n/a
Updates & synchronizes dependencies used in various templates.
Improves formatting in the templates.
Removes unnecessary duplicated path from fetch requests in templates.
n/a
No, there were no changes to the API, only minor improvements to existing templates.
n/a

Apim/custom widgets scaffolder beta2 - templates updated

---

sdk/apimanagement/api-management-custom-widgets-scaffolder/CHANGELOG.md
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/execute.js
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/bin/execute-configs.ts

@azure/api-management-custom-widgets-scaffolder
n/a
Update the CLI of the scaffolder package to make it more intuitive
n/a
No, there were no changes to the API, only minor improvements to existing templates.
n/a

Apim/custom widgets packages beta2 CLI improvement

---

sdk/containerregistry/container-registry/README.md
sdk/containerregistry/container-registry/TROUBLESHOOTING.md

- Resolves #22876
Adds troubleshooting guide for ACR

[ACR] Troubleshooting guide

---

sdk/netapp/arm-netapp/samples-dev/netAppResourceCheckNameAvailabilitySample.ts
sdk/netapp/arm-netapp/samples-dev/netAppResourceCheckQuotaAvailabilitySample.ts
sdk/netapp/arm-netapp/samples/v16/javascript/netAppResourceCheckNameAvailabilitySample.js
sdk/netapp/arm-netapp/samples/v16/javascript/netAppResourceCheckQuotaAvailabilitySample.js
sdk/netapp/arm-netapp/samples/v16/typescript/package.json
sdk/netapp/arm-netapp/samples/v16/typescript/src/netAppResourceCheckNameAvailabilitySample.ts
sdk/netapp/arm-netapp/samples/v16/typescript/src/netAppResourceCheckQuotaAvailabilitySample.ts

https://github.com/Azure/azure-sdk-for-js/issues/23042

fix bugs in netapp by putting the parameters in the right position

---

sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/samples-dev/logsQuery.ts
sdk/monitor/monitor-query/samples-dev/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/samples/v1/javascript/logsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryBatch.js
sdk/monitor/monitor-query/samples/v1/javascript/logsQueryMultipleWorkspaces.js
sdk/monitor/monitor-query/samples/v1/javascript/metricsQuery.js
sdk/monitor/monitor-query/samples/v1/typescript/package.json
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQuery.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryBatch.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryMultipleWorkspaces.ts
sdk/monitor/monitor-query/samples/v1/typescript/src/metricsQuery.ts

Updating to make consistent with the other languages and in response to customer feedback.

[monitor-query] Update samples to use 10-minute server timeout

---

sdk/search/perf-tests/search-documents/package.json
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/README.md
sdk/search/search-documents/package.json
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchAudience.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/src/serialization.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/src/synonymMapHelper.browser.ts
sdk/search/search-documents/src/synonymMapHelper.ts
sdk/search/search-documents/test/internal/browser/synonymMap.browser.spec.ts
sdk/search/search-documents/test/internal/node/synonymMap.node.spec.ts
sdk/search/search-documents/test/internal/serialization.spec.ts
sdk/search/search-documents/test/internal/synonymMap.txt

N/A
We have released the `@azure/search-documents` SDK V 11.2.1 on August 2021. Now, the request has come to release 11.3.0. But, only 3 features must be included for this release:
1. TokenCredential AAD Support
2. National Cloud Support
3. Any Bug Fixes that went in after August 2021 
So, I have branched off from the 11.2.1 code base and added the appropriate changes. This does not include any regenration or swagger changes.
Wherever appropriate, I have modified the test cases to include changes. 
None
- [X ] Added impacted package name to the issue description
@xirzec @ShivangiReja Please review and approve the PR.

[@azure/search-documents] Code Changes for Search Release 11.3.0

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples-dev/buildModel.ts
sdk/formrecognizer/ai-form-recognizer/samples-dev/composeModel.ts
sdk/formrecognizer/ai-form-recognizer/src/documentModelAdministrationClient.ts
sdk/formrecognizer/ai-form-recognizer/src/options/BuildModelOptions.ts
sdk/formrecognizer/ai-form-recognizer/src/options/DeleteModelOptions.ts
sdk/formrecognizer/ai-form-recognizer/src/options/index.ts
sdk/formrecognizer/ai-form-recognizer/test/private/tracing.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/public/node/analysis.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/public/training.spec.ts

Updates mainly to the names in the Admin client, `..Model..` -> `..DocumentModel..`

[Form Recognizer] Consistency changes 

---

sdk/search/search-documents/CHANGELOG.md

None
None. It is just updating a date in changelog.
None. It is just updating a date in changelog.
None. It is just updating a date in changelog.
NA

[@azure/search-documents] Update Date in Changelog

---

common/config/rush/pnpm-lock.yaml
sdk/attestation/attestation/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/core/core-client/package.json
sdk/core/core-http-compat/package.json
sdk/core/core-http/package.json
sdk/core/core-paging/package.json
sdk/core/core-rest-pipeline/package.json
sdk/core/core-util/package.json
sdk/core/core-xml/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
sdk/monitor/monitor-ingestion/package.json
sdk/monitor/monitor-query/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-internal-avro/package.json
sdk/storage/storage-queue/package.json
sdk/tables/data-tables/package.json
sdk/template/template/package.json

This fixes an error in automated `rush update --full` build.
***NO_CI***

[engsys] upgrade `downlevel-dts` version to ^0.10.0

---

.github/CODEOWNERS

[Personalizer] Update CODEOWNERS

---

sdk/confidentialledger/confidential-ledger-rest/README.md

Issue: https://github.com/Azure/azure-sdk-for-js/issues/23041

[Confidential Ledger] Update post ledger entry example

---

sdk/network/arm-network/recordings/node/my_test/recording_ipgroups_begindeleteandwait_test.json
sdk/network/arm-network/recordings/node/my_test/recording_ipgroups_create_test.json
sdk/network/arm-network/recordings/node/my_test/recording_ipgroups_get_test.json
sdk/network/arm-network/recordings/node/my_test/recording_ipgroups_list_test.json
sdk/network/arm-network/recordings/node/my_test/recording_subnets_begindeleteandwait_test.json
sdk/network/arm-network/recordings/node/my_test/recording_subnets_create_test.json
sdk/network/arm-network/recordings/node/my_test/recording_subnets_get_test.json
sdk/network/arm-network/recordings/node/my_test/recording_subnets_list_test.json
sdk/network/arm-network/recordings/node/my_test/recording_virtualnetworks_begindeleteandwait_test.json
sdk/network/arm-network/recordings/node/my_test/recording_virtualnetworks_create_test.json
sdk/network/arm-network/recordings/node/my_test/recording_virtualnetworks_get_test.json
sdk/network/arm-network/recordings/node/my_test/recording_virtualnetworks_list_test.json
sdk/network/arm-network/recordings/node/my_test/recording_virtualnetworks_updatetags_test.json

To fix full rush update error due to new behavior in @azure/core-lro.

[arm-network] Re-record tests

---

.github/fabricbot.json

The focus of these changes is to update the contacts for Personalizer, based on CODEOWNERS changes made in #23136

[Bot Rules] Update Personalizer contacts

---

sdk/cognitivelanguage/ai-language-conversations/CHANGELOG.md

This PR prepares for the release of @azure/ai-language-conversations 1.0.0-beta.1
* Sets the release date in the CHANGELOG.

[ai-language-conversations] Prepare to release 1.0.0-beta.1

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/src/utils/constants.ts

[Manual] Post release automated changes for azure-notification-hubs

Post release automated changes for notificationhubs releases

---

.github/CODEOWNERS

Updated EngSys owner from @praveenkuttappan to @ckairen

Update EngSys owner

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/request/request.ts

Update package json azure identity

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Was missing an entry for shipping the recent fix in #22986

[cosmos] update changelog for release

---

.vscode/cspell.json
sdk/personalizer/ai-personalizer-rest/package.json
sdk/personalizer/ai-personalizer-rest/tests.yml
sdk/personalizer/ci.yml

Fixing the builds to release the personalizer package

[Personalizer] Release prep

---

sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-datalake/package.json
sdk/storage/perf-tests/storage-file-share/package.json

- Fixes #23123
storage-blob: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1836980&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=948263dc-2a7b-5031-89c1-ea1ca73fbaf3&l=43
storage-file-datalake: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1836981&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=948263dc-2a7b-5031-89c1-ea1ca73fbaf3&l=43
storage-file-share: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1836982&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=948263dc-2a7b-5031-89c1-ea1ca73fbaf3&l=43

[Perf] Update storage perf dependency versions

---

common/config/rush/pnpm-lock.yaml
sdk/test-utils/test-utils/package.json
sdk/test-utils/test-utils/src/chaiAzure.ts

[engsys][test-utils] update `typescript` dependency to `~4.8.0`

---

sdk/web-pubsub/web-pubsub/review/web-pubsub.api.md
sdk/web-pubsub/web-pubsub/src/hubClient.ts
sdk/web-pubsub/web-pubsub/src/index.ts

@azure/web-pubsub
Customer could have the ability to print out headers/queries they'd like

Allow customer to specify logging details

---

sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/README.md
sdk/keyvault/arm-keyvault-profile-2020-09-01-hybrid/README.md
sdk/keyvault/arm-keyvault/README.md
sdk/keyvault/arm-keyvault/samples/v2-beta/javascript/README.md
sdk/keyvault/arm-keyvault/samples/v2-beta/typescript/README.md
sdk/keyvault/keyvault-admin/README.md
sdk/keyvault/keyvault-admin/samples/v4/javascript/README.md
sdk/keyvault/keyvault-admin/samples/v4/typescript/README.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/samples/v4/javascript/README.md
sdk/keyvault/keyvault-certificates/samples/v4/typescript/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/samples/v4/javascript/README.md
sdk/keyvault/keyvault-keys/samples/v4/typescript/README.md
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/samples/v4/javascript/README.md
sdk/keyvault/keyvault-secrets/samples/v4/typescript/README.md

Partial application of f280f87

[keyvault] Challenge verification - Fix broken links for release pipeline

---

sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/balancedStrategy.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/greedyStrategy.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/loadBalancingStrategy.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/unbalancedStrategy.ts
sdk/eventhub/event-hubs/test/internal/loadBalancingStrategy.spec.ts

I am planning to write some spec tests for load-balancing so I am refactoring its logic here into a function that doesn't send requests and can be easily used in mocked tests.

[Event Hubs] Refactor load-balancing

---

sdk/monitor/monitor-ingestion/CHANGELOG.md
sdk/monitor/monitor-ingestion/review/monitor-ingestion.api.md
sdk/monitor/monitor-ingestion/samples-dev/logsIngestionClient.ts
sdk/monitor/monitor-ingestion/samples-dev/uploadCustomLogs.ts
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/logsIngestionClient.js
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/uploadCustomLogs.js
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/package.json
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/src/logsIngestionClient.ts
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/src/uploadCustomLogs.ts
sdk/monitor/monitor-ingestion/src/logsIngestionClient.ts
sdk/monitor/monitor-ingestion/src/models.ts
sdk/monitor/monitor-ingestion/test/public/logsIngestionClient.spec.ts

- `@azure/monitor-ingestion`
- Renames types for cross-language consistency as raised in consistency review meeting and #23153.
- Addresses architect feedback, making the name of this property consistent with the [`cause` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) on `Error`.

[monitor-ingestion] Renames from consistency review + architecture feedback

---

sdk/synapse/synapse-access-control-rest/package.json
sdk/synapse/synapse-access-control-rest/review/synapse-access-control.api.md
sdk/synapse/synapse-access-control-rest/samples-dev/createRoleAssignment.ts
sdk/synapse/synapse-access-control-rest/samples-dev/listRoleAssignments.ts
sdk/synapse/synapse-access-control-rest/samples/v1-beta/javascript/createRoleAssignment.js
sdk/synapse/synapse-access-control-rest/samples/v1-beta/javascript/listRoleAssignments.js
sdk/synapse/synapse-access-control-rest/samples/v1-beta/typescript/package.json
sdk/synapse/synapse-access-control-rest/samples/v1-beta/typescript/src/createRoleAssignment.ts
sdk/synapse/synapse-access-control-rest/samples/v1-beta/typescript/src/listRoleAssignments.ts
sdk/synapse/synapse-access-control-rest/src/accessControlRestClient.ts
sdk/synapse/synapse-access-control-rest/src/clientDefinitions.ts
sdk/synapse/synapse-access-control-rest/src/index.ts
sdk/synapse/synapse-access-control-rest/src/isUnexpected.ts
sdk/synapse/synapse-access-control-rest/src/models.ts
sdk/synapse/synapse-access-control-rest/src/outputModels.ts
sdk/synapse/synapse-access-control-rest/src/paginateHelper.ts
sdk/synapse/synapse-access-control-rest/src/parameters.ts
sdk/synapse/synapse-access-control-rest/src/responses.ts
sdk/synapse/synapse-access-control-rest/swagger/README.md
sdk/synapse/synapse-access-control-rest/test/public/test.spec.ts

@azure-rest/synapse-access-control
refresh @azure-rest/synapse-access-control with latest code generator and swagger as of service team's requirement

release-for-synapse-access-control-rlc

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/TROUBLESHOOTING.md

based on the .NET version https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md.

[doc][ServiceBus] add troubleshooting guide

---

sdk/maps/maps-common/CHANGELOG.md
sdk/maps/maps-search/CHANGELOG.md

- `@azure/maps-search`
- `@azure/maps-common`
- As title, update the release date to `1.0.0-beta.1` and re-structure the CHANGELOG format.
- NA
- NA
- NA

[Maps] Update the CHANGELOG for October Release

---

sdk/servicebus/service-bus/samples-dev/browseMessages.ts
sdk/servicebus/service-bus/samples-dev/exceedMaxDeliveryCount.ts
sdk/servicebus/service-bus/samples-dev/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples-dev/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/v7/javascript/receiveMessagesLoop.js

Change made is with regard to update the comment to which Javascript file to be ran under the `javascript` parent folder.

Update comment to refer to the right JS file

---

sdk/core/core-util/CHANGELOG.md

[core-util] Prepare for Oct. 2022 release

---

common/config/rush/pnpm-lock.yaml
sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json
sdk/apimanagement/api-management-custom-widgets-tools/package.json

- `@azure/api-management-custom-widgets-scaffolder`
- `@azure/api-management-custom-widgets-tools`
- Fixes #22560

[engsys] Upgrade @types/mustache to ^4.2.1

---

sdk/servicebus/service-bus/CHANGELOG.md

- update release date
- add changelog entry

[ServiceBus] Prepare for Oct. 2022 release

---

sdk/cognitivelanguage/ai-language-text/README.md

need to declare results iterator in sample

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_all_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_invalid_language_hint.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_some_documents_with_errors_and_multiple_actions.json
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

The service error messages improved so this PR updates the test expectations to match them.

[Language Text] Update expectations

---

sdk/test-utils/recorder/MIGRATION.md

Follows up from my feedback on #23426 which didn't make it in on time. Adding a couple more advantages to migration.

[recorder] More migration advantages

---

sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md

Regenerate with the most recent version of the swagger that recently graduated from the dev folder.

[Language Text] Regenerate with main swagger

---

sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-identity/README.md

Custom token expiration feature GA release of the @azure/communication-identity SDK - 1.2.0
Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-js/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

[JS] Custom token expiration feature GA release updates

---

sdk/monitor/monitor-ingestion/README.md

[monitor-ingestion] Add "Retrieve logs" section to README

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json

Update the Signaling Package to Use the Latest PNH Template

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/constants.ts

[Identity] release identity 3.1.0-beta.1

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/metric.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts

[Azure Monitor Exporter] Suppress tracing while exporting metrics

---

sdk/monitor/monitor-ingestion/CHANGELOG.md

[Ingestion] release ingestion

---

sdk/core/core-amqp/package.json
sdk/core/core-amqp/src/util/runtimeInfo.native.ts
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/runtimeInfo.native.ts

- for entry point
- for runtime info

[core-amqp,service-bus] add react-native mappings

---

sdk/eventhub/event-hubs/samples-dev/iothubConnectionString.ts
sdk/eventhub/event-hubs/samples/v5/javascript/iothubConnectionString.js
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionString.ts

To align with the [.NET sample](https://github.com/Azure/azure-sdk-for-net/blob/main/samples/iothub-connect-to-eventhubs/IotHubConnection.cs#L97). We shouldn't assume that the event hub name is the same as the IoT hub name.

[Event Hubs] Update iothub sample

---

sdk/videoanalyzer/video-analyzer-edge/package.json

- [videoanalyzer]
- #21199
Migrating the package.json file core-tracing to 1.0 GA

[videoanalyzer] migrate to core tracing 1.0

---

sdk/communication/communication-job-router/package.json
sdk/communication/communication-job-router/src/generated/src/jobRouterApiClient.ts
sdk/communication/communication-job-router/src/generated/src/operations/jobRouter.ts
sdk/communication/communication-job-router/src/generated/src/operations/jobRouterAdministration.ts
sdk/communication/communication-job-router/src/generated/src/tracing.ts
sdk/communication/communication-job-router/swagger/README.md

- `@azure/communication-job-router`
- #21199
Upgrades the core-tracing to 1.0 GA, updating the swagger README and package.json.

[communication job router] Upgrade to core-tracing GA 1.0

---

sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/23535
Run will succeed [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1927855&view=results)

[Text Analytics] Skip failing test

---

.scripts/automation_generate.sh

Update code gen version

---

sdk/cognitivelanguage/ai-language-text/README.md
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_accepts_string_and_language.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_accepts_string_with_no_language.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_throws_on_empty_list.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_invalid_classification_type.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_invalid_number_of_categories.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_unsupported_language.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_accepts_string_and_language.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_accepts_string_with_no_language.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_throws_on_empty_list.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_invalid_classification_type.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_invalid_number_of_categories.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_unsupported_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_accepts_string_and_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_accepts_string_with_no_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_client_throws_on_empty_list.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_invalid_classification_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_invalid_number_of_categories.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_multi/recording_service_errors_on_unsupported_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_accepts_string_and_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_accepts_string_with_no_language.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_client_throws_on_empty_list.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_invalid_classification_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_invalid_number_of_categories.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_dynamic_classification_single/recording_service_errors_on_unsupported_language.json
sdk/cognitivelanguage/ai-language-text/test/public/analyze.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

[language-text] Add dynamic classification tests

---

sdk/monitor/monitor-opentelemetry-exporter/README.md
sdk/monitor/monitor-opentelemetry-exporter/review/monitor-opentelemetry-exporter.api.md
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/typescript/src/basicTracerNode.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/src/index.ts
sdk/monitor/monitor-opentelemetry-exporter/src/sampling.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/sampling.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts

Adding AI Sampler
Fixed issue with Span Event not adding correct parent ID when root span
Dependency exceptions will be send as Message telemetry

[Azure Monitor Exporter] Adding ApplicationInsightsSampler

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md

[Azure Monitor Exporter] Update changelog for 1.0.0-beta.9 release

---

sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/package.json

[core-rest-client] update unreleased version to 1.0.1

---

.github/CODEOWNERS

Communication-Identity, Communication-Common
[User Story 2989869](https://skype.visualstudio.com/SPOOL/_workitems/edit/2989869): [SDK][Common][Java] - Fix the pipeline
Updating CODEOWNERS for communication identity and common.
No, the change is only in CODEOWNERS file.

Updating CODEOWNERS for communication identity and common

---

sdk/maps/maps-common/CHANGELOG.md
sdk/maps/maps-route-rest/CHANGELOG.md
sdk/maps/maps-route-rest/README.md
sdk/maps/maps-search/CHANGELOG.md

- @azure/maps-common
- @azure/maps-search 

[Maps] Update CHANGELOG for Nov Release

---

sdk/core/core-paging/CHANGELOG.md

core-paging
Update changelog for release

[core-paging] Update changelog for release

---

sdk/cognitivelanguage/ai-language-text/src/transforms.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

@azure/ai-language-text
client-only mitigation to https://github.com/Azure/azure-sdk-for-js/issues/23618
Unexpected property name in the operation result.
N/A
Already have test cases.
N/A

[Language Text] Include mitigation for output rename for Dynamic Classification

---

.scripts/automation_generate.sh
.scripts/automation_init.sh

cadl dpg support in sdk automation pipeline

---

.github/CODEOWNERS

N/A
N/A
Add NickKouds to CODEOWNERS for Batch
N/A
N/A
N/A
N/A

Update CODEOWNERS for Batch

---

sdk/core/core-http/src/serializer.ts
sdk/core/core-http/test/serializationTests.ts

[core-http] should use options.xmlCharKey if specified

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md

Updating Changelog to reflect current release date

[notification hubs] Prepare Beta 7 Release

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
sdk/cognitivelanguage/ai-language-text/test/public/analyze.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

ai-language-text
#23521
Add test for auto language detection and script detection

[language text] add script and auto language detection tests

---

sdk/test-utils/ci.yml

Just so I can avoid manually triggering this on every eng/common update.

Run Test-Utils on proxy update

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] prepare for 2022 November release

---

sdk/identity/identity/CHANGELOG.md

[identity] update changelog for 3.1.0 GA release

---

.vscode/cspell.json
sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/eventGridClient.ts
sdk/eventgrid/eventgrid/src/generated/generatedClient.ts
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/predicates.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

The only updates for our November release are adding type interfaces for two new healthcare API events which the service now sends.

[EventGrid] Update Healthcare Events, Prepare for Nov Release

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/util/constants.ts
sdk/storage/storage-blob/package.json

For the runtime behavior change in deserializing parsed project from XML.
`@azure/core-http`

[core-http] bump major version to v3

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
sdk/keyvault/test-resources.json

[keyvault] Prepare beta release for keyvault-admin and keyvault-keys

---

sdk/identity/identity/test/manual/interactive-browser-credential/index.html
sdk/identity/identity/test/manual/interactive-browser-credential/package.json
sdk/identity/identity/test/manual/interactive-browser-credential/webpack.config.js

Example app demoing InteractiveBrowserCredential with service-bus
No logged issues
Fixes the non-functional app demoing InteractiveBrowserCredential with service-bus

[Identity] Fix identity InteractiveBrowserCredential app with webpack example (for browser)

---

eng/pipelines/docindex.yml

Added the condition check for main branch update.
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1990535&view=results

Add condition check on main branch updates

---

sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/mappers.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md

[Language Text] Regenerate with the most recent swagger version

---

sdk/cosmosdb/cosmos/README.md

CosmosDB README.md example code - item creation is an async operation

---

sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

See corresponding bug report for context: https://github.com/Azure/azure-sdk-for-js/issues/23900

[Language Text] Skip failing test

---

sdk/appconfiguration/app-configuration/samples-dev/featureFlag.ts

app-configuration
#14884
Update `featureFlag.ts` sample with `timewindow` filter

[app-config] Update feature flags sample with timewindow filter

---

sdk/monitor/monitor-query/README.md

[Monitor Query] Fix link

---

sdk/core/core-xml/CHANGELOG.md
sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json

- [core-xml]
- [notification-hubs]
Update core-xml and notification-hubs to latest date for release.

[core-xml] Update CHANGELOG for release

---

sdk/communication/communication-email/CHANGELOG.md
sdk/communication/communication-email/README.md
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_retrieves_the_email_status_with_the_returned_message_id.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_to_a_single_recipient.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_to_multiple_types_of_recipients.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_with_an_attachment.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_with_an_empty_to_field.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_retrieves_the_email_status_with_the_returned_message_id.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_to_a_single_recipient.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_to_multiple_types_of_recipients.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_with_an_empty_to_field.json
sdk/communication/communication-email/review/communication-email.api.md
sdk/communication/communication-email/src/emailClient.ts
sdk/communication/communication-email/src/generated/src/models/index.ts
sdk/communication/communication-email/src/generated/src/models/mappers.ts
sdk/communication/communication-email/swagger/README.md
sdk/communication/communication-email/test/public/emailClient.spec.ts

- I added AAD support for authenticating the email client
- I made the "to" property in the EmailMessage optional and regenerated the client

Adding AAD authetication and making the "to" property optional

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts

We should wait for the Promise to resolve
#23849

[core-rest-pipeline] await `prepareFormData()`

---

eng/ignore-links.txt
sdk/loadtestservice/arm-loadtesting/CHANGELOG.md
sdk/loadtestservice/arm-loadtesting/README.md
sdk/loadtestservice/arm-loadtesting/package.json
sdk/loadtestservice/arm-loadtesting/recordings/node/loadtesting_test/recording_loadtests_create_test.json
sdk/loadtestservice/arm-loadtesting/recordings/node/loadtesting_test/recording_loadtests_delete_test.json
sdk/loadtestservice/arm-loadtesting/recordings/node/loadtesting_test/recording_loadtests_get_test.json
sdk/loadtestservice/arm-loadtesting/recordings/node/loadtesting_test/recording_loadtests_list_test.json
sdk/loadtestservice/arm-loadtesting/src/loadTestClient.ts

https://github.com/Azure/sdk-release-request/issues/3262

update version of loadtesting

---

.github/CODEOWNERS

Update CODEOWNERS for communication-phone-numbers

---

common/scripts/install-run-rush.js
common/scripts/install-run.js
rush.json

Bumping the rush version to latest because of some stale indirect dependencies. As far as I can tell nothing has broken, but I'm not sure if there is particular validation that needs to be done here.

[engsys] update rush version to latest

---

sdk/monitor/perf-tests/monitor-ingestion/README.md
sdk/monitor/perf-tests/monitor-ingestion/test/uploadLogs.spec.ts

- `@azure/monitor-ingestion`
Added a few more options to the perf tests following up from discussion in the standup.

[monitor-ingestion] More perf test options

---

sdk/maps/maps-route-rest/README.md
sdk/maps/maps-search/README.md

- #24043 
- #24042 
- Fix issue code snippet in maps search/route README
Most of the changes follows @zzhxiaofeng suggestion excepts:
- Remove `LatLon` since the code snippets are written in JavaScript.
- For the redeclare block-scoped variables `routeDirectionsResult`, since we don't expect users to create a request with and without helper function at the same time, so I think it's okay to leave it like this.
- Rewrite the part of retreiving properties from `routeDirectionsResult`.

[Maps] Refine READMEs

---

sdk/servicebus/service-bus/test/stress/Dockerfile

Update stress Dockerfile

---

sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/src/appConfigCredential.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/featureFlag.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts
sdk/appconfiguration/app-configuration/src/logger.ts
sdk/appconfiguration/app-configuration/src/secretReference.ts

App Configuration
#15288
Import logger and log relevant messages

[App configuration] Import logger to app configuration

---

sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_get_secretreference.json
sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_update_secretreference.json
sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_list_and_update_multiple_secretreferences.json
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_get_secretreference.json
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_update_secretreference.json
sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_list_and_update_multiple_secretreferences.json
sdk/appconfiguration/app-configuration/test/public/secretReference.spec.ts
sdk/appconfiguration/app-configuration/test/public/tracing.spec.ts

app-configuration
#13298
All the resources created will be completely deleted.

[app-config] Cleanup resources after the test

---

sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

text-analytics
#23894
Unskip the test since the service fixes the pointer issue

[text analytics] Unskip test

---

common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-query/package.json

- [monitor query]
- #23953
Updates to the latest release for min values

[monitor-query] Update @azure/monitor-opentelemetry-exporter dependency

---

sdk/maps/maps-route-rest/package.json
sdk/maps/maps-route-rest/samples-dev/lro.ts
sdk/maps/maps-route-rest/samples/v1-beta/javascript/README.md
sdk/maps/maps-route-rest/samples/v1-beta/javascript/lro.js
sdk/maps/maps-route-rest/samples/v1-beta/typescript/README.md
sdk/maps/maps-route-rest/samples/v1-beta/typescript/src/lro.ts

- Disable MS Docs for README under samples to align with other packages
- Adjust the LRO samples to align with other packages

[Maps]: Update samples in `@azure-rest/maps-route`

---

sdk/containerregistry/container-registry/samples-dev/uploadDownloadBlob.ts
sdk/containerregistry/container-registry/samples-dev/uploadManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/javascript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/javascript/anonymousListTags.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/containerRegistryClient.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/deleteImages.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/package.json
sdk/containerregistry/container-registry/samples/v1-beta/javascript/repositoryAndArtifact.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/sample.env
sdk/containerregistry/container-registry/samples/v1-beta/javascript/setImageProperties.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadDownloadBlob.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/typescript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/typescript/package.json
sdk/containerregistry/container-registry/samples/v1-beta/typescript/sample.env
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/anonymousListTags.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/containerRegistryClient.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/deleteImages.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/repositoryAndArtifact.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/setImageProperties.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadDownloadBlob.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/tsconfig.json

- #23790 
Added samples showing how to upload a blob and manifest to ACR using the existing beta API.

[ACR] Add samples for blob and manifest upload/download

---

sdk/monitor/monitor-opentelemetry-exporter/README.md

- [monitor opentelemetry exporter]
- #24044
Updating README with updated imports and fixed broken code snippets

[monitor opentelemetry exporter] Fix README code snippet bugs

---

sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_create_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_delete_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_get_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_list_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_update_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_create_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_delete_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_get_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_list_test.json
sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_update_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_create_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_delete_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_get_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_list_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_update_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_create_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_delete_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_get_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_list_test.json
sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_update_test.json

https://github.com/Azure/autorest.typescript/issues/1626

update test in comput-rest

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts

This PR merges changes from hotfix branch hotfix/identity_3.1.2 to main
Original issue - https://github.com/Azure/azure-sdk-for-js/issues/24003
Fixed by shipping version https://www.npmjs.com/package/@azure/identity/v/3.1.2 through the hotfix branch
Merging hotfix branch release commits back into main branch

Hotfix/identity 3.1.2

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/core/core-lro/test/lro.spec.ts
sdk/core/core-lro/test/utils/utils.ts
sdk/core/core-rest-pipeline/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-common/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-internal-avro/package.json
sdk/storage/storage-queue/package.json
sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub/package.json

[engsys] upgrade dev dependency `puppeteer` to `^19.2.2`

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts

[Identity] Post release version bump

---

sdk/communication/communication-identity/tests.yml

Identity SDK
[User Story 2766257](https://skype.visualstudio.com/SPOOL/_workitems/edit/2766257): [SDK] Run Identity live tests in PPE
This PR addresses the story [User Story 2766257](https://skype.visualstudio.com/SPOOL/_workitems/edit/2766257): [SDK] Run Identity live tests in PPE. As Dogfood environment is quite unstable, and tests fail quite often due to failing deployment of test resources, we are adding tests in PPE to have more stable test runs. 
The following steps were made:
- created a secret value in the KeyVault which contains subscription configs for PPE resources. 
- added new variables which point to the newly created secrets to the variable group of the live test pipeline
- added config for PPE tests
- run live test pipelines: [result …

Support PPE live tests for Identity SDK

---

sdk/cosmosdb/cosmos/README.md

@azure/cosmos
N/A
Added documentation regarding logging.
N/A
N/A
N/A
N/A

Added documentation regarding logging.

---

sdk/cosmosdb/cosmos/.vscode/launch.json
sdk/cosmosdb/cosmos/Contributing.md

@azure/cosmos
Adding VSCode launch configurations for debuging individual testcases as well as single files.
N/A
N/A
N/A

Adding VSCode launch configurations for debuging individual testcases as well as single files.

---

sdk/web-pubsub/web-pubsub-client/.eslintrc.json
sdk/web-pubsub/web-pubsub-client/package.json
sdk/web-pubsub/web-pubsub-client/samples-browser/package.json
sdk/web-pubsub/web-pubsub-client/samples-browser/public/index.html
sdk/web-pubsub/web-pubsub-client/samples-browser/sample.env
sdk/web-pubsub/web-pubsub-client/samples-browser/server.js
sdk/web-pubsub/web-pubsub-client/samples-browser/src/index.js
sdk/web-pubsub/web-pubsub-client/samples-browser/webpack.config.js
sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.browser.ts
sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.ts
sdk/web-pubsub/web-pubsub-client/src/ws.browser.js
sdk/web-pubsub/web-pubsub-client/tsconfig.json

[web-pubsub-client] Add a browser sample and fix some bugs

---

.github/CODEOWNERS

Removed my GitHub alias from JS codeowners

Update JS engsys team on codeowners

---

sdk/web-pubsub/web-pubsub-client/package.json
sdk/web-pubsub/web-pubsub-client/samples-browser/server.js
sdk/web-pubsub/web-pubsub-client/samples-browser/webpack.config.js
sdk/web-pubsub/web-pubsub-client/samples-dev/helloworld.ts
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/README.md
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/helloworld.js
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/package.json
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/sample.env
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/README.md
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/package.json
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/sample.env
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/src/helloworld.ts
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/tsconfig.json

- fix(web-pubsub-client): fix browser export for ws
- fix(web-pubsub-client): various fixes in samples

[web-pubsub-client] Fix some bugs

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/constants.ts
sdk/appconfiguration/app-configuration/test/public/index.spec.ts

[app-config] Add error message for 412 error

---

sdk/schemaregistry/test-resources.json

Updates the test-resources.json file to fix failures in the live tests pipeline.
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2060151&view=results)
Fixes https://github.com/Azure/azure-sdk-for-js/issues/24255 and https://github.com/Azure/azure-sdk-for-js/issues/24254

[Schema Registry] Update test-resources.json

---

sdk/web-pubsub/web-pubsub-client/README.md
sdk/web-pubsub/web-pubsub-client/samples-dev/helloworld.ts
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/helloworld.js
sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/src/helloworld.ts

[web-pubsub-client] Update readme

---

sdk/cognitivelanguage/ai-language-text/tests.yml
sdk/cognitivelanguage/test-resources.json

Enables custom text feature in dynamically-generated language resources by creating a storage account and linking it to the language resource.
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2069956&view=results)

[Language Text] Improve test-resources.json

---

eng/scripts/docs/Docs-ToC.ps1

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2071571&view=results
https://review.learn.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest&branch=daily%2F2022-12-19-ci-succeeded

Add 'deprecated' to toc display name

---

sdk/web-pubsub/web-pubsub/CHANGELOG.md

@azure/web-pubsub
https://github.com/Azure/azure-sdk-for-js/issues/24337 and https://github.com/Azure/azure-sdk-for-js/issues/24334
A vulnerable production dependency.
N/A
N/A
N/A

[Web PubSub] Patch release

---

sdk/maps/maps-geolocation-rest/CHANGELOG.md
sdk/maps/maps-render-rest/CHANGELOG.md
sdk/maps/maps-search-rest/CHANGELOG.md

[Maps] geolocation, render, search pre-release

---

sdk/recoveryservicessiterecovery/arm-recoveryservices-siterecovery/CHANGELOG.md
sdk/recoveryservicessiterecovery/arm-recoveryservices-siterecovery/package.json
sdk/recoveryservicessiterecovery/arm-recoveryservices-siterecovery/src/siteRecoveryManagementClient.ts

add-migration-guide-for-sierecovery

---

.github/CODEOWNERS
.github/fabricbot.json

No code changes here; Just removing myself from CODEOWNERS so I stop getting issues assigned to me.

Removing myself from CODEOWNERS since I no longer work on Azure Search

---

sdk/core/core-rest-pipeline/CHANGELOG.md

- Add release date that was lost in merge
- Remove empty section

[core-rest-pipeline] Fix CHANGELOG for release

---

sdk/core/core-lro/test/lro.spec.ts

N/A
Some unit tests didn't take the `throwOnNon2xxResponse` flag into account but they should. This PR updates the poller configuration in them to use the flag. The PR also adjusts expectation accordingly, mainly that when running in the non-throwing mode, no thrown error is expected.
N/A
N/A

[core-lro] Minor updates to tests

---

sdk/storage/storage-blob/recordings/browsers/blobclient/recording_begincopyfromurl_with_cold_tier.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_setaccesstier_set_tofrom_cold.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_sync_copy_with_cold_tier.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_upload_blob_with_cold_tier_should_work.json
sdk/storage/storage-blob/recordings/browsers/blockblobclient/recording_commitblocklist_with_cold_tier.json
sdk/storage/storage-blob/recordings/browsers/blockblobclient/recording_syncuploadfromurl_with_cold_tier_should_work.json
sdk/storage/storage-blob/recordings/browsers/containerclient/recording_listblobsbyhierarchy_with_all_parameters_configured.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_begincopyfromurl_with_cold_tier.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_setaccesstier_set_tofrom_cold.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_sync_copy_with_cold_tier.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_upload_blob_with_cold_tier_should_work.js
sdk/storage/storage-blob/recordings/node/blockblobclient/recording_commitblocklist_with_cold_tier.js
sdk/storage/storage-blob/recordings/node/blockblobclient/recording_syncuploadfromurl_with_cold_tier_should_work.js
sdk/storage/storage-blob/recordings/node/containerclient/recording_listblobsbyhierarchy_with_all_parameters_configured.js
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/operations/blockBlob.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/models.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/blockblobclient.spec.ts
sdk/storage/storage-blob/test/containerclient.spec.ts

Add a test case for listing with prefix, delimiter and include version
Add support for cold tier

[storage-blob]cold tier and blob listing with prefix,delimiter and include version

---

sdk/communication/communication-identity/package.json

Communication-Identity
https://github.com/Azure/azure-sdk-for-js/issues/22133
Excluding failing sample from smoke tests.
N/A
N/A
N/A
N/A

Exclude failing sample from smoke tests

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_append_with_acquire_lease.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_append_with_autorenew_lease.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_append_with_release_lease.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_flush_with_acquire_lease.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_flush_with_autorenew_lease.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_flush_with_release_lease.json
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_append_with_acquire_lease.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_append_with_autorenew_lease.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_append_with_release_lease.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_flush_with_acquire_lease.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_flush_with_autorenew_lease.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_flush_with_release_lease.js
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/index.ts
sdk/storage/storage-file-datalake/src/generated/src/models/mappers.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/operations/path.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-datalake/test/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/utils/testutils.common.ts

[Storage]Append with, Acquire, Release & Renewal of Lease; Flush with Release Lease

---

common/tools/dev-tool/src/commands/index.ts
common/tools/dev-tool/src/commands/run/vendored.ts
common/tools/dev-tool/src/util/printer.ts
common/tools/dev-tool/src/util/samples/syntax.ts
sdk/eventhub/event-hubs/test/public/hubruntime.spec.ts
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/options/BuildModelOptions.ts
sdk/formrecognizer/ai-form-recognizer/src/options/FormRecognizerClientOptions.ts
sdk/keyvault/keyvault-certificates/test/public/utils/common.ts
sdk/keyvault/keyvault-common/package.json
sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts
sdk/storage/storage-internal-avro/src/AvroParser.ts
sdk/storage/storage-internal-avro/src/AvroReadableFromBlob.ts
sdk/storage/storage-internal-avro/test/node/avroreader.spec.ts

- keyvault-command doesn't have samples-dev directory
- result of of `rush format`.  formatting changes that potentially caused by prettier upgrade

[engsys] fix check-format failures

---

sdk/cognitivelanguage/ai-language-text/README.md

The Language resource can't be created using the Azure CLI because it is not currently possible to agree to the Responsible AI agreement over CLI. See https://github.com/Azure/azure-sdk-for-python/issues/28233 for more details.

[Language Text] Update README

---

sdk/web-pubsub/web-pubsub-client/CHANGELOG.md
sdk/web-pubsub/web-pubsub-client/README.md

[web-pubsub-client] Prepare for beta release

---

sdk/tables/data-tables/CHANGELOG.md

Preparing @azure/data-tables for release

[Tables] prepare for release

---

eng/pipelines/templates/jobs/perf.yml

- eventhub: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129190&view=results
- storage-blob: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129191&view=results
- storage-file-datalake: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129193&view=results
- storage-file-share: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129195&view=results

[Perf] Update to Node 18

---

sdk/test-utils/perf/CHANGELOG.md
sdk/test-utils/perf/src/multicore.ts

[Perf] Console.logs that are part of the test are not being propagated

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/searchClient.ts

[Search] Fix discarded user-defined `onResponse` callback

---

sdk/cosmosdb/cosmos/README.md

[@azure/cosmos](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/cosmosdb/cosmos)
#22789 
External link was commented out as part of original PR to pass a check. Uncommenting the link now.
N/A

Uncomment external link in README

---

sdk/cognitiveservices/cognitiveservices-contentmoderator/src/operations/imageModeration.ts

@azure/cognitiveservices-contentmoderator
The customer won't be able to know what the _required_ params for this method should be.

@azure/cognitiveservices-contentmoderator ref doc changes

---

sdk/test-utils/test-credential/CHANGELOG.md
sdk/test-utils/test-credential/package.json

New patch version for `@azure-tools/test-credential` - 1.0.1

[Recorder] New patch version for `@azure-tools/test-credential` - 1.0.1

---

sdk/core/core-http/test/credentialTests.ts
sdk/core/core-http/test/serializationTests.ts
sdk/eventhub/perf-tests/event-hubs/test/subscribe.spec.ts
sdk/eventhub/perf-tests/event-hubs/tsconfig.json
sdk/servicebus/perf-tests/service-bus/tsconfig.json

The changes in this PR is the result of `rush format`

[engsys] fix check-format errors

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/azureDeveloperCliCredential.browser.ts
sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
sdk/identity/identity/src/credentials/azureDeveloperCliCredentialOptions.ts
sdk/identity/identity/test/internal/node/azureDeveloperCliCredential.spec.ts

Adding support for the Azure SDK client to support authentication using the Azure Developer Credential (azd)

Adding AzureDeveloper cli credential

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json

Update Signaling Package.

---

sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__area_codes_lists/recording_can_list_all_geographic_area_codes.json
sdk/communication/communication-phone-numbers/recordings/browsers/phonenumbersclient__area_codes_lists_aad/recording_can_list_all_geographic_area_codes.json
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__area_codes_lists/recording_can_list_all_geographic_area_codes.json
sdk/communication/communication-phone-numbers/recordings/node/phonenumbersclient__area_codes_lists_aad/recording_can_list_all_geographic_area_codes.json
sdk/communication/communication-phone-numbers/test/public/areaCodes.spec.ts

Add administrative division in geographic area codes test

---

sdk/web-pubsub/web-pubsub-client/README.md

wpb-pubsub-client
https://github.com/Azure/azure-webpubsub/issues/477
Remove signalr term

[web-pubsub-client] Remove signalr term

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client/CHANGELOG.md
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-paging/CHANGELOG.md

- update dates
- add core-amqp CHANGELOG entry

[core] Prepare for 2023 Feb release

---

sdk/maps/maps-search-rest/CHANGELOG.md

Update the release date in CHANGELOG for release.

[Maps] Pre-release update

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md

Adds appropriate CHANGELOG for 1.0.0-beta.11 release

Update CHANGELOG for 1.0.0-beta.11 release

---

sdk/web-pubsub/web-pubsub-client/CHANGELOG.md
sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts

[web-pubsub-client] Prepare release for Beta.2

---

eng/scripts/Generate-APIView-CodeFile.ps1

Remove steps to rebuild ts-genapi  api parser. Installed package location has all required scripts.

Remove api parser rebuild step

---

sdk/storage/README.md

storage packages
Update readme on storage sdk feature releasing branch to correct link in readme file.

Update readme to correct link

---

sdk/storage/README.md

storage packages
Update readme file to notice customer about storage sdk releasing branch

[storage]Update readme to notice about storage sdk branch

---

sdk/containerregistry/container-registry/CHANGELOG.md

Prepares for February beta release with new upload functionality.

[ACR] Prepare release

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

[cognitive-language] Fix pipeline with updated expectations

---

common/config/rush/pnpm-config.json
common/config/rush/pnpm-lock.yaml
eng/scripts/check-external-dependency.ps1

Followups of #24656
Porting #24761 and #24768 from "main" to keep the branches in sync

[RUSH] Porting "Followups of #24656"

---

sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/client/Item/Item.ts
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/src/documents/PartitionKey.ts
sdk/cosmosdb/cosmos/src/documents/PartitionKeyDefinitionVersion.ts
sdk/cosmosdb/cosmos/src/documents/PartitionKeyInternal.ts
sdk/cosmosdb/cosmos/src/documents/PartitionKeyKind.ts
sdk/cosmosdb/cosmos/src/documents/index.ts
sdk/cosmosdb/cosmos/src/extractPartitionKey.ts
sdk/cosmosdb/cosmos/src/utils/batch.ts
sdk/cosmosdb/cosmos/src/utils/hashing/hash.ts
sdk/cosmosdb/cosmos/src/utils/hashing/multiHash.ts
sdk/cosmosdb/cosmos/src/utils/hashing/v2.ts
sdk/cosmosdb/cosmos/src/utils/typeChecks.ts
sdk/cosmosdb/cosmos/test/internal/unit/hashing/v1.spec.ts
sdk/cosmosdb/cosmos/test/internal/unit/hashing/v2.spec.ts
sdk/cosmosdb/cosmos/test/public/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

Hierarchical partition

---

.github/CODEOWNERS
.github/fabricbot.json

For context, please see this comment:
- https://github.com/Azure/azure-sdk-for-js/pull/24621#discussion_r1102503993
Related PR:
- https://github.com/Azure/azure-sdk-tools/pull/5088

Add `CODEOWNERS` for all `/sdk/.../...-rest/` paths.

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts

[identity] update identity version

---

common/config/rush/pnpm-config.json
common/config/rush/pnpm-lock.yaml
eng/common/pipelines/templates/jobs/perf.yml
eng/pipelines/templates/jobs/perf.yml
eng/scripts/check-external-dependency.ps1
rush.json
sdk/eventhub/event-hubs/perf-tests.yml
sdk/eventhub/event-hubs/perf.yml
sdk/keyvault/keyvault-secrets/perf-tests.yml
sdk/servicebus/service-bus/perf-tests.yml
sdk/servicebus/service-bus/perf.yml
sdk/storage/storage-blob/perf-tests.yml
sdk/storage/storage-blob/perf.yml
sdk/storage/storage-file-datalake/perf-tests.yml
sdk/storage/storage-file-share/perf-tests.yml
sdk/storage/storage-file-share/perf.yml

`common/config` - from main
`eng/scripts` - location update - resulting from `pnpm-config.json`

[RUSH] Porting necessary rush changes from main

---

sdk/maps/maps-geolocation-rest/README.md
sdk/maps/maps-render-rest/README.md
sdk/maps/maps-search-rest/README.md

[Maps] Uncomment the link in README for render, search, geolocation

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

Temporarily pin devDependency "@types/trusted-types"

---

sdk/test-utils/recorder/ASSET_SYNC_MIGRATION.md

- #24729 
Migration guide for asset sync.

[recorder] Asset sync migration guide

---

design/modular-development.md

- [@azure/notification-hubs]
Adds a design document for modular design for all projects, adding subpath exports and extended ESM support

[design] Adding modular design document

---

sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob-changefeed/src/ChangeFeed.ts
sdk/storage/storage-blob-changefeed/src/ChangeFeedFactory.ts
sdk/storage/storage-blob-changefeed/src/LazyLoadingBlobStream.ts
sdk/storage/storage-blob-changefeed/src/Segment.ts
sdk/storage/storage-blob-changefeed/src/SegmentFactory.ts
sdk/storage/storage-blob-changefeed/src/Shard.ts
sdk/storage/storage-blob-changefeed/src/ShardFactory.ts
sdk/storage/storage-blob-changefeed/src/utils/tracing.ts
sdk/storage/storage-blob-changefeed/src/utils/utils.common.ts
sdk/storage/storage-blob-changefeed/test/blobchangefeedclient.spec.ts

`@azure/storage-blob-changefeed`
Fixes #21311
This PR migrates to core-tracing GA and updates tests accordingly.
#24773
#24548

[storage-blob-changefeed] Migrate to tracing GA

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

Fix cosmos custom pipeline yml which was broken by change to main pipeline yml to add CodeQL support

Reverting removal of reference to global.yml variables in ci.yml

---

.scripts/automation_init.sh

used fixed rush version because the latest one has bug

used fixed rush version because the latest one has bug

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/src/utils/constants.ts

- [@azure/notification-hubs]
Updates Notification Hubs to GA 1.0

[notification hubs] Update to GA 1.0

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Updated CHANGELOG.md

---

eng/common/pipelines/templates/jobs/perf.yml

Verification build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2208340&view=results

Port eng/common/perf.yml to storage/stable

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage] Prepare for STG86 GA

---

.github/CODEOWNERS

Add ACS Rooms Code Owners

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-text/src/lro.ts
sdk/cognitivelanguage/ai-language-text/test/internal/warn_text.spec.ts

Addresses https://github.com/Azure/azure-sdk-for-js/issues/23243

[Language Text] Log API warnings

---

common/autoinstallers/rush-prettier/pnpm-lock.yaml

this is the result of `rush update-autoinstaller --name rush-prettier` to address minimatch 3.0.4 security warning

[engsys] update rush-prettier lock file

---

sdk/cosmosdb/cosmos/src/globalEndpointManager.ts
sdk/cosmosdb/cosmos/test/public/functional/globalEndpointManager.spec.ts

@azure/cosmos
22726
This pull request aims to correct the flow of the update read endpoint within the background refresh thread. Previously, it was retrieving results from the database write endpoint.
Yes
https://github.com/Azure/azure-sdk-for-js/pull/24296

update backgroud read endpoint refresh flow

---

sdk/cognitivelanguage/ai-language-text/test/internal/warn_text.spec.ts
sdk/core/logger/src/index.ts

@azure/logger
N/A
The docstring doesn't describe how to disable logging.
N/A
N/A
N/A

[logger] Improve docstring for setLogLevel

---

sdk/core/core-http/test/credentialTests.ts
sdk/core/core-http/test/serializationTests.ts
sdk/eventhub/event-hubs/test/public/hubruntime.spec.ts

- files were formatted in PR #24378 with downgraded version prettier v2.8.1
changes in this PR are the result of `rush format` in the repo.

[engsys] fix format Feb 2023

---

sdk/identity/identity/README.md

Related to changes in https://github.com/Azure/azure-sdk-for-js/pull/24830

Add WorkloadIdentityCredential docs to Identity README

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json
sdk/communication/communication-toll-free-verification/package.json
sdk/entra/functions-authentication-events/package.json
sdk/maps/maps-common/package.json

- @types/node: 14.0.0
- dotenv: 16.0.0
- downlevel-dts: 0.10.0
- typescript: 4.8.0

[engsys] update some dependency versions for consistency in the repo

---

eng/typescript-emitter-package.json

Upgrade to cadl v0.40

---

sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/util/retries.ts

Simplifies some code and threads the abort signal to more promises in link opening. It is part of my work to simplify link opening logic to get ready to add receiver redirect.

[Event Hubs] Minor edits

---

sdk/keyvault/keyvault-keys/README.md

Fixes #23690 .
@joheredi, @heaths, @dw511214992 for notification.

Fix Azure Key Vault Keys Readme Issues

---

sdk/agrifood/agrifood-farming-rest/samples/v1-beta/javascript/sample.env
sdk/agrifood/agrifood-farming-rest/samples/v1-beta/typescript/sample.env
sdk/agrifood/agrifood-farming-rest/samples/v1/javascript/sample.env
sdk/agrifood/agrifood-farming-rest/samples/v1/typescript/sample.env

- azure-rest/agrifood-farming
- Cleaning up old secrets from sample.env which are already rotated

[Agrifood] Cleaning up old secrets from sample.env

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] Prepare for 2023 March release

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-util/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md
sdk/core/logger/CHANGELOG.md

- update release date
- add changelog entries

[core] Prepare for 2023 March release

---

.github/CODEOWNERS
common/config/rush/pnpm-lock.yaml

Merge conflict caused an outdated lockfile. Fixing it and updating code owners

Fix lock file

---

sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/src/generated/generatedClient.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/mappers.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md

[language-text] Make contexts property required for summarization

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization_with_maxsentencecont.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_maxsentencecount.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_orderby.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization_with_maxsentencecont.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_maxsentencecount.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_orderby.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization_with_maxsentencecont.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_maxsentencecount.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_orderby.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_abstractive_summarization_with_maxsentencecont.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_maxsentencecount.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_extractive_summarization_with_orderby.json
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/utils/resultHelper.ts

[language-text] Ignore fields in summarization results

---

sdk/devcenter/developer-devcenter-rest/samples-dev/sampleCreateDevBox.ts
sdk/devcenter/developer-devcenter-rest/samples-dev/sampleCreateEnvironment.ts
sdk/devcenter/developer-devcenter-rest/samples/v1-beta/javascript/sampleCreateDevBox.js
sdk/devcenter/developer-devcenter-rest/samples/v1-beta/javascript/sampleCreateEnvironment.js
sdk/devcenter/developer-devcenter-rest/samples/v1-beta/typescript/src/sampleCreateDevBox.ts
sdk/devcenter/developer-devcenter-rest/samples/v1-beta/typescript/src/sampleCreateEnvironment.ts
sdk/devcenter/developer-devcenter-rest/samples/v1/javascript/sampleCreateDevBox.js
sdk/devcenter/developer-devcenter-rest/samples/v1/javascript/sampleCreateEnvironment.js
sdk/devcenter/developer-devcenter-rest/samples/v1/typescript/src/sampleCreateDevBox.ts
sdk/devcenter/developer-devcenter-rest/samples/v1/typescript/src/sampleCreateEnvironment.ts

fix： https://github.com/Azure/azure-sdk-for-js/issues/25076

fix sample issue

---

sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/DataLakeFileSystemClient.ts
sdk/storage/storage-file-datalake/src/DataLakeLeaseClient.ts
sdk/storage/storage-file-datalake/src/DataLakeServiceClient.ts
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/utils/tracing.ts
sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

`@azure/storage-file-datalake`
Fixes #21315
This PR migrates to core-tracing GA and updates tests accordingly.
https://github.com/Azure/azure-sdk-for-js/pull/24773
https://github.com/Azure/azure-sdk-for-js/pull/24548
https://github.com/Azure/azure-sdk-for-js/pull/24850

[storage-file-datalake] Migrate to core-tracing GA

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/workloadIdentityCredential.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/25089
The options bag may not be defined. Fixed the conditional logic to reflect that otherwise it throws an error.

[identity] fix workload identity bug

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/http/operation.ts

fixes https://github.com/Azure/azure-sdk-for-js/issues/25077

Update log level to verbose when unrecognized status

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/recorder.ts

Release 3.0.0 to unblock https://github.com/Azure/autorest.typescript/pull/1775/files#r1127488247

[Recorder] Release 3.0.0

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/src/models/responses.ts

updates from bugbash
Changed from startcallrequestDTO to startcalloptions

bugbash changes

---

.scripts/automation_generate.sh

Upgrade the autorest.typescript version to the latest

Update version to the latest

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts

Update the methods so it more closely matches the dotnet sdk, added enums that can be used if desired.

update to match dotnet sdk more closely

---

sdk/communication/communication-chat/tests.yml
sdk/communication/communication-email/tests.yml
sdk/communication/communication-phone-numbers/tests.yml
sdk/communication/communication-rooms/tests.yml
sdk/communication/communication-sms/tests.yml
sdk/communication/communication-toll-free-verification/tests.yml

Affects @azure/communication-chat, @azure/communication-email, @azure/communication-phone-numbers, @azure/communication-rooms, @azure/communication-sms, @azure/communication-toll-free-verification.
Add PPE environments to all these. email package was missing Int as well.

Add missing environments to communication- packages

---

sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/samples-dev/downloadImage.ts
sdk/containerregistry/container-registry/samples-dev/uploadImage.ts
sdk/containerregistry/container-registry/samples-dev/uploadManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/javascript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/javascript/downloadImage.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadImage.js
sdk/containerregistry/container-registry/samples/v1-beta/typescript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/downloadImage.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadImage.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadManifest.ts
sdk/containerregistry/container-registry/src/blob/containerRegistryBlobClient.ts
sdk/containerregistry/container-registry/src/blob/models.ts
sdk/containerregistry/container-registry/test/public/containerRegistryBlobClient.spec.ts

- #25092 
- Add sample for full image download
- Update blob upload sample to show upload of a full image

[ACR] Samples updates to address feedback

---

sdk/digitaltwins/digital-twins-core/README.md

- @azure/digital-twins 
- #25199
Updates README to fix typo `eTag` => `etag`.

[digital twins] Update README snippets

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-common/CHANGELOG.md
sdk/keyvault/keyvault-common/package.json
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

Changelog updates and package version bumps for upcoming keyvault releases.

[keyvault] Prepare release

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callAutomationClient.ts
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/callMedia.ts
sdk/communication/communication-call-automation/src/index.ts
sdk/communication/communication-call-automation/src/models/constants.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/src/utli/converters.ts

updated the sdk according to code review feedback

---

sdk/purview/purview-sharing-rest/CHANGELOG.md

purview-sharing-rest
Updating release date in change log.

purview-sharing-rest: Update changelog for package release

---

.gitignore
eng/emitter-package.json
eng/scripts/Language-Settings.ps1

This PR does the one-time setup needed to run cadl scripts to generate code. The documentation on how to use the scripts here: https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/Cadl-Project-Scripts.md#per-project-setup

Setup cross language cadl compile

---

sdk/web-pubsub/web-pubsub-client-protobuf/src/generated/clientProto.d.ts
sdk/web-pubsub/web-pubsub-client-protobuf/src/generated/clientProto.js
sdk/web-pubsub/web-pubsub-client-protobuf/src/protos/client.proto
sdk/web-pubsub/web-pubsub-client-protobuf/src/webPubSubProtobufProtocolBase.ts
sdk/web-pubsub/web-pubsub-client-protobuf/test/client.spec.ts

eb-pubsub-client-protobuf
Add more tests

[web-pubsub-client-protobuf] Add more tests

---

sdk/containerregistry/container-registry/samples-dev/deleteBlob.ts
sdk/containerregistry/container-registry/samples-dev/deleteManifest.ts
sdk/containerregistry/container-registry/samples-dev/downloadCustomManifest.ts
sdk/containerregistry/container-registry/samples-dev/uploadCustomManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/javascript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/javascript/deleteBlob.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/deleteManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/downloadCustomManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadCustomManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/typescript/README.md
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/deleteBlob.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/deleteManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/downloadCustomManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadCustomManifest.ts

Adding samples for delete blob and manifest operations.

[ACR] Samples for deleteBlob, deleteManifest, and custom manifest upload/download

---

sdk/datafactory/arm-datafactory/CHANGELOG.md
sdk/datafactory/arm-datafactory/_meta.json
sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_create_test.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_delete_test.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_get_test.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_list_test.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_dataflowdebugsession_create_test.json
sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_dataflowdebugsession_delete_test.json
sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
sdk/datafactory/arm-datafactory/src/models/index.ts
sdk/datafactory/arm-datafactory/src/models/mappers.ts

https://github.com/Azure/sdk-release-request/issues/3842

datafactory release

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/src/utils/constants.ts

[notification hubs] Updating to 1.0 GA

---

eng/scripts/check-external-dependency.ps1

- linkify the npm package name for easier jump to the npmjs page of the package

[engsys] improve bot filed dep issue description

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/common/constants.ts
sdk/cosmosdb/cosmos/src/globalEndpointManager.ts
sdk/cosmosdb/cosmos/src/indexMetrics/CompositeIndexUtilizationEntity.ts
sdk/cosmosdb/cosmos/src/indexMetrics/Constants.ts
sdk/cosmosdb/cosmos/src/indexMetrics/IndexMetricWriter.ts
sdk/cosmosdb/cosmos/src/indexMetrics/IndexUtilizationInfo.ts
sdk/cosmosdb/cosmos/src/indexMetrics/SingleIndexUtilizationEntity.ts
sdk/cosmosdb/cosmos/src/indexMetrics/index.ts
sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
sdk/cosmosdb/cosmos/src/request/FeedResponse.ts
sdk/cosmosdb/cosmos/src/request/request.ts
sdk/cosmosdb/cosmos/test/public/indexMetrics.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/query.spec.ts

azure-cosmos-js-sdk
https://github.com/Azure/azure-sdk-for-js/issues/20194
Currently cosmos db node sdk doesn't support index metrics feature this change would enable the same.
N/A
yes

Enable index metrics feature 

---

sdk/communication/communication-call-automation/test/public/callMediaClient.spec.ts

This pull request adds testing for the functions in the CallMedia client:
- play()
- playToAll()
- startRecognizing()
- cancelAllMediaOperations()

Update tests for Media functions (Play, Recognize, Cancel)

---

.gitignore
.scripts/automation_generate.sh
documentation/RLC-Swagger-quickstart.md
documentation/RLC-quickstart.md
eng/emitter-package.json
eng/scripts/Language-Settings.ps1
eng/typescript-emitter-package.json

fixes https://github.com/Azure/azure-sdk-for-js/issues/25310

Update getstarted doc

---

sdk/communication/communication-email/CHANGELOG.md
sdk/communication/communication-email/README.md
sdk/communication/communication-email/package.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_to_a_single_recipient.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_to_multiple_types_of_recipients.json
sdk/communication/communication-email/recordings/browsers/emailclient_playbacklive/recording_successfully_sends_an_email_with_an_attachment.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_to_a_single_recipient.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_to_multiple_types_of_recipients.json
sdk/communication/communication-email/recordings/node/emailclient_playbacklive/recording_successfully_sends_an_email_with_an_attachment.json
sdk/communication/communication-email/review/communication-email.api.md
sdk/communication/communication-email/src/generated/src/emailRestApiClient.ts
sdk/communication/communication-email/src/generated/src/models/index.ts
sdk/communication/communication-email/src/generated/src/models/mappers.ts
sdk/communication/communication-email/src/generated/src/models/parameters.ts
sdk/communication/communication-email/src/models.ts
sdk/communication/communication-email/swagger/README.md
sdk/communication/communication-email/test/public/utils/recordedClient.ts

- The SDK was regenerated with the new GA-ready swagger
- Versioning was updated
- Test recordings were updated
- The CHANGELOG was updated

[Communication][Email] Preparing SDK for GA release

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/appServiceMsi2017.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/appServiceMsi2019.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/cloudShellMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/fabricMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/models.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/utils.ts
sdk/identity/identity/test/internal/node/utils.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/23328
Parsing the refresh_in parameter passed in by the msal service for Managed Identity. This parameter determines in how much time the token will be refreshed proactively by the service
Yes

[identity] Enabling proactive token refreshing in Managed Identity

---

.scripts/automation_generate.sh

Update command line

---

.scripts/automation_generate.sh

Update typespec option

---

sdk/communication/communication-common/CHANGELOG.md

communication-common
[User Story 3193020](https://skype.visualstudio.com/SPOOL/_workitems/edit/3193020): [SDK][JS] Release MicrosoftBotIdentifier feature
communication-common release 3.0.0-beta.1

communication-common release 3.0.0-beta.1

---

sdk/communication/communication-phone-numbers/CHANGELOG.md
sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-phone-numbers/src/generated/src/phoneNumbersClient.ts
sdk/communication/communication-phone-numbers/src/generated/src/siprouting/sipRoutingClientContext.ts
sdk/communication/communication-phone-numbers/src/generated/src/tracing.ts
sdk/communication/communication-phone-numbers/src/utils/constants.ts
sdk/communication/communication-phone-numbers/swagger/README-SipRouting.md
sdk/communication/communication-phone-numbers/swagger/README.md

[Communication] - Phone Numbers - Prepare for GA 1.2.0 release

---

sdk/web-pubsub/ci.yml
sdk/web-pubsub/web-pubsub-client-protobuf/CHANGELOG.md

@azure/web-pubsub-client-protobuf
Prepare for beta release

Prepare for beta.1 release

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/browsers/datalakefilesystemclient/recording_listpaths__encryption_context.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_datalakedirectoryclient_create_with__encryption_context.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_datalakefileclient_create_with_all_parameters.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_datalakefileclient_createifnotexist_with_encryption_context.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_read_a_file_with_encryption_context_set.json
sdk/storage/storage-file-datalake/recordings/node/datalakefilesystemclient/recording_listpaths__encryption_context.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_datalakedirectoryclient_create_with__encryption_context.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_datalakefileclient_create_with_all_parameters.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_datalakefileclient_createifnotexist_with_encryption_context.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_read_a_file_with_encryption_context_set.js
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/index.ts
sdk/storage/storage-file-datalake/src/generated/src/models/mappers.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/operations/path.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

[Storage]Add support for encryption context

[Storage]Add support for encryption context

---

sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/pipelineRequest.ts
sdk/core/core-rest-pipeline/src/util/uuidUtils.browser.ts
sdk/core/core-rest-pipeline/src/util/uuidUtils.native.ts
sdk/core/core-rest-pipeline/src/util/uuidUtils.ts
sdk/core/core-rest-pipeline/test/uuidUtils.spec.ts

- #25397
- #25396
Uses the native modules when possible for UUID

[core-rest-pipeline] Remove UUID module

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/models/events.ts
sdk/communication/communication-call-automation/src/models/responses.ts

As suggested by DevEx Review,
Made few values non-optional where we know for sure it will be populated in either response or events

Made changes in optional fields of Result & Events

---

sdk/cosmosdb/cosmos/package.json

@azure/cosmos
Updated version to 3.17.4-beta.1

Updated version to 3.17.4-beta.1

---

sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/context/context.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/context.test.ts

Add prefix to SDK Version and use Distro version if present

[Azure Monitor Exporter] Use Prefix/Distro version if available

---

sdk/tables/data-tables/CHANGELOG.md

Updating changelog for @azure/data-tables release.

[Tables] Prepare for release 13.2.2

---

.github/CODEOWNERS

A simple update that resolves errors in our CODEOWNERS file.

Remove invalid CODEOWNERS

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_fhir.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_healthcare_with_known_documents_type.json
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

[language-text] update recordings for healthcare tests

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-http-compat/CHANGELOG.md
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-util/CHANGELOG.md

- update release dates in CHANGELOG
- add change entries that are missing

[core] Prepare for 2023 April release

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/contentDownloader.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/test/public/callRecordingClient.spec.ts

communication-call-automation
addressed review comments, added basic unit tests, changed from enums to string unions.

review updates

---

sdk/core/core-client-rest/CHANGELOG.md

[rest/core-client] prepare for 2023 April release

---

eng/common/pipelines/templates/steps/credscan.yml
sdk/storage/storage-blob/recordings/node/containerclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-blob/recordings/node/containerclient_nodejs_only/recording_setaccesspolicy_should_work_when_expiry_and_start_undefined.js
sdk/storage/storage-blob/recordings/node/containerclient_nodejs_only/recording_setaccesspolicy_should_work_when_permissions_expiry_and_start_undefined.js
sdk/storage/storage-blob/test/node/containerclient.spec.ts
sdk/storage/storage-file-datalake/recordings/node/datalakefilesystemclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-file-datalake/recordings/node/datalakefilesystemclient_nodejs_only/recording_setaccesspolicy_should_work_when_expiry_and_start_undefined.js
sdk/storage/storage-file-datalake/test/node/filesystemclient.spec.ts
sdk/storage/storage-file-share/recordings/node/shareclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-file-share/recordings/node/shareclient_nodejs_only/recording_setaccesspolicy_and_getaccesspolicy_with_empty_signedidentifier.js
sdk/storage/storage-file-share/test/node/shareclient.spec.ts
sdk/storage/storage-queue/recordings/browsers/queueclient/recording_setaccesspolicy_negative.json
sdk/storage/storage-queue/recordings/node/queueclient/recording_setaccesspolicy_negative.js
sdk/storage/storage-queue/recordings/node/queueclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-queue/recordings/node/queueclient_nodejs_only/recording_setaccesspolicy_should_work_when_permissions_expiry_and_start_undefined.js
sdk/storage/storage-queue/test/node/queueclient.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

Porting from main branch
Sync eng/common directory with azure-sdk-tools for PR https://github.com/Azure/azure-sdk-tools/pull/5918 See [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/README.md#workflow)

Sync eng/common directory with azure-sdk-tools for PR 5918 (#25467)

---

sdk/web-pubsub/web-pubsub-client/CHANGELOG.md

[WebPubSubClient] Prepare release for beta.3

---

sdk/storage/storage-file-share/recordings/node/shareclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-file-share/recordings/node/shareclient_nodejs_only/recording_setaccesspolicy_and_getaccesspolicy_with_empty_signedidentifier.js
sdk/storage/storage-file-share/test/node/shareclient.spec.ts
sdk/storage/storage-queue/recordings/browsers/queueclient/recording_setaccesspolicy_negative.json
sdk/storage/storage-queue/recordings/node/queueclient/recording_setaccesspolicy_negative.js
sdk/storage/storage-queue/recordings/node/queueclient_nodejs_only/recording_setaccesspolicy.js
sdk/storage/storage-queue/recordings/node/queueclient_nodejs_only/recording_setaccesspolicy_should_work_when_permissions_expiry_and_start_undefined.js
sdk/storage/storage-queue/test/node/queueclient.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

Replace the secret-looking signed identifier ID with a UUID
Fixes issue #25479

[credscan][file,queue] Fix warnings

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json

Port from main: bump xml2js version to resolve CVE-2023-0842 for @azure/core-http (#25502)

---

eng/pipelines/docindex.yml

Related and dependent on https://github.com/Azure/azure-sdk-tools/pull/5951

Use normal PAT for queuing build

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage] Prepare for STG87 GA release.

---

sdk/core/core-util/CHANGELOG.md
sdk/core/core-util/src/uuidUtils.ts

- @azure/core-util
- #25501
- https://github.com/Azure/azure-sdk-for-js/issues/25541 
- https://github.com/Azure/azure-sdk-for-js/issues/25538 
- https://github.com/Azure/azure-sdk-for-js/issues/25532
Adds the native implementation if missing in older Node.js

[core] Fix UUID if not present in Node.js

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/appServiceMsi2017.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/appServiceMsi2019.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/cloudShellMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/fabricMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/models.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/utils.ts
sdk/identity/identity/test/internal/node/utils.spec.ts

https://github.com/Azure/azure-sdk-for-js/pull/25213 - Related PR
We had enabled proactive refresh for token in managed identity but removed that feature in this PR as it will be handled by MSAL.

[Identity] Remove proactive refresh in for Managed Identity

---

sdk/identity/identity/CHANGELOG.md

[Identity] update changelog and prepare release

---

sdk/core/core-util/CHANGELOG.md

- @azure/core-util
Updating to 1.3.1 to be released today

[core] Update to release @azure/core-util

---

.github/ISSUE_TEMPLATE/deprecation_request.yaml

Trying to streamline this process a bit.

Create new issue template for deprecation requests

---

common/config/rush/pnpm-lock.yaml
sdk/formrecognizer/perf-tests/ai-form-recognizer/package.json

Previous PR https://github.com/Azure/azure-sdk-for-js/pull/25470 is missing pnpm-lock.yaml update because no checks are triggered for the perf test change.

[engsys] fix rush install/update

---

common/config/rush/pnpm-lock.yaml

[Language Text Authoring] Update lock file

---

common/config/rush/pnpm-lock.yaml
sdk/cognitivelanguage/ai-language-textauthoring/package.json
sdk/cognitivelanguage/ai-language-textauthoring/sample.env
sdk/cognitivelanguage/ai-language-textauthoring/samples-dev/import.ts
sdk/cognitivelanguage/ai-language-textauthoring/tsconfig.json

To fix pipeline failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2706324&view=logs&j=0507bd12-9185-5a14-d31a-4db893ef2eeb&t=e330da5b-af55-5f83-45e3-3f7d86e7e157

[Language Text Authoring] Add a sample and skip executing it

---

sdk/translation/ai-translation-text-rest/CHANGELOG.md

[Text Translation] Releasing version 1.0.0-beta.1

[Text Translation] Releasing version 1.0.0-beta.1

---

sdk/communication/communication-short-codes/CHANGELOG.md
sdk/communication/communication-short-codes/review/communication-short-codes.api.md
sdk/communication/communication-short-codes/src/models.ts
sdk/communication/communication-short-codes/src/shortCodesClient.ts
sdk/communication/communication-short-codes/src/utils/customPipelinePolicies.ts

Exposing top/skip params to listUSProgramBriefs.
Adding a custom pipeline policy so that pagination works.

[communication][communication-short-codes] support pagination in short codes

---

sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

#25593
Skipping tests for healthcare tasks

[language text] Skip healthcare tasks

---

sdk/test-utils/recorder/ASSET_SYNC_MIGRATION.md

Minor edits to improve clarity

Update ASSET_SYNC_MIGRATION.md - Improve clarity

---

common/config/rush/pnpm-lock.yaml
sdk/confidentialledger/arm-confidentialledger/CHANGELOG.md
sdk/confidentialledger/arm-confidentialledger/_meta.json
sdk/confidentialledger/arm-confidentialledger/package.json
sdk/confidentialledger/arm-confidentialledger/review/arm-confidentialledger.api.md
sdk/confidentialledger/arm-confidentialledger/src/models/index.ts
sdk/confidentialledger/arm-confidentialledger/src/models/mappers.ts

https://github.com/Azure/sdk-release-request/issues/4048

confidentialledger release

---

eng/emitter-package.json

Bump emitter version

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts
sdk/appconfiguration/app-configuration/src/generated/src/models/index.ts
sdk/appconfiguration/app-configuration/src/generated/src/models/parameters.ts
sdk/appconfiguration/app-configuration/swagger/swagger.md
sdk/appconfiguration/perf-tests/app-configuration/package.json
sdk/appconfiguration/perf-tests/app-configuration/tsconfig.json

- Releasing 1.4.1
- Update generated code so the version in generated code is automatically updated
- Fixes #25463, updates changelog
- Update perf package to rely on 1.4.1, updates perf/tsconfig.json to use the standard one used by other packages too

[App Config] 1.4.1 release

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/authorityValidationOptions.ts
sdk/identity/identity/src/credentials/azureCliCredentialOptions.ts
sdk/identity/identity/src/credentials/azureDeveloperCliCredentialOptions.ts
sdk/identity/identity/src/credentials/azurePowerShellCredentialOptions.ts
sdk/identity/identity/src/credentials/clientAssertionCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredentialOptions.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/tokenExchangeMsi.ts
sdk/identity/identity/src/credentials/usernamePasswordCredentialOptions.ts
sdk/identity/identity/src/credentials/workloadIdentityCredential.ts
sdk/identity/identity/src/credentials/workloadIdentityCredentialOptions.ts
sdk/identity/identity/test/internal/node/workloadIdentityCredential.spec.ts
sdk/identity/identity/test/public/node/workloadIdentityCredential.spec.ts

Addressed the feedback received from Archboard review on 18th April 2023

[Identity] Archboard review identity

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md

- @azure/opentelemetry-instrumentation-azure-sdk
Updating with latest OTEL dependencies

[opentelemetry instrumentation] Release for 1.0-beta3

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

[EngSys][dev-tool] upgrade dependency `yaml` to `~2.2.0`

---

sdk/identity/identity/README.md
sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts

Azd team update `azd login` to `azd auth login`. Updating the correspond readme. If the pr is approved, would someone help me to click merge button? I couldn't do that as it says The base branch restricts merging to authorized users.

update to azd auth login readme

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/review/core-client.api.md
sdk/core/core-client-rest/src/common.ts

add-logging-options-in-client-options

---

sdk/core/core-client-rest/CHANGELOG.md

[core][core-client-rest] prepare for 2023 May release

---

common/scripts/install-run.js
rush.json

- All
N/A
Older versions of pnpm have an [issue with Node v20](https://github.com/pnpm/pnpm/issues/6424) which can be addressed by upgrading to `7.32.2` for pnpm and the latest Rush.  Note that Rush does not support `8.x` yet for pnpm.

[engsys] Update to latest pnpm 7.x and Rush

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/swagger/README.md
sdk/communication/communication-call-automation/test/callRecordingClient.spec.ts

call automation
we now enable channel affinity as an optional parameter when starting a call recording
Yes

Add channel affinity for call recording

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
sdk/communication/communication-call-automation/src/contentDownloader.ts
sdk/communication/communication-call-automation/src/models/events.ts

renamed events

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/authorityValidationOptions.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredentialOptions.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/tokenExchangeMsi.ts

None
Naming changes for following API:
- `credentialProcessTimeout` => `processTimeout`
-  `disableAuthorityValidationAndInstanceDiscovery` => `disableInstanceDiscovery`

[Identity] Archboad review feedback naming updates

---

sdk/search/search-documents/CHANGELOG.md

[Search] Prepare 2023 May Release

---

sdk/communication/communication-short-codes/.nycrc
sdk/communication/communication-short-codes/test/internal/generated_client.spec.ts

add generated client to code coverage report.
include test for generated client

include tests for generated client in short codes

---

eng/pipelines/templates/stages/platform-matrix.json

Fixes pipeline failing due to unavailable OS image

[Search] Update platform matrix

---

eng/scripts/docs/tests/rex-tool-tests.json

Add REX tool shared tests specifications

Add rex-tool-tests.json for shared tests with docs team

---

sdk/containerregistry/container-registry/package.json
sdk/containerregistry/container-registry/src/constants.ts

The release automation wasn't updating `constants.ts`. This value isn't exposed in our API but is passed to our telemetry.

[ACR] Update SDK_VERSION constant

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/samples/v3/javascript/README.md
sdk/identity/identity/samples/v3/javascript/azureDeveloperCliCredential.js
sdk/identity/identity/samples/v3/javascript/clientSecretCredential.js
sdk/identity/identity/samples/v3/javascript/defaultAzureCredential.js
sdk/identity/identity/samples/v3/javascript/environmentCredential.js
sdk/identity/identity/samples/v3/javascript/package.json
sdk/identity/identity/samples/v3/javascript/sample.env
sdk/identity/identity/samples/v3/javascript/workloadIdentityCredential.js
sdk/identity/identity/samples/v3/typescript/README.md
sdk/identity/identity/samples/v3/typescript/package.json
sdk/identity/identity/samples/v3/typescript/sample.env
sdk/identity/identity/samples/v3/typescript/src/azureDeveloperCliCredential.ts
sdk/identity/identity/samples/v3/typescript/src/clientSecretCredential.ts
sdk/identity/identity/samples/v3/typescript/src/defaultAzureCredential.ts
sdk/identity/identity/samples/v3/typescript/src/environmentCredential.ts
sdk/identity/identity/samples/v3/typescript/src/workloadIdentityCredential.ts
sdk/identity/identity/samples/v3/typescript/tsconfig.json
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/util/processMultiTenantRequest.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/25864

[Identity] Remove console logging for processMultitenantRequest

---

sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes_by_page.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes_by_page.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/test/public/listShortCodes.spec.ts
sdk/communication/communication-short-codes/test/public/manageProgramBriefAttachment.spec.ts
sdk/communication/communication-short-codes/test/public/manageUSProgramBriefs.spec.ts
sdk/communication/communication-short-codes/test/public/utils/recordedClient.ts
sdk/communication/communication-short-codes/test/public/utils/testProgramBriefAttachment.ts
sdk/communication/communication-short-codes/test/public/utils/testUSProgramBrief.ts

improve code coverage for short codes js sdk
Add pagination tests for US program briefs

[Communication][communication-short-codes] - Add pagination tests for US program briefs

---

sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_health/recording_entity_assertions.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_lros_health/recording_entity_assertions.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_health/recording_entity_assertions.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_lros_health/recording_entity_assertions.json
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

text-analytics
Update the healthcare test to reflect the new results returned

[Text Analytics] Update healthcare test and recording 

---

sdk/communication/communication-rooms/CHANGELOG.md

Add release date for Rooms Public Preview Release JS

---

sdk/communication/communication-alpha-ids/recordings/browsers/alphaidsclient__manage_configuration/recording_can_manage_configuration.json
sdk/communication/communication-alpha-ids/recordings/node/alphaidsclient__manage_configuration/recording_can_manage_configuration.json
sdk/communication/communication-alpha-ids/test/public/manageAlphaIdConfiguration.spec.ts
sdk/communication/communication-alpha-ids/test/public/utils/alphaIdClientTestUtils.ts
sdk/communication/communication-alpha-ids/tests.yml

enable PPE cloud in alpha ids live tests

[communication][communication-alpha-ids] enable PPE cloud for alpha ids live tests

---

eng/emitter-package.json

Upgrade tsp emitter to the latest version

Upgrade tsp emitter to the latest version

---

sdk/communication/communication-job-router/recordings/browsers/routerclient_job_operations/recording_should_create_a_scheduled_job.json
sdk/communication/communication-job-router/recordings/browsers/routerclient_job_operations/recording_should_list_scheduled_jobs.json
sdk/communication/communication-job-router/recordings/node/routerclient_job_operations/recording_should_create_a_scheduled_job.json
sdk/communication/communication-job-router/recordings/node/routerclient_job_operations/recording_should_list_scheduled_jobs.json
sdk/communication/communication-job-router/review/communication-job-router.api.md
sdk/communication/communication-job-router/src/generated/src/models/index.ts
sdk/communication/communication-job-router/src/generated/src/models/mappers.ts
sdk/communication/communication-job-router/src/generated/src/models/parameters.ts
sdk/communication/communication-job-router/src/generated/src/operations/jobRouter.ts
sdk/communication/communication-job-router/src/generated/src/operationsInterfaces/jobRouter.ts
sdk/communication/communication-job-router/src/models/options.ts
sdk/communication/communication-job-router/swagger/README.md
sdk/communication/communication-job-router/test/public/methods/jobs.spec.ts

[ACS JobRouter] Job scheduling changes

---

sdk/monitor/monitor-query/README.md

Remove content that already exists in the TSG, and link to it.

Link to troubleshooting guide from README

---

.vscode/cspell.json
sdk/communication/communication-job-router/review/communication-job-router.api.md
sdk/communication/communication-job-router/src/generated/src/models/index.ts
sdk/communication/communication-job-router/src/generated/src/models/mappers.ts
sdk/communication/communication-job-router/src/generated/src/models/parameters.ts
sdk/communication/communication-job-router/src/generated/src/operations/jobRouter.ts
sdk/communication/communication-job-router/src/models/models.ts
sdk/communication/communication-job-router/src/models/options.ts
sdk/communication/communication-job-router/src/routerAdministrationClient.ts
sdk/communication/communication-job-router/src/routerClient.ts
sdk/communication/communication-job-router/swagger/README.md

Add reofferTimeUtc to Decline API

---

sdk/communication/communication-short-codes/README.md
sdk/communication/communication-short-codes/recordings/browsers/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs_by_page.json
sdk/communication/communication-short-codes/recordings/node/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs.json
sdk/communication/communication-short-codes/recordings/node/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs_by_page.json
sdk/communication/communication-short-codes/review/communication-short-codes.api.md
sdk/communication/communication-short-codes/samples-dev/getAllShortCodeCosts.ts
sdk/communication/communication-short-codes/samples/v1/javascript/getAllShortCodeCosts.js
sdk/communication/communication-short-codes/samples/v1/typescript/src/getAllShortCodeCosts.ts
sdk/communication/communication-short-codes/src/generated/src/models/index.ts
sdk/communication/communication-short-codes/src/generated/src/models/mappers.ts
sdk/communication/communication-short-codes/src/generated/src/operations/shortCodesOperations.ts
sdk/communication/communication-short-codes/src/generated/src/operationsInterfaces/shortCodesOperations.ts
sdk/communication/communication-short-codes/src/models.ts
sdk/communication/communication-short-codes/src/shortCodesClient.ts
sdk/communication/communication-short-codes/swagger/shortcodes.json
sdk/communication/communication-short-codes/test/public/listShortCodeCosts.spec.ts

Note:  The current function/sdk is restricted to internal usage only
@azure-tools/communication-short-codes
Added a new function to get the eligible short code costs for a resource.
Yes
- [x ] Added impacted package name to the issue description

Added shortcode cost wrapper to the shortcode SDK

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/constants.ts

[core] prepare for June 2023 releases

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md

Update package version to prepare for STG88 preview

Update package version to prepare for STG88 preview

---

sdk/eventhub/event-hubs/samples-dev/iothubConnectionStringWebsockets.ts
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/tsconfig.json

This is the right importing behavior we want.

[Event Hubs] Update sample

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/commonUtils.test.ts

Use Kubernetes resource attributes when present, to support AKS customers

[Azure Monitor] OpenTelemetry Exporter Add support for Kubernetes resource attributes

---

sdk/cognitivelanguage/ai-language-text/assets.json
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

ai-language-text
Remove the fix me in the tests

[cognitive language] Remove fixme in the tests

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/predicates.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

**API View To Approve** https://apiview.dev/Assemblies/Review/0972d8e0f04346beb9caa64994e8499f/d4f74574fb3d4f219b1bb6ea3652c09f?diffRevisionId=1bcdb912a7f84f35aa7773f029f70761&doc=False&diffOnly=True
NA
The EventGrid Service Team has added 5 new events. The SDK must be regenerated to include the code changes related to these 5 new events. The SDK minor version has been updated.
NA
`autorest --typescript swagger\README.md`
@xirzec @ellismg @jeremymeng  Please review and approve the PR.
@lmazuel FYI

[@azure/eventgrid] Adding new events for EG Version 4.13.0

---

sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/src/utils/tracing.ts
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts

`@azure/storage-file-share`
Fixes #21312
This PR migrates to core-tracing GA and updates tests accordingly.
https://github.com/Azure/azure-sdk-for-js/pull/24773
https://github.com/Azure/azure-sdk-for-js/pull/24548
https://github.com/Azure/azure-sdk-for-js/pull/24850
https://github.com/Azure/azure-sdk-for-js/pull/25048

[storage-file-share] Migrate to core-tracing GA

---

sdk/eventgrid/eventgrid/api-extractor.json

apiview needs it as input to generate api reports

[EngSys][EventGrid] enable generation of api doc model

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/metric.ts

Breeze require delta aggregation temporality for most instruments

[Azure Monitor] OpenTelemetry Update Metrics Exporter aggregation temporality

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-text/README.md
sdk/cognitivelanguage/ai-language-text/Samples.md

ai-cognitive-language
Update What's New section in Readme, remove summarization gated access request

[Cognitive Language] Update Changes in Readme

---

sdk/openai/openai/samples/cookbook/simpleCompletionsPage/README.md
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/completions.html
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/index.html
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/package.json
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/src/index.js
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/webpack.config.js

@Azure/openai
Adds full browser page example using openai SDK
Webpack is the first library listed for packaging JS SDKs.
Merely a sample page, no functionality added

add simple completions page example

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md

- @azure/opentelemetry-instrumentation-azure-sdk
Releases latest OTEL updates for the AppInsights Team

[instrumentation] update changelog

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-textauthoring/README.md

[cognitive language] Update release date

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/src/utils/xmlUtils.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/xmlUtils.spec.ts

- #25914
Updates code to fix the error code parsing for XML.

[notification hubs] Update XML Error parsing for Issue #25914

---

.vscode/cspell.json
sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callMedia.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/swagger/README.md
sdk/communication/communication-call-automation/test/callMediaClient.spec.ts

This pull request updates the SDK with the remaining V4 Media features, including:
- Media Streaming
- Play TTS
- Play SSML
- Recognize choices
- Recognize speech

Update SDK with V4 Media Features

---

.vscode/settings.json

None - this is a dev dependency fix
https://github.com/prettier/prettier-vscode/issues/3020
Tweak our VS Code settings so that the prettier extension can properly format during development once again.

[engsys] Address issue with prettier extension

---

sdk/cognitivelanguage/ai-language-text/samples-dev/abstractiveSummarization.ts
sdk/cognitivelanguage/ai-language-text/samples-dev/customEntityRecognition.ts
sdk/cognitivelanguage/ai-language-text/samples-dev/customMultiLabelClassification.ts
sdk/cognitivelanguage/ai-language-text/samples-dev/customSingleLabelClassification.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/README.md
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/abstractiveSummarization.js
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/customEntityRecognition.js
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/customMultiLabelClassification.js
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/customSingleLabelClassification.js
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/extractiveSummarization.js
sdk/cognitivelanguage/ai-language-text/samples/v1/javascript/languageDetection.js
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/README.md
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/abstractiveSummarization.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/customEntityRecognition.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/customMultiLabelClassification.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/customSingleLabelClassification.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/extractiveSummarization.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/src/languageDetection.ts
sdk/cognitivelanguage/ai-language-text/samples/v1/typescript/tsconfig.json

[cognitive language] Publish samples

---

sdk/communication/communication-common/CHANGELOG.md

communication-common
Added patch release updates(2.2.1) into the changelog file

[ACS][Common] Post-release changes

---

sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/utils/tracing.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

`@azure/storage-queue`
Fixes #21313
This PR migrates to core-tracing GA and updates tests accordingly.
https://github.com/Azure/azure-sdk-for-js/pull/24773
https://github.com/Azure/azure-sdk-for-js/pull/24548
https://github.com/Azure/azure-sdk-for-js/pull/24850
https://github.com/Azure/azure-sdk-for-js/pull/25048
https://github.com/Azure/azure-sdk-for-js/pull/26135

[storage-queue] Migrate to core-tracing GA

---

sdk/monitor/monitor-ingestion/README.md
sdk/monitor/monitor-ingestion/TROUBLESHOOTING.md
sdk/monitor/monitor-query/TROUBLESHOOTING.md

Closes https://github.com/Azure/azure-sdk-for-js/issues/25036
@azure/monitor-ingestion

[Monitor Ingestion] update ts guide

---

eng/pipelines/weekly_automation.yml

[EngSys] prefix auto rush PRs with EngSys prefix

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/BlobDownloadResponse.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/generatedModels.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

CHANGELOG update is not included in this PR and will be copied over in one future PR.

[Storage] port PR #24934 from storage/stable branch

---

sdk/test-utils/recorder/ASSET_SYNC_MIGRATION.md

Permissions to `Azure/azure-sdk-assets`

---

sdk/communication/ci.yml
sdk/communication/communication-tiering/CHANGELOG.md
sdk/communication/communication-tiering/package.json
sdk/communication/communication-tiering/test/public/utils/recordedClient.ts

Added Tiering SDK to CI, to autogenerate package.

Adding tiering SDK to CI

---

sdk/communication/communication-chat/.nycrc

Remove Generated Code from Test Coverage Excluded

---

sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md

There are still inconsistent package versions in some places. This PR updates them all to `12.20.0`

[storage] update package version to 12.20.0

---

sdk/eventhub/event-hubs/CHANGELOG.md

[EventHubs] prepare for 5.11.1 patch release

---

sdk/communication/communication-rooms/.nycrc

This file will help us to publish the code coverage for rooms
Rooms Service
none
Rooms pipeline is not publishing code coverage
not need

Create .nycrc file for code coverage

---

sdk/communication/communication-phone-numbers/CHANGELOG.md
sdk/communication/communication-phone-numbers/recordings/node/siproutingclient__match_number_to_routes/recording_return_empty_array_when_not_found.json
sdk/communication/communication-phone-numbers/recordings/node/siproutingclient__match_number_to_routes/recording_should_match_number_to_routes.json
sdk/communication/communication-phone-numbers/recordings/node/siproutingclient__match_number_to_routes_aad/recording_return_empty_array_when_not_found.json
sdk/communication/communication-phone-numbers/recordings/node/siproutingclient__match_number_to_routes_aad/recording_should_match_number_to_routes.json
sdk/communication/communication-phone-numbers/src/generated/src/phoneNumbersClient.ts
sdk/communication/communication-phone-numbers/src/generated/src/siprouting/models/index.ts
sdk/communication/communication-phone-numbers/src/generated/src/siprouting/sipRoutingClientContext.ts
sdk/communication/communication-phone-numbers/src/generated/src/tracing.ts
sdk/communication/communication-phone-numbers/src/utils/constants.ts
sdk/communication/communication-phone-numbers/swagger/README-SipRouting.md

private release preview 2023-06-26

---

sdk/communication/communication-chat/test/internal/chatClient.mocked.spec.ts
sdk/communication/communication-chat/test/internal/chatThreadClient.mocked.spec.ts

@azure/communication-chat
https://skype.visualstudio.com/SPOOL/_workitems/edit/3091791
Added more test to improve the test code coverage.
Yes

ACS Chat Code Coverage Improvement

---

sdk/maps/maps-geolocation-rest/CHANGELOG.md
sdk/maps/maps-render-rest/CHANGELOG.md
sdk/maps/maps-route-rest/CHANGELOG.md
sdk/maps/maps-search-rest/CHANGELOG.md

- `@azure-rest/maps-render`
- `@azure-rest/maps-search`
- `@azure-rest/maps-route`
- `@azure-rest/maps-geolocation`
Pre-release for the new version of these packages.

[Maps] 2023 July Pre-Release

---

sdk/cognitivelanguage/ai-language-text/assets.json
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

ai-language-text
The pipeline has been failing for a week [here](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5076&_a=summary). Update the expectation to fix the failing pipeline.

[cognitive language] Update test expectation

---

sdk/cosmosdb/cosmos/CHANGELOG.md

@azure/cosmos
N/A
Some of the features were missing in change log this PR adds them

update change log with released features

---

sdk/communication/communication-call-automation/src/callMedia.ts

Fixing operation context for play

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Reverts Azure/azure-sdk-for-js#26308

Revert "update change log with released features"

---

sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/utils/utils.common.ts

[Storage]Added back internal blob prefix properties

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage]Upgrade storage SDK versions for features GA

---

sdk/openai/openai/CHANGELOG.md
sdk/openai/openai/package.json
sdk/openai/openai/review/openai.api.md
sdk/openai/openai/samples-dev/completionsRest.ts
sdk/openai/openai/sources/customizations/OpenAIClient.ts
sdk/openai/openai/sources/customizations/api/models.ts
sdk/openai/openai/sources/customizations/api/operations.ts
sdk/openai/openai/src/OpenAIClient.ts
sdk/openai/openai/src/api/models.ts
sdk/openai/openai/src/api/operations.ts
sdk/openai/openai/src/index.ts

@azure/openai
getImage alias added as convenience method for image generation
TBD, will add ASAP (if not in this PR, in next openAI PR)

[OpenAI] add getImage alias

---

sdk/openai/openai/assets.json
sdk/openai/openai/src/logger.ts
sdk/openai/openai/src/rest/openAIClient.ts
sdk/openai/openai/test/public/openai.spec.ts

`@azure/openai`
Adding back recordings for open.ai and addressing a couple issues where the package name was incorrect in generated files.

[OpenAI] update recordings and fixup a few codegen issues

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/README.md

Prepare for 1.0.0-beta.1 release

[Azure Monitor OpenTelemetry] Improve readme with more information

---

common/tools/dev-tool/README.md

dev-tool
Adding the missing `publish` command to the README.md for `samples`

[dev-tool] Update README.md with publish comment

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/swagger/README.md

updated support for callback URI overr~ide

---

sdk/storage/storage-file-datalake/assets.json
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/index.ts
sdk/storage/storage-file-datalake/src/generated/src/models/mappers.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/operations/pathOperations.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

Port PR https://github.com/Azure/azure-sdk-for-js/pull/25094
- update swagger and re-generate
- update models
- port tests
- port product source changes
- add recordings for new tests

[Storage] Port encryption context support from storage/stable branch

---

sdk/communication/arm-communication/README.md
sdk/communication/arm-communication/tsconfig.json

This is an automatic PR generated weekly with changes from running the
command rush update --full

Readme File update for the JS SDK with Managed Identity 

---

sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/utils/utils.common.ts

- port PR https://github.com/Azure/azure-sdk-for-js/pull/26441

[storage] Port PR #26441 from storage/stable

---

sdk/storage/storage-blob/src/Clients.ts

- port fix PR https://github.com/Azure/azure-sdk-for-js/pull/25516

[storage] port bug fix PR #25516 from storage/stable

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/http/operation.ts
sdk/core/core-lro/test/lro.spec.ts

fixes https://github.com/Azure/azure-sdk-for-js/issues/26538

Suggest proper resourceLocation for PATCH in OperationLocation mode

---

sdk/storage/storage-file-share/assets.json
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-file-share/src/StorageClient.ts
sdk/storage/storage-file-share/src/generated/src/models/index.ts
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/operations/directory.ts
sdk/storage/storage-file-share/src/generated/src/operations/file.ts
sdk/storage/storage-file-share/src/generated/src/operations/share.ts
sdk/storage/storage-file-share/src/generated/src/storageClient.ts
sdk/storage/storage-file-share/src/generatedModels.ts
sdk/storage/storage-file-share/src/models.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts
sdk/storage/storage-file-share/test/shareclient.spec.ts
sdk/storage/storage-file-share/test/utils/index.browser.ts
sdk/storage/storage-file-share/test/utils/index.ts
sdk/storage/storage-file-share/test/utils/testutils.common.ts

Port PR https://github.com/Azure/azure-sdk-for-js/pull/25005
- port code
- port tests
- add recordings for trailing dots tests
- add recordings for OAuth tests

[storage] port file OAuth and trailing dots support from storage/stable branch

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/models/events.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/swagger/README.md
sdk/communication/communication-call-automation/test/callConnection.spec.ts

add support for transfer in group call

---

sdk/communication/communication-job-router/README.md
sdk/communication/communication-job-router/src/index.ts

Job Router SDK README update

---

sdk/communication/communication-alpha-ids/CHANGELOG.md
sdk/communication/communication-alpha-ids/karma.conf.js
sdk/communication/communication-alpha-ids/recordings/browsers/alphaidsclient__manage_configuration/recording_can_list_all_dynamic_alpha_ids_countries.json
sdk/communication/communication-alpha-ids/recordings/browsers/alphaidsclient__manage_configuration/recording_can_manage_configuration.json
sdk/communication/communication-alpha-ids/recordings/browsers/alphaidsclient__preregistered_alpha_ids_operations/recording_can_list_all_preregistered_alpha_ids.json
sdk/communication/communication-alpha-ids/recordings/browsers/alphaidsclient__preregistered_alpha_ids_operations/recording_can_list_all_preregistered_alpha_ids_countries.json
sdk/communication/communication-alpha-ids/recordings/node/alphaidsclient__manage_configuration/recording_can_list_all_dynamic_alpha_ids_countries.json
sdk/communication/communication-alpha-ids/recordings/node/alphaidsclient__manage_configuration/recording_can_manage_configuration.json
sdk/communication/communication-alpha-ids/recordings/node/alphaidsclient__preregistered_alpha_ids_operations/recording_can_list_all_preregistered_alpha_ids.json
sdk/communication/communication-alpha-ids/recordings/node/alphaidsclient__preregistered_alpha_ids_operations/recording_can_list_all_preregistered_alpha_ids_countries.json
sdk/communication/communication-alpha-ids/src/alphaIdsClient.ts
sdk/communication/communication-alpha-ids/src/utils/customPipelinePolicies.ts
sdk/communication/communication-alpha-ids/test/public/dynamicAlphaId.spec.ts
sdk/communication/communication-alpha-ids/test/public/preRegisteredAlphaId.spec.ts
sdk/communication/communication-alpha-ids/test/public/utils/msUserAgentPolicy.ts
sdk/communication/communication-alpha-ids/test/public/utils/recordedClient.ts

Added a custom msuseragent header to identify tests.

add msuseragent for alpha ids tests

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts

[Identity] Merging Hotfix/identity 3.2.4 to main

---

design/multi-client-and-multi-endpoint-in-modular.md

update multi-client and multi-endpoint design doc to resolve comments

multi-client-resolve-comments

---

sdk/documenttranslator/ai-document-translator-rest/README.md

[document-translator] fix broken links in README

---

sdk/openai/openai/README.md
sdk/openai/openai/samples/cookbook/embeddingLongInputs.js
sdk/openai/openai/samples/cookbook/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26368
Updates a typo in the readme and updates the cookbook to work similar to the Python one.

[OpenAI] Update cookbook and samples

---

sdk/communication/communication-job-router/CHANGELOG.md

[ACS JobRouter] Execute pre release script

---

common/config/rush/pnpm-lock.yaml
common/scripts/install-run.js
rush.json

To address `semver` vulnerability issue.

[engsys] upgrade rush version to 5.100.2

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callAutomationClient.ts
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts

azure/communication-call-automation
#customers' feedback:
SIP UUI format: The format used by ACS (userToUser) is not aligned to RFC format. Developers being more familiar with the latter, I recommend we align to RFC format (User-to-User) in SDK as well as EG payload, just we like we do for custom headers.
In line with No.1, it might be a better experience to manage the strict header key format at SDK layer, so that every developer doesnt have to remember to set the correct format in the request.
eg. Instead of callInvite.SipHeaders.Add("userToUser", "616d617a6f6e5f6368696;encoding=hex");
we do callInvite.SipHeaders.AddUserToUser("616d617a6f6e5f6368696;encoding=hex");
eg. Instead of callInvite.SipHeaders.Add("X-MS-Custom-", "434erdr454tf"),
we do callInvite.SipHeaders.AddCustomHeader("", …

CallInvite has CustomContext class

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClient.ts
sdk/storage/storage-queue/swagger/README.md

- ensure service versions are latest
- copy over CHANGELOG entries from storage/stable branch

[Storage] update versions and CHANGELOG entries

---

sdk/appconfiguration/app-configuration/README.md

[app config] Update readme code snippets

---

.vscode/cspell.json
sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/models/options.ts

- Alpha release candidate build spellcheck fixed
- ARB recent review fixes.

Alpha release candidate build and ARB review fixes.

---

sdk/keyvault/TROUBLESHOOTING.md
sdk/keyvault/keyvault-certificates/migration-guide.md
sdk/keyvault/keyvault-keys/migration-guide.md
sdk/keyvault/keyvault-secrets/migration-guide.md

- Fixes #26358
Documentation updates with new information reflecting recent changes and feedback; see corresponding [.NET](https://github.com/Azure/azure-sdk-for-net/pull/37028) and [Python](https://github.com/Azure/azure-sdk-for-python/pull/30897) PRs.

[keyvault] Update migration and troubleshooting guides

---

sdk/core/core-auth/CHANGELOG.md
sdk/core/core-auth/package.json
sdk/core/core-auth/review/core-auth.api.md
sdk/core/core-auth/src/tokenCredential.ts

@azure/core-auth
Associated issue and PR - https://github.com/Azure/azure-sdk-for-js/pull/26614
- Adding option to enable CAE under token credential options

[core] update core-auth changes for CAE Identity

---

sdk/communication/communication-short-codes/CHANGELOG.md
sdk/communication/communication-short-codes/recordings/browsers/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs_by_page.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_and_list_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes_by_page.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/recordings/node/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs.json
sdk/communication/communication-short-codes/recordings/node/shortcodecostsclient__lists_short_code_costs/recording_can_list_all_short_code_costs_by_page.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_and_list_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes_by_page.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/review/communication-short-codes.api.md
sdk/communication/communication-short-codes/src/generated/src/models/index.ts
sdk/communication/communication-short-codes/src/generated/src/models/mappers.ts
sdk/communication/communication-short-codes/src/generated/src/operations/shortCodes.ts
sdk/communication/communication-short-codes/swagger/shortcodes.json

rename shortCodesCosts to costs in communication-short-codes

---

sdk/appconfiguration/app-configuration/README.md

[App Configuration] Update samples in Readme

---

sdk/schemaregistry/schema-registry-json/README.md

schema-registry-json
Update the links to the main branch

[schema-registry-json] Update links in Readme

---

sdk/schemaregistry/schema-registry-json/README.md
sdk/schemaregistry/schema-registry-json/samples-dev/schemaRegistryJsonSample.ts
sdk/schemaregistry/schema-registry-json/samples-dev/schemaRegistryJsonWithValidation.ts
sdk/schemaregistry/schema-registry-json/samples/v1-beta/javascript/schemaRegistryJsonSample.js
sdk/schemaregistry/schema-registry-json/samples/v1-beta/javascript/schemaRegistryJsonWithValidation.js
sdk/schemaregistry/schema-registry-json/samples/v1-beta/typescript/src/schemaRegistryJsonSample.ts
sdk/schemaregistry/schema-registry-json/samples/v1-beta/typescript/src/schemaRegistryJsonWithValidation.ts
sdk/schemaregistry/schema-registry-json/test/public/errors.spec.ts

ID cannot contain specific special characters

[schema-registry-json] Update samples ID

---

sdk/schemaregistry/ci.yml
sdk/schemaregistry/schema-registry-json/test/public/errors.spec.ts

[Schema Registry] Add Json package in ci.yml file

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md

[Storage]Prepare for STG90 preview

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26037
@joheredi, @mpodwysocki for notification.

Fix Azure OpenTelemetry instrumentation Readme Issue

---

sdk/schemaregistry/schema-registry-json/samples-dev/schemaRegistryJsonWithValidation.ts
sdk/schemaregistry/schema-registry-json/samples/v1-beta/javascript/schemaRegistryJsonWithValidation.js
sdk/schemaregistry/schema-registry-json/samples/v1-beta/typescript/src/schemaRegistryJsonWithValidation.ts

[schema-registry-json] Update validation sample

---

sdk/keyvault/keyvault-keys/CHANGELOG.md

Changelog updates for new Keys patch.

[keyvault] keyvault-keys: prepare release

---

sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/performanceCounters.test.ts

[Azure Monitor] OpenTelemetry Distro fix issue with tests reliability

---

.devcontainer/devcontainer.json

Move "settings" and "extensions" inside `customizations/vscode` as suggested at https://containers.dev/supporting

[engsys] update devcontainer.json

---

dataplane.code-workspace

- communication-administration has been deleted
- ai-anomaly-detector was removed and replaced by -rest version

Fix outdated workspace

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/README.md
sdk/identity/identity/TOKEN_CACHING.md
sdk/identity/identity/TROUBLESHOOTING.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26759

[identity] Doc updates for GA

---

common/tools/dev-tool/src/util/customization/classes.ts
common/tools/dev-tool/test/customization/classes.spec.ts

- `@azure/dev-tool`
- Fix #26800 
Fixes duplicate doc comments in declarations. This was happening because we were writing out both docs and comments. Since doc comments are also regular comments, they were getting output twice. This wasn't getting picked up in the tests since comment ranges aren't a part of the AST, and are not available after manipulating the source file (see [the warning on comment ranges here](https://ts-morph.com/details/comments)), and the test cases were being constructed by manipulating an empty source file.
I fixed the issue by just not emitting comments in this specific situation (comments in methods etc. are preserved) and only emitting docstrings. Comments in addition to docs at the method/class declaration level are rare in my experience so I think this is …

[customization] Prevent duplicate docs

---

eng/emitter-package.json

Bump typespec-ts emitter version in Aug

Bump typespec-ts emitter version in Aug

---

sdk/communication/communication-call-automation/CHANGELOG.md

Updated beta2 release date

---

sdk/communication/communication-call-automation/README.md

Updated readme links

---

sdk/communication/communication-alpha-ids/test/public/utils/recordedClient.ts

fix missing headers issue in alpha ids

---

sdk/communication/communication-phone-numbers/package.json

Update version in package json to 20230820

---

sdk/healthinsights/health-insights-cancerprofiling-rest/README.md
sdk/healthinsights/health-insights-clinicalmatching-rest/README.md

Readme links update

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/assets.json
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/assets.json
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/index.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/operations/pathOperations.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts

Port PR https://github.com/Azure/azure-sdk-for-js/pull/26730
- port blob changes
- port file-datalake changes

[storage] port pagenate deletion support from storage/stable branch

---

sdk/monitor/monitor-query/README.md

N/A
This PR is to update the Readme file with the example of batch metrics query.
No special design considerations for this issue. This is just to update the Readme
N/A
N/A

Update Readme with Batch Query Example

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-query/package.json

[Azure Monitor Exporter] Release 1.0.0-beta.15

---

sdk/healthinsights/health-insights-cancerprofiling-rest/CHANGELOG.md
sdk/healthinsights/health-insights-clinicalmatching-rest/CHANGELOG.md

Add release date to CHANGELOG.md file

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/src/shared/types.ts

[Azure Monitor OpenTelemetry] 1.0.0-beta.2 release

---

sdk/openai/openai/assets.json
sdk/openai/openai/test/public/openai.spec.ts
sdk/openai/openai/test/public/utils/recordedClient.ts

- `@azure/openai`
Fixes a request not being intercepted by the recorder

[openai] Record request to fetch generated image when checking dimensions

---

sdk/openai/openai/assets.json
sdk/openai/openai/test/public/openai.spec.ts
sdk/openai/openai/test/public/utils/utils.ts

OpenAI
Remove list of model names in playback modes

[Open AI] Update recording policy the model name test

---

sdk/appconfiguration/app-configuration/assets.json
sdk/appconfiguration/app-configuration/test/public/snapshot.spec.ts

[App Config] Unskip browser tests for snapshot feature

---

sdk/communication/communication-phone-numbers/package.json

excluded manageSipRoutingConfiguration sample from samples run.

---

sdk/communication/test-resources/test-resources-post.ps1

communication-phone-numbers
[#3371703](https://skype.visualstudio.com/SPOOL/_workitems/edit/3371703)
SIP Configuration needed domains setup before the test execution. Because we use Dynamic ACS Resources, generated on the fly, we had to add script that initializes those domains for dynamically generated ACS Resources

3394121 - Fix ACS DR SIP Configuration tests

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-query/package.json

[Azure Monitor Exporter] Release 1.0.0-beta.16

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/src/shared/types.ts

[Azure Monitor OpenTelemetry] 1.0.0-beta.3 release

---

sdk/openai/openai/README.md

#26978
Update missing import in Readme code snippets

[OpenAI] Update OpenAI Readme Sample Import

---

sdk/schemaregistry/schema-registry-json/README.md

[Schema Registry JSON] Update Json Serializer Readme

---

sdk/openai/openai/CHANGELOG.md
sdk/openai/openai/sources/customizations/api/deserializers.ts
sdk/openai/openai/src/api/deserializers.ts

[Open AI] Parse usage for get completions method

---

sdk/quantum/arm-quantum/samples-dev/workspacesCreateOrUpdateSample.ts
sdk/quantum/arm-quantum/samples/v1-beta/javascript/workspacesCreateOrUpdateSample.js
sdk/quantum/arm-quantum/samples/v1-beta/typescript/src/workspacesCreateOrUpdateSample.ts

fix: https://github.com/Azure/azure-sdk-for-js/issues/26980

[mgmt] quantum sample issue fix

---

sdk/openai/openai/CHANGELOG.md

[Open AI] Update changelog

---

eng/emitter-package-lock.json

update emitter-package-lock.json file to the latest

update emitter-package-lock.json file

---

sdk/openai/openai/samples/cookbook/speechToSpeechChat/README.md
sdk/openai/openai/samples/cookbook/speechToSpeechChat/index.html
sdk/openai/openai/samples/cookbook/speechToSpeechChat/package.json
sdk/openai/openai/samples/cookbook/speechToSpeechChat/speechToSpeechChat.html
sdk/openai/openai/samples/cookbook/speechToSpeechChat/src/azureSpeech.js
sdk/openai/openai/samples/cookbook/speechToSpeechChat/src/index.js
sdk/openai/openai/samples/cookbook/speechToSpeechChat/src/webSpeech.js
sdk/openai/openai/samples/cookbook/speechToSpeechChat/webpack.config.js

@Azure/openai
Adds a speech to speech example integrating AOAI completions with JS Speech SDK

[openai] add speech to speech sample

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] prepare for 2023 September release

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/README.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/CosmosClient.ts
sdk/cosmosdb/cosmos/src/CosmosDiagnostics.ts
sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts
sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForPartitionKey.ts
sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedIteratorResponse.ts
sdk/cosmosdb/cosmos/src/client/ClientUtils.ts
sdk/cosmosdb/cosmos/src/client/Container/Container.ts
sdk/cosmosdb/cosmos/src/client/Database/Database.ts
sdk/cosmosdb/cosmos/src/common/constants.ts
sdk/cosmosdb/cosmos/src/diagnostics/DiagnosticNodeInternal.ts
sdk/cosmosdb/cosmos/src/diagnostics/DiagnosticWriter.ts
sdk/cosmosdb/cosmos/src/diagnostics/index.ts
sdk/cosmosdb/cosmos/src/globalEndpointManager.ts
sdk/cosmosdb/cosmos/src/index.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContextBase.ts
sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/src/routing/partitionKeyRangeCache.ts
sdk/cosmosdb/cosmos/src/utils/diagnostics.ts
sdk/cosmosdb/cosmos/test/public/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/public/integration/changeFeedIterator.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/extractPartitionKey.spec.ts

Adding Diagnostic for change feed

---

sdk/core/core-rest-pipeline/CHANGELOG.md

- update core-rest-pipeline CHANGELOG

[core] prepare for 2023 September release

---

sdk/openai/openai/samples/cookbook/speechToSpeechChat/README.md

@azure/openai
Better description in readme for sample

Update README.md - include mention of Web Speech API

---

sdk/monitor/monitor-opentelemetry/review/monitor-opentelemetry.api.md
sdk/monitor/monitor-opentelemetry/samples-dev/customMetric.ts
sdk/monitor/monitor-opentelemetry/samples-dev/customTrace.ts
sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
sdk/monitor/monitor-opentelemetry/src/metrics/handler.ts
sdk/monitor/monitor-opentelemetry/src/metrics/standardMetrics.ts
sdk/monitor/monitor-opentelemetry/src/shared/config.ts
sdk/monitor/monitor-opentelemetry/src/shared/jsonConfig.ts
sdk/monitor/monitor-opentelemetry/src/shared/types.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standadMetrics.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.json
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/jsonConfig.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/azureFnHook.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts

Addressing API review requested changes

[Azure Monitor OpenTelemetry Distro] Rename azureMonitorExporterConfig

---

sdk/cosmosdb/cosmos/README.md

@azure/cosmos
- Add change feed pull model in readme.
- Update change feed limitations in readme.

Add changefeed in readme and update limitations

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Added date to CHANGELOG.md

---

sdk/cosmosdb/cosmos/CHANGELOG.md

@azure/cosmos
Updating Changelog for @azure/cosmos v4.0.0

Updating Changelog for @azure/cosmos v4.0.0

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage]Prepare for STG90 features GA release

[Storage]Prepare for STG90 features GA release

---

sdk/apimanagement/api-management-custom-widgets-scaffolder/CHANGELOG.md
sdk/apimanagement/api-management-custom-widgets-tools/CHANGELOG.md

api-management-custom-widgets scaffolder@beta3 & tools@beta2 release

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/connectionStringParser.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts

* Added Statsbeat Tests to the OpenTelemetry Exporter
* Check for valid instrumentation keys passed to the Exporter

[Monitor-OpenTelemetry-Exporter] Add Statsbeat Tests

---

common/config/rush/pnpm-lock.yaml
common/scripts/install-run.js
rush.json

- Update @microsoft/rush version to 5.106.0
- upgrade pnpm version to 8.7.5 and regenerate version 6 lockfile

[engsys] upgrade rush and pnpm

---

sdk/communication/communication-call-automation/CHANGELOG.md
sdk/communication/communication-call-automation/package.json
sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
sdk/communication/communication-call-automation/src/generated/src/models/parameters.ts
sdk/communication/communication-call-automation/src/models/constants.ts
sdk/communication/communication-call-automation/swagger/README.md

Updating GA2 changes
- Pointing to GA2 swagger
- GA2 Api auto rest generated code 
- Updated GA2 versions
- Added GA2 changelog place holders

Updating GA2 changes

---

sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/src/traces/sampler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standadMetrics.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/sampler.test..ts

[Azure Monitor OpenTelemetry] Add custom AI Sampler for distro

---

sdk/communication/communication-phone-numbers/README.md

Related to this issue https://github.com/Azure/azure-sdk-for-js/issues/26365#issuecomment-1718919473

Update README main

---

sdk/search/search-documents/README.md
sdk/search/search-documents/samples-dev/skillSetOperations.ts
sdk/search/search-documents/samples/v12-beta/javascript/skillSetOperations.js
sdk/search/search-documents/samples/v12-beta/typescript/src/skillSetOperations.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26655
@joheredi, @alzimmermsft, @dgetu for notification.

Fix Cognitive Search Readme And Sample Issues

---

sdk/openai/openai/README.md

Update it to point to main instead of the deleted branch.

[OpenAI] Update sample link

---

sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/package.json

Bump GA minor version
N/A
N/A
N/A
N/A
- [ X ] Added impacted package name to the issue description
- [ X ] Added a changelog (if necessary)

bump minor version

---

sdk/openai/openai/sources/customizations/api/deserializers.ts
sdk/openai/openai/src/api/deserializers.ts
sdk/openai/openai/test/internal/deserializer.spec.ts

@azure/openai
https://portal.microsofticm.com/imp/v3/incidents/details/424851016/home
The API renamed this property last minute
N/A
Yes
N/A

[OpenAI] Rename prompt_annotations to prompt_filter_results

---

sdk/batch/arm-batch/assets.json
sdk/chaos/arm-chaos/assets.json
sdk/compute/arm-compute-rest/assets.json
sdk/compute/arm-compute/assets.json
sdk/eventhub/arm-eventhub/assets.json
sdk/imagebuilder/arm-imagebuilder/assets.json
sdk/mediaservices/arm-mediaservices/assets.json
sdk/monitor/arm-monitor/assets.json
sdk/redis/arm-rediscache/assets.json

Update recordings to match upgraded dependencies.

Update test recordings for arm libraries

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/src/withAuth.ts
sdk/eventhub/event-hubs/test/internal/auth.spec.ts
sdk/eventhub/event-hubs/test/public/auth.spec.ts
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/core/linkEntity.ts
sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
sdk/servicebus/service-bus/src/util/sasServiceClientCredentials.ts
sdk/servicebus/service-bus/test/internal/auth.spec.ts

@azure/event-hubs, @azure/service-bus
N/A
Bump @azure/core-amqp dependency in both from v3 to v4.
N/A
N/A
N/A

[Messaging] Bump core-amqp dependency to v4

---

eng/emitter-package-lock.json
eng/emitter-package.json

Bump emitter version 0.17.0

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/assets.json
sdk/search/search-documents/src/generated/service/models/mappers.ts
sdk/search/search-documents/test/public/node/searchIndexClient.spec.ts

Temporary fix to the generated client while we wait to bump `autorest/typescript` with our next major.

[Search] Hotfix Generated Client

---

sdk/web-pubsub/web-pubsub-client/package.json

https://github.com/Azure/azure-sdk-for-js/issues/26400
React native use some different packages from node, I added some package map to resolve it.

[web-pubsub-client] React native support

---

sdk/loadtesting/arm-loadtesting/assets.json
sdk/loadtesting/arm-loadtesting/test/loadtesting_quota_operations.spec.ts
sdk/loadtesting/arm-loadtesting/test/loadtesting_resource_operations.spec.ts

fixes https://github.com/Azure/azure-sdk-for-js/issues/27159

[mgmt] rerun arm-loadtesting cases and push

---

sdk/communication/communication-common/CHANGELOG.md

add release date

---

sdk/cosmosdb/cosmos/test/internal/session.spec.ts

@azure/cosmos
https://github.com/Azure/azure-sdk-for-js/issues/26924
Some of the conditions mentioned in this file were causing issues in typescript version 5.2. This PR aims to fix that.
yes

Fix session spec file: issue in session.spec.ts causing compiler error in TypeScript 5.2

---

sdk/openai/openai/README.md

@azure/openai
Fixes https://github.com/Azure/azure-sdk-for-js/issues/27275
Missed import of `AzureKeyCredential` in README.md
N/A
N/A
N/A

[OpenAI] Update README

---

sdk/cosmosdb/cosmos/README.md

Fix README sample for @azure/cosmos

---

sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/test/public/crypto.spec.browser.ts
sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.browser.ts
sdk/keyvault/keyvault-keys/test/public/node/crypto.spec.ts
sdk/keyvault/keyvault-keys/test/public/node/localCryptography.spec.ts

Commits that I forgot to push to address feedback in https://github.com/Azure/azure-sdk-for-js/pull/27266

[keyvault] Use node/ folder for node-only Keys tests

---

sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-opentelemetry/src/shared/logging/internal.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standardMetrics.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/logging/internal.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/logging/logger.test.ts

[monitor/monitor-opentelemetry] Update Testing Coverage

---

sdk/cosmosdb/cosmos/README.md
sdk/cosmosdb/cosmos/samples/v3/javascript/ChangeFeedIterator/ChangeFeedIteratorEpkRange.js

@azure/cosmos
#27273 
Fix typos in readme and samples of change feed.
N/A

Update samples and readme

---

sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/log.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/metric.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatExporter.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/baseSender.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/context/context.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileAccessControl.ts
sdk/monitor/monitor-opentelemetry-exporter/src/sampling.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/connectionStringParser.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/commonUtils.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/fileSystemPersist.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/httpSender.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/metricUtil.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/sampling.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/assert.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/breezeTestUtils.ts

https://github.com/Azure/azure-sdk-for-js/issues/17942

[Azure Monitor Exporter] First iteration of Lint error fixes

---

sdk/communication/communication-phone-numbers/tests.yml

Add livetests to PPE

---

sdk/apimanagement/api-management-custom-widgets-scaffolder/CHANGELOG.md
sdk/apimanagement/api-management-custom-widgets-tools/CHANGELOG.md

`@azure/api-management-custom-widgets-tools`
`@azure/api-management-custom-widgets-scaffolder`
I forgot to run the release pipeline for these packages last month, so now I need to bump the date and release them out of band.

API Managment - fix release dates

---

sdk/appconfiguration/app-configuration/CHANGELOG.md

app-configuration
Prepare release for app config

[App Configuration] Prepare Release Script

---

sdk/monitor/monitor-opentelemetry/src/index.ts
sdk/monitor/monitor-opentelemetry/src/types.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts

Fixed issue with features/instrumentations were ignored when set outside of this package

[Azure Monitor OpenTelemetry ]Fix issue with wrong values for Statsbeat Features and Instrumentations

---

sdk/communication/communication-call-automation/CHANGELOG.md
sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/callMedia.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/generated/src/models/parameters.ts
sdk/communication/communication-call-automation/src/generated/src/operations/callConnection.ts
sdk/communication/communication-call-automation/src/generated/src/operationsInterfaces/callConnection.ts
sdk/communication/communication-call-automation/src/models/events.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/src/models/responses.ts
sdk/communication/communication-call-automation/swagger/README.md
sdk/communication/communication-call-automation/test/callConnection.spec.ts

Added following Signaling features to GA2
- Added functionality to cancel add participant request sent out to a participant
- Added param to override callback URL
- Added param to set transferee, is the participant who is transferring the call.
- Updated chagelog

Adding signaling features

---

sdk/network/arm-network/samples-dev/vpnSitesCreateOrUpdateSample.ts
sdk/network/arm-network/samples/v32/javascript/vpnSitesCreateOrUpdateSample.js
sdk/network/arm-network/samples/v32/typescript/src/vpnSitesCreateOrUpdateSample.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/25699
@joheredi, @dw511214992 for notification.

Fix Resource Management - Network Sample Issue

---

sdk/monitor/monitor-opentelemetry/src/metrics/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts

[Monitor OpenTelemetry] Handle issue of custom MeterReaders not being able to collect metrics for instrumentations

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-query/package.json

[Azure Monitor Exporter] Release 1.0.0-beta.17

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/README.md

[Azure Monitor OpenTelemetry] Fix Build Issue with Broken Link 1.1.0 Release

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] Prepare for Oct. 2023 release

---

sdk/core/core-amqp/CHANGELOG.md

[core-amqp] Prepare for Oct 2023 release

---

sdk/communication/communication-rooms/README.md
sdk/communication/communication-rooms/test.env

Removed non-existing type in ACS Rooms readme

Removed non-existing type in ACS Rooms readme

---

sdk/maps/maps-search-rest/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26647
@joheredi, @markweitzel, @andykao1213 for notification.

Fix Maps Search Readme Issue

---

sdk/core/core-lro/samples/typescript/samplesClient.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26981
@joheredi, @deyaaeldeen for notification.

Fix Core Lro Sample Issue

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azureDeveloperCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts
sdk/identity/identity/test/internal/tenantIdUtils.spec.ts
sdk/identity/identity/test/manual-integration/DevToolsTest/package.json
sdk/identity/identity/test/manual-integration/DevToolsTest/src/developerCredentials.ts
sdk/identity/identity/test/manual-integration/DevToolsTest/test.env
sdk/identity/identity/test/manual-integration/DevToolsTest/tsconfig.json

Added some validations for tenant and scope in this hotfix

[identity] Merge release for 3.3.1 to upstream

---

SUPPORT.md

To better align with the Node ecosystem and encourage customers to migrate to actively maintained runtimes, performing a small tweak to our `SUPPORT.md` file to signal our adoption of Node's support lifecycle.
We will still make reasonable efforts to avoid causing unnecessary churn for customers.

Update support policy to match Node's support lifecycle

---

sdk/communication/communication-job-router-rest/README.md

update README.md for Job Router Rest sdk

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage] Upgrade package version, preparing for STG91 preview

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
sdk/identity/identity/src/credentials/clientAssertionCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.browser.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/credentials/onBehalfOfCredential.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.browser.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts
sdk/identity/identity/src/errors.ts
sdk/identity/identity/src/msal/browserFlows/msalAuthCode.ts
sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/src/util/scopeUtils.ts
sdk/identity/identity/src/util/tenantIdUtils.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azureDeveloperCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts
sdk/identity/identity/test/internal/tenantIdUtils.spec.ts

None
- updated logic for tenant id and scope
- renamed internal functions and doc links

[Identity] Validation checks updated and renamed internal functions

---

sdk/identity/identity/CHANGELOG.md

[Identity] Merge Hotfix/identity 3.3.2 to upstream

---

eng/emitter-package.json

This PR updates the dependency version on the TypeScript TypeSpec emitter.

Update emitter version

---

eng/emitter-package-lock.json

This PR updates the package-lock file to accompany the change made by #27436

Updating emitter-package-lock.json to match emitter-package.json.

---

.scripts/automation_generate.sh

upgrade-autorest-typescript-version

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md

[Storage]Correct change log

---

sdk/storage/storage-file-share/test/node/directoryclient.spec.ts
sdk/storage/storage-file-share/test/node/fileclient.spec.ts
sdk/storage/storage-file-share/test/node/shareclient.spec.ts

[Storage]Disable unsupported cases temporarily

---

sdk/web-pubsub/web-pubsub-client-protobuf/CHANGELOG.md

@azure/web-pubsub-client-protobuf
Update Changelog for preparing beta.2

Prepare for beta.2 release

---

sdk/communication/communication-call-automation/CHANGELOG.md
sdk/communication/communication-call-automation/package.json
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
sdk/communication/communication-call-automation/src/models/constants.ts
sdk/communication/communication-call-automation/swagger/README.md

Call automation
download recording is not synchronous, it will now be synchronous

await on download bug fix and beta package update

---

sdk/communication/communication-call-automation/src/callRecording.ts

Call automation
download recording is not synchronous, it will now be synchronous

add await for pipe

---

sdk/core/core-rest-pipeline/CHANGELOG.md

core-rest-pipeline
Prepare for an out-of-band release for core-rest-pipeline with 3 bug fixes

[core-rest-pipeline] Run release script

---

sdk/core/core-util/CHANGELOG.md

core-util
Prepare an out-of-band release with a feature added & a bug fixed

[core-util] Run Prepare Release Script

---

common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-opentelemetry/src/index.ts
sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
sdk/monitor/monitor-opentelemetry/src/metrics/handler.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts

[Azure Monitor OpenTelemetry] Use @opentelemetry/sdk-node to initialize distro

---

sdk/cognitivelanguage/ai-language-text/assets.json
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

The live pipeline has been failing for some time so this PR updates tests to skip some and update others.
Succeeded live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3185077&view=results

[Language Text] Update tests

---

sdk/identity/identity/TOKEN_CACHING.md

Add a table row for `EnvironmentCredential`.

Add EnvironmentCredential to token cache table

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callMedia.ts

Fixed review comments - The options parameters should be called options to be consistent with other APIs

Fixed review comments

---

sdk/openai/openai/README.md
sdk/openai/openai/assets.json
sdk/openai/openai/samples-dev/audioTranscription.ts
sdk/openai/openai/samples-dev/audioTranslation.ts
sdk/openai/openai/samples/v1-beta/javascript/audioTranscription.js
sdk/openai/openai/samples/v1-beta/javascript/audioTranslation.js
sdk/openai/openai/samples/v1-beta/typescript/src/audioTranscription.ts
sdk/openai/openai/samples/v1-beta/typescript/src/audioTranslation.ts
sdk/openai/openai/test/public/node/whisper.spec.ts

To match the new resource used in testing.

[OpenAI] Edit Whisper deployment name in samples and tests

---

sdk/communication/communication-call-automation/CHANGELOG.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
sdk/communication/communication-call-automation/src/models/constants.ts
sdk/communication/communication-call-automation/swagger/README.md

Call automation
Download recording is not synchronous, it will now be synchronous

Await on download bug fix and GA package update

---

sdk/communication/communication-call-automation/CHANGELOG.md
sdk/communication/communication-call-automation/src/callRecording.ts

Call automation
Download recording is not synchronous, it will now be synchronous

add download to path await fix

---

sdk/eventgrid/eventgrid/README.md

https://github.com/Azure/azure-sdk-for-js/issues/26367
The sample provided in the Readme is both complex and not working. I have updated the sample with a simple scenario which highlights the API that is explained. I have also verified that this new sample works fine.
No special consideration for design.
No. This is just updating the Readme file. Also, the sample is tested.
NA
NA
@xirzec Please review and approve the PR

[@azure/eventgrid] Fixing the Readme issue

---

sdk/openai/openai/samples-dev/listChatCompletionsWithContentFilter.ts
sdk/openai/openai/samples/cookbook/simpleCompletionsPage/webpack.config.js
sdk/openai/openai/samples/v1-beta/javascript/listChatCompletionsWithContentFilter.js
sdk/openai/openai/samples/v1-beta/typescript/src/listChatCompletionsWithContentFilter.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/27564

[OpenAI] Fix samples

---

sdk/identity/identity/CHANGELOG.md

[identity] update release date

---

sdk/identity/identity-broker/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts

@azure/identity post release version update

[Identity] Post-release version updates

---

sdk/easm/ci.yml
sdk/easm/defender-easm-rest/CHANGELOG.md
sdk/easm/defender-easm-rest/package.json
sdk/easm/defender-easm-rest/test/public/utils/recordedClient.ts

[easm] Add CHANGELOG.md for sdk first release

---

common/config/rush/pnpm-lock.yaml
sdk/cognitivelanguage/ai-language-text/package.json
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/storage-blob-changefeed/assets.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClient.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClient.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

Upgrade storage packages versions

---

common/tools/dev-tool/src/config/rollup.base.config.ts
common/tools/dev-tool/src/util/customization/customize.ts
common/tools/dev-tool/src/util/testProxyUtils.ts
common/tools/eslint-plugin-azure-sdk/config/rush-project.json
sdk/appconfiguration/perf-tests/app-configuration/tsconfig.json
sdk/core/ts-http-runtime/package.json
sdk/devcenter/developer-devcenter-rest/test/public/devBoxesTest.spec.ts
sdk/devcenter/developer-devcenter-rest/test/public/environmentsTest.spec.ts
sdk/eventhub/perf-tests/event-hubs/test/subscribe.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/public/browser/analysis.spec.ts
sdk/keyvault/perf-tests/keyvault-secrets/test/secretTest.ts
sdk/monitor/monitor-query/samples-dev/logsResourceCentricQuery.ts
sdk/monitor/perf-tests/monitor-opentelemetry/test/monitorOpenTelemetry.spec.ts
sdk/monitor/perf-tests/monitor-opentelemetry/test/spanExport.spec.ts
sdk/servicebus/service-bus/src/core/autoLockRenewer.ts

Some files are not formated in commits that were merged without CI. This PR updates them with the result from `rush format`, and also fixes `format` script for ts-http-runtime

[EngSys] Fix format checking error

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClient.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage]Update release version

---

sdk/contentsafety/ai-content-safety-rest/README.md

fixes https://github.com/Azure/azure-sdk-for-js/issues/27562

[ai-content-safety] update readme.md

---

.scripts/automation_generate.sh
eng/emitter-package-lock.json
eng/emitter-package.json

Upgrade emitter-package and emitter-package-lock

Upgrade ts emitter version to v0.18.0

---

sdk/storage/test-resources.json

Enable file OAuth test cases

---

.vscode/cspell.json
sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/models/options.ts

Fixed rebase and build issues

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/brokerAuthOptions.ts

[Identity] based on customer feedback making brokerOptions field optional

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/partitionReceiver.ts
sdk/eventhub/event-hubs/test/internal/cancellation.spec.ts
sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts

https://github.com/Azure/azure-sdk-for-js/issues/27253
https://github.com/Azure/azure-sdk-for-js/issues/27253#issuecomment-1791749605
To be tested using stress testing framework.
UPDATE: The results are in and it is confirmed there is no more space leak!
https://github.com/Azure/azure-sdk-for-js/pull/26065

[Event Hubs] Improve prefetching

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] Prepare for November 2023 release

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Storage]Bump package version for STG91 GA

---

sdk/storage/test-resources.json

[Storage] Allow public access in storage test account

---

sdk/storage/test-resources.json

Create test account with allowing public access

---

documentation/DPG-quickstart.md
documentation/RLC-quickstart.md

Fix link issues in getstarted

---

sdk/appconfiguration/app-configuration/package.json
sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/predicates.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md
sdk/eventgrid/perf-tests/eventgrid/package.json

**API View To Approve** 
https://apiview.dev/Assemblies/Review/30d6488f3dd647a79d175e408d5d5303?diffRevisionId=20bf158c9f2341eba08c706d55a0aa4c&diffOnly=False&revisionId=f5dd29153bf946c0aa1d47886fcd5eaf&doc=true
NA
The EventGrid Service Team has added 2 new events. The SDK must be regenerated to include the code changes related to these 2 new events. The SDK minor version has been updated.
- `Microsoft.ResourceNotifications.Resources.CreatedOrUpdated`
- `Microsoft.ResourceNotifications.Resources.Deleted`
One of the important issues to note down is that this release does have a breaking change. The data type of `tags` …

[@Azure/eventgrid] Adding new events for EG Version 5.0.0

---

sdk/cosmosdb/cosmos/test/internal/unit/client.spec.ts
sdk/cosmosdb/cosmos/test/internal/unit/diagnostics.spec.ts
sdk/cosmosdb/cosmos/test/public/common/_testConfig.ts
sdk/cosmosdb/cosmos/test/public/functional/conflict.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/container.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/database.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/databaseaccount.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/globalEndpointManager.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item/batch.item.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item/item.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/query.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/changeFeedIterator.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/sslVerification.spec.ts

Removing metadata strick check & moving localhost to 127.0.0.1

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json

[notification-hubs] Update Notification Hubs dependencies

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/test/httpHeadersTests.ts
sdk/core/core-rest-pipeline/CHANGELOG.md

[core-http] prepare for v3.0.4 release

---

sdk/communication/communication-job-router-rest/README.md

[JobRouter] Update readme.md

---

sdk/communication/communication-job-router-rest/README.md

[JobRouter] Update readme

---

sdk/communication/communication-job-router-rest/CHANGELOG.md

[ACS JobRouter][GA] Execute pre-release

---

sdk/communication/communication-job-router-rest/CHANGELOG.md
sdk/communication/communication-job-router-rest/package.json
sdk/communication/communication-job-router-rest/src/azureCommunicationRoutingServiceClient.ts

Post release automated changes for azure-rest-communication-job-router

Post release automated changes for communication releases (#27841)

---

sdk/communication/communication-call-automation/CHANGELOG.md

Updated changelog

---

sdk/communication/communication-job-router-rest/README.md

Fix README code block overflow

---

sdk/communication/communication-job-router-rest/README.md

Small README updates

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/src/generated/logquery/src/models/index.ts
sdk/monitor/monitor-query/src/generated/logquery/src/operations/metadata.ts
sdk/monitor/monitor-query/src/generated/logquery/src/operations/query.ts
sdk/monitor/monitor-query/src/generated/logquery/src/operationsInterfaces/metadata.ts
sdk/monitor/monitor-query/src/generated/logquery/src/operationsInterfaces/query.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/azureMonitorMetricBatch.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/azureMonitorMetricBatchContext.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/models/index.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/models/mappers.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/models/parameters.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/operations/index.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/operations/metricsBatch.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/operationsInterfaces/index.ts
sdk/monitor/monitor-query/src/generated/metricBatch/src/operationsInterfaces/metricsBatch.ts
sdk/monitor/monitor-query/src/generated/metrics/src/models/index.ts
sdk/monitor/monitor-query/src/generated/metrics/src/models/mappers.ts
sdk/monitor/monitor-query/src/generated/metrics/src/models/parameters.ts
sdk/monitor/monitor-query/src/generated/metricsdefinitions/src/models/index.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/metricsBatchQueryClient.ts
sdk/monitor/monitor-query/swagger/logquery.md
sdk/monitor/monitor-query/swagger/metric-Batch.md
sdk/monitor/monitor-query/swagger/metric-definitions.md
sdk/monitor/monitor-query/swagger/metric-namespaces.md
sdk/monitor/monitor-query/swagger/metrics.md

NA
There is no specific problem to be addressed by this PR. The service team has done some changes to their service and provided us with a swagger update. We are regenerating the SDK based on the new PRs. These changes do not cause any breaking changes or even any API changes. All changes are happening only in the generated code and the custom code is handling them internally and not exposing any changes to the customers. 
No special design considerations are required in creating this PR. This only requires regeneration and modifying the custom code to handle the changes in the generated layer.
No. Since there are no changes exposed, the existing test cases are sufficient to handle the changes.
1. https://github.com/Azure/azure-sdk-for-java/pull/37687 (Corresponding …

[@azure/monitor-query] Releasing new beta version 1.2.0-beta.3 November 2023
