common/config/rush/pnpm-lock.yaml
sdk/tables/data-tables/package.json

The newer version of API Extractor is not compatible with ApiView. CI fails with the latest api extractor.
n/a
n/a
n/a

[Tables] Pin api-view version

---

sdk/core/core-client-rest/src/urlHelpers.ts
sdk/core/core-client-rest/test/urlHelpers.spec.ts

During Metrics Advisor exmperienment, we found that the nextLink functionality is not working well if we encoded the query keys in URL. You could try it by [this call](https://endpoint.cognitiveservices.azure.com/metricsadvisor/v1.0/dataFeeds?dataFeedName=js-test-&%24maxpagesize=1). So I fix this by
1. Only encode the query values and keep the keys as themselves
2. Support the skipUrlEncoding option at query value level
All integration cases in autorest.typescript repo has passed.
#20987

Support the skipUrlEncoding option at query parameter

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/eventGridClient.ts
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/swagger/README.md
sdk/eventgrid/perf-tests/eventgrid/package.json

The EventGrid service team is adding a new feature called channels
which can be used by Partner Topics (note that "partners" here does
not mean internal Microsoft folks, but rather larger external
customers). The channels act as a sort of namespacing mechanism
(similar to the Domain Topics for topics using the classic
"EventGrid" schema) but are only supported when the schema of the
topic is set to Cloud Events.
Unlike domain topics, where the event payload incldues information on
which topic inside the domain to send to, the channel which is
published to is specificed in an `aeg-channel-name` header as part of
the request to send events.
To support this - we add a new property to our options bag,
`channelName` which can be used to specify the channel to use when
sending a set of events. …

[EventGrid] Support Channel Names for Partner Topics

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json

This is the first step towards React-Native support for Storage libraries.  This change allows required polyfill modules to be loaded asynchronously rather than synchronously at bundling/packaging time.

[Storage] add `react-native` mapping to ESM entry point

---

sdk/identity/identity/README.md

Documenting the Azure Identity's account identifier logging feature in the logging section of readme with an example
Fixes #21014

[Identity] Documenting the Azure Identity's account identifier logging feature

---

eng/tools/rush-runner.js

ESLint step is skipped during Analyze step due to a bug introduced as part of change to split package scope among ARM and client packages.

Run lint step for all packages when artifact list is not passed

---

common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts

and report violation as warning.  Note that by default it also reports the cases where `: any` is specified explicitly.
The implicit `any` catch variable will be reported as error after we upgrade to typescript 4.6 or later.  However, the warning for explicit `any` catch variable can help us track the work to move away from any catch variable.

[engsys] enable @typescript-eslint/no-implicit-any-catch rule

---

common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts

This reverts commit 6d5a9e376ef33e5797af33248cb05d3aad8ec325.
It doesn't work as expected. While it reports warnings for explicit any catch variables, it doesn't understand unknown any catch variables and still reports them as explicit any errors.

Revert "[engsys] add @typescript-eslint/no-implicit-any-catch (#21386)"

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts

The `AzureCliCredential` is currently unable to display some errors properly to our consumers. This PR extends our error detection to bubble up errors similar to the one shown on this issue: #21151
If approved:
Fixes #21151

[Identity] Improving the errors of the AzureCliCredential

---

sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/src/index.ts

Fixed #7608 by removing unused `/* eslint-disable @typescript-eslint/member-ordering */` from
```
- sdk/keyvault/keyvault-certificates/src/index.ts:8
- sdk/keyvault/keyvault-secrets/src/index.ts:3
- sdk/keyvault/keyvault-keys/src/index.ts:3
```
according to @jeremymeng in https://github.com/Azure/azure-sdk-for-js/issues/7608#issuecomment-984091941

Remove unused eslint-disable @typescript-eslint/member-ordering in keyvault sdk

---

common/config/rush/pnpm-lock.yaml
sdk/template/template/package.json

Pin API-extractor to 7.18.11 for template package before we pin it for al packages

Pin API Extractor for template package

---

eng/scripts/Language-Settings.ps1

This is blocking js docs publishing:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1522200&view=results

Fix $package variable in docs ms validation function

---

sdk/purview/purview-catalog-rest/test/public/glossary.spec.ts

to unblock `js - eslint-plugin - ci` build, while we are still investigating why
the error is not reported by PR validation.

[purview] fix linter error

---

sdk/monitor/monitor-query/test/internal/unit/logsQueryClient.unittest.spec.ts

The test is checking a private property of ServiceClient that just got renamed.
This PR fixes the build.

[monitor-query][test] fix build error

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/recorder/src/sanitizer.ts
sdk/test-utils/recorder/test/sanitizers.spec.ts

- `@azure/test-recorder`
- Fixes #18223
The test proxy has support for adding sanitizers at two levels: at the per-recording level and at the session level. Before this PR, the JS recorder client only allowed for sanitizers to be added at the per-recording level (using the `addSanitizers` instance method on the Recorder class). This PR adds a static `Recorder.addSessionSanitizers(...)` method which allows for sanitizers to be set at the session level. These sanitizers will be applied to every recording following the call.
Yes ✅

[Recorder] Add support for session-level sanitizers

---

sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts

The order of MSIs that all languages should align to is:
1. Arc.    
2. Fabric.    
3. App Service 2019.                                                                                                            
4. App Service 2017.                                                           
5. Cloud Shell.                                                                               
6. Pod Identity v2.                                                            
7. IMDS / Pod Identity v1.  
For us, that only means moving the Arc MSI to be the first.
Feedback appreciated.

[Identity] ManagedIdentityCredential MSI order

---

sdk/appservice/arm-appservice-profile-2019-03-01-hybrid/README.md
sdk/appservice/arm-appservice-profile-2019-03-01-hybrid/package.json
sdk/authorization/arm-authorization-profile-2019-03-01-hybrid/README.md
sdk/authorization/arm-authorization-profile-2019-03-01-hybrid/package.json
sdk/compute/arm-compute-profile-2019-03-01-hybrid/README.md
sdk/compute/arm-compute-profile-2019-03-01-hybrid/package.json
sdk/dns/arm-dns-profile-2019-03-01-hybrid/README.md
sdk/dns/arm-dns-profile-2019-03-01-hybrid/package.json
sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/README.md
sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/package.json
sdk/locks/arm-locks-profile-hybrid-2019-03-01/README.md
sdk/locks/arm-locks-profile-hybrid-2019-03-01/package.json
sdk/monitor/arm-monitor-profile-2019-03-01-hybrid/README.md
sdk/monitor/arm-monitor-profile-2019-03-01-hybrid/package.json
sdk/network/arm-network-profile-2019-03-01-hybrid/README.md
sdk/network/arm-network-profile-2019-03-01-hybrid/package.json
sdk/policy/arm-policy-profile-hybrid-2019-03-01/README.md
sdk/policy/arm-policy-profile-hybrid-2019-03-01/package.json
sdk/resources/arm-resources-profile-hybrid-2019-03-01/README.md
sdk/resources/arm-resources-profile-hybrid-2019-03-01/package.json
sdk/storage/arm-storage-profile-2019-03-01-hybrid/README.md
sdk/storage/arm-storage-profile-2019-03-01-hybrid/package.json
sdk/subscription/arm-subscriptions-profile-hybrid-2019-03-01/README.md
sdk/subscription/arm-subscriptions-profile-hybrid-2019-03-01/package.json

1. @azure/arm-appservice-profile-2019-03-01-hybrid
2. @azure/arm-authorization-profile-2019-03-01-hybrid
3. @azure/arm-compute-profile-2019-03-01-hybrid
4. @azure/arm-dns-profile-2019-03-01-hybrid
5. @azure/arm-keyvault-profile-2019-03-01-hybrid
6. @azure/arm-locks-profile-hybrid-2019-03-01
7. @azure/arm-monitor-profile-2019-03-01-hybrid
8. @azure/arm-network-profile-2019-03-01-hybrid
9. @azure/arm-policy-profile-hybrid-2019-03-01
10. @azure/arm-resources-profile-hybrid-2019-03-01
11. @azure/arm-storage-profile-2019-03-01-hybrid
12. @azure/arm-subscriptions-profile-hybrid-2019-03-01
N/A
There are 12 profiles that got generated with v4x generator. During management plane migrations, new 12 profile packages have been generated to replace the above 12 packages. So, they have already become …

Deprecate Old Profile Packages

---

gulpfile.ts

Looks that some very old version of TS is used, and `any` type for catch variable
is not recognized.  This reverts an earlier change of preparing to move to TS
v4.6 by adding `: any` type annotation to catch variable.  We can investigate upgrading separately.

[engsys] fix gulpfile error

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/review/data-tables.api.md
sdk/tables/data-tables/src/index.ts

n/a
As a consumer of the typings, one may want to define a parameter that is compatible with the underlying TableClient, eg:
```ts
function createClient(accountName: string, tableName: string, credential?: NamedKeyCredential);
```
At the moment this isn't possible without importing the `NamedKeyCredential` directly from `@azure/core-auth` which means having to explicitly declare this dependency in a project.
In line with other exports, exporting dependant types helps keep the API more clearly defined and makes the load on consumers lighter by having to not know about implicit dependencies.
yes
n/a

[tables] Add NamedKeyCredential to exports for easier consumption

---

sdk/appservice/arm-appservice-profile-2019-03-01-hybrid/README.md
sdk/appservice/arm-appservice-profile-2019-03-01-hybrid/package.json
sdk/authorization/arm-authorization-profile-2019-03-01-hybrid/README.md
sdk/authorization/arm-authorization-profile-2019-03-01-hybrid/package.json
sdk/compute/arm-compute-profile-2019-03-01-hybrid/README.md
sdk/compute/arm-compute-profile-2019-03-01-hybrid/package.json
sdk/dns/arm-dns-profile-2019-03-01-hybrid/README.md
sdk/dns/arm-dns-profile-2019-03-01-hybrid/package.json
sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/README.md
sdk/keyvault/arm-keyvault-profile-2019-03-01-hybrid/package.json
sdk/locks/arm-locks-profile-hybrid-2019-03-01/README.md
sdk/locks/arm-locks-profile-hybrid-2019-03-01/package.json
sdk/monitor/arm-monitor-profile-2019-03-01-hybrid/README.md
sdk/monitor/arm-monitor-profile-2019-03-01-hybrid/package.json
sdk/network/arm-network-profile-2019-03-01-hybrid/README.md
sdk/network/arm-network-profile-2019-03-01-hybrid/package.json
sdk/policy/arm-policy-profile-hybrid-2019-03-01/README.md
sdk/policy/arm-policy-profile-hybrid-2019-03-01/package.json
sdk/resources/arm-resources-profile-hybrid-2019-03-01/README.md
sdk/resources/arm-resources-profile-hybrid-2019-03-01/package.json
sdk/storage/arm-storage-profile-2019-03-01-hybrid/README.md
sdk/storage/arm-storage-profile-2019-03-01-hybrid/package.json
sdk/subscription/arm-subscriptions-profile-hybrid-2019-03-01/README.md
sdk/subscription/arm-subscriptions-profile-hybrid-2019-03-01/package.json

1. @azure/arm-appservice-profile-2019-03-01-hybrid
2. @azure/arm-authorization-profile-2019-03-01-hybrid
3. @azure/arm-compute-profile-2019-03-01-hybrid
4. @azure/arm-dns-profile-2019-03-01-hybrid
5. @azure/arm-keyvault-profile-2019-03-01-hybrid
6. @azure/arm-locks-profile-hybrid-2019-03-01
7. @azure/arm-monitor-profile-2019-03-01-hybrid
8. @azure/arm-network-profile-2019-03-01-hybrid
9. @azure/arm-policy-profile-hybrid-2019-03-01
10. @azure/arm-resources-profile-hybrid-2019-03-01
11. @azure/arm-storage-profile-2019-03-01-hybrid
12. @azure/arm-subscriptions-profile-hybrid-2019-03-01
N/A
There are 12 profiles that got generated with v4x generator. During management plane migrations, new 12 profile packages have been generated to replace the above 12 packages. So, they have already become …

Deprecate Old Profiles

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json

- fix react native bundling issue by adding a `react-native` mapping to ESM
entry point so that dependencies can be loaded asynchronously.

[data-tables] add `react-native` mapping to ESM entry point

---

sdk/servicebus/service-bus/test/internal/operationOptionsForATOM.spec.ts

after core-rest-pipeline moved to core-tracing 1.0.0

[ServiceBus][Test] fix tracing test

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
sdk/schemaregistry/schema-registry-avro/README.md
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/public/avroSerializer.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/20063
The old payload format was planned to be supported until the last beta before the first stable release and since the first stable release is scheduled for May, the compatability should be removed now.

[Schema Registry Avro] Remove old format compatability

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json

opentelemetry-instrumentation-azure-sdk
#21140
OTel uses peer dependencies to request a version of @opentelemetry/api that is
compatible with their SDK. In min testing, that peer version is 1.0.2, so we
want to bump our min-version here as well.
This doesn't resolve the max part of min/max but I believe the next rush update
--full when merged will resolve it.

[opentelemetry] - Bump otel API min-version

---

sdk/core/core-http/src/policies/msRestUserAgentPolicy.native.ts
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/util/userAgentPlatform.native.ts

- use major.minor.patch for react-native version
- remove unnecessary String cast in string interpolation

[core] improve user agent information for React Native

---

sdk/schemaregistry/schema-registry-avro/test/public/avroSerializer.spec.ts
sdk/schemaregistry/schema-registry-avro/test/public/utils/mockedRegistryClient.ts

Mocked error message didn't match live test error message.
Failed run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1534686&view=logs&j=b800360f-d572-5e16-3e20-e4f204d3fbd3&t=3b97752f-f53c-5e36-3379-45368efa0b3c
Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1535009&view=results
N/A
N/A

[Schema Registry Avro] Fix test

---

sdk/core/core-amqp/src/errors.ts

by reverting to the old runtime behavior of checking whether a message has
already been translated.
The regression was introduced in PR #21485 and caused a Service Bus live test to
fail.

[core-amqp] Fix a regression

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/Clients.ts

Remove unuse options introduced from last feature implementation.

Remove unuse options introduced from last feature implementation.

---

sdk/containerregistry/container-registry/test/public/containerRegistryBlobClient.spec.ts

Due to an issue with the recorder serializing and deserializing request body, the computed digest from the request body does not match the recorded Docker-Content-Digest header during playback. Previously, I tried to mock this by overriding the Docker-Content-Digest header returned by the recording, but a recent change to the test proxy seems to have changed the formatting of the response returned by the proxy, breaking the mock.
The existing workaround is clearly flaky so this PR disables the test for the time being, until we can get a more robust fix in the test proxy.

[ACR] Disable flaky/broken manifest upload test to fix build

---

sdk/core/core-tracing/review/core-tracing.api.md
sdk/core/core-tracing/src/interfaces.ts
sdk/core/core-tracing/src/tracingClient.ts

core-tracing
N/A - API review for core-tracing
We recently added the OptionsWithTracingContext type but it accepts an unbounded
type parameter which is not realistic in our scenarios.
This PR ensures we accept the type parameter we expect.

[core-tracing] - Narrow Options type in OptionsWithTracingContext

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/src/util/error.ts
sdk/eventhub/event-hubs/test/internal/eventHubProducerClient.idem.spec.ts
sdk/eventhub/event-hubs/test/internal/transformEventsForSend.spec.ts
sdk/eventhub/event-hubs/test/public/eventHubBufferedProducerClient.spec.ts

[Event Hubs] Rename idempotent retries flag

---

sdk/monitor/monitor-opentelemetry-exporter/tests.yml

This build pipelines occasionally went over 15 minutes limit. This PR removes the limit, so that default of 60 minutes is used.

[monitor-ot-exporter][test] remove 15 minutes timeout limit

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/constructorHelpers.ts
sdk/servicebus/service-bus/src/util/constants.ts
sdk/servicebus/service-bus/test/internal/unit/client.spec.ts

- Port relevant changes from Event Hubs PR https://github.com/Azure/azure-sdk-for-js/pull/12909. Most of work was done in core-amqp. This PR just
needs to connect the client options with the underlying connection context.
@azure/service-bus
#21574

[ServiceBus] add custom endpoint support

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/recordings/node/usernamepasswordcredential_internal/recording_accepts_tokencachepersistenceoptions.json
sdk/identity/identity-cache-persistence/recordings/node/usernamepasswordcredential_internal/recording_authenticates_silently_with_tokencachepersistenceoptions.json
sdk/identity/identity/package.json
sdk/identity/identity/recordings/node/usernamepasswordcredential/recording_authenticates.json
sdk/identity/identity/recordings/node/usernamepasswordcredential/recording_supports_tracing.json
sdk/identity/identity/recordings/node/usernamepasswordcredential_internal/recording_authenticates_with_tenantid_on_gettoken.json

This unblocks the `rush update --full` automation. It looks that v6.3.0 has made
some typing improvement that makes v4.5.1 incompatible
```
src/msal/nodeFlows/msalNodeCommon.ts(270,7): error TS2322: Type 'import("/mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/@azure+msal-common@4.5.1/node_modules/@azure/msal-common/dist/account/AccountInfo").AccountInfo' is not assignable to type 'import("/mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/@azure+msal-common@6.3.0/node_modules/@azure/msal-common/dist/account/AccountInfo").AccountInfo'.
Types of property 'idTokenClaims' are incompatible.
Type 'object | undefined' is not assignable to type '(TokenClaims & { [key: string]: unknown; }) | undefined'.
Type 'object' is not assignable to type 'TokenClaims & { [key: string]: unknown; }'.
Type …
```

[identity] upgrade dependency @azure/msal-common to ^v6.3.0

---

eng/pipelines/templates/variables/globals.yml

Disable auto injected docker image check step temporarily until issues #21765 and #21766 are fixed.

Disable docker image warning in CI

---

sdk/core/core-paging/CHANGELOG.md
sdk/core/core-paging/package.json
sdk/core/core-paging/src/getPagedAsyncIterator.ts

@azure/core-paging
The default implementation of `byPage` did not support input continuation tokens
This PR adds default support for input continuation tokens in `byPage` by treating them opaquely.
N/A
N/A

[core-paging] provide default continuation token support

---

eng/pipelines/aggregate-reports.yml

The pipeline has been timed out after 4 hours recently.  The last successful run took 3h 55m.  Increase the limit to a larger value to give it some room.

[engsys] increase aggregate-report timeout limit to 6 hours

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/core/core-rest-pipeline/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-internal-avro/package.json
sdk/storage/storage-queue/package.json
sdk/web-pubsub/web-pubsub-express/package.json
sdk/web-pubsub/web-pubsub/package.json

upgrade `puppeteer` dev dependency to ^14.0.0 by running the following command
`rush add --dev -m -p puppeteer@^14.0.0` in one of the affected package folder.
The breaking changes is dropping NodeJS v12 support so we will have to wait a bit until we remove NodeJS v12 from our test matrix.

[engsys] upgrade `puppeteer` dev dependency to ^14.0.0

---

sdk/eventgrid/eventgrid/src/util.ts
sdk/eventgrid/eventgrid/test/internal/util.spec.ts

`@azure/eventgrid`
I did not create an issue. Should I have? 
We ran into trouble, because we only needed a token for 30 minutes and from 11:30 am to 12:30 pm the expiration date was 12:00 am, which is of course in the past.
Yes. The exact problem was added as a test case, that failed before adjusting the code

[eventgrid] Correctly Format Datetime to 12 hour Format

---

documentation/RLC-quickstart.md

Fix the issues mentioned here #21842 :
- Please provide windows command for 'export TEST_MODE=record && rushx test ' as 'export' is not supported in windows
- [0] [test-proxy] Image tag obtained from the powershell script => 1.0.0-dev.20220427.1

Update the testing part in RLC-quickstart

---

common/tools/dev-tool/src/config/rollup.base.config.ts
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts

- remove circular refs of eventHubBufferedProducerClient -> index ->
eventHubBufferedProducerClient
- remove circular refs of eventData -> eventDataBatch -> eventData
- suppress circular refs from dependency `rhea-promise`

[EventHubs] Fix rollup circular dependency warnings

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json
sdk/core/core-lro/review/core-lro.api.md
sdk/core/core-lro/src/lroEngine/lroEngine.ts
sdk/core/core-lro/src/lroEngine/models.ts
sdk/core/core-lro/src/lroEngine/operation.ts

@@azure/core-lro
lroEngine provides a default implementation of client-side polling for LROs and the default cancellation method is a no-op.
This PR makes cancellation configurable by adding an optional function that specifies how cancellation should work. Currently, cancellation requests are not standardized according to the [REST API spec](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs) so I am not sure if we could provide a reasonable default implementation. 
N/A
N/A

[core-lro] lroEngine to support cancellation

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/requestResponseLink.ts

The live test logs shows that under some circumstance `this.receiver` could be
`undefined`.  We do have code to clean up the timer already so that might have
happened before the clean up and after receiver is closed.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'address')
at Receiver.get address [as address] (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/rhea-promise@2.1.0/node_modules/rhea-promise/lib/link.ts:96:24)
at Timeout._onTimeout (/Users/runner/work/1/s/sdk/core/core-amqp/src/requestResponseLink.ts:158:39)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
```
This PR ensures that we don't throw when `this.receiver` is undefined.  The
address is only used in logging.

[core-amqp] handle possible `undefined` receiver in timeout handler

---

sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts

There's a recent behavior change in Blob SDK that empty metadata is now returned as `undefined` (issue #21863) instead of previous value of empty string.  This PR adds a guard against undefined metadata so we don't access property off `undefined`.

[EH-checkpoint-store-blob] guard against undefined blob metadata

---

sdk/agrifood/agrifood-farming-rest/package.json

This is consistent with most of other packages in the repo.  Version 1.2.2 is
never released, and we already bumped the version to 1.3.0.
This fix js - core nightly because we tried to use 1.2.2 there but failed to resolve it.

[agrifood-farming-rest] downgrade dep @azure/core-paging to ^1.2.0

---

sdk/textanalytics/ai-text-analytics/README.md

The old feature branch has been deleted and the file lives in the main branch now.

[Text Analytics] Update link in README

---

sdk/web-pubsub/web-pubsub/recordings/node/hubclient_working_with_a_hub/recording_can_broadcast_using_apim.json
sdk/web-pubsub/web-pubsub/recordings/node/hubclient_working_with_a_hub/recording_can_grant_permissions_to_connections.json
sdk/web-pubsub/web-pubsub/recordings/node/hubclient_working_with_a_hub/recording_can_trace_through_the_various_options.json
sdk/web-pubsub/web-pubsub/test/hubs.spec.ts
sdk/web-pubsub/web-pubsub/test/testEnv.ts

- `@azure/web-pubsub`
- Changes related to #20400
A similar issue to #21813. From there:
> I recently improved the error messages coming out of the recorder in https://github.com/Azure/azure-sdk-for-js/pull/21575, making the recorder client throw a special error when the recorder failed to find a matching recording for a request. Before that change, the recorder client would yield a standard RestError with a 404 response when a request couldn't be matched to a recording.
There is a test in web-pubsub which expects a 404 response from the server. It checks for this by catching `RestError` and validating the status code. However, due to an unnoticed issue in the sanitization of recordings, the 404 that the test was catching was actually coming from the test proxy not being able to match the …

[web-pubsub] Fix recorded tests

---

sdk/eventhub/event-hubs/test/internal/eventProcessor.spec.ts

This is to work around a service issue when receiving messages from start
position of -1.  Similar to PR# https://github.com/Azure/azure-sdk-for-js/pull/20982

[event hubs] Fix test timeout failure on China cloud

---

sdk/core/core-amqp/test/requestResponse.spec.ts

The compiler is having problem figuring it out in latest `rush update --full` run.
>test/requestResponse.spec.ts(607,31): error TS7006: Parameter 'tid' implicitly has an 'any' type.

[core-amqp][test] add explicit type for clearTimeout parameter

---

sdk/textanalytics/ai-text-analytics/package.json

Because TA uses features available in the new version only and we don't want min testing to fail.

[Text Analytics] Bump core-lro dep version

---

sdk/servicebus/service-bus/api-extractor.json
sdk/servicebus/service-bus/package.json

in public-trimmed dts rollup, @beta APIs are removed. Because we only ship
public-trimmed version it prevents us from gathering feedback for @beta APIs.
This PR enable generation of beta-trimmed dts rollup.
We still need the piece in the publishing process to use the proper version
depending on whether we are releasing a beta/dev version or not.

[ServiceBus] enable beta-trimmed api-extractor dts rollup

---

sdk/servicebus/service-bus/CHANGELOG.md

for the `omitMessageBody` feature.

[service-bus] prepares an out-of-band beta release

---

sdk/servicebus/service-bus/.eslintrc.json
sdk/servicebus/service-bus/package.json

Previous change update the package to include beta-trimmed dts rollup but missed
updating the `types` field.  This PR fixes it.

[ServiceBus] Fix `types` for beta release

---

sdk/keyvault/keyvault-keys/test/public/identifier.spec.ts

- Fixes #21927
Adds a test case to verify that the JS client does not have the same issue as Python described in https://github.com/Azure/azure-sdk-for-python/issues/24446.

[KeyVault] Add test case to verify port numbers preserved in vault URL

---

eng/tools/dependency-testing/index.js

Previously `npm view <packageName> versions --json` returns an array even when
the result only contains one version.  In latest NPM version in NodeJS v16 the
result is now a string, which isn't expected by `semver` APIs.
This PR wraps the single string result with an array.

[engsys] Fix min-max version script error due to npm breaking change

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/common/constants.ts

Updating the current API version to 2020-07-15. This will unblock Data Explorer and Portal so that hierarchical partition keys support can be added

Update the current API version to 2020-07-15

---

sdk/core/core-amqp/src/retry.ts

This PR fixed #14864.
I use a local variable `updatedConfig` instead of the passed in `config` to avoid modifying the original argument. I choose to use the local variable even when the config options is defined because if I were to use the original config, 
```
if (!configConfig.retryOptions) {
updatedConfig.retryOptions = {};
}
// config.retryOptions might be undefined.
if (config.retryOptions.maxRetries == undefined || config.retryOptions.maxRetries < 0) {  
...
}
```
Another workaround would be saving the argument in a local variable and reset the argument at the end of the function (but this would not work asynchronously)

use local config in retry<T>

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/request/SharedOptions.ts

@azure/cosmos
Missing @beta annotation on beta property
The property was added directly to the `SharedOptions` interface instead of inheriting from a `@beta` interface, this prevents the TS issue where the stable interface depends on a beta interface.
This PR is adding a `@beta` tag missing on the new property.

Add back missing @beta tag

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/review/core-client.api.md
sdk/core/core-client/src/interfaces.ts
sdk/core/core-client/src/serializer.ts
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/review/core-http.api.md
sdk/core/core-http/src/serializer.ts
sdk/core/core-http/src/util/xml.ts

`@azure/core-http` (For Track 1) & `@azure/core-client` (For Track 2). Thus, by extension, all the packages dependent on these package. 
https://github.com/Azure/azure-sdk-for-js/issues/21839
Basically, the problem started with this [issue](https://github.com/Azure/azure-sdk-for-js/issues/21839). One of the customers reported that there is an issue with a way `multipleOf` constraint is handled. That is because of the `%` operator. While working through this, we have [decided ](https://github.com/Azure/azure-sdk-for-js/issues/21839#issuecomment-1135156751) that the constraints check can be removed altogether. I have already confirmed with other language owners that they do not perform constraints check.
There are 2 design options. 
Remove the constraints method altogether. This will …

[@azure/core-http]/[@azure/core-client] - Remove Constraints Check

---

sdk/storage/storage-blob/tests.yml

- Reverts unintentional move to westus in #13886
- Aligns storage-blob with storage-file-share and storage-file-datalake
- Ensures access is over ipv4, which is required for some SAS tests
- If both agent VMs and storage account are in westus, access is over ipv6

Move storage-blob resource location to canadacentral

---

sdk/identity/identity/test/manual-integration/Kubernetes/Dockerfile

Update docker file to use different image for node alpine and also update the branch to main. This docker file seems not used for a while since it was still referring master branch.

Fix dockerfile copy ref

---

sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_cannot_create_a_certificate_with_an_empty_name.json
sdk/keyvault/keyvault-certificates/recordings/node/certificates_client__create_read_update_and_delete/recording_cannot_create_a_certificate_with_an_empty_name.js
sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations/recording_cannot_create_a_key_with_an_empty_name.json
sdk/keyvault/keyvault-keys/recordings/browsers/keys_client__create_read_update_and_delete_operations_for_managed_hsm_getrandombytes/recording_returns_an_error_when_bytes_is_out_of_range.json
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations/recording_cannot_create_a_key_with_an_empty_name.js
sdk/keyvault/keyvault-keys/recordings/node/keys_client__create_read_update_and_delete_operations_for_managed_hsm_getrandombytes/recording_returns_an_error_when_bytes_is_out_of_range.js
sdk/keyvault/keyvault-keys/test/public/keyClient.spec.ts
sdk/keyvault/keyvault-secrets/recordings/browsers/secret_client__create_read_update_and_delete_operations/recording_cannot_create_a_secret_with_an_empty_name.json
sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_cannot_create_a_secret_with_an_empty_name.js
sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts

- Fixes #22087
Removes error message check that relies on now-removed constraint validation.

[Key Vault] Fix tests that rely on now-removed constraint validation

---

sdk/schemaregistry/schema-registry-avro/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/22117

[Schema Registry Avro] Fix warning

---

sdk/core/core-amqp/test/requestResponse.spec.ts

The explicit parameter type was added in PR #21892 to resolve a compiler error.
It has been working for a while, but now broken due to @types/node fix in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60591
This PR updates the parameter type to use `any` as we don't care about the parameter type in this test and it will not be affected by future type changes

[core-amqp][test] fix build error in rush update --full

---

common/config/rush/pnpm-lock.yaml
sdk/deviceupdate/iot-device-update-rest/package.json
sdk/digitaltwins/dtdl-parser/package.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json

These three packages likely missed the bulk upgrade because they were still in
open PRs.

[engsys] upgrade dev dependency `nyc` version to ^15.0.0

---

sdk/servicebus/perf-tests/service-bus/test/subscribe.spec.ts
sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/log.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/src/serviceBusRuleManager.ts
sdk/servicebus/service-bus/test/public/ruleManager.spec.ts
sdk/servicebus/service-bus/test/public/utils/managementUtils.ts

@Azure/service-bus 
This existed in Track 1 and allowed users with only Listen claims to manage rules on the subscription that they had listen claims for. In Track 2, this can be done using the `ServiceBusAdministrationClient`, but Get Rules and List Rules require Manage claims.
This PR adds a rule manager that can add, delete, and retrieve rules for a specified subscription via AMQP link.
#20890

[ServiceBus] add subscription-level rule manager.

---

sdk/textanalytics/ai-text-analytics/src/lro.ts
sdk/textanalytics/ai-text-analytics/src/textAnalysisClient.ts
sdk/textanalytics/ai-text-analytics/src/transforms.ts

Use a `throwError` helper everywhere which in turn transforms the caught error before throwing it again.

[Text Analytics] Simplifying error handling

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

Upgrade the following dependencies to version `~5.27.0`
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- @typescript-eslint/typescript-estree
- @typescript-eslint/experimental-utils

[engsys][eslint-plugin] upgrade dependency `@typescript-eslint/*` to ~5.27.0

---

sdk/servicebus/service-bus/test/public/amqpAnnotatedMessage.spec.ts

This RP rewrites the assertion with excluded properties with assertion on
expected properties. as log of `deepEqualExcluding()` doesn't give enough
information on the difference when the assertion fails.
#22047

[servicebus][test] assert on expected properties

---

sdk/servicebus/service-bus/src/serviceBusRuleManager.ts
sdk/servicebus/service-bus/test/public/ruleManager.spec.ts

Testing reveals that if we use max int as maxCount, and also use top then
service will return InternalServerError.
This PR workarounds around that by defaulting to 100 as maxPageSize.

[ServiceBus] workaround a service issue by using page size of 100

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/utils/utils.ts
sdk/test-utils/recorder/test/testProxyClient.spec.ts

- `@azure/test-recorder`
- Fixes #22012 
The `TEST_MODE` environment variable was previously case sensitive, leading to confusing results when setting it to a value with any upper-case characters (e.g., `TEST_MODE=Live` would result in running tests in playback mode). This change makes `TEST_MODE` case-insensitive.
Yes

[Recorder] Make TEST_MODE environment variable value case-insensitive

---

common/tools/dev-tool/src/util/testProxyUtils.ts
common/tools/dev-tool/src/util/testUtils.ts
sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/testing-recorder-new/karma.conf.js

`@azure-tools/test-recorder` and all the SDKs/tests/users
#22059 
If the 5000 port is blocked on a client machine, they won't be able to use the recorder and dev-tool commands directly to run the test-proxy tool.
Means, that the test-proxy tool needs to be run at a different port, but the `test-recorder` expects the tool runs at 5000.
Adds a new environment variable `TEST_PROXY_HTTP_PORT` which will be used for both mapping the test-proxy instance to localhost and in the recorder code to avoid using the hardcoded 5000 port.
Defaults to 5000 if `TEST_PROXY_HTTP_PORT` isn't defined.

[Recorder] TEST_PROXY_{HTTP|HTTPS}_PORT

---

sdk/monitor/monitor-query/package.json
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/logsQueryClient.ts
sdk/monitor/monitor-query/src/metricsQueryClient.ts
sdk/monitor/monitor-query/src/models/publicMetricsModels.ts
sdk/monitor/monitor-query/src/tracing.ts
sdk/monitor/monitor-query/test/internal/unit/logsQueryClient.unittest.spec.ts
sdk/monitor/monitor-query/test/internal/unit/metricsQueryClient.unittest.spec.ts
sdk/monitor/monitor-query/test/internal/unit/modelConverters.unittest.spec.ts
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/metricsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/shared/testShared.ts

Fixes #21245 
Upgrading tracing to 1.0.0 for monitor query and setting up tracing for monitor query APIs.

[Monitor Query] move to tracing 1.0.0

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/serviceBusRuleManager.ts
sdk/servicebus/service-bus/test/public/ruleManager.spec.ts

We should stop when there's no more returned rules. I did this previously
probably to support continuationToken as we have to make the last request to
know that there are no more results, and we then set continuationToken to
undefined on this empty page.  Now that the continuationToken is removed, we can
stop yielding empty page.
@azure/service-bus

[ServiceBus] don't yield empty page when listing rules in RuleManager

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts

https://github.com/Azure/azure-sdk-for-js/issues/21726
On macOS, the default browser held open the connection, and refused to close the associated sockets unless the window was closed. The workaround with the setting ` newInstance` forces a spawn of a new browser instance, not causing the application to hang or the socket to not close.
**Note : This issue happens in Linux too and is not fixed by the PR. [Filed an issue ](https://github.com/sindresorhus/open/issues/287) on the `open` dependency for linux**
PR by @mpodwysocki - https://github.com/Azure/azure-sdk-for-js/pull/22195

[Identity] Fixes to spawn a new instance on macOS

---

common/tools/dev-tool/src/config/rollup.base.config.ts

in addition to `path.sep` as on Windows in PowerShell, even though
`path.sep` is `"\\"`, the rollup warnings are still using `"/"`.

[dev-tool] also check for rollup warning match using "/"

---

sdk/storage/storage-blob-changefeed/CHANGELOG.md
sdk/storage/storage-blob-changefeed/review/storage-blob-changefeed.api.md
sdk/storage/storage-blob-changefeed/src/BlobChangeFeedClient.ts
sdk/storage/storage-blob-changefeed/src/ChangeFeedFactory.ts
sdk/storage/storage-blob-changefeed/src/ChunkFactory.ts
sdk/storage/storage-blob-changefeed/test/changefeed.spec.ts

- Change to return empty change feed when meta/segments.json is not created
- Add ability to set Change Feed chunk download size
@azure/storage-blob-changefeed
- Change to return empty change feed when meta/segments.json is not created
- Add ability to set Change Feed chunk download size

Added two new features for change feed package.

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-rest-pipeline/package.json

The breaking change is now TypeScript version v4 is required so it doesn't affect us as we've been using v4 for quite a while.
Resolves #19222

[engsys] upgrade dependency `http-proxy-agent` to ^5.0.0

---

sdk/keyvault/keyvault-admin/src/accessControlClient.ts
sdk/keyvault/keyvault-admin/src/backupClient.ts
sdk/keyvault/keyvault-admin/src/challengeAuthenticationCallbacks.ts
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/test/internal/challengeAuthenticationCallbacks.spec.ts

- Fixes #22028
Currently keyvault-admin falls back to a hard-coded scope when making subsequent requests after the challenge-based authentication flow has been completed. This causes issues when the scope conflicts with the scope returned by the `WWW-Authenticate` header in the challenge. Hard-coding the scope means that the SDK can't be used in other clouds (e.g., as pointed out by the service team, Dogfood having a scope of `https://managedhsm-int.azure-int.net`).
This PR updates the logic so that the scope from the original `WWW-Authenticate` response is used on subsequent requests instead of the hard-coded value.
This is tricky to test. There's some validation in the fact that the existing tests continue to pass with these changes. Might be worth adding a …

[KeyVault] keyvault-admin - Don't hard code request scope

---

sdk/keyvault/test-resources-post.ps1

- Key Vault packages
- #22074 
Add some more options to `Export-AzKeyVaultSecurityDomain` to make sure that exceptions are logged as they should be.
When making the changes in #22093 I forgot to copy over the changes in the actual command, so we weren't getting the verbose error logging like we should have :(. This fixes that issue.
- Follows up #22093

[KeyVault] Fix HSM security domain download logging

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/samples-dev/healthcare.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/lro.ts
sdk/textanalytics/ai-text-analytics/src/models.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md
sdk/textanalytics/ai-text-analytics/test/public/analyzeBatch.spec.ts

Simplifies the property name based on feedback that "last" is redundant.

[Text Analytics] Rename lastModifiedOn to modifiedOn

---

eng/tools/analyze-deps/package-lock.json
eng/tools/analyze-deps/package.json
eng/tools/dependency-testing/package.json
eng/tools/eng-package-utils/package.json
eng/tools/versioning/package.json

To avoid squatters in the global registry, let's keep these packages namespaced under @azure-tools. Nothing imports them by name though, so I don't think we have to update anywhere else.

[engsys] Namespace internal package names for eng tooling

---

eng/tools/dependency-testing/index.js
eng/tools/versioning/VersionUtils.js
eng/tools/versioning/increment.js
eng/tools/versioning/set-dev.js
eng/tools/versioning/set-version.js

It's found in pipeline error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1658487&view=logs&j=e594813e-738e-5b20-1335-c7b2b68ed8dd&t=4c0c4aec-211a-5ded-3c08-c4e487a21e87
It's caused by the package name change in https://github.com/Azure/azure-sdk-for-js/pull/22319
This PR also changes the one in tools/dependency-testing

fix dependency error in tools/versioning

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/models.ts

Fixes #22301
User(s) were confused about the  `maxAutoLockRenewalDurationInMs` option, partly owing to the naming and arguably incomplete documentation.
Adds an example to the JS docs, to clear any confusions the users may have.

[Service Bus] Improves documentation for `maxAutoLockRenewalDurationInMs`

---

sdk/monitor/monitor-query/src/tracing.ts

This is a holdover from when we used `createTracingFunction`. Now that this package is using TracingClient, the comment should reflect that.

[monitor-query] Update tracing.ts comment

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

- `@azure/eslint-plugin-azure-sdk`
- Fixes #22304 
- Fixes #22305
- Fixes #22306
- Fixes #22307
Upgrades the following packages to ~5.29.0 (from ~5.27.0):
- `@typescript-eslint/eslint-plugin`
- `@typescript-eslint/experimental-utils`
- `@typescript-eslint/parser`
- `@typescript-eslint/typescript-estree`

[engsys][eslint-plugin] Upgrade `@typescript-eslint/*` to ~5.29.0

---

sdk/core/core-lro/test/engine.spec.ts
sdk/core/core-lro/test/utils/router.ts
sdk/core/core-lro/test/utils/utils.ts

From the tests point of view, the path of the initial request is inconsequential and could be anything. I updated the path property to be optional in `LroResponseSpec` and the implementation defaults it to "path". This simplifies the tests a bit because `path` now doesn't have to be specified in the first item in the routes list.

[core-lro] Update tests to be less verbose

---

sdk/identity/identity/test/msalTestUtils.ts

None on this  repo but fixes - https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4942
- Live tests fail on @azure/identity with this error -
`CredentialUnavailableError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.`
Upon investigation, it was found that this error was being caused by an overriding of the configure client options function added for the recorder in the Identity tests. Earlier this workaround was needed because the recorder's implementation of this function was not available, but now this is available and …

[Identity] Remove the workaround for configure client options to fix the live tests

---

sdk/keyvault/keyvault-admin/recordings/node/keyvaultbackupclient_beginbackup/recording_throws_when_polling_errors.js
sdk/keyvault/keyvault-admin/recordings/node/keyvaultbackupclient_beginrestore/recording_throws_when_polling_errors.js
sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts

- Fixes #22313
We're seeing some different behavior from the service causing it to fail sooner than previously when a bad SAS token is passed in two error-handling tests. This PR updates the tests so that they align with the new behavior.

[KeyVault] Fix keyvault-admin live tests

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

- `@azure/eslint-plugin-azure-sdk`
- Fixes #22428  
- Fixes #22429 
- Fixes #22430
- Fixes #22431
Upgrades the following packages to ~5.30.0 (from ~5.29.0):
- `@typescript-eslint/eslint-plugin`
- `@typescript-eslint/experimental-utils`
- `@typescript-eslint/parser`
- `@typescript-eslint/typescript-estree`

[engsys] Upgrade dependency @typescript-eslint/* to ~5.30.0

---

sdk/monitor/monitor-opentelemetry-exporter/samples-dev/httpSample.ts

[Azure Monitor Exporter] Add unref to avoid server to block samples execution

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serviceBusRuleManager.ts
sdk/servicebus/service-bus/test/public/ruleManager.spec.ts

so it won't be awkward when passing in operation options, but not sql rule action.
@azure/service-bus

Add an `createRule` overload that doesn't take `ruleAction`

---

common/smoke-test/Initialize-SmokeTests.ps1

`@azure/msal-node` is not managed in this repo, so we should keep the version
specified in package.json.

[smoke-tests] skip overriding version for dependency not managed in this repo

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

The service now supports the "channel name" feature added in
4.10.0-beta.1 and this release adds support in a GA package.
There are no changes in the implementation from 4.10.0-beta.1

[EventGrid] Prepare EventGrid 4.10.0 release

---

sdk/core/core-auth/CHANGELOG.md
sdk/core/core-auth/package.json
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json

for the added `claims` option
Also update changelog release dates as the two packages haven't been released

[core] bump core-auth version to 1.4.0

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/constants.ts
sdk/keyvault/keyvault-certificates/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-certificates/swagger/README.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/constants.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/constants.ts
sdk/keyvault/keyvault-secrets/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-secrets/swagger/README.md

- Keyvault keys, certificates and secrets
- The post-release script that generates the post-release changes PR failed for these packages when I released the beta last week
- This was because the `package.json` metadata wasn't updated to point to the core v2 generated client.
- This PR:
- Updates the `package.json` metadata so that this build step won't fail again.
- Adds the changes that the automation would have added manually.

[KeyVault] Fix post-release changes for keyvault corev2 releases

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/constructorHelpers.ts
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/core/shared.ts
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/internal/retries.spec.ts
sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts
sdk/servicebus/service-bus/test/internal/unit/batchingReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/unit/linkentity.unittest.spec.ts
sdk/servicebus/service-bus/test/internal/unit/messageSender.spec.ts
sdk/servicebus/service-bus/test/internal/unit/messageSession.spec.ts
sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts
sdk/servicebus/service-bus/test/internal/unit/sender.spec.ts
sdk/servicebus/service-bus/test/internal/unit/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/internal/unit/serviceBusReceiverUnitTests.spec.ts
sdk/servicebus/service-bus/test/internal/unit/unittestUtils.ts

Its main purpose is to help correlate client logs and errors. It can be specified when creating instances of `ServiceBusClient` via optional `ServiceBusClientOptions.identifier`. If not specified, a unique one will be generated.
#21902
When creating one of the Service Bus client types, it can be useful for a host application to be able to uniquely identify the client instance. The Service Bus service also supports setting the identifier of an AMQP link, which it will associate with some error messages to make it easier to correlate errors with a given client instance.

[ServiceBus] Add `identifier` property to `ServiceBusClient`

---

sdk/core/core-client/package.json

for the new `claims` property `GetTokenOptions`.

[core-client] bump dependency `core-auth` version to `^1.4.0`

---

sdk/identity/identity/test/internal/node/clientAssertionCredential.spec.ts

None
This PR fixes the live internal test by fixing the name of the environment variable used by a test
Pipeline run - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1699943&view=results

[Identity] fix the certificate env var for internal live test

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1
eng/scripts/docs/Docs-ToC.ps1

This is the PR for service overview automation work.
It depends pre-requisite common PR: https://github.com/Azure/azure-sdk-tools/pull/3578/files
This is testing review site: 
https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/arm-confidentialledger-readme?view=azure-node-latest&branch=daily%2F2022-05-02-ci-succeeded
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1712881&view=results

Enable service level readme generation for daily docs.

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json

- ESLint plugin
- Fixes #22622
Updates package to `~3.0.0`. The sole breaking change is the package [dropping support for Node v8 and v10](https://github.com/eslint/eslint-plugin-markdown/releases/tag/v3.0.0), so should be safe.

[engsys] Update eslint-plugin-markdown to ~3.0.0

---

sdk/digitaltwins/digital-twins-core/CHANGELOG.md
sdk/digitaltwins/digital-twins-core/review/digital-twins-core.api.md
sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts

During the SDK review of 1.1.0, it was determined that the change fixing a typo in a function (decomissionModel) should be reverted, since it was deemed confusing to have both side by side.

[Microsoft.DigitalTwins] Revert fixing typo after SDK review

---

eng/scripts/docs/Docs-ToC.ps1

The review site is not correctly showing the right display. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1718787&view=results

Use the right var for package info

---

sdk/digitaltwins/digital-twins-core/package.json

@ azure/core-http
The package version needs to be downgraded since 2.2.6 is not publicly available as of yet.
In order to release SDK version, the core-http version needs to be downgraded.
N/A
N/A
N/A
N/A

Downgrade core-http version

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/lroEngine/impl.ts
sdk/core/core-lro/src/lroEngine/models.ts
sdk/core/core-lro/src/lroEngine/operation.ts
sdk/core/core-lro/test/engine.spec.ts

N/A
The lroEngine was logging raw responses without sanitization, a bad practice at best and a security vulnerability at worst.
The customer should rely on core-client logging for information about the responses so the operation and polling statuses are logged instead of raw responses. See a sample of the cleaned-up log in [log.txt](https://github.com/Azure/azure-sdk-for-js/files/9127914/log.txt)
N/A
N/A

[core-lro] Clean-up logging

---

sdk/communication/communication-common/package.json
sdk/communication/communication-common/src/credential/communicationAccessKeyCredentialPolicy.ts
sdk/communication/communication-common/src/credential/isNode.browser.ts
sdk/communication/communication-common/src/credential/isNode.ts
sdk/communication/communication-common/test/communicationKeyCredentialPolicy.spec.ts
sdk/communication/communication-common/test/communicationTokenCredential.spec.ts

- @azure/communication-common
- https://skype.visualstudio.com/SPOOL/_workitems/edit/2762212
- Addressing technical debt
- We planned to remove the local copy of isNode once a stable version of @azure/core-util is released
- The local copy was created during the migration to Azure Core v2 ([here](https://github.com/Azure/autorest.typescript/wiki/%60core-http%60-dependency-migration-to-%60core-client%60-%60core-rest-pipeline%60#other-changes-to-consider-when-migrating-to-core-v2))
- https://github.com/Azure/azure-sdk-for-js/pull/21352

@azure/communication-common - remove a local copy of isNode

---

sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/test/identifierModelSerializer.spec.ts

communication-common and its downstream dependencies
Needed to be able to handle the new stable version of `CommunicationIdentifierModel`, see swagger: https://github.com/Azure/azure-rest-api-specs/pull/19675
This PR aligns the logic with C# and Java and checks that at most one of the known properties is part of the payload. Alternatively, the existing JS pattern could have been altered to exclude `kind` from the check. But handling new additional properties without failure seemed better than risking not to throw when encountering a malformed service response.
Yes.
https://github.com/Azure/azure-rest-api-specs/pull/19675

[communication-common] Handle unknown additional properties when deserializing identifier REST model

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/samples-dev/sendMessages.ts
sdk/servicebus/service-bus/samples/v7/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/v7/typescript/src/sendMessages.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/internal/unit/amqpUnitTests.spec.ts

when the `ServiceBusMessage` has `timeToLive` property set.
The problem is that we are adding a number to a `Date` object, resulting in an
invalid date value for `absolute_expiry_time`. This PR corrects it by calling
`getTime()` on the `Date` object first before adding the ttl number.
A unit test is added and the sendMessages sample is updated to show how to set
`timeToLive`.

[ServiceBus] Fix bug in converting ServiceBusMessage to RheaMessage

---

common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/javascript/package.json
sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/typescript/package.json

- monitor opentelemetry exporter
- #22531
- #22530
- #22529
Updates to @opentelemetry/sdk-metrics-base and associated packages from 0.29.2 to 0.30.0
N/A
N/A

[monitor opentelemery exporter] update dependencies

---

sdk/core/core-client/package.json

This is to ensure that core-client and core-rest-pipeline are using core-auth
1.4.0 or later for the new `GetTokenOptions.claims` property.

[core-client] Increment core-rest-pipeline version to `^1.9.1`

---

sdk/tables/data-tables/recordings/browsers/batch_operations/recording_should_send_a_set_of_update_batch_operations_with_options.json
sdk/tables/data-tables/recordings/node/batch_operations/recording_should_send_a_set_of_update_batch_operations_with_options.json
sdk/tables/data-tables/review/data-tables.api.md
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/src/models.ts
sdk/tables/data-tables/test/public/transaction.spec.ts

Currently, you cannot submit an ifMatch parameter when adding an updateEntity() command to a transaction like you can to the tableClient.updateEntity(). This PR adds the ability to pass an update option to transaction.updateEntity().
none
Adds the currently missing ability to call transaction.updateEntity() with update options so the submitTransaction() will send a ifMatch header for the update.
---
Yes
None

[Table] Add option to transaction.updateEntity() command

---

sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts

NA
The nightly build runs fail due to a previous change with the @azure/core-http dependency. In order to make it work, a test assertion needs to be modified.
The test assertion originally was modified to work against 2.2.6 version within the builds. However, 2.2.6 is an unreleased version that should not be specified with the package.json. Since the tests need to be compatible with <= 2.2.6, this change is to allow it work against all environments for the nightly build.
NA
NA
https://github.com/Azure/azure-sdk-for-js/pull/22644

Added test fix for nightly build run

---

sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/test/public/invalidParameters.spec.ts

We intended to call `peekBySequenceNumber()` when `PeekMessagesOptions.fromSequenceNumber` property is specified.  However, currently other falsey values would also fail the condition. This resulting in `peek()` is called instead, leading to unexpected behavior.
This PR changes the condition to check for `undefined`.

[ServiceBus] fix existence checking of `PeekMessagesOptions.fromSequenceNumber`

---

sdk/cognitivelanguage/ai-language-text/README.md

These links don't exist yet because the package wasn't released yet. Fixes https://github.com/Azure/azure-sdk-for-js/issues/22670

[Language Text] Remove links

---

sdk/test-utils/test-utils/src/xhrHttpClient.ts

Not sure why the change was fine in PR but now check-format failed.
This PR is the result of `npm run format`

[test-utils] run `format` npm script

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-network-traversal/package.json

to be consistent the version used in the repo
resolves #19239

[engsys] upgrade dev dep `rollup-plugin-visualizer` version to `^5.5.2`

---

eng/common/pipelines/templates/jobs/perf.yml
sdk/test-utils/perf/src/managerProgram.ts
sdk/test-utils/perf/src/utils.ts

```
Completed 7,421 operations in a weighted-average of 5.00s (1,482.92 ops/s, 0.001 s/op)
```
| Test       | Arguments                                                | 12.11.0 | source  | %Change |
|------------|----------------------------------------------------------|---------|---------|---------|
| download   | --size 10240 --parallel 64                               | 1991.58 | 1911.60 | -4.02%  |
| download   | --size 10485760 --parallel 32                            | 144.92  | 145.36  | 0.30%   |
| download   | --size 10485760 --parallel 32 --sync                     | -1.00   | -1.00   | 0.00%   |
| download   | --size 1073741824 --parallel 1 --warmup 60 --duration 60 | 0.17    | 0.18    | 5.88%   |
| download   | --size 1073741824 --parallel 8 --warmup 60 --duration 60 | 1.24 …

[Perf] Display results with 4 significant figures

---

sdk/apimanagement/ci.yml

It is not necessary and adds time/failures to eng/common sync changes

Remove api management ci from running on eng/common changes

---

sdk/core/core-amqp/package.json
sdk/core/core-amqp/test/tokenProvider.spec.ts

These two tests compare two expiry values from two consecutive Date.now()
calls (the first in the test and the second in the library code) and expect them
to be equal:
Math.floor(Date.now() / 1000) + 3600
However, it happens that the elapsed time between the two Date.now() call
sometimes can fail the expectation.
> AssertionError: expected 1659139755 to equal 1659139754
This PR change the verification to allow max of 2 milliseconds delta between the
two timestamps.
While at this I also updated the nyc reporters to more useful ones. Previous
ones just print out lines of data that not meant to be human-understandable.

[core-amqp][test] fix test issue comparing two timestamps

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/models.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts
sdk/servicebus/service-bus/test/internal/unit/batchingReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/unit/linkentity.unittest.spec.ts
sdk/servicebus/service-bus/test/internal/unit/messageSession.spec.ts
sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts
sdk/servicebus/service-bus/test/internal/unit/receiverCommon.spec.ts
sdk/servicebus/service-bus/test/internal/unit/sender.spec.ts
sdk/servicebus/service-bus/test/internal/unit/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/internal/unit/serviceBusReceiverUnitTests.spec.ts
sdk/servicebus/service-bus/test/internal/unit/streamingReceiver.spec.ts

- add public `identifier` property to senders, receivers, and their corresponding options
- `ProcessErrorArgs` now has `identifier` indicating by which client the error is raised.
#21902

[ServiceBus] add `identifer` property to more types and options

---

sdk/cosmosdb/cosmos/src/client/Item/Item.ts
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/src/common/helper.ts

@azure/cosmos
n/a
With recent changes creating databases and containers with special characters in id wasn't blocked by the SDK anymore - this caused issues because databases created couldn't be deleted afterwards via SDK anymore.
This PR just adds back the id character validation for any resource but items. Fixing why the SDK can't delete these resources will be added in subsequent PR.
n/a
No - existing test failed.
n/a
n/a

Fixing issues for containers and databases with ids with white spaces or special characters

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/CHANGELOG.md
sdk/identity/identity-cache-persistence/package.json

This removes a transitive dependency on github.com/samuelkubai/node-bindings from the repo.
An NPM bug (https://github.com/npm/cli/issues/4896) causes github package references to hang on Linux hosts because it attempts to use the unsupported git protocol.
This causes a two minute delay when running rush update from linux hosts, including our pipeline agents. Furthermore, github-based dependencies are altogether risky, since they can naturally subvert versioning constraints, so we will be blocked from upgrading msal-node-extensions until we can upgrade to a version that does not have this behavior.
Fortunately, we never shipped a dependency on msal-node-extensions 13, so this downgrade shouldn't require a release.
CC @mikeharder @xirzec

[identity] Partially revert #19356

---

sdk/notificationhubs/ci.yml
sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json

- `@azure/core-amqp` was being used for version `3.1.1` which was not yet published. Downgraded to `3.1.0`

[notification hubs] Fixing AMQP version used by Notification Hubs

---

eng/pipelines/templates/steps/cosmos-integration-public.yml
sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/client/Item/Item.ts
sdk/cosmosdb/cosmos/src/common/helper.ts
sdk/cosmosdb/cosmos/src/common/uriFactory.ts
sdk/cosmosdb/cosmos/src/utils/headers.ts
sdk/cosmosdb/cosmos/test/public/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/public/functional/itemIdEncoding.spec.ts

@azure/cosmos
[ICM#315831633](https://portal.microsofticm.com/imp/v3/incidents/details/315831633/home)
PR https://github.com/Azure/azure-sdk-for-js/pull/22548 - https://github.com/Azure/azure-sdk-for-js/pull/22548 changed the encoding of special characters in the documentId to make sure it work with RoutingGateway - it turned out that ComputeGateway and RoutingGateway expect different encoding (RoutingGateway expects id in the Uri to be double-percent-encoded - while Compute expects it to be only single percent-encoded. Aftersome discussion we decided that ComputeGateway behavior is actually correct - and making sure SDK works weel even when id has special characters in ComputeGateway means there are no regressions for customers on RoutingGateway (same failures as before …

Fixing id encoding issues when using special characters for custome already on ComputeGateway

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/samples-dev/prebuilt/prebuilt-vaccinationCard.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analysis.ts

This PR makes a few laundry-list changes to prepare for the release of `4.0.0-beta.6`.
- Fixes a small bug causing DocumentLine#polygon instances to miss the transformation from `number[]` to `Point2D[]`
- Rewrites several sections of the README:
- Rework `beginAnalyzeDocument` section
- Replaces references to `PrebuiltModels`, which has been removed, with references to prebuilt DocumentModel samples
- Replace references to FOTT with references to FR Studio
- Remove references to removed `beginExtract` methods, replacing them with prebuilt DocumentModel samples
- Correct header casing
- Correct some references to methods that were renamed
- Sets the CHANGELOG release date.
- Corrects an error in the docType of the vaccinationCard sample DocumentModel.
Closes #22840

[ai-form-recognizer] Prepare 4.0.0 beta.6 release

---

sdk/automanage/arm-automanage/README.md

None
None
Add examples that display how to use the new Automanage Javascript package.
I could have separated this into its own examples file, however, this seemed to be the best approach due to the README being the first thing customers are exposed to. 
No. Only a readme file is being updated.
N/A

Add examples to readme

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/policies/deserializationPolicy.ts
sdk/core/core-http/test/policies/deserializationPolicyTests.ts

@azure/core-http and its dependents
Fixes #22881
node-fetch forces a lowercase normalization of header names coming over the wire, but storage has scenarios where this is undesirable (see #8117).
Until we get storage moved over to the new pipeline, we would like advanced consumers to be able to preserve header casing via a custom `HttpClient`.
This PR addresses the issue by ensuring we pass the normalized (rather than the original) header casing to the deserialization policy which always hardcodes the lowercase version of the name.
Yes! Two new cases, one for normal responses and one for error responses.

[core-http] Add support for headers having original casing during deserialization.

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/README.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchAudience.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/src/serviceUtils.ts

`@azure/search-documents`
https://github.com/Azure/azure-sdk-for-js/issues/22813
This PR is to enable national cloud support for Azure Search Documents. This PR uses the .NET PR - https://github.com/Azure/azure-sdk-for-net/pull/30316 as reference.
This is a standard straight forward implementation. No specific design concerns.
https://github.com/Azure/azure-sdk-for-net/pull/30316

[@azure/search-documents] Enable national cloud support for Azure Search SDK

---

sdk/keyvault/keyvault-certificates/package.json

This PR bumps dev dependency on `@azure/keyvault-secrets` to `^4.5.0` (the minimum version with Core v2 support) to fix the minmax tests.

[KeyVault] Fix minmax tests for keyvault-certificates

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/src/utils/utils.node.ts

@azure/storage-blob
@azure/storage-file-share
Fix a hang issue in downloading when there's transient network issue

Fix a hang issue in downloading when there's transient network issue

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_setpermissions.js
sdk/storage/storage-file-datalake/src/transforms.ts
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/transforms.spec.ts

@azure/storage-file-datalake
For pathClient.setPermission interface, following is doc for permission string format:
```
Optional and only valid if Hierarchical Namespace is enabled for the account. Sets POSIX access permissions for the file owner, the file owning group, and others. Each class may be granted read(4), write(2), or execute(1) permission. Both symbolic (rwxrw-rw-) and 4-digit octal notation (e.g. 0766) are supported. 
The sticky bit is also supported and in symbolic notation, its represented either by the letter t or T in the final character-place depending on whether the execution bit for the others category is set or unset respectively (e.g. rwxrw-rw- with sticky bit is represented as rwxrw-rwT. A rwxrw-rwx with sticky bit is represented as rwxrw-rwt), absence of t or T …
```

Fix failures in passing or converting permissions

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/src/utils/utils.common.ts

@azure/storage-blob
@azure/storage-file-share
@azure/storage-file-datalake
@azure/storage-queue

[storage]Fix issue of not be able to parse URL with account name in Path correctly

---

dataplane.code-workspace
sdk/core/core-http-compat/review/core-http-compat.api.md
sdk/core/core-http-compat/src/extendedClient.ts
sdk/core/core-http-compat/src/index.ts
sdk/core/core-http-compat/src/policies/disableKeepAlivePolicy.ts
sdk/core/core-http-compat/src/policies/requestPolicyFactoryPolicy.ts
sdk/core/core-http-compat/src/response.ts
sdk/core/core-http-compat/src/util.ts
sdk/core/core-http-compat/test/extendedClient.spec.ts
sdk/core/core-http-compat/test/requestPolicyFactoryPolicy.spec.ts
sdk/core/core-http-compat/test/testPolicies.ts

New compat behavior requested by storage team:
- A corev2 policy that can wrap core-http style policies and insert them into the pipeline.
This will allow Storage to keep using their `PipelineLike` interface without breaking changes by allowing old-style http policies to participate in corev2 pipelines.

[core-http-compat] Policy factory compat

---

sdk/communication/communication-short-codes/CHANGELOG.md
sdk/communication/communication-short-codes/package.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
sdk/communication/communication-short-codes/recordings/node/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
sdk/communication/communication-short-codes/src/generated/src/models/parameters.ts
sdk/communication/communication-short-codes/src/generated/src/shortCodesClient.ts
sdk/communication/communication-short-codes/src/generated/src/tracing.ts
sdk/communication/communication-short-codes/src/utils/constants.ts
sdk/communication/communication-short-codes/swagger/README.md
sdk/communication/communication-short-codes/swagger/shortcodes.json
sdk/communication/communication-short-codes/test/public/utils/recordedClient.ts
sdk/communication/communication-short-codes/test/public/utils/testProgramBriefAttachment.ts
sdk/communication/communication-short-codes/test/public/utils/testUSProgramBrief.ts

--
**NOTE: This is a private SDK intended for internal use only. This SDK will not be officially supported**
We're updating the version of the API, alongside with minor updates in the swagger file. This also removes the unnecessary beta 5 version, as the beta 4 was never released and the version was mistakenly bumped. Finally, we're also updating the version for the `communication-commons` dependency, assuring that this package is up to date.
--
No. Only metadata was changed.
--

Use API GA version and reuse unreleased beta 4

---

sdk/remoterendering/mixed-reality-remote-rendering/test/public/remoteRenderingClient.spec.ts

Temporarily remove the wrong input test. A real fix will be added soon.

---

sdk/core/core-rest-pipeline/src/pipeline.ts
sdk/core/core-rest-pipeline/test/pipeline.spec.ts

Policies using 'afterPhase' would get executed later than expected due to `noPhase` not getting run again until the full phase walk finished.
Yes

[core-rest-pipeline] Fix issue with afterPhase policies getting run later than expected

---

sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts

- `@azure/event-hubs`
- `@azure/service-bus`
- Fixes #22897
`@types/long` is a stub type package. The `long` package provides its own type definitions, so the dependency on the type definitions package is unnecessary. This PR removes the unnecessary dependency.

[Event Hubs, Service Bus] Remove unnecessary dependency on `@types/long`

---

common/config/rush/pnpm-lock.yaml
sdk/apimanagement/api-management-custom-widgets-tools/package.json

- `@azure/api-managemnet-custom-widgets-tools`
- Fixes #22843 
Upgrades type definitions (`@types/mime`) to `^3.0.1` to match major version with the actual `mime` dependency.

[engsys] Upgrade @types/mime to ^3.0.1

---

sdk/apimanagement/api-management-custom-widgets-tools/package.json

- `@azure/api-management-custom-widgets-tools`
- Fixes #22842 
Removes type definition dependency that is unused (there's no corresponding dependency on the actual `inquirer` package and no references to the types in the code.

[engsys] Remove unused `@types/inquirer` dependency from api-management-custom-widgets-tools

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/request/SharedOptions.ts
sdk/cosmosdb/cosmos/src/request/request.ts
sdk/cosmosdb/cosmos/test/internal/session.spec.ts

Describe the bug https://github.com/Azure/azure-sdk-for-js/issues/22765
Setting maxIntegratedCacheStalenessInMs doesn't set the staleness to 0 and instead it appears to fall back to the default cache staleness of 5 minutes.
Issue
To Reproduce
Steps to reproduce the behavior:
The first request should cost X RUs and the second request should also cost X RUs, indicating that request 1 wasn't cached due to staleness being set to 0. The same behavior should apply to the options for container.items.query()
const requestOptions = {
maxIntegratedCacheStalenessInMs: 0, };
const { resource: readDoc, requestCharge: charge } = await container.item("1", "1").read(requestOptions);
console.log(Reading item: + readDoc.id + RUs: + charge);
const { resource: readDoc2, requestCharge: charge2 } = await …

max integrated cache staleness in Ms zero check fix

---

.github/CODEOWNERS
sdk/monitor/monitor-opentelemetry-exporter/review/monitor-opentelemetry-exporter.api.md
sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/metric.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/assert.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts

Added metric attributes
Create an envelope per metric data point

[Azure Monitor Exporter] Export Metric attributes

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/common/constants.ts

- GA: Support DedicatedGatewayRequestOptions and MaxIntegratedCacheStaleness [#21240](https://github.com/Azure/azure-sdk-for-js/pull/21240)
- Add indexing metrics populateQueryMetrics sample [#21799](https://github.com/Azure/azure-sdk-for-js/pull/21799)
- Upgrade cosmos with azure core tracing [#22284](https://github.com/Azure/azure-sdk-for-js/pull/22284)
- Removed old logging and implement Azure core logging coverage [#18723](https://github.com/Azure/azure-sdk-for-js/pull/18723?)
- ParallelQueryExecutionContextBase breaks use of abortSignal [#18544](https://github.com/Azure/azure-sdk-for-js/pull/18544)
- Fixes id encoding issues when using special characters fo RoutingGateway

cosmos release 3.17.0

---

eng/pipelines/templates/stages/archetype-js-release.yml

This is not necessary and is causing us to do a full checkout unnecessarily.

Don't skip checkout exclusion in release config

---

common/config/rush/pnpm-lock.yaml
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json

- [opentelemetry-instrumentation-azure-sdk]
- #22955
Updates the OpenAPI dependencies to fix the unmet peer dependency issue.

[opentelemetry] Update @azure/opentelemetry-instrumentation-azure-sdk OpenAPI dependencies

---

.github/CODEOWNERS

N/A
N/A
Updating code owners from the Cosmos DB team
N/A
N/A
N/A

update code owners for Cosmos SDK

---

sdk/identity/identity/.nycrc

The dev-tool runs nyc for integration tests. However, without proper reporter
configurations, desired code coverage reports are not generated.
This PR adds the .nycrc file that is copied from the template project thus
enables code coverage report generation.

[engsys][identity] enable code coverage result generation

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/utils/sessionFilePath.ts

- Fixes #22800 
For recorded browser tests to work, the `RECORDINGS_RELATIVE_PATH` environment variable needs to be set programmatically in the Karma configuration (as detailed in the [recorder migration guide]). The recorder does not throw if the environment variable is not set, and instead uses `undefined`. This causes browser recordings to be saved in a directory named 'undefined' at the SDK root, which is both confusing and incorrect. This PR makes the recorder throw an error if `RECORDINGS_RELATIVE_PATH` is left undefined, making it easier for users to diagnose and resolve the issue.
[recorder migration guide]: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/test-utils/recorder/MIGRATION.md#browser-tests-and-modifications-to-karma-configuration

[recorder] Throw error if RECORDINGS_RELATIVE_PATH not set in browser

---

common/tools/dev-tool/src/commands/run/testNodeJSInput.ts
common/tools/dev-tool/src/commands/run/testNodeTSInput.ts

It appears that dev-tool doesn't receive the wrapping quotes around glob pattern on Linux/MacOS from the `process.argv` variable, which prevents Mocha from handle the pattern correctly.
This PR adds the quotes when the argument is a glob pattern that contains "**" so that expansion can be done by Mocha.

[dev-tool] ensure test file `**` glob pattern option is quoted

---

sdk/notificationhubs/notification-hubs/src/serializers/registrationSerializer.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/registrationSerializer.spec.ts

- #23089
Fixes an issue if there are no registration entries that an empty collection is returned.
This checks if the `feed.entry` list is undefined and returns an empty list if undefined.

[notification hubs] Fix empty registration feed bug

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/tables/data-tables/src/generated/generatedClientContext.ts
sdk/tables/data-tables/src/utils/tracing.ts
sdk/tables/data-tables/swagger/README.md

Preparing changelog for September release

Prepare Tables for September Release

---

sdk/servicebus/service-bus/CHANGELOG.md

[ServiceBus] prepare for 2022 September release

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/src/lro.ts
sdk/cognitivelanguage/ai-language-text/src/models.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

Rename `cancelOperation` to `sendCancellationRequest` after offline discussion with the JS architect.
EDIT: I created https://github.com/Azure/azure-sdk-for-js/issues/23138 to track whether to add a `cancelOperation` in the future.

[Language Text] Rename cancelOperation to sendCancellationRequest

---

sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/servicebus/service-bus/package.json

to ensure packages can get the `delay()` refactoring.
Without this change our `js - core` nightly is failing. It would fail the min-max testing as well.
What's happening is that our nightly pipeline does something special: for example, rewriting our @azure/core-util package versions to be like "1.1.1-alpha.20220909.2" so we can publish nightly alpha package of this version to npmjs.org.
If our other packages depend on the same minimum version (^1.1.1) then we also update the version to be ">=1.1.1-alpha <1.1.1-alphb" then rush would be able to find this version in the repository and we are building and testing against the version to be published.
However, if the version doesn't match (^1.1.0 in this case), we would not modify the dep version, and rush would get v1.1.0 from npmjs instead …

[engsys] update dep core-util version to `^1.1.1`

---

sdk/servicebus/service-bus/src/core/shared.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

This is ported from .NET PR https://github.com/Azure/azure-sdk-for-net/pull/30963
The service hardcodes a max of 1 minute and 5 seconds when accepting a session. This means the retry timeout the user specifies in the client is ignored if they specify a value higher than this. We should specify the timeout property in the link settings properties when opening a link for next available session to support long polling.
#23118

[ServiceBus] Pass timeout to server when accepting next session

---

eng/scripts/Create-ApiReview.ps1

Remove strict mode to unblock script failure in create api review step.

remove strict mode to unblock scheduled pipeline runs

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md
sdk/notificationhubs/notification-hubs/samples-dev/listRegistrations.ts
sdk/notificationhubs/notification-hubs/src/notificationHubsClient.ts
sdk/notificationhubs/notification-hubs/src/serializers/notificationHubJobSerializer.ts
sdk/notificationhubs/notification-hubs/src/serializers/registrationSerializer.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/notificationHubJobSerializer.spec.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/registrationSerializer.spec.ts

- #23222
- #23218 
- Fixes customer reported issue of `deleteRegistration` not being exported on the `NotifcationHubsServiceClient`.
- Fixes customer reported issue of a single item registration feed not being iterable.
Yes

[notification hubs] Prepare NH Beta 5

---

eng/pipelines/templates/steps/common.yml

macOS 11 and macOS 12 don't include Python 3.6 as a pre-installed Python version which is leading to macOS pipelines producing the warning "[warning]You should provide GitHub token if you want to download a python release. Otherwise you may hit the GitHub anonymous download limit."

Updating python 3.6 to 3.9

---

documentation/test-quickstart.md
sdk/communication/communication-job-router/README.md
sdk/eventhub/eventhubs-checkpointstore-table/README.md

Three instances missed previous PR in find-and-replace because of "en/" locale in the link.

[doc] fix nodejs lts broken link

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json
common/tools/dev-tool/src/util/samples/processor.ts
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/package.json
common/tools/dev-tool/test/samples/files/expectations/output-customization/typescript/package.json
common/tools/dev-tool/test/samples/files/expectations/simple/typescript/package.json
common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/package.json
common/tools/eslint-plugin-azure-sdk/package.json
common/tools/eslint-plugin-azure-sdk/src/rules/ts-use-interface-parameters.ts

- and react to the changes that decorators are now in the same field as modifiers
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees

[dev-tool] upgrade dev dependency `typescript` to `~4.8.0`

---

sdk/synapse/synapse-artifacts/CHANGELOG.md
sdk/synapse/synapse-artifacts/package.json
sdk/synapse/synapse-artifacts/review/synapse-artifacts.api.md
sdk/synapse/synapse-artifacts/src/artifactsClient.ts
sdk/synapse/synapse-artifacts/src/models/index.ts
sdk/synapse/synapse-artifacts/src/models/mappers.ts
sdk/synapse/synapse-artifacts/src/models/parameters.ts
sdk/synapse/synapse-artifacts/src/tracing.ts
sdk/synapse/synapse-artifacts/swagger/README.md

@azure/synapse-artifacts
refresh the @azure/synapse-artifacts library with latest swagger and codegen as service team's requirement

refresh-synapse-artifact-for-data-plane

---

sdk/communication/communication-alpha-ids/CHANGELOG.md
sdk/communication/communication-alpha-ids/package.json
sdk/communication/communication-alpha-ids/src/generated/src/alphaIDsClient.ts
sdk/communication/communication-alpha-ids/src/generated/src/tracing.ts
sdk/communication/communication-alpha-ids/src/utils/constants.ts
sdk/communication/communication-alpha-ids/swagger/README.md

- @azure-tools/communication-alpha-ids
--
**NOTE: This is a private SDK intended for internal use only. This SDK will not be officially supported**
This prepares the short codes SDK for the beta 1 release.
--
--
--

Prepare Alpha Ids package to Beta 1

---

sdk/search/search-documents/tests.yml

Recently the test resource deployment step for search live test pipeline can take more than 40 minutes to finish, while the integration test step only takes less than 10  minutes. We have contacted service team about deployment issue.
Still it is better to let the pipeline finish running than canceling the run after all these time spent on test resource deployment.

[engsys] increase search live test pipeline timeout to 90 minutes

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/http/models.ts
sdk/core/core-lro/src/http/operation.ts
sdk/core/core-lro/src/http/poller.ts
sdk/core/core-lro/src/legacy/lroEngine/operation.ts
sdk/core/core-lro/src/poller/models.ts
sdk/core/core-lro/src/poller/operation.ts
sdk/core/core-lro/test/lro.spec.ts
sdk/core/core-lro/test/utils/router.ts
sdk/core/core-lro/test/utils/utils.ts

Adds more smarts to core-lro to
- precisely detect when an operation failed without relying on raised exceptions thrown by the underlying core library when receiving non 2xx responses
- handle non-string status fields

[core-lro] Increase accuracy of termination detection and handle bad status field

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/pipeline.ts
sdk/core/core-rest-pipeline/test/pipeline.spec.ts

Reference re-use caused cloned pipelines to not be independent unless policies were first removed.
#23313
When cloning a Pipeline, we re-used the internal policy array. This bug wasn't caught by unit tests as we first removed a policy before adding them, which internally causes us to recreate the array.
We could also recreate the array when adding new policies, but this felt like overkill, so instead I chose to copy the array on construction.
Updated existing test to cover this problem.

[core-rest-pipeline] Fix bug in Pipeline.clone()

---

sdk/schemaregistry/schema-registry-avro/test/public/utils/mockedRegistryClient.ts
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/README.md
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/samples-dev/getSchemaByVersion.ts
sdk/schemaregistry/schema-registry/src/models.ts
sdk/schemaregistry/schema-registry/src/schemaRegistryClient.ts
sdk/schemaregistry/schema-registry/src/utils.ts
sdk/schemaregistry/schema-registry/test/public/schemaRegistry.spec.ts

Re-work the design for `getSchemaByVersion` to re-use `SchemaDescription` instead of creating a new input type.

[Schema Registry] Simplify getSchemaByVersion

---

documentation/credscan-process.md

- prefer suppressing fake secrets files over string values
- add notes about CredScan tool limitation on suppressing string values

[doc][credscan] update guideline on how to handle credscan errors

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json
sdk/core/core-lro/review/core-lro.api.md
sdk/core/core-lro/src/http/models.ts
sdk/core/core-lro/src/http/operation.ts
sdk/core/core-lro/src/http/poller.ts
sdk/core/core-lro/src/legacy/lroEngine/lroEngine.ts
sdk/core/core-lro/src/legacy/lroEngine/models.ts
sdk/core/core-lro/src/legacy/lroEngine/operation.ts
sdk/core/core-lro/src/legacy/poller.ts
sdk/core/core-lro/src/poller/models.ts
sdk/core/core-lro/src/poller/operation.ts
sdk/core/core-lro/src/poller/poller.ts
sdk/core/core-lro/test/lro.spec.ts
sdk/core/core-lro/test/utils/router.ts
sdk/core/core-lro/test/utils/utils.ts

Adds `resolveOnUnsuccessful` flag that controls whether to throw an error if the operation failed or was canceled. This flag is turned off by default but REST-level clients should turn it on to maintain the direction of not raising exceptions when receiving unexpected responses.

[core-lro] add a flag to control whether to throw when the operation is unsuccessful

---

sdk/core/core-lro/CHANGELOG.md

Release the addition of `resolveOnUnsuccessful` flag today.
[API View](https://apiview.dev/Assemblies/Review/df21e9c5d8714b978c0d09c47f2d5cbc?diffRevisionId=049a16a7322348abbc3b36b9b47d106b&doc=False&diffOnly=False&revisionId=e200c5415eb749afbabe14f7dfcad092)

[core-lro] Prepare release

---

.github/fabricbot.json

Updated bot rules to match CODEOWNERS change in #23415

[BOT RULES] Form Recognizer

---

sdk/monitor/monitor-ingestion/CHANGELOG.md
sdk/monitor/monitor-ingestion/README.md
sdk/monitor/monitor-ingestion/samples-dev/concurrency.ts
sdk/monitor/monitor-ingestion/samples-dev/logsIngestionClient.ts
sdk/monitor/monitor-ingestion/samples-dev/maxConcurrency.ts
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/README.md
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/concurrency.js
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/logsIngestionClient.js
sdk/monitor/monitor-ingestion/samples/v1-beta/javascript/maxConcurrency.js
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/README.md
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/package.json
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/src/concurrency.ts
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/src/logsIngestionClient.ts
sdk/monitor/monitor-ingestion/samples/v1-beta/typescript/src/maxConcurrency.ts
sdk/monitor/monitor-ingestion/src/logsIngestionClient.ts

- `@azure/monitor-ingestion`
The default concurrency value was discussed in the arch board review. After doing some perf analysis and a follow-up discussion with Jose, we settled on setting the concurrency to 5 by default (in line with .NET). This PR implements that plus adds a bit of documentation and a sample.

[monitor-ingestion] Change default concurrency to 5

---

sdk/test-utils/recorder/MIGRATION.md

Just adds some selling points to recorder v2.

[Recorder] Add advantages of migration

---

sdk/core/core-paging/CHANGELOG.md
sdk/core/core-paging/package.json
sdk/core/core-paging/review/core-paging.api.md
sdk/core/core-paging/src/getPagedAsyncIterator.ts
sdk/core/core-paging/src/models.ts
sdk/core/core-paging/test/getPagedAsyncIterator.spec.ts

core-paging
In many cases (app-configuration for example), the page is not a list of elements, and we need an iterator over elements.
Added an optional function `to-elements` to extract elements from a page
To be added
https://github.com/Azure/azure-sdk-for-js/pull/23333

[core-paging] add to-elements method

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_move_should_not_encode__in_the_source.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_move_with_destination_path_encoded.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_move_with_destination_path_not_encoded.js
sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_should_work_with_agentobjectid_preauthorizedagentobjectid.js
sdk/storage/storage-file-datalake/src/DataLakeFileSystemClient.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_get_directory_client_under_another_directory.json
sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_get_file_client_under_another_directory.json
sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_rename_to_under_a_different_directory.json
sdk/storage/storage-file-share/recordings/browsers/fileclient/recording_rename_to_under_a_different_directory.json
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_get_directory_client_under_another_directory.js
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_get_file_client_under_another_directory.js
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_rename_to_under_a_different_directory.js
sdk/storage/storage-file-share/recordings/node/fileclient/recording_rename_to_under_a_different_directory.js
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-file-share/test/directoryclient.spec.ts

@azure/storage-blob
@azure/storage-file-datalake
@azure/storage-file-share

[storage]Fixed an issue of escaping slashes in blob name unnecessarily.

---

sdk/servicebus/service-bus/package.json

It should've been updated to 1.4.0 when merging main but was missed.

[ServiceBus] correct core-paging dependency version

---

common/tools/eslint-plugin-azure-sdk/.eslintrc.json
common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts
sdk/core/abort-controller/.eslintrc.json
sdk/core/core-amqp/.eslintrc.json
sdk/core/core-auth/.eslintrc.json
sdk/core/core-client/.eslintrc.json
sdk/core/core-http/.eslintrc.json
sdk/core/core-lro/.eslintrc.json
sdk/core/core-paging/.eslintrc.json
sdk/core/core-tracing/.eslintrc.json
sdk/core/core-util/.eslintrc.json
sdk/core/core-xml/.eslintrc.json
sdk/core/logger/.eslintrc.json
sdk/eventhub/eventhubs-checkpointstore-table/.eslintrc.json
sdk/eventhub/mock-hub/.eslintrc.json
sdk/identity/identity-cache-persistence/.eslintrc.json
sdk/identity/identity-vscode/.eslintrc.json
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/keyvault/keyvault-admin/.eslintrc.json
sdk/keyvault/keyvault-common/.eslintrc.json
sdk/mixedreality/mixed-reality-authentication/.eslintrc.json
sdk/tables/data-tables/.eslintrc.json

- the default sorting rules are strange
- no automation to fix all the violations
- benefit not worth the effort required to maintain

[engsys] turn off `sort-imports` linter rule

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/configuration.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumenter.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/instrumenter.spec.ts

- [@azure/opentelemetry-instrumentation-azure-sdk]
- #20834
Renamed `AZURE_HTTP_TRACING_DISABLED` to `AZURE_HTTP_TRACING_CHILDREN_DISABLED` based upon recommendation by @xirzec on https://github.com/Azure/azure-sdk-for-js/pull/20776#discussion_r826428637
Chose easiest rename option.
- #20776

[instrumentation] rename of environment variable AZURE_HTTP_TRACING_DISABLED

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/consumer-test.js
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/test/internal/unit/client.spec.ts
sdk/cosmosdb/cosmos/tsconfig.strict.json

@azure/cosmos
https://github.com/Azure/azure-sdk-for-js/issues/20824
CosmosClient's patch api is failing for AADCredentials, (It was reported for Managed Identity Credentials). This was due to missing pipeline (responsible for actually fetching auth token) for patch api.
Yes

Fixing missing pipeline integration for CosmosClient in patch api

---

rush.json

- `@azure/keyvault-common`
- #22705
- #23355 
Forgot to change this property in `rush.json`. Setting this should let the pipeline publish an alpha for `keyvault-common`.

[keyvault] Update version policy for keyvault-common

---

.vscode/cspell.json

- "beider" in "beiderMorse". Person name used in encoder types
```ts
export type PhoneticEncoder = "metaphone" | "doubleMetaphone" | "soundex" | "refinedSoundex" | "caverphone1" | "caverphone2" | "cologne" | "nysiis" | "koelnerPhonetik" | "haasePhonetik" | "beiderMorse";
```
- ignore unknown words in generated synapse-access-control-rest package.

[cspell] suppress unknown word for search and synapse

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/samples/v3/javascript/ItemManagement.js
sdk/cosmosdb/cosmos/src/index.ts
sdk/cosmosdb/cosmos/src/utils/patch.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

3.17.0
https://github.com/Azure/azure-sdk-for-js/issues/22991
Add support for the move operation under Patch
N/A
yes
- [] Does this PR needs any fixes in the SDK Generator?** _(If so, create an Issue in the [Autorest/typescript](https://github.com/Azure/autorest.typescript) repository and link it here)_
- [] Added a changelog (if necessary)

add move operation

---

.github/fabricbot.json

The purpose of these changes is to update the set of service contacts for Cosmos to match the changes to CODEOWNERS in #23607.

[Bot Rules] Update Cosmos contacts

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/package.json

- @azure/identity-cache-persistence
Due to an old version of nan linked with a previous version of @azure/msal-node-extensions, it will fail to build in Node 19.  This upgrades the library from  1.0.0-alpha.9 to 1.0.0-alpha.25.
N/A
N/A

[identity] upgrade @azure/msal-node-extensions

---

sdk/maps/maps-common/CHANGELOG.md
sdk/maps/maps-common/api-extractor.json
sdk/maps/maps-common/package.json
sdk/maps/maps-route-rest/package.json
sdk/maps/maps-search/CHANGELOG.md
sdk/maps/maps-search/api-extractor.json
sdk/maps/maps-search/package.json

- `@azure/maps-search`
- `@azure/maps-common`
- `@azure-rest/maps-route`
- Correct the path for type definition files else the users are not able to consume them.
NA
NA

Fix the type generation path

---

sdk/identity/identity/README.md
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/visualStudioCodeCredential.ts

Added a disclaimer about the current shortcomings of VisualStudioCodeCredential in the corresponding docstring so that users will be notified in the credential API doc.
Also, added a missing envvar to the README.

[Identity] Documentation improvements

---

.github/CODEOWNERS

Communication
As separate teams exist for SDKs under `Communication`, there is no need to have dedicated people for all PRs and issues for all these SDKs.
Excessive `Communication` PR notifications.

remove team for all Communication requests

---

sdk/core/core-http/src/serializer.ts
sdk/core/core-http/test/serializationTests.ts

where there's no XML attributes, and the XML parser parses
"\<Name\>content\</Name\>" into `Name: "content"` instead of `Name: { "_": "content" }`
`@azure/core-http`

[core-http] Handle special case for `x-ms-text` autorest extension

---

dataplane.code-workspace
sdk/appconfiguration/perf-tests/app-configuration/package.json
sdk/appconfiguration/perf-tests/app-configuration/test/listSettings.spec.ts
sdk/communication/communication-email/package.json
sdk/communication/communication-sms/samples/v1/javascript/package.json
sdk/communication/communication-sms/samples/v1/typescript/package.json
sdk/keyvault/keyvault-admin/package.json
sdk/servicebus/service-bus/test/stress/app/package.json
sdk/servicebus/service-bus/test/stress/app/src/scenarioShortLivedReceivers.ts
sdk/template/perf-tests/template/package.json
sdk/template/perf-tests/template/test/getConfigurationSetting.spec.ts

Trying to pay down some debt by removing places we depend on `@azure/core-http` where I think we don't actually need to.
Used this for discovery: https://cs.github.com/Azure/azure-sdk-for-js?q=%40azure%2Fcore-http%22+language%3AJSON
@HarshaNalluru can you confirm that the perf test changes won't affect anything? It looked like we were only using the generateUuid function.

Remove unnecessary @azure/core-http deps

---

sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/src/models.ts
sdk/cognitivelanguage/ai-language-text/src/transforms.ts

The old implementation was an added type constraint but that was not correct because the types used for instantiation didn't respect the constraint. This PR replaces the constraint with an intersection type instead.
This implementation makes sure that `detectedLanguage` is part of the output models for `beginAnalyzeBatch` but not for the corresponding ones for `analyze`.
The PR also adds `isLanguageDefaulted` property which is returned by the service but not described in the swagger.

[Language Text] Correct implementation of auto language detection

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/samples/v3/javascript/ItemManagement.js
sdk/cosmosdb/cosmos/src/index.ts
sdk/cosmosdb/cosmos/src/utils/patch.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

Reverts Azure/azure-sdk-for-js#23128
Somehow tests got passed in this PR build (We are investigating how those tests are ignored)
Also we need to have the emulator support for this to work which is not in public yet!

Revert "add move operation"

---

sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_change_point.ts
sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_entire_series_anomaly.ts
sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_last_point_anomaly.ts
sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_change_point.ts
sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_entire_series_anomaly.ts
sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_last_point_anomaly.ts

@azure-rest/ai-anomaly-detector
Build break in main caused by this package failing to build when doing a global `rush build`

[@azure-rest/ai-anomaly-detector] remove unused export in sample 

---

sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/mappers.ts
sdk/cognitivelanguage/ai-language-text/src/transforms.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md
sdk/cognitivelanguage/ai-language-text/test/internal/utils.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts

It adds a swagger transform to specify the type of `detectedLanguage` to be a string and then attempts to deserialize it in the convenience layer and set the iso name correctly.

[Language Text] Mitigating bug in auto detected language for TA4H

---

sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts
sdk/identity/identity/src/util/processMultiTenantRequest.browser.ts
sdk/identity/identity/src/util/processMultiTenantRequest.ts
sdk/identity/identity/test/httpRequests.browser.ts
sdk/identity/identity/test/httpRequests.ts
sdk/identity/identity/test/internal/node/clientAssertionCredential.spec.ts
sdk/identity/identity/test/internal/node/onBehalfOfCredential.spec.ts

- [identity]
- #23693
The `additionallyAllowedTenantIds` was not passed through to the base `MsalFlow` class to allow it to resolve the additionally allowed tenant IDs in the `getToken()` method.  This fixes this bug and also fixes some minor ESLint issues.

[identity] Fix MSAL Flow additionallyAllowedTenantIds to pass through

---

common/config/rush/pnpm-lock.yaml
sdk/maps/maps-route-rest/package.json

to be consistent with the ones in this repo and in latest codegen.

[engsys] bump api-extractor and typescript versions for maps-routes-rest

---

sdk/cognitivelanguage/ai-language-text/src/lro.ts
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

Mitigation for the incorrect name used in for the `lastUpdatedDateTime` property in the job states. The service currently returns it as `lastUpdateDateTime` instead.

[Language Text] Mitigation for modifiedOn

---

sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/test/internal/tenantIdUtils.spec.ts

- [identity]
- #23693
Fixes the browser flows for the associated bug to also allow through the `additionallyAllowedTenants` to flow through.  Also adds some unit tests.

[identity] Fix MSAL Flow additionallyAllowedTenants to pass through

---

sdk/devcenter/ci.yml
sdk/devcenter/developer-devcenter-rest/CHANGELOG.md
sdk/devcenter/developer-devcenter-rest/karma.conf.js
sdk/devcenter/developer-devcenter-rest/recordings/node/devcenter_dev_boxes_operations_test/recording_create_dev_box.json
sdk/devcenter/developer-devcenter-rest/recordings/node/devcenter_environments_operations_test/recording_create_environment.json
sdk/devcenter/developer-devcenter-rest/review/developer-devcenter.api.md
sdk/devcenter/developer-devcenter-rest/src/azureDevCenter.ts
sdk/devcenter/developer-devcenter-rest/src/generated/azureDevCenter.ts
sdk/devcenter/developer-devcenter-rest/src/generated/clientDefinitions.ts
sdk/devcenter/developer-devcenter-rest/src/generated/index.ts
sdk/devcenter/developer-devcenter-rest/src/generated/isUnexpected.ts
sdk/devcenter/developer-devcenter-rest/src/generated/models.ts
sdk/devcenter/developer-devcenter-rest/src/generated/outputModels.ts
sdk/devcenter/developer-devcenter-rest/src/generated/paginateHelper.ts
sdk/devcenter/developer-devcenter-rest/src/generated/parameters.ts
sdk/devcenter/developer-devcenter-rest/src/generated/pollingHelper.ts
sdk/devcenter/developer-devcenter-rest/src/generated/responses.ts
sdk/devcenter/developer-devcenter-rest/src/index.ts
sdk/devcenter/developer-devcenter-rest/src/pollingHelper.ts
sdk/devcenter/developer-devcenter-rest/swagger/README.md
sdk/devcenter/developer-devcenter-rest/test/public/devBoxesTest.spec.ts
sdk/devcenter/developer-devcenter-rest/test/public/environmentsTest.spec.ts

Regenerate client, update polling workaround, update client setup workaround
@azure-rest/developer-devcenter. Package is currently unreleased (will release with 11/8 release cycle)
https://github.com/Azure/autorest.typescript/issues/1615
https://github.com/Azure/azure-sdk-for-js/issues/23420#issuecomment-1302500411
Moving two fixes to the above issues into customized code folder to separate from generated code.
The first is adding a default option, which is not supported by JS autorest right now. The second is working around an issue with the test recorder when polling LROs. There was a change to recorder behavior that necessitated an update to our fix here.
During this, consumed some formatting changes from the latest autorest version.
N/A
Covered by existing tests
N/A
N/A

[DevCenter] Move client workaround to customized code

---

eng/pipelines/npm-tasks.yml

This updates the npm admin tasks pipeline to gate permissions on an approval, not on pipeline invocation. There were larger permissions problems with the non-standard security setup in the base pipeline, so we're switching to the approval model consistent with how package releases are done.

Use deployment/approval for npm admin task pipeline

---

sdk/search/search-documents/test/internal/base64.spec.ts
sdk/search/search-documents/test/internal/browser/synonymMap.browser.spec.ts
sdk/search/search-documents/test/internal/geographyPoint.spec.ts
sdk/search/search-documents/test/internal/node/synonymMap.node.spec.ts
sdk/search/search-documents/test/internal/serialization.spec.ts
sdk/search/search-documents/test/internal/serviceUtils.spec.ts
sdk/search/search-documents/test/public/odata.spec.ts

`sdk\search\search-documents`
#13005 
The existing mocha tests for the `sdk\search\search-documents`  made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context ([https://mochajs.org/#arrow-functions](https://mochajs.org/#arrow-functions)).
**_Not applicable._**
**_Not applicable._**
- **_I don't believe this is relevant._**
- **_I don't believe this is necessary_**

fix: search-documents - modified mocha tests to use function keyword instead of arrow syntax

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/test/requestResponse.spec.ts
sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts

When the remote closes the sender with an error we currently just log the error logged as a warning and are not doing anything else. Since we won't receive any response, the send operation eventually times out, rejecting with `OperationTimeoutError`. As `OperationTimeoutError` is retryable, we would get the same time out error in each retry again, even though some sender errors are not retryable, for example, `MessageSizeExceeded` error in issue #23623.
This PR rejects the promise of request on sender_error events so that it fails with proper errors. These errors still go through the retry logic, but should be failing faster.

[core-amqp] request response link should reject when sender error

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts

The comments indicates that it is possible that we receive more messages than we ask for, and we want to return them. However, current code only resolve after max-wait-time-after-first message has passed. Once we have extra, during the wait time, more messages could still arrive.
This PR changes to remove immediately when we get what we ask for or more.

[ServiceBus] resolve received messages immediately when we got extra

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

azure-sdk-for-js
23518
Item.batch has poorly defined return type of response, although it appears to be returning a list of OperationResponse objects in response.results. So, in this PR we are going to update the contract of Item.batch operation from type any to OperationResponse[].
Updating the contract of batch operation.
Yes

Update Item batch operation method signature

---

sdk/attestation/attestation/test/browser/attestationTests.browser.spec.ts
sdk/attestation/attestation/test/public/attestationTests.spec.ts
sdk/attestation/attestation/test/public/attestationTokenTests.spec.ts
sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts
sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts
sdk/attestation/attestation/test/public/tokenCertTests.spec.ts

`sdk\attestation\attestation`
#13005 
The existing mocha tests for the `sdk\attestation\attestation` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions).
#23761 - Same fix, but for the `sdk/search/search-documents` package
**_Not applicable_**
- **_I don't believe this is relevant._**
- **_I don't believe this is necessary_**
I did run the package's test suite before and after the changes to confirm all …

fix: attestation - remove mocha arrow functions

---

sdk/keyvault/keyvault-admin/test/internal/userAgent.spec.ts

- #22705
- Due to keyvault-admin no longer using the code-sharing approach for keyvault-common, the location of the test file when running integration tests has gone up one level.
- This means the relative path used in the integration tests to find the `package.json` is no longer accurate.
This PR updates the path so it is correct.

[keyvault] keyvault-admin: fix user agent integration test

---

common/config/rush/pnpm-lock.yaml
sdk/purview/purview-catalog-rest/package.json

Fix the core-lro version for purview catalog due to the issue https://github.com/Azure/azure-sdk-for-js/issues/23731

Fix core-lro version for purview catalog version

---

sdk/batch/batch/test/batchClient.spec.ts

`sdk\batch\batch`
#13005 
The existing mocha tests for the `sdk\attestation\attestation` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions).
**_Not applicable_**
- **_I don't believe this is relevant._**
- **_I don't believe this is necessary_**

fix: batch: remove mocha arrow functions

---

sdk/cognitivelanguage/ai-language-conversations/test/public/analyze.spec.ts

`sdk\cognitivelanguage\ai-language-conversations`
#13005 
The existing mocha tests for the `sdk\cognitivelanguage\ai-language-conversations` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions).
**_Not …

fix: ai-language-conversations: remove mocha arrow functions

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts

Currently that log looks unrelated to any nearby code. This PR moves it to a better place where the `maxConcurrentCalls` option is set. The info logged still remains the same.

[ServiceBus] move a logging line to a better place

---

sdk/maps/maps-route-rest/README.md
sdk/maps/maps-route-rest/package.json
sdk/maps/maps-route-rest/samples/v1-beta/javascript/README.md
sdk/maps/maps-route-rest/samples/v1-beta/typescript/README.md
sdk/maps/maps-search/samples/v1-beta/javascript/README.md
sdk/maps/maps-search/samples/v1-beta/typescript/README.md

- @azure/maps-search
NA
- Links like docs & npm aren't available unless the package is released. Add them back in this PR.
NA
No
NA
NA
- x ] Added a changelog (if necessary)

[Maps] Add the correct API reference links in READMEs

---

.github/CODEOWNERS

Communication-Identity, Communication-Common
Updating CODEOWNERS for Communication Identity & Common Packages
No, the change is only in CODEOWNERS file.

Updating CODEOWNERS for Communication Identity & Common Packages

---

eng/scripts/Create-ApiReview.ps1

Enforcer api approval status for preview version in CI job when releasing a preview version package that was never GAed before.

Enforce package name approval status for preview version

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/test/internal/node/azureApplicationCredential.spec.ts
sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/23903
The "expiresOnTimestamp" field in Managed Identity should be in seconds and was assigned milliseconds. The PR fixes the bug

[identity] Expires on timestamp should be in seconds not ms

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json
sdk/cognitivelanguage/ai-language-text/package.json
sdk/identity/identity/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/template/template/package.json

to have pipelines' validation.

[engsys] Upgrade dev dependency `dotenv` version to `^16.0.0` for selected packages

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

The break changes listed at
https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#1100--2022-11-28 does not affect us.
Resolves #24022

[engsys] upgrade dependency `fs-extra` to `^11.0.0`

---

common/config/rush/pnpm-lock.yaml
sdk/notificationhubs/notification-hubs/package.json

We use this to bundle browser tests. The breaking change
https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md#breaking-changes
doesn't affect us.
Resolves #24017

[engsys] upgrade dev dependency `@rollup/plugin-typescript` version to `^10.0.0`

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/review/core-client.api.md
sdk/core/core-client/src/interfaces.ts
sdk/core/core-client/src/serializer.ts
sdk/core/core-client/test/serializer.spec.ts

Ports the following PRs to core-client to ensure we deserialize Storage payloads correctly in CoreV2:
https://github.com/Azure/azure-sdk-for-js/pull/23631
https://github.com/Azure/azure-sdk-for-js/pull/23658
https://github.com/Azure/azure-sdk-for-js/pull/23660
https://github.com/Azure/azure-sdk-for-js/pull/23680

[core-client] Port xmlIsMsText from core-http

---

sdk/loadtestservice/load-testing-rest/README.md
sdk/maps/maps-route-rest/README.md

fix:
https://github.com/Azure/azure-sdk-for-js/issues/24042
https://github.com/Azure/azure-sdk-for-js/issues/24041

fix readme.md 

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/serializer.ts

- `@azure/core-client`
Support for resettable streams was added to `core-rest-pipeline` some time ago in #21013, but a corresponding change to `core-client`'s validation is also needed (see the issue: #24048)
- Follow up to https://github.com/Azure/azure-sdk-for-js/pull/21013
- Fixes #24048

[core-client] Allow resettable streams

---

sdk/containerregistry/container-registry/package.json
sdk/containerregistry/container-registry/recordings/node/containerregistryblobclient/recording_can_upload_blob_from_resettable_stream.json
sdk/containerregistry/container-registry/recordings/node/containerregistryblobclient/recording_can_upload_oci_manifest_from_resettable_stream.json
sdk/containerregistry/container-registry/src/blob/containerRegistryBlobClient.ts
sdk/containerregistry/container-registry/test/public/containerRegistryBlobClient.spec.ts

Now that resettable streams work (#24049, #21013) we can pass them through to the generated client.

[container-registry] Pass resettable streams through to generated client

---

sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

Reverts Azure/azure-sdk-for-js#24080
Service fix is not consistent

Revert "[text analytics] Unskip test"

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/azureApplicationCredential.ts
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts

This protected property is no longer used and has confused consumers when trying to log credential objects.
#24075
I believe that this property was previously used by `ChainedTokenCredential` to calculate an error message when all credentials in the chain failed. At some point this must have been refactored and now the property is unnecessary. Since it is a *protected* property rather than a public one, I believe it can be safely removed.

[identity] Remove `UnavailableMessage` from `ChainedTokenCredential`

---

sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts

#24003
Sometimes token lifetimes are tracked by absolute timestamps ("expires On") and sometimes using a time interval ("expires In").  The managedIdentityCredential AppTokenProvider implementation was inconsistent in its treatment, directly coercing an absolute timestamp to an interval.
It would be better if the SDK were consistent internally in its use of relative or absolute time, but that's a much taller ask.
No, but someone should.

identity: managedIdentityCredential expires-in/-on

---

sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts

@azure/storage-blob
Clarity on container name rules - by linking to rules.
The developer doesn't know when they read this content that there are rules around what is an acceptable container name. They won't find that out until they get the error back from the method.
https://github.com/Azure/azure-docs-rest-apis/pull/5077
- [X ] Added impacted package name to the issue description

Blob Storage - container name rules link

---

sdk/maps/ci.yml

It's likely a leftover from copy-and-paste

[engsys] remove extraneous `safeName` entry in maps ci.yml

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts
common/tools/dev-tool/src/util/samples/info.ts
common/tools/dev-tool/src/util/samples/syntax.ts
common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/tsconfig.json
common/tools/dev-tool/test/samples/files/expectations/output-customization/typescript/tsconfig.json
common/tools/dev-tool/test/samples/files/expectations/simple/javascript/getConfigurationSetting.js
common/tools/dev-tool/test/samples/files/expectations/simple/typescript/src/getConfigurationSetting.ts
common/tools/dev-tool/test/samples/files/expectations/simple/typescript/tsconfig.json
common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/javascript/getConfigurationSetting.js
common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/src/getConfigurationSetting.ts
common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/tsconfig.json
common/tools/dev-tool/test/samples/files/inputs/simple/getConfigurationSetting.ts
common/tools/dev-tool/test/samples/files/inputs/simple@1.0.0-beta.1/getConfigurationSetting.ts

This PR removes outdated syntax restrictions from dev-tool when generating samples. This follows the end of our Node.js 12 grace period. Additionally, it increases the compiler target in samples from ES2018 to ES2020.
I've also removed version 12 from the default `check-node-versions` configuration.
CC @xirzec

[dev-tool] Remove stale sample guardrails

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/util/lock.ts

so that we don't get a map of ever-increasing size.

[core-amqp] remove map entry when we are done processing its task queues

---

sdk/purview/purview-catalog-rest/samples-dev/typedefs.ts
sdk/purview/purview-catalog-rest/samples/v1-beta/javascript/README.md
sdk/purview/purview-catalog-rest/samples/v1-beta/javascript/package.json
sdk/purview/purview-catalog-rest/samples/v1-beta/javascript/sample.env
sdk/purview/purview-catalog-rest/samples/v1-beta/javascript/typedefs.js
sdk/purview/purview-catalog-rest/samples/v1-beta/typescript/README.md
sdk/purview/purview-catalog-rest/samples/v1-beta/typescript/package.json
sdk/purview/purview-catalog-rest/samples/v1-beta/typescript/sample.env
sdk/purview/purview-catalog-rest/samples/v1-beta/typescript/src/typedefs.ts
sdk/purview/purview-catalog-rest/samples/v1-beta/typescript/tsconfig.json

@azure-rest/purview-catalog
https://github.com/Azure/azure-sdk-for-js/issues/22749
Sample was using optional chain which is not supported in ES2020 so adding an explicit nullcheck to fix samples publishing.
N/A
N/A
N/A

[Purview Catalog] Remove unsupported ES2020 optional chain in sample

---

common/config/rush/pnpm-lock.yaml
sdk/web-pubsub/web-pubsub-client/package.json

to `^19.2.2` which is consistent with the rest of rush projects

[engsys] update `puppeteer` version in `web-pubsub-client`

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-job-router/karma.conf.js
sdk/communication/communication-job-router/package.json
sdk/communication/communication-job-router/src/models/models.ts
sdk/communication/communication-job-router/src/models/options.ts
sdk/communication/communication-job-router/src/models/responses.ts
sdk/communication/communication-job-router/src/routerAdministrationClient.ts
sdk/communication/communication-job-router/src/routerClient.ts
sdk/communication/communication-job-router/test/internal/utils/mockClient.ts
sdk/communication/communication-job-router/test/public/exceptionPolicies.spec.ts
sdk/communication/communication-job-router/test/public/utils/recordedClient.ts
sdk/communication/communication-job-router/test/public/utils/testData.ts

Somehow this package was still depending on an older version of prettier than we use everywhere else in the repo. Due to the version bump, the files in this package needed to be reformatted.
I split this out from #24206 to make it easier to review/stage.

[communication-job-router] format with prettier

---

sdk/keyvault/keyvault-certificates/api-extractor.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/identifier.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/test/internal/userAgent.spec.ts
sdk/keyvault/keyvault-certificates/tsconfig.json

- #22705
Migrates `keyvault-certificates` to use the keyvault-common common package.

[keyvault] keyvault-certificates: depend on keyvault-common

---

sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

The `analyzeBatch.spec.ts` suite [doesn't get run by the min/max testing pipelines](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2066987&view=logs&j=abc7da81-7c4f-5087-422d-51020873ec4f&t=fb7db649-54ee-549f-6bbf-f1116b8abfe1) because that suite imports a non-public definition from the `src` directory. This PR fixes the issue by removing this non-conforming import.
[Succeeded run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2068887&view=results)

[Language Text] Fix min/max testing

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts

`@azure/app-configuration`
CI was failing because appconfig was pulling in the public version of `core-http-compat` (1.3.0) which causes an interesting quirk in rush: core-http-compat pulled in the public version of core-client (1.6.1) while appconfig itself pulled in the repo version of core-client (1.7.0).
Since AppConfig was removing and re-adding the deserializationPolicy from the pipeline, this meant the deserializationPolicy from 1.7.0 was not able to access the OperationSpec stored by the ServiceClient from 1.6.1. 
In practice this issue is less likely to occur in the wild since most package managers would consolidate down to a single version of core-client and there are not pre-release local versions to choose from.
The fix in this PR is to correctly leverage our internal pipeline …

[appconfig] Fix core-client mismatch with AppConfig

---

sdk/web-pubsub/web-pubsub-client/package.json

#17994
Delete dependency on `@azure-tools/test-recorder` because it is not used

[web-pubsub-client] Migrate to new recorder

---

sdk/web-pubsub/web-pubsub-client/src/utils/abortablePromise.ts
sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts

Make ackable operation cancellable
Yes

[web-pubsub-client] Make ackable operation cancellable

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json
sdk/core/core-lro/src/poller/poller.ts
sdk/core/core-lro/test/lro.spec.ts

[Failures](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2034536&view=logs&j=71cc2e7d-6454-5bf0-71b5-f1eef07a6c23&t=f2857310-5d68-5640-1409-0ba88dcfe076&l=1299) in https://github.com/Azure/autorest.typescript/pull/1586
`poll()` always sends the polling request as long as the operation has a location to poll from. However, once the operation is in a terminal state, there is no need to send the polling request.
Sending the useless polling request is not the end of the world and won't affect the state of the poller. I don't feel strongly about the change but it is nice to not do unjustified extra work.
Yes.
N/A

[core-lro] No polling allowed when the operation is in a terminal state

---

sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/test/identifierModelSerializer.spec.ts

Communication - Common
[User Story 3024912](https://skype.visualstudio.com/SPOOL/_workitems/edit/3024912): [SDK][JS][Common & Identity] Fix "strictNullChecks" error warning
When passing the value directly to `{}` to generate an error message string (without explicitly casting to String), the following warning message is generated:
(parameter) missingPropertyName: Q extends keyof Required<SerializedCommunicationIdentifier>[P]
Implicit conversion of a 'symbol' to a 'string' will fail at runtime. Consider wrapping this expression in 'String(...)'.ts(2731)
This pull request introduces a way to handle the error without an additional explicit type casting.
No changes in behavior.

added extends string to use in string generation

---

sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts

`rush update` suggests
>  WARN  deprecated @opentelemetry/api-metrics@0.33.0: Please use @opentelemetry/api >= 1.3.0

[engsys] remove deprecated `@opentelemetry/api-metrics` dependency

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/review/core-client.api.md
sdk/core/core-client/src/deserializationPolicy.ts
sdk/core/core-client/src/interfaces.ts
sdk/core/core-client/src/serializer.ts
sdk/core/core-client/test/deserializationPolicy.spec.ts

`@azure/core-client`
While porting `@azure/digital-twins-core` I ran into an odd behavior in core-client. Namely, whenever an `OperationSpec` included a `headersMapper`, we would include *all* headers returned from the service, even if they were not mapped.
This led to some odd behavior in part due to the fact we collapse the `body` property when the body is a `DictionaryMapper` which changed from `@azure/core-http`. This lead to many extra properties being added to result shapes beyond the desired `etag`, such as
```
'content-length': '347',
'content-type': 'application/json; charset=utf-8',
'strict-transport-security': 'max-age=2592000',
traceresponse: '00-25c03f641ea6ddb793b38a8567a93d68-89d6b78c8e8dae10-01',
'mise-correlation-id': 'd96f6b01-eae3-4048-a411-d14c2927d99f',
date: 'Fri, 06 …
```

[core-client] Ignore extra headers

---

sdk/maps/maps-search-rest/package.json

- The version for `@azure/maps-common` is incorrect. The beta.3 is the next release version, which has yet to exist.

Correct the version of maps-common in maps-search-rest

---

eng/typescript-emitter-package.json

`typescript-emitter-package.json` defines the depended cadl packages used by sdk automation pipeline.

Add typescript-emitter-package.json

---

sdk/cognitivelanguage/test-resources.json

@azure/ai-language-text
The Language resource doesn't have access to the storage account. This PR adds a new role assignment for the Language resource in the storage account. The ARM template bit is based on [Synapse's](https://github.com/Azure/azure-sdk-for-js/blob/741a885d2c4193fd3221a7a0081203852e9ed984/sdk/synapse/test-resources.json#L271).
N/A
N/A
N/A

[Cognitive Language] Update test-resources.json

---

common/config/rush/pnpm-lock.yaml

After [@azure/msal-node@1.14.6](https://www.npmjs.com/package/@azure/msal-node/v/1.14.6) has been released.

Remove jsonwebtoken v8 from the lockfile

---

sdk/core/core-lro/CHANGELOG.md

This release contains the work in https://github.com/Azure/azure-sdk-for-js/pull/24159 and is needed for the code generator tests to pass.

[core-lro] Prepare release for v2.5

---

eng/pipelines/templates/stages/archetype-js-release.yml

Per offline discussion, removing this leg until we can replace it with something more robust.

Disable smoke tests in release pipeline

---

sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableTransaction.ts
sdk/tables/data-tables/test/public/transaction.spec.ts

https://github.com/Azure/azure-sdk-for-js/issues/22341
If `submitTransaction` is called concurrently, concurrent transactions step into each other's feet, causing one of the transactions to win over the others and be sent multiple times.
Currently, we have a cached TransactionClient which we use internally to translate the transaction actions into the batch request body. This causes concurrent transactions to use the same resource causing issues. The fix in this PR removed the cached transaction client and creates a new one per transaction to ensure isolation between transactions
YES

[Tables] Fix problem when concurrent transactions are submitted

---

sdk/communication/test-resources.json

The email live tests were previously using pre-provisioned resources. The secrets for these resources were stored in a key vault and accessed by the pipeline.
We are now creating these test resources at the pipeline runtime using an arm template.

Adding email live tests resources to test-resources.json

---

sdk/digitaltwins/digital-twins-core/package.json

Address issue discovered by min-max testing.
`@azure/digital-twins-core`
Fixes #24467
Minimum specified version of core-rest-pipeline didn't expose the `isRestError` typeguard used by this package.

[digital-twins] bump minimum version of core-rest-pipeline

---

sdk/notificationhubs/notification-hubs/src/serializers/notificationDetailsSerializer.ts

The xml parsing test started failing after core-xml changes in PR #24356. This PR applies test fix similar to what's been done to core-xml tests in PR #24356.

[NotificationHubs] fix unit tests

---

sdk/eventhub/perf-tests/event-hubs/test/send.spec.ts

Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2125764&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=948263dc-2a7b-5031-89c1-ea1ca73fbaf3&l=12

[Perf] EventHubs SendTest should extend BatchPerfTest

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/managementClient.ts

Some errors (e.g., `MessageSizeExceeded`) would close the underlying rhea link. Currently we have a `replyTo` property that is initialized when constructing the management client and remains unchanged. However, this leads to the following error when attempting to re-establish a new link:
```
InvalidOperationError: A link with the same 'attach.target.address' value '504c8ecd-6f73-1b4e-9108-d1e12fc3ac9f' address has been already registered to the entity management node $management.
```
This PR ensure that whenever we send a request, if we are going to establish a new link, the `replyTo` property has a unique value.
Fixes #24476
There's a live test failure due to the issue.

[ServiceBuss] Ensure unique `replyTo` when new link is needed

---

sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/appVersionImport.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/apps.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/entityRole.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/examples.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/export.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/features.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/featuresPhraseLists.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/import.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/model.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelClosedLists.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelEntities.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelIntents.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelPatternAny.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelPrebuiltDomain.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelPrebuilts.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/modelRegexEntities.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/patterns.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/prebuiltEntityRole.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/train.test.ts
sdk/cognitiveservices/cognitiveservices-luis-authoring/test/Luis/versions.test.ts

`sdk\cognitiveservices\cognitiveservices-luis-authoring`
#13005 
The existing mocha tests for the `sdk\cognitiveservices\cognitiveservices-luis-authoring` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: cogserv-luis-authoring: remove mocha arrow functions

---

sdk/servicebus/service-bus/src/core/autoLockRenewer.ts

Previously the two stopping cases share a same log message, which can be confusing for the first case. This PR
separates them to have different log messages.

[ServiceBus] improve auto lock renew logging when stopping

---

common/autoinstallers/rush-prettier/pnpm-lock.yaml

to be consistent with the prettier version in repo pnpm-lock.yaml

Update autoinstallers prettier version to 2.8.3

---

sdk/storage/storage-blob/src/BlobBatch.ts

`@azure/storage-blob`
Noticed failing tests for batch caused by a missing `return` statement which caused a race condition in assembling the batch body. This was introduced by PR #24548 - not sure why the tests didn't catch it sooner, possibly there was a bad merge or a side effect of promise resolution timing.

[storage-blob] Fix issue with missing `return` in blobBatch

---

sdk/web-pubsub/web-pubsub-client/review/web-pubsub-client.api.md
sdk/web-pubsub/web-pubsub-client/src/models/index.ts
sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts

`autoRejoinGroup` options didn't take effect and some naming are `autoRestoreGroup` which doesn't keep consistent.
yes

[web-pubsub-client] Fix naming restoreGroup and add tests

---

sdk/maps/maps-search-rest/CHANGELOG.md
sdk/maps/maps-search-rest/package.json

- The type declaration file path is incorrect in the `files` prop in `package.json`, thus causing the user cannot access the file.

[Maps] Correct the file path for type declaration in `@azure-rest/maps-search`

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

Fixes https://github.com/Azure/azure-sdk-for-js/issues/24635
Pinning "@microsoft/api-extractor": "7.34.0" to fix `rush update --full` failure
Revert this PR once we have a resolution from the rush team with some other workaround or a new version with the fix

[RUSH] Pin "@microsoft/api-extractor": "7.34.0" to fix `rush update --full`

---

common/config/rush/pnpm-lock.yaml
eng/tools/generate-doc/package.json
sdk/devcenter/developer-devcenter-rest/samples/v1/typescript/package.json
sdk/hybridcontainerservice/arm-hybridcontainerservice/samples/v1-beta/typescript/package.json
sdk/maps/maps-route-rest/package.json
sdk/monitor/perf-tests/monitor-ingestion/package.json
sdk/web-pubsub/web-pubsub-client/package.json

for packages that missed the last version bump train.

[engsys] upgrade dev dependency `@types/node` to `^14.0.0`

---

sdk/cognitiveservices/cognitiveservices-luis-runtime/test/Luis/predictions.test.ts

`sdk\cognitiveservices\cognitiveservices-luis-runtime`
#13005 
The existing mocha tests for the `sdk\cognitiveservices\cognitiveservices-luis-runtime` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions).
#23850 - …

fix: cogserv-luis-runtime: remove mocha arrow functions

---

sdk/test-utils/recorder/test/sanitizers.spec.ts
sdk/test-utils/recorder/test/testProxyTests.spec.ts
sdk/test-utils/recorder/test/utils/utils.ts

Fixes tests broken by move to native test proxy binaries. These tests passed in CI (due to the test proxy being started separately) but weren't working locally.

[recorder] Remove host.docker.internal from recorder tests

---

sdk/communication/communication-common/test/internal/cryptoUtils.spec.ts
sdk/communication/communication-common/test/public/clientArguments.spec.ts
sdk/communication/communication-common/test/public/communicationKeyCredentialPolicy.spec.ts
sdk/communication/communication-common/test/public/communicationTokenCredential.spec.ts
sdk/communication/communication-common/test/public/connectionString.spec.ts
sdk/communication/communication-common/test/public/identifierModelSerializer.spec.ts
sdk/communication/communication-common/test/public/identifierModels.spec.ts

`sdk\communication\communication-common`
#13005 
The existing mocha tests for the `sdk\communication\communication-common` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: comm-common: remove mocha arrow functions

---

common/config/rush/pnpm-lock.yaml
sdk/loadtestservice/load-testing-rest/package.json
sdk/loadtestservice/load-testing-rest/samples-dev/sample.ts
sdk/loadtestservice/load-testing-rest/src/parameters.ts
sdk/loadtestservice/load-testing-rest/test/public/testAdministration.spec.ts
sdk/loadtestservice/load-testing-rest/test/public/testRun.spec.ts

which is the version currently used by other packages.
Also include results of `rushx format`

[engsys] upgrade load-testing dev dependency prettier to ^2.5.1

---

common/config/rush/pnpm-config.json

- Dependency requiring this workaround has been updated (microsoft/rushstack#3952)

Revert "Allow any version of @types/node to satisfy peer dependencies"

---

documentation/RLC-Swagger-quickstart.md
documentation/RLC-quickstart.md

Update ts emitter version

---

sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_listfilesanddirectories__with_invalid_char.json
sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_listhandles_for_directory_with_invalid_char_should_work.json
sdk/storage/storage-file-share/recordings/browsers/fileclient/recording_listhandles_for_file_with_invalid_char_should_work.json
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_listfilesanddirectories__with_all_attributes.js
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_listfilesanddirectories__with_invalid_char.js
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_listhandles_for_directory_with_invalid_char_should_work.js
sdk/storage/storage-file-share/recordings/node/fileclient/recording_listhandles_for_file_with_invalid_char_should_work.js
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/generated/src/models/index.ts
sdk/storage/storage-file-share/src/generated/src/models/mappers.ts
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/generatedModels.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts

Add support for file invalid char

Add support for invalid char in file

---

sdk/communication/communication-email/test/public/emailClient.spec.ts

`sdk\communication\communication-email`
#13005 
The existing mocha tests for the `sdk\communication\communication-email` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: comm-email: remove mocha arrow functions

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/karma.conf.js
sdk/test-utils/recorder/src/index.ts
sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/recorder/src/utils/relativePathCalculator.browser.ts
sdk/test-utils/recorder/src/utils/relativePathCalculator.ts
sdk/test-utils/recorder/src/utils/sessionFilePath.ts

Remove additional `RECORDING_ASSETS_PATH` environment variable in Karma config by calculating the assets.json path relative to the existing `RECORDINGS_RELATIVE_PATH` variable. Includes a fix to the start method to retry in the event the `assets.json` does not exist.

[recorder] Figure out assets.json from RELATIVE_RECORDINGS_PATH

---

sdk/core/core-util/src/delay.ts

Minor edit to use modern syntax and simpler control flow.

[core-util] Edit delay()

---

common/config/rush/pnpm-lock.yaml
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/swagger/README.md

Update version for blob, share and datalake.

Prepare for STG86 preview

---

sdk/communication/communication-identity/test/public/communicationIdentityClient.mocked.spec.ts

`sdk\communication\communication-identity`
#13005 
The existing mocha tests for the `sdk\communication\communication-identity` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: comm-identity: remove mocha arrow functions

---

sdk/web-pubsub/web-pubsub-client/README.md

Organized and edited README so that it's easier to get started with this client library and easier to find further reference docs.

Organized and edited the README of Web PubSub client library

---

sdk/core/core-rest-pipeline/src/util/userAgentPlatform.browser.ts

- [@azure/core-rest-pipeline]
#24758
Relies on the deprecated `oscpu`.  This uses the non-standard `globalThis.navigator.userAgentData.platform` and falls back to the deprecated `globalThis.navigator.platform`.
We could have removed the OS checks overall, but we can get better telemetry to keep the OS detection.

[core-rest-pipeline] Remove oscpu from OS sniffing

---

eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/variables/globals.yml

This will enable codeQL to run on all scheduled CI jobs across all services.

Enable codeQL for scheduled CI jobs

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/src/common/constants.ts
sdk/cosmosdb/cosmos/src/utils/batch.ts
sdk/cosmosdb/cosmos/test/internal/unit/utils/batch.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts
sdk/cosmosdb/cosmos/test/tsconfig.json

@azure/cosmos
#23923
CosmosDB Items.bulk api doens't honour 2Mb cap imposed on a single batch request. With these changes if size of a batch (cumulative size of it's operations) exceeds 2Mb it is split into smaller batches before sending.
Yes

For CosmosDB bulk api added support for splitting of batch based on size.

---

sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob-changefeed/review/storage-blob-changefeed.api.md
sdk/storage/storage-blob-changefeed/src/BlobChangeFeedClient.ts
sdk/storage/storage-blob-changefeed/src/ChangeFeed.ts
sdk/storage/storage-blob-changefeed/src/Chunk.ts
sdk/storage/storage-blob-changefeed/src/ChunkFactory.ts
sdk/storage/storage-blob-changefeed/src/LazyLoadingBlobStream.ts
sdk/storage/storage-blob-changefeed/src/Segment.ts
sdk/storage/storage-blob-changefeed/src/SegmentFactory.ts
sdk/storage/storage-blob-changefeed/src/Shard.ts
sdk/storage/storage-blob-changefeed/src/ShardFactory.ts
sdk/storage/storage-blob-changefeed/src/models/models.ts
sdk/storage/storage-blob-changefeed/src/utils/utils.common.ts
sdk/storage/storage-blob-changefeed/test/blobchangefeedclient.spec.ts
sdk/storage/storage-blob-changefeed/test/utils/index.ts
sdk/storage/storage-blob-changefeed/test/utils/testutils.common.ts

storage-blob-changefeed
Migrated to use `core-rest-pipeline` (coreV2). Since this package doesn't directly expose REST operations, there is very little change. `core-http` only provided a few common interfaces that have been moved to other packages.

[storage-blob-changefeed] Migrate to core-rest-pipeline

---

sdk/tables/ci.yml
sdk/tables/data-tables/tests.yml

Remove unnecessary old variable that currently breaks the pipeline after @kurtzeborn change https://github.com/Azure/azure-sdk-for-js/pull/23941.

Remove unnecessary jobMatrixFilter variable 

---

sdk/storage/README.md

The `feature/storage/stable` branch was removed in favor of `storage/stable` branch.

[storage][docs] fix links

---

.github/CODEOWNERS

For context, see:
- https://github.com/Azure/azure-sdk-for-js/pull/24621#pullrequestreview-1294287181
Related PR:
- https://github.com/Azure/azure-sdk-tools/pull/5088

In `CODEOWNERS`, restore erroneously removed `/eng/pipelines/aggregate-reports.yml` path

---

sdk/storage/README.md

The `feature/storage/stable` branch was removed in favor of `storage/stable` branch.

Port [storage][docs] fix links (PR #24838)

---

sdk/communication/communication-rooms/test/internal/roomsClient.mocked.spec.ts

`sdk\communication\communication-rooms`
#13005 
The existing mocha tests for the `sdk\communication\communication-rooms` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: comm-rooms: remove mocha arrow functions

---

sdk/communication/communication-chat/test/internal/chatClient.mocked.spec.ts
sdk/communication/communication-chat/test/internal/chatThreadClient.mocked.spec.ts

`sdk\communication\communication-chat`
#13005 
The existing mocha tests for the `sdk\communication\communication-chat` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions). …

fix: comm-chat: remove mocha arrow functions

---

sdk/keyvault/ci.yml

We auto-target `test-utils`, which is a good barometer, but I am only comfortable with merging proxy changes if I can see that at least one real library in each repo really works.

Add `keyvault` trigger when updating eng/common/testproxy

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

- Workaround for puppeteer/puppeteer#9665
- Revert when `puppeteer > 19.7.0` is released (#24870)

Temporarily pin dependency "puppeteer"

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

- Reverts commit 149223735921959652f1cc0968b5b1582636edc7
- Fixes #24870
I verified `rush update --full` works correctly after these changes and the release of `puppeteer-core@19.7.1`.

Revert "Temporarily pin dependency "puppeteer" (#24869)"

---

sdk/cosmosdb/cosmos/src/queryExecutionContext/FetchResult.ts

[@azure/cosmos](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/cosmosdb/cosmos)
#24493 
The code was breaking for any parallel query where the result is `0` or `false` or array of them.
Eg. `SELECT value c['type'] from c where c['type']=0`. This fix enables typecheck of the `feedResponse`.

Fix Issue-24493: Typecheck feedResponse in FetchResult

---

sdk/cosmosdb/cosmos/src/utils/batch.ts

[@azure/cosmos](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/cosmosdb/cosmos)
#24287 
A warning is logged on console if partition key is not present in resource body for bulk operations. This fix checks for a non-partitioned container, and skips logging a warning for it.

Check for unpartitioned container

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

@azure/cosmos
Agent pool in `eng\pipelines\templates\stages\platform-matrix.json` has been migrated to windows-2022, from windows-2019. This caused tests to skip for @azure/cosmos which uses non standard file `eng\pipelines\templates\stages\cosmos-sdk-client.yml` instead of `eng\pipelines\templates\stages\archetype-sdk-client.yml`. We are currently planning to move to `archetype-sdk-client.yml`
NA

Migration @azure/cosmos ci pipeline to run on windows-2022 agent pool.

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/BlobDownloadResponse.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generatedModels.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

1. Added createdOn in BlobDownloadResponseParsed and FileReadResponse in datalake package 
2. Renamed new added option `leaseDuration` to `leaseDurationInSeconds`
3. Expose `KnownEncryptionAlgorithmType` to describe extendable enum type  `EncryptionAlgorithmType`'s available value.

[storage]Added createdOn in BlobDownloadResponseParsed and FileReadResponse in datalake package

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts
sdk/servicebus/service-bus/test/internal/unit/receiver.spec.ts

Currently the two options only affect `receiveMessages()`.  This PR pass them to peek operations as well so the received messages are consistent.

[ServiceBus] pass `skipParsingBodyAsJson` and `skipConvertingDate` options to peek operations

---

.devcontainer/devcontainer.json

GitHub grants minimal permissions to a Codespace when it is created through creating a personal access token (PAT). By default, this PAT only grants write access to the repo that the Codespace was created from. This causes permissions issues when pushing assets to the `Azure/azure-sdk-assets` repo since the PAT does not grant write permission to that repo. Fortunately, we can request additional permissions through the `devcontainer.json`, which will give the Codespace write access to the `Azure/azure-sdk-assets` repo.
Reference: https://docs.github.com/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces

Add permission for `Azure/azure-sdk-assets` to `devcontainer.json`

---

sdk/core/core-xml/src/xml.browser.ts

Original PR description:
>Zlatkovsky commented on Nov 15, 2022
In our use-case of the ms-rest-js library, we have a large existing application (complete with caching, service-workers, etc) that we dynamically load additional JavaScript code into. The additional JS is what brings in the ms-rest-js.
>
>The application has Trusted Types enabled (e.g., CSP rule `'trusted-types LibraryA LibraryB etc`). But, interestingly, its `require-trusted-types-for 'script'` is currently under "report only" (`Content-Security-Policy-Report-Only`). In those cases, a call to `trustedTypes.createPolicy` will fail because the policy isn't on the allowed-list, even though _skipping_ the `createPolicy` would be OK. So in effect, https://github.com/Azure/ms-rest-js/commit/531aea9bfbbe6ef6c06984ab06f99775b90923ca …

[core-xml] port https://github.com/Azure/ms-rest-js/pull/475

---

common/tools/dev-tool/src/config/rollup.base.config.ts

It turns out that on windows some warnings are reported with `\` separator while others with `/` at the same time, e.g.,
str ../../../common/temp/node_modules/.pnpm/chai@4.3.7/node_modules/chai/lib/chai.js
str C:\github\jeremymeng\js-main\common\temp\node_modules\.pnpm\sinon@9.2.4\node_modules\sinon\pkg\sinon-esm.js
This PR changes to try both separators when checking whether to suppress bundle warnings.

[dev-tool] try `/` and `\` path separators when checking bundling warnings

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

@azure/cosmos
22726
adding a dev dependency to re-solve error
'@sinonjs/fake-timers' is imported by dist-esm/test/public/functional/globalEndpointManager.spec.js, but could not be resolved – treating it as an external dependency
N/A

add sinon-fake-timers dependency

---

sdk/eventhub/event-hubs/package.json

N/A
The library uses `createAbortablePromise` that is part of v1.2.0 and not v1.1.0.
N/A
N/A
https://github.com/Azure/azure-sdk-for-js/pull/24731

[Event Hubs] Bump core-util version

---

sdk/servicebus/service-bus/tests.yml

There's little impact to the total running time of the pipeline. We get larger logs but it should provide big help on diagnosing failures.

[ServiceBus][Test] enable detailed logging in live test pipeline

---

sdk/cognitivelanguage/ai-language-text/CHANGELOG.md
sdk/cognitivelanguage/ai-language-text/review/ai-language-text.api.md
sdk/cognitivelanguage/ai-language-text/src/generated/generatedClient.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/index.ts
sdk/cognitivelanguage/ai-language-text/src/generated/models/mappers.ts
sdk/cognitivelanguage/ai-language-text/src/models.ts
sdk/cognitivelanguage/ai-language-text/src/textAnalysisClient.ts
sdk/cognitivelanguage/ai-language-text/swagger/README.md
sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts

It is not working in the service according to Mikael.

[Language Text] Remove defaultLanguage

---

.vscode/settings.json
sdk/communication/communication-call-automation/.eslintrc.json
sdk/communication/communication-call-automation/test/public/callAutomationClient.spec.ts
sdk/communication/communication-call-automation/test/public/utils/connectionUtils.ts

- setting up first unit test using chai/sinon
- adding ESLint config for VSCode
- [] Added impacted package name to the issue description
- [] Does this PR needs any fixes in the SDK Generator?** _(If so, create an Issue in the [Autorest/typescript](https://github.com/Azure/autorest.typescript) repository and link it here)_
- [] Added a changelog (if necessary)

Unit Test Setup

---

sdk/core/core-http-compat/src/extendedClient.ts
sdk/core/core-http-compat/src/policies/disableKeepAlivePolicy.ts
sdk/core/core-http-compat/test/extendedClient.spec.ts

`@azure/core-http-compat`
Fixes #25073
In the case that the consumer provides a pipeline that already has the disableKeepAlivePolicy added, we don't want to add it a second time. This can happen in situations like Storage where the same pipeline might be re-used by multiple clients.
Yes

[core-http-compat] Fix issue with disable keep alive policy being added multiple times

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/src/utils/utils.common.ts

`@azure/storage-file-datalake`
Fixes #25068 
`windowsFileTimeTicksToTime` calculation somehow went wrong since 2023 with a 1-day difference, perhaps due to miscalculation w.r.t leap days.
This PR attempts to fix the bug and fix the tests.
The new implementation makes use of the JS Date object to do most of the calculation instead of relying on the numbers/constants to account for the leap days.  
```js
// Existing Code - Straight from the storage-file-datalake code
function windowsFileTimeTicksToTime(timeNumber: string | undefined): Date | undefined {
if (!timeNumber) return undefined;
const timeNumberInternal = parseInt(timeNumber!);
if (timeNumberInternal === 0) return undefined;
const date = new Date(timeNumberInternal / 10000);
date.setUTCFullYear(date.getUTCFullYear() - 369);
return …
```

[storage-file-datalake] [Bug Fix] Fix the date property(createdOn, expiresOn) in some of the returned responses

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/workloadIdentityCredentialOptions.ts
sdk/identity/identity/src/index.ts

- [@azure/identity]
Customer reported issue with non-exported `WorkloadIdentityDefaultCredentialOptions`

[identity] Re-export WorkloadIdentityCredential options

---

.vscode/cspell.json
sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/README.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md
sdk/notificationhubs/notification-hubs/src/models/installation.ts
sdk/notificationhubs/notification-hubs/src/models/notification.ts
sdk/notificationhubs/notification-hubs/src/models/notificationDetails.ts
sdk/notificationhubs/notification-hubs/src/models/registration.ts
sdk/notificationhubs/notification-hubs/src/serializers/notificationDetailsSerializer.ts
sdk/notificationhubs/notification-hubs/src/serializers/registrationSerializer.ts
sdk/notificationhubs/notification-hubs/src/utils/constants.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/registrationSerializer.spec.ts
sdk/notificationhubs/notification-hubs/test/public/unit/installation.spec.ts
sdk/notificationhubs/notification-hubs/test/public/unit/notification.spec.ts

Adds Xiaomi support for Track 2 SDKs with registration, installation, send and send outcome operations.
yes
- https://github.com/Azure/azure-notificationhubs-dotnet/pull/261
- https://github.com/Azure/azure-notificationhubs-dotnet/pull/260
- https://github.com/Azure/azure-notificationhubs-dotnet/pull/259

[notification hubs] Adding Xiaomi support

---

sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/src/managementClient.ts

Simplifying `LinkEntity` further and fixing an `undefined` name bug in logging.
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2617273&view=results)

[Event Hubs] Simplify LinkEntity

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/test/internal/unit/batchingReceiver.spec.ts

instead of always adding credit of `maxMessageCount`. Otherwise, in the case of user aborting the call then re-receive, we keep adding excessive credits.

[ServiceBus] when batch-receiving add credit when needed

---

sdk/confidentialledger/confidential-ledger-rest/test/public/colderEndpoints.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/getCollections.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/historicalRangeQuery.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/ledgerHistory.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/listEnclaveQuotes.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/postTransaction.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/testUserAuth.spec.ts
sdk/confidentialledger/confidential-ledger-rest/test/public/usersEndpoint.spec.ts

`sdk\confidentialledger\confidential-ledger-rest`
#13005 
The existing mocha tests for the `sdk\confidentialledger\confidential-ledger-rest` made use of the arrow syntax for callback functions. Mocha recommends not to do this because you lose access to the mocha context (https://mochajs.org/#arrow-functions).
#23850 - Same fix …

fix: confidential-ledger-rest: remove mocha arrow functions

---

sdk/communication/communication-phone-numbers/test/public/lro.search.spec.ts
sdk/communication/communication-phone-numbers/test/public/lro.update.spec.ts
sdk/communication/communication-phone-numbers/test/public/utils/statusCodeHelpers.ts

Due to a small backend change, tests that validate operations on unauthorized or invalid phone numbers now return status code 403, as opposed to 400 or 404 previously. To simplify the code of the test, the assertion now checks that the request has been rejected due to a client error, which is validated by checking if the status code falls under the 4xx bucket.
While it should be enough to validate that the operation itself fails, the check for client error was added to ensure that the request is indeed being rejected by the server instead of it failing due to another unrelated reason, which would usually be represented by a 5XX error.

[Communication] PhoneNumbers - Simplify status code assertions.

---

sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

to ensure v3 rhea and rhea-promise transitive dependencies.

[amqp messaging] bump dependency @azure/core-amqp version to ^3.3.0

---

sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/samples-dev/uploadCustomManifest.ts
sdk/containerregistry/container-registry/samples-dev/uploadImage.ts
sdk/containerregistry/container-registry/samples-dev/uploadManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadCustomManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadImage.js
sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadManifest.js
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadCustomManifest.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadImage.ts
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadManifest.ts
sdk/containerregistry/container-registry/src/blob/models.ts

- Remove `Readable.from` since we have a `Buffer` overload now
- Use new `sizeInBytes` in upload manifest sample
- Fix custom manifest upload sample

[ACR] Update samples with recent changes

---

sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts
sdk/eventhub/event-hubs/tests.yml

1.These changes enable event hubs to run live tests against `AzureUsGovernment` and `AzureChina` clouds. The sovereign cloud live tests will be green with the changes.
**2.File changed description:**
- eventHubConsumerClient.spec.ts : Increase the waiting time of `loopUntil`. The reason for this is to fix the timeout problem on the `China` cloud.
- test.yml : enable `UsGov` and `China` clouds.
**3.Pipeline results:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2630890&view=results
@benbp, @hector-norza, @joheredi, @ronniegeraghty, @jsquire, @deyaaeldeen for notification.

Update event hubs to enable live testing in sovereign clouds for multiple services

---

sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji.json
sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji.json
sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji.json
sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_string_encoding_textelementsv8/recording_family_emoji_with_skin_tone_modifier.json
sdk/cognitivelanguage/ai-language-text/test/public/analyze.spec.ts
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

#25272 
All compound emojis are correctly counted as a single TextElement or grapheme after the service bug fixed

[language-text] Fix test for grapheme offset in PII Entity

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/README.md
sdk/notificationhubs/notification-hubs/src/auth/hmacSha256.browser.ts
sdk/notificationhubs/notification-hubs/src/utils/optionUtils.ts
sdk/notificationhubs/notification-hubs/test/internal/unit/optionUtils.spec.ts

- #25316
- #25230
The `optionUtils` function `isSendNotificationOptions` used the old version of the `SendNotificationOptions` which had the `tags` and not the `tagExpression`.  This PR fixes that.
Yes

[notification hubs] Fixing tag expression send

---

sdk/communication/communication-email/tests.yml

I've added a parameter to the email live test pipelines that allows only the PPE stage to be run. This allows us to start a build on this pipeline from our service deployment pipeline.

[Communication][Email] Adding parameter for only running the PPE stage

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/dataTransformer.ts
sdk/servicebus/service-bus/test/internal/unit/dataTransformer.spec.ts

We should treat `Uint8Array` message body similar to what we do with `Buffer`.
Fixes #25336
Related Event Hubs PR: #21185

[ServiceBus] Fix issue sending message body of `Uint8Array`

---

sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/samples-dev/downloadImage.ts
sdk/containerregistry/container-registry/samples/v1-beta/javascript/downloadImage.js
sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/downloadImage.ts
sdk/containerregistry/container-registry/src/blob/containerRegistryBlobClient.ts
sdk/containerregistry/container-registry/src/blob/models.ts

- Fixes #24628
See the underlying issue for details, but, basically, we should be verifying the downloaded manifest using the digest provided by the user, if one is provided.

[ACR] Validate digest on downloadManifest

---

sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts

#24901
https://github.com/Azure/azure-sdk-for-js/pull/24902 try to fix this issue but blocked by format. 
`IsDuplicated` always return true in WebPubSubResult.

[web-pubsub-client] Fix isDuplicated always returned as true

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/receiverHelper.ts
sdk/servicebus/service-bus/src/util/constants.ts
sdk/servicebus/service-bus/test/internal/unit/receiverHelper.spec.ts

There are cases where the service doesn't respond to our drain-credit request, or the response comes back after a long and unexpected time. Since we are blocking on the `receiver_drained` event before resolving, application code could be blocked indefinitely when suspending/closing.
This PR adds a timeout around credit draining, and if the timeout limit expires we close the receiver then returns.

[ServiceBus] add drainCredit timeout when suspending receiver

---

sdk/containerregistry/container-registry/swagger/README.md

- Fixes #25029
Removes incorrect section from the Swagger.

[ACR] Remove securityDefinitions property from Swagger

---

sdk/storage/storage-queue/src/QueueServiceClient.ts

@azure/storage-queue
Didn't find any when doing a quick search
Current code example says that "iterator" should be used to obtain the value, but it is item where one should get the value from 
No code change per say, just example / usage change

Corrected code typo in the code examples

---

design/readme-snippets.md

- [dev-tool]
Adds a design document on how we are going to do snippet extraction for READMEs and source code.
- #24536

[dev tool] Add design docs for README snippets

---

sdk/eventhub/event-hubs/src/batchingPartitionChannel.ts
sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/dataTransformer.ts
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/src/loadBalancerStrategies/loadBalancingStrategy.ts
sdk/eventhub/event-hubs/src/logger.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/partitionProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/partitionReceiver.ts
sdk/eventhub/event-hubs/src/pumpManager.ts
sdk/eventhub/event-hubs/src/util/error.ts
sdk/eventhub/event-hubs/src/withAuth.ts
sdk/eventhub/event-hubs/test/internal/cancellation.spec.ts
sdk/eventhub/event-hubs/test/internal/checkOnInterval.spec.ts
sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts
sdk/eventhub/event-hubs/test/internal/node/waitForEvents.spec.ts
sdk/eventhub/event-hubs/test/internal/receiveBatch.spec.ts

As the title says. This makes the code more safe as more things become const and thus unmutable. It also decreases the surface of the receiver. Also decomposes the receiver into many smaller functions that can be easily unit-tested.
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2660101) for 299ae54e3e379c05e6fe07226c536f7bcbb8e1d0
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2661988&view=results) for  https://github.com/Azure/azure-sdk-for-js/pull/25390/commits/e3fb251e264db1b396edeafb28331d17d0835fb8
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2665541&view=results) for https://github.com/Azure/azure-sdk-for-js/pull/25390/commits/47afb57856b44028cc73dee770945056e6b724f1
[Successful …

[Event Hubs] Convert EventHubReceiver class to a function

---

sdk/notificationhubs/notification-hubs/CHANGELOG.md
sdk/notificationhubs/notification-hubs/package.json
sdk/notificationhubs/notification-hubs/samples-dev/createInstallation.fcmLegacy.ts
sdk/notificationhubs/notification-hubs/samples-dev/createInstallation.ts
sdk/notificationhubs/notification-hubs/src/api/sendNotification.ts
sdk/notificationhubs/notification-hubs/src/utils/constants.ts

- https://github.com/Azure/azure-sdk-for-js/issues/25397
- https://github.com/Azure/azure-sdk-for-js/issues/25396
Removes the usage of the `uuid` generation to use `@azure/core-util`
- #25400
- https://github.com/Azure/azure-sdk-for-js/pull/25413

[notification hubs] Fixing UUID generation

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/inMemoryCheckpointStore.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/test/internal/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/public/amqpAnnotatedMessage.spec.ts
sdk/eventhub/event-hubs/test/public/eventData.spec.ts
sdk/eventhub/event-hubs/test/public/utils/testInMemoryCheckpointStore.ts

- Replaces calls to `generate_uuid` from rhea-promise with calls to `getRandomName`
- Replaces calls to `uuid` in public tests with `randomUUID`
- Removes the dependency on `uuid`
[Successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2668672&view=results)

[Event Hubs] Remove uuid dep

---

sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/test/public/node/searchClient.spec.ts

This change allows for the service to be the source of truth in validating the service version. The client is tested against the latest stable and preview APIs, and older API versions are not guaranteed by the SDK to be backward compatible. 
Fixes #24145

[Search] Remove service version checks

---

sdk/communication/communication-alpha-ids/.nycrc

Enable the Code Coverage tab report by adding the missing .nycrc file to Alpha Sender Ids

[Communication][communication-alpha-ids] enable code coverage report in alpha sender ids tests

---

sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
sdk/web-pubsub/web-pubsub-express/review/web-pubsub-express.api.md
sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/src/cloudEventsProtocols.ts

@azure/web-pubsub-express
https://github.com/Azure/azure-sdk-for-js/issues/24515
The Azure Web PubSub service defines it's protocol sending CloudEvents out as `query`, however in TS we defined it as `queries` in the interface. To resolve the inconsistency between them, add a `query` property to the interface but mark it as obsolete and mean why set the value of `queries` as the value of `query` to make the property work.

Fix the query property inconsistency with the protocol

---

sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/src/models.ts

- Fix #24128
Azure Germany is deprecated. This PR marks the corresponding audience in `KnownContainerRegistryAudience` as deprecated.

[ACR] Deprecate support for Azure Germany

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/Clients.ts

Fixed an issue of: StoragePipelineOptions is not passed into constructors for blob clients correctly when using undefined as credential parameter.
Repro code is like:
```
const options: StoragePipelineOptions = { keepAliveOptions: { enable: false }, retryOptions: { maxTries: 1, maxRetryDelayInMs: 0, retryDelayInMs: 0 } }
const blockBlobClient = new BlockBlobClient(sasUrl.sasTokenUri, undefined, options);
```
The issue is because: 
BlobClient and BlockBlobClient supports constructor with parameters like:
```
constructor(
connectionString: string,
containerName: string,
blobName: string,
// Legacy, no fix for eslint error without breaking. Disable it for this interface.
/* eslint-disable-next-line @azure/azure-sdk/ts-naming-options*/
options?: StoragePipelineOptions
);
constructor(
url: …
```

[Storage] Fixed an issue of: StoragePipelineOptions is not passed constructor correctly

---

sdk/containerregistry/container-registry/CHANGELOG.md

Changelog entry and date for upcoming ACR beta.

[ACR] Prepare beta release

---

sdk/eventhub/eventhubs-checkpointstore-table/CHANGELOG.md
sdk/eventhub/eventhubs-checkpointstore-table/package.json

`@azure/eventhubs-checkpointstore-table`

[eventhubs-checkpointstore-table] upgrade dependency `@azure/data-tables` to `^13.2.2`

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/diagnostics/instrumentServiceBusMessage.ts
sdk/servicebus/service-bus/src/diagnostics/tracing.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/receiverCommon.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
sdk/servicebus/service-bus/test/internal/unit/tracing.spec.ts

- @azure/service-bus
Updating to latest [OTEL messaging standards](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes).  This is also explained in a gist from @lmolkova [here](https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92)

[service bus] Updating to latest OTEL for Messaging

---

.vscode/cspell.json

as the file mostly contains aliases and paths, with a handful comments. There's little value spell-checking it.  Also aliases will cause a lot of noises.  This PR excludes it from being checked.

[engsys] exclude `.github/CODEOWNERS` from spell checking

---

common/tools/dev-tool/src/commands/test-proxy/index.ts

Fixes the following error
Updates the index file by adding the "init" command, unsure how we missed the first time.
Fixes #25610

[Test Proxy] Init fix - "test-proxy init" command unrecognized error

---

sdk/metricsadvisor/perf-tests/ai-metrics-advisor/package.json
sdk/metricsadvisor/perf-tests/ai-metrics-advisor/test/listAnomalies.spec.ts
sdk/metricsadvisor/perf-tests/ai-metrics-advisor/test/listIncidents.spec.ts

This allows us to remove transitive dependency on core-http v1

[perf-tests][metrics-advisor] upgrade to depend on `ai-metrics-advisor` GA version

---

sdk/test-utils/recorder/ASSET_SYNC_MIGRATION.md

Adding a new section to show how to Inspect updates to the recordings in VS Code through the source control view.

[Recorder][Asset Sync] Inspecting updates to the recordings in VS Code

---

samples/web-workers/js/worker.js
samples/web-workers/ts/worker.ts

Due to security reason we don't want to have secrets in the browsers. This PR updates the web-worker sample to use container SAS url to construct storage blob clients.

[samples][web-worker] use SAS url in browsers

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/samples-dev/createCallOperations.ts
sdk/communication/communication-call-automation/src/callAutomationClient.ts
sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
sdk/communication/communication-call-automation/src/callConnection.ts
sdk/communication/communication-call-automation/src/callMedia.ts
sdk/communication/communication-call-automation/src/callRecording.ts
sdk/communication/communication-call-automation/src/contentDownloader.ts
sdk/communication/communication-call-automation/src/models/events.ts
sdk/communication/communication-call-automation/src/models/models.ts
sdk/communication/communication-call-automation/src/models/options.ts
sdk/communication/communication-call-automation/src/models/responses.ts
sdk/communication/communication-call-automation/test/callAutomationClient.spec.ts
sdk/communication/communication-call-automation/test/callConnection.spec.ts
sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
sdk/communication/communication-call-automation/test/callRecordingClient.spec.ts
sdk/communication/communication-call-automation/test/utils/connectionUtils.ts
sdk/communication/communication-call-automation/test/utils/mockClient.ts
sdk/communication/communication-call-automation/test/utils/recordedClient.ts

Communication-call-automation
feedback from azure board review
General
- callInvite is now an interface instead of a class
- rename target/s to targetParticipant/s
- append EventData to events
- event parser parse is now a function instead of a class
- update uri to url 
CallMediaUpdates
- move all required params in options to method signature 
CallConnectionUpdates
- rename callConnectionImpl to callConnection
- getParticipant takes a CommunicationIdentifier instead of a participantMri string. 
CallRecordingUpdates
- remove "recording from method names" ex startRecording is now start.

azure board review comments

---

eng/pipelines/docindex.yml

Add a call after ToC generation to verify that the json files contain the required members which cannot be null or empty.

Add task to verify json files contain required members after ToC generation

---

sdk/notificationhubs/notification-hubs/README.md
sdk/notificationhubs/notification-hubs/migrationguide.md

Adds a migration guide so we can deprecate azure-sb and provide them onboarding to @azure/notification-hubs.

[notification hubs] Add migration guide

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/partitionReceiver.ts

when long-lived parent signal is holding onto all it's child signal
https://github.com/Azure/azure-sdk-for-js/issues/12030
This PR adds a listener to the abort event directly.

[EventHubs] workaround known memory leak in azure/AbortController

---

design/dev-tool-migrations.md

This pull request adds a design document for an automated migration framework that, if accepted, will be integrated into `dev-tool`.
I've come to view a tool like this as required to support continued incremental updates across the monorepo.
I won't describe the tool too much in this description, since it's described in the included Markdown file, but it basically works like a git merge:
- dev-tool tracks a list of migrations, `dev-tool migrate --list` will show the ones that haven't been applied to a package.
- you "merge" the migrations into a package using `dev-tool migrate`. Migrations can be fully or partially automatic _OR_ manual. The tool will tell you what to do.
- if the migration fails, it is suspended and you have the chance to fix it and then run `dev-tool migrate --continue` …

[design/dev-tool] automated migration framework

---

common/tools/dev-tool/src/util/samples/configuration.ts

- `@azure-tools/dev-tool`
Fixes an issue with publishing samples where the `//metadata` field is not present in the `package.json`. This was the error:
```
[publish] Cannot read properties of undefined (reading 'sampleConfiguration')
```

[dev-tool] Fix TypeError when `//metadata` field not present in package.json

---

common/tools/dev-tool/src/util/testProxyUtils.ts

- `@azure-tools/dev-tool`
Fix for test proxy issue with argument parsing where `-l` was not being recognized correctly.

[dev-tool][recorder] Use full argument name for `storage-location` when starting test proxy

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/searchClient.ts

As per discussion with the architects offline, renaming the generic argument to `SearchClient` to `TModel`.

[Search] Rename `Model` to `TModel`

---

sdk/containerregistry/container-registry/README.md
sdk/containerregistry/container-registry/recordings/node/containerregistrycontentclient/recording_can_upload_oci_manifest.json
sdk/containerregistry/container-registry/recordings/node/containerregistrycontentclient/recording_can_upload_oci_manifest_with_tag.json
sdk/containerregistry/container-registry/recordings/node/containerregistrycontentclient/recording_must_specify_media_type_when_uploading_docker_manifest.json
sdk/containerregistry/container-registry/review/container-registry.api.md
sdk/containerregistry/container-registry/samples-dev/deleteBlob.ts
sdk/containerregistry/container-registry/samples-dev/downloadImage.ts
sdk/containerregistry/container-registry/samples-dev/uploadManifest.ts
sdk/containerregistry/container-registry/samples/v1/javascript/deleteBlob.js
sdk/containerregistry/container-registry/samples/v1/javascript/downloadImage.js
sdk/containerregistry/container-registry/samples/v1/javascript/uploadManifest.js
sdk/containerregistry/container-registry/samples/v1/typescript/src/deleteBlob.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/downloadImage.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/uploadManifest.ts
sdk/containerregistry/container-registry/src/content/containerRegistryContentClient.ts
sdk/containerregistry/container-registry/src/content/models.ts
sdk/containerregistry/container-registry/test/internal/basic.spec.ts
sdk/containerregistry/container-registry/test/public/containerRegistryContentClient.spec.ts

- Should fix #25757
- As a result of changes introduced in #25592, the properties in `OciAnnotations` are not being remapped. This PR updates `OciAnnotations` so that the property names correspond to the specification.
- `isOciImageManifest` was returning `false` for OCI image manifests that did not have a media type specified, even though this is an optional property. This PR makes `isOciImageManifest` more robust plus adds tests for different kinds of manifests to make sure it's doing what it should.

[ACR] Model updates and improvements to `isOciImageManifest`

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/package.json
sdk/monitor/monitor-query/recordings/browsers/logsqueryclient_live_tests/recording_includequerystatistics.json
sdk/monitor/monitor-query/recordings/browsers/logsqueryclient_live_tests/recording_includerenderincludevisualization.json
sdk/monitor/monitor-query/recordings/browsers/logsqueryclient_live_tests__server_timeout/recording_servertimeoutinseconds.json
sdk/monitor/monitor-query/recordings/node/logsqueryclient_live_tests/recording_includequerystatistics.json
sdk/monitor/monitor-query/recordings/node/logsqueryclient_live_tests/recording_includerenderincludevisualization.json
sdk/monitor/monitor-query/recordings/node/logsqueryclient_live_tests__server_timeout/recording_servertimeoutinseconds.json
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/src/constants.ts
sdk/monitor/monitor-query/src/generated/logquery/src/azureLogAnalyticsContext.ts
sdk/monitor/monitor-query/src/generated/metrics/src/monitorManagementClientContext.ts
sdk/monitor/monitor-query/src/generated/metricsdefinitions/src/monitorManagementClientContext.ts
sdk/monitor/monitor-query/src/generated/metricsnamespaces/src/monitorManagementClientContext.ts
sdk/monitor/monitor-query/src/models/constants.ts
sdk/monitor/monitor-query/test/public/metricsQueryClient.spec.ts

The hotfix resolves these 2 issues:
- Fixed the aliases spelling error for a `Durations` constant for `fortyEightHours`.
- Fixed the ISO8601 values for `twentyFourHours` and `fortyEightHours` to reflect `P24H` and `P48H` respectively, instead of `P1D` and `P2D`.

[Monitor Query] Merge Hotfix/monitor query 1.0.4 to main and update version for next release 1.1.0

---

common/config/rush/common-versions.json
sdk/core/core-http/src/util/xml.browser.ts
sdk/core/core-xml/src/xml.browser.ts

`@azure/core-xml`, `@azure/core-http`
Fixes issue #24872.
Upgrading to @trusted-types v2.0.3 caused compilation error. While it is breaking, it surfaces an issue that we can address by adding propert parameter type.
Pinning to v2.0.2 which isn't desirable as we want to stay on latest dependency versions.

[core] add proper parameter type for TrustedTypePolicy `createHTML` callback

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/serialization.ts
sdk/search/search-documents/test/internal/serialization.spec.ts

#25777 
Some valid ISO8601 date strings were not being deserialized into `Date` objects. This fixes the deserialization behavior for ISO8601 date strings with millisecond values specified with under 3 digits of precision.

[Search] Fix ISO8601 deserialization

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/src/serialization.ts
sdk/search/search-documents/test/internal/serialization.spec.ts

#25777 
Some valid ISO8601 date strings were not being deserialized into `Date` objects. This fixes the deserialization behavior for ISO8601 date strings with millisecond values specified with under 3 digits of precision.

[Search GA] Fix ISO8601 deserialization

---

sdk/search/search-documents/package.json

Format checking is broken on this hotfix branch. Disabling for release, leaving it to be fixed with the upcoming rebase onto main

[Search] Skip broken format check for hotfix release

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/workloadIdentityCredential.ts

TypeError: Cannot read properties of undefined (reading 'tenantId')
at new WorkloadIdentityCredential (.../@azure/identity/dist/index.js:1999:60)
at new DefaultWorkloadIdentityCredential (...@azure/identity/dist/index.js:3589:13)
- #25827
- #25402

[Identity] Fix undefined dereference

---

sdk/containerregistry/container-registry/src/content/containerRegistryContentClient.ts
sdk/containerregistry/container-registry/src/utils/helpers.ts
sdk/containerregistry/container-registry/src/utils/retriableReadableStream.ts

- Fix #25645
Add extra validation to `downloadBlob` and `getManifest`:
- Restrict manifest size to 4 MB
- Throw early if bytes read during `downloadBlob` exceed the value in the
`Content-Length` header
Based somewhat on the [Java PR for the same thing](https://github.com/Azure/azure-sdk-for-java/pull/34737), but without validation of the `Content-Range` header since we are using optimistic download.

[ACR] Harden downloadBlob and getManifest validation

---

sdk/search/search-documents/package.json

The release pipeline failed to bump the version of this package. This change updates the package's metadata so it'll have the correct behavior next time.

[Search] Fix constant paths for version bumping

---

sdk/monitor/monitor-query/README.md

Now that the resource-centric logs query feature exists, a workspace isn't required. Update the prereqs section accordingly.

Update logs query prereqs

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/callMedia.ts
sdk/communication/communication-call-automation/src/generated/src/models/index.ts
sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
sdk/communication/communication-call-automation/src/models/events.ts
sdk/communication/communication-call-automation/swagger/README.md
sdk/communication/communication-call-automation/test/callMediaClient.spec.ts

@azure/communication-call-automation
API review fixes for send and continuous DTMF.
Added operation_context in ContinuousDtmfRecognitionToneFailed, ContinuousDtmfRecognitionToneReceived
- Removed participant_id from ToneInfo
- Changed args order for send_dtmf
- Auto generated code as per latest swagger
Yes
https://github.com/Azure/azure-rest-api-specs/commit/25ea7bc8f78804ee079bd41753d237feaf2777d7
https://github.com/Azure/azure-rest-api-specs/commit/885b18fa094fbb953b1a0cb77c52536a8d745be5

Auto gererated code with latest swagger changes

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

None
Now new features/bug fixes are added to this PR. The previous release 4.11.1 added new system events to the SDK. Normally, we update the minor version and not the patch version for such releases. But, since only the patch version has been updated for that release, in order to maintain consistency, on the release guidelines, I am updating the minor version and releasing a new version of the SDK through this PR.
No special design consideration.
Very trivial update of Minor Version. No test cases are required.
None
None
@xirzec Please review and approve. Thanks

[@azure/eventgrid] Update EG Minor Version

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/serviceClient.ts
sdk/core/core-client/test/serviceClient.spec.ts
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/src/util/constants.ts
sdk/core/core-http/test/serviceClientTests.ts

It is possible that credential scopes are not in the format of valid URL.  It is also noted in the doc that there are shorter form of scope https://learn.microsoft.com/EN-US/azure/active-directory/develop/scopes-oidc
>In requests to the authorization, token or consent endpoints for the Microsoft Identity platform, if the resource identifier is omitted in the scope parameter, the resource is assumed to be Microsoft Graph. For example, `scope=User.Read` is equivalent to `https://graph.microsoft.com/User.Read`.
Related issue: #25881

[Core] remove URL validations on credential scopes

---

sdk/notificationhubs/notification-hubs/src/api/deleteRegistration.ts

According to the docs, the delete API expects a `HTTP DELETE /registrations/<registrationId>`, but the got uses `HTTP GET`, hence delete does not work.
https://learn.microsoft.com/en-us/rest/api/notificationhubs/delete-registration
https://www.npmjs.com/package/@azure/notification-hubs
N/A
According to the docs, the delete API expects a `HTTP DELETE /registrations/<registrationId>`, but the got uses `HTTP GET`, hence delete does not work.
https://learn.microsoft.com/en-us/rest/api/notificationhubs/delete-registration

Updates notification-hubs deleteRegistration so that it actually HTTP DELETEs.

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/serviceClient.ts
sdk/core/core-client/test/serviceClient.spec.ts
sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/serviceClientTests.ts

It is possible that credential scopes are not in the format of valid URL. It is also noted in the doc that there are shorter form of scope https://learn.microsoft.com/EN-US/azure/active-directory/develop/scopes-oidc
>In requests to the authorization, token or consent endpoints for the
Microsoft Identity platform, if the resource identifier is omitted in the scope parameter, the resource is assumed to be Microsoft Graph. For example, `scope=User.Read` is equivalent to
`https://graph.microsoft.com/User.Read`.
Related issue: #25881

Port [Core] remove URL validations on credential scopes (#25896)

---

sdk/identity/identity/README.md

**Summary of changes**
- Add API ref links for the workload identity and azd credentials
- Alphabetize table rows for dev tool credentials
- Switch from `require` to `import` in code samples

Update Azure Identity lib README

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/assert.ts
sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts

Added envelope sent to Breeze endpoint including OpenTelemetry resource attributes

[Azure Monitor OpenTelemetry Exporter] Add OTel resource metric envelope

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/Declarations/Constants.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts

This PR allows statsbeat to be disabled via setting an environment variable.
Yes, added the relevant test to determine that statsbeat is disabled when the environment variable is set.

Add Ability to Disable Statsbeat in the Exporter

---

.vscode/cspell.json
common/config/rush/pnpm-lock.yaml
sdk/eventgrid/eventgrid/.eslintrc.json
sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/cadl-generated/EventGridClient.ts
sdk/eventgrid/eventgrid/src/cadl-generated/api/EventGridContext.ts
sdk/eventgrid/eventgrid/src/cadl-generated/api/index.ts
sdk/eventgrid/eventgrid/src/cadl-generated/api/models.ts
sdk/eventgrid/eventgrid/src/cadl-generated/api/operations.ts
sdk/eventgrid/eventgrid/src/cadl-generated/common/interfaces.ts
sdk/eventgrid/eventgrid/src/cadl-generated/index.ts
sdk/eventgrid/eventgrid/src/cadl-generated/logger.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/clientDefinitions.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/eventGridClient.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/index.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/isUnexpected.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/models.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/outputModels.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/parameters.ts
sdk/eventgrid/eventgrid/src/cadl-generated/rest/responses.ts
sdk/eventgrid/eventgrid/src/eventGridClientV2.ts
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/models.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

@azure/eventgrid 
NA
1. The EventGrid Service team has introduced a new Client called `EventGridClient` with 4 apis - `publishCloudEvent`, `publishCloudEvents`, `receiveCloudEvents`, `acknowledgeCloudEvents`, `releaseCloudEvents` and `rejectCloudEvents`. Now, the service is represented using the [new CADL specification](https://github.com/Azure/azure-rest-api-specs/tree/feature/eventgrid/typespec/specification/eventgrid/Azure.Messaging.EventGrid). This SDK, in this PR, has been generated using the new [JS SDK CADL Generator](https://github.com/Azure/autorest.typescript/tree/main/packages/typespec-ts). 
2. During the generation process, I had a few issues in the generation process. Seperate issues have been filed for the same and many of them have already been resolved. For the remaining …

[@azure/eventgrid] - Azure EventGrid Beta Release V4.13.0-beta.1

---

sdk/openai/openai/samples-dev/chatCompletions.ts
sdk/openai/openai/samples-dev/completionsRest.ts
sdk/openai/openai/samples-dev/listChatCompletions.ts
sdk/openai/openai/samples-dev/listCompletions.ts
sdk/openai/openai/samples-dev/openAi.ts
sdk/openai/openai/samples/v1-beta/javascript/chatCompletions.js
sdk/openai/openai/samples/v1-beta/javascript/completions.js
sdk/openai/openai/samples/v1-beta/javascript/listChatCompletions.js
sdk/openai/openai/samples/v1-beta/javascript/listCompletions.js
sdk/openai/openai/samples/v1-beta/javascript/openAi.js
sdk/openai/openai/samples/v1-beta/typescript/src/chatCompletions.ts
sdk/openai/openai/samples/v1-beta/typescript/src/completions.ts
sdk/openai/openai/samples/v1-beta/typescript/src/listChatCompletions.ts
sdk/openai/openai/samples/v1-beta/typescript/src/listCompletions.ts
sdk/openai/openai/samples/v1-beta/typescript/src/openAi.ts

And adds a sample to use the rest-level client.

[OpenAI] Update samples

---

common/tools/dev-tool/src/commands/migrate.ts
common/tools/dev-tool/src/commands/run/testNodeJSInput.ts
common/tools/dev-tool/src/migrations/sample-config-to-metadata.ts
common/tools/dev-tool/src/util/migrations.ts
common/tools/dev-tool/src/util/resolveProject.ts

It is possible that package.json (e.g., some core packages) doesn't have metadata yet.  This PR handles the case.
dev-tool

[dev-too] Fix migration error for packages without metadata section

---

sdk/communication/test-resources/test-resources.json

sdk/communication/*
Live test pipelines are failing due to the failure of deployment test resources in INT environment for all the modalities across all the platforms since the Communication Services API version : 2020-08-20-preview is obsolete, which was recently removed from support.
* Updating CommunicationServices API version to '2023-03-31' since the previous API version : 2020-08-20-preview is obsolete, and recently removed from support.
* Updating resource type 'roleAssignments' in the namespace 'Microsoft.Authorization' to latest api version : '2022-04-01'.

Communication Resource | API Version Update

---

sdk/communication/communication-job-router/review/communication-job-router.api.md
sdk/communication/communication-job-router/src/models/models.ts
sdk/communication/communication-job-router/src/routerClient.ts

[JobRouter] Minor fix to API

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/log.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.test.ts

Added support for Application Insights events PageView, Availability, Event, Exception and Message

[Azure Monitor] Add support for Application Insights log events

---

sdk/openai/openai/src/rest/openAIClient.ts

@azure/openai
https://github.com/Azure/azure-sdk-for-js/issues/26021
It's evident that when we use an OpenAI key
https://github.com/Azure/azure-sdk-for-js/blob/ad7b405ee43d76778f3f65ffd40f898d6481ee7e/sdk/openai/openai/src/OpenAIClient.ts#L113-L119
We set the credentials to use `apiKeyHeaderName: "Authorization"`, however when you create the client it completely overrides the options. This leads to the following error from openAI's API:
```
error: {
message: "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from …
```

[@azure/openai] fixed openAI credentials

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

switching from ~ version to ^ so we can get minor version upgrades from the bot.
dev-tool

[engsys][dev-tool] upgrade dependency `yaml` version to `^2.3.0`

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_appendblock__append_large_block.js
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_datalakedirectoryclient_create_with_all_parameters.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_datalakefileclient_create_with_all_parameters.json
sdk/storage/storage-file-datalake/recordings/browsers/datalakepathclient/recording_read_a_file_with_permissions_set.json
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_datalakedirectoryclient_create_with_all_parameters.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_datalakefileclient_create_with_all_parameters.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient/recording_read_a_file_with_permissions_set.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_datalakedirectoryclient_create_with_acl.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_datalakedirectoryclient_create_with_group.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_datalakedirectoryclient_create_with_owner.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_datalakefileclient_create_with_acl.js
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_datalakefileclient_create_with_group.js
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

Added support for HNS permission

Added support for HNS permission 

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
sdk/keyvault/keyvault-keys/test/internal/crypto.spec.ts

- Fixes #26001
Local cryptography relies on having permission to get a key from the Key Vault in order to perform the operation. But it is possible, using a Key Vault access policy, for the get permission to not be granted even if other operations are permitted (e.g. sign, verify, encrypt, decrypt...). This scenario doesn't work at the moment because we assume that the get permission is always present, and don't handle the 403 if we can't get the key.
This PR fixes the issue by handling the error and falling back to remote-only operations if the get permission isn't granted.

[keyvault] CryptographyClient: fall back to remote operations if missing get permission

---

common/tools/dev-tool/src/commands/migrate.ts

otherwise the ongoing git commit could cause subsequent migration to fail when another git operation is invoked
dev-tool

[dev-tool] await onMigrationSkipped

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/recorder.ts

- Fixes #25946
Add some more user-friendly error messages based on recent feedback:
- Clarify error when attempting to redirect a request but the recorder has not been started
- Forward mismatch error when recording file cannot be found during `start` call in playback mode
- Add more descriptive message in the case that the test proxy has not been started before running the tests

[recorder] Improve error messages

---

sdk/eventhub/event-hubs/samples/v5/browser/package.json
sdk/eventhub/event-hubs/samples/v5/browser/webpack.config.js

The old version of `buffer` that webpack bundled has a bug causing sample to fail.
https://github.com/feross/buffer/issues/237
This PR upgrades webpack to v5 and adds required polyfills as in v5 they are no longer built-in.

[EventHubs] fix browser sample

---

sdk/eventhub/event-hubs/README.md
sdk/servicebus/service-bus/README.md

As they are dependencies of the libraries and will be installed when installing EH or SB packages.

[Docs][EH,SB] update README to not install buffer and process for browsers

---

eng/pipelines/templates/stages/platform-matrix.json

Node.js 20 will enter long-term support (LTS) in October, we're adding support for it now (6 months prior)

Add support for Node 20

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
sdk/eventhub/event-hubs/src/models/private.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/partitionReceiver.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/internal/cancellation.spec.ts
sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts

Updates the partition receiver to use Rhea's prefetch window instead of manually fetching the exact number of events needed. It also adds a `subscribe` option, `prefetchCount`, that controls the max number of events to prefetch.
Live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2814550&view=results
Related issue: https://github.com/Azure/azure-sdk-for-js/issues/26055

[Event Hubs] Prefetch events

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/logger.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/models/private.ts
sdk/eventhub/event-hubs/src/models/public.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/partitionReceiver.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/internal/cancellation.spec.ts
sdk/eventhub/event-hubs/test/internal/client.spec.ts
sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts
sdk/eventhub/event-hubs/test/internal/receiveBatch.spec.ts
sdk/eventhub/event-hubs/test/public/eventHubBufferedProducerClient.spec.ts
sdk/eventhub/event-hubs/test/public/eventHubConsumerClient.spec.ts

Resolves https://github.com/Azure/azure-sdk-for-js/issues/16406
Related to https://github.com/Azure/azure-sdk-for-js/issues/26057
Adds an option to set the client identifier.
Live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2827224&view=results

[Event Hubs] Support user-provided client identifier

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-xml/package.json

- @azure/service-bus
- @azure/core-xml
- fast-xml-parser
https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-5668858
Snyk's service has identified a ReDOS issue with the currently used version of fast-xml-parser and says that it's been fixed in version 4.2.4
Package upgrade only

Fix fast-xml-parser ReDoS vulnerability

---

common/tools/dev-tool/src/commands/run/bundle.ts

instead of hard-coded `dist/index.js`.

[dev-tool] use the `main` field as bundled cjs output name

---

common/tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-main-is-cjs.md
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-main-is-cjs.ts
common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-main-is-cjs.ts

currently only index.js is allowed.

[eslint-plugin] update rule to allow .cjs main entry

---

eng/scripts/Language-Settings.ps1
eng/scripts/docs/Docs-ToC.ps1

In the past we've been able to assume that all packages which had metadata JSON files had shipped from our repos/engsys and had a `DirectoryPath` field with useful information in it. In the case of ToC, we use that `DirectoryPath` field to arrive at a package-level readme filename for use in the ToC. However, if that field is empty we want to fall back on other heuristics of arriving at the filename. 
Sample broken build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2824162&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=51aa7976-5924-5040-41de-f124a4debc20&l=162
Sample working build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2827344&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739 (canceled before it kicks off the daily docs build, that's not …

Fix: Handle empty DirectoryFolder metadata property

---

.devcontainer/devcontainer.json
.devcontainer/init.sh

Adds a script `init.sh` to bootstrap new Codespaces. At the moment, the script does the following:
- Installs Node LTS based on the version in `.nvmrc` and sets it as the default Node version
- Installs Rush and Autorest
- Runs `rush update`
- Installs Powershell (for running engsys scripts and asset sync migration)

[engsys] Add bootstrap script for Codespaces

---

sdk/remoterendering/test-resources.json

Previous unit test arm template was using the wrong API version.

Azure Remote Rendering: Fix test setup

---

eng/emitter-package-lock.json
eng/emitter-package.json

Pin dependencies and add emitter-package-lock.json lockfile
fixes https://github.com/Azure/azure-sdk-for-js/issues/26197
fixes https://github.com/Azure/azure-sdk-for-js/issues/26198

Pin dependencies and add emitter-package-lock.json lockfile

---

sdk/storage/storage-file-share/assets.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/generated/src/models/index.ts
sdk/storage/storage-file-share/src/generated/src/models/mappers.ts
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClient.ts
sdk/storage/storage-file-share/src/generatedModels.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts
sdk/storage/storage-file-share/test/utils/testutils.common.ts

- port tests
- use isBrowser from core-util
- port the source changes
- re-generate client
- update test resource names to use different variable names. New recorder
unique names are slightly different from previous version and cause same name to 
be retrieved for "dir" variable.
- add recordings

[storage] Port PR #24759 from storage/stable

---

sdk/identity/identity/samples/AzureCacheForRedis/ioredis.md
sdk/identity/identity/samples/AzureCacheForRedis/node-redis.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/24791
- updated scope for public preview
- Send Redis auth command 2 to 5 mins before expiry to prevent costly connection operation when token expires

[Identity] update redis samples for public preview scope

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/package.json
sdk/core/core-amqp/review/core-amqp.api.md
sdk/core/core-amqp/src/auth/tokenProvider.ts
sdk/core/core-amqp/src/util/hmacSha256.browser.ts
sdk/core/core-amqp/src/util/hmacSha256.ts
sdk/core/core-amqp/test/tokenProvider.spec.ts

- @azure/core-amqp
This migrates the core-amqp project to use the native crypto from both the web and Node/Deno/Bun so that we can use the [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) for platforms that support it, as well as the Node.js crypto library.  This removes the jssha npm package which currently has issues with ESM and TypeScript types.
This change forces the `TokenProvider` to change with the `getToken` to be async as the SubleCrypto methods used of `sign` and `importKey` are both async methods.

[core-amqp] Update TokenProvider to use native crypto

---

eng/tools/versioning/VersionUtils.js
sdk/core/core-xml/CHANGELOG.md
sdk/core/core-xml/package.json

Our dev-tool migration adds metadata section to package.json if they don't have them yet. But the added metadata section doesn't contain the `constantPaths`. This broke the version increment script for some core packages, including core-xml.
This PR fixes the script so it can increment those affected packages properly.

[core-xml] increment version after release

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts

#26293
A user reported `SearchIndexClient` sharing a `userAgentPolicy` with the `SearchClient`s it creates through `SearchIndexClient.getSearchClient`. This client is not cached, and the constructors of both types of clients modify the `userAgentPolicy` in place, causing a user agent to be recursively prepended until the request exceeds the maximum size allowed by the service. 
Adding the SDK version as a user agent is now handled by the generated library, so this change just removes the buggy implementation in the authored clients.

[Search] Fix all clients adding one or more duplicate user agents

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/karma.conf.js
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/recordings/browsers/event_grid_client_v2/recording_publishes_a_single_cloud_event.json
sdk/eventgrid/eventgrid/recordings/browsers/event_grid_client_v2/recording_publishes_multiple_cloud_events.json
sdk/eventgrid/eventgrid/recordings/browsers/event_grid_client_v2/recording_rejects_a_cloud_event.json
sdk/eventgrid/eventgrid/recordings/browsers/event_grid_client_v2/recording_releases_a_cloud_event.json
sdk/eventgrid/eventgrid/recordings/node/event_grid_client_v2/recording_publishes_a_single_cloud_event.json
sdk/eventgrid/eventgrid/recordings/node/event_grid_client_v2/recording_publishes_multiple_cloud_events.json
sdk/eventgrid/eventgrid/recordings/node/event_grid_client_v2/recording_rejects_a_cloud_event.json
sdk/eventgrid/eventgrid/recordings/node/event_grid_client_v2/recording_releases_a_cloud_event.json
sdk/eventgrid/eventgrid/src/eventGridClientV2.ts
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md
sdk/eventgrid/eventgrid/test.env
sdk/eventgrid/eventgrid/test/public/eventGridClientV2.spec.ts
sdk/eventgrid/eventgrid/test/public/utils/recordedClient.ts
sdk/eventgrid/test-resources.json

N/A
In the EventGrid V2 Beta Version, we have an API called `publishCloudEvents`. In this API, each of the event (from parameters) must be converted and pushed to the `eventsWireModel` array. Now, while pushing it, a wrong method is called on the array. Instead of calling `push` method, `concat` method is called which causes the array to be empty and causes issue. This PR changes the method to `push`.
Integration Test Cases have been added for each API in EventGrid Client. The associated recordings have been added to the PR.
**Note: Since this is a Bug Fix release, I have updated the Version from `4.13.0-beta.1` to `4.13.0-beta.2`.**
The design is simple and straightforward. No special concern.
Yes. The test cases have been added for each API of the EventGrid client.
N/A …

[@azure/eventgrid] Fix the Push Issue with the PublishCloudEvents API

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/withAuth.ts

In our previous refactoring, we accidentally dropped the `getToken()` calls when renewing token.  This PR adds the calls back.
The internal `TokenInfo` property `timeoutInMs` is renamed to `timeToLiveInMs` to avoid confusion with operation timeout parameter `timeoutInMs`.

[EventHub] Fix a regression in token renewal

---

common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-opentelemetry/src/traces/azureFnHook.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standadMetrics.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/azureFnHook..test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts

Functionality for @azure/monitor-opentelemetry package
Adding Azure Fn code to handle auto correlation when running in that environment

[Azure Monitor OpenTelemetry] Add Azure Functions Correlation Hook

---

sdk/communication/communication-call-automation/src/callMedia.ts

Example of Call using this fix:
https://ngc.skype.net/call/0716907d-3e06-44dd-a85d-16d0479f8522/
New request sent:
```json
{
"recognizeinputtype": "speechOrDtmf",
...
}
```
Event Received:
```json
[
{
"id": "edcca2d3-7997-4d4a-bcb5-8cb5c6b08bef",
"source": "calling/callConnections/411f0b00-56cd-47c6-9388-05f08399937b",
"type": "Microsoft.Communication.RecognizeCompleted",
"data": {
"operationContext": "context",
"resultInformation": {
"code": 200,
"subCode": 8531,
"message": "Action completed, max digits received."
},
"recognitionType": "dtmf",
"collectTonesResult": {
"tones": [
"two"
]
},
"dtmfResult": {
"tones": [
"two"
]
},
...
}
]
```

Using the right type of Recognition

---

sdk/keyvault/perf-tests/keyvault-secrets/test/secretTest.ts
sdk/test-utils/perf/GettingStarted.md

`configureClientOptionsCoreV1` was removed in the perf framework along with the core-http removal from the repo.
But the keyvault perf test builds were excluded, which left this unnoticed.

[Keyvault Secrets] [Perf Tests] Fix build

---

sdk/cosmosdb/cosmos/package.json

so it can get non-breaking minor updates from rush automation.

[engsys][cosmos] switch dev dependency `@sinonjs/fake-timers` to use caret version

---

sdk/monitor/monitor-opentelemetry/review/monitor-opentelemetry.api.md
sdk/monitor/monitor-opentelemetry/src/client.ts
sdk/monitor/monitor-opentelemetry/src/shared/config.ts
sdk/monitor/monitor-opentelemetry/src/shared/types.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/jsonConfig.test.ts

Optional properties in InstrumentationOptions  allow customer to only specify settings they are interested
Typo in tracer provider method

[Azure Monitor OpenTelemetry] Fix issues with types

---

sdk/communication/test-resources/test-resources.json

ACS SDKs test pipelines are failing in executing samples. The `"COMMUNICATION_CONNECTION_STRING"` is missing from the test resources from the previous changes.
Add the `"COMMUNICATION_CONNECTION_STRING"` into the test resources to fix the test pipeline.

[Communication] Update ACS test-resources to fix executing samples in pipeline

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/src/getClient.ts
sdk/core/core-client-rest/test/getClient.spec.ts

`@azure-rest/core-client`
https://github.com/Azure/autorest.typescript/issues/1916
Since we were using spread syntax on `RequestParameters` if an `undefined` value was passed this would take precedence over the client option, which was not expected.
This PR switches the order of when the spread happens while still pulling the value from `RequestParameters` when present.
Yes!

[@azure-rest/core-client] Correctly handle allowInsecureConnection override

---

common/tools/dev-tool/src/commands/run/bundle.ts
common/tools/dev-tool/src/util/resolveProject.ts

This package modifies the bundling logic slightly so that after checking for a package.json `main` field it will also look at the package.json `exports["."].require` field.

[dev-tool] Honor exports when bundling.

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/searchClient.ts

Some core client options were not being passed to the generated client. This was caused by a few options not being extracted by a helper `extractOperationOptions`, which has been removed in this PR since duck typing seems to be sufficient here. Removing the function and using duck typing with the user-provided options should prevent options that we expose from being left out in the future.

[Search] Fix `serializerOptions` and `onResponse` options for `SearchClient` methods

---

sdk/communication/communication-call-automation/src/callAutomationClient.ts
sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
sdk/communication/communication-call-automation/swagger/README.md

- Duplicated lib info in UserAgent.
- Fixed naming of package in autorest to be correct

[ACS][CallAutomation] Fixing duplicated lib info fix

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/assets.json
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/indexModels.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/test/public/node/searchClient.spec.ts

Pending #23627 being validated and merged into stable, customers are blocked on the inability to select fields that aren't at the top level of a document. This change is a stopgap measure - `select` and `searchFields` have been declared with `string[]` type. This removes the existing type narrowing, but introduces that missing behavior.
Depends on #25583

[Search] Hotfix for nested select and searchFields

---

sdk/monitor/monitor-opentelemetry/src/client.ts

Connection string provided through env variable would be ignored, parsing is triggered in Azure Monitor Exporters, distro should not have any extra validation for it.

[Azure Monitor] Fix issue with connection string provided through env variable

---

sdk/communication/communication-call-automation/src/callAutomationClient.ts
sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
sdk/communication/communication-call-automation/swagger/README.md

- Duplicated lib info in UserAgent.
- Fixed naming of package in autorest to be correct

Fixing duplicated lib info fix

---

sdk/monitor/monitor-opentelemetry/src/client.ts
sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
sdk/monitor/monitor-opentelemetry/src/metrics/handler.ts

Fixed issue of OTLP exporter enabled even if configured off
Fixed issue of Logs not being flush when client was flushed

[Azure Monitor OpenTelemetry] Add MeterProvider and LoggerProvider as global

---

eng/common/spelling/package-lock.json
eng/tools/analyze-deps/package-lock.json

The dependency scanner was complaining about `semver` in particular, so I updated the lockfiles for these CI tools.

Update outdated deps for eng tools

---

sdk/storage/storage-blob/assets.json
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-file-datalake/assets.json
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

Port PR https://github.com/Azure/azure-sdk-for-js/pull/25675
- update blob service version to 2023-01-03
- add "appendBlock - append large block" test
- port file-datalake source changes
- port file-datalake tests and add recordings

[storage] port HNS permission support from storage/stable

---

sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts

Fixes #https://github.com/Azure/azure-sdk-for-js/issues/25989
Fixes #https://github.com/Azure/azure-sdk-for-js/issues/26395
Fixes #https://github.com/Azure/azure-sdk-for-js/pull/26566
The `authenticateManagedIdentity` method inside of `SetAppTokenProvider` callback wasn't taking the current scopes as the parameter- it was taking the scopes of the `getMethod` call at the time this `SetAppTokenProvider` callback was defined. As a result, when a successive `getToken` call is made with a different scope for another service, this new scope doesn't get passed in the `authenticateManagedIdentity` method call, instead it used the `scope` from the time of defining, resulting in the Invalid Audience error from the service.

[Identity] fix bug related to managed identity - set app token provider callback scopes

---

sdk/keyvault/keyvault-keys/package.json

- #26001
Bump version of `core-rest-pipeline` dependency to include `isRestError` type guard which is used as part of fix in #26001.

[keyvault] keyvault-keys: bump minimum version of core-rest-pipeline

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/util/userAgentPlatform.native.ts

`Platform.constants` was introduced in React Native version v0.63. This PR adds a check before accessing the property.
#26609

[core] Fix TypeError when setting user agent string in React Native

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

The breaking changes do not affect our usages.
v5: Require Node.js 14.
v4: Require Node.js 12. Package now pure ESM.

[engsys][dev-tool] upgrade dependency `strip-json-comments` to `^5.0.0`

---

sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts

@azure/cosmso
Few tests in `sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts` share name of database created. This could result in race condition, where one test deletes on database while the other tests expects it to be there.

Added entropy to database names created across bulk tests for @azure/cosmso

---

sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts

@azure/cosmos
Bulk tests are failing for Routing gateway with Request Rate is too high error. Increasing throughput of the containers.

Increasing throughput for containers in bullk test

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/scripts/Language-Settings.ps1

Builds: 
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2931582&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2931583&view=results

Enable nightly build pipeline failure on docs.ms validation failure

---

sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/test/public/functional/item/item.spec.ts

@azure/cosmos
#21383
Upsert operation was failing when partition key of container is /id and id is missing in the object body. This fix generates the uuid before extracting partition key from the body, similar to create operation.
N/A
Yes

fix upsert /id generation

---

common/tools/dev-tool/src/util/testProxyUtils.ts

We changed the location and I failed to [update the PR.](https://github.com/Azure/azure-sdk-for-js/pull/26532)
Sorry @HarshaNalluru  . Here's the necessary fix now.

Update `dev-tool` with new migration script location

---

sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/utils.spec.ts
sdk/storage/storage-file-datalake/src/utils/utils.common.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-queue/src/utils/utils.common.ts

Port PR https://github.com/Azure/azure-sdk-for-js/pull/26159
- port source and test change for blob
- update one negative test. We used to throw an error when splting an undefined `parsedUrl.pathname` in `getAccountNameFromUrl`.  In core v2 we changed to use `URL` instead of `URLBuilder`. `parsedUrl.pathname` is now an empty string, an empty `accountName` is returned instead of error thrown.
- duplicate source change for other storage package as we currently are doing for internal util methods.

[storage] port accountName from SAS connect string support from storage/stable

---

sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts

`@azure/storage-file-share`
When the empty string was passed as a continuationToken to the `byPage` method of any `list` operation, the constructed url would have an empty marker parameter `&marker=&`. 
This was causing issues with SharedKey authentication since we now share the same credential signing logic as `storage-blob` and the implementation of `getURLQueries` in storage-blob ignores query parameters without a value: 
https://github.com/Azure/azure-sdk-for-js/blob/b4e1a63cd2499016f91852c7208f0c4c569651d4/sdk/storage/storage-blob/src/utils/utils.common.ts#L371
However, the previous copy of this method in `storage-file-share` did not: 
https://github.com/Azure/azure-sdk-for-js/blob/b4e1a63cd2499016f91852c7208f0c4c569651d4/sdk/storage/storage-file-share/src/utils/utils.common.ts#L306 …

[storage-file-share] Fix empty continuation token with list methods

---

sdk/storage/storage-file-share/test/directoryclient.spec.ts

Two tests are not awaiting on `dirClient.exists()` calls, which some times caused weird test failure probably due to different timing in async calls where test recorder couldn't find recording for some tests.
This PR adds await for the two calls.

[storage-file-share] Fix DirectoryClient `exists` test

---

sdk/storage/storage-file-share/package.json

as we have bumped core-util minor version, v1.3.3 no longer exists

[storage-file-share] update core-util version to ^1.4.0

---

sdk/keyvault/keyvault-secrets/README.md

- Fixes #26431
Documentation fix as reported in #26431.

[keyvault-secrets] Change incorrectly named `expires` property to `expiresOn` in README

---

sdk/keyvault/keyvault-certificates/assets.json
sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-certificates/test/public/list.spec.ts
sdk/keyvault/keyvault-certificates/test/public/lro.recover.spec.ts
sdk/keyvault/keyvault-certificates/test/public/recoverBackupRestore.spec.ts
sdk/keyvault/keyvault-keys/assets.json
sdk/keyvault/keyvault-keys/test/internal/recoverBackupRestore.spec.ts
sdk/keyvault/keyvault-keys/test/public/keyClient.spec.ts
sdk/keyvault/keyvault-keys/test/public/list.spec.ts
sdk/keyvault/keyvault-keys/test/public/lro.recoverDelete.spec.ts
sdk/keyvault/keyvault-keys/test/public/utils/common.ts
sdk/keyvault/keyvault-secrets/assets.json
sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts
sdk/keyvault/keyvault-secrets/test/public/list.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.delete.spec.ts
sdk/keyvault/keyvault-secrets/test/public/lro.recover.spec.ts
sdk/keyvault/keyvault-secrets/test/public/recoverBackupRestore.spec.ts

- Fix #26601
- Fix https://github.com/Azure/azure-sdk-for-js/issues/26229
- Fix https://github.com/Azure/azure-sdk-for-js/issues/26644
- Fix https://github.com/Azure/azure-sdk-for-js/issues/26157
- Fix https://github.com/Azure/azure-sdk-for-js/issues/25853
- Fix https://github.com/Azure/azure-sdk-for-js/issues/26182
- Fix https://github.com/Azure/azure-sdk-for-js/issues/23997
- Fix https://github.com/Azure/azure-sdk-for-js/issues/24755
- Fix https://github.com/Azure/azure-sdk-for-js/issues/23580
See [the issue](https://github.com/Azure/azure-sdk-for-js/issues/26601), but basically these tests are super flaky and don't add any value -- they're testing the transport, not Key Vault. Removing them will make …

[keyvault] Remove timeout tests

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/src/commands/migrate.ts
common/tools/dev-tool/src/util/resolveProject.ts
common/tools/dev-tool/src/util/testProxyUtils.ts
common/tools/eslint-plugin-azure-sdk/package.json

The breaking change in v9 is related to how BOM is handled. It doesn't affect our usage.
While validating the change I found some false-positive linter errors in dev-tool and suppressed them.

[engsys] upgrade `eslint-config-prettier` version to `^9.0.0`

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples-dev/buildClassifier.ts
sdk/formrecognizer/ai-form-recognizer/samples-dev/buildModel.ts
sdk/formrecognizer/ai-form-recognizer/src/constants.ts
sdk/formrecognizer/ai-form-recognizer/src/documentAnalysisClient.ts
sdk/formrecognizer/ai-form-recognizer/src/documentModel.ts
sdk/formrecognizer/ai-form-recognizer/src/documentModelAdministrationClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analysis.ts
sdk/formrecognizer/ai-form-recognizer/src/models/contentSource.ts
sdk/formrecognizer/ai-form-recognizer/src/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/options/AnalyzeDocumentOptions.ts
sdk/formrecognizer/ai-form-recognizer/src/options/FormRecognizerClientOptions.ts
sdk/formrecognizer/ai-form-recognizer/src/options/index.ts
sdk/formrecognizer/ai-form-recognizer/src/util.ts
sdk/formrecognizer/ai-form-recognizer/swagger/README.md
sdk/formrecognizer/ai-form-recognizer/test/public/node/classifiers.spec.ts
sdk/formrecognizer/perf-tests/ai-form-recognizer/package.json

This PR makes several changes related to the impending 5.0.0 release of Document Intelligence (f.k.a. Form Recognizer).
- The major version revision signals a breaking change in which key-value pairs and extracted languages will not be returned unless a special `feature` is provided when making the analysis request.
- Support for explicit API version was removed. This functionality never worked very well in TypeScript, and the major version revision gives us an opportunity to remove it and avoid its inherent complexity until a better solution is available.
This also addresses some issues with the way that training data content sources were represented and named. The new representation is stricter about providing only one of the two possible source type fields: `azureBlobSource` or …

[ai-form-recognizer] 5.0.0 changes

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

per https://github.com/sinonjs/fake-timers/blob/main/CHANGELOG.md, v11.0.0 is a release of 10.2.0. So it should be fine since what we've been installing with `^10.0.2` is working fine.

[engsys] upgrade dev dependency `@sinonjs/fake-timers` to `^11.0.0`

---

common/scripts/install-run.js
rush.json
sdk/purview/purview-sharing-rest/package.json

- upgrade `rush` and `pnpm` to their latest versions
- remove a dependency on `@microsoft/rush` that was likely added accidentally.

[engsys] upgrade rush to 5.101.0 and pnpm to 8.6.12

---

sdk/eventhub/event-hubs/perf-tests.yml
sdk/eventhub/event-hubs/perf.yml
sdk/servicebus/service-bus/perf-tests.yml
sdk/servicebus/service-bus/perf.yml

For consistent naming across languages

[Perf Tests] [AMQP] Test naming consistency update

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

The docker images we pull force node as the default command. This PR overrides that command to be shell instead.

[dev-tool] Fix check-node-versions

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/scripts/validate-docs-package.ps1
sdk/core/ci.yml
sdk/identity/ci.yml

Example pipeline fixed by this change: 
* Identity -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2995011&view=results
* Core -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2995180&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b
Work item to undo this when we integrate `@microsoft/type2docfx` https://github.com/Azure/azure-sdk-for-js/issues/26770

Add skipPublishDocMs to false error reports in docs heuristics

---

sdk/search/search-documents/assets.json
sdk/search/search-documents/src/generated/data/models/index.ts
sdk/search/search-documents/src/generated/data/models/mappers.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/swagger/Data.md

The `SearchRequest.vector` property will soon be removed from the REST API surface, so we're getting ahead of that and rolling it into `SearchRequest.vectors`.

[Search] Add Swagger transform for `SearchRequest.vector`

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk-helper/package.json
dataplane.code-workspace
rush.json
sdk/core/abort-controller/test/aborter.spec.ts

ESlint plugins are resolved relative to the config file. In our repo that means ESLint would try resolving plugins from `sdk` folder or individual package folder if it contains a config file. The plugins needed are actually installed under `common/tools/eslint-plugin-azure-sdk`. Linting works when running cli because `NODE_PATH` is set to contain a bunch of directories, including `common/temp/node_modules/.pnpm/node_modules`, and ESLint is able to find plugins.
When the `dataplane.code-workspace` is opened in VS Code, ESLint in `vscode-eslint` extension attempts to load plugins but couldn't because there's no `NODE_PATH` or equivalent. As a result, the extension crashes.
This PR provides a workaround utilizing the
`eslint.options.resolvePluginsRelativeTo` setting and a empty rush project …

[engsys] workaround for `vscode-eslint` extension in workspace

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.test.ts

https://github.com/microsoft/ApplicationInsights-node.js/issues/1169
Fixes an issue with serializing legacy Application Insights logs with nested objects.
Yes, added in the `logUtils.tests` file.

[monitor-opentelemetry-exporter] Fix Nested Object Serialization

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/review/monitor-query.api.md
sdk/monitor/monitor-query/src/index.ts
sdk/monitor/monitor-query/src/internal/modelConverters.ts
sdk/monitor/monitor-query/src/metricsBatchQueryClient.ts
sdk/monitor/monitor-query/src/models/publicBatchModels.ts
sdk/monitor/monitor-query/swagger/metric-Batch.md
sdk/monitor/monitor-query/test/public/metricsBatchClient.spec.ts
sdk/monitor/monitor-query/test/public/shared/testShared.ts

N/A
1. In this release, In the `MetricsBatchOptionalParams`object, the names of the properties `endtime`, `orderby`, `starttime` are changed to `endTime`, `orderBy`, `startTime` respectively.
2. The scope value is not set correctly in the previous release. In this release, I am setting the scope value correctly.
3. The previous release did not have integration tests. With this PR, I have added the integration tests.
There are no special design changes in this PR, other than setting the credential scope. 
One point to note is that the new tests are marked as skip. Because, the recordings will have subscription id in them which we do not want to expose. So, for CI, I have marked them as Skip. I am working on possible solutions to bypass this issue in the future. But, …

[@azure/monitor-query] Code Changes to add scope to Metrics Query Client and modify MetricsBatchOptionalParams

---

sdk/monitor/monitor-opentelemetry-exporter/README.md

- @azure/monitor-opentelemetry-exporter
- #26877
Documentation on the README states that the browser is supported when it is currently unsupported.  Removing the wording from the README.

[monitor] Update Monitor exporter README

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/fetchHttpClient.ts
sdk/core/core-rest-pipeline/test/browser/fetchHttpClient.spec.ts

According to WHATWG fetch spec (https://fetch.spec.whatwg.org/#fetch-method) when body is a ReadableStream object, init.duplex must be set and currently the only valid value is "half".  This PR sets the property when request body is a ReadableStream.

[core-rest-pipeline] set init.duplex to "half" when streaming body via fetch 

---

sdk/core/core-http/src/policies/disableResponseDecompressionPolicy.browser.ts
sdk/core/core-http/src/policies/proxyPolicy.browser.ts
sdk/core/core-rest-pipeline/src/policies/decompressResponsePolicy.browser.ts
sdk/core/core-rest-pipeline/src/policies/proxyPolicy.browser.ts

`@azure/core-http`
Partner report of memory leak in test bench.
Eager error construction on module load can cause trouble when the Error constructor is hooked/cached by development tooling. This PR changes the pattern of caching the Error object to a more typical new-on-throw pattern. This should also improve the stack trace to be more accurate on the thrown Error.

[core] Defer Error construction

---

common/tools/eslint-plugin-azure-sdk-helper/package.json

so that rush commands like "rush build" and "rush lint" won't be broken.

[EngSys] add stub NPM scripts to eslint-plugin-helper

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/policies/disableResponseDecompressionPolicy.browser.ts
sdk/core/core-http/src/policies/proxyPolicy.browser.ts
sdk/core/core-http/src/util/constants.ts

`@azure/core-http`
Partner report of memory leak in test bench.
Eager error construction on module load can cause trouble when the Error constructor is hooked/cached by development tooling. This PR changes the pattern of caching the Error object to a more typical new-on-throw pattern. This should also improve the stack trace to be more accurate on the thrown Error.

[core-http] Port changes from PR #26897 Defer Error construction

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json

@azure/communication-chat
Updated to @azure/communication-signaling@1.0.0-beta.20. Added EUDB real-time notification support. `https://*.trouter.teams.microsoft.com` and `teams.microsoft.com` needs to be allowed for real-time notifications.

[Communication] ACS Chat 1.3.2 Release

---

sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/CosmosClient.ts
sdk/cosmosdb/cosmos/test/public/functional/databaseaccount.spec.ts

@azure/cosmos
https://github.com/Azure/azure-sdk-for-js/issues/25932
Currently, status and substatus code are returned as undefined whenever call client.getDataBaseAccount() is made. This PR fixes up this issue by setting up these fields in the response
yes

Fixing undefined status and substatus code in response of client.getDataBaseAccount() call

---

sdk/keyvault/keyvault-admin/tests.yml
sdk/keyvault/keyvault-keys/tests.yml

Fixes #25734.
Running tests which use Managed HSM only weekly to reduce cost.

[keyvault] Make Managed HSM tests only weekly

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/util/utils.ts

We already have the logic in `MessageSender._trySend()`.  This PR adds the same to `ManagementClient._makeManagementRequest()` so that when the link is not sendable, we wait for one second then check again.  A `SendBusyError` is thrown if we still cannot send messages.
#26855

[ServiceBus] wait and throw error if sender link is not sendable

---

sdk/monitor/monitor-opentelemetry/src/index.ts
sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
sdk/monitor/monitor-opentelemetry/src/metrics/handler.ts
sdk/monitor/monitor-opentelemetry/src/shared/config.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/metricHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/azureFnHook..test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts

Removing singleton will allow customers to create multiple instances and send telemetry to different connection strings if needed

[Azure Monitor OpenTelemetry Distro] Remove singleton in handlers

---

sdk/monitor/monitor-query/README.md
sdk/monitor/monitor-query/samples-dev/logsResourceCentricQuery.ts
sdk/monitor/monitor-query/samples/v1/javascript/README.md
sdk/monitor/monitor-query/samples/v1/javascript/logsResourceCentricQuery.js
sdk/monitor/monitor-query/samples/v1/typescript/README.md
sdk/monitor/monitor-query/samples/v1/typescript/src/logsResourceCentricQuery.ts
sdk/monitor/monitor-query/samples/v1/typescript/tsconfig.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/26002

[Monitor Query] Monitor Query Resource Centric sample

---

sdk/communication/communication-call-automation/review/communication-call-automation.api.md
sdk/communication/communication-call-automation/src/models/models.ts

CallInvite was missing MicrosoftTeamsUserIdentifier

Add MicrosoftTeamsUserIdentifier to Call Invite

---

sdk/identity/identity/test-resources.bicep
sdk/identity/identity/tests.yml

Parity with https://github.com/Azure/azure-sdk-for-net/pull/38370
These values actually aren't used as they get overridden by the base subscription config (https://github.com/Azure/azure-sdk-for-js/blob/main/eng/pipelines/templates/stages/archetype-sdk-tests.yml#L45). This PR removes them because we've had some issues where these values have been updated, but then got overridden by the older values from the subscription config. Part of an effort to deprecate yaml defined values and one-off keyvault secrets.

Remove duplicate identity test variables

---

sdk/communication/communication-identity/package.json
sdk/communication/communication-identity/test/public/communicationIdentityClient.spec.ts
sdk/communication/communication-identity/test/public/node/getTokenForTeamsUser.node.spec.ts
sdk/communication/communication-identity/test/public/node/tokenCustomExpiration.node.spec.ts
sdk/schemaregistry/schema-registry-json/package.json
sdk/schemaregistry/schema-registry-json/samples/v1-beta/typescript/package.json

Rush warns about
> WARN  deprecated mocha-testdata@1.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  deprecated @types/ajv@1.0.0: This is a stub types definition for ajv (https://github.com/epoberezkin/ajv). ajv provides its own type definitions, so you don't need @types/ajv installed!
This PR rewrites `given()` with plain `forEach()` calls and remove the two dependencies `mocha-testdata` and `@types/ajv`.
communication-identity
schema-registry-avro
#24379

[engsys] remove some deprecated dev dependencies

---

common/tools/dev-tool/src/commands/run/testNodeJSInput.ts
common/tools/dev-tool/src/commands/run/testNodeTSInput.ts
sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json
sdk/communication/communication-common/package.json
sdk/core/abort-controller/package.json
sdk/core/core-auth/package.json
sdk/core/core-client-rest/package.json
sdk/core/core-http-compat/package.json
sdk/core/core-lro/package.json
sdk/core/core-paging/package.json
sdk/core/core-rest-pipeline/package.json
sdk/core/core-tracing/package.json
sdk/core/core-util/package.json
sdk/core/core-xml/package.json
sdk/core/logger/package.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
sdk/iot/iot-modelsrepository/package.json
sdk/keyvault/keyvault-common/package.json
sdk/storage/storage-internal-avro/package.json
sdk/test-utils/test-utils/package.json
sdk/web-pubsub/web-pubsub-client-protobuf/package.json
sdk/web-pubsub/web-pubsub-client/package.json
sdk/web-pubsub/web-pubsub-express/package.json

It is desirable to centralize our NPM test scripts so that we can change common options easily.  Currently test-proxy is always launched, which isn't useful for packages (e.g., core) that don't have recorded tests.
This PR adds an opt-in option to not launch test-proxy when running tests.
`@azure/dev-tool`

[dev-tool] add a `--no-test-proxy` option to run test commands

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/azurePowerShellCredential.ts

Passing -NoProfile is generally recommended to ensure the powershell script is run in the default environment without user profile side effects interfering.

[Identity] Disable loading profiles in powershell

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/client/ChangeFeed/FeedRange.ts

@azure/cosmos
N/A
`FeedRange` for changefeed is changed from interface to abstract class for avoiding confusion among users. Users cannot create instance of abstract class and can now only pass feed range from the result of `container.getFeedRanges()` call.
N/A

change FeedRange interface to abstract class

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/steps/test.yml

We no longer run Node tests against bundled tests. The test inputs are from dist-esm/test and running `build` produces the same output as `build:test` as far as Node is concerned.
For browser we still need the bundled tests from `build:test`.
This PR enables "Build test assets" step only if the run is for browser.

[engsys] build test assets only for browser runs

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/CosmosClient.ts
sdk/cosmosdb/cosmos/src/CosmosDiagnostics.ts
sdk/cosmosdb/cosmos/src/diagnostics/DiagnosticNodeInternal.ts
sdk/cosmosdb/cosmos/src/diagnostics/diagnosticLevelComparator.ts
sdk/cosmosdb/cosmos/src/diagnostics/index.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/parallelQueryExecutionContextBase.ts
sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/src/utils/diagnostics.ts
sdk/cosmosdb/cosmos/test/internal/unit/diagnostics.spec.ts
sdk/cosmosdb/cosmos/test/public/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/public/functional/client.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item/item.spec.ts

- Fixing diagnostic level not setting during client initialization + making diagnostic level scope limited to Cosmos client instance.
- Now, Diagnostic Node is present in `CosmosDiagnostic` for only `info` diagnostic level.
- Fixed diagnostic verification utility.
@azure/cosmos

Fixing diagnostic level not setting during client initilization + making diagnostic level scope limited to Cosmos client instance

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/src/serializer.ts
sdk/core/core-client/test/browser/serializer.spec.ts

We have browser stream support in fetchHttpClient but miss to allow it to be serialized so an error is thrown when serializing a browser ReadableStream.
This PR adds the condition for browser ReadableStream when checking whether the type is supported.
`@azure/core-client`

[core-client] allow serializing browser ReadableStream

---

sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/TableServiceClient.ts

If a consumer re-uses a single options argument when configuring multiple clients, they may run into issues because both the TableClient and TableServiceClient mutate the options bag directly instead of creating a copy.
This issue was originally raised in the following community PR, but it was never merged:
https://github.com/Azure/azure-sdk-for-js/pull/26211

[data-tables] Avoid mutating client options parameter

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/steps/test.yml

This reverts commit e453c2d5f7a65c4cbb1e9cf1ba8904bfc6d830b6.
PR #27035 keeps `build;test` only for browser runs. It turns out that a couple of packages have custom `build:test` scripts that are different from `build`.  While we can explore more on enabling `build:test` for these few packages, this PR reverts the changes to unblock automation builds.

Revert "[engsys] build test assets only for browser runs (#27035)"

---

sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts
sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForPartitionKey.ts
sdk/cosmosdb/cosmos/test/public/integration/changeFeedIterator.spec.ts

@azure/cosmos
N/A
- Removes check for empty 200 response from backend in async iterator which earlier led to empty diagnostics
- Add diagnostics to read container in changefeed

fix changefeed diagnostics

---

sdk/identity/identity/test-resources-pre.ps1
sdk/identity/identity/tests.yml

Updating the identity live tests to remove logic and env setting from yaml in favor of a dedicated keyvault config and powershell script. This will make it possible to improve local and sovereign cloud testing, and make cross-language config updates more easily.
Related: https://github.com/Azure/azure-sdk-for-net/pull/38473

Move identity variable setting into test-resources-pre.ps1

---

sdk/communication/communication-chat/package.json
sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/package.json
sdk/communication/communication-common/review/communication-common.api.md
sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/src/identifierModels.ts
sdk/communication/communication-common/test/public/identifierModels.spec.ts

Change MicrosoftBotIdentifier to MicrosoftTeamsAppIdentifier for 3.0.0 GA
No need to add more UTs, current UTs are ok. I've modified UTs in this PR

microsoft teams app identifier

---

sdk/monitor/monitor-opentelemetry/src/index.ts
sdk/monitor/monitor-opentelemetry/src/shared/types.ts
sdk/monitor/monitor-opentelemetry/src/types.ts

[Azure Monitor OpenTelemetry] Fix issues with SDK version not propagating correctly

---

sdk/contentsafety/ai-content-safety-rest/package.json

Since 1.4.1 core-util has not been released, and https://github.com/Azure/azure-sdk-for-js/pull/26748 jumps from 1.4.0 to 1.5.0 core-util directly.. leads to CI failure at #26748.
Instead of depending on the unreleased/fixed `1.4.1` version of `core-util`... 
Depending on `^1.4.0` is better and won't have other dependencies on releases.

[ai-content-safety-rest] Update dependency @azure/core-util version to ^1.4.0

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/sanitizer.ts
sdk/test-utils/recorder/src/utils/envSetupForPlayback.ts
sdk/test-utils/recorder/test/sanitizers.spec.ts

- Fixes #11379 (an issue from 2020!)
Fixes a long-running issue recently rediscovered by @minhanh-phan. If we have 2 environment variables in our `.env`, where one is a substring of another, e.g.:
```sh
VAR_1=TestTestTest
VAR_2=Test
```
we can run into an issue where the shorter environment variable gets replaced first in the recordng, causing the first variable to not be sanitized properly. This causes issues in playback.
This PR fixes the issue by:
- Ordering the sanitizers applied by `envSetupForPlayback` by the length of the environment variable value, in descending order, and
- Adding the sanitizers in a deterministic order instead of applying them in parallel and using `Promise.all`.

[recorder] Fix env var issue where one variable a substring of another

---

.gitignore
common/tools/dev-tool/src/util/testProxyUtils.ts

- `@azure-tools/dev-tool`
This is a quality-of-life change which makes inspecting recordings easier. With the new asset sync flow, recordings are no longer stored in the repo with each package. If you want to look at your recordings for some reason (e.g. after re-recording to make sure you aren't leaking any secrets), it takes a few extra steps to find them: navigate to the repo root, look at the `.breadcrumb` file in the `.assets` folder, and then use that to find the location of the recordings corresponding to your package.
This PR improves that process by creating a symbolic link to the recordings from each package, restoring the original flow.

[dev-tool] Create a symbolic link to recordings when running the proxy tool

---

common/config/rush/pnpm-lock.yaml

There's an error from previous commit which caused `rush update` to bump dependency versions. Normally only `rush update --full` does that.
This PR fixes pnpm-lock.yaml by checking out to a good and old version then run `rush update`

[engsys] fix pnpm-lock.yaml

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts

Warnings are displayed when using exporter because  OTel recently added validation for the metric name and these should not have spaces https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument

[Azure Monitor OpenTelemetry Exporter] Update Statsbeat Metric names

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/public/snapshot.spec.ts
sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/src/index.ts
sdk/test-utils/recorder/src/utils/utils.ts

also add a `testPollingOptions` in recorder to help testing in playback mode.

[AppConfig] allow setting `updateIntervalInMs` in LRO options

---

sdk/confidentialledger/confidential-ledger-rest/package.json

The minor version of test-recorder was bumped thus 3.0.1 is no longer valid. This PR changes the version to ^3.0.0

[test] fix recorder dependency version

---

sdk/core/core-util/CHANGELOG.md
sdk/eventhub/event-hubs/CHANGELOG.md

Packages have not been released yet.
Followup of #26748

[Event Hubs] [core-util] Mark next week for release in changelog

---

common/config/rush/pnpm-lock.yaml
common/tools/eslint-plugin-azure-sdk/package.json
common/tools/eslint-plugin-azure-sdk/src/rules/github-source-headers.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-apiextractor-json-types.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-apisurface-supportcancellation.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-config-include.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal-private-member.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-error-handling.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-modules-only-named.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-naming-options.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-author.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-bugs.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-engine-is-present.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-files-required.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-homepage.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-keywords.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-license.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-main-is-cjs.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-module.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-name.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-repo.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-required-scripts.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-sdktype.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-sideeffects.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-types.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-use-interface-parameters.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-use-promises.ts
common/tools/eslint-plugin-azure-sdk/src/rules/ts-versioning-semver.ts
common/tools/eslint-plugin-azure-sdk/src/utils/exports.ts

- update eslint to ^8.50.0, @types/eslint to ~8.44.0
- fix deprecation warnings by using recommended new api

[eslint-plugin] update eslint version and fix deprecation warnings

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json

There are some breaking changes when they upgrade to TS 5.2 but we don't use the affected Api.
https://github.com/dsherret/ts-morph/compare/19.0.0...20.0.0

[dev-tool] update dependency ts-morph version to ^20.0.0

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json

Bug fixes
Fixes bug for browser bundling for Azure Developer CLI Credential which otherwise includes `child_process`.

[Identity] update mapping for browser for azd

---

sdk/monitor/monitor-opentelemetry/README.md

Documentation is wrong, and the property name used throws an error.
N/A
N/A
N/A

[Monitor-Opentelemetry] fix documentation

---

sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/test/public/crypto.spec.browser.ts
sdk/keyvault/keyvault-keys/test/public/crypto.spec.ts
sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.browser.ts
sdk/keyvault/keyvault-keys/test/public/localCryptography.spec.ts

- Fixes #27106
Fix browser bundling warnings by:
- Create browser mappings for Node-only tests which use `crypto.createHash`, which does not have a polyfill
- Re-enabling Node polyfill for browser bundle

[keyvault] Fix keyvault-keys build warnings

---

sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts

#27268 
Issue is causing first time this code is executed credentialScopes are not passed to core-client adding incorrect default one.

[Azure Monitor OpenTelemetry Exporter] Fix issue with credentialScopes setup

---

sdk/keyvault/keyvault-admin/package.json

Fixes bundle warnings about a missing polyfill.

[keyvault] Add --browser-test=false to keyvault-admin bundle options

---

eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/cosmos-sdk-client.yml
eng/pipelines/templates/stages/platform-matrix.json
eng/pipelines/templates/steps/use-node-test-version.yml
sdk/communication/communication-phone-numbers/phone-numbers-livetest-matrix.json
sdk/keyvault/keyvault-admin/platform-matrix.json
sdk/keyvault/keyvault-keys/platform-matrix.json

Update the CI matrix so we are no longer testing on Node 14 as it has reached the end of our EOL + 6 months policy.
For coverage and browser legs I bumped it to use the current LTS (18) rather than 16 which is EOL, since most customers are not expected to be using an out of support runtime.

[engsys] update platform matrix for node 14 deprecation

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/serviceBusError.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

Related: issue #9775, #27010
This PR fixed the following timing issue when trying to establish link for next session but there are none available.
what's happening is
- SDK is trying to create a link for next avaiable session (`options.source.filter: { com.microsoft:session-filter': undefined }`)
- Because no sessions are available, after one minute, a link is established, but with `"source":null,"target":null`. The call to create link resolves.
- However, the service immediately use that link to ask SDK to close the link, with an error of `"com.microsoft:timeout"`/`The operation did not complete within the allotted timeout of 00:00:59.9130000.`
- SDK respects the request and start acquiring a lock to close the link
- Meanwhile, SDK gets a link, nice! It will continue as the link has been …

[ServiceBus] throw error earlier when timing out

---

common/tools/dev-tool/src/config/rollup.base.config.ts

Ignore warnings like
>../../../common/temp/node_modules/.pnpm/@opentelemetry+resources@1.17.0_@opentelemetry+api@1.6.0/node_modules/@opentelemetry/resources/build/esm/detect-resources.js (16:17) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
and
>Circular dependency: ../../../common/temp/node_modules/.pnpm/@opentelemetry+sdk-trace-base@1.17.0_@opentelemetry+api@1.6.0/node_modules/@opentelemetry/sdk-trace-base/build/esm/index.js -> ../../../common/temp/node_modules/.pnpm/@opentelemetry+sdk-trace-base@1.17.0_@opentelemetry+api@1.6.0/node_modules/@opentelemetry/sdk-trace-base/build/esm/BasicTracerProvider.js -> ../../../common/temp/node_modules/.pnpm/@opentelemetry+sdk-trace-base@1.17.0_@opentelemetry+api@1.6.0/node_modules/@openteleme …

[dev-tool] ignore more rollup warnings from opentelemetry

---

sdk/monitor/monitor-opentelemetry/src/shared/config.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/jsonConfig.test.ts

JSON config values are ignored if options are provided, this is causing issue with auto attach scenarios, where JSON should have precedence over default and options provided by code.

[Azure Monitor OpenTelemetry] Change JSON config values precedence

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md

It caused failure in core - ci pipeline.

[core][doc] retro fix broken links in CHANGELOG

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/package.json
sdk/monitor/monitor-opentelemetry/src/types.ts

[Azure Monitor OpenTelemetry] 1.1.0 Release

---

sdk/web-pubsub/web-pubsub-client/review/web-pubsub-client.api.md
sdk/web-pubsub/web-pubsub-client/src/protocols/index.ts
sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts
sdk/web-pubsub/web-pubsub-client/test/jsonProtocol.spec.ts

Change the interface of `parseMessages` and allow protocol implementor to return a list of messages. It's designed for further possible new protocols that contains multiple messages in one websocket frame.
yes

[web-pubsub-client] ParseMessages can return array of messages

---

.github/CODEOWNERS

I have to say, of all the azure-sdk-for-&lt;lang&gt; repositories that I've been fixing up for bad/missing paths, this one is the worst, by far. 
/CC @qiaozha and @MaryGao 
When releasing a hybrid library with the date in its name, the old one was removed but when the new path entries were added, the old ones were left. There are also a number entries that will not work correctly. For example,
`# PRLabel: %Mgmt`
`/sdk/analysisservices/arm-analysisservices/ @qiaozha @MaryGao`
`/sdk/analysisservices/ci.mgmt.yml @qiaozha @MaryGao`
This will add the Mgmt label to a PR that changes anything in /sdk/analysisservices/arm-analysisservices/ but, the PRLabel only applies to the entry immediately below it. The /sdk/analysisservices/ci.mgmt.yml will not have this label applied. Each source line needs …

Fix bad paths and remove missing paths from CODEOWNERS

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/util/errors.ts
sdk/servicebus/service-bus/test/internal/unit/sender.spec.ts

to `scheduleMessages()`.
The service ignores the value when it is not valid. This may surprise JavaScript developers who pass in a datetime string and expect it to work.  This adds an `instanceof` check to only accept `Date` instances

[ServiceBus] throw error for invalid `scheduledEnqueueTimeUtc`

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/fetchHttpClient.ts

@azure/core-rest-pipeline and all libraries that depend on it
https://github.com/Azure/azure-sdk-for-js/issues/27412
Cloudflare workers implement the Fetch API spec but not all of it since some of it doesn't make sense on the edge. However, CF shows this unsupport by throwing instead of silently ignoring the provided fields. This PR enables Azure libraries to work with Cloudflare workers by fixing this by setting those fields only if they're available in the `Request` class prototype.
Alternatively, I thought about introducing an explicit CF worker check but AFAIK, it is hard because it looks very similar to the browser.
No but tested locally.
N/A

[core] Add cloudflare support

---

sdk/servicebus/service-bus/src/sender.ts

Service Bus live tests failed due to the switched ordering of parameter type checking for `messages` and `scheduledEnqueueTimeUtc`.  Even though this is unlikely a real world scenario where users would passing in undefined `messages` before a valid `scheduledEnqueueTimeUtc`, this PR restores the old order to presrve the existing behavior.

[ServiceBus] revert to old order of checking parameters for scheduleMessages

---

.vscode/cspell.json

The package is a RLC and these words are inherited from api specs.
Fixes #27434

[Easm] Fix cspell errors

---

common/config/rush/pnpm-lock.yaml
sdk/openai/openai/.eslintrc.json
sdk/openai/openai/CHANGELOG.md
sdk/openai/openai/package.json

@azure/openai
N/A
We would like to use an isomorphic stream interface for SSE operations and NodeJS v18 implements the web stream `ReadableStream` API. This change will come in a later release after it goes through some validation but for now we would like our customers to prepare for the minimum node requirement.
N/A
N/A
N/A

[OpenAI] Bump min node version

---

sdk/core/core-util/CHANGELOG.md
sdk/core/core-util/src/checkEnvironment.ts

`@azure/core-util`
Fixes #27077
Deno implemented `process.versions.node`, which is how we detect that we are running inside a Node environment. Since Deno actually is much closer to a browser environment, this is *not* what was expected at runtime and resulted in things like loading the browser version of pipeline policies that throw due to not being implemented/relevant in browsers.
I kept this really simple by making `isNode` check that `isDeno` is false. Since `isNode` was previously false inside Deno environments, I don't think this will break anything.
https://github.com/Azure/azure-sdk-for-js/pull/27090

[core-util] Fix issue with Deno showing up as isNode at runtime.

---

sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azureDeveloperCliCredential.spec.ts
sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts

This fixes issue in build pipeline test result publish step where the test result publisher failed to read the result xml due to the 0x00 character in the file.

[test] use friendlier name in identity unit test titles

---

common/tools/dev-tool/src/util/customization/customize.ts
common/tools/dev-tool/src/util/customization/functions.ts

dev-tool
This PR addresses a couple of problems with the `customize` tool.
- If when replacing a function, you called a function that had the same names as prefix it would make the old function private instead of removing it (e.g replacing `foo` and having another a function call to `_foobar` would trigger this issue)
- If customized code was importing from the same file but the generated version, the reference to the generated file would show up in the end result.
- In some conditions, importing from generated code would result in the import not being translated into importing the end result file.
- Under certain circumstances, importing a custom-only file would not be reflected in the end result.
- Named imports of generated code were not being reflected.

Fixing issues with dev-tool customize.

---

common/tools/dev-tool/src/commands/run/bundle.ts
sdk/identity/identity/package.json

Because `umd` doesn't support dynamic imports and rollup will give errors like:
>RollupError: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
This error showed up in rush automation runs where we upgraded to msal-browser 3.3.0 which started using `await import`.
This PR uses `inlineDynamicImports: true` for browser test bundle.

[dev-tool] Inline dynamic imports in browser bundle

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/transformations.ts
sdk/keyvault/keyvault-certificates/test/internal/transformations.spec.ts

- Fixes https://github.com/Azure/azure-sdk-for-js/issues/25716
Add convenience property `x509ThumbprintString` which is a hex-encoded representation of the existing `x509Thumbprint` property.

[keyvault] Add `x509ThumbprintString` property to `CertificateProperties`

---

sdk/cognitivelanguage/ai-language-conversations/samples/v1-beta/javascript/README.md
sdk/cognitivelanguage/ai-language-conversations/samples/v1-beta/typescript/README.md
sdk/maps/maps-geolocation-rest/README.md
sdk/maps/maps-render-rest/README.md
sdk/maps/maps-route-rest/README.md
sdk/maps/maps-search-rest/README.md
sdk/web-pubsub/web-pubsub-client-protobuf/README.md
sdk/web-pubsub/web-pubsub-client/README.md

A couple of README files have different link than most packages' in this repo, likely due to in-flight PRs when we update the link to point to github one. These are now broken. This PR replaces them with the one used in other packages.

[Doc] fix broken links to Node.js releases

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

dev-tool
Remove node 14 & 16 in dev-tool checkNodeVersions command

[dev-tool] Drop NodeJS v14 & 16

---

eng/pipelines/templates/stages/platform-matrix.json
sdk/communication/communication-phone-numbers/phone-numbers-livetest-matrix.json
sdk/keyvault/keyvault-admin/platform-matrix.json
sdk/keyvault/keyvault-certificates/platform-matrix.json
sdk/keyvault/keyvault-secrets/platform-matrix.json

This PR migrates our CI away from testing Node16. 
Due to Node16 [depending on an insecure version of OpenSSL](https://nodejs.org/en/blog/announcements/nodejs16-eol) we believe that customers should migrate without delay to a supported LTS version of the Node runtime. As such we do not intend to fix bugs that only reproduce in Node 16 runtimes, obviating the need to proactively run in this environment.

[engsys] Update CI to use node 18 as a minimum runtime version

---

sdk/web-pubsub/web-pubsub-client-protobuf/README.md
sdk/web-pubsub/web-pubsub-client/README.md

```
##[error][404] broken link https://nodejs.org/about/releases/
Checking 1 links found on page file:///mnt/vss/_work/1/s/sdk/web-pubsub/web-pubsub-client-protobuf/review/web-pubsub-client-protobuf.api.md
Checking 4 links found on page file:///mnt/vss/_work/1/s/sdk/web-pubsub/web-pubsub-client-protobuf/samples/v1-beta/javascript/README.md
Checking 5 links found on page file:///mnt/vss/_work/1/s/sdk/web-pubsub/web-pubsub-client-protobuf/samples/v1-beta/typescript/README.md
Checking 0 links found on page file:///mnt/vss/_work/1/s/sdk/web-pubsub/web-pubsub-client-protobuf/CHANGELOG.md
Checking 11 links found on page file:///mnt/vss/_work/1/s/sdk/web-pubsub/web-pubsub-client-protobuf/README.md
##[warning]broken link https://nodejs.org/about/releases/
Checking 1 links found on page …
```

update broken link in web-pubsub-client and web-pubsub-client-protobuf

---

sdk/storage/storage-file-datalake/.nycrc
sdk/storage/storage-file-share/.nycrc
sdk/storage/storage-queue/.nycrc

Some build output file paths in code coverage config are now out-dated:
- shared policies are now from storage-blob so they are no longer needed in `exclude` list.
- output files for queue are now under dist-esm/storage-queue
This PR updates these config files to have correct paths.

[storage] update code coverage config files

---

eng/pipelines/aggregate-reports.yml
eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/variables/globals.yml

- with 18.x by default
- with 20.x to avoid dupe/have better coverage

[EngSys] Replace NodeJS version of 16.x in pipelines with 18.x or 20.x

---

common/tools/dev-tool/src/util/customization/helpers/addFileHeaders.ts
sdk/template/template-dpg/src/WidgetServiceClient.ts
sdk/template/template-dpg/src/api/WidgetServiceContext.ts
sdk/template/template-dpg/src/api/foo.ts
sdk/template/template-dpg/src/api/index.ts
sdk/template/template-dpg/src/api/models.ts
sdk/template/template-dpg/src/api/operations.ts
sdk/template/template-dpg/src/common/interfaces.ts
sdk/template/template-dpg/src/index.ts
sdk/template/template-dpg/src/logger.ts
sdk/template/template-dpg/src/rest/clientDefinitions.ts
sdk/template/template-dpg/src/rest/index.ts
sdk/template/template-dpg/src/rest/isUnexpected.ts
sdk/template/template-dpg/src/rest/models.ts
sdk/template/template-dpg/src/rest/outputModels.ts
sdk/template/template-dpg/src/rest/parameters.ts
sdk/template/template-dpg/src/rest/responses.ts
sdk/template/template-dpg/src/rest/widgetServiceClient.ts

There are two trailing whitespaces in the header template. However after we customize, we run format so the whitespaces are removed.  That would fail the check of whether the header already exists.  This PR removes the trailing whitespaces thus after formatting the header still matches the template.
Issue #26741

[dev-tool][customization] fix duplicate file header

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts

Statsbeat feature enum should use 0 to indicate feature statsbeat and 1 to indicate instrumentation. They were erroneously set to strings.

[Azure Monitor-Opentelemetry] Fix Statsbeat Feature Enum to Match Spec

---

sdk/core/ts-http-runtime/review/ts-http-runtime.api.md
sdk/core/ts-http-runtime/src/index.ts

Adding the missing export for KeyCredential for ts http runtime lib

Adding the missing export for KeyCredential in ts http runtime lib

---

sdk/identity/identity/README.md

Update the list to reflect reality, per this code: https://github.com/Azure/azure-sdk-for-js/blob/722ce97e25b2492737a75711d35322929dab277d/sdk/identity/identity/src/credentials/defaultAzureCredential.ts#L149-L156

Correct the azd credential ordering in README

---

common/tools/dev-tool/src/util/customization/helpers/annotations.ts
common/tools/dev-tool/src/util/customization/interfaces.ts

dev-tool
This change adds support for customizing interface call signatures. It also fixes an issue with the property removal functionality.

Adding call signature customization support.

---

CONTRIBUTING.md

I bumped into this issue when I was running `rush update` on a clean-slate Windows.

Add missed prereq python library

---

common/tools/dev-tool/src/commands/run/bundle.ts

to maintain back compatibility.
Related issue https://github.com/Azure/azure-sdk-for-js/issues/27618
Previously `import * as serviceBus from @azure/service-bus` is working but broken after upgrading to rollup v3.
The rollup migration guide suggested `esModule: true`
More details:
- https://rollupjs.org/migration/#changed-defaults
- https://rollupjs.org/configuration-options/#output-esmodule

[dev-tool][bundle] set esModule to true for cjs output

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts

Add AKS resource provider in Statsbeat, add missing resource identifiers

---

sdk/keyvault/keyvault-admin/swagger/README.md
sdk/keyvault/keyvault-certificates/swagger/README.md
sdk/keyvault/keyvault-keys/swagger/README.md
sdk/keyvault/keyvault-secrets/swagger/README.md

Updating Autorest config to reference most recent Swagger. Regenerating caused no change in generated code.

[keyvault] Update Swagger commit hash for 7.5-preview.1

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-common/package.json
sdk/communication/communication-common/src/tokenParser.ts

- @azure/communication-common
- #27594
Upgrades from 3.x to 4.x for [`jwt-decode`](https://www.npmjs.com/package/jwt-decode).  This includes a breaking change of the default exports versus single exports.

[communication] Update jwt-decore to 4.0

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/internal/unit/messageSession.spec.ts

Currently in session receiver, we fire-and-forget user's error handler instead of awaiting it. This is causing problems when customer want to modify state in message handler, and want to roll back in case of error as currently we would carry on to abandon the message when error happens, then add credit. The same message could arrive and processed, while the error handling is still going on.
This PR changes it to wait for user error handler before proceeding. This behavior of awaiting user error handler is in line with our streaming receiver and other languages.

[ServiceBus] await error handler in session receiver

---

sdk/test-utils/recorder/package.json

Because the recorder accesses stuff only available in that version.

[Recorder] Update min dep of core-rest-pipeline

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/httpHeaders.ts
sdk/core/core-rest-pipeline/test/httpHeaders.spec.ts
sdk/core/ts-http-runtime/src/httpHeaders.ts
sdk/core/ts-http-runtime/test/httpHeaders.spec.ts

as the spec doesn't allow them:
https://www.rfc-editor.org/rfc/rfc9110#name-field-values

[core] trim leading and trailing whitespace from header values

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/httpHeaders.ts
sdk/core/core-http/test/httpHeadersTests.ts

as the spec doesn't allow them:
https://www.rfc-editor.org/rfc/rfc9110#name-field-values

[core-http] trim leading and trailing whitespace from header values

---

sdk/communication/communication-sms/tests.yml

Done as part of [Task 3499226](https://skype.visualstudio.com/SPOOL/_workitems/edit/3499226): [Reliability] Fix Int pipeline configuration for all SDKs.
Int pipeline yaml definition updated with the new configuration for int environment ([sample execution](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3252150&view=results))

Remove PPE and enable Int livetest runs with SMS specific configuration

---

common/tools/dev-tool/src/util/customization/customize.ts
common/tools/dev-tool/src/util/customization/exports.ts
common/tools/dev-tool/src/util/customization/helpers/annotations.ts
common/tools/dev-tool/src/util/customization/imports.ts
common/tools/dev-tool/src/util/customization/interfaces.ts
common/tools/dev-tool/test/customization/annotations.spec.ts
common/tools/dev-tool/test/customization/exports.spec.ts
common/tools/dev-tool/test/customization/interfaces.spec.ts

dev-tool
This PR changed the following items in the customization tool.
- Enhanced annotations to be able to receive a parameter.
- Added support for a rename annotation for interface properties.
- When modifying a property, it now does it in-place (keeping the original order of properties)
- Added basic export customization support.

Customization additions

---

common/config/rush/pnpm-lock.yaml
sdk/monitor/perf-tests/monitor-opentelemetry/package.json

of
> ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
>
>.
└─┬ @rush-temp/perf-monitor-opentelemetry 0.0.0
└─┬ @opentelemetry/sdk-logs 0.43.0
├── ✕ unmet peer @opentelemetry/api@">=1.4.0 <1.7.0": found 1.7.0
├─┬ @opentelemetry/core 1.17.0
│ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.7.0": found 1.7.0
└─┬ @opentelemetry/resources 1.17.0
└── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.7.0": found 1.7.0

[EngSys] fix `rush update --full` error

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/baseSender.ts

Aligns the statsbeat feature with the spec such that we no longer continue to export statsbeat if an invalid iKey is used.

Stop Sending Statsbeat if iKey is Invalid

---

.nvmrc

To fix Codespaces using Node 16 by default

Update Node version in .nvmrc to v18

---

common/tools/dev-tool/src/util/customization/helpers/preformat.ts

@azure/dev-tool
#26798 
Fixes enums being duplicated by the customization tool.

[Customization] Fix duplicate const enums

---

common/tools/dev-tool/src/util/customization/customize.ts
common/tools/dev-tool/src/util/customization/helpers/preformat.ts
common/tools/dev-tool/src/util/customization/imports.ts
common/tools/dev-tool/test/customization/interfaces.spec.ts

@azure/dev-tool
#26947 
Imports weren't being resolved from the correct file. The behavior we expect is that imports in the generated and custom layers are propagated to the emitted output. If something in the generated layer consumes a local import, the corresponding emitted file should import that symbol from the same relative path. Ditto for the custom layer, but imports from that layer take precedence. Also, when the custom layer imports from the generated layer, the corresponding emitted file should import that symbol from the path of the module relative to the root of the _generated_ layer. This PR is intended to implement the above behavior.

[Customization] Fix import customization

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/StorageClient.ts
sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClient.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClient.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

Storage accounts can be configured allow both HTTP and HTTPS connections. Azurite also uses HTTP.  Unlike core-http, by default Core v2 doesn't allow HTTP. This PR sets `allowInsecureConnection` to `true` for storage clients.
#27813

[storage] allow insecure connections

---

sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client-rest/src/sendRequest.ts
sdk/core/core-client-rest/test/sendRequest.spec.ts

Currently we convert request body to string by default. This isn't always desirable and could be problematic. It breaks Image Analysis scenario where request body needs to be raw bytes.
This PR keeps the raw bytes as the request body when the content type is `applicatoni/octect-stream`. This is a short-term fix to unblock Image Analysis SDK while we investigate for better and long term solutions.
`@azure-rest/core-client`
#27748

[core-client-rest] keep request body as bytes for `application/octet-stream`

---

sdk/core/ts-http-runtime/package.json

Dependency is no longer needed with new form data policy

[ts-http-runtime] drop `form-data` dependency

---

sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/src/http/models.ts
sdk/core/core-lro/src/http/operation.ts

N/A
The LRO polling helpers in RLCs set the `flatResponse` property to the raw response object (not flattened) which confuses the LRO engine in how to retrieve certain properties from the response body. This PR updates the engine to access properties in the raw response bodies as well.
N/A
N/A
N/A

[core-llro] Update logic for fetching resourceLocation

---

sdk/core/core-lro/src/http/operation.ts
sdk/core/core-lro/test/lro.spec.ts

Failure in https://dev.azure.com/azure-sdk/public/_build/results?buildId=3285449&view=ms.vss-test-web.build-test-results-tab&runId=44507543&resultId=100042&paneView=debug
`resourceLocation` is returned by the service as null for some reason, so we need to check if `resourceLocation` not only present but also is not null and not an empty string.
N/A
Yes

[core-lro] Fix resource location check

---

sdk/identity/identity/package.json

I did not create a issue but this PR to solve the issue right away.
I tried to update azure/identety to version 4. But internally this packages uses the azure/core-util package. Here it uses the `randomUUID`. The version 4 requires the core-util in version 1.0.0 which does not include that `randomUUID` function. This leads to an error since the package manager does not update the core-util package since it was already installed in a lower version e.g. 1.1.0. 
This results in an error at runtime, sinde the function `randomUUID` is not defined.
Using the version 1.3.0 resolves the issue sinde this version includes the necesarry `randomUUID` see release notes: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-util/CHANGELOG.md#130-2023-04-06

fix: core-util version

---

common/tools/dev-tool/src/util/customization/customize.ts
common/tools/dev-tool/src/util/customization/helpers/preformat.ts
common/tools/dev-tool/src/util/customization/imports.ts
common/tools/dev-tool/test/customization/interfaces.spec.ts

`template-dpg` has a broken build at the moment due to 5dfa839 As the package has since been added to the core CI pipeline, it needs to be reverted to stop spurious CI failures.
Will be reintroduced with #27824

Revert "[Customization] Fix import customization (#27808)"

---

common/tools/eslint-plugin-azure-sdk/ci.yml
eng/pipelines/templates/steps/test-eslint.yml

I noticed that we were running the unit tests for `@azure/eslint-plugin-azure-sdk` as part of the 'run-eslint' step that gets kicked off as part of `analyze` for every SDK package. This meant we spent 1 minute 30 seconds running unit tests each and every time we ran CI for any package.
My (perhaps incomplete) understanding is that we added running the tests so that the ci.yml for `@azure/eslint-plugin-azure-sdk` could run the tests as part of CI, but I don't think we intended to have them run all the time for everyone.
This change creates a new `test-eslint` template that can be used by `ci.yml` and removes running the unit tests from the normal analyze step.

[engsys] Avoid running eslint plugin unit tests on every analyze

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-client-rest/package.json

for `@azure-rest/core-client` release as v2 hasn't been published yet.

[core-client-rest] downgrade dependency `@azure/abort-controller` to v1

---

eng/pipelines/templates/stages/platform-matrix.json

Latest 21.3.0 contains changes that breaks `writeFileSync` of temp files on
MacOS. This PR unblocks `js - core` release pipeline while we follow up on the
NodeJS issue.

Temporarily pin NodeTestVersion of v21 to 21.2.0

---

common/tools/eslint-plugin-azure-sdk/package.json

instead of .js files. This allows running unit-tests without building them, which is consistent with other packages in the repo.

[test][eslint-plugin] run unit tests on .ts files

---

eng/pipelines/templates/stages/platform-matrix.json

now that a fix to `fs.writeFileSync` has been released.
Revert "Temporarily pin NodeTestVersion of v21 to 21.2.0 (#27951)"
This reverts commit b1a31b3d36e1fd5b0c3e0062567f5ea07c977369.
#27957

[EngSys] unpin NodeTestVersion of 21.2.0

---

sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

We don't minify commonjs output any more. Also there's no `uglifyjs` dev dependency in these package.json files.

[EngSys][KeyVault] remove unused NPM script "build:minify"

---

sdk/openai/openai/package.json

@azure/openai
Fixes https://github.com/Azure/azure-sdk-for-js/issues/28034
Sub-path export for models was broken after the changes for the 2023-12-01-preview API.
N/A
N/A
N/A

[OpenAI] Fix sub-path export for models

---

eng/pipelines/templates/stages/platform-matrix.json

Because of a regression in v21.4.0, running our tests with `esm` package is broken.
https://github.com/nodejs/node/issues/51081
Revert "[EngSys] unpin NodeTestVersion of 21.2.0 (#27999)"
This reverts commit 884d750c2fc130fba6e5501b1a2fd8fef51fcbe9.

[EngSys][Test] Pin NodeTestVersion to 21.2.0 again

---

sdk/maps/maps-geolocation-rest/CHANGELOG.md
sdk/maps/maps-geolocation-rest/README.md
sdk/maps/maps-geolocation-rest/review/maps-geolocation.api.md
sdk/maps/maps-geolocation-rest/src/MapsGeolocation.ts
sdk/maps/maps-render-rest/CHANGELOG.md
sdk/maps/maps-render-rest/README.md
sdk/maps/maps-render-rest/review/maps-render.api.md
sdk/maps/maps-render-rest/src/mapsRender.ts
sdk/maps/maps-route-rest/CHANGELOG.md
sdk/maps/maps-route-rest/README.md
sdk/maps/maps-route-rest/review/maps-route.api.md
sdk/maps/maps-route-rest/src/mapsRoute.ts
sdk/maps/maps-search-rest/CHANGELOG.md
sdk/maps/maps-search-rest/README.md
sdk/maps/maps-search-rest/review/maps-search.api.md
sdk/maps/maps-search-rest/src/MapsSearch.ts

NA
Add SAS token authentication.
NA
No. To get the SAS token, we need to use the `listSas` in arm-maps. However, it requires start & expiry time, which cannot be recoreded for playback test, and I didn't found the `listSas` test in arm-maps, so I believe we don't have a good solution to test it now.

[Maps] SAS token support

---

sdk/apimanagement/api-management-custom-widgets-scaffolder/CHANGELOG.md
sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/execute.js
sdk/apimanagement/api-management-custom-widgets-scaffolder/src/scaffolding.ts

api-management-custom-widgets-scaffolder
https://dev.azure.com/msazure/One/_workitems/edit/25953312
conflicting names of custom and build-in widgets

api-management-custom-widgets-scaffolder displayNameToName fnc with prefix

---

common/tools/dev-tool/package.json

With caret version we can get upgrades from automated weekly run. Also for its main packaeg `semver` we depend on caret version too (`^7.5.4`)
Resolves #25838

[dev-tool] change dev dependency `@types/semver` version to `^7.5.6`

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

Looking at the history, I don't see any functionality changes. https://github.com/janogonzalez/priorityqueuejs/compare/1.0.0...v2.0.0
>v2
>Stop supporting component and browser builds.
but that's just removing the structure used to build and test the package in browsers using components, which doesn't affect our usage.
`@azure/cosmosdb`
#19233

[Engsys][cosmosdb] upgrade runtime dependency `priorityqueuejs` to v2

---

sdk/storage/storage-blob/package.json

It may be useful in perf testing before but no more as we move perf tests out and migrated to Core v2.

[storage-blob] remove unused dev dependency `@types/node-fetch`

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts
sdk/openai/openai/CHANGELOG.md
sdk/openai/openai/assets.json
sdk/openai/openai/sources/customizations/api/client/openAIClient/index.ts
sdk/openai/openai/src/api/client/openAIClient/index.ts
sdk/openai/openai/test/public/node/whisper.spec.ts

@azure/openai & @azure/core-rest-pipeline
https://github.com/Azure/azure-sdk-for-js/issues/28145
The `responseFormat` parameter is included in a form data request. If the customer does not specify it, the parameter is added to the form data request with a value of undefined. However, the form data policy attempts to treat this value as a File object.
To avoid sending an incorrect parameter, the fix is to not send it if it is not set by the customer. Additionally, the core should verify that the form data value is defined and is an object before proceeding to treat it as such.
Yes
N/A

[OpenAI & Core] Fix whisper responseFormat behavior

---

sdk/automanage/arm-automanage/review/arm-automanage.api.md

The api report now has some non-essential changes (known api-extractor issue https://github.com/microsoft/rushstack/issues/2895) likely due to the api-extractor upgrades in PR #27776.
This PR fix the build by commit the api report changes.

[arm-automanage] fix ci build due to api report change

---

.github/CODEOWNERS

The linter pipeline is failing because a user is no longer part of Azure.

Remove defunct user from CODEOWNERS

---

sdk/storage/storage-blob/src/sas/AccountSASPermissions.ts

fix spelling error in AccountSASPermissions.yml

---

sdk/core/core-tracing/.eslintrc.json

@azure/core-tracing 
N/A
As a way to ensure I have the correct roles and credentials set up to commit code, I wanted to make a quick non-impactful change to the repo.
Specifically, two eslint rule overrides can be removed from core-tracing:
- ts-no-const-enums: we no longer export const enums
- ts-versioning-semver: this package now follows proper semver 
With those two overrides removed, we can just remove the eslintrc file entirely and rely on the base config.
No source code changes

[core-tracing] Remove unnecessary ESLint rule overrides

---

common/tools/dev-tool/src/commands/run/vendored.ts

On Windows platform we should use the `.CMD` scripts under `node_modules/./bin/`

[dev-tool] fix `run vendored` command issue on Windows

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/package.json
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/predicates.ts
sdk/eventgrid/eventgrid/src/tracing.ts
sdk/eventgrid/eventgrid/swagger/README.md

NA
The EventGrid Service Team has added 2 new events. The SDK must be regenerated to include the code changes related to these 2 new events. The SDK minor version has been updated.
- `Microsoft.Storage.StorageTaskAssignmentQueued`
- `Microsoft.Storage.StorageTaskAssignmentCompleted`
- https://github.com/Azure/azure-sdk-for-js/pull/27384 (This is the PR that adds similar events to the SDK in the 4.15.0 release)
- https://github.com/Azure/azure-sdk-for-js/pull/26939 (This is the PR that adds similar …

[@azure/eventgrid] Adding new events for EG Version 5.1.0

---

sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts
sdk/core/core-rest-pipeline/test/formDataPolicy.spec.ts

- Fixes #28081
According to the `multipart/form-data` specification, binary content should have a default Content-Type of `application/octet-stream` if none is provided. Not supplying a `Content-Type` value implies that the content is text-based with a default encoding.
This PR corrects behavior so that form fields with values of type `Blob` and `File` have their content type set to `application/octet-stream` in the multipart request if no other content type is specified.
Fixed existing test to conform to corrected behavior.

[core] Default to `application/octet-stream` content type for multipart blobs

---

common/tools/vite-plugin-browser-test-map/package.json
common/tools/vite-plugin-browser-test-map/src/index.ts

Fix following errors when running "npm run lint"
```
> eslint src --ext .ts
Oops! Something went wrong! :(
ESLint: 8.56.0
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
npm init @eslint/config
ESLint looked for configuration files in /home/meng/git/jssdk/common/tools/vite-plugin-browser-test-map/src and its ancestors. If it found none, it then looked in your home directory.
```
and
```
4:36  error    Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead …
```

[tool] fix linting of vite-plugin-browser-test-map

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-identity/package.json
sdk/communication/communication-identity/samples/v1/javascript/package.json
sdk/communication/communication-identity/samples/v1/typescript/package.json

This reverts commit 60a6bd5a3a22e30950b2520edc8939c8d7be1186.
Look that PR #28180 removed our last dependency on @azure/msal-node 1.18.4 from communication-identity and broke live tests.
It's possible that because @azure/msal-node v2 is now ESM ("type": "module"), and our .js tests failed to require it.

Revert "[EngSys][comm-identity] upgrade dependency `@azure/msal-node` to ^2.5.1 (#28180)"

---

sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts
sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts
sdk/core/ts-http-runtime/src/createPipelineFromOptions.ts
sdk/core/ts-http-runtime/src/policies/formDataPolicy.ts

@azure/ts-http-runtime
N/A
This PR makes two minor changes to the core packages, neither should result in
behavior change at runtime.
- Moves setting the requests' multipartBody outside the loop to avoid setting it
repeatedly. The end result is the same, since we return early if there is no form data.
- Explicitly declares an ordering between multipartPolicy and formDataPolicy to
ensure the two are always sequenced correctly. This happens implicitly today but
will now be enforced.
Both of these changes were spin-offs of changes in #28083
N/A 
There are no behavior changes to test - these should be considered pure refactors
https://github.com/Azure/azure-sdk-for-js/pull/28083/

[core] Enforce ordering of formData and multipart policies

---

tsconfig.json

All data-plane packages that inherit from our global tsconfig.
Noticed our default emit target was es2017, but es2020 has been [fully supported in Node since 16.5](https://node.green/). As our minimum runtime is now Node 18, it feels safe to bump up the minimum here. This will also let us use things like BigInt and String.prototype.matchAll.

[engsys] Update default TypeScript compilerOptions for data plane packages

---

sdk/identity/identity/src/constants.ts
sdk/identity/identity/test/authTestUtils.ts

- None documented
- Fix min-max tests in live test pipeline. The failures occur due to references to non-public constants of the sdk code through the public tests. So fixing these references will potentially solve the pipeline failures.

[Identity] potentially fix min-max tests

---

sdk/maps/maps-search-rest/package.json

Change the dependency `@azure/logger` to 1.0.4 since 1.0.5 is not release yet.

[Azure Maps] Update @azure/logger version

---

common/config/rush/command-line.json
common/tools/eslint-plugin-azure-sdk/package.json
common/tools/vite-plugin-browser-test-map/package.json
sdk/eventhub/mock-hub/package.json

- make the command optional, as some generated packages don't have this command
- add "lint:fix" to eslint-plugin-azure-sdk and vite-plugin-browser-test-map
- fix typo in mock-hub's "lint:fix" command

[EngSys] fix "rush lint:fix"

---

sdk/servicebus/service-bus/package.json

This ensures we can use the newly added constants `maxUint32Value`

[ServiceBus] bump runtime dependency core-amqp version to ^4.1.1

---

sdk/batch/batch/package.json
sdk/vision/ai-vision-image-analysis-rest/package.json

We have moved to use Mocha's builtin XUnit reporter
Resolves #28242

[engsys] remove unused dev dependency `mocha-junit-reporter`

---

tsconfig.json

as we still rely on `esm` to run dist-esm/**/*.spec.js tests, and newer syntaxes are not supported.
Revert "[engsys] Update default TypeScript compilerOptions for data plane packages (#28223)"
This reverts commit 209ce9c84d1bf5162dfa4dbb5e1fa09174965331.

[engsys] revert compilerOptions back to target ES2017

---

common/config/rush/command-line.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

as core-util browser testing is broken by 1.2.0 with the following error
https://github.com/vitest-dev/vitest/issues/4984
```
FAIL  test/public/aborterUtils.spec.ts > createAbortablePromise > should resolve if not aborted nor rejected
ReferenceError: process is not defined
❯ test/public/aborterUtils.spec.ts:30:21
28|
29|   it("should resolve if not aborted nor rejected", async function () {
30|     const clock = vi.useFakeTimers();
|                     ^
31|     const promise = createPromise();
32|     await clock.advanceTimersToNextTimerAsync();
```

[engsys] pin vitest and @vitest/browser version to 1.1.3

---

sdk/core/core-rest-pipeline/package.json

which was accidentally removed.

[core-rest-pipeline] add back dev dependency of `@types/node`

---

common/config/rush/pnpm-lock.yaml
sdk/attestation/attestation/package.json

The breaking changes from 10.9.0 to 11.0.0 is removing of some RSA encryptions/decryptions. Looks that JS SDK is not affected.
https://github.com/kjur/jsrsasign/releases/tag/11.0.0
Resolves #28270

[EngSys][Attestation] upgrade dependency `jsrsasign` version to ^11.0.0

---

common/config/rush/command-line.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
rush.json
sdk/core/core-rest-pipeline/package.json
sdk/core/core-util/package.json

@azure/core-util
#28256
We discovered a bug in [vitest 1.2.0](https://github.com/vitest-dev/vitest/issues/4984) 
which has now been fixed. Given that release 1.2.1 includes this bug fix, we can
remove our workaround of pinning vitest.
Fixes #28256

[core] Upgrade vitest to 1.2.1

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/msal/browserFlows/msalAuthCode.ts
sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts

https://github.com/Azure/azure-sdk-for-js/issues/28215
- The public client application needs to be initialized explicitly with the new version of msal-browser. This affects the browser-side's Interactive Browser Credential which throws the `unitialized_public_client` error from @azure/msal-browser when trying to authenticate with the getToken() call.
- We can either call the initialize() method on the public application's instance OR we can call the `createPublicClientApplication()` method for initializing the public client application, like we are doing in this PR
- No, will open a separate PR for test cases and samples for IBC credentials. As this focuses on ONLY the changes needed for the bug fix.

[Identity] Initialize public client application before API calls for msal-browser - IBC

---

eng/pipelines/templates/stages/archetype-js-release.yml

The purpose is to gate on the REST API specifications used to release SDK are from the main branch of [Azure/azure-rest-api-spec](https://github.com/Azure/azure-rest-api-specs).
All the data plane GA packages to be released.
I scanned through this JS repo and identified 11 data plane services that have released GA packages but their configuration file either `tsp-location.yaml` or `swagger\README.md` reference the REST API specs from a non-main branch of Azure spec repo.
Please refer to [this spreadsheet](https://microsoftapc-my.sharepoint.com/:x:/g/personal/raychen_microsoft_com/ETMHnmWSA6VKmGouTjAITwEBqSavTLQkOcd2Ykx2eEE8_g?e=oalb1N) to get the details of all the violated packages.
After this PR is merged, the next GA release for these packages will be blocked. They need to correct the …

Added pipeline to validate spec location

---

eng/pipelines/templates/stages/archetype-js-release.yml

Reverts Azure/azure-sdk-for-js#28303
There is an incorrect assumption at https://github.com/Azure/azure-sdk-for-js/blob/main/eng/common/scripts/Verify-RestApiSpecLocation.ps1#L235 for the JS repo which doesn't have the package name in the path like other languages.

Revert "Added pipeline to validate spec location"

---

sdk/monitor/monitor-opentelemetry/perf.yml

Perf tests.. switching from 1.1.2 to 1.1.1, since 1.1.2 is not published yet

[monitor-opentelemetry] Compare between the published version and the src 

---

sdk/openai/openai/CHANGELOG.md
sdk/openai/openai/assets.json
sdk/openai/openai/review/openai.api.md
sdk/openai/openai/sources/customizations/models/models.ts
sdk/openai/openai/src/models/models.ts
sdk/openai/openai/src/rest/models.ts
sdk/openai/openai/test/public/completions.spec.ts

@azure/openai
https://github.com/Azure/azure-sdk-for-js/issues/28325
@jmaczan found that the spec contains a bug in representing an input option to chat completions. The spec is being fixed in https://github.com/Azure/azure-rest-api-specs/pull/27487.
N/A
Yes
https://github.com/Azure/azure-rest-api-specs/pull/27487

[OpenAI] Fix toolChoice

---

sdk/communication/communication-rooms/tests.yml

None
INT environment was used to run ACS Rooms Live Test SDK. However, the resource is actually from PPE. Therefore, update it to use PPE environment.
Updated Rooms Live Test SDK to use PPE instead of INT environment
None

Updated Rooms Live Test SDK to use PPE

---

.vscode/cspell.json
sdk/identity/identity/src/msal/browserFlows/msalAuthCode.ts
sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalAuthorizationCode.ts
sdk/identity/identity/src/msal/nodeFlows/msalClientAssertion.ts
sdk/identity/identity/src/msal/nodeFlows/msalClientCertificate.ts
sdk/identity/identity/src/msal/nodeFlows/msalClientSecret.ts
sdk/identity/identity/src/msal/nodeFlows/msalDeviceCode.ts
sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalOnBehalfOf.ts
sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts
sdk/identity/identity/src/msal/nodeFlows/msalUsernamePassword.ts
sdk/identity/identity/src/msal/utils.browser.ts
sdk/identity/identity/src/msal/utils.ts
sdk/identity/identity/test/node/msalNodeTestSetup.ts

N/A 
As we start to cleanup and refactor Identity, one of the low hanging fruits we can remove right now is the MsalBaseUtils class
which all the MsalFlows inherit from. By standardizing here we can start to peel away some of the inheritance based indirection
and move towards composition of smaller building blocks.
I tried to minimize the number of changes and make this a pure refactor, as 1:1 to the existing behavior as possible while we 
work out the larger refactor of the Msal inheritance based flows. 
This is a pure refactor

[identity] Remove MsalBaseUtils class

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/azureCliCredential.ts
sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts

Resolves #27648
In version 2.54.0 the Azure CLI started including an `expires_on` field
containing a POSIX timestamp in seconds in addition to the existing `expiresOn`
field denoting the expiry in RFC3339 format.
We want to migrate to `expires_on` when the underlying az cli supports it and
fallback to the existing `expiresOn` otherwise.
https://github.com/Azure/azure-sdk-for-net/pull/41366
https://github.com/Azure/azure-sdk-for-cpp/issues/5075

[identity] Use expires_on if az cli credential provides it

---

eng/pipelines/templates/stages/archetype-js-release.yml

This PR is to add back the spec location validation back to the release pipeline.
Here is the original PR which was reverted by an issue of the JS package path.
https://github.com/Azure/azure-sdk-for-js/pull/28303
Here is the PR of the fix of common script that has been merged:
https://github.com/Azure/azure-sdk-tools/pull/7569
This is the [test run result](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3433518&view=logs&j=7bb69cc7-6f52-585e-8b13-5bae7c4a9fa4&t=7abbbe6b-d005-5c95-feb6-99ffe4e699e1) in JS repo.
@weshaggard @jeremymeng , please review.

Added spec location validation pipeline

---

sdk/identity/identity/assets.json
sdk/identity/identity/recordings/node/clientcertificatecredential_internal_parsecertificate/recording_includes_the_x5c_value_when_sendcertificatechain_is_true.json
sdk/identity/identity/recordings/node/clientcertificatecredential_internal_parsecertificate/recording_omits_the_x5c_value_when_sendcertificatechain_is_false.json

An order-of-operations when merging #28391 and #28361 means that two recordings
still need to be migrated over. 
This PR addresses that, moving the last two recordings to the assets repo

[identity] Clean up remaining recordings

---

common/tools/dev-tool/src/commands/run/testVitest.ts

- verbose reporter allows us to see all passing and failing tests
- junit reporter writes result files for devops pipeline to upload to associated builds

[dev-tool] add reporter options to vitest command line

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/package.json
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-lro/package.json
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts
sdk/core/core-util/CHANGELOG.md
sdk/core/core-util/package.json

- bump minor versions for @azure/abort-controller dependency version upgrade

[core] Prepare for Feb 2024 releases

---

sdk/test-utils/recorder/src/index.ts
sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/recorder/src/testInfo.ts
sdk/test-utils/recorder/src/utils/sessionFilePath.ts
sdk/test-utils/recorder/test/recorder.spec.ts

Currently we just need suite title and test title to generate recording file names. `vitest` provides the info via `context` of the callback function.
This PR adds vitest support to recorder. Call site would look like
```ts
//...
beforeEach(async (context) => {
recorder = new Recorder(context);
```

[test-recorder] Support test context from vitest

---

sdk/identity/identity/test/internal/identityClient.spec.ts
sdk/identity/identity/test/internal/node/onBehalfOfCredential.spec.ts
sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/public/node/clientSecretCredential.spec.ts
sdk/identity/identity/test/public/node/usernamePasswordCredential.spec.ts

- fix unreachable host test
- fix second test
- put expected and actual in the right place
- [identity] Fix tests due to MSAL behavior change
Resolves #28413 
in 2.6.2, @azure/msal-node made some changes to their implementation which impacted our tests. Additional details can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6859). I'll save you a click:
>  In 2.6.2 we fixed a bug affecting how we resolve endpoints. MSAL.js ships with hardcoded endpoints for Microsoft authorities and the bug prevented these from being used, resulting in making a network request to resolve these endpoints.
Adding insult to injury, our integration tests still pull in MSAL 1.x as 2.x is not compatible with our ESM package 😠 whatever
changes we make here …

[identity] Fix tests for msal-node 2.6.2

---

sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/src/msal/utils.ts
sdk/identity/identity/test/node/msalNodeTestSetup.ts

N/A - prepares Identity for #26238
When core moves to ESM, we can no longer directly stub out core-util's
randomUUID as (as far as I understand it) ESM modules are immutable.
In the future, vitest's import maps (IIRC) would help alleviate this pain, but
this should be a reasonable solution to unblock core's migration to ESM.
#26238

[identity] prepare for core's ESM migration

---

sdk/core/core-util/src/checkEnvironment.ts
sdk/core/ts-http-runtime/src/util/checkEnvironment.ts

- @azure/core-util
The current logic would show Bun reporting as Node.  This changes the logic to ensure that Bun and Deno are detected correctly.  Bun gives the following information which can make it seem like it is Node as it has a `node` and `bun` version.
```js
> process.versions
{
node: '21.6.0',
bun: '1.0.25',
webkit: 'a780bdf0255ae1a7ed15e4b3f31c14af705facae',
boringssl: 'b275c5ce1c88bc06f5a967026d3c0ce1df2be815',
openssl: '1.1.0',
libarchive: 'dc321febde83dd0f31158e1be61a7aedda65e7a2',
mimalloc: '7968d4285043401bb36573374710d47a4081a063',
picohttpparser: '066d2b1e9ab820703db0837a7255d92d30f0c9f5',
uwebsockets: 'a8ff7be642a3cd93e033b324cfd1fc966b69af12',
zig: '0.12.0-dev.1828+225fe6ddb',
zlib: '885674026394870b7e7a05b7bf1ec5eb7bd8a9c0',
tinycc: …
```

[core] Update bun and deno checks

---

common/tools/dev-tool/src/commands/run/testVitest.ts
common/tools/eslint-plugin-azure-sdk/tsconfig.json

running `npm run format` on dev-tool and eslint-plugin-azure-sdk to fix check-format error

[dev-tool,eslint-plugin] format

---

sdk/monitor/monitor-opentelemetry/review/monitor-opentelemetry.api.md
sdk/monitor/monitor-opentelemetry/src/index.ts
sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
sdk/monitor/monitor-opentelemetry/src/shared/types.ts
sdk/monitor/monitor-opentelemetry/src/traces/handler.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts

[Azure Monitor OpenTelemetry] Allow spanProcessors and logRecordProcessors to be passed as options.

---

eng/scripts/Language-Settings.ps1

Needed for https://github.com/Azure/azure-sdk-tools/pull/7629 to work
Example pipeline working: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3467799&view=logs&j=5e8cddd4-765d-5046-f31f-2d7d6b215293&t=5e8cddd4-765d-5046-f31f-2d7d6b215293 (note CreateDocIndex works)

Domain-specific changes to fix docindex

---

sdk/openai/openai-assistants/package.json

We already replaced it with the Mocha builtin reporter. This instance must have been included because of an older version of codegen.
Resolves issue #28467.

[EngSys] remove leftover dev dependency `mocha-junit-reporter`

---

sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/review/communication-common.api.md
sdk/communication/communication-common/src/identifierModelSerializer.ts

communication-common
Renaming field `teamsAppId` to `appId` to match REST specification.

[JS] Communication Common | Renaming field name in Microsoft Teams App Identifier Serializer

---

sdk/monitor/monitor-opentelemetry/README.md

README refers to a no-longer supported "config" property on the browser SDK loader.

[Monitor OpenTelemetry] Fix README

---

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
sdk/monitor/monitor-opentelemetry/src/shared/config.ts

#28433
Types are set incorrectly on the resource detector returned resources.

[Azure Monitor OpenTelemetry] Fix Resource Type Issue

---

sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
sdk/identity/identity/src/msal/types.ts
sdk/identity/identity/src/msal/utils.ts

Split off a chunk from PR #28493
Splitting off a chunk discovered in
[#28493](https://github.com/Azure/azure-sdk-for-js/pull/28493/files/484b309d3b2b3ed861bafba4f969c34ea73f8e30#r1480584766)
to show what it might look like and provide smaller commits.
This replaces the type signature of ensureValidMsalToken from void to an
assertion function and allow TypeScript to better understand that the properties
we requested exist and are valid.
I had to introduce a new type to avoid changing existing types which are relied
on in other areas
No, this is just type changes. Internal and do not require a changelog or tests.
#28493

[identity] Remove ! operators from accessToken handlers

---

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatExporter.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/baseSender.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts
sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts

We should fail silently if errors occur in the sender when sending statsbeat metrics.
Yes

[Monitor OpenTelemetry Exporter] Do Not Diag.Error If Sender is Sending Statsbeat Signals

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/policies/proxyPolicy.ts
sdk/core/core-rest-pipeline/test/node/proxyPolicy.spec.ts
sdk/core/ts-http-runtime/package.json
sdk/core/ts-http-runtime/src/policies/proxyPolicy.ts
sdk/core/ts-http-runtime/test/node/proxyPolicy.spec.ts

- https://github.com/Azure/azure-sdk-for-js/security/dependabot/49
Upgrades to the 7.x version of the `https-proxy-agent` and `http-proxy-agent` used for our proxy pipelines.

[core] Upgrade http(s)-proxy-agent

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/samples-dev/websockets.ts
sdk/eventhub/event-hubs/samples/v5/javascript/package.json
sdk/eventhub/event-hubs/samples/v5/javascript/websockets.js
sdk/eventhub/event-hubs/samples/v5/typescript/package.json
sdk/eventhub/event-hubs/samples/v5/typescript/src/websockets.ts
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples/v7-beta/javascript/package.json
sdk/servicebus/service-bus/samples/v7-beta/typescript/package.json
sdk/servicebus/service-bus/samples/v7/typescript/package.json

- @azure/event-hubs
- @azure/service-bus
- https://github.com/Azure/azure-sdk-for-js/security/dependabot/49
Updates with the latest `https-proxy-agent` which does not have the vulnerability.

[messaging] Update https-proxy-agent

---

sdk/openai/openai-assistants/sources/customizations/api/operations.ts
sdk/openai/openai-assistants/sources/customizations/api/util.ts

https://github.com/Azure/azure-sdk-for-js/issues/28561
All date instances created from OpenAI responses are broken as OpenAI uses unix timestamp and new Date(...) results in a date sometime in 1970
I can add tests if this PR will get any attention 🙏🏼

[@azure/openai-assistants] Properly convert OpenAI unix timestamps to Date

---

.github/CODEOWNERS

Adding Maor as reviewer for Key Vault since he is back on the team and has lots of experience in this area!

Add Maor as code owner for keyvault

---

common/tools/dev-tool/src/config/rollup.base.config.ts

By conventions rollup plugins prefix virtual modules with \0. Other plugins should not try to process those virtual modules.
This PR updates our load-source-maps plugin to ignore modules whose id starts with "\x00" thus fixes the following warning.
```
(!) Plugin load-source-maps: TypeError: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00commonjsHelpers.js'
at open (node:internal/fs/promises:605:10)
at readFile (node:internal/fs/promises:1085:20)
at Object.load (/home/runner/work/rushstack/rushstack/jssdk/common/tools/dev-tool/src/config/rollup.base.config.ts:141:36)
at /home/runner/work/rushstack/rushstack/jssdk/common/temp/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/shared/rollup.js:1009:40
at async …
```

[dev-tool] fix TypeError warning in load-source-maps Rollup plugin

---

sdk/core/core-client/README.md

core-client doesn't provide sample code because it is not intended to be consumed directly by Azure SDK customers.

[doc][core-client] fix broken link

---

sdk/core/abort-controller/package.json
sdk/core/core-auth/package.json
sdk/core/core-client-rest/package.json
sdk/core/core-client/package.json
sdk/core/core-http-compat/package.json
sdk/core/core-lro/package.json
sdk/core/core-paging/package.json
sdk/core/core-rest-pipeline/package.json
sdk/core/core-sse/package.json
sdk/core/core-tracing/package.json
sdk/core/core-util/package.json
sdk/core/core-xml/package.json
sdk/core/logger/package.json
sdk/core/ts-http-runtime/package.json

The feature is to support any modules inside of the package to be able to import from the `dist/` of the package itself.  Currently we only ever need that for samples development and for that we add "paths" in tsconfig.json to point to the package's src/index.ts. We haven't needed to import a sub path down in `dist/`.
This PR disables selfLink for now until there's a need. Because with it enabled, tshy creates symlinks under the dist/ directory which broken build cache.
More info can be found at https://github.com/isaacs/tshy?tab=readme-ov-file#local-package-exports

[core] disable tshy selfLink

---

sdk/cosmosdb/cosmos/package.json

When we switched to Mocha built-in XUnit reporter, we missed adding the reporter option for cosmos db, resulting in test-results.xml not being generated.
This PR adds the missing option.

[EngSys][cosmos] add reporter-option to integration test command

---

sdk/storage/storage-common/src/PooledBuffer.ts

Related: https://github.com/Azure/azure-sdk-for-js/issues/27759
The comment suggests that importing may not work in the past. However, it builds fine and tests are passing now on our supported platforms.
`@azure/storage-*`

[Storage] remove usage of `require("buffer")`

---

common/tools/dev-tool/src/commands/run/testNodeTSInput.ts

Turns out that it is not needed. Mocha is able to load .ts test files without it.

[dev-tool] remove `-r esm` from `test:node-ts-input` options

---

sdk/identity/identity-cache-persistence/CHANGELOG.md
sdk/identity/identity-cache-persistence/package.json

@azure/identity-cache-persistence
Resolves #28608
@azure/identity-cache-persistence was never released with msal-node 2.x support.
As a result, it does not support node 20.
Further, the [released version](https://deps.dev/npm/%40azure%2Fidentity-cache-persistence/1.0.0/dependencies)
still depends on an alpha version of msal-node-extensions.
This PR preps the release of 1.1.0 with fixes to both of these.
There are no tests in this package unfortunately. I will validate manually
against our nightly build and add a tracking issue to add tests.

[identity] Prepare cache persistence plugin for release

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/samples/AzureCacheForRedis/ioredis.md
sdk/identity/identity/samples/AzureCacheForRedis/node-redis.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/28511
Begin using the new, human-readable scope (https://redis.azure.com/.default) in the ioredis & node-redis passwordless code samples for Redis.
https://github.com/Azure/azure-sdk-for-java/pull/38747/files

[Identity] update redis samples with scopes and TSG guide

---

sdk/search/ci.yml

@search/search-documents
Adds the `search/stable` branch, the source of truth for GA releases, to the CI and live test pipelines.

[search] Enable CI and live test pipelines on search/stable branch

---

.github/CODEOWNERS
.github/CODEOWNERS_baseline_errors.txt

In order to aid with autotriage, we have to set some additional metadata inside of CODEOWNERS.
The main shift is we need to tag things with #ServiceLabel in order to have issues be triaged appropriately. Secondarily, for SDKs that are owned by the SDK team (anyone under Peter) we need to add an AzureSdkOwners entry even if it's redundant with the path ownership.
Related PRs from other languages:
https://github.com/Azure/azure-sdk-for-net/pull/41995
https://github.com/Azure/azure-sdk-for-java/pull/38797
I didn't touch Mgmt paths, will check with @lirenhe if this is something he can take care of.
While I was making changes, I cleaned up some errors that GitHub was complaining about when viewing the file.

[CODEOWNERS] Fix issues and label dataplane paths

---

sdk/identity/identity/assets.json
sdk/identity/identity/src/msal/nodeFlows/msalClient.ts
sdk/identity/identity/src/msal/utils.ts
sdk/identity/identity/test/internal/node/msalClient.spec.ts
sdk/identity/identity/test/node/msalNodeTestSetup.ts

Resolves #28692
Before we start adding features to MSAL Client, we need to have confidence that our stack and integration
with MSAL is properly setup.
This PR adds a place for recorded tests, removes the msalNodeTestSetup call from non-recorded tests,
and moves the "it supports clientSecretCredential" test to a recorded test
We could have pushed for _everything_ to be recorded, but some of the niche scenarios we setup are convoluted 
to test without mocking anyway. This moves us in the direction we want without over-complicating things

[identity] Add recorded test for MSAL Client
