Azure/azure-sdk-for-js

- sdk/core/core-lro/src/http/operation.ts
Addresses feedback in https://github.com/Azure/azure-sdk-for-js/pull/27873/files#r1402822669
> [core-lro] Fix resource location check

- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/review/core-client.api.md
- sdk/core/core-client-rest/src/restError.ts
- sdk/core/core-client-rest/test/createRestError.spec.ts
- sdk/core/ts-http-runtime/review/ts-http-runtime.api.md
- sdk/core/ts-http-runtime/src/client/restError.ts
- sdk/core/ts-http-runtime/test/client/createRestError.spec.ts
https://github.com/Azure/autorest.typescript/pull/1997#discussion_r1401339120
> add-overload-for-create-rest-error

- sdk/communication/communication-identity/CHANGELOG.md
- sdk/communication/communication-identity/src/constants.ts
- sdk/communication/communication-identity/src/generated/src/identityRestClient.ts
- sdk/communication/communication-identity/src/generated/src/tracing.ts
- sdk/communication/communication-identity/swagger/README.md
Granular Token feature GA release of the communication-identity SDK - 1.3.0
> [JS] Communication Identity | Granular Token feature GA release updates

- sdk/core/core-client-rest/CHANGELOG.md
> [core-client-rest] prepare for 2023-11-30 release

- rush.json
- rush version to 5.112.1
- pnpm version to 8.11.0
> [engsys] upgrade rush and pnpm versions

- sdk/communication/communication-chat/CHANGELOG.md
Update `Changelog` for the `ChatSDK 1.4.0` release
> [ChatSDK][GA]Update Changelog.md for 1.4.0 GA release

- sdk/search/arm-search/README.md
- sdk/search/search-documents/README.md
> Azure AI Search rebranding and messaging

- .vscode/cspell.json
- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callMedia.ts
- sdk/communication/communication-call-automation/src/models/models.ts
> Fixing naming typo for Play Source Id

- sdk/communication/communication-chat/src/chatClient.ts
Fix the issue found in the Chat JS SDK beta release
> [ACS][Chat] Provide API version to Signaling Client

- sdk/template/perf-tests/template/package.json
- sdk/template/perf-tests/template/test/getConfigurationSetting.spec.ts
- sdk/test-utils/recorder/package.json
- sdk/test-utils/recorder/test/sanitizers.spec.ts
- sdk/test-utils/recorder/test/utils/server.browser.ts
- sdk/test-utils/recorder/test/utils/server.ts
- sdk/test-utils/recorder/test/utils/utils.ts
- @azure-tools/test-recorder
- @azure-tests/perf-template
> [test-utils] Remove UUID module

- sdk/tables/data-tables/package.json
- sdk/tables/data-tables/samples-dev/createAndDeleteTable.ts
- sdk/tables/data-tables/src/utils/uuid.ts
- sdk/tables/perf-tests/data-tables/package.json
- sdk/tables/perf-tests/data-tables/test/createComplexEntity.spec.ts
- sdk/tables/perf-tests/data-tables/test/createComplexEntityBatchTest.spec.ts
- sdk/tables/perf-tests/data-tables/test/createSimpleEntity.spec.ts
- sdk/tables/perf-tests/data-tables/test/createSimpleEntityBatchTest.spec.ts
- sdk/tables/perf-tests/data-tables/test/index.spec.ts
- sdk/tables/perf-tests/data-tables/test/listComplexEntities.spec.ts
- sdk/tables/perf-tests/data-tables/test/listSimpleEntities.spec.ts
- sdk/tables/perf-tests/data-tables/test/tables.spec.ts
- sdk/tables/perf-tests/data-tables/test/utils/createBaseEntity.ts
- @azure/data-tables
- @azure-tests/perf-data-tables
> [tables] Remove UUID module

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationClient.ts
- sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
- sdk/communication/communication-call-automation/src/callMedia.ts
- sdk/communication/communication-call-automation/src/generated/src/models/index.ts
- sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
- sdk/communication/communication-call-automation/src/models/events.ts
- sdk/communication/communication-call-automation/src/models/models.ts
- sdk/communication/communication-call-automation/src/models/options.ts
- sdk/communication/communication-call-automation/swagger/README.md
- sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
- Added live transcription functionality and tests
> Live transcription functionality

- .vscode/cspell.json
- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callMedia.ts
- sdk/communication/communication-call-automation/src/models/models.ts
> Updating deprecated names

- sdk/contentsafety/ai-content-safety-rest/CHANGELOG.md
- sdk/contentsafety/ai-content-safety-rest/README.md
> [@azure-rest/ai-content-safety] Update README and CHANGELOG

- .github/ISSUE_TEMPLATE/learn-feedback.yml
- .github/ISSUE_TEMPLATE/z-learn-feedback.yml
Related to https://github.com/Azure/azure-sdk-for-java/pull/38000
> Add issue template for new learn.microsoft.com feedback control

- sdk/appconfiguration/app-configuration/package.json
- sdk/appconfiguration/app-configuration/test/internal/node/throttlingRetryPolicy.spec.ts
- sdk/appconfiguration/perf-tests/app-configuration/package.json
- sdk/appconfiguration/perf-tests/app-configuration/test/listSettings.spec.ts
- @azure/app-configuration
Removes the UUID module in favor of @azure/core-util.
> [appconfiguration] Remove UUID

- .gitignore
- eng/scripts/Language-Settings.ps1
Add required overload in LanguageSettings.ps1 to support code generation from the [autorest.typescript - preview](https://dev.azure.com/azure-sdk/internal/_build?definitionId=6415) pipeline
> Add support for autorest preview pipeline

- sdk/servicebus/service-bus/src/core/linkEntity.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
to improve logging.  This is similar to other existing lock tokens.
> [ServiceBus] add prefix to locks

- sdk/synapse/synapse-artifacts/CHANGELOG.md
- sdk/synapse/synapse-artifacts/package.json
- sdk/synapse/synapse-artifacts/review/synapse-artifacts.api.md
- sdk/synapse/synapse-artifacts/src/artifactsClient.ts
- sdk/synapse/synapse-artifacts/src/models/index.ts
- sdk/synapse/synapse-artifacts/src/models/mappers.ts
- sdk/synapse/synapse-artifacts/src/tracing.ts
- sdk/synapse/synapse-artifacts/swagger/README.md
> Synapse SDK new release

- eng/tools/analyze-deps/package-lock.json
- eng/tools/analyze-deps/package.json
- eng/tools/dependency-testing/package.json
- eng/tools/eng-package-utils/package.json
- eng/tools/generate-doc/package.json
- eng/tools/versioning/package.json
Eng sys script tools
None
Updating package dependencies to latest.
> [Eng sys] update package versions for eng sys tools

- common/config/rush/pnpm-lock.yaml
- sdk/apimanagement/api-management-custom-widgets-tools/CHANGELOG.md
- sdk/apimanagement/api-management-custom-widgets-tools/package.json
api-management-custom-widgets-tools
https://github.com/Azure/azure-sdk-for-js/issues/27975
update of an outdated package
> package "mime" updated

- common/config/rush/pnpm-lock.yaml
- sdk/automanage/arm-automanage/package.json
- sdk/automation/arm-automation/package.json
- sdk/cognitivelanguage/ai-language-textauthoring/package.json
- sdk/dnsresolver/arm-dnsresolver/package.json
- sdk/education/arm-education/package.json
- sdk/labservices/arm-labservices/package.json
- sdk/loadtesting/arm-loadtesting/package.json
- sdk/logic/arm-logic/package.json
- sdk/machinelearningexperimentation/arm-machinelearningexperimentation/package.json
- sdk/managementpartner/arm-managementpartner/package.json
- sdk/marketplaceordering/arm-marketplaceordering/package.json
- sdk/migrate/arm-migrate/package.json
- sdk/msi/arm-msi/package.json
- sdk/openai/openai/samples/cookbook/bringYourOwnData/package.json
- sdk/operationalinsights/arm-operationalinsights/package.json
- sdk/policyinsights/arm-policyinsights/package.json
- sdk/portal/arm-portal/package.json
- sdk/powerbidedicated/arm-powerbidedicated/package.json
- sdk/relay/arm-relay/package.json
- sdk/scvmm/arm-scvmm/package.json
- sdk/securitydevops/arm-securitydevops/package.json
- sdk/securityinsight/arm-securityinsight/package.json
- sdk/servicebus/arm-servicebus/package.json
- sdk/servicefabricmesh/arm-servicefabricmesh/package.json
- sdk/storageimportexport/arm-storageimportexport/package.json
- sdk/synapse/arm-synapse/package.json
- sdk/vmwarecloudsimple/arm-vmwarecloudsimple/package.json
Most of packages have been updated as well as codegen.  This RP upgrades left-over packages.
Resolves #19217
> [EngSys] upgrade dev dependency `dotenv` to version `^16.0.0`

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/package.json
- sdk/core/core-sse/CHANGELOG.md
- sdk/openai/openai/package.json
Prepare release for core-client-rest and core-sse with bug fixes needed by openai.
> [core] Prepare release

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/package.json
- sdk/search/search-documents/package.json
Update changelog entry & version in package.json
> [OpenAI] Post-release Changelog Update

- .github/CODEOWNERS
Remove a user that is no longer in Azure.
> Remove a defunct user from CODEOWNERS

- sdk/maps/maps-geolocation-rest/CHANGELOG.md
- sdk/maps/maps-render-rest/CHANGELOG.md
- sdk/maps/maps-route-rest/CHANGELOG.md
- sdk/maps/maps-search-rest/CHANGELOG.md
- @azure-rest/geolocation
NA
Update change log for Jan release
> [Maps] 2024 Jan release

- sdk/identity/identity-broker/test/internal/node/interactiveBrowserCredential.spec.ts
None
Failing build for  broker package because of `import` statement
> [Identity] fix the build for failing identity pipeline

- .github/CODEOWNERS
> Update CODEOWNERS Backup

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationClient.ts
- sdk/communication/communication-call-automation/src/generated/src/models/index.ts
- sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
- sdk/communication/communication-call-automation/src/generated/src/models/parameters.ts
- sdk/communication/communication-call-automation/src/generated/src/operations/callDialog.ts
- sdk/communication/communication-call-automation/src/generated/src/operationsInterfaces/callDialog.ts
- sdk/communication/communication-call-automation/src/models/options.ts
- sdk/communication/communication-call-automation/swagger/README.md
> [ACS][CallAutomation]answer api has alternate caller id, mute returns 202

- sdk/maps/maps-render-rest/README.md
> Update Render API URL in README

- sdk/maps/maps-search-rest/CHANGELOG.md
- sdk/maps/maps-search-rest/README.md
> [Azure Maps]Update Maps Search V2 links

- eng/emitter-package-lock.json
- eng/emitter-package.json
Bump the ts emitter version to 0.20.0
> bump-ts-emitter-version

- sdk/openai/openai/assets.json
Re-record audio tests and update the assets link file
> [OpenAI] Update Recordings for Whisper

- sdk/identity/identity/CHANGELOG.md
N/A
Back in November we released a few fixes in 3.4. While the code changes are not
necessary for 4.0 we should still have a complete CHANGELOG marking those
releases.
This is just a CHANGELOG entry
> [identity] Update changelog for 3.4.x

- common/tools/dev-tool/src/config/rollup.base.config.ts
This PR enhances our `load-source-map` rollup plugin to support inline source maps if they are of "data:application/json;charset=utf-8;base64" type.  This should resolve build warnings from bundling.
> [dev-tool] handle some inline source maps

- sdk/attestation/attestation/swagger/README.md
- sdk/digitaltwins/digital-twins-core/swagger/README.md
- sdk/purview/purview-scanning-rest/swagger/README.md
- sdk/quantum/quantum-jobs/swagger/readme.md
#28308 
GA'd code should be generated from swagger/typespec from the main branch of the azure-rest-api-specs repo, not from other branches or random commits/local files, for maintainability and reproducible builds
> Update swagger input links to azure-rest-api-specs main branch

- sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts
- sdk/monitor/monitor-opentelemetry/README.md
- sdk/monitor/monitor-opentelemetry/review/monitor-opentelemetry.api.md
- sdk/monitor/monitor-opentelemetry/src/browserSdkLoader/browserSdkLoader.ts
- sdk/monitor/monitor-opentelemetry/src/index.ts
- sdk/monitor/monitor-opentelemetry/src/shared/config.ts
- sdk/monitor/monitor-opentelemetry/src/shared/types.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/browserSdkLoader/browserSdkLoader.test.ts
Need to clean up unneeded API components in the Browser SDK Loader
> Cleanup Browser SDK Loader

- common/tools/dev-tool/src/commands/run/testVitest.ts
- sdk/core/core-rest-pipeline/package.json
- sdk/core/core-util/package.json
and update the `unit-test:browser` NPM scripts of core-util and core-rest-pipeline
> [dev-tool] ensure browsers are installed for playwright browser tests

- sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry-exporter/package.json
- sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
- sdk/monitor/monitor-opentelemetry-exporter/swagger/README.md
- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/package.json
- sdk/monitor/monitor-opentelemetry/src/types.ts
- sdk/monitor/monitor-query/package.json
> Distro Release 1.2.0 & Exporter Release 1.0.0-beta.19

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/sources/customizations/api/client/openAIClient/deserializers.ts
- sdk/openai/openai/src/api/client/openAIClient/deserializers.ts
- sdk/openai/openai/test/internal/deserializer.spec.ts
#28311
Check if choices are undefined and add a test case
> [OpenAI] Check undefined choices in chat completions method response

- .github/CODEOWNERS
Adding myself as CODEOWNER for the following packages:
> Add maorleger to codeowners

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/src/rest/openAIClient.ts
Run the prepare release script
> [OpenAI] Prepare for Release

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/package.json
- sdk/search/search-documents/package.json
> [OpenAI] Post release Update Version

- sdk/identity/identity/test/internal/node/interactiveBrowserCredential.spec.ts
28373
A more conservative version https://github.com/Azure/azure-sdk-for-js/pull/28346. I will document my learnings in this issue
but the original PR also contains useful context to how we ended up here
> [identity] Disable broken IBC test

- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/exporter.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts
> [Azure Monitor OpenTelemetry] Update Quickpulse transmission time

- eng/emitter-package-lock.json
- eng/emitter-package.json
Update the emitter file with the latest version of the emitter
> [tools] Bump TS Emitter Version to 21

- sdk/monitor/monitor-opentelemetry-exporter/src/generated/models/index.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/breezeUtils.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.test.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts
> [Azure Monitor OpenTelemetry Exporter] Change time precision to nanoseconds

- sdk/openai/openai-assistants/CHANGELOG.md
- sdk/openai/openai-assistants/review/openai-assistants.api.md
- sdk/openai/openai-assistants/sources/generated/src/models/models.ts
- sdk/openai/openai-assistants/sources/generated/src/rest/outputModels.ts
- sdk/openai/openai-assistants/src/models/models.ts
- sdk/openai/openai-assistants/src/rest/outputModels.ts
mirrors [TypeSpec fix](https://github.com/Azure/azure-rest-api-specs/pull/27632)
https://github.com/Azure/azure-rest-api-specs/pull/27632
> [OpenAI] [Assistants] Fix for ThreadRun->RequiredAction->RequiredFunctionToolCall

- sdk/sql/arm-sql/assets.json
- sdk/sql/arm-sql/samples-dev/databaseSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples-dev/managedDatabaseSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples-dev/managedServerSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples-dev/serverSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples/v10-beta/javascript/databaseSecurityAlertPoliciesCreateOrUpdateSample.js
- sdk/sql/arm-sql/samples/v10-beta/javascript/managedDatabaseSecurityAlertPoliciesCreateOrUpdateSample.js
- sdk/sql/arm-sql/samples/v10-beta/javascript/managedServerSecurityAlertPoliciesCreateOrUpdateSample.js
- sdk/sql/arm-sql/samples/v10-beta/javascript/serverSecurityAlertPoliciesCreateOrUpdateSample.js
- sdk/sql/arm-sql/samples/v10-beta/typescript/src/databaseSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples/v10-beta/typescript/src/managedDatabaseSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples/v10-beta/typescript/src/managedServerSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/samples/v10-beta/typescript/src/serverSecurityAlertPoliciesCreateOrUpdateSample.ts
- sdk/sql/arm-sql/test/sql_examples.ts
fix https://github.com/Azure/azure-sdk-for-js/issues/28446
> [mgmt] issue fix

- sdk/maps/maps-render-rest/samples-dev/getMapTileInBrowser.ts
- sdk/maps/maps-render-rest/samples-dev/getMapTileInNode.ts
- sdk/maps/maps-render-rest/samples/v1-beta/javascript/README.md
- sdk/maps/maps-render-rest/samples/v1-beta/javascript/getMapTileInBrowser.js
- sdk/maps/maps-render-rest/samples/v1-beta/javascript/getMapTileInNode.js
- sdk/maps/maps-render-rest/samples/v1-beta/typescript/README.md
- sdk/maps/maps-render-rest/samples/v1-beta/typescript/src/getMapTileInBrowser.ts
- sdk/maps/maps-render-rest/samples/v1-beta/typescript/src/getMapTileInNode.ts
- sdk/maps/maps-render-rest/samples/v1-beta/typescript/tsconfig.json
- `@azure-rest/maps-render`
#28444 
#26649 
The reader may accidentally run the sample `getMapTileInBrowser` in the Node.js environement. Add comment to emphasize the correct environment for the samples.
> Update sample code for getting map tiles in browser and Node.js

- .github/CODEOWNERS
> [OpenAI] add glharper as openai codeowner

- eng/emitter-package-lock.json
- eng/emitter-package.json
Bump emitter to the latest version
> [Tool] Update Emitter Version

- sdk/servicebus/service-bus/CHANGELOG.md
> [ServiceBus] prepare for February 2024

- sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts
> [Azure Monitor OpenTelemetry Exporter] Fix issue with wrong format for duration field

- sdk/containerservice/arm-containerservice/test/containerservice_examples.ts
- sdk/networkanalytics/arm-networkanalytics/test/networkanalytics_operations_test.spec.ts
> [mgmt][test] add testPollingOptions for arm-networkanalytics delete test

- sdk/search/search-documents/README.md
Fixes #27563
@joheredi, @alzimmermsft, @dgetu for notification.
> Fix Search Documents Sample Issue 

- sdk/communication/communication-call-automation/README.md
Fixes #27923，#28123
@joheredi, @mayurid for notification.
> Fix Communication Call Automation Readme Issue

- sdk/openai/openai-assistants/CHANGELOG.md
@Azure/openai-assistants
Update changelog for next release
> [OpenAI] [Assistants] Update CHANGELOG.md

- sdk/openai/openai-assistants/CHANGELOG.md
- sdk/openai/openai-assistants/package.json
https://github.com/Azure/azure-sdk-for-js/issues/28529
types/src wasn't added to package build files list
- [x ] Added a changelog (if necessary)
> [OpenAI] [Assistants] add types/src

- sdk/openai/openai/assets.json
- sdk/openai/openai/test/public/embeddings.spec.ts
- sdk/openai/openai/test/public/utils/asserts.ts
So the promise is awaited inside the test. Fixes https://github.com/Azure/azure-sdk-for-js/issues/28542
> [OpenAI] Update embedding test

- sdk/monitor/monitor-opentelemetry-exporter/src/utils/breezeUtils.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
> [Azure Monitor OpenTelemetry Exporter] Fix issue with duration format

- common/tools/dev-tool/src/commands/customization/apply-v2.ts
- common/tools/dev-tool/src/commands/customization/index.ts
- common/tools/dev-tool/src/util/run.ts
- `@azure-tools/dev-tool`
New concept for customization tool I want to check in so we can test whether it works better for our needs than the existing tool.
As a high-level overview, this tool leverages Git and its diff/merge capabilities to take handwritten modifications to the old generated code and apply it to new generated code after regenerating. The user will resolve any merge conflicts if present after the fact.
Check out [this Loop](https://microsoft.sharepoint.com/:fl:/s/d2e0cc81-28c8-4a82-99d9-ca0dd295e2db/EXZ9gfh_8htMlfbQd6eg4QsBUYsqnFHVBlmwd1Z7xDeGJg?e=r3gHj1&nav=cz0lMkZzaXRlcyUyRmQyZTBjYzgxLTI4YzgtNGE4Mi05OWQ5LWNhMGRkMjk1ZTJkYiZkPWIlMjF5UHE5d2tMRE5rT3ZGYXN1a0JTWTBPYkRyajNGbklCTmptdGJRZmxWS1VRbFB3LTFjd0x1U29EWWFSdk5MZ0lIJmY9MDEzUzdQV1EzV1BXQTdRNzdTRE5HSkw1V1FPNlQyQllJTCZjPSUyRi …
> [dev-tool] Customization v2 prototype

- sdk/openai/openai-rest/README.md
> [doc][openai-rest] fix broken link

- sdk/openai/openai-assistants/README.md
Fix https://github.com/Azure/azure-sdk-for-js/issues/28593
#28593 
> [OpenAI] [Assistants] correct README code snippet for createRun usage

- sdk/communication/communication-common/CHANGELOG.md
Microsoft Teams App Identifier GA Patch release of the communication-common SDK - 2.3.1
> [JS] Communication Common | Microsoft Teams App Identifier feature Patch release updates

- sdk/servicebus/service-bus/src/core/batchingReceiver.ts
We added a timeout of 200 milliseconds on credit draining before returning from `receiveMessages()`.  There's customer report that indicates this timeout is aggressive in environment with slow network and caused link churn because we close link when draining times out to avoid going into a bad state.
This PR changes the wait time to the max of 200 ms and the remaining portion of the `maxWaitTimeInMs` option that is passed to `receiveMessages()`, allowing customer to customize the time out indirectly.
#28023 
- exposing an option to set drain timeout. This is not desired since waiting for draining is an internal implementation detail
- increase 200 ms to some other higher value.  It's not possible to determin a best value for this as environments are different.
- …
> [ServiceBus] wait up to max wait time for draining credit when receiving messages

- sdk/communication/communication-chat/review/communication-chat.api.md
- sdk/communication/communication-chat/src/chatClient.ts
- sdk/communication/communication-chat/src/generated/src/models/index.ts
- sdk/communication/communication-chat/src/generated/src/models/mappers.ts
- sdk/communication/communication-chat/src/models/mappers.ts
- sdk/communication/communication-chat/src/models/models.ts
- sdk/communication/communication-chat/src/models/options.ts
- sdk/communication/communication-chat/swagger/README.md
- sdk/communication/communication-chat/test/internal/chatClient.mocked.spec.ts
- sdk/communication/communication-chat/test/internal/chatThreadClient.mocked.spec.ts
- sdk/communication/communication-chat/test/internal/utils/mockClient.ts
- sdk/communication/communication-chat/test/public/chatClient.spec.ts
- sdk/communication/communication-chat/test/public/chatThreadClient.spec.ts
- sdk/template/template-dpg/tsconfig.json
> Data Retention API Change

- sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md
- sdk/notificationhubs/notification-hubs/src/models/notificationBodyBuilder.ts
Fixes the enums for `notification_priority` and `visibility` for the Android messages.
> [notification-hubs] Fix Firebase V1 Message Format enums

- sdk/identity/identity/assets.json
- sdk/identity/identity/test/node/msalNodeTestSetup.ts
- sdk/identity/identity/test/public/node/multiTenantAuthentication.spec.ts
Contributes to #26434
Automation of common test scenarios, this commit adds a single multi-tenant test
using the static test resources.
https://github.com/Azure/azure-sdk-for-net/pull/38992
https://github.com/Azure/azure-sdk-for-python/pull/34257
> [identity] Add Multi-tenant test

- sdk/communication/communication-ten-dlc/CHANGELOG.md
- sdk/communication/communication-ten-dlc/package.json
- sdk/communication/communication-ten-dlc/src/generated/src/tenDLCClient.ts
- sdk/communication/communication-ten-dlc/src/generated/src/tracing.ts
> Mark package as In Release

- sdk/openai/openai/assets.json
- sdk/openai/openai/src/api/client/openAIClient/index.ts
- sdk/openai/openai/test/public/completions.spec.ts
- sdk/openai/openai/test/public/utils/asserts.ts
@azure/openai
#28673
Fix function schemas properties being transformed into snake case. Update assert functions for prompt filter results.
> [OpenAI] Fix Function Schemas Transformed into Snake Case

- sdk/communication/communication-messages-rest/tsp-location.yaml
> Updated the commit in tsp-location.yaml

- sdk/notificationhubs/notification-hubs/CHANGELOG.md
- sdk/notificationhubs/notification-hubs/src/utils/constants.ts
Preparing release for @azure/notification-hubs v1.1.0
Features Added:
- Added Support for [Firebase Cloud Messaging (FCM)](https://firebase.google.com/docs/cloud-messaging) V1 API with the following:
- `FcmV1RegistrationDescription` and `FcmV1TemplateRegistrationDescription` for registrations with associated factory methods.
- `FcmV1Installation` for installation operations and associated factory methods.
- `FcmV1Notification` for notification send support and associated factory methods.
> Preparing release for @azure/notification-hubs v1.1.0

- sdk/openai/openai-assistants/CHANGELOG.md
- sdk/openai/openai-assistants/sources/customizations/api/operations.ts
- sdk/openai/openai-assistants/sources/customizations/api/util.ts
- sdk/openai/openai-assistants/src/api/operations.ts
- sdk/openai/openai-assistants/src/api/util.ts
Fixes date issue in src
- [ x] Added a changelog (if necessary)
> [OpenAI] [Assistants] correct date issue in src

- sdk/appconfiguration/app-configuration/CHANGELOG.md
- sdk/appconfiguration/app-configuration/package.json
- sdk/appconfiguration/app-configuration/src/internal/constants.ts
- sdk/appconfiguration/app-configuration/swagger/swagger.md
Run prepare release script with the correct version
> [App Config] Run Prepare Release Script

- eng/ignore-links.txt
- sdk/communication/ci.yml
- sdk/communication/communication-messages-rest/package.json
> Fixed release pipeline to publish doc for communication messages

- swagger_to_sdk_config.json
> update breakingchange label config

- sdk/communication/communication-messages-rest/CHANGELOG.md
- sdk/communication/communication-messages-rest/package.json
> communication-messages package version update

- sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry-exporter/package.json
- sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
- sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
- sdk/monitor/monitor-opentelemetry-exporter/swagger/README.md
- sdk/monitor/monitor-opentelemetry/package.json
- sdk/monitor/monitor-query/package.json
> [Azure Monitor OpenTelemetry Exporter] 1.0.0-beta.21 release

- common/config/rush/pnpm-lock.yaml
- sdk/cosmosdb/cosmos/package.json
> revert identity package

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/abort-controller/package.json
- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/package.json
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/package.json
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-http-compat/CHANGELOG.md
- sdk/core/core-http-compat/package.json
- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-lro/package.json
- sdk/core/core-paging/CHANGELOG.md
- sdk/core/core-paging/package.json
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/package.json
- sdk/core/core-rest-pipeline/src/constants.ts
- sdk/core/core-sse/CHANGELOG.md
- sdk/core/core-sse/package.json
- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-tracing/package.json
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-util/package.json
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/core-xml/package.json
- sdk/core/logger/CHANGELOG.md
- sdk/core/logger/package.json
- `@azure/abort-controller`
- `@azure/core-auth`
- `@azure/core-client`
- `@azure/core-http-compat`
- `@azure/core-lro`
- `@azure/core-paging`
- `@azure/core-sse`
- `@azure/core-tracing`
- `@azure/core-util`
- `@azure/logger`
Preparing for upcoming Core release. We are doing a minor version bump for all packages which we have migrated to ESM.
> [core] Prepare release of all Core packages that have been migrated to ESM

- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/package.json
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
- sdk/eventgrid/eventgrid/src/generated/models/index.ts
- sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
- sdk/eventgrid/eventgrid/src/index.ts
- sdk/eventgrid/eventgrid/src/predicates.ts
- sdk/eventgrid/eventgrid/src/tracing.ts
- sdk/eventgrid/eventgrid/swagger/README.md
NA
The EventGrid Service Team has added 2 new events. The SDK must be regenerated to include the code changes related to these 2 new events. The SDK minor version has been updated.
- `Microsoft.ApiCenter.ApiDefinitionAdded`
- `Microsoft.ApiCenter.ApiDefinitionUpdated`
- https://github.com/Azure/azure-sdk-for-js/pull/27384 (This is the PR that adds similar events to the SDK in the 4.15.0 release)
- https://github.com/Azure/azure-sdk-for-js/pull/26939 (This is the PR that adds similar events to the SDK …
> [@azure/eventgrid] Adding new events for EG Version 5.3.0

- common/tools/dev-tool/test/customization/classes.spec.ts
- common/tools/dev-tool/test/customization/interfaces.spec.ts
`@azure/dev-tool`
Fixing lint errors in `dev-tool` to unblock https://github.com/Azure/azure-sdk-for-js/pull/28916 and [js - eslint-plugin - ci](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3595289&view=logs&j=58292cae-3c74-5729-4cfd-9ceee65fe129&t=5e44d412-b571-5a43-3bb4-5c5145c0a5aa)
> [dev-tool] Fix lint errors

- sdk/monitor/monitor-opentelemetry/src/generated/models/index.ts
- sdk/monitor/monitor-opentelemetry/src/generated/models/mappers.ts
- sdk/monitor/monitor-opentelemetry/src/generated/models/parameters.ts
- sdk/monitor/monitor-opentelemetry/src/generated/quickpulseClient.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/exporter.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/sender.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/types.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts
- sdk/monitor/monitor-opentelemetry/swagger/README.md
> [Azure Monitor OpenTelemetry] Update swagger definition file for Quickpulse

- sdk/datafactory/arm-datafactory/CHANGELOG.md
- sdk/datafactory/arm-datafactory/_meta.json
- sdk/datafactory/arm-datafactory/assets.json
- sdk/datafactory/arm-datafactory/package.json
- sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
- sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
- sdk/datafactory/arm-datafactory/src/models/index.ts
- sdk/datafactory/arm-datafactory/src/models/mappers.ts
https://github.com/Azure/sdk-release-request/issues/4989
> [mgmt] datafactory release

- sdk/storage/test-resources.json
[Autorest/typescript](https://github.com/Azure/autorest.typescript) repository and link it here)_
> Create test account with allowing public access (#27723)

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-http-compat/CHANGELOG.md
- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-paging/CHANGELOG.md
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-sse/CHANGELOG.md
- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/logger/CHANGELOG.md
- All Core packages that have been migrated to ESM
> [core] Update changelog dates for Core patch release

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
- sdk/communication/communication-call-automation/src/callMedia.ts
- sdk/communication/communication-call-automation/src/models/events.ts
- sdk/communication/communication-call-automation/src/models/models.ts
- sdk/communication/communication-call-automation/src/models/options.ts
- sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
> Beta 3 hold unhold sdk changes.

- sdk/monitor/monitor-opentelemetry-exporter/test/internal/httpSender.test.ts
- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/README.md
- sdk/monitor/monitor-opentelemetry/package.json
- sdk/monitor/monitor-opentelemetry/review/monitor-opentelemetry.api.md
- sdk/monitor/monitor-opentelemetry/src/logs/batchLogRecordProcessor.ts
- sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
- sdk/monitor/monitor-opentelemetry/src/shared/config.ts
- sdk/monitor/monitor-opentelemetry/src/shared/jsonConfig.ts
- sdk/monitor/monitor-opentelemetry/src/types.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/batchLogRecordProcessor.test.ts
> [Azure Monitor OpenTelemetry] Add support for log sampling based on trace

- sdk/monitor/monitor-query/README.md
Make README more consistent with other languages, incorporate Acrolinx feedback, and update docs.microsoft.com links
> Edit pass on Monitor Query README

- .github/CODEOWNERS
> [JS] Update CODEOWNERS for AppConfig service

- sdk/translation/ai-translation-text-rest/tests.yml
`@azure-rest/ai-translation-text`
With the [recent refactoring of test pipelines](https://github.com/Azure/azure-sdk-for-js/commit/ecdb45e61db7c965ee9aae8a7aa0d12f7b4f5012), some malformed configuration in this file started failing our live test pipelines.
This PR cleans up the incorrect keys and should unblock the tests.
> [translation] Fix bad value in tests.yml

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationClient.ts
- sdk/communication/communication-call-automation/src/callConnection.ts
- sdk/communication/communication-call-automation/src/generated/src/models/index.ts
- sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts
- sdk/communication/communication-call-automation/src/models/options.ts
- sdk/communication/communication-call-automation/swagger/README.md
[Task 3643688](https://skype.visualstudio.com/SPOOL/_workitems/edit/3643688): [SDK][JavaScript]Move 'SourceCallerIdNumber' from Answer to Transfer API
Added the source caller id to the transfer api
> Added SourceCallerIdNumber from answer to transfer api

- sdk/communication/communication-identity/CHANGELOG.md
- sdk/communication/communication-identity/package.json
Release of the communication-identity SDK - 1.3.1
>  [JS] Communication Identity | Release updates with latest Common version

- sdk/communication/communication-phone-numbers/CHANGELOG.md
- sdk/communication/communication-phone-numbers/package.json
azure-communication-phonenumbers
beta package publishing failed, this is a targeted PR to address those issues
no - no code written, just configuration changes
https://github.com/Azure/azure-sdk-for-js/pull/28662
- [n/a] Does this PR needs any fixes in the SDK Generator?** _(If so, create an Issue in the [Autorest/typescript](https://github.com/Azure/autorest.typescript) repository and link it here)_
> Fix beta package publishing

- sdk/identity/identity-broker/CHANGELOG.md
- sdk/identity/identity-broker/samples/v1/javascript/README.md
- sdk/identity/identity-broker/samples/v1/typescript/README.md
- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/TROUBLESHOOTING.md
- sdk/identity/identity/interactive-browser-credential.md
- sdk/identity/identity/migration-v1-v2.md
- sdk/identity/identity/samples/AzureIdentityExamples.md
- sdk/identity/identity/samples/v2/javascript/README.md
- sdk/identity/identity/samples/v2/typescript/README.md
- sdk/identity/identity/samples/v3-beta/javascript/README.md
- sdk/identity/identity/samples/v3-beta/typescript/README.md
- sdk/identity/identity/samples/v3/javascript/README.md
- sdk/identity/identity/samples/v3/typescript/README.md
- sdk/identity/identity/samples/v4/javascript/README.md
- sdk/identity/identity/samples/v4/typescript/README.md
- sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
- sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
- sdk/identity/identity/src/credentials/clientSecretCredential.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
- sdk/identity/identity/src/credentials/onBehalfOfCredential.browser.ts
- sdk/identity/identity/src/credentials/onBehalfOfCredential.ts
- sdk/identity/identity/test/manual/authorization-code-credential/authorizationCodeSample.ts
- sdk/identity/perf-tests/identity/README.md
Replace Azure AD docs/learn.microsoft.com links with their Entra counterparts
> Update Azure AD Learn links in Identity

- common/config/rush/pnpm-lock.yaml
- common/tools/eslint-plugin-azure-sdk-helper/package.json
- common/tools/eslint-plugin-azure-sdk/package.json
- common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts
- @azure/eslint-plugin-azure-sdk
- #28861
Updates to latest plugin version.
> [eslint-plugin-azure-sdk] Update Markdown plugin

- sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
- sdk/identity/identity/src/regionalAuthority.ts
- sdk/identity/identity/test/internal/node/regionalAuthority.spec.ts
Contributes to #29066
A very small refactor that should help us easily move the regional authority
logic to MSALClient next month.
> [identity] Move regional authority logic to function

- sdk/monitor/monitor-opentelemetry-exporter/README.md
> [Azure Monitor OpenTelemetry Exporter] Update README Code Snippet

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/samples/v1-beta/javascript/bringYourOwnData.js
- sdk/openai/openai/samples/v1-beta/typescript/src/bringYourOwnData.ts
- sdk/openai/openai/src/rest/openAIClient.ts
@azure/openai
Run prepare release script and publish samples
> [OpenAI] Prepare release script & publish samples

- sdk/monitor/monitor-opentelemetry/src/logs/batchLogRecordProcessor.ts
Update logic to match .NET implementation
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/LogFilteringProcessor.cs
> [Azure Monitor OpenTelemetry] Log sampling, check for spanId

- sdk/communication/communication-chat/assets.json
- sdk/communication/communication-chat/review/communication-chat.api.md
- sdk/communication/communication-chat/src/chatThreadClient.ts
- sdk/communication/communication-chat/src/generated/src/models/index.ts
- sdk/communication/communication-chat/src/generated/src/models/mappers.ts
- sdk/communication/communication-chat/src/models/mappers.ts
- sdk/communication/communication-chat/src/models/models.ts
- sdk/communication/communication-chat/swagger/README.md
- sdk/communication/communication-chat/test/internal/chatClient.mocked.spec.ts
- sdk/communication/communication-chat/test/internal/chatThreadClient.mocked.spec.ts
- sdk/communication/communication-chat/test/internal/utils/mockClient.ts
- sdk/communication/communication-chat/test/public/chatThreadClient.spec.ts
- sdk/communication/communication-chat/tsconfig.json
> Add none retention policy support

- sdk/communication/communication-rooms/CHANGELOG.md
- sdk/communication/communication-rooms/README.md
- sdk/communication/communication-rooms/assets.json
- sdk/communication/communication-rooms/package.json
- sdk/communication/communication-rooms/samples/v1/typescript/src/participantOperations.ts
- sdk/communication/communication-rooms/samples/v1/typescript/src/roomOperations.ts
- sdk/communication/communication-rooms/src/generated/src/models/mappers.ts
- sdk/communication/communication-rooms/src/generated/src/models/parameters.ts
- sdk/communication/communication-rooms/src/generated/src/pagingHelper.ts
- sdk/communication/communication-rooms/src/generated/src/roomsRestClient.ts
- sdk/communication/communication-rooms/src/generated/src/tracing.ts
- sdk/communication/communication-rooms/swagger/README.md
communication-rooms ACS Rooms SDK 
Updating version following new Rooms version (2024-04-15)
> Update Rooms SDK for PSTN GA

- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/sender.ts
@azure/montior-opentelemetry
#29143
Updated the sender application insights resource endpoint.
> [Monitor OpenTelemetry] Update Application Insights Resource Endpoint

- sdk/communication/communication-chat/assets.json
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-chat/src/generated/src/chatApiClient.ts
- sdk/communication/communication-chat/src/generated/src/models/index.ts
- sdk/communication/communication-chat/src/generated/src/models/mappers.ts
- sdk/communication/communication-chat/src/generated/src/models/parameters.ts
- sdk/communication/communication-chat/src/generated/src/operations/chat.ts
- sdk/communication/communication-chat/src/generated/src/operations/chatThread.ts
- sdk/communication/communication-chat/src/generated/src/operationsInterfaces/chat.ts
- sdk/communication/communication-chat/src/generated/src/operationsInterfaces/chatThread.ts
- sdk/communication/communication-chat/src/generated/src/tracing.ts
- sdk/communication/communication-chat/swagger/README.md
communication-chat
N/A
Connect communication-chat to GW version 2024-03-01-preview
> [Chat] Beta release 1.5.0-beta.2 to use GW 2024-03-01-preview version

- sdk/communication/communication-chat/CHANGELOG.md
Communication chat
Changelog update prior to release
> Update changelog for 1.5.0-beta.2 release

- sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
-Added error messaging relaxation for https://github.com/Azure/azure-sdk-for-js/issues/28290
> [Identity] Error messaging updated for IMDS 403

- sdk/openai/openai/review/openai-api.api.md
- sdk/openai/openai/src/OpenAIClient.ts
- sdk/openai/openai/src/api/operations.ts
@azure/openai
Update generated method signature to match public API
> [OpenAI] Update generated method signature

- sdk/openai/openai-assistants/samples/v1-beta/typescript/src/codeAssistant.ts
- sdk/openai/openai-assistants/samples/v1-beta/typescript/src/functionAssistant.ts
- sdk/openai/openai-assistants/samples/v1-beta/typescript/src/retrievalAssistant.ts
- sdk/openai/openai-assistants/sources/customizations/models/models.ts
- sdk/openai/openai-assistants/src/models/models.ts
- sdk/openai/openai-assistants/test/public/openaiassistants.spec.ts
#29147
outdated model in examples/tests
> [OpenAI] [Assistants] update models used in samples/tests

- eng/pipelines/templates/stages/platform-matrix.json
- sdk/test-utils/recorder/CHANGELOG.md
`@azure-tools/test-recorder` and `js - template - tests` pipeline
Fixes #29246
> [test-recorder] [Hotfix] Bump core-client version

- sdk/monitor/monitor-query/README.md
React to feedback in https://github.com/Azure/azure-sdk-blog/pull/479#discussion_r1556370730. Also apply small changes as part of a cross-language README consistency review.
> Document role requirement for multi-resource metrics queries

- sdk/identity/identity/src/msal/nodeFlows/brokerOptions.ts
update api ref docs to include default
> [identity] update api ref docs to include default

- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/package.json
Correcting version bump for Core REST client to be a minor bump due to new feature
> [core] Minor bump for core-client-rest

- sdk/monitor/test-resources.json
Apply fix similar to the one in PR #29262
> [Test][Monitor] add environment variables needed by AAD tests

- sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts
- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/src/index.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
- sdk/monitor/monitor-opentelemetry/src/types.ts
- sdk/monitor/monitor-opentelemetry/src/utils/statsbeat.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
Update statsbeat feature/instrumentation settings to allow collection of dynamically updated features/instrumentations.
Add collection of live metrics and live metrics activation.
> [Monitor OpenTelemetry][Monitor OpenTelemetry Exporter] Add Live Metrics and Live Metrics Activation to Statsbeat

- sdk/monitor/monitor-opentelemetry/README.md
> [Azure Monitor OpenTelemetry] Fix README Formatting

- sdk/communication/communication-job-router-rest/CHANGELOG.md
> [ACS][JobRouter] Pre release for js

- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/swagger/README.md
> [Chat] Updated Release Date and Swagger Hash

- sdk/communication/communication-identity/package.json
Build test package is failing due to dependencies conflict [Pipeline failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3705705&view=logs&j=8599d413-ac92-517d-1cdb-470be2ca69b4&t=c9aff480-5e38-59bc-26d9-d89fa2820c4b&l=27)
Updated azure core dependency in communication identity package to resolve conflicts
> [JS][ACS Identity] Fixing failure in pipeline

- sdk/test-utils/recorder/CHANGELOG.md
- sdk/test-utils/recorder/src/recorder.ts
- sdk/test-utils/recorder/src/utils/fallbackSanitizers.ts
- sdk/test-utils/recorder/src/utils/utils.ts
`@azure-tools/test-recorder@3.2.0`
https://github.com/Azure/azure-sdk-for-js/pull/29331
> [Recorder] v3 <- cherry-pick central sanitizers from v4

- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
> [Storage] Bump version and prepare for release.

- eng/emitter-package-lock.json
- eng/emitter-package.json
Upgrade the emitter version in mid april
> Upgrade the emitter version in mid april

- common/scripts/install-run-rush-pnpm.js
- common/scripts/install-run-rush.js
- common/scripts/install-run-rushx.js
- common/scripts/install-run.js
- rush.json
This should resolve the install issue on Windows.
> [EngSys] upgrade rush version to 5.120.6

- sdk/identity/identity/CHANGELOG.md
This PR just adds a changelog entry for the MSALClient migration, so that
customers are aware in case any behavior has changed.
> [identity] Add changelog entry for MSALClient migration

- sdk/template/template-dpg/package.json
Suppressing template-dpg failure to unblock https://github.com/Azure/azure-sdk-for-js/issues/29436
> [template-dpg] Suppress build failure

- sdk/core/core-client-rest/CHANGELOG.md
Update CHANGELOG with release date to unblock release.
> [core] CHANGELOG date for @azure-rest/core-client release

- sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/README.md
Fixes #27274
@joheredi, @mpodwysocki for notification.
> Fix OpenTelemetry Instrumentation Readme Issue

- sdk/identity/identity/README.md
Hyperlink for AZD wasn't finished.
> Docs/Readme.md - Fix hyperlink

- sdk/remoterendering/mixed-reality-remote-rendering/assets.json
These recording were missing from a recent test update to account for better service error messages.
> Updated Recordings for Remote Rendering

- sdk/core/core-sse/samples/v1/typescript/package.json
- sdk/core/core-sse/samples/v2/javascript/README.md
- sdk/core/core-sse/samples/v2/javascript/createSseStream.js
- sdk/core/core-sse/samples/v2/javascript/package.json
- sdk/core/core-sse/samples/v2/typescript/README.md
- sdk/core/core-sse/samples/v2/typescript/package.json
- sdk/core/core-sse/samples/v2/typescript/src/createSseStream.ts
- sdk/core/core-sse/samples/v2/typescript/tsconfig.json
Fixes https://github.com/Azure/azure-sdk-for-js/issues/29520
Generate samples for v2 and update package.json in v1 folder to install v1.
> [core-sse] Update samples

- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/src/receivers/receiver.ts
- sdk/servicebus/service-bus/src/util/constants.ts
as this is the contract between SDK and service.
#29503
> [ServiceBus] Revert to check deleted count against MaxDeleteMessageCount

- eng/pipelines/templates/stages/platform-matrix.json
> [EngSys] Move from NodeJS v21 to v22

- sdk/identity/identity/src/credentials/azurePipelinesServiceConnectionCredential.ts
Explain how to find the service connection ID
> Update service connection ID docs

- sdk/test-utils/test-utils/CHANGELOG.md
- sdk/test-utils/test-utils/package.json
- @azure-tools/test-utils
Removing the `"private": true` from the `package.json` to allow for publishing.
> [test-utils] Update to release package

- common/config/rush/pnpm-lock.yaml
- sdk/template/template/package.json
- sdk/test-utils/recorder/package.json
- @azure/template
- #29538
Adding `loupe` directly to `template` and removing from `test-recorder`.
> [template] Fix loupe issue

- sdk/communication/communication-sms/CHANGELOG.md
Added release date of version 1.2.0-beta.1  to thye changelog.
n/a
n/a
n/a
n/a
> [Communication] - sms - Added release date of version 1.2.0-beta.1 

- sdk/communication/communication-call-automation/package.json
- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/models/models.ts
- sdk/communication/communication-call-automation/src/utli/converters.ts
Adding Teams App Identifier to JS library
> [ACS][CallAutomation] Update common version and TeamsAppIdentifier

- sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/NonStreamingOrderByEndpointComponent.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/index.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/orderByComparator.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/pipelinedQueryExecutionContext.ts
- sdk/cosmosdb/cosmos/test/public/functional/vectorEmbeddingPolicy.spec.ts
> Feature/cosmosdb/ru cap + vector search

- sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testDigitalTwins.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testEventRoutes.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts
- sdk/digitaltwins/digital-twins-core/test/public/testRelationships.spec.ts
- sdk/eventhub/event-hubs/test/connectionStringUtils.spec.ts
- sdk/eventhub/event-hubs/test/internal/amqp.spec.ts
- sdk/eventhub/event-hubs/test/internal/bufferedProducerUnitTests.spec.ts
- sdk/eventhub/event-hubs/test/public/amqpAnnotatedMessage.spec.ts
- sdk/eventhub/event-hubs/test/public/eventHubBufferedProducerClient.spec.ts
This PR applies the same fix as in PR #29582
> [Test] fix build errors due to changes in latest @types/chai

- sdk/search/search-documents/README.md
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderAutoFlushSize.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderAutoFlushTimer.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderManualFlush.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/dataSourceConnectionOperations.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/indexOperations.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/indexerOperations.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/searchClientOperations.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/skillSetOperations.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/stickySession.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/vectorSearch.ts
- sdk/search/search-documents/test/public/node/searchClient.spec.ts
Small fixups for preview docs
Designed to be reviewed on a per-commit basis.
Fixes #29330 
Fixes #29381 
Depends on #29600
> [Search] Fix documentation for preview client

- eng/pipelines/templates/steps/test.yml
The other test proxy steps have this condition.  This PR adds the same to
publish step as well.
> [EngSys] add condition for publishing test proxy log

- eng/pipelines/templates/steps/npm-release-task.yml
> esrp release fix

- .github/CODEOWNERS
Which should help increase my awareness of upcoming API changes
> Add maorleger as codeowner to API md files

- sdk/core/core-amqp/.tshy/browser.json
- sdk/core/core-amqp/.tshy/commonjs.json
- sdk/core/core-amqp/.tshy/react-native.json
- sdk/core/core-amqp/package.json
> [core-amqp] Add additional targets

- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/src/logs/handler.ts
- sdk/monitor/monitor-opentelemetry/src/utils/logUtils.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/logs/logHandler.test.ts
Add Log Level Configuration for Bunyan & Winston loggers.
Yes
> [Monitor OpenTelemetry] Add Log Level Configuration for Bunyan & Winston

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/credentials/azurePipelinesCredential.ts
- Mark the api for OIDC token to be preview for the preview release
> [identity] Release beta for AzurePipelinesCredential

- sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/NonStreamingOrderByDistinctEndpointComponent.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/NonStreamingOrderByEndpointComponent.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/pipelinedQueryExecutionContext.ts
- sdk/cosmosdb/cosmos/src/queryIterator.ts
- sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
- sdk/cosmosdb/cosmos/test/public/functional/vectorEmbeddingPolicy.spec.ts
> remove comments

- sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/NonStreamingOrderByDistinctEndpointComponent.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/NonStreamingOrderByEndpointComponent.ts
- sdk/cosmosdb/cosmos/src/queryExecutionContext/pipelinedQueryExecutionContext.ts
- sdk/cosmosdb/cosmos/src/queryIterator.ts
- sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
- sdk/cosmosdb/cosmos/test/public/functional/vectorEmbeddingPolicy.spec.ts
- sdk/cosmosdb/cosmos/test/public/integration/nonStreamingOrderBy/nonStreamingDistinctOrderBy.spec.ts
- sdk/cosmosdb/cosmos/test/public/integration/nonStreamingOrderBy/nonStreamingOrderBy.spec.ts
> Preview feat cosmosdb ru cap+vector search

- sdk/search/search-documents/assets.json
- sdk/search/search-documents/test/compressionDisabled.ts
- sdk/search/search-documents/test/public/node/searchClient.spec.ts
- sdk/search/search-documents/test/public/utils/setup.ts
Enables tests that were temporarily disabled when the feature wasn't available to the public.
Designed to be reviewed on a per-commit basis.
Depends on #29600
> [Search] Enable vector compression tests

- sdk/monitor/monitor-opentelemetry/src/index.ts
- sdk/monitor/monitor-opentelemetry/src/utils/statsbeat.ts
> [Monitor OpenTelemetry] Add Winston to Statsbeat Tracking

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-blob/test/blobclient.spec.ts
- sdk/storage/storage-blob/test/blobclientpollers.spec.ts
- sdk/storage/storage-blob/tests.yml
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClientContext.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-datalake/tests.yml
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-file-share/test/fileclient.spec.ts
- sdk/storage/storage-file-share/tests.yml
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/models/parameters.ts
- sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
- sdk/storage/storage-queue/tests.yml
> [Storage]Bump version for STG93 GA release

- sdk/storage/storage-queue/swagger/README.md
> [Storage]Update swagger commit for storage-queue

- sdk/eventhub/event-hubs/src/eventData.ts
- sdk/eventhub/event-hubs/src/eventDataBatch.ts
- sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
- sdk/eventhub/event-hubs/src/eventhubConnectionConfig.ts
- sdk/eventhub/event-hubs/src/models/public.ts
> [Event Hubs] Fix typos in JSDoc

- common/config/rush/pnpm-lock.yaml
- sdk/web-pubsub/web-pubsub-client-protobuf/package.json
- @azure/web-pubsub-client-protobuf
- #29684
> [web pub sub] upgrade protobufjs

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callMedia.ts
- sdk/communication/communication-call-automation/src/models/options.ts
- sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
[User Story 3672944](https://skype.visualstudio.com/SPOOL/_workitems/edit/3672944): [JS][SDK][BETA4] Add Prompts(List) in Recognize feature
1.Recognize PromptList.
2.Unit Test.
> Added Beta4 Recognize Prompt List.

- eng/pipelines/templates/stages/cosmos-sdk-client.yml
- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/src/utils/hashing/encoding/number.ts
- sdk/cosmosdb/cosmos/test/public/functional/client.spec.ts
- sdk/cosmosdb/cosmos/test/public/integration/changeFeedIterator.spec.ts
@azure/cosmos
This PR addresses:
- issue with js-cosmosdb-ci pipeline where tests were getting skipped.
- errors in cosmos db tests.
> Fix cosmos db ci pipeline tests

- common/config/rush/pnpm-lock.yaml
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/samples-dev/advanced/sessionRoundRobin.ts
- sdk/servicebus/service-bus/samples/v7-beta/javascript/package.json
- sdk/servicebus/service-bus/samples/v7-beta/typescript/package.json
- sdk/servicebus/service-bus/samples/v7/javascript/package.json
- sdk/servicebus/service-bus/samples/v7/typescript/package.json
- sdk/servicebus/service-bus/samples/v7/typescript/src/advanced/sessionRoundRobin.ts
- sdk/servicebus/service-bus/src/core/managementClient.ts
- sdk/servicebus/service-bus/test/internal/batchReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/connectionManagement.spec.ts
- sdk/servicebus/service-bus/test/internal/operationOptionsForATOM.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/batchingReceiver.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/linkentity.unittest.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/serviceBusClient.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/utils.spec.ts
- sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts
- sdk/servicebus/service-bus/test/public/sessionsTests.spec.ts
- sdk/servicebus/service-bus/test/stress/app/src/scenarioLongRunning.ts
- fix compilation errors
- fix v7-beta sample tagetting version
> [ServiceBus] upgrade dependency @azure/abort-controller to ^2.1.2

- sdk/face/ai-vision-face-rest/README.md
@azure-rest/ai-vision-face
Update README.md to:
- Change the term `Cognitive Services` to `Azure AI services`.
- Update introduction to Liveness Detection according to new announcements on the Build event.
- [o] Added impacted package name to the issue description
> Update README of @azure-rest/ai-vision-face

- sdk/oracledatabase/arm-oracledatabase/samples-dev/autonomousDatabasesGenerateWalletSample.ts
- sdk/oracledatabase/arm-oracledatabase/samples/v1-beta/javascript/autonomousDatabasesGenerateWalletSample.js
- sdk/oracledatabase/arm-oracledatabase/samples/v1-beta/typescript/src/autonomousDatabasesGenerateWalletSample.ts
fixes: https://github.com/Azure/azure-sdk-for-js/issues/29810
> [mgmt] fix credscan issue

- common/tools/dev-tool/src/util/browserRelayServer.ts
dev-tool
We run into preflight CORS issue while testing App Config migration to DAC in the browser. This PR update the relay server to allow "Content-Type" and other headers to mitigate the issue.
The other solution is to use `cors` middleware package to ensure the preflight request succeeds.
> [Dev Tool] Update allow headers for relay server

- sdk/storage/storage-file-share/assets.json
- sdk/storage/storage-file-share/review/storage-file-share.api.md
- sdk/storage/storage-file-share/src/Pipeline.ts
- sdk/storage/storage-file-share/src/StorageRetryPolicyFactory.ts
- sdk/storage/storage-file-share/src/policies/StorageRetryPolicy.ts
- sdk/storage/storage-file-share/src/policies/StorageRetryPolicyV2.ts
- sdk/storage/storage-file-share/test/retrypolicy.spec.ts
- sdk/storage/storage-file-share/test/utils/InjectorPolicy.ts
- sdk/storage/storage-file-share/test/utils/index.browser.ts
- sdk/storage/storage-file-share/test/utils/index.ts
> [Storage]Remove secondary host from retry policy, file share does not support secondary

- sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
- sdk/monitor/monitor-query/README.md
- sdk/monitor/monitor-query/test/public/shared/testShared.ts
fixes #29522 
@joheredi, @lmolkova and @sarangan12 for notification.
> Fix Azure Monitor Query Readme

- sdk/vision/ai-vision-image-analysis-rest/README.md
fixes #29091 
@joheredi, @dargilco for notification.
> Fix Azure Image Analysis Readme

- eng/pipelines/prepare-pipelines.yml
See https://github.com/Azure/azure-sdk-tools/pull/8359
> Update variable groups for prepare-pipelines

- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts
- sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForPartitionKey.ts
- sdk/cosmosdb/cosmos/src/client/Container/Container.ts
- sdk/cosmosdb/cosmos/src/client/Database/Database.ts
- sdk/cosmosdb/cosmos/src/client/Database/Databases.ts
- sdk/cosmosdb/cosmos/src/client/Item/Item.ts
- sdk/cosmosdb/cosmos/src/client/Item/Items.ts
- sdk/cosmosdb/cosmos/src/common/helper.ts
- sdk/cosmosdb/cosmos/src/encryption/Cache/ProtectedDataEncryptionKeyCache.ts
- sdk/cosmosdb/cosmos/src/encryption/ClientEncryptionPolicy.ts
- sdk/cosmosdb/cosmos/src/encryption/EncryptionManager.ts
- sdk/cosmosdb/cosmos/src/encryption/EncryptionProcessor.ts
- sdk/cosmosdb/cosmos/src/encryption/EncryptionSettingForProperty.ts
- sdk/cosmosdb/cosmos/src/queryIterator.ts
- sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
- sdk/cosmosdb/cosmos/src/request/RequestOptions.ts
- sdk/cosmosdb/cosmos/src/request/request.ts
- sdk/cosmosdb/cosmos/test/public/functional/dotnetcse.spec.ts
> Client-Side-Encryption - add test cases, and fix errors

- sdk/schemaregistry/schema-registry-avro/test/public/avroSerializer.spec.ts
- sdk/schemaregistry/schema-registry/package.json
- sdk/schemaregistry/schema-registry/test/public/utils/recordedClient.ts
@azure/schema-registry
#29866
Update the dependency version for @azure/core-client in @azure/schema-registry. Skip failing test in @azure/scheme-registry-avro
> [Schema Registry] Update Dependencies in package.json

- sdk/quantum/quantum-jobs/test/utils/testAuthentication.ts
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/models/parameters.ts
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> [Storage]Update version for GA release.

- sdk/apimanagement/api-management-custom-widgets-tools/.tshy/browser.json
- sdk/apimanagement/api-management-custom-widgets-tools/.tshy/commonjs.json
- sdk/apimanagement/api-management-custom-widgets-tools/package.json
`@azure/api-management-custom-widgets-tools`
When building from main, these files showed as modified, just getting them checked in to avoid having a dirty tree
> [api-management] Check in missing changes

- common/tools/dev-tool/src/commands/admin/list/esm-migrations.ts
- common/tools/dev-tool/src/commands/admin/list/index.ts
Creates a list tool to track our migration to ESM efforts.
> [dev-tool] Create list migrations tool

- sdk/storage/storage-queue/swagger/README.md
> Update Swagger spec commit for queue

- common/config/rush/pnpm-lock.yaml
- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/review/core-amqp.api.md
- sdk/core/core-amqp/src/util/constants.ts
- sdk/eventhub/event-hubs/CHANGELOG.md
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/review/event-hubs.api.md
- sdk/eventhub/event-hubs/src/eventData.ts
- sdk/eventhub/event-hubs/src/eventHubSender.ts
- sdk/eventhub/event-hubs/src/eventPosition.ts
- sdk/eventhub/event-hubs/src/managementClient.ts
- sdk/eventhub/event-hubs/src/partitionProcessor.ts
- sdk/eventhub/event-hubs/src/partitionReceiver.ts
- sdk/eventhub/event-hubs/src/util/constants.ts
- sdk/eventhub/event-hubs/test/internal/eventPosition.spec.ts
- sdk/eventhub/event-hubs/test/internal/eventProcessor.spec.ts
- sdk/eventhub/event-hubs/test/internal/eventdata.spec.ts
- sdk/eventhub/event-hubs/test/internal/misc.spec.ts
- sdk/eventhub/event-hubs/test/internal/partitionPump.spec.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/CHANGELOG.md
- sdk/eventhub/eventhubs-checkpointstore-blob/package.json
- sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
- sdk/eventhub/eventhubs-checkpointstore-blob/test/utils/testUtils.ts
@azure/core-amqp, @azure/event-hubs, and @azure/eventhubs-checkpointstore-blob
Gist: https://gist.github.com/conniey/f96d64547efa955a9e763cee6b65d1fc
Enable the SDK to communicate with GeoDR-enabled Event Hubs.
The PR follows closely what the crew agreed on for now which is changing the type of `offset`s to be a string but this will be revisited later.
Tests will come later.
N/A
> [Event Hubs] Support GeoDR

- sdk/identity/identity/package.json
- sdk/test-utils/recorder/package.json
@azure/test-utils
#29930
Bump the version of @azure/core-client for min/ max test in live pipeline in Identity & Test recorder
> [Identity] Bump core-client Version For Min Test

- sdk/containerregistry/container-registry/test/utils/utils.ts
after test-credential upgrade
Issue https://github.com/Azure/azure-sdk-for-js/issues/29740
> [test][container-registry] fix build error

- sdk/eventgrid/eventgrid-namespaces/README.md
- sdk/eventgrid/eventgrid-namespaces/package.json
- sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/README.md
- sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/namespaceActivities.js
- sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/package.json
- sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/sample.env
- sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/README.md
- sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/package.json
- sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/sample.env
- sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/src/namespaceActivities.ts
- sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/tsconfig.json
- sdk/eventgrid/eventgrid-system-events/README.md
- sdk/eventgrid/eventgrid-system-events/review/eventgrid-system-events.api.md
- sdk/eventgrid/eventgrid-system-events/src/models.ts
1. @azure/eventgrid-namespaces 
2. @azure/evengrid-system-events 
None
There is no specific problem associated with this PR. The Readme files have to be updated for latest changes. This PR accomplishes that. Also, the casing in he CloudEVent must be modified based on the latest changes that went in to the Namespaces package. 
No design concerns
No. Readme file changes do not require any tests.
. 
https://github.com/Azure/azure-sdk-for-js/pull/29764
> [@azure/eventgrid-namespaces]  [@azure/evengrid-system-events] Update Readme file and Cloud Event Model

- sdk/devcenter/developer-devcenter-rest/CHANGELOG.md
Update release date for DevCenter 1.0.0 
Original dev center sdk 1.0.0 PR: https://github.com/Azure/azure-sdk-for-js/pull/29512
APIView: [@azure-rest/developer-devcenter - apiview.dev](https://apiview.dev/Assemblies/Review/e17096012eb7466a8aab7c74742c6bff?revisionId=b4d2f5f84d98499dacfcc5e7cdd15d52)
> [DevCenter] Update release date

- .vscode/cspell.json
- common/config/rush/pnpm-lock.yaml
- sdk/communication/communication-identity/package.json
- sdk/identity/identity-broker/CHANGELOG.md
- sdk/identity/identity-broker/package.json
- sdk/identity/identity-cache-persistence/CHANGELOG.md
- sdk/identity/identity-cache-persistence/package.json
- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
- sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
- sdk/identity/identity/test/internal/node/managedIdentityCredential/arcMsi.spec.ts
- sdk/identity/identity/test/internal/node/workloadIdentityCredential.spec.ts
> [identity] Identity bug fix

- sdk/communication/communication-call-automation/src/models/audio.ts
- sdk/communication/communication-call-automation/src/utli/streamingDataParser.ts
- sdk/communication/communication-call-automation/test/streamingDataParser.spec.ts
1.Added beta4 audio streaming parser.
2.Unit test.
> Added beta4 audio streaming parser.

- sdk/monitor/monitor-query/test/public/shared/testShared.ts
https://github.com/Azure/azure-sdk-for-js/issues/29886
The test credentials in authenticated for a particular audience. So it has to be set correctly. This PR sets it correctly.
No specific design considerations.
> [@azure/monitor-query] Update Audience Value in tests

- common/config/rush/pnpm-lock.yaml
- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/assets.json
- sdk/communication/communication-chat/package.json
- sdk/communication/communication-chat/test.env
- sdk/communication/communication-chat/test/public/utils/recordedClient.ts
- sdk/core/core-lro/test/lro.spec.ts
Update the test recorder version and fix the recordings.
> Update the test recorder version and fix the recordings.

- common/tools/dev-tool/src/templates/sampleReadme.md.ts
- common/tools/dev-tool/src/util/samples/generation.ts
before they are later sorted by weight.
- also format code
> [dev-tool] sort collected sources by their paths first

- SUPPORT.md
N/A
This PR updates our SUPPORT.md file with additional policy changes we are
making, ensuring that the support policy is well-documented and developers can
find relevant information for dropping Node.js support.
Resolves #28449
> Add information about Node.js EOL policies

- sdk/eventgrid/eventgrid/CHANGELOG.md
to Azure SDK Design Guidelines for TypeScript
> [doc][eventgrid] fix broken link

- sdk/monitor/monitor-query/package.json
None
The live tests for `@azure/monitor-query` are failing daily for only one configuration `ubuntu2004_node_18x_min`. Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3864316&view=logs&j=0daa86f4-d78e-5a1c-68e8-8dcfd7021055. The error message is the following:
```
Invoking "rushx build"
----------------------
Found configuration in /mnt/vss/_work/1/s/rush.json
Rush Multi-Project Build Tool 5.120.6 - Node.js 18.20.3 (LTS)
> "tsc -p ."
../../../../../common/temp/node_modules/.pnpm/@azure-tools+test-recorder@3.5.0/node_modules/@azure-tools/test-recorder/types/src/recorder.d.ts(6,10): error TS2305: Module '"@azure/core-client"' has no exported member 'AdditionalPolicyConfig'.
Error: Failed calling tsc -p ..  Exit code: 2
```
In order to fix this …
> [@azure/monitor-query] Live Tests CI Failure

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-tests-isolated.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
Needed for https://github.com/Azure/azure-sdk-tools/pull/8422
> SubscriptionConfigurationFilePath -> SubscriptionConfigurationFilePaths

- sdk/test-utils/test-credential/CHANGELOG.md
- sdk/test-utils/test-credential/package.json
- sdk/test-utils/test-credential/src/index.ts
@azure-tools/test-credential
Update to ChainedTokenCredential so that the live test pipeline can successfully get the token.
> [Test-Credential] Update to ChainedTokenCredential

- sdk/eventgrid/eventgrid-system-events/package.json
@azure/eventgrid-system-events
Fix typo in package.json
> [@azure/eventgrid-system-events] Fix typo in package.json

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/credentials/onBehalfOfCredential.ts
- sdk/identity/identity/src/msal/nodeFlows/msalClient.ts
- sdk/identity/identity/test/internal/node/onBehalfOfCredential.spec.ts
Resolves #29408 
Migrates OBO credential to the MSALClient flow
> [identity] Migrate OBO to msalClient

- eng/pipelines/templates/steps/npm-release-task.yml
Pull changes from main for eng folder
> [Test Credential 1.x] Update eng folder from main

- eng/common/pipelines/templates/steps/validate-all-packages.yml
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/stages/platform-matrix.json
- eng/pipelines/templates/variables/image.yml
Get update from main for macos & validate stages
> [Test- Recorder 1.x] Update Macos & Validate pipeline

- sdk/keyvault/keyvault-admin/test/public/utils/authentication.ts
- sdk/keyvault/keyvault-certificates/assets.json
- sdk/keyvault/keyvault-certificates/test/public/utils/testAuthentication.ts
- sdk/keyvault/keyvault-secrets/assets.json
- sdk/keyvault/keyvault-secrets/test/public/utils/testAuthentication.ts
Key Vault packages
Skipping some global sanitizers and re-recording where necessary to fix Key Vault CI
> [keyvault] fix ci in response to global sanitizers

- eng/common/pipelines/templates/steps/validate-all-packages.yml
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/stages/platform-matrix.json
- eng/pipelines/templates/variables/image.yml
Update macos & validate pipeline task
> [Eng] Update eng folder

- eng/pipelines/templates/stages/platform-matrix.json
Remove windows agent in matrix
> [Eng] Remove windows agent

- sdk/communication/communication-call-automation/test/callAutomationClient.spec.ts
> Connect api live test.

- common/tools/dev-tool/src/commands/admin/migrate-package.ts
Adds the following:
- Global regex replace for context replacements
- Changes sinon spy to `vi.spyOn`
- Adds node specifiers to node imports
> [dev-tool] Update migration tool for Sinon and Node Imports

- eng/pipelines/templates/jobs/live.tests.yml
Needed to enable pipeline credential
> Add SYSTEM_ACCESSTOKEN to tests

- common/config/rush/pnpm-lock.yaml
- Run rush update --full after release hot fix for test-credential 1.2
> Run rush update --full

- common/config/rush/pnpm-lock.yaml
- common/tools/dev-tool/package.json
- #30160
Updates to latest ts-morph package.
> [dev-tool] Update ts-morph

- sdk/core/core-rest-pipeline/CHANGELOG.md
> [core-rest-pipeline] prepare for 2024-06-24 release

- sdk/oracledatabase/arm-oracledatabase/samples-dev/autonomousDatabasesGenerateWalletSample.ts
- sdk/oracledatabase/arm-oracledatabase/samples/v1-beta/javascript/autonomousDatabasesGenerateWalletSample.js
- sdk/oracledatabase/arm-oracledatabase/samples/v1-beta/typescript/src/autonomousDatabasesGenerateWalletSample.ts
fixes  https://github.com/Azure/azure-sdk-for-js/issues/29810
> [mgmt] update samples to fix credscan issue

- sdk/core/core-lro/CHANGELOG.md
core-lro v3 api view has approved: https://apiview.dev/Assemblies/Review/2c2e6c39be9f4efcb7dcb5812ec03caa?revisionId=5ccd136f6bef4070b2acec454fd0443f&doc=False
> Update the changelog date for core-lro v3

- sdk/core/core-client-rest/CHANGELOG.md
have a core client release for mpg preview.
> core-client-rest-june-release-for-mpg-preview

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
Failing (yesterday): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3912438&view=results
Fixed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3914964&view=results
There is an error in `archetype-sdk-tests.yml` which breaks some pipelines. 
Failing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3913894&view=results
Fixed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3916475&view=logs&j=43701d7e-216c-59bf-08d1-1efd0c7ac90a&t=2c222b04-4a7e-5bc1-61a2-d8f951031fe8
> Fix up live testing

- sdk/communication/communication-recipient-verification/CHANGELOG.md
- sdk/communication/communication-rooms/CHANGELOG.md
@azure/communication-rooms
N/A - build errors
Our CI pipelines verify that changelogs have the expected sections. Somehow this
slipped unnoticed until #29710 started failing CI because of this.
This PR just adds an expected header. The original PR reviews argued against
"features added" so I just put it under "Other Changes"
> [communication] Add header to changelog

- sdk/communication/communication-call-automation/src/utli/streamingDataParser.ts
- sdk/communication/communication-call-automation/test/callRecordingClient.spec.ts
- sdk/communication/communication-call-automation/test/streamingDataParser.spec.ts
1.Fixed streamDataParser transcription data mapping.
2.Updated unit test.
> Fixed streamDataParser unit test.

- sdk/ai/ai-inference-rest/CHANGELOG.md
Add date and required subheader to changelog
> [AI] [Inference] update changelog to pass release process

- .github/CODEOWNERS
- sdk/ai/ai-inference-rest/package.json
- `dist/` already include the other two that follows
- We don't usually pack CHANGELOG
- We don't pack the `review/` directory.
-------
`@azure-rest/ai-inference`
> [AI][Inference] remove entries that are not needed from `files`

- sdk/identity/identity/samples/AzureCacheForRedis/ioredis.md
- sdk/identity/identity/samples/AzureCacheForRedis/node-redis.md
Azure Cache for Redis Passwordless Samples
> [Identity] extract username from access token for redis samples

- sdk/storage/storage-blob/sample.env
- sdk/storage/storage-blob/test.env
- sdk/storage/storage-blob/test/utils/testutils.common.ts
- sdk/storage/storage-blob/tests.yml
- sdk/storage/storage-file-datalake/test.env
- sdk/storage/storage-file-datalake/test/utils/testutils.common.ts
- sdk/storage/storage-file-datalake/tests.yml
- sdk/storage/storage-file-share/assets.json
- sdk/storage/storage-file-share/test/node/directoryclient.spec.ts
- sdk/storage/storage-file-share/test/node/fileclient.spec.ts
- sdk/storage/storage-file-share/test/node/shareclient.spec.ts
- sdk/storage/storage-file-share/test/utils/testutils.common.ts
- sdk/storage/storage-file-share/tests.yml
- sdk/storage/storage-queue/test.env
- sdk/storage/storage-queue/test/utils/testutils.common.ts
- sdk/storage/storage-queue/tests.yml
- sdk/storage/test-resources-post.ps1
- sdk/storage/test-resources.json
> [Storage]Remove service principal secret from storage testing

- sdk/scvmm/arm-scvmm/samples-dev/guestAgentsCreateSample.ts
- sdk/scvmm/arm-scvmm/samples-dev/vmmServersCreateOrUpdateSample.ts
- sdk/scvmm/arm-scvmm/samples/v1/javascript/guestAgentsCreateSample.js
- sdk/scvmm/arm-scvmm/samples/v1/javascript/vmmServersCreateOrUpdateSample.js
- sdk/scvmm/arm-scvmm/samples/v1/typescript/src/guestAgentsCreateSample.ts
- sdk/scvmm/arm-scvmm/samples/v1/typescript/src/vmmServersCreateOrUpdateSample.ts
fixes https://github.com/Azure/azure-sdk-for-js/issues/30232
swagger pr https://github.com/Azure/azure-rest-api-specs/pull/29666
> [mgmt] fix cred issue

- sdk/schemaregistry/schema-registry-json/review/schema-registry-json.api.md
- sdk/schemaregistry/schema-registry-json/samples-dev/schemaRegistryJsonSample.ts
- sdk/schemaregistry/schema-registry-json/samples-dev/schemaRegistryJsonWithValidation.ts
- sdk/schemaregistry/schema-registry-json/samples/v1/javascript/package.json
- sdk/schemaregistry/schema-registry-json/samples/v1/typescript/package.json
- sdk/schemaregistry/schema-registry-json/samples/v1/typescript/src/schemaRegistryJsonSample.ts
- sdk/schemaregistry/schema-registry-json/samples/v1/typescript/src/schemaRegistryJsonWithValidation.ts
- sdk/schemaregistry/schema-registry-json/samples/v1/typescript/src/withEventHubsConsumerClient.ts
- sdk/schemaregistry/schema-registry-json/src/jsonSchemaSerializer.ts
Update API view after arch board discussion
> [Schema Registry JSON] Update API View

- sdk/devcenter/developer-devcenter-rest/CHANGELOG.md
Update release date on changelog. APIView has been approved [@azure-rest/developer-devcenter - apiview.dev](https://apiview.dev/Assemblies/Review/e17096012eb7466a8aab7c74742c6bff?revisionId=dcf9502b75b34a37ae47c475aa281d56&doc=False)
> [DevCenter] Update release date for DevCenter 1.0.0

- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-util/CHANGELOG.md
> [core] prepare for 2024 July release

- .github/CODEOWNERS
Resolves issue https://github.com/Azure/azure-sdk-for-js/issues/30236
> [CODEOWNERS] add an entry for ai-translation-document-rest

- sdk/core/logger/CHANGELOG.md
> [core-logger] Prepare for 2024 July release

- .github/CODEOWNERS
This PR does two things:
- Adds a new more specific rule for api.md files inside of Mgmt packages to ensure @qiaozha and @MaryGao can approve changes to ARM packages.
- Cleans up our manual listing of deputies for api.md reviews to be the core review team since it was mostly redundant.
> [CODEOWNERS] Add rule for mgmt review files

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/assets.json
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/Pipeline.ts
- sdk/storage/storage-blob/src/policies/StorageCorrectConentLengthPolicy.ts
- sdk/storage/storage-blob/src/policies/StorageCorrectContentLengthPolicy.browser.ts
- sdk/storage/storage-blob/src/policies/StorageCorrectContentLengthPolicy.ts
- sdk/storage/storage-blob/test/blockblobclient.spec.ts
- sdk/storage/storage-blob/test/node/blockblobclient.spec.ts
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/Pipeline.ts
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/Pipeline.ts
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/Pipeline.ts
> [Storage] Correct content-length header with request body length

- .github/CODEOWNERS
and cover eslint-plugin-azure-sdk-helper directory too
> [CODEOWNERS] add an entry for /common/tools

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
> [identity] Prepare identity for July release

- sdk/appconfiguration/app-configuration/CHANGELOG.md
- sdk/appconfiguration/app-configuration/assets.json
- sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
- sdk/appconfiguration/app-configuration/test/public/index.spec.ts
> [App Config] Update Etag parsing for list configuration setting

- sdk/digitaltwins/digital-twins-core/package.json
- sdk/digitaltwins/digital-twins-core/test-resources.json
- sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
- sdk/digitaltwins/digital-twins-core/test/utils/testAuthentication.ts
- sdk/digitaltwins/digital-twins-core/tests.yml
@azure/digital-twins-core
#30395
#29699
Migrate test suite to use federated authentication. Skip 1 test that is failing in the live pipeline. Tracking issue is linked to this PR
> [Digital Twin Core] Migrate Test Suite

- sdk/ai/ai-inference-rest/CHANGELOG.md
- sdk/ai/ai-inference-rest/README.md
- sdk/ai/ai-inference-rest/assets.json
- sdk/ai/ai-inference-rest/package.json
- sdk/ai/ai-inference-rest/review/ai-inference.api.md
- sdk/ai/ai-inference-rest/samples-dev/embeddings.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/README.md
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/embeddings.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/package.json
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/README.md
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/package.json
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/embeddings.ts
- sdk/ai/ai-inference-rest/src/clientDefinitions.ts
- sdk/ai/ai-inference-rest/src/isUnexpected.ts
- sdk/ai/ai-inference-rest/src/modelClient.ts
- sdk/ai/ai-inference-rest/src/models.ts
- sdk/ai/ai-inference-rest/src/outputModels.ts
- sdk/ai/ai-inference-rest/src/parameters.ts
- sdk/ai/ai-inference-rest/src/responses.ts
- sdk/ai/ai-inference-rest/test/public/browser/streamingChat.spec.ts
- sdk/ai/ai-inference-rest/test/public/chatCompletions.spec.ts
- sdk/ai/ai-inference-rest/test/public/embeddings.spec.ts
- sdk/ai/ai-inference-rest/test/public/node/streamingChat.spec.ts
- sdk/ai/ai-inference-rest/test/public/types.ts
- sdk/ai/ai-inference-rest/test/public/utils/recordedClient.ts
- sdk/ai/ai-inference-rest/tsp-location.yaml
add embeddings routes, sync with latest TypeSpec
> [AI] [Inference] add embeddings routes, sync with latest TypeSpec

- sdk/storage/storage-file-datalake/package.json
[Storage]Added to pack referenced files under storage-blob folder.
> [Storage]Added to pack referenced files under storage-blob folder.

- sdk/ai/ai-inference-rest/assets.json
- sdk/ai/ai-inference-rest/package.json
- sdk/ai/ai-inference-rest/test/public/utils/recordedClient.ts
> [AI] [Inference] use createTestCredential for tests

- sdk/vision/ai-vision-image-analysis-rest/CHANGELOG.md
- sdk/vision/ai-vision-image-analysis-rest/src/imageAnalysisClient.ts
@azure-rest/ai-vision-image-analysis
N/A
Changelog and user agent update for beta-3
No. Version update only.
> Prep for ImageAnalysis Beta3

- sdk/vision/ai-vision-image-analysis-rest/src/clientDefinitions.ts
- sdk/vision/ai-vision-image-analysis-rest/src/imageAnalysisClient.ts
- sdk/vision/ai-vision-image-analysis-rest/src/isUnexpected.ts
- sdk/vision/ai-vision-image-analysis-rest/src/parameters.ts
- sdk/vision/ai-vision-image-analysis-rest/src/responses.ts
- sdk/vision/ai-vision-image-analysis-rest/test/public/AnalysisTests.spec.ts
- sdk/vision/ai-vision-image-analysis-rest/test/public/utils/clientMethods.ts
- sdk/vision/ai-vision-image-analysis-rest/test/public/utils/recordedClient.ts
@azure-rest/ai-vision-image-analysis
N/A
Test cases were failing on playback due to environment mis-configuration.
> Update tests with environmental changes

- sdk/ai/ai-inference-rest/assets.json
- sdk/ai/ai-inference-rest/test/public/chatCompletions.spec.ts
- sdk/ai/ai-inference-rest/test/public/embeddings.spec.ts
- sdk/ai/ai-inference-rest/test/public/utils/recordedClient.ts
Add regression tests for chat completions and embeddings routes
> [AI] [Inference] chat and embeddings regression tests

- sdk/cosmosdb/cosmos/README.md
@azure/cosmos
Updated non-streamable cross-partition query in README
> updated non-streamable query in README 

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
- sdk/storage/test-resources.json
> [Storage]Bump package version, upgrade @azure/core-tracing dependency

- sdk/monitor/monitor-opentelemetry/src/metrics/utils.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standardMetrics.test.ts
https://github.com/microsoft/ApplicationInsights-node.js/issues/1342
> [monitor-opentelemetry] Fix issue with standard metrics dependency cardinality

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/README.md
To point to the main branch rather than the deleted feature branch.
> [OpenAI] Edit links

- sdk/communication/communication-call-automation/src/models/audio.ts
- sdk/communication/communication-call-automation/src/utli/streamingDataParser.ts
Fixed streamDataParser audio data mapping
> Fixed streamDataParser audio data mapping

- eng/pipelines/templates/jobs/live.tests.yml
so that all configurations have it.
> [EngSys] Apply AzurePowerShellCredential workaround unconditionally

- sdk/openai/openai/MIGRATION.md
- sdk/openai/openai/package.json
> [OpenAI] Edit migration guide

- sdk/botservice/arm-botservice/assets.json
- sdk/botservice/arm-botservice/test/botservice_examples.ts
fixes https://github.com/Azure/azure-sdk-for-js/issues/30491
> [mgmt] add sanitized for bot service test cases

- sdk/healthdataaiservices/azure-health-deidentification/LICENSE
- sdk/healthdataaiservices/azure-health-deidentification/review/health-deidentification.api.md
- sdk/healthdataaiservices/azure-health-deidentification/src/clientDefinitions.ts
- sdk/healthdataaiservices/azure-health-deidentification/src/deidentificationClient.ts
- sdk/healthdataaiservices/azure-health-deidentification/src/index.ts
- sdk/healthdataaiservices/azure-health-deidentification/src/models.ts
- sdk/healthdataaiservices/azure-health-deidentification/src/outputModels.ts
- sdk/healthdataaiservices/azure-health-deidentification/test/public/jobOperationsTest.spec.ts
- sdk/healthdataaiservices/azure-health-deidentification/test/public/realtimeOperationsTest.spec.ts
- sdk/healthdataaiservices/azure-health-deidentification/test/public/utils/recordedClient.ts
> Renaming client because autorest in js isn't respecting the @client tag

- sdk/ai/ai-inference-rest/README.md
- sdk/ai/ai-inference-rest/samples-dev/streamChatCompletions.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/README.md
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/README.md
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/streamChatCompletions.ts
#30554
sample fixes in README and samples folder
> [AI] [Inference] README sample fixes #30554

- sdk/core/core-client-rest/src/common.ts
> [@azure-rest/core-client] Fix typo in common.ts

- common/config/rush/pnpm-lock.yaml
- sdk/healthdataaiservices/azure-health-deidentification/package.json
> Fix dependency versions after testing package

- sdk/identity/identity/README.md
- sdk/identity/identity/TOKEN_CACHING.md
- sdk/identity/identity/src/credentials/deviceCodeCredential.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
- Resolves #25740
- Resolves #30383
- Resolves #30560
This PR adds various documentation updates ported over from other languages,
improving verbiage around `authenticate` usage and the azure authority host.
> [identity] Various documentation improvements

- .github/CODEOWNERS
N/A
N/A
This updates the Code Owners for JS SDK as few team members have left the team.
N/A
N/A
N/A
> update CODEOWNERS for Azure Cosmos DB JS SDK

- sdk/servicebus/service-bus/TROUBLESHOOTING.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/samples/v7-beta/javascript/README.md
- sdk/servicebus/service-bus/samples/v7-beta/typescript/README.md
as the sample has been removed.
> [Docs][ServiceBus] remove broken links to usingAadAuth sample

- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/logger/CHANGELOG.md
> [core] prepare for 2024 August release

- sdk/identity/identity/package.json
- sdk/identity/identity/src/client/identityClient.ts
- sdk/identity/identity/test/internal/node/clientSecretCredential.spec.ts
- sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts
- sdk/identity/identity/test/public/node/clientSecretCredential.spec.ts
- sdk/identity/identity/test/public/node/deviceCodeCredential.spec.ts
- sdk/identity/identity/test/public/node/usernamePasswordCredential.spec.ts
and update code to adapt the changes.
> [identity] upgrade depedency `@azure/abort-controller` to v2

- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-certificates/src/lro/create/operation.ts
- sdk/keyvault/keyvault-certificates/src/lro/operation/operation.ts
- sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
- sdk/keyvault/keyvault-common/package.json
- sdk/keyvault/keyvault-keys/package.json
- sdk/keyvault/keyvault-secrets/package.json
- sdk/keyvault/keyvault-secrets/test/public/CRUD.spec.ts
and fix code.
-------
`@azure/keyvault-*`
> [KeyVault] upgrade dependency `@azure/abort-controller` to v2

- sdk/maps/maps-common/package.json
- sdk/monitor/monitor-ingestion/package.json
- sdk/monitor/monitor-ingestion/test/public/logsIngestionClient.spec.ts
- sdk/remoterendering/mixed-reality-remote-rendering/package.json
- sdk/synapse/synapse-artifacts/package.json
- update monitor-ingestion test code to adapt to the change
-------
monitor-ingestion mixed-reality-remote-rendering synapse-artifacts maps-common
> [multiple packages] upgrade dependency @azure/abort-controller to v2

- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/sample.env
- sdk/eventhub/event-hubs/samples-dev/iothubConnectionString.ts
- sdk/eventhub/event-hubs/samples-dev/iothubConnectionStringWebsockets.ts
- sdk/eventhub/event-hubs/samples/v5-beta/express/package.json
- sdk/eventhub/event-hubs/samples/v5-beta/express/src/asyncBatchingProducer.ts
- sdk/eventhub/event-hubs/samples/v5-beta/javascript/README.md
- sdk/eventhub/event-hubs/samples/v5-beta/javascript/iothubConnectionString.js
- sdk/eventhub/event-hubs/samples/v5-beta/javascript/iothubConnectionStringWebsockets.js
- sdk/eventhub/event-hubs/samples/v5-beta/javascript/package.json
- sdk/eventhub/event-hubs/samples/v5-beta/javascript/sample.env
- sdk/eventhub/event-hubs/samples/v5-beta/typescript/README.md
- sdk/eventhub/event-hubs/samples/v5-beta/typescript/package.json
- sdk/eventhub/event-hubs/samples/v5-beta/typescript/sample.env
- sdk/eventhub/event-hubs/samples/v5-beta/typescript/src/iothubConnectionString.ts
- sdk/eventhub/event-hubs/samples/v5-beta/typescript/src/iothubConnectionStringWebsockets.ts
- sdk/eventhub/mock-hub/src/sender/streamingPartitionSender.ts
- sdk/eventhub/test-resources.json
They now reference the environment variable created by the arm template.
> [Event Hubs] Cleanup IoT Hub samples

- eng/ignore-links.txt
fixes https://github.com/Azure/azure-sdk-for-js/issues/30635
> revert a broken link in ignore-links.txt

- .github/CODEOWNERS
Add Jarno Hakulinen for AI Inference SDK
> [AI] [Inference] Update CODEOWNERS

- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/toolCall.ts
#30554 
Fix constructor syntax in sample
> [AI] [Inference] Fix #30554

- sdk/identity/identity/src/credentials/deviceCodeCredentialOptions.ts
- sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
Fixes  https://github.com/Azure/azure-sdk-for-js/issues/30280
> [Identity] update docs for IDC and device code credentials

- sdk/cosmosdb/cosmos/CHANGELOG.md
@azure/cosmos
This PR updates changelog samples related to vector search feature
> Update vector search changelog

- sdk/cosmosdb/cosmos/CHANGELOG.md
> add release date in changelog

- sdk/monitor/monitor-opentelemetry/README.md
> fix typo in README

- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/formrecognizer/ai-form-recognizer/test/private/poller.spec.ts
- sdk/keyvault/keyvault-admin/package.json
- sdk/keyvault/keyvault-admin/test/public/accessControlClient.aborts.spec.ts
- sdk/keyvault/keyvault-admin/test/public/backupClient.abort.spec.ts
- sdk/monitor/monitor-query/package.json
- sdk/textanalytics/ai-text-analytics/package.json
- sdk/web-pubsub/web-pubsub-client/package.json
- sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
- sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts
and fix code
-------
ai-form-recognizer, ai-text-analytics, web-pubsub-client
> [webpubsub,fr,ta] upgrade dependency @azure/abort-controller to v2

- sdk/maps/maps-geolocation-rest/CHANGELOG.md
- sdk/maps/maps-render-rest/CHANGELOG.md
- sdk/maps/maps-route-rest/CHANGELOG.md
- sdk/maps/maps-search-rest/CHANGELOG.md
- #30420 
Update the changelog for changes in #30420
> [Maps] Update changelog for fixing `scopes` in bearer token

- sdk/core/ci.yml
as there's no more pending work for issue #26770
> [core-rest-pipeline] enable publishing docs

- sdk/storage/storage-blob/review/storage-blob.api.md
- sdk/storage/storage-blob/src/BlobServiceClient.ts
- sdk/storage/storage-blob/src/Clients.ts
- sdk/storage/storage-blob/src/ContainerClient.ts
- sdk/storage/storage-blob/src/index.ts
- sdk/storage/storage-blob/src/sas/AccountSASSignatureValues.ts
- sdk/storage/storage-blob/src/sas/BlobSASSignatureValues.ts
- sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
- sdk/storage/storage-file-datalake/src/DataLakeFileSystemClient.ts
- sdk/storage/storage-file-datalake/src/DataLakeServiceClient.ts
- sdk/storage/storage-file-datalake/src/clients.ts
- sdk/storage/storage-file-datalake/src/index.ts
- sdk/storage/storage-file-datalake/src/sas/AccountSASSignatureValues.ts
- sdk/storage/storage-file-datalake/src/sas/DataLakeSASSignatureValues.ts
- sdk/storage/storage-file-share/review/storage-file-share.api.md
- sdk/storage/storage-file-share/src/AccountSASSignatureValues.ts
- sdk/storage/storage-file-share/src/Clients.ts
- sdk/storage/storage-file-share/src/FileSASSignatureValues.ts
- sdk/storage/storage-file-share/src/ShareServiceClient.ts
- sdk/storage/storage-file-share/src/index.ts
- sdk/storage/storage-queue/review/storage-queue.api.md
- sdk/storage/storage-queue/src/AccountSASSignatureValues.ts
- sdk/storage/storage-queue/src/QueueClient.ts
- sdk/storage/storage-queue/src/QueueSASSignatureValues.ts
- sdk/storage/storage-queue/src/QueueServiceClient.ts
- sdk/storage/storage-queue/src/index.ts
> Added ability to retrieve SAS string to sign for debugging purposes

- .github/CODEOWNERS
> update azure batch code owners

- common/config/rush/pnpm-lock.yaml
- common/tools/vite-plugin-browser-test-map/src/index.ts
- sdk/core/core-amqp/package.json
- sdk/core/core-amqp/vitest.browser.config.ts
- @azure/core-amqp
Removes the polyfills for vite and instead injects the given polyfills for process and Buffer.
> [core-amqp] Remove polyfills

- sdk/communication/communication-call-automation/CHANGELOG.md
- sdk/communication/communication-call-automation/package.json
- sdk/communication/communication-call-automation/src/callAutomationClient.ts
- sdk/communication/communication-call-automation/src/models/constants.ts
- sdk/communication/communication-call-automation/swagger/README.md
1.3.0-beta.1
Media streaming not added in the group call
Enable the media streaming for the group call
> Adding the audio streaming support for the group call

- sdk/core/core-sse/samples-dev/createSseStream.ts
- sdk/core/core-sse/samples/v2/javascript/createSseStream.js
- sdk/core/core-sse/samples/v2/javascript/package.json
- sdk/core/core-sse/samples/v2/typescript/package.json
- sdk/core/core-sse/samples/v2/typescript/src/createSseStream.ts
This public endpoint will return events such as:
```
Server time is 2024-08-10T12:57:47+00:00
Message at time 2024-08-10T12:57:47+00:00
Keep listening to server updates
Update request received
Update request received
```
> [core-sse] Update sample to use a real world example

- sdk/core/core-xml/package.json
> [core-xml] Updating to latest fast-xml-parser

- rush.json
- rush to latest 5.131.4
- pnpm to latest v8 8.15.9
> [EngSys] update rush and pnpm version

- .github/CODEOWNERS
> Update CODEOWNERS for Web PubSub

- sdk/identity/identity/CHANGELOG.md
> [identity] 4.5.0-beta.2 release

- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/exporter.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/sender.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/types.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/liveMetrics.test.ts
> [monitor-opentelemetry] Fix issue with credential in Quickpulse sender

- common/tools/eslint-plugin-azure-sdk/src/configs/index.ts
- common/tools/eslint-plugin-azure-sdk/src/typings/eslint-plugin-promise.d.ts
now that the plugin has flat config support
-------
> [eslint-plugin] enable eslint-plugin-promise for our flat config

- eng/pipelines/templates/stages/archetype-js-release.yml
Depends on https://github.com/Azure/azure-sdk-tools/pull/8842
> Remove azure-sdk-docs-prod-blob-name usage

- eng/pipelines/templates/jobs/live.tests.yml
Enable system access token env var in the relay credential
> Update System_Access_Token env for browser live test pipeline

- sdk/core/core-lro/test/lro.spec.ts
Addresses https://github.com/Azure/azure-sdk-for-js/issues/30793
> [core-lro] Add test case for PUT ignoring final-state-via

- sdk/communication/communication-alpha-ids/README.md
- sdk/communication/communication-email/README.md
- sdk/communication/communication-identity/README.md
- sdk/communication/communication-messages-rest/README.md
- sdk/communication/communication-phone-numbers/README.md
- sdk/communication/communication-recipient-verification/README.md
- sdk/communication/communication-rooms/README.md
- sdk/communication/communication-short-codes/README.md
- sdk/communication/communication-sms/README.md
- sdk/communication/communication-tiering/README.md
- sdk/communication/communication-toll-free-verification/README.md
These are not detected properly in current configuration, but will appear once
we move to use ESLint flat config.
> [eslint] fix linting issues in communication README.md files

- sdk/documentintelligence/ai-document-intelligence-rest/CHANGELOG.md
> [Document Intelligence] Release 1.0.0-beta.3

- sdk/remoterendering/mixed-reality-remote-rendering/test/public/remoteRenderingClient.spec.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/30883
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4077351&view=results
> [Remote Rendering] Fix test

- eng/pipelines/bicep-warnings.yml
Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4083622&view=results
This PR introduces a new Azure DevOps pipeline that automatically lints all Bicep files in the repository and generates a report of any linting warnings. These reports are stored as artifacts and uploaded to Azure Blob Storage for tracking over time.
- Automated Linting: Ensures that all Bicep files are consistently checked for best practices and potential issues.
- Historical Tracking: By appending the date to the lint warnings file, we can monitor progress and improvements over time.
- Monitor the lint warnings reports over time to identify and address recurring issues.
- Use the stored reports to guide refactoring efforts and improve Bicep code quality across the repository.
``` …
```
> [EngSys] Add a Bicep linter pipeline

- eng/CredScanSuppression.json
add sdk/batch/batch-rest/test/utils/fakeTestSecrets.ts to credscan suppression list.
> [EngSys] fix aggregate-report error

- sdk/cosmosdb/cosmos/src/utils/aggregateUtils.browser.ts
- sdk/cosmosdb/cosmos/src/utils/aggregateUtils.ts
> fix linting

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/src/common/constants.ts
@azure/cosmos
N/A
This PR updates changelog and release version of SDK from 4.1.0 to 4.1.1.
N/A
N/A
> [cosmos] Update changelog and release version(4.1.1)

- sdk/playwrighttesting/create-microsoft-playwright-testing/src/initialize.ts
@azure/create-microsoft-playwright-testing
Ensure running prettier does not modify service configuration file
- Missing comma
- Change double quotes to single quotes
> refactor(playwrighttesting): ensure prettier does not change service configuration

- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
Interrupted tests being incorrectly marked as failed.
> Marking interrupted tests as skipped

- sdk/openai/openai/samples-dev/codeInterpreter.ts
- sdk/openai/openai/samples/v2-beta/javascript/codeInterpreter.js
- sdk/openai/openai/samples/v2-beta/typescript/src/codeInterpreter.ts
> [OpenAI] Update Assistants sample

- sdk/playwrighttesting/create-microsoft-playwright-testing/CHANGELOG.md
- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting): CHANGELOG 1.0.0-beta.1 release date changed to 9th Sep

- sdk/playwrighttesting/microsoft-playwright-testing/README.md
- sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/manually-connecting-to-browsers/README.md
- sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/README.md
- sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/manually-connecting-to-browsers/README.md
- sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/README.md
Unsupported markdown format in generated package docs.
> docs(playwrighttesting): unsupported markdown format in url

- .github/CODEOWNERS
Adding Operator Nexus - Network Cloud to code owners to receive bot notifications
> Add Operator Nexus - Network Cloud to CODEOWNERS 

- sdk/openai/openai/CHANGELOG.md
- sdk/openai/openai/package.json
Thanks to @diberry for the catch!
> [OpenAI] Fix import

- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/src/constants.ts
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-util/package.json
@azure/core-auth
@azure/core-util
Update changelog for release. Also, for core-util make a minor version bump as
per semver.
> [core] Prepare packages for release

- sdk/playwrighttesting/microsoft-playwright-testing/README.md
> docs(playwrighttesting): enhance authentication section in README

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting): CHANGELOG for 1.0.0-beta.2 release for microsoft-playwright-testing

- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/README.md
- sdk/monitor/monitor-opentelemetry/src/shared/config.ts
> [monitor-opentelemetry]  Update enableTraceBasedSamplingForLogs config default value to false

- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-lro/package.json
Prepare release for core-lro in Sep
> [core] Prepare release for core-lro in Sep

- sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/serviceClient.ts
`
Display informational messages to the user in case of errors at the end of test.
> fix(playwrighttesting): Updated error handling for reporting

- sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
`@azure/microsoft-playwright-testing`
Improved Sas uri expiry logic.
> improved SAS expriy check logic

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting): CHANGELOG for 1.0.0-beta.3 release for microsoft-playwright-testing

- sdk/vision/ai-vision-image-analysis-rest/samples/javascript/package.json
Fixes [#28746](https://github.com/Azure/azure-sdk-for-js/issues/28746)
@joheredi and @dargilco for notification.
> [sample][image-analysis] update the dependency package version in package.json

- common/config/rush/pnpm-lock.yaml
- sdk/schemaregistry/perf-tests/schema-registry-avro/package.json
- sdk/schemaregistry/schema-registry/CHANGELOG.md
- sdk/schemaregistry/schema-registry/package.json
- sdk/schemaregistry/schema-registry/src/constants.ts
> [Schema Registry] Post release update for Schema Registry

- sdk/identity/identity/CHANGELOG.md
> [Identity] update changelog for beta release

- .github/CODEOWNERS
> Update CODEOWNERS for AppConfig service

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/assets.json
- sdk/storage/storage-blob/review/storage-blob.api.md
- sdk/storage/storage-blob/src/Clients.ts
- sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
> [Storage] Add CPK support in uploadStream function

- common/tools/eslint-plugin-azure-sdk/src/configs/markdown-customized.ts
> [eslint-plugin] ignore *.api.md files from linting

- sdk/apimanagement/api-management-custom-widgets-scaffolder/tsconfig.json
- sdk/formrecognizer/ai-form-recognizer/src/documentAnalysisClient.ts
- sdk/search/search-documents/tsconfig.json
This is the result of `rush format`, correcting several formatting issues
introduced in the last NO_CI commit.
> [EngSys] fix formatting

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> [Storage]Bump SDK versions for STG95 GA

- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/package.json
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
- sdk/eventgrid/eventgrid/src/generated/models/index.ts
- sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
- sdk/eventgrid/eventgrid/src/tracing.ts
- sdk/eventgrid/eventgrid/swagger/README.md
NA
This PR consists of the following changes:
- A new property `tierToColdSummary` is added to the `StorageLifecyclePolicyCompletedEventData` interface.
- https://github.com/Azure/azure-sdk-for-js/pull/28176 (This is the PR that adds similar events to the SDK in the 5.1.0 release)
- https://github.com/Azure/azure-sdk-for-js/pull/28513 (This is the PR that adds similar events to the SDK in the 5.2.0 release)
- https://github.com/Azure/azure-sdk-for-js/pull/28891 (This is the PR that adds similar events …
> [@azure/eventgrid] Update System events for EG Version 5.7.0 

- sdk/storage/storage-file-share/swagger/README.md
> [Storage]Update file swagger spec to a commit on main

- sdk/identity/identity/samples/AzureIdentityExamples.md
> [identity] document various user-assigned managed identities

- sdk/openai/openai/test/public/utils/setup.ts
Fix the failing browser issue in injecting Azure Log Level
> [OpenAI] Set up logging for browser

- sdk/template/template/package.json
> [template] skip samples execution temporarily

- sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts
> [Monitor OpenTelemetry Exporter] Fix issue with Log attribute serialization

- eng/pipelines/aggregate-reports.yml
Remove pipeline step of copying that file
> [EngSyS] react to unused InterdependencyGraph.html being removed from eng/common

- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-tracing/package.json
> [core] Prepare core-tracing for release

- sdk/core/core-xml/CHANGELOG.md
- update version and date in CHANGELOG
> [core-xml] prepare for 2024 October release

- sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
- sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
> [instrumentation] Prepare OTel instrumentation for October release

- common/tools/dev-tool/src/commands/admin/migrate-package.ts
Fixes newline character to use `\n` in windows as well as other OS's
> [dev-tool] newline fix

- common/tools/dev-tool/README.md
Just update the readme to specify dev-tool uses tsx instead of ts-node now
> [dev-tool] Update readme

- sdk/core/core-client-rest/CHANGELOG.md
Use Core release date for this package instead of all package release date
> [core-client-rest] Update release date

- common/config/rush/pnpm-lock.yaml
- common/tools/dev-tool/src/commands/admin/migrate-package.ts
- sdk/template/template/assets.json
- sdk/template/template/package.json
- sdk/template/template/test/internal/basic.spec.ts
- sdk/template/template/test/public/configurationClient.spec.ts
- @azure/template
Adds `supportsTracing` back to the template project.
> [template] Add supportsTracing back

- sdk/communication/communication-sms/tests.int.yml
- sdk/communication/communication-sms/tests.yml
Split tests for Public and INT environments
Int pipeline is not stable. Splitting public and int tests until we find solution.
> [communication]-[sms]-Split tests for Public and INT environments

- sdk/monitor/monitor-opentelemetry/README.md
> [Monitor OpenTelemetry] Add Link to Official Docs to Browser SDK Loader Docs

- common/config/rush/pnpm-lock.yaml
- common/tools/dev-tool/package.json
Resolves #31321
Nothing in [breaking changes](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/breaking-changes.md) that should impact us
> [dev-tool] Upgrade ts-morph to 24.x

- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/src/index.ts
> [Monitor OpenTelemetry] Fix Log Record Processor Warning

- sdk/core/core-client-rest/CHANGELOG.md
Preparing for out of band patch release to fix regression (#31349).
> [core-client-rest] Prepare patch release

- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/package.json
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
- sdk/eventgrid/eventgrid/src/generated/models/index.ts
- sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
- sdk/eventgrid/eventgrid/src/tracing.ts
- sdk/eventgrid/eventgrid/swagger/README.md
NA
This PR consists of the following changes:
- A new property `onBehalfOfCallee` is added to the `AcsIncomingCallEventData` interface.
- The property `serializedName` has been removed from `MediaJobOutputProgressEventData` & `MediaJobScheduledEventData` models.
- https://github.com/Azure/azure-sdk-for-js/pull/28513 (This is the PR that adds similar events to the SDK in the 5.2.0 release)
- https://github.com/Azure/azure-sdk-for-js/pull/28891 (This is the PR that adds similar events to the SDK in the …
> [@azure/eventgrid] Update System events for EG Version 5.8.0

- sdk/eventhub/eventhubs-checkpointstore-table/test/public/tables-checkpointstore.spec.ts
- sdk/eventhub/eventhubs-checkpointstore-table/test/util/testUtils.ts
To accommodate GeoDR.
Live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4226755&view=results
> [Event Hubs Checkpoint Tables] Update tests

- sdk/notificationhubs/notification-hubs/CHANGELOG.md
- #30439
- #30697
Releasing fixes for `@azure/notification-hubs` plus new features.
> [notification-hubs] Release 2.0

- sdk/translation/ai-translation-document-rest/test/public/node/documentTranslationTest.spec.ts
tracking issue: https://github.com/Azure/azure-sdk-for-js/issues/31393
> [test][ai-translation-document] skip broken test

- sdk/servicebus/service-bus/tests.yml
now that we have better merged vitest configs
> [ServiceBus] re-enable min/max testing

- .github/CODEOWNERS
Some labels were incorrect due to minor typos, whereas some no longer exist.
> Correct lint issues in CODEOWNERS

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/assets.json
- sdk/storage/storage-blob/review/storage-blob.api.md
- sdk/storage/storage-blob/src/Clients.ts
- sdk/storage/storage-blob/src/ContainerClient.ts
- sdk/storage/storage-blob/src/generated/src/models/index.ts
- sdk/storage/storage-blob/src/generated/src/models/parameters.ts
- sdk/storage/storage-blob/src/generated/src/operations/blob.ts
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-blob/test/blobclient.spec.ts
- sdk/storage/storage-blob/test/node/sas.spec.ts
- sdk/storage/storage-blob/test/utils/index.ts
- sdk/storage/storage-blob/test/utils/testutils.common.ts
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/assets.json
- sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
- sdk/storage/storage-file-datalake/src/DataLakeFileSystemClient.ts
- sdk/storage/storage-file-datalake/src/clients.ts
- sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-datalake/test/node/sas.spec.ts
- sdk/storage/storage-file-datalake/test/utils/index.ts
- sdk/storage/storage-file-datalake/test/utils/testutils.common.ts
> STG96 blob and datalake

- common/config/rush/pnpm-lock.yaml
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
> [Storage]Bump package version for STG96 features preview

- eng/scripts/Generate-APIView-CodeFile.ps1
> Update JS parser version

- sdk/openai/openai/tests.yml
> [OpenAI] Edit tests.yml

- eng/scripts/Generate-APIView-CodeFile.ps1
Update API parser version to 2.0.0 to rebuild reviews with include a bug fix about context end
> Update API view parser to 2.0.2

- common/config/rush/pnpm-lock.yaml
- sdk/monitor/monitor-opentelemetry-exporter/package.json
- sdk/monitor/monitor-opentelemetry/package.json
- @azure/monitor-opentelemetry-exporter
- @azure/monitor-opentelemetry
- #31391
Updates to latest packages
> [monitor] update to latest OTEL

- .github/CODEOWNERS
Address remaining CODEOWNERS issues - for areas with no good owners I have removed them, same with folks who I contacted to set themselves public but did not respond.
> Fix lint issues in CODEOWNERS

- sdk/playwrighttesting/microsoft-playwright-testing/src/common/environmentVariables.ts
> fix(playwrighttesting): removing duplicate runId from env

- sdk/vision/ai-vision-image-analysis-rest/CHANGELOG.md
- sdk/vision/ai-vision-image-analysis-rest/README.md
- sdk/vision/ai-vision-image-analysis-rest/package.json
- sdk/vision/ai-vision-image-analysis-rest/src/imageAnalysisClient.ts
@azure-rest/ai-vision-image-analysis
N/A
Stable Release
No changes.
> Prep for stable release.

- sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/serviceClient.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/utils.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/utils.spec.ts
> fix(playwrighttesting):escape config parameters

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/review/identity.api.md
- sdk/identity/identity/src/credentials/azureCliCredential.ts
- sdk/identity/identity/src/credentials/azureCliCredentialOptions.ts
- sdk/identity/identity/src/util/subscriptionUtils.ts
- sdk/identity/identity/test/internal/node/azureCliCredential.spec.ts
Closes #27781
Add subscription property for AzureCliCredentialOptions
> [Identity] Add subscription property for AzureCliCredentialOptions

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting): CHANGELOG for 1.0.0-beta.4 release for microsoft-playwright-testing

- sdk/ai/ai-inference-rest/README.md
- sdk/ai/ai-inference-rest/samples-dev/chatCompletions.ts
- sdk/ai/ai-inference-rest/samples-dev/embeddings.ts
- sdk/ai/ai-inference-rest/samples-dev/getModelInfo.ts
- sdk/ai/ai-inference-rest/samples-dev/imageFileCompletions.ts
- sdk/ai/ai-inference-rest/samples-dev/streamChatCompletions.ts
- sdk/ai/ai-inference-rest/samples-dev/streamingToolCall.ts
- sdk/ai/ai-inference-rest/samples-dev/telemetry.ts
- sdk/ai/ai-inference-rest/samples-dev/telemetryWithToolCall.ts
- sdk/ai/ai-inference-rest/samples-dev/toolCall.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/chatCompletions.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/embeddings.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/getModelInfo.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/imageFileCompletions.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/streamChatCompletions.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/streamingToolCall.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/telemetry.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/telemetryWithToolCall.js
- sdk/ai/ai-inference-rest/samples/v1-beta/javascript/toolCall.js
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/chatCompletions.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/embeddings.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/getModelInfo.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/imageFileCompletions.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/streamChatCompletions.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/streamingToolCall.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/telemetry.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/telemetryWithToolCall.ts
- sdk/ai/ai-inference-rest/samples/v1-beta/typescript/src/toolCall.ts
No code changes.   Only sample and readme
Sample has scope incorrect for connection
Sample has scope incorrect for connection
> Fixed scope in samples and readme

- sdk/core/ts-http-runtime/review/azure-core-comparison.diff
- sdk/core/ts-http-runtime/review/ts-http-runtime.api.md
- sdk/core/ts-http-runtime/src/auth/tokenCredential.ts
- sdk/core/ts-http-runtime/src/client/common.ts
- sdk/core/ts-http-runtime/src/client/getClient.ts
- sdk/core/ts-http-runtime/src/client/sendRequest.ts
- sdk/core/ts-http-runtime/src/client/urlHelpers.ts
- sdk/core/ts-http-runtime/src/fetchHttpClient.ts
- sdk/core/ts-http-runtime/src/interfaces.ts
- sdk/core/ts-http-runtime/src/nodeHttpClient.ts
- sdk/core/ts-http-runtime/src/policies/formDataPolicy.ts
- sdk/core/ts-http-runtime/src/policies/multipartPolicy.ts
- sdk/core/ts-http-runtime/src/policies/proxyPolicy.ts
- sdk/core/ts-http-runtime/src/policies/tracingPolicy.ts
- sdk/core/ts-http-runtime/src/retryStrategies/throttlingRetryStrategy.ts
- sdk/core/ts-http-runtime/src/util/checkEnvironment.ts
- sdk/core/ts-http-runtime/src/util/sanitizer.ts
- sdk/core/ts-http-runtime/src/util/tokenCycler.ts
- sdk/core/ts-http-runtime/src/util/uuidUtils.common.ts
- sdk/core/ts-http-runtime/src/util/uuidUtils.ts
Updating the unbranded Core package with some recent changes in Core that didn't make it over.
To review, you can look at the `azure-core-comparison.diff` report. Notice that the diff between the Azure packages and the unbranded package has gotten smaller as a result of this PR. Where there are meaningful behavioral differences between the Azure core and the unbranded core, I've tried to add comments to the unbranded package explaining the change. These comments show up in the diff report and will hopefully help explain most meaningful differences. Unfortunately, the diff report is still a bit noisy with expected changes, e.g. changes to imports, and interpreting a diff of a diff is confusing (at least, I find it tricky!). When confused, I have found looking …
> [ts-http-runtime] Update ts-http-runtime with recent Core changes

- sdk/ai/ai-inference-rest/CHANGELOG.md
- sdk/ai/ai-inference-rest/package.json
- sdk/ai/ai-inference-rest/src/constants.ts
update change log
update change log
> update change log

- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/package.json
N/A
N/A
Release Azure Communication Chat Version 1.5.3
N/A
N/A
> Release Azure Communication Chat Version 1.5.3

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
- sdk/monitor/monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/liveMetrics.test.ts
> [Monitor OpenTelemetry] Support Parsing AAD Audience from Connection String

- common/config/rush/pnpm-lock.yaml
- sdk/computeschedule/arm-computeschedule/package.json
- sdk/containerinstance/arm-containerinstance/package.json
- sdk/containerservice/arm-containerservice/package.json
- sdk/fabric/arm-fabric/package.json
- sdk/hybridcompute/arm-hybridcompute/package.json
- sdk/mongocluster/arm-mongocluster/samples/v1/typescript/package.json
- sdk/notificationhubs/notification-hubs/package.json
- sdk/servicefabricmanagedclusters/arm-servicefabricmanagedclusters/package.json
- sdk/servicenetworking/arm-servicenetworking/samples/v1-beta/typescript/package.json
- sdk/template/template/package.json
Upgrade typescript version to `5.6.2`.
> Upgrade typescipt version

- eng/scripts/Generate-APIView-CodeFile.ps1
Update JS APIView parser to 2.0.3
> Update JS parser version to 2.0.3

- .github/CODEOWNERS
> [codeowners] Add Minh-Anh to identity

- sdk/ai/azure-ai-projects/src/agents/files.ts
- sdk/ai/azure-ai-projects/src/agents/index.ts
- sdk/ai/azure-ai-projects/src/agents/messages.ts
- sdk/ai/azure-ai-projects/src/agents/runs.ts
- sdk/ai/azure-ai-projects/src/agents/threads.ts
> JS SDK code for agents files, threads, runs, messages

- sdk/eventhub/event-hubs/samples-express/package.json
- sdk/eventhub/event-hubs/samples-express/src/asyncBatchingProducer.ts
- sdk/eventhub/event-hubs/samples/v5/express/package.json
- sdk/eventhub/event-hubs/samples/v5/express/src/asyncBatchingProducer.ts
- sdk/eventhub/event-hubs/samples/v5/javascript/README.md
- sdk/eventhub/event-hubs/samples/v5/javascript/iothubConnectionString.js
- sdk/eventhub/event-hubs/samples/v5/javascript/iothubConnectionStringWebsockets.js
- sdk/eventhub/event-hubs/samples/v5/javascript/package.json
- sdk/eventhub/event-hubs/samples/v5/javascript/sample.env
- sdk/eventhub/event-hubs/samples/v5/typescript/README.md
- sdk/eventhub/event-hubs/samples/v5/typescript/package.json
- sdk/eventhub/event-hubs/samples/v5/typescript/sample.env
- sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionString.ts
- sdk/eventhub/event-hubs/samples/v5/typescript/src/iothubConnectionStringWebsockets.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/31571
> [Event Hubs] Fix sample

- common/config/rush/pnpm-lock.yaml
- sdk/face/ai-vision-face-rest/CHANGELOG.md
- sdk/face/ai-vision-face-rest/LICENSE
- sdk/face/ai-vision-face-rest/assets.json
- sdk/face/ai-vision-face-rest/package.json
- sdk/face/ai-vision-face-rest/review/ai-vision-face.api.md
- sdk/face/ai-vision-face-rest/src/clientDefinitions.ts
- sdk/face/ai-vision-face-rest/src/faceClient.ts
- sdk/face/ai-vision-face-rest/src/isUnexpected.ts
- sdk/face/ai-vision-face-rest/src/models.ts
- sdk/face/ai-vision-face-rest/src/outputModels.ts
- sdk/face/ai-vision-face-rest/src/parameters.ts
- sdk/face/ai-vision-face-rest/src/pollingHelper.ts
- sdk/face/ai-vision-face-rest/src/responses.ts
- sdk/face/ai-vision-face-rest/tsconfig.json
- sdk/face/ai-vision-face-rest/tsp-location.yaml
- sdk/face/ai-vision-face-rest/vitest.browser.config.ts
- sdk/face/ai-vision-face-rest/vitest.config.ts
@azure-rest/ai-vision-face
To support the latest Azure AI Face v1.2-preview.1 API.
> [@azure-rest/ai-vision-face] Update to v1.2-preview.1

- sdk/ai/ai-inference-rest/README.md
> Updated readme for inference

- .vscode/cspell.json
- sdk/web-pubsub/web-pubsub/CHANGELOG.md
- sdk/web-pubsub/web-pubsub/assets.json
- sdk/web-pubsub/web-pubsub/review/web-pubsub.api.md
- sdk/web-pubsub/web-pubsub/src/hubClient.ts
- sdk/web-pubsub/web-pubsub/test/hubs.spec.ts
- sdk/web-pubsub/web-pubsub/test/testEnv.ts
- Add SocketIO support for generating Client Access URL
- Add custom sanitizer for test recorder to fix URI mismatched issue
> Add SocketIO support for client access url

- eng/pipelines/templates/steps/build.yml
Fix artifact copying introduced by https://github.com/Azure/azure-sdk-for-js/pull/31420
> Fix artifact location

- .github/CODEOWNERS
None
@pranav-gupta-msft needs to set their membership in the Azure org to public. @wonner needs to follow the steps in https://eng.ms/docs/products/azure-developer-experience/onboard/access to join the Azure GitHub org and mark themselves as public.
> [CODEOWNERS] Remove invalid owners

- eng/tools/rush-runner.js
> Identify a few more packages for --to always

- sdk/appconfiguration/app-configuration/CHANGELOG.md
- sdk/appconfiguration/app-configuration/package.json
- sdk/appconfiguration/app-configuration/review/app-configuration.api.md
- sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
- sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts
- sdk/appconfiguration/app-configuration/src/internal/constants.ts
- sdk/appconfiguration/app-configuration/src/models.ts
- sdk/appconfiguration/app-configuration/swagger/swagger.md
- Update the options bag to include the `apiVersion`
> [App Config] Add ApiVersion in the Options Bag

- eng/guardian-tools/policheck/PolicheckExclusions.xml
> Exclude pnpm lock files in policheck

- sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
Upload buffer and upload file methods weren't awaited and hence sometimes missed resulting in 404 in webapp.
> fix(playwrighttesting): await upload buffer method

- sdk/core/core-rest-pipeline/CHANGELOG.md
Remove entry with no items in Changelog for release
> [Core] Remove entry in changelog

- sdk/translation/ai-translation-document-rest/CHANGELOG.md
- sdk/translation/ai-translation-document-rest/package.json
> GA release prep

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/agents/customModels.ts
- sdk/ai/ai-projects/src/agents/index.ts
- sdk/ai/ai-projects/src/agents/inputOutputs.ts
- sdk/ai/ai-projects/src/agents/runModels.ts
- sdk/ai/ai-projects/src/agents/runs.ts
- sdk/ai/ai-projects/test/public/agents/assistants.spec.ts
- sdk/ai/ai-projects/test/public/agents/runs.spec.ts
- sdk/ai/ai-projects/test/public/agents/streaming.spec.ts
Exposes API for Runs, Tests and Samples
`
createRun: (threadId: string, assistantId: string, options?: Omit<CreateRunOptions, "assistant_id">, requestParams?: OptionalRequestParameters) => Promise<ThreadRunOutput>;
getRun: (threadId: string, runId: string, requestParams?: OptionalRequestParameters) => Promise<ThreadRunOutput>;
updateRun: (threadId: string, runId: string, options?: UpdateRunOptions, requestParams?: OptionalRequestParameters) => Promise<ThreadRunOutput>;`
> Run operations

- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
> fix(playwrightTesting):Limiting progressBar update.

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/models/parameters.ts
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> [Storage] Bump version for STG96 GA release

- sdk/playwrighttesting/create-microsoft-playwright-testing/CHANGELOG.md
- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting):  date change in changelog 1.0.0-beta.5 and 1.0.0-beta.2

- sdk/tables/data-tables/CHANGELOG.md
Preparing release for Cosmos Entra ID support. This functionality has been validated by a partner team against the most recent nightly build.
> [data-tables] Update changelog for release

- sdk/cosmosdb/cosmos/CHANGELOG.md
@azure/cosmos
Update changeLog for release.
N/A
> [@azure/cosmos] Update CHANGELOG.md

- sdk/ai/ai-projects/package.json
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agents_basics.ts
- sdk/ai/ai-projects/samples-dev/agents/agents_function.ts
- sdk/ai/ai-projects/samples-dev/agents/messages.ts
- sdk/ai/ai-projects/samples-dev/agents/streaming.ts
- sdk/ai/ai-projects/src/agents/index.ts
- sdk/ai/ai-projects/src/agents/inputOutputs.ts
- sdk/ai/ai-projects/src/agents/runs.ts
- sdk/ai/ai-projects/src/agents/streaming.ts
- sdk/ai/ai-projects/src/agents/streamingModels.ts
- sdk/ai/ai-projects/src/agents/utils.ts
- sdk/ai/ai-projects/test/public/agents/functionTool.spec.ts
- sdk/ai/ai-projects/test/public/agents/streaming.spec.ts
Add samples for Agent functions
Updated streaming support for submitToolOutputsToRunStreaming
> Update submitToolOutputs and Run agent with functions

- sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
- sdk/web-pubsub/web-pubsub/assets.json
- sdk/web-pubsub/web-pubsub/src/hubClient.ts
- sdk/web-pubsub/web-pubsub/test.env
- sdk/web-pubsub/web-pubsub/test/hubs.spec.ts
- sdk/web-pubsub/web-pubsub/test/testEnv.ts
- sdk/web-pubsub/web-pubsub/test/testUtils.ts
- Add a test util to parse JWT token payload to validate audience
- Add more tests for AAD
- Fix mismatched DTO field when calling generateClientToken
> Fix client type issues and improve tests

- sdk/ai/ai-projects/test/public/agents/files.spec.ts
removing getFileContent test to match sample
> Update file tests

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/agents/index.ts
- sdk/ai/ai-projects/src/generated/src/models.ts
- sdk/ai/ai-projects/src/generated/src/outputModels.ts
- sdk/ai/ai-projects/src/generated/src/parameters.ts
- sdk/ai/ai-projects/tsp-location.yaml
Update with latest codgen from ai-projects typespec
> Latest codegen from typespec

- sdk/ai/ai-projects/sample_file_for_upload.txt
- sdk/ai/ai-projects/samples-dev/agents/file_search.ts
- sdk/ai/ai-projects/samples-dev/agents/sample_file_for_upload.txt
> Adding file search sample

- sdk/apimanagement/arm-apimanagement/CHANGELOG.md
- sdk/apimanagement/arm-apimanagement/assets.json
- sdk/apimanagement/arm-apimanagement/package.json
- sdk/apimanagement/arm-apimanagement/src/apiManagementClient.ts
- sdk/apimanagement/arm-apimanagement/src/operations/apiPolicy.ts
https://github.com/Azure/azure-sdk-for-js/issues/31566
> [mgmt] apimanagement

- sdk/appconfiguration/app-configuration/vitest.browser.config.ts
Increase timeout for LRO test for better test reliability
Live test run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4362875&view=results
#31891
> [App Config] Test timeout increase for browser LRO test

- sdk/loadtesting/load-testing-rest/CHANGELOG.md
- sdk/loadtesting/load-testing-rest/src/getFileValidationPoller.ts
Adding NOT_VALIDATED state to the list of terminal states of file validation poller
> [Azure Load Testing] Add NOT_VALIDATED to list of terminal states

- sdk/ai/ai-projects/assets.json
- sdk/ai/ai-projects/src/agents/index.ts
Fixing bug and updating test assets
> Fixing listFiles bug

- common/tools/dev-tool/src/commands/run/extract-api.ts
PR #31720 incorrectly assumed that packages with an "exports" field were managed by tshy, and thus the dts rollup options were omitted. However, not all packages with "exports" are tshy-managed. Since PR #31720 removed subpath's dts rollup options instead of disabling rollup, as a result, api-extractor performed rollups but using the same dts roll options (from api-extractor.json) for all subpaths, causing an overwrite of the rollup for default export by the last export's rollup.
This PR adds a check for tshy usage. If tshy is used, dts rollup is disabled, otherwise the original rollup behavior is kept.
> [dev-tool] check for tshy usage when extracting api

- common/scripts/install-run-rush.js
- common/scripts/install-run.js
- rush.json
This addresses security issue of jsonpath-plus 4.0.0
> [EngSys] upgrade @microsoft/rush to version 5.141.1

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
> docs(playwrighttesting): CHANGELOG for core package 1.0.0-beta.6 release

- sdk/ai/ai-inference-rest/README.md
it is failing aggregate-reports pipeline.
Resolves #31842
> [doc][ai-inference] fix broken link in README

- common/config/rush/pnpm-lock.yaml
- sdk/core/perf-tests/core-rest-pipeline/package.json
> [EygSys] upgrade dev dependency `undici` version to ^7.0.0

- sdk/core/core-rest-pipeline/src/util/file.ts
- sdk/core/ts-http-runtime/review/azure-core-comparison.diff
- sdk/core/ts-http-runtime/src/util/file.ts
to prepare for TypeScript 5.7's update to lib.dom.d.ts
https://github.com/microsoft/TypeScript/pull/60061/files#diff-dc0eab937d15e62545da3ed7b4f40ad6b24f15dd88fbc6ceda2bfb4ed8356eb0R3424
> [core] add `bytes` to unimplemented File methods

- sdk/identity/identity/package.json
**Summary of changes**
- Update required resource docs links
- Update product slugs per https://review.learn.microsoft.com/help/platform/metadata-taxonomies/product?branch=main
- Replace Azure AD keyword to reflect new product branding
> Update package.json for Azure Identity library

- sdk/eventhub/event-hubs/eslint.config.mjs
- sdk/eventhub/event-hubs/package.json
- sdk/eventhub/event-hubs/tsconfig.browser.config.json
- sdk/eventhub/event-hubs/tsconfig.json
- sdk/eventhub/event-hubs/tsconfig.samples.json
- sdk/eventhub/event-hubs/tsconfig.src.json
- sdk/eventhub/event-hubs/tsconfig.tests.json
- sdk/eventhub/event-hubs/vitest.browser.config.ts
- sdk/eventhub/event-hubs/vitest.config.ts
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4385850&view=results
> [Event Hubs] Precise Typechecking

- common/config/rush/pnpm-lock.yaml
- common/tools/dev-tool/package.json
for https://github.com/Azure/azure-sdk-for-js/issues/29498
> [EngSys] upgrade `strip-json-comments` version to ^5.0.1

- common/config/rush/pnpm-lock.yaml
to add new dev dependency autorest for quantum-jobs
> [engsys] rush update

- sdk/search/search-documents/samples-dev/setup.ts
- sdk/search/search-documents/samples/v12-beta/javascript/setup.js
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderAutoFlushSize.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderAutoFlushTimer.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/bufferedSenderManualFlush.ts
- sdk/search/search-documents/samples/v12-beta/typescript/src/setup.ts
Fixes [#30926](https://github.com/Azure/azure-sdk-for-js/issues/30926)
@joheredi, @dgetu for notification.
> Fix Azure AI Search Sample Issue

- sdk/quantum/quantum-jobs/review/quantum-jobs.api.md
- @azure/quantum-jobs
Updates the API View which was incorrect as per the last PR.
> [quantum jobs] Fix the API View for @azure/quantum-jobs

- sdk/eventhub/event-hubs/TROUBLESHOOTING.md
"name" field was mentioned twice. Remove duplicate.
> [EventHubs] Update TROUBLESHOOTING.md

- sdk/anomalydetector/ai-anomaly-detector-rest/eslint.config.mjs
- sdk/anomalydetector/ai-anomaly-detector-rest/package.json
- sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.browser.config.json
- sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.json
- sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.samples.json
- sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.src.json
- sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.test.json
- sdk/anomalydetector/ai-anomaly-detector-rest/vitest.config.ts
- sdk/anomalydetector/ai-anomaly-detector-rest/vitest.esm.config.ts
- @azure-rest/ai-anomaly-detector
N/A
N/A
> [anomalydetector] Precise Typechecking

- sdk/agrifood/agrifood-farming-rest/eslint.config.mjs
- sdk/agrifood/agrifood-farming-rest/package.json
- sdk/agrifood/agrifood-farming-rest/tsconfig.browser.config.json
- sdk/agrifood/agrifood-farming-rest/tsconfig.json
- sdk/agrifood/agrifood-farming-rest/tsconfig.samples.json
- sdk/agrifood/agrifood-farming-rest/tsconfig.src.json
- sdk/agrifood/agrifood-farming-rest/tsconfig.test.json
- sdk/agrifood/agrifood-farming-rest/vitest.config.ts
- sdk/agrifood/agrifood-farming-rest/vitest.esm.config.ts
- @azure-rest/agrifood-farming
N/A
N/A
> [agrifood] Precise Typechecking

- sdk/schemaregistry/schema-registry-json/vitest.esm.config.ts
The vitest file was missing and it is needed to run the tests.
> [schemaregistry json] Fix esm tests

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agents_bing_grounding_streaming.ts
- sdk/ai/ai-projects/samples-dev/agents/code_interpreter_streaming.ts
- sdk/ai/ai-projects/samples-dev/agents/streaming.ts
- sdk/ai/ai-projects/src/agents/customModels.ts
- sdk/ai/ai-projects/src/agents/index.ts
- sdk/ai/ai-projects/src/agents/runs.ts
- sdk/ai/ai-projects/test/public/agents/streaming.spec.ts
Expose stream respose to createRun and createThreadAndRun api
> update-stream for createRun and createThreadAndRun

- sdk/ai/ci.yml
> Add AI Projects to AI ci pipeline

- sdk/keyvault/test-resources.bicep
@azure/keyvault-*
N/A - nightly test failures
We do not create a managed identity in non HSM deployments as its not needed. We
need to do the same conditional check for role assignments here.
> [keyvault] Fix non-HSM deploys

- .github/CODEOWNERS
> Update CODEOWNERS for Health Deidentification

- sdk/monitor/monitor-opentelemetry-exporter/package.json
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/log.test.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/metric.test.ts
- sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/trace.test.ts
- sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standardMetrics.test.ts
#32101 
Integration tests were failing as the flush was not completing.
> [Monitor OpenTelemetry Exporter] Fix Integration Tests Flush

- sdk/ai/ai-projects/assets.json
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/agents/customModels.ts
- sdk/ai/ai-projects/src/agents/index.ts
- sdk/ai/ai-projects/src/agents/inputOutputs.ts
- sdk/ai/ai-projects/src/agents/inputValidations.ts
- sdk/ai/ai-projects/src/agents/runTrace.ts
- sdk/ai/ai-projects/src/agents/runs.ts
- sdk/ai/ai-projects/src/agents/streamingModels.ts
- sdk/ai/ai-projects/src/customization/convertModelsToWrite.ts
- sdk/ai/ai-projects/src/customization/convertOutputModelsFromWire.ts
- sdk/ai/ai-projects/src/customization/models.ts
- sdk/ai/ai-projects/src/customization/outputModels.ts
- sdk/ai/ai-projects/test/public/agents/files.spec.ts
- sdk/ai/ai-projects/test/public/agents/functionTool.spec.ts
- sdk/ai/ai-projects/test/public/agents/runs.spec.ts
- sdk/ai/ai-projects/test/public/agents/streaming.spec.ts
- sdk/ai/ai-projects/test/public/agents/tracing.spec.ts
- sdk/ai/ai-projects/test/public/utils/createClient.ts
> Refactor Agents Run api addressing feedback

- sdk/documentintelligence/ai-document-intelligence-rest/MIGRATION-FR_v4-DI_v1.md
> [Document Intelligence] fix link

- common/config/rush/pnpm-lock.yaml
- sdk/notificationhubs/arm-notificationhubs/package.json
- sdk/notificationhubs/arm-notificationhubs/test/notificationhubs.spec.ts
- sdk/notificationhubs/arm-notificationhubs/tsconfig.browser.config.json
- sdk/notificationhubs/arm-notificationhubs/tsconfig.json
- sdk/notificationhubs/arm-notificationhubs/tsconfig.samples.json
- sdk/notificationhubs/arm-notificationhubs/tsconfig.src.json
- sdk/notificationhubs/arm-notificationhubs/tsconfig.test.json
- sdk/notificationhubs/arm-notificationhubs/vitest.config.ts
- sdk/notificationhubs/arm-notificationhubs/vitest.esm.config.ts
Fixes failure in https://dev.azure.com/azure-sdk/public/_build/results?buildId=4415385&view=logs&jobId=2993fb17-9fe5-5b0b-e997-efa0cab8f900&j=2993fb17-9fe5-5b0b-e997-efa0cab8f900&t=dd1086b5-315c-5d00-e372-83915904aafa
> [notificationhubs] Fix tests typechecking

- sdk/ai/ai-projects/src/agents/assistants.ts
- sdk/ai/ai-projects/src/agents/files.ts
- sdk/ai/ai-projects/src/agents/messages.ts
- sdk/ai/ai-projects/src/agents/openAIError.ts
- sdk/ai/ai-projects/src/agents/runSteps.ts
- sdk/ai/ai-projects/src/agents/runs.ts
- sdk/ai/ai-projects/src/agents/streaming.ts
- sdk/ai/ai-projects/src/agents/threads.ts
- sdk/ai/ai-projects/src/agents/vectorStores.ts
- sdk/ai/ai-projects/src/agents/vectorStoresFileBatches.ts
- sdk/ai/ai-projects/src/agents/vectorStoresFiles.ts
- sdk/ai/ai-projects/src/customization/convertModelsToWrite.ts
- sdk/ai/ai-projects/src/customization/convertOutputModelsFromWire.ts
- sdk/ai/ai-projects/test/public/agents/functionTool.spec.ts
- sdk/ai/ai-projects/test/public/agents/runs.spec.ts
Improve error management by replacing the existing error handling with the OpenAIError class, ensuring better clarity and consistency in error reporting. Additionally, address an issue related to setting required actions on ThreadRunOutput.
> Refactor error handling with OpenAIError class

- .github/CODEOWNERS
Adding new codeowner for ACS CallAutomation
> [ACS][CallAutomation] Adding codeowner section for ACS CallAutomation

- sdk/communication/communication-call-automation/assets.json
- sdk/communication/communication-call-automation/package.json
- sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Add_a_participant_and_get_call_properties.json
- sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Add_a_participant_cancels_add_participant_request.json
- sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_List_all_participants.json
- sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Mute_a_participant.json
- sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Remove_a_participant.json
- sdk/communication/communication-call-automation/recordings/CallRecording_Live_Tests_Creates_a_call,_start_recording,_and_hangs_up.json
- sdk/communication/communication-call-automation/recordings/Call_Automation_Main_Client_Live_Tests_Create_a_call_and_hangup.json
- sdk/communication/communication-call-automation/recordings/Call_Automation_Main_Client_Live_Tests_Reject_call.json
- sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Cancel_all_media_operations.json
- sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Play_audio_to_all_participants.json
- sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Play_audio_to_target_participant.json
- sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Trigger_DTMF_actions.json
- sdk/communication/communication-call-automation/test/node/callMediaClient.spec.ts
- sdk/communication/communication-call-automation/test/utils/recordedClient.ts
Live Test Updated for CallAutomation + Recorded
- LocalAuth disabled for ServiceBus
- PhoneNumber test now randomized to avoid duplicated tests
- Various Bug Fixes
- more redaction added
> [ACS][CallAutomation] Live Test Updated V2

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/agents/inputOutputs.ts
- sdk/ai/ai-projects/src/agents/streaming.ts
- sdk/ai/ai-projects/src/agents/streamingModels.ts
- sdk/ai/ai-projects/src/customization/convertOutputModelsFromWire.ts
- sdk/ai/ai-projects/src/customization/streamingModels.ts
- sdk/ai/ai-projects/src/customization/streamingWireModels.ts
Enhance the streaming event model by returning public models and refining error handling mechanisms. This update improves the robustness of event data processing.
> Refactor event data handling and improve error management

- sdk/communication/communication-sms/CHANGELOG.md
- sdk/communication/communication-sms/assets.json
- sdk/communication/communication-sms/samples/v1/typescript/README.md
- sdk/communication/communication-sms/samples/v1/typescript/src/optOutAdd.ts
- sdk/communication/communication-sms/samples/v1/typescript/src/optOutCheck.ts
- sdk/communication/communication-sms/samples/v1/typescript/src/optOutRemove.ts
- sdk/communication/communication-sms/samples/v1/typescript/src/sendSms.ts
- sdk/communication/communication-sms/src/optOutsClient.ts
communication-sms
Fix the error in optOut.remove method
> [communication]-[sms] Fix opt out remove action

- sdk/eventhub/event-hubs/test/internal/node/partitionKeyHashMap.spec.ts
> [Event Hubs] Fix type

- sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
> fix(playwrighttesting): handling OS name and browser name

- .scripts/automation_init.sh
N/A
N/A
Fix tsp-client version in SDK automation
N/A
N/A
N/A
N/A
> Update @azure-tools/typespec-client-generator-cli version for tsp-client

- .github/CODEOWNERS
- sdk/communication/communication-email/CHANGELOG.md
- sdk/communication/communication-email/README.md
N/A
N/A
The "Inline Images" example was missing from the most recent release of our SDK.
N/A
N/A - readme only
> Adding inline image example to readme

- sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts
> refactor(playwrighttesting): fix error pattern in scalable

- sdk/cosmosdb/cosmos/src/common/platform.ts
> Minor change in userAgentDetails() function

- common/config/rush/pnpm-lock.yaml
- sdk/ai/ai-projects/assets.json
- sdk/ai/ai-projects/eslint.config.mjs
- sdk/ai/ai-projects/package.json
- sdk/ai/ai-projects/tsconfig.browser.config.json
- sdk/ai/ai-projects/tsconfig.json
- sdk/ai/ai-projects/tsconfig.samples.json
- sdk/ai/ai-projects/tsconfig.src.json
- sdk/ai/ai-projects/tsconfig.test.json
- sdk/ai/ai-projects/vitest.browser.config.ts
- sdk/ai/ai-projects/vitest.config.ts
- sdk/ai/ai-projects/vitest.esm.config.ts
> Add TypeScript configuration files and update assets for ai-projects

- sdk/communication/communication-sms/assets.json
- sdk/communication/communication-sms/test/internal/smsClient.internal.spec.ts
- sdk/communication/communication-sms/test/public/smsClient.spec.ts
> [Communication][SMS] Add Tests and samples

- sdk/communication/communication-sms/assets.json
- sdk/communication/communication-sms/test/internal/smsClient.internal.spec.ts
- sdk/communication/communication-sms/test/public/smsClient.spec.ts
SMS
https://github.com/Azure/azure-sdk-for-js/issues/32393
Fix the tests and upload recordings
> [Communication][SMS] Fix test, update recordings

- sdk/communication/communication-sms/README.md
- sdk/communication/communication-sms/samples/v1/javascript/README.md
- sdk/communication/communication-sms/samples/v1/javascript/optOutAdd.js
- sdk/communication/communication-sms/samples/v1/javascript/optOutCheck.js
- sdk/communication/communication-sms/samples/v1/javascript/optOutRemove.js
- sdk/communication/communication-sms/samples/v1/typescript/src/optOutRemove.ts
Add missing JS samples, update README
> [Communication][SMS] Add javascript samples and update readme

- sdk/advisor/arm-advisor/README.md
- sdk/advisor/arm-advisor/package.json
- sdk/advisor/arm-advisor/test/snippets.spec.ts
- @azure/arm-advisor
- #32416
Adds snippets for the README which are type checked.
> [advisor] Update @azure/arm-advisor to use snippets

- sdk/monitor/monitor-query/samples/v1/javascript/README.md
- sdk/monitor/monitor-query/samples/v1/javascript/logsQuery.js
- sdk/monitor/monitor-query/samples/v1/javascript/logsQueryBatch.js
- sdk/monitor/monitor-query/samples/v1/javascript/logsQueryMultipleWorkspaces.js
- sdk/monitor/monitor-query/samples/v1/javascript/logsResourceCentricQuery.js
- sdk/monitor/monitor-query/samples/v1/javascript/metricsQuery.js
- sdk/monitor/monitor-query/samples/v1/javascript/package.json
- sdk/monitor/monitor-query/samples/v1/typescript/README.md
- sdk/monitor/monitor-query/samples/v1/typescript/package.json
- sdk/monitor/monitor-query/samples/v1/typescript/src/logsQuery.ts
- sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryBatch.ts
- sdk/monitor/monitor-query/samples/v1/typescript/src/logsQueryMultipleWorkspaces.ts
- sdk/monitor/monitor-query/samples/v1/typescript/src/logsResourceCentricQuery.ts
- sdk/monitor/monitor-query/samples/v1/typescript/src/metricsQuery.ts
- sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts
`@azure/monitor-query`
https://github.com/Azure/azure-sdk-for-js/issues/32413
An issue https://github.com/Azure/azure-sdk-for-js/issues/32413 has been created to address the live tests pipeline failure for Monitor Query SDK. On analysis, I have found that there is only one test failing in the pipeline i.e. `LogsQueryClient live tests - server timeout` in `logsQueryClient.spec.ts` file. 
Now, if I look into this test, here is the logic:
1. Execute a query `range x from 1 to ${randomLimit} step 1 | count` with the `serverTimeoutInSeconds` set to 1. 
2. This query is supposed to encounter a timeout error and be thrown. (If you look at the recordings in playback mode, you can confirm that the error is thrown).
3. But, now with the live mode the error is not thrown. As a result, the test is …
> [@azure/monitor-query] Skip failing test in the Monitor Query SDK

- .github/CODEOWNERS
- sdk/tables/data-tables/CHANGELOG.md
Also add me as backup owner for tables
> [Data Tables] prepare for 2025 January release

- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/clInfoProvider.spec.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/reporterUtils.spec.ts
https://github.com/microsoft/playwright-testing-service/issues/158
https://github.com/Azure/azure-sdk-for-js/issues/32394
Add code snippet and location in error message
Yes
**Before**
**After**
> fix(playwrighttesting): attach code snippet in error message

- sdk/attestation/arm-attestation/README.md
- sdk/attestation/arm-attestation/package.json
- sdk/attestation/arm-attestation/test/attestation_examples.spec.ts
- sdk/attestation/arm-attestation/test/snippets.spec.ts
- sdk/attestation/attestation/README.md
- sdk/attestation/attestation/package.json
- sdk/attestation/attestation/samples-dev/attestEnclaves.ts
- sdk/attestation/attestation/samples-dev/createAttestationClient.ts
- sdk/attestation/attestation/samples-dev/getAttestationPolicy.ts
- sdk/attestation/attestation/samples-dev/getPolicyManagementCertificates.ts
- sdk/attestation/attestation/samples-dev/modifyPolicyManagementCertificates.ts
- sdk/attestation/attestation/samples-dev/setAttestationPolicy.ts
- sdk/attestation/attestation/src/attestationAdministrationClient.ts
- sdk/attestation/attestation/src/attestationClient.ts
- sdk/attestation/attestation/test/browser/attestationTests.browser.spec.ts
- sdk/attestation/attestation/test/public/attestationTests.spec.ts
- sdk/attestation/attestation/test/public/attestationTokenTests.spec.ts
- sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts
- sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts
- sdk/attestation/attestation/test/public/tokenCertTests.spec.ts
- sdk/attestation/attestation/test/snippets.spec.ts
- sdk/attestation/attestation/test/utils/cryptoUtils.ts
- sdk/attestation/attestation/vitest.browser.config.ts
- @azure/arm-attestation
- @azure/attestation
Updates all projects under `attestation` to use snippets extraction.
> [attestation] Update attestation projects to snippets extraction

- common/tools/dev-tool/src/util/samples/processor.ts
TypeScript compiler would erase `import type` statements during transpilation to
JavaScript. As a result any comments attached to import type statements are lost
in the generated JavaScript samples. This PR replaces `import type` statements
with empty statements whose comments will not be removed after the
transpilation.
> [dev-tool] preserve comments for import type declarations in JS sample generation

- sdk/automanage/arm-automanage/README.md
- sdk/automanage/arm-automanage/package.json
- sdk/automanage/arm-automanage/test/sampleTest.spec.ts
- sdk/automanage/arm-automanage/test/snippets.spec.ts
- @azure/arm-automanage
Updates all `automanage` packages to use snippets extraction.
> [automanage] Update automanage packages to use snippets extraction

- sdk/azureadexternalidentities/arm-azureadexternalidentities/README.md
- sdk/azureadexternalidentities/arm-azureadexternalidentities/package.json
- sdk/azureadexternalidentities/arm-azureadexternalidentities/test/sampleTest.spec.ts
- sdk/azureadexternalidentities/arm-azureadexternalidentities/test/snippets.spec.ts
- @azure/arm-azureadexternalidentities
Updates `azureadexternalidentities` projects to use snippets extraction.
> [azureadexternalidentities] Update azureadexternalidentities projects to use snippets extraction

- sdk/azurestack/arm-azurestack/README.md
- sdk/azurestack/arm-azurestack/package.json
- sdk/azurestack/arm-azurestack/test/sampleTest.spec.ts
- sdk/azurestack/arm-azurestack/test/snippets.spec.ts
- @azure/arm-azurestack
Update `azurestack` projects to use snippets extraction.
> [azurestack] Update azurestack projects to use snippets extraction

- sdk/azurestackhci/arm-azurestackhci/README.md
- sdk/azurestackhci/arm-azurestackhci/package.json
- sdk/azurestackhci/arm-azurestackhci/test/azurestackhci_operations_test.spec.ts
- sdk/azurestackhci/arm-azurestackhci/test/snippets.spec.ts
- @azure/arm-azurestackhci 
Updates the `azurestackhci` projects to use snippets extraction.
> [azurestackhci] Update azurestackhci projects to use snippets extraction

- sdk/batch/arm-batch/README.md
- sdk/batch/arm-batch/package.json
- sdk/batch/arm-batch/test/batch_examples.spec.ts
- sdk/batch/arm-batch/test/snippets.spec.ts
- sdk/batch/batch-rest/MigrationGuide.md
- sdk/batch/batch-rest/README.md
- sdk/batch/batch-rest/package.json
- sdk/batch/batch-rest/test/computeNodes.spec.ts
- sdk/batch/batch-rest/test/jobs.spec.ts
- sdk/batch/batch-rest/test/poolScaling.spec.ts
- sdk/batch/batch-rest/test/pools.spec.ts
- sdk/batch/batch-rest/test/snippets.spec.ts
- sdk/batch/batch-rest/test/tasks.spec.ts
- @azure/arm-batch
- @azure-rest/batch
Updates the `batch` projects to use snippets extraction.
> [batch] Update batch projects to use snippets extraction

- sdk/billing/arm-billing/README.md
- sdk/billing/arm-billing/package.json
- sdk/billing/arm-billing/test/billing_operations_test.spec.ts
- sdk/billing/arm-billing/test/snippets.spec.ts
- @azure/arm-billing
Updates the `billing` projects to use snippet extraction.
> [billing] Update billing projects to use snippets extraction

- sdk/billingbenefits/arm-billingbenefits/README.md
- sdk/billingbenefits/arm-billingbenefits/package.json
- sdk/billingbenefits/arm-billingbenefits/test/sampleTest.spec.ts
- sdk/billingbenefits/arm-billingbenefits/test/snippets.spec.ts
- @azure/arm-billingbenefits
Updates all `billingbenefits` projects to use snippets extraction.
> [billingbenefits] Update billingbenefits projects to use snippets extraction

- sdk/botservice/arm-botservice/README.md
- sdk/botservice/arm-botservice/package.json
- sdk/botservice/arm-botservice/test/botservice_examples.spec.ts
- sdk/botservice/arm-botservice/test/snippets.spec.ts
- @azure/arm-botservice
Updates the `botservice` packages to use snippets extraction.
> [botservice] Update botservice projects to use snippet extraction

- sdk/baremetalinfrastructure/arm-baremetalinfrastructure/README.md
- sdk/baremetalinfrastructure/arm-baremetalinfrastructure/package.json
- sdk/baremetalinfrastructure/arm-baremetalinfrastructure/test/baremetalinfrastructure_operations_test.spec.ts
- sdk/baremetalinfrastructure/arm-baremetalinfrastructure/test/snippets.spec.ts
- @azure/arm-baremetalinfrastructure
Updates all `baremetalinfrastructure` projects to use snippets extraction.
> [baremetalinfrastructure] Update baremetalinfrastructure to use snippets extraction

- sdk/cdn/arm-cdn/README.md
- sdk/cdn/arm-cdn/package.json
- sdk/cdn/arm-cdn/test/cdn_examples.spec.ts
- sdk/cdn/arm-cdn/test/snippets.spec.ts
- @azure/arm-cdn
Updates the `cdn` projects to use snippet extraction.
> [cdn] Update cdn projects to use snippet extraction

- sdk/keyvault/keyvault-certificates/test/public/CRUD.spec.ts
Resolves #31685
Fixes live tests for certificates which have been recently broken by a
service-level change (changing certificate to Certificate).
Also removes the retries as that can cause conflicts.
> [keyvault] fix certificate live tests

- common/config/rush/pnpm-lock.yaml
- common/tools/eslint-plugin-azure-sdk/package.json
- @azure/eslint-plugin-azure-sdk
- #32538
Updates to the latest version of the `eslint-config-prettier` package.
> [eslint-plugin-azure-sdk] Upgrade eslint-config-prettier to v10

- sdk/cognitivelanguage/ai-language-conversations/README.md
- sdk/cognitivelanguage/ai-language-conversations/package.json
- sdk/cognitivelanguage/ai-language-conversations/src/conversationAnalysisClient.ts
- sdk/cognitivelanguage/ai-language-conversations/test/snippets.spec.ts
- sdk/cognitivelanguage/ai-language-text/MIGRATION_ai_text_analytics.md
- sdk/cognitivelanguage/ai-language-text/README.md
- sdk/cognitivelanguage/ai-language-text/Samples.md
- sdk/cognitivelanguage/ai-language-text/package.json
- sdk/cognitivelanguage/ai-language-text/samples-dev/abstractiveSummarization.ts
- sdk/cognitivelanguage/ai-language-text/src/textAnalysisClient.ts
- sdk/cognitivelanguage/ai-language-text/test/snippets.spec.ts
- sdk/cognitivelanguage/ai-language-textauthoring/README.md
- sdk/cognitivelanguage/ai-language-textauthoring/package.json
- sdk/cognitivelanguage/ai-language-textauthoring/test/snippets.spec.ts
- @azure/ai-language-conversations
- @azure/ai-language-text
- @azure/ai-language-textauthoring
- - https://github.com/Azure/azure-sdk-for-js/issues/32416
Updates all `cognitivelanguage` projects to use snippets extraction.
> [cognitive-language] Update projects to use snippets extraction

- common/config/rush/pnpm-lock.yaml
- sdk/chaos/arm-chaos/README.md
- sdk/chaos/arm-chaos/package.json
- sdk/chaos/arm-chaos/test/chaos_examples.spec.ts
- sdk/chaos/arm-chaos/test/snippets.spec.ts
- @azure/arm-chaos
Updates all projects under `chaos` to use snippets extraction.
> [chaos] Update chaos projects to use snippets extraction

- sdk/cognitiveservices/arm-cognitiveservices/README.md
- sdk/cognitiveservices/arm-cognitiveservices/package.json
- sdk/cognitiveservices/arm-cognitiveservices/test/cognitiveservices_congitiveservice.spec.ts
- sdk/cognitiveservices/arm-cognitiveservices/test/cognitiveservices_openai.spec.ts
- sdk/cognitiveservices/arm-cognitiveservices/test/snippets.spec.ts
- @azure/arm-cognitiveservices
Updates all projects under `cognitiveservices` to use snippets extraction.
> [cognitiveservices] Update cognitiveservices for snippet extraction

- common/config/rush/pnpm-lock.yaml
- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
> [identity] Update msal-browser to 4.0.1

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
Update package version and changelog after release of 4.6.0
> [identity] Update version after release of 4.6.0

- common/tools/dev-tool/src/commands/admin/migrate-package.ts
fixes https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4484318&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=2173
> [dev-tool] update vitest dependency version to resolve rush update failure

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
@azure/microsoft-playwright-testing/reporter
> docs(playwrighttesting):Changelog for 1.0.0-beta.7

- eng/pipelines/templates/stages/archetype-sdk-tests-isolated.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
- sdk/appconfiguration/app-configuration/tests.yml
- sdk/containerregistry/container-registry/tests.yml
- sdk/eventhub/event-hubs/tests.yml
- sdk/eventhub/eventhubs-checkpointstore-blob/tests.yml
- sdk/keyvault/keyvault-certificates/tests.yml
- sdk/keyvault/keyvault-keys/tests.yml
- sdk/keyvault/keyvault-secrets/tests.yml
- sdk/search/search-documents/tests.yml
- sdk/servicebus/service-bus/tests.yml
Remove sovereign cloud testing references
> Remove sovereign cloud testing references

- sdk/playwrighttesting/microsoft-playwright-testing/CHANGELOG.md
- sdk/playwrighttesting/microsoft-playwright-testing/package.json
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/reporterUtils.spec.ts
Show effective parallelism instead of requested worker count.
Yes
> chore(playwrighttesting): show effective parallelism instead of requested worker

- sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/cIInfoProvider.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/clInfoProvider.spec.ts
> fix(playwrighttesting): ADO job name from environment variables

- .github/CODEOWNERS
It should not be limited to data-plane directory.
> [CODEOWNER] update `healthdataaiservices` entry

- sdk/ai/ai-projects/eslint.config.mjs
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agentsWithFunctionTool.ts
- sdk/ai/ai-projects/samples-dev/agents/codeInterpreter.ts
- sdk/ai/ai-projects/samples-dev/agents/codeInterpreterWithStreaming.ts
- sdk/ai/ai-projects/samples-dev/agents/fileSearch.ts
- sdk/ai/ai-projects/src/agents/customModels.ts
- sdk/ai/ai-projects/src/agents/streamingModels.ts
- sdk/ai/ai-projects/src/agents/utils.ts
- sdk/ai/ai-projects/tsconfig.src.json
- sdk/ai/ai-projects/tsconfig.test.json
- sdk/eventgrid/eventgrid/CHANGELOG.md
- sdk/eventgrid/eventgrid/package.json
- sdk/eventgrid/eventgrid/review/eventgrid.api.md
- sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
- sdk/eventgrid/eventgrid/src/generated/models/index.ts
- sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
- sdk/eventgrid/eventgrid/src/tracing.ts
- sdk/eventgrid/eventgrid/swagger/README.md
Merging this commit into main to fix configuration/test issues
ai-projects
rushx test fails
Update configuration
This is the needed fix
No new functionality added
[Add TypeScript configuration files and update assets for ai-projects #32376](https://github.com/Azure/azure-sdk-for-js/pull/32376)
> [ai-projects] Add TypeScript configuration files and update assets

- sdk/ai/ai-inference-rest/package.json
- sdk/ai/ai-inference-rest/vitest.browser.config.ts
- sdk/ai/ai-inference-rest/vitest.config.ts
- sdk/ai/ai-projects/vitest.browser.config.ts
- sdk/ai/ai-projects/vitest.config.ts
- inference: move hookTimeout to config file
- project: bump hookTimeout to 50000ms
> [test] adjust ai tests' hookTimeout

- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/cIInfoProvider.ts
- sdk/playwrighttesting/microsoft-playwright-testing/test/utils/clInfoProvider.spec.ts
> revert(playwrighttesting): ADO env variable for branch name

- sdk/ai/ai-projects/assets.json
- sdk/face/ai-vision-face-rest/assets.json
@azure/ai-projects
@azure-rest/ai-vision
Follow up for #32672 
A few client libraries' tests needed re-recording after changing the default content-type
> [ai] Update recordings for content-type

- sdk/eventgrid/eventgrid-namespaces/assets.json
@azure/eventgrid-namespaces
Update the recordings after the switch to application/json content type
> [eventgrid] Update recordings

- sdk/identity/identity/package.json
> [identity] Bump msal-browser min-version to 4.0.2

- .github/CODEOWNERS
> [Monitor OpenTelemetry][Monitor OpenTelemetry Exporter] Update codeowners to Include Nev

- sdk/template/template-dpg/assets.json
@azure/template-dpg
Follow up for #32672
Updates the content-type for template-dpg's recordings to match what
@azure-rest/core-client now emits
> [template-dpg] Update recordings for content-type

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/common/constants.ts
- sdk/cosmosdb/cosmos/src/request/request.ts
> Added header and changeLog for Merge Support 

- sdk/communication/communication-chat/CHANGELOG.md
- sdk/communication/communication-chat/assets.json
- sdk/communication/communication-chat/review/communication-chat.api.md
- sdk/communication/communication-chat/src/chatClient.ts
- sdk/communication/communication-chat/src/chatThreadClient.ts
- sdk/communication/communication-chat/src/models/events.ts
- sdk/communication/communication-chat/test/internal/chatClient.mocked.spec.ts
- sdk/communication/communication-chat/test/public/chatClient.spec.ts
> Merge streaming changes into beta-release branch

- eng/pipelines/pullrequest.yml
See https://github.com/Azure/azure-sdk-for-python/pull/39465
> Move pullrequest.yml location to eng

- .github/CODEOWNERS
Resolves https://github.com/Azure/azure-sdk-for-js/issues/32673
> [CODEOWNERS] add an entry for AI Projects

- sdk/core/core-client-rest/CHANGELOG.md
- sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
- otel-instrumentation
- azure-rest/core-client
> [core][instrumentation] Update CHANGELOG for february releases

- sdk/openai/openai/test/public/node/batches.spec.ts
- Fix batch test to iterate on the batch objects output.
> [OpenAI] Fix Batch Test Behavior

- sdk/ai/ai-inference-rest/vitest.config.ts
- sdk/ai/ai-projects/vitest.config.ts
after we revert the pre-restore-recording changes.
> [test][ai] put back higher hookTimeout

- sdk/computefleet/arm-computefleet/assets.json
- sdk/mongocluster/arm-mongocluster/assets.json
- sdk/trustedsigning/arm-trustedsigning/assets.json
mongocluster
computefleet
trustedsigning
Follow up for #32672
Updating recordings to match the new content-type changes
> [mongocluster][computefleet][trustedsigning] Update recordings for content-type

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
- Run prepare release script for Identity v4.7.0
> [Identity] Run Prepare-Release Script

- common/tools/dev-tool/src/commands/admin/migrate-package.ts
fixes https://github.com/Azure/azure-sdk-for-js/issues/32895
> [dev-tool] Revert #32597 change

- sdk/servicebus/service-bus/test/internal/retries.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/serviceBusReceiverUnitTests.spec.ts
- sdk/servicebus/service-bus/test/internal/unit/streamingReceiver.spec.ts
- sdk/servicebus/service-bus/vitest.browser.config.ts
to adopt the aggregate error change in core-amqp retry
> [ServiceBus] update tests verifying retry errors

- sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts
> fix(playwrighttesting): Incorrect AuthType in Configuration

- sdk/storage/storage-file-datalake/test/browser/highlevel.browser.spec.ts
> Fix test failure

- sdk/computeschedule/arm-computeschedule/package.json
- sdk/easm/defender-easm-rest/package.json
- sdk/pineconevectordb/arm-pineconevectordb/package.json
- sdk/servicenetworking/arm-servicenetworking/package.json
as we now use dev-tool to extract Apis.
> [EngSys] remove `@microsoft/api-extractor` dev dependency

- sdk/core/core-rest-pipeline/src/fetchHttpClient.ts
- sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- sdk/core/core-rest-pipeline/src/xhrHttpClient.ts
- sdk/core/ts-http-runtime/review/azure-core-comparison.diff
- sdk/core/ts-http-runtime/src/fetchHttpClient.ts
- sdk/core/ts-http-runtime/src/nodeHttpClient.ts
- sdk/core/ts-http-runtime/src/xhrHttpClient.ts
- sdk/storage/storage-file-datalake/test/node/highlevel.node.spec.ts
- sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
- sdk/storage/storage-file-share/test/node/highlevel.node.spec.ts
and update storage file datalake test to adopt the error message change
> [core] update abort error messsages to have period

- common/tools/dev-tool/src/commands/admin/migrate-package.ts
- common/tools/dev-tool/src/util/run.ts
> [dev-tool] log output before throwing errors

- sdk/communication/communication-call-automation/CHANGELOG.md
Removing the unsupported features from readme document
> updating the change log

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/customization/convertOutputModelsFromWire.ts
- sdk/ai/ai-projects/src/customization/streamingModels.ts
- sdk/ai/ai-projects/src/customization/streamingWireModels.ts
Fix consistent with python/c# changes for this issue: https://github.com/Azure/azure-sdk-for-net/issues/48333
> RunStepFileSearchToolCallResultsOutput issue fix

- sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
- sdk/web-pubsub/web-pubsub-express/package.json
- sdk/web-pubsub/web-pubsub-express/tsconfig.json
- sdk/web-pubsub/web-pubsub/CHANGELOG.md
- sdk/web-pubsub/web-pubsub/test/hubs.spec.ts
- Release web-pubsub-express SDK 1.0.6
- Release web-pubsub 1.1.4
- Fix live test for socketio
> Release Azure WebPubSub

- eng/emitter-package-lock.json
- eng/emitter-package.json
Upgrade emitter-package version
> Upgrade emitter-package version

- .vscode/settings.json
- eng/pipelines/templates/jobs/ci.yml
- eng/pipelines/templates/steps/npm-release-task.yml
Update to latest EsrpRelease task and use managed identity in PME
> Use PME for ESRP release

- sdk/core/core-sse/package.json
- sdk/core/core-sse/samples-dev/createSseStream.ts
- sdk/core/core-sse/samples/v2/javascript/README.md
- sdk/core/core-sse/samples/v2/javascript/createSseStream.js
- sdk/core/core-sse/samples/v2/javascript/package.json
- sdk/core/core-sse/samples/v2/typescript/README.md
- sdk/core/core-sse/samples/v2/typescript/package.json
- sdk/core/core-sse/samples/v2/typescript/src/createSseStream.ts
- sdk/core/core-sse/samples/v2/typescript/tsconfig.json
- sdk/core/core-sse/tsconfig.samples.json
The updated sample introduces `getEnglishWikiRecentChanges` API that should serve as an example for SSE APIs generated by our code generation tooling.
> [core-sse] Make sample isomorphic

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-xml/CHANGELOG.md
> [core] prepare for March 2025 releases

- sdk/translation/ai-translation-document-rest/assets.json
- sdk/translation/ai-translation-document-rest/test/public/getSupportedFormatsTest.spec.ts
- sdk/translation/ai-translation-document-rest/test/public/node/documentTranslationTest.spec.ts
@azure-rest/ai-translation-document
#31948 
Add await for test case and update recording
> [ai-translation-document] Update test and recording

- sdk/communication/communication-rooms/CHANGELOG.md
- sdk/communication/communication-rooms/README.md
- sdk/communication/communication-rooms/assets.json
- sdk/communication/communication-rooms/package.json
- sdk/communication/communication-rooms/review/communication-rooms.api.md
- sdk/communication/communication-rooms/samples/v1/javascript/package.json
- sdk/communication/communication-rooms/samples/v1/javascript/participantOperations.js
- sdk/communication/communication-rooms/samples/v1/javascript/roomOperations.js
- sdk/communication/communication-rooms/samples/v1/typescript/package.json
- sdk/communication/communication-rooms/samples/v1/typescript/src/participantOperations.ts
- sdk/communication/communication-rooms/samples/v1/typescript/src/roomOperations.ts
- sdk/communication/communication-rooms/samples/v1/typescript/tsconfig.json
- sdk/communication/communication-rooms/src/generated/src/models/index.ts
- sdk/communication/communication-rooms/src/generated/src/models/mappers.ts
- sdk/communication/communication-rooms/src/generated/src/models/parameters.ts
- sdk/communication/communication-rooms/src/generated/src/operations/rooms.ts
- sdk/communication/communication-rooms/src/generated/src/roomsRestClient.ts
- sdk/communication/communication-rooms/src/generated/src/tracing.ts
- sdk/communication/communication-rooms/src/models/models.ts
- sdk/communication/communication-rooms/swagger/README.md
- sdk/communication/communication-rooms/test/public/roomsClient.spec.ts
- sdk/communication/communication-rooms/test/public/utils/recordedClient.ts
communication-rooms package updating to 1.2.0 following this feature release
unit tests added for Collaborator
> [Communication][Rooms] Add Collaborator role to room participant roles

- eng/emitter-package-lock.json
- eng/emitter-package.json
Bump emitter version in sdk repo for March release
> Bump emitter version in sdk repo for March release

- samples/cors/ts/README.md
- samples/cors/ts/client/index.html
- samples/cors/ts/client/index.ts
- samples/cors/ts/client/package.json
- samples/cors/ts/server/package.json
- samples/cors/ts/server/server.ts
This PR address security warnings caused by old version of dependencies. The changes include
- server: remove unused dependencies
- server: replace `ts-node` with `tsx`
- client: remove dotenv and axios which depend on NodeJS
- replace axios with fetch API
- replace env variable with HTML input
- client: upgrade parcel bundler to v2
> [samples] update the CORS sample

- samples/frameworks/electron/ts/index.html
- samples/frameworks/electron/ts/package.json
- samples/frameworks/electron/ts/src/main.ts
> [Samples] upgrade dependencies for electron sample

- .github/CODEOWNERS
> Update translation owner

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/README.md
- sdk/cosmosdb/cosmos/package.json
- sdk/cosmosdb/cosmos/src/common/constants.ts
@azure/cosmos
Update CHANGELOG, README, SDKVersion for Release.
> [@azure/cosmos] 4.3.0 Update CHANGELOG, README, SDKVersion

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
Run prepare release script for @azure/identity for March release
> [Identity] Run prepare release script for March

- sdk/cognitivelanguage/ai-language-textauthoring/README.md
- sdk/cognitivelanguage/ai-language-textauthoring/package.json
- Make it clear that this is a private SDK used internally
> [Language Authoring] Update Readme and package.json

- sdk/appconfiguration/app-configuration/CHANGELOG.md
- sdk/appconfiguration/app-configuration/package.json
- sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts
- sdk/appconfiguration/app-configuration/src/internal/constants.ts
- sdk/appconfiguration/app-configuration/swagger/swagger.md
Run prepare release script and update to beta version
> [App Config] Prepare release script

- eng/pipelines/run-for-all-packages.yml
and separate build and lint step into multiple single command steps.
> [EngSys] add --verbose option in run-for-all pipeline

- .github/CODEOWNERS
Add Daniel Ortega to CODEOWNER for Azure Communication Services Phone Numbers
> Add Daniel Ortega to CODEOWNER for Azure Communication Services Phone Numbers

- sdk/maps/maps-geolocation-rest/CHANGELOG.md
- sdk/maps/maps-geolocation-rest/package.json
- sdk/maps/maps-geolocation-rest/swagger/README.md
- sdk/maps/maps-render-rest/CHANGELOG.md
- sdk/maps/maps-render-rest/package.json
- sdk/maps/maps-render-rest/swagger/README.md
- sdk/maps/maps-route-rest/CHANGELOG.md
- sdk/maps/maps-search-rest/CHANGELOG.md
- sdk/maps/maps-search-rest/package.json
- sdk/maps/maps-search-rest/swagger/README.md
> Update changelog for 2025 mar release

- sdk/communication/communication-rooms/assets.json
- sdk/communication/communication-rooms/swagger/README.md
communication-rooms
resolving api spec commit id to be a commit from main branch of azure-api-spec repo, for release
n/a
#33125 
n/a
> [Communication][Rooms] Update commit id for API spec for collaborator feature

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/models/parameters.ts
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/models/parameters.ts
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/models/parameters.ts
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> Bump API version and package version for STG97 features

- .github/ISSUE_TEMPLATE/z-learn-feedback.yml
> Add platform id to feedback template

- sdk/ai/ai-projects/CHANGELOG.md
> updating changelog for beta 3 release

- sdk/communication/communication-rooms/assets.json
- sdk/communication/communication-rooms/package.json
communication-rooms
2.3.2 is not released yet, incorrectly referenced in Rooms package.json
> [Communication][Rooms] Downgrade communication-common to latest released version

- documentation/DPG-quickstart.md
- documentation/Generate-code-from-TypeSpec.md
- documentation/RLC-quickstart.md
fixes https://github.com/Azure/autorest.typescript/issues/3067
> Update doc with kebab-case options

- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/test-eslint.yml
to show all the errors and warnings.
> [EngSys] enable verbose logging for linting

- sdk/test-utils/perf/GettingStarted.md
for the directory structure changes
> [doc] update perf tests GettingStarted guide

- sdk/ai/ai-projects/CHANGELOG.md
> Changelog fix

- eng/pipelines/templates/steps/npm-release-task.yml
- eng/scripts/verify-npm-tags.ps1
now handles empty tag exception
> Verify npm tag handling

- sdk/core/ts-http-runtime/CHANGELOG.md
- sdk/core/ts-http-runtime/package.json
- sdk/core/ts-http-runtime/review/azure-core-comparison.diff
- sdk/core/ts-http-runtime/src/client/clientHelpers.ts
- sdk/core/ts-http-runtime/src/constants.ts
- sdk/core/ts-http-runtime/src/policies/auth/checkInsecureConnection.ts
- sdk/core/ts-http-runtime/test/authPolicy/apiKeyAuthenticationPolicy.spec.ts
- sdk/core/ts-http-runtime/test/authPolicy/basicAuthenticationPolicy.spec.ts
- sdk/core/ts-http-runtime/test/authPolicy/bearerAuthenticationPolicy.spec.ts
- sdk/core/ts-http-runtime/test/authPolicy/insecureConnection.spec.ts
- sdk/core/ts-http-runtime/test/authPolicy/oauth2AuthenticationPolicy.spec.ts
Bug fix to pass the `allowInsecureConnection` through to the policy
> [ts-http-runtime] Insecure connection fix

- swagger_to_sdk_config.json
> [sdk automation] update error log

- swagger_to_sdk_config.json
> keep showInComment

- eng/pipelines/run-for-all-packages.yml
- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/build.yml
- eng/pipelines/templates/steps/cosmos-additional-steps.yml
- eng/pipelines/templates/steps/monitor-additional-steps.yml
- eng/pipelines/templates/steps/test-eslint.yml
- eng/tools/ci-runner/package.json
- eng/tools/ci-runner/src/helpers.js
- eng/tools/ci-runner/test/actions.spec.js
- eng/tools/eng-package-utils/getPackagePath.js
- eng/tools/eng-package-utils/package.json
- package.json
- pnpm-lock.yaml
- sdk/core/ts-http-runtime/scripts/azure-diff.ts
- sdk/test-utils/recorder/src/utils/relativePathCalculator.ts
- pipelines: separate installing of Pnpm and `pnpm install` into two steps
- More replacements of rush/rushx
> more rush replacement

- .github/CODEOWNERS
add more ai-projects approvers
> add more ai-projects approvers

- common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-sdktype.ts
- common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-sdktype.ts
- common/tools/eslint-plugin-azure-sdk/vitest.config.ts
> [eslint] Fix sdk-type to include perf-test

- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agentsAzureAiSearch.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/README.md
- sdk/ai/ai-projects/samples/v1-beta/javascript/agents/agentsAzureAiSearch.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/README.md
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/agents/agentsAzureAiSearch.ts
- sdk/ai/ai-projects/src/agents/utils.ts
- sdk/ai/ai-projects/src/customization/convertModelsToWrite.ts
- sdk/ai/ai-projects/src/customization/convertOutputModelsFromWire.ts
- sdk/ai/ai-projects/src/customization/models.ts
- sdk/ai/ai-projects/src/index.ts
support advanced param for azure ai search tool
> update azure ai search advanced params

- .github/CODEOWNERS
> [Monitor OpenTelemetry][Monitor OpenTelemetry Exporter] Update CODEOWNERS

- sdk/openai/openai/samples-dev/responsesStream.ts
- sdk/openai/openai/samples-dev/responsesStreamingTools.ts
- sdk/openai/openai/samples/v2-beta/javascript/README.md
- sdk/openai/openai/samples/v2-beta/javascript/responsesStream.js
- sdk/openai/openai/samples/v2-beta/javascript/responsesStreamingTools.js
- sdk/openai/openai/samples/v2-beta/typescript/README.md
- sdk/openai/openai/samples/v2-beta/typescript/src/responsesStream.ts
- sdk/openai/openai/samples/v2-beta/typescript/src/responsesStreamingTools.ts
> [OpenAI] Samples for Responses Stream

- swagger_to_sdk_config.json
> add "stdout" config

- sdk/appconfiguration/app-configuration/CHANGELOG.md
- sdk/appconfiguration/app-configuration/package.json
- sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts
- sdk/appconfiguration/app-configuration/src/internal/constants.ts
- sdk/appconfiguration/app-configuration/swagger/swagger.md
> [AppConfig] Prepare release for v1.9

- sdk/ai/ai-projects/README.md
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agentsWithOpenApi.ts
- sdk/ai/ai-projects/src/customization/models.ts
- sdk/ai/ai-projects/src/generated/src/models.ts
- sdk/ai/ai-projects/src/generated/src/outputModels.ts
- sdk/ai/ai-projects/test/snippets.spec.ts
- sdk/ai/ai-projects/tsp-location.yaml
adding default_params support for openApi and updating sample
> OpenApi schema updates

- sdk/ai/ai-projects/samples-dev/agents/agentsSharepoint.ts
> Adding sharepoint sample

- common/tools/turborepo-remote-cache/CHANGELOG.md
- common/tools/turborepo-remote-cache/Dockerfile
- common/tools/turborepo-remote-cache/LICENSE
- common/tools/turborepo-remote-cache/README.md
- common/tools/turborepo-remote-cache/cache.bicep
- common/tools/turborepo-remote-cache/eslint.config.mjs
- common/tools/turborepo-remote-cache/package.json
- common/tools/turborepo-remote-cache/sample.env
- common/tools/turborepo-remote-cache/src/auth.ts
- common/tools/turborepo-remote-cache/src/index.ts
- common/tools/turborepo-remote-cache/src/storage.ts
- common/tools/turborepo-remote-cache/src/util/debug.ts
- common/tools/turborepo-remote-cache/src/util/log.ts
- common/tools/turborepo-remote-cache/src/util/logger.ts
- common/tools/turborepo-remote-cache/test/auth.spec.ts
- common/tools/turborepo-remote-cache/test/debug.spec.ts
- common/tools/turborepo-remote-cache/test/logger.spec.ts
- common/tools/turborepo-remote-cache/test/storage.spec.ts
- common/tools/turborepo-remote-cache/tsconfig.json
- common/tools/turborepo-remote-cache/turbo.openapi3.json
- common/tools/turborepo-remote-cache/vitest.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- @azure/turborepo-remote-cache
- #33717
Implements the [TurboBuild Cache Spec](https://turbo.build/docs/openapi/artifacts/artifact-exists) using express and Azure Blob Storage.
> [EngSys] Add build cache to common tools

- sdk/ai/ai-projects-1dp/samples-dev/connections/connectionsBasics.ts
- sdk/ai/ai-projects-1dp/samples-dev/deployments/deploymentsBasics.ts
update samples of connections and deployments for 1dp
> update samples of connections and deployments for 1dp

- sdk/cosmosdb/cosmos/samples/v3/javascript/README.md
- sdk/cosmosdb/cosmos/samples/v3/typescript/README.md
> renaming in sample readmd

- sdk/ai/ai-inference-rest/samples/cookbook/simpleCompletionsPage/src/index.js
> [AI] [Projects] Fix #32812

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
> [Identity] Prepare release April

- eng/pipelines/templates/jobs/npm-release-task.yml
- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/stages/partner-release.yml
Right now integration needs manual approval to execute, need to remove this
> [Eng Sys] remove publish to prod environment for integration

- sdk/openai/openai/test/public/assistants.spec.ts
- sdk/openai/openai/test/utils/createClients.ts
- sdk/openai/openai/test/utils/setup.ts
- sdk/openai/openai/test/utils/types.ts
- sdk/openai/openai/test/utils/utils.ts
> Rewrite assistants tests to use TWD

- sdk/communication/communication-common/README.md
- sdk/communication/communication-common/test/snippets.spec.ts
- sdk/communication/communication-messages-rest/README.md
- sdk/communication/communication-messages-rest/test/snippets.spec.ts
- @azure/communication-common
- @azure-rest/communication-messages
- https://github.com/Azure/azure-sdk-for-js/issues/33880
Updates snippets to be compliant with our `update-snippets` check.
> [communication] Fix snippets extraction for communication projects

- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
- @azure/keyvault-certificates
- @azure/keyvault-keys
- @azure/keyvault-secrets
- https://github.com/Azure/azure-sdk-for-js/issues/33880
Ignores the CHANGELOG files for snippets extraction.
> [keyvault] Update snippets to ignore CHANGELOGs for keyvault

- sdk/monitor/monitor-opentelemetry/README.md
- @azure/monitor-opentelemetry
- #33880
Updates the OTEL snippets code snippets file from the spec.
> [monitor] Update snippets for monitor

- sdk/identity/identity/CHANGELOG.md
> [Identity] Patch release

- sdk/identity/identity/test/manual/interactive-browser-credential/package.json
- sdk/identity/identity/test/manual/interactive-browser-credential/webpack.config.js
- Remove dependency on dev-tool
- Add polyfill for util
> [Identity] Update IBC test

- eng/pipelines/templates/steps/analyze.yml
- eng/tools/check-snippet-changes.ps1
- eng/tools/ci-runner/src/actions.js
Whenever snippets get updated the changes should be reflected in docs and committed.
> [EngSys] add a step to check for snippet changes

- common/tools/turborepo-remote-cache/Dockerfile
save us some installation steps.
> switch to official node image

- documentation/Generate-code-from-TypeSpec.md
related to https://github.com/Azure/azure-rest-api-specs/pull/33581
> Remove `generate-metadata` option

- sdk/openai/openai/test/public/completions.spec.ts
> Tidy up completions.spec.ts

- sdk/ai/ai-projects/README.md
- sdk/ai/ai-projects/test/snippets.spec.ts
updating snippet to match sample change
> listThreads snippet update

- sdk/ai/ai-projects-1dp/assets.json
- sdk/ai/ai-projects-1dp/test/public/connections/connections.spec.ts
- sdk/ai/ai-projects-1dp/test/public/utils/createClient.ts
> add test for connections

- sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md
- sdk/confidentialledger/confidential-ledger-rest/assets.json
- sdk/confidentialledger/confidential-ledger-rest/src/generated/confidentialLedger.ts
> Regenrating JS SDK to apply fix for breaking change on API Spec

- sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md
- sdk/confidentialledger/confidential-ledger-rest/package.json
- sdk/confidentialledger/confidential-ledger-rest/src/confidentialLedger.ts
- sdk/confidentialledger/confidential-ledger-rest/src/generated/confidentialLedger.ts
> Updating release version in changelog

- sdk/datafactory/arm-datafactory/package.json
- sdk/datafactory/arm-datafactory/samples-dev/changeDataCaptureCreateOrUpdateSample.ts
- sdk/datafactory/arm-datafactory/samples-dev/credentialOperationsCreateOrUpdateSample.ts
- sdk/datafactory/arm-datafactory/samples/v19/javascript/changeDataCaptureCreateOrUpdateSample.js
- sdk/datafactory/arm-datafactory/samples/v19/javascript/credentialOperationsCreateOrUpdateSample.js
- sdk/datafactory/arm-datafactory/samples/v19/typescript/src/changeDataCaptureCreateOrUpdateSample.ts
- sdk/datafactory/arm-datafactory/samples/v19/typescript/src/credentialOperationsCreateOrUpdateSample.ts
> [mgmt] Update datafactory samples

- sdk/openai/openai/test/public/assistants.spec.ts
- sdk/openai/openai/test/public/tts.spec.ts
- sdk/openai/openai/test/public/vision.spec.ts
> Disable Assistant o1-mini, and old API tts and vision tests

- sdk/ai/ai-projects-1dp/samples-dev/redteams/redteamBasics.ts
- sdk/ai/ai-projects-1dp/samples/v1-beta/javascript/README.md
- sdk/ai/ai-projects-1dp/samples/v1-beta/javascript/redteams/redteamBasics.js
- sdk/ai/ai-projects-1dp/samples/v1-beta/typescript/README.md
- sdk/ai/ai-projects-1dp/samples/v1-beta/typescript/src/evaluations/evaluationBasics.ts
- sdk/ai/ai-projects-1dp/samples/v1-beta/typescript/src/redteams/redteamBasics.ts
> add redteam sample

- sdk/eventhub/mock-hub/package.json
- sdk/test-utils/perf/package.json
- sdk/test-utils/recorder/package.json
- sdk/test-utils/test-credential/package.json
- sdk/test-utils/test-utils-vitest/package.json
- @azure-tools/mock-hub
- @azure-tools/test-credential
- @azure-tools/test-recorder
- @azure-tools/test-utils-vitest
Updates to enforce snippet extraction.
> [test-utils] Update to add snippets extraction

- sdk/search/search-documents/README.md
- sdk/search/search-documents/package.json
- sdk/search/search-documents/src/odata.ts
- sdk/search/search-documents/src/searchClient.ts
- sdk/search/search-documents/src/searchIndexClient.ts
- sdk/search/search-documents/src/searchIndexerClient.ts
- sdk/search/search-documents/test/snippets.spec.ts
- @azure/search-documents
Updates @azure/search-documents to use snippets extraction.
> [search] Migrate search-documents to use snippets extraction

- sdk/apimanagement/arm-apimanagement/README.md
- sdk/carbonoptimization/arm-carbonoptimization/README.md
- sdk/containerregistry/arm-containerregistry/README.md
- sdk/containerservice/arm-containerservice/README.md
- sdk/datafactory/arm-datafactory/README.md
- sdk/dependencymap/arm-dependencymap/README.md
- sdk/elasticsans/arm-elasticsan/README.md
- sdk/iotfirmwaredefense/arm-iotfirmwaredefense/README.md
- sdk/lambdatesthyperexecute/arm-lambdatesthyperexecute/README.md
- sdk/neonpostgres/arm-neonpostgres/README.md
- sdk/netapp/arm-netapp/README.md
- sdk/networkcloud/arm-networkcloud/README.md
- sdk/onlineexperimentation/arm-onlineexperimentation/README.md
- sdk/portalservices/arm-portalservicescopilot/README.md
- sdk/programmableconnectivity/arm-programmableconnectivity/README.md
- sdk/recoveryservicesbackup/arm-recoveryservicesbackup/README.md
- sdk/recoveryservicessiterecovery/arm-recoveryservices-siterecovery/README.md
- sdk/redisenterprise/arm-redisenterprisecache/README.md
- sdk/standbypool/arm-standbypool/README.md
- sdk/storage/arm-storage/README.md
- sdk/storageactions/arm-storageactions/README.md
- sdk/workloads/arm-workloadssapvirtualinstance/README.md
- ARM Packages
Updates the snippets files via automation.
> [EngSys] Update snippets files

- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/package.json
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-http-compat/CHANGELOG.md
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-util/package.json
- sdk/core/logger/CHANGELOG.md
- sdk/core/logger/package.json
- sdk/core/ts-http-runtime/CHANGELOG.md
- `@azure/core-util`
- `@azure/core-client`
- `@azure/core-http-compat`
- `@azure/logger`
Updating release dates and CHANGELOG entries for the May Core release.
> [core] Prepare for May release

- common/tools/dev-tool/src/index.ts
Adds additional logging for errors from dev-tool including the error message and cause if available.
> [dev-tool] Update error message with better logic

- sdk/search/search-documents/tsconfig.test.json
- @azure/search-documents
Fixes the snippets issues with unused variables by using the standard test TSConfig
> [search] Fix search-documents test TS Config

- sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md
- sdk/confidentialledger/confidential-ledger-rest/package.json
- sdk/confidentialledger/confidential-ledger-rest/review/confidential-ledger.api.md
- sdk/confidentialledger/confidential-ledger-rest/src/clientDefinitions.ts
- sdk/confidentialledger/confidential-ledger-rest/src/models.ts
- sdk/confidentialledger/confidential-ledger-rest/src/outputModels.ts
- sdk/confidentialledger/confidential-ledger-rest/src/parameters.ts
- sdk/confidentialledger/confidential-ledger-rest/src/responses.ts
> Updating ClientDefinition.ts with missing endpoints from previous release

- .github/CODEOWNERS
- remove invalid/non-public users
- delete entries of deleted directories
> [CODEOWNERS] update entries

- sdk/communication/communication-call-automation/src/callMedia.ts
> Added play bargin for media.

- .scripts/automation_init.sh
fixes https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4813695&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=542
update to the latest version to pass the automation
@wanlwanl  could you help review this pr?
0.21.0 could generate the sdk
> update @azure-tools/typespec-client-generator-cli version

- sdk/monitor/monitor-query/CHANGELOG.md
- sdk/monitor/monitor-query/package.json
- sdk/monitor/monitor-query/src/constants.ts
- sdk/monitor/monitor-query/src/generated/logquery/src/azureLogAnalyticsContext.ts
- sdk/monitor/monitor-query/src/generated/metrics/src/monitorManagementClientContext.ts
- sdk/monitor/monitor-query/src/generated/metricsdefinitions/src/monitorManagementClientContext.ts
- sdk/monitor/monitor-query/src/generated/metricsnamespaces/src/monitorManagementClientContext.ts
- bump to unreleased patch version
> [monitor-query] prepare for May 2025 release

- sdk/documentintelligence/ai-document-intelligence-rest/CHANGELOG.md
- sdk/documentintelligence/ai-document-intelligence-rest/README.md
- sdk/documentintelligence/ai-document-intelligence-rest/package.json
- sdk/documentintelligence/ai-document-intelligence-rest/review/ai-document-intelligence.api.md
- sdk/documentintelligence/ai-document-intelligence-rest/src/audience.ts
- sdk/documentintelligence/ai-document-intelligence-rest/src/documentIntelligence.ts
- sdk/documentintelligence/ai-document-intelligence-rest/src/index.ts
- sdk/documentintelligence/ai-document-intelligence-rest/test/public/node/analysis.spec.ts
- sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
- sdk/formrecognizer/ai-form-recognizer/README.md
- sdk/formrecognizer/ai-form-recognizer/package.json
- sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
- sdk/formrecognizer/ai-form-recognizer/src/constants.ts
- sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClient.ts
- sdk/formrecognizer/ai-form-recognizer/src/index.ts
- sdk/formrecognizer/ai-form-recognizer/src/options/FormRecognizerClientOptions.ts
- sdk/formrecognizer/ai-form-recognizer/src/util.ts
`@azure/ai-form-recognizer`
`@azure-rest/ai-document-intelligence`
> [Document Intelligence] [Form Recognizer] Add audience option for Azure Gov cloud support

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationEventParser.ts
- sdk/communication/communication-call-automation/src/models/events.ts
- sdk/communication/communication-call-automation/swagger/README.md
Added IncomingCall event to beta6 branch and tested with Contoso Application.
Correlation ID: -> 74254760-78ed-4249-8c78-862a366152e0
> IncomingCall Event

- sdk/identity/identity/managed-identity-matrix.json
- sdk/identity/identity/vitest.browser.config.ts
Update the test type for managed identity so that it matches the new format for test command.
Update vitest browser config for browser test
> [Identity] Update test type

- sdk/communication/communication-call-automation/CHANGELOG.md
- sdk/communication/communication-call-automation/package.json
Upgraded alpha sdk version from 1.4.0-alpha to 1.5.0-alpha
> Alpha SDK Version Upgrade

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/communication/communication-call-automation/src/callAutomationClient.ts
- sdk/communication/communication-call-automation/src/models/events.ts
- sdk/communication/communication-call-automation/src/models/models.ts
- sdk/communication/communication-call-automation/src/models/responses.ts
- sdk/communication/communication-call-automation/swagger/README.md
Removed reliance on REST interface by removing Omit mapping. Fixed all forgotten export issues.
> Bug Fix: ae-forgotten-export beta6 branch

- common/config/rush/pnpm-lock.yaml
- sdk/ai/ai-projects/package.json
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/agents/agentsBasics.ts
- sdk/ai/ai-projects/samples-dev/connections/connectionsBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/README.md
- sdk/ai/ai-projects/samples/v1-beta/javascript/agents/agentsBasics.js
- sdk/ai/ai-projects/samples/v1-beta/javascript/connections/connectionsBasics.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/README.md
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/agents/agentsBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/connections/connectionsBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/evaluations/evaluationBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/indexes/indexesBasics.ts
- sdk/ai/ai-projects/src/aiProjectClient.ts
- sdk/ai/ai-projects/src/api/aiProjectContext.ts
- sdk/ai/ai-projects/src/api/connections/index.ts
- sdk/ai/ai-projects/src/api/connections/operations.ts
- sdk/ai/ai-projects/src/classic/connections/index.ts
- sdk/ai/ai-projects/src/constants.ts
- sdk/ai/ci.yml
> add default connection and agents

- sdk/ai/ai-projects/src/api/inference/operations.ts
> update inference url

- documentation/Generate-code-from-TypeSpec.md
resolved https://github.com/Azure/typespec-azure/pull/2541/files#r2057393146
> Update doc for generate modular sdk

- sdk/cosmosdb/cosmos/review/cosmos.api.md
- sdk/cosmosdb/cosmos/src/bulk/BulkResponse.ts
- sdk/cosmosdb/cosmos/src/bulk/Limiter.ts
- sdk/cosmosdb/cosmos/src/common/constants.ts
- sdk/cosmosdb/cosmos/src/request/ErrorResponse.ts
- sdk/cosmosdb/cosmos/src/request/request.ts
@azure/cosmos
This PR fixes some parsing errors in the bulk response.
> [cosmos] Fix bulk error response

- sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts
@azure/cosmos
This PR fixes handling of merge error during change feed.
> change feed merge fix

- sdk/cosmosdb/cosmos/src/bulk/Limiter.ts
@azure/cosmos
This PR fixes split/merge error handling in bulk
> [cosmos] fix bulk split timeout

- sdk/ai/ai-projects/src/aiProjectClient.ts
- sdk/ai/ai-projects/src/api/evaluations/operations.ts
- sdk/ai/ai-projects/src/models/models.ts
use azure scope for evaluation
> use azure scope for evaluation

- sdk/ai/ai-projects/samples-dev/inference/imageEmbedding.ts
- sdk/ai/ai-projects/samples-dev/inference/textEmbeddings.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/inference/imageEmbedding.js
- sdk/ai/ai-projects/samples/v1-beta/javascript/inference/textEmbeddings.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/connections/connectionsBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/inference/imageEmbedding.ts
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/inference/textEmbeddings.ts
- sdk/ai/ai-projects/src/aiProjectClient.ts
> fix inference test

- sdk/ai/ai-agents/CHANGELOG.md
- sdk/ai/ai-agents/README.md
- sdk/ai/ai-agents/test/snippets.spec.ts
updating README and CHANGELOG for beta release
> Azure AI Agents README updates

- sdk/cosmosdb/cosmos/test/public/functional/NonStreamingQueryPolicy.spec.ts
> update fts method

- sdk/ai/ai-projects/src/aiProjectClient.ts
> update route client

- sdk/cosmosdb/cosmos/src/bulk/Limiter.ts
@azure/cosmos
This PR fixes retry of operations in split/merge case.
> fix split/merge handling

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
Update changelog with PR number & minor version bump
> [Identity] May release update

- sdk/ai/ai-projects/samples-dev/indexes/indexesBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/indexes/indexesBasics.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/indexes/indexesBasics.ts
- sdk/ai/ai-projects/src/aiProjectClient.ts
> update indexes samples

- sdk/ai/ai-projects/samples-dev/evaluations/evaluationBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/evaluations/evaluationBasics.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/evaluations/evaluationBasics.ts
> remove comment code

- sdk/cosmosdb/cosmos/CHANGELOG.md
- sdk/cosmosdb/cosmos/src/request/defaultAgent.ts
Builds off of #34238 but since we've already fixed the test commands it felt simpler to just open a new PR with a smaller set of changes. I plan to close #34238 in favor of this one shortly.
Resolves #34220
> [cosmos] Fix require statements v2

- sdk/ai/ai-projects/src/api/inference/operations.ts
> update azure openai logic

- sdk/ai/ai-projects/assets.json
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/src/aiProjectClient.ts
- sdk/ai/ai-projects/src/api/aiProjectContext.ts
- sdk/ai/ai-projects/test/public/connections/connections.spec.ts
> beta6 fix comments 2

- common/config/rush/pnpm-lock.yaml
- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-common/CHANGELOG.md
- sdk/storage/storage-common/package.json
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> [Storage]Update package version for STG98 features

- common/config/rush/pnpm-lock.yaml
> Update pnpm-lock file

- sdk/communication/communication-call-automation/CHANGELOG.md
- sdk/communication/communication-call-automation/package.json
- sdk/communication/communication-call-automation/src/models/constants.ts
- sdk/communication/communication-call-automation/swagger/README.md
- sdk/communication/communication-call-automation/test/utils/mockClient.ts
Updating the version
Updating the feature changelog
API View --> [APIView](https://spa.apiview.dev/review/d4c9735f0c764120b459c554aee9f1d4?activeApiRevisionId=1d8725d33fe4492c82faa22b2fe9f05b&diffApiRevisionId=559c00fcf56945a69f85243ded47c92d)
> changelog update

- sdk/storage/test-resources.bicep
- Add `parent` instead of nesting resources
- Switch to use resource accessor operators for listing keys and account SAS.
> [Storage] update test-resources.bicep

- sdk/ai/ai-projects/samples-dev/datasets/datasetsBasics.ts
- sdk/ai/ai-projects/src/api/datasets/operations.ts
> update ai-agents dependency and update dataset dependency

- sdk/storage/storage-common/package.json
> Update package for storage-common

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-common/CHANGELOG.md
- sdk/storage/storage-common/package.json
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
> Bump storage-common version

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-queue/package.json
> Bump storage-blob version

- sdk/keyvault/keyvault-admin/test/public/accessControlClient.aborts.spec.ts
- sdk/keyvault/keyvault-admin/test/public/backupClient.abort.spec.ts
> [keyvault] Update AbortError expections in tests

- sdk/ai/ai-projects/CHANGELOG.md
- sdk/ai/ai-projects/src/api/aiProjectContext.ts
- sdk/ai/ai-projects/src/constants.ts
upgrading ai-agents package for bug fixes
> azure ai projects beta 8

- .github/CODEOWNERS
> [CODEOWNERS] update dev-tool entry

- .github/workflows/copilot-setup-steps.yml
to customize the copilot agent's dev environment
https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent
> [EngSys] add copilot-setup-steps.yml

- sdk/sitemanager/arm-sitemanager/README.md
fixes https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4909313&view=logs&j=3facec84-71ec-57ab-8937-e7da3fbb0ee2&t=de87bda4-3353-5df0-7f98-c2eb4345aa56
> [mgmt] Update  sitemanager README.md

- sdk/monitor/monitor-opentelemetry-exporter/samples-dev/basicTracerNode.ts
- sdk/monitor/monitor-opentelemetry-exporter/samples-dev/httpSample.ts
- sdk/monitor/monitor-opentelemetry-exporter/samples-dev/logSample.ts
- sdk/monitor/monitor-opentelemetry-exporter/samples-dev/metricsSample.ts
#33659
Fix failing samples in nightly builds.
> [Monitor OpenTelemetry Exporter] Fix Failing Samples

- sdk/ai/ai-projects/README.md
- sdk/ai/ai-projects/test/snippets.spec.ts
> fix readme samples

- sdk/keyvault/keyvault-certificates/package.json
- sdk/keyvault/keyvault-certificates/samples-dev/importCertificate.ts
- sdk/keyvault/keyvault-certificates/samples-dev/mergeCertificate.ts
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/backupAndRestore.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/contacts.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/deleteAndRecover.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/helloWorld.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/importCertificate.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/issuers.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/listCertificates.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/mergeCertificate.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/operations.js
- sdk/keyvault/keyvault-certificates/samples/v4/javascript/package.json
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/package.json
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/backupAndRestore.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/contacts.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/deleteAndRecover.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/helloWorld.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/importCertificate.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/issuers.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/listCertificates.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/mergeCertificate.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/operations.ts
- sdk/keyvault/keyvault-certificates/samples/v4/typescript/tsconfig.json
> [keyvault] Refresh samples for kv-certs and remove fake certs

- .github/CODEOWNERS
> update ai-project code owner

- sdk/ai/ai-projects/CHANGELOG.md
- sdk/ai/ai-projects/README.md
- sdk/ai/ai-projects/package.json
- sdk/ai/ai-projects/review/ai-projects.api.md
- sdk/ai/ai-projects/samples-dev/datasets/datasetsBasics.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/datasets/datasetsBasics.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/datasets/datasetsBasics.ts
- sdk/ai/ai-projects/src/api/datasets/operations.ts
- sdk/ai/ai-projects/src/api/index.ts
- sdk/ai/ai-projects/src/classic/datasets/index.ts
- sdk/ai/ai-projects/src/index.ts
- sdk/ai/ai-projects/test/public/node/datasets/datasets.spec.ts
- sdk/ai/ai-projects/test/public/node/evaluations/evaluations.spec.ts
> add file filter for datasets.uploadFolder

- sdk/ai/ai-projects/README.md
> update ai project endpoint address

- sdk/keyvault/keyvault-admin/CHANGELOG.md
- sdk/keyvault/keyvault-certificates/CHANGELOG.md
- sdk/keyvault/keyvault-keys/CHANGELOG.md
- sdk/keyvault/keyvault-secrets/CHANGELOG.md
Update changelog and prepare for June GA release
> [keyvault] Update changelog for June release

- sdk/communication/communication-phone-numbers/test/snippets.spec.ts
> Fix path from snipets tests

- .vscode/cspell.json
Ignore various eng files en masse with cspell
> Ignore various eng files en masse with cspell

- eng/pipelines/templates/stages/partner-release.yml
Use new common npm-publish tempalate for partner releases
> Use common publish for partner-release

- common/config/rush/pnpm-lock.yaml
- sdk/communication/communication-identity/CHANGELOG.md
- sdk/communication/communication-identity/package.json
- sdk/communication/communication-identity/src/constants.ts
- sdk/communication/communication-identity/src/generated/src/identityRestClient.ts
- sdk/communication/communication-identity/src/generated/src/tracing.ts
- sdk/communication/communication-identity/swagger/README.md
> Release peraparation for communication.identity package

- sdk/keyvault/keyvault-admin/assets.json
- sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts
This small PR updates our recording to use attributes in kv admin to ensure
they're properly recorded and deserialized
> [keyvault] Add attributes to recording

- sdk/ai/ai-agents/CHANGELOG.md
- sdk/ai/ai-agents/package.json
- sdk/ai/ai-agents/src/api/agentsContext.ts
- sdk/ai/ai-agents/src/api/operations.ts
- sdk/ai/ai-agents/src/constants.ts
- sdk/ai/ai-projects/package.json
> fixing event data parsing issue

- sdk/ai/ai-agents/samples-dev/streaming.ts
- sdk/ai/ai-agents/samples/v1-beta/javascript/streaming.js
- sdk/ai/ai-agents/samples/v1-beta/typescript/src/streaming.ts
> streaming sample fix

- sdk/communication/communication-sms/CHANGELOG.md
communication-sms
Adding missing release date
> Set release date for Messaging Connect release

- api-extractor-base.json
- sdk/core/core-rest-pipeline/api-extractor.json
This change introduces a central location for the API extractor configurations across the repo.
> [api extractor] Create base config

- sdk/onlineexperimentation/ci.yml
`@azure-rest/onlineexperimentation`
Fix artifact name in sdk/onlineexperimentation/ci.yml.
> Fix artifact name in sdk/onlineexperimentation/ci.yml.

- sdk/communication/communication-call-automation/review/communication-call-automation.api.md
- sdk/servicebus/service-bus/review/service-bus.api.md
for service-bus and communication-call-automation
> [EngSys] update api.md after api-extractor.json changes

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-common/CHANGELOG.md
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/assets.json
- sdk/storage/storage-file-share/src/Clients.ts
- sdk/storage/storage-file-share/test/shareclient.spec.ts
- sdk/storage/storage-queue/CHANGELOG.md
> [Storage] check snapshotnotfound error on deleteifexists

- sdk/storage/storage-blob/assets.json
- sdk/storage/storage-file-share/src/Clients.ts
- sdk/storage/storage-file-share/test/shareclient.spec.ts
> [Storage]Prettier

- sdk/communication/communication-sms/CHANGELOG.md
communication-sms
updating the release date
> Update release date for Messaging Connect release

- .github/prompts/test-recording.prompt.md
- sdk/test-utils/recorder/README.md
- Test recorder
Playing around with a custom prompt for the test recorder. I have tried it out on Key Vault, where I messed with the sanitizer configuration to see if it could figure out what the problem was. It did, and re-added the global sanitizer that I removed. I was quite impressed.
I'm hoping that we can give this a go, see if it is helpful, and further refine it as folks try it out.  Hopefully it will save some time and get better as time goes on.
> First cut at a test recording agent

- sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts
Use a strong hash instead of sha1
> fix(playwrighttesting): use sha256 hash for id generation

- sdk/ai/ai-projects/package.json
- sdk/ai/ai-projects/samples-dev/telemetry/inferenceRemoteTelemetry.ts
- sdk/ai/ai-projects/samples/v1-beta/javascript/package.json
- sdk/ai/ai-projects/samples/v1-beta/javascript/telemetry/inferenceRemoteTelemetry.js
- sdk/ai/ai-projects/samples/v1-beta/typescript/package.json
- sdk/ai/ai-projects/samples/v1-beta/typescript/src/telemetry/inferenceRemoteTelemetry.ts
> add remote telemetry

- sdk/ai/ai-agents/src/api/runs/operations.ts
fix bug https://github.com/Azure/azure-sdk-for-js/issues/34948
> fix submitToolOutputs stream events

- sdk/eventgrid/eventgrid-systemevents/CHANGELOG.md
- sdk/eventgrid/eventgrid-systemevents/package.json
- sdk/eventgrid/eventgrid-systemevents/review/eventgrid-systemevents.api.md
- sdk/eventgrid/eventgrid-systemevents/src/generated/models/models.ts
- sdk/eventgrid/eventgrid-systemevents/tsp-location.yaml
> [eventgrid-systemevents] prepare for 1.0.1 release

- sdk/ai/ai-agents/CHANGELOG.md
- sdk/ai/ai-agents/package.json
- sdk/ai/ai-agents/src/constants.ts
- sdk/ai/ai-projects/package.json
> update changelog and module version

- sdk/loadtesting/create-playwright/CHANGELOG.md
- sdk/loadtesting/playwright/CHANGELOG.md
- sdk/loadtesting/playwright/samples/v1/javascript/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/customising-service-parameters/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/manually-connecting-to-browsers/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/set-default-authentication-mechanism/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/using-connect-options/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/customising-service-parameters/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/manually-connecting-to-browsers/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/set-default-authentication-mechanism/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/using-connect-options/README.md
> docs(loadtesting): 1.0.0-beta.1 release changes for both packages

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/credentials/azurePowerShellCredential.ts
- sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts
> [Identity] Update AzPowershellCred for Breaking Changes

- sdk/test-utils/recorder/README.md
- sdk/test-utils/recorder/src/utils/relativePathCalculator.ts
https://github.com/Azure/azure-sdk-for-js/pull/34506 - suppresses the snippet checks
This pull request updates the `relativePathCalculator.ts` file to update documentation for better clarity and usability.
> [Recorder] Fix outdated docs

- sdk/identity/identity/CHANGELOG.md
> [Identity] Prepare Release for July Patch

- common/config/rush/pnpm-lock.yaml
- sdk/servicebus/service-bus/CHANGELOG.md
- sdk/servicebus/service-bus/package.json
- sdk/servicebus/service-bus/src/util/constants.ts
> [ServiceBus] prepare for 7.10.0-beta.2 release

- sdk/core/abort-controller/CHANGELOG.md
- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-amqp/package.json
- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-auth/package.json
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client-rest/package.json
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-client/package.json
- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-lro/package.json
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-rest-pipeline/package.json
- sdk/core/core-rest-pipeline/src/constants.ts
- sdk/core/core-sse/CHANGELOG.md
- sdk/core/core-sse/package.json
- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-tracing/package.json
- sdk/core/core-util/CHANGELOG.md
- sdk/core/core-util/package.json
- sdk/core/core-xml/CHANGELOG.md
- sdk/core/logger/CHANGELOG.md
- sdk/core/logger/package.json
- sdk/core/ts-http-runtime/CHANGELOG.md
- sdk/core/ts-http-runtime/package.json
- sdk/core/ts-http-runtime/src/constants.ts
Prep core releases for node 18 EOL release
See #33017
> [core] Update CHANGELOG for releases

- sdk/communication/communication-short-codes/README.md
- sdk/communication/communication-short-codes/test/snippets.spec.ts
- Add missing required properties in messageDetails
> Fix short code readme snippet

- sdk/loadtesting/playwright/src/utils/cIInfoProvider.ts
- sdk/loadtesting/playwright/src/utils/utils.ts
- sdk/loadtesting/playwright/test/utils/clInfoProvider.spec.ts
- sdk/loadtesting/playwright/test/utils/utils.spec.ts
> fix(loadtesting): updated correct interface for CIInfo

- common/config/rush/pnpm-lock.yaml
- sdk/openai/openai/package.json
- sdk/openai/openai/samples-dev/batch.ts
- sdk/openai/openai/samples-dev/chatCompletionsWithStructuredOutput.ts
- sdk/openai/openai/samples-dev/images.ts
- sdk/openai/openai/samples-dev/textToSpeech.ts
- sdk/openai/openai/samples/v2-beta/javascript/batch.js
- sdk/openai/openai/samples/v2-beta/javascript/chatCompletionsWithStructuredOutput.js
- sdk/openai/openai/samples/v2-beta/javascript/images.js
- sdk/openai/openai/samples/v2-beta/javascript/package.json
- sdk/openai/openai/samples/v2-beta/javascript/textToSpeech.js
- sdk/openai/openai/samples/v2-beta/typescript/package.json
- sdk/openai/openai/samples/v2-beta/typescript/src/batch.ts
- sdk/openai/openai/samples/v2-beta/typescript/src/chatCompletionsWithStructuredOutput.ts
- sdk/openai/openai/samples/v2-beta/typescript/src/images.ts
- sdk/openai/openai/samples/v2-beta/typescript/src/textToSpeech.ts
- sdk/openai/openai/test/public/abortsignal.spec.ts
- sdk/openai/openai/test/public/assistants.spec.ts
- sdk/openai/openai/test/public/chatCompletions.spec.ts
- sdk/openai/openai/test/public/node/assistantsFile.spec.ts
- sdk/openai/openai/test/public/node/batches.spec.ts
- sdk/openai/openai/test/utils/asserts.ts
- sdk/openai/openai/test/utils/types.ts
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5107687&view=results
> [openai] Upgrade openai dep

- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/test-eslint.yml
To make it easier to find errors, here is an example of the new output:
> [linting] color errors

- sdk/storage/storage-blob/CHANGELOG.md
- sdk/storage/storage-blob/package.json
- sdk/storage/storage-blob/src/generated/src/storageClient.ts
- sdk/storage/storage-blob/src/utils/constants.ts
- sdk/storage/storage-blob/swagger/README.md
- sdk/storage/storage-common/CHANGELOG.md
- sdk/storage/storage-common/package.json
- sdk/storage/storage-file-datalake/CHANGELOG.md
- sdk/storage/storage-file-datalake/package.json
- sdk/storage/storage-file-datalake/src/generated/src/storageClient.ts
- sdk/storage/storage-file-datalake/src/utils/constants.ts
- sdk/storage/storage-file-datalake/swagger/README.md
- sdk/storage/storage-file-share/CHANGELOG.md
- sdk/storage/storage-file-share/package.json
- sdk/storage/storage-file-share/src/generated/src/storageClient.ts
- sdk/storage/storage-file-share/src/utils/constants.ts
- sdk/storage/storage-file-share/swagger/README.md
- sdk/storage/storage-queue/CHANGELOG.md
- sdk/storage/storage-queue/package.json
- sdk/storage/storage-queue/src/generated/src/storageClient.ts
- sdk/storage/storage-queue/src/utils/constants.ts
- sdk/storage/storage-queue/swagger/README.md
> [Storage]Bump version for STG98 GA

- sdk/communication/communication-phone-numbers/assets.json
- sdk/communication/communication-phone-numbers/test/public/reservations.spec.ts
- sdk/communication/communication-phone-numbers/test/public/utils/operationLocationFixPolicy.ts
- sdk/communication/communication-phone-numbers/test/public/utils/recordedClient.ts
- sdk/communication/communication-phone-numbers/test/public/utils/testPhoneNumber.ts
> Fix serialization issue

- sdk/playwrighttesting/create-microsoft-playwright-testing/src/initialize.ts
@azure/create-microsoft-playwright-testing
> chore(playwrighttesting): by default reporting is false

- sdk/loadtesting/playwright/src/common/messages.ts
- sdk/loadtesting/playwright/src/common/playwrightServiceConfig.ts
- sdk/loadtesting/playwright/src/utils/utils.ts
- sdk/loadtesting/playwright/test/common/playwrightServiceConfig.spec.ts
- sdk/loadtesting/playwright/test/utils/utils.spec.ts
> fix(loadtesting): GUID validation for RunID

- common/config/rush/pnpm-lock.yaml
- sdk/anomalydetector/ai-anomaly-detector-rest/package.json
- sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/package.json
- sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/package.json
Resolves #35206
[CHANGELOG](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/CHANGELOG.md)
> [anomaly-detector] Update to csv-parse 6.0

- sdk/ai/ai-agents/CHANGELOG.md
- sdk/ai/ai-agents/assets.json
- sdk/ai/ai-agents/package.json
- sdk/ai/ai-agents/src/constants.ts
- sdk/ai/ai-agents/src/models/models.ts
- sdk/ai/ai-agents/test/public/agents/runs.spec.ts
- sdk/ai/ai-projects/package.json
> fix serialization error

- .scripts/automation_generate.sh
upgrade @autorest/typespec version to `6.0.45`
> Lock `@autorest/typescript` version

- sdk/loadtesting/playwright/src/utils/utils.ts
- sdk/loadtesting/playwright/test/core/playwrightService.spec.ts
- sdk/loadtesting/playwright/test/utils/utils.spec.ts
> fix(loadtesting): updated error handling for runID guid validation

- sdk/loadtesting/create-playwright/README.md
- sdk/loadtesting/playwright/README.md
> docs(loadtesting): updated link

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/package.json
- sdk/identity/identity/src/constants.ts
> [Identity] August release

- common/tools/dev-tool/src/commands/run/extract-api.ts
This PR adds back the list of dependencies to the JSON API view file.
> [dev-tool] Support listed dependencies in the API view

- sdk/identity/identity/CHANGELOG.md
- sdk/identity/identity/src/util/processUtils.ts
Remove the change for `exec` in `ProcessUtils` from #34878
> [Identity] Hot fix change

- eng/pipelines/templates/stages/archetype-js-release.yml
- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/build.yml
- eng/tools/eng-package-utils/package-lock.json
- eng/tools/versioning/package-lock.json
and add package-lock.json for stable builds.
> [EngSys] use `npm ci` for eng/tools/eng-package-utils and eng/tools/versioning

- package.json
- pnpm-lock.yaml
This PR updates all dependencies recursively. Not changing version ranges in
package.json files.
Also update the weekly automation to use the same command.
> [EngSys] pnpm update --recursive --no-save

- sdk/core/ts-http-runtime/src/util/concat.common.ts
Use an isomorphic type instead of a DOM one.
> [ts-http-runtime] Simplify type

- .github/CODEOWNERS
Update owners for Identity for proper issue routing
> [Identity] Update AzureSdkOwners in CODEOWNERS file

- sdk/communication/communication-call-automation/CHANGELOG.md
- sdk/communication/communication-call-automation/package.json
- sdk/communication/communication-call-automation/src/generated/src/callAutomationApiClient.ts
- sdk/communication/communication-call-automation/swagger/README.md
Updating the release date for ga6
> Updating the release date for the ga6

- .github/CODEOWNERS
Updates ownership of Azure AI Search.
> Update CODEOWNERS for Azure AI Search

- sdk/loadtesting/create-playwright/CHANGELOG.md
- sdk/loadtesting/playwright/CHANGELOG.md
> docs(loadtesting): date change in changelog

- sdk/loadtesting/playwright/samples/v1/javascript/customising-service-parameters/package.json
- sdk/loadtesting/playwright/samples/v1/javascript/manually-connecting-to-browsers/package.json
- sdk/loadtesting/playwright/samples/v1/javascript/set-default-authentication-mechanism/package.json
- sdk/loadtesting/playwright/samples/v1/javascript/using-connect-options/package.json
- sdk/loadtesting/playwright/samples/v1/typescript/customising-service-parameters/package.json
- sdk/loadtesting/playwright/samples/v1/typescript/manually-connecting-to-browsers/package.json
- sdk/loadtesting/playwright/samples/v1/typescript/set-default-authentication-mechanism/package.json
- sdk/loadtesting/playwright/samples/v1/typescript/using-connect-options/package.json
> fix(loadtesting): updated version in samples

- sdk/loadtesting/create-playwright/README.md
- sdk/loadtesting/playwright/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/manually-connecting-to-browsers/README.md
- sdk/loadtesting/playwright/samples/v1/javascript/set-default-authentication-mechanism/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/manually-connecting-to-browsers/README.md
- sdk/loadtesting/playwright/samples/v1/typescript/set-default-authentication-mechanism/README.md
> fix(loadtesting): updated command

- sdk/resources/arm-resourcesbicep/CHANGELOG.md
> Update changelog release date

- sdk/core/core-amqp/CHANGELOG.md
- sdk/core/core-auth/CHANGELOG.md
- sdk/core/core-client-rest/CHANGELOG.md
- sdk/core/core-client/CHANGELOG.md
- sdk/core/core-http-compat/CHANGELOG.md
- sdk/core/core-lro/CHANGELOG.md
- sdk/core/core-rest-pipeline/CHANGELOG.md
- sdk/core/core-tracing/CHANGELOG.md
- sdk/core/core-util/CHANGELOG.md
- sdk/core/ts-http-runtime/CHANGELOG.md
> [core] prepare for 2025 September release

- eng/pipelines/weekly_automation.yml
before the bot creats pull requests for dependency upgrades
> [EngSys] build packages and update remote cache in weekly automation

- .github/copilot-instructions.md
Hope with these, copilot will have better success in submitting PRs
> [EngSys] Update Copilot instructions for building packages and formatting

- documentation/DPG-quickstart.md
- documentation/Generate-code-from-TypeSpec.md
- documentation/RLC-quickstart.md
- eng/common/scripts/TypeSpec-Project-Process.ps1
> Update documentation and scripts to replace 'package-dir' with 'emitter-output-dir' for TypeSpec configuration

- sdk/identity/identity/src/credentials/defaultAzureCredential.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/36004
> Fix BrokerCredential reference in DAC docs

- common/tools/dev-tool/src/commands/customization/apply-v2.ts
- common/tools/dev-tool/src/util/run.ts
> [dev-tool] Address feedback from #35993

- .github/CODEOWNERS
Update the code owner for automation scripts.
> Update CODEOWNERS for automation scripts

- sdk/cosmosdb/cosmos/review/cosmos-node.api.md
- sdk/cosmosdb/cosmos/src/common/constants.ts
- sdk/cosmosdb/cosmos/src/documents/DatabaseAccount.ts
> Minor Change @4.6.0 release

- .github/CODEOWNERS
> [engsys] Cleanup invalid owners
