sdk/identity/identity/package.json, sdk/identity/identity/test/internal/node/msalClient.spec.ts
N/A - nightly tests 
Two issues are addressed in this PR:
When I added the live tests for MSAL Client via #28680 I did not realize Identity differs from other packages
in the env vars we use. In Identity, as shown in other live tests, we use `IDENTITY_SP_CLIENT_SECRET`, 
`IDENTITY_SP_TENANT_ID`, and `IDENTITY_SP_CLIENT_ID` instead of the usual `AZURE_` naming convention.
Not sure why that is, but I'm sure there's a reason. Using these env vars fixes the live test.
The second fixes an issue with our existing mocking solution that no longer plays nicely with core. When 
core was switched to ESM, our integration tests started failing because `http` and `https` are no longer
being correctly mocked [here](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/ …
=> [identity] Fix integration tests

common/git-hooks/pre-push
The Pre Push script has some scenarios which is causing issues to developers. I am working on resolving these issues. But, In the mean time, there must be an easy way for the developers to push their commits to github,
As discussed with @xirzec, I am adding an environment variable to skip these checks.
=> Adding an environment variable to skip the pre push checks

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/src/retry.ts, sdk/core/core-amqp/test/retry.spec.ts, sdk/eventhub/event-hubs/test/internal/cancellation.spec.ts, sdk/eventhub/event-hubs/test/public/cancellation.spec.ts, sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts, sdk/servicebus/service-bus/test/internal/unit/messageSender.spec.ts, sdk/servicebus/service-bus/test/internal/unit/receiverCommon.spec.ts, sdk/servicebus/service-bus/test/internal/unit/streamingReceiver.spec.ts
@azure/core-amqp
N/A
The errors thrown between retries could differ and the customer wouldn't be able to know them unless they enable logging.
Another design is to provide an error handler callback to be called on all errors but since it is an extreme measure, we can revisit this latter if we get an ask for it.
N/A
N/A
=> [core-amqp] Update error from retry

common/config/rush/pnpm-lock.yaml, common/tools/dev-tool/package.json
`dev-tool`
Fixes #28763
From their CHANGELOG.md entry, the only "breaking" change is removal of Node 12 support, so this is a simple bump.
=> [dev-tool] Update dev-tool dependency `archiver` to latest major

sdk/identity/identity-cache-persistence/CHANGELOG.md, sdk/identity/identity-cache-persistence/package.json
Automation failed to increment package version due to the prepush hook not
working on CI. This PR runs the same script and increments the package version
for @azure/identity-cache-persistence after release.
=> [identity] increment package version for cache-persistence

sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts, sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts, sdk/identity/identity/src/plugins/consumer.ts, sdk/identity/identity/test/internal/node/msalPlugins.spec.ts
Resolves #28679
When migrating plugin support to MSALClient I noticed that msalNodeCommon
defines all the plugin declarations. To avoid duplication, provide an easy path 
to migrate (by avoiding imports on msalNodeCommon) and provide a single
source of truth for plugin settings it made sense to migrate all the definitions
to a single file.
This is purely mechanical, just moving things around and updating imports
#28493
=> [identity] Refactor plugin definitions

.vscode/settings.json
N/A
N/A
I was setting up my tooling demo for the team and ran into a bug in the prettier v3,
chasing down the error, looks like it is [this issue](https://github.com/prettier/prettier-vscode/issues/3007#issuecomment-1628836459) and while there's no fix released yet, 
the common workaround seems to work on a new machine for me.
This should in theory fix prettier for folks (if it's not working) using VSCode
=> [EngSys] Fix prettier path

sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts, sdk/identity/identity/test/internal/node/msalPlugins.spec.ts
Resolves #28675
This PR adds CAE support for MSALClient as part of the larger refactor. With CAE
support, a developer can pass `enableCae` to a token credential request and use
a different cache and different client capabilities.
With this change, I'm able to run live and recorded tests using clientSecretCredential
with MSALClient backend!
=> [identity] MSALClient CAE support for confidentialClientApplication

sdk/identity/identity/package.json
Follows #28801 to use tsx for running identity tests, which avoids requiring the mocha workarounds
Using esm4mocha, but I think this is a good path forward to try
=> [identity] Use tsx for tests

sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts, sdk/identity/identity/test/internal/node/msalPlugins.spec.ts
Nightly test failures
Our nightly tests started failing with a `TypeError: Descriptor for property
generatePluginConfiguration is non-configurable and non-writable` error.
I'm far from an expert here, but I believe the error is due to ESModules being
immutable, whereas CJS Modules are mutable.
Wrapping the stubbable / mockable object is a reasonable workaround to keep
tests green regardless of whether they get run as ESM or CJS
Deleting the tests is an option, or an integration test. Neither seem to fit the
bill here. Once we have credentials migrated over we may be able to delete some
of the unit tests and rely on recorded tests to test the various scenarios. But
we are not there yet.
=> [identity] Fix nightly tests

.vscode/cspell.json, sdk/core/core-client/.tshy/browser.json, sdk/core/core-client/.tshy/commonjs.json, sdk/core/core-client/.tshy/esm.json, sdk/core/core-client/.tshy/react-native.json, sdk/core/core-client/package.json, sdk/core/core-client/src/operationHelpers.ts, sdk/core/core-client/src/state-browser.mts, sdk/core/core-client/src/state-cjs.cts, sdk/core/core-client/src/state.ts, sdk/core/core-client/vitest.config.ts
@azure/core-client
N/A, follow up on #28631 
If you are exporting both CommonJS and ESM forms of a package, then it is possible for both versions to be loaded at 
run-time. However, the CommonJS build is a different module from the ESM build, and thus a different thing from the
point of view of the JavaScript interpreter in Node.js.
https://github.com/isaacs/tshy/blob/main/README.md#dual-package-hazards
tshy handles this by building programs into separate folders and treats "dual
module hazards" as a fact of life.
One of the hazards of dual-modules is shared module-global state.
In core-clientwe have a module-global operationRequestMap that is used for deserializing. 
In order to ensure it works in this dual-package world we must use one of multiple-recommended
workarounds.
In this case, …
=> [core-client] Share state between ESM and CJS

common/tools/dev-tool/src/commands/run/testNodeJSInput.ts, common/tools/dev-tool/src/commands/run/testNodeTSInput.ts
Reverts back to the original for the testing ts-node for JS and TS.
- https://github.com/Azure/azure-sdk-for-js/pull/28801
=> [dev-tool] revert old files back to ts-node

sdk/keyvault/keyvault-admin/package.json, sdk/keyvault/keyvault-keys/package.json, sdk/keyvault/keyvault-secrets/package.json
- @azure/keyvault-keys
- @azure/keyvault-admin
- @azure/keyvault-secrets
Fixes the glob path issue with the upgrade to `rimraf` since there were extra calls to `rimraf` after the standard calls.
=> [keyvault] Fix rimraf globs for keyvault

common/config/rush/build-cache.json
The `azsdkjsrush` storage account has seemingly been deleted, so this will always fail and waste effort during CI.
Tracking issue for a full fix: #28865
=> [rush] [engsys] Disable build cache 

sdk/communication/communication-call-automation/assets.json, sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Add_a_participant_and_get_call_properties.json, sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Add_a_participant_cancels_add_participant_request.json, sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_List_all_participants.json, sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Mute_a_participant.json, sdk/communication/communication-call-automation/recordings/CallConnection_Live_Tests_Remove_a_participant.json, sdk/communication/communication-call-automation/recordings/CallRecording_Live_Tests_Creates_a_call,_start_recording,_and_hangs_up.json, sdk/communication/communication-call-automation/recordings/Call_Automation_Main_Client_Live_Tests_Create_a_call_and_hangup.json, sdk/communication/communication-call-automation/recordings/Call_Automation_Main_Client_Live_Tests_Reject_call.json, sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Cancel_all_media_operations.json, sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Play_audio_to_all_participants.json, sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Play_audio_to_target_participant.json, sdk/communication/communication-call-automation/recordings/Call_Media_Client_Live_Tests_Trigger_DTMF_actions.json, sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callAutomationClient.ts, sdk/communication/communication-call-automation/src/callAutomationEventParser.ts, sdk/communication/communication-call-automation/src/callMedia.ts, sdk/communication/communication-call-automation/src/eventprocessor/eventResponses.ts, sdk/communication/communication-call-automation/src/generated/src/models/index.ts, sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts, sdk/communication/communication-call-automation/src/generated/src/models/parameters.ts, sdk/communication/communication-call-automation/src/generated/src/operations/callConnection.ts, sdk/communication/communication-call-automation/src/generated/src/operations/callMedia.ts, sdk/communication/communication-call-automation/src/generated/src/operationsInterfaces/callMedia.ts, sdk/communication/communication-call-automation/src/models/events.ts, sdk/communication/communication-call-automation/swagger/README.md, sdk/communication/communication-call-automation/test/callAutomationClient.spec.ts, sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
Added the CreatCallFailed and AnswerFailed event.
This changed is tested against the Contoso app.
=> Adding the createFailed and AnswerFailed events on the call automation SDK

common/config/rush/pnpm-lock.yaml, sdk/monitor/perf-tests/monitor-opentelemetry/package.json, sdk/monitor/perf-tests/monitor-opentelemetry/test/index.spec.ts, sdk/monitor/perf-tests/monitor-opentelemetry/test/logExport.spec.ts, sdk/monitor/perf-tests/monitor-opentelemetry/test/metricExport.spec.ts, sdk/monitor/perf-tests/monitor-opentelemetry/test/spanExport.spec.ts, sdk/monitor/perf-tests/monitor-opentelemetry/tsconfig.json
- @azure-tests/perf-monitor-opentelemetry
Updates to latest OTEL packages
=> [monitor] Update to latest OTEL

eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-js-release.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-sdk-tests-isolated.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/stages/cosmos-sdk-client.yml, eng/pipelines/templates/stages/platform-matrix.json, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build.yml, eng/pipelines/templates/steps/test.yml, eng/pipelines/templates/variables/globals.yml, eng/pipelines/templates/variables/image.yml, sdk/communication/communication-phone-numbers/phone-numbers-livetest-matrix.json, sdk/keyvault/keyvault-admin/platform-matrix.json, sdk/keyvault/keyvault-certificates/platform-matrix.json, sdk/keyvault/keyvault-keys/platform-matrix.json, sdk/keyvault/keyvault-secrets/platform-matrix.json, sdk/template/template/tests.yml
This is the culmination of the last couple weeks of work to transition pipelines. [Python](https://github.com/Azure/azure-sdk-for-python/pull/34663) was our first repo migrated, and I haven't seen anything ship stopping from them yet!
If you see fallout due to this merge, please @ me on the [teams thread](https://teams.microsoft.com/l/message/19:344f6b5b36ba414daa15473942c7477b@thread.skype/1709939872585?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1709939872585&teamName=Azure%20SDK&channelName=Language%20%E2%80%93%20JS%E2%80%89%EF%BC%86%E2%80%89TS%20%F0%9F%A5%B7&createdTime=1709939872585).
- [Core](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3577021&view=results)
- …
=> 1ES Template Conversion

eng/tools/dependency-testing/templates/package.json
N/A
Build failures
`esm` is slowly becoming a larger problem for us and we've been on a mission to
remove it. min/max tests fail because esm is unable to handle safe-navigation
operators (?.) 
While a separate PR switches tests to use tsx, this PR focuses on min/max tests
and can be merged separately.
#28826
=> [EngSys] Use tsx for min/max testing

eng/pipelines/templates/stages/archetype-js-release.yml
Correcting some autoformatting stuff that was introduced in my `1es-template` PR.
There were two nightly failures:
- Failure in `Publish package to daily feed` (addressed by balancing quotes)
- Failure to run `PublishDocsToNightlyBranch` (addressed by updating `vmImage` -> `image` in the pool settings for the job.)
I have kicked a couple test builds:
- [Template Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3589129&view=results)
- [Template Release Nightly](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3589156&view=results)
=> Resolve failing `nightly` PublishDocs and PublishPackage

common/config/rush/pnpm-lock.yaml, sdk/monitor/monitor-opentelemetry-exporter/package.json, sdk/monitor/monitor-opentelemetry/package.json
`@azure/monitor-opentelemetry`
`@azure/monitor-opentelemetry-exporter`
`cross-env` was removed from the devdeps of monitor-opentelemetry and monitor-opentelemetry-exporter which causes pipeline failures when running the test pipeline since the integration test command uses this binary.
=> [monitor] Fix pipeline issue from missing dependency

sdk/core/core-lro/package.json
- `@azure/core-lro`
In the ESM migration it appears we accidentally removed the `files` section from package.json for this package, so the built and packed package includes everything including the source code. This PR restores the field in line with the other ESMified Core packages.
=> [core-lro] Restore `files` section to package.json

sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/sender.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts, sdk/monitor/monitor-opentelemetry/src/types.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/liveMetrics.test.ts
Fixed issue with quickpulse document duration
Fixed issue with miscalculation in dependency duration metric
Updated default quickpulse endpoint
=> [Azure Monitor OpenTelemetry] Live Metrics updates

sdk/test-utils/recorder/CHANGELOG.md
`@azure-tools/test-recorder`
#28667 
Releasing recorder 3.1.0 unblocks the #28667 that upgrades recorder to 4.0.0 with vitest.
=> [Recorder] Release recorder 3.1.0

sdk/openai/openai/assets.json, sdk/openai/openai/review/openai.api.md, sdk/openai/openai/sources/customizations/models/models.ts, sdk/openai/openai/src/models/models.ts, sdk/openai/openai/test/public/completions.spec.ts, sdk/openai/openai/test/public/utils/asserts.ts
=> [OpenAI]add index property

sdk/monitor/monitor-opentelemetry/CHANGELOG.md
=> [Azure Monitor OpenTelemetry] Update 1.3.0 CHANGELOG

sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/eventhub.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
Add support for AiDeviceId, AiDeviceModel and AiApplicationVer
Fix issue with AiUserId, this is not part of resource attributes
Removed deprecated references from @opentelemetry/semantic-conventions
=> [Azure Monitor OpenTelemetry Exporter] Add support for more Azure Monitor part A/tags

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md, sdk/core/core-rest-pipeline/src/policies/proxyPolicy.ts, sdk/core/core-rest-pipeline/test/node/proxyPolicy.spec.ts, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/policies/proxyPolicy.ts, sdk/core/ts-http-runtime/test/node/proxyPolicy.spec.ts
https://github.com/Azure/azure-sdk-for-js/issues/28951
When PR #28563 upgraded `http-proxy-agent` it didn't properly pass along `port` as this is now encoded in the proxy URL instead of the agent options.
This PR trims down the unnecessary parsing we are doing to turn the proxy URL into `ProxySettings`, preferring to pass the URL as-is to `http-proxy-agent` and avoid losing information. In cases where we receive `ProxySettings` we will convert it into a URL correctly.
For unknown historical reasons, `getDefaultProxySettings` was exposed as public surface, but since we no longer need this internally, I have marked it as deprecated so we may remove it in a later major version.
Existing tests were updated to validate the proxy URL being set correctly on the agent …
=> [core-rest-pipeline] Address issue with proxy port setting being ignored

eng/pipelines/npm-tasks.yml, eng/pipelines/templates/stages/1es-redirect.yml
See title.
[Test Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3615161&view=results) unpublishing a random manual test release of `@azure/template`.
=> Ensure NPM Task Job is `1es-template`-ized

sdk/core/abort-controller/CHANGELOG.md, sdk/core/abort-controller/package.json, sdk/core/core-auth/CHANGELOG.md, sdk/core/core-auth/package.json, sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/package.json, sdk/core/core-client/CHANGELOG.md, sdk/core/core-client/package.json, sdk/core/core-http-compat/CHANGELOG.md, sdk/core/core-http-compat/package.json, sdk/core/core-lro/CHANGELOG.md, sdk/core/core-lro/package.json, sdk/core/core-paging/CHANGELOG.md, sdk/core/core-paging/package.json, sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/package.json, sdk/core/core-rest-pipeline/vitest.browser.config.ts, sdk/core/core-sse/CHANGELOG.md, sdk/core/core-sse/package.json, sdk/core/core-tracing/CHANGELOG.md, sdk/core/core-tracing/package.json, sdk/core/core-util/CHANGELOG.md, sdk/core/core-util/package.json, sdk/core/core-util/vitest.browser.config.ts, sdk/core/core-xml/CHANGELOG.md, sdk/core/core-xml/package.json, sdk/core/logger/CHANGELOG.md, sdk/core/logger/package.json, sdk/core/ts-http-runtime/package.json, sdk/core/ts-http-runtime/vitest.browser.config.ts
For discussion. Re-adds "browser" field to `package.json` to support older bundlers that do not have support for the more modern "exports" field added in Node 14.
=> [core] Reinstate "browser" package.json field

sdk/eventhub/event-hubs/CHANGELOG.md, sdk/eventhub/event-hubs/src/models/public.ts, sdk/eventhub/event-hubs/src/util/retries.ts
N/A
One customer is complaining that the minimum wait of 60 seconds is too long and they wish to be able to lower it.
N/A
N/A
N/A
=> [Event Hubs] Remove minimum timeout value

common/tools/dev-tool/src/commands/run/testNodeJSInput.ts, common/tools/dev-tool/src/commands/run/testNodeTSInput.ts, common/tools/dev-tool/src/commands/run/testNodeTsxTS.ts, common/tools/dev-tool/src/commands/run/testVitest.ts
Invert the `no-test-proxy` option in our test run commands, creating a `test-proxy` option instead. The command line parsing library dev-tool uses, `minimist`, special cases CLI options starting with `--no-`, such that passing `--no-test-proxy` sets the `test-proxy` option to `false`, instead of setting the `no-test-proxy` option to `true` as our commands assume. This fix corrects that assumption by inverting the option.
Passing `--no-test-proxy` in to the run command, as many of our package.json scripts do, will work properly after this change.
=> [dev-tool] Fix `--no-test-proxy` option for test run commands

sdk/identity/identity-broker/README.md, sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/review/identity.api.md, sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts, sdk/identity/identity/src/msal/nodeFlows/brokerOptions.ts, sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts
Resolves #27390
Adds `useDefaultBrokerAccount` to `brokerOptions` and plumbs it through to the
InteractiveBrowserCredential. When the user enables this feature, brokered IBC will first
attempt to use the default OS account. If that fails, it falls back to the
existing behavior.
We desperately need to improve our test coverage, but we do not have IBC tests
today.
=> [identity] Add support for useDefaultBrokerAccount

sdk/test-utils/perf/CHANGELOG.md, sdk/test-utils/perf/package.json
To allow publishing to npm.
Followup of #28916
=> [Perf] Unmark "private"

sdk/test-utils/test-credential/CHANGELOG.md
- Publishing the current changes in `@azure-tools/test-credential` as version `1.0.2`.
- This allows upgrading to `2.0.0` to consume `@azure-tools/test-recorder@4.0.0` with the newer env settings.
- Added changelog
- Currently blocking the PR #28667 as this package depends on the older `@azure-tools/test-recorder` version `3.x.y`
=> [test-credential] Publish current version to npm

sdk/identity/identity-broker/package.json, sdk/identity/identity-broker/test/internal/node/interactiveBrowserCredential.spec.ts
`@azure/identity-broker`
Fixes #27779
A dev-time dependency for investigating a hang in a test was inadvertently left in the test code.
=> [identity-broker] remove unnecessary dev dependency

sdk/test-utils/test-credential/CHANGELOG.md, sdk/test-utils/test-credential/package.json
Types for `@azure/test-credential` were not published for `1.0.0` - `1.0.2` versions due to a configuration issue or an oversight during the publishing process. The builds might not have failed before because the missing types did not affect the build process.
Nonetheless, this change is in the right direction in ensuring the types are published correctly.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3625592&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=acc99708-be46-50ff-f197-4ecb2c3cab18&l=444
=> [test-credential] Publish types for `@azure/test-credential`

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/constants.ts, sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts
N/A - noticed in passing
When a user does not specify a cache name, we end up stringifying "undefined" as
the cache name. In addition, we prepend a `.` both in the constants and the
cache name. 
The resulting cache name ends up being `undefined..cae` or `undefined..nocae`
which is not what we want.
This PR fixes both of these issues and matches the MSAL cache name to the one
specified in @azure/identity-cache-persistence.
Sharing constants between packages may have been better to ensure consistency;
however, that seemed to be overkill for this. Since we _always_ set the cache
name and pass it into the plugin, the reality is that @azure/identity is the 
source of truth for how the files are named.
=> [identity] Fix default cache name

sdk/personalizer/ai-personalizer-rest/tests.yml
`@azure-rest/ai-personalizer`
With the [recent refactoring of test pipelines](https://github.com/Azure/azure-sdk-for-js/commit/ecdb45e61db7c965ee9aae8a7aa0d12f7b4f5012), some malformed configuration in this file started failing our live test pipelines. Specifically, the `Clouds` parameter, which is expected to be a string, was being passed as a literal causing the pipeline to fail.
=> [personalizer] Fix cloud selection in tests.yml

sdk/translation/ai-translation-text-rest/README.md
`@azure-rest/ai-translation-text`
Fix a broken link discovered by our pipelines. This was caused by a recent regeneration of this package from TSP as the source file link was no longer valid.
=> [ai-translation-text] fix broken link in README

eng/scripts/Language-Settings.ps1
This change is necessary to match change in Update-DocsMsMetadata.ps1 made in [this azure-sdk-tools PR](https://github.com/Azure/azure-sdk-tools/pull/7951).  The Get-javascript-DocsMsDevLanguageSpecificPackageInfo function is the implementation of the GetDocsMsDevLanguageSpecificPackageInfoFn. This is something that should have been called all the time but because javascript was the only language using this, Update-DocsMsMetadata.ps1 was only calling this if the packageInfo file's DevVersion was set. Because this needs to be called all the time, if it's defined for a given language, and javascript only needs process if the DevVersion is set, move that check to the implemented function.
=> Update Get-javascript-DocsMsDevLanguageSpecificPackageInfo in Language-Settings.ps1

sdk/notificationhubs/notification-hubs/CHANGELOG.md, sdk/notificationhubs/notification-hubs/package.json, sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md, sdk/notificationhubs/notification-hubs/src/models/notification.ts, sdk/notificationhubs/notification-hubs/src/models/notificationHeaderBuilder.ts, sdk/notificationhubs/notification-hubs/src/utils/constants.ts, sdk/notificationhubs/notification-hubs/test/public/unit/notification.spec.ts
- #28243
Adds overloads to the notification creation methods so that it accepts both a string of JSON but also an object which will be turned into JSON to allow for a more fluent approach.
```js
// Object
const templateNotification = createTemplateNotification({
body: { title: "(Hello title)", body: "Hello" },
});
// String
const templateNotification = createTemplateNotification({
body: `{"title":"(Hello title)","body":"Hello"}`,
});
```
=> [notification-hubs] Add builders for other message types

common/config/rush/pnpm-lock.yaml, sdk/schemaregistry/schema-registry-avro/package.json, sdk/schemaregistry/schema-registry-avro/src/avroSerializer.ts, sdk/schemaregistry/schema-registry-avro/test/public/avroSerializer.spec.ts, sdk/schemaregistry/schema-registry-json/package.json, sdk/schemaregistry/schema-registry-json/src/jsonSerializer.ts, sdk/schemaregistry/schema-registry-json/test/public/jsonSerializer.spec.ts
- @azure/schema-registry
- @azure/schema-registry-avro
- https://github.com/Azure/azure-sdk-for-js/issues/25221
Updates to latest `lru-cache`
=> [schema registry] Update LRU cache

.github/CODEOWNERS
Removes the .NET application insights SDK team from the exporter service attention and replaces it with the Node.js team.
=> Update CODEOWNERS for Exporter Service Attention

eng/pipelines/aggregate-reports.yml
aggregate report is broken due to azcopy can't do authorization by using AAD Workload Identity. https://github.com/Azure/azure-storage-azcopy/issues/2545
this is a workaround for this known issue
=> [aggregate-reports] Workaround for upload dependency report

sdk/core/core-client/src/authorizeRequestOnTenantChallenge.ts, sdk/core/core-client/test/authorizeRequestOnTenantChallenge.spec.ts
`@azure/storage-blob`
As reported by @EmmaZhu there are currently two issues when interacting with Azure Disk Storage.
The first is if you try to access a Storage account that is not properly configured to support bearer challenges. In that case an invalid `authorization_uri` will be returned. Our code currently makes assumptions about `authorization_uri`, specifically that it can 'split' the path part of the URL and reliably get a tenantId. In the case that a valid tenant is not found, the request can end up refreshing in an infinite loop. 
My solution to this problem is to actually check if what we think is a tenant id is a valid guid or not. Now in the case where we don't see the expected `authorization_uri`, we will allow the request to fail with the 401.
The second issue occurs when …
=> [storage] address two issues related to Azure Disk Storage

sdk/test-utils/test-credential/CHANGELOG.md, sdk/test-utils/test-credential/package.json
Listed types in package.json and files included for publishing were not in sync.
`"types": "types/tools-test-credential.d.ts"` vs `"types/latest/src"`
Needed to unblock #28667
=> [test-credential] Fix types

sdk/monitor/monitor-opentelemetry/perf-tests.yml
Perf project for monitor-opentelemetry
Perf pipeline for monitor-opentelemetry is failing due to a peer dependency issue.
Pinning `"@opentelemetry/api": 1.7.0`
=> [Perf] [monitor-opentelemetry] Fix perf pipeline

sdk/entra/functions-authentication-events/package.json, sdk/loadtesting/load-testing-rest/package.json, sdk/monitor/monitor-ingestion/package.json, sdk/storage/storage-blob/test/utils/testutils.common.ts, sdk/template/template-dpg/package.json, sdk/test-utils/test-utils/karma.conf.js, sdk/vision/ai-vision-image-analysis-rest/package.json
- Switch from ~ to ^ for `@azure-tools/test-credential` dependency
- Karma.conf update to `test-utils` package.
=> [test-credential] Cleanup tilde (~) in favor of caret (^) for @azure-tools/test-credential dependency

sdk/translation/ai-translation-text-rest/CHANGELOG.md, sdk/translation/ai-translation-text-rest/assets.json, sdk/translation/ai-translation-text-rest/karma.conf.js, sdk/translation/ai-translation-text-rest/review/ai-translation-text.api.md, sdk/translation/ai-translation-text-rest/src/custom/authentication.ts, sdk/translation/ai-translation-text-rest/src/custom/customClient.ts, sdk/translation/ai-translation-text-rest/src/index.ts, sdk/translation/ai-translation-text-rest/test/public/breakSentenceTest.spec.ts, sdk/translation/ai-translation-text-rest/test/public/translateTest.spec.ts, sdk/translation/ai-translation-text-rest/test/public/utils/recordedClient.ts
Text Translation SDK
Adding support for AAD authentication using Text Translation endpoints. Those endpoints require use of special header `Ocp-Apim-ResourceId` vs using custom endpoint.
=> [Text Translation] Adding support for AAD authentication

sdk/identity/identity-broker/package.json, sdk/identity/identity-cache-persistence/package.json, sdk/identity/identity-vscode/package.json
@azure/identity-cache-persistence
@azure/identity-broker
@azure/identity-vscode
Workaround for #29171 which will be the long term fix
Identity CI builds started failing because of build errors in identity-cache-persistence.
This is due to an implicit dependency on @azure/core-client via pulling in of source files from identity directly:
[example1](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity-cache-persistence/src/index.ts#L4)
[example2](https://github.com/Azure/azure-sdk-for-js/blob/1d60a7b672b3be6c51d0a07eafbad36862e6231d/sdk/identity/identity-cache-persistence/test/internal/node/clientSecretCredential.spec.ts#L7-L11)
Because the plugin packages have a runtime dependency on a published version of identity, they pull in source files directly from the source …
=> [identity] fix transitive dependency

sdk/test-utils/recorder/CHANGELOG.md, sdk/test-utils/test-credential/CHANGELOG.md
`@azure-tools/test-recorder` and `@azure-tools/test-credential` being published to npm.
https://github.com/Azure/azure-sdk-for-js/pull/29016 is blocked as vite is unable to pick up the local sources for recorder and instead falling back to the published npm version.
This PR helps publishing the v4 recorder and v2 test-credential, in an attempt to try if vite picks up these dependencies as expected.
=> [ESM] [Recorder] Prep releasing v4 recorder and v2 test-credential

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/export/sender.ts
Need to revert live metrics endpoint change.
=> [Monitor OpenTelemetry] Revert QuickPulse Endpoint Change

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/samples-dev/defaultAzureCredential.ts, sdk/identity/identity/src/credentials/defaultAzureCredential.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/models.ts, sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/28279
- IMDS probing retry configuration updated for `DefaultAzureCredential`, with `maxRetryCount` increased to 5.
- Allow IMDS probing retry options in MI Credential to be overridden by customers
- IMDS Probing for error 404 uses the same retry policy for other errors like 408, 500s (exponential retry policy from core)
=> [Identity] Update IMDS probing logic

sdk/openai/openai/review/openai-models.api.md, sdk/openai/openai/review/openai-rest.api.md, sdk/openai/openai/review/openai.api.md, sdk/openai/openai/src/models/models.ts, sdk/openai/openai/src/rest/outputModels.ts, sdk/openai/openai/test/internal/deserializer.spec.ts, sdk/openai/openai/test/public/utils/asserts.ts
@azure/openai
#28966
Expose the model property for ChatCompletions
=> [OpenAI] Expose model property for ChatCompletions

eng/pipelines/templates/stages/platform-matrix.json
=> downgrade node version for unit tests

common/config/rush/pnpm-lock.yaml
Test pipelines have been broken because of the min-max build test failure
https://github.com/Azure/azure-sdk-for-js/issues/29232
https://github.com/Azure/azure-sdk-for-js/issues/29246
This PR is the followup of the `@azure-tools/test-recorder@3.1.2` release that upgraded the min version of `core-client` to get the needed types https://github.com/Azure/azure-sdk-for-js/pull/29247
=> [Recorder] Recorder upgrade to 3.1.2 - rush update --full

common/config/rush/pnpm-lock.yaml, sdk/apimanagement/api-management-custom-widgets-tools/package.json
- @azure/api-management-custom-widgets-tools
Removes `@types/mime` as the types are now included by default.
=> [apimanagement] Remove @types/mime

sdk/apimanagement/api-management-custom-widgets-tools/package.json
This change is the result of running build. Looks the current path is incorrect
as the CJS build output is under ./dist/commonjs
=> [api management tool] fix "main" entry in package.json

sdk/storage/storage-blob/src/sas/BlobSASSignatureValues.ts
`@azure/storage-blob`
The docs comments uses the value 86400 i.e. number of seconds in a day, to add on the expiresOn example, which could incorrectly lead the reader (_totally not speaking from experience 👀_) to believe that they should just add however many seconds into the future they want, when instead they should be adding milliseconds.
=> [docs] Use correct unit for expiresOn examples

sdk/eventgrid/eventgrid-namespaces/README.md, sdk/eventgrid/eventgrid-namespaces/samples/v1-beta/javascript/README.md, sdk/eventgrid/eventgrid-namespaces/samples/v1-beta/javascript/package.json, sdk/eventgrid/eventgrid-namespaces/samples/v1-beta/typescript/README.md, sdk/eventgrid/eventgrid-namespaces/samples/v1-beta/typescript/package.json
@azure/eventgrid-namespaces
NA
The `@azure/eventgrid-namespaces` package has been pushed to main branch last week. For the initial push, the CI did not permit the links to be pointed to correct location (since the location is not available). This PR is to fix the links. 
Note: I am still waiting for the docs to be published. Once it is done, I will update those links
No special design considerations. Just changing links in Readme files
No. Textual changes in Readme file
https://github.com/Azure/azure-sdk-for-js/pull/29245
NA
=> [@azure/eventgrid-namespaces] Fix Links in samples

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/src/errors.ts, sdk/core/core-amqp/test/errors.spec.ts
Rhea expects an Error object
https://github.com/amqp/rhea/blob/2.0.8/lib/connection.js#L591 but some times it
gets an ErrorEvent instead from certain packages, ws for example
https://github.com/websockets/ws/blob/8.16.0/lib/event-target.js#L224
while rhea may be changed to unwrap the error from an ErrorEvent instance, this PR handles the ErrorEvent case in our code base since we have more control here.
https://github.com/Azure/azure-sdk-for-js/issues/29294
=> [core-amqp] Handle case of ErrorEvent being passed as Error to rhea

sdk/containerregistry/test-resources-post.ps1
Likely the Import-AzContainerRegistryImage powershell command now requires the TargetTag parameter.
=> [ACR][Test] fix failure in test resource deployment

sdk/core/core-rest-pipeline/package.json, sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts, sdk/core/core-rest-pipeline/src/util/file.ts, sdk/core/core-rest-pipeline/test/defaultLogPolicy.spec.ts, sdk/core/core-rest-pipeline/test/node/multipartPolicy.spec.ts, sdk/core/ts-http-runtime/src/createPipelineFromOptions.ts, sdk/core/ts-http-runtime/src/util/file.ts, sdk/core/ts-http-runtime/test/defaultLogPolicy.spec.ts
Use `isNodeLike` in favor of the deprecated `isNode` in Core packages that depend on `core-util`.
Eventually we should remove the deprecated `isNode` property from the unbranded Core. I have added this to the [unbranded breaking change wishlist](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21pY3Jvc29mdC5zaGFyZXBvaW50LmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlWcElZeko0WVc1ZloxVjFUWE4wUkU5RFIya3pTakkyUkVOUFoxWk9SVVpNYlV3NE9GRkRiR1ZLY0dwSldHbzRjMDFwUlVoVVdWUXRObTAwUmxkaVpEVW1aajB3TVVSSFJqSlBSVFJVUlUxUk5EZFNSa0UzV2tVeVQwWk9RMFEwVmxnMk5ESkZKbU05Sm1ac2RXbGtQVEUlM0QiLCJyIjpmYWxzZX0sInAiOnsidSI6Imh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQuY29tLzpmbDovci9zaXRlcy82MTU1NGI1Ni1jOTBiLTQ5NjEtYmE3Yy02MWNhYWUyMzUzMzUvU2hhcmVkJTIwRG9jdW1lbnRzL0xvb3BBcHB …
=> [core] Use isNodeLike

sdk/identity/identity/src/credentials/clientAssertionCredential.ts, sdk/identity/identity/src/credentials/clientCertificateCredential.ts, sdk/identity/identity/src/credentials/clientSecretCredential.ts, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/types.ts, sdk/identity/identity/test/internal/node/clientAssertionCredential.spec.ts, sdk/identity/identity/test/internal/node/clientSecretCredential.spec.ts, sdk/identity/identity/test/internal/node/workloadIdentityCredential.spec.ts
Resolves #28875 
Now that 4.1.0 is shipped we can merge this change which begins migrating credentials to the MSALClient pattern
and away from the MsalNodeCommon base class.
=> [identity] ClientSecretCredential, ClientCertificateCredential, ClientAssertionCredetial use MSALClient

eng/pipelines/templates/stages/archetype-js-release.yml, eng/scripts/Generate-APIView-CodeFile.ps1, eng/scripts/stage-api-review-file.ps1
Send a request to APIView to mark the package version as shipped in APIView after it's shipped from a release pipeline.
=> Mark JS pacakge as shipped in APIView after publishing the package

.github/CODEOWNERS
remove communication network traversal from codeowners to resolve ci failure https://dev.azure.com/azure-sdk/public/_build/results?buildId=3705411&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=259e4be2-1fd3-5c65-f373-9da11bbaf3b4&l=23
=> remove communication network traversal from codeowners

common/tools/dev-tool/package.json, common/tools/dev-tool/src/commands/run/testNodeTSInput.ts, sdk/cosmosdb/cosmos/package.json
All via dev-tool
esm is still being required in our test:node-ts-input and I don't believe it is
necessary. I'm removing it, but PLEASE do let me know what I'm missing - I don't
know much about mocha config to be honest.
=> [EngSys] Remove esm from default ts-node

sdk/servicebus/service-bus/test/internal/batchReceiver.spec.ts, sdk/servicebus/service-bus/test/internal/retries.spec.ts, sdk/servicebus/service-bus/test/internal/streamingReceiver.spec.ts, sdk/servicebus/service-bus/test/internal/streamingReceiverSessions.spec.ts, sdk/servicebus/service-bus/test/public/invalidParameters.spec.ts, sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts, sdk/servicebus/service-bus/test/public/sessionsTests.spec.ts
PR #28751 updates the message of thrown error from retry to include messages of all the retried errors. This PR fixes affected Service Bus tests.
=> [Test][ServiceBus] react to the retryable error change in core-amqp

common/tools/dev-tool/src/commands/about.ts, common/tools/dev-tool/src/commands/admin/list/packages.ts, common/tools/dev-tool/src/commands/package/resolve.ts, common/tools/dev-tool/src/commands/run/build-test.ts, common/tools/dev-tool/src/commands/run/bundle.ts, common/tools/dev-tool/src/commands/run/extract-api.ts, common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts, common/tools/dev-tool/src/commands/samples/publish.ts, common/tools/dev-tool/src/commands/samples/run.ts, common/tools/dev-tool/src/config/rollup.base.config.ts, common/tools/dev-tool/src/util/customization/customize.ts, common/tools/dev-tool/src/util/customization/helpers/preformat.ts, common/tools/dev-tool/src/util/pathUtil.ts, common/tools/dev-tool/src/util/samples/generation.ts, common/tools/dev-tool/src/util/testProxyUtils.ts, common/tools/dev-tool/test/customization/classes.spec.ts, common/tools/dev-tool/test/customization/interfaces.spec.ts
- use `unknown` for catch variable type
- suppress error where `any` is desired
=> [dev-tool] Resolve linter errors

sdk/textanalytics/ai-text-analytics/package.json
Skipping unit tests in text analytics to unblock recorder v3 release 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3708215&view=logs&j=f3d84248-526b-5c53-c1d9-c908a2c076cb&t=a08660e7-0c74-50b6-45ab-0cb70a5776f5
This is expected and is needed for the spring grove efforts.
=> [Recorder] v3 - echo skipped to bypass the failures caused by central sanitizers

sdk/storage/storage-file-share/package.json, sdk/textanalytics/ai-text-analytics/package.json
Skipping unit tests in text analytics to unblock recorder v3 release
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3711559&view=logs&j=69104f8e-b88e-5d11-595c-90fd5e8e65ca&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=4ba20f2a-6568-5c82-27d3-3f34c36a0661&l=994
This is expected and is needed for the spring grove efforts.
=> [Storage-file] Skip browser tests temporarily

common/tools/dev-tool/src/commands/run/testNodeTSInput.ts
Some packages have the option in .mocharc but this is more centralized.  Packages whose tests haven't been migrated to vitest yet still need this.
=> [engsys] modular packages need ts-node/esm loader to run tests

common/config/rush/pnpm-lock.yaml, sdk/communication/communication-identity/package.json
as @azure/msal-node v1 has been deprecated.
=> [communication-identity] upgrade dependency @azure/msal-node to ^2.7.0

sdk/eventgrid/eventgrid-namespaces/CHANGELOG.md, sdk/eventgrid/eventgrid-namespaces/package.json, sdk/eventgrid/eventgrid-namespaces/review/eventgrid-namespaces.api.md, sdk/eventgrid/eventgrid-namespaces/src/constants.ts, sdk/eventgrid/eventgrid-namespaces/src/index.ts, sdk/eventgrid/eventgrid-namespaces/test/public/eventGridNamespacesClient.spec.ts
@azure/eventgrid-namespaces
No
The requirement is to add the `EventGridDeserializer` with the namespaces SDK.
No special design considerations.
Yes
https://github.com/Azure/azure-sdk-for-js/pull/29245
=> [@azure/eventgrid-namespaces] Include EventGridDeserializer with namespaces

sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts, sdk/identity/identity/test/internal/node/msalPlugins.spec.ts
Resolves #28872
Two things are addressed in this PR:
1. Complete porting over the logic for MSAL broker plugin to MSALClient by
adding support for legacyMSAPassthrough
2. Improve logging for MSALClient and establish some patterns
=> [identity] Add consumer_passthrough support to MSALClient and improve logging

sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/regionalAuthority.ts
Resolves #29066
ClientSecretCredential, ClientCertificateCredential, and ClientAssertionCredential are the only three
that support the AZURE_REGIONAL_AUTHORITY_NAME  today via the msalNodeCommon flow. 
Just for feature parity I am adding this to the same 3 credentials that
supported it before, and no other ones. I'll create an issue to investigate
whether we can remove the support entirely.
_not_ port it over, and see if anyone cares. If they do it's easy to fix and
they would only be 1p teams
=> [identity] Migrate regional authority support to MSALClient

sdk/notificationhubs/notification-hubs/CHANGELOG.md, sdk/notificationhubs/notification-hubs/review/notification-hubs-models.api.md, sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md, sdk/notificationhubs/notification-hubs/samples-dev/sendDirectNotification.fcmV1.ts, sdk/notificationhubs/notification-hubs/src/api/listRegistrationsByChannel.ts, sdk/notificationhubs/notification-hubs/src/models/notificationBodyBuilder.ts, sdk/notificationhubs/notification-hubs/src/utils/registrationUtils.ts, sdk/notificationhubs/notification-hubs/test/internal/unit/registrationUtils.spec.ts
- #29404
- #29371
- #29372
- Fixes the issue with creating a wrapper around the entire FCM V1 notification body to include `message`.
- Changes the data types of the `data` properties from `Record<string, any>` to `Record<string, string>`.
- Fixes the `listRegistrationsByChannel` to include `fcmv1` as a parameter to query for devices.
Added unit tests for the helper for `listRegistrationsByChannel` to validate the query string returned.
=> [notification-hubs] Fix FCMV1 bugs for notification creation and list registrations

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/package.json, sdk/identity/identity/src/constants.ts
=> [identity] Prepare identity for May release

rush.json
Noticed in passing, `rush install` now outputs this warning:
```
Warning: Please remove the obsolete "variants" field from your rush.json file. 
Installation variants have been replaced by the new Rush subspaces feature. 
In the next major release, Rush will fail to execute if this field is present.
```
Might as well fix that now
=> [EngSys] Remove obsolete variants field from rush.json

common/tools/dev-tool/src/util/testProxyUtils.ts, sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json, sdk/communication/communication-common/package.json, sdk/core/core-amqp/package.json, sdk/eventhub/event-hubs/package.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json, sdk/iot/iot-modelsrepository/package.json, sdk/keyvault/keyvault-admin/test/public/utils/common.ts, sdk/keyvault/keyvault-common/package.json, sdk/monitor/monitor-opentelemetry-exporter/package.json, sdk/monitor/monitor-opentelemetry/package.json, sdk/openai/openai/package.json, sdk/openai/openai/samples-dev/audioTranscription.ts, sdk/openai/openai/samples-dev/audioTranslation.ts, sdk/openai/openai/samples-dev/bringYourOwnData.ts, sdk/openai/openai/samples-dev/chatCompletions.ts, sdk/openai/openai/samples-dev/completions.ts, sdk/openai/openai/samples-dev/getEmbeddings.ts, sdk/openai/openai/samples-dev/getImages.ts, sdk/openai/openai/samples-dev/openAi.ts, sdk/openai/openai/samples-dev/streamChatCompletions.ts, sdk/openai/openai/samples-dev/streamChatCompletionsWithContentFilter.ts, sdk/openai/openai/samples-dev/streamCompletions.ts, sdk/openai/openai/samples-dev/toolCall.ts, sdk/servicebus/service-bus/package.json, sdk/storage/storage-internal-avro/package.json, sdk/test-utils/test-utils/package.json, sdk/web-pubsub/web-pubsub-client-protobuf/package.json, sdk/web-pubsub/web-pubsub-client/package.json, sdk/web-pubsub/web-pubsub-express/package.json
The "=true" part is no longer needed after PR #28978
=> [EngSys] shorten `-no-test-proxy=true` test option

sdk/communication/communication-sms/CHANGELOG.md, sdk/communication/communication-sms/package.json
Can't release beta 1.2.0 version because of addition of version 1.1.1 to Changelog by bot.
n/a
n/a
=> [Communication] - SMS - Removed version 1.1.1 from CHANGELOG.md

sdk/notificationhubs/notification-hubs/CHANGELOG.md, sdk/notificationhubs/notification-hubs/review/notification-hubs-models.api.md, sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md, sdk/notificationhubs/notification-hubs/src/models/notificationBodyBuilder.ts
- #29465
Fixes the right signatures for the FCM versus FCM Legacy.
=> [notification-hubs] Fix FCMV1 bugs

sdk/openai/openai-assistants/review/openai-assistants-models.api.md, sdk/openai/openai-assistants/review/openai-assistants.api.md, sdk/openai/openai-assistants/src/index.ts, sdk/openai/openai-assistants/src/models/models.ts
Fix #29473 
#29473 
Add fileIds to Thread messages
=> [OpenAI] [Assistants] Add fileIds to Thread messages

sdk/identity/identity/samples/AzureIdentityExamples.md, sdk/identity/identity/src/credentials/azurePipelinesServiceConnectionCredential.ts, sdk/identity/identity/test/public/node/azurePipelinesServiceConnection.spec.ts
- Testing whether OIDC API 7.1 is available or not. Unfortunately, it's not available. So we only ship a preview with 7.1-preview.1
Response = {"$id":"1","innerException":null,"message":"The requested version \"7.1\" of the resource is under preview. The -preview flag must be supplied in the api-version for such requests. For example: \"7.1-preview\"","typeName":"Microsoft.VisualStudio.Services.WebApi.VssInvalidPreviewVersionException, Microsoft.VisualStudio.Services.WebApi","typeKey":"VssInvalidPreviewVersionException","errorCode":0,"eventId":3000}
=> [Identity] Testing service connections on pipeline

common/tools/dev-tool/src/commands/run/testVitest.ts, sdk/core/core-http-compat/vitest.config.ts, sdk/core/core-lro/vitest.config.ts, sdk/core/core-paging/vitest.config.ts, sdk/core/core-sse/vitest.config.ts, sdk/core/core-tracing/vitest.config.ts, sdk/core/core-util/vitest.config.ts, sdk/core/core-xml/vitest.config.ts, sdk/core/ts-http-runtime/vitest.config.ts
We should use `=== -1` which means not found.
While at this, also fix result file names for NodeJS tests.
=> [dev-tool] fix test:vitest browser config issue

sdk/openai/openai-assistants/review/openai-assistants-api.api.md, sdk/openai/openai-assistants/review/openai-assistants-rest.api.md, sdk/openai/openai-assistants/src/api/operations.ts, sdk/openai/openai-assistants/src/rest/models.ts
#29500 only updated the types, not the actual operations
With #29500 PR, the `fileIds` type is added, but the actual operations (`createThread` and `createThreadAndRun`) are still missing the `file_ids` property in the message objects.
This PR adds `file_ids` to both of these two operations.
Additionally, there are some other fixes:
* The `AssistantThreadCreationOptions` in `rest/models.ts` was not updated along with #29500 PR.
* The `AssistantThreadCreationOptions` type in `api/operations.ts` was incorrectly importing from `rest/index`, instead it should be importing from `models/models`.
=> [OpenAI] [Assistants] Add `file_ids` to Thread operations.

sdk/core/core-util/CHANGELOG.md
This particular GitHub issue doesn't exist. Not sure why it started failing the link verification. It is possible that this file somehow evaded checking.
=> [doc][core-util] remove broken link

sdk/template/template/package.json
Template browser tests are broken (tracked by issue #29538).  This PR skips it to unblock CI.
=> [Test] skip template browser tests to unblock `js - core - ci` pipeline

sdk/core/core-tracing/samples/v1/javascript/basicTracing.js, sdk/core/core-tracing/samples/v1/javascript/package.json, sdk/core/core-tracing/samples/v1/typescript/package.json, sdk/core/core-tracing/samples/v1/typescript/src/basicTracing.ts, sdk/core/core-tracing/samples/v1/typescript/tsconfig.json
Regenerates samples to fix any formatting issues as well as remove the `type: module` specifier as we are not generating ESM for our samples.
Resolves #29521
=> [core] regen tracing samples

common/tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
- fix false positive when there are no comments at all. There may be some internal cache nodes in the array but they don't hold any comments.
- instead of showing squiggles for whole declaration body, only report on the id node if its available.
=> [eslint-plugin] improve ts-doc-internal UX experience

eng/tools/rush-runner.js
- storage has moved to core v2. the template package already covers core v2.
- remove ai-text-analytics which is another core v2 package.
- add a RLC package @azure-rest/synapse-access-control
- remove service-bus from identity's list as it doesn't use any identity functionality in CI tests.
- remove storage from test-util CI since core v2 is already covered by ai-text-analytics
- remove perf-data-tables as perf-storage-blob covers core v2
=> [engsys][test] reduce dependency test packages in core pipelines

eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/steps/test.yml
intead of dumping the output to the console, since
- the time to output to console could be several minutes when the log file is big
- viewing the step in azure devops webste takes long time to render for big file
it's better to have it as an artifact. We don't often need to look at the log
unless there's test proxy some issue to investigate.
=> [EngSys] upload test proxy logs to artificats from pipelines

sdk/web-pubsub/web-pubsub-client/CHANGELOG.md, sdk/web-pubsub/web-pubsub-client/package.json, sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts, sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts
In the previous RP, we found a bug that if sequenceId == 0, then it won't be sent to the service. Which means if no message is received from the service, there won't be a keepalive enabled
Yes
=> [webpubsubclient] Fix a bug that 0 sequenceId won't be sent to service

eng/pipelines/templates/steps/npm-release-task.yml
EsrpRelease@6 required a custom service connection that held an aad app secret in its configuration. The latest version, EsrpRelease@7, uses a standard ARM service connection, moving most of the configuration settings (KeyVaultName, AuthCertName ...) from the custom connection into the task itself.
=> Upgrade to a version ESRP Release that supports federated auth

sdk/core/core-amqp/package.json
similar to other core packages, we don't need selfLink as we uses "paths" in
tsconfig to map the package to .src/index.ts
=> [core-amqp] disable tshy selfLink

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md, sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts, sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts, sdk/core/core-rest-pipeline/src/util/sanitizer.ts, sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/createPipelineFromOptions.ts, sdk/core/ts-http-runtime/src/policies/tracingPolicy.ts, sdk/core/ts-http-runtime/src/util/sanitizer.ts, sdk/core/ts-http-runtime/test/tracingPolicy.spec.ts
@typespec/ts-http-runtime
Resolves #29433
Tracing spans capture the url as an attribute. A customer noticed that URLs are
not sanitized correctly in Java - specifically the QS params.
This was fixed in Java and will now be fixed in JS. It could be considered a
breaking change; however, the OTEL instrumentation package is still in beta and
as this should have been sanitized earlier we can consider this a bugfix.
I could duplicate the Sanitizer#sanitizeUrl method; however, I wanted to make
sure I can take advantge of the default query params if the list is ever
updated.
=> [core] Sanitize URLs in tracing policy

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/assets.json, sdk/identity/identity/src/credentials/deviceCodeCredential.ts, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/test/internal/node/deviceCodeCredential.spec.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
Resolves #29377 
This PR makes the following changes to the Identity library:
1. Migrates DeviceCodeCredential to the MSALClient flow
2. Skips silent authentication for client credential based flows
3. Allows passing disableAutomaticAuthentication as an option param instead of during client construction
The reason this is important and exciting is because DeviceCodeCredential is the first PublicClientApplication based
flow that is being migrated to MSALClient!
=> [identity] DeviceCodeCredential uses MSALClient

sdk/resources/arm-resources/config/rush-project.json, sdk/servicebus/service-bus/config/rush-project.json, sdk/template/template/config/rush-project.json, sdk/template/template/package.json, sdk/test-utils/recorder/package.json
Build cache was enabled for most of our commonly built packages in PR
https://github.com/Azure/azure-sdk-for-js/pull/27409.
This PR enables build cache for several more packages that get built in core -
ci pipelines to further reduce time on packages when they haven't changed.
=> [EngSys] enable build cache for more packages in core - ci pipelines

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/metricUtil.test.ts, sdk/monitor/monitor-opentelemetry/src/metrics/types.ts
Performance counter names should be converted from OpenTelemetry valid names to the those appropriate for breeze to avoid OTel warnings.
Yes, in the `metricUitl.tests.ts`.
=> [Monitor OpenTelemetry Exporter] Add Performance Counter Name Mapping

sdk/test-utils/recorder/CHANGELOG.md, sdk/test-utils/recorder/package.json, sdk/test-utils/recorder/src/sanitizer.ts, sdk/test-utils/recorder/src/utils/fallbackSanitizers.ts, sdk/test-utils/recorder/src/utils/paths.ts
`@azure-tools/test-recorder@3.4.0`
- Added support for the TestProxy/removeSanitizers API, to support the removing the central sanitizers by id at the test-proxy level.
Cherrypicking from #29661
=> [Recorder] RemoveSanitizers API to 3.4.0 hotfix

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/assets.json, sdk/identity/identity/src/credentials/usernamePasswordCredential.ts, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts, sdk/identity/identity/test/internal/node/usernamePasswordCredential.spec.ts, sdk/identity/identity/test/msalTestUtils.ts, sdk/identity/identity/test/node/msalNodeTestSetup.ts, sdk/identity/identity/test/public/node/usernamePasswordCredential.spec.ts
Resolves #29409 
Migrates UsernamePasswordCredential to the MSALClient flow, simplifying the implementation.
=> [identity] Migrate UsernamePasswordCredential to MSALClient

sdk/core/core-rest-pipeline/src/util/tokenCycler.ts, sdk/core/core-rest-pipeline/test/bearerTokenAuthenticationPolicy.spec.ts, sdk/core/ts-http-runtime/src/util/tokenCycler.ts, sdk/core/ts-http-runtime/test/bearerTokenAuthenticationPolicy.spec.ts
`core-rest-pipeline`
`ts-http-runtime`
https://github.com/Azure/azure-sdk-for-js/issues/29608
When debugging a recent issue from Storage, it was reported that in the case of the tokenCycler being unable to retrieve a new access token from a CAE challenge, it would fall back to delaying for the maximum lifetime of the current (invalid) access token instead of failing immediately.
This change improves the robustness of this scenario by invaliding the existing cached token when claims are received.
Yes, I added a test and confirmed it was timing out before the fix was added.
=> [core-rest-pipeline] Improve robustness of tokenCycler

sdk/cognitivelanguage/ai-language-conversations/tests.yml
to fix samples run in live tests.  It would have been nicer if the same set of variables are used for both tests and samples. However the names in samples are better customer-facing and this PR is a simple and straightforward fix.
=> [Test] add environment variables that is needed by samples

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callMedia.ts, sdk/communication/communication-call-automation/src/models/options.ts, sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
[User Story 3576848](https://skype.visualstudio.com/SPOOL/_workitems/edit/3576848): [Beta4][CA SDK][JS] Update SDK with the interrupt call media flag for Play api
1.Added beta4 interruptCallMediaOperation to playToAll.
2.Unit test.
=> Added beta4 interruptCallMediaOperation to playToAll.

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callAutomationEventParser.ts, sdk/communication/communication-call-automation/src/callMedia.ts, sdk/communication/communication-call-automation/src/models/events.ts, sdk/communication/communication-call-automation/src/models/options.ts, sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
[User Story 3586532](https://skype.visualstudio.com/SPOOL/_workitems/edit/3586532): [JS][SDK][Beta4] Node Audio streaming Sdk
1.StartMediaStreaming.
2.StopMediaSteaming.
3.Unit Test.
4.Media streaming events.
=> Added beta4 audio streaming apis and events.

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callAutomationEventParser.ts, sdk/communication/communication-call-automation/src/models/events.ts
Added beta4 PlayStarted event in event parser.
=> Added Beta4 PlayStarted Event.

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callMedia.ts, sdk/communication/communication-call-automation/src/models/options.ts, sdk/communication/communication-call-automation/test/callMediaClient.spec.ts
[User Story 3667737](https://skype.visualstudio.com/SPOOL/_workitems/edit/3667737): [Beta4][JS][SDK] Update the SDK according to Azure Board's comments.
HoldOptions update operationCallbackUri to operationCallbackUrl
=> Beta4 HoldOptions update operationCallbackUri to operationCallbackUrl

sdk/search/search-documents/CHANGELOG.md, sdk/search/search-documents/assets.json, sdk/search/search-documents/package.json, sdk/search/search-documents/src/generated/data/models/index.ts, sdk/search/search-documents/src/searchIndexingBufferedSender.ts, sdk/search/search-documents/src/serviceUtils.ts, sdk/search/search-documents/test/public/node/searchClient.spec.ts, sdk/search/search-documents/test/public/node/searchIndexClient.spec.ts, sdk/search/search-documents/test/public/utils/setup.ts
A small refactor of tests to support 2024-05 test cases
Designed to be reviewed on a per-commit basis.
Depends on #29600
=> [Search] Refactor tests

sdk/notificationhubs/notification-hubs/package.json, sdk/notificationhubs/notification-hubs/samples-dev/sendDirectNotification.fcmV1.ts
Fixes the sample to ensure that the data is payload is using `Record<string, string>` instead of `Record<string, unknown>`.
=> [notification-hubs] Fix FCM V1 Sample

sdk/notificationhubs/notification-hubs/CHANGELOG.md, sdk/notificationhubs/notification-hubs/review/notification-hubs-models.api.md, sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md, sdk/notificationhubs/notification-hubs/src/models/notificationDetails.ts, sdk/notificationhubs/notification-hubs/src/serializers/notificationDetailsSerializer.ts, sdk/notificationhubs/notification-hubs/test/internal/unit/notificationDetailsSerializer.spec.ts
Adds parsing for `BrowserOutcomeCounts` and `FcmV1OutcomeCounts` to the notification response details.
=> [notification-hubs] Adding FCMv1 to Notification Outcomes

common/config/rush/pnpm-lock.yaml, sdk/identity/identity/assets.json, sdk/identity/identity/package.json, sdk/identity/identity/test/node/msalNodeTestSetup.ts, sdk/identity/identity/test/public/node/tokenProvider.spec.ts, sdk/identity/test-resources-pre.ps1
Re-enabled tests in playback mode, including better filtering in live mode to skip the MI tests
=> [identity] Re-enable tests

common/tools/dev-tool/src/commands/run/bundle.ts, common/tools/dev-tool/src/util/resolveProject.ts, sdk/test-utils/test-utils/package.json
@azure-tools/test-utils
Resolves #29736
When @azure-tools/test-utils moves to `npm` it will no longer default to the on-disk version of core-tracing. This impacts our `supportsTracing` test helper as it no longer sets the instrumenter on the same version as the client package. Imagine this flow:
In this case, test-util and app-configuration are not talking to the same "module global" instrumenter. 
This PR fixes this by removing core-tracing from test-utils, setting it as a peerDependency instead. All packages that test tracing also implement tracing, and as such are already depending on core-tracing.
This was verified locally, but I'll need to get it out to NPM before verification can complete
See #29709 for a few alternatives:
1. Pass the instrumenter through
2. Use mocks
Both require …
=> [test-util] Move core-tracing to peerDependencies

common/config/rush/pnpm-lock.yaml, common/tools/eslint-plugin-azure-sdk-helper/package.json, common/tools/eslint-plugin-azure-sdk/package.json
also explicitly set module type to "commonjs".  This follows what `typescript-eslint` does.
=> [engsys] upgrade typescript-eslint dependency to ~7.10.0

.github/CODEOWNERS
Added correct aliases for Application Insights
Removed # ServiceLabel: %Monitor - Exporter %Service Attention, # PRLabel: %Monitor already exists for OTel and Exporter with correct owners
=> [Azure Monitor] Update codeowners for Monitor OpenTelemetry

common/config/rush/pnpm-lock.yaml, sdk/test-utils/test-utils/CHANGELOG.md, sdk/test-utils/test-utils/package.json
Updates @azure-tools/test-utils to 1.0.2 since 1.0.1 has been published to NPM
already.
Also, run rush update --full to ensure everyone is on the repo-source version of
test-utils until we can fix the NPM version.
=> [test-util] Update package version

common/tools/dev-tool/src/commands/run/bundle.ts, common/tools/dev-tool/src/util/resolveProject.ts, sdk/test-utils/test-utils/package.json
This reverts commit 11da2154832fdaba7fc1a62590d6285f779960ca.
Unfortunately, rush does not play well with peerDeps and I am bumping into https://github.com/microsoft/rushstack/issues/1415
I really wanted this to work but rather than continue going down this path I think it's safer to revert and find an alternative
given the issues with rush and pnpm
=> Revert "[test-util] Move core-tracing to peerDependencies (#29775)"

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/browserSdkLoader/browserSdkLoader.ts, sdk/monitor/monitor-opentelemetry/src/shared/config.ts, sdk/monitor/monitor-opentelemetry/src/traces/sampler.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
Currently setting a 0 sampling ratio will fall back to the default sampling ratio of 1.
Yes
=> [Monitor OpenTelemetry] Fix Zero Sampling Ratio

eng/pipelines/docindex.yml
The msdocs-apidrop-connection service connection will replace the azuresdk-apidrop-devops-queue-build-pat that was being used to kick off runs.
The docindex run was run against this refs/merge for both testing and also initial approval of the service connection.
=> Use the service connection instead of PAT to kick off docs CI runs

sdk/monitor/monitor-ingestion/CHANGELOG.md, sdk/monitor/monitor-ingestion/README.md, sdk/monitor/monitor-ingestion/package.json, sdk/monitor/monitor-ingestion/review/monitor-ingestion.api.md, sdk/monitor/monitor-ingestion/src/constants.ts, sdk/monitor/monitor-ingestion/src/index.ts, sdk/monitor/monitor-ingestion/src/logsIngestionClient.ts, sdk/monitor/monitor-query/CHANGELOG.md, sdk/monitor/monitor-query/README.md, sdk/monitor/monitor-query/package.json, sdk/monitor/monitor-query/review/monitor-query.api.md, sdk/monitor/monitor-query/src/constants.ts, sdk/monitor/monitor-query/src/index.ts, sdk/monitor/monitor-query/src/logsQueryClient.ts, sdk/monitor/monitor-query/src/metricsClient.ts, sdk/monitor/monitor-query/src/metricsQueryClient.ts, sdk/monitor/perf-tests/monitor-query/package.json
1. @azure/monitor-ingestion
2. @azure/monitor-query
1. [#27280](https://github.com/Azure/azure-sdk-for-js/issues/27280) 
2. [#28821](https://github.com/Azure/azure-sdk-for-js/issues/28821) 
In order to support sovereign clouds, we must be able to allow the SDK users to specify the endpoints and audience parameters. The users could already  specify/modify the endpoint parameter. This PR will enable the users to do the same for audience.
No special design concerns to discuss.
https://github.com/Azure/azure-sdk-for-js/pull/22887/
@KarishmaGhiya @srnagar Please review and approve the PR.
@xirzec FYI
=> [@azure/monitor-query] Provide sovereign cloud support for monitor SDKs

common/config/rush/pnpm-lock.yaml, sdk/web-pubsub/web-pubsub-express/.eslintrc.json, sdk/web-pubsub/web-pubsub-express/.tshy/build.json, sdk/web-pubsub/web-pubsub-express/.tshy/commonjs.json, sdk/web-pubsub/web-pubsub-express/.tshy/esm.json, sdk/web-pubsub/web-pubsub-express/api-extractor.json, sdk/web-pubsub/web-pubsub-express/package.json, sdk/web-pubsub/web-pubsub-express/samples-dev/server.ts, sdk/web-pubsub/web-pubsub-express/samples-dev/tsconfig.json, sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts, sdk/web-pubsub/web-pubsub-express/src/index.ts, sdk/web-pubsub/web-pubsub-express/src/utils.ts, sdk/web-pubsub/web-pubsub-express/src/webPubSubEventHandler.ts, sdk/web-pubsub/web-pubsub-express/test/connect.spec.ts, sdk/web-pubsub/web-pubsub-express/test/connected.spec.ts, sdk/web-pubsub/web-pubsub-express/test/ctor.spec.ts, sdk/web-pubsub/web-pubsub-express/test/disconnected.spec.ts, sdk/web-pubsub/web-pubsub-express/test/user.spec.ts, sdk/web-pubsub/web-pubsub-express/test/validate.spec.ts, sdk/web-pubsub/web-pubsub-express/tsconfig.json, sdk/web-pubsub/web-pubsub-express/vitest.config.ts
- @azure/web-pubsub-express
Updates to ESM via `tshy` and moves from Mocha/Chai/Sinon to `vitest`
=> [web pub sub] update express to ESM

sdk/servicebus/service-bus/src/core/managementClient.ts, sdk/servicebus/service-bus/test/public/sessionsTests.spec.ts
After upgrading to `@azure/abort-controller` v2, some tests that verify the
abort error messages have been failing. It turns out that in our async
operations because multiple callbacks are attached to the same abort signal (for
example, retry logic, delay calls for timeout, authentication, auto
lock-renewing, etc.) and multiple abort errors are thrown reacting to their
signal being aborted. After upgrading to `@azure/abort-controller` v2, the order
of `AbortError`s being thrown have changed thus the error we catch in the test
is now different from the one before upgrading. It is possible that our previous
`AbortContoller` implementation of parent-children aborter pattern implies
certain ordering which is different from when manually attaching callbacks.
However, what's important to the …
=> [ServiceBus] Remove verification of abort error messages in tests

sdk/web-pubsub/web-pubsub-express/.eslintrc.json, sdk/web-pubsub/web-pubsub-express/package.json
`@azure/web-pubsub-express`
Doing a rebuild of this package leaves `package.json` in a dirty state.
=> [webpubsub] missing changes from build

sdk/test-utils/recorder/CHANGELOG.md, sdk/test-utils/recorder/src/sanitizer.ts, sdk/test-utils/recorder/test/sanitizers.spec.ts
`@azure-tools/test-recorder@3.x`
and all the packages relying on it
Ported from #29897
Fixes connectionStringSanitizer regression stemmed from batch sanitizers migration, where the request bodies are incorrect.
=> Ported from #29897 - conn string sanitizer fix

sdk/test-utils/recorder/CHANGELOG.md, sdk/test-utils/recorder/src/sanitizer.ts, sdk/test-utils/recorder/test/sanitizers.spec.ts
`{    target : value   }` being sent to test proxy instead of `  {  target: target, value: value  } `
Regression happened when we migrated to batch sanitizers.
Added a couple of tests as well to make sure the requests are hit at the test-proxy level and it doesn't error out.
=> [Recorder] Fixes connectionStringSanitizer regression - incorrect bodies

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/README.md, sdk/monitor/monitor-opentelemetry/src/metrics/utils.ts, sdk/monitor/monitor-opentelemetry/src/shared/config.ts, sdk/monitor/monitor-opentelemetry/test/utils/basic.ts
* We should align with the spec and enable live metrics by default.
* Update our semantic convention imports.
=> [Monitor OpenTelemetry] Enable Live Metrics by Default

.github/CODEOWNERS
CODEOWNERS
Add Simar as an owner to the Azure Monitor OpenTelemetry Distro & Exporter.
=> [CODEOWNERS] Add Simar to codeowners for the Azure Monitor distro & exporter

sdk/communication/communication-chat/assets.json, sdk/communication/communication-chat/test/public/utils/recordedClient.ts
1. remove central sanitizer "AZSDK4001", // url need not be sanitized, fake conn string handles it already
2. Predictable `const fakeToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTc2MzQ4MDguMTd9.Rx6RqlnKsM09viqebSbPDKRcUp3EIKDEHNVXq3Wb0ms";`
3. New `NoOpAzureCommunicationTokenCredential` that implements `AzureCommunicationTokenCredential` and extends `NoOpCredential`
=> Fix playback for communication-chat SDK

sdk/identity/identity/test/internal/node/msalClient.spec.ts, sdk/identity/identity/test/public/node/clientCertificateCredential.spec.ts
#29929
Identity relies on a set of static resources for some of its tests. The
cert/secret for one of these resources expired and we cannot renew the
credentials until we use test / ephemeral tenants.
This PR skips those tests in live mode as per our discussion with the Identity
feature crew
=> [identity] Skip expired cert tests

common/tools/dev-tool/src/commands/admin/list/esm-migrations.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-apiextractor-json-types.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-files-required.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-main-is-cjs.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-module.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-types.ts, common/tools/eslint-plugin-azure-sdk/src/utils/index.ts, common/tools/eslint-plugin-azure-sdk/src/utils/verifiers.ts, sdk/.eslintrc.json, sdk/apimanagement/api-management-custom-widgets-scaffolder/.eslintrc.json, sdk/apimanagement/api-management-custom-widgets-tools/.eslintrc.json, sdk/core/abort-controller/.eslintrc.json, sdk/core/core-amqp/.eslintrc.json, sdk/core/core-paging/.eslintrc.json, sdk/core/core-paging/package.json, sdk/core/core-util/.eslintrc.json, sdk/core/ts-http-runtime/.eslintrc.json, sdk/devcenter/developer-devcenter-rest/.eslintrc.json, sdk/face/ai-vision-face-rest/.eslintrc.json, sdk/web-pubsub/web-pubsub-express/.eslintrc.json
as packages using tshy has been migrated to ESM and these rules no longer apply to them.
This PR skip these rules to avoid having to turn them off for individual packages.
We could remove these rules too. Although it's still nice to have them before we migrage all packages to ESM with tshy.
=> [eslint-plugin] skip some package json linting for packages using tshy

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/authorizationCodeCredential.ts, sdk/identity/identity/src/credentials/deviceCodeCredential.ts, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
Resolves #29406
Following the existing patterns, this PR migrates AuthorizationCodeCredential to
the MSALClient, moving away from MSALNodeCommon
It's a tricky flow to test end-to-end; however, I plan to add tests either here
or in a follow-up PR where possible.
=> [identity] Migrate AuthorizationCodeCredential to MSALClient

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts, sdk/monitor/monitor-opentelemetry/CHANGELOG.md
Currently only server Span error event will generate Exception telemetry in Application Insights, client spans are generating Trace telemetry by default, we should suppress this, as this data is not useful for customers.
Yes, added test cases for each of the control paths related to the span event envelope creation logic.
=> [Monitor OpenTelemetry Exporter] Client Exception Span Events Should Not Create Trace Telemetry

sdk/servicebus/service-bus/CHANGELOG.md, sdk/servicebus/service-bus/src/core/linkEntity.ts, sdk/servicebus/service-bus/src/session/messageSession.ts
This PR fixes a memory leak in `MessageSession.createRheaLink` where in error cases we didn't
close the created `rhea-promise` receiver.  Eventually this would lead to
client exceeding the quota on maximum allowed links on a connection.
The fix is to close the created receiver before we throw errors.
=> [ServiceBus] close link before throwing error in createRheaLink()

sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
Resolves #29888
Now that all credentials have been either migrated or a PR opened with their
migration we can narrow down the type of MsalClientOptions to just the used
options.
In the future, we can further refine this by:
- Renaming tokenCredentialOptions to "identityClientOptions"
- Bucket brokerOptions and persistenceOptions under "pluginOptions"
Etc. 
But the goal here is to just have a new definition of used properties so it can
be refined in the future.
I could do the above recommendations now, but I'd rather keep the scope small if
possible.
Just a refactor
=> [identity] Define MsalClientOptions

sdk/core/core-lro/test/lro.spec.ts
fixes https://github.com/Azure/azure-sdk-for-js/issues/29634
=> Fix the build issue in core-lro testing

common/config/rush/pnpm-lock.yaml, sdk/communication/communication-messages-rest/package.json
Resolves dependabot alerts and ensure the repo is on 4.2.1
=> [communication] Use Identity 4.2.1

sdk/core/abort-controller/package.json, sdk/core/core-amqp/package.json, sdk/core/core-auth/package.json, sdk/core/core-client-rest/package.json, sdk/core/core-client/package.json, sdk/core/core-http-compat/package.json, sdk/core/core-lro/package.json, sdk/core/core-paging/package.json, sdk/core/core-rest-pipeline/package.json, sdk/core/core-rest-pipeline/src/util/userAgentPlatform.ts, sdk/core/core-rest-pipeline/test/browser/userAgentPlatform.spec.ts, sdk/core/core-rest-pipeline/test/node/userAgentPlatform.spec.ts, sdk/core/core-sse/package.json, sdk/core/core-tracing/package.json, sdk/core/core-util/package.json, sdk/core/core-xml/package.json, sdk/core/logger/package.json, sdk/core/ts-http-runtime/package.json, sdk/core/ts-http-runtime/src/util/userAgentPlatform.ts, sdk/core/ts-http-runtime/test/browser/userAgentPlatform.spec.ts, sdk/core/ts-http-runtime/test/node/userAgentPlatform.spec.ts
- #29997
Checks for undefined `process` and `process.versions`.  Added unit tests.
=> [core] Fix platform specific data with tests

sdk/communication/communication-chat/CHANGELOG.md, sdk/communication/communication-chat/package.json, sdk/core/core-lro/test/lro.spec.ts
@Azure/communication-chat 
Customer escalated the issue:
The issue was introduced from the @azure/communication-chat@1.4.0.  Chat client updated the internal API client by generating the new service client version with the `endpoint` param to replace the `baseUri` and kept the dependency version  @azure/core-client@1.3.0 and higher. While the `endpoint` is introduced only in @azure/core-client@1.6.0.
Customer see error "baseUrl is not specified" if the dependency version not updated.
Update the @azure/core-client version to fix the issue
=> Updated core client version to fix the base uri conflict

eng/common/spelling/package-lock.json
Reverts Azure/azure-sdk-for-js#30003
This change needs to be made in azure-sdk-tools repo to ensure the eng/common directory remains in-sync.
fyi @xirzec
=> Revert "Bump braces from 3.0.2 to 3.0.3 in /eng/common/spelling"

sdk/newrelicobservability/arm-newrelicobservability/test/newrelicobservability_operations_test.spec.ts.ts
@azure/arm-newrelicobservability
None
On June 6, 2024, an issue was reported by Manik Khandelwal as the `rushx build` command is failing for the `@azure/arm-newrelicobservability` SDK. The following error is reported:
```
test/newrelicobservability_operations_test.spec.ts.ts(56,7): error TS2353: Object literal may only specify known properties, and 'clientId' does not exist in type 'CreateTestCredentialOptions'.
test/newrelicobservability_operations_test.spec.ts.ts(60,56): error TS2554: Expected 0-1 arguments, but got 2.
```
This PR has been created to fix this issue. 
Looking at the root cause of the issue, the current code changes in the `newrelicobservability_operations_test.spec.ts.ts` (with client id & client secret) are added on March 21, 2024 (Refer …
=> [@azure/arm-newrelicobservability] Fix the Test Case

eng/tools/dependency-testing/index.js, eng/tools/dependency-testing/templates/package.json, eng/tools/dependency-testing/templates/vitest.dependency-test.config.ts
by writing a copy of vitest config file to the test/public project and update
related commands to run vitest.
This PR addresses NodeJs only.
Related issue: https://github.com/Azure/azure-sdk-for-js/issues/29867
=> [dependency-test] support packages that moved to vitest

sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts, sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/metrics/utils.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standardMetrics.test.ts
Fixes #29398
Success/failure on standard metrics collection for dependencies and requests should follow the spec:
< 400 is success
Updated test cases that already use the dividing line between success/failure (status code 400)
=> [Monitor OpenTelemetry] Update Success/Failure Status Codes for Standard Metrics

.github/CODEOWNERS, sdk/storage/storage-blob/package.json, sdk/storage/storage-file-datalake/package.json, sdk/storage/storage-file-share/package.json, sdk/storage/storage-file-share/test/fileserviceclient.spec.ts, sdk/storage/storage-queue/package.json
=> [storage] Fixed issue of not be able to update package version in release pipeline

common/config/rush/pnpm-lock.yaml, sdk/communication/communication-chat/CHANGELOG.md, sdk/communication/communication-chat/assets.json, sdk/communication/communication-chat/package.json, sdk/communication/communication-chat/test.env, sdk/communication/communication-chat/test/public/utils/recordedClient.ts
@Azure/communication-chat 
Customer escalated the issue:
The issue was introduced from the @azure/communication-chat@1.4.0.  Chat client updated the internal API client by generating the new service client version with the `endpoint` param to replace the `baseUri` and kept the dependency version  @azure/core-client@1.3.0 and higher. While the `endpoint` is introduced only in @azure/core-client@1.6.0.
Customer see error "baseUrl is not specified" if the dependency version not updated.
Update the @azure/core-client version to fix the issue
=> Update the Core Client Version and Test Recorder

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/review/opentelemetry-instrumentation-azure-sdk.api.md, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/configuration.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumentation.browser.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumentation.ts
#27510
In order to onboard to OTel's auto-instrumentation-node metapackage we need to
export the instrumentation class directly in order to add ourselves to the
[map](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/src/utils.ts#L95) of instrumentations.
Avoiding breaking changes by continuing to export the factory function ensures
that Azure Monitor is not impacted.
It's possible that OTel does not accept a PR with a 3rd party dependency - if
that's the case we may end up deprecating this package in favor of a new one
under the OTel namespace
=> [instrumentation] Export the instrumentation class directly

common/tools/dev-tool/src/util/samples/info.ts, common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/tsconfig.json, common/tools/dev-tool/test/samples/files/expectations/output-customization/typescript/tsconfig.json, common/tools/dev-tool/test/samples/files/expectations/simple/typescript/tsconfig.json, common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/tsconfig.json, common/tools/dev-tool/test/samples/files/expectations/special-characters/typescript/tsconfig.json, sdk/servicebus/service-bus/samples/v7/javascript/advanced/sessionRoundRobin.js, sdk/servicebus/service-bus/samples/v7/javascript/package.json, sdk/servicebus/service-bus/samples/v7/typescript/package.json, sdk/servicebus/service-bus/samples/v7/typescript/tsconfig.json
Sample source structure used to be flat but later nested directories are supported as well. This PR fix the glob pattern to also include sub directories.
- also re-publish samples for @azure/service-bus
I didn't update all the other samples as there are no complaints. They can get new update in their next publish.
=> [dev-tool] fix samples typescript source to include sub directory

.github/CODEOWNERS
so that they are not overriden by general /common/ entry.
=> [CODEOWNERS] move more specific /common/tools entries after /common/ entry

common/tools/dev-tool/src/commands/admin/index.ts, common/tools/dev-tool/src/commands/admin/migrate-package.ts, common/tools/dev-tool/src/templates/sampleReadme.md.ts
Creates a starter migration toolkit for projects to move to ESM and vitest.  This project for dev-tool introduces a tool invoked such as the following to migrate service-bus
```
dev-tool admin migrate-package --package-name=@azure/service-bus
```
This does the following:
- Changes the package.json for the following:
- Removes chai/mocha/karma
- Adds vitest and tshy
- Modifies the build and test commands
- Renames the mapped files to the proper output type such as `-browser.mts`
- Changes the tsconfig.json for the following:
- Moves module and moduleResolution to NodeNext
- Removes outDir and declarationDir
- Fixes the source files
- Uses extension for files such as "foo.js" instead of "foo"
- Removes "chai" usage
- Adds vitest usage for spec files
- Fixes …
=> [dev-tool] Create migration tool

.github/CODEOWNERS_baseline_errors.txt
Remove a defunct error from the CODEOWNERS baseline error file.
This error no longer exists in the azure-sdk-for-js repository.
=> Remove defunct error from baseline file

eng/tools/dependency-testing/index.js
as packages not migrated yet would be broken when they build using tsc
and the *config.ts are included as source.
=> [dependency-test] only add vitest config for migrated packages

common/tools/dev-tool/src/commands/admin/migrate-package.ts
Adds updates for the following:
- Changes assert to only use `vitest` for now and not sure the `@azure-tools/test-utils`
- Any utility in the `/test` folders will be updated to use `vitest` for assertions
- Add `beforeEach`, `afterEach`, `vi` and `expect` to any test class using `sinon` for easy replacement
- Fix pathing issue so that `import { foo } from "..";` is translated to `import { foo } from "../index.js";`
- Removes `source-map-support` as we're not using Karma.
=> [dev-tool] Add additional fixes for the migration tool

sdk/test-utils/recorder/src/recorder.ts
In most scenarios our SDK doesn't use or depend on this header.
=> [test-recorder] ignore `Accept-Encoding` header

common/tools/eslint-plugin-azure-sdk-helper/package.json, common/tools/eslint-plugin-azure-sdk/package.json, sdk/cosmosdb/cosmos/package.json, sdk/identity/identity-broker/package.json
to fix broken nightly pipelines where we update `@azure` package versions to
nightly versions and dependency versions to a range for their nightly versions.
Version `^3.0.0` would not get updated because of the following check in
`set-dev.js` then `rush install` would fail to find matching one and report error.
https://github.com/Azure/azure-sdk-for-js/blob/9488fe4bd780306e2f00eaa1509eba20982215f4/eng/tools/versioning/set-dev.js#L80
=> [eslint-plugin] set package version back to 3.0.0

sdk/core/core-rest-pipeline/src/util/userAgentPlatform-browser.mts, sdk/core/core-rest-pipeline/test/browser/userAgentPlatform.spec.ts, sdk/core/ts-http-runtime/src/util/userAgentPlatform-browser.mts, sdk/core/ts-http-runtime/test/browser/userAgentPlatform.spec.ts
Adds support for capturing the browser name and version from the `userAgentData` in addition to the OS data we already capture.
=> [core] Adding Browser and Version to platform data

common/tools/dev-tool/src/commands/admin/migrate-package.ts
Fixed the `beforeEach` statements to get rid of the Mocha `Context` and replace with `vitest` context and fixes the test-recorder creation.
=> [dev-tool] Update migration tool to include beforeEach fixes

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/package.json, sdk/core/core-client-rest/review/core-client.api.md, sdk/core/core-client-rest/src/common.ts, sdk/core/core-client-rest/src/sendRequest.ts, sdk/core/core-client-rest/test/sendRequest.spec.ts, sdk/core/core-rest-pipeline/CHANGELOG.md
Proposal to mitigate a couple of breaking changes between the old and new `core-client` packages:
- `onResponse` is now called when an error is thrown while sending the request. This was not being done by `core-client-rest` but [is being done by `core-client`
](https://github.com/Azure/azure-sdk-for-js/blob/9f03724468521497f8499907433a715b062a9884/sdk/core/core-client/src/serviceClient.ts#L217-L229).
- Updated the type of the `onResponse` callback to be more backwards-compatible with the old Core. The old Core's callback had three parameters (response, flatResponse, and error), but the new package has only two (response and error). The `flatResponse` property does not make sense in the new Core and we have decided not to support this property. In order to …
=> [core] Provide `error` parameter to onResponse callback

sdk/servicebus/service-bus/test/internal/managementClient.spec.ts
This particular error message was updated in PR #29853 but the test wasn't and
since it's a live test, the CI didn't catch it. This PR fixes the test failure
by updating the expected error message.
=> [Test][ServiceBus] update expected error message

sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json, sdk/apimanagement/api-management-custom-widgets-tools/package.json, sdk/devcenter/developer-devcenter-rest/package.json, sdk/face/ai-vision-face-rest/package.json, sdk/notificationhubs/notification-hubs/package.json, sdk/template/template/package.json, sdk/test-utils/recorder/package.json, sdk/web-pubsub/web-pubsub-express/package.json
Run `rush build` on the repo to ensure the newly added `source` fields are
generated.
This avoids unnecessary noise on PRs that may build tshy packages as part of
their dependency graph (such as #29374)
=> [engSys] Run rush build

sdk/core/core-rest-pipeline/src/util/userAgentPlatform-browser.mts, sdk/core/ts-http-runtime/src/util/userAgentPlatform-browser.mts
Adds additional browsers for detection.
=> [core] Adding additional browsers to detection list

eng/pipelines/templates/jobs/live.tests.yml
Needed to ensure the variables are set when running in a Windows context
=> Set AZURESUBSCRIPTION_CLIENT_ID and AZURESUBSCRIPTION_TENANT_ID

eng/pipelines/templates/jobs/live.tests.yml
Our samples currently use `DefaultAzureCredential` to authenticate the client. This causes a problem running samples live in the pipeline because Managed Identity does not work in the live pipeline. This is a short term work around: we create a fake authority host so that Managed Identity fail and it will succeed with the new credentials.
We do not want to change the samples to use a different credentials because we want our customers to use DAC. We are discussing a long-term solution by potentially adding exclude managed identity property similar to Python/ .NET
=> [Eng] Update Env Var for Execute Samples Task

sdk/storage/storage-queue/review/storage-queue.api.md, sdk/storage/storage-queue/src/QueueClient.ts
It was lost in our previous code refactoring and caused TypeScript compilation
errors.
Related issue: #30101
=> [storage-queue] add back missing `abortSignal` option

.github/CODEOWNERS
The issue tracking system works in a way that more specific paths override more general ones. This means that a rule like `/sdk/ @xirzec` will be overridden by a more specific rule like `/sdk/foo @someOwner` when assigning issues.
~~However, when considering required reviewers based on CODEOWNERS, GitHub does *not* take this approach, leading to the catch-all person needing to approve *all* reviews that touch that path.~~
This creates a problem when introducing a new service folder as nobody is assigned to approve it. To avoid myself becoming the bottleneck in such cases, we can add the group to this line as it does not have notifications enabled. I also added more approvers for `rush.json` which is affected by new package generation.
=> [CODEOWNERS] Avoid bottleneck in CODEOWNERS

sdk/eventhub/event-hubs/CHANGELOG.md, sdk/eventhub/event-hubs/src/eventPosition.ts, sdk/eventhub/event-hubs/test/internal/eventPosition.spec.ts, sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
Fixes https://github.com/Azure/azure-sdk-for-js/issues/30056
The earliest position definition should be `-1:-1`.
N/A
N/A
N/A
=> [Event Hubs] Fix earliest definitiion

.github/CODEOWNERS
since apparently I can't approve PRs for this package (not sure if there's anyone else we would want to add?)
=> [CODEOWNERS] Add timovv as code owner for core-client-rest

sdk/eventhub/eventhubs-checkpointstore-table/karma.conf.js
@azure/eventhubs-checkpointstore-table
https://github.com/Azure/azure-sdk-for-js/issues/30222
> polyfill.io, a popular JavaScript library service, can no longer be trusted and should be removed from websites.
Source: [https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet)
We can replace the URL with one from Fastly, Cloudflare or self-host it. Replacing the CDN link with Cloudflare seemed like a fast option.
There aren't any changes done to the actual code. The replaced library is also 100% compatible with existing one.
N/A
=> fix(eventhub): replace `polyfill.io` with Cloudflare equivalent

sdk/core/core-rest-pipeline/src/util/userAgentPlatform-browser.mts
`localNavigator` may be `undefined` at L69.
core-rest-pipeline
https://github.com/lobehub/lobe-chat/issues/3037
`localNavigator` may be undefined at L69.
=> [core-rest-pipeline] Update userAgentPlatform-browser.mts to fit undefined localNavigator

eng/emitter-package-lock.json, eng/emitter-package.json
upgrade typespec-ts to 0.30.1 to fix
=> upgrade emitter

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml
our `rush update --full` automation introduced a compilation error due to
https://github.com/microsoft/ApplicationInsights-JS/issues/2369
This PR pins its version to 1.1.2 until the issue is fixed.
=> [EngSys] temporarily pin @microsoft/applicationinsights-web-snippet version

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
#30230
As part of the MSALClient migration we need to continue supporting cross-tenant
federation.
This PR addressed that scenario by ensuring we always recalculate the authority
using the same logic we do initially but using the secondary tenant as input.
=> [identity] Fix support for cross-tenant federation

common/tools/dev-tool/src/commands/admin/migrate-package.ts
of
>/datadrive/git/jssdk/common/tools/dev-tool/src/commands/admin/migrate-package.ts
242:45  error  Unnecessary escape character: \i  no-useless-escape
=> [dev-tool] fix linting error

common/tools/eslint-plugin-azure-sdk/src/rules/ts-apiextractor-json-types.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-files-required.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-main-is-cjs.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-module.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-types.ts, common/tools/eslint-plugin-azure-sdk/src/utils/index.ts, common/tools/eslint-plugin-azure-sdk/src/utils/verifiers.ts
Previously it was checking the existence of .tshy directory. Now that we removed
all .tshy the code is broken.  This PR updates to check the package.json instead.
=> [eslint-plugin] update to check whether package is ESM

eng/tools/generate-doc/index.ts, eng/tools/generate-doc/package.json
upgrade `typedoc` version to ^0.26.3 to support typescript 5.5
=> [EngSys] fix generate-doc installation error

sdk/keyvault/keyvault-admin/test/public/backupClient.abort.spec.ts, sdk/keyvault/keyvault-admin/test/public/backupClient.spec.ts, sdk/keyvault/keyvault-admin/tests.yml, sdk/keyvault/keyvault-certificates/tests.yml, sdk/keyvault/keyvault-keys/tests.yml, sdk/keyvault/keyvault-secrets/tests.yml, sdk/keyvault/test-resources-post.ps1, sdk/keyvault/test-resources.json
`@azure/keyvault-admin`
`@azure/keyvault-keys`
`@azure/keyvault-certificates`
`@azure/keyvault-secrets`
#29699
Migrates keyvault packages to use federated credentials and the test credential.
Re-recording tests is something I have seen folks do but the tests all pass unchanged (probably because we only changed AAD traffic) so I did not re-record
#29833
=> [keyvault] Migrate to federated credentials

sdk/core/core-client/src/serviceClient.ts
from ServiceClient constructor ref doc.
=> [Doc][core-client] remove outdated `@param credential`

sdk/eventgrid/eventgrid-namespaces/package.json
It is used in run time so should be in "dependencies" instead.
@azure/eventgrid-namespaces
=> [eventgrid-namespaces] move core-client to direct dependencies list

sdk/core/core-rest-pipeline/src/util/sanitizer.ts, sdk/core/core-rest-pipeline/test/sanitizer.spec.ts, sdk/core/ts-http-runtime/src/util/sanitizer.ts, sdk/core/ts-http-runtime/test/sanitizer.spec.ts
when `url` key has a value of empty string.
Associated issues: https://github.com/Azure/azure-sdk-for-js/issues/30291 https://github.com/Azure/azure-sdk-for-js/issues/30304
=> [core] fix ERR_INVALID_URL in sanitizer

sdk/core/core-rest-pipeline/src/util/userAgentPlatform-browser.mts, sdk/core/ts-http-runtime/src/util/userAgentPlatform-browser.mts
currently the property only holds a string `edge-runtime` but in the future
hopefully it would contain more useful info.
while at it also port PR https://github.com/Azure/azure-sdk-for-js/pull/30194 to ts-http-runtime
-------
`@azure/core-rest-pipeline`, `@typespec/ts-http-runtime`
=> [core] add EdgeRuntime telemetry info

sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/log.test.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts
Fix failing exporter test for logs.
=> [Monitor OpenTelemetry Exporter] Fix OTel Version and Resolve Async Issues with Logs Test

eng/tools/generate-doc/index.ts
We have shared source code directories like storage-common which are not real packages. They
now cause latest `typedoc` to crash.  We don't have a usage scenario so this PR
skips directories that don't have a package name.
=> [generate-doc] skipping doc generation for non-package files

sdk/storage/storage-common/src/index.ts
Not exactly sure what changes cause this error:
>[node-tests]  Exception during run: ../storage-common/src/index.ts(4,1): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
It seems to only happen for shared source when running unit tests and could be
related to `tsx` loader since normal tsc build works fine.
This PR change `export *` to export items explicitly.
-------
`@azure/storage-*`
=> [Storage] fix broken unit-test after typescript 5.5.3 upgrade

sdk/identity/identity/README.md
Don't pin the samples link to the v2 folder. Instead, drop the reader in the main samples directory and allow them to select a version/sample folder.
=> Update Samples link in Azure Identity README

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml
Now that https://github.com/microsoft/ApplicationInsights-JS/issues/2369 has
been fixed.
Revert "[EngSys] temporarily pin @microsoft/applicationinsights-web-snippet version (#30233)"
This reverts commit 1df8d78576a952f7f6a8aabb6cc0e4fcdd02d6a9.
=> [EngSys] unpin @microsoft/applicationinsights-web-snippet version

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/package.json, sdk/core/core-client-rest/src/sendRequest.ts, sdk/core/core-client-rest/test/sendRequest.spec.ts
Currently, all request body that has content types that start with "application/json" will be serialized by the `getRequestBody` function. This is an issue for Schema Registry because the request body has already been serialized and the content type also starts with "application/json". Reordering the serialization method to check for `Uint8Array` before checking for "application/json" would eliminate this problem.
- Add an option called `skipSerialization` in the internal options bag for sending request. It'll affect the RLC experience and force the customer to use this option to make a successful request 
- Check for specific content types. It'll be limited in scope and affect other services that also has a similar content type format
=> [core-client-rest] Update Serialization Check Logic

common/tools/vite-plugin-browser-test-map/package.json, common/tools/vite-plugin-browser-test-map/src/index.ts
@azure/-tools/vite-plugin-browser-test-map
N/A
The type declaration file wasn't set in package.json and the return type of the plugin function was too permissive causing type errors when imported.
N/A
N/A
N/A
=> [Vite Browser Map] Fix types

common/tools/dev-tool/tsconfig.json, sdk/appconfiguration/app-configuration/tsconfig.json, sdk/core/logger/tsconfig.json, sdk/eventhub/event-hubs/tsconfig.json, sdk/eventhub/eventhubs-checkpointstore-blob/tsconfig.json, sdk/eventhub/eventhubs-checkpointstore-table/tsconfig.json, sdk/eventhub/mock-hub/tsconfig.json, sdk/servicebus/service-bus/tsconfig.json
It helps old JS runtimes that only support ES 5 but we moved to ES 6 long time ago
and now moved to ES2017.  Most of our packages don't have this option. This PR
removes its usage.
=> [EngSys] remove `downlevelIteration` typescript option

eng/pipelines/run-for-all-packages.yml
to lint and build all packages.  This can be used to valid changes that touches
large number of files, and are skipping CIs.
=> [EngSys] add a pipeline that can be manually triggered

sdk/identity/test-resources-pre.ps1, sdk/identity/test-resources.bicep
N/A nightly failures
on 7/1 AKS released a new patch version, but we have the older version hardcoded. As a result, deploy-test-resources started failing.
This PR updates the test-resources-pre script to fetch the latest available AKS version.
=> [identity] Fix build failures

sdk/eventhub/event-hubs/CHANGELOG.md, sdk/eventhub/event-hubs/package.json, sdk/eventhub/event-hubs/src/eventPosition.ts, sdk/eventhub/event-hubs/src/util/constants.ts, sdk/eventhub/event-hubs/test/internal/eventPosition.spec.ts, sdk/eventhub/eventhubs-checkpointstore-blob/package.json
N/A
The service doesn't recognize the GeoDR representation of earliest position causing tests to fail. This PR reverts this change for now until the service is updated.
N/A
N/A
https://github.com/Azure/azure-sdk-for-js/pull/30191/
=> [Event Hubs] Revert GeoDR earliestPosition change

vitest.shared.config.ts
To enable typechecking test suites, otherwise type errors will go silent. See https://vitest.dev/config/#typecheck
=> Add typechecking to vitest.shared.config.ts

sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json, sdk/apimanagement/api-management-custom-widgets-scaffolder/rollup.config.bin.mjs
so that rush doesn't treat successful builds as completed with warnings
-------
@azure/api-management-custom-widgets-scaffolder
=> [apimanagement] remove console.log from bundling command output

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/client/identityClient.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/imdsRetryPolicy.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/legacyMsiProvider.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/msalMsiProvider.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/tokenExchangeMsi.ts, sdk/identity/identity/test/internal/node/azureApplicationCredential.spec.ts, sdk/identity/identity/test/internal/node/managedIdentityCredential/imdsRetryPolicy.spec.ts, sdk/identity/identity/test/internal/node/managedIdentityCredential/msalMsiProvider.spec.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
Resolves #25253
With MSAL implementing Managed Identity via the ManagedIdentityApplication, we
want to migrate our existing legacy implementation to use MSAL instead.
This PR:
- Creates a msalMsiProvider that implements the MSAL MSI flow
- Moves ManagedIdentityCredential to use msalMsiProvider under the hood
Some implementation details:
- TokenExchangeMsi is _not_ supported by MSAL and we expect to continue
supporting it as a special handler
- IMDS probing is _not_ supported by MSAL and we expect to continue probing and
failing-fast as a special handler
#30045
1. Every scenario runs against GA identity and this PR
2. Every scenario runs using DAC and MI directly
|scenario|result|notes|
|---|----|----|
|Azure VM|pass||
|Azure Kubernetes|pass|only user assigned MI so far| …
=> [identity] Use MSAL for Managed Identity

eng/pipelines/templates/stages/platform-matrix.json
temporarily pinning npm 22 to 22.4.0 to adress issue #30445
=> pin npm to 22.4.x

eng/pipelines/templates/stages/archetype-sdk-tests.yml
When we enable Federated Auth, `ServiceConnection` is a required parameter in `AzurePowerShell@5` task. Without this variable, the Deploy Test Resources tasks will fail. This PR aims to set this variable by default for the `Preview` cloud.
=> [Eng Sys] Update default config for preview cloud for live tests

sdk/identity/identity/integration/AzureKubernetes/Dockerfile, sdk/identity/test-resources-post.ps1
@azure/identity 
We're getting rate-limited by dockerhub - this PR switches to use mcr's mirror for our CI pipeline.
=> [identity] Use MCR for as docker registry

sdk/vision/ai-vision-image-analysis-rest/CHANGELOG.md, sdk/vision/ai-vision-image-analysis-rest/README.md, sdk/vision/ai-vision-image-analysis-rest/assets.json, sdk/vision/ai-vision-image-analysis-rest/review/ai-vision-image-analysis.api.md, sdk/vision/ai-vision-image-analysis-rest/src/clientDefinitions.ts, sdk/vision/ai-vision-image-analysis-rest/src/imageAnalysisClient.ts, sdk/vision/ai-vision-image-analysis-rest/src/isUnexpected.ts, sdk/vision/ai-vision-image-analysis-rest/src/models.ts, sdk/vision/ai-vision-image-analysis-rest/src/outputModels.ts, sdk/vision/ai-vision-image-analysis-rest/src/parameters.ts, sdk/vision/ai-vision-image-analysis-rest/src/responses.ts, sdk/vision/ai-vision-image-analysis-rest/test/public/AnalysisTests.spec.ts, sdk/vision/ai-vision-image-analysis-rest/test/public/utils/clientMethods.ts, sdk/vision/ai-vision-image-analysis-rest/test/public/utils/recordedClient.ts
@azure-rest/ai-vision-image-analysis
N/A
Re-generated the client to pick up a TypeSpec change that added EntraID support.
Added test case for above.
Modified readme to show use of DefaultAzureCredential
Yes.
https://github.com/Azure/azure-rest-api-specs/pull/28482
=> Add EntraID support to ImageAnalysis RLC

sdk/communication/arm-communication/sample.env, sdk/communication/communication-alpha-ids/tests.yml, sdk/communication/communication-call-automation/tests.yml, sdk/communication/communication-chat/tests.yml, sdk/communication/communication-common/tests.yml, sdk/communication/communication-identity/tests.yml, sdk/communication/communication-rooms/tests.yml, sdk/communication/communication-short-codes/tests.yml, sdk/communication/communication-tiering/tests.yml, sdk/communication/test-resources/test-resources.json
Changes:
In order to move away from Secret based authentication, we want to adopt FIC.
For the same azure-sdk team has added the support and we need to use service connection for our live test pipelines to access our test resources.
=> Use federated auth for ACS SDKs

.github/CODEOWNERS
to js team because we need to add projects for management packages and ignore links to documents that are not ready yet.
also remove `/**/tsconfig.strict.json` entry. It was added for we did migration work for cosmos but we shouldn't own it any more.
=> [CODEOWNERS] update rush.json and ignore-links.txt owners

sdk/ai/ai-inference-rest/assets.json, sdk/ai/ai-inference-rest/test/public/chatCompletions.spec.ts, sdk/ai/ai-inference-rest/test/public/embeddings.spec.ts, sdk/ai/ai-inference-rest/test/public/node/imageChat.spec.ts, sdk/ai/ai-inference-rest/test/public/types.ts, sdk/ai/ai-inference-rest/test/public/utils/recordedClient.ts, sdk/ai/ai-inference-rest/vitest.browser.config.ts, sdk/ai/ai-inference-rest/vitest.config.ts
adds chat multi-turn and auth error test
=> [AI] [Inference] add non-happy path tests

sdk/core/abort-controller/package.json, sdk/core/core-amqp/package.json, sdk/core/core-auth/package.json, sdk/core/core-client-rest/package.json, sdk/core/core-client/package.json, sdk/core/core-http-compat/package.json, sdk/core/core-lro/package.json, sdk/core/core-paging/package.json, sdk/core/core-rest-pipeline/package.json, sdk/core/core-sse/package.json, sdk/core/core-tracing/package.json, sdk/core/core-util/package.json, sdk/core/logger/package.json, sdk/core/ts-http-runtime/package.json
For back-compatibility.
This PR adds react-native top level field to package.json, similar to PR https://github.com/Azure/azure-sdk-for-js/pull/30493.
-------
core-util, core-rest-pipeline, core-amqp, logger
=> [core] Add react-native support at top level

sdk/identity/identity/tests.yml
N/A build failures
Looks like this was missed as part of the recent changes, but we need the ServiceConnection property to be set at the tests.yml level. This PR fixes that.
[teams chat (MICROSOFT INTERNAL)](https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1721920991966?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1721920991966&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1721920991966)
=> [identity] Add ServiceConnection to tests.yml

eng/pipelines/templates/stages/cosmos-sdk-client.yml
More details about the issue [here]
Cosmos ci pipeline is failing after turning on Federated Auth by default
=> [Eng] Turn off federated auth for cosmos

sdk/attestation/attestation/tests.yml, sdk/communication/communication-common/tests.yml, sdk/eventhub/event-hubs/tests.yml, sdk/keyvault/keyvault-keys/tests.yml, sdk/search/search-documents/tests.yml, sdk/storage/storage-blob/tests.yml, sdk/storage/storage-file-datalake/tests.yml, sdk/storage/storage-file-share/tests.yml, sdk/storage/storage-queue/tests.yml
This doesn't cover the many files still using secret sub configs with custom principals, those will be migrated separately. This changes the defaults to use file-based sub configs and service connections everywhere else. It is intended to be merged after/alongside federated auth mode becoming the default.
Relies on https://github.com/Azure/azure-sdk-tools/pull/8680
=> Default to sub config file paths/svc connection for public + sovereign live tests

.github/CODEOWNERS
as typescript samples also have their own tsconfig.json configuration files.
=> [CODEOWNERS] match tsconfig.json under management sub directories too

sdk/identity/identity/src/credentials/azurePowerShellCredential.ts, sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts
- Customer reported issue - https://github.com/Azure/azure-sdk-for-js/issues/30356
- The token parsing logic in AzurePowershellCredential currently does not account for warmings being emitted by az-powershell, due to which the json token parsing when attempted on the warning string will definitely fail. 
- One option is to suppress the warnings, 
- the other is to make the token parsing logic more robust
We will do both in case we don't want to suppress few warnings (future-proofing solutions)
In this PR, I am essentially making the  token parsing logic more robust to account for all strings and multiple json objects, carefully pick the correct json for the access token and log the rest of the output as warning with the logger.
- Yes two test cases
=> [Identity] Fix PowershellCredential token parsing logic

sdk/identity/identity/src/credentials/azurePipelinesCredential.ts, sdk/identity/identity/test/internal/node/azurePipelinesCredential.spec.ts
- Seeing that customers get 400 (authority_not_found) error (that is written by us) instead of the actual errors thrown by the AuthenticationError constructor.
- An example where the customer was using a different task like a "script" task, but the error it throws is different from the error detected -
=> [Identity] Update error messages for AzurePipelinesCredential

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/environmentCredential.ts, sdk/identity/identity/test/internal/node/environmentCredential.spec.ts
Resolves #29592
SNI authentication is a 1p certificate feature supported by
ClientCertificateCredential. In order to implement SNI based auth one has to use
ClientCertificateCredential directly instead of DefaultAzureCredential because
there's no way to configure sendCertificateChain from DAC.
For consistency with other languages, we're adding support for
AZURE_CLIENT_SEND_CERTIFICATE_CHAIN as an env var here
https://github.com/Azure/azure-sdk-for-java/pull/41031
=> [identity] add support for AZURE_CLIENT_SEND_CERTIFICATE_CHAIN env var

sdk/servicebus/service-bus/test/public/atomManagement.spec.ts
In live test pipeline, our DefaultAzureCredential would succeed in getting a
token from MSI but that token doesn't work with our test resources.  This PR
works around the issue by passing a fake Msi client id to DefaultAzureCredential
constructor, thus cause token retrieval to fail, and DefaultAzureCredential can
continue to try the next credential type in the chain.
=> [Test][ServiceBus] work around Managed Identity credential issue

sdk/eventhub/event-hubs/samples-express/package.json, sdk/eventhub/event-hubs/samples-express/src/asyncBatchingProducer.ts
Addresses issue #4 in https://github.com/Azure/azure-sdk-for-js/issues/30555.
=> [Event Hubs] Update sample

sdk/eventhub/event-hubs/vitest.browser.config.ts, sdk/eventhub/event-hubs/vitest.config.ts, vitest.browser.shared.config.ts, vitest.shared.config.ts
The verbose reporter writes out the status of each unit test after it gets executed. This is inline with our experience with mocha before and it helps us track progress better in real time.
=> [vitest] Use verbose reporter

sdk/monitor/monitor-query/CHANGELOG.md, sdk/monitor/monitor-query/package.json, sdk/monitor/monitor-query/review/monitor-query.api.md, sdk/monitor/monitor-query/src/constants.ts, sdk/monitor/monitor-query/src/generated/logquery/src/azureLogAnalyticsContext.ts, sdk/monitor/monitor-query/src/generated/metrics/src/monitorManagementClientContext.ts, sdk/monitor/monitor-query/src/generated/metricsdefinitions/src/monitorManagementClientContext.ts, sdk/monitor/monitor-query/src/generated/metricsnamespaces/src/monitorManagementClientContext.ts, sdk/monitor/monitor-query/src/index.ts, sdk/monitor/monitor-query/src/logsQueryClient.ts, sdk/monitor/monitor-query/src/metricsQueryClient.ts, sdk/monitor/perf-tests/monitor-query/package.json
NA
The audience values set for MetricsQueryClient is incorrect and has to be fixed. Also, new Audience values are introduced for LogsQueryClient and MetricsClient. 
No specific design considerations or big API changes.
No. They are just changes to enum values.
NA
NA
@srnagar @xirzec Please review and approve the PR.
=> [@azure/monitor-query] Fixed the audience values for MetricsQueryClient and MetricsClient

eng/pipelines/templates/jobs/live.tests.yml
Now that the product issue is fixed and released in identity, we no longer needs
this workaround. This PR removes it.
=> [EngSys] remove AzurePowerShell credential workaround

sdk/appconfiguration/app-configuration/package.json, sdk/appconfiguration/app-configuration/test/internal/node/throttlingRetryPolicy.spec.ts, sdk/cognitivelanguage/ai-language-conversations/package.json, sdk/containerregistry/container-registry/package.json, sdk/eventhub/eventhubs-checkpointstore-blob/package.json, sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts, sdk/eventhub/eventhubs-checkpointstore-table/package.json, sdk/eventhub/mock-hub/package.json, sdk/eventhub/mock-hub/src/sender/streamingPartitionSender.ts
- upgrade for app-configuration
- upgrade for ai-language-conversations
- upgrade for container-registry
- upgrade for event hubs checkpoint stores
- upgrade for mock-hub
=> [appconf, etc.] upgrade dependency `@azure/abort-controller` version to v2

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/review/identity.api.md, sdk/identity/identity/src/credentials/managedIdentityCredential/msalMsiProvider.ts, sdk/identity/identity/src/errors.ts, sdk/identity/identity/test/public/errors.spec.ts
In order to improve the error experience for Managed Identity we want to do a few things:
1. Remove misleading error messages like authority_not_found for any 400
2. Display the error's cause / InnerException / etc. 
3. Provide helpful debugging information in the exception message
(1) and (2) are done here, (3) is still in flux as I need to think about what information will be helpful without
being overwhelming.
Printing out the error's cause is an implementation detail of the runtime and _not_ something that gets stringified
=> [identity] Errors can include a cause field

eng/pipelines/templates/steps/npm-release-task.yml
If we have an email from who requested the build we should use that for both owners and approvers.
=> Update approver for EsrpRelease

sdk/cosmosdb/cosmos/CHANGELOG.md, sdk/cosmosdb/cosmos/src/client/Item/Items.ts, sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts
@azure/cosmos
- On a partition error gone error in bulk calls, `substatus` in the error needs to be checked instead of `subStatusCode`.
- Update ChangeLog with just the split proof support in bulk API. Currently our SDK as a whole does not support merge.
=> Fix Bulk split error substatus

sdk/identity/identity/src/errors.ts
@azure/identity 
N/A
A minor cosmetic fix where we only set `cause` if it exists in the options.
Before this change, node would print `[cause]: undefined` which can be
misleading. 
Now, we'll omit `cause` entirely if its not set.
Testing error presentation is challenging
=> [identity] Only set error.cause if it exists

sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts
@azure/cosmos
Previously, pre-split epk range headers were getting discarded during calculation of post-split over-lapping ranges. This was leading to fetching of changefeed of entire partition instead of just the range headers. Now, epk-range headers are being used to calculate the new overlapping ranges.
=> Fix post split overlapping query range

eng/pipelines/templates/stages/archetype-js-release.yml
There was an issue with the nightly MSDocs build where it was trying to install a preview version of a library whose nightly publish to the dev feed had failed. As expected, this caused the nightly MSDocs build to fail. The nightly MSDocs publish step depends on nightly PublishPackages step but, for whatever reason, never checked if it succeeded. The MSDocs publish for an official release correctly checks if the publish succeeded.
NET, Java, JS and Python are all getting this same fix.
Testing was done by running [js - template](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4029274&view=results) with SetDevVersion set to True to produce a nightly release which succeeded
=> Do not publish to the nightly MSDocs branch if nightly PublishPackages fails

eng/pipelines/templates/steps/analyze.yml, sdk/monitor/monitor-opentelemetry-exporter/.eslintrc.json, sdk/monitor/monitor-opentelemetry-exporter/package.json, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatExporter.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileAccessControl.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts, sdk/monitor/monitor-opentelemetry-exporter/src/sampling.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/breezeUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/connectionStringParser.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/fileSystemPersist.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/log.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/metric.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/functional/trace.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/httpSender.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/metricUtil.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/utils/basic.ts
This PR
- removes `-f html -o telemetry-exporter-lintReport.html || exit 0` from `lint` NPM script
- updates eslint config to report warn for some rules
- applies result of `lint:fix`
- fixes/suppresses linting errors
- in analyze pipeline, changes to build packages before linting so that linting with types works
monitor-opentelemetry-exporter
https://github.com/Azure/azure-sdk-for-js/issues/17942
=> [monitor-opentelemetry-exporter] enable linting

sdk/storage/storage-file-datalake/package.json
Fix https://github.com/Azure/azure-sdk-for-js/issues/30463 by including the portions of @azure/storage-blob required by @azure/storage-file-datalake.
@azure/storage-file-datalake
https://github.com/Azure/azure-sdk-for-js/issues/30463
Imports are broken. The package is unusable.
N/A
No. No code has changed.
N/A
N/A
=> [DataLake] Update storage-blob includes in package.json

common/tools/eslint-plugin-azure-sdk/package.json
so that VS Code prettier extension can import it via the "prettier" key in most of our packages' package.json:
```
"prettier": "@azure/eslint-plugin-azure-sdk/prettier.json",
```
=> [eslint-plugin] exports ./prettier.json

sdk/monitor/monitor-opentelemetry/src/shared/logging/logger.ts
https://github.com/Azure/azure-sdk-for-js/issues/30660
The default set by AZURE_LOG_LEVEL is ignored
Change the value in the line above to conform to upper. I felt it is better to overwrite the default, as in essence AZURE_LOG_LEVEL is the default for this.
No, haven't been any before as well :-P
=> fix: default for AZURE_LOG_LEVEL

sdk/core/core-util/CHANGELOG.md, sdk/core/core-util/review/core-util.api.md, sdk/core/core-util/src/delay.ts, sdk/core/core-util/src/index.ts, sdk/core/core-util/test/public/delay.spec.ts, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/index.ts, sdk/core/ts-http-runtime/src/util/delay.ts, sdk/core/ts-http-runtime/test/util/delay.spec.ts
@azure/core-util
Contributes to #30187
Ports over the logic from @azure/core-rest-pipeline's exponentialRetryStrategy
to a helper function that can be used by client libraries.
This code was duplicated in @azure/identity and a partner team attempted to add
exponential-backoff as a dependency to add support for this logic.
A helper function can be used to calculate the next interval, leaving the
business logic / deciding what to do next to the specific usecase
https://github.com/Azure/azure-sdk-for-js/pull/30172#discussion_r1655215478
=> [core] Added calculateRetryDelay helper

sdk/keyvault/keyvault-admin/README.md, sdk/keyvault/keyvault-certificates/README.md, sdk/keyvault/keyvault-keys/README.md, sdk/keyvault/keyvault-secrets/README.md
Links in the documentation are pointing to the Java documentation.
=> Fixing links to be JS links, not Java

sdk/eventhub/event-hubs/scripts/mockService.mts, sdk/eventhub/event-hubs/test/internal/eventProcessor.spec.ts, sdk/eventhub/event-hubs/test/internal/node/disconnect.spec.ts, sdk/eventhub/event-hubs/test/internal/receiveBatch.spec.ts, sdk/eventhub/event-hubs/test/utils/clients.ts, sdk/eventhub/event-hubs/test/utils/constants.ts, sdk/eventhub/test-resources.json
So consumer group name can be loaded from the environment variable.
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4039773&view=results
=> [Event Hubs] Abstract event receiver and processor in tests

sdk/web-pubsub/web-pubsub/CHANGELOG.md, sdk/web-pubsub/web-pubsub/src/generated/generatedClientContext.ts
=> Release Azure WebPubsub

sdk/identity/identity/src/credentials/azurePowerShellCredential.ts, sdk/identity/identity/test/internal/node/azurePowerShellCredential.spec.ts
@azure/identity 
Resolves #30356
Adds support for the `-AsSecureString` flag for `AzurePowerShellCredential` in order to support upcoming breaking
changes from Az Pwsh modules in a backwards compat way
=> [identity] Add support for AsSecureString in PowerShellCredential

.github/CODEOWNERS
as we often need to update the file to add entries for Management plane packages
=> [CODEOWNERS] add an entry for ./github/CODEOWNERS

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/azurePipelinesCredential.ts, sdk/identity/identity/src/credentials/clientAssertionCredential.ts, sdk/identity/identity/src/credentials/clientSecretCredential.ts, sdk/identity/identity/src/credentials/onBehalfOfCredential.ts, sdk/identity/identity/src/credentials/usernamePasswordCredential.ts, sdk/identity/identity/src/credentials/workloadIdentityCredential.ts, sdk/identity/identity/test/internal/node/clientAssertionCredential.spec.ts, sdk/identity/identity/test/internal/node/clientSecretCredential.spec.ts, sdk/identity/identity/test/internal/node/usernamePasswordCredential.spec.ts
Improve client error messages
Noticed in passing in the AzurePipelinesCredential - the error message lists all
required parameters but does not specify _which_ parameter was not provided.
Now that I am paying attention to errors, I did a sweep of our credentials
updating each credential with better / more specific error messages
Alternatively we can add some method to collect all required parameters and
which were not provided to avoid getting errors one at a time for each
parameter, but I decided not to go that route here - keeping things simple and
straightforward
=> [identity] Update parameter validation errors

.scripts/automation_generate.sh, .scripts/automation_init.sh
fixes https://github.com/Azure/azure-sdk-tools/issues/7967
=> remove nvm installation for SDK automation

common/config/rush/pnpm-lock.yaml
eventhubs-checkpointstore-blob still has playwright 1.45.3 in lockfile.  This PR updates the version to 1.46.0
=> [EngSys] rush update --full to fix inconsistent playwright versions

sdk/vision/ai-vision-image-analysis-rest/package.json
to get the latest version and be consistent with the rest packages.
=> [engsys] use caret version for api-extractor

eng/pipelines/run-for-all-packages.yml, eng/pipelines/templates/steps/run-eslint.yml, eng/pipelines/templates/steps/test-eslint.yml
Recently linting was enabled for `monitor-opentelemetry-exporter`.  Its eslint
config enables typed linting which requires its dependencies to be build in
order to have proper types.
This PR passes `-t @azure/monitor-opentelemetry-exporter` to `rush build`
before linting so that its dependencies are built.
While at it, also change the `run-for-all-packages` pipeline to use `install-run-rush.js` for consistency.
=> [eslint] fix ci failures

common/config/rush/pnpm-lock.yaml, common/tools/eslint-plugin-azure-sdk-helper/package.json, common/tools/eslint-plugin-azure-sdk/package.json, common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-customized.ts
which allows up to remove the fixup as the new version supports flat config.
-------
=> [eslint-plugin] upgrade `eslint-plugin-no-only-tests` to `^3.3.0`

common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-customized.ts
Add a configuration to turn off all `eslint-plugin-n` rules for browser code files.
Also remove the redundant `plugins` block in `nCustomization` because the
plugin's "flat/recommended" config already does that
https://github.com/eslint-community/eslint-plugin-n/blob/e5e758ea0cd238220127ae7bcbd967f1d8920f28/lib/index.js#L87
-------
=> [eslint-plugin] turn off `eslint-plugin-n` rules for browsers

eng/pipelines/templates/jobs/live.tests.yml, sdk/identity/identity/test/integration/node/azureKubernetesTest.spec.ts, sdk/identity/identity/tests.yml, sdk/identity/test-resources-post.ps1
N/A - test fixes
Identity client libraries need some extensive setup to test various credentials in different workloads. Some of the commands
require the az cli, and this enables us to login using az cli.
Eventually, my hope is to use this to provide federated credentials for keyvault managed HSMs resource creation where our credential expires by the time the HSM is deployed
=> [identity] Use federated token in az cli

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/review/identity.api.md, sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/msalMsiProvider.ts, sdk/identity/identity/src/index.ts, sdk/identity/identity/test/integration/azureVMUserAssignedTest.spec.ts, sdk/identity/identity/test/internal/node/managedIdentityCredential/msalMsiProvider.spec.ts
Resolves https://github.com/Azure/azure-sdk-for-js-pr/issues/262
Adds support for providing an objectID to be used in managed Identity.
=> [identity] Add support for Managed Identity ObjectID

sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/customising-service-parameters/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/manually-connecting-to-browsers/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/using-connect-options/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/customising-service-parameters/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/manually-connecting-to-browsers/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/using-connect-options/README.md
Uncomment links to other README files in the microsoft-playwright-testing SDK.
As per https://github.com/Azure/azure-sdk/blob/main/docs/policies/README-TEMPLATE.md#link-guidelines, any relative link to a file which does not exist in main, will require the initial PR to go in with link commented out, followed by a PR to uncomment those links.
N/A
Not pplicable
Initial PR - https://github.com/Azure/azure-sdk-for-js/pull/30433
=> docs(): uncomment broken links for microsoft-playwright-testing

common/tools/eslint-plugin-azure-sdk/tests/plugin.ts, common/tools/eslint-plugin-azure-sdk/tests/ruleTester.ts, common/tools/eslint-plugin-azure-sdk/tests/rules/ts-modules-only-named.ts, common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-keywords.ts
- adjust options passed `RuleTester` constructor
- remove `recommended` property that no longer exists
- use `output` of array to indicate multi-pass fixes with overlapping range
- temporarily disable two test cases of ts-modules-only-named suite.
=> [eslint-plugin] fix tests after upgrading typescript-eslint

sdk/eventhub/kv.bicep, sdk/eventhub/test-resources.bicep
Moving to a modular bicep definition so that we can share bits and pieces between all of them. This PR factors out the key vault definition so other bicep scripts can import it too. For now, it lives next to the event hub's test-resources.bicep script but I'll consider moving it to a central place once other libraries move to import it.
The PR also edits the script to make it more compact.
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4079360&view=results
=> [Event Hubs] [Bicep] Factor out KV definition

common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-customized.ts
because dev-tool is using @summary and @azsdk-weight when publishing samples.
=> [eslint-plugin] add an override to turn off tsdoc/syntax for samples-dev

common/tools/dev-tool/src/commands/run/index.ts, common/tools/dev-tool/src/commands/run/typecheck.ts
In our current setup, tshy won't build test and samples-dev folder even they are
included in tsconfig.json.  This PR adds a command that does the type-checking
for all files included in tsconfig.json, and allow additional files to be passed
in as well.
=> [dev-tool] add command to type check files not being built by tshy

eng/tools/dependency-testing/index.js, sdk/keyvault/keyvault-certificates/package.json
@azure/keyvault-certificates
#30822 
When migrating keyvault-certificates to ESM and vitest I forgot to port over the extended timeout needed for these tests
(see [this diff](https://github.com/Azure/azure-sdk-for-js/commit/58ac994ec5a58472d5887e94583007fe7c88cb82#diff-238f0a9c86d168f8a93aba09420e13a2cdc1bb6d157e76949a197eacd26774a3L54)) and noticed that the live tests started failing with a timeout.
This commit adds the timeout back in a command line argument. It also addresses an issue in our dependency-testing script where min/max tests were no longer carrying over the timeout from the package json's path in tests that have migrated to vitest.
=> [kevault-certificates] Update timeout for nightly builds

common/config/rush/build-cache.json, eng/pipelines/templates/steps/build.yml
Use AzureCLI@2 task to generate a SAS for cache write credential so we don't need to store secrets anymore.
=> [EngSys] re-enable rush build cache

sdk/core/core-auth/CHANGELOG.md, sdk/core/core-auth/package.json, sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/package.json, sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/package.json
Bump core package versions to next minor and dependency versions after the refreshAfterTimestamp addition to AccessToken https://github.com/Azure/azure-sdk-for-js/pull/30402
=> bump core versions

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/utils/opentelemetryInstrumentationPatcher.ts
#30900
Removes the usage of a relative path such that changing the module location will not break imports.
=> [Monitor OpenTelemetry] Update OTel Instrumentation Module Path to fix ESM/Webpack

common/tools/eslint-plugin-azure-sdk/tests/rules/ts-modules-only-named.ts
There's some change in `typescript-eslint` that breaks some eslint test cases.
Previously when running tests, in a rule's `create()` method, we get a relative
path for `context.filename`, and when we pass a setting of `{ main:
"src/test.ts" }` in rule tester option, the two were considered the same file,
therefore the following condition check failed, and we continue to report error
for default exports.
https://github.com/Azure/azure-sdk-for-js/blob/6dd8b582e2f5a3257befab368bab0e64499f4d57/common/tools/eslint-plugin-azure-sdk/src/rules/ts-modules-only-named.ts#L31
After the upgrade, `context.filename` now contains the full path, the file
`src/test.ts` in our test fixture has a full path of
`/.../common/tools/eslint-plugin-azure-sdk/tests/fixture/src/test.ts`. It is not
considered the same …
=> [eslint-plugin] fix `ts-modules-only-named` invalid test cases

sdk/cosmosdb/cosmos/CHANGELOG.md, sdk/cosmosdb/cosmos/src/ClientContext.ts, sdk/cosmosdb/cosmos/src/client/Item/Items.ts, sdk/cosmosdb/cosmos/test/public/functional/item/bulk.item.spec.ts
@azure/cosmos
The default value of continueOnError in bulkRequestOptions has been set to true.
=> [cosmos ]set default value of continueOnError in bulkRequestOptions to true

sdk/remoterendering/mixed-reality-remote-rendering/test/public/remoteRenderingClient.spec.ts
mixed-reality-remote-rendering
Test pipeline failures in the mixed-reality-remote-rendering sdk tests.
Test failures are fixed by removing the respectively failing check.
The specific checks are ill formed currently, as the testing account is internally load balanced. Azure Remote Rendering introduced this recently as the tests created negative customer impact with regards to session availability. Hence, the tests will not necessarily be served the exact requested session type. Consequently the check is now pointless.
There isn't any functional change to the SDK in this PR.
N/A
N/A
- [x ] Added impacted package name to the issue description
- [x ] Does this PR needs any fixes in the SDK Generator?** _(If so, create an Issue in the …
=> Removing VM size check from Azure Remote Rendering sdk tests

common/config/rush/pnpm-lock.yaml, sdk/test-utils/test-credential/CHANGELOG.md, sdk/test-utils/test-credential/api-extractor.json, sdk/test-utils/test-credential/package.json, sdk/test-utils/test-credential/src/index.ts, sdk/test-utils/test-credential/tsconfig.json
`@azure-tools/test-credential@v1` will now depend on the Azure Pipelines Credential.
Impacts the live test pipelines for all the packages leveraging `test-credential@v1`
Ports the PR #30633
=> [test-credential] Porting #30633 to test-credential v1

sdk/identity/identity/BREAKING_CHANGES.md, sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/managedIdentityCredential/msalMsiProvider.ts, sdk/identity/identity/test/internal/node/managedIdentityCredential/msalMsiProvider.spec.ts
Resolves #30380
If the Cloud Shell ManagedIdentitySource is detected via MSAL and a user-assigned managed identity clientID or resourceID is supplied, the ManagedIdentityCredential should throw.
The rationale for taking this minor breaking change is that CloudShell does not support specifying a clientID or ResourceID and the current behavior of silently falling back to attempting to use a system-assigned identity could be unexpected.
https://github.com/Azure/azure-sdk-for-cpp/pull/5837
=> [identity] Throw if user-assigned IDs are used for CloudShell MSI

sdk/core/core-lro/CHANGELOG.md, sdk/core/core-lro/review/core-lro.api.md, sdk/core/core-lro/src/http/models.ts, sdk/core/core-lro/src/http/operation.ts, sdk/core/core-lro/test/lro.spec.ts
fixes https://github.com/Azure/azure-sdk-for-js/issues/30949
We should skip the final GET when the final-state-via is set as `operation-location` and see [definition](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options).
```
operation-location - poll until terminal state, skip any final GET on Location or Origin-URI and use the final response at the uri pointed to by the header Operation-Location
```
=> Support operation-location final-state-via for LRO

sdk/notificationhubs/notification-hubs/CHANGELOG.md, sdk/notificationhubs/notification-hubs/package.json, sdk/notificationhubs/notification-hubs/review/notification-hubs-api.api.md, sdk/notificationhubs/notification-hubs/review/notification-hubs-models.api.md, sdk/notificationhubs/notification-hubs/review/notification-hubs.api.md, sdk/notificationhubs/notification-hubs/src/api/beginSubmitNotificationHubJob.ts, sdk/notificationhubs/notification-hubs/src/models/notificationHubJob.ts
Moves @azure/notification-hubs to @azure/core-lro v3
=> [notification-hubs] Moving to core-lro v3

sdk/playwrighttesting/microsoft-playwright-testing/review/microsoft-playwright-testing.api.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/playwright.service.config.js, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/playwright.service.config.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/entraIdAccessToken.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/types.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightServiceEntra.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/common/entraIdAccessToken.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightService.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightServiceEntra.spec.ts
Remove fallback logic in authentication
Earlier, we used to have fallback logic in authentication. Entra -> PAT or PAT -> Entra. This PR removes the fallback logic.
Yes
=> chore(playwrighttesting): remove fallback authentication logic

rush.json
@azure/create-microsoft-playwright-testing
Dev version cannot be published for utility packages
- VersionPolicy should be client or core in rush.json to get alpha version build.
Change version policy to `client` from `utility`
=> fix(playwrighttesting): change policy name in rush.json to client

sdk/playwrighttesting/microsoft-playwright-testing/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/manually-connecting-to-browsers/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/manually-connecting-to-browsers/README.md, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/README.md, sdk/playwrighttesting/microsoft-playwright-testing/src/common/types.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
=> refactor(playwrighttesting): jsdocs example fixes and doc markdown changes

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts, sdk/monitor/monitor-opentelemetry-exporter/src/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/fileSystemPersist.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.test.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts
https://github.com/Azure/azure-sdk-for-js/issues/30969
Enforces truncation on properties parsed from user telemetry.
Yes
=> [Monitor OpenTelemetry Exporter] Fix Property Truncation

sdk/test-utils/test-credential/CHANGELOG.md, sdk/test-utils/test-credential/package.json
@azure-tools/test-credential
N/A - hotfix 1.3.0
In https://github.com/Azure/azure-sdk-for-js/pull/30977/files#diff-f69713a41b4518b09d100824cfa2dc13e3105ab66b0f81f12a8290df980f441dL8 we updated the filename for the rollup dts file but forgot to update the `files` section to ensure the new file is included in the published package.
This hotfix focuses on the straightforward fix which is updating the `files` declaration. Once this is released, I will also look at opportunities for us to catch this before publishing the package. I don't know what that will look like yet, but for now let's fix the published package
=> [test-credential] Include the correct types in package

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts, sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts, sdk/core/ts-http-runtime/src/policies/tracingPolicy.ts, sdk/core/ts-http-runtime/test/tracingPolicy.spec.ts
@typespec/ts-http-runtime
N/A
Back when we were migrating to the new core tracing we wanted to be cautious and
bail as early as possible in our core tracing policy. This meant that we:
1. Guard against any errors
2. Ignore automatic span propagation, instead expecting HLC libraries to call
tracingClient.withSpan to kick off the manual span propagation (context
parameter passing in options)
Now that we have RLC which does not have a tracingClient, and having had this
code in production for quite some time, we can remove the optimization that
aassumes the tracingContext will be added upstream.
This is a non-impactful change for high-level clients or anyone who has not opted-in to OTel tracing.
For users who use rest-level clients _and_ have opted into OTel, they …
=> [core] Create spans using automatic span propagation

sdk/storage/storage-blob/karma.conf.js, sdk/storage/storage-file-datalake/karma.conf.js, sdk/storage/storage-file-share/karma.conf.js, sdk/storage/storage-queue/karma.conf.js
After `puppeteer` upgrade from 23.1.1 to 23.2.1, storage browser tests failed to start chrome headless browsers. However, other package's browser tests are not impacted.  This PR copies the browser settings in karma config from a working package.
=> [Storage] Fix broken browser tests

sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/httpService.ts
REST calls getting stuck due to high retries and no timeouts.
=> chore(playwrighttesting): rest-core client retries and timeout tuning

sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts
Multiline error messages could not be parsed by existing regex patterns. Also 2 error scenarios weren't covered.
=> fix(playwrighttesting): scalable error message regex parsing

samples/web-workers/README.md, samples/web-workers/arm-template.json, samples/web-workers/js/package.json, samples/web-workers/js/sample.env, samples/web-workers/js/worker.js, samples/web-workers/ts/sample.env, samples/web-workers/ts/worker.ts
Resolves #31049 
A few changes were needed here:
1. Upgrade jsdom to >= 19 in the JS sample, similar to https://github.com/Azure/azure-sdk-for-js/issues/20934 which fixed the TS sample
2. Update the sample to use a SAS URL so that it can be runnable
3. Remove usage of env vars, instead using the string directly and recommending passing a SAS URL from the server in production
=> [samples] Update web-workers sample

sdk/playwrighttesting/microsoft-playwright-testing/src/common/environmentVariables.ts
Fetching and setting access token was a one time operation in reporting. Thus, when the token was rotated, it was not picked up by the reporter worker resulting in expired token calls.
=> fix(playwrighttesting): fetch access token value from environment variables

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
- #31026
Removes excess listeners for streams to ensure that we're not adding listeners to check for done and then not removing them.
=> [core] Remove excess listeners for streams

CONTRIBUTING.md
per discussion at https://github.com/Azure/azure-sdk-for-js/issues/23147#issuecomment-1252542676
=> [Doc] Remove build instructions for non-rush packages from contributing guide

sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts
monitor-opentelemetry
https://github.com/Azure/azure-sdk-for-js/issues/30970
This PR addresses the issue where the live metrics component of the SDK was re-emitting old documents at every time interval along with the new documents. 
Testing was manually done by including the app insights sdk in a test application & checking the documents that appear on the documents pane on the live metrics page.
=> [monitor-opentelemetry] Fix document spam bug

common/tools/eslint-plugin-azure-sdk/src/configs/index.ts
so we don't have errors in editors when opening vitest configs
=> [eslint-plugin] exclude *.config.*ts from linting

sdk/keyvault/keyvault-certificates/test/public/lro.create.spec.ts, sdk/keyvault/keyvault-certificates/test/public/lro.delete.spec.ts, sdk/keyvault/keyvault-certificates/test/public/lro.recover.spec.ts, sdk/keyvault/keyvault-certificates/test/public/mergeAndImport.spec.ts
- Fix #31012
1. Minmax tests are not run in the package directory (they are instead run in `test/public`). This PR updates the path for some static test resource files to be relative to the test file itself instead of relative to the working directory.
2. Stop using instanceof for a couple of tests where we are testing the type of the error. The name of the error should be enough. I think this might have been causing failures maybe due to a dual-package hazard kind of interaction?
=> [keyvault-certificates] fix minmax failure

sdk/test-utils/test-credential/CHANGELOG.md
@azure-tools/test-utils
I noticed that the hotfix changes from 1.x branch were not listed in the
CHANGELOG on main. This PR just ports those over so they are listed in
chronological order
=> [test-utils] Port CHANGELOG from 1.x branch

sdk/core/core-rest-pipeline/package.json, sdk/core/core-rest-pipeline/src/retryStrategies/exponentialRetryStrategy.ts, sdk/core/ts-http-runtime/src/retryStrategies/exponentialRetryStrategy.ts
#30187
Now that core-util is published with a `calculateRetryDelay` helper, we can use
that instead of duplicating the logic from core-rest-pipeline
=> [core] Use core-util's helper for exponential retry delay

sdk/identity/identity/package.json, sdk/identity/identity/src/credentials/managedIdentityCredential/imdsRetryPolicy.ts
@azure/identity 
#30187
Now that core-util is published with a `calculateRetryDelay` helper, we can use
that instead of duplicating the logic from core-rest-pipeline
There's an existing test suite for this policy, and this should be considered a
pure refactor now
=> [identity] Use helper from core-util

sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/serviceClient.ts
Any API failure in post test result API call would terminate the node process immediately. This PR swallows the exception and allows the execution to proceed.
=> fix(playwrighttesting): suppress POST test result API failures to prevent node process from being terminated

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/review/identity.api.md, sdk/identity/identity/src/credentials/clientAssertionCredentialOptions.ts
To have ClientAssertionCredentialOptions implement ISupportsTokenCachePersistenceOptions. As a consumer of Identity, Azure PowerShell is dependent on the Azure Identity library for .NET. Now the client assertion workflow has increasing usage, so the ask should have higher priority.
Business Impact:
In the client assertion auth flow, Azure PowerShell customers acquire the access token with the federated token. The access token must be used by the subsequent Azure PowerShell cmdlets. We depend on Azure.Identity to save the tokens to the MSAL cache. As the federated token has a short lifetime, it's impossible to cache the federated token and reauthenticate every time a cmdlet is run.
=> [Identity] Client assertion add token cache persistence

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/utils.ts, sdk/identity/identity/test/internal/node/msalClient.spec.ts
#30557
Looks like we missed one place where we need to read the AZURE_AUTHORITY_HOST
env var when porting logic over to msalClient. This PR addresses the issue and
allows for environment variable to be read when needed.
=> [identity] Support AZURE_AUTHORITY_HOST in cross cloud requests

sdk/core/core-tracing/CHANGELOG.md, sdk/core/core-tracing/review/core-tracing.api.md, sdk/core/core-tracing/src/index.ts, sdk/core/core-tracing/src/instrumenter.ts, sdk/core/core-tracing/src/interfaces.ts, sdk/core/core-tracing/test/instrumenter.spec.ts, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/index.ts, sdk/core/ts-http-runtime/src/tracing/instrumenter.ts, sdk/core/ts-http-runtime/src/tracing/interfaces.ts, sdk/core/ts-http-runtime/test/tracing/instrumenter.spec.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/spanWrapper.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/transformations.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/spanWrapper.spec.ts
@typespec/ts-http-runtime
Resolves #31158
OpenTelemetry supports adding events to a span, and part of the gen-ai
specification expects events to be added on a span. 
This PR adds support for the `addEvent` API in our core-tracing library as well
as our otel-sdk.
Adding a required field is a breaking change, so this is added as optional. The
implementation will need to use the safe-navigation operator syntax or check for
the function's existence before calling it.
In passing, I am updating some of our internal transformations to use OTel's APIs instead.
=> [tracing] Add support for addEvent

sdk/playwrighttesting/microsoft-playwright-testing/src/utils/cIInfoProvider.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/clInfoProvider.spec.ts
`
SDK was passing Default Job Config as Empty Strings instead of null
Added test for clInfoProvider.
=> fix(playwrighttesting): SDK Default Job Config as Empty Strings

sdk/eventgrid/eventgrid-system-events/CHANGELOG.md, sdk/eventgrid/eventgrid-system-events/package.json, sdk/eventgrid/eventgrid-system-events/review/eventgrid-system-events.api.md, sdk/eventgrid/eventgrid-system-events/src/cadl-generated/models/models.ts
@azure/eventgrid-system-events
NA
- A new property `tierToColdSummary` is added to the `StorageLifecyclePolicyCompletedEventData` interface.
There are no specific/complex design scenarios for this task.
https://github.com/Azure/azure-sdk-for-js/pull/29688
https://github.com/Azure/azure-sdk-for-js/pull/30627
`npx tsp compile client.tsp`
=> [@azure/eventgrid-system-events] Update System events for Version 1.0.0-beta.4

sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/entraIdAccessToken.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/executor.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/messages.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/types.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/utils.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightService.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/utils.spec.ts
`
1. Error message printing twice one for scalable and one for reporting
2. When using PLAYWRIGHT_SERVICE_URL and PLAYWRIGHT_SERVICE_ACCESS_TOKEN of different workspace, scalable fails as expected but reporting works
=> BUG FIXED: mismatch of workspace and error message printing twice.

sdk/openai/openai/test/public/completions.spec.ts, sdk/openai/openai/tsconfig.browser.config.json, sdk/openai/openai/vitest.browser.config.ts
@azure/openai
N/A
The browser test files were not being built correctly because of two things:
- The mts files in the test folder were not being built by TypeScript
- vitest couldn't resolve `@azure/openai/types` import
This PR fixes the two issues by adding the mts files under the test folder to TypeScript context and rewrites the import to `@azure/openai/types` to the relative path instead.
N/A
N/A
=> [OpenAI] Fix browser tests

common/tools/dev-tool/src/commands/run/extract-api.ts
This PR fixes an error in extra-api command when a package doesn't enable the docModel generation, we were trying to open an api.md file that doesn't exists.
=> [dev-tool] only process api.json files if they are generated

eng/scripts/Language-Settings.ps1, eng/scripts/docs/Docs-Onboarding.ps1
Last part of https://github.com/Azure/azure-sdk-tools/issues/6800 that still needs to be done in JS
Move validation functions from Language-Settings.ps1 to Docs-Onboarding.ps1
Release process succeeds https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4171903&view=logs&j=19b87903-f8bc-5cbb-22d9-4f6eb3469d8e&t=39d7f548-7a77-5d57-b2f3-bf0cc5f8dda2 ... There is a failure in one of the other template package releases but it's unrelated to this change.
=> Docs cleanup

.github/CODEOWNERS
- Remove zombie `@Azure/azsdk-keyvault` team
- Maor to primary Key Vault owner
=> Update Key Vault CODEOWNERS

common/tools/dev-tool/src/commands/admin/list/esm-migrations.ts
dev-tool
A few QoL additions as we aim to complete the ESM migration:
- output markdown
- Add verbose mode to output individual package status
I only focused on ESM migration as we plan to migrate ESM + Vitest in a single
commit. This all builds off of the work Matt started and allows us to keep an up-to-date 
wiki for folks to follow the migration status
=> [dev-tool] Generate detailed report for ESM migrations

common/tools/dev-tool/src/commands/admin/migrate-package.ts
@azure/dev-tool
N/A - part of migrations
A few quality-of-life improvements as I migrate keyvault packages to ESM:
1. Allow skipping browser test configuration
2. Ensure linters are happy by appending an empty line to updated json files
3. Replace `tsc -p .` with `dev-tool run build-package` in the scripts section
4. Replace `@azure-tools/test-utils` with `@azure-tools/test-utils-vitest`
5. Remove `tshy` from the dependencies to add since `build-package` uses a vendored tshy version
=> [dev-tool] migrate-package command improvements

eng/scripts/Generate-APIView-CodeFile.ps1
Pin API view parser version to avoid causing build failures when a new API view parser version is released. This change is required before JS API view is migrated to new model.
=> Pin API view parser version

.github/CODEOWNERS_baseline_errors.txt
The baseline file suppresses errors and ideally should be empty. In this PR, I'm trying to peel some of the low hanging fruit off like ensuring our own team members are configured correctly and we're not assigning issues to invalid labels.
=> [CODEOWNERS] cleanup some baseline entries that hopefully are no longer needed

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/instrumenter.spec.ts
Resolves #31287
Looks like Sinon's matchers are a little looser than vitest's - while we are
calling inject with 3 arguments we only care about the first in this test.
This PR restores the tests and updates the assertion
=> [instrumentation] Fix test assertion

sdk/template/template/test/public/configurationClient.spec.ts
One of the template tests has been flaky on Mac OS. Given that template is run as part of core and likely most PRs we decided to pend the test for now and investigate it as part of #31296
=> [template] Skip flaky test in Mac OS

sdk/ai/ai-inference-rest/package.json
N/A
`@azure/core-tracing` will release as 1.2.0 as per https://github.com/Azure/azure-sdk-for-js/pull/31272/files
This PR prepares ai-inference to use the correct version of `@azure/core-tracing` and get support for `addEvent`
=> [ai] Update core-tracing min-version

sdk/template/test-resources.bicep
- `@azure/template`
Grants the "App Configuration Data Owner" when deploying the template live test resources. This fixes some issues recording tests for the template package (and possibly the live tests too).
Copied from the App Config test-resources.bicep [here](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/appconfiguration/test-resources.bicep)
=> [template] Add role assignment to test-resources.bicep

sdk/template/template/test/public/configurationClient.spec.ts
- @azure/template
- #31296
Adds a better timeout and retry logic for the issues with the best being flaky.
=> [template] Add retry/timeout to macOS tests

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/src/nodeHttpClient.ts, sdk/core/core-rest-pipeline/test/node/nodeHttpClient.spec.ts, sdk/core/ts-http-runtime/src/nodeHttpClient.ts, sdk/core/ts-http-runtime/test/node/nodeHttpClient.spec.ts
Extract @MaryGao's fix from PR https://github.com/Azure/azure-sdk-for-js/pull/31027
Fix an issue in `isStreamComplete` where the method never resolves when the stream is not readable.
=> [core] fix isStreamComplete issue

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/package.json, sdk/core/core-amqp/review/core-amqp.api.md, sdk/core/core-amqp/src/util/constants.ts, sdk/eventhub/event-hubs/src/eventHubSender.ts, sdk/eventhub/event-hubs/src/util/constants.ts
So that we can release GA fixes from main branch.
While at it, also port CHANGELOG entries from hotfix branch.
=> [core-amqp] move geographic replication constant to Event Hubs

sdk/eventhub/event-hubs/CHANGELOG.md, sdk/eventhub/event-hubs/src/eventData.ts, sdk/eventhub/event-hubs/src/eventDataBatch.ts, sdk/eventhub/event-hubs/src/eventHubProducerClient.ts, sdk/eventhub/event-hubs/test/internal/sender.spec.ts
Issue: https://github.com/Azure/azure-sdk-for-js/issues/31067
This PR adds runtime validation to the input message structure. This is needed so that strict receivers that follow the AMQP spec don't reject non-compliant messages.
=> [Event Hubs] Add message structure validation to the producer

sdk/cosmosdb/cosmos/src/request/RequestHandler.ts, sdk/cosmosdb/cosmos/test/public/common/setup.ts
@azure/cosmos
#31119 
1. "http:" protocol now works properly
2. Unhandled errors in tests now properly include stack trace in STDERR
We could possibly have done a further bifurcation of the logic for http: vs https:. I chose this design because it was a minimal change and maintains the original intent.
No. There's not currently a good means to test http: against Cosmos DB, but that's a WIP.
N/A
N/A
=> fix(CosmosDB: http protocol endpoints no longer break CosmosClient

sdk/identity/identity/README.md
Resolves #31307
It is not clear from our documentation that @azure/identity is optimized for the
"pass a credential to another client library" use-case and that refreshing /
caching / etc. are implementation details without proper API support and
documentation.
This PR attempts to provide additional information regarding when to use
something like MSAL directly.
=> [identity] Add to guidelines when to use MSAL directly

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/baseSender.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts
We should collect non-essential statsbeat about disk retry.
Yes
=> [Monitor OpenTelemetry Exporter] Add Non-Essential Statsbeat

sdk/playwrighttesting/microsoft-playwright-testing/src/model/testResult.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/reporterUtils.spec.ts
=> fix(playwrighttesting): optional fields in playwright config are compulsory in service reporter

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/review/core-client.api.md, sdk/core/core-client-rest/src/common.ts, sdk/core/core-client-rest/src/urlHelpers.ts, sdk/core/core-client-rest/test/urlHelpers.spec.ts
- Fix https://github.com/Azure/azure-sdk-for-js/issues/31349
We generate RLCs that allow for path parameters to be `number`. The change for `allowReserved` assumed that path parameters could only be `string`, causing number parameters to not be serialized properly. This PR fixes that assumption.
Added a test to check for a number path parameter
- #31058
=> [core-client-rest] Fix serialization of non-string path parameters

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/filtering/filter.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/filtering/validator.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/liveMetricsFilter.test.ts
monitor-opentelemetry
This PR adds support for document filtering in live metrics.
Modifications were made to existing unit tests to test documents functionality, as much of the new code added uses existing filtering functionality. Also, many cases for documents were manually tested E2E, such as the single/multi session cases for applying filters to documents and metrics & confirming that SDK conforms to any configuration sent to it by the service.
=> [monitor-opentelemetry] Live Metrics Filtering for Documents

eng/tools/dependency-testing/templates/vitest.dependency-test.config.ts
Resolves #30578 
While simple settings like `test-timeout` and `hook-timeout` are often defined in package.json scripts, there are
other settings that are specified in the vitest.config.ts of the target package.
Our existing setup uses the default vitest template which does not work for libraries that use customized config.
This PR improves that experience by creating a 3-way-merge of:
1. The base config
2. The template config (which specifies the test patterns)
3. The package's config
Only done for node right now. If you need it for browser, you now have a path forward
There are some gotchas here:
1. testTimeout is defined in package.json which takes precedence over any config files I believe - it may be surprising that your testTimeout does not take (note that this is somewhat the case …
=> [engsys] Allow min/max tests to use vitest config of the target package

sdk/identity/identity/README.md
Replace much of the `DefaultAzureCredential` content in the Azure Identity README with a link to the new credential chains doc on Learn.
=> Drive traffic to credential chains doc

sdk/keyvault/keyvault-admin/CHANGELOG.md, sdk/keyvault/keyvault-certificates/CHANGELOG.md, sdk/keyvault/keyvault-common/CHANGELOG.md, sdk/keyvault/keyvault-common/package.json, sdk/keyvault/keyvault-keys/CHANGELOG.md, sdk/keyvault/keyvault-secrets/CHANGELOG.md
- `@azure/keyvault-common`
Caught this while doing pre-release checks. `@azure/core-util@^1.10.1` has not released yet
=> [keyvault] keyvault-common: use core-util@^1.10.0

sdk/cosmosdb/cosmos/src/client/Item/Item.ts, sdk/cosmosdb/cosmos/src/client/Item/Items.ts, sdk/cosmosdb/cosmos/src/extractPartitionKey.ts, sdk/cosmosdb/cosmos/src/utils/batch.ts, sdk/cosmosdb/cosmos/test/public/functional/npcontainer.spec.ts
@azure/cosmos
This PR cherry-picks the commits from https://github.com/Azure/azure-sdk-for-js/pull/30250 to beta branch.
=> [cosmos] Beta/fix non-partitioned container pk format

sdk/keyvault/keyvault-common/package.json
Exactly the same as https://github.com/Azure/azure-sdk-for-js/pull/31418 except for logger
=> [keyvault] keyvault-common: use released @azure/logger dependency

sdk/identity/identity/src/credentials/chainedTokenCredential.ts, sdk/identity/identity/src/credentials/defaultAzureCredential.ts
Drive traffic to the new credential chains doc on Learn. Also, eliminate duplication in the `DefaultAzureCredential` API docs.
=> Improve API docs for DAC and ChainedTokenCredential

sdk/core/core-client-rest/src/getClient.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff
Simplify `isCredential` helper used in getClient.ts. This change was already made in the unbranded package but not in Azure core.
No change in the Unbranded diff report for this PR because I made the change and updated the diff as part of #31487, just forgot to check in this particular change. The unbranded diff check is currently reporting a failure on main and this change should fix that.
=> [core-client-rest] use helpers for isCredential

eng/pipelines/templates/jobs/smoke.tests.yml
The smoke-tests pipeline has been disabled but I still cleaned up to smoke tests to remove usages of sub-config-azure-cloud-test-resources and try to use a service connection. When we decide to re-enable the smoke tests pipeline we will want to update the deployment to use federated auth as well.
@xirzec you disabled this pipeline 1/10/2023. Do you have any plans to try and re-enable it? If not perhaps we just delete this instead.
=> Use federated auth for smoke testing

sdk/communication/communication-chat/CHANGELOG.md, sdk/communication/communication-chat/package.json, sdk/communication/communication-chat/src/generated/src/chatApiClient.ts, sdk/communication/communication-chat/src/generated/src/tracing.ts, sdk/communication/communication-chat/swagger/README.md
Bump @azure/communication-chat version from 1.5.3 to 1.5.4
=> Update AzureCommunicationChat Version to 1.5.4

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/src/requestResponseLink.ts
even on verbose as it can contains secrets.
=> [core-amqp] don't log request on `RequestResponseLink`

sdk/core/ts-http-runtime/package.json
The diff check seems to be running as it should, so let's enable it so that failure makes CI go red
- [Example of it passing on main](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4279078&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=70ccc7c9-8d04-5255-456e-9568fe142bcd&l=612)
- [Example of it failing on a PR branch that has not updated the diff](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4276826&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d31d5e2d-d8df-53bc-da94-87e19f5b2ee4&l=616) (lint step failure is due to ESLint failures, not the unbranded check tool)
- #31285
=> [ts-http-runtime] Enforce azure diff check

sdk/schemaregistry/schema-registry-avro/package.json
After moving to vendored rimraf, this particular "clean" script is failing likely due to the escaped quoted argument before it and how dev-tool handls arguments. Moving `*.tgz *.log` fixes it.
=> [EngSys] fix `schema-registry-avro` build failure on Windows

sdk/core/abort-controller/MIGRATION.md
`@azure/abort-controller`
Resolves #29112
Adds a migration guide to explain moving from 1.x to 2.x of the `@azure/abort-controller` package. This is a doc-only change.
=> [abort-controller] Add 2.0 migration guide

eng/pipelines/templates/jobs/ci.yml
During pr matrix generation. Follow-up on #31631
=> We want to pull down ci.mgmt.yml as well as ci.yml for Matrix resolution

sdk/openai/openai/CHANGELOG.md, sdk/openai/openai/review/openai-types.api.md, sdk/openai/openai/src/types/index.ts, sdk/openai/openai/src/types/models.ts, sdk/openai/openai/src/types/outputModels.ts, sdk/openai/openai/test/public/utils/asserts.ts
@azure/openai
N/A
This PR adds `azure_block_id` to the response model of file uploads and removes the [enhancement](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation#changes-between-2024-03-01-preview-and-2024-04-01-preview-api-specification) feature from chat completions and the [`role_information`](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation#changes-between-2024-07-01-preview-and-2024-08-01-preview-api-specification) field from On Your Data requests.
N/A
N/A
=> [OpenAI] Remove outdated definitions

sdk/core/ci.yml, sdk/identity/ci.yml
Fixes #26770 
I have tested and validated that these packages will work with the new `type2docfx` docs build system and this PR enables docs.ms publishing. 
@xirzec -- When searching through `ci.yml` files I noticed two places where we intentionally skip publishing docs on docs.ms: 
* https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/communication/ci.yml#L64-L69
* https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/test-utils/ci.yml#L32-L49
In both of these instances these are `@azure-tools/___` packages. I left these untouched. Should docs be published for these on docs.microsoft.com whenever they release?
=> Enable publishing for packages previously excluded from Docs MS

eng/pipelines/templates/steps/common.yml
we don't need a specific version of Python. The one available on the build agent should be enough.
=> [EngSys] remove Use Python step from JS pipelines

sdk/monitor/monitor-opentelemetry-exporter/package.json, sdk/monitor/monitor-opentelemetry-exporter/test-opentelemetry-versions.js, sdk/monitor/monitor-opentelemetry-exporter/vitest.integration.config.ts
Migrate the non-standard tests
=> [Test] Fix monitor-opentelemetry-exporter live tests

sdk/ai/ai-projects/review/ai-projects.api.md, sdk/ai/ai-projects/samples-dev/agents/threads.ts, sdk/ai/ai-projects/src/agents/index.ts, sdk/ai/ai-projects/src/agents/threads.ts, sdk/ai/ai-projects/test/public/agents/threads.spec.ts
Threads basics (should be further tested/sampled when other methods, like files, are implemented)
=> Agents threads wrappers, tests, and sample

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/src/urlHelpers.ts, sdk/core/core-client-rest/test/urlHelpers.spec.ts, sdk/core/ts-http-runtime/src/client/urlHelpers.ts, sdk/core/ts-http-runtime/test/client/urlHelpers.spec.ts
@azure/core-client-rest 
@azure/ts-http-runtime
N/A - found in passing
The existing regex for finding template values to replace assumes only `\w` characters are allowed in the template, but 
`-` should be valid for a template name as this [playground](https://azure.github.io/typespec-azure/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2 …
=> Allow dashes in path parameter templates

sdk/playwrighttesting/microsoft-playwright-testing/src/common/constants.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/utils.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightService.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/utils.spec.ts
Added X-MS-Package-Version header to connect session API for language and package version decoding.
The getReporterVersion function returns the reporter version, which includes a special character ("."). This caused tests to fail with the error: "Invalid character in header content ["x-ms-package-version"]." Therefore, the characters were escaped.
Since we are passing the header from the package, this needs to be handled by the server. We are encoding it here, but it needs to be decoded on the server side.
yes
=> fix(playwrighttesting): Add X-MS-Package-Version header to connect session API

sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/utils.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightService.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/utils.spec.ts
Removed runName support from the wsEndpoint
=> fix(playwrighttesting): Removed runName support from the wsEndpoint

.vscode/launch.json, .vscode/settings.json
None
None
Using the JavaScript Debug Terminal and auto-attaching to every subprocess
results in a long wait time to hit breakpoints when debugging. To improve the
experience, we can include a launch.json configuration that allows running
vitest tests and only attaching to the vitest process itself.
Because we need the test proxy running, using dev-tool is the recommended way to
run tests. This PR adds the proper configuration to support that scenario.
While here I also went ahead and removed `node_modules` from VSCode's exclusion
list so they show up in the file explorer. Happy to revert that but I find it difficult to dig into
dependencies and set breakpoints in node modules when they are hidden.
https://github.com/user-attachments/assets/85e9c69f-c112-4a76-955f-76228ba689e6
=> Debug configuration for vitest

eng/pipelines/templates/steps/generate-doc.yml, eng/tools/generate-doc/package-lock.json
A recent package update broke the tool so we are adding a lock file to ensure we have a reliable execution.
For details the newer version of https://www.npmjs.com/package/shiki?activeTab=versions version 1.23.0 introduced a new dependency in https://github.com/shikijs/shiki/pull/832 which no longer compiles.
```
node_modules/oniguruma-to-es/types/parse.d.ts(61,49): error TS2339: Property 'orphan' does not exist on type '{}'.
node_modules/oniguruma-to-es/types/parse.d.ts(96,31): error TS2339: Property 'atomic' does not exist on type '{}'.
node_modules/oniguruma-to-es/types/parse.d.ts(96,39): error TS2339: Property 'flags' does not exist on type '{}'.
```
Until we figure out what the best way to fix those issues we are pinning to the older version using a lock file.
=> Add lock file for generate-doc tool

eng/pipelines/templates/stages/1es-redirect.yml
This is how it [used to run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4248236&view=logs&j=b1e79959-24d8-5aa9-2799-72d40c3e051b&t=1a422346-a7fc-5798-c84d-6e5b319d46e3).
In the past week, we started seeing very long builds due to codeQL kicking on:
- [example 1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4319395&view=logs&j=b1e79959-24d8-5aa9-2799-72d40c3e051b&t=1a422346-a7fc-5798-c84d-6e5b319d46e3)
- [example 2](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317694&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ce3b9047-3f2a-5c21-9248-60a34a33907c)
=> Disable codeql to avoid timeouts / long runtimes

eng/scripts/docs/Docs-ToC.ps1, sdk/openai/ci.yml
Work item to undo the workaround when proper support is implemented in `type2docfx`: https://github.com/Azure/azure-sdk-for-js/issues/31787
Docs with changes in place: https://review.learn.microsoft.com/en-us/javascript/api/overview/azure/openai-readme?view=azure-node-preview&branch=djurek%2Fopenai-readme
The change in `Docs-Toc.ps1` adds the OpenAI entry and then sorts the packages in Cognitive Services so that OpenAI ends up in the right place.
=> Workaround to enable OpenAI documentation on learn.microsoft.com

eng/tools/generate-doc/package-lock.json
Follow-up on https://github.com/Azure/azure-sdk-for-js/pull/31789 as the dependency was updated to not use the object deconstruction. See comment https://github.com/Azure/azure-sdk-for-js/pull/31789#issuecomment-2482218003
=> Update to latest version of dependencies for generate-doc tool

sdk/identity/identity/vitest.browser.config.ts, sdk/identity/identity/vitest.config.ts, sdk/identity/identity/vitest.managed-identity.config.ts
- @azure/identity
Bumps the `hookTimeout` and `testTimeout` for @azure/identity tests.
=> [identity] Bump vitest hook/test timeout

sdk/storage/storage-blob/swagger/README.md
=> Update blob swagger spec to a commit on main branch

sdk/servicebus/service-bus/src/session/messageSession.ts, sdk/servicebus/service-bus/test/public/sessionsTests.spec.ts
We have a check for when asking for any session, i.e., not providing a session id), but not receiving a link having a session id. However, the check is `if (!this._providedSessionId && !receivedSessionId)` which also evaluates to `true` for session id of empty string, which is valid session id.
This PR changes it to check for `undefined` so that session id of empty string doesn't lead to error being thrown.
=> [ServiceBus] fix issue of accepting session with empty string name

sdk/identity/identity/tests.yml, sdk/identity/test-resources-pre.ps1
- The resource deployment script for MI tests has been failing. Fixing this by:
1. Setting the location explicitly to `westus2`
Reason:
We need to deploy vms in the TME tenant, the default region of westus doesnt work. Have to set the Location to westus2, as it has quota for vms/aks. Otherwise we get the error like this :
```
Preflight validation check for resource(s) for container service t32358a8eb2bf4865 in resource group rg-identity-t32358a8eb2bf4865 failed. Message: The VM size of Standard_D2s_v3 is not allowed in your subscription in location 'westus'.
```
=> [Identity] Fix the resource deployment step for MI tests

common/config/rush/pnpm-lock.yaml, sdk/template/perf-tests/template/package.json, sdk/template/template/CHANGELOG.md, sdk/template/template/package.json, sdk/template/template/src/constants.ts, sdk/template/template/src/generated/generatedClientContext.ts, sdk/template/template/swagger/README.md
After we bump the version of template package, rush/pnpm now pulls
@azure/template@1.0.11 from npm.  That is a very old version that depends on
core-http@1.2.6 whose dependency `xml2js` caused a security alert.
This PR updates the perf-template package to depend on the version of
`@azure/template` in the repo, then `rush update --full` gets rid of those
outdated dependencies.
=> [test] update perf-template test dependency `template` version

sdk/ai/ai-projects/assets.json, sdk/ai/ai-projects/test/public/agents/assistants.spec.ts, sdk/ai/ai-projects/test/public/agents/functionTool.spec.ts, sdk/ai/ai-projects/test/public/agents/messages.spec.ts, sdk/ai/ai-projects/test/public/agents/runSteps.spec.ts, sdk/ai/ai-projects/test/public/agents/runs.spec.ts, sdk/ai/ai-projects/test/public/agents/streaming.spec.ts, sdk/ai/ai-projects/test/public/agents/threads.spec.ts, sdk/ai/ai-projects/test/public/agents/vectorStores.spec.ts, sdk/ai/ai-projects/test/public/connections/connections.spec.ts, sdk/ai/ai-projects/test/public/utils/createClient.ts
Serialize tests, define sanitization rules and connect to test recordings.
=> Allow running tests with recordings

common/tools/dev-tool/src/commands/run/testBrowser.ts, common/tools/dev-tool/src/commands/run/testNodeJSInput.ts, common/tools/dev-tool/src/commands/run/testNodeTSInput.ts, common/tools/dev-tool/src/commands/run/testNodeTsxTS.ts, common/tools/dev-tool/src/commands/run/testVitest.ts, common/tools/dev-tool/src/util/testProxyUtils.ts
- Invocation of `test-proxy` in the `child_process` will now support environment variables
- injects the current environment variables into the child's environment 
- Added a new flag `"test-proxy-debug"` to all the test commands, which enables debug logging for the test-proxy
- sets the environment variable `Logging__LogLevel__Default` to `"Debug"`
- Simply setting the environment variable `Logging__LogLevel__Default` to `"Debug"` will have the same effect as passing `test-proxy-debug` flag to the test commands.
Related to https://github.com/Azure/azure-sdk-tools/pull/9164
=> [dev-tool] Enable test-proxy Debug log-level

eng/pipelines/docindex.yml
This PR only updates the manual run conditions which were completely backwards. When running manually they wouldn't update main unless a variable was set and would always kick off the daily run which is only supposed to be kicked off during the scheduled run. The daily branch updates kick off a docs run against the daily branch which is created/updated when scheduled runs publish daily libraries. On the docs side, when the run against the daily branch completes, it nukes the branch and renames it to "daily/<date>-[ci-succeeded|ci-failed"]. Unless we're specifically testing something related to kicking off the daily runs, it should only ever be run from the scheduled doc index runs. Multiple daily runs can cause issues on the docs with the way the success/failure branch is created. …
=> Update the docIndex default for manual runs

sdk/playwrighttesting/microsoft-playwright-testing/review/microsoft-playwright-testing.api.md, sdk/playwrighttesting/microsoft-playwright-testing/src/common/customerConfig.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/messages.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/common/types.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/global/playwright-service-global-setup.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/global/playwright-service-global-teardown.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/core/playwrightService.spec.ts
Fixes https://github.com/microsoft/playwright-testing-service/issues/151
Playwright OSS had introduced support for multiple global setup/teardown files via https://github.com/microsoft/playwright/pull/32955. This SDK did not support array of string as input params and hence threw a TypeError.
Yes
=> fix(playwrighttesting): Add support for multiple global files

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/src/policies/bearerTokenAuthenticationPolicy.ts, sdk/core/core-rest-pipeline/test/bearerTokenAuthenticationPolicy.spec.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff
- Fix #31959 
- Fix #31934
Container Registry's custom challenge handler [is implemented as a class](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/containerregistry/container-registry/src/containerRegistryChallengeHandler.ts#L38). Its `authorizeRequest` and `authorizeRequestOnChallenge` use class fields to store the credential and token cycler. However, in the change to enable CAE support (#31501), we assign the class methods to a new object without binding them to the original object, meaning that the fields are no longer accessible using `this`.
This PR fixes the issue by binding the methods to the original object.
Yes, added a test case.
- #31501
=> [core] bind challengeCallbacks

eng/pipelines/templates/steps/analyze.yml
[Mariana hit this situation](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4363935&view=logs&j=36df4387-3551-57fa-098c-b43a23930261&t=8d5dfa63-dbe9-55f5-dc41-53a9f3f32393). 
The issue here is that I believe the failed step which _should_ have caused the artifact name to add the `FailedAttemptN` suffix was AFTER the artifact upload. That means during the analyze phase the order was:
- static analyze 1 (succeeded)
- static analyze 2 (succeeded)
- publish artifact 
- static analyze 3 (failed)
And if a failure occurs in `static analyze 3` step above, we will attempt to publish the same artifact name twice. That causes it's own error, and is what we're seeing on the linked build.
=> Avoid multiple artifact upload errors during retry

common/config/rush/pnpm-lock.yaml, sdk/computefleet/arm-computefleet/package.json, sdk/computeschedule/arm-computeschedule/package.json, sdk/connectedcache/arm-connectedcache/package.json, sdk/edgezones/arm-edgezones/package.json, sdk/fabric/arm-fabric/package.json, sdk/face/ai-vision-face-rest/package.json, sdk/iotoperations/arm-iotoperations/package.json, sdk/kubernetesruntime/arm-containerorchestratorruntime/package.json, sdk/mongocluster/arm-mongocluster/package.json, sdk/standbypool/arm-standbypool/package.json, sdk/terraform/arm-terraform/package.json, sdk/trustedsigning/arm-trustedsigning/package.json
Some generated packages still have v8. This PR upgrades them to v9. A separate
PR is submitted to update the code generator.
=> [EngSys] upgrade dev dependency `eslint` version to v9

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, sdk/identity/identity/assets.json, sdk/identity/identity/test/internal/node/deviceCodeCredential.spec.ts, sdk/identity/identity/test/node/msalNodeTestSetup.ts
With the recent upgrades to msal node (2.15 to 2.16) and msal common (14.15 to 14.16), the request uri used by msal has now been updated to include the client-request-id as a query parameter in the request uri. I have manually updated recordings of the tests to reflect the change, in order to fix the breaking recorded tests after upgrading dependecy on msal.
Unable to re-record the tests to auto-generate the recordings, due to tenant restrictions, hence manually updated the recordings.
Also unpinning the msal dependency that were pinned in this PR - https://github.com/Azure/azure-sdk-for-js/pull/31819/
=> [Identity] update recordings for msal-common and msal-node updates

sdk/playwrighttesting/microsoft-playwright-testing/package.json, sdk/playwrighttesting/microsoft-playwright-testing/review/microsoft-playwright-testing.api.md, sdk/playwrighttesting/microsoft-playwright-testing/src/common/types.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/core/playwrightService.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/index.ts
Playwright version <1.49 does not support string[], thus typescript throws an error if string array is being returned. Using any prevents this error.
```Type 'string | string[] | undefined' is not assignable to type 'string | undefined'.```
=> fix(playwrighttesting): use PlaywrightTestConfig from @playwright/test

sdk/eventgrid/eventgrid/CHANGELOG.md, sdk/eventgrid/eventgrid/package.json, sdk/eventgrid/eventgrid/review/eventgrid.api.md, sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts, sdk/eventgrid/eventgrid/src/generated/models/index.ts, sdk/eventgrid/eventgrid/src/generated/models/mappers.ts, sdk/eventgrid/eventgrid/src/index.ts, sdk/eventgrid/eventgrid/src/predicates.ts, sdk/eventgrid/eventgrid/src/tracing.ts, sdk/eventgrid/eventgrid/swagger/README.md
@Azure/eventgrid
NA
This PR consists of the following changes:
- Added new System Events:
- `Microsoft.ResourceNotifications.ContainerServiceEventResources.ScheduledEventEmitted`
- A new property `policyRunSummary` has been added to `StorageLifecyclePolicyCompletedEventData` interface.
- New properties `StorageLifecycleCompletionStatus` and `KnownStorageLifecycleCompletionStatus` have been added.
- https://github.com/Azure/azure-sdk-for-js/pull/28176 (This is the PR that adds similar events to the SDK in the 5.1.0 …
=> [@azure/eventgrid] Update System events for EG Version 5.9.0

eng/scripts/Generate-APIView-CodeFile.ps1
Install JS API parser and dependencies using local view of Azure DevOps feed for JS packages.
=> Install JS API parser using local view of devops feed

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
Values in the custom properties on both Network and Long Interval stats were not being correctly set and sent.
Yes
=> [Monitor OpenTelemetry Exporter] Fix Statsbeat Common Properties

sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/src/policies/tracingPolicy.ts, sdk/core/core-rest-pipeline/test/tracingPolicy.spec.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/src/policies/tracingPolicy.ts, sdk/core/ts-http-runtime/test/tracingPolicy.spec.ts
- @typespec/ts-http-runtime 
Fixes #31693 
According to https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status there are a few things we need to adjust:
| http status | span status |
| ----------- | ----------- |
| 1xx         | unset       |
| 2xx         | unset       |
| 3xx         | unset       |
| 4xx         | error       |
| 5xx         | error       |
Note: We should never mark the HTTP spans as success, leaving them unset instead, per the spec.
The 4xx and 5xx handling is handled in high level clients by the deserialization policy which turns this into an exception.
For RLC we must handle this ourselves within the tracingPolicy
=> [core] Handle 4xx and 5xx in tracing policy

common/tools/dev-tool/src/commands/admin/index.ts, common/tools/dev-tool/src/commands/admin/migrate-source.ts, sdk/communication/communication-alpha-ids/package.json, sdk/communication/communication-call-automation/package.json, sdk/communication/communication-chat/package.json, sdk/communication/communication-email/package.json, sdk/communication/communication-identity/package.json, sdk/communication/communication-job-router/package.json, sdk/communication/communication-phone-numbers/package.json, sdk/communication/communication-recipient-verification/package.json, sdk/communication/communication-rooms/package.json, sdk/communication/communication-short-codes/package.json, sdk/communication/communication-sms/package.json, sdk/communication/communication-tiering/package.json, sdk/communication/communication-toll-free-verification/package.json
- @azure-tools/communication-alpha-ids
- @azure/communication-call-automation
- @azure/communication-chat
- @azure/communication-email
- @azure/communication-identity
- @azure/communication-job-router
- @azure/communication-phone-numbers
- @azure-tools/communication-recipient-verification
- @azure/communication-rooms
- @azure/communication-sms
- @azure-tools/communication-tiering
- @azure-tools/communication-toll-free-verification
This adds a source fixup tool which fixes the imports for generated code from autorest using NodeNext TypeScript resolution.  This is used so that the code will compile after being generated via autorest to be compliant with our ESM builds.
- #31889
=> [dev-tool] Add source fixups for Communication packages

.github/CODEOWNERS
It should not be added after the more specific management entry
arm-healthdataaiservices. This PR moves it to the data plane section and also
adds the azure-health-deidentification directory so it matches the labels.
=> [CODEOWNERS] move health-deidentification to data plane section

common/tools/dev-tool/src/commands/admin/migrate-source.ts
When falling back to current package
=> [dev-tool] avoid resolving rush projects in migrate-source

common/config/rush/pnpm-lock.yaml, sdk/identity/identity-cache-persistence/api-extractor.json, sdk/identity/identity-cache-persistence/package.json, sdk/identity/identity-cache-persistence/src/index.ts, sdk/identity/identity-cache-persistence/src/platforms.ts, sdk/identity/identity-cache-persistence/src/provider.ts, sdk/identity/identity-cache-persistence/test/internal/node/clientCertificateCredential.spec.ts, sdk/identity/identity-cache-persistence/test/internal/node/clientSecretCredential.spec.ts, sdk/identity/identity-cache-persistence/test/internal/node/deviceCodeCredential.spec.ts, sdk/identity/identity-cache-persistence/test/internal/node/msalNodeTestSetup.ts, sdk/identity/identity-cache-persistence/test/internal/node/setup.spec.ts, sdk/identity/identity-cache-persistence/test/internal/node/usernamePasswordCredential.spec.ts, sdk/identity/identity-cache-persistence/test/snippets.spec.ts, sdk/identity/identity-cache-persistence/tsconfig.browser.config.json, sdk/identity/identity-cache-persistence/tsconfig.json, sdk/identity/identity-cache-persistence/vitest.browser.config.ts, sdk/identity/identity-cache-persistence/vitest.config.ts, sdk/test-utils/recorder/src/index.ts
- @azure/identity-cache-persistence
- https://github.com/Azure/azure-sdk-for-js/issues/31338
Migrates @azure/identity-cache-persistence to ESM/vitest via automation.
=> [identity] Migrate @azure/identity-cache-persistence to ESM/vitest

rush.json, sdk/appservice/arm-appservice-rest/package.json, sdk/compute/arm-compute-rest/package.json, sdk/containerservice/arm-containerservice-rest/package.json, sdk/network/arm-network-rest/assets.json, sdk/network/arm-network-rest/package.json, sdk/network/arm-network-rest/test/public/network_rest_sample.spec.ts, sdk/network/arm-network-rest/test/public/utils/recordedClient.ts, sdk/servicefabric/arm-servicefabric-rest/package.json, sdk/servicefabric/arm-servicefabric-rest/test/public/utils/recordedClient.ts
- @azure-rest/arm-appservice
- @azure-rest/arm-compute
- @azure-rest/arm-containerservice
- @azure-rest/arm-network
- @azure-rest/arm-servicefabric
Moves the following packages from the `client` to `mgmt` for the `sdk-type` to reflect these are ARM packages and not data-plane packages.
=> [EngSys] Update @azure-rest ARM packages to mgmt not client

eng/pipelines/docindex.yml
Right now, the docs SDK CI runs run a scheduled run against main and the timing of the runs is isn't great. The solution here is to have the docIndex runs kick off SDK CI the run against main the same way we're kicking off the run against the daily branch. This will remove anything fiddly.
As part of this change, add a parameter, defaulting to false, to determine whether or not the SDK CI run should be kicked off.
This is what the parameter I'd added looks like. It's the second checkbox down, unchecked by default.
This is the [docIndex run with it unchecked](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4391936&view=results). Notice it didn't kick off the SDK CI run.
This is the [docIndex run with it checked](https://dev.azure.com/azure-sdk/internal/_build/results?buildId …
=> Update docIndex to kick off the docs SDK CI run for main

sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
https://github.com/microsoft/ApplicationInsights-node.js/issues/1383#issuecomment-2386384129
=> [monitor-opentelemetry-exporter] Truncate operation name context tag

eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build.yml, eng/pipelines/templates/steps/run-eslint.yml, eng/pipelines/templates/steps/test-eslint.yml, eng/pipelines/templates/steps/test.yml, eng/tools/rush-runner/eslint.config.mjs, eng/tools/rush-runner/index.js, eng/tools/rush-runner/package.json, eng/tools/rush-runner/test/helper.spec.js, eng/tools/rush-runner/tsconfig.json, eng/tools/rush-runner/vitest.config.mjs
so that we can have better local developer experiences with help from compiler, test runner, formatter, and linter etc. when making changes. The code is kept in JavaScript in order for it to be invoked without having to install dev dependencies and build the package.
=> [EngSys] move `rush-runner.js` into a dev package

eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/build.yml
See title.
- @ckairen When @jeremymeng hits a large cross-cutting PR, we need to allow for a "couple" more minutes for the build and analyze steps to complete.
- This is also addressing the PR build failure that @deyaaeldeen is facing over in #32097
=> Addressing `private` package docs copy failure during pr - Extending PR Timeout on `Build`/`Analyze`

eng/pipelines/templates/steps/build.yml
The first PR, I looked at the .zip, and totally missed that the source included `docgen`, not `browser`.
Hotfix the hotfix.
=> Hotfix conditional include of documentation artifact copy

.vscode/cspell.json, sdk/batch/batch-rest/CHANGELOG.md, sdk/batch/batch-rest/LICENSE, sdk/batch/batch-rest/MigrationGuide.md, sdk/batch/batch-rest/README.md, sdk/batch/batch-rest/assets.json, sdk/batch/batch-rest/generated/batchClient.ts, sdk/batch/batch-rest/generated/clientDefinitions.ts, sdk/batch/batch-rest/generated/isUnexpected.ts, sdk/batch/batch-rest/generated/models.ts, sdk/batch/batch-rest/generated/outputModels.ts, sdk/batch/batch-rest/generated/parameters.ts, sdk/batch/batch-rest/generated/responses.ts, sdk/batch/batch-rest/package.json, sdk/batch/batch-rest/review/batch.api.md, sdk/batch/batch-rest/src/batchClient.ts, sdk/batch/batch-rest/src/clientDefinitions.ts, sdk/batch/batch-rest/src/isUnexpected.ts, sdk/batch/batch-rest/src/models.ts, sdk/batch/batch-rest/src/outputModels.ts, sdk/batch/batch-rest/src/parameters.ts, sdk/batch/batch-rest/src/responses.ts, sdk/batch/batch-rest/test/computeNodes.spec.ts, sdk/batch/batch-rest/test/jobs.spec.ts, sdk/batch/batch-rest/test/pools.spec.ts, sdk/batch/batch-rest/test/utils/envTokenCredential.ts, sdk/batch/batch-rest/test/utils/pool.ts, sdk/batch/batch-rest/test/utils/recordedClient.ts, sdk/batch/batch-rest/tsp-location.yaml
=> [@azure-rest/batch] update service api version to 2024-07-01

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
Resolves #28188
Our min/max tests scripts rely on the integration-test:node contents to
determine whether to use mocha or vitest for min/max tests. Since these were
skipped, this package's min/max tests assumed mocha was still used.
Adding these back fixes the min/max tests and ensures they run correctly and not
skipped.
=> [opentelemetry-instrumentation] Fix min/max tests

eng/tools/rush-runner/index.js
So we don't blow up the unit test invocation during builds, as is visible over in #32133
FYI @deyaaeldeen
=> Adding new test recorder to --to restricted packages

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/eslint.config.mjs, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tsconfig.browser.config.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tsconfig.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tsconfig.samples.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tsconfig.src.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tsconfig.test.json, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/vitest.config.ts, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/vitest.esm.config.ts
- @azure/opentelemetry-instrumentation-azure-sdk
N/A
N/A
=> [instrumentation] Precise Typechecking

sdk/attestation/attestation/eslint.config.mjs, sdk/attestation/attestation/package.json, sdk/attestation/attestation/samples-dev/modifyPolicyManagementCertificates.ts, sdk/attestation/attestation/samples-dev/utils/cryptoUtils.ts, sdk/attestation/attestation/src/attestationAdministrationClient.ts, sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts, sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts, sdk/attestation/attestation/tsconfig.browser.config.json, sdk/attestation/attestation/tsconfig.json, sdk/attestation/attestation/tsconfig.samples.json, sdk/attestation/attestation/tsconfig.src.json, sdk/attestation/attestation/tsconfig.test.json, sdk/attestation/attestation/vitest.config.ts, sdk/attestation/attestation/vitest.esm.config.ts
=> [attestation] Precise Typechecking

sdk/batch/batch-rest/eslint.config.mjs, sdk/batch/batch-rest/package.json, sdk/batch/batch-rest/src/paginateHelper.ts, sdk/batch/batch-rest/test/computeNodes.spec.ts, sdk/batch/batch-rest/test/poolScaling.spec.ts, sdk/batch/batch-rest/test/pools.spec.ts, sdk/batch/batch-rest/test/tasks.spec.ts, sdk/batch/batch-rest/test/utils/envTokenCredential.ts, sdk/batch/batch-rest/test/utils/pool.ts, sdk/batch/batch-rest/tsconfig.browser.config.json, sdk/batch/batch-rest/tsconfig.json, sdk/batch/batch-rest/tsconfig.samples.json, sdk/batch/batch-rest/tsconfig.src.json, sdk/batch/batch-rest/tsconfig.test.json, sdk/batch/batch-rest/vitest.config.ts, sdk/batch/batch-rest/vitest.esm.config.ts
=> [batch] Precise Typechecking

sdk/tables/data-tables/eslint.config.mjs, sdk/tables/data-tables/package.json, sdk/tables/data-tables/tsconfig.browser.config.json, sdk/tables/data-tables/tsconfig.json, sdk/tables/data-tables/tsconfig.samples.json, sdk/tables/data-tables/tsconfig.src.json, sdk/tables/data-tables/tsconfig.test.json, sdk/tables/data-tables/vitest.config.ts, sdk/tables/data-tables/vitest.esm.config.ts
=> [table] Precise Typechecking

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/liveMetrics.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts, sdk/monitor/monitor-opentelemetry/src/metrics/utils.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/standardMetrics.test.ts
The app map considers attributes taken from both standard metrics cloud resource properties as well as logs. While we correctly set cloud role attributes on logs in the exporter, we do not set these values correctly in AKS environments on standard metrics which leads to incorrect app map application names showing.
Yes
=> [Monitor OpenTelemetry] Fix Setting Cloud Resource Attributes in AKS Scenarios on Standard Metrics

sdk/eventgrid/eventgrid-namespaces/eslint.config.mjs, sdk/eventgrid/eventgrid-namespaces/package.json, sdk/eventgrid/eventgrid-namespaces/tsconfig.browser.config.json, sdk/eventgrid/eventgrid-namespaces/tsconfig.json, sdk/eventgrid/eventgrid-namespaces/tsconfig.samples.json, sdk/eventgrid/eventgrid-namespaces/tsconfig.src.json, sdk/eventgrid/eventgrid-namespaces/tsconfig.test.json, sdk/eventgrid/eventgrid-namespaces/vitest.config.ts, sdk/eventgrid/eventgrid-namespaces/vitest.esm.config.ts, sdk/eventgrid/eventgrid-system-events/eslint.config.mjs, sdk/eventgrid/eventgrid-system-events/package.json, sdk/eventgrid/eventgrid-system-events/src/cadl-generated/helpers/serializerHelpers.ts, sdk/eventgrid/eventgrid-system-events/tsconfig.browser.config.json, sdk/eventgrid/eventgrid-system-events/tsconfig.json, sdk/eventgrid/eventgrid-system-events/tsconfig.samples.json, sdk/eventgrid/eventgrid-system-events/tsconfig.src.json, sdk/eventgrid/eventgrid-system-events/tsconfig.test.json, sdk/eventgrid/eventgrid-system-events/vitest.config.ts, sdk/eventgrid/eventgrid-system-events/vitest.esm.config.ts, sdk/eventgrid/eventgrid/eslint.config.mjs, sdk/eventgrid/eventgrid/package.json, sdk/eventgrid/eventgrid/tsconfig.browser.config.json, sdk/eventgrid/eventgrid/tsconfig.json, sdk/eventgrid/eventgrid/tsconfig.samples.json, sdk/eventgrid/eventgrid/tsconfig.src.json, sdk/eventgrid/eventgrid/tsconfig.test.json, sdk/eventgrid/eventgrid/vitest.config.ts, sdk/eventgrid/eventgrid/vitest.esm.config.ts
- @azure/eventgrid-namespaces
- @azure/eventgrid
- @azure/evengrid-system-events
N/A
N/A
=> [eventgrid] Precise Typechecking

eng/pipelines/templates/steps/build.yml
Fixes a bug with the build pipeline where the `ChangedServices` is not properly quoted where in all other locations it is.
```sh
ChangedServices: /mnt/vss/_work/_temp/35cd28fd-3b0a-453b-8cde-112bdf15fc19.ps1:3
Line |
3 |  node eng/tools/rush-runner/index.js build $(ChangedServices) -package …
|                                              ~~~~~~~~~~~~~~~
| The term 'ChangedServices' is not recognized as a name of a cmdlet,
| function, script file, or executable program. Check the spelling of the
| name, or if a path was included, verify that the path is correct and try
| again.
##[error]PowerShell exited with code '1'.
Finishing: Build libraries
```
See https://dev.azure.com/azure-sdk/public/_build/results?buildId=4409811&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6 …
=> [EngSys] Fix build pipeline to quote ChangedServices

sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md, sdk/confidentialledger/confidential-ledger-rest/assets.json, sdk/confidentialledger/confidential-ledger-rest/package.json, sdk/confidentialledger/confidential-ledger-rest/review/confidential-ledger.api.md, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/clientDefinitions.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/confidentialLedger.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/index.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/isUnexpected.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/logger.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/models.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/outputModels.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/paginateHelper.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/parameters.ts, sdk/confidentialledger/confidential-ledger-rest/src/generated/src/responses.ts, sdk/confidentialledger/confidential-ledger-rest/swagger/README.md, sdk/confidentialledger/confidential-ledger-rest/test/public/usersEndpoint.spec.ts
@azure-rest/confidential-ledger
Add a single API - the ability to *list* users from the "app/users" endpoint. Please see the [doc](https://microsoft-my.sharepoint-df.com/:w:/g/personal/tachou_microsoft_com1/EVUirfTSrlhJslGy0i_eCOgBP_wb0gDTlBZOBynm5wWoCw?e=oaZcv4) here. 
Customers can `GET` details of a user from the `app/users/{userId}` endpoint, but needed to know the `userId` beforehand.  The API was amended in `preview-2024-01-26` to include the ability to list all users from the `app/users` endpoint.
Yes
[Spec API Change](https://github.com/Azure/azure-rest-api-specs/pull/27564)
=> [ConfidentialLedger] Generate SDK based on preview-2024-01-26 spec

sdk/servicebus/perf-tests/service-bus/package.json, sdk/servicebus/service-bus/vitest.unit.config.ts
The merged config pulls in unwanted integration tests.
=> [test] fix service bus unit test issue

common/tools/dev-tool/src/commands/admin/migrate-package.ts, common/tools/dev-tool/src/commands/index.ts, common/tools/dev-tool/src/commands/run/vendored.ts, common/tools/dev-tool/src/util/platform.ts
Some CLI scripts (prettier, npm, for example) would cause error on Windows when they are invoked via `spawn()` without `shell: true` options. This PR fixes the issue by applying the same workaround in PR #29414.
Resolves issue https://github.com/Azure/azure-sdk-for-js/issues/32202
=> [dev-tool] fix migrate-package issues on Windows

eng/tools/generate-doc/index.ts, eng/tools/generate-doc/package-lock.json, eng/tools/generate-doc/package.json
Passes `tsconfig.src.json` if available to TypeDoc. Otherwise, defaults to `tsconfig.json`.
=> [generate-doc] Discover tsconfig.src.json

common/tools/dev-tool/src/commands/run/build-test.ts, common/tools/dev-tool/src/util/resolveTsConfig.ts, common/tools/dev-tool/test/resolveTsConfig.spec.ts
This PR improves the `resolveTsConfig` function to be more complete in case other parts of our tooling may need to use it:
- Updates `resolveTsConfig` to use `fs/promises` and updates the `resolveConfig` function to be asynchronous.
- Resolves references to `${configDir}` in all paths in the configuration file.
=> [dev-tool] update resolveTsConfig

sdk/test-utils/ci.yml
to follow our convention. This may resolve an issue in our CI where Create-APIView script failed to retrieve
package name for it.
=> [test] update artifact name for `@azure-tools/test-utils-vitest`

eng/scripts/Language-Settings.ps1
Right now, we search:
`sdk/<servicedirectory>/<folder>/package.json`
This PR simply adds:
`sdk/<servicedirectory>/<folder>/perf-tests/<folder>/package.json`
Of course, an alternative is to use the equivalent of a `glob` under the service directory folder, where we _exclude_ certain folders from the globbing. Reason I didn't go with that is that I feel like the error case for that will be much more common than the one for this solution. Namely that every time we add a auto-generated folder structure that may contain a `package.json` under it, we'll need to add that folder to the `exclude` list. I have a strong feeling that's why this has been left as-is.
That being said, I'm entirely ok with going to the other methodology. Will post a comment with the total comparison of detected packages …
=> Enable perf-tests package discovery

eng/scripts/Language-Settings.ps1, sdk/appconfiguration/perf-tests/app-configuration/README.md
This PR has a touched file in the appconfiguration perf-test package. I will be reverting that prior to merge. I didn't do that with my last PR #32222 which is why this issue slipped through.
EDIT: getting successes across the board reverting the change to the perf-test package.
=> Fix stored `DirectoryPath` for a perf-test package

sdk/identity/identity/src/credentials/clientCertificateCredential.ts, sdk/identity/identity/src/credentials/clientCertificateCredentialModels.ts, sdk/identity/identity/src/credentials/defaultAzureCredential.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts, sdk/identity/identity/src/credentials/managedIdentityCredential/options.ts, sdk/identity/identity/src/credentials/onBehalfOfCredential.ts, sdk/identity/identity/src/index.ts, sdk/identity/identity/tsconfig.json
https://github.com/Azure/azure-sdk-for-js/issues/32227
The API extractor is showing the following warnings:
```
2024-12-14T01:02:41.6475182Z Warning: /mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/https://github.com/Azure+msal-node@2.16.2/node_modules/@azure/msal-node/dist/config/Configuration.d.ts:4:8 - (TS1192) Module '"http"' has no default export.
2024-12-14T01:02:41.6475819Z Warning: /mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/https://github.com/Azure+msal-node@2.16.2/node_modules/@azure/msal-node/dist/config/Configuration.d.ts:5:8 - (TS1192) Module '"https"' has no default export.
2024-12-14T01:02:41.6476323Z Warning: dist/browser/index.d.ts:20:39 - (TS2305) Module '"./credentials/clientCertificateCredential.js"' has no exported member …
```
=> [identity] Fix build warnings

sdk/appconfiguration/app-configuration/test/README.md
This was introduced in https://github.com/Azure/azure-sdk-for-js/pull/8398 and seems to have copied from the eventhub doc, accidentally:
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/eventhub/event-hubs/test/README.md#assign-owner-role-to-the-registered-application
This search for `authorize-access-event-hubs` has two hits:
https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-js%20authorize-access-event-hubs&type=code
=> Fix copy-paste typo in a link within AppConfig README.md to point to the expected AppConfig EntraID doc

common/config/rush/pnpm-lock.yaml, sdk/test-utils/test-credential/api-extractor.json, sdk/test-utils/test-credential/package.json, sdk/test-utils/test-credential/src/browserRelayCredential.ts, sdk/test-utils/test-credential/src/index.ts, sdk/test-utils/test-credential/test/browserRelayCredential.spec.ts, sdk/test-utils/test-credential/test/index.spec.ts, sdk/test-utils/test-credential/test/noOpCredential.spec.ts, sdk/test-utils/test-credential/tsconfig.browser.config.json, sdk/test-utils/test-credential/tsconfig.json, sdk/test-utils/test-credential/tsconfig.samples.json, sdk/test-utils/test-credential/tsconfig.src.json, sdk/test-utils/test-credential/tsconfig.test.json, sdk/test-utils/test-credential/vitest.browser.config.ts, sdk/test-utils/test-credential/vitest.config.ts, sdk/test-utils/test-credential/vitest.esm.config.ts
- @azure-tools/test-credential
- https://github.com/Azure/azure-sdk-for-js/issues/31338
Migrates @azure-tools/test-credential to ESM/vitest via automation.
=> [test-utils] Migrate @azure-tools/test-credential to ESM/vitest

sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/util/file.ts
Document Intelligence bumping its `typescript` dev dependency version to
~5.7.2, and caused some other packages to also use ~5.7.2.  This leads to the
build error in ts-http-runtime, where newer version of lib.dom.d.ts expects
`bytes` property in `File` type.
`bytes` property was added previously in PR
https://github.com/Azure/azure-sdk-for-js/pull/31990, but got removed in PR
https://github.com/Azure/azure-sdk-for-js/pull/31627 maybe due to bad merge?
It also seems to be a pnpm or rush bug that the pnpm-lock.yaml file have
typescript@5.7.2 for other packages that depends on ~5.6.2, for example,
ts-http-runtime:
https://github.com/Azure/azure-sdk-for-js/blob/8a7d4e90ac3795b0494653eb04cebd6bc0f3213d/common/config/rush/pnpm-lock.yaml#L19848
This also results in api.md changes for …
=> [core] fix js - core build

common/tools/dev-tool/src/commands/admin/migrate-source.ts
Fixes the source migration to not look for the `NodeNext` but to make the migration.  Also fixes the idempotency of the migration for config files.
=> [dev-tool] Fix source fixups per tsconfig changes

common/tools/dev-tool/src/commands/admin/create-migration.ts, common/tools/dev-tool/src/commands/migrate.ts, common/tools/dev-tool/src/config/rollup.base.config.ts, common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/package.json, common/tools/dev-tool/test/samples/files/expectations/output-customization/typescript/package.json, common/tools/dev-tool/test/samples/files/expectations/simple/typescript/package.json, common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/package.json, common/tools/dev-tool/test/samples/files/expectations/special-characters/typescript/package.json
- some eslint-disable directives no long apply
- dev-tool stays at typescript@~5.6.2 but its unit-test baseline got upgraded incorrectly in the last NO_CI commit
=> [dev-tool] fix test and linting

sdk/test-utils/recorder/src/utils/env-browser.mts, sdk/test-utils/test-utils-vitest/src/multiVersion.ts, sdk/test-utils/test-utils-vitest/test/multiVersion.spec.ts
- @azure-tools/test-utils-vitest
Adds multi-version testing to vitest, which requires globals in order to work.
=> [test-utils-vitest] Add multiversion testing to vitest

sdk/apimanagement/api-management-custom-widgets-scaffolder/eslint.config.mjs, sdk/formrecognizer/ai-form-recognizer/eslint.config.mjs
The custom rules to suppress errors/warnings for bin scripts were removed in
previous commits. This PR restores them.
=> [eslint] restore custom rules for bin scripts

sdk/playwrighttesting/microsoft-playwright-testing/src/reporter/mptReporter.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/reporterUtils.ts, sdk/playwrighttesting/microsoft-playwright-testing/src/utils/storageClient.ts
@azure-microsoft-playwright-testing
=> fix(playwrighttesting): handling other attachments

sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/customising-service-parameters/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/customising-service-parameters/playwright.service.config.js, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/manually-connecting-to-browsers/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/manually-connecting-to-browsers/tests/sample.spec.js, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/set-default-authentication-mechanism/playwright.service.config.js, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/javascript/using-connect-options/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/customising-service-parameters/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/customising-service-parameters/playwright.service.config.ts, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/manually-connecting-to-browsers/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/manually-connecting-to-browsers/tests/sample.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/package.json, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/set-default-authentication-mechanism/playwright.service.config.ts, sdk/playwrighttesting/microsoft-playwright-testing/samples/v1/typescript/using-connect-options/package.json
=> chore(playwrighttesting): improve javascript and typescript samples

sdk/identity/identity/src/credentials/azureCliCredential.ts, sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
- @azure/identity
- #32374
Fixes the case-sensitivity issue with getting environment variables such as enforcing `SYSTEMROOT` instead of a cased `SystemRoot`.
=> [identity] Fix case-sensitivity for Windows environment variables

sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileAccessControl.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemHelpers.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts
- @azure/monitor-opentelemetry-exporter
- https://github.com/Azure/azure-sdk-for-js/issues/32374
Fixes the case-sensitivity issue with getting environment variables such as enforcing `SYSTEMDRIVE` instead of a cased `systemdrive`.
=> [monitor] Fix possible case sensitivity issues for Windows env vars

common/tools/eslint-plugin-azure-sdk/eslint.perftests.config.mjs, common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-customized.ts, common/tools/eslint-plugin-azure-sdk/src/configs/index.ts
This address the issue when running `lint:fix` using the first suggestion provided by typescript-eslint
>  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/test/public/utils/recordedClient.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
That TSConfig uses project "references" and doesn't include `<tsconfigRootDir>/test/public/utils/recordedClient.ts` directly, which is not supported by `parserOptions.project`.
Either:
>- Switch to `parserOptions.projectService`
>- Use an ESLint-specific TSConfig
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#are-typescript-project-references-supported
-------
eslint-plugin
#32350
=> [eslint-plugin] switch to `parserOptions.projectService`

common/tools/dev-tool/src/templates/sampleReadme.md.ts
On Windows, relative path string has "\" as path separator, which leads to broken GitHub links to the sample code files. This PR normalizes path separator in relative paths to "/" when generate file names and links in sample README.
=> [dev-tool] use "/" in relative paths in published sample README

eng/tools/rush-runner/index.js, eng/tools/rush-runner/test/helpers.spec.js, sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/namespaceActivities.js, sdk/eventgrid/eventgrid-namespaces/samples/v1/javascript/package.json, sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/package.json, sdk/eventgrid/eventgrid-namespaces/samples/v1/typescript/src/namespaceActivities.ts
All packages using CI
@qiaozha noticed that tests were no longer failing the build. After some investigation, I realized that PR #32148 introduced a regression with how the process exitCode was being propagated. Previously, we were setting it globally via `process.exitCode` where we spawn the node process, but this was refactored to use return codes.
However, the return code was never used when the task was anything except `lint` and `check-format` meaning that build and test operations did not report failure correctly.
In the future, we should figure out a better way to abstract and test this script's return codes, but I'd like to get a fix in to prevent bad PRs from being merged in the meantime.
=> [engsys] Fix rush-runner

sdk/tables/data-tables/CHANGELOG.md, sdk/tables/data-tables/review/data-tables.api.md, sdk/tables/data-tables/src/TableClient.ts, sdk/tables/data-tables/src/TableTransaction.ts
Fixes #28624
`submitTransaction` on `TableClient` didn't allow for passing request-level options, such as an `AbortSignal` to cancel the request.
=> [data-tables] Add options to submitTransaction

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts, sdk/core/core-amqp/test/config.spec.ts
We should but currently don't extract point number from the endpoint into connection configuration. This PR fixes that.
=> [core-amqp] parse port number from endpoint

sdk/servicebus/service-bus/CHANGELOG.md, sdk/servicebus/service-bus/src/util/connectionStringUtils.ts, sdk/servicebus/service-bus/test/internal/unit/connectionString.spec.ts
In local emulator scenario, a custom port may be specified in the endpoint of a
connection string. This PR ensures the extracted namespace doesn't contain the
port.
-------
=> [ServiceBus] remove port in namespace extracted from connection string

sdk/documentintelligence/ai-document-intelligence-rest/CHANGELOG.md, sdk/documentintelligence/ai-document-intelligence-rest/MIGRATION-FR_v4-DI_v1.md, sdk/documentintelligence/ai-document-intelligence-rest/README.md, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeDocumentByModelId.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeIdentityDocument.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeInvoice.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeReceipt.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeReceiptByModelId.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/analyzeW2TaxForm.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/classifyDocument.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/extractLayout.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples-dev/readDocument.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeDocumentByModelId.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeIdentityDocument.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeInvoice.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeReceipt.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeReceiptByModelId.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/analyzeW2TaxForm.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/classifyDocument.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/extractLayout.ts, sdk/documentintelligence/ai-document-intelligence-rest/samples/v1/typescript/src/readDocument.ts
@azure-rest/ai-document-intelligence-rest
#32326 
Some types renamed in version 1.0.0 are not reflected everywhere
- 
This PR only change types, there is no test for that as far as I know.
-
-
=> update CHANGELOG and samples to reflect additional type renamings in document intelligence

sdk/pullrequest.yml
We want to exclude cosmos data plane as it has a special CI pipeline.
=> [EngSys] fix typo in pullrequest pipeline exclusion

sdk/template/template/CHANGELOG.md
I think https://github.com/Azure/azure-sdk-for-js/pull/31849 introduced this invalid date which has thrown off the changelog parser.
=> Fix invalid date in template changelog

common/tools/eslint-plugin-azure-sdk/package.json, sdk/communication/communication-sms/README.md
There's a regression from eslint-plugin's ESM migration.  `./prettier.json` should be exported
as-is to be used by other packages as their formatting configs in VS Code.
=> [eslint-plugin] fix prettier.json export

sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
PR #32406 adds the `port` property to parsed connection configuration even it is
`undefined`. While the effect is similar, it broke an Event Hub unit test that
expects the `port` property to not exist when a connection string does not
specify a port.
This PR changes to only add the `port` property when it is not `undefined`.
-------
We could update broken test to check for `undefined` but it is slightly better to keep the existing behavior
=> [core-amqp] set `port` when it is not undefined in connection config

eng/pipelines/templates/steps/analyze.yml, sdk/template/template/CHANGELOG.md
@jeremymeng I guess my last change didn't fix the template pipeline. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4392967&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d34cfe88-f3e1-5ca1-ec50-18a5cea1099a
It looks like after @scbedd refactoring we aren't setting the template package version early enough. We need to set that version before the save package properties otherwise things like verify change log will fail as what is on disk doesn't match the package properties.
=> Update template version before dumping package props

sdk/anomalydetector/ai-anomaly-detector-rest/README.md, sdk/anomalydetector/ai-anomaly-detector-rest/package.json, sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_change_point.ts, sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_entire_series_anomaly.ts, sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_last_point_anomaly.ts, sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_multivariate_detection.ts, sdk/anomalydetector/ai-anomaly-detector-rest/test/public/anomalydetector.spec.ts, sdk/anomalydetector/ai-anomaly-detector-rest/test/snippets.spec.ts, sdk/anomalydetector/ai-anomaly-detector-rest/vitest.browser.config.ts
- @azure-rest/ai-anomaly-detector
Updates snippets for all projects under the `anomalydetector` folder.
=> [anomaly-detector] Update projects to use snippets

sdk/communication/communication-common/CHANGELOG.md, sdk/communication/communication-common/README.md, sdk/communication/communication-common/src/entraTokenCredential.ts, sdk/communication/communication-common/test/public/node/entraCommunicationTokenCredential.spec.ts
=> Ops new endpoints

common/tools/dev-tool/src/util/browserRelayServer.ts, common/tools/dev-tool/src/util/testProxyUtils.ts
Due to https://github.com/nodejs/node/issues/52909, fetch() may be stuck
indefinitely in NodeJS v20 or lower if body is not read. This PR consumes the
response body to avoid that from happening.
=> [dev-tool] consume response body of fetch() result

sdk/appplatform/arm-appplatform/README.md, sdk/appplatform/arm-appplatform/package.json, sdk/appplatform/arm-appplatform/test/appplatform_examples.spec.ts, sdk/appplatform/arm-appplatform/test/snippets.spec.ts
- @azure/arm-appplatform
Updates all `appplatform` projects to use snippets extraction.
=> [appplatform] Update appplatform projects to use snippets extraction

sdk/core/abort-controller/package.json, sdk/core/core-amqp/package.json, sdk/core/core-auth/package.json, sdk/core/core-client-rest/package.json, sdk/core/core-client/package.json, sdk/core/core-http-compat/package.json, sdk/core/core-lro/package.json, sdk/core/core-paging/package.json, sdk/core/core-rest-pipeline/package.json, sdk/core/core-sse/package.json, sdk/core/core-tracing/package.json, sdk/core/core-util/package.json, sdk/core/core-xml/package.json, sdk/core/logger/package.json, sdk/core/ts-http-runtime/package.json
These declaration source map files are useful for code navigation (go-to-implementation) in local
development. However, since we don't pack source code, they are not usable in published packages.
This PR excludes them from packing.
=> [Core] stop packing d.ts.map files

sdk/identity/identity/src/util/processMultiTenantRequest.ts
- @azure/identity
- #32466
Fixes the error message for `tenantId` matching in the `processMultiTenantRequest` function in the `@azure/identity` package.  Previously used `tenantId` from the constructor instead of the resolved `tenantId`.
=> [identity] Fixing error message for tenantID matching

sdk/identity/identity/samples/AzureIdentityExamples.md
Update the Azure Identity examples README so customers interested in `ChainedTokenCredential` are directed to the supporting doc on Learn.
=> Link to credential chains doc

sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/javascript/README.md, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/javascript/listFormats.js, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/javascript/translateFromBlob.js, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/typescript/README.md, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/typescript/package.json, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/typescript/src/listFormats.ts, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/typescript/src/translateFromBlob.ts, sdk/documenttranslator/ai-document-translator-rest/samples/v1-beta/typescript/tsconfig.json
The apiref links don't have correct scope `@azure-rest`. This fixes them
by re-publishing samples. No changes around features used in samples.
=> [samples][ai-document-translator] fix broken links

common/tools/dev-tool/src/commands/admin/migrate-package.ts, common/tools/dev-tool/src/util/admin/migrate-package/codemods/fixSourceFile.ts
- #32184
Addresses the feedback about the migration for the [ARM Migration](https://github.com/Azure/azure-sdk-for-js/issues/32184#issuecomment-2552944717)
=> [dev-tool] Update migration tool for ARM scripts

sdk/changes/arm-changes/README.md, sdk/changes/arm-changes/package.json, sdk/changes/arm-changes/test/sampleTest.spec.ts, sdk/changes/arm-changes/test/snippets.spec.ts
- @azure/arm-changes
Updates the `changes` projects to use snippets extraction.
=> [changes] Update changes projects to use snippet extraction

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/src/restError.ts, sdk/core/core-client-rest/test/createRestError.spec.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/src/client/restError.ts, sdk/core/ts-http-runtime/test/client/createRestError.spec.ts
Noticed with Jose when testing the todo end-to-end demo TypeSpec.
If we receive an unexpected status from the service (an error or otherwise), we try to create an error with `createRestError`. It is possible that a service might for some reason return an error response with no body, intentionally or otherwise. Currently this causes a TypeError when createRestError tries to read properties off of the body. This PR guards against the body being undefined so that the expected `RestError` is thrown instead.
=> [core-client-rest] correctly throw RestError when response has no body

eng/scripts/docs/tests/rex-tool-tests.json
This is an old package, tooling and dependencies have moved on, and it's not a valuable exercise of type2docfx.
=> Remove @azure/identity-cache-persistence@1.0.0 from regression testing. 

common/tools/dev-tool/src/templates/sampleReadme.md.ts, common/tools/dev-tool/src/util/samples/generation.ts, common/tools/dev-tool/src/util/samples/info.ts
Sample generation tests use package names that doesn't have scope so they are broken by e8acf696589 which
assumes package names are always in the form of "@scope/packageName". This PR handles the non-scope case.
=> [dev-tool] fix unit tests

common/tools/dev-tool/src/commands/admin/migrate-package.ts
as it prevents `ts-morph` from finding any files in the project thus no further
source transformations can be done.  This PR reverts the previous change.
=> [dev-tool] don't add `files: []` in migration-package

.github/CODEOWNERS
Updated "Health Deidentification" so it uses a team alias instead of user aliases. Left the original user aliases for now. 
New team alias reference: https://github.com/orgs/Azure/teams/healthdatadeidentification/members
/sdk/healthdataaiservices/azure-health-deidentification
Allows easier management of team codeowners, and avoids a new PR on every member change
=> Update CODEOWNERS Health Deidentification to use team alias

sdk/healthdataaiservices/azure-health-deidentification/test-resources.bicep
Created storage was being flagged by security wave.
All tests passing after changes and advisor recommendations all green.
@azure/arm-healthdataaiservices
Created storage being flagged by security wave.
Storage should be Identity-Based Access Control, and then apply the AllowSharedKeyAccess = false
https://eng.ms/docs/products/azure-storage/security/standards/identity-based-access
Service 360 flag
Followed recommended settings here and applied same settings used in main service.
https://eng.ms/docs/products/azure-storage/security/standards/identity-based-access
No, only storage settings.
Related only where the New-TestResources.ps1 cmd fails without this PR (missing test data).
https://github.com/Azure/azure-sdk-for-js/pull/31921
`..\..\..\eng\common\TestResources\New-TestResources.ps1 …
=> Added extra hardening security

sdk/storage/storage-blob-changefeed/package.json, sdk/storage/storage-blob/package.json, sdk/storage/storage-file-datalake/package.json, sdk/storage/storage-file-share/package.json, sdk/storage/storage-queue/package.json
The recent Mocha upgrades broke storage integration tests on Windows, likely due to their upgrade of yargs dependency. With single quotes, we now get errors like
>Error: No test files found: "'dist-esm/storage-file-share/test/**/*.spec.js'"
This PR changes to use escaped doubled quotes in the scripts.
=> [storage][test] fix integration by double-quoting file patterns

sdk/quantum/quantum-jobs/assets.json, sdk/quantum/quantum-jobs/test/public/quantumJobClient.spec.ts
Reduced number of entries in the result array of a recorded response from over 1300 to 35.
https://github.com/Azure/azure-sdk-assets/blob/f7105f0ae9cc5e7582368af3c4ade9abeae6d7c3/js/sdk/quantum/quantum-jobs/recordings/node/quantum_job_lifecycle/recording_test_quantum_job_lifecycle.json#L192
=> [quantum-jobs][test] reduce size of recorded data

common/tools/eslint-plugin-azure-sdk/src/rules/github-source-headers.ts, common/tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts, common/tools/eslint-plugin-azure-sdk/tests/fixture/tsconfig.json, common/tools/eslint-plugin-azure-sdk/tests/rules/github-source-headers.ts, common/tools/eslint-plugin-azure-sdk/tests/rules/ts-doc-internal.ts
Some of our custom rules perform operations on TypeScript files only and they use a regex of `/\.ts$/.test(fileName)` to check whether a file is TypeScript code file or not. With the migration to ESM we can have .mts and .cts files as well. This PR updates the pattern to also match those files.
`@azure/eslint-plugin-azure-sdk`
=> [eslint-plugin] update regex of matching TypeScript file extentions

common/tools/dev-tool/src/commands/admin/list/index.ts, common/tools/dev-tool/src/commands/admin/list/snippets-migrations.ts
Adds a list command for `snippets-migrations` to the `dev-tool` package to list the progress for snippet extraction.
=> [dev-tool] Add counters for snippets migrations

sdk/cosmosdb/cosmos/review/cosmos.api.md, sdk/cosmosdb/cosmos/src/common/constants.ts, sdk/cosmosdb/cosmos/src/documents/ConnectionPolicy.ts, sdk/cosmosdb/cosmos/src/retry/resourceThrottleRetryPolicy.ts, sdk/cosmosdb/cosmos/src/retry/retryOptions.ts, sdk/cosmosdb/cosmos/src/retry/retryUtility.ts
@azure/cosmos
#27312
This PR makes `RetryOptions` for throttled requests in `ConnectionPolicy` optional. User can now pass some of the retry options, default value is picked for rest of the options.
N/A
=> [@azure/cosmos] Make retryOptions as Optional

sdk/cosmosdb/cosmos/review/cosmos.api.md, sdk/cosmosdb/cosmos/src/request/RequestOptions.ts, sdk/cosmosdb/cosmos/src/request/SharedOptions.ts
@azure/cosmos
#27336
This PR moves `consistencyLevel` and `disableRUPerMinuteUsage` from `RequestOptions` to `SharedOptions`. 
These options are used in both `RequestOptions` and `FeedOptions` and gets extended by `SharedOptions`.
N/A
=> [@azure/cosmos] Move consistencyLevel and disableRUPerMinuteUsage to SharedOptions

sdk/communication/communication-identity/test/public/communicationIdentityClient.mocked.spec.ts, sdk/communication/communication-phone-numbers/test/internal/headers.spec.ts, sdk/communication/communication-phone-numbers/test/internal/siprouting/headers.spec.ts
- @azure/communication-phone-numbers
- @azure/communication-identity
Fixes vitest methods to ensure after each a `vi.restoreAllMocks` is called to ensure the mock is reset.
- #32680
=> [communication] Fix vitest mock teardown calls

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/logs/logRecordProcessor.ts, sdk/monitor/monitor-opentelemetry/src/metrics/quickpulse/utils.ts, sdk/monitor/monitor-opentelemetry/src/traces/spanProcessor.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/metrics/liveMetrics.test.ts
Crashes experienced when opening live metrics when using Next.js versions > 12 as some of the requests sent do not contain a valid HTTP.url value which throws an exception when passed to `URL()`.
Yes, test case added to ensure that requests without a populated HTTP field don't throw exceptions.
=> [Monitor OpenTelemetry] Live Metrics Next.js > 12 Fix

sdk/servicebus/service-bus/package.json, sdk/servicebus/service-bus/test/public/amqpAnnotatedMessage.spec.ts, sdk/servicebus/service-bus/test/stress/app/package.json, sdk/servicebus/service-bus/test/stress/app/src/scenarioLongRunning.ts, sdk/servicebus/service-bus/test/stress/app/src/scenarioShortLivedReceivers.ts, sdk/servicebus/service-bus/test/stress/app/src/utils.ts
- @azure/service-bus
- #32739
Removes the `uuid` package and associated `@types/uuid` as they are not needed since we have `randomUUID` from `@azure/core-util`.
=> [service-bus] Remove uuid package and types

sdk/cosmosdb/cosmos/package.json, sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts, sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForPartitionKey.ts, sdk/cosmosdb/cosmos/test/internal/unit/changeFeed/ChangeFeedForEpkRange.spec.ts
@azure/cosmos
#32652
- SDK is currently incorrectly handling TimeoutError in items.getChangeFeedIterator(). Empty response gets generated internally instead of throwing the error.
- Fix unit test command
=> [@azure/cosmos] fix changefeed iterator TimeOutError bug

common/tools/dev-tool/src/commands/run/testVitest.ts, common/tools/dev-tool/src/util/testProxyUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/eventhub.spec.ts
This pull request addresses an issue in [PR #32668](https://github.com/Azure/azure-sdk-for-js/pull/32668) where the existence of the `assets.json` file was not checked before pulling the recordings. This PR adds a check for the file's existence.
Introduced retries for the 'restore' command to mitigate EBUSY errors, which occur due to resource locking by simultaneous pipeline processes.
This change fixes the failing pipelines, such as the `monitor-opentelemetry-exporter` package.
- **Before**: [Pipeline Results](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4512250&view=logs&j=2993fb17-9fe5-5b0b-e997-efa0cab8f900&t=dd1086b5-315c-5d00-e372-83915904aafa) ❌
- **After**: [Pipeline Results](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4512907&view=logs&j=2a01393f …
=> [dev-tool] Restore the assets only when they are present

sdk/servicebus/service-bus/review/service-bus.api.md, sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts, sdk/servicebus/service-bus/src/util/connectionStringUtils.ts, sdk/servicebus/service-bus/test/internal/unit/atomAdminClient.spec.ts, sdk/servicebus/service-bus/test/internal/unit/connectionString.spec.ts
even though today service bus emulator doesn't support on the fly management
API, the support may be added in the future.  This PR updates the atom admin
client to use HTTP when emulator is targeted.
=> [ServiceBus] update atom admin client to use HTTP for emulator

sdk/cosmosdb/cosmos/review/cosmos.api.md, sdk/cosmosdb/cosmos/src/ClientContext.ts, sdk/cosmosdb/cosmos/src/CosmosClient.ts, sdk/cosmosdb/cosmos/src/CosmosClientOptions.ts, sdk/cosmosdb/cosmos/src/common/constants.ts, sdk/cosmosdb/cosmos/src/common/platform.ts
@azure/cosmos 
#32191 
#20289 
Currently there is no way to change user agent once CosmosClient has been created.But with addition of CosmosDB Integrations with AI libraries like Langchain and LlamaIndex, we want to track the adoption. Users can pass the CosmosClient instance itself during initialization of different stores (eg. vectorStore) which leads to default value of user-agent getting used and does not help in tracking adoption of these AI libraries. Also, if connectionString is passed, there is no way to set other CosmosClientOptions.
After merging this PR we will be able to :
1. Update the User Agent string after creating the client.
2. We can pass Connection string in the CosmosClientOptions itself, along with the other configurations during client creation.
=> Made User Agent configurable post Cosmos client creation ; Added a new header x-ms-useragent

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/src/retry.ts, sdk/core/core-amqp/test/retry.spec.ts, sdk/core/core-amqp/tsconfig.src.json, sdk/eventhub/event-hubs/tsconfig.test.json, sdk/servicebus/service-bus/test/internal/unit/abortSignal.spec.ts, sdk/servicebus/service-bus/test/internal/unit/messageSender.spec.ts, sdk/servicebus/service-bus/test/internal/unit/receiverCommon.spec.ts, sdk/servicebus/service-bus/test/internal/unit/streamingReceiver.spec.ts, sdk/servicebus/service-bus/test/public/utils/chai.ts, sdk/servicebus/service-bus/test/public/utils/testUtils.ts, sdk/servicebus/service-bus/tsconfig.test.json
@azure/core-amqp
https://github.com/Azure/azure-sdk-for-js/issues/32767
See linked issue.
We shouldn't set the message property on the error object, hence using `AggregateError`.
N/A
N/A
=> [core-amqp] Use AggregateError

common/tools/dev-tool/src/commands/run/testVitest.ts, common/tools/dev-tool/src/util/testProxyUtils.ts
This PR reverts the recent changes from [PR 32668](https://github.com/Azure/azure-sdk-for-js/pull/32668) and [PR 32752](https://github.com/Azure/azure-sdk-for-js/pull/32752). 
These changes did not fully resolve the race condition issues, as we observed continued failures, albeit with lesser frequency, even after increasing the timeouts. 
Increasing the timeouts further does not seem like a clean solution. Therefore, reverting these changes in this PR.
- Revert the changes introduced in PR 32668 and PR 32752.
- [TO DO] A new approach to restore assets sequentially in a separate job will be implemented in a follow-up PR.
Issues observed at the current state of restoring assets: [Issue 32805](https://github.com/Azure/azure-sdk-for-js/issues/32805)
=> [dev-tool] Revert restoring assets

eng/pipelines/templates/steps/test.yml, eng/tools/rush-runner/index.js, eng/tools/rush-runner/package.json, eng/tools/rush-runner/src/actions.js, eng/tools/rush-runner/src/args.js, eng/tools/rush-runner/src/rush.js, eng/tools/rush-runner/src/spawn.js, eng/tools/rush-runner/src/testProxyRestore.js
Fixes https://github.com/Azure/azure-sdk-for-js/issues/32805
Related PR: https://github.com/Azure/azure-sdk-for-js/pull/32806
The original issue was that "restoring recordings when the first test is triggered" takes time, leading to flakily failing unit-test pipelines. There is a need to have the recordings pre-loaded before the tests are run in the CI pipeline.
#32806 - Earlier attempts of pre-restoring recordings in CI for playback tests with retries and increased timeouts to avoid race conditions did not fully solve the problem. This PR is a follow up of that.
Employs a new approach to restore assets sequentially using the test-proxy tool, which is already downloaded by the CI pipeline.
The assets restoration process is applied only to the unit-test pipeline in playback mode.
Updates …
=> Restore assets before unit-tests are run

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.spec.ts
#32387 
We should remove the faulty logic that filters span exception events until the changes can be made upstream in OpenTelemetry JS to support proper filtering logic.
=> [OpenTelemetry Exporter] Remove Faulty Span Exception Emitting Logic

common/tools/dev-tool/src/commands/admin/migrate-package.ts
as @microsoft/rush might not be available in CI pipeline and the recommendation
for CI is to use `common/scripts/install-run-rushx.js`. For this scenario though
"npm run" is good enough.
-------
dev-tool
=> [dev-tool] replace "rushx" with "npm run" in migrate-package

common/config/rush/pnpm-lock.yaml, sdk/network/arm-network/package.json, sdk/servicefabricmanagedclusters/arm-servicefabricmanagedclusters/package.json
for leftover packages to make them consistent with rest of this repository.
=> [EngSys] bump dev dependency `mocha` to v11

common/config/rush/pnpm-lock.yaml, sdk/quota/arm-quota/package.json
for arm-quota. The codegen hasn't been updated yet that may be why v2 was
re-introduced.
related codegen PR: https://github.com/Azure/autorest.typescript/pull/3046
=> [EngSys] bump vitest dev dependencies to v3

sdk/web-pubsub/web-pubsub/vitest.config.ts
Due to some vitest bug, type check testing is failing for web-pubsub after PR #32712.
This PR disables type checking test for web-pubsub.
=> [web-pubsub] disable type check test

sdk/openai/openai/test/utils/createClients.ts, sdk/openai/openai/test/utils/setup.ts, sdk/test-utils/test-credential/review/test-credential.api.md, sdk/test-utils/test-credential/src/index.ts
Introduces the `createLiveCredential` function for tests that run exclusively in live mode. Unlike `createTestCredential`, which defaults to playback mode and returns a non-functional token unless the `TEST_MODE` environment variable is set to "live" or "record," `createLiveCredential` always provides a functional token without requiring any additional configuration.
=> [test-credential] Export createLiveCredential

eng/pipelines/templates/steps/build.yml
Information in package info file is used by CI to create/update package work item. Package info file is created after version is updated to daily dev version by CI so package work item adds daily alpha version as next version to be released. Package work item should show the version before converting to alpha version and solution is to generate the package properties file before version is updated to alpha version.
=> Save package version in package info file before updating version to daily alpha

.vscode/launch.json
It appears that with `rushx` we can run NPM scripts under sub directories. This PR adds debug launch
configurations that start debugging current active test file in the editor.
I had to add `*-customized:current-file` configurations because some packages pass additional arguments with
`--` already so it would be wrong to include `"--"` in the `"args"` again. Developers need to pick one
configuration to use based on their test scripts.
=> [EngSys] add VS Code launch.json configurations for current file

sdk/core/core-xml/CHANGELOG.md, sdk/core/core-xml/src/xml.ts, sdk/core/core-xml/test/xml.spec.ts
- add a unit-test
- pass `trimValues: false` to fast-xml-parser XMLParser.parse()
- stringifyXML() does not have any issue. Adding a unit test to cover the scenario anyway
Browser version works correctly.
-------
`@azure/core-xml`
https://github.com/Azure/azure-sdk-for-js/issues/32486
=> [core-xml] keep leading and trailing spaces when parsing

sdk/web-pubsub/web-pubsub/test/integration.spec.ts
after ESM migration, this error started appearing
>ws.WebSocket is not a constructor
>TypeError: ws.WebSocket is not a constructor
This PR updates the test to use named import `WebSocket` instead.
=> [web-pubsub] fix live tests

eng/scripts/Language-Settings.ps1
This is the same change that was made in Python, is in my testing code for Java and will be made for Rust.
The targetedFiles list needs to remove anything that's in the ExcludePaths otherwise, it will end up trying to process them if they're in the ChangedFiles or DeletedFiles. The scenario is this, something changes in the root of path being excluded, the code on line 74 would end up adding additional packages for validation for something that should be being excluded.
=> Filter ExcludePaths out of the targetedFiles

eng/pipelines/templates/steps/analyze.yml
as it is not necessary.  The build is green
=> [EngSys] remove Build Libraries step from analyze

sdk/openai/openai/test/public/chatCompletions.spec.ts, sdk/openai/openai/test/public/vision.spec.ts
o3 models currently return 500: Gateway error or 400: Model does not work error. The PR will skip these models until they function properly
Pipeline passing [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4566388&view=results)
=> [OpenAI] Skip o3 models in the tests

sdk/test-utils/test-utils-vitest/config/rush-project.json
as most packages depend on it.
=> [EngSys] add test-utils-vitest to build cache

common/config/rush/pnpm-lock.yaml, sdk/identity/identity-broker/CHANGELOG.md, sdk/identity/identity-broker/README.md, sdk/identity/identity-broker/package.json, sdk/identity/identity-cache-persistence/CHANGELOG.md, sdk/identity/identity-cache-persistence/package.json, sdk/identity/identity/CHANGELOG.md
@azure/identity-broker @azure/identity-cache-persistence
- Updated broken docs link for API for identity-broker package
- Updated msal-node from v2 to v 3.2.2, msal-node-extension and identity dependency versions in identity plugin packages
=> [Identity-broker] [Identity-cache-persistence] update versions and doc links

sdk/healthdataaiservices/azure-health-deidentification/test/public/realtimeOperationsTest.spec.ts
sdk/healthdataaiservices/azure-health-deidentification
Increased test timeouts from 10 to 20 seconds to address the DeID test failures.
Random timeouts caused by slow response time during tests. Increased times solved the issues.
Increased resource availability. Chose to increase timeout time as tests are low priority versus other tasks
None, time increase only
=> Increased test timeout values from 10 to 20 seconds

eng/scripts/Language-Settings.ps1
Similar changes are being made to Java, Net and Python. 
When splitting on the directory separator for a file in the repo root, $pathComponents.Length -eq 1.
=> Handle PR changes in the root of the repository

sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts
The helper `prepareRequestOptions()` is used once internally in imdsMsi.ts. It is only used to create a request to invoke a response from IMDS endpoint. This PR simplifies the code to remove the `{ skipMetadataHeader: true, skipQuery: true, }` options argument and creates the request directly.
`@azure/identity`
=> [identity] simplify code to check IMDS availability

common/config/rush/pnpm-lock.yaml, sdk/servicebus/service-bus/package.json, sdk/servicebus/service-bus/review/service-bus.api.md, sdk/web-pubsub/web-pubsub-client-protobuf/package.json, sdk/web-pubsub/web-pubsub-client-protobuf/tsconfig.src.json
Typing changes in `long` 5.3.1
https://github.com/dcodeIO/long.js/releases/tag/v5.3.1
leads to trivial changes in Service Bus api.md (due to known api-extractor issue https://github.com/search?q=repo%3Amicrosoft%2Frushstack+api+extractor+_2&type=issues)
This PR bumps the version and updates the api.md
-------
- `@azure/service-bus`
-  `@azure/web-pubsub-client-protobuf`
=> [ServiceBus] bump dependency `long` version to ^5.3.1

common/tools/dev-tool/package.json, common/tools/dev-tool/src/util/testProxyUtils.ts
- #32939
Removes the `env-paths` dependency from the @azure/dev-tool project and only uses the logic we needed to get the cache location.  Removed dependency due to ESM only nature and the little benefit we got from it.
=> [dev-tool] Remove env-paths dependency

sdk/core/core-rest-pipeline/src/fetchHttpClient.ts, sdk/core/core-rest-pipeline/src/nodeHttpClient.ts, sdk/core/core-rest-pipeline/src/xhrHttpClient.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/src/fetchHttpClient.ts, sdk/core/ts-http-runtime/src/nodeHttpClient.ts, sdk/core/ts-http-runtime/src/xhrHttpClient.ts, sdk/test-utils/test-utils/src/xhrHttpClient.ts
for the two AbortErrors thrown in nodeHttpClient to make customer issue
investigation easier.
=> [core-rest-pipeline] use different abort error messages

eng/pipelines/pullrequest.yml, eng/scripts/Language-Settings.ps1
This PR is in preparation for an upcoming change that'll allow us to exclude specific files. Right now, we were always adding a trailing "/" if one wasn't there and this was done to ensure that things didn't overmatch. For example, if you had sdk/foo and sdk/foobar with an exclude of sdk/foo, without the slash, it would overmatch sdk/foo and sdk/foobar. We were adding the trailing the slash to ensure that this didn't happen. Because always have a need to exclude specific files, adding the trailing slash won't allow this case to work.
This is the first change and it's a safe. Adding the trailing slash allows the removal of where we were doing this in Language-Settings.ps1. Note: There's still a place in eng/common Package-Properties.ps1 where this also has to be done before specific file …
=> Add trailing slash exclude paths

common/tools/eslint-plugin-azure-sdk/package.json
Version v9+ of @eslint/js provides its own type definitions, so we do not need
this installed any more.
-------
https://github.com/Azure/azure-sdk-for-js/issues/33171
=> [eslint-plugin] remove deprecated dev dependency @types/eslint__js

common/config/rush/pnpm-lock.yaml, sdk/core/core-xml/package.json, sdk/core/core-xml/src/xml.ts
- @azure/core-xml
- #33172
Updates to latest `fast-xml-parser`, however, has issues with the types as noted in the PR in the `fast-xml-parser` repo https://github.com/NaturalIntelligence/fast-xml-parser/issues/724
=> [core-xml] Update to latest fast-xml-parser

sdk/identity/identity/src/credentials/azureDeveloperCliCredential.ts
- @azure/identity
- #33176
Fixes the error message for AZD to `"The SystemRoot environment variable is not set. This may cause issues when using the Azure Developer CLI credential.",` where previously it omitted the word Developer.
=> [identity] Fix error message for AZD

common/config/rush/pnpm-lock.yaml, sdk/core/core-xml/package.json, sdk/core/core-xml/src/xml.ts
- @azure/core-xml
- #33172
Updates to 5.0.7 which adds CommonJS typings to fix the `fast-xml-parser` issue as noted in the issue here, which has now been closed https://github.com/NaturalIntelligence/fast-xml-parser/issues/724
=> [core-xml] Updating to latest fast-xml-parser

sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/review/core-amqp.api.md, sdk/core/core-amqp/src/errors.ts, sdk/core/core-amqp/test/errors.spec.ts
@azure/core-amqp
https://github.com/Azure/azure-sdk-for-js/issues/33205
Some network errors are not being retried.
It makes sense to retry network errors.
Yes
N/A
=> [core-amqp] Mark more network errors as retryable

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/metricUtil.spec.ts
We shouldn't apply the cloud tags to our statsbeat telemetry as it isn't needed.
Yes
=> [Monitor OpenTelemetry Exporter] Don't Apply Cloud Tags to Statsbeat Telemetry

sdk/playwrighttesting/microsoft-playwright-testing/package.json, sdk/playwrighttesting/microsoft-playwright-testing/test/snippets.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/clInfoProvider.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/packageManager.spec.ts, sdk/playwrighttesting/microsoft-playwright-testing/test/utils/reporterUtils.spec.ts
- @azure/microsoft-playwright-testing
Updates all projects under `playwrighttesting` to use snippets extraction.
=> [playwrighttesting] Migrate playwrighttesting projects to use snippet extraction

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/utils/common.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
The original env var being used will only detect AKS environments when auto-attach occurs. The new env var being checked will add support for when manual attach is used.
Yes
=> [Monitor OpenTelemetry] Update AKS Detection

common/tools/dev-tool/jsconfig.json, common/tools/dev-tool/register.js
`dev-tool`
One issue is VS Code using up a ton of memory and the TS language service crashing when viewing a `.js` file. This was fixed by adding a `jsconfig.json` file. I figured this out from this comment: https://github.com/microsoft/vscode/issues/235547#issuecomment-2547765610
The other issue is I wanted to be able to run dev-tool from outside of a project folder when using admin commands (like listing all projects, checking migration progress, etc) but `register.js` always tries to load a local `package.json` and throws if you are in a folder without one so I put a simple check to see if the file exists.
=> [dev-tool] Work around two minor issues

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts, sdk/monitor/monitor-opentelemetry/CHANGELOG.md
Attach type should be reported on all statsbeat records.
Yes
=> [Monitor OpenTelemetry Exporter] Fix Reporting the Attach Type on Statsbeat Records

sdk/monitor/monitor-opentelemetry-exporter/src/utils/metricUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/metricUtil.spec.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
From #33229 when removing the cloud attributes, the sdkVersion is also removed unintentionally. This PR fixes that mistake and adds a test case to ensure this is not possible in the future.
Yes
=> [Monitor OpenTelemetry Exporter] Removing Cloud Attributes Should Not Also Remove sdkVersion

sdk/core/core-client/src/deserializationPolicy.ts, sdk/core/core-client/test/deserializationPolicy.spec.ts
Currently, when we receive an error response and there is no default body mapper, we immediately throw a
RestError without further inspecting the response body. It's ideal for operation specifications to define a
default mapper for unexpected responses. However, some services did not implement this leading to issues like
https://github.com/Azure/azure-sdk-for-js/issues/33035 where the error message contains a JSON string of the
error object, and the error code is undefined.
This PR modifies the behavior to look into parsedBody if it has an 'error' property that contains both
'code' and 'message' properties, improving the developer experience in this scenario.
=> [core-client] Check response body for error details even without default body mapper

sdk/identity/identity/README.md
Remove env vars that represent a deprecated ROPC flow. We want this README to represent best practices.
=> Remove username and password env vars from README

sdk/servicebus/service-bus/src/core/managementClient.ts
We used to import from "buffer" and rely on the `buffer` NPM package for browser polyfill. Importing from
"node:buffer" broke the scenario.  This PR reverts back to import from "buffer".
=> [ServiceBus] fix management client for browser

sdk/appconfiguration/app-configuration/CHANGELOG.md, sdk/appconfiguration/app-configuration/README.md, sdk/appconfiguration/app-configuration/package.json, sdk/appconfiguration/app-configuration/review/app-configuration.api.md, sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts, sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts, sdk/appconfiguration/app-configuration/src/internal/constants.ts, sdk/appconfiguration/app-configuration/src/internal/helpers.ts, sdk/appconfiguration/app-configuration/src/models.ts, sdk/appconfiguration/app-configuration/swagger/swagger.md, sdk/appconfiguration/app-configuration/test/internal/helpers.spec.ts, sdk/appconfiguration/app-configuration/test/public/index.spec.ts, sdk/appconfiguration/app-configuration/test/snippets.spec.ts
This PR adds support for specifying the Microsoft Entra audience to use when forming authorization scopes in token authentication. Add `audience` property to `AppConfigurationClientOptions` with `KnownAppConfigAudience` to specify the token audience. The SDK will default to public cloud when no audience is supplied.
=> [App Config] Support For AAD Token Audience

sdk/core/core-rest-pipeline/src/util/inspect.common.ts, sdk/core/ts-http-runtime/src/util/inspect.common.ts
This addresses build warnings seen in TypeScript 5.8 upgrade
>Warning: dist/browser/restError.d.ts:31:5 - (TS2464) A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
We could use some string or number but `Symbol` is more in line with the NodeJS version's `unique symbol`.
=> [core] address warning with typescript 5.8

sdk/servicebus/service-bus/vitest.browser.config.ts
After vitest.browser.config.ts was refactored to merge with shared browser config, some tests started failing likely due to the fakeTimers settings.  This PR restores the behavior prior to the refactoring.
=> [ServiceBus][Test] fix browser test

sdk/appconfiguration/app-configuration/test/public/index.readonlytests.spec.ts, sdk/appconfiguration/app-configuration/test/public/index.spec.ts, sdk/appconfiguration/app-configuration/test/public/snapshot.spec.ts
- "accepts operation options" tests are testing options passed into core than specific App Configuration features. Some of these tests have been flaky in live test pipeline only in windows environment. Skipping for now and we have created an issue to track this.
=> [App Config] Skip flaky tests in live mode

eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-sdk-tests-isolated.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, sdk/identity/identity/tests.yml, sdk/identity/test-resources-post.ps1, sdk/keyvault/keyvault-admin/tests.yml, sdk/keyvault/keyvault-keys/tests.yml, sdk/keyvault/test-resources-post.ps1
`@azure/identity`
`@azure/keyvault-admin`
`@azure/keyvault-keys`
Builds on previous work in https://github.com/Azure/azure-sdk-for-js/pull/31335
This PR adds support for `PersistOidcToken` parameter passing, allowing one to 
refresh their credential using `Connect-AzAccount` or `az login`
=> [engSys] Use common OIDC token env vars for live tests

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml
as 5.8 introduces some changes that cause generated .d.ts files incompatible
with previous versions of TypeScript compiler:
https://github.com/microsoft/TypeScript/issues/61360#issuecomment-2703357823
This PR temporarily pinns its version to ~5.7.3 until we can upgrade to v5.8
tracking upgrading to 5.8: https://github.com/Azure/azure-sdk-for-js/issues/33324
We could upgrade to 5.8, but the incompatible output would cause a lot of warnings from api-extractor because it still bundles 5.7.3.
=> [EngSys] pin dev dependency `typescript` version to ~5.7.3

sdk/core/core-amqp/eslint.config.mjs, sdk/core/core-client-rest/eslint.config.mjs, sdk/core/core-rest-pipeline/eslint.config.mjs, sdk/core/core-rest-pipeline/test/agentPolicy.spec.ts, sdk/core/core-sse/eslint.config.mjs
Our core code use a style of mixing browser code with NodeJS code in some files.
The `n/no-unsupported-features/node-builtins` complains about experimental Web
features that is not supported yet in NodeJS v18 even though they are only
intended to be used in browsers. for example,
>   87:28  warning  The 'fetch' is still an experimental feature and is not supported until Node.js 21.0.0. The configured version range is '>=18.0.0'     n/no-unsupported-features/node-builtins
This PR suppresses those warnings for core packages.
=> [eslint] turn off `n/no-unsupported-features/node-builtins` rule for core

eng/pipelines/templates/steps/analyze.yml
To avoid an issue with python and readme verification, set the python version first
=> Set python version before calling verify-readmes

sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/review/core-client.api.md, sdk/core/core-client-rest/src/common.ts, sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md, sdk/core/core-rest-pipeline/src/index.ts, sdk/core/core-rest-pipeline/src/interfaces.ts, sdk/core/core-rest-pipeline/src/nodeHttpClient.ts, sdk/core/core-sse/CHANGELOG.md, sdk/core/core-sse/review/core-sse.api.md, sdk/core/core-sse/src/index.ts, sdk/core/core-sse/src/models.ts, sdk/core/core-sse/src/sse.ts, sdk/core/core-sse/src/utils.ts, sdk/core/core-sse/test/public/node/connection.spec.ts, sdk/core/core-sse/test/public/node/util.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/client/common.ts, sdk/core/ts-http-runtime/src/index.ts, sdk/core/ts-http-runtime/src/interfaces.ts, sdk/core/ts-http-runtime/src/nodeHttpClient.ts
This reverts commit 4967916d8fbadad8a209a20783142573c053ddf6.
Storage still uses test-recorder v3 which pulls in incompatible core-rest-pipeline version from npmjs and
leads to test build failure. This RP reverts the change for now to unblock storage March release and PR 
validation pipelines
=> Revert "[core] Support NodeJS stream cancellation (#33341)"

eng/tools/rush-runner/src/helpers.js, sdk/test-utils/recorder/CHANGELOG.md, sdk/test-utils/recorder/src/recorder.ts
Browser tests in all the packages
#32851 
Ignore `Origin` header for browsers in Playback mode
=> [Recorder] Exclude Origin header

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, sdk/storage/storage-blob/README.md, sdk/storage/storage-blob/src/Clients.ts, sdk/storage/storage-file-datalake/README.md, sdk/storage/storage-file-datalake/samples-dev/dataLakeServiceClient.ts, sdk/storage/storage-file-datalake/samples/v12/javascript/dataLakeServiceClient.js, sdk/storage/storage-file-datalake/samples/v12/typescript/src/dataLakeServiceClient.ts, sdk/storage/storage-file-datalake/src/clients.ts, sdk/storage/storage-file-share/README.md, sdk/storage/storage-file-share/samples-dev/shareServiceClient.ts, sdk/storage/storage-file-share/samples/v12/javascript/shareServiceClient.js, sdk/storage/storage-file-share/samples/v12/typescript/src/shareServiceClient.ts, sdk/storage/storage-file-share/src/Clients.ts, sdk/storage/storage-file-share/test/utils/index.ts, sdk/translation/ai-translation-document-rest/test/public/node/containerHelper.ts
Pin vitest to 3.0.7 because 3.0.8 broke installation and we need
the following fix to be published
https://github.com/vitest-dev/vitest/pull/7628
- rush update --full
=> [EngSys] pin vitest* dev dependency versions

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml
Later versions bundles typescript 5.8.2 which cause incompatibility issue with
current typescript 5.7.3 that we are using.
It will be unpinned as part of upgrade to typescript v5.8.
=> [EngSys] pin dev dependency @microsoft/api-extractor version to 7.51.1

sdk/storage/storage-file-share/review/storage-file-share.api.md, sdk/storage/storage-file-share/src/Clients.ts, sdk/storage/storage-file-share/src/FileDownloadResponse.ts, sdk/storage/storage-file-share/src/generatedModels.ts, sdk/storage/storage-file-share/src/models.ts, sdk/storage/storage-file-share/test/directoryclient.spec.ts, sdk/storage/storage-file-share/test/fileclient.spec.ts
=> Update file share API according to review comments

sdk/cosmosdb/cosmos/review/cosmos.api.md, sdk/cosmosdb/cosmos/src/queryIterator.ts
@azure/cosmos
This PR reverts marking the constructor of QueryIterator as internal.
=> Revert queryIterator constructor marked as internal

sdk/servicebus/test-resources.bicep
`supportsSafeSecretStandard` is a parameter that tells whether the subscription the resource is being created in disallows API-key-like authentication. This PR updates the test-resources.json file to use this parameter to disable such authentication methods if they're disallowed by the target subscription. This unblocks creating resources in the playground subscription.
Live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4659763&view=results
=> [service bus] Disable local auth when not in TME

sdk/core/core-rest-pipeline/review/core-rest-pipeline.api.md, sdk/core/core-rest-pipeline/src/restError.ts, sdk/core/ts-http-runtime/review/azure-core-comparison.diff, sdk/core/ts-http-runtime/review/ts-http-runtime.api.md, sdk/core/ts-http-runtime/src/restError.ts
TypeScript version v5.8 and later generate a type declaration for `RestError` that is incompatible with
previous versions of TypeScript, which means our d.ts generated by TypeScript v5.8+ will cause compilation
error when being consumed by earlier versions of TypeScript.
The `[util.custom]()` member of `RestError` is used to override the behavior of `util.inspec` on `RestError`
instances and not meant to be used directly. This PR removes the method from the class members and instead
assign to the `util.custom` property in the constructor.
=> [core-rest-pipeline] remove `[custom]` from RestError members

common/tools/dev-tool/src/commands/admin/migrate-package.ts
Part of SDK automation in specs repo PR check is to generate JS SDK packages for
spec changes and build them. The dev-tool `migrate-package` is executed on the
generated package before building it. There are case where the generated package
doesn't include a `test` directory, which causes "npm run format" to fail.
This PR checks whether the `test` directory exists or is empty. If either is
true test file patterns are removed from the `"format"` NPM script of the
package.
=> [dev-tool] fix `migrate-package` to not format empty test directory

documentation/Quickstart-on-how-to-write-tests.md, sdk/purview/purview-administration-rest/README.md
This PR replaces references to purview-catalog with ones to purview-scanning
because the former has been deprecated and removed.
=> [doc] fix broken link to purview catalog

common/tools/eslint-plugin-azure-sdk/package.json, sdk/databasewatcher/arm-databasewatcher/package.json, sdk/deviceregistry/arm-deviceregistry/package.json, sdk/impactreporting/arm-impactreporting/package.json
- remove api-extractor from individual packages
- bump vitest to ^3.0.9, same as rest of the repository
=> [EngSys] clean up some dev dependencies

sdk/core/core-rest-pipeline/test/pipeline.spec.ts
To guard against breaking changes similar to what was introduced in https://github.com/Azure/azure-sdk-for-js/pull/33341
=> [core-rest-pipeline] add a test for pipeline response shape

common/tools/dev-tool/src/commands/admin/migrate-package.ts
Migration tool is a step in JS Automation and it is before build step, So Migration tool will remove subpath exports in tshy configs after the code generation
So create a PR to fix this
=> [Migration tool] Do not remove subpath exports for modular package.json generation

.github/copilot-instructions.md, documentation/linting.md
before running other rush commands.  This helps copilot in a fresh workspace.
=> [Docs] tell copilot to run `rush update`

eng/scripts/Language-Settings.ps1
There's an [eng/common change](https://github.com/Azure/azure-sdk-tools/pull/10096) that's going to be pushed out very soon that will need this function.
eng/common/scripts/Save-Package-Properties.ps1 had the following code which was only for JS. 
```
if ($pkg.ArtifactName)
{
$configFilePrefix = $pkg.ArtifactName
}
```
The $configFilePrefix is actually the name of the packageInfo file. The problem is the above code was always causing the PackageInfo file names to be set to the ArtifactName if it was set, preventing me from making necessary changes. The solution was to define Get-PackageInfoNameOverride in Language-Settings.ps1 and have it return what the PackageInfo name should be set to. For JS this is the ArtifactName. I've already tested these changes locally generating all PackageInfo …
=> Add Get-PackageInfoNameOverride function to Language-Settings

sdk/core/core-lro/CHANGELOG.md, sdk/core/core-lro/review/core-lro.api.md, sdk/core/core-lro/src/http/models.ts, sdk/core/core-lro/src/http/operation.ts, sdk/core/core-lro/src/http/poller.ts, sdk/core/core-lro/test/public/lro.spec.ts, sdk/core/core-lro/test/utils/router.ts
@azure/keyvault-admin 
Contributes to #32142
Adds `skipFinalGet` as an optimization and proper support for LROs where fetching the final resource is unnecessary for various reasons. 
Naming mostly! I think `skipFinalGet` is the best I could land on, but maybe `skipFetchResource` or something like that?
Yes
Entire feature was written by GH Copilot in Agent mode with my help!
=> [core-lro] Add support for `skipFinalGet`

common/tools/dev-tool/vitest.config.mts, common/tools/eslint-plugin-azure-sdk/vitest.config.ts, eng/tools/rush-runner/vitest.config.mjs, sdk/apimanagement/api-management-custom-widgets-tools/vitest.browser.config.ts, sdk/eventhub/event-hubs/vitest.browser.config.ts, sdk/test-utils/recorder/vitest.browser.config.ts, sdk/test-utils/test-utils-vitest/vitest.browser.config.ts, vitest.browser.base.config.ts, vitest.browser.shared.config.ts, vitest.shared.config.ts
- all packages using vitest
The vitest `verbose` reporter outputs to console a JSON-serialized version of any error thrown during a test run. In the case a `RestError` is thrown, this results in the request and response objects being output, including any secrets that may be present. This may lead to secrets being leaked in CI logs. [I thought](https://github.com/Azure/azure-sdk-for-js/pull/29737#issuecomment-2179047796) that vitest turned off this behavior by default, but it turns out that they left it on for the verbose reporter specifically for whatever reason, so [when we changed over](https://github.com/Azure/azure-sdk-for-js/pull/30581) to it from the basic reporter back in July we inadvertently turned it back on.
So that we can still get the benefits of the verbose reporter while …
=> [test] use custom vitest reporter

eng/pipelines/templates/jobs/ci.yml
@jeremymeng reached out about this pr that looked [wonky.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4693084&view=logs&j=2a01393f-ea32-556d-315a-d0f84478d58d&t=2dcd174d-08bd-5b06-32f6-08c9530e78f7)
The issue is that we need the triggeringPath files to exist when we are checking whether or not to trigger a package based on them.
The lack of `common/config` presence was causing `azure-core` packages to NOT resolve when generating the targeted packages, so we were falling back to `template` packages. Rather than adding `common/config` to the sparse checkout, I'm just enhancing it to pull all the files. We lose 10 to 15 seconds, it's nbd.
=> Adjustment to `sparse-checkout` settings for Create-PRJobMatrix

sdk/communication/communication-common/src/entraTokenCredential.ts, sdk/communication/communication-common/test/public/node/entraCommunicationTokenCredential.spec.ts
Use Teams Phone Extensibility token exchange API with route according to REST API review. Use correct API version
Replacing historical route and API version used for calling ACS Auth token exchange API by values approved in REST API review
No, just updated existing ones to verify changed values
=> In AzureCommunicationTokenCredential, use correct route and API version when calling ACS Auth token exchange API

sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts
N/A - followup for #32819
The move to ESM and Vitest uncovered some test-pollution that needs to be
addressed. To get the PR merged, I temporarily skipped those tests. 
This PR re-enables those tests to the best we can do given the constraints in
place and OTel's usage of globals.
A few changes were made:
1. OTel require hook will fire only once so instead of passing the config to a
new instrumentation, we can spy on the initialized instrumentation and update
its config via a spy. That allows it to always get a fresh config.
2. For ensuring disable works, we don't need to check on any spies and it's
sufficient to ensure that no http instrumentation was created.
IMO this entire test suite can be simplified to only test the business logic of
the handler. When we …
=> [monitor] Re-enable traceHandler tests

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml
as the latest version 3.4.1 causes playback tests to fail. This PR pins its version to 3.3.0 to unblock full rush update.
=> [EngSys] Pin @azure/msal-node version to 3.3.0 temporarily

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
We should not filter out a value used to tell ingestion that a standard metric was processed.
=> [Monitor OpenTelemetry Exporter] Do not filter out standard metrics property

sdk/core/core-lro/CHANGELOG.md, sdk/core/core-lro/src/http/operation.ts, sdk/core/core-lro/test/public/lro.spec.ts
N/A
Polling responses may contain a status field, this PR logs it before it transforms it to the set of known statuses. It also relaxes the termination checking to be able to handle statuses that are not exactly "succeeded" or "failed" but still contain some variation of these words. This enables polling for many non-conforming LRO APIs without having to create dedicated custom pollers for them.
- Add an option that specifies the set of terminal statuses to check for, this set has to be specified either by the user or by code gen. This doesn't work in cases where this set is not part of the spec or the user is not familiar with it
- Do nothing and let the user/code gen build custom pollers but that feels a lot more expensive than it should be
Yes
N/A
=> [core-lro] Relaxed status transformation

sdk/openai/openai/CHANGELOG.md, sdk/openai/openai/src/types/index.ts, sdk/openai/openai/test/public/chatCompletions.spec.ts, sdk/openai/openai/test/utils/utils.ts
openai
This PR adds `user_security_context` as an optional Azure parameter as `AzureUserSecurityContext` in the `openai` package for `ChatCompletionCreateParams` streaming and non-streaming interfaces.
yes
=> Add user_security_context optional Azure param in openai

eng/pipelines/templates/steps/build.yml, eng/pipelines/weekly_automation.yml, eng/scripts/check-external-dependency.ps1, eng/tools/ci-runner/src/testProxyRestore.js
left to do:
- deprecated depedency report. tracked by https://github.com/Azure/azure-sdk-for-js/issues/33596
- available major version upgrades report. tracked by https://github.com/Azure/azure-sdk-for-js/issues/33597
=> Update weekly automation to use `pnpm`

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/utils/connectionStringParser.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts, sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/utils/connectionStringParser.ts
We should hide iKey in debug logs.
=> [Monitor OpenTelemetry][Monitor OpenTelemetry Exporter] Hide iKey in Debug Logs

sdk/appconfiguration/app-configuration/CHANGELOG.md, sdk/appconfiguration/app-configuration/README.md
- @azure/appconfiguration
- #33880
Updates the snippets generation and adds an ignore to the CHANGELOG.
=> [appconfiguration] Fix snippets generation

common/tools/dev-tool/ci.yml, common/tools/dev-tool/package.json
Currently analyze pipeline won't do anything for dev-tool so we rely on the
"build" NPM script to lint and check format. However, that adds unnecessary work
every time dev-tool is built.
This PR adds a special CI pipeline for dev-tool so that any issue caught in pull requests. Now we can remove linting and checking format from "build" NPM script.
We already have prior art of special pipeline for eslint-plugin-azure-sdk.
=> [EngSys] add a special CI pipeline for dev-tool

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/README.md, sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/snippets.spec.ts
- @azure/opentelemetry-instrumentation-azure-sdk
- https://github.com/Azure/azure-sdk-for-js/issues/33880
Fixes the snippets extraction by using explicit imports instead of default imports.
=> [instrumentation] Fix snippets imports for named imports

sdk/monitor/monitor-query/src/logsQueryClient.ts, sdk/monitor/monitor-query/test/internal/unit/logsQueryClient.unittest.spec.ts, sdk/monitor/monitor-query/vitest.browser.int.config.ts, sdk/monitor/monitor-query/vitest.int.config.ts
We were overriding the `requestOptions` property in the option bag instead of merging. This PR ensures that the original values are carried over.
=> [monitor-query] fix an issue where `customHeaders` option value is lost

sdk/monitor/monitor-query/src/models/timeInterval.ts
The `duration` format is already explained in individual types of the union.
However, the overall doc for the type doesn't include it. This PR adds the info to
the overall ref doc as well so that when ref docs of individual types are not
showing we can still understand the format of the duration.
=> [monitor-query][doc] improve `QueryTimeInterval` reference doc

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/package.json, sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
- `self.location` is not defined in all environments so it's necessary to add a type guard to ensure we can access the property.
- `exports` have order significance and the most specific ones should be listed first. Refer to [Node conditional exports](https://nodejs.org/api/packages.html#conditional-exports) guide.
=> [Identity] Update workered exports order

sdk/schemaregistry/README.md
The old branch is probably deleted.  We should link to main branch now anyway.
=> [SchemaRegistry][doc] update link to schema-registry-json

sdk/schemaregistry/schema-registry-avro/package.json
We updated "build:test" to just echo, but didn't update the
"integration-test:browser" script to really build the test. This PR adds the
command to build browser tests in "integration-test:browser" script.
=> [schema-registry-avro][test] fix browser integration tests

sdk/eventgrid/test-resources.bicep
It was missed when we migrated to .bicep for deployment
=> [eventgrid-namespace][test] add "https://" for namespace endpoint

sdk/identity/identity-broker/package.json, sdk/monitor/monitor-opentelemetry/package.json
as the dev-tool command has been removed.
=> [EngSys] update outdated test:node-ts-input usage

sdk/core/core-util/package.json, sdk/core/logger/package.json
for the new features.  This fixes the `js - core` nightly build.
Our nightly automation updates packages to use dev/nightly versions only when
the min satisfying version numbers are exact match. This ensures dependency
semantic version range is accurate.
=> [core] bump dependency ts-http-runtime version

sdk/core/core-rest-pipeline/package.json
Bump minimum version of ts-http-runtime to latest to prevent nightly failures (forgot to do it before merging #33948). See https://github.com/Azure/azure-sdk-for-js/pull/33994.
=> [core] core-rest-pipeline: fix ts-http-runtime dependency version

turbo.json
using "^format" means running "format" for all dependencies first, which is not what we want for tasks that can be run independently.  This PR removes `dependsOn` for tasks that doesn't need their dependencies to run that task first.
=> Fix turbo.json depends

eng/pipelines/templates/jobs/live.tests.yml
I'm not sure what the difference is here, or why we want the main tests to run on `succeededOrFailed()`. At the very least the duplicate display names was confusing me, so figured I'd throw up a quick fix.
=>  Update live test job display names

sdk/openai/openai/package.json, sdk/openai/openai/test/public/assistants.spec.ts, sdk/openai/openai/test/public/browser/webSocketRealtime.spec.ts, sdk/openai/openai/test/public/images.spec.ts, sdk/openai/openai/test/public/tts.spec.ts, sdk/openai/openai/test/public/vision.spec.ts, sdk/openai/openai/test/utils/asserts.ts, sdk/openai/openai/test/utils/models.ts
This PR refactors the vision.spec.ts test suite to use the new testWithDeployments function for improved maintainability and consistency with other test files.
- Migrates vision.spec.ts to use testWithDeployments
- Aligns with recent refactors in other test suites
**Support for gpt-image-1**
- new deployments have gpt-image-1 for image generaion
- newer version of openai dependency was needed. multiple bug fixes due to the change
Please review for correctness and consistency with the new test patterns.
=> Convert vision.spec to new testWithDeployments function and more

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/environmentCredential.ts
If UsernamePasswordCredential environment variables are detected in EnvironmentCredential and DefaultAzureCredential, we now ensure that a warning noting its deprecation is logged.
Without this, by default, the user won't see the warning emitted in the UsernamePasswordCredential class constructor if UsernamePasswordCredential wasn't directly instantiated by the user.
=> [identity] deprecation warning of user name password usage in env cred

eng/containers/ci.yml
Copying over the container pipeline from net/java so that we can publish the new turborepo remote cache image (https://github.com/Azure/azure-sdk-for-js/tree/feat/pnpm-prep/common/tools/turborepo-remote-cache)
=> Initialize containers publish pipeline

sdk/identity/identity/src/credentials/clientCertificateCredential.ts, sdk/identity/identity/src/credentials/onBehalfOfCredential.ts, sdk/identity/identity/src/msal/types.ts
- Keep property `thumbprint` to ensure backwards compatibility with older version of ADFS. Mark the property as deprecated since it's not recommended and `thumbprintSha256` is preferred
=> [Identity] Add Thumbprint Property Back

sdk/identity/identity/test/integration/node/azureKubernetesTest.spec.ts
- Getting credential script is run in postscript command, so we no longer needs to run it in the test
MI live tests pass [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4812380&view=results)
=> [Identity] Update Kubernetes test

sdk/core/core-client/package.json, sdk/core/core-http-compat/package.json
for core-client and core-http-compat.
=> [core] bump dependency @azure/core-rest-pipeline version to ^1.20.0

eng/pipelines/templates/jobs/live.tests.yml
to be more meaningful. The difference is that one is usual testing, and the other is min/max testing (DependencyVersion not equal to '')
=> [EngSys] Update integration test step title in live.tests.yml

sdk/tables/data-tables/CHANGELOG.md, sdk/tables/data-tables/src/TableClient.ts, sdk/tables/data-tables/test/internal/errorHandling.spec.ts
Although tables allow empty strings as partition/row key values, null value is not permitted. Our typing is correct, and TypeScript compiler will report errors if `null` or `undefined` is passed to either one of them. However, developers who don't use type checking will get a non-helpful error at runtime in this case:
>TypeError: Cannot read properties of undefined (reading 'replace')
at escapeQuotes (.../node_modules/@azure/data-tables/dist/index.js:4439:18)
at TableClient.upsertEntity
This PR adds validation for entity `partitionKey` and `rowKey` so a better error is thrown when undefined or null is passed as value for them.
https://github.com/Azure/azure-sdk-for-js/issues/34129
=> [data-tables] add partitionKey and rowKey validation

sdk/core/ts-http-runtime/src/util/concat.ts, sdk/core/ts-http-runtime/test/multipartPolicy.spec.ts
- Fixes bug introduced in #33948 (unreleased)
Came across this when investigating with @HarshaNalluru yesterday evening. I introduced this when taking the `createFile` shim and friends out of the Unbranded package. The logic I 'fixed' results in infinite recursion if a `Blob` is passed into `toStream` in Node. Apparently we didn't have a test for passing a `Blob` body into `multipartPolicy` so this wasn't caught. I added a test here to fix the gap in coverage.
Ultimately, it seems unlikely that someone would actually pass a Blob as input here in Node, so the impact of this would probably have been limited, but it's still a bug and it's an easy fix.
=> [core] fix stack overflow when passing a Blob for multipart part body in Node

eng/pipelines/templates/stages/archetype-js-release.yml
See evidence:
Manually queued `js - ai`: 
Nightly queued `js - ai`:
I believe the issue is that the condition based on a build time variable is no longer working -- somehow? I honestly don't understand it but AFAICT nothing has changed except for the variable is no longer honored in a compile time fashion.
By moving this compile-time condition to `runtime`, I believe that we can get around this problem. Here [is evidence](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4824878&view=logs&j=43330500-c246-546c-96b0-add58568f780)
=> Manual Queues of `Integration` build are not publishing

documentation/Bundling.md
- `@azure/storage-blob` (documentation examples in the Bundling samples)
- None
There was a spelling mistake in the Bundling guide: the term “brower-compatible” was used instead of “browser-compatible” in both the Webpack and Rollup sections. This PR corrects those typos so that the documentation reads correctly.
1. **Leave the typo** – not acceptable because it impacts clarity.  
2. **Correct the typo in the documentation only** – simplest and most direct fix.  
3. **Introduce an alias or note** – overkill for a simple spelling correction.  
This PR implements option 2, as it directly addresses the typo with minimal risk.
_No test cases added._  
This is purely a documentation change; no code behavior is affected.
- N/A
N/A
=> docs: fix typo in Bundling.md - brower → browser

documentation/Bundling.md, samples/Bundling/parcel/js/package.json, samples/Bundling/parcel/ts/package.json
to opt in package exports support. Otherwise Parcel won't be able to resolve imports from subpaths.
=> [docs] update bundling instruction for Parcel bundler

eng/tools/dependency-testing/templates/vitest.dependency-test.config.ts
The current merged config for dependency testing tries to run all tests under `test/public` folder as shown [here](https://github.com/Azure/azure-sdk-for-js/blob/main/eng/tools/dependency-testing/templates/vitest.dependency-test.config.ts#L38). This is because dependency testing uses `test/public` test folder [here](https://github.com/Azure/azure-sdk-for-js/blame/main/eng/pipelines/templates/jobs/live.tests.yml#L131), so the default vitest config exclude properties for the browser `test/**/browser/*.spec.ts` will miss the browser folder.
The current logic for min/max config is redundant after our centralizing Vitest config effort. All package configs are extended from the shared config, so we no longer have to use the 3-way merging logic for dependency testing. The PR updates the logic to …
=> [Eng Sys] Update Dependency Testing Config for Browser

eng/common/TestResources/New-TestResources.ps1.md, eng/common/TestResources/README.md
This got out of sync due to https://github.com/Azure/azure-sdk-for-js/commit/57056dcef4d646fdca6f4af7bd5b2539c3cb57a2, for which we bypassed checks to prevent a build storm. As a result the eng/common change prevention didn't run.
=> Force js test resource md files into parity with tools repo

sdk/cosmosdb/cosmos/review/cosmos.api.md, sdk/cosmosdb/cosmos/src/ClientContext.ts, sdk/cosmosdb/cosmos/src/common/constants.ts, sdk/cosmosdb/cosmos/src/queryExecutionContext/hybridQueryExecutionContext.ts, sdk/cosmosdb/cosmos/src/request/ErrorResponse.ts, sdk/cosmosdb/cosmos/src/request/FeedOptions.ts, sdk/cosmosdb/cosmos/src/request/hybridSearchQueryResult.ts, sdk/cosmosdb/cosmos/src/utils/supportedQueryFeaturesBuilder.ts, sdk/cosmosdb/cosmos/test/internal/unit/hybridExecutionContext.spec.ts, sdk/cosmosdb/cosmos/test/internal/unit/utils/supportedQueryFeaturesBuilder.spec.ts, sdk/cosmosdb/cosmos/test/public/integration/fullTextSearch.spec.ts
@azure/cosmos
#34221
1. ***Add support for weighted RRF in hybrid search.***
We allow weights to be negative but the negative sign is used to signal that we should sort scores in ascending order for the corresponding component. The final WRRF score is then computed using the absolute value of the weight.
In this approach, the sign of the weight indicates the interpretation of the ranking itself rather than directly affecting the calculated score:
WRRF(d) = ∑ |w_i| × 1/(k + r_i'(d))
2. ***Adds support for the optimized query plan***
Adds a QueryFeature that returns optimized query plan, effectively removing the need for rewriting orderByExpressions in the SDK. 
A flag `disableHybridSearchQueryPlanOptimization` is added to disable returning optimized query plan. This is done to ensure the …
=> Add support for Weighted RRF +  Hybrid Search Query plan optimization

sdk/cosmosdb/cosmos/src/client/ChangeFeed/ChangeFeedForEpkRange.ts, sdk/cosmosdb/cosmos/test/internal/unit/changeFeed/ChangeFeedForEpkRange.spec.ts
@azure/cosmos
This PR addresses the bug of changefeed for entire container returning wrong results after partition merge.
=> [@azure/cosmos] fix: changefeed merge

sdk/cosmosdb/cosmos/src/utils/hashing/encoding/number.ts, sdk/cosmosdb/cosmos/src/utils/hashing/encoding/string.ts, sdk/cosmosdb/cosmos/src/utils/hashing/murmurHash.ts, sdk/cosmosdb/cosmos/src/utils/hashing/v1.ts, sdk/cosmosdb/cosmos/src/utils/hashing/v2.ts, sdk/cosmosdb/cosmos/src/utils/uint8.ts, sdk/cosmosdb/cosmos/test/internal/unit/hashing/v1.spec.ts, sdk/cosmosdb/cosmos/test/internal/unit/hashing/v2.spec.ts, sdk/cosmosdb/cosmos/test/internal/unit/utils/uint8.spec.ts
@azure/cosmos
This PR uses Uint8Array instead of Buffer for partition-key hashing to support bulk operations in browsers env.
=> convert to uint8array to add support for browser

sdk/monitor/monitor-opentelemetry/src/utils/common.ts
The latest @types/node changes add `string[]` to the `RequestOptions.headers` type:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72617
https://github.com/nodejs/node/pull/58049
This PR adds a check and narrow the type to `http.OutgoingHttpHeaders` before accessing user-agent
property. We don't ever set the user agent header using the `string[]` form so this should be fine.
=> [monitor-opentelemetry] fix type checking build error

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/credentials/defaultAzureCredential.ts, sdk/identity/identity/test/internal/node/defaultAzureCredential.spec.ts
=> [Identity] update the DAC chain based on env var AZURE_TOKEN_CREDENTIALS

eng/CredScanSuppression.json, sdk/storage/storage-file-datalake/test/node/filesystemclient.spec.ts, sdk/storage/storage-file-datalake/test/utils/fakeTestSecrets.ts
It is not a secret and can be suppressed.
=> [credscan] move storage-file-datalake test acl id into fakeTestSecrets

sdk/ai/ai-inference-rest/CHANGELOG.md, sdk/ai/ai-inference-rest/package.json, sdk/ai/ai-inference-rest/src/modelClient.ts, sdk/ai/ai-projects/CHANGELOG.md, sdk/ai/ai-projects/package.json
@azure/ai-inference-rest 
@azure/ai-projects
https://github.com/Azure/azure-sdk-for-js/pull/34146
Seems like the version update PR was never merged, so this bumps the two
packages in our repo so that the CHANGELOG entries can be added
=> ai version bump

common/tools/dev-tool/src/commands/run/update-snippets.ts, sdk/appconfiguration/app-configuration/CHANGELOG.md, sdk/core/abort-controller/CHANGELOG.md, sdk/digitaltwins/digital-twins-core/CHANGELOG.md, sdk/documentintelligence/ai-document-intelligence-rest/CHANGELOG.md, sdk/documentintelligence/ai-document-intelligence-rest/README.md, sdk/documentintelligence/ai-document-intelligence-rest/test/snippets.spec.ts, sdk/eventhub/event-hubs/CHANGELOG.md, sdk/identity/identity/CHANGELOG.md, sdk/keyvault/keyvault-admin/CHANGELOG.md, sdk/keyvault/keyvault-certificates/CHANGELOG.md, sdk/keyvault/keyvault-keys/CHANGELOG.md, sdk/keyvault/keyvault-secrets/CHANGELOG.md, sdk/openai/openai/CHANGELOG.md, sdk/quantum/quantum-jobs/CHANGELOG.md, sdk/schemaregistry/schema-registry/CHANGELOG.md, sdk/servicebus/service-bus/CHANGELOG.md, sdk/storage/storage-blob/CHANGELOG.md, sdk/storage/storage-common/CHANGELOG.md, sdk/storage/storage-file-share/CHANGELOG.md, sdk/storage/storage-queue/CHANGELOG.md, sdk/tables/data-tables/CHANGELOG.md, sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
It's not a scenario where we would need to keep code blocks in sync with
snippets in snippets.spec.ts. This PR changes to ignore change log files so that
we don't have to add the ignore directive to every CHANGELOG.md.
=> [dev-tool] ignore CHANGELOG.md from update-snippets

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
We should not send network/instrumentation/feature statsbeat when counts are zero.
Yes
=> [Monitor OpenTelemetry Exporter] Do Not Export Zero Value Statsbeat

eng/pipelines/templates/steps/analyze.yml
For the analyze job I don't think we need to set the test package version. Setting it breaks at least the verify snippets step which is looking at changed files on disk.
=> Remove setting test package version

common/tools/dev-tool/src/commands/run/update-snippets.ts
On Windows file paths are using "\" as path separator, which causes the comparison between the path in the import specifier text and the relative file path to fail.
This PR replaces "\" with "/" in the relative file paths before comparing them.
=> [dev-tool] fix path comparison on windows for update-snippets

sdk/communication/communication-common/CHANGELOG.md, sdk/communication/communication-common/README.md, sdk/communication/communication-common/package.json, sdk/communication/communication-common/src/entraTokenCredential.ts, sdk/communication/communication-common/test/public/node/entraCommunicationTokenCredential.spec.ts, sdk/communication/communication-common/test/snippets.spec.ts
ACS Auth TeamsExtension REST API moved to GA.
This PR updates the Communication Common SDK to use the GA version of the TeamsExtension REST API for token exchange and prepares the SDK for major release.
=> Updating Communication Common SDK to version supporting Teams Phone Extensibility GA version

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
Fixed an issue where the first call to collect long interval statsbeat would throw since the reader was not registered. This issue was introduced as a part of #34146.
Yes, one added to ensure we don't regress on this issue.
=> [Monitor OpenTelemetry Exporter] Fix LongIntervalStatsbeat Reader Register

.github/CODEOWNERS, eng/pipelines/docindex.yml, eng/pipelines/templates/variables/image.yml
Example successful docindex run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4900330&view=results
This uses variables in image.yml. When the images are updated in those variables the docindex pipeline will follow from those changes.
=> Update docindex pool and add CODEOWNERS for notifications

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/models/events.ts
Converted the REST identifier model to the SDK identifier model for IncomingCall event, specifically CustomCallingContextInternal & CommunicationIdentifierModel are no longer exposed.
IncomingCall event now uses CustomCallingContext & CommunicationIdentifier respectively.
=> REST<->SDK Model Translation for IncomingCall Event

sdk/ai/ai-agents/test/snippets.spec.ts, sdk/ai/ai-agents/tsconfig.samples.json, sdk/ai/ai-projects/test/snippets.spec.ts, sdk/ai/ai-projects/tsconfig.samples.json
The names should match the package names.
Also change `test/snippets.spec.ts` to import from `"../src/index.js"` so it stay in-sync with source changes. Previously `update-snippets` wasn't working properly on Windows when importing from `"../src/index.js"`. The issue has been fixed in dev-tool.
=> [ai-agents,projects] fix paths mapping in tsconfig.samples.json

sdk/notificationhubs/notification-hubs/assets.json, sdk/notificationhubs/notification-hubs/test/public/utils/recordedClient.ts
After test entry name change, some broken playback test under test\public previously not included in `unit-test:node` are now running in `test:node` and failing.  This PR updates the recorded client to use header sanitizer for the `x-ms-azsdk-telemetry` header and update recordings for missing `ServiceBusNotification-Tags` header.
=> [notificationhubs][test] update recorded client sanitizers

common/tools/dev-tool/src/commands/run/build-package.ts, sdk/appcontainers/arm-appcontainers/src/index.ts
We use rush to build packages. By default rush doesn't log output from each
package. It only shows summary, and errors if there are any. Rush also truncates
output. Combining with the fact that the error stdout output from tshy is quite
long, when a package fails to build, the final output by rush doesn't contain
useful information about actual build errors. So far we rely on `--verbose`
option to `rush`. However, This option leads to overwhelming logs for packages
that don't have errors.
This PR changes the `build-package` command to report tshy output via
`logger.error` when the spawned tshy process exits with non-zero code.
https://github.com/Azure/azure-sdk-tools/issues/10739
=> [dev-tool] log tshy build errors

.github/workflows/copilot-setup-steps.yml
to prevent copilot from thinking that we no longer support v18
also remove COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS environment variable as
it only applies to current job.
=> [EngSys] use NodeJS v18 in copilot dev environment

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/longIntervalStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/networkStatsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/baseSender.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/baseSender.spec.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
The network statsbeat should be a singleton to avoid scenarios where multiple statsbeat exports are initialized.
Yes
=> [Monitor OpenTelemetry Exporter] Make Network Statsbeat Singleton

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md, sdk/keyvault/keyvault-keys/src/cryptographyClientModels.ts
Looks like I never added the new `CKM_AES_KEY_WRAP{_PAD}` algorithms to the
union type. This PR adds them to the public API.
=> [keyvault] Add missing key wrap algos

sdk/servicebus/service-bus/src/receivers/receiver.ts
as the service reduced the valid range to 1-500.
Resolves #34274
=> [ServiceBus] reduce max count of messages to delete

sdk/core/core-client-rest/src/dom.d.ts
=> [core-client-rest] Delete dom.d.ts

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/review/identity.api.md, sdk/identity/identity/src/credentials/workloadIdentityCredential.ts
A customer pointed out that the return type of WorkloadIdentityCredential is
inconsistent and misleading. 
While core-auth exposes a getToken with a return type of `Promise<AccessToken |
null>`, Identity credentials generally throw if they're unsuccessful in getting a token and
their return types are the narrower `Promise<AccessToken>` 
Aligning WorkloadIdentityCredential with the rest of our credential return types
provides consistency and is not a breaking change (you can narrow return types
and widen input types)
Resolves #32612
=> [identity] Fix return type for workload identity

eng/tools/rush-runner/src/actions.js, eng/tools/rush-runner/src/helpers.js, eng/tools/rush-runner/src/rush.js, eng/tools/rush-runner/src/testProxyRestore.js, eng/tools/rush-runner/test/actions.spec.js, eng/tools/rush-runner/test/helpers.spec.js
Currently if reduced test matrix is enabled, we use `--only` for all packages.
We actually only want to do that for restricted packages because the list of
packages impacted by them is too large.  We still want to build and test
packages impacted by non-restricted packages.
=> [EngSys] fix CI runner testing for non-restricted packages

sdk/storage/storage-blob-changefeed/test/chunk.spec.ts
After upgrading to vitest 3.2.0, new typecheck errors started appearing because of the typing improvement to the return type of `expect.anything()`. 
>Argument of type 'AsymmetricMatcher<unknown, MatcherState>' is not
assignable to parameter of type 'AvroReadable'. Type 'AsymmetricMatcher<unknown, MatcherState>' is missing the following properties from type 'AvroReadable' position, read
Looking at the test, we actually don't need anything from the constructor argument. This PR updates the tests by replacing `expect.anything()` usage with a simple object literal.
=> [storage-blob-changefeed] fix test typecheck failure (#34732)

sdk/loadtesting/create-playwright/src/initialize.ts, sdk/loadtesting/create-playwright/test/initialize.spec.ts
@azure/create-playwright
New config
```ts
import { defineConfig } from '@playwright/test';
import { getServiceConfig, ServiceOS } from '@azure/playwright';
import { DefaultAzureCredential } from '@azure/identity';
import config from './playwright.config';
/* Learn more about service configuration at https://aka.ms/mpt/config */
export default defineConfig(
config,
getServiceConfig(config, {
exposeNetwork: '<loopback>',
timeout: 3 * 60 * 1000, // 3 minutes
os: ServiceOS.LINUX,
credential: new DefaultAzureCredential(),
})
);
```
=> refactor(loadtesting): install @azure/identity and create config with DefaultAzureCredentials

sdk/communication/communication-call-automation/assets.json, sdk/communication/communication-call-automation/package.json, sdk/communication/communication-chat/assets.json, sdk/communication/communication-rooms/assets.json
This pr is fixing tests for communication packages:
- call-automation
- rooms
- chat
This PR fixes [Failing build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4963547&view=ms.vss-test-web.build-test-results-tab&runId=55078128&resultId=100009&paneView=debug). 
After this [PR](https://github.com/Azure/azure-sdk-for-js/pull/33209), recordings were pointing to wrong API version. Recordings have been reverted or updated to point to proper API version in call-automation case.
pipeline started failing after: https://github.com/Azure/azure-sdk-for-js/pull/33209
=> Fix recordings

sdk/identity/identity/integration/AzureKubernetes/Dockerfile, sdk/identity/identity/test/integration/node/azureKubernetesTest.spec.ts
Revert AKS test to node 18 for the MCR image. Pipelines passing [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5005857&view=results)
- Linked issue for tracking purpose: #34944
=> [Identity] Revert AKS to node 18 image

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/index.ts, sdk/monitor/monitor-opentelemetry/src/types.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
* Updated the `StatsbeatFeatures` interface and `StatsbeatFeaturesMap` to include the `customerStatsbeat` property. (`sdk/monitor/monitor-opentelemetry/src/types.ts`, [[1]](diffhunk://#diff-48c64776365220d515750e313877e3ff6c92347670e2e5892c0df15179561028R72) [[2]](diffhunk://#diff-48c64776365220d515750e313877e3ff6c92347670e2e5892c0df15179561028R86)
* Added a new enum value, `CUSTOMER_STATSBEAT`, to `StatsbeatFeature` for tracking this feature. (`sdk/monitor/monitor-opentelemetry/src/types.ts`, [sdk/monitor/monitor-opentelemetry/src/types.tsR200](diffhunk://#diff-48c64776365220d515750e313877e3ff6c92347670e2e5892c0df15179561028R200))
* Updated the `useAzureMonitor` function to check the new environment variable and set the `customerStatsbeat` property …
=> [Monitor OpenTelemetry] Add Tracking for Customer Statsbeat to Feature Statsbeat

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/index.ts, sdk/monitor/monitor-opentelemetry/src/types.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/main.test.ts
We should track multi-ikey feature usage in Statsbeat.
Yes
=> [Monitor OpenTelemetry] Add Support for Multi-iKey Feature Statsbeat Tracking

sdk/communication/communication-call-automation/review/communication-call-automation.api.md, sdk/communication/communication-call-automation/src/callAutomationEventParser.ts, sdk/communication/communication-call-automation/src/callConnection.ts, sdk/communication/communication-call-automation/src/eventprocessor/eventResponses.ts, sdk/communication/communication-call-automation/src/generated/src/models/index.ts, sdk/communication/communication-call-automation/src/generated/src/models/mappers.ts, sdk/communication/communication-call-automation/src/models/events.ts, sdk/communication/communication-call-automation/src/models/options.ts, sdk/communication/communication-call-automation/src/models/responses.ts, sdk/communication/communication-call-automation/swagger/README.md, sdk/communication/communication-call-automation/test/node/callConnection.spec.ts
Communication-Call-Automation
Implements moveParticipants method for Azure Communication Services Call Automation SDK, enabling movement of participants between different calls. Follows existing SDK patterns with MoveParticipantSucceeded/MoveParticipantFailed events (singular per participant) and fromCall tracking for source call identification. Includes comprehensive interfaces (MoveParticipantsOptions, MoveParticipantsResult), event processing integration, and full test coverage with unit and live integration tests. API: moveParticipants(targetParticipants: CommunicationIdentifier[], options: MoveParticipantsOptions). Added unit tests for move participants.
Yes
https://github.com/Azure/azure-sdk-for-net/pull/50197
https://github.com/Azure/azure-sdk-for-python/pull/41448
=> Add moveParticipants functionality

sdk/core/core-util/vitest.config.ts
to avoid the possibility of mocked timers in one file affecting tests in another file.  There are only a handful of tests in core-util so the running time shouldn't be affected too much.
Related issue: https://github.com/Azure/azure-sdk-for-js/issues/34965
=> [Test][core-util] disable file Paralleism

sdk/test-utils/recorder/README.md
Came across a case in communication SDK where the recording was not saved for a particular test, turned out the recorder was not stopped at the end of the test due to a try-catch-return before the `await recorder.stop()` call.
Thanks @v-dharmarajv
=> [Recorder] Add FAQ

common/tools/dev-tool/src/commands/samples/publish.ts, common/tools/dev-tool/src/util/fileTree.ts, common/tools/dev-tool/src/util/samples/generation.ts
If `--force` is passed to `samples publish` command we log a warning instead of
throwing an error.
This option was removed in the refactoring PR
https://github.com/Azure/azure-sdk-for-js/pull/18556 but no reason is provided.
In fact we still have `--force` and `-f` usage in our NPM scripts today and they
are not doing anything.
This PR brings `--force` option back so that we can use it in intended
scnearios (for example, codegen automation)
Related issue: https://github.com/Azure/azure-sdk-tools/issues/10938#issuecomment-3011673979
=> [dev-tool] bring back --force option for samples publish command

sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.spec.ts
This pull request introduces utility functions to improve the detection of resource providers in the `StatsbeatMetrics` class and refactors the logic for identifying App Service and Function App environments. The changes streamline the code and enhance maintainability.
* [`sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts`](diffhunk://#diff-cd480996193513616a585afa0e25d1719ddb1862d3d45e3f13ee7ab00b2e7d24R294-R307): Added two new utility functions, `isAppService` and `isFunctionApp`, to encapsulate the logic for detecting App Service and Function App environments. These functions check specific environment variables to determine the type of resource provider.
* [`sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetri …
=> [Monitor OpenTelemetry Exporter] Update RP Checks for Statsbeat

sdk/cosmosdb/cosmos/src/queryExecutionContext/hybridQueryExecutionContext.ts, sdk/cosmosdb/cosmos/src/queryIterator.ts, sdk/cosmosdb/cosmos/test/internal/unit/hybridExecutionContext.spec.ts, sdk/cosmosdb/cosmos/test/public/integration/fullTextSearch.spec.ts
@azure/cosmos
#34933
This PR fixes the issue of SDK throwing an error on executing parameterized RRF queries.
Yes
=> [@azure/cosmos]: Fix Hybrid Search Parameterized queries

sdk/cosmosdb/cosmos/src/extractPartitionKey.ts, sdk/cosmosdb/cosmos/test/public/integration/extractPartitionKey.spec.ts
@azure/cosmos
This PR fixes a bug where the partition key for a migrated container was incorrectly returned as an empty array ([]). It now returns the correct partition key value.
Yes
=> [Cosmos] Enhance partition key extraction logic and update tests for system key

common/config/rush/pnpm-lock.yaml, sdk/communication/communication-sms/samples/v1-beta/javascript/package.json, sdk/communication/communication-sms/samples/v1-beta/typescript/package.json, sdk/healthdataaiservices/health-deidentification-rest/samples/v1/javascript/package.json, sdk/healthdataaiservices/health-deidentification-rest/samples/v1/typescript/package.json, sdk/kubernetesconfiguration/arm-kubernetesconfiguration-privatelinkscopes/samples/v1-beta/javascript/package.json, sdk/kubernetesconfiguration/arm-kubernetesconfiguration-privatelinkscopes/samples/v1-beta/typescript/package.json, sdk/playwright/arm-playwright/package.json
The PR with the old version might be in-flight while we bump to v20
=> [engsys] bump node version to 20 for leftover occurrence of v18

.github/CODEOWNERS
Mikhail is no longer working on openai.
=> [openai] update code owners

sdk/identity/identity-broker/README.md, sdk/identity/identity-broker/test/snippets.spec.ts, sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/README.md, sdk/identity/identity/TROUBLESHOOTING.md, sdk/identity/identity/package.json, sdk/identity/identity/review/identity-browser.api.diff.md, sdk/identity/identity/src/credentials/brokerCredential.ts, sdk/identity/identity/src/credentials/defaultAzureCredential.ts, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts, sdk/identity/identity/src/msal/nodeFlows/msalPlugins.ts, sdk/identity/identity/test/internal/node/brokerCredential.spec.ts, tsconfig.src.build.json
- Add broker flow to DAC using a new broker credential
1. Separate out the `getBrokeredToken` function & add a separate check for `disableAutomaticAuthentication` to prevent falling back to interactive authentication. This won't break current IBC implementation since IBC has throw before `onAuthenticationRequired` callback is reached.
**Pros:**
- Codepath is clear to follow, decoupled `getBrokeredToken` from `getTokenByInteractiveRequest`
- Save the time that customers would fail from `getTokenSilent` and go directly to the method that we want
**Cons:**
- More significant code change
- `disableAutomaticAuthentication` property is now overloaded with new code path
3. Add another property called `silentBrokeredAuthenticationOnly` to signify what we want to do. This property …
=> [Identity] Add broker flow to DAC chain

api-extractor-base.json, common/tools/dev-tool/src/commands/run/extract-api.ts
`dev-tool`
When running `api-extractor` locally it will introduce CRLF as the eol for api reports which is different from what is checked into git. Similarly, the `diff` package that we use to look at deltas between runtimes by default will preference towards introducing them as well.
=> [engsys] [devtool] tweak api-extractor and runtime diff report to always use unix newlines

sdk/agricultureplatform/arm-agricultureplatform/package.json, sdk/agricultureplatform/arm-agricultureplatform/src/static-helpers/urlTemplate.ts, sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json, sdk/apimanagement/api-management-custom-widgets-scaffolder/tsconfig.src.build.json, sdk/core/core-amqp/package.json, sdk/core/core-sse/package.json, sdk/core/core-sse/review/core-sse-node.api.md, sdk/core/core-sse/src/models.ts, tsconfig.src.build.json
Updates a few packages to use `tsconfig.src.build.json` when it is not straightforward.
- **core-sse**: rewrite the stream type to an equivalent form to fix this failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=5109924&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=25f5bbca-262e-5e46-5cac-451228cdef01&l=7862
- **core-amqp**: adds `ES2021.Promise` to the list of libs in `tsconfig.src.build.json` to support `AggregateError` (it is already supported in nodejs 16+)
- **apimanagement**: enable skipLibCheck because of an error in lru-cache v10
- **arm-agricultureplatform**: fix format
=> use tsconfig.src.build.json in select libs

eng/pipelines/templates/steps/build.yml
azure-identity-vscode
Failure at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5104412&view=logs&j=fd4602b3-f8ce-5804-85c1-0ad7d8f5d5ab
The doc publishing check is too restrictive. This PR allows generated docs to be copied over and published as a pipeline artifact.
The release jobs for the Docs have their own checks to ensure its only published when necessary.
https://github.com/Azure/azure-sdk-for-js/blob/5426b48f11184a99e1b9566399ce29b6fc0d542d/eng/pipelines/templates/stages/archetype-js-release.yml#L103
https://github.com/Azure/azure-sdk-for-js/blob/5426b48f11184a99e1b9566399ce29b6fc0d542d/eng/pipelines/templates/stages/archetype-js-release.yml#L71
NA
No. Pipeline change
None
NA
=> Lossen doc publishing restriction

api-extractor-base.json, common/tools/dev-tool/src/commands/run/extract-api.ts
The API Extractor uses `tsconfig.src.json` as its TypeScript configuration when generating all API files. However, each generated API file must be compliant with its target runtime environment. This means that all publicly exposed types must be fully defined for that runtime. For example, Node.js-specific types should not appear in a browser API report unless they have been explicitly redefined for the browser context. If we were to generate the complete API for the browser for ts-http-runtime today, we will find many references to undefined types in the browser context such as the `NodeJS` namespace: 
This PR improves the API extractor logic to look for `tsocnfig.src.<runtime name>.json` to use when generating the API files and falls back to `tsconfig.src.json` if one doesn't exist. A …
=> [api extractor] Use runtime-specific tsconfig

sdk/monitor/monitor-query-logs/tsp-location.yaml
Needed to fix the validation check https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5157329&view=logs&j=76698a2a-d14c-5c6b-54c9-86ac83b9ff72&t=77075814-4745-5051-6a72-475c72cab76c
=> [monitor-query-logs] tsp-location update with full hash

sdk/identity/identity/CHANGELOG.md, sdk/identity/identity/src/msal/nodeFlows/msalClient.ts
When using InteractiveBrowserCredential we set `wait` to true, which forces the
promise to wait until the app is _closed_ before fulfilling the promise. This
isn't quite right, as we want to hand control back to MSAL as soon as the app
opens and MSAL will then listen to the auth code and resolve the promise with an
access token.
The reason we did not notice this was because according to the 
[open documentation](https://github.com/sindresorhus/open?tab=readme-ov-file#wait) you
have to explicitly specify an app for it to be able to wait which we do not do.
As a result, on Mac, IBC does not resolve correctly until the browser instance
is exited. 
This PR removes the `wait` override, ensuring that control is handed back to
MSAL as soon as the browser opens.
Manual validation: …
=> [identity] Avoid waiting for app to close

sdk/identity/identity/package.json
It never worked, and having now given back control to MSAL before the browser is closed the sample will hang unfortunately. Disabling it makes sense given that it doesn't work on CI
=> [identity] Skip IBC sample execution

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/src/shared/config.ts, sdk/monitor/monitor-opentelemetry/src/shared/logging/diagFileConsoleLogger.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/logging/diagFileConsoleLogger.filter.test.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/logging/diagFileConsoleLogger.test.ts
https://github.com/Azure/azure-sdk-for-js/issues/35066
This pull request focuses on silencing noisy warnings related to async resource attributes and improving test coverage and logging behavior in the OpenTelemetry monitoring SDK. The main changes include adding filtering for specific warnings, handling VM resource detection asynchronously, and enhancing test cases to verify the new behavior.
* **Silencing noisy warnings**: Updated `DiagFileConsoleLogger` to filter out warnings about accessing resource attributes before async attributes are settled and improper module load order. This prevents unnecessary warnings from being displayed to users. (`sdk/monitor/monitor-opentelemetry/src/shared/logging/diagFileConsoleLogger.ts`, …
=> [Monitor OpenTelemetry] Silence Useless/Unactionable OpenTelemetry Logs

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, sdk/agricultureplatform/arm-agricultureplatform/package.json, sdk/databasewatcher/arm-databasewatcher/package.json, sdk/deviceregistry/arm-deviceregistry/package.json, sdk/eventhub/arm-eventhub/package.json, sdk/hybridconnectivity/arm-hybridconnectivity/package.json, sdk/hybridkubernetes/arm-hybridkubernetes/package.json, sdk/impactreporting/arm-impactreporting/package.json, sdk/kusto/arm-kusto/package.json, sdk/nginx/arm-nginx/package.json, sdk/pineconevectordb/arm-pineconevectordb/package.json, sdk/policy/arm-policy/package.json, sdk/policyinsights/arm-policyinsights/package.json, sdk/quota/arm-quota/package.json, sdk/redis/arm-rediscache/package.json, sdk/storage/storage-common/package.json
until we fix the break introduced by v5.9
also bump older versions to ~5.8.2 for packages missed the upgrade likely due to in-flight PRs
=> [EngSys] pin typescript version to v5.8 temporarily

sdk/notificationhubs/notification-hubs/assets.json, sdk/notificationhubs/notification-hubs/test/public/createOrUpdateRegistration.spec.ts, sdk/notificationhubs/notification-hubs/test/public/getRegistration.spec.ts, sdk/notificationhubs/notification-hubs/test/public/listRegistrations.spec.ts, sdk/notificationhubs/notification-hubs/test/public/listRegistrationsByTag.spec.ts, sdk/notificationhubs/notification-hubs/test/public/utils/recordedClient.ts
`@azure/notification-hubs`
Bodiless Matcher doesn't always get activated even though registered as part of the test, leading to test failures in the pipeline for some jobs, not all.
I couldn't reproduce the issue locally, but there are several instances of evidence from the pipeline.
1. Pipeline/job complaining mismatch in req body - https://dev.azure.com/azure-sdk/public/_build/results?buildId=5175819&view=logs&j=3b001400-51a2-579b-5880-362a5b0a112a&t=4fd227ba-0f36-57a1-8fce-5a18caa54ed9&l=1759
2. Corresponding test recording - [azure-sdk-assets/js/sdk/notificationhubs/notification-hubs/recordings/node/listregistrationsbytag/recording_should_list_all_registrations.json at js/notificationhubs/notification-hubs_9b371a54ae · Azure/azure-sdk-assets](https://github.com/Azure/azure-sdk-assets/b …
=> [notfication-hubs] Remove the need for BodilessMatcher in the tests with sanitizers

common/tools/dev-tool/src/commands/admin/list/index.ts, common/tools/dev-tool/src/commands/admin/list/typespec-migrations.ts
Adds a new command to dev-tool that can be used to check swagger -> tsp migration status
```bash
npx dev-tool admin list typespec-migrations
npx dev-tool admin list typespec-migrations --client-type RLC
npx dev-tool admin list typespec-migrations --client-type HLC
```
=> [dev-tool] Add TypeSpec migration report

sdk/identity/identity/src/credentials/brokerCredential.ts, sdk/identity/identity/src/credentials/defaultAzureCredential.ts
Add BrokerCredential to the list of credentials used by DAC. Also remove the AZURE_TOKEN_CREDENTIALS detail, as we want the credential chains doc to be the source of truth for that info.
=> Update DAC docs

CONTRIBUTING.md
This pull request adds clarification to the build command documentation in `CONTRIBUTING.md`, specifically regarding how to build a project and its dependencies using pnpm when inside a project.
Documentation updates:
* Added examples for `pnpm -F {./}... build` and `pnpm --filter=<package>... build` to show how to build a project and its dependencies from within the project directory.
=> Update pnpm commands in contributing.md

turbo.json
as they are generated as part of `build` script:
- temp/*.api.json
- review/*.api.md
=> [EngSys] include temp and review files in turbo build outputs

eng/pipelines/templates/steps/build.yml
Some packages like [test-utils](https://github.com/Azure/azure-sdk-for-js/blob/bfe9b4b6b22a90b216cb5943c0515c8310e28360/sdk/test-utils/ci.yml#L39) do not want to publish to the dev tag so we need to skip them. My earlier PR https://github.com/Azure/azure-sdk-for-js/pull/34850 had a but on the property, name so fixing that here.
=> Look for the correct property to skip dev feed publishing

common/tools/eslint-plugin-azure-sdk/package.json, sdk/containerregistry/container-registry-perf-tests/package.json
The two packages already include "npm run clean" in their "build" script
=> Remove redundant "prebuild" scripts

pnpm-lock.yaml, sdk/identity/identity-broker/CHANGELOG.md, sdk/identity/identity-broker/package.json, sdk/identity/identity-cache-persistence/package.json, sdk/identity/identity-vscode/CHANGELOG.md, sdk/identity/identity-vscode/package.json, sdk/identity/identity/TROUBLESHOOTING.md
Updates the min-version of `@azure/msal-node-extensions` to one that supports Mac OS broker. In addition, update identity-broker and identity-vscode to the next minor.
=> [identity] Mac OS Broker support

sdk/monitor/monitor-opentelemetry/CHANGELOG.md, sdk/monitor/monitor-opentelemetry/README.md, sdk/monitor/monitor-opentelemetry/src/shared/config.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/shared/config.test.ts, sdk/monitor/monitor-opentelemetry/test/internal/unit/traces/traceHandler.test.ts
This pull request updates the default configuration for OpenTelemetry instrumentations in the Azure Monitor SDK, making several instrumentations enabled by default and updating documentation and tests to reflect this change.
**Configuration changes:**
* The following instrumentations are now enabled by default: `azureSdk`, `mongoDb`, `mySql`, `postgreSql`, `redis`, and `redis4` in the `InternalConfig` class (`config.ts`). Previously, only `http` was enabled by default. (`[sdk/monitor/monitor-opentelemetry/src/shared/config.tsL81-R86](diffhunk://#diff-e87f512e0da7968d6421a844d909559a6b2963c947802ea359a7172e4e41d0c6L81-R86)`)
**Documentation updates:**
* The README and CHANGELOG have been updated to clarify that Azure SDK, MongoDB, MySQL, PostgreSQL, Redis, and …
=> [Monitor OpenTelemetry] Enable Instrumentations by Default

common/tools/dev-tool/package.json, common/tools/eslint-plugin-azure-sdk/package.json, common/tools/vite-plugin-browser-test-map/package.json, package.json, pnpm-lock.yaml, samples/cors/ts/package.json, sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json, sdk/core/core-rest-pipeline-perf-tests/package.json, sdk/test-utils/recorder/package.json, sdk/web-pubsub/web-pubsub-client-protobuf/package.json
Notable changes in newer version
- `cpy-cli` v6: requires NodeJS v20+
- `rimraf` v6:  requires NodeJS v20+
- `glob` v11:   requires NodeJS v20+
- `cspell` v9:  requires NodeJS v20+
- `concurrently` v9: requires NodeJS v20+. named export has been changed but we don't use it. https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
=> [EngSys] upgrade several dev dependencies

.github/CODEOWNERS
The focus of these changes is to transfer ownership of the Azure messaging services to the associated service teams.
=> [CODEOWNERS] Messaging ownership transfer

pnpm-lock.yaml, sdk/core/core-amqp/CHANGELOG.md, sdk/core/core-amqp/package.json, sdk/core/core-auth/CHANGELOG.md, sdk/core/core-auth/package.json, sdk/core/core-client-rest/CHANGELOG.md, sdk/core/core-client-rest/package.json, sdk/core/core-client/CHANGELOG.md, sdk/core/core-client/package.json, sdk/core/core-http-compat/CHANGELOG.md, sdk/core/core-http-compat/package.json, sdk/core/core-lro/CHANGELOG.md, sdk/core/core-lro/package.json, sdk/core/core-rest-pipeline-perf-tests/package.json, sdk/core/core-rest-pipeline/CHANGELOG.md, sdk/core/core-rest-pipeline/package.json, sdk/core/core-tracing/CHANGELOG.md, sdk/core/core-tracing/package.json, sdk/core/core-util/CHANGELOG.md, sdk/core/core-util/package.json
This should help reduce incompatible version issues that appeared recently.
=> [Core] bump `@azure/*` dependency versions to latest published

sdk/monitor/monitor-opentelemetry-exporter/src/types.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/logUtils.spec.ts, sdk/monitor/monitor-opentelemetry-exporter/test/internal/spanUtils.spec.ts
https://msazure.visualstudio.com/One/_git/CommonSchema/pullrequest/13225763?path=/v4.0/Mappings/AzureMonitor-AI.md
This pull request updates how OpenTelemetry end user identifiers are mapped to Application Insights tags, ensuring more accurate user tracking and improved compatibility with semantic conventions. The main changes involve introducing support for new experimental OpenTelemetry attributes, updating mapping logic, and enhancing test coverage.
**End User Attribute Mapping:**
* Added support for `ATTR_ENDUSER_ID` and `ATTR_ENDUSER_PSEUDO_ID` in `experimentalOpenTelemetryValues`, and included them in `httpSemanticValues` for consistent attribute handling. [[1]](diffhunk://#diff-e3555707ab8d46333aa668332f4c26950f95975852c4f234c0f308f321ccd50bR184 …
=> [Monitor OpenTelemetry Exporter] Add Support for User Semantic Conventions

sdk/monitor/ci.yml
as the package `azure/monitor-query` has been deleted.
=> Remove azure-monitor-query from CI artifact list

sdk/core/core-xml/tsconfig.browser.config.json
The browser version needs types from `@types/trusted-types`. This PR adds an
entry for `trusted-types` in core-xml's `types` compiler options in its
tsconfig.browser.config.json.
=> [core-xml] fix TypeScript compilation error for browser

eng/swagger_to_sdk_config.json
Copied the current configuration file used by SDK validation pipeline and added `buildScript` option.
=> Added spec-gen-sdk config for azsdk-cli tools

sdk/appconfiguration/app-configuration/assets.json, sdk/appconfiguration/app-configuration/test/public/index.spec.ts
`@azure/app-configuration`
#35887
parallel CI jobs (or other tests) that introduce an unlabeled setting can cause an additional { name: null } label to appear between successive enumerations in `toSortedLabelsArray`, leading to a mismatch.
Yes.
=> [App Configuration] - Make list label test deterministic

sdk/appconfiguration/app-configuration/test/public/utils/testHelpers.ts
#35887
In the testsuite, we have `deleteEverySetting` function, it will list all configuration settings and delete each setting.
However, the ADO CI pipeline may [occasionally fail](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5375880&view=logs&j=93ae3283-646d-56f5-516e-76f2b1ad7aff&t=79cb0933-95ff-5f35-aa3e-6c46498861b6&s=e1cfda09-5da2-5701-1d18-8913ba179eab). The root cause is that：
Other parallel tests may delete a setting after it was listed, creating a racing problem.
Before deleting a setting, we will first call `client.setReadOnly({ key: setting.key, label: setting.label }, false);` which will delete the lock for the configuration settings which will return 404 if the configuration setting is not existed. (Deleting an unexisted setting will return 204). We should …
=> [App Configuration] - Fix the racing problem when deleting a lock in the testcases

.vscode/settings.json, dataplane.code-workspace
This PR updates VS Code workspace settings to use Prettier as the default formatter and disables format-on-save specifically for Markdown files as we don't enforce a specific formatting style for them so auto-formatting can cause unwanted changes.
- Add editor.defaultFormatter: esbenp.prettier-vscode
- Add [markdown] override to disable format on save
- Mirror settings in dataplane.code-workspace for consistency
=> chore(vscode): set Prettier as default formatter and disable formatOnSave for Markdown

sdk/identity/identity/README.md
Removes the Azure AD reference from the Identity library's README, per the recommendation at https://learn.microsoft.com/entra/fundamentals/how-to-rename-azure-ad#communicate-the-change-to-your-customers to keep the old name reference for only 1 year.
=> Remove Azure AD reference from Identity README

pnpm-workspace.yaml
This PR prepares for the removal of the dev-tool run vendored call on these
tools. Per Pnpm recommendation, dependencies needed by individual packages
should be included in their package.json instead of global package.json.
These dev dependencies will be added to individual packages later with their
"catalog:` specifier.
=> [EngSys] add several dev dependency to default catalog

common/tools/dev-tool/src/commands/run/build-package.ts, pnpm-lock.yaml, pnpm-workspace.yaml, sdk/core/abort-controller/package.json, sdk/core/core-amqp/package.json, sdk/core/core-auth/package.json, sdk/core/core-client-rest/package.json, sdk/core/core-client/package.json, sdk/core/core-http-compat/package.json, sdk/core/core-lro/package.json, sdk/core/core-paging/package.json, sdk/core/core-rest-pipeline-perf-tests/package.json, sdk/core/core-rest-pipeline/package.json, sdk/core/core-sse/package.json, sdk/core/core-tracing/package.json, sdk/core/core-util/package.json, sdk/core/core-xml/package.json, sdk/core/logger/package.json, sdk/core/ts-http-runtime/package.json
per Pnpm recommendation, dependencies needed for individual packages should be
included in their package.json while the global package.json lists tools for mono
repo maintenance.
This PR adds `tshy` to the default catalog and includes it in core packages'
package.json files. Changes to rest of packages and code generator will be in
separate pull requests.
=> [EngSys] add `tshy` to default catalog and to core packages' dev deps
