common/config/rush/pnpm-lock.yaml
sdk/core/core-arm/package.json
sdk/core/core-http/package.json

- We'd like to keep our set of dev dependencies as small as possible.  This improves install time, reduces maintenance cost, etc.
- Since this dependency was only used to open a code-coverage HTML file, we don't think it's worth the cost.

Remove dev dependency opn-cli

---

sdk/storage/storage-queue/src/MessageIdClient.ts

If used this constructor for connection string, storage service throws an error saying "URL is undefined".
Came across this bug while working on sas conn string, then realised that there are no tests that cover this code path and thus the bug got unnoticed. 
Created an issue to add more tests and resolve the duplicated tests https://github.com/azure/azure-sdk-for-js/issues/4366

[Storage] Bug fix - InvalidUri 

---

sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/usernamePasswordCredential.spec.ts

This change adds username/password authentication as described in the AAD OAuth documentation:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc
Resolves #4310.

[Identity] Add UsernamePasswordCredential for username/password authentication

---

CONTRIBUTING.md

Updating the "rush add " command with "--caret" flag.
Installing a new npm package - 
- "npm install" adds ^ by default in the package.json, 
- "rush add" adds ^ only when the --caret flag is specified[ in the package.json].
Example - 
- `rush add -p hello --caret` -> `"hello": "^0.3.2"`
- `rush add -p hello` ->  `"hello": "~0.3.2"`

Updating the "rush add " command with "--caret" flag in Contributing.md

---

sdk/keyvault/keyvault-keys/tests/utils/recorder.ts
sdk/keyvault/keyvault-secrets/tests/utils/recorder.ts

With this change, we can have a `.env` file in `sdk/keyvault` (the parent
folder, as well as with other of our projects using dotenv) with the
following properties:
```
AZURE_CLIENT_ID=XXXXXXXX
AZURE_CLIENT_SECRET=XXXXXXXX
AZURE_TENANT_ID=XXXXXXXX
KEYVAULT_NAME=XXXXXXXX
TEST_MODE=["record" or "playback", without quotes]
```
And then run `rushx integration-test:node` to record (or playback) all
the tests with the Node environment, and also `rushx integration-test:browser`
to run the tests with the browser environment.
Would this help with #4389 ?
**Note:** The recorder already replaces all the environment variables with stub values! Only TEST_MODE=playback is needed to run the playback tests.
Please review 💙

[KeyVault] dotenv fix

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/src/log.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/pumpManager.ts
sdk/eventhub/event-hubs/src/util/cancellableDelay.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

Fixes #4464 
This change does a couple things:
1. Adds a `PumpManager` class that can create and remove `PartitionPumps`.
2. Updates the `EventProcessor` to have a loop. The loop is started when calling `eventProcessor.start()`.
Within the loop, the EventProcessor checks which partitions it is processing and starts processing any partitions it isn't already. Right now it does this check every 30 seconds but this could be configurable/based on some partition ownership rule in the future.
3. Updates `start` to no longer return a promise, since it just kicks off the loop.
I also temporarily removed the type validation that was being done on the PartitionProcessor because there isn't a way for the user to catch the error today. #4534 will address this.

[EPH] adds support for processing multiple partitions

---

sdk/storage/storage-blob/src/AppendBlobClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/PageBlobClient.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-queue/src/MessageIdClient.ts
sdk/storage/storage-queue/src/MessagesClient.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

Updating the union type of credential to `credential: SharedKeyCredential | AnonymousCredential | TokenCredential` for storage-blob and storage-queue.
Issue - #3944

[Storage] Better integration of @azure/identity

---

sdk/core/core-auth/package.json

This change switches `@azure/abort-controller` from being a `devDependency` to a full `dependency` in `@azure/core-auth` so that the re-exported `AbortSignalLike` can be resolved by developers who use `@azure/core-auth` as a dependency in their own code.  Having this dependency set as a `devDependency` in `core-auth` causes compile-time issues due to the `AbortSignalLike` type not being resolvable by the TypeScript compiler.

[core-auth] Change @azure/abort-controller to non-dev dependency in core-auth

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/lib/axiosHttpClient.ts
sdk/core/core-http/package.json
sdk/core/core-http/test/axiosHttpClientTests.node.ts
sdk/cosmosdb/cosmos/package.json

@daviwil: Note the move from `dependencies` to `devDependencies` in `core-http`.  I assume having an `@types` package in regular `dependencies` is always a mistake?

Update dev dependency @types/tunnel

---

sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/pumpManager.ts

This change updates the way `PartitionPump` handles errors from Event Hubs.
If a `receiveBatch` call returns an error, the user-defined `processError` method is called.
The `PartitionPump` is not stopped.
No future events are processed by the pump.
The user-defined `close` method is not called.
If a `receiveBatch` call returns an error, the user-defined `processError` method is called.
The `PartitionPump` is not stopped _if the error is retryable_.
Future events are processed by the pump _if the error is retryable_.
The user-defined `close` method is called _if the error is __not__ retryable_.

[Event Hubs] updates PartitionPump to continue receiving events for retryable errors

---

sdk/core/core-auth/package.json

This change updates `@azure/core-auth` to `1.0.0-preview.3` following the release of `1.0.0-preview.2` and also sorts the `dependencies` list to be alphabetical.

[core-auth] Bump @azure/core-auth version and sort dependencies

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/identity/identity/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

No listed breaking changes between `0.11.1` and `0.12.1`:
https://github.com/browserify/node-util/blob/master/CHANGELOG.md#0121
EventHubs live tests failures are a known issue: https://github.com/Azure/azure-sdk-for-js/pull/4574

Update dependency util to latest

---

sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

One of the EventProcessor tests were failing in some environments.
This test was failing in some cases because the delay between starting and stopping an EventProcessor was too small, which meant sometimes an event wouldn't be received during the delay.
I increased the delay, and changed the 2nd `start`/`stop` check to only check that PartitionProcessor methods have been called.

[Event Hubs] fixes flaky EventProcessor test

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/samples/cryptography.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts

This finishes filling out the documentation by adding samples to the API docs and a new section to the README that covers the CryptographyClient.

[Cryptography] Add README for CryptographyClient and samples to API docs

---

sdk/storage/storage-blob/src/AppendBlobClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/PageBlobClient.ts
sdk/storage/storage-queue/src/MessageIdClient.ts
sdk/storage/storage-queue/src/MessagesClient.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

Followup PR for https://github.com/Azure/azure-sdk-for-js/pull/4466
While adding the SAS connection string support to the existing connection string methods, observed that the browser tests failed because of undefined object `SharedKeyCredential`.
This PR fixes the issue by not letting the code path hit the `SharedKeyCredential` in the browser and is required for https://github.com/Azure/azure-sdk-for-js/pull/4372

[Storage] Verify SharedKeyCredential type only in NodeJS runtime

---

sdk/core/abort-controller/rollup.base.config.js
sdk/core/core-amqp/rollup.base.config.js
sdk/eventhub/event-hubs/rollup.base.config.js
sdk/eventhub/event-processor-host/rollup.base.config.js
sdk/identity/identity/rollup.base.config.js
sdk/keyvault/keyvault-keys/rollup.base.config.js
sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/servicebus/service-bus/rollup.base.config.js
sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-file/rollup.base.config.js
sdk/storage/storage-queue/rollup.base.config.js
sdk/template/template/rollup.base.config.js

- Was required due to rollup/rollup-plugin-commonjs#394
- Fixed in rollup-plugin-commonjs@1.10.1

Remove trailing slash from namedExports

---

sdk/eventhub/event-hubs/samples/eventProcessor.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

* Now EPH sample utilizes `InMemoryPartitionManager` and checkpoint events.
* Added a test case for the in memory checkpointing feature
-  create a in memory partition manager
-  create an event processor and do checkpointing, stop after some time
-  create another event processor with same partition manager. It starts processing from the 
checkpoint.

[Event Hubs] Add test to receive events from the checkpoint and update EPH sample

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

- rushFlags variable in our js-client pipeline actually is not being used currently
- added a glob filter variable which will filter the .tgz artifacts that we will actually want to publish
- we won't remove the filter variable in the release pipeline that we currently have, we'll let that be in

globFilter variable added

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/tools/select-packages/index.js

- updating existing script for the to and from action for different rush tasks
For ex we want to run in our pipelines:
1. `rush build --to <package> --from <package>`
2. `rush test --from <package>`
3. `rush lint --from <package>`

adding to and from parameters according to the action

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

Only breaking change I could see was dropping support for Node 6:
https://github.com/shellscape/mocha-chrome/compare/v1.1.0...v2.0.0

Update dev dependency mocha-chrome

---

README.md

Happened to notice a couple of `kevault` instances in README.md, fixing those to `keyvault`.

Fix spelling of 'keyvault' in README.md

---

sdk/core/core-http/lib/webResource.ts

This PR adds a new property by the name `spanOptions` to `RequestOptionsBase` in `core-http`
This gets used to create new spans when tracing is enabled.
To keep #4654 restricted to Keyvault related changes, this change has been pulled out of that PR

SpanOptions in RequestOptionsBase to create span for tracing

---

sdk/keyvault/keyvault-keys/src/index.ts

The getKey() method in the generated code in keyvaultClient.ts takes options of type `RequestOptionsBase`
This method is called from the hand written layer in index.ts. Here, instead of passing the request options, a higher level of options of type `GetKeyOptions` is passed instead.
This PR fixes this issue

[Keyvault Keys] Options to getKey() takes requestOptions

---

sdk/core/core-arm/Changelog.md
sdk/core/core-http/Changelog.md

Adding `1.0.0-preview.2` changelogs for these packages.

[core-http] Update core-http and core-arm changelogs for release

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/tools/select-packages/index.js

- Remove the `from` tag from pipeline, as it doesn't actually build the packages that are dependent on the target package 
- Revert the changes in script select-packages/index.js for from env variable

Revert commit

---

sdk/core/core-tracing/lib/implementations/noop/tracerNoOpImpl.ts
sdk/core/core-tracing/lib/interfaces/tracer.ts
sdk/core/core-tracing/lib/plugins/noop/noOpTracePlugin.ts
sdk/core/core-tracing/lib/plugins/opencensus/openCensusTracePlugin.ts
sdk/core/core-tracing/review/core-tracing.api.md

This PR adds a property to the `Tracer` interface to identify the plugin type being used.
This is useful when trying to decide whether or not tracer context should be added to the headers for a request

[Core Tracing] Add plugin type to tracer interface

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json

This change bumps the `@azure/core-auth` dependency for `@azure/core-http` and `@azure/core-amqp` to `1.0.0-preview.2`.

[core-http/amqp] Update core-auth dependency in core-http and core-amqp

---

.docsettings.yml
common/config/rush/pnpm-lock.yaml
sdk/identity/identity/.eslintignore
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/manual/README.md
sdk/identity/identity/test/manual/dist/index.html
sdk/identity/identity/test/manual/package.json
sdk/identity/identity/test/manual/src/index.tsx
sdk/identity/identity/test/manual/tsconfig.json
sdk/identity/identity/test/manual/webpack.config.js
sdk/identity/identity/tsconfig.json

This change adds a new `InteractiveBrowserCredential` to `@azure/identity` that leverages [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) to enable browser-based authentication for SDK libraries.O
Since it's almost impossible to write automated tests for this (without hooks provided from MSAL.js), I've put together a React-based manual testing UI to test that the authentication works in a "real" browser-based app.  I admit, I went a little overboard on this, but the idea is that this could be a foundation for a more full-fledged manual test / sample UI that all of our browser-supporting SDK libraries could plug into.
**Screenshot**

[Identity] Add InteractiveBrowserCredential for browser-based authentication

---

sdk/core/core-amqp/samples/cbsAuthUsingAad.ts
sdk/eventhub/event-hubs/samples/usingAadAuth.ts
sdk/keyvault/keyvault-certificates/samples/singleCertificate.ts
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/samples/cryptography.ts
sdk/keyvault/keyvault-keys/samples/helloWorld.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/README.md
sdk/keyvault/keyvault-secrets/samples/backupAndRestore.ts
sdk/keyvault/keyvault-secrets/samples/challenge.ts
sdk/keyvault/keyvault-secrets/samples/deleteAndRecover.ts
sdk/keyvault/keyvault-secrets/samples/helloWorld.ts
sdk/keyvault/keyvault-secrets/samples/listOperations.ts
sdk/keyvault/keyvault-secrets/src/index.ts

This change updates all samples and READMEs that reference `EnvironmentCredential` to use `DefaultAzureCredential` instead.  We want to advertise this as the standard credential so that it will work for most users in most cases without extra configuration.  This also allows us to update the default credentials used inside of its chain over time.

Update samples and readmes to use DefaultAzureCredential

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

This change moves `@types/tunnel` back to a full `dependency` so that consumers of `@azure/core-http` don't hit TypeScript compiler errors about missing types from that package when installing via plain `npm`.  For some reason Rush masks this issue in our repo.  This change was introduced very recently in #4541 so we didn't catch it until we tried to verify release packages using only `npm`.
/fyi @ramya-rao-a @chradek

[core-http] Move @types/tunnel to full dependency

---

sdk/core/core-tracing/package.json

This PR removes the `private:true` in package.json that blocks us from publishing the package

[Core Tracing] Remove private in package.json

---

sdk/core/core-tracing/ThirdPartyNotices.txt
sdk/core/core-tracing/package.json

We need ThirdPartyNotices whenever we redistribute open source software in our package. Since core-tracing presently incorporates interfaces from opentelemetry-js, this PR includes the necessary notice. This can be deleted once we have an actual npm dependency on opentelemtry-js.

[core-tracing] Add ThirdPartyNotices.txt

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/review/event-hubs.api.md

Currently the sample for EventProcessor in the README uses types.
We need these samples to be in javascript to reduce the number of steps for the user to be able to run the code.

[Event Hubs] Update sample in Readme to use js not ts

---

sdk/keyvault/keyvault-keys/tests/list.test.ts
sdk/keyvault/keyvault-secrets/tests/list.test.ts

The issue is likely to be that we weren't waiting for both entities to be deleted before we moved on.

[KeyVault] Fix flaky tests around the getDeleted* tests

---

common/config/rush/pnpm-lock.yaml
rush.json

This is a followup PR for https://github.com/Azure/azure-sdk-for-js/pull/4741 (which removed cosmos v2 from azure-sdk-for-js repo).

[Cosmos] Updating `rush.json` and `pnpm-lock` files after removing cosmos

---

sdk/graphrbac/graph/README.md

Code samples for the Graph client do not work as written. This PR updates the samples with the necessary changes for them to run.

[Graph] Fix code samples in README

---

sdk/core/core-amqp/package.json
sdk/core/core-arm/lib/azureServiceClient.ts
sdk/core/core-arm/package.json
sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/lib/serviceClient.ts
sdk/core/core-http/lib/webResource.ts
sdk/core/core-http/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/template/template/package.json

This change reintroduces the `ServiceClientCredentials` interface as an accepted credential type for `ServiceClient` classes.  This is necessary because libraries like @azure/app-configuration and the various Cognitive Services libraries need to use their own custom (non-AAD) authentication schemes.  Without this change, users of those libraries would have to construct their own RequestPolicy pipeline just so that the `signingPolicy` can be used.
Since this affects a bunch of libraries I went ahead and bumped the core dependency versions of our various libraries so that everything is up to date (@chradek, this will affect your tracing PR).

[core-http] Reintroduce ServiceClientCredentials as an accepted credential type

---

sdk/appconfiguration/app-configuration/README.md

This change fixes a build break caused by PR #4753.  Apparently that PR was treated as a management plane library so the CI run did not run these README checks.  I'm also adding the changes necessary to have the `js - client` CI pipeline run for it.

Make @azure/app-configuration README conformant with docwarden

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/package.json

Surprisingly there were no `pnpm-lock.yaml` updates after making these changes.
Fixes #4673.

[Identity] Update @azure/identity dependencies to use caret versions

---

.docsettings.yml

Build failed because of the missing headers in test/readme
```
sdk/cosmosdb/cosmos/test/readme.md is missing headers with patterns: 
* ^Azure (.+ client library for (JS|AMQP operations)|Smoke Test for JS) 
* ^Getting started$ 
* ^Key concepts$ 
* ^Examples$ 
* ^Troubleshooting$ 
* ^Next steps$ 
* ^Contributing$
```
Ignore readme for now.
Later, update Readme.md files by adding the missing headers - Issue to track #4799

[Cosmos] Update .docsettings.yml to ignore cosmos/test/readme missing headers

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/tools/select-packages/index.js

Related issue: #4350 
Since rush doesn't build all transitive dependencies with the `--from` tag, we cannot use the from tag with build step. We will try with the from tag with just the `test` step
Reference to earlier commit that had to be reverted - https://github.com/Azure/azure-sdk-for-js/commit/70563f408cd9753d11b9ce29a8434a8765300043

from tags added for test step

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

#fix for PR 4771 that broke the js - identity - ci pipeline
Running `build` and `build:test` steps for entire repo

To from tag

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/mocha.reporter.config.json
sdk/core/abort-controller/package.json
sdk/core/core-arm/mocha.config.json
sdk/core/core-arm/package.json
sdk/core/core-arm/test/mocha.opts
sdk/core/core-http/mocha.config.json
sdk/core/core-http/package.json
sdk/core/core-http/test/mocha.opts
sdk/cosmosdb/cosmos/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

- All packages
- "mocha-multi-reporters" was replaced with "mocha-multi" to align with repo standard
- core-arm, core-http
- Reporter "list" was replaced with "spec" to align with repo standard
- keyvault-*
- Command-line options were moved to align with repo standard

Replace mocha-multi-reporters with mocha-multi

---

sdk/keyvault/keyvault-certificates/tests/utils/recorder.ts
sdk/keyvault/keyvault-keys/tests/utils/recorder.ts
sdk/keyvault/keyvault-secrets/tests/utils/recorder.ts
sdk/storage/storage-blob/test/utils/recorder.ts
sdk/storage/storage-file/test/utils/recorder.ts
sdk/storage/storage-queue/test/utils/recorder.ts

- The behavior of `testContext` changed slightly between mocha v5 and v6.
- In mocha v5, `testContext.currentTest` was null for "before all" hooks, so it could be used to disambiguate between "before all" and "before each" hooks.
- In mocha v6, `testContext.currentTest` points to the individual test that will be run next, for both "before all" and "before each" hooks.
- The new test selection logic is compatible with both mocha v5 and v6

Make recorder test selection compatible with mocha@6

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

- Move "sdk" from "contents" to "sourceFolder"
- Logically equivalent to the previous configuration
- Improves perf because the "sourceFolder" filter is applied before the "contents" filter
- Without this change, CopyFiles can fail with an out-of-memory error in large repos
- Fixes #4847

Improve performance of CopyFiles

---

sdk/test-utils/recorder/package.json

Build failed for the PR https://github.com/Azure/azure-sdk-for-js/pull/4883 when test-utils-recorder is imported in keyvault packages because of the outdated lint step.
Thanks to @KarishmaGhiya for helping.
/cc - @sadasant

[Record and Playback] Update lint step in the test-utils-recorder

---

sdk/cognitiveservices/cognitiveservices-luis-authoring/package.json
sdk/cognitiveservices/cognitiveservices-luis-authoring/src/lUISAuthoringClientContext.ts

We released version 3.0.0 of luis runtime as part of #4792 but forgot to update the user agent string.
This PR attempts to fix the user agent string

[Luis authoring] Update package version in user agent string

---

sdk/cognitiveservices/cognitiveservices-luis-runtime/package.json
sdk/cognitiveservices/cognitiveservices-luis-runtime/src/lUISRuntimeClientContext.ts

We released version 4.0.0 of luis runtime as part of #4791 but forgot to update the user agent string.
This PR attempts to fix the user agent string

[Luis runtime] Update package version in user agent string

---

sdk/identity/identity/src/credentials/managedIdentityCredential.ts

If the IMDS endpoint was not available, the request would time out, but this error code was not handled resulting in a false detection of the IMDS endpoint.

[Identity] Fix IMDS endpoint detection false positive

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

The `receiveMessages()` call uses 2 timers internally
- The first is configurable by the user and is meant to be the max time that can be taken by the operation. Default is 60 seconds
- The second is hard-coded to 1 second. This timer gets reset every time a new message is received internally. This timer exists so that we don't wait too much for subsequent messages and return as soon as possible with non zero number of messages.
Currently we unset the first timer after receiving the first message.
Due to this, as long as a new message received within 1 second of the old message, we continue to receive messages until maxMessageCount is hit and the user provided timeout gets ignored.
In PeekLock mode, this problem is not seen much as the messages are received much faster than in …

[Service Bus] Use timer for entire receiveMessages operation

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/shims.d.ts
sdk/core/core-http/lib/policies/msRestUserAgentPolicy.browser.ts
sdk/core/core-paging/types/corePaging.d.ts
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

In version 3.6.2 of TypeScript, NavigatorID adds `oscpu` as a string. This conflicts with our existing type that declared `oscpu` as a string or undefined, and causes build failures when using the latest version of TypeScript.
/cc @bterlson

[core-http] fixes type error when using TypeScript 3.6.2

---

sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/lib/policies/tracingPolicy.ts
sdk/core/core-http/lib/serviceClient.ts
sdk/core/core-http/lib/webResource.ts
sdk/core/core-http/package.json
sdk/core/core-http/test/policies/tracingPolicyTests.ts
sdk/core/core-tracing/lib/plugins/noop/noOpSpanPlugin.ts
sdk/core/core-tracing/lib/plugins/opencensus/openCensusSpanPlugin.ts
sdk/core/core-tracing/lib/plugins/opencensus/openCensusTraceStatePlugin.ts
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts

This update is meant to add support for setting the `traceparent` and `tracestate` headers when keyvault keys is instrumented with tracing.
I created a new policy in `core-http` so that any package that depends on `core-http` can eventually support tracing. Note that it is not in the default pipeline right now.
- Added a dependency on `core-tracing`.
- Updated `WebResource` to have a `spanOptions` field. This is needed when using manual tracing instrumentation.
- Added the `TracingPolicy` policy. This policy will check if `spanOptions` exists on the `WebResource`, and if it does it will:
- create a new child span
- set the `traceparent` and `tracestate` headers as appropriate
- reexports exports from `core-tracing`
- Added an opencensus plugin for span context. This wraps the span context …

[core-http][core-tracing][keyvault keys] adds tracing policy

---

sdk/core/core-auth/review/core-auth.api.md
sdk/core/core-auth/src/tokenCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

This PR attempts to add  #4855 by plumbing a ping timeout that the user can configure. It will also default to a longer 5000 ms (vs the original 500 ms) if the timeout has not been configured.

Attempt to address ping timeout issue

---

sdk/cosmosdb/cosmos/src/typings/atob.d.ts
sdk/cosmosdb/cosmos/src/typings/binary-search-bounds.d.ts
sdk/cosmosdb/cosmos/test/types/proxy-agent.ts

Build failed in the feature/storage branch because of the missing files in `types` and `typings` folders resulted from merging the mater.
This PR attempts to add the files and fix the build.

[Storage] Add missing files in `types` and `typings` folders for comsos

---

sdk/servicebus/service-bus/src/core/messageReceiver.ts

The `onDetached()` can be called multiple times on the same receiver. One such cases is when both a `receiver_close` and `session_close` event is fired.
In such cases, only one of the `onDetached()` calls should result in `init()` creating a new receiver link. This is handled today by the `isConnecting` boolean property which we use to ensure that when a new receiver is being created, another call to `init()` becomes a no-op.
But, since we update the `name` regardless of whether `init()` is creating a new link or it is a no-op, we can end up in a situation where the `name` property of the receiver is not the same name as the actual underlying receiver. This results in all message settlement request failing as the name of the receiver on the message will never match the name of the …

[Service Bus] Use new name for receiver only if creating a new receiver

---

sdk/core/core-http/lib/policies/deserializationPolicy.ts

This is an attempt to fix #4844.  Leaving it as a draft to open conversation about possible implications of adding text/plain as an accepted MIME type.

[core-http] Add text/plain to accepted MIME types for JSON output

---

sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/lib/util/utils.ts
sdk/core/core-http/lib/util/xml.browser.ts
sdk/core/core-http/lib/webResource.ts
sdk/core/core-http/webpack.testconfig.ts

Fir formatting issues to prevent noise later.

[core-http] Fix formatting errors

---

eng/tools/analyze-deps/deps.html.hbs
eng/tools/analyze-deps/index.js

Releases from unified pipelines don't define the `Release.*` variables.

Update analyze-deps to detect releases from unified pipelines

---

sdk/core/core-http/lib/webResource.ts

to pass the two missing fields `proxySettings` and `keepAlive` to the
constructor call.
Fixes #5020

[core-http] Fix WebResource.clone()

---

sdk/storage/storage-file/samples/javascript/proxyAuth.js
sdk/storage/storage-file/samples/typescript/proxyAuth.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-queue/samples/javascript/proxyAuth.js
sdk/storage/storage-queue/samples/typescript/proxyAuth.ts
sdk/storage/storage-queue/src/Pipeline.ts

Basic authentication support for storage-blob - https://github.com/Azure/azure-sdk-for-js/pull/5009
This PR adds similar support for file and queue.

[Storage] Basic authentication support for storage-file and storage-queue

---

sdk/identity/identity/src/client/errors.ts
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.browser.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.browser.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/chainedTokenCredential.spec.ts
sdk/identity/identity/test/clientSecretCredential.spec.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/usernamePasswordCredential.spec.ts

This PR runs the prettier formatter on all the files in the identity library.
This is done so that we can remove noise from PRs like #5019

[Identity] Format all files

---

sdk/core/core-auth/review/core-auth.api.md
sdk/core/core-auth/src/tokenCredential.ts

This PR updates the `GetTokenOptions` interface in `core-auth` to support the `spanOptions` that will be used in `@azure/identity` to create spans appropriately if a tracer was set.
This change has been pulled out of @sarangan12's PR #5019 in order to enable shipping of the `core-auth` package ahead of time when compared to `@azure/identity`.

Update GetTokenOptions to support tracing

---

sdk/eventhub/ci.yml

This PR adds ```@azure/eventhubs-checkpointstore-blob``` to the set of artifacts that is releasable via the unified pipeline.

Add checkpointstore package to set of artifacts.

---

sdk/storage/README.md
sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/samples/README.md
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file/README.md
sdk/storage/storage-file/package.json
sdk/storage/storage-file/samples/README.md
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/samples/README.md
sdk/storage/storage-queue/src/utils/constants.ts

Updates to all the references to version numbers for storage sdks - 12.0.0-preview.3

[Storage] Update version numbers - 12.0.0-preview.3

---

sdk/core/abort-controller/changelog.md

Adds the changelog.md file for abort-controller and adds an entry for the upcoming release.

[Abort Controller] adds changelog

---

sdk/cosmosdb/cosmos/samples/package.json

js - cosmos - ci pipeline failed many times because of this `ItemManagement` sample due to which PR validations are failing.
https://dev.azure.com/azure-sdk/public/_build?definitionId=450&_a=summary
This PR skips that particular sample until more investigation is done. Keeping the issue https://github.com/Azure/azure-sdk-for-js/issues/5049 open until this is fixed.

[Comsos] Skip ItemManagement sample in PR validations

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json

NPMJS doesn't seem to be updating the readme displayed on the site - we're going to bump the version and upload the package again.

[app-configuration] Bumping version for re-upload

---

samples/SmokeTest/.gitignore
samples/SmokeTest/package-lock.json
samples/SmokeTest/package.json

* Add `package-lock.json` for repeatable builds
* Pin preview versions since there may be breaking changes between previews
* Add `*.js` and `*.js.map` to `.gitignore` (files are generated by `tsc`)

Update dependencies to latest

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/partitionProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

The intent of these changes is to introduce the concept of partition metrics and piggy-backing last enqueued event info on received events. These metrics allow library consumers the opportunity for real-time inspection of the event processing backlog without the need to make dedicated requests for partition information.
Below are changes: 
*  Added `LastEnqueuedEventInfo` property and getter/setter for this on the PartitionProcessor class.
* Added `trackLastEnqueuedEventInfo`  in  an `EventHubConsumerOptions` interface.
* Added tests.

[Event Hubs] Add trackLastEnqueuedInfo feature on EventProcessor

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/src/auth/aad.ts

For more context refer to #4927 
This PR updates amqp-common and introduces the `TokenCredentialInterface` for use within amqp-common and dependents.

[amqp-common] Remove ms-rest-node-auth dependency from getting included in final bundling

---

sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

Related PR: https://github.com/Azure/azure-sdk-for-js/pull/5140
`processEvents()` method swallows all the errors, so removed all the test checks from `processEvents(events)` method that could throw errors.

[Event Hubs] Fix trackLastEnqueuedInfo tests

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/changelog.md
sdk/core/core-amqp/package.json
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/test/requestResponse.spec.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts

Fixes #4767 
Details are in the issue above. This change only removes the message listener from an amqp receiver if the outer Promise can be either resolved or rejected by the response from the server.

[core-amqp] fixes bug when making parallel send requests with RequestResponseLink

---

sdk/storage/storage-file/recordings/browsers/directoryclient/recording_listhandles_should_work.json
sdk/storage/storage-file/recordings/node/directoryclient/recording_listhandles_should_work.js
sdk/storage/storage-file/samples/javascript/iterators-handles.js
sdk/storage/storage-file/samples/typescript/iterators-handles.ts
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/test/directoryclient.spec.ts

[Storage][File] Add async iterator for listing handles in DirectoryClient

---

sdk/identity/identity/src/credentials/managedIdentityCredential.ts

Fixes #4965 
Switch to using default date parser for MSI access token expiration. This should accept more date formats that the original format. Should help address connecting with Azure Function Apps (and possibly Azure App Service as well).
Note: this will fix is also more lenient than the parsing we had originally.

[Identity] Use the JS date parser for expiration

---

sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

- remove extra `}` after a link
- wrap code examples with js code block so the typedoc output correctly show example code in code blocks.

[Storage] Fix doc issues - broken link and example code blocks

---

common/config/rush/version-policies.json
rush.json

This allows us to have "groups" of libraries and to build them by name, via:
```shell
rush build --to-version-policy <group>
rush build --from-version-policy <group>
```
So far the groups I have defined are:
- `core` - core libraries
- `client` - data plane libraries
- `management` - management plane libraries
- `utility` - utility / test libraries that don't get shipped

Create and assign version policies as groups

---

sdk/storage/storage-blob/test/blobbatch.spec.ts
sdk/storage/storage-blob/test/blobserviceclient.spec.ts
sdk/storage/storage-blob/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-blob/test/node/sas.spec.ts

Tests that depend on ACCOUNT_TOKEN are being skipped(by `return;`) in the CI integration tests due to the lack of a valid ACCOUNT_TOKEN.
Instead of "return"ing, this.skip() can be leveraged to skip the test.
That way we can be sure we are not testing it when we don't have a valid ACCOUNT_TOKEN.

[Storage] Leverage `this.skip();` instead of `return;` in the test for TokenCredential

---

sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/samples/javascript/proxyAuth.js
sdk/storage/storage-blob/samples/typescript/proxyAuth.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/samples/javascript/proxyAuth.js
sdk/storage/storage-file/samples/typescript/proxyAuth.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/samples/javascript/proxyAuth.js
sdk/storage/storage-queue/samples/typescript/proxyAuth.ts
sdk/storage/storage-queue/src/Pipeline.ts

When `pipelineOptions.proxy` is undefined, `getDefaultProxySettings()` in core-http tries to load the proxy settings from the environment 
(Example - `process.env.HTTP_PROXY = "http://127.0.0.1:8888";` can be set)

[Storage] Get proxySettings from Environment when not defined in the code

---

sdk/storage/storage-blob/typedoc.json
sdk/storage/storage-file/typedoc.json
sdk/storage/storage-queue/typedoc.json

We still want to be able to jump to types that we own even they are from other
packages. For example, `PagedAsyncIterableIterator` is from `@core-paging`.
Setting `excludeExternals` to `false` and excluding files under `node_modules`
so that we could still have docs for types from other libraries in the repo.
Also exclude storage-specific files for generated operations.

[Storage] config typedoc behavior

---

sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/AppendBlobClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/PageBlobClient.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/node/emulator-tests.spec.ts
sdk/storage/storage-blob/test/utils/index.ts
sdk/storage/storage-blob/test/utils/testutils.common.ts

This PR adds the support for Development connection string and some tests for the emulator(local).
- Development Connection String
- `DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;`
- Shorthand notation is also supported
- `UseDevelopmentStorage=true` or 
- `UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://myProxyUri`
Added a separate set of Emulator tests(test suite in the node tests) which will be skipped if the `STORAGE_CONNECTION_STRING` environment variable doesn't start with `UseDevelopmentStorage=true`.

[Storage] Support for Development Connection String - storage-blob

---

sdk/storage/storage-blob/recordings/node/aborter/recording_should_abort_after_aborter_timeout.js
sdk/storage/storage-blob/recordings/node/aborter/recording_should_abort_after_father_aborter_calls_abort.js
sdk/storage/storage-blob/recordings/node/aborter/recording_should_abort_when_calling_abort_before_request_finishes.js
sdk/storage/storage-blob/recordings/node/aborter/recording_should_not_abort_after_calling_abort.js
sdk/storage/storage-blob/recordings/node/aborter/recording_should_not_abort_when_calling_abort_after_request_finishes.js
sdk/storage/storage-blob/test/aborter.spec.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts
sdk/storage/storage-blob/test/node/utils.spec.ts
sdk/storage/storage-file/recordings/node/aborter/recording_should_abort_after_parent_aborter_calls_abort.js
sdk/storage/storage-file/test/aborter.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-file/test/node/highlevel.node.spec.ts
sdk/storage/storage-queue/test/aborter.spec.ts

Some tests currently do not verify expected errors properly. They just catch the
error then pass the tests. The problem is `assert.fail()` in the `try`-block
also throws error. Assertion error is swallowed if we don't check the caught
error.
This change adds verification for the expected errors.
Resolves #4580

[Storage] verify errors for tests that expect errors

---

sdk/storage/storage-blob/samples/javascript/azureAdAuth.js
sdk/storage/storage-blob/samples/typescript/azureAdAuth.ts
sdk/storage/storage-queue/samples/javascript/azureAdAuth.js
sdk/storage/storage-queue/samples/typescript/azureAdAuth.ts

Adding more description to the DefaultAzureCredential sample related to the setup in comments.
```
Setup :
- Reference - [Authorize access to blobs and queues with Azure Active Directory from a client application](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app)
- Register a new AAD application and give permissions to access Azure Storage on behalf of the signed-in user
- Follow [Documentation to register a new application](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) in the Azure Active Directory(in the azure-portal).
- In the API permissions section, select Add a permission and choose Microsoft APIs. 
- Pick `Azure Storage` and select the checkbox next to `user_impersonation` and then click `Add permissions`. This …
```

[Storage] Improve comments for AAD setup - DefaultAzureCredential

---

sdk/cosmosdb/cosmos/test/functional/ttl.spec.ts

The backend now supports 0 for TTL

[Cosmos] Remove zero TTL check

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/helloworld.ts
sdk/appconfiguration/app-configuration/samples/helloworldWithLabels.ts
sdk/appconfiguration/app-configuration/src/index.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/tsconfig.json

This allows you to iterate over the list of settings returned individually or, optionally, by page which also returns the HTTP responses.

listRevisions and listConfigurationSettings now return PagedAsyncIterableIterator

---

sdk/cosmosdb/cosmos/package.json

writeSDKVersion was being called after bundling so it was missing in the final artifacts

[Cosmos] Fix incorrect lib version in UserAgent

---

sdk/core/core-http/lib/fetchHttpClient.ts
sdk/storage/storage-file/test/utils/recorder.ts

We were reporting the progress before data is pushed. This leads to customer
reported issue like
https://github.com/Azure/azure-sdk-for-js/issues/4719
where the uploaded progress events are triggered before data chunks are
completely uploaded.
This change introduces a `ReportStream` that provides the correct `_transform`
behavior.

[core-http] Report progress after pushing data

---

sdk/storage/storage-file/test/fileclient.spec.ts

Reference - https://github.com/Azure/azure-sdk-for-js/issues/5326
Aborter error is different in both node and browser.
Browsers - `Error: The request was aborted`
Node - `AbortError: The user aborted a request`

[Storage] Fix test failure caused by the differences in node and browser

---

sdk/test-utils/recorder/GUIDELINES.md

Updating the description of getUniqueName() to make the behaviour clear.

[Common Recorder] getUniqueName() - Update the description when same label is used more than once

---

eng/pipelines/templates/steps/cosmos-additional-steps.yml

Issue - https://github.com/Azure/azure-sdk-for-js/issues/5350
cc - @joheredi

[Cosmos] Use rushx instead of rush in the CI steps specific to Cosmos

---

sdk/cosmosdb/cosmos/samples/MultiRegionWrite/ConflictWorker.ts
sdk/cosmosdb/cosmos/src/ChangeFeedIterator.ts
sdk/cosmosdb/cosmos/src/ChangeFeedOptions.ts
sdk/cosmosdb/cosmos/src/LocationInfo.ts
sdk/cosmosdb/cosmos/src/client/Container/PartitionKeyRange.ts
sdk/cosmosdb/cosmos/src/client/Container/UniqueKeyPolicy.ts
sdk/cosmosdb/cosmos/src/common/statusCodes.ts
sdk/cosmosdb/cosmos/src/documents/ConnectionMode.ts
sdk/cosmosdb/cosmos/src/documents/ConsistencyLevel.ts
sdk/cosmosdb/cosmos/src/documents/DataType.ts
sdk/cosmosdb/cosmos/src/documents/IndexKind.ts
sdk/cosmosdb/cosmos/src/documents/IndexingMode.ts
sdk/cosmosdb/cosmos/src/documents/PermissionMode.ts
sdk/cosmosdb/cosmos/src/documents/TriggerOperation.ts
sdk/cosmosdb/cosmos/src/documents/TriggerType.ts
sdk/cosmosdb/cosmos/src/documents/UserDefinedFunctionType.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/FetchResult.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/SqlQuerySpec.ts
sdk/cosmosdb/cosmos/src/request/LocationRouting.ts
sdk/cosmosdb/cosmos/src/request/SharedOptions.ts
sdk/cosmosdb/cosmos/src/request/StatusCodes.ts
sdk/cosmosdb/cosmos/src/request/TimeoutError.ts
sdk/cosmosdb/cosmos/src/retry/retryOptions.ts
sdk/cosmosdb/cosmos/src/session/VectorSessionToken.ts
sdk/cosmosdb/cosmos/test/common/MockQueryIterator.ts
sdk/cosmosdb/cosmos/test/common/TestData.ts
sdk/cosmosdb/cosmos/test/common/_testConfig.ts

Reference - https://github.com/Azure/azure-sdk-tools/issues/199
When a file starts with the JSDoc comments`(/** * * */)`, placement of copyright headers by the `eslint-plugin-azure-sdk`  is a bit off. (#5151)
This PR fixes the positioning of Copyright Headers for all the affected files in cosmos sdk.

[Cosmos] Moving copyright headers to the top of the file

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-file/package.json
sdk/storage/storage-queue/package.json

Cleaning up versions after the September release. See docs here: https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#javascript

bump versions after September preview release

---

sdk/eventhub/event-hubs/karma.conf.js
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts
sdk/eventhub/event-hubs/tests.yml

This PR updates the test matrix to include browser test runs.
Since we need different connection strings for the browser tests, the env vars for them are pulled into the matrix

Use separate EventHubs namespace for browser tests in CI

---

sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/index.ts
sdk/appconfiguration/app-configuration/samples/setReadOnlySample.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/src/responseBodyNotFoundError.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/test/throwOrNotThrow.spec.ts

Update APIs to consistently handle etags via ifMatch/ifNoneMatch fields in the options parameter.
* Many tests added to get all the edge cases and to document the various status codes and errors
* Added an exception that might get moved into core (ResourceBodyNotFoundError). Hiding this away in my package for now since the name is still under discussion (but the concept is not).

[app-configuration] Handle ETags and ifMatch/ifNoneMatch conditionals

---

sdk/core/core-http/lib/policies/tracingPolicy.ts
sdk/core/core-http/test/policies/tracingPolicyTests.ts

The changes are smaller than they look...formatting changes are included.
I noticed while working on the event-hubs tracing that the `traceparent` header should start with a version number (always '00' for now), and the traceFlags should always be 2 digits.
Updating the TracingPolicy to use the function in `core-tracing` which handles this correctly.

[core-http] fixes traceparent header generation

---

sdk/storage/storage-blob/src/BatchRequest.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/src/utils/constants.ts

so they can be customized for different Azure stacks.
Resolves #5097.

[Storage] Export storage OAuth scopes

---

sdk/identity/identity/src/client/identityClient.ts

A very small PR to add the TracingPolicy from core-http into IdentityClient.

Add TracingPolicy to IdentityClient

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/lib/responseBodyNotFoundError.ts
sdk/core/core-http/test/errorTests.ts

ResponseBodyNotFoundError can be used by applications to indicate that the response body is empty. 
Used (currently) in AppConfig to indicate when a request has no body which can potentially be actionable by a user.

[core-http] Creating a new Error type for signaling when a response body is empty (ResponseBodyNotFoundError)

---

sdk/core/core-http/rollup.config.ts
sdk/core/core-tracing/package.json

This change fixes `core-http`'s browser bundle which started picking up Node-specific code after PR #5207.  The issue was actually caused by a combination of `core-tracing`'s `browser` configuration and `core-http`'s Rollup `nodeResolve` configuration, meaning that the wrong file was being pulled from `core-tracing` when `core-http`'s browser bundle was created.
The fix is to correct the `browser` path mapping for `core-tracing` and remove the `main` entrypoint from `core-http`'s `nodeResolve` configuration.

[core-http] Fix broken browser bundle due to Rollup config

---

sdk/storage/storage-queue/src/MessageIdClient.ts
sdk/storage/storage-queue/src/MessagesClient.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/StorageClient.ts
sdk/storage/storage-queue/src/utils/utils.common.ts

Adds 
- messageId, queueName on MessageIdClient 
- queueName on MessagesClient 
- queueName on QueueClient
- accountName on StorageClient
- and the code to parse them from the URL

[Storage] Add name properties on clients - storage-queue

---

eng/tools/rush-runner.js
sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/samples/helloWorld.ts

From docs: https://nodejs.org/docs/latest-v10.x/api/child_process.html#child_process_child_process_spawnsync_command_args_options
``` 
status <number> | <null> The exit code of the subprocess, or null if the subprocess terminated due to a signal.
```
Status is a `number` or `null` so I used `!==`

rush-runner.js: exit with failing status code on failures

---

sdk/storage/storage-file/package.json
sdk/storage/storage-file/recordings/browsers/directoryclient/recording_createfile_and_deletefile_with_tracing.json
sdk/storage/storage-file/recordings/browsers/fileclient/recording_create_with_tracing.json
sdk/storage/storage-file/recordings/node/directoryclient/recording_createfile_and_deletefile_with_tracing.js
sdk/storage/storage-file/recordings/node/fileclient/recording_create_with_tracing.js
sdk/storage/storage-file/rollup.base.config.js
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-file/src/ShareClient.ts
sdk/storage/storage-file/src/StorageClient.ts
sdk/storage/storage-file/src/utils/tracing.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts

This PR adds a dependency on @azure/core-tracing and makes it possible to pass a parent `Span` to public facing operations.
Also included are a couple small tests that validate Spans are being created properly.

Add tracing to storage-file

---

sdk/test-utils/recorder/README.md
sdk/test-utils/recorder/src/baseRecorder.ts
sdk/test-utils/recorder/src/index.ts

This is just a proposal! Let's review it and make it better together <3
Fixes #4961

[Common Recorder] Updated README

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-arm/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-paging/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/template/template/package.json

Now including `rush update` results for working ci build pipelines. 
(please ignore the `- tests` failures, those pipelines were triggered by too broad of an /azp run command)

Version Bump after September Preview

---

sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/recordings/browsers/queueclient/recording_getproperties_with_tracing.json
sdk/storage/storage-queue/recordings/node/queueclient/recording_getproperties_with_tracing.js
sdk/storage/storage-queue/rollup.base.config.js
sdk/storage/storage-queue/src/MessageIdClient.ts
sdk/storage/storage-queue/src/MessagesClient.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/StorageClient.ts
sdk/storage/storage-queue/src/utils/tracing.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

This PR adds a dependency on @azure/core-tracing and makes it possible to pass a parent Span to public facing operations.

Add tracing to storage-queue

---

sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/rollup.config.ts
sdk/core/core-http/test/policies/tracingPolicyTests.ts
sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/util/tracing.ts
sdk/identity/identity/test/node/authorizationCodeCredential.spec.ts
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/index.ts

Currently we have an issue where core-http is re-exporting a private copy of core-tracing for node, which causes spans to not get created on the proper tracer.
This PR fixes this issue by correctly configuring rollup, which eliminates the need to re-export core-tracing types. The other changes in this PR are having other packages now correctly depend on core-tracing instead of consuming it via core-http.

Fix core-tracing duplication

---

sdk/core/core-http/lib/webResource.ts

PR #5047 fixed the issue where `proxySettings` and `keepAlive` are not passed to
the clone. However, this change surfaced a new issue where we always create new
agents (proxy agent or keepAlive agent) when sending requests. In the keepAlive
case it leads to increased memory usage since GC cannot recycle agents until
timeout expires.
This is a temporary workaround for the memory leak issue. We need a proper
design to fix the root issue.

[core-http] undo change to pass keepAlive to clone()

---

sdk/identity/identity/src/client/errors.ts
sdk/identity/identity/test/errors.spec.ts

This change improves the exception message for `AggregateAuthenticationError` by including the messages from the inner exceptions in its message.  This improves clarity for a user who receives an exception from the `DefaultAzureCredential`.
Fixes #5275.

[Identity] Include inner error messages in AggregateAuthenticationError message

---

sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/tracingHelpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/tracingHelpers.spec.ts

Some changes, mostly just refactoring.
One thing I discovered as I was doing this was that (not sure why) the listConfigurationSettingsOptions and listRevisionsOptions weren't exposing inherited properties from RequestOptionsBase (and thus I couldn't add the spanOptions). 
I fixed this by just flattening them out into their own classes which appears to have solved it and was going to happen anyways since I need to do something similar to improve doc generation.

[app-configuration] Adding distributed tracing

---

sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts

This change fixes an issue in `DeviceCodeCredential` where an unexpected `AuthenticationError` response would not break the polling loop, causing the loop to poll indefinitely.  I ran across this issue because I was trying to authenticate with an AAD App Registration that was not configured as a "public client" so an `invalid_client` error was being returned.  The error-checking switch statement was not looking for this specific error type nor did it have a `default` case, so the error was ignored.
The fix is to add a `default` case which rethrows any error type that we aren't explicitly checking for.

[Identity] Rethrow AuthenticationErrors in DeviceCodeCredential poll loop

---

sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/containerclient.spec.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

Adds the TracingPolicy from core-http so that we trace all HTTP requests made by the storage client.

Trace storage http requests

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/tslint.json

This PR makes the lint step mandatory and will be executed as part of the build step.
This is just to make sure that we don't ship any regressions.
Currently, for the packages in this repo, "eslint" step generates a errors/failures report but the build doesn't fail.
Once the lint step("eslint") is made mandatory in this repo, the change from this PR will be reverted.

[Cosmos] Retain the old lint step temporarily

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/helloworld.ts
sdk/appconfiguration/app-configuration/samples/helloworldWithLabels.ts
sdk/appconfiguration/app-configuration/samples/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/samples/setReadOnlySample.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/test/throwOrNotThrow.spec.ts
sdk/appconfiguration/app-configuration/typedoc.json

This PR fixes a few issues that would hamper release for preview.4:
1. Removed usages of Pick or type aliasing which were causing typedoc to have issues with discovering and documenting our types. Mostly, I just merged models together and used inheritance which does seem to work consistently.
2. The API surface was inconsistent with two function s- Get and Delete didn't take a ConfigurationSettingId as a parameter which meant they operated differently than everything else. Found this as I was merging models together.

[app-configuration] Fixing contracts for typedoc and inconsistency with exposed APIs

---

sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/samples/backupAndRestore.ts
sdk/keyvault/keyvault-certificates/samples/contacts.ts
sdk/keyvault/keyvault-certificates/samples/helloWorld.ts
sdk/keyvault/keyvault-certificates/samples/issuers.ts
sdk/keyvault/keyvault-certificates/samples/operations.ts
sdk/keyvault/keyvault-certificates/tsconfig.samples.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/samples/helloWorld.ts
sdk/keyvault/keyvault-keys/tsconfig.samples.json
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/samples/backupAndRestore.ts
sdk/keyvault/keyvault-secrets/samples/challenge.ts
sdk/keyvault/keyvault-secrets/samples/helloWorld.ts
sdk/keyvault/keyvault-secrets/tsconfig.samples.json

Jonathan found that some of the samples have issues. Here's a PR fixing them.
Since this is only in the samples, perhaps this doesn't affect the current release build?
Fixes #5444

[KeyVault] Addressed feedback on samples

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/queryExecutionContext/defaultQueryExecutionContext.ts
sdk/cosmosdb/cosmos/src/queryMetrics/clientSideMetrics.ts
sdk/cosmosdb/cosmos/src/request/RequestHandler.ts
sdk/cosmosdb/cosmos/src/retry/retryUtility.ts

There are 2 circular dependency problems
Problem: `RequestHandler.execute` calls `retryUtitlity.execute` to retry the request if there is an error. However `RetryUtility.execute` calls `RequestHandler.executeRequest` causing the circular dependency
There are a few options to fix this:
a) Move retryUtility.execute to RequestHandler
b) Have pass executeRequest to retryUtility.execute as a parameter
c)  Move executeRequest to retryUtility
I think option **(b)** would be preferable because it would provide flexibility of passing any other request to be retried if needed, without a hard dependency on RequestHandler
@ramya-rao-a , @southpolesteve, @HarshaNalluru  - What do you think? Do you have any other options in mind?
Problem: `headerUtils.getInitialHeader` uses `queryMetrics.zero` which …

Fix circular dependencies in @azure/cosmos

---

sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json

As part of #5472 we have to release Event Hubs.
This PR makes the update in constants.ts file to keep the version in sync.
Also updates the checkpoint store accordingly

Update version of Event Hubs as part of release prep

---

sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/util/delay.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

This PR improves the runtime of Identity unit tests by avoiding waiting real-world clock time when testing code that uses delays, such as polling for token updates. 
On my Surface Laptop this took the runtime from 26s to 113ms
This is accomplished by replacing the use of core-http's simple `delay` function with one that is able to be mocked for testing.

Make identity tests run 230x faster

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/rollup.config.js
sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/OrderedDistinctEndpointComponent.ts
sdk/cosmosdb/cosmos/src/queryExecutionContext/EndpointComponent/UnorderedDistinctEndpointComponent.ts
sdk/cosmosdb/cosmos/src/utils/digest.browser.ts
sdk/cosmosdb/cosmos/src/utils/digest.ts
sdk/cosmosdb/cosmos/src/utils/encode.ts

Addresses problem 1) discussed in #5023, fixing Cosmos in Edge.
This PR is changes the hashing algorithm previously used `SHA1` fro `SHA256` which is supported by Edge and all other browsers. Also removing the dependency on `crypto-hash`

[Cosmos] Use local digest instead of crypto-hash

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/rollup.config.js
sdk/cosmosdb/cosmos/src/auth.ts
sdk/cosmosdb/cosmos/src/utils/encode.ts
sdk/cosmosdb/cosmos/src/utils/headers.ts
sdk/cosmosdb/cosmos/src/utils/hmac.browser.ts
sdk/cosmosdb/cosmos/src/utils/hmac.ts

Addresses problem **(2)** discussed in #5023.
Dropping dependency on @azure/cosmos-sign which depends on crypto-js in favor of signing locally using node/browser crypto libraries.

[Cosmos] Sign headers locally 

---

sdk/storage/storage-queue/README.md

Current link for product documentation points to .net sdk usage

[Storage] Fix product doc link for storage queues

---

sdk/keyvault/keyvault-certificates/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-keys/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-secrets/src/core/challengeBasedAuthenticationPolicy.ts

This PR fixes an issue reported in #5021 which states that the `ChallengeBasedAuthenticationPolicy` is authenticating with AAD for every request to the KeyVault service instead of reusing the original access token that it received.  The fix is to use a similar approach to PR #4174 and store the token cache externally because `RequestPolicy` instances get recreated for each request in `core-http`.
The changes for all 3 file are identical because this class is currently duplicated across the `@azure/keyvault-*` libraries.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/5021.

[KeyVault] Externalize ChallengeBasedAuthenticationPolicy token cache

---

sdk/core/core-tracing/lib/tracerProxy.ts
sdk/core/core-tracing/lib/utils/cache.ts
sdk/core/core-tracing/lib/utils/global.browser.ts
sdk/core/core-tracing/lib/utils/global.ts
sdk/core/core-tracing/package.json

Recently we've dealt with the pain of versioning core-tracing consistently across package versions, since the global Tracer for the SDK was stored inside the module scope.
This PR removes the strict versioning requirement by instead introducing global variables accessed through a unique Symbol. This does require a Symbol polyfill for downlevel usage, but this was already required in other places (e.g. for asyncIterator.)

[core-tracing] Store Tracer globally instead of in module scope

---

sdk/core/core-auth/package.json
sdk/core/core-auth/review/core-auth.api.md
sdk/core/core-auth/src/tokenCredential.ts
sdk/core/core-http/lib/policies/bearerTokenAuthenticationPolicy.ts
sdk/core/core-http/test/policies/bearerTokenAuthenticationPolicyTests.ts

This PR is a small change to pass along SpanOptions on a WebRequest from a service library to Identity when it makes a getToken() call for a particular credential type.
I also added some typing information to core-auth to correctly type SpanOptions.
The rest is all whitespace changes from prettier. :)
**Merge *after* Preview 4 release**

Pass SpanOptions to getToken

---

sdk/core/core-http/lib/nodeFetchHttpClient.ts

Fixes the [same issue](https://github.com/Azure/ms-rest-js/issues/373) as in `@azure/ms-rest-js` when using webpack to bundle a server-side node project.

Fix node-fetch require for webpack

---

sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/generated/src/appConfigurationContext.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/samples.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/test/throwOrNotThrow.spec.ts

Two changes, both to align with the pending [design guideline changes](https://github.com/Azure/azure-sdk/pull/646) concerning specifying etags and how we handle 204/304 responses.
ETags are now extracted from the passed in model, rather than requiring them to be passed in via ifMatch/ifNoneMatch flags - we now provide onlyIfUnchanged and onlyIfChanged which are booleans, rather than strings.
HTTP 204/304 handling ("valid" responses but with empty response bodies) are now handled by:
* Adding a top level statusCode field for get and delete's responses
* Setting all the fields (aside from _response and statusCode) 
Also, updated the http status code 204 and 304 handling in getConfigurationSetting and deleteConfigurationSetting, which

[app-configuration] Bring etag and HTTP status code 204/304 handling in line with latest design guidelines

---

sdk/eventhub/eventhubs-checkpointstore-blob/src/blobPartitionManager.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-partition-manager.spec.ts

Makes the blob storage always use the same casing for the consumer group and other fields that are also not case-sensitive. Without this you'll get incorrect/inconsistent checkpointing depending on what casing the user passed in (very bad).

[event-hubs] Make blob storage casing consistent

---

sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts

As part of our final etag discussion we decided that deleteConfigurationSetting should just return the HTTP response but _not_ a model object. 
This simplifies things in a nice way - it's no longer ambiguous what the return value is for delete and they can still check the HTTP response if they need it.

[app-configuration] Delete returns a response, not a ConfigurationSetting

---

sdk/storage/storage-blob/src/generated/src/models/containerMappers.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/containerclient.spec.ts
sdk/storage/storage-blob/test/utils/testutils.common.ts

Addressing #5521 
By removing the `encrypted` property through autorest `BlobMetadata` becomes a simple dictionary
Note: Files under the `generated` folder were generated with autorest

Blob remove encrypted property from BlobMetadata

---

sdk/storage/storage-file/samples/typescript/advanced.ts
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/FileDownloadResponse.ts
sdk/storage/storage-file/src/FileServiceClient.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-file/src/SASQueryParameters.ts
sdk/storage/storage-file/src/ShareClient.ts
sdk/storage/storage-file/src/generated/src/models/index.ts
sdk/storage/storage-file/src/generated/src/models/mappers.ts
sdk/storage/storage-file/src/generated/src/models/parameters.ts
sdk/storage/storage-file/src/generated/src/operations/directory.ts
sdk/storage/storage-file/src/generated/src/operations/file.ts
sdk/storage/storage-file/src/generated/src/operations/service.ts
sdk/storage/storage-file/src/generated/src/operations/share.ts
sdk/storage/storage-file/src/models.ts
sdk/storage/storage-file/src/policies/LoggingPolicy.ts
sdk/storage/storage-file/src/utils/BufferScheduler.ts
sdk/storage/storage-file/src/utils/constants.ts
sdk/storage/storage-file/swagger/README.md
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-file/test/fileserviceclient.spec.ts
sdk/storage/storage-file/test/node/highlevel.node.spec.ts
sdk/storage/storage-file/test/node/sas.spec.ts
sdk/storage/storage-file/test/node/shareclient.spec.ts
sdk/storage/storage-file/test/utils/index.ts

Addresses File parts of #5553
Note: Files under the `generated` folder were generated with autorest

[Storage][File] Various renames from API review

---

sdk/storage/storage-queue/src/QueueClient.ts

This PR attempts to rename options & responses as per https://github.com/Azure/azure-sdk-for-js/issues/5590#issuecomment-542985484

[Storage Queues] Rename options & responses as per method names

---

sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClient.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/swagger/README.md

The parameter was missing the x-ms-parameter-location properties, which leads to
incorrect code generated in our storageClientContext.ts. Among them `import * as
Models ...` which blocks our api review report generation.
This change adds the missing "x-ms-parameter-location": "method".

[Storage][Blob] Add missing x-ms-parameter-location for PathRenameMode

---

sdk/core/core-http/lib/policies/logPolicy.ts

Bringing us into alignment with .NET as of PR https://github.com/Azure/azure-sdk-for-net/pull/8166.  I'm also adding `api-version` to whitelisted query params because it seems like we'd care to know that in any case.

[core-http] Update default whitelisted headers and query params

---

sdk/storage/storage-blob/src/BlobClient.ts

This PR updates the downloadToBuffer() method to return buffer instead of void as per #5463

[Storage] Update downloadToBuffer to return buffer

---

sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlockBlobClient.ts
sdk/storage/storage-file/src/FileClient.ts

When the high-level functions were moved into clients, their options type name
were not updated. This change renames them to be consistent with other options
types.
Resolves #5648

[Storage] Rename options types to be consistent

---

sdk/core/core-http/Changelog.md
sdk/core/core-http/lib/fetchHttpClient.ts

Fixes #5631 
The root cause of the issue is that core-http was not removing abort event listeners from the user's abortSignal after requests completed. If a user uses the same abortSignal for multiple operations, memory use will gradually increase. An event listener is added because core-http creates its own abortController that gets passed to the http client (to implement timeouts) and it needs to be triggered if the user's abortSignal is triggered.
Since the listener is only meant to trigger the AbortController that's created for the actual http request, it's safe to remove once the response is completed.
I tested against the code provided in the linked issue. Prior to this change, I could see linear growth in memory usage. After this change memory usage stabilizes and the garbage …

[core-http] fixes abortSignal memory leak

---

sdk/core/ci.yml
sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/testClient.test.ts

This fixes an issue that can occur where:
1. poller.poll is called and throws an error
2. poller.pollUntilDone is not called, or does not have a .catch handler attached
In this scenario, an UnhandledPromiseRejectionWarning was being thrown. This happened because poller.poll would call `this.reject` which rejected the promise returned by `poller.pollUntilDone`. This was being done to essentially cache the rejected promise in case `pollUntilDone` was called, but no error handler was being attached to that promise otherwise.

[core-lro] fixes UnhandledPromiseRejectionWarning 

---

sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/test/throwOrNotThrow.spec.ts

As part of the initial design review we renamed the methods that lock and unlock a value to setReadOnly/clearReadOnly. 
This PR goes through and also renames the locked field anywhere else it could show up - the ConfigurationSetting model (and all the derivatives that are used for responses) and when specifying filters for list(Revisions|ConfigurationSettings).

[app-configuration] Fixing inconsistencies found during peer review

---

sdk/core/core-arm/lib/lroPollStrategy.ts
sdk/core/core-http/lib/policies/deserializationPolicy.ts
sdk/core/core-http/lib/restError.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts

Per recent conversation with @ramya-rao-a I am removing the body field from RestError Object in core-http Library. If required, this can be read from the response object. 
Additional details:
With https://github.com/Azure/azure-sdk-for-js/pull/5437, 
- the `response` property on the error will now have the parsed body & headers along with raw body & headers that it already had. 
- the `details` property on the error will have the shape/data model as defined in swagger for errors
With these changes, the `body` property on the `RestError` itself becomes redundant.

Remove body field from RestError Object in core-http Library

---

sdk/core/core-http/lib/fetchHttpClient.ts
sdk/core/core-http/lib/restError.ts
sdk/core/core-http/lib/xhrHttpClient.ts
sdk/core/core-http/test/defaultHttpClientTests.ts
sdk/core/core-lro/test/abort.test.ts
sdk/core/core-lro/test/utils/testServiceClient.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-secrets/test/CRUD.test.ts
sdk/storage/storage-blob/src/policies/RetryPolicy.ts
sdk/storage/storage-blob/src/utils/RetriableReadableStream.ts
sdk/storage/storage-blob/test/aborter.spec.ts
sdk/storage/storage-blob/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/policies/RetryPolicy.ts
sdk/storage/storage-file/src/utils/RetriableReadableStream.ts
sdk/storage/storage-file/test/aborter.spec.ts
sdk/storage/storage-file/test/node/highlevel.node.spec.ts
sdk/storage/storage-queue/src/policies/RetryPolicy.ts
sdk/storage/storage-queue/test/aborter.spec.ts

Fixes #5659 
This puts us in accordance with our guidelines. See the linked issue for more details.

[core-http] throw AbortError on request cancellation

---

sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/node/sas.spec.ts
sdk/storage/storage-file/src/DirectoryClient.ts
sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-file/test/fileclient.spec.ts
sdk/storage/storage-file/test/node/sas.spec.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/test/messageidclient.spec.ts
sdk/storage/storage-queue/test/messagesclient.spec.ts
sdk/storage/storage-queue/test/node/messageidclient.spec.ts
sdk/storage/storage-queue/test/node/sas.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts

This PR renames the properties on the DirectoryClient, FileClient and QueueClient  as per #5568

[Storage] Standardize name and path usage in clients

---

sdk/storage/storage-blob/test/node/emulator-tests.spec.ts
sdk/storage/storage-queue/test/node/emulator-tests.spec.ts

Not sure why the build didn't fail at #5613

[Storage] Fix build failures caused by the left over old references after #5613

---

sdk/storage/storage-file/src/FileClient.ts
sdk/storage/storage-file/src/generatedModels.ts

for consistency with Blob.
In PR #5672 we adopted the field names `conditions` and `sourceConditions`.
This change fixes the only place in File where `SourceModifiedAccessConditions`
is used in public API to be consistent.

[Storage][File] use sourceConditions field name in public API

---

sdk/core/core-lro/src/pollOperation.ts
sdk/core/core-lro/src/poller.ts
sdk/core/core-lro/test/testClient.test.ts
sdk/core/core-lro/test/utils/testOperation.ts
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/test/lro.delete.test.ts
sdk/keyvault/keyvault-keys/test/lro.recoverDelete.test.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/test/lro.delete.test.ts
sdk/keyvault/keyvault-secrets/test/lro.recover.test.ts

Based on feedback from @bterlson, this minor rename PR prefixes a few boolean properties of `PollerOperationState` with `is`.
This aligns them with `isStopped` and `isDone` on the poller itself.

[core-lro] Change PollerOperationState to prefix boolean states with `is`

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/operations/appendBlob.ts
sdk/storage/storage-blob/src/generated/src/operations/blob.ts
sdk/storage/storage-blob/src/generated/src/operations/blockBlob.ts
sdk/storage/storage-blob/src/generated/src/operations/container.ts
sdk/storage/storage-blob/src/generated/src/operations/directory.ts
sdk/storage/storage-blob/src/generated/src/operations/pageBlob.ts
sdk/storage/storage-blob/src/generated/src/operations/service.ts
sdk/storage/storage-blob/test/appendblobclient.spec.ts
sdk/storage/storage-file/package.json
sdk/storage/storage-file/src/generated/src/operations/directory.ts
sdk/storage/storage-file/src/generated/src/operations/file.ts
sdk/storage/storage-file/src/generated/src/operations/service.ts
sdk/storage/storage-file/src/generated/src/operations/share.ts
sdk/storage/storage-file/test/directoryclient.spec.ts
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/operations/messageId.ts
sdk/storage/storage-queue/src/generated/src/operations/messages.ts
sdk/storage/storage-queue/src/generated/src/operations/queue.ts
sdk/storage/storage-queue/src/generated/src/operations/service.ts
sdk/storage/storage-queue/test/queueserviceclient.spec.ts

Regenerating autorest with @microsoft.azure/autorest.typescript@5.0.1

[Storage] Re-generate autorest with version 5.0.1

---

sdk/core/core-amqp/changelog.md
sdk/core/core-arm/Changelog.md
sdk/core/core-auth/Changelog.md
sdk/core/core-http/Changelog.md
sdk/core/core-lro/CHANGELOG.md
sdk/core/core-tracing/Changelog.md
sdk/core/logger/Changelog.md

[core] update changelogs

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/samples/javascript/cryptography.js
sdk/keyvault/keyvault-keys/samples/javascript/helloWorld.js
sdk/keyvault/keyvault-keys/samples/typescript/cryptography.ts
sdk/keyvault/keyvault-keys/samples/typescript/helloWorld.ts
sdk/keyvault/keyvault-keys/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/poller.ts
sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-keys/test/crypto.test.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-keys/test/lro.delete.test.ts
sdk/keyvault/keyvault-keys/test/lro.recoverDelete.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts

For #5577
Fixes:
- Key to KeyVaultKey
- Key.KeyMaterial to KeyVaultKey.Key
- Core version to preview.9
- All dates should end in "On", except for "notBefore" and "scheduledPurgedDate".
- All options should match the method's name.
- All methods that return keyProperties (like the ones that iterate) should contain "propertiesOf" in their names.
- Flattened all the options bag to extend the RequestOptionsBase interface.
Note:
- ~.Net API apparently doesn't have a method that list the "properties of" the deleted keys. They have "GetDeletedKeys", however, I couldn't use the result of the underlying operation to reconstruct the key. Seems like the underlying operation is returning key properties, not keys. If so, we might need to change that on the .Net API.~ "GetDeletedKeys" should iterate …

[keyvault-keys] API changes

---

sdk/storage/README.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-blob/samples/browserSamples/basic.html
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/README.md
sdk/storage/storage-file/karma.conf.js
sdk/storage/storage-file/samples/browserSample.html
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/karma.conf.js
sdk/storage/storage-queue/samples/browserSample.html

In the core-logger package, debug shim uses `Object.assign` which is incompatible with IE11
Introduced here - https://github.com/Azure/azure-sdk-for-js/blob/5297357da043fd539b5053c99ddc49e18394ae5e/sdk/core/logger/src/debug.ts#L133
Updating the polyfill wiith `Object.assign` fixes the issue. Thanks to @chradek, for suggesting the fix.
**BLOB - IE** 
**FILE - IE**
(Failed test - Known Issue - IE behavior)
**QUEUE - IE**

[Storage] Update polyfill to fix the failed browser tests in IE

---

README.md
sdk/storage/README.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/samples/browserSamples/basic.html
sdk/storage/storage-blob/samples/browserSamples/largeFileUploads.html
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/README.md
sdk/storage/storage-file/samples/browserSample.html
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/README.md
sdk/storage/storage-queue/samples/browserSample.html

This PR updates old links pointing to the feature/storage branch to use master instead as we have now merged feature/storage branch to master

Replace feature/storage with master in README files

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/node/authorizationCodeCredential.spec.ts
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts

This change updates `IdentityClientOptions` to be based on `PipelineOptions` instead of `ServiceClientOptions`.  The change went very smoothly; the majority of changes were adding expected trace spans for `core-http` since the `tracingPolicy` wasn't being added to the pipeline in tests before this commit.

[Identity] Change base type of IdentityClientOptions to PipelineOptions

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventHubReceiver.ts

/cc @ramya-rao-a 
The SDK doesn't currently catch errors that might be thrown by user-provided message handlers. We were seeing an issue where these errors caused receivers to disconnect and create new receivers. In extreme cases this would lead to OperationTimeoutErrors.
This change wraps the user-provided handler in a try/catch and logs any error it catches.
Note: This fix is for the stable version of the SDK, not the preview.

[event hubs] catch errors thrown from user-handlers

---

sdk/eventhub/event-hubs/package.json

In #5520, we made an update to amqp-common which was not required to fix the bug at hand.
This PR reverts that change to keep the next changes minimal and to keep rush happy as it cannot handle version mismatches (service bus uses version 5 of amqp-common in that branch)

Revert amqp-common update

---

sdk/core/core-http/lib/coreHttp.ts
sdk/core/core-http/lib/pipelineOptions.ts
sdk/core/core-http/lib/policies/logPolicy.ts
sdk/core/core-http/lib/serviceClient.ts
sdk/core/core-http/test/logFilterTests.ts

* Don't clone the log function with .bind(), since we later check `logger.enabled`
* Minor refactor to have `logPolicy` take `LoggingOptions` directly.
* Tighten some typings.
* Prettier did some minor formatting cleanup
Fixes #5744

Fix log issue in core-http

---

sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts

This PR creates 2 new clients for sending & receiving
- EventHubProducerClient
- supports only the batch scenario as discussed in one of the review meetings
- EventHubConsumerClient
- supports only single partition scenario for now. Future PRs will tweak the API to support multi partitions & update the return type as well
This is intended to be the starting point for rest of the refactoring work and is done in a way that doesn't change the existing EventHubClient.

[Event Hubs] Initial attempt to split EventHubClient

---

sdk/core/core-http/lib/policies/logPolicy.ts
sdk/core/core-http/test/logFilterTests.ts

This change fixes an issue I found while working on PR https://github.com/Azure/azure-sdk-for-js/pull/5636 where the casing of allowed header names and query parameters affected whether `logPolicy` actually allowed them through in the sanitization phase.  In other words, a header name cased as `Accept` would not be considered the same as the `accept` that shows up in the actual headers object in the `WebResource`.
For example, here's a snippet from `@azure/storage-file` logs before this change (pay attention to `date` and `etag` headers):
```
azure:storage-file:info Headers: {
"_headersMap": {
"content-length": "REDACTED",
"date": "REDACTED",
"etag": "REDACTED",
"last-modified": "REDACTED",
"server": "REDACTED",
"x-ms-client-request-id": "7ae3e068-1c2f-42da-8196-90e51755a5a2", …
```

[core-http] Normalize casing of allowed headers and query params

---

sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-file/src/Pipeline.ts
sdk/storage/storage-queue/src/Pipeline.ts

#5751 changed the `LogPolicy` to accept a single parameter instead of 2. The logger is now part of the options passed into the policy, rather than a separate param.

[storage] fix logging policy

---

sdk/storage/storage-blob/src/BlobServiceClient.ts

Related to #5716
It seems like we are getting containerItems as an empty string rather than as empty array as [defined in the types](https://github.com/Azure/azure-sdk-for-js/blob/0b10e832d87807d7d0a58dcbb1b57b819417a2ea/sdk/storage/storage-blob/src/generated/src/models/index.ts#L314)
We seem to be getting the string from a layer below us, since there is no manipulation on our side. I'm investigating where the empty string is actually coming from and if there is a better way to handle this. Meanwhile this is a potential fix on our side. This fix will probably need to be replicated in queue and add tests to cover this scenario
@HarshaNalluru, @jeremymeng , @ramya-rao-a  any thoughts?

[Storage][Blob] Containeritems empty

---

sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/swagger/README.md

Fixes #5177
Update comment for Content-Type through autorest to align with [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob)

[Storage][Blob] Fix comment on BlobGetPropertiesHeaders.contentLength

---

sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-file/ChangeLog.md
sdk/storage/storage-file/src/utils/utils.node.ts

- shimming in browsers in rollup config wasn't enough for fs.stat 
- utils.node.js file is being loaded in the browser for react apps (dist-esm folder is getting loaded for the react-app as opposed to the browser bundle)
- **utils.node.js** file is being loaded in the browser for react apps
- Error -  `fs.stat` is not allowed in the browser
- Usage of `fs.stat` in **utils.node.js** file
This PR comes up with a simple fix to leverage `fs.stat` only in the node environment.
```typescript
util.promisify(isNode ? fs.stat : function stat() {})
```
After this fix, 
- `@azure/storage-file` library works fine in the react-app.
- `@azure/storage-blob` library has circular dependencies which break the react-app(fixing that in a separate PR),
- `@azure/storage-queue` library doesn't have this issue. …

[Storage] `fs.stat` works only in node environment

---

sdk/identity/identity/README.md

[identity] Fixed README references to keyvault-keys API methods

---

sdk/core/core-http/lib/operationOptions.ts
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/src/index.ts

In order to make it more obvious that `SpanOptions` is about tracing, this change moves it under a new `tracing` property bag inside `OperationOptions`. This will also allow us to add additional tracing-related properties in the future that are not part of `SpanOptions`, which is defined by OpenTelemetry.
Fixes #5755

Move SpanOptions inside OperationOptions

---

sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts

This adds support for loading the client certificate credential from a path given in the environment (AZURE_CLIENT_CERTIFICATE_PATH) as well as using the username/password given in the environment (AZURE_USERNAME / AZURE_PASSWORD).
Part of the implementation for https://github.com/Azure/azure-sdk-for-js/issues/5696.

Respect env certificate and user/pw

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.browser.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.browser.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.browser.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.browser.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.browser.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts
sdk/identity/identity/src/index.ts
sdk/identity/identity/test/authTestUtils.ts
sdk/identity/identity/test/clientSecretCredential.spec.ts
sdk/identity/identity/test/identityClient.spec.ts
sdk/identity/identity/test/node/authorizationCodeCredential.spec.ts
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/deviceCodeCredential.spec.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts
sdk/identity/identity/test/usernamePasswordCredential.spec.ts

Renamed IdentityClientOptions->TokenCredentialOptions

---

sdk/core/core-http/lib/pipelineOptions.ts
sdk/core/core-http/lib/serviceClient.ts

This change removes `updatePipelinePolicies` from `PipelineOptions` as it is no longer needed since the Storage libraries will not adopt `PipelineOptions` verbatim before GA.  Removing it now gives us more time to design a better pipeline customization API for `PipelineOptions`.

[core-http] Remove PipelineOptions.updatePipelinePolicies

---

sdk/eventhub/eventhubs-checkpointstore-blob/package.json

https://github.com/Azure/azure-sdk-for-js/pull/5824#discussion_r339172201
/cc - @chradek (Close this PR if there is a valid reason to not use caret `^` for this dependency)

[checkpointstore-blob] update dependency version with a caret `^`

---

eng/pipelines/doc-index.yml

This will enable the default landing page of the docs to be `/` or `/index.html` instead of `/api/index.html`

add steps for mashup index

---

sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-keys/test/lro.delete.test.ts
sdk/keyvault/keyvault-keys/test/lro.recoverDelete.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-keys/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-keys/test/utils/testClient.ts
sdk/keyvault/keyvault-secrets/test/CRUD.test.ts
sdk/keyvault/keyvault-secrets/test/list.test.ts
sdk/keyvault/keyvault-secrets/test/lro.delete.test.ts
sdk/keyvault/keyvault-secrets/test/lro.recover.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-secrets/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-secrets/test/utils/testClient.ts
sdk/storage/storage-blob/test/blobclientpollers.spec.ts
sdk/storage/storage-blob/test/utils/recorder.ts

The fix is to pass this in each test call: https://github.com/Azure/azure-sdk-for-js/pull/5836/files#diff-b3ce67ba95f6d817b36c629e38d5f3b5R25
Not sure how I forgot to add this from the beginning!
Is there an issue for this?

Poller implementations: Instant playback

---

sdk/keyvault/keyvault-keys/test/utils/recorderUtils.ts
sdk/keyvault/keyvault-secrets/test/utils/recorderUtils.ts
sdk/storage/storage-blob/test/blobclientpollers.spec.ts
sdk/storage/storage-blob/test/utils/recorder.ts

2 of the storage blob tests were failing _most_ of the time when running live against the service.
Both were related to the `beginCopyFromURL` poller.
1 failure occurred when trying to abort a copy, and the other when trying to listen to copy progress events.
In both cases, if the initial `startCopyFromURL` request returned with a success copy status, then the tests would fail. This is because
1. A copy can't be aborted once it has been completed.
2. There are no progress events if the copy completes 'immediately'.
Because we can't determine how long it will take the service to perform the copy, both tests have been updated to only run in `playback` mode using recorded service responses. This allows us to test that the poller behavior is correct, without having to rely on the speed of the …

[storage-blob][keyvault] fixes record & playback issues with some pollers

---

sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-secrets/test/CRUD.test.ts
sdk/keyvault/keyvault-secrets/test/list.test.ts
sdk/keyvault/keyvault-secrets/test/lro.delete.test.ts
sdk/keyvault/keyvault-secrets/test/lro.recover.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts

Fixes #5846
Fixes #5849
recorder.skip doesn't work if TEST_MODE is not set.
The tests being skipped in this PR in browser mode are due to https://github.com/Azure/azure-sdk-for-js/issues/5747
The tests are skipped in playback mode because the http requests take no time to respond, so timeout does not work.

[KeyVault] Fix failures for live tests around timeout when run in browser mode

---

sdk/storage/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

[Storage] Remove outdated instruction to download bundle

---

sdk/storage/storage-file-share/README.md

With #5705 we renamed the `@azure/storage-file` package to `@azure/storage-file-share`
This PR is to add a note in the readme alluding to this change.
Also, found some stale references in the code samples, so fixed them too.
@XiaoningLiu, @jiacfan, 
I have refrained from touching any words that begin with `Azure File` as that might be referring to the service. If such occurrences need to be updated, please do so in a separate PR after this PR is merged
Fixes #5769

[Storage File] Add note on package rename in readme

---

sdk/storage/storage-blob/package.json

`fs` isn't required in the browser, but webpack will complain about the missing export. This change ensures webpack will not complain and bundle without error out-of-the-box.

[Storage] [Blob] add fs: false to storage-blob package.json browser mapping

---

sdk/appconfiguration/app-configuration/README.md
sdk/eventhub/event-hubs/README.md
sdk/keyvault/keyvault-certificates/README.md

Partially addresses #5823
Changes to READMEs for app-configuration, event-hubs, and keyvault-certificates:
- Changed ES6-style import statements to CommonJS require statements with object destructuring in inline samples.
- Re-ordered some sections to be consistent across packages (especially "Contributing" and "Getting Started"
- Added code to inline samples to make them theoretically runnable (though I haven't tested them all as there are too many and they require resources in Azure to test)
- Wrapped `await` statements in an async function so that they can run
- added module imports and relevant declarations to the top of inline samples
#5823 also suggests to make "Deploy in Azure" buttons open their pages in a new tab, but this isn't possible on GitHub.

README samples and standards for app-configuration, event-hubs, and keyvault-certificates

---

sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json

After talking though the changes in https://github.com/Azure/azure-sdk-for-js/pull/5860 with @Petermarcu, we became uncomfortable shipping browser bundles for any package for GA. We will be bringing them back when we have better plans in place for the following issues:
1. Keeping ThirdPartyNotices.txt up-to-date without requiring manually combing through bundles every time we ship a package.
2. An explicit servicing plan should a security issue arise anywhere in the bundled dependency graph
3. A strategy for ensuring users don't consider using these bundles a good idea short of quick-n-dirty/getting started scenarios.
4. Test collateral that runs against the actual browser artifact

Remove in-box browser bundles for keyvault-* and identity

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/BlobClient.ts

Bring back missed changes to after moving BlobClients to BlobClient.ts
Missed changes:
- Some JSDoc fixes from this [commit](https://github.com/Azure/azure-sdk-for-js/commit/81a6e7678f1d074e81d5d98da99fdd3276b67fc6#diff-f0c6a76a3a221f38b579b9754d8908f6)
- DefaultValues in uploadStream from this [commit ](https://github.com/Azure/azure-sdk-for-js/pull/5740/files)

Bring back missed changes to after moving BlobClients to BlobClient.ts

---

sdk/core/ci.yml

This PR adds the ```eng/``` path to the PR path filters. This is because we disabled the ```js - client - ci``` pipeline which shouldn't be needed anymore because of unified pipelines, but we still wanted some coverage for changes to the eng folder.

Added eng to core ci build for coverage.

---

sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/credentials/authorizationCodeCredential.ts
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/clientSecretCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/src/credentials/usernamePasswordCredential.ts

- Added a code snippet to the documentation for `ChainedTokenCredential`
- removed an errant line from `DeviceCodeCredential` docs
- remove cross package links to `TokenCredential` and `AccessToken` from `core-auth` as they dont render well at the moment
_From @ramya-rao-a:_
From our github.io pages:
From our official docs:

[Identity] Add code snippet for ChainedTokenCredential, remove cross package links

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/AccountSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/SASQueryParameters.ts
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobserviceclient.spec.ts
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts
sdk/storage/storage-blob/test/node/containerclient.spec.ts
sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
sdk/storage/storage-blob/test/node/sas.spec.ts
sdk/storage/storage-blob/test/utils/index.ts
sdk/storage/storage-queue/review/storage-queue.api.md
sdk/storage/storage-queue/src/AccountSASSignatureValues.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueSASSignatureValues.ts
sdk/storage/storage-queue/src/SASQueryParameters.ts
sdk/storage/storage-queue/src/generated/src/models/index.ts
sdk/storage/storage-queue/src/generated/src/models/mappers.ts
sdk/storage/storage-queue/swagger/README.md
sdk/storage/storage-queue/test/node/queueclient.spec.ts
sdk/storage/storage-queue/test/node/sas.spec.ts
sdk/storage/storage-queue/test/queueclient.spec.ts
sdk/storage/storage-queue/test/utils/index.ts

There are a few places where start and expiry are used inconsistently. For consistency throughout the library and with other languages the following renames are needed:
start. startTime => startsOn
expiry, expiryTime => expiresOn
Fixes #5894

[Storage] [Queue & Blob] Consistency on startsOn and expiresOn

---

sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/core/keyVaultBase.ts
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/keysModels.ts
sdk/keyvault/keyvault-keys/src/lro/delete/operation.ts
sdk/keyvault/keyvault-keys/src/lro/recover/operation.ts
sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-keys/test/lro.recoverDelete.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/keyvault/keyvault-secrets/src/core/keyVaultBase.ts
sdk/keyvault/keyvault-secrets/src/index.ts
sdk/keyvault/keyvault-secrets/src/lro/delete/operation.ts
sdk/keyvault/keyvault-secrets/src/lro/recover/operation.ts
sdk/keyvault/keyvault-secrets/src/secretsModels.ts
sdk/keyvault/keyvault-secrets/test/CRUD.test.ts
sdk/keyvault/keyvault-secrets/test/list.test.ts
sdk/keyvault/keyvault-secrets/test/lro.delete.test.ts
sdk/keyvault/keyvault-secrets/test/lro.recover.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts

It started with just punctuation and cleanups on the optional parameters and types.
Then there were also some references to the CryptographyClient that needed to be updated.
We continued to find things until this issue was put in place: https://github.com/Azure/azure-sdk-for-js/issues/5906
Fixes #5906
From @ramya-rao-a:
Also included in this PR is the fix for #5917 for keys & secrets

[keyvault] Update code snippets, improve js docs

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/README.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

For readmes of following services: 
- storage
- keyvault
- eventhub

Fix broken reference links to gitHub.io in readme

---

sdk/storage/storage-blob/src/AccountSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobBatch.ts
sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobClient.ts
sdk/storage/storage-blob/src/BlobDownloadResponse.ts
sdk/storage/storage-blob/src/BlobLeaseClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/PageBlobRangeResponse.ts
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/StorageClient.ts
sdk/storage/storage-blob/src/StorageRetryPolicyFactory.ts
sdk/storage/storage-blob/src/TelemetryPolicyFactory.ts
sdk/storage/storage-blob/src/credentials/AnonymousCredential.ts
sdk/storage/storage-blob/src/policies/CredentialPolicy.ts
sdk/storage/storage-blob/src/pollers/BlobStartCopyFromUrlPoller.ts

GA doc check for storage-blob
Changes:
- Added a few more samples to inline doc comments in storage-blob (if an example was in the README, I added it to the inline samples for related methods)
- Added intra-package links to related types using `@link` syntax for everything I could catch. This should help make the docs a lot more navigable, as now most options types (which have their own HTML pages) link to their consumer methods as well as vice-versa.
- Fixed occasional typos as I noticed them
CC @ramya-rao-a

[storage-blob] Links, examples, and some doc fixes

---

documentation/using-azure-identity.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-queue/README.md

This change adds conceptual documentation for `@azure/identity` to make it easier for Azure SDK users to get started with it.  I'm trying to be as comprehensively concise as I can while deferring to the AAD docs for the detailed information. 
**NOTE:** This is a draft PR because I'm still fleshing out sections and adding details, but I'm sending it out early to get feedback to ensure I'm headed in the right direction!
([**Rendered**](https://github.com/daviwil/azure-sdk-for-js/blob/add-identity-docs/documentation/using-azure-identity.md))
Resolves #5898.

[Identity] Add @azure/identity conceptual documentation and update READMEs

---

sdk/storage/storage-blob/BreakingChanges.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/BreakingChanges.md
sdk/storage/storage-queue/ChangeLog.md
sdk/storage/storage-queue/README.md

As the bundling documentation may move, aka.ms seems to be the wise choice.

[Storage] Use aka.ms links for bundling documentation

---

sdk/keyvault/keyvault-secrets/samples/javascript/backupAndRestore.js

This fixes a place we didn't rename to latest API changes in one of the JS samples.

[KeyVault] Fix typo in KV JS sample

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/package.json
sdk/cognitiveservices/cognitiveservices-inkrecognizer/package.json
sdk/core/abort-controller/package.json
sdk/core/core-auth/package.json
sdk/core/core-lro/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

- Fixes "Different ordering in api properties with node 10 and node 12" (microsoft/rushstack#1552)

Update dev dependency api-extractor to latest

---

sdk/cosmosdb/cosmos/package.json

- karma-webpack has a peer dependency on webpack
- The missing dependency should have caused an error, but it was masked by a Rush feature "implicitlyPreferredVersions" which basically merges dependencies across projects
- We are planning to disable this rush feature (to address unrelated issues) which requires adding this missing dependency
- microsoft/rushstack#1415

[Cosmos] Add dev dependency webpack

---

sdk/appconfiguration/app-configuration/package.json
sdk/cognitiveservices/cognitiveservices-inkrecognizer/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-arm/package.json
sdk/core/core-asynciterator-polyfill/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-lro/package.json
sdk/core/core-paging/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/testhub/package.json
sdk/identity/identity/package.json
sdk/identity/identity/test/manual/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

- TypeScript allows breaking changes between minor versions
- Prevents breaking repo when running "rush update --full"
This should have no impact on build or test, since `pnpm-lock.yaml` already contains `typescript: 3.6.4` from the last run of `rush update --full`.
Updating to `typescript@3.7.2` causes build breaks in our repo.

Change typescript dependency from caret to tilde

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/samples/typescript/helloWorld.ts
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts

This adds a default certificate policy that users can reference without having to remember one themselves. 
Example:
```typescript
// Creating a self-signed certificate
const certificate = await client.createCertificate(certificateName, CertificatePolicy.Default);
```
fixes https://github.com/Azure/azure-sdk-for-js/issues/6052

Add default certificate policy

---

sdk/test-utils/recorder/src/recorder.ts

**NEW FEATURE - NON-BREAKING**
`skip` helper method takes in a new parameter that'll nicely update the test title with the provided reason in the console logs when a test is skipped. 😎
After this change -
Fixes #5246

[Common Recorder] Update the Skip method with a `reason` optional parameter

---

common/config/rush/pnpm-lock.yaml
rush.json

- Rush recommends using "fewer-dependencies" by default
- https://github.com/microsoft/rushstack/issues/1415#issuecomment-524168914
The impact of this change is a small diff in `pnpm-lock.yaml`:
https://github.com/Azure/azure-sdk-for-js/pull/6058/commits/a6ba337bf85385276653ef3ab659bfdc4dbb51c2
This diff is expected, because the point of `fewer-dependencies` is to prefer re-using existing dependencies rather than always using latest.
This PR was generated via the following steps, each with a separate commit:
1. Run `rush update --full` to update all deps to latest (without changing `resolutionStrategy`)
2. Set `resolutionStrategy=fewer-dependencies`
3. Run `rush update -full` again to compute the diff solely caused by the different `resolutionStrategy`

[Rush] Set resolutionStrategy=fewer-dependencies

---

sdk/cosmosdb/cosmos/changelog.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/test/integration/split.spec.ts

410 is an internal error that signals a partition split. We should not surface these to the user, instead, we should throw a 503

[Cosmos] Synthesize 503 error when a 410 surfaces out of a query

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/samples/receiveEvents.ts
sdk/eventhub/event-hubs/samples/receiveEventsWithLoadBalanced.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/test/eventHubConsumerClient.spec.ts
sdk/eventhub/event-hubs/test/sender.spec.ts
sdk/eventhub/event-hubs/test/utils/receivedMessagesTester.ts

Renames and consolidation:
* on<events> renamed to process<events>
* Moving the one positional parameter that was an event handler (onReceivedEvents) into the options structure along with the other event handlers. Made it required.
* Changed the EventProcessorOptions interfaces to make it so batch options weren't required. I had to do this in a less terse way than I prefer because of typedoc but the important thing is that the public interfaces just use straight inheritance.

[event-hubs] Addressing feedback from Brian

---

sdk/appconfiguration/app-configuration/README.md
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/sample.env
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/samples/setReadOnlySample.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/etags.spec.ts
sdk/appconfiguration/app-configuration/test/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts
sdk/appconfiguration/app-configuration/test/throwOrNotThrow.spec.ts

* clearReadOnly has been removed in favor of just adding a boolean parameter to setReadOnly that indicates if we're clearing or setting the readonly flag.
* The readonly field has been renamed to isReadOnly
* Updated readme and samples as well.

[app-configuration] readOnly naming changes

---

sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/src/AccountSASSignatureValues.ts
sdk/storage/storage-file-share/src/FileDownloadResponse.ts
sdk/storage/storage-file-share/src/Pipeline.ts
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-file-share/src/TelemetryPolicyFactory.ts
sdk/storage/storage-file-share/src/credentials/AnonymousCredential.ts
sdk/storage/storage-file-share/src/credentials/StorageSharedKeyCredential.ts
sdk/storage/storage-file-share/src/policies/CredentialPolicy.ts
sdk/storage/storage-file-share/src/policies/StorageSharedKeyCredentialPolicy.ts

Same treatment as blobs & queues for file shares. See: #5924  #5931 #5936 & #5957 
One PR with both sets of changes rather than two.
Changes:
- README:
- Reordered sections of the readme
- removed locales from URLs
- Made samples runnable
- Removed version information and changelog-style sections
- Prefer `require` to es6 for now
- Inline docs:
- Added samples from readme to inline docs
- Added link tags where I noticed they could be added
- Surrounded the names of exteranal types with backticks as appropriate
- linked options types to their consumer methods

[storage-file-share] Doc fixes, links, and README check for file-share

---

sdk/core/core-lro/package.json
sdk/core/core-lro/rollup.base.config.js

Some remaining KeyVault-Keys traces have been addressed.
**NOTE:** The production minified path is correct, so the bug I'm fixing doesn't affect the actual released bundle nor tests from packages using this library.

[core-lro] Browser build path fixes

---

sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts

This adds a WellKnownIssuers enum that users can use for picking default issuer values.

Add well-known issuers enum

---

.vscode/settings.json
package.json

VS Code was complaining about us using a deprecated settings.json option for prettier `prettier.eslintIntegration`. 
I also added prettier to our root package.json so we control the version of prettier being used instead of defaulting to the one bundled with the extension. 
I realized that the eslint extension hasn't been working for me ever (which explains how lint errors keep creeping in), but I wasn't able to fix that as part of this PR. I filed #6155 to track that work.

Remove deprecated option for prettier

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts

`rush build` had some warnings. This fixes it.

WIP [KeyVault] Fixed build warnings

---

sdk/storage/README.md

Use the same snippet from the individual package README files in the general storage README, advising users to use `@azure/logger` instead of a custom pipeline logger.
Addresses #5968

[storage] Use @azure/logger in storage README

---

sdk/storage/storage-file-share/recordings/browsers/directoryclient/recording_verify_directoryclient_name_matches_file_name.json
sdk/storage/storage-file-share/recordings/browsers/fileclient/recording_verify_fileclient_name_matches_file_name.json
sdk/storage/storage-file-share/recordings/node/directoryclient/recording_verify_directoryclient_name_matches_file_name.js
sdk/storage/storage-file-share/recordings/node/fileclient/recording_verify_fileclient_name_matches_file_name.js
sdk/storage/storage-file-share/recordings/node/shareclient/recording_throws_error_if_constructor_sharename_parameter_is_empty.js
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-file-share/test/directoryclient.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts
sdk/storage/storage-file-share/test/node/sas.spec.ts
sdk/storage/storage-file-share/test/shareclient.spec.ts

Addresses #5568 for file-shares
This is a breaking change.
Changes:
- Renamed `shareName` to `name` in ShareClient
- added `name` fields to FileClient and Directory client that return only the basename portion of the file path
- added basic tests
- added doc strings to path, name, and shareName fields

[storage-file-share] shareName/name fields for Share clients

---

sdk/test-utils/recorder/package.json

- Missing dependencies were masked by Rush configuration which merges dependencies across packages

[test-utils-recorder] Add missing dev dependencies

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-certificates/src/index.ts

🌞 related to https://github.com/Azure/azure-sdk-for-js/issues/5489

[KeyVault-Certificates] More clarity on the use cases of the Self issuerName

---

sdk/eventhub/event-hubs/test/utils/receivedMessagesTester.ts

The test utility wasn't properly recognizing errors that occur when a new receiver with a `>=` ownerLevel causes another receiver to disconnect.
/cc @richardpark-msft

[Event Hubs] fix flaky live test

---

sdk/storage/storage-blob/src/Clients.ts

Not importing `BlockBlobUploadOptions` and `BlobDeleteOptions` since they are exported from the same file.
Fixes #6160

[Storage Blob] Fix - Build warning "Import declaration conflicts"

---

sdk/storage/storage-file-share/samples/javascript/basic.js
sdk/storage/storage-file-share/samples/typescript/basic.ts
sdk/storage/storage-file-share/src/FileDownloadResponse.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/generated/src/models/index.ts
sdk/storage/storage-file-share/src/generated/src/operations/file.ts
sdk/storage/storage-file-share/swagger/README.md

Fix #6020 and #6023 
- rename the `optionalbody` parameter of file operations in the generated models to `body` using swagger transformation
- rename `blobBody` accessor to `contentAsBlob` to align with other storage clients.

[storage-file-share] naming consistency around content bodies

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/managedIdentityCredential.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

This change fixes an issue that occurs when authenticating with a user-assigned managed identity inside of an application deployed to Azure App Service or Azure Functions.  The issue manifests as an authorization error when accessing a resource (like Blob Storage) because the wrong access token gets returned by the MSI endpoint.
There is a slight implementation difference in how App Service / Functions accepts the client ID of the user-assigned identity: it is [expected to be sent as `clientid`](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet#using-the-rest-protocol) rather than `client_id` as in other services which provide MSI authentication.
This issue was originally identified by @jianghaolu and fixed in the Java SDK in PR [#5897]( …

[Identity] Send user-assigned managed identity ID as 'clientid' with no '_'

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts

Get consistent about vaultUrl visibility.
Part of https://github.com/Azure/azure-sdk-for-js/issues/6198

[KeyVault] Make vaultUrl public and readonly

---

.docsettings.yml
sdk/keyvault/README.md

This adds a README.md to the root of keyvault to describe what is available in the different KV libraries
Fixes https://github.com/azure/azure-sdk-for-js/issues/5666

Add README to root of Key Vault

---

sdk/storage/storage-file-share/recordings/node/highlevel_nodejs_only/recording_downloadtobuffer_should_throw_an_error_if_the_count_size_in_bytes_is_too_large.js
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/test/node/highlevel.node.spec.ts
sdk/storage/storage-file-share/test/utils/recorder.ts

Addresses #6016 
This is not a breaking API change (see diff of api.md file).
Changes:
- Modified signature of `downloadToBuffer` to return a `Promise<Buffer>` instead of a `Promise<void>`
- Overloaded `downloadToBuffer`
- passing a `Buffer` as the first argument is now optional, with a three-argument overload with `offset` as its first argument
- if no buffer is given, then we will allocate a buffer of `count` bytes (given by second argument)
- if no count is given, we will ask the service for the size of the file and allocate enough space to store the contents of the file beginning from `offset` to the end
- Added tests for the new overload
- Recorded test runs from live integration tests, skipping one because it does not run in playback
- Updated API reference

[storage-file-share] overload downloadToBuffer with internal buffer option

---

sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/src/eventHubReceiver.ts

When an event hubs receiver encounters a transient issue, it closes the link and attempts to create a new one.
Currently, if the receiver's attempt to recreate the link fails and it exhausts its retries, the user is never notified.
This change causes the user-provided error handler to be invoked with the final error that is thrown when the receiver fails to reconnect. At this point, the user can decide whether to restart their receiver by calling `client.receive()` again.

[event hubs] forward detached errors to user error handler (2.x)

---

sdk/eventhub/event-hubs/src/eventHubClient.ts

This is needed since I've updated the version of amqp-common event hubs uses to preview.6, and that version no longer sets the aadAudience:
https://github.com/Azure/azure-sdk-for-js/pull/4098/files
I did not update the changelog since this has no user-facing change.

[event hubs] set audience for MSITokenCredentials (2.x)

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples/package.json

Only breaking change is removing support for Node 4, 5, and 7:
https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0

 Update dev dependency https-proxy-agent

---

sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobPartitionManager.ts

This PR is meant to fix [this issue](https://github.com/Azure/azure-sdk-for-js/issues/6235) in which you can find all the details.
- **@azure/event-hubs**
Falsy value of offset and sequence number (`= 0`) are causing the `EventProcessor` to set the wrong `eventPosition` that is falledback to the defaultEventPosition or `EventPosition.earliest()`.
Checking for the `!= null`, instead (which both cover `undefined` and `null`).
Version of library and `changelog.md` were not updated on purpose since the [current version](https://github.com/Azure/azure-sdk-for-js/blob/aab5b7b79d771ed2780a0beaf04bd9d3ace800ca/sdk/eventhub/event-hubs/package.json#L4) pushed in the code is `5.0.0-preview.7` but the published [next version](https://www.npmjs.com/package/@azure/event-hubs/v/5.0.0-preview.6) is …

[Event Hubs] Fix for sequence number = 0 bug. 

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/eventhub/ci.yml

The EvenHubs pipelines are wasting significant amounts of time spinning up agents to run tests that are then just skipped. This plumbs through a pre-existing variable to disable unit tests so that it can be turned off for the EventHubs pipeline.

Pipe through logic to disable unit tests.

---

common/config/rush/common-versions.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/testhub/package.json

- 2.1.2 causes a type-related build break in event-processor-host

Pin dependency @azure/event-hubs to 2.1.1

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/testhub/package.json

Now that event hubs 2.1.3 is released which fixes the type issues introduced in version 2.1.2, we no longer have to pin to a patch version.
I left the dep set to `^2.1.1` since that's what event-processor-host uses in the published version.

Unpin dependency @azure/event-hubs-2.1.1

---

common/config/rush/pnpm-lock.yaml
sdk/cognitiveservices/cognitiveservices-inkrecognizer/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

Only breaking change is dropping support for Node < 7:
https://github.com/kentcdodds/cross-env/releases/tag/v6.0.0

Update dev dependency cross-env

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

@southpolesteve: Was the dependency pinned for a specific reason, or should it have been using caret?

[cosmos] Update dev dependency snap-shot-it

---

common/config/rush/pnpm-lock.yaml
sdk/cosmosdb/cosmos/package.json

I'm not sure if this dependency was using `~` instead of `^` intentionally, but it should use `^` unless there's a strong reason not to.
`@typescript-eslint/eslint-plugin-tslint@2.8.0` does generate additional lint problems in the report, but not a significant amount:
[cosmos-lintReport-2.3.3.html.zip](https://github.com/Azure/azure-sdk-for-js/files/3865617/cosmos-lintReport-2.3.3.html.zip): 804 problems (287 errors, 517 warnings)
[cosmos-lintReport-2.8.0.html.zip](https://github.com/Azure/azure-sdk-for-js/files/3865610/cosmos-lintReport-2.8.0.html.zip): 851 problems (334 errors, 517 warnings)

[cosmos] Update dev dependency eslint-plugin-tslint

---

sdk/core/core-http/package.json
sdk/cosmosdb/cosmos/package.json

Change is effectively a no-op, since `pnpm-lock.yaml` already contains `karma-webpack@4.0.2`.  However, we prefer to use GA versions instead of previews in our `package.json` files.

Update dev dependency karma-webpack

---

sdk/keyvault/keyvault-certificates/package.json

This removes an unused dependency in keyvault-certificates.
Fixes #6249

[KeyVault-Certificates] Remove unused core-arm depedency

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/package.json
sdk/core/core-lro/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json

* Drop Support for Node 6, to make it possible to use async/await in karma codebase.
* travis: no support for node < 6
* node 10 not supported by libxmljs-mt

Update karma junit reporter

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

* Puppeteer now requires Node.js v8+; Node.js v6 is no longer supported

Update dev dependency puppeteer

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

```
- Tightened typings / APIs
- Made userHeaders optional
- Added readable stream options to constructor type
- Passed options to constructor if not used with new
- Fixed memory leak #447
- Bumped nodejs requirement to v6
```
Only breaking change appears to be requirement on node >= 6 which doesn't impact us.
@daviwil: Note this is a runtime dependency (not a dev dependency) so this might require extra scrutiny.

[core-http] Update dependency form-data

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/core/core-auth/Changelog.md
sdk/core/core-http/Changelog.md
sdk/eventhub/event-hubs/changelog.md
sdk/identity/identity/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/storage/storage-blob/ChangeLog.md
sdk/storage/storage-file-share/ChangeLog.md
sdk/storage/storage-queue/ChangeLog.md

Add a note to unreleased packages about the recent adoption of OpenTelemetry 0.2 and upgrade of the `@azure/core-tracing` package.

Update changelogs for `@azure/core-tracing` update

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/package.json
sdk/identity/identity/samples/authorizationCodeSample.ts

@daviwil: Note the code change to the sample, as recommended by the docs for `open@7.0.0`:
> Correctly handle URL and path escaping on Windows (#146) 7ef15d2
> If you use open with URLs, you'll want to use the new {url: true} option.
> 
> https://github.com/sindresorhus/open/releases/tag/v7.0.0
How can I validate the change to this sample?  Do any of our pipelines run the sample, or does it need to be run manually?

[identity] Update dev dependency "open"

---

sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts

Address #6213
Just adds a couple of lines to the `downloadToBuffer` docs explaining Buffer limitations and referencing `downloadToFile` as an alternative if size is a consideration.

[storage] Add warning about limits of Node.js buffer sizes to documentation

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
rush.json

- Required to support dependencies with incompatible peerDependencies ranges
- Reverts two workarounds which are no longer necessary
- strictPeerDependencies=false
- rhea-promise in preferredVersions
* https://rushjs.io/pages/advanced/preferred_versions/
* https://github.com/microsoft/rushstack/issues/1415
* https://github.com/microsoft/rushstack/issues/1621

Set implicitlyPreferredVersions=false

---

sdk/core/core-tracing/Changelog.md

Update the changelog to talk about the OpenTelemetry 0.2 update.

Update core-tracing changelog

---

sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobSASSignatureValues.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts

Per previous discussions and reasoning outlined in #5997 
Removed `@example` from doc comments leaving only the code fences so they will render inline on docs.microsoft.com

[storage] removed @example from all doc comments

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/src/credentials/environmentCredential.ts
sdk/identity/identity/test/node/environmentCredential.spec.ts

A customer [recently reported](https://github.com/Azure/azure-sdk-for-js/issues/5882) that they were not able to authenticate with `@azure/keyvault-secrets` using an `EnvironmentCredential`.  No error was being thrown at the time of authentication.  It turns out that they had misspelled one of the environment variables that `EnvironmentCredential` expects and, upon being invoked, `getToken` returned `null` instead of throwing an exception to alert the user of this fact.  This caused authentication to silently fail.
This change causes `EnvironmentCredential` to throw an error listing any missing environment variables when `getToken` has been called without having an inner credential configured (as it happens when no appropriate set of environment variables are found).
Note that I am not …

[Identity] EnvironmentCredential now throws an error with missing env variables

---

sdk/cosmosdb/cosmos/src/queryIterator.ts

I noticed this typo when using the lib to log the results object of a query.

[Cosmos] Fix typo on private var

---

sdk/cosmosdb/cosmos/src/client/Container/ContainerDefinition.ts
sdk/cosmosdb/cosmos/src/documents/PartitionKeyDefinition.ts

Description came from the create a collection article on docs.ms
I didn't see any links in existing definitions but markdown formatted links should show up in VS Code.

Add jsdoc for partitionKey

---

sdk/cosmosdb/cosmos/changelog.md
sdk/cosmosdb/cosmos/src/queryExecutionContext/orderByDocumentProducerComparator.ts
sdk/cosmosdb/cosmos/src/request/StatusCodes.ts
sdk/cosmosdb/cosmos/test/functional/sproc.spec.ts
sdk/cosmosdb/cosmos/test/integration/crossPartition.spec.ts

The current error when doing on ORDER BY query on a field that contains mixed types is not very helpful. This improves the error message to direct the user toward `IS_NUMBER` or ` IS_STRING`
Example erroring query: `SELECT * from C ORDER BY c.name`
Where c.name could be a string or boolean.
Working query: `SELECT * from C ORDER BY c.name WHERE IS_STRING(c.name)`
Fixes #4954

[Cosmos] Improve error for mixed type orderby

---

sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-queue/src/QueueClient.ts

Discussion in #4966 , this behavior of `BlobClient.getProperties` should be documented. I have added  a warning to the documentation comments.
Some other clients have the same situation in which a sort of "higher-order" client (i.e. ContainerClient -> BlobClient, BlobServiceClient -> ContainerClient, etc.) has an `includeMetadata` key in its options bag for list methods that will result in metadata key-value pairs being returned in the XML body of the request. However, the "lower-order" clients also have a `getProperties` method that will return the metadata in the HTTP headers.
In those cases where an `includeMetadata` key exists in the list method options bag, I have added the warning.

[storage] document lower-casing of metadata in getProperties methods

---

sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

For more context refer to #5757 
This PR is to address the slowness / misses in receiving messages in `receiveAndDelete` mode by removing the timer around new message wait time.
Also fixes documentation discrepancies.

[ServiceBus] Remove newMessageWaitTimer for receiveAndDelete

---

sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/receiver.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

The retry that results in the behavior described in #5541 happens due to the below sequence of events
- The receiver is [cached before it is initialized](https://github.com/Azure/azure-sdk-for-js/blob/%40azure/service-bus_1.1.0/sdk/servicebus/service-bus/src/core/streamingReceiver.ts#L113).
- The claim negotiation which is part of the initialization process fails due to the token provider throwing an error.
- 60 seconds later, there is a connection error (condition: `amqp:connection:forced`, description: `The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'`) coming from the service as there has been no activity on it for over a minute.  
- This is a retryable error which results in the library trying to [recover cached senders …

[Service Bus] Cache receiver only if it is initialized successfully

---

.docsettings.yml
common/scripts/prep-samples.js
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/samples/javascript/README.md
sdk/storage/storage-file-share/samples/javascript/advanced.js
sdk/storage/storage-file-share/samples/javascript/anonymousCred.js
sdk/storage/storage-file-share/samples/javascript/basic.js
sdk/storage/storage-file-share/samples/javascript/customPipeline.js
sdk/storage/storage-file-share/samples/javascript/iterators-files-and-directories.js
sdk/storage/storage-file-share/samples/javascript/iterators-handles.js
sdk/storage/storage-file-share/samples/javascript/iterators-shares.js
sdk/storage/storage-file-share/samples/javascript/package.json
sdk/storage/storage-file-share/samples/javascript/proxyAuth.js
sdk/storage/storage-file-share/samples/javascript/sharedKeyCred.js
sdk/storage/storage-file-share/samples/javascript/withConnString.js
sdk/storage/storage-file-share/samples/tsconfig.json
sdk/storage/storage-file-share/samples/typescript/README.md
sdk/storage/storage-file-share/samples/typescript/advanced.ts
sdk/storage/storage-file-share/samples/typescript/anonymousCred.ts
sdk/storage/storage-file-share/samples/typescript/basic.ts
sdk/storage/storage-file-share/samples/typescript/customPipeline.ts
sdk/storage/storage-file-share/samples/typescript/iterators-files-and-directories.ts
sdk/storage/storage-file-share/samples/typescript/iterators-handles.ts
sdk/storage/storage-file-share/samples/typescript/iterators-shares.ts
sdk/storage/storage-file-share/samples/typescript/package.json
sdk/storage/storage-file-share/samples/typescript/proxyAuth.ts
sdk/storage/storage-file-share/samples/typescript/sharedKeyCred.ts
sdk/storage/storage-file-share/samples/typescript/tsconfig.json
sdk/storage/storage-file-share/samples/typescript/withConnString.ts

Addresses #5679 for file-shares.
I'm starting here and getting some feedback before I proceed to the rest of the packages. I'll want to add similar files for all the packages that are GA or that are going GA. I'll leave some comments on the files below with some open questions for anyone with input.
We need to have README files in each of the packages' `samples/typescript` and `samples/javascript` folders (with YAML front-matter configured like this) in order for our sample code to be ingested to docs.microsoft.com/samples
This is, to the best of my knowledge, the recommended formatting.
CC @kaerm @ramya-rao-a

[storage-file-share] README files for samples directories

---

sdk/servicebus/service-bus/changelog.md
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

When a customer is using a streaming receiver (via receiveMessagehandler) and the receiver encounters a transient issue, the SDK will attempt to reconnect to the service in the background.
If all of the retries are exhausted, or a non-retryable error is encountered, the SDK will stop trying to reconnect the receiver. However, the final error received is not passed to the user-provided error handler if one was registered.
This change updates `MessageReceiver.onDetached` to forward the last error it receives to the user-provided error handler if it exists.
I added a test that creates a StreamingReceiver directly, updates `_init` to throw a non-retryable error and calls `onDetached` directly. The test then valdiates that the error thrown by `_init` is caught by the user's error handler.
The …

[service bus] forward detached errors to user error handler

---

sdk/identity/identity/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-queue/README.md

In the README files for packages that have gone GA. 
#6311

Replace azure.github.io links with docs.microsoft.com

---

sdk/appconfiguration/app-configuration/README.md
sdk/eventhub/event-hubs/README.md
sdk/keyvault/README.md
sdk/keyvault/keyvault-certificates/README.md
sdk/storage/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/samples/javascript/README.md
sdk/storage/storage-file-share/samples/typescript/README.md

#6311 
Due to workspace settings, the formatter also ran on some of the files.
I replaced all of the azure.github.io API reference links with docs.microsoft.com, except for eventhubs-checkpointstore, which doesn't have a docs.microsoft.com page.

READMEs: Formatted and removed all other links to azure.github.io API docs

---

sdk/storage/storage-file-share/package.json

Samples execution regressed after recent changes to samples. Disable this for
now until https://github.com/Azure/azure-sdk-for-js/issues/6362 is fixed.

[Storage] disable execute:samples temporarily

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml

At least for now we are deleting the packaging diffing option
in the analyze step because we don't have a great way to get
the latest package to compare against. We can consider enabling
this again in the future but for now we are removing to unblock
builds.
PTAL @KarishmaGhiya @mitchdenny @mikeharder 
cc @azure/azure-sdk-eng

Remove packaging diff from Analyze step

---

sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json

Pins to version 12.x.x of `@azure/storage-blob` since storage-blob is no longer in preview.

[eventhubs-checkpointstore-blob] pins to major version of storage-blob dep

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/src/generated/src/appConfigurationContext.ts
sdk/core/core-auth/Changelog.md
sdk/core/core-auth/package.json
sdk/core/core-http/Changelog.md
sdk/core/core-http/lib/util/constants.ts
sdk/core/core-http/package.json
sdk/core/core-tracing/Changelog.md
sdk/core/core-tracing/lib/tracerProxy.ts
sdk/core/core-tracing/lib/utils/cache.ts
sdk/core/core-tracing/lib/utils/log.ts
sdk/core/core-tracing/package.json
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

I realized that preview6 didn't bump the OT compatibility version for our global singleton despite taking breaking changes.
This PR not only bumps the version, but also improves upon our conflict logic. Previously we just threw an error to alert users to the mismatch, but this feels bad in the case where a consumer doesn't care about tracing at all.
Instead, we will now throw only when a tracer has explicitly been set by the user. We also have changed our singleton name so that we never run into a case where a preview5 consumer gets an unexpected error.
Fixes #6371

Improve `@azure/core-tracing` behavior when dealing with OpenTelemetry mismatches

---

sdk/eventhub/eventhubs-checkpointstore-blob/package.json

Changing our dependency on @azure/storage-blob package version to an 
older release so we can release eventhubs-checkpointstore-blob without
waiting for a newer storage package.

[event-hubs] Revert to the published version of @azure/storage-blob

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/core/utils/constants.ts
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts

We accidentally released an older version of these packages.

[KeyVault] Upgraded the versions to reflect the update on core-tracing

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/src/ShareFileClient.ts

The code snippets for browsers in the README have never been tested.  This change updates them to a working version.  A reference back to the JavaScript Bundle section is also added.

[Storage] Fix browser code snippets in README and comments

---

sdk/storage/README.md
sdk/storage/storage-queue/README.md

The Queue code snippets probably were not tested when we replace the queue name
with a place holder name.
The snippets in storage/README.md was not updated when we did rename
refactoring.
This change fixes them to a working version.

[Storage] Fix more code snippets in README

---

sdk/eventhub/event-hubs/README.md

Broken links in the documentation for consuming events

[Event Hubs] Fix link by adding missing hash

---

sdk/core/abort-controller/changelog.md

Updates changelog entry.
package.json already shows the correct version (1.0.1)

[abort-controller] prepare for 1.0.1 release

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

so when the `build:autorest` NPM script is executed, the package version is not
changed to the default `1.0.0`.
Resolves #6327

[Storage] passing package versions to build:autorest script

---

sdk/core/core-http/lib/fetchHttpClient.ts
sdk/core/core-http/test/defaultHttpClientTests.ts

The regression was introduced in #5298. If a second argument `data`
is passed to `callback()` in `_transform()`, `data` will be pushed
again.  I misread the doc when adding the report transform.
This change removes the second argument from `callback()`.
Fixes #6352.

[Core-http] Fix issue of data being pushed twice when reporting progress

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/samples/getSettingOnlyIfChanged.ts
sdk/appconfiguration/app-configuration/samples/helloworld.ts
sdk/appconfiguration/app-configuration/samples/helloworldWithLabels.ts
sdk/appconfiguration/app-configuration/samples/listRevisions.ts
sdk/appconfiguration/app-configuration/samples/optimisticConcurrencyViaEtag.ts
sdk/appconfiguration/app-configuration/samples/setReadOnlySample.ts
sdk/appconfiguration/app-configuration/src/generated/src/appConfigurationContext.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/helpers.spec.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts
sdk/appconfiguration/app-configuration/test/internal/synctokenpolicy.spec.ts
sdk/appconfiguration/app-configuration/test/package.spec.ts
sdk/appconfiguration/app-configuration/test/testHelpers.ts

As part of a .net API review we discovered some inconsistent behavior
with how we handle filters, especially with regards to proper escaping.
This PR renames those fields and also makes them strings rather than
arrays while also documenting the format allowed for the underlying
string.
(also, fixing an odd issue where `nock` was failing. Adding the
dependency and removing a method that didn't need to be called)
Fixes #6384

[app-configuration] Renaming keys => keyFilter, label => labelFilter

---

common/config/rush/pnpm-lock.yaml
sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/rollup.base.config.js
sdk/core/amqp-common/src/ConnectionContextBase.ts
sdk/core/amqp-common/src/util/constants.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/testhub/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md

This change is needed to fix #6118 
The idle_time_out is used by rhea. If no data has been sent from the service within the idle_time_out period, then rhea will trigger a `disconnect` event on the `Connection` object. There is a heartbeat sent by rhea when the SDK isn't actively sending or receiving data.
To test, I set up a linux-based docker container with a simple event hubs script that receives messages.
I then would use iptables to block traffic on the port communicating to event hubs to allow the idle_time_out to be met.
I also observed that when the connection disconnected, event hubs reconnected and continued receiving events.
Setup an npm package that depends on:
- `@azure/event-hubs`
- `@azure/amqp-common-preview.9`
```docker
FROM node:12.13.0
WORKDIR /usr/src/app
RUN apt-get …
```

[amqp-common] Sets connection idle timeout to 60 seconds

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- Default on Windows is "cores - 1" (microsoft/rushstack#436)
- Increasing to "max" ensures parallelism is set to the number of cores on all platforms
- Significantly improves Windows build times

Set rush parallelism to "max" (# of cores)

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts

The sync token policy that's already in place can handle both requests and responses

[app-configuration] Remove manual instrumentation of each method for syncToken

---

.github/CODEOWNERS

Adding @xirzec and @bterlson as code owners to core packages to ensure they are included in code reviews for the same

Add more code owners to core

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- Results are published for both success and failure
- Unlink dependencies should use the same condition as publish
- Continuation of #6418
Example where "unlink dependencies" step was skipped due to test failures:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=206607

Unlink dependencies if tests fail

---

sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/partitionProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/pumpManager.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/eventhubs-checkpointstore-blob/changelog.md
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts

Changes to error handling and reporting due to feature team discussion.
* If the _user's_ event handlers (processEvents, processInitialization, 
processClose) throw errors we funnel those into their processError()
handler so they'll know about it. 
* BlobCheckpointStore shouldn't eat all errors when claiming partitions. 
Now, the only case where it _will_ eat errors is when we have an etag 
conflict due to someone else taking partition ownership.
Fixes #6444

[event-hubs] Better error handling and reporting

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/src/retry.ts

This change adds logging around the dns.resolve call in `checkNetworkConnection`. We recently found that `ETIMEOUT` could be returned by dns.resolve which we didn't expect to see previously. This logging should help us troubleshoot issues around troubleshooting network connection errors.
I manually tested this change by running an event hubs receiver sample and disconnecting my network.

[amqp-common] add logging to dns.resolve

---

sdk/core/core-http/lib/policies/proxyPolicy.ts
sdk/core/core-http/lib/serviceClient.ts

so that libraries that don't use the PipelineOptions from core-http can use
this behavior without duplicating code.
Resolves #6387

[Core-http] Move getDefaultProxySettings into proxyPolicy

---

sdk/eventhub/event-hubs/samples/README.md
sdk/eventhub/event-hubs/samples/package.json
sdk/eventhub/event-hubs/samples/receiveEvents.ts
sdk/eventhub/event-hubs/samples/receiveEventsUsingCheckpointStore.ts
sdk/eventhub/event-hubs/samples/runsamples.ts
sdk/eventhub/event-hubs/samples/sample.env
sdk/eventhub/event-hubs/samples/sampleHelpers.ts
sdk/eventhub/event-hubs/samples/sendEvents.ts
sdk/eventhub/event-hubs/samples/tsconfig.json
sdk/eventhub/event-hubs/samples/useWithIotHub.ts
sdk/eventhub/event-hubs/samples/usingAadAuth.ts
sdk/eventhub/event-hubs/samples/websockets.ts

Improving the samples by making them:
* Simpler for users to just download and run.
* Makes it more effective for us as a testing tool since we can use it to test whatever is published based on using @next as the default version for the packages.
* Lets us use some convenient libraries like `dotenv`.
Also, made an improvement to the sendEvents.ts example, fixing #6254

[event-hubs] Updating samples folder to make it a standalone project

---

common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json

Fixes #6369 
This change updates event-hubs to use the latest version of amqp-common.
This change is needed so that the SDK can detect when a connection is idle. See #6118 for more details.

[event-hubs][2.x] update amqp-common dep

---

.github/CODEOWNERS
common/config/rush/pnpm-lock.yaml
sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/changelog.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/constants.ts

Fixes #6118 
`@azure/event-hubs@2.1.4` includes this fix. This updates the preview version of `@azure/event-hubs` and `@azure/service-bus` to depend on the version of their core amqp libraries that has a 1 minute idle timeout.

Event Hubs & Service Bus to use latest version of core-amqp & amqp-common

---

sdk/eventhub/event-hubs/changelog.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts

[event-hubs](2.x) appends a unique id to user-provided receive name

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
sdk/core/core-http/lib/policies/logPolicy.ts

The User-Agent header is not alterable in the browser so we need to fallback to the x-ms-useragent header so we can still send the same information.
This also requires a change on the service backend which won't take effect until January but we will start sending the correct header on next release of the SDK.
Fixes #5810 (for the SDK-side).
(service issue to accept the new header)
https://github.com/Azure/AppConfiguration/issues/217

[app-configuration] Use the x-ms-useragent header when in the browser

---

common/config/rush/common-versions.json
sdk/eventhub/event-processor-host/changelog.md
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/event-processor-host/src/util/constants.ts
sdk/eventhub/event-processor-host/test/eph.spec.ts
sdk/eventhub/testhub/package.json

This updates the minimum version of event-hubs due to a number of bug fixes introduced between 2.1.1 and 2.1.4.
This should not have any tangible change for customers using `@azure/event-processor-host` version 2.1.0 today, except that it enforces the minimum version of event hubs.
(I apologize for the formatting changes!)

[event-processor-host] update event-hubs dep

---

sdk/eventhub/ci.yml

I noticed that event-processor-host is not included in the release pipeline, and I can't run the legacy pipeline from master anymore.
I believe this update should add event-processor-host to the release pipeline, but would like confirmation from @mitchdenny 
/cc @ramya-rao-a

[event-processor-host] update ci.yml

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- If build is cancelled due to agent timeout, some tests results may have already been generated and should still be published

Publish test results even if build is canceled

---

sdk/eventhub/event-hubs/migrationguide.md

Updated migration guide to
- remove types from samples
- add note that we now await the async callbacks
- improved error handling

Tweak migration guide to have more comments, less types

---

sdk/keyvault/keyvault-certificates/src/index.ts

backupCertificate now returns a Uint8Array (or undefined).

[KeyVault-Certificates] Found a small documentation bug

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/samples/typescript/helloWorld.ts
sdk/keyvault/keyvault-certificates/src/certificatesModels.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/test/CRUD.test.ts
sdk/keyvault/keyvault-certificates/test/lro.create.test.ts
sdk/keyvault/keyvault-certificates/test/lro.delete.test.ts
sdk/keyvault/keyvault-certificates/test/lro.operation.test.ts
sdk/keyvault/keyvault-certificates/test/lro.recover.test.ts

Fixes #6518
What this PR fixes:
- certificatePolicy parameter -> policy in beginCreateCertificate
- version parameter in updateCertificateProperties should be optional
- Should enforce that CertificatePolicy gets issuerName and one or both of subject and subjectAlternativeNames
- JsonWebKeyType enum name -> CertificateKeyType
- id, name, createdOn, and updatedOn should be readonly for CertificateIssuer. Go over others to make sure what should be readonly is readonly
- issuerProperties property -> properties in CertificateIssuer 
- Remove credentials property from CertificateIssuer
Tasks that weren't fixed as part of this PR because they are fixed on master:  
See _Fixed on master_ here: https://github.com/Azure/azure-sdk-for-js/issues/6518#issuecomment-565083908
All the questions have …

[KeyVault-Certificates] Fixes for the API inconsistencies

---

sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/index.ts

It still can be an empty string, but swagger has it required here: https://docs.microsoft.com/en-us/rest/api/keyvault/updatecertificate/updatecertificate
This is probably the best fix for typescript, since otherwise this would mean changing some GAd packages.
Fixes #6543

[KeyVault-Certificates] version IS a required property of update certificates

---

sdk/servicebus/service-bus/test/atomXml.spec.ts

For more context refer to #6197 
This code should remain unaffected or can be converted to a live test once the MQ item on configuring unique test resources is through

[Service Bus] Add tests for empty list response

---

sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

nyc is obscuring Mocha's stack traces. It's unable to follow through the references. This is the fastest fix (probably by days of separation from the next fastest fix), and this will incidentally make our Node tests faster.
Fixes #6298

Separating nyc from the integration tests for Node

---

sdk/cosmosdb/cosmos/src/client/Container/Container.ts

The code sample leaves out the partition key, but the TypeScript definition reports that it is required.

Add partition key to code sample

---

sdk/storage/storage-blob/.nycrc
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/.nycrc
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/.nycrc
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/.nycrc
sdk/storage/storage-queue/package.json

The code coverage report include data for dependencies (`dotenv` for
example). This is because we run the test on the one single bundled
file, while nyc exclusion works by not instrumenting imported or
required modules in the exclusion list.
This change run nyc on individual spec.js files instead. A dev
dependency `esm` is introduced so that nyc can load our test modules.
NodeJS part of #2820.

[Storage] fix nyc code coverage exclusion issue

---

sdk/test-utils/recorder/package.json

Fixes prettier error in VS CODE for the test-utils/recorder folder by adding prettier devDependency

[recorder] Fix prettier error in VS CODE for the test-utils/recorder folder

---

sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/test/eventHubConsumerClient.spec.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts

When reading from a single partition we can completely forgo any of the processing we do in the normal multi-partition loop. 
This should let users get the benefits of all the other infrastructure (checkpointing) without having to pay a performance penalty for load balancing and ownership.
Fixes #6554

[event-hubs] Remove the processing loop when processing single vs multiple partitions

---

sdk/test-utils/recorder/src/recorder.ts
sdk/test-utils/recorder/src/utils.ts

This is a simplistic solution. The idea is that, when the tests run, they will store these names in an in-memory array and throw if the name happens to be repeated. It's cheap enough.
I see a random number generator in the name, I wonder if we should remove that.
Fixes #5698

[recorder] Improved getUniqueName

---

sdk/storage/storage-blob/samples/typescript/README.md

Fixes a typo in the links section of this readme which causes the link to be broken in the table.

[storage-blob] typo in storage ts sample readme

---

sdk/test-utils/recorder/src/baseRecorder.ts

Found a bug that can potentially corrupt the recordings if a required environment variable is null or an empty string.
**Fix in this PR**
Update the recordings with dummy environment variables only if the corresponding actual environment variable is non-null.

[Common Recorder] Update the recording only if the env variable is non null

---

.gitattributes

Generated files are collapsed by default in the diff view. This will make reviewing PRs a bit easier.

Update gitattributes to mark generated files

---

sdk/storage/storage-blob/src/BlobBatchClient.ts
sdk/storage/storage-blob/src/BlobServiceClient.ts
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/src/utils/cache.ts
sdk/storage/storage-file-datalake/src/DataLakeFileSystemClient.ts
sdk/storage/storage-file-datalake/src/DataLakeServiceClient.ts
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/utils/cache.ts
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-file-share/src/ShareDirectoryClient.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/ShareServiceClient.ts
sdk/storage/storage-file-share/src/utils/cache.ts
sdk/storage/storage-queue/src/QueueClient.ts
sdk/storage/storage-queue/src/QueueServiceClient.ts
sdk/storage/storage-queue/src/utils/cache.ts

Currently child clients obtained via `get*Client()` share their parent
client's pipeline. But when the pipeline doesn't have a httpClient
specified, a `DefaultHttpClient` will be created for each of the
clients.
There's no reason why we cannot share the http client instance among
storage clients.  This change create a default http client instance
for parent client's pipeline if none is specified.

[Storage] Share a single httpClient among clients

---

sdk/servicebus/service-bus/src/queueClient.ts
sdk/servicebus/service-bus/src/subscriptionClient.ts

For more context refer to #6136 
Verified output using typedocs command `typedoc --excludePrivate --excludeNotExported --exclude "node_modules/**/*" --ignoreCompilerErrors --mode file --out ./docs ./src`

[Service Bus] Remove unnecessary docs from function overloads

---

sdk/eventhub/event-hubs/README.md

Add a small note to the README.md which notes that when using AAD that
you need to assign a specific role to your principal in order to access
Event Hubs.
In addition, I changed some of the connection strings to be marked as
"code" so they render a little better by default.

[eventhubs] Add a note about Roles for AAD Auth

---

eng/pipelines/doc-index.yml

This is for issue - #6323
The contributing link was not resolved to complete path since we are scoping the script to run within a service folder. But for links which are in the root readme, we will have  to run in the entire repo. The downside though is that the script also picks up other READMEs which are in the node-modules folder(s) of packages under `/common/temp/pnpm-store/2/registry.npmjs.org/`
Reference - https://dev.azure.com/azure-sdk/public/_build/results?buildId=216691&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=9a4ddc9a-5b6e-5495-335e-b34e54a89692
cc: @weshaggard @scbedd

replace relative link in the root readme too

---

sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/partitionLoadBalancer.ts
sdk/eventhub/event-hubs/src/pumpManager.ts
sdk/eventhub/event-hubs/src/util/delayWithoutThrow.ts
sdk/eventhub/event-hubs/test/eventHubConsumerClient.spec.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/loadBalancer.spec.ts

This PR is meant to fix a few issues found while doing some manual testing.
1. [x] consumerClient.subscribe with a single partition should recover until explicitly stopped.
2. [x] Errors related to load-balancing should honor the event processor loop delay. Currently, network connection errors will cause the event processor loop to iterate very quickly without the 10 second delay.
3. [x] When `processClose` is called, the partition should be considered abandoned so it can be reclaimed on the next loop iteration. This currently works when a CheckpointStore is provided, but does not otherwise when reading from all partitions.
4. [x] Swallow errors thrown from user's error handler. Without this, errors could lead to uncaught promise warnings.
~~I still need to tackle the 3rd item as it's a …

[event-hubs] Updates subscribe recovery to be more robust

---

sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts

This PR adds `MessagingError` to the type supported by the error argument taken by the user provided `processError` callback.
This will help in typing when user wants to deal with the messaging error via its `code`

[Event Hubs] Include MessagingError in processError signature

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/migrationguide.md
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/eventDataBatch.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/impl/eventHubClient.ts

This PR attempts to 
- make general improvements to docs on the interfaces
- fix a few more places have stale references in the docs for user facing APIs.
- re-order properties of some of the interfaces in the order of most common usage.
- `EventDataBatch` is no longer a class. So "instance of EventDataBatch` is inaccurate
- update changelog
- update migration guide with behavioral changes when compared to previous version

[Event Hubs] Update API reference docs, changelog & migration guide

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/README.md

There's a standard for readmes and our sections were either just slightly out of order or needed to be promoted to be H2's, rather than H3's.
This fixes the eventhubs-checkpointstore-blob and event-hubs packages.

[event-hubs] readme re-ordering based on doc review

---

sdk/eventhub/event-hubs/test/packageInfo.spec.ts

#6744 Changed the `integration-test:node` script to pull test files from `dist-esm` instead of `dist`. This caused the test that validates that the version constant matches the package.json to fail since it used a relative path to get the package.json.
For now I'm just updating the relative path in the test to unblock our live tests.
I'm a little worried that our script no longer uses the same (bundled) version of the SDK that node.js users would use when running the tests. Getting our samples run in an automated fashion will help with this, and we manually run the samples now before releasing, but would like to make sure we don't miss this going forward.

[event-hubs] fix version test

---

sdk/textanalytics/ai-text-analytics/README.md

The impressions link was improperly formatted after the package rename. Also switched the reference docs to be an aka.ms link so we can forward to the proper docs (on github.io and later docs.microsoft.com)

Fix up README issues for Text Analytics

---

sdk/eventhub/event-hubs/src/diagnostics/instrumentEventData.ts
sdk/eventhub/event-hubs/src/diagnostics/messageSpan.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventPosition.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/impl/eventHubClient.ts
sdk/eventhub/event-hubs/src/partitionLoadBalancer.ts
sdk/eventhub/event-hubs/src/partitionProcessor.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/receiveHandler.ts
sdk/eventhub/event-hubs/src/receiver.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/src/util/operationOptions.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts

I went through the list of exported package members vs what was being displayed in the github io docs.
This should remove all the members that aren't exported from the package's entry point.

[event-hubs] cleanup docs for unexported members

---

sdk/eventhub/event-hubs/migrationguide.md

* Adding in an introduction to the feature of the newer library.
* Fixing broken links to samples, now that they've moved to sub-paths.
Fixes #6604

[event-hubs] migration guide - adding in a "new in V5 feature list" and fixing broken samples links

---

sdk/storage/storage-file-datalake/recordings/browsers/aborter/recording_should_abort_after_aborter_timeout.json
sdk/storage/storage-file-datalake/recordings/browsers/aborter/recording_should_abort_after_father_aborter_calls_abort.json
sdk/storage/storage-file-datalake/recordings/browsers/aborter/recording_should_abort_when_calling_abort_before_request_finishes.json
sdk/storage/storage-file-datalake/test/aborter.spec.ts

Followup of #6786 
Issue - #6891

[Storage] Un-skip browser tests leveraging aborter in storage-file-datalake package

---

sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-file-share/test/node/highlevel.node.spec.ts

The duration of these tests normally is below 100 seconds but
occasionally goes over 2 minutes which is the timeout we specified
for mocha tests. We have seen from storage account logs that downloading
257 MB blob can take over 7 minutes.
This change increases the timeout value of these individual test cases 
to 10 minutes which hopefully should be large enough even for slow network.

[Storage][test] set larger timeout when uploading 257 MB

---

sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-file-datalake/rollup.base.config.js
sdk/storage/storage-file-share/rollup.base.config.js
sdk/storage/storage-queue/rollup.base.config.js

There were types that are imported then re-exported for easy consumption by our
library users. Some of these types triggered rollup warnings like
(!) Unused external imports
RequestPolicyOptions,WebResource imported from external module '@azure/core-http' but never used
Unlike other re-exported things, RequestPolicyOptions is used nowhere in the
library. For a non-test build, this isn't an issue because rollup properly
detects that its re-exported from index.js. For tests, because we're using
multi-entry with exports: false, rollup sees a module with no exports and so all
of a sudden RPO is no longer re-exported and is thus unused.
This change does the following as suggested by @bterlson:
- Add the index file to the input list for tests, and
- Remove the exports: false option for …

[Storage] fix unused import warning in node test rollup

---

sdk/keyvault/keyvault-certificates/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-keys/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-secrets/src/core/challengeBasedAuthenticationPolicy.ts

Adding a check to ensure the resources we use during challenge-based auth are https resources. Throws an exception if they aren't.
@schaabs - is this close to what you had in mind?

[KeyVault] Require resources in challenge based auth to be https

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/partitionLoadBalancer.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/loadBalancer.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts

This "fixes" the problem we're seeing in #6439.
Our code was always assuming that we were allowed an "extra" partition, even
when the partitions would be evenly divisible by the number of processors.
This PR changes that to take into account whether or not we really do want to
have an extra partition.
NOTE: there is still a possibility of deadlock if a new processor comes online and
can't claim it's first partition. This is logged in issue #6945.

[event-hubs] Fixing bug in load balancing algorithm with even numbers of processors.

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts

Fixes #6065 and replaces #6338 
This PR updates the `onDetached` method to call the `finalAction` method of the ongoing receive operation.
This also changes the behaviour of the `finalAction` method so that if the receiveMode is `receiveAndDelete` and there is a detachedError, the promise will resolve with the messages received so far. This change was made because the messages have already been removed from service bus so the user can safely act on them.
I tested by running the following code with the changes in this PR:
```ts
import {ServiceBusClient, ReceiveMode} from '@azure/service-bus';
async function run() {
const client = ServiceBusClient.createFromConnectionString(
"ConnectionString"
);
const queueClient = client.createSubscriptionClient('TOPIC', 'SUBSCRIPTION');
const receiver = …
```

[service-bus] fixes receiveMessages settle issue when disconnected

---

sdk/eventhub/event-hubs/migrationguide.md

Fixes #6604
* Include a link to the Azure SDK for TypeScript guidelines
* Change title of doc to mention the actual package name

[event-hubs] Migration guide changes to point to motivation and additional differences

---

common/smoke-test/smoke-tests.yml

Moving the smoke tests yml file is difficult to test without having the pipeline in `master`.. When the original PR merged it was using a yml file which pointed to the wrong location for the globals.yml. This PR fixes that.

Smoke Tests: correct location for globals.yml

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/variables/globals.yml

This PR adds the logic to lock down the version of doc-warden that is being used in the build pipeline. We are doing this because we want to be able to update the doc-warden package and we don't want a bug to blow up all the pipelines, instead, when we publish doc-warden we can flight usage of the new version with a PR by updating the version in the global variables.

DocWarden version lock-down.

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/storage/storage-blob/review/storage-blob.api.md

- Blob
The change might have been caused by newer version of api-extractor or tsc and now caused warning in the build.
- Cosmos
The parameter `partitionKey` was renamed in #6855 to `partitionKeyValue` but the api report was not updated.

Update Blob and Cosmos api review report files

---

sdk/servicebus/service-bus/test/utils/testUtils.ts

This PR reverts the workaround put in place for #6682 which we no longer need as we now use a clean namespace for every test run

Revert workaround for #6682

---

sdk/eventhub/event-hubs/README.md

EventHubs is GA so we can fix some of the links to just point to the current package.

[event-hubs] Fix broken/outdated links

---

sdk/storage/storage-blob/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-file-datalake/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-file-share/src/policies/StorageRetryPolicy.ts
sdk/storage/storage-queue/src/policies/StorageRetryPolicy.ts

Currently there's no way to configure StorageRetryPolicy to log retries without changing the code. Furthermore, the commented code in current `logf` method relies on `RequestPolicyOptions.log()` method, which depends on `HttpPipelineLogger` argument passed to `RequestPolicy`'s constructor. But there's no option to configure the option when creating a `StorageRetryPolicyFactory` instance.
This change enables retry logging using the same azure logger that we use in other places in storage code. HtttpPipelineLogLevel has four levels: OFF, ERROR, WARNING, INFO, which maps nicely to azure logger's `error()/warning()/info()` methods.

Enable retry logging using azure logger

---

common/scripts/install-run.js
rush.json

- This reverts commit dcd57274dbe9acd7deb3d34173a9582017f71203.
- Reverting to workaround microsoft/rushstack#1723
Verification Build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=244861&view=results

Revert "Update rush to 5.19.1 (#7114)"

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

Resolves #6714
There was a regression in fetch-mock
https://github.com/wheresrhys/fetch-mock/issues/493
which is already fixed in the latest version of fetch-mock.

[core-http][test] revert workaround of pinning fetch-mock version

---

sdk/storage/storage-file-share/test/node/fileclient.spec.ts

which uploads 257 MB data.
Previous change in PR #6950 only covers high level tests.

[storage][test] set larger timeout for fileclient test

---

sdk/core/ci.yml

The sdk/core/ci.yml file had unnecessary quotes around the ServiceDirectory entry. It is the only ci.yml file in the repo with the quotes.

Quick fix for core's CI.yml

---

sdk/test-utils/recorder/src/utils.ts

@sadasant came up with the issue, error is as follows.
```
1) Keys client - create, read, update and delete operations                                                                                                                                        
"before each" hook for "can create a key with requestOptions timeout":                                                                                                                        
Error: Unable to locate the 'recordings' folder anywhere in the hierarchy of the file path /home/vsonline/workspace/sdk/keyvault/keyvault-keys/dist-esm/test/CRUD.test.js                       
Error: 'recordings' folder is not found at /home/vsonline/workspace/sdk/keyvault/keyvault-keys/dist-esm 
```
- Recorder was relying on the package.json as a …

[Recorder] Bug Fix - Verify for `sdk` folder and `rush.json` file along with the `package.json`

---

eng/tools/analyze-deps/index.js
sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/baseRecorder.ts
sdk/test-utils/recorder/src/utils.ts
sdk/test-utils/recorder/test/utils.spec.ts

- While the PR https://github.com/Azure/azure-sdk-for-js/pull/7119 fixed a bug where replacements of query-param parts of recordings aren't acted upon, it checked in with a regression.
- The fix was to call filterSecrets method over the complete recording by converting the content from JSON to string with  `JSON.stringify`.
- The above introduced a new issue where `JSON.stringify` adds an escape character to the plain text strings present in the recordings and the callback functions with regex replacements weren't expecting the escape characters.
Hence the callback functions failed to filter the recordings properly.
- There are even more issues if we rely on `JSON.stringify`, if applied twice, it would add escape characters everywhere.
- Instead of relying upon the `JSON.stringify`, came …

[Recorder] Bug Fix - Filter secrets from JSON

---

sdk/test-utils/recorder/package.json

Moving dependencies and devDependencies around appropriately.

[Recorder] Cleanup - Moving around the devDependencies

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml
sdk/storage/storage-queue/tests.yml
sdk/storage/test-resources-post.ps1
sdk/storage/test-resources.json

Unlike Blob and File storage, there are no documented approaches to specifying CORS rules using ARM. This uses a feature of the resource provisioner to run a powershell [command](https://docs.microsoft.com/en-us/powershell/module/az.storage/set-azstoragecorsrule?view=azps-3.3.0) that will set CORS rules for queues.

add script to set CORS rules for storage queue testing

---

sdk/core/core-http/lib/policies/deserializationPolicy.ts

In PR #7173 we removed some sanitization logic, but accidentally also removed setting the response and request on RestError.

Add request/response back to deserialization error

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/lib/webResource.ts
sdk/core/core-http/lib/xhrHttpClient.ts

Issue - https://github.com/Azure/azure-sdk-for-js/issues/5747
https://github.com/Azure/azure-sdk-for-js/issues/5747#issuecomment-580012332
`requestOptions timeout` test is failing in the browser while it succeeds in node.
The test expects AbortError to be thrown.
Upon some digging through the internals of it in core-http, found this..
In node, we do a setTimeout with abort().
In browser, we are throwing a new error instead of the AbortError - This is the only difference and the reason for test failure.
Updated the `core-http` timeout to throw abort error instead just as suggested by the reviewers.

[core-http] Fix the error inconsistency of requestOptions.timeout - node vs browser

---

sdk/core/core-http/lib/policies/deserializationPolicy.ts

This PR refactors the `deserializeResponseBody()` function with the below intentions
- Remove the code path for `CloudError`. This is dead code and we do not support a generic `CloudError` anymore. It was for an intermediate phase where Swagger Spec did support it, but @sarangan12 has confirmed that no existing swagger specs use it anymore
- Remove type declarations when it can be inferred by the assigned value
- Flip `if` checks to support early exit
- Add comments
Tip to review: Use the `Hide white space changes` setting to reduce the noise in the diff

[core-http] Refactor deserialze method for simplicity

---

eng/tools/analyze-deps/index.js

This is to allow dependency graph data.js to have only the internal dependencies by default. If external dependencies are required, they can be generated using the `--external` flag

Dependency report data.js to exclude external dependencies by default

---

sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_analyzesentiment/recording_service_returns_an_error_for_an_empty_document.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_analyzesentiment/recording_service_returns_error_for_invalid_language.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_detectlanguage/recording_service_errors_on_invalid_country_hint.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_extractkeyphrases/recording_service_errors_on_unsupported_language.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_recognizeentities/recording_service_errors_on_unsupported_language.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_recognizelinkedentities/recording_service_errors_on_unsupported_language.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_recognizepiientities/recording_service_errors_on_unsupported_language.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_analyzesentiment/recording_service_returns_an_error_for_an_empty_document.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_analyzesentiment/recording_service_returns_error_for_invalid_language.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_detectlanguage/recording_service_errors_on_invalid_country_hint.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_extractkeyphrases/recording_service_errors_on_unsupported_language.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_recognizeentities/recording_service_errors_on_unsupported_language.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_recognizelinkedentities/recording_service_errors_on_unsupported_language.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_recognizepiientities/recording_service_errors_on_unsupported_language.js
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
sdk/textanalytics/ai-text-analytics/src/detectLanguageResult.ts
sdk/textanalytics/ai-text-analytics/src/extractKeyPhrasesResult.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/src/recognizeCategorizedEntitiesResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizeLinkedEntitiesResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizePiiEntitiesResult.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsResult.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md
sdk/textanalytics/ai-text-analytics/test/collections.spec.ts
sdk/textanalytics/ai-text-analytics/test/error.spec.ts
sdk/textanalytics/ai-text-analytics/test/textAnalyticsClient.spec.ts

This PR adds a convenience layer to the text analytics error model that flattens out the `innerError` hierarchy, since TA only supports one nested inner error.
Effectively, we are swallowing the generated TextAnalyticsError and InnerError and replacing them with a single TextAnalyticsError that is not generated.
We override the ErrorCode enum because there is a discrepancy between the string literals specified in the swagger and the string literals that we observe during testing. The new model has only `code`, `message`, and an optional `target` (though I couldn't find a scenario in which I could make the service return anything other than `target: undefined`.
I also fixed a couple of typos (makeTextAnalysisResult -> makeTextAnalyticsSuccessResult and makeTextAnalysisErrorResult -> …

[ai-text-analytics] Unify TA error model

---

sdk/storage/storage-blob/src/Clients.ts

The change in swagger was added to 2019-02-02 but we didn't pick it up and re-generate.
Do this in Jul19 release once and for all.

[Storage][Blob] add md5 and crc headers for copy blob from URL 

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts

This removes the ATOM based service bus from the entry point since it is not yet ready for GA. This feature has not been shipped yet.

[service-bus] disable atom-based client

---

sdk/core/core-paging/CHANGELOG.md
sdk/core/core-paging/package.json
sdk/core/core-paging/types/corePaging.d.ts

Currently `PageSettings` was locked to a specific shape, but there are services like Cognitive Search that do not support `maxPageSize` and have complex continuation logic (i.e. here's the object bag of request options to change for the next page.)
This PR genericizes the page settings so that a service client can specify what options are interesting to a paged request.

Genericize PageSettings in PagedAsyncIterableIterator

---

sdk/core/core-paging/types/corePaging.d.ts

The new additional generic type param wasn't passed recursively.

Fix small issue in PR #7283

---

sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/test/functional/conflict.spec.ts

Fixes a bug where if you accidentally passed `forceQueryPlan` to a non-item resource it would throw an error. Long term we should split up the QueryIterator

[Cosmos] Fix bug in QueryIterator for non-item resources

---

sdk/textanalytics/ai-text-analytics/samples/typescript/tsconfig.json

(CC @bterlson @xirzec )
While testing for the TA release, I discovered that our TA TypeScript samples have been broken for a little bit due to a bug in the tsconfig.
When we introduced the `error?: undefined` discriminant in `TextAnalyticsSuccess`, we needed to set "strict" in the sample tsconfig (specifically "strictNullChecks", because otherwise TSC can't use `null` or `undefined` as a discriminant, since they would be valid for all types.
Adding both "strict" and "alwaysStrict" will make the published tsconfig more similar to the one we use for builds.
This was a particularly strange one to debug.

[ai-text-analytics] hotfix: use `"strict": true` in sample tsconfig

---

sdk/core/core-http/lib/policies/proxyPolicy.ts
sdk/core/core-http/test/policies/proxyPolicyTests.node.ts

by extracting then removing them from the url and parse the updated
url as URLBuilder doesn't support them.
For #5011

[core-http] support username and password in proxy url string

---

sdk/storage/storage-blob/api-extractor.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/tsconfig.json
sdk/storage/storage-file-datalake/api-extractor.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/tsconfig.json
sdk/storage/storage-file-share/api-extractor.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/tsconfig.json
sdk/storage/storage-queue/api-extractor.json
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/tsconfig.json

Since TypeScript 3.7 introduced an incompatible change to their typings files, we have to generate a downlevel version that works with 3.1 -> 3.5.
Fixes #7296

[storage] Fix typings support for TypeScript 3.1

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml
sdk/storage/storage-blob/tests.yml
sdk/storage/storage-file-datalake/tests.yml
sdk/storage/storage-file-share/tests.yml
sdk/storage/storage-queue/tests.yml

Even in the case of test timing out the build should be finished under one hour.
Shortening the timeout to 60 minutes so we are not wasting build agent resource.

Shorten timout for storage live tests to 60 minutes

---

.gitignore

What script generates these files? Once I remove this line, after I run `rushx build` in these three packages, no untracked files appear on the tree.
Fixes #7370

[KeyVault] Seems like this line isn't needed

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/globalEndpointManager.ts
sdk/cosmosdb/cosmos/test/functional/globalEndpointManager.spec.ts

Currently, you can only pass the full name: "East US 2"
This PR allows passing the full name OR a normalized URL name: "eastus2"

[Cosmos] Normalize when selecting preferredLocation endpoints

---

sdk/core/core-http/lib/serializer.ts
sdk/core/core-http/lib/util/utils.ts
sdk/core/core-http/rollup.base.config.js
sdk/core/core-http/test/utilsTests.ts

The regression was introduced in #4916, when the local variable `validUuidRegex` was moved out of the function into a const.  Regex `test()` with global flag set will change the state of the regex (advancing the `lastIndex`) and cause next `test()` to fail in our case.  We don't need the global flag here for validating a uuid string.
This change removes the global flag from `validUuidRegex` constant.
I also remove usage of regex global flags in serializer.ts since they are all used to match single lines.

[core-http] Fix utils isValidUuid() regression

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/sender.ts

**Bug**
- Send a message with `scheduleMessage()` method from the SDK.
- Receive the message through the Azure Function Triggers or [Service Bus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer), the received message is `undefined` or corrupted.
(the same is not the case when received the message with `Receiver.registerMessageHandler` from the sdk, which is the reason why the bug wasn't discovered till now)
**Fix**
- Encoding the message would fix the above issues.
- dataTransformer.encode() on the message body just like the sendBatch()
- removing the workaround that was added #6983 
**User Issue** - #6816 
**More info** - https://github.com/Azure/azure-sdk-for-js/issues/6816#issuecomment-574461068

[Service Bus] Encoding the message.body in the scheduleMessages method

---

sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-blob/test/node/utils.spec.ts
sdk/storage/storage-file-datalake/src/utils/utils.node.ts

The utility function `streamToBuffer2()` had two logic bugs:
1. If `pos == bufferSize`, and the next call to `stream.read()` would return null, the method should succeed rather than fail.  This is covered by the test cases where `streamType == test` and `buffer.length == stream.length`.
https://github.com/Azure/azure-sdk-for-js/blob/9da9f89ae29e2c233b8fc6530c2667eb95c40d52/sdk/storage/storage-blob/src/utils/utils.node.ts#L86-L94
2. If the last chunk exceeded the remaining size in the buffer, it would be sliced and the method would succeed, however it should throw since the buffer was too small.  This is covered by the test cases where `buffer.length < stream.length`.
https://github.com/Azure/azure-sdk-for-js/blob/9da9f89ae29e2c233b8fc6530c2667eb95c40d52/sdk/storage/storage-blob/src/utils/u …

[Storage] Fix logic bugs in streamToBuffer2()

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/index.ts
sdk/core/core-amqp/src/util/utils.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/index.ts
sdk/eventhub/event-hubs/src/models/public.ts
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts

Issue - #7066 
First draft - https://github.com/HarshaNalluru/azure-sdk-for-js/pull/26
Moved `WebSocketOptions` from eventhubs to core-amqp upon @ramya-rao-a's suggestion to avoid duplication.

[Service Bus] [Event Hubs] Update websocket options shape

---

eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/stages/cosmos-sdk-client.yml

The problem here is that the ServiceDirectory parameter from the ci.yml wasn't fully plumbed through to the archetype-js-release.yml which never needed it until now.

Plumb ServiceDirectory parameter variable through release pipelines

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/test/index.spec.ts

AppConfig has tightened the rules on where wildcards can be used within filter strings for labels and keys. AppConfig is pre-GA so changes like this should not be considered "breaking".
This PR alters the JSDoc comments to reflect that change.

[app-configuration] Updated documentation to reflect that key/label filters have changed

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml
sdk/eventhub/event-processor-host/tests.yml
sdk/servicebus/service-bus/tests.yml
sdk/storage/storage-blob/tests.yml
sdk/storage/storage-file-datalake/tests.yml
sdk/storage/storage-file-share/tests.yml
sdk/storage/storage-queue/tests.yml

and override the parameter for service bus and event process host as their
normal passing builds take more time.

Change default live tests pipeline timeout limit to 60 minutes

---

sdk/keyvault/keyvault-certificates/test/mergeAndImport.test.ts
sdk/keyvault/keyvault-keys/test/crypto.test.ts

After merging the recorder.skip changes, the nightly builds highlighted that our browser live tests are now failing. This is due to the fact that some of these tests are not expected to ever run on the browser, and `recorder.skip` will not work if `TEST_MODE` is `live`.

[KeyVault] Live test browser fixes

---

sdk/core/core-lro/package.json
sdk/core/logger/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/servicebus/service-bus/package.json
sdk/template/template/package.json
sdk/test-utils/recorder/package.json
sdk/textanalytics/ai-text-analytics/package.json

It is not recommended to map rolled-up files in the browser section. This change
removes them.

Remove bundled browser file from browser mapping

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/managementClient.ts

Adds the security_token field for management apis in event hubs. Java and .NET already do this.
While testing event-hubs in Azure Stack we observed that the management APIs would throw unauthorized errors if the security_token wasn't present.

[event-hubs] add security_token to management apis

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml

as Azure devops pipeline only supports publishing one set of code coverage result. Publishing for both NodeJs and
browser would result in one of the report overwrites the other.
Instead browser code coverage report are uploaded as an artifact.

Disable publishing browser code coverage report

---

sdk/storage/storage-blob/recordings/browsers/blobclient/recording_undelete.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_undelete.js
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts

The service may return a segment with a valid continuation token, but
with empty result array. In this case we need to keep getting next
page until we have a non-empty result array.
Remove the duplicate "BlobClient Node.js only undelete" test

[storage][test] fetch next page until non-empty result array

---

common/config/rush/common-versions.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

Increase minimum core-http version from 1.0.0 to 1.0.3 to incorporate important bug fixes.
One data-loss bug fixed in 1.0.3 is #6656
cc @jeremymeng

require core-http version of ^1.0.3

---

sdk/core/core-http/lib/restError.ts
sdk/core/core-http/lib/util/sanitizer.ts

In #7173 we sanitized `RestError` for when it was output by Node to avoid leaking sensitive information.
Unfortunately, the way we did it uses JSON.stringify which respects if properties are enumerable or not, and all `Error` properties are non-enumerable by default.
This PR tries to fix things up a bit by:
- Giving `RestError` and appropriate `name` property.
- When serializing Errors, promoting `name` and `message` to being included.
- When emitting the output shape of `RestError`, including some preamble with the message, as Node normally does for errors.
I didn't include the `stack` property since the printing was very awkward. It included the message and didn't print the newlines correctly, so it was very hard to read, e.g.
```
"stack": "RestError: The request is invalid. Details: …
```

Improve RestError output in Node

---

sdk/eventhub/event-hubs/karma.conf.js

@jeremymeng found that I missed updating remap-coverage meant for karma-remap-coverage for event hubs in the PR - https://github.com/Azure/azure-sdk-for-js/pull/7496

[Event Hubs] Code coverage in browsers - leftovers

---

sdk/core/core-lro/test/abort.test.ts

Before this PR, the changed test passes using tslib 1.10.0, but not with tslib 1.11.0. This is due to the fact that tslib 1.11.0 includes a fix to the async scheduling generated by TypeScript https://github.com/microsoft/tslib/pull/70
To address this, this PR makes a slight change that properly awaits for the pollUntilDone method to finish before asserting the exception.

[core-lro] Using await to test that pollUntilDone throws

---

sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-blob/tests.yml
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/test/node/fileclient.spec.ts
sdk/storage/storage-file-share/test/node/highlevel.node.spec.ts
sdk/storage/storage-file-share/tests.yml

- double the time for large data tests to 20 minutes. We have seen them passing
closer to 10-minute mark.
- increase global mocha timeout to 5 minutes
- increase pipeline time out for blob and file-share to 90 minutes.

[Storage] increase live test timeout limits

---

sdk/test-utils/recorder/.nycrc

Code coverage report wasn't being generated, the reason being `.nycrc` config's absence.

[Recorder] nyc code coverage config for the recorder tests

---

eng/.docsettings.yml

The nightly builds started failing after Synapse was merged to master due to its README not conforming to the expected format. This is a code-generated data-plane SDK, not one of our track2 SDKs that are added to the rush list.

[ci] add synapse readme to exceptions list

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/package.json
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

Updated core-amqp to 1.1.0 from 1.0.2 because exporting `WebSocketOptions` is considered a feature, not a bug fix.
Also updated event-hubs and service-bus to depend on this version of core-amqp.
For background info, WebSocketOptions used to be exported from event-hubs, but is now exported from core-amqp so service-bus can reference them as well. Boths ervice-bus and event-hubs will re-export WebSocketOptions.

[core-amqp] prepare for 1.1.0 release

---

dataplane.code-workspace

Check in a helper file for VS Code to easily load all of our track2 data-plane packages. 
More details: https://code.visualstudio.com/docs/editor/multi-root-workspaces
This mirrors the set of packages managed by Rush.

Create new workspace for data-plane packages

---

sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/test/node/sas.spec.ts
sdk/storage/storage-file-share/src/ShareClient.ts
sdk/storage/storage-file-share/test/node/sas.spec.ts

According to https://docs.microsoft.com/en-us/rest/api/storageservices/set-container-acl and https://docs.microsoft.com/en-us/rest/api/storageservices/set-share-acl, "When you establish a stored access policy on a container, it may take up to 30 seconds to take effect. During this interval, a shared access signature that is associated with the stored access policy will fail with status code 403 (Forbidden), until the access policy becomes active.".
This PR fix the unstable access policy accordingly.

[Storage] Fix unstable access policy SAS cases.

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_detectlanguage/recording_client_accepts_none_country_hint_with_detectlanguageinput_input.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_detectlanguage/recording_client_accepts_none_country_hint_with_string_input.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_detectlanguage/recording_client_accepts_none_country_hint_with_detectlanguageinput_input.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_detectlanguage/recording_client_accepts_none_country_hint_with_string_input.js
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/generated/textAnalyticsClientContext.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md
sdk/textanalytics/ai-text-analytics/test/collections.spec.ts
sdk/textanalytics/ai-text-analytics/test/textAnalyticsClient.spec.ts

This is the set of renames and tweaks to APIs with changelog updates for preview.3 of TextAnalytics
- id -> dataSourceEntityId
- length, offset -> graphemeLength, graphemeOffset
- sentimentScores -> confidenceScores, SentimentScorePerLabel -> SentimentConfidenceScorePerLabel
I also
- Removed the PR numbers from the changelog, since they don't link correctly anyway and other packages don't have them.
- Re-recorded tests.

[ai-text-analytics] API changes for Preview 3

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/src/index.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

This changes the type name from SentimentConfidenceScorePerLabel to SentimentConfidenceScores to align with a rename in Java and .NET.

[ai-text-analytics] Rename type for SentimentConfidenceScores

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/mappers.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

Rename `characterCount` to `graphemeCount` in DocumentStatistics for consistency with use of "grapheme" in response objects.

[ai-text-analytics] characterCount -> graphemeCount

---

package.json

This has started breaking CI due to an outdated dependency, but I don't think the management libs actually use/need this.

Remove webpack dependency from root

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/README.md
sdk/textanalytics/ai-text-analytics/src/generated/generatedClient.ts
sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

This PR:
- adds more examples showing the usage of the library to the README
- brings the README key concepts in line with newer conceptual copy
- adds the release date to the CHANGELOG
- renames `TextAnalyticsClient` in `src/generated` to `GeneratedClient` in order to avoid a name collision in generated reference documentation

[ai-text-analytics] Repo Documentation Fixes for Preview 3

---

sdk/eventhub/event-hubs/src/eventPosition.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts

In response to https://github.com/microsoft/TypeScript/pull/27591

[event-hubs] better type guards for event position

---

sdk/eventhub/eventhubs-checkpointstore-blob/samples/downlevelContainerClient.js
sdk/eventhub/eventhubs-checkpointstore-blob/samples/downlevelContainerClient.ts
sdk/eventhub/eventhubs-checkpointstore-blob/samples/receiveEventsWithDownleveledStorage.js
sdk/eventhub/eventhubs-checkpointstore-blob/samples/receiveEventsWithDownleveledStorage.ts

This adds a sample that illustrates how to downlevel the Storage Blob `ContainerClient` to target an older API version. This can be useful when running this code against an older version of the service.

[eventhubs-checkpointstore-blob] add sample for downleveling storage blob

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

Fix documentation issues to align with the [documentation guide](http://aka.ms/jointhesdk/docs)
**TODO**
- README: add `Authenticate the client` section

[Storage] align with documentation guide

---

sdk/cosmosdb/cosmos/rollup.config.js

As @southpolesteve suggested a long time ago.. this PR is to update the rollup config to make it throw errors if circular dependencies are present instead of warnings. 
All the existing circular dependencies have been fixed in https://github.com/Azure/azure-sdk-for-js/pull/5256 and https://github.com/Azure/azure-sdk-for-js/pull/5374. This PR is to make sure we don't regress and introduce new circular dependencies.

[Cosmos] Rollup - throw errors if circular dependencies are present

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/constructorHelpers.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/models.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/test/track2.samples.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

Public surface had some issues:
- `ServiceBusClient` wasn't exported from index.ts (and thus a few associated types were _also_ not properly exported)
- Some older code from preview 0.01 were still exported (QueueAuths, etc..). Those have been removed
I also changed over some tests to:
- Run in the browser
- Import some of the critical classes via `..\src` rather than by file, giving a _little_ extra check the critical types are exported properly.

[service-bus] track2 - fixing issues with the public surface (ServiceBusClient)

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/src/requestResponseLink.ts

During the CBS claim negotiation, `"$cbs" time out` might occur in case the service is unavailable.
This PR attempts to update the timeout from 10s to 60s as per the recommendation from the service team.
This requires updating the `amqp-common` library with the fix (and publishing it to npm) and then updating service-bus track 1 library to use the latest `amqp-common` library.
Fixes part of https://github.com/Azure/azure-sdk-for-js/issues/7786

[amqp-common] Increase timeout from 10s to 60s to avoid `"$cbs" timeout`s

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/request/ResourceResponse.ts

Currently the types indicate resource will never be undefined but that
is not the case when nothing is returned from a query in Cosmos. This
fix causes API to break in a sense that it may result in compile errors
however these compile errors may be masking bugs when the consumer is
using strict null checking.
Fixes #7819

Make ResourceResponse.resource optional

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/steps/generate-doc.yml

Cancelled original plan - 
- Typedoc 0.17.0 requires TS 3.8.3 as peer dependency 
- We need to global install Typedoc since we run the Typedoc command, that is why we need to global install TS  in this PR
----Change in plans ------
Typedoc 0.17.0 is exposing internal variables while generating docs. So will pin to 0.16.x for now until further investigation. 
- moving generate doc steps into separate pipeline for sanity purpose

Pinning to Typedoc 0.16.x until further investigation

---

eng/tools/generate-doc/theme/default/assets/js/get_options.js

Before we can swap over entirely, we need to make certain all the existing package version info is up to date with the new methodology. I am going to use a one-off script to make this update across the board.

Handling Sorted Versions Files

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/README.md
sdk/servicebus/service-bus/samples/typescript/README.md

This PR removes the YAML frontmatter from our samples so that 2.0.0-preview.1 samples don't overwrite the working samples on docs.microsoft.com.
It also references the older samples, source, and NPM package through stable links in the README similar to Event Hubs.

[service-bus] Remove samples frontmatter and reference old version in README

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts

`ServiceBusAtomManagementClient` is not exposed by the Service Bus public facing apis at the moment. Removing all other related interfaces and classes to keep the public surface clean

[Service Bus] Remove lingering artifacts for management apis

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/receivers/shared.ts
sdk/servicebus/service-bus/src/receivers/subscriptionRuleManager.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/deferredMessage.spec.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts
sdk/servicebus/service-bus/test/topicFilters.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts
sdk/servicebus/service-bus/test/utils/transitional.ts

This PR makes it so you can now create dead letter receivers and subscription rule management from the client, removing some clutter that was appearing on the Receiver interface.
Fixes #7815 
Fixes #1424

[service-bus] Preview.1 - create separate rule manager and dead letter receiver methods.

---

sdk/core/core-lro/README.md

While reading the docs I notice 2 typos

[core-lro] Fix 2 typos in README

---

sdk/core/core-http/src/policies/deserializationPolicy.ts
sdk/identity/identity/src/client/identityClient.ts
sdk/search/search/src/searchIndexClient.ts
sdk/search/search/src/searchServiceClient.ts

Replaces the fix done by #4975 to only apply to the identity package.
This prevents clients that have text/plain endpoints from getting serialization errors with the defaults.

[core-http] Fix default deserialization policy

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/deadLetter.spec.ts

deadLetter() changes and fixes!
- Function arguments have now been made consistent with the other settlement methods - it takes a propertiesToModify with two extra named fields called out (deadLetterReason, deadLetterErrorDescription) but is otherwise just an object.
- Fixed bug where it wasn't actually setting the error description and reason when the message being settled was a deferred message.
- Fixed a similar bug where it wasn't properly setting custom properties either. There's more to do here, filed as issue 7959.
Sundry:
- There was a slight (but annoying) mis-casing in the DeadLetterOptions for deadLetterReason
Fixes #7958

[service-bus] deadletter() changes for API compliance and bugs

---

sdk/core/core-http/src/webResource.ts
sdk/core/core-http/test/webResourceTests.ts

Porting fix from Azure/azure-sdk-for-node#5143

[core-http] Support dashes in parameter names

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventData.ts
sdk/eventhub/event-hubs/src/util/constants.ts
sdk/eventhub/event-hubs/test/eventdata.spec.ts

Fixes #7801 
Since `systemProperties` was already an object with an index signature of string to any, no API changes were needed to support this.
It also turned out every one of the properties added is a typed field on the amqp message.

[event-hubs] set known amqp props on systemProperties

---

sdk/servicebus/service-bus/test/utils/testutils2.ts

Swapping `actual` and `expected` fields for should.equal appropriately.

[Service Bus] Test utils improvement - Swap [`actual`,`expected`] fields for should.equal

---

sdk/servicebus/service-bus/src/modelsToBeSharedWithEventHubs.ts
sdk/servicebus/service-bus/test/receiveAndDeleteMode.spec.ts
sdk/servicebus/service-bus/test/stress/stress_fixedNumberOfClientsMultipleQueues.ts
sdk/servicebus/service-bus/test/stress/stress_fixedNumberOfClientsSingleQueue.ts
sdk/servicebus/service-bus/test/stress/stress_messageRandomDisposition.ts
sdk/servicebus/service-bus/test/stress/stress_sessionManualLockRenewal.ts
sdk/servicebus/service-bus/test/stress/stress_singleMessageComplete.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

Running the formatter to avoid noise in PRs that contain non-formatting changes

Run formatter on Service Bus

---

sdk/servicebus/service-bus/README.md

During the preview users will get the latest released preview build using the @next tag. Just swapping over from the @dev tag since the release is imminent.

[service-bus] Track 2 - use the @next tag for npm install

---

sdk/servicebus/service-bus/test/sendBatch.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

Issue - #8019 
Fixing the flakey `receiveBatch` for sessions with a higher `maxWaitTime`.

[Service Bus] Fix sendBatch test's cleanup failure for sessions

---

sdk/appconfiguration/app-configuration/test/index.spec.ts

During test cleanup we do all the deletes for all the settings we've created in parallel. 
It appears we're getting throttled so, to fix that, I've changed it to do them serially instead.

[app-configuration] Fixing some test suite timeouts from too many parallel requests

---

sdk/identity/identity/package.json
sdk/identity/identity/src/credentials/defaultAzureCredential.browser.ts

PR #7994 introduced a build break to rollup by referencing `process` inside `DefaultAzureCredential`.
This fix adds a browser version of `DefaultAzureCredential` without the reference to `process`.

[identity] Fix browser bundle issue

---

common/config/rush/common-versions.json
sdk/storage/storage-blob/README.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/recordings/node/blockblobclient_nodejs_only/recording_should_not_decompress_during_downloading.js
sdk/storage/storage-blob/rollup.base.config.js
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/test/node/blockblobclient.spec.ts
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/Pipeline.ts
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-share/README.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/recordings/node/fileclient_nodejs_only/recording_should_not_decompress_during_downloading.js
sdk/storage/storage-file-share/rollup.base.config.js
sdk/storage/storage-file-share/src/Pipeline.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/test/node/fileclient.spec.ts
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts

The default behavior of node-fetch client is to decompress according
to `Accept-Encoding` when retrieving data. In blob storage it is
supported to set the content encoding of blobs so that browsers and
other clients can decompress accordingly. However we don't want this
behavior in our SDK libraries, because
- there's inconsistency between incoming data and outgoing data. Most
customers would not expect `client.download()` would give them
different data than what they upload in compressed format.
- Retry for partial response would not work on the decompressed response.
This change disables the decompression behavior for storage clients in
NodeJS.
Note that for browsers we don't have control and browser will always
honor the `Accept-Encoding` header and decompress accordingly.
Related to …

[Storage] disable decompression of response when downloading

---

sdk/eventhub/eventhubs-checkpointstore-blob/rollup.base.config.js
sdk/keyvault/keyvault-certificates/rollup.base.config.js
sdk/keyvault/keyvault-keys/rollup.base.config.js
sdk/keyvault/keyvault-secrets/rollup.base.config.js

PR #7994 also introduced a problem where a new dependency `keytar` is not bundle safe and needed to be excluded in test bundles that referenced it indirectly via @azure/identity.

[identity] Fix build:test break

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/tools/publish-to-npm.ps1
sdk/template/ci.yml
sdk/template/template/CHANGELOG.md
sdk/template/template/package.json

Move archetype-js-release.yml into the public repo.
Add dependsOn: PublishPackage for PublishDocs and UpdatePackageVersion deployments.
This PR Depends on https://github.com/Azure/azure-sdk-tools/pull/439

Make JS Release Stage Public

---

eng/tools/generate-doc/theme/default/assets/js/get_options.js

When you visit a page like [this one](https://azuresdkdocsdev.blob.core.windows.net/$web/python/azure-core/latest/index.html) (notice the `latest` instead of a valid version) we want the drop down to properly default to the actual latest released version.

Correctly select version if on the "latest" page

---

sdk/servicebus/service-bus/package.json

https://github.com/Azure/azure-sdk-for-js/pull/8074 PR seems to have unintentionally disabled the integration-tests, Fixing that here.

[Service Bus] run all the tests with integration-test command

---

sdk/eventhub/event-hubs/src/models/public.ts
sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/connectionContext.ts
sdk/servicebus/service-bus/src/constructorHelpers.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/util/constants.ts

- Disable dataTransformer by removing from the ClientOptions to be in sync with event-hubs
- Version 5.0.0 to 7.0.0
- Update API report

[Service Bus] Removing `dataTransformer` from the ClientOptions

---

sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/serviceClientTests.ts

This small change avoids JSON.stringifying strings when sending them to text/plain endpoints.
This will work assuming it is expected that an operation spec for a text/plain endpoint should have a contentType including `text/plain`, which is presently not the case in the latest autorest.

[core-http] Support text/plain request endpoints

---

sdk/core/core-auth/CHANGELOG.md
sdk/core/core-auth/api-extractor.json
sdk/core/core-auth/package.json
sdk/textanalytics/ai-text-analytics/test/tracing.spec.ts

When we released core-auth 1.1.0 today, I didn't catch an issue with the types file being incompatible with older versions of TypeScript. This is a 1.1.1 patch version that adds the downleveled types to the package.
I've tested this with the Text Analytics samples by packing core-auth and installing/building using TS 3.1.
@bterlson and @xirzec I think this is everything I need to do to make the downleveling work, but I'm not 100% sure so I'd appreciate your checking this.

[core-auth] hotfix to provide downleveled types

---

sdk/search/search/CHANGELOG.md
sdk/search/search/package.json
sdk/search/search/review/search.api.md
sdk/search/search/src/base64.browser.ts
sdk/search/search/src/base64.ts
sdk/search/search/src/indexModels.ts
sdk/search/search/src/searchIndexClient.ts
sdk/search/search/src/shims.d.ts
sdk/search/search/test/base64.spec.ts

Give users an opaque string for continuation instead of exposing service internals.
Fixes #7843
Related to Azure/azure-sdk-for-net#10590

[search] Create continuation token.

---

sdk/identity/identity/CHANGELOG.md

This adds a line to the changelog about the new VSCode credential.

[Identity]Add line to changelog about VSCode credential

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionState.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/topicFilters.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesLoop.ts
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/models.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/deadLetter.spec.ts
sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/track2.samples.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

Fixes #8165 by renaming the `maxWaitTimeInSeconds` parameter to `maxWaitTimeInMs`

[Service Bus] maxWaitTimeInSeconds -> maxWaitTimeInMs

---

common/config/rush/pnpm-lock.yaml

This rush update --full will fix the storage daily dev builds as it will remove the core-http 1.0.4 reference from lock file

rush update --full

---

sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/receivers/subscriptionRuleManager.ts
sdk/servicebus/service-bus/src/sender.ts

The retry() method takes an abort signal and uses it abort the waiting done in between retries.
This PR ensures that the abortSignal gets passed in to this method.

[Service Bus] Pass abortsignal to retry()

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serviceBusClient.ts

This PR updates the parameter names in the client constructor to match with those in Event Hubs after the internal API review 
Reference: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/src/eventHubProducerClient.ts#L84-L108

[Service Bus] Update param names to match those in Event Hubs

---

sdk/textanalytics/ai-text-analytics/README.md

Through experimenting with the samples I found out (and confirmed with @xirzec) that unlike several other services the `Owner` role in AAD does not grant access to read/write the API in Cognitive Services. The `Cognitive Services {User,Contributor,Data Reader}` roles are required. For testing I usually create a resource and assign an SP to be an owner of that resource, so I spent some time today debugging why that wasn't working for our token RBAC samples. 
We figure it would be good to add a callout that mentions this for users messing with the samples.

[ai-text-analytics] added note to readme about roles

---

sdk/core/core-http/README.md
sdk/core/core-http/samples/index.html
sdk/core/core-http/samples/index.js
sdk/core/core-http/samples/node-sample.ts

- update instructions to obtain an access token
- fix request policy factories. When factories are passed in, the
credential passed to constructor is not used.
- revamp browser sample to use the Parcel bundler as we no longer
ship the browser distribution.
Fixes #7589

[core-http] Update sample

---

sdk/keyvault/keyvault-certificates/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts

The testClient's "flush" methods wait until the resource is deleted, then purge the resource, but they can't wait for the resource to finish being purged, therefore we can't trust that we can recover the backup at any reasonable time. We've already contacted the KeyVault service team to see if they can make the purge methods LRO-friendly. If they do that, we will be able to clean this up and simply use LROs.
With this PR, these tests will only run in `record` and `playback` mode. We have unlimited time to wait for recordings to happen, and playback tests don't experience any timeout. Live tests won't encounter this problem after this PR.

[KeyVault] Restore backup tests cannot be trusted to run live

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/test/textAnalyticsClient.spec.ts

This PR guards all of our methods on TextAnalyticsClient with `Array.isArray` and checks to make sure the length is not zero.
This is to avoid sending requests to the Text Analytics service that are guaranteed to return an HTTP error so that we can provide a more instructive message.
We already tested the empty input case and asserted that it would throw, so all I've done on the tests is add a regexp to validate the Error message.
This is the last change to be included in preview 4, so I've also updated the CHANGELOG to include the release date.

[ai-text-analytics] Throw an Error when documents is empty

---

sdk/identity/identity/package.json
sdk/identity/identity/src/client/identityClient.ts
sdk/identity/identity/src/util/authHostEnv.browser.ts
sdk/identity/identity/src/util/authHostEnv.ts
sdk/identity/identity/test/identityClient.spec.ts

Built from https://github.com/Azure/azure-sdk-for-js/pull/8001, this allows you to use the AZURE_AUTHORITY_HOST from your environment, if available.

[Identity] Add the ability to read AZURE_AUTHORITY_HOST from environment

---

sdk/servicebus/service-bus/test/invalidParameters.spec.ts

browseMessages operation accepts "undefined" as fromSeqNum, so removing the tests.

[Service Bus] Fix test failures

---

sdk/identity/identity/src/util/authHostEnv.ts

The auth host function will now return undefined if the environment variable isn't available.  This should allow the defaults to work.

[Identity] Fix the auth host function if the environment variable isn't available

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/abortSignal.spec.ts

Support aborting (at least on init and retries) for when the user sends.
Future work: move this support deeper into the stack so we can start properly aborting, rather than setting up a timer around init().

[service-bus] Adding in AbortSignal support for sending messages

---

sdk/keyvault/keyvault-certificates/test/list.test.ts
sdk/keyvault/keyvault-keys/test/list.test.ts
sdk/keyvault/keyvault-secrets/test/list.test.ts

This PR is for my own sanity. This shouldn't affect the builds other than reducing build time, but these tests right now are not valuable on CI. I am planning to clean this up once we release the new test guidelines. For now, all I want is to not see them running on CI.

[KeyVault] Forcing the purge tests to run only on record

---

sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

I'm wrapping this PR at this stage. I've added some "TODO"s in the file...
"TODO"s are beyond the scope of this PR, the existence of "name" property on sbClient, "isClosed" on a sender, and the error messages depending on them, etc. - Logged #8192

[Service Bus] Port track 1 tests to track 2 - Part 2

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/src/request/FeedOptions.ts
sdk/cosmosdb/cosmos/test/integration/query.spec.ts

@azure/cosmos V2 has two different but equivalent ways to specify the partition key for a query:
```js
// V2 These are effectively the same
container.items.query("SELECT * from c", { partitionKey: "foo" }).toArray();
container.items.query('SELECT * from c WHERE c.yourPartitionKey = "foo"').toArray();
```
In an effort to simplify, the V3 SDK removed `partitionKey` from `FeedOptions` so there was only one way to specify the partition key:
```js
// V3
container.items.query('SELECT * from c WHERE c.yourPartitionKey = "foo"').fetchAll();
```
Based on customer feedback, we identified scenarios where it still makes sense to support passing the partition key via `FeedOptions` and have decided to restore the behavior.

[Cosmos] Add partitionKey back to FeedOptions

---

sdk/core/core-http/src/operationOptions.ts
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/src/webResource.ts

**Problem**
Currently serviceClient.sendOperation request is not adding shouldDeserialize to the WebResource
**Fix**
When shouldDeserialized is passed in the request options, add it to the httpRequest WebResource

[core-http] Add shouldDeserialize to WebResource in SendOperationRequest

---

sdk/servicebus/service-bus/README.md

- Broken anchor link to the "receive from a session" snippet
- Bad wording around how to specify a session id for a message
- Incorrect text about having to specify a session id when getting a session receiver (it's not required)
- Some automatic reformatting from prettier.
- Random typos

[service-bus] Fixing some small readme issues

---

sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/test/deadLetter.spec.ts

The underlying rhea library for JS doesn’t allow us to pass the propertiesToModify when we deadletter the received message using the delivery object (the same is allowed for abandon/defer). 
As per the [AMQP spec](http://www.amqp.org/sites/amqp.org/files/amqp.pdf), we cannot provide the properties-to-modify(through message-annotations) when the delivery is being “rejected”(deadletter)
[deadletter-ing in .NET SDK](https://github.com/Azure/azure-sdk-for-net/blob/81d6ed42d456bbb3b02eeec8253f93fc1c519a3f/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs#L584-L619) – Key takeaway here is that the `props-to-modify` are loaded into the “error.info” field along with the deadletter-reason and deadletter-description.
We do use the `info` field to populate the reason and …

[Service Bus] Custom props on deadLetter() for non-deferred messages

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/samples/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/typescript/src/sendMessages.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/test/connectionManagement.spec.ts

Adding an .open() method on Sender to allow users to control when connection and link initialization occur.
Fixes #3212

[service-bus] Allow users to call `open()` on a Sender and initialize the connection

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/package.json
sdk/core/abort-controller/package.json
sdk/core/core-auth/package.json
sdk/core/core-lro/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json
sdk/textanalytics/ai-text-analytics/package.json

- There is a bug in the newer versions of api-extractor (both 7.7.12 and 7.7.13) where it changes the public api and appends "_2" to many of the public-facing interfaces and properties - 
Also look at the commits - https://github.com/Azure/azure-sdk-for-js/pull/8179/commits
```
git diff .\sdk\storage\storage-file-datalake\
diff --git a/sdk/storage/storage-file-datalake/package.json b/sdk/storage/storage-file-datalake/package.json
index 905c34f082..cb1ecf55e3 100644
--- a/sdk/storage/storage-file-datalake/package.json
+++ b/sdk/storage/storage-file-datalake/package.json
@@ -106,7 +106,7 @@
"devDependencies": {
"@azure/identity": "1.1.0-preview.2",
"@azure/test-utils-recorder": "^1.0.0",
-    "@microsoft/api-extractor": "7.7.11",
+    "@microsoft/api-extractor": "^7.7.13", …
```

pin api-extractor to 7.7.11

---

sdk/cognitiveservices/cognitiveservices-customvision-prediction/README.md

Add a note in Custom Vision Prediction README, to make clear that the samples presented are written in Typescript.
Fixes #5291

[Custom Vision Prediction] Update information about samples in README

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/connectionContext.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

This change updates the `MessageReceiver.onDetached` method to surface more errors to the user's error handler when using the streaming receiver.
Currently `onDetached` is called in 3 places for the streaming receiver:
- onAmqpClose (our callback for the `close` event fired on the AMQP link object in rhea)
- onSessionClose (our callback for the `close` event fired on the AMQP session object in rhea)
- connection disconnect (our callback for the `disconnect` event fired on the AMQP connection object in rhea)
Previously, we had logic in place where if the `onAmqpError` or `onSessionError` handlers (our callbacks for the `error` events fired on either the AMQP link or session object in rhea) were called with a non-retryable error, we would invoke the user's error handler. We skip calling …

[service-bus] surface disconnect errors to streaming receiver error handler

---

sdk/servicebus/service-bus/samples/javascript/advanced/movingMessagesToDLQ.js
sdk/servicebus/service-bus/samples/tsconfig.json
sdk/servicebus/service-bus/samples/typescript/src/advanced/movingMessagesToDLQ.ts

Dead letter samples weren't compiling with the `build:samples` (they were in a subdirectory).
Altered wildcard to pick them up and also fixed some casing issues with the parameter.
Fixes #8417

[service-bus] Update track 2 readme to fix samples

---

common/config/rush/common-versions.json
sdk/formrecognizer/ai-form-recognizer/package.json

as FormRecognizer might be released before core-tracing preview.8.

[FormRecognizer] downgrade core-tracing to 1.0.0-preview.7

---

sdk/formrecognizer/ai-form-recognizer/dom-shims.d.ts
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/typescript/README.md
sdk/formrecognizer/ai-form-recognizer/src/common.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/index.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/analyze/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/shims.d.ts
sdk/formrecognizer/ai-form-recognizer/src/utils/utils.browser.ts
sdk/formrecognizer/ai-form-recognizer/src/utils/utils.node.ts
sdk/formrecognizer/ai-form-recognizer/tsconfig.json

This change applies the same approach we used for `core-http`.  A `dom-shims.d.ts` is packed in the package to provide shims for DOM types this library uses internally.  In our code we actually compile another file `src/shims.d.ts` that references the the "dom" library.
Fixes #8420

[FormRecognizer] Remove the need to shim FileReader for end users

---

sdk/formrecognizer/ai-form-recognizer/package.json

So far, this just turns on the integration test script. I am working on being able to run the full tests in the browser but this should remove our ADO warnings.

[ai-form-recognizer] enable browser integration tests

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/src/ConnectionContextBase.ts
sdk/core/amqp-common/test/context.spec.ts

This change adds a `refreshConnection` method to `ConectionContextBase`. `refreshConnection` creates a new connection object, locks, and CbsClient.
The idea is that when a connection `disconnect` event is handled by service-bus or event-hubs, they can call `connectionContext.refreshConnection()` so that a rhea Connection is used.

[amqp-common] Add ability to create a new Connection on existing  ConnectionContextBase

---

sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/test/connectionManagement.spec.ts

As part of the fixing #8329 we allowed the user to call open() on a sender to preemptively initialize it.  However, it didn't work if you had closed the sender.
This commit goes all the way and allows you to reopen a sender after it has been closed.

[service-bus] sender.open() should clear the internal _isClosed flag #8466 

---

common/config/rush/common-versions.json
sdk/formrecognizer/ai-form-recognizer/package.json

for preview.1 release as core-auth v1.1.2 hasn't been released yet.

[FormRecognizer] downgrade core-auth dependency version to v1.1.0

---

common/config/rush/pnpm-lock.yaml
sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/connectionContext.ts
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

This change updates the `ConnectionContext` disconnect behavior.
Previous to this change, when a `disconnect` event was detect and the SDK attempted to recreate its links/sessions/connection, it would do some cleanup of the `rhea-promise` connection object and re-use it. Normally this works fine, but over time we've seen issues in logs that indicate that the connection object may be getting into an unexpected state in some cases.
This PR updates the `disconnect` behavior to create a new `rhea-promise` connection object when the SDK determines that the links/sessions/connection should be recreated.
This relies on #8444 to be merged first.
To test this change, I create a streaming receiver and run inside a docker container. With logging enabled, I disable the network connection for the …

[service-bus] recreate Connection object on disconnect

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/base64.browser.ts
sdk/search/search-documents/src/base64.ts
sdk/search/search-documents/src/odataMetadataPolicy.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchServiceClient.ts
sdk/search/search-documents/src/serviceUtils.ts

We are not explicitly setting an odata metadata policy for the service client.
This change extends the policy that the index client was using so that it can support either scenario and uses it for sending `minimal` in the service client case.

[search] Fix odata metadata policy

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- Ensures steps are killed when run is cancelled
- Exception is "Tag scheduled builds" which should always run

Add succeededOrFailed() to all custom conditions

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- Condition used for "unlink dependencies" and "PublishTestResults" should match
This PR will need a bit more work.  The `rush unlink` command fails with error "Another rush command is already running in this repository".  I think the issue is that the previous `rush test` command was killed when the job was cancelled, so we might need to either sleep a few seconds or somehow force the new rush command through (e.g. by deleting a lockfile).
Example: https://dev.azure.com/azure-sdk/public/_build/results?buildId=229792&view=logs&j=ba8c15a9-bc1f-5628-021b-e6d79d48e15f&t=ea8763a5-7b1c-546a-3b50-4594d764634e&l=28

Unlink dependencies even if build is cancelled

---

sdk/core/core-http/package.json

Due to the following api-extractor issue, our tripple slash reference to
`../dom-shim.d.ts` is not kept in the rollup type definition file.
https://github.com/microsoft/rushstack/issues/1761
Until the issue is fixed, we will have to stay with the non-rollup type
definition files.

[core-http] revert back to use non-rollup type definition file

---

sdk/identity/identity/src/credentials/managedIdentityCredential.ts

This adds the IMDS expires_on precedence fix that was rolled into 1.0.3 into the current preview as well.
This allows us to use expires_on, if available, if we're using IMDS. Previously, we would only use expires_in, which meant that under some conditions, we wouldn't have an updated expiration of the token.

[Identity] Change expires_on precendence for IMDS

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/sender.spec.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/renewLock.spec.ts
sdk/servicebus/service-bus/test/retries.spec.ts
sdk/servicebus/service-bus/test/sendBatch.spec.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts

Created a send(messages[]) overload that transparently creates and sends a batch internally.

[service-bus] Track2 - adding in a send(messages[]) overload

---

common/smoke-test/smoke-tests.yml
eng/common/TestResources/README.md
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

The change that this is merging ahead of is: https://github.com/Azure/azure-sdk-tools/pull/549 
If we don't add the `ServiceDirectory` we'll see failures during the de-provisioning step.

Add ServiceDirectory parameter to usages of remove-tests-resources.yml

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/api-extractor.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples/tsconfig.json
sdk/servicebus/service-bus/src/util/constants.ts
sdk/servicebus/service-bus/tsconfig.json

Service Bus library would not work for the users relying on Typescript 3.1-3.5 since the types are incompatible.
This PR attempts to provide the types for the lower versions of typescript(3.1-3.5) along with the latest.

[Service Bus] Add downleveling for service-bus track 1

---

sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/renewLock.spec.ts

- Updating lockedUntilUTC property on the message once the renewLock operation completes.
- Fixed an assertion that would properly verify the above.
- Previously, if the diff between the expected and actual is less than 10s, the assertion succeeded. Due to this, the test succeeded though the lockedUntilUTC property didn't change.

[Service Bus] Set lockedUntilUtc property on the message after renewLock

---

sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts

Do not set managementClient to undefined to avoid TypeError and to allow using managementClient for settlement to surface better errors. 
- isOpen() would return false in case the client is being closed was unused(meaning never sent/received any messages or any other operations)
- And the close() would return right away, we never set the `isClosed` flag to true. This would allow using the client even after it is closed. 
- To avoid the above, moved this `isClosed=true` to the top which would make the SDK throw an error when user tries to operate on a closed client.

[Service Bus] Improve error when settling messages after Queue/Subscription client is closed

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/api-extractor.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples/tsconfig.json
sdk/servicebus/service-bus/tsconfig.json

Service Bus library would not work for the users relying on Typescript 3.1-3.5 since the types are incompatible.
This PR attempts to provide the types for the lower versions of typescript(3.1-3.5) along with the latest.

[Service Bus] Add downleveling for service-bus track 2

---

sdk/eventhub/event-hubs/src/impl/eventHubClient.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/src/util/operationOptions.ts

This PR refactors the `getParentSpan()` function to take tracing options directly to simplify its signature. Fixes #8407

[Event Hubs] getParentSpan to take tracing options directly

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/models/public.ts
sdk/eventhub/event-hubs/test/sender.spec.ts

Fixes #8470 
Updates the `EventHubProducerClient.sendBatch` method to also accept an array of `EventDataBatch`. This also necessitated adding a new `options` type that let's the user specify a `partitionKey` or `partitionId`.
Because of the additional options, I also needed to add validation to ensure that none of the options conflicted with the options that can be set on a batch in the `createBatch` call.

[event-hubs] update sendBatch to accept lists of events

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/src/recorder.ts

Since Mocha 7.0.0, Mocha behaves as follows:
> "When conditionally skipping in a it test, related afterEach hooks are now executed"
> [Source](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#700--2020-01-05)
Therefore, now the `recorder.stop()` calls in the `afterEach()` will always be executed. Calling `stop()` in `recorder.skip()` causes a double execution of `recorder.stop()`, which hangs the browser tests.

[recorder] afterEach is now always executed

---

sdk/core/core-lro/README.md
sdk/core/core-lro/samples/README.md

The indications I've received so far are to:
- Provide a better introduction, stating that even though core-lro is a public package, it's only intended to be used by Azure SDK developers.
- Installing core-lro would normally be donde with `rushx`.
- Examples and more complex instructions should be moved to the samples folder README.
Please let me know if I missed something!

[core-lro] README improvements

---

sdk/storage/storage-blob/src/credentials/StorageSharedKeyCredential.browser.ts
sdk/storage/storage-file-datalake/src/credentials/StorageSharedKeyCredential.browser.ts
sdk/storage/storage-file-share/src/credentials/StorageSharedKeyCredential.browser.ts
sdk/storage/storage-queue/src/credentials/StorageSharedKeyCredential.browser.ts

This fixes #8499.
The issue was that in `StorageClient.ts` we have the following check
and assume that in browser scenario `isNode` would be `false` which
would short-circuit the evaluation of `factory instanceof
StorageSharedKeyCredential`. So we added an `undefined` const for
browser stub of `StorageSharedKeyCredential`.
```typescript
if (
(isNode && factory instanceof StorageSharedKeyCredential) ||
factory instanceof AnonymousCredential ||
isTokenCredential(factory)
) {
this.credential = factory;
}
```
However, in an Electron + Angular application, `isNode` is `true` but
browser files are used. So the condition after `&&` is evaluated and
caused an error:
```
TypeError: Right-hand side of 'instanceof' is not an object
at DataLakeServiceClient.StorageClient (StorageClient.js:35)
at new …
```

[Storage] Change StorageSharedKeyCredential browser stub to class

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/review/event-hubs.api.md
sdk/eventhub/event-hubs/src/eventDataBatch.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/test/sender.spec.ts

Fixes #8567 
Previously, the `tryAdd` method would encode an AMQP message that contained all the events added to the batch in order to calculate the size of the batch with the new event added. This ends up being very expensive as more events are added to the batch (Making adding an event an O(n^2) operation).
With this change, the individual events are still encoded and stored as before, but now we calculate what the new size will be based on the known overhead of creating a batch. I took the overhead values from what [.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpEventBatch.cs#L23-L29) and python have (5 bytes for small messages, 8 bytes for large messages) and verified through testing that these are correct. We also …

[event-hubs] improve EventDataBatch.tryAdd performance

---

sdk/servicebus/service-bus/tests.yml

After speaking with @HarshaNalluru we're shifting the testing over to the default matrix. The original default matrix was extensive and the long running tests took up a lot of agent time. The smaller matrix offers a better balance of coverage and time.

Use the default test matrix with service bus

---

eng/pipelines/templates/jobs/archetype-sdk-integration.yml

A more thorough audit of the integration test yml revealed that we're using Windows for samples testing when we agreed upon Linux. This corrects that.

Use Linux for samples instead of Windows

---

sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

- Removing the unintentional uncaught test reference in the src code
- Updating the tests to fix test failures
- Making the supposed `MessagingError` an actual `MessagingError`

[Service Bus] Remove test reference in src and fix test failures

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/session.js

- session sample for JS was missing the await keyword on createSessionReceiver()
- readme was missing a quote in one of the snippets, making it invalid

[service-bus] Minor fixes prior to preview.2 release

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

Cosmos CI pipeline uses the emulator (and `archetype-sdk-integration.yml`) which automatically adds browser and samples testing to the test matrix. These tests are not required in this scenario and should be skipped.

Fix cosmos public CI pipeline

---

sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/partitionPump.spec.ts
sdk/eventhub/event-hubs/test/sender.spec.ts
sdk/eventhub/event-hubs/test/utils/testUtils.ts

There were two sets of tests that were failing:
- A createBatch() test suddenly had diagnostic IDs populated. Looks like we were replacing the global tracer in tests that had activated tracing and that state was propagating to other tests. Most tests don't bother checking the event properties so it's gone unnoticed.
- A set of random tests for array sending that were using date that were _probably_ failing because of clock skew. To fix those I just swapped them over to our typical pattern of using sequence number.

[event-hubs] Fixing flaky tests.

---

sdk/eventhub/event-hubs/README.md

Broken snippet - missing an 'async' for a function and using the wrong name for the client (`consumerClient` vs `client`).

[event-hubs] Fixing broken snippet in readme

---

sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/src/util/utils.ts

Issue #8430 
- Removing DispositionStatus enum and keeping DispositionType since the names are more clear w.r.t to the settlement methods.
- Updated managementClient's updateDispositionStatus method to take DispositionType as a parameter and internally mapping it as DispositionStatus.

[Service Bus] Merge DispositionStatus and DispositionType

---

sdk/servicebus/service-bus/samples/javascript/README.md
sdk/servicebus/service-bus/samples/javascript/advanced/sessionRoundRobin.js
sdk/servicebus/service-bus/samples/javascript/package.json
sdk/servicebus/service-bus/samples/typescript/README.md
sdk/servicebus/service-bus/samples/typescript/package.json
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts

Porting over the sessionRoundRobin sample we wrote for Track 2 to Track 1. 
Some changes apart from the obvious ones:
- The track 1 API doesn't work with abortSignals so I needed to hook up the handler explicitly.
- Use `sessionReceiver.getSessionState` as a proxy call for explicitly opening a session. In Track 2 we open the session receiver explicitly when we create it.
For reviewer convenience I checked in the track 2 sample first and then modified it so you can see the changes more easily.
Addresses #8691

[service-bus] track1 - porting sessionRoundRobin sample

---

sdk/servicebus/service-bus/test/atomManagement.spec.ts

A couple of tests related to createTopic() failed due to the change in response received from the service. Updated the expected response as per the new response observed.

[Service Bus] atomManagement API - Fix test failures

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml
eng/pipelines/templates/steps/generate-doc.yml
sdk/core/core-lro/test/abort.test.ts
sdk/eventhub/event-processor-host/tests.yml
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

This PR has what is needed to make the base branch for the challenge based authentication hotfix stable.
Related to:
- [KeyVault Keys and Secrets Hotfix 4.0.3] Recordings #8783
- [KeyVault Keys Hotfix 4.0.3] Addressing the challenge authentication cache bug #8767
- [KeyVault Secrets Hotfix 4.0.3] Addressing the challenge authentication cache bug #8766

[KeyVault Keys and Secrets Hotfix 4.0.3] Commits to make sure the builds work

---

sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts

The implmentation of `KeyCredential` is now spelled
`AzureKeyCredential`. Update the doc comment on the constructor.

[ai-text-analytics] Fix code sample in docs

---

sdk/servicebus/service-bus/src/serviceBusClient.ts

Simple improvements for the doc strings when describing the receiveMode for create*() methods in ServiceBusClient

[service-bus] Improve doc strings for create() methods on ServiceBusClient

---

sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts

This fixes the @types/qs breakage, where return types were recently made more specific. This caused issues where we assume it's returning 'any'.
With this, it's possible to do a `rush update --full`
cc @KarishmaGhiya

Workaround @types/qs breakage

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

- Build and test steps should only run if previous steps succeeded
- Introduced in #8518 (succeededOrFailed() was used incorrectly)

Change build and test condition to succeeded()

---

sdk/core/core-arm/package.json
sdk/core/core-arm/test/mocha.opts
sdk/core/core-http/.vscode/launch.json
sdk/core/core-http/package.json
sdk/core/core-http/test/mocha.opts

passing options via command line instead.
Also added a VS Code launch configuration for debugging Node tests.

[core-http/arm] remove deprecated configuration via mocha.opts

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml
eng/pipelines/templates/steps/generate-doc.yml
sdk/eventhub/event-processor-host/tests.yml
sdk/test-utils/recorder/src/baseRecorder.ts
sdk/test-utils/recorder/src/utils.ts

This PR has what is needed to make the base branch for the challenge based authentication hotfix stable.
The base branch, `hotfix/keyvault-challengeAuth-certificates-from-4.0.0`, comes from the commit `7c1b8d7f174f90456932acce99b9d0bf49dc197b`, which comes from the stable KeyVault release https://github.com/Azure/azure-sdk-for-js/releases/tag/%40azure%2Fkeyvault-certificates_4.0.0
I made a couple PRs before this one, but the git history and the builds got weird. This one should be fine.

[KeyVault Certificates Hotfix 4.0.1] Commits to make sure the builds work

---

sdk/core/abort-controller/karma.conf.js
sdk/core/core-amqp/karma.conf.js
sdk/core/core-https/karma.conf.js
sdk/core/core-lro/karma.conf.js
sdk/core/logger/karma.conf.js
sdk/eventhub/event-hubs/karma.conf.js
sdk/eventhub/eventhubs-checkpointstore-blob/karma.conf.js
sdk/formrecognizer/ai-form-recognizer/karma.conf.js
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/rollup.base.config.js
sdk/identity/identity/karma.conf.js
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-keys/karma.conf.js
sdk/keyvault/keyvault-secrets/karma.conf.js
sdk/search/search-documents/karma.conf.js
sdk/servicebus/service-bus/karma.conf.js
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-file-datalake/karma.conf.js
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-queue/karma.conf.js
sdk/template/template/karma.conf.js
sdk/test-utils/perfstress/karma.conf.js
sdk/test-utils/recorder/karma.conf.js
sdk/textanalytics/ai-text-analytics/karma.conf.js

so we can debug TypeScript source code for browser tests. One still
needs to disable code coverage first though to have the source mapping
working.

Include sourcemap file in karma files section

---

sdk/eventhub/event-hubs/src/eventHubSender.ts

Issue - #8166 
The issue is to confirm if the init call is being retried as expected.
- _init is being retried properly - no changes here
- the send call is not honoring the timeout, this PR attempts to update that similar to what was agreed upon for service-bus from https://github.com/Azure/azure-sdk-for-js/pull/7972

[Event Hubs] Share the retryAttemptTimeout among init and the send call

---

sdk/core/amqp-common/changelog.md
sdk/core/amqp-common/package.json
sdk/core/amqp-common/src/errors.ts

OperationTimeoutError should be retryable. We've already made this change in track 2.
Fixes #8835

[amqp-common] OperationTimeoutError should also be considered a retryable error

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
sdk/keyvault/keyvault-keys/test/CRUD.test.ts
sdk/keyvault/keyvault-keys/test/challengeBasedAuthenticationPolicy.test.ts
sdk/keyvault/keyvault-keys/test/recoverBackupRestore.test.ts

This PR highlights the changes needed to release the hotfix that resolves an issue reported by a customer: https://github.com/Azure/azure-sdk-for-js/issues/8378
The PR to master is: https://github.com/Azure/azure-sdk-for-js/pull/8558/
Related to:
- [KeyVault Keys and Secrets Hotfix 4.0.3] Commits to make sure the builds work #8782
- [KeyVault Keys and Secrets Hotfix 4.0.3] Recordings #8783
- [KeyVault Secrets Hotfix 4.0.3] Addressing the challenge authentication cache bug #8766

[KeyVault Keys Hotfix 4.0.3] Addressing the challenge authentication cache bug

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/rollup.base.config.js
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/rollup.base.config.js
sdk/keyvault/keyvault-keys/src/cryptographyClient.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/keyvault/keyvault-secrets/src/index.ts

Similar to: https://github.com/Azure/azure-sdk-for-js/pull/8872
Changes from: https://github.com/Azure/azure-sdk-for-js/pull/7998/files Plus a bunch of other things I had to do.
The upgrade to identity's 1.1.0-preview.3 was suggested by Jeff Fisher, and it worked nicely!
**IMPORTANT:** KeyVault keys and secrets tests will fail because we have already merged the recordings related to the hotfix to this branch.
CI can possibly still fail from other reasons, so beware of that. I'll make sure it passes though! Just have patience.

[KeyVault Keys and Secrets Hotfix 4.0.3] Updating core-http and opentelemetry

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/core/core-lro/test/abort.test.ts
sdk/core/core-tracing/package.json
sdk/identity/identity/test/node/clientCertificateCredential.spec.ts
sdk/identity/identity/test/node/managedIdentityCredential.spec.ts
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/rollup.base.config.js
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/rollup.base.config.js
sdk/keyvault/keyvault-secrets/src/index.ts

Changes from: https://github.com/Azure/azure-sdk-for-js/pull/7998/files Plus a bunch of other things I had to do.
The upgrade to identity's 1.1.0-preview.3 was suggested by Jeff Fisher, and it worked nicely!
CI can possibly fail still, so beware of that. I'll make sure it passes though! Just have patience.

[KeyVault Certificates Hotfix 4.0.1] Updating core-http and opentelemetry

---

sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/core/challengeBasedAuthenticationPolicy.ts
sdk/keyvault/keyvault-secrets/src/core/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts
sdk/keyvault/keyvault-secrets/test/CRUD.test.ts
sdk/keyvault/keyvault-secrets/test/challengeBasedAuthenticationPolicy.test.ts
sdk/keyvault/keyvault-secrets/test/recoverBackupRestore.test.ts

This PR highlights the changes needed to release the hotfix that resolves an issue reported by a customer: https://github.com/Azure/azure-sdk-for-js/issues/8378
The PR to master is: https://github.com/Azure/azure-sdk-for-js/pull/8558/
Related to:
- [KeyVault Keys and Secrets Hotfix 4.0.3] Commits to make sure the builds work #8782
- [KeyVault Keys and Secrets Hotfix 4.0.3] Recordings #8783
- [KeyVault Keys Hotfix 4.0.3] Addressing the challenge authentication cache bug #8767

[KeyVault Secrets Hotfix 4.0.3] Addressing the challenge authentication cache bug

---

sdk/servicebus/service-bus/samples-v1/javascript/README.md
sdk/servicebus/service-bus/samples-v1/javascript/advanced/sessionRoundRobin.js
sdk/servicebus/service-bus/samples-v1/javascript/package.json
sdk/servicebus/service-bus/samples-v1/typescript/README.md
sdk/servicebus/service-bus/samples-v1/typescript/package.json
sdk/servicebus/service-bus/samples-v1/typescript/src/advanced/sessionRoundRobin.ts
sdk/servicebus/service-bus/samples/javascript/advanced/sessionRoundRobin.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts

Recently, we moved the Track 1 samples to the master branch in https://github.com/Azure/azure-sdk-for-js/pull/8607 to fix https://github.com/Azure/azure-sdk-for-js/issues/7317
This PR makes the below changes on top of that move
- Copy the new sample for round robin sessions that was added to 1.1.7 hot fix branch
- Fix wrong dependencies in package.json

[Service Bus] Port round robin sample to v1 folder

---

sdk/storage/storage-blob/test/blobbatch.spec.ts
sdk/storage/storage-blob/test/blobserviceclient.spec.ts
sdk/storage/storage-blob/test/node/containerclient.spec.ts
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts
sdk/storage/storage-blob/test/node/utils.spec.ts
sdk/storage/storage-blob/test/retrypolicy.spec.ts
sdk/storage/storage-blob/test/utils/constants.ts
sdk/storage/storage-blob/test/utils/index.browser.ts
sdk/storage/storage-blob/test/utils/index.ts

This is preferable for all packages to identify the tests that are using exported public members v/s internal references
Eg of min-max testing issues we run into - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=386486&view=logs&j=1c9290f0-7664-5780-0e82-5fab6e3e2db5&t=b211ce22-692d-5fec-1417-52e3b1830f7c

converting storage-blob exported references to src references

---

sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/blobclientpollers.spec.ts
sdk/storage/storage-file-share/test/fileclient.spec.ts

Storage Blob service in some data center/region may have a feature
enabled to sanitize the header to remove the `sig` part in the SAS
token. This change removes the `sig` part when verifying
`properties.copySource` against the original source url.

[Storage][Test] Omit the sig part when verifying copySource

---

sdk/servicebus/service-bus/test/abortSignal.spec.ts

This test seemed to start failing after the sendBatch update, not sure why it didn't fail on that PR itself.
Test failed because the batchMessage being passed is invalid.
Not updating the MessageSender's sendBatch with any sort of validations since the Sender's methods have the validations already and the user won't use the MessageSender directly.

[Service Bus] Fix abortSignal test failure for sendBatch

---

sdk/appconfiguration/app-configuration/test/README.md

In the course of validating #8257 I found a small typo. 
Other than that, all the instructions appear accurate and I was able to bootstrap just fine using the variables specified. :)
Fixes #8527

[app-configuration] Fix minor typo in test readme for app configuration

---

sdk/core/abort-controller/karma.conf.js
sdk/core/core-amqp/karma.conf.js
sdk/core/core-https/karma.conf.js
sdk/core/core-lro/karma.conf.js
sdk/core/logger/karma.conf.js
sdk/eventhub/event-hubs/karma.conf.js
sdk/eventhub/eventhubs-checkpointstore-blob/karma.conf.js
sdk/formrecognizer/ai-form-recognizer/karma.conf.js
sdk/identity/identity/karma.conf.js
sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-keys/karma.conf.js
sdk/keyvault/keyvault-secrets/karma.conf.js
sdk/search/search-documents/karma.conf.js
sdk/servicebus/service-bus/karma.conf.js
sdk/storage/storage-blob/karma.conf.js
sdk/storage/storage-file-datalake/karma.conf.js
sdk/storage/storage-file-share/karma.conf.js
sdk/storage/storage-queue/karma.conf.js
sdk/template/template/karma.conf.js
sdk/test-utils/perfstress/karma.conf.js
sdk/test-utils/recorder/karma.conf.js
sdk/textanalytics/ai-text-analytics/karma.conf.js

This is a follow up of #8839. Files do need to be served so browser
debugging tools can load them along side the tests. See
http://karma-runner.github.io/5.0/config/files.html for docs on files
options.

Serve the source map files during karma test run

---

.github/CODEOWNERS

This change (arbitrarily) selects code owners for the Smoke Tests pipelines. You will receive email notifications from Azure DevOps when the smoke tests fail. If someone else should be in your place please comment here. 
What are smoke tests? 
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/198/Smoke-Testing
Who is being subscribed? 
@ramya-rao-a @chradek @daviwil @sadasant @HarshaNalluru @southpolesteve

Update CODEOWNERS with smoke test owners

---

sdk/cognitiveservices/cognitiveservices-computervision/LICENSE.txt
sdk/cognitiveservices/cognitiveservices-computervision/package.json
sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClient.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-computervision/src/models/parameters.ts

Based on request from @lmazuel, I have regenerated the Cognitive Services Computer Vision TS SDK in this PR. Command used to regenerated SDK:
```
autorest --reset && autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/saranganrajamanickam/Projects/azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.4 --package-version=7.0.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/ComputerVision/readme.md
```
A few pointers to give context:
1. I have waited for the completion of this PR: https://github.com/Azure/azure-rest-api-specs/pull/8734 before regenerating. 
2. Last time, this SDK was regenerated on Sep 11, 2019. At that time ***autorest.typescript version - 4.2.2*** was used …

Regenerated CS Computer Vision & Bumped Major Version

---

sdk/cognitiveservices/cognitiveservices-customvision-prediction/LICENSE.txt
sdk/cognitiveservices/cognitiveservices-customvision-prediction/README.md
sdk/cognitiveservices/cognitiveservices-customvision-prediction/package.json
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/models/parameters.ts
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/predictionAPIClient.ts
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/predictionAPIClientContext.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/LICENSE.txt
sdk/cognitiveservices/cognitiveservices-customvision-training/README.md
sdk/cognitiveservices/cognitiveservices-customvision-training/package.json
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/parameters.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/trainingAPIClient.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/trainingAPIClientContext.ts

Based on request from @zikalino, I have regenerated the Cognitive Services Custom Vision Prediction & Training TS SDKs in this PR. Command used to regenerated SDK:
**Prediction**
```
autorest --reset && autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/saranganrajamanickam/Projects/azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.4 --package-version=5.0.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/2c3bdf02d5f714174ed160fcfade02d5e5669bce/specification/cognitiveservices/data-plane/CustomVision/Prediction/readme.md
```
**Training**
```
autorest --reset && autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/saranganrajamanickam/Projects/azure-sdk-for-js …
```

Regenerated CS Custom Vision - Prediction & Training & Bumped Major Version

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/searchServiceClient.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts

The List Skillsets operation does have a select fields (even though the docs say otherwise). The swagger document [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Azure.Search/stable/2019-05-06/searchservice.json#L759) can be used for reference. 
```ts
import { SearchServiceClient, AzureKeyCredential, Skillset, odata, SynonymMap, Index }  from "@azure/search-documents";
const client: SearchServiceClient = new SearchServiceClient(
"xyz",
new AzureKeyCredential("abc")
);
async function main(): Promise<void> {
const listOfSkillSets = await client.listSkillsets({
select: ['name', 'skills']
})
listOfSkillSets.forEach((sk, index) => {
console.log(`Name: ${sk.name}`);
console.log(`Name: ${sk.skills}`);
});
}
main();
```
@xirzec Please review and …

Code changes to add select to List Skillsets operation

---

sdk/core/core-http/review/core-http.api.md
sdk/core/core-http/src/operationSpec.ts
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/serviceClientTests.ts

This change adds a `mediaType` field to the `OperationSpec` interface.
This field can then be used to determine how a request body should be serialized.
This is related to the work in #7963
`mediaType` describes the type of the request body in a more generic way than contentType.
For example, some valid values for mediaTypes would be "binary", "xml", "json", "text".
This change adds a check to see if the `mediaType` is `text`, and serializes the request body the same as if it had the contentType `text/plain`.
Multiple contentType values can be treated the same way. For example, imagine an operation that supports `text/plain` or `text/markdown`. Both of these contentTypes would map to the `text` mediaType. If we rely on the contentType value rather than mediaType, we will need to maintain …

[core-http] support text media type serialization

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples-v1/javascript/useProxy.js
sdk/servicebus/service-bus/samples-v1/typescript/src/useProxy.ts
sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/src/serviceBusClient.ts

Porting #8889 
~~(Not porting the comments for "scope" since we rely on the AAD and `@azure/identity` for TokenCredentials which doesn't require scope to be passed.)~~

[Service Bus] Port "scope" comments and websocket comments for useProxy sample from track 1

---

sdk/servicebus/service-bus/src/serviceBusClient.ts
sdk/servicebus/service-bus/test/internal/serviceBusClient.spec.ts

1. `validateEntityNamesMatch` would throw an error saying the entity path provided in the connection string is undefined and hence mismatch if the user relies on the token credential way instead of a connection string. 
This would mean that the user can never be able to create a sender or a receiver if started from the tokencredential way.
2. We should not do the validation and let the service throw an error in case of inconsistencies.
Due to these reasons, I'm removing the `validateEntityNamesMatch` method and updated the relevant code that touches this.
Issue - Part 4 of #8192

[Service Bus] Remove entityPath validation

---

sdk/core/core-auth/tsconfig.json

because storage packages still need to target ES5.

[core-auth] target ES5

---

sdk/core/core-http/review/core-http.api.md

This updates the api review file in core-http to match the actual changes that were merged from #8977.

[core-http] update mediaTypes in API review

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/README.md
sdk/core/core-amqp/review/core-amqp.api.md
sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/cbs.ts
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/messageHeader.ts
sdk/core/core-amqp/src/messageProperties.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/retry.ts
sdk/core/core-amqp/src/util/utils.ts
sdk/core/core-amqp/test/message.spec.ts
sdk/core/core-amqp/test/requestResponse.spec.ts

I know this PR is kind of obnoxious, but I thought I could help.
I was able to detect these by using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) on VSCode.

[core-amqp] Fixing typos

---

sdk/core/abort-controller/README.md

I found one typo in the abort-controller 🌞
I was able to detect these by using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) on VSCode.

[abort-controller] Fixing typos

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/src/serviceModels.ts

**Specification for this PR**
Currently in the SDK we expose ```ETagOperationOptions``` which has ```AccessCondition```. It should be removed. We should not expose it. Instead, we need to introduce a boolean value ```OnlyIfUnchanged```. This value must be used to determine if the etag value should be sent to the server or not. 
1) For CreateOrUpdate, this is straight forward: we already take entire models that have an ETag, so you just get that and, if onlyIfUnchanged is true, pass the If-Match header.
2) For Delete, which takes stringName as inputParameter, Unconditionally delete resources.
3) For Delete, which takes the model as inputParameter, Use onlyIfUnchanged similar to CreateOrUpdate.
This is related to issue https://github.com/Azure/azure-sdk-for-js/issues/8517 
@xirzec Please …

Add OnlyIfUnchanged parameter to CreateUpdate & Delete operations

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

Since we are using `karma@^4`, I think we should also use `@types/karma@^4`.
I will try updating to `karma@^5` in a separate PR, this major update is much more likely to cause breaks.

Remove unused dev dependency "@types/karma"

---

sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts

[FormRecognizer] rename parameter name of *FromUrl() methods

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

`tough-cookie@4.0.0` still supports Node 8, and none of the breaking changes seem relevant to us:
https://github.com/salesforce/tough-cookie/releases/tag/v4.0.0
@bterlson: Since this is a runtime dependency I will not merge unless the JS arch board agrees.

Update runtime dependency "tough-cookie"

---

sdk/textanalytics/ai-text-analytics/README.md
sdk/textanalytics/ai-text-analytics/test/README.md

Addresses #8390 and contains a first stab at instructions for using AAD in TextAnalytics's testing README ( #8463 )
CC @sadasant I think the README content on how to use AAD here is maybe a little long, so I'd like to extract it to a separate location if we know where that should live right now. Otherwise, let me know what you think of the content.

[ai-text-analytics] Some tweaks to readme files

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_can_disable_a_certificate.json
sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_can_disable_a_certificate_version.json
sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_can_update_certificate_with_requestoptions_timeout.json
sdk/keyvault/keyvault-certificates/recordings/browsers/certificates_client__create_read_update_and_delete/recording_can_update_the_tags_of_a_certificate.json
sdk/keyvault/keyvault-certificates/recordings/node/certificates_client__create_read_update_and_delete/recording_can_disable_a_certificate.js
sdk/keyvault/keyvault-certificates/recordings/node/certificates_client__create_read_update_and_delete/recording_can_disable_a_certificate_version.js
sdk/keyvault/keyvault-certificates/recordings/node/certificates_client__create_read_update_and_delete/recording_can_update_the_tags_of_a_certificate.js
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/test/CRUD.test.ts

This PR addresses the bug reported on #9020
The bug is that: updateCertificateProperties is not correctly passing the attributes required by the underlying method.
I will be adding these changes to my current 4.0.2 hotfix PR https://github.com/Azure/azure-sdk-for-js/pull/9122

[KeyVault Certificates] Making sure updateCertificateProperties properly passes the certificate attributes to the underlying generated method

---

sdk/core/core-http/test/msRestUserAgentPolicyTests.browser.ts
sdk/core/core-http/test/serializationTests.ts
sdk/core/core-http/test/xmlTests.ts

Issue 1) on Firefox user agent string contains more than two
fields:
"core-http/1.1.3 OS/WindowsNT 10.0; Win64; x64"
while on Chrome it has just two:
"core-http/1.1.3 OS/Win32"
Changed to verify it has at least two fields.
Issue 2) Most likely either Chrome has a bug, or behavior of dates
before January 1, 1970 is not well defined. For the date Tue, Jan 1
0001 00:00:00 GMT, Chrome sets the year to be 2001, while Firefox
keeps the year as 0001.
Changed to use another date in the test.
Issue 3) The error message when parsing xml with an input of undefined
or null is different between Chrome and Firefox.
Changed to pass on either one.

[core-http] fix browser tests on Firefox

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json
sdk/core/core-http/src/util/utils.ts
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/samples/BulkUpdateWithSproc.ts
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/test/misc.spec.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/event-processor-host/src/azureStorageCheckpointLeaseManager.ts
sdk/eventhub/event-processor-host/src/eventProcessorHost.ts
sdk/eventhub/event-processor-host/src/hostContext.ts
sdk/eventhub/event-processor-host/test/eph.spec.ts
sdk/eventhub/testhub/commands/sendReceive.ts
sdk/eventhub/testhub/package.json
sdk/identity/identity/package.json
sdk/identity/identity/src/credentials/clientCertificateCredential.ts

https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md

Update runtime dependency "uuid"

---

sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts

The parameter to the *FromUrl() methods were already renamed. This change makes
the names more consistent.

[FormRecognizer] rename data parameter to recognition methods.

---

common/config/rush/pnpm-lock.yaml
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-https/package.json
sdk/core/core-tracing/package.json
sdk/core/logger/package.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-processor-host/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json
sdk/textanalytics/ai-text-analytics/package.json

Node 8 support was officially dropped in `7.0.0`, but I suspect it will continue to work.
https://github.com/kentcdodds/cross-env/releases/tag/v7.0.0
Blocked by #9172

Update dev dependency "cross-env"

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-http/package.json

> v7, v8 & v9 are practically identical, only differing in their treatment of a few edge cases, or in compatibility with other libraries and environments.
http://www.wheresrhys.co.uk/fetch-mock/#aboutprevious-versions

[core-http] Update dev dependency "fetch-mock"

---

sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/internal/utils.spec.ts

Splits off some of the simpler bits of #8994

[service-bus] AbortSignal helpers

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/serviceModels.ts

Per other languages, we're making listing indexes a pageable operation, even though today its an atomically returned array so that the service can later move to a paging model without breaking.
Since there is no continuation token or support for page size at the moment, I removed the paging options from byPage to avoid conflicts with whatever support we add in later.
Fixes #8484

[search-documents] Make listIndexes and listIndexesNames pageable.

---

sdk/servicebus/service-bus/src/util/utils.ts

The PR Standardizing the tsconfig.json files #8671 reported to be fine, but it landed breaking master, since there was a non-conflicting change that was missing as part of the PR.
Here's the fix.
I wonder if we could change the repository settings to force people to update all PRs before merging them. It could have helped me see the problem.

Fixing the build after merging the tsconfig.json update

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-https/package.json
sdk/core/core-https/src/nodeHttpsClient.ts
sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/samples/javascript/package.json
sdk/eventhub/event-hubs/samples/typescript/package.json
sdk/eventhub/event-processor-host/package.json
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples-v1/javascript/package.json
sdk/servicebus/service-bus/samples-v1/typescript/package.json
sdk/servicebus/service-bus/samples/javascript/package.json
sdk/servicebus/service-bus/samples/typescript/package.json

- Remove unnecessary dev dependency from "@azure/event-hubs" and "@azure/service-bus"
- No longer needed since the samples have been moved to their own package
- Update runtime dependency used by samples to match "@azure/core-https"
- Update dev dependency used by "@azure/event-processor-host" (samples still use the runtime package.json)

[core-https] Update runtime dependency "https-proxy-agent"

---

sdk/storage/storage-file-datalake/package.json

Dependency was added in #6337 but it appears to be unused. I do not see any references to `nock` in the `storage-file-datalake` sources (except for the test recordings, which I believe are a special case and do not require a dev dependency in the runtime package).

[storage-file-datalake] Remove unused dev dependency "nock"

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/url.ts
sdk/core/core-http/test/urlTests.ts

Fixes issue #8353
Currently URLBuilder can handle the cases where a full URL is passed as a parametrized path i.e. `http://localhost/{nextLink}` and **nextLink** being `http://localhost/page/2`. Here nextLink will be the new URL
It does this by checking if the path inserting in the placeholder `{nextLink}` contains a protocol (or scheme) and re-build the URL from the path. Resulting in the URL `http://localhost/page/2`
The problem is that the current logic assumes that the baseURL will always be in the form `scheme://hostname` however there are cases where the baseURL would contain some parts such as an api version for example `http://localhost/v2/{nextLink}` and **nextLink** being `http://localhost/v2/page/2`
In this case we correctly identify the path containing a full url and try to …

[core-http] URLBuilder incorrectly handles parametrized path with full URLs

---

sdk/keyvault/keyvault-certificates/tsconfig.json
sdk/keyvault/keyvault-keys/tsconfig.json
sdk/keyvault/keyvault-secrets/tsconfig.json

My latest PR standardizing the tsconfig.json files disregarded the warnings around our use of Async Iterators on the KeyVault projects. This PR introduces the most minimal change to fix the build warnings.

[KeyVault] Fix build warnings

---

sdk/core/ci.yml
sdk/core/core-https/package.json

Was:
> This PR changes ```azure-core-https``` from private to public. Because the package is marked as private it failed the integration stage of the nightly pipelines where it attempted to publish the dev version of the package.
> If this package shouldn't be pushed (even as a dev package) yet then it should be removed from the artifact list in the ```ci.yml```. Otherwise this PR should be merged to fix the nightly builds.
I've swapped this to now keep the package private but remove it from the artifact list so it won't attempt to publish.
/cc @KarishmaGhiya @mikeharder

Remove azure-core-https from the artifact list.

---

sdk/textanalytics/ai-text-analytics/README.md

This was left in and caused our README to break near the bottom.

[ai-text-analytics] Removed an errant code fence in the TA readme

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json

Breaking changes:
https://github.com/browserify/stream-browserify/blob/master/CHANGELOG.md#300
https://github.com/nodejs/readable-stream#version-3xx
Live tests passed for `event-hubs` and `servicebus`.
Related: #9281, #9282, #9283

[core-amqp] Update runtime dependency "stream-browserify"

---

sdk/core/core-http/package.json

Dev dependency `ts-loader` appears to be unused.  The only package which depends on it is `core-http`, and there are no other references to `ts-loader` in `package.json` or the source code.
https://github.com/Azure/azure-sdk-for-js/search?q=ts-loader&unscoped_q=ts-loader

[core-http] Remove unused dev dependency "ts-loader"

---

sdk/servicebus/service-bus/package.json

- No runtime or dev dependency on "async-lock"
Live tests for `servicebus` passed.

[service-bus] Remove unused dev dependency "@types/async-lock"

---

sdk/servicebus/service-bus/migrationguide.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/samples/javascript/README.md
sdk/servicebus/service-bus/samples/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/typescript/README.md
sdk/servicebus/service-bus/samples/typescript/src/browseMessages.ts
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/models.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts
sdk/servicebus/service-bus/test/renewLockSessions.spec.ts
sdk/servicebus/service-bus/test/retries.spec.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts
sdk/servicebus/service-bus/test/sessionsRequiredCleanEntityTests.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/smoketest.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/utils/testutils2.ts

Based on recent design discussions and user studies, we have decided to revert the naming change made to the peek operation. The name `peek` is a standard term used for the operation being discussed for queues. Changing it can cause confusion or reduce clarity on what the method is meant to do.

[Service Bus] browse -> peek

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/vscodeCredential.ts
sdk/identity/identity/src/index.ts

This makes a few changes to adjust to the current DAC recommendation:
* VSCodeCredential and AzureCliCredential are now publicly exported so devs can get to them directly
* We also expose a helper method on DefaultAzureCredential which will return the same chain of credentials that DAC will create by default. This will allow users to explore them and learn from them as they see fit.
In addition to these changes, we should also include running the manual tests against a ChainedTokenCredential built from this new DAC helper

[Identity] Make credentials and DAC list public

---

rush.json

This PR changes ```@azure/template``` from being designated a ```utility``` to being ```client``` in the Rush configuration. The reason for this is that the template pipeline is failing in the Integration stage on the nightly runs because it doesn't have a dev suffix.
In other repos we actually do release our template package and use it as a bit of a canary for when we are making engineering systems changes (it allows us to bump the version and test releases end-to-end). Even though it means we are publishing a useless package, there are some benefits around having this canary mechanism.
Without doing this we would need to adjust all the scripts which work with client packages to make sure that they know to skip ```@azure/template``` for whatever they do.
It does appear that …

Make @azure/template a client library so it participates in dev versioning

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/migrationguide.md
sdk/eventhub/event-hubs/samples/javascript/receiveEvents.js
sdk/eventhub/event-hubs/samples/typescript/src/receiveEvents.ts
sdk/eventhub/event-hubs/src/eventHubConsumerClientModels.ts

Addresses some documentation issues reported in:
#8419 
#8798 (Note, the 1st item in issue was already previously resolved)
#8873 
Also updates the date for the 5.2.1 release.

[event-hubs] doc improvements

---

sdk/cosmosdb/cosmos/src/client/Container/Containers.ts

The content of the comment in the method is the same as that described in `Databases.createIfNotExists()`, and it does not match the content of `Containers.createIfNotExists()`, so it was corrected.

Incorrect comment in Containers.createIfNotExists()

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/utils/headers.ts

This is causing a downstream portal bug where Firefox is not properly setting the auth header due to the incorrect casing.

[Cosmos] Use constants for auth headers returned by generateHeaders function

---

sdk/eventhub/event-hubs/test/node/disconnects.spec.ts

This should guard against either of the two reasons the receiver disconnect test may be flaky:
https://github.com/Azure/azure-sdk-for-js/pull/9343#issuecomment-639891210
1. It sets the event position to the current time rather than the start of the event hub, so it should not receive any messages.
2. The 2nd receiveBatch takes 2 seconds instead of 1 second to run now. We know that rhea's idle method waits 1 second before closing the socket, so this should guard against a race condition where receiveBatch returns before idle completes its work.

[event-hubs] fix flaky disconnect test

---

sdk/eventhub/event-hubs/migrationguide.md
sdk/eventhub/event-hubs/test/node/disconnects.spec.ts

Addresses comments added to #9342 after merging.
Also makes the receiver disconnect test resistant to clock skew by starting at the last known sequence number in the partition (exclusive).
Sorry for the whitespace changes...the formatter ran on save...and I'm not sure why it didn't last time. It does appear to fix some extra white space and match our formatting though.

[event-hubs] migration guide and test updates

---

sdk/search/search-documents/README.md
sdk/search/search-documents/samples/javascript/readonlyQuery.js
sdk/search/search-documents/samples/typescript/src/readonlyQuery.ts

Minor change in the sample

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/README.md
sdk/servicebus/service-bus/samples/javascript/advanced/managementClient.js
sdk/servicebus/service-bus/samples/typescript/README.md
sdk/servicebus/service-bus/samples/typescript/src/advanced/managementClient.ts

Adding JS and TS samples, updating readmes

[Service Bus] Sample for SBManagementClient

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/serializer.ts
sdk/core/core-http/test/data/TestClient/src/models/mappers.ts
sdk/core/core-http/test/serializationTests.ts

**Problem**
Given a mapper with flattened modelProperties, if the first defined parameter of a flattened property is a constant, we drop it in serialization.
For example, the mapper below would drop `details.capacity` when serializing since it is the first property of details defined and it is also a constant. However if `maxProductDisplayName` was defined before capacity, both properties would be serialized as expected.
```typescript
{
type: {
name: "Composite",
className: "SimpleProduct",
modelProperties: {
id: {
serializedName: "id",
constraints: {},
required: true,
type: {
name: "Number"
}
},
name: {
serializedName: "name",
required: true,
type: {
name: "String"
}
},
capacity: {
defaultValue: "Large",
isConstant: true,
serializedName: "details.max_product_capacity",
type: {
name: …
```

[core-http] Fix constant flattened property serialization

---

sdk/textanalytics/ai-text-analytics/README.md
sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md
sdk/textanalytics/ai-text-analytics/test/README.md

- Fix the other half of the code fence that I thought was just dangling (I have no idea how this even happened).
- De-localized all links (removed "en-us" from urls)

[ai-text-analytics] Final doc fixes before GA

---

sdk/textanalytics/ai-text-analytics/README.md

The ability to use `undefined` as a union discriminant wasn't added until TS 3.2, so I've added a note to the error-handling docs in the README showing explaining that 3.1 users will have to cast, and showing how to do it.

[ai-text-analytics] add caveat note about TS 3.1

---

sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/samples/typescript/tsconfig.json

Fixing some issues with the samples:
- Needed to add in AsyncIterable
- `useProxy.ts` was incorrectly importing ws, causing it to not actually use a proxy.
- `useProxy.ts` wasn't compiling against later versions of https-proxy-agent
Fixes #9371

[service-bus] Fixing some issues with the samples

---

sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/samples/javascript/advanced/sessionRoundRobin.js
sdk/servicebus/service-bus/samples/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesLoop.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/javascript/usingAadAuth.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts
sdk/servicebus/service-bus/samples/typescript/src/browseMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/samples/typescript/src/usingAadAuth.ts

Fixing formatting using the current prettier version and adding the samples to the `format` target for Service Bus.
(This was purely a `npm run format` run)

[service-bus] Fix formatting of samples

---

sdk/eventhub/event-hubs/test/eventProcessor.spec.ts
sdk/eventhub/event-hubs/test/utils/subscriptionHandlerForTests.ts

This PR updates the `startingFromHere()` helper method to no longer support `EventHubClient`.
This is part of a multiple series of code changes required to 
- have tests depend on public api surface where possible
- reduce internal dependency on `EventHubClient` so that it can be eventually removed altogether

[Event Hubs] Update startingFromHere helper to stop using EventHubClient

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-arm/package.json
sdk/core/core-auth/package.json
sdk/core/core-http/package.json
sdk/core/core-https/package.json
sdk/core/core-lro/package.json
sdk/core/core-tracing/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json
sdk/template/template/package.json
sdk/test-utils/recorder/package.json
sdk/textanalytics/ai-text-analytics/package.json

To compare the output before and after this change, remove the ".txt" extension and open in a web browser.
[browser-stats-before.html.txt](https://github.com/Azure/azure-sdk-for-js/files/4733921/browser-stats-before.html.txt)
[browser-stats-after.html.txt](https://github.com/Azure/azure-sdk-for-js/files/4733919/browser-stats-after.html.txt)
* Drops support for Node 8
* Shouldn't break us since we only run `rollup` on Node 10+
* Requires `rollup >= 1.2.0`
* Our `package.json` requests `rollup@^1.16.3`, but `pnpm-lock.yaml` contains `1.32.1`
https://github.com/btd/rollup-plugin-visualizer/blob/master/CHANGELOG.md#400

Update dev dependency "rollup-plugin-visualizer"

---

sdk/appconfiguration/app-configuration/samples/javascript/optimisticConcurrencyViaEtag.js
sdk/appconfiguration/app-configuration/samples/javascript/package.json
sdk/appconfiguration/app-configuration/samples/typescript/src/optimisticConcurrencyViaEtag.ts

- Adding in a check that'll at least print when the results are incorrect so we don't run into this again.
- Fixing package.json - we don't have a next tag now that AppConfig is GA.

[appconfig] Updating optimisticConcurrencyViaETag to include changes from #9451.

---

common/config/rush/pnpm-lock.yaml
sdk/core/core-amqp/package.json
sdk/core/core-http/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

Node 8 is no longer supported, however `puppeteer` is only used for browser testing where we use Node 10 or higher.
https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0
https://github.com/puppeteer/puppeteer/pull/5365

Update dev dependency "puppeteer"

---

sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/internal/sender.spec.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/retries.spec.ts
sdk/servicebus/service-bus/test/smoketest.spec.ts

This slipped through the type checks that we had and would result in the user sending a message with an empty body.
Fixes #9167

[service-bus] Throw an error if the user tries to just send a string (sender.send(string))

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeReceiptFromUrl.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeReceiptFromUrl.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formrecognizerclient.spec.ts

in the custom form/receipt recognition options.  This was missed in the
consistency push.

[FormRecognizer] rename includeTextDetails to includeTextContent

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/test/eventHubConsumerClient.spec.ts

Fixes #9289 
The EventHubConsumerClient subscription could deadlock if the user's `processError` handler was invoked with a non partition-specific error (e.g. unable to get partition ids) __and__ the user awaited `subscription.close()` within `processError`.
This behavior is being caused because we have some circular awaits in this scenario. Here's what's happening:
1. EventProcessor loop begins.
2. Call to get partition ids fail due to bad eventHubName, enter catch block in loop.
3. Inside catch block, we await processError.
4. User's processError awaits subscription.close().
5. subscription.close() waits for the EventProcessor loop to exit before yielding.
It's at this point that we've reached a holding pattern, since processError won't yield to the loop until the loop has …

[event-hubs] fix subscription deadlock

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/core/messageReceiver.ts
sdk/servicebus/service-bus/src/core/messageSender.ts
sdk/servicebus/service-bus/src/core/streamingReceiver.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/internal/abortSignal.spec.ts
sdk/servicebus/service-bus/test/internal/batchingReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/unittestUtils.ts
sdk/servicebus/service-bus/test/internal/utils.spec.ts
sdk/servicebus/service-bus/test/utils/abortSignalTestUtils.ts

- Plumbing abortSignal through so it can be used to cancel the init() call in subscribe() and any part of receiveBatch()
- Standardizing our AbortError message for all the new abortSignal work for Sender and Receiver. 
Part of #4375

[service-bus] T2: Enabling abort in receiveBatch and subscribe

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/test/requestResponse.spec.ts

Fixes #9287.
In `core-amqp`, the `sendRequest` method on `RequestResponseLink` has a timeout that can be specified by the user.
Currently when a message is received with a successful status code, the timer is cleared. However, it is not cleared if a message is received with an error status code. This caused the timer to remain active until the operation timeout was reached, preventing the node.js process from exiting.
This change moves the clearTimeout call right above where we check the status code of the message so that it is applied for all messages.

[core-amqp] ensure sendRequest timeout is cleared for all responses

---

sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/eventHubProducerClient.ts
sdk/eventhub/event-hubs/src/impl/eventHubClient.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/sender.ts
sdk/eventhub/event-hubs/test/client.spec.ts
sdk/eventhub/event-hubs/test/hubruntime.spec.ts
sdk/eventhub/event-hubs/test/node/disconnects.spec.ts

This PR has changes to make the class `EventHubProducerClient` no longer dependent on the internal `EventHubClient` class. This gets us one step closer to our goals in #6505
Noteworthy changes:
- The code in `EventHubClient.close()` is moved to `ConnectionContext.close()` so that it can be re-used in `EventHubProducerClient.close()`
- The code in the `EventHubClient` constructor to create the connection context is moved to a helper method so that it is re-usable in `EventHubProducerClient`
- `EventHubClient.createProducer()` is removed in favor of instantiating the `EventHubProducer` class directly in `EventHubProducerClient`. This method was needed when `EventHubClient` was the public facing client.
- `EventHubProducer` constructor does not need event hub name and namespace to be passed …

[Event Hubs] Remove EventHubClient dependency in ProducerClient

---

eng/pipelines/templates/steps/use-node-test-version.yml
rush.json

Adds the following warnings during `rush install`, though these seem harmless and there appears to be no way to configure rush to prevent these warnings:
```
WARN  Deprecated options: 'lock', 'resolution-strategy'
```

Update pnpm to v5

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/serviceModels.ts

This is related to PR: https://github.com/Azure/azure-sdk-for-js/issues/9318 
1. The text parameter is moved from method parameter to inside the options bag. 
2. No action is taken for the second part of the issue. A comment has been added to mention one of the analyzerename or tokenizername is required. 

Move text from method parameter to options bag

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

- follow-redirects@1.12.0 adds a peer dependency on "debug"
- http-proxy@1.18.1 depends on follow-redirects@^1.0.0, but does not depend on "debug", which causes an error due to missing peer dependencies
- rush update --full

Pin dev dependency "follow-redirects"

---

sdk/eventhub/event-hubs/samples/javascript/package.json
sdk/eventhub/event-hubs/samples/typescript/package.json
sdk/eventhub/event-hubs/samples/typescript/src/websockets.ts
sdk/eventhub/event-hubs/samples/typescript/tsconfig.json

Propagating the fixes we found for #9412 (websockets/proxy samples were broken) to the sample here.
Some small issues:
- The tsconfig.json needed to have esModulesInterop turned on
- package.json for both the JS and TS samples were referencing a tag we no longer publish (changed to 'latest' rather than 'next')
- Small changes for the TS so it can compile properly using `import`, rather than `require`.
Fixes #9415

[event-hubs] Fixing websockets sample to line up with Service Bus

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

- follow-redirects@1.12.1 removes peer dependency "debug"
- Fixes #9612

Unpin dev dependency "follow-redirects"

---

sdk/identity/identity/karma.conf.js
sdk/identity/identity/package.json

Wondered why "test-utils-recorder" was in the dependency tree while building the service-bus package. Looked into identity package, the tests don't depend on the recorder, hence removing it from the devDependencies.
This PR would reduce the build time :)
I believe, it got unintentionally added in https://github.com/Azure/azure-sdk-for-js/pull/8839

[Identity] Remove unneeded devDependency "test-utils-recorder"

---

sdk/formrecognizer/ai-form-recognizer/samples/javascript/copyModel.js

to remove the TypeScript keyword from copy-n-paste

[FormRecognizer] fix JavaScript copy model sample

---

sdk/core/core-http/src/coreHttp.ts
sdk/core/core-http/src/nodeFetchHttpClient.ts
sdk/core/core-http/src/policies/disableResponseDecompressionPolicy.browser.ts
sdk/core/core-http/src/policies/disableResponseDecompressionPolicy.ts
sdk/core/core-http/src/policies/systemErrorRetryPolicy.ts
sdk/core/core-http/test/policies/bearerTokenAuthenticationPolicyTests.ts
sdk/core/core-http/test/policies/disableResponseDecompressionPolicy.browser.ts
sdk/core/core-http/test/policies/disableResponseDecompressionPolicy.node.ts
sdk/core/core-http/test/policies/proxyPolicyTests.node.ts
sdk/core/core-http/test/policies/systemErrorRetryPolicyTests.spec.ts
sdk/core/core-http/test/utilsTests.ts
sdk/core/core-http/test/xmlTests.ts

This PR has changes from running `npm run format` on the `core-http` package in order to reduce the noise in the PR #8687

[core-http] Run formatter

---

sdk/core/core-http/src/policies/msRestUserAgentPolicy.browser.ts
sdk/core/core-http/src/serviceClient.ts
sdk/core/core-http/test/msRestUserAgentPolicyTests.browser.ts
sdk/core/core-http/test/serviceClientTests.ts

Based on the analysis at https://github.com/Azure/azure-sdk-for-js/issues/6530#issuecomment-642326789
* KeyVault service doesn't support CORS yet which means no browser support
* Storage doesn't send x-ms-command-name or x-ms-useragent for browsers as they
are not using core-http user agent policy
* Event Hubs/Service Bus don't use http
* Rest of services allows the x-ms-useragent header key
it is safe to change the header key for browser user agent information from
`x-ms-command-name` to `x-ms-useragent` in core-http.
Updates to AppConfiguration and Storage libraries will be in separate PRs.

[core-http] change browser telemetry header key to x-ms-useragent

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/generated/data/models/index.ts
sdk/search/search-documents/src/generated/data/models/mappers.ts
sdk/search/search-documents/src/indexModels.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/swagger/Data.md

This PR contains code changes for 2 issues:
1. Code changes to nest user defined fields into a document property
2. Mark options field with default empty object for suggest & autocomplete APIs
Tested with samples end to end and confirmed the code changes are working fine. 

Code changes to nest user defined fields into a document property

---

sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts

Based on the discussion from https://github.com/Azure/azure-sdk-for-js/pull/9430#discussion_r440320811...
Adding the wiki link(https://en.wikipedia.org/wiki/ISO_8601#Durations) in the doc strings for all the attributes that rely on ISO-8601 duration format.

[Service Bus] More info in the doc strings for ISO-8601 duration format

---

.scripts/readme.ts
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/README.md
sdk/search/search-documents/package.json
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/models/parameters.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts
sdk/search/search-documents/swagger/Data.md
sdk/search/search-documents/swagger/Service.md

1. In the swagger configuration files (`Data.md`, `Service.md`) under the `swagger` file, changed the input files to point from `preview/2019-05-06-preview` to `preview/2020-06-30` folder. 
2. The regeneration of the SDK (as a result of the above change) does not produce any code changes. 
3. Modifed `apiVersion` property value in `searchClient.ts`, `searchIndexClient.ts` and `searchIndexerClient.ts` files from `2019-05-06-Preview` to `2020-06-30`. 
4. The next version (to be released) is supposed to be `1.0.0-preview.5`. But, now it has been decided that it is going to be `11.0.0` (https://github.com/Azure/azure-sdk-for-js/issues/9671). So, I have changed the version reference in `Changelog`, `package.json`, etc. 
5. Added release details in Changelog.
6. Minor Typo in Readme.
@xirzec …

Regeneration and Other changes

---

sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/src/eventHubSender.ts
sdk/eventhub/event-hubs/src/eventProcessor.ts
sdk/eventhub/event-hubs/src/managementClient.ts
sdk/eventhub/event-hubs/src/partitionPump.ts
sdk/eventhub/event-hubs/src/receiveHandler.ts
sdk/eventhub/event-hubs/src/util/error.ts

Addresses #8481 from the event-hubs side. This ensures that error stack traces don't show up in logs under warning logging.

[event-hubs] ensure error stack traces only logged in verbose mode

---

sdk/core/core-amqp/src/cbs.ts
sdk/core/core-amqp/src/requestResponseLink.ts

Addresses #8481 from the core-amqp side. This ensures that error stack traces don't show up in logs under `warning` logging.

[core-amqp] ensure error stack traces only logged in verbose mode

---

sdk/servicebus/service-bus/README.md

We were missing the proper link in our readme for "what is service bus?" leading people to wonder what is "what is service bus?".
Fixes #9683

[service-bus] Missing the necessary link for "what is service bus?" in the readme

---

sdk/keyvault/keyvault-common/package.json
sdk/tables/azure-tables/package.json
sdk/tables/ci.yml

These two libraries were not updated in #9539, possibly due to the exception of core-http v1.1.1 made for storage and
these two files came after #9539 was created/the the exception was made.

[keyvault-common,table] bump core-http dep version to 1.1.4

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/generated/service/models/index.ts
sdk/search/search-documents/src/generated/service/models/mappers.ts

A new swagger update has happened on June 25 https://github.com/Azure/azure-rest-api-specs/pull/9968 which removes the SkillSetCounter property in ServiceCounters model. 
This PR is to accomodate that change. Only change is regenerate the SDK and update the changelog.

Remove SkillSetCounter Py in ServiceCounters model

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

Since there are some bug fixes in core-amqp 1.1.4 that were made for service bus and event hubs, we should make that version our new minimum.

[event-hubs][service-bus] update core-amqp to 1.1.4

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/trainUnlabeledModel.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/trainUnlabeledModel.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/mappers.ts
sdk/formrecognizer/ai-form-recognizer/src/lro/copy/poller.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/swagger/README.md
sdk/formrecognizer/ai-form-recognizer/test/node/formtrainingclient.spec.ts

- Rename properties `requestedOn` to `trainingStartedOn` and `completedOn` to `trainingCompletedOn` in `CustomFormModel` and `CustomFormModelInfo` types.

[FormRecognizer] Renames based on Arch Board feedback

---

sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

Here's what comes to mind. Feedback appreciated.
TODOs:
Once approved:
Fixes #9033

[KeyVault] Documenting the lack of browser support

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/test/functional/item.spec.ts

Fix #9734
When the parition key is the 'id' field, it must be generated before being extracted.

Generate id before extracting partition key

---

sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/receivers/shared.ts
sdk/servicebus/service-bus/test/internal/shared.spec.ts

As part of formalizing processError being async we also need to handle errors that might be thrown from it.
This is an internals change but not contract breaking or changelog worthy. :)
Fixes #7836

[service-bus] Make sure we properly handle processError being treated as async.

---

sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/src/util/errors.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts

In v1 of the Service Bus package, we had checks in the `createReceiver()` method to throw an error if a receiver for a session is asked and one already exists. This was done so that we can throw the error early in the game instead of making user wait until they make a call on the receiver to get the error.
In v7 of the Service Bus package, we have a dedicated method for creating session receiver and it is async to cover the part of actually creating a receiver link with the service. Due to this we no longer need the custom error we were throwing before.
This PR removes such checks, improves error message for such cases, and adds tests.

Service Bus] Remove check for session exists when creating session receiver

---

sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts

The tracking of expired sessions and throwing a custom SessionLockLostError when a message from such a session is attempted to be settled was introduced in #1180 to fix #1051 which was about unhelpful errors.
When a session lock expires, the AMQP receiver link first gets an error and then gets closed resulting in the corresponding instance of the `MessageSession` class getting cleared from the cache. We now have code in place which throws the `SessionLockLostError` with message `Failed to settle the message as the AMQP link with which the message was received is no longer alive` on not finding the right `MessageSession` instance in cache.
Therefore, we no longer need to track the expired sessions on our end and throw our own SessionLockLostError.
The tests in `renewSessionLock.spec.ts` …

[Service Bus] Tracking expired sessions is not needed

---

sdk/appconfiguration/app-configuration/README.md

Also, prettier made some minor formatting changes that looked good.

[app-configuration] Fixing readme with feedback from Cala.

---

sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/src/serviceBusMessageBatch.ts
sdk/servicebus/service-bus/test/internal/sender.spec.ts

This PR ensures we have input validation in all apis that take messages as input.
Resolves #9487

[Service Bus] Add isServiceBusMessage checks to all methods that take messages

---

sdk/formrecognizer/ai-form-recognizer/test/mocked.spec.ts

Two PRs that were green were merged, but conflicted with each other, so this should take care of that.
- requestedOn -> trainingStartedOn
- completedOn -> trainingCompletedOn
- removed credentials from GeneratedClient construction in tests

[ai-form-recognizer] Fix a merge conflict related to requestedOn -> trainingStartedOn

---

sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts

The `Receiver` interface is what the user would get as the return type and therefore the docs on the methods in the interface is what gets shown in the editor or API references.
This PR makes the below changes
- Updates the docs on the methods in the interface `Receiver` to reflect the current state of changes
- Removes the docs on the corresponding methods in the implementation. Maintaining two sets of docs would result in one of them getting stale at some point or the other.

[Service Bus] Remove redundant docs between interfaces and implementations

---

common/config/rush/common-versions.json
sdk/storage/storage-blob-changefeed/CHANGELOG.md
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md

[Discussion in Teams](https://teams.microsoft.com/l/message/19:344f6b5b36ba414daa15473942c7477b@thread.skype/1593573639993?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1593573639993&teamName=Azure%20SDK&channelName=Language%20%E2%80%93%20JS%E2%80%89%EF%BC%86%E2%80%89TS%20%F0%9F%90%B1%E2%80%8D%F0%9F%91%A4&createdTime=1593573639993)
Use "rc" for blob, changefeed, datalake, file.
Queue will be GA.

[storage] version bump up for stg73 preview release

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/pipelines/templates/steps/stage-artifacts.yml

This is a fix to avoid the match on shorter package name accidentally match the longer package name.
For eg - if there is a package `core-http` then the regex `core-http*` also matches `core-https` . To avoid this situation we are introducing some fixes in the parameters for matching artifact name and matching .zip packages

Fix release artifacts parameter name for passing to stage-artifacts.yml 

---

sdk/cosmosdb/cosmos/package.json

In #8936, the `build` script was made to use the `lint` script, but the `lint` script uses eslint and is not yet ready to be turned on due to the multiple errors that still need to be fixed.
This PR gets us back to the temporary fix we had put in place in #5429 so that we continue maintaining status quo for some more time

[Cosmos] Fail build on lint errors

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/policies/exponentialRetryPolicy.ts
sdk/core/core-http/test/policies/exponentialRetryPolicyTests.spec.ts
sdk/keyvault/keyvault-certificates/test/public/list.spec.ts

The refactoring in PR #9667 introduce a behavior change: when the response is
undefined we retry.  This is different from the previous behavior that we don't
retry on undefined response or response.status.
Also the `delay()` and `_nextPolicy.sendRequest()` call should be inside the
try-block.

[core-http] Fix a regression in exponential retry policy

---

common/config/rush/common-versions.json
sdk/cosmosdb/cosmos/package.json
sdk/eventhub/event-processor-host/package.json

This PR updates the last 2 packages in the repo that were still using v2 of the eslint plugin

Update eslint plugin version to 3.0

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-js-release.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml

Add Changelog / Release Notes verification to the build / release pipeline.

Enable ChangeLog Verification in Repo

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/differentiateLabeledUnlabeled.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/getBoundingBoxes.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeReceiptFromUrl.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/differentiateLabeledUnlabeled.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/getBoundingBoxes.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeReceiptFromUrl.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formrecognizerclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/node/formtrainingclient.spec.ts
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts

We want to support non-text elements (e.g. checkboxes, other types of structured form items) in form fields, but the names we have now heavily suggest that all data are text. This addresses this by giving these fields a more generic name.
Field names:
- labelText -> labelData (on FormField)
- valueText -> valueData (on FormField)
- textContent -> fieldElements (on FieldData, FormTableCell)
Type names:
- FieldText -> FieldData
- FormContent -> FormElement
Client Option:
- includeTextContent -> includeFieldElements

[ai-form-recognizer] Anticipating support for non-text field elements

---

sdk/cosmosdb/cosmos/src/client/Item/ItemDefinition.ts
sdk/cosmosdb/cosmos/src/common/constants.ts
sdk/cosmosdb/cosmos/src/queryIterator.ts
sdk/cosmosdb/cosmos/src/queryMetrics/timeSpan.ts
sdk/cosmosdb/cosmos/src/utils/atob.browser.ts
sdk/cosmosdb/cosmos/src/utils/atob.ts
sdk/cosmosdb/cosmos/src/utils/digest.browser.ts
sdk/cosmosdb/cosmos/src/utils/digest.ts
sdk/cosmosdb/cosmos/src/utils/encode.ts
sdk/cosmosdb/cosmos/src/utils/globalCrypto.ts
sdk/cosmosdb/cosmos/src/utils/hashObject.ts
sdk/cosmosdb/cosmos/src/utils/headers.ts
sdk/cosmosdb/cosmos/src/utils/hmac.browser.ts
sdk/cosmosdb/cosmos/src/utils/hmac.ts
sdk/cosmosdb/cosmos/src/utils/types.ts
sdk/cosmosdb/cosmos/src/utils/user-agent.browser.ts
sdk/cosmosdb/cosmos/src/utils/user-agent.ts
sdk/cosmosdb/cosmos/test/mocha.env.ts
sdk/cosmosdb/cosmos/test/unit/auth.spec.ts

This PR adds the copyright text to files in the cosmos package that are missing it.
This is a step towards fixing the linter errors from the common eslint plugin used in this repo.

[Cosmos] Add missing copyright text

---

sdk/identity/identity/rollup.base.config.js

This PR fixes the rollup script to avoid the below warning

[Identity] Fix warning on unresolved dependencies

---

sdk/identity/identity/rollup.base.config.js

This PR fixes the rollup script to avoid the below warning when building test code

[Identity] Fix warning on unresolved dependencies when building tests

---

sdk/cognitiveservices/cognitiveservices-customvision-prediction/package.json
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/predictionAPIClient.ts
sdk/cognitiveservices/cognitiveservices-customvision-prediction/src/predictionAPIClientContext.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/package.json
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/index.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/mappers.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/models/parameters.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/trainingAPIClient.ts
sdk/cognitiveservices/cognitiveservices-customvision-training/src/trainingAPIClientContext.ts

**Commands Used**
```autorest --typescript --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/saranganrajamanickam/Projects/azure-sdk-for-js --use=@microsoft.azure/autorest.typescript@4.2.4 --package-version=5.1.0 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/16178fee3c9288bd43fd4db804e4b010257f1414/specification/cognitiveservices/data-plane/CustomVision/Prediction/readme.md
AutoRest code generation utility [version: 2.0.4283; node: v10.15.3]
Loading AutoRest core      '/usr/local/lib/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
Loading AutoRest extension '@microsoft.azure/autorest.typescript' (4.2.4->4.2.4)
Loading AutoRest extension '@microsoft.azure/autorest.modeler' …
```

Release Custom Vision Prediction & Training - July 2020

---

sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/src/utils/utils.browser.ts
sdk/storage/storage-blob/src/utils/utils.node.ts
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/src/utils/utils.browser.ts
sdk/storage/storage-file-datalake/src/utils/utils.node.ts
sdk/storage/storage-file-share/src/ShareFileClient.ts
sdk/storage/storage-file-share/src/utils/utils.browser.ts
sdk/storage/storage-file-share/src/utils/utils.node.ts

Put them in utils.node instead, and add stubs for browsers.

[Storage] avoid importing fs directly in exporting modules

---

sdk/cosmosdb/cosmos/test/functional/container.spec.ts
sdk/cosmosdb/cosmos/test/integration/encoding.spec.ts

The backend recently removed the ability for new containers to use lazy indexing. As a result, some of our tests are failing. We need to keep the IndexingMode.lazy around as some older accounts will still have this ability enabled. Without this change, master tests will start failing soon.

Remove Lazy Index Tests

---

common/config/rush/common-versions.json
sdk/keyvault/keyvault-admin/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/package.json

Revert "Make exception for storage"
This reverts commit a3035f8256e11105d9d16615f7e7809aa40fd1ff.

[Storage] Revert the exception made for storage when bumping core-http dep version

---

sdk/servicebus/service-bus/src/receivers/receiver.ts

There was disagreement about the returned type between the doc comment
and the code itself.

[servicebus] docs: fix type in doc comment

---

sdk/servicebus/service-bus/test/internal/atomXml.spec.ts

The tests in atomXml.spec.ts file are unit tests of sorts, target internal classes and do not need any live test resources.
The right home for these are in the "internal" folder so that they are run as part of PR CI and not just the nightly CI
This separation of internal tests will eventually help us in having a set of tests that test only the public facing api which can then be used for our min/max dependency version testing

[Service Bus] atomXml.spec.ts has internal tests

---

eng/tools/dependency-testing/index.js

- Silly silly mistake that fixes the error we ran into - https://github.com/Azure/azure-sdk-for-js/issues/9933

fixing the logic to add to the common-versions.json

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/defaultAzureCredential.ts

After the arch board yesterday, and some conversations today, looks like the simplest way forward for 1.1 is to remove the export of the DAC credentials. We'll review customer feedback as 1.1 ships to see what delta from here we need to ensure that the transition from DAC to ChainedTokenCredential is as smooth as possible.

[Identity] Remove exporting the DAC credentials list

---

sdk/servicebus/service-bus/src/util/errors.ts

Now that the SubscriptionRuleManager is removed with https://github.com/Azure/azure-sdk-for-js/pull/9952, nobody is using these helper methods. 
Moreover, they refer to the client from track1 and are not relevant in track 2.

[Service Bus] Remove unused helper methods

---

sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/connectionContext.ts

This PR replaces the use of `Dictionary` which is custom type defined in rhea-promise with inlined types based on the suggestion in https://github.com/Azure/azure-sdk-for-js/pull/9710#discussion_r451159031

[Service Bus] Avoid using Dictionary

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/test/requestResponse.spec.ts

Fixes #9615 
This change ensures that when a `RequestResponseLink` is closed, the sender and receiver are closed before the session.
Previously, when `this.sender.close()` was called, the session was also closed. 
Interestingly, after the sender and session were closed, I'd see a new see a new message arrive on the (cbs) receiver followed immediately by a new session being created. This appears to be in response to the EventHubConsumerClient calling `receiveBatch`, and triggering a race condition where the cbs receiver hasn't been explicitly closed yet, but the session has been.
Next `this.receiver.close()` is called, and viewed as already being closed.
I can tell from the logs that the session the cbs receiver was attached to was session 0, and the error from the service says it can't …

[core-amqp] close session after sender and receiver in requestResponseLink

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/tools/versioning/set-dev.js
sdk/tables/ci.yml
sdk/template/ci.yml

- Prevent private packages from being published to dev feed or failing at npm step- as such packages  won't get the dev tag
- Adding an option with the artifact parameter in ci.yml 
- Example of this is done in tables ci.yml in this PR and this works - https://dev.azure.com/azure-sdk/public/_build/results?buildId=453563&view=results

Preventing dev feed for private package on script level and with artifact parameter option in pipeline

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/core/managementClient.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/internal/atomXml.spec.ts
sdk/servicebus/service-bus/test/propsToModify.spec.ts
sdk/servicebus/service-bus/test/utils/testUtils.ts

Renaming the `userProperties` attribute to `properties` in both ServiceBusMessage and CorrelationFilter to stay consistent with .NET, Java and python SDKs.

[Service Bus] Renaming `userProperties` to `properties` - Both ServiceBusMessage and ATOM API

---

sdk/test-utils/recorder/src/customConsoleLog.ts
sdk/test-utils/recorder/test/browser/recorder.spec.ts

In function `customConsoleLog()` we save `window.console.log` to a
local variable and use this variable to log to real console.  The
problem is that when `customConsoleLog()` is called multiple times,
`window.console.log` is no longer the original one, and we end up
nesting the modified `log` function again and again.
This PR saves the original console log function to a module level
variable instead so it's not wrapped multiple times.
Fixes #6475

[Test Recorder] Fix browser custom console logging when recording

---

eng/tools/dependency-testing/templates/package.json
sdk/keyvault/keyvault-certificates/karma.conf.js
sdk/keyvault/keyvault-certificates/package.json

This recent PR changed the tests so that they waited for all of the pollers we use: https://github.com/Azure/azure-sdk-for-js/pull/9879 
Since then, the timeout used for tests is no longer accurate for live tests. For that reason, I'm making this PR to ensure that live tests can pass as expected.

[Key Vault Certificates] Test timeout need to be increased since now we wait for all pollers

---

sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts

Receivers can die if they exceed the maximum number of retries that we configure internally.
This is by design in track 1 (ie, 1.1.x) and we're hesitant to change that behavior since the library is already established and doing so might destabilize customers. This is being revisited in track 2 but for now we're going to release a sample that shows how to properly recover from these kinds of errors.
Partial addressing of #9958

[service-bus] Add in receiver restart into the standard sample for .registerMessageHandler

---

sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts

Fixing sample to only recover when .retryable is true (ie, "escaped" retryable errors).
Still a partial fix for #9958 in that it demonstrates the recovery technique.

[service-bus] Fixing sample to only recover when .retryable is true (ie, "escaped" errors)

---

sdk/test-utils/recorder/package.json

Adding sdk-type = client to package.json of test-utils-recorder - otherwise rush-runner script doesn't detect this package for tests and runs tests for all packages under rush.json

fixing test-utils-recorder package.json

---

sdk/storage/storage-blob/src/policies/StorageSharedKeyCredentialPolicy.ts
sdk/storage/storage-file-datalake/src/policies/StorageSharedKeyCredentialPolicy.ts
sdk/storage/storage-file-share/src/policies/StorageSharedKeyCredentialPolicy.ts
sdk/storage/storage-queue/src/policies/StorageSharedKeyCredentialPolicy.ts

Fix issue #9300. Recover content-length header which is previously removed for Axios known issue(https://github.com/axios/axios/issues/2107).

Recover content-length header which is previously removed for Axios.

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/propsToModify.spec.ts

[Service Bus] Exposing `deadLetterErrorDescription` and `deadLetterReason` on the `ReceivedMessage`

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/src/session/messageSession.ts
sdk/servicebus/service-bus/test/internal/batchingReceiver.spec.ts
sdk/servicebus/service-bus/test/internal/messageSession.spec.ts

[sessions] Changing our receiveMessages() algorithm to match .NET's.
The new version works like this:
receive(maxMessages, maxWaitTime)
Internally we then wait for:
1. maxMessages to arrive
2. maxWaitTime to expire
or
3. An internal 1 second timeout that will fire _after_ the first message
has been received _or_ the remaining time left from `maxWaitTime` (whichever one
is smaller)
Complements #9968 and is the final change for #9718

[service-bus] Change MessageSession over to using the .NET receiveMessages algorithm

---

sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/errors.ts

Rename the argument to the constructor to AggregateAuthenticationError based on arch board feedback.
cc @bterlson

[Identity] Rename argument to AggregateAuthenticationError

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/client/Container/index.ts
sdk/cosmosdb/cosmos/src/client/Database/index.ts
sdk/cosmosdb/cosmos/src/client/Permission/index.ts
sdk/cosmosdb/cosmos/src/documents/index.ts
sdk/cosmosdb/cosmos/src/index.ts
sdk/cosmosdb/cosmos/src/request/ErrorResponse.ts
sdk/cosmosdb/cosmos/src/request/index.ts

The [api extractor output](https://github.com/Azure/azure-sdk-for-js/blob/%40azure/cosmos_3.7.4/sdk/cosmosdb/cosmos/review/cosmos.api.md) for the cosmos package has about 20 warnings for forgotten exports. The common eslint plugin throws linting errors for the same.
This PR attempts to fix the least controversial of these forgotten exports.
Pending forgotten exports are:
- `VerboseOmit`: This is documented as "Shim for Omit added in TypeScript 3.5". Am not sure whether this should be exported or not
- `CosmosHeaders`: There are 2 CosmosHeaders defined in the package. Product owners need to decide if they want to export both, or remove one in favor of the other
-  `FetchFunctionCallback`: This is marked as `@hidden`, so not sure what the intent here was

[Cosmos] Fix missing exports warnings

---

sdk/identity/identity/package.json
sdk/identity/identity/src/credentials/vscodeCredential.ts

As keytar does not build on all platforms where we support Azure Identity, make keytar an optional dependency. If keytar is not available, fail gracefully with a message telling the user why the VSCode credential could not be used.
Helps to address https://github.com/Azure/azure-sdk-for-js/issues/9288 and related issues, where the given platform may not have the ability to install the dependencies keytar needs (and therefore keytar fails to build), or on a platform where keytar itself isn't support (eg on Linux running without X11/Xorg).

[Identity] Make keytar an optional dependency

---

sdk/tables/azure-tables/package.json

Tables SDK doesn't have any test yet, so disabling the test step while we work on the test suite

[Tables] Disable test step

---

sdk/storage/storage-file-datalake/src/generated/src/operations/pathOperations.ts
sdk/storage/storage-file-datalake/swagger/README.md

Using the fix suggested in https://github.com/Azure/azure-sdk-for-js/issues/9436

[storage] [datalake] adding parameter location for PathSetAccessControlRecursiveMode

---

eng/tools/versioning/set-dev.js

- This PR adds logic to check rush common-versions for the exact version the dev tags are being replaced for - if that version is present in common-versions- then update common-versions adding the dev version as an exception too.

Fix broken storage pipeline

---

sdk/eventhub/event-hubs/src/connectionContext.ts
sdk/eventhub/event-hubs/src/linkEntity.ts
sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/src/connectionContext.ts
sdk/servicebus/service-bus/src/core/linkEntity.ts
sdk/servicebus/service-bus/test/batchReceiver.spec.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts

Addresses #9914 for service bus 7.x
Fixes #9926 `TypeError: Cannot read property 'idle_time_out' of undefined`.
Similar PR for service bus 1.x: https://github.com/Azure/azure-sdk-for-js/pull/10046
This change ports the uncaught TypeError fixes that were made in event-hubs in #8884. It also ensures that existing token renewal timeouts are cleared when an entity receiver/sender is brought back up.
https://github.com/Azure/azure-sdk-for-js/pull/8884#issue-417044472 contains a detailed description for the changes made to `ConnectionContext` to ensure that the connection has been refreshed before attempting to bring a connection back up.
When a client is brought back up after a disconnect, `_ensureTokenRenewal` is called. Since we weren't clearing the existing timer before replacing it, the …

[service-bus] fix uncaught TypeError

---

sdk/eventhub/event-hubs/test/receiver.spec.ts

There was a maxWaitTime of 0 seconds put in place for a test case as a workaround for bug #8598.
The bug was then fixed in #9543 which was closed in favor of #9567
Therefore, removing the workaround

[Event Hubs] Remove workaround for bug 8598 in test

---

.github/CODEOWNERS

Adding @bingisbestest and @nerajput1607 as code owners for the qna maker packages as per https://github.com/Azure/azure-sdk-for-js/issues/10161#issuecomment-662648547

Add code owners for QnA Maker

---

common/smoke-test/KeyVault.ts
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/constants.ts
sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/vscodeCredential.ts
sdk/identity/identity/src/index.ts

This is a small batch of changes ahead of the out-of-band release. These include:
* Renaming KnownAuthorityHost to AzureAuthorityHost
* Making tenant id part of the option bag for DAC and VSCodeCredential
* Update the changelog

[Identity] Changes for the out-of-band identity release

---

sdk/cognitiveservices/cognitiveservices-qnamaker-runtime/README.md

This PR is to fix the issue https://github.com/Azure/azure-sdk-for-js/issues/10158. Changes included in this PR:
1. **JS Sample**
a. Changes TS Code Sample to JS Code Sample
b. Changed `QnAMakerClient` to `QnAMakerRuntimeClient`
2. **HTML Sample**
a. Removed the reference to `@azure/ms-rest-browserauth`
b. `kbid` was not declared which will cause error. So, added a declaration for that.
c. `cognitiveServiceCredentials` was not defined correctly. Fixed the definition.
I haved tested both the samples and confirmed that the code changes are working fine. 
Interestingly, While testing these samples, I have found another issue with `@azure/ms-rest-js` package(version: 2.0.6). In essence, if you try to run the HTML sample with ms-rest-js version 2.0.6, you are going to hit error. This is true …

Fix sample code on the QnAMaker Readme

---

sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/src/eventHubReceiver.ts
sdk/eventhub/event-hubs/test/receiver.spec.ts

Fixes #9704 
This update fixes an issue with `receiveBatch` where events could fail to make it to the user, appearing to be 'skipped'.
This could happen if the user requested N messages, N - M events arrived, and a retryable error (e.g. network issue) caused the `receiveBatch` call to exhaust its retries.
The `EventHubReceiver` keeps an internal checkpoint of the last event it received so that each `receiveBatch` call knows what position to start receiving events from. It also has an `_internalQueue` that holds any events that were received but haven't been returned by a `receiveBatch` call yet. This internal queue protects us from losing any messages that make it to the client after `receiveBatch` yields.
`receiveBatch` collects the specified number of events to be received before …

[event-hubs] fixes receiveBatch error handling to preserve received events

---

sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/authenticationMethods.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/getBoundingBoxes.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeContent.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/recognizeCustomForm.js
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/authenticationMethods.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/getBoundingBoxes.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeContent.ts
sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeCustomForm.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts
sdk/formrecognizer/ai-form-recognizer/test/transforms.spec.ts

Closes #10033 
We've decided not to use a "rows" array for the GA release of the library. This patch reverts to the same "cells"-only design that the service returns.

[ai-form-recognizer] Revert table rows -> cells only

---

sdk/eventhub/eventhubs-checkpointstore-blob/CHANGELOG.md
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts

Fixes #10132
This update changes the way `updateCheckpoint` works such that it will always attempt to set blob metadata first, then fallback to creating a new blob if it doesn't already exist.
Previously, we always called `upload` to replace the existing blob. This caused a performance issue when listing checkpoints in Storage Blob Containers that had soft-delete or blob versioning enabled.

[eventhubs-checkpointstore-blob] fix listCheckpoints performance with versioned containers
