Azure/azure-sdk-for-js

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/policies/exponentialRetryPolicy.ts
sdk/core/core-http/src/policies/systemErrorRetryPolicy.ts
sdk/core/core-http/src/util/exponentialBackOffRetry.ts
sdk/core/core-http/src/util/exponentialBackoffStrategy.ts
sdk/core/core-http/test/policies/systemErrorRetryPolicyTests.spec.ts

Refactor to share common code of `ExponentialRetryPolicy` and `SystemErrorRetryPolicy`.
Also change the multiplier to have initial value of 1.
Address #4201 and code-reuse part of #9569

[core-http] Share common code for exponential backoff

---

sdk/formrecognizer/ai-form-recognizer/README.md
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/src/transforms.ts

- Add ref doc to FormField.value and FormField.valueType
- Filter RecognizedForm.pages to those relevant to the recognized form
- Remove `||` from sample snippets

[FormRecognizer] address issues/feedbacks from UX study

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/serializers/namespaceResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/atomXml.spec.ts

The final fate of the timestamp attributes as per the discussion from https://github.com/Azure/azure-sdk-for-js/issues/9375#issuecomment-651498762

[Service Bus] Change suffix for time stamp attributes from "On" to "At" 

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/receivers/receiver.ts
sdk/servicebus/service-bus/src/receivers/sessionReceiver.ts
sdk/servicebus/service-bus/test/streamingReceiver.spec.ts
sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts

[Service Bus] Removing `isReceivingMessages` from the Receiver API Surface

---

sdk/recoveryservicesbackup/arm-recoveryservicesbackup/package.json
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupEnginesMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupJobsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupPoliciesMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectableItemsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectedItemsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectionContainersMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectionIntentMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupResourceStorageConfigsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupResourceVaultConfigsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupWorkloadItemsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/index.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/itemLevelRecoveryConnectionsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/jobDetailsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/mappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/privateEndpointConnectionOperationsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectableContainersMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectedItemOperationResultsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectedItemsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionContainerOperationResultsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionContainersMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionIntentOperationsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionPoliciesMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionPolicyOperationResultsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/recoveryPointsMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/restoresMappers.ts
sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/recoveryServicesBackupClientContext.ts

Re-generate arm-recoveryservicesbackup to fix missing nextLink  in ResourceLists
Fixes #7630

[arm-recoveryservicesbackup] Re-generate to fix missing nextLink

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/samples/javascript/authenticationMethods.js
sdk/formrecognizer/ai-form-recognizer/samples/javascript/package.json

- A couple of fixes to a JS sample that I found while doing release testing
- Update the CHANGELOG release date

[ai-form-recognizer] Final preview.4 changes

---

eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/stages/cosmos-sdk-client.yml

Clean up repository resources.

Clean up resources

---

sdk/storage/storage-blob/recordings/browsers/blobclient/recording_create_page_blob_should_work_with_tags.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_create_page_blob_should_work_with_tags.js
sdk/storage/storage-blob/test/blobclient.spec.ts

The previous is failing as the deletion may take some time.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=450915&view=logs&j=bbd7d436-e05d-51a8-99a8-0701dc9dffeb&t=b35bd286-0ff8-5789-8141-60cce3239968

[storage] fix an unstable test case

---

sdk/eventhub/event-hubs/test/README.md
sdk/identity/identity/README.md

I'm trying to fix the analyze step

Link fixes

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/README.md

/cc @richardpark-msft <- let me know when your sample is ready!

[service-bus] prepare for 1.1.8 release

---

sdk/servicebus/service-bus/samples-v1/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples-v1/typescript/src/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/javascript/README.md
sdk/servicebus/service-bus/samples/javascript/advanced/deferral.js
sdk/servicebus/service-bus/samples/javascript/advanced/managementClient.js
sdk/servicebus/service-bus/samples/javascript/advanced/movingMessagesToDLQ.js
sdk/servicebus/service-bus/samples/javascript/advanced/processMessageFromDLQ.js
sdk/servicebus/service-bus/samples/javascript/advanced/sessionState.js
sdk/servicebus/service-bus/samples/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesLoop.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/javascript/scheduledMessages.js
sdk/servicebus/service-bus/samples/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/javascript/session.js
sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/javascript/usingAadAuth.js
sdk/servicebus/service-bus/samples/typescript/README.md
sdk/servicebus/service-bus/samples/typescript/src/advanced/deferral.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/managementClient.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/movingMessagesToDLQ.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/processMessageFromDLQ.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionState.ts
sdk/servicebus/service-bus/samples/typescript/src/browseMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesLoop.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/typescript/src/scheduledMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/sendMessages.ts
sdk/servicebus/service-bus/samples/typescript/src/session.ts
sdk/servicebus/service-bus/samples/typescript/src/useProxy.ts
sdk/servicebus/service-bus/samples/typescript/src/usingAadAuth.ts

This is just copying over the changes from PR#10058

[service-bus] Copy over the exact sample for receiveMessagesStreaming.js/ts from 1.1.8

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_getproperties_and_listblob_rehydratepriority_eq_high.json
sdk/storage/storage-blob/recordings/browsers/blobclient/recording_getproperties_and_listblob_rehydratepriority_eq_standard.json
sdk/storage/storage-blob/recordings/node/blobclient/recording_getproperties_and_listblob_rehydratepriority_eq_high.js
sdk/storage/storage-blob/recordings/node/blobclient/recording_getproperties_and_listblob_rehydratepriority_eq_standard.js
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/generated/src/models/index.ts
sdk/storage/storage-blob/src/generated/src/models/mappers.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/blobclient.spec.ts

.NET PR: https://github.com/Azure/azure-sdk-for-net/pull/12982

[storage][[stg73] rehydrate priority

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/topicResourceSerializer.ts
sdk/servicebus/service-bus/src/serviceBusAtomManagementClient.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts

This PR renames the interfaces *Description to *Properties as a step towards the renames and edits being tracked in #10081

[Service Bus] Description -> Properties

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/src/searchClient.ts

This PR is to address the issue https://github.com/Azure/azure-sdk-for-js/issues/10128 
Thanks a lot for @Oblarg for reporting and pointing the code to be fixed. 
@xirzec Please review and approve. 

Pass in the correct continuation token for search documents

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/serializers/queueResourceSerializer.ts
sdk/servicebus/service-bus/src/serializers/subscriptionResourceSerializer.ts
sdk/servicebus/service-bus/src/util/utils.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts

Flatten MessageCountDetails and rename `messageCount` to `totalMessageCount` to resolve #10082

[Service Bus] Flatten MessageCountDetails

---

sdk/identity/identity/src/credentials/vscodeCredential.ts

[Identity] Just a typo I found

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/advanced/managementClient.js
sdk/servicebus/service-bus/samples/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/managementClient.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionRoundRobin.ts
sdk/servicebus/service-bus/samples/typescript/src/browseMessages.ts

This PR fixes #10188 which lists a bunch of places in the readme and samples where the apis dont match what we have in the source code

[Service Bus] Fix broken code in readme and samples

---

sdk/eventhub/eventhubs-checkpointstore-blob/tests.yml

[eventhubs-checkpointstore-blob] add live tests job

---

sdk/eventhub/event-hubs/karma.conf.js
sdk/eventhub/event-hubs/rollup.base.config.js
sdk/eventhub/event-hubs/test/client.spec.ts

Fixes #4666 
I was able to remove other shims as well since rhea has been updated to be more bundler friendly.

[event-hubs] cleanup rollup config

---

sdk/appconfiguration/app-configuration/README.md

[app-configuration] Fixing issue with readme snippet for getConfiguration()

---

sdk/test-utils/perfstress/test/nodeFetch.spec.ts
sdk/test-utils/perfstress/test/sleep.spec.ts
sdk/test-utils/recorder/test/node/utils.spec.ts

[Test Utils] formatting

---

sdk/servicebus/service-bus/samples/javascript/advanced/managementClient.js
sdk/servicebus/service-bus/samples/javascript/advanced/sessionState.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/managementClient.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/sessionState.ts
sdk/servicebus/service-bus/src/clientEntityContext.ts
sdk/servicebus/service-bus/src/core/batchingReceiver.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/utils/managementUtils.ts

[Service Bus] formatting

---

sdk/search/search-documents/karma.conf.js
sdk/search/search-documents/src/searchClient.ts

[Search] formatting

---

sdk/identity/identity/src/credentials/defaultAzureCredential.ts
sdk/identity/identity/src/credentials/vscodeCredential.ts
sdk/identity/identity/src/index.ts

[Identity] formatting

---

sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/test/internal/http.spec.ts

[App Configuration] formatting

---

common/tools/eslint-plugin-azure-sdk/README.md
common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts

[Common] format

---

sdk/textanalytics/ai-text-analytics/karma.conf.js
sdk/textanalytics/ai-text-analytics/src/detectLanguageResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizeLinkedEntitiesResultArray.ts

[Text Analytics] formatting

---

sdk/tables/azure-tables/package.json

[Tables] formatting

---

common/config/rush/pnpm-lock.yaml
sdk/appconfiguration/app-configuration/package.json
sdk/core/abort-controller/package.json
sdk/core/core-amqp/package.json
sdk/core/core-client/package.json
sdk/core/core-http/package.json
sdk/core/core-https/package.json
sdk/core/core-lro/package.json
sdk/core/logger/package.json
sdk/eventhub/event-hubs/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/identity/identity/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/search/search-documents/package.json
sdk/servicebus/service-bus/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/package.json
sdk/storage/storage-internal-avro/package.json
sdk/storage/storage-queue/package.json
sdk/tables/azure-tables/package.json
sdk/template/template/package.json
sdk/test-utils/perfstress/package.json
sdk/test-utils/recorder/package.json
sdk/textanalytics/ai-text-analytics/package.json

I hope this works 😁
I did test this locally on Identity and KeyVault Secrets, both on node and the browser, both in record and playback, and it did work!

Upgrading to karma 5.1.0

---

sdk/core/core-http/src/policies/exponentialRetryPolicy.ts
sdk/core/core-http/test/policies/exponentialRetryPolicyTests.spec.ts
sdk/core/core-tracing/.eslintrc.json
sdk/core/core-tracing/package.json

[Core] formatting

---

sdk/eventhub/eventhubs-checkpointstore-blob/CHANGELOG.md

[eventhubs-checkpointstore-blob] prepare for 1.0.1 release

---

sdk/cognitiveservices/cognitiveservices-customvision-training/README.md
sdk/cognitiveservices/cognitiveservices-customvision-training/package.json
sdk/cognitiveservices/cognitiveservices-customvision-training/src/trainingAPIClientContext.ts

Changed it based on feedback from #10362 
@areddish

Fixed CustomVision Training sample to use ApiKeyCredentials

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/README.md

Fixes Issue https://github.com/Azure/azure-sdk-for-js/issues/10243 
The third `odata` issue is not an issue. I have validated that node runs correctly with `odata` keyword. So, I did not fix it. Other changes are incorporated. 
Patch version has already been updated. Once it is merged, I will start the release process. 
@xirzec/@ramya-rao-a Please review and approve

Fixed Search Readme

---

sdk/marketplaceordering/arm-marketplaceordering/LICENSE.txt
sdk/marketplaceordering/arm-marketplaceordering/README.md
sdk/marketplaceordering/arm-marketplaceordering/package.json
sdk/marketplaceordering/arm-marketplaceordering/rollup.config.js
sdk/marketplaceordering/arm-marketplaceordering/src/marketplaceOrderingAgreementsContext.ts
sdk/marketplaceordering/arm-marketplaceordering/tsconfig.json

release-for-mgmt-marketplaceordering

---

sdk/authorization/arm-authorization/README.md
sdk/authorization/arm-authorization/package.json
sdk/authorization/arm-authorization/src/authorizationManagementClientContext.ts

Updating imports in `arm-authorization` sample so that the code can be run in Javascript and Typescript.
See #10318 for context

[arm-authorization] Update sample imports to work with JS

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/package.json
sdk/core/core-http/src/util/constants.ts
sdk/core/core-tracing/CHANGELOG.md

for core-tracing and core-http

[core] update changelog for August release

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts
sdk/search/search-documents/src/searchClient.ts

This PR is to fix the issue https://github.com/Azure/azure-sdk-for-js/issues/10442. 
Incremented patch version.

Fix parented tracing span in search API

---

eng/pipelines/templates/stages/archetype-js-release.yml

[Successful Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=483588&view=results)

Enable JS Docs.MS CI Onboarding

---

sdk/servicebus/service-bus/src/serviceBusClient.ts

This PR updates the docs on relevant methods to clarify when a connection is actually made to the service.
Fixes #10135

[Service Bus] Clarify when a connection is made to the service

---

sdk/identity/identity/package.json

Fixes #9282 
I couldn't find anything weird with this. 🤔

[Identity] Removed stream-browserify

---

sdk/tables/azure-tables/review/tables.api.md
sdk/tables/azure-tables/src/TableClient.ts
sdk/tables/azure-tables/src/TableServiceClient.ts

[Tables] Add delete method to TableClient

---

common/tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-keywords.md
common/tools/eslint-plugin-azure-sdk/package.json
common/tools/eslint-plugin-azure-sdk/src/rules/ts-package-json-keywords.ts
common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-keywords.ts

~The tests fail on my machine for this package with the following message `sh: 1: unit-test:node: not found`, not sure why, so I could not verify if this is all what is needed.~
EDIT: it turns out the npm test script was broken. I verified all tests work.

[ESLint] Update package.json rule to use lowercase azure

---

sdk/privatedns/arm-privatedns/LICENSE.txt
sdk/privatedns/arm-privatedns/README.md
sdk/privatedns/arm-privatedns/package.json
sdk/privatedns/arm-privatedns/rollup.config.js
sdk/privatedns/arm-privatedns/src/privateDnsManagementClientContext.ts
sdk/privatedns/arm-privatedns/tsconfig.json

issue:  https://github.com/Azure/azure-sdk-for-js/issues/10458

release privatedns in compatibale with @azure/ms-rest-nodeauth

---

common/git-hooks/pre-commit

Run `rush update` to install the new version of the hook.

Skip prettying during merge

---

sdk/identity/identity/CHANGELOG.md

[Identity] Fixed typo on the CHANGELOG.md

---

sdk/storage/storage-blob-changefeed/README.md
sdk/storage/storage-blob-changefeed/samples/typescript/resume.ts

Fix https://github.com/Azure/azure-sdk-for-js/issues/10248
Add a summary of examples and modify parameters

Modify changefeed README.md and typescript sample resume.ts

---

sdk/formrecognizer/ai-form-recognizer/README.md

Fix https://github.com/Azure/azure-sdk-for-js/issues/10245
Add a summary of examples.

Modify formrecognizer/ai-form-recognizer/README.md

---

sdk/cognitiveservices/cognitiveservices-qnamaker-runtime/package.json
sdk/cognitiveservices/cognitiveservices-qnamaker-runtime/src/qnAMakerRuntimeClientContext.ts
sdk/cognitiveservices/cognitiveservices-qnamaker/package.json
sdk/cognitiveservices/cognitiveservices-qnamaker/src/qnAMakerClientContext.ts

This is related to the issue https://github.com/Azure/azure-sdk-for-js/issues/10304 
@ramya-rao-a Please review and approve

Update Version in QnAMaker & QnAMaker Runtime

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

Bumps changelog and package.json versions to 3.8

[Cosmos] Bump version to 3.8

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/constants.ts
sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts

- changed version number to 3.0.0-preview.1
- Added `BeginRecognizeReceiptsOptions` (straight alias) to align with other languages.

[ai-form-recognizer] Final changes for 3.0.0-preview.1

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

Pass artifacts parameter so that verify changelog step has something to run on.

Pass artifcats to cosmos ci job

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml

Resolves [this failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=489948&view=logs&j=5b5da614-455a-5033-5d68-6326090fc11b&t=c4942afe-99e6-5410-d9b8-65bacd11acad).

Add TargetRepo Params for Cosmos-Client.yml

---

sdk/textanalytics/ai-text-analytics/samples/javascript/README.md
sdk/textanalytics/ai-text-analytics/samples/typescript/README.md

[Text Analytics] Update Opinion Mining samples links

---

sdk/storage/storage-blob/README.md

Fix https://github.com/Azure/azure-sdk-for-js/issues/10246
Add a summary of examples

Modify storage-blob/README.md

---

sdk/storage/storage-file-datalake/README.md

Fix https://github.com/Azure/azure-sdk-for-js/issues/10247
Add a summary of examples

Modify storage-file-datalake/README.md

---

sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/stronglyTypingRecognizedForm.ts

There was an issue with the shape of the strongly typed model sample that I found while testing the release candidate for today's preview, and this fixes it by adding more wrapping to correctly model the service's response structure.

[ai-form-recognizer] Fix strongly typed model sample

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

Bumps version to 3.8.1 pending release

[Cosmos] Adds 3.8.1 changelog and version bump

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

Pushes autoscale and URL release as 3.9

[Cosmos] Push to 3.9.0

---

sdk/monitor/opentelemetry-exporter/package.json

[opentelemetry-exporter] Master seems to be broken because of missing package.json scripts

---

sdk/tables/azure-tables/review/tables.api.md
sdk/tables/azure-tables/samples/typescript/src/connectionString.ts
sdk/tables/azure-tables/src/TableClient.ts
sdk/tables/azure-tables/src/TableServiceClient.ts
sdk/tables/azure-tables/src/generatedModels.ts
sdk/tables/azure-tables/src/models.ts

* Flatten `value` property in get and list responses 
* Convert types with index properties to generic
Coming up in the next PR:
* Integration tests for our operations
/cc: @mahdiva

[Tables] Flatten responses

---

sdk/template/ci.yml

Enabling PR runs on `eng/common` changes to help end to end testing of changes to Eng Common

Trigger template PR run from changes to common

---

sdk/storage/storage-file-datalake/tests.yml
sdk/storage/test-resources-post.ps1
sdk/storage/test-resources.json

Fix https://github.com/Azure/azure-sdk-for-js/issues/10171.
Do not skip tests in live tests.

[storage][test] datalake live tests pipeline config

---

eng/pipelines/aggregate-reports.yml

Add Repository Resource Ref verification to aggregate reports pipeline.

Add Ref verification to aggregate report pipeline

---

sdk/appconfiguration/arm-appconfiguration/package.json
sdk/appconfiguration/arm-appconfiguration/src/appConfigurationManagementClientContext.ts
sdk/appconfiguration/arm-appconfiguration/src/models/index.ts
sdk/appconfiguration/arm-appconfiguration/src/models/mappers.ts

https://github.com/Azure/sdk-release-request/issues/692

Release sdk 692

---

sdk/storage/storage-blob/recordings/browsers/blobserviceclient/recording_setproperties_for_static_website.json
sdk/storage/storage-blob/recordings/node/blobserviceclient/recording_setproperties_for_static_website.js
sdk/storage/storage-blob/test/blobserviceclient.spec.ts

Reference:
https://github.com/wastore/azure-docs-rest-apis/pull/73
https://github.com/Azure/azure-sdk-for-net/pull/12954

[storage-blob] service properties's static website add a new field defaultIndexDocumentPath

---

sdk/anomalydetector/ai-anomaly-detector/CHANGELOG.md
sdk/anomalydetector/ci.yml

* Updating changelog with release date
* Fix package name in ci.yml

[Anomaly Detector] Update CI and changelog

---

sdk/monitor/opentelemetry-exporter/package.json
sdk/monitor/opentelemetry-exporter/test/unit/breezeTestUtils.ts
sdk/monitor/opentelemetry-exporter/test/unit/export/export.test.ts
sdk/monitor/opentelemetry-exporter/test/unit/platform/nodejs/httpSender.test.ts
sdk/monitor/opentelemetry-exporter/test/unit/platform/nodejs/persist/fileSystemPersist.test.ts
sdk/monitor/opentelemetry-exporter/test/unit/utils/connectionStringParser.test.ts
sdk/monitor/opentelemetry-exporter/test/unit/utils/eventhub.test.ts
sdk/monitor/opentelemetry-exporter/test/unit/utils/spanUtils.test.ts

- Move unit tests to `test/unit/` to prepare for `test/integration/`, etc folders

[Monitor] move unit tests to /test/unit folder

---

sdk/cosmosdb/cosmos/CHANGELOG.md

[Cosmos] Fixes release date

---

sdk/tables/data-tables/README.md

Updating README file to contain information to get started with the Tables SDK and align with the guidelines: https://review.docs.microsoft.com/en-us/help/contribute-ref/contribute-ref-how-to-document-sdk?branch=master#readme

[Tables] Update README

---

.github/CODEOWNERS

Update CODEOWNERS to add label and reviewers for Azure Template changes.

Update codeowners file for Azure Template

---

sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/index.ts
sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/internal/serviceBusMessage.spec.ts

Another initial draft for AMQPAnnotatedMessage to support it from the send side - https://github.com/Azure/azure-sdk-for-js/pull/10955
Pending: Investigation into whether the new interfaces can be pushed to core-amqp

[Service Bus] Add AMQPAnnotatedMessage to the ReceivedMessage

---

eng/ignore-links.txt
sdk/digitaltwins/digitaltwins/samples/Readme.md

Fix broken links in digitaltwins.

Fix broken links

---

sdk/eventhub/event-hubs/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/sample.env
sdk/eventhub/eventhubs-checkpointstore-blob/samples/javascript/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/samples/javascript/receiveEventsUsingCheckpointStore.js
sdk/eventhub/eventhubs-checkpointstore-blob/samples/typescript/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/samples/typescript/src/receiveEventsUsingCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/snippets.spec.ts

We had a few spots where we had sample usage of eventhubs-checkpointstore-blob. Made them all syntactically correct and handle an empty array of events, which can happen when the wait timeout expires.
Fixes #11007

[event-hubs, eventhubs-checkpointstore-blob] Fixing samples and readme

---

sdk/textanalytics/ai-text-analytics/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/10962.

[Text Analysis] Add a link to opinion mining sample to README

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/Pipeline.ts
sdk/storage/storage-blob/test/node/sas.spec.ts
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/Pipeline.ts
sdk/storage/storage-file-datalake/test/node/sas.spec.ts
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/Pipeline.ts
sdk/storage/storage-file-share/test/node/sas.spec.ts
sdk/storage/storage-queue/review/storage-queue.api.md
sdk/storage/storage-queue/src/Pipeline.ts
sdk/storage/storage-queue/test/node/sas.spec.ts

[storage] make credential in newPipeline's parameters optional

---

sdk/storage/storage-blob/recordings/browsers/highlevel/recording_set_tier_while_upload.json
sdk/storage/storage-blob/recordings/node/highlevel/recording_set_tier_while_upload.js
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/Clients.ts
sdk/storage/storage-blob/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-blob/test/node/highlevel.node.spec.ts

[storage-blob] add tier option for highlevel upload

---

sdk/containerservice/arm-containerservice/package.json
sdk/containerservice/arm-containerservice/src/containerServiceClientContext.ts
sdk/containerservice/arm-containerservice/src/models/index.ts
sdk/containerservice/arm-containerservice/src/models/mappers.ts
sdk/containerservice/arm-containerservice/src/models/parameters.ts
sdk/containerservice/arm-containerservice/src/operations/managedClusters.ts

https://github.com/Azure/sdk-release-request/issues/696

Release sdk 696

---

sdk/eventhub/event-hubs/package.json
sdk/eventhub/event-hubs/test/diagnostics/messageSpan.spec.ts

[Event Hub] Prettying

---

sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/src/utils/accountConnectionString.browser.ts
sdk/tables/data-tables/src/utils/connectionString.ts
sdk/tables/data-tables/test/unit/sharedKeyCredential.spec.ts
sdk/tables/data-tables/test/unit/utils.spec.ts

[Tables] prettying

---

sdk/servicebus/service-bus/src/serviceBusMessage.ts
sdk/servicebus/service-bus/test/operationOptionsForATOM.spec.ts

[Service Bus] Prettying

---

sdk/tables/data-tables/CHANGELOG.md

Updating changelog for beta1 release

[Tables] Update changelog

---

sdk/tables/data-tables/CHANGELOG.md

[Tables] Add release date

---

eng/pipelines/templates/variables/globals.yml

Remove shallow depth variable to disable shallow git clone

Disable shallow git clone

---

sdk/appconfiguration/app-configuration/test/testHelpers.ts

[App Configuration] Prettying

---

sdk/textanalytics/ai-text-analytics/src/analyzeSentimentResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizePiiEntitiesResult.ts
sdk/textanalytics/ai-text-analytics/src/recognizePiiEntitiesResultArray.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts

[Text Analytics] Prettying

---

sdk/search/search-documents/test/node/searchClient.spec.ts
sdk/search/search-documents/test/node/searchIndexClient.spec.ts
sdk/search/search-documents/test/node/searchIndexerClient.spec.ts
sdk/search/search-documents/test/utils/setup.ts
sdk/search/search-documents/test/utils/setupIndex.ts

[Search] Prettying

---

sdk/identity/identity/src/credentials/clientCertificateCredential.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredentialOptions.ts
sdk/identity/identity/test/public/clientCertificateCredential.spec.ts

[Identity] Prettying

---

sdk/servicebus/service-bus/src/constructorHelpers.ts

Fix test failure observed at https://github.com/Azure/azure-sdk-for-js/pull/10984 (failure on master)

[Service Bus] Test fix - Followup of entityPath update

---

sdk/tables/data-tables/README.md
sdk/tables/data-tables/src/utils/constants.ts

Fixes:
- Wrong user agent
- Update version after release
- Remove locale in readme URLs
- Fix a couple of typos in README

[Tables] Fix readme, version and useragent

---

sdk/servicebus/service-bus/test/internal/errors.spec.ts

Fixes the following browser test failures.

[Service Bus] Fix browser test failures - New logging tests

---

sdk/storage/storage-blob-changefeed/README.md
sdk/storage/storage-blob/README.md
sdk/storage/storage-file-datalake/README.md

https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/835
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/836
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/837
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/838
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/839

[storage][blob] fix README.md

---

sdk/cosmosdb/cosmos/test/functional/item.spec.ts

[CosmosDB] Prettying

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/migrationguide.md

Changelog, readme and migration guide

[Service Bus] Release prep for service-bus preview.6

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-certificates/src/generated/utils/constants.ts
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/generated/utils/constants.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/src/generated/utils/constants.ts

This PR is meant to set the release tag for the September beta release for Key Vault.
For the release notes, besides the changelog of each package, you can also review the highlights here: https://github.com/Azure/azure-sdk/pull/1750/files#diff-cb6e033da257d50177572473d247e597R151-R182

[Key Vault] September release PR

---

sdk/keyvault/ci.yml

Added new keyvault package into artifact list.

Added keyvault-admin into artifact list

---

sdk/storage/storage-blob/recordings/node/blobclient/recording_create_append_blob_should_work_with_tags.js
sdk/storage/storage-blob/test/blobclient.spec.ts

Deletion takes time.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=539665&view=logs&j=bbd7d436-e05d-51a8-99a8-0701dc9dffeb&t=b35bd286-0ff8-5789-8141-60cce3239968
```
1) BlobClient
Create append blob should work with tags:
RestError: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:223ec35f-b01e-0049-2c15-8cd369000000
Time:2020-09-16T10:36:32.6490095Z</Message></Error>
at new RestError (/home/vsts/work/1/s/sdk/core/core-http/src/restError.ts:27:5)
at /home/vsts/work/1/s/sdk/core/core-http/src/policies/deserializationPolicy.ts:176:21
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

[storage][test] fix an unstable case

---

eng/pipelines/aggregate-reports.yml

Follow up PR for https://github.com/Azure/azure-sdk-for-js/pull/11317/

Enable the link check on aggregate-report

---

sdk/identity/identity/.eslintignore
sdk/identity/identity/.eslintrc.json
sdk/identity/identity/test/public/clientCertificateCredential.spec.ts
sdk/identity/identity/tsconfig.json

ESLint broke. This fixes it. 👷‍♂️🛠

[Identity] Fix broken eslint in the builds

---

sdk/servicebus/service-bus/src/serializers/ruleResourceSerializer.ts
sdk/servicebus/service-bus/src/util/atomXmlHelper.ts
sdk/servicebus/service-bus/src/util/tracing.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts
sdk/servicebus/service-bus/test/internal/errors.spec.ts
sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
sdk/servicebus/service-bus/test/sendBatch.spec.ts
sdk/servicebus/service-bus/test/sessionsRequiredCleanEntityTests.spec.ts
sdk/servicebus/service-bus/test/sessionsTests.spec.ts
sdk/servicebus/service-bus/test/streamingReceiverSessions.spec.ts

This PR has changes from running the `lint:fix` script on the Service Bus package with hopes of reducing the noise when someone wants to work on #10781

[Service Bus] Run lint:fix script

---

sdk/storage/storage-blob/README.md
sdk/storage/storage-file-datalake/README.md
sdk/storage/storage-file-share/README.md
sdk/storage/storage-queue/README.md

Add fromConnectionString method to README

---

.github/CODEOWNERS

@qiaozha This should fix the noise due to you being assigned as code reviewer everytime there is a file with the word "Management" in its name :)

Not every Management file is arm related

---

sdk/template/template/samples/javascript/package.json
sdk/template/template/samples/typescript/package.json

Samples in template project need the template package, not the identity package

Samples in template project need the template package

---

sdk/communication/communication-administration/README.md
sdk/communication/communication-administration/samples/javascript/README.md
sdk/communication/communication-administration/samples/typescript/README.md
sdk/communication/communication-chat/README.md
sdk/communication/communication-common/README.md
sdk/communication/communication-sms/README.md
sdk/communication/communication-sms/samples/javascript/README.md
sdk/communication/communication-sms/samples/typescript/README.md

This PR updates the links in communication packages to working public links.

[Communication] Update README links

---

eng/pipelines/npm-tasks.yml
eng/scripts/npm-admin-tasks.ps1
eng/tools/npm-admin-tasks.ps1

New pipeline to run npm tasks like add or remove tag, deprecate package version.

Pipeline to run self service npm tasks

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

The change in the next release is a breaking one and this PR just adds the corresponding tag to the CHANGELOG.md.

[Text Analytics] Adding breaking tag to changelog

---

sdk/textanalytics/ai-text-analytics/README.md

[Text Analytics] Fix README.md

---

sdk/keyvault/keyvault-admin/README.md

The readme had a bad reference in one of the samples.
@zzhxiaofeng Is this what you meant?
Fixes #11491

[Key Vault Admin] Fixed bad reference in the readme

---

sdk/eventhub/event-hubs/README.md

This PR fixes Azure Event Hub Readme Issue (#11494 )

Azure Event Hub Readme Issue

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushSizeBased.ts
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushTimerBased.ts
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/manualFlush.ts
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts

This PR is to update the changelog and version for the october release. 
In addition, I have added one line to the new batch samples to make sure the "unused failure" error reported [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=561564&view=logs&j=073ebbf1-9390-59a1-0ff8-08c656576bcd&t=f89087ce-ed28-5584-5ae2-a2cef8b201ba&l=112) does not happen. 

October release changes

---

sdk/identity/identity/src/credentials/managedIdentityCredential.ts

My recent changes on the ManagedIdentityCredential removed an expected behavior: The IMDS endpoint should only be pinged once. After that, we will assume that the endpoint is available.
I've added comments to help others to follow through this logic.
I've also made an issue to refactor this credential: https://github.com/Azure/azure-sdk-for-js/issues/11653

[Identity] Ensure that we only ping once

---

sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
sdk/metricsadvisor/ai-metrics-advisor/package.json

- Updated changelog with release date
- Unmarking private package to allow publish

release prep

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/migrationguide.md
sdk/servicebus/service-bus/src/core/autoLockRenewer.ts

- Still some lingering preview.6 text
- MinimalLink was getting picked up by typedoc despite the fact that it's not exported.

[service-bus] Minor updates to prep for preview.7 release

---

sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/hooks.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/incidentsAndAlerts.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/ingestionStatus.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricQueries.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/seriesData.js
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/hooks.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/incidentsAndAlerts.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/ingestionStatus.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricQueries.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/seriesData.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts

- log properties explicitly
- log different properties for union types
- add code using for-await-of to listing methods

[MetricsAdvisor] Samples improvements

---

eng/tools/generate-static-index/service-mapper.json

Ad metricsadvisor in index service mapping

Added metricadvisor service in github io doc index

---

sdk/monitor/monitor-opentelemetry-exporter/src/generated/models/index.ts
sdk/monitor/monitor-opentelemetry-exporter/src/generated/models/mappers.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/export/export.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/platform/nodejs/httpSender.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/platform/nodejs/persist/fileSystemPersist.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/utils/spanUtils.test.ts

Uses https://github.com/Azure/azure-rest-api-specs/pull/11110

[Monitor][Codegen] update codegen to use date-time timestamps

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexingBufferedSender.ts
sdk/search/search-documents/src/searchIndexingBufferedSenderImpl.ts

This is related to https://github.com/Azure/azure-sdk-for-js/issues/11784. 

Make BufferedSender an interface and Hide the Constructor

---

sdk/keyvault/keyvault-admin/samples/javascript/README.md
sdk/keyvault/keyvault-admin/samples/typescript/README.md

Christopher Scott found a bug in our readmes!

[Key Vault Admin] Samples README format fix

---

common/config/rush/pnpm-lock.yaml
sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts
sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts

[schema registry] Omit extra record methods from deserialization

---

sdk/cosmosdb/cosmos/rollup.config.js

- Added jsbi in external and global
- Modified uuid/v4 to uuid.
This PR is for the issue

added missing global varrible names

---

README.md
common/smoke-test/README.md
sdk/billing/arm-billing/README.md
sdk/eventhub/event-hubs/README.md
sdk/eventhub/event-hubs/test/README.md
sdk/identity/identity/README.md
sdk/keyvault/keyvault-certificates/test/README.md
sdk/keyvault/keyvault-secrets/test/README.md
sdk/servicebus/service-bus/test/README.md

Local git revert the last commit and then keep the link changes.

Revert the formatting changes.

---

sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts
sdk/identity/identity/src/credentials/managedIdentityCredential.ts

This PR is just about running `rushx format`, then doing `rushx lint` and see if I could do at least a small fix. It will help reduce the changes of future executions of `rushx format` and `rushx lint`!

[Identity] Formatting and one lint fix

---

sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/README.md
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/README.md

Adding metadata to samples readme

Samples readme metadata 

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Release for unmerged changes to falsy values in bulk
see #11671

[Cosmos] Adds release date for 3.9.3

---

sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/recordings/node/datalakepathclient_nodejs_only/recording_move_should_encode_source.js
sdk/storage/storage-file-datalake/src/clients.ts
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts

[storage-file-datalake] encode move source

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

Add node 14 in CI, PR and live test matrix.
Partial fix for #9462

Add node 14 in test matrix

---

eng/pipelines/prepare-pipelines.yml

This PR adds the YAML for the prepare pipelines automation.

Add prepare pipelines configuration.

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/src/sender.ts
sdk/servicebus/service-bus/test/internal/sender.spec.ts
sdk/servicebus/service-bus/test/invalidParameters.spec.ts
sdk/servicebus/service-bus/test/managementClient.spec.ts
sdk/servicebus/service-bus/test/retries.spec.ts
sdk/servicebus/service-bus/test/sendAndSchedule.spec.ts
sdk/servicebus/service-bus/test/serviceBusClient.spec.ts

[servicebus]scheduleMessages method swap enqueuedTime and messages order

---

eng/pipelines/templates/steps/analyze.yml

Added the step to avoid we ship the wrong link out of the door.

Run link verification step at CI/Manual

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/review/service-bus.api.md
sdk/servicebus/service-bus/samples/javascript/advanced/administrationClient.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/administrationClient.ts
sdk/servicebus/service-bus/src/serializers/namespaceResourceSerializer.ts
sdk/servicebus/service-bus/test/atomManagement.spec.ts

Addressing https://github.com/Azure/azure-sdk-for-js/issues/11956

fix(service-bus): removing namespaceType from NamespaceProperties

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-js-release.yml

Add default TestPipeline parameter.

Add default test pipeline parameter

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/steps/build.yml

Fix TestPipeline Parameter Bug

---

sdk/search/search-documents/samples/javascript/sample.env

Updating `Cognitive Services` to `Cognitive Search` in sample.env

Fixing typo in sample.env

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/src/common/helper.ts
sdk/cosmosdb/cosmos/src/request/defaultAgent.ts
sdk/cosmosdb/cosmos/src/utils/atob.native.ts
sdk/cosmosdb/cosmos/src/utils/globalCrypto.native.ts

Use .native.ts to create several react native specific versions of internal functions. Requires "isomorphic-webcrypto" package be installed by React Native users

Add react native support to @azure/cosmos

---

eng/pipelines/templates/stages/archetype-js-release.yml

Unlock JS release by finding artifact correctly

 Fix release script to find artifact

---

CONTRIBUTING.md

We should not use relative links: https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md#link-guidelines.

fix link in CONTRIBUTING.md, try 2

---

sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/samples/javascript/advanced/deferral.js
sdk/servicebus/service-bus/samples/javascript/advanced/processMessageFromDLQ.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/typescript/src/advanced/deferral.ts
sdk/servicebus/service-bus/samples/typescript/src/advanced/processMessageFromDLQ.ts
sdk/servicebus/service-bus/samples/typescript/src/receiveMessagesStreaming.ts
sdk/servicebus/service-bus/samples/typescript/src/sendMessages.ts

This PR updates our samples as follows:
- Update comments in certain TS samples to match what is in the JS ones
- Update the sendMessages sample to use the batch
- Update the sendMessages sample in readme to use the batch
Closes #12118

[Service Bus] Use batch in samples

---

sdk/servicebus/service-bus/CHANGELOG.md

This PR updates the changelog for the changes introduced in PRs the past couple of days

[Service Bus] Update changelog

---

sdk/servicebus/service-bus/samples/javascript/advanced/administrationClient.js
sdk/servicebus/service-bus/samples/javascript/advanced/deferral.js
sdk/servicebus/service-bus/samples/javascript/advanced/listingEntities.js
sdk/servicebus/service-bus/samples/javascript/advanced/movingMessagesToDLQ.js
sdk/servicebus/service-bus/samples/javascript/advanced/processMessageFromDLQ.js
sdk/servicebus/service-bus/samples/javascript/advanced/sessionState.js
sdk/servicebus/service-bus/samples/javascript/browseMessages.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesLoop.js
sdk/servicebus/service-bus/samples/javascript/receiveMessagesStreaming.js
sdk/servicebus/service-bus/samples/javascript/scheduledMessages.js
sdk/servicebus/service-bus/samples/javascript/sendMessages.js
sdk/servicebus/service-bus/samples/javascript/session.js
sdk/servicebus/service-bus/samples/javascript/useProxy.js
sdk/servicebus/service-bus/samples/javascript/usingAadAuth.js

I owe @HarshaNalluru an apology - these 'export main' should never have been in the JS samples :|

[service-bus] Removing the 'export' keyword that should have never been there.

---

common/smoke-test/smoke-tests.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml

Continuation of https://github.com/Azure/azure-sdk-tools/pull/1137

Use pre-installed Azure PowerShell modules

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/review/core-amqp.api.md
sdk/core/core-amqp/src/cbs.ts

Address the typo for statusDescription and fixes https://github.com/Azure/azure-sdk-for-js/issues/9031

[Core AMQP] satusDescription -> statusDescription

---

sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/src/constants.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-secrets/package.json

Updated link to constants.ts for all keyvault packages and incremented version for keyvault-keys

Update constant link for keyvault

---

sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md
sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/dataFeed.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/hooks.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/incidentsAndAlerts.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/ingestionStatus.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricQueries.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/seriesData.js
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/hooks.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/incidentsAndAlerts.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/ingestionStatus.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricQueries.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/seriesData.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
sdk/metricsadvisor/ai-metrics-advisor/test/adminclient.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/advisorclient.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/datafeed.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/hookTests.spec.ts

instead of wrapping the result array in a property.

[MetricsAdvisor] Change *PageResponse types to extend Array

---

sdk/metricsadvisor/ai-metrics-advisor/README.md

This PR fixes the readme broken link bug reported https://github.com/Azure/azure-sdk-for-js/issues/12050

fix broken link

---

common/config/rush/pnpm-lock.yaml

This PR attempts to update(weekly) the lock file with `rush update --full`

`rush update --full` 🛠

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/util/runtimeInfo.browser.ts
sdk/core/core-amqp/src/util/utils.ts

Let's release core-amqp 2.0.0-beta.1
Also fixes https://github.com/Azure/azure-sdk-for-js/issues/12156

[Core AMQP] Update Changelog date and @internal @ignore for non-exports

---

sdk/servicebus/service-bus/CHANGELOG.md

Apart from adding the date for the preview, I have moved around the changelog items to move higher impact changes up

[Service Bus] Preview 8 prep in changelog

---

eng/pipelines/npm-tasks.yml
eng/scripts/npm-admin-tasks.ps1

New option to unpublish package

Add option to unpublish package

---

sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/indexModels.ts
sdk/search/search-documents/src/searchIndexingBufferedSenderImpl.ts
sdk/search/search-documents/src/serviceUtils.ts

Based on the latest discussion in team meetings, we have decided to open up configuration options to the user and also introduce exponential back off during the retries. 

Open up Buffered Sender Configurations

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushSizeBased.ts
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/autoFlushTimerBased.ts
sdk/search/search-documents/samples/typescript/src/bufferedSender/uploadDocuments/manualFlush.ts

Updated Changelog and added 2 lines of code to handle process.
@xirzec @joheredi  Please review and approve.

November release changes

---

sdk/core/core-amqp/CHANGELOG.md

/cc @HarshaNalluru @ramya-rao-a

[core-amqp] prepare for 2.0.0 release

---

eng/scripts/Language-Settings.ps1

- Update logic in Language Settings File

Update Logic in Language Settings File

---

sdk/storage/storage-blob-changefeed/test/blobchangefeedclient.spec.ts
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_appendblockfromurl.js
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_conditional_tags_for_appendblockfromurls_destination_blob.js
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_create_appendblock_appendblockfromurl_and_download_with_cpk.js
sdk/storage/storage-blob/recordings/node/blobclient_nodejs_only/recording_synccopyfromurl.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_create_uploadpages_uploadpagesfromurl_download_clearpages_and_resize_with_cpk.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_uploadpagesfromurl.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only_conditional_tags/recording_uploadpagesfromurl_with_conditional_tags_for_destination_blob.js
sdk/storage/storage-blob/test/blobclient.spec.ts
sdk/storage/storage-blob/test/encrytion.spec.ts
sdk/storage/storage-blob/test/leaseclient.spec.ts
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts
sdk/storage/storage-blob/test/node/containerclient.spec.ts
sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
sdk/storage/storage-file-datalake/test/browser/highlevel.browser.spec.ts
sdk/storage/storage-file-datalake/test/leaseclient.spec.ts
sdk/storage/storage-file-datalake/test/node/filesystemclient.spec.ts
sdk/storage/storage-file-datalake/test/node/highlevel.node.spec.ts
sdk/storage/storage-file-datalake/test/node/pathclient.spec.ts
sdk/storage/storage-file-datalake/test/pathclient.spec.ts

"query should work with large file" case keep failing in Node8.
```
1) BlobClient Node.js only
query should work with large file:
Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\sdk\storage\storage-blob\dist-esm\storage-blob\test\node\blobclient.spec.js)
at Test.Runnable._timeoutError (D:\a\1\s\common\temp\node_modules\.pnpm\mocha@7.2.0\node_modules\mocha\lib\runnable.js:442:10)
at Timeout.<anonymous> (D:\a\1\s\common\temp\node_modules\.pnpm\mocha@7.2.0\node_modules\mocha\lib\runnable.js:252:24)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
```

[storage]fix CI

---

sdk/core/core-amqp/README.md

Add node.js support matrix in readme

---

eng/pipelines/templates/stages/archetype-js-release.yml
eng/pipelines/templates/steps/build.yml
eng/scripts/SetTestPipelineVersion.ps1

- Use build Number as prerelease version number to fix race condition.

Use build Number to fix race condition

---

sdk/core/core-paging/package.json
sdk/keyvault/keyvault-common/package.json

adding `rimraf` to devDependencies in core-paging and keyvault-common.

Fix rush clean command

---

eng/.docsettings.yml
sdk/eventhub/README.md
sdk/keyvault/README.md
sdk/servicebus/README.md

This PR adds the bare minimum to follow the [guide for service level readmes](https://review.docs.microsoft.com/en-us/help/contribute-ref/template-library-index?branch=master)
The same content will then be added for the landing pages for each service in the reference docs

Service level readmes for Service Bus, Event Hubs and Key Vault

---

sdk/servicebus/service-bus/migrationguide.md

[Service Bus] Update migration guide with perf improvements and coming up features

---

sdk/servicebus/service-bus/CHANGELOG.md

[service-bus] prepare for 7.0.0 release

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/README.md
sdk/textanalytics/ai-text-analytics/samples/javascript/README.md
sdk/textanalytics/ai-text-analytics/samples/typescript/README.md

And also update links to samples in readme files.

[Text Analytics] Update changelog for 5.1.0-beta.3 release

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/README.md
sdk/servicebus/service-bus/package.json

[service-bus] remove Preview from service-bus

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md

Last PR before 3.1.0-beta.1 is released. Release validation checklist is complete, need to re-generate a package with the correct release date in the changelog.

[ai-form-recognizer] Set 3.1.0-beta.1 release date

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

[Text Analytics] Edit CHANGELOG.md

---

eng/tools/dependency-testing/index.js
eng/tools/dependency-testing/templates/package.json
sdk/formrecognizer/ai-form-recognizer/tests.yml

- Enable min-max for form recognizer
- Change reference for test assets folder by the same script which updates the source references to package references
- Form recognizer min-max tests pass - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=627625&view=results

enable min max for form recognizer

---

eng/pipelines/templates/stages/archetype-js-release.yml

For the readme content we write.

Support moniker specific output folders

---

sdk/cosmosdb/cosmos/src/tsconfig.strict.json
sdk/cosmosdb/cosmos/src/utils/hashing/v1.ts
sdk/cosmosdb/cosmos/src/utils/hashing/v2.ts

Fixes strictness issues in `utils/hashing/v1.ts` and `utils/hashing/v2.ts` in #12745.

[Cosmos] Fix strictness issues in utils/hashing

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/src/BatchResponseParser.ts

[storage] sort batch sub response according to Content-ID

---

sdk/communication/communication-chat/review/communication-chat.api.md
sdk/communication/communication-chat/src/generated/src/models/index.ts
sdk/communication/communication-chat/src/generated/src/models/parameters.ts
sdk/communication/communication-chat/src/generated/src/operations/chat.ts

- get threads was still using maxPageSize, regenerated again with the fixed swagger

Update generated code with maxpagesize fix

---

sdk/storage/storage-blob/src/Clients.ts

Part of fix for [#12726](https://github.com/Azure/azure-sdk-for-js/issues/12726)

Fix code block - incorrect ending backtick

---

sdk/keyvault/keyvault-admin/test/README.md
sdk/keyvault/keyvault-certificates/test/README.md
sdk/keyvault/keyvault-keys/test/README.md
sdk/keyvault/keyvault-secrets/test/README.md

Adding how to set the access policies to the test READMEs.
Fixes #9774

[Key Vault] AAD Access Policies

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/package.json
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/client/msalClient.ts

Updating the msal-node version to 1.0.0-beta.1

[Identity] Fix the identity build

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-http/src/url.ts
sdk/core/core-http/src/util/url.browser.ts
sdk/core/core-http/src/util/url.ts

Remove unused URLSearchParams causing an issue with IE11. Fixes #12828

[core-http] Remove unused URLSearchParams

---

sdk/communication/communication-chat/README.md

To fix issue([12919](https://github.com/Azure/azure-sdk-for-js/issues/12919)).
@jongio for notification

Update Communication Chat README

---

dataplane.code-workspace

I noticed these packages were managed by rush but they are not in the dataplane workspace. I am not 100% if all these packages should be added to the workspace so I would love to hear your thoughts.

Add dataplane pckgs

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/scripts/Language-Settings.ps1

Create API review automatically from CI

Create API review from scheduled CI

---

sdk/keyvault/keyvault-secrets/migration-guide.md

Migration guide for Key Vault Secrets.
Part of #12365 
Known to-dos (mostly from feedback on https://github.com/Azure/azure-sdk-for-js/pull/12978):
- Add section with the type differences.
Reviews appreciated 🙏

[Key Vault Secrets] Migration guide

---

sdk/keyvault/keyvault-certificates/migration-guide.md

Migration guide for Key Vault Certificates.
Part of #12365 
Known to-dos (mostly from feedback on https://github.com/Azure/azure-sdk-for-js/pull/12978):
- Add section with the type differences.
Reviews appreciated 🙏

[Key Vault Certificates] Migration guide

---

sdk/storage/storage-file-datalake/README.md

Fix https://github.com/Azure/azure-sdk-for-js/issues/11495

Fix datalake Readme issue

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/samples/javascript/src/batchOperations.js
sdk/tables/data-tables/samples/javascript/src/queryEntities.js
sdk/tables/data-tables/samples/javascript/src/updateAndUpsertEntities.js
sdk/tables/data-tables/samples/typescript/src/batchOperations.ts
sdk/tables/data-tables/samples/typescript/src/queryEntities.ts
sdk/tables/data-tables/samples/typescript/src/updateAndUpsertEntities.ts

Fixes #12914 . Also adding a sample on how to query topN items

[Tables] Fix typos in samples

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/13088

[Identity] upgrade axios version

---

eng/scripts/Language-Settings.ps1
eng/tools/versioning/VersionUtils.js
eng/tools/versioning/increment.js
eng/tools/versioning/set-version.js

- Use `eng\common\scripts\Update-ChangeLog.ps1` rather than `eng\common\Update-Change-Log.ps1`

Update update changelog

---

sdk/identity/identity/CHANGELOG.md

Changelog entry for Identity 1.2.1

---

.github/CODEOWNERS

I'm switching to using this account for all work-related GitHub activity.

Update CODEOWNERS with my new GitHub account

---

sdk/communication/communication-administration/README.md
sdk/communication/communication-chat/README.md
sdk/communication/communication-common/README.md
sdk/communication/communication-sms/README.md

Add PowerShell documentation on how to create a Communication Service Resource.

[Communication] - ALL - Adding PowerShell Docs to README

---

eng/pipelines/templates/steps/monitor-additional-steps.yml

Forgot to update this path when we renamed the package

[monitor] Fix monitor CI script

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json
sdk/identity/identity/src/client/msalClient.ts
sdk/identity/identity/src/credentials/deviceCodeCredential.ts
sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts

This should be the last step in removing the vulnerable Axios dependency.

[Identity] Bump msal-node dep

---

sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
sdk/keyvault/keyvault-keys/src/generated/models/index.ts
sdk/keyvault/keyvault-keys/swagger/README.md

In our V6 Generated SDKs, the clients inside our generated layers are getting exposed in docs. So, Updating the SDK to add hidden tags.
Note: The comments change is due to upgrade in ts-morph. 
@sadasant Please review and approve.

Adding hidden tag to generated clients

---

sdk/monitor/opentelemetry-exporter-azure-monitor/CHANGELOG.md

Forgot to set this for the release. Oops!

[monitor] Set changelog release date

---

eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/template/ci.yml

Use conditional logic for setting TestPipeline parameter to true
Should fix https://github.com/Azure/azure-sdk-for-net/issues/17569#event-4193128149

Use conditional logic for setting TestPipeline parameter to true

---

sdk/attestation/attestation/package.json

This is required for CI pipeline to behave correctly.

[Attestation] Adds sdk-type to package.json

---

sdk/attestation/attestation/CHANGELOG.md

[Attestation] Set release date

---

eng/scripts/Language-Settings.ps1

Add `LanguageDisplayName` variable.

Add LanguageDisplayName variable to Language-Settings file

---

.github/CODEOWNERS

add chradek to API codeowners list

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/credentials/UserDelegationKeyCredential.browser.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/credentials/UserDelegationKeyCredential.browser.ts

[storage] add shim for UserDelegationKeyCredential in browser

---

sdk/storage/storage-blob/test/perfstress/track-2/core-https.spec.ts

Fix build failure on master

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json

Increment package version after release of azure-cosmos.

Increment version for cosmosdb releases

---

sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/src/utils/constants.ts
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts

Increment package version after release of azure-storage-blob.
Changelog for storage-blob and storage-file-share has already been updated.

Increment version for storage releases

---

common/config/rush/pnpm-lock.yaml
dataplane.code-workspace
sdk/core/core-crypto/karma.conf.js
sdk/core/core-crypto/package.json

#13309 didn't catch this because core-crypto went in around the same time.

[core-crypto] Remove karma-remap-istanbul dependency

---

sdk/servicebus/service-bus/src/core/shared.ts

This PR removes a hidden tag to see how that affects the docs published at docs.microsoft.com

[Service Bus] Remove hidden tag for an interface to test the effects on docs.microsoft.com

---

sdk/cosmosdb/cosmos/package.json

The sign off test command is currently broken

[Cosmos] Fix signoff test command

---

eng/CredScanSuppression.json

Suppress credscan for fake secrets

Suppress credscan for dake secrets

---

eng/scripts/npm-admin-tasks.ps1

Deprecate all package version when version is set to all

Add option to deprecate all packages in npm admin task

---

sdk/hdinsight/arm-hdinsight/LICENSE.txt
sdk/hdinsight/arm-hdinsight/package.json
sdk/hdinsight/arm-hdinsight/src/hDInsightManagementClientContext.ts
sdk/hdinsight/arm-hdinsight/src/models/applicationsMappers.ts
sdk/hdinsight/arm-hdinsight/src/models/clustersMappers.ts
sdk/hdinsight/arm-hdinsight/src/models/index.ts
sdk/hdinsight/arm-hdinsight/src/models/locationsMappers.ts
sdk/hdinsight/arm-hdinsight/src/models/mappers.ts
sdk/hdinsight/arm-hdinsight/src/models/operationsMappers.ts
sdk/hdinsight/arm-hdinsight/src/operations/applications.ts
sdk/hdinsight/arm-hdinsight/src/operations/clusters.ts
sdk/hdinsight/arm-hdinsight/src/operations/extensions.ts
sdk/hdinsight/arm-hdinsight/src/operations/scriptActions.ts

for release issue: https://github.com/Azure/sdk-release-request/issues/1134

arm-hdinsight release

---

CONTRIBUTING.md

Adds a subsection about documentation to our contributing guide.

[Contributing guide] Adding a section about documentation

---

sdk/metricsadvisor/ai-metrics-advisor/README.md
sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/metricFeedback.js
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/quickstart.js
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/dataFeed.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/metricFeedback.ts
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/quickstart.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/adminclient.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/advisorclient.spec.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/datafeed.spec.ts

Following functions have been updated so far -

[Metrics Advisor] Create functions modified to return id with response instead of complete objects

---

eng/pipelines/templates/stages/archetype-js-release.yml

This PR updates the jobs in the release pipeline to use the 1ES pools.

1ES pools update for release pipeline

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/formrecognizer/ai-form-recognizer/review/ai-form-recognizer.api.md
sdk/formrecognizer/ai-form-recognizer/src/constants.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/generatedClientContext.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/index.ts
sdk/formrecognizer/ai-form-recognizer/src/generated/models/mappers.ts
sdk/formrecognizer/ai-form-recognizer/src/models.ts
sdk/formrecognizer/ai-form-recognizer/swagger/README.md

This PR includes the version bump and renames to `Appearance` and its related types for the impending release of 3.1.0-beta.2.
- Appearance -> TextAppearance
- Style -> TextStyle
- TextStyle -> StyleName

[ai-form-recognizer] 3.1-beta.2 Renames

---

sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/aad_metricsadvisorclient/recording_listanomalydimensionvalues.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/aad_metricsadvisorclient/recording_listanomalydimensionvalues_by_page.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/aad_metricsadvisorclient/recording_listanomalydimensionvalues_with_datetime_strings.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/api_key_metricsadvisorclient/recording_listanomalydimensionvalues.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/api_key_metricsadvisorclient/recording_listanomalydimensionvalues_by_page.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/browsers/api_key_metricsadvisorclient/recording_listanomalydimensionvalues_with_datetime_strings.json
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/aad_metricsadvisorclient/recording_listanomalydimensionvalues.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/aad_metricsadvisorclient/recording_listanomalydimensionvalues_by_page.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/aad_metricsadvisorclient/recording_listanomalydimensionvalues_with_datetime_strings.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/api_key_metricsadvisorclient/recording_listanomalydimensionvalues.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/api_key_metricsadvisorclient/recording_listanomalydimensionvalues_by_page.js
sdk/metricsadvisor/ai-metrics-advisor/recordings/node/api_key_metricsadvisorclient/recording_listanomalydimensionvalues_with_datetime_strings.js
sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/samples/javascript/incidentsAndAlerts.js
sdk/metricsadvisor/ai-metrics-advisor/samples/typescript/src/incidentsAndAlerts.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/advisorclient.spec.ts

- listDimensionValuesForDetectionConfig() => listAnomalyDimensionValues()
- Updated tests and recordings
- Added samples
- Updated missing param in ref doc

[metrics advisor] updated method name for listDimensionValuesForDetectionConfig()

---

eng/pipelines/prepare-pipelines.yml

Add APIView KV variable group to new pipelines

Add APIView variable group

---

sdk/communication/communication-administration/.vscode/launch.json
sdk/communication/communication-chat/.vscode/launch.json
sdk/communication/communication-identity/.vscode/launch.json
sdk/communication/communication-sms/.vscode/launch.json

Related to https://github.com/Azure/azure-sdk-for-js/pull/9940
Applying those fixes to communications sdk

Communications - VS Code debug fixes

---

sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/package.json
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json

Update version for storage blob/file 12.4.1 and datalake/queue 12.3.1 release

[Storage] Update version for storage blob/file 12.4.1 and datalake/queue 12.3.1 release

---

sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorKeyCredentialPolicy.ts
sdk/metricsadvisor/ai-metrics-advisor/test/public/keyRotation.spec.ts

- Update methods for both keys
- Get methods for both keys
- Updated Constructor and changed fields to private

[Metrics Advisor] Api Key rotation

---

sdk/core/core-http/CHANGELOG.md
sdk/core/core-https/CHANGELOG.md

Changelog update for ms-cv header added for `core-http` and `core-https`

[core-http] add changelog

---

sdk/identity/identity/README.md

Update Identity readme

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/package.json

To help address https://github.com/Azure/azure-sdk-for-js/issues/13531, update the keytar dependency to the latest version.

[Identity] Update the keytar dependency

---

sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/review/communication-common.api.md
sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/src/identifierModels.ts
sdk/communication/communication-common/test/identifierModelSerializer.spec.ts
sdk/communication/communication-common/test/identifierModels.spec.ts

Js equivalent of https://github.com/Azure/azure-sdk-for-net/pull/18389

[communication-common] Rewrote identifier serializer to match new schema

---

sdk/core/core-http/CHANGELOG.md

Update release date in CHANGELOG

[core-http] prepare for Feburary 2021 release

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-https/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md

[core-https][core-xml][core-client] Add release notes for February

---

sdk/eventgrid/eventgrid/tests.yml
sdk/eventgrid/test-resources.json

- Match the same `tests.yml` format as some existing track 2 packages
- Add a `test-resources.json` so the live pipeline deployes the resources
for the live tests.
Fixes #13588

[Event Grid] Fix Live Test Pipeline

---

sdk/core/core-amqp/CHANGELOG.md

Let's not do a release on a Friday...updating to Monday!

[core-amqp] update changelog for release

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/samples/javascript/README.md
sdk/keyvault/keyvault-admin/samples/typescript/README.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/samples/javascript/README.md
sdk/keyvault/keyvault-secrets/samples/typescript/README.md

Update CHANGELOG for release. Covers:
- @azure/keyvault-admin 
- @azure/keyvault-certificates
- @azure/keyvault-keys
- @azure/keyvault-secrets
Also did a documentation pass and noticed some broken `deploy to Azure` links so fixed those.

[KeyVault] - Update changelog for release

---

samples/cors/ts/README.md
sdk/cosmosdb/cosmos/README.md
sdk/template/template/README.md

- Update CORS doc to be more generic
- Add instructions to package authors on CORS section in template
- Add a CORS section to cosmos DB
Closes #13149

Update new template with CORS instructions

---

sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/amqpAnnotatedMessage.ts
sdk/core/core-amqp/src/auth/token.ts
sdk/core/core-amqp/src/cbs.ts
sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/log.ts
sdk/core/core-amqp/src/messageHeader.ts
sdk/core/core-amqp/src/messageProperties.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/retry.ts
sdk/core/core-amqp/src/util/runtimeInfo.browser.ts
sdk/core/core-amqp/src/util/utils.ts

This PR fixes most of the tsdoc linting errors bringing down the total linting errors from over 400 to 33
Related to #12947
Do not merge until the current update of 2.1.0 is released

[Core AMQP] Fix tsdoc linting errors

---

sdk/iotcentral/arm-iotcentral/package.json
sdk/iotcentral/arm-iotcentral/src/iotCentralClientContext.ts
sdk/iotcentral/arm-iotcentral/src/models/appsMappers.ts
sdk/iotcentral/arm-iotcentral/src/models/index.ts
sdk/iotcentral/arm-iotcentral/src/models/mappers.ts
sdk/iotcentral/arm-iotcentral/src/operations/apps.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1216

arm-iotcentral-relaese

---

sdk/communication/communication-sms/README.md
sdk/communication/communication-sms/samples/javascript/sendSms.js
sdk/communication/communication-sms/samples/typescript/src/sendSms.ts

This PR addresses #12918 and adds instructions on how to get a phone number before sending a sms.

[communication] update sms readme and samples

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md

I forgot to set the correct release date, so this PR does that.

[ai-form-recognizer] Added changelog release date

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/README.md

Updated the release date and fix a minor issue in README.

[Text Analytics] Prepare for release of v5.1.0-beta.4

---

sdk/tables/data-tables/CHANGELOG.md

Update release notes for Tables Feb release

[Tables] Update release notes for beta.5

---

sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/util/utils.ts
sdk/core/core-amqp/test/context.spec.ts
sdk/core/core-amqp/test/requestResponse.spec.ts

This PR brings down the number of linter errors in core-amqp from 33 to 18!
Related to #10775

[Core AMQP] Fix a few more linter errors

---

eng/common/docgeneration/Generate-DocIndex.ps1
sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md

- Update Changelog for Feb release

[Metrics Advisor] update changelog

---

sdk/search/search-documents/CHANGELOG.md

Modified change log for search documents

Modified change log for search documents

---

sdk/monitor/monitor-opentelemetry-exporter/samples/grpc/server.js
sdk/monitor/monitor-opentelemetry-exporter/samples/https/client.js
sdk/monitor/monitor-opentelemetry-exporter/samples/https/server.js

There were breaking changes in OpenTelemetry affecting samples code

Update OpenTelemetry exporter samples

---

eng/pipelines/templates/steps/analyze.yml

Add check to catch delinquent eng/common changes

Add check to catch delinquent eng/common changes

---

eng/pipelines/templates/steps/analyze.yml

Reverts Azure/azure-sdk-for-js#13506

Revert "Add check to catch delinquent eng/common changes"

---

sdk/eventhub/eventhubs-checkpointstore-blob/package.json
sdk/eventhub/eventhubs-checkpointstore-blob/src/blobCheckpointStore.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/index.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/log.ts
sdk/eventhub/eventhubs-checkpointstore-blob/src/util/error.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/blob-checkpointstore.spec.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/snippets.spec.ts
sdk/eventhub/eventhubs-checkpointstore-blob/test/utils/testUtils.ts

This PR fixes around 30 linter problems for the checkpoint store package bringing the total count to 14. Related to #12953 and #10777

[CheckpointStore] Fix linter errors

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/interactive-browser-credential.md

Identity 1.2.4-beta.1 release date 🎉

[Identity] 1.2.4-beta.1 release date

---

eng/pipelines/templates/jobs/archetype-sdk-client.yml
eng/pipelines/templates/jobs/archetype-sdk-integration.yml
eng/pipelines/templates/jobs/smoke-tests.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/steps/test.yml

This PR re-enables agent OS verification, and is dependent on this PR:
https://github.com/Azure/azure-sdk-tools/pull/1371

Re-enable agent OS verification

---

sdk/identity/identity/src/credentials/interactiveBrowserCredential.ts

This removes an old comment about node.js not being supported and the MSAL startup log message.

[Identity] Fix old comments and log message

---

sdk/servicebus/service-bus/src/core/messageSender.ts

This PR fixes the places where we are failing the [Promise executor functions should not be async](https://eslint.org/docs/rules/no-async-promise-executor) rule
Tip: Use the "hide whitespace changes" option when reviewing. This is mostly moving the code around

[Service Bus] Promise executor functions should not be async

---

eng/pipelines/templates/steps/analyze.yml

Add check to catch delinquent eng/common changes

Add eng-common-workflow-check

---

sdk/storage/storage-internal-avro/test/browser/avroreadable.spec.ts
sdk/storage/storage-internal-avro/test/node/avroreadable.spec.ts
sdk/storage/storage-internal-avro/test/node/avroreader.spec.ts

addresses #10782 , specifically it fixes eslint errors in the storage-internal-avro subfolder test files

fix eslint errors in storage-internal-avro pkg test files

---

sdk/communication/communication-administration/package.json
sdk/communication/communication-administration/src/phoneNumber/generated/src/operations/phoneNumberAdministration.ts
sdk/communication/communication-administration/src/phoneNumber/generated/src/phoneNumberRestClient.ts
sdk/communication/communication-administration/src/phoneNumber/generated/src/phoneNumberRestClientContext.ts
sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/src/constants.ts
sdk/communication/communication-chat/src/generated/src/chatApiClientContext.ts
sdk/communication/communication-chat/test/chatClient.spec.ts
sdk/communication/communication-chat/test/chatThreadClient.spec.ts
sdk/communication/communication-identity/package.json
sdk/communication/communication-identity/src/constants.ts
sdk/communication/communication-identity/src/generated/src/identityRestClient.ts
sdk/communication/communication-identity/src/generated/src/identityRestClientContext.ts
sdk/communication/communication-identity/src/generated/src/operations/communicationIdentity.ts
sdk/communication/communication-identity/swagger/README.md
sdk/communication/communication-sms/package.json
sdk/communication/communication-sms/src/constants.ts
sdk/communication/communication-sms/src/generated/src/operations/sms.ts
sdk/communication/communication-sms/src/generated/src/smsApiClient.ts
sdk/communication/communication-sms/src/generated/src/smsApiClientContext.ts

Follow up to #13719
Updating version numbers in constants, generated code and in dependencies to common.
There's noise in generated code where a previous manual linter fix got reverted. Lint doesn't complain about generated code.

[communication] Follow up to automatic version incrementer

---

sdk/monitor/monitor-opentelemetry-exporter/review/monitor-opentelemetry-exporter.api.md
sdk/monitor/monitor-opentelemetry-exporter/src/config.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts

https://github.com/Azure/azure-sdk/issues/1975#issuecomment-777872790

OpenTelemetry Exporter arch board feedback

---

eng/CredScanSuppression.json

This is the PR to suppress all existing issues reported by CredScan pipeline. 
Three types of suppressing:
1. Suppress the placeholder fake key.
2. Suppress the entire key file.
3. Suppress the generated key inside files. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=740263&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=73b5eb55-653d-5b46-19cb-2116006ac112

Added suppression rules for JS

---

sdk/communication/communication-administration/review/communication-administration.api.md
sdk/communication/communication-administration/src/common/models.ts
sdk/communication/communication-administration/src/phoneNumber/lro/purchase/operation.ts
sdk/communication/communication-administration/src/phoneNumber/lro/release/operation.ts
sdk/communication/communication-administration/src/phoneNumber/lro/reserve/operation.ts
sdk/communication/communication-administration/src/phoneNumber/phoneNumberAdministrationClient.ts
sdk/communication/communication-administration/test/lro.purchase.spec.ts
sdk/communication/communication-administration/test/lro.reserve.spec.ts
sdk/communication/communication-administration/test/utils/mockHttpClients.ts
sdk/communication/communication-administration/test/utils/recordedClient.ts

Git issue: https://github.com/Azure/azure-sdk-for-js/issues/13723

[Communication] - Administration - Fixing linter warnings

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/monitor-opentelemetry-exporter/package.json
sdk/monitor/monitor-opentelemetry-exporter/src/config.ts
sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/context/context.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/httpSender.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/connectionStringParser.ts
sdk/monitor/monitor-opentelemetry-exporter/src/utils/spanUtils.ts
sdk/monitor/monitor-opentelemetry-exporter/test/common/scenario/basic.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/utils/eventhub.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/utils/spanUtils.test.ts

https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.17.0

OpenTelemetry Exporter updating to latest dependencies

---

eng/pipelines/templates/steps/analyze.yml

Run `eng-common-workflow-enforcer.yml` at the end of the analyze stage.

Move eng/common workflow check to end of analyze stage

---

.github/CODEOWNERS

for existing and new libraries

Update Azure Core owners

---

sdk/monitor/monitor-opentelemetry-exporter/test/common/scenario/basic.ts

Context need to be passed as a parameter now during startSpan method

OpenTelemetry Exporter functional test fix

---

sdk/netapp/arm-netapp/LICENSE.txt
sdk/netapp/arm-netapp/package.json
sdk/netapp/arm-netapp/src/azureNetAppFilesManagementClientContext.ts
sdk/netapp/arm-netapp/src/models/accountBackupsMappers.ts
sdk/netapp/arm-netapp/src/models/accountsMappers.ts
sdk/netapp/arm-netapp/src/models/backupPoliciesMappers.ts
sdk/netapp/arm-netapp/src/models/backupsMappers.ts
sdk/netapp/arm-netapp/src/models/index.ts
sdk/netapp/arm-netapp/src/models/mappers.ts
sdk/netapp/arm-netapp/src/models/parameters.ts
sdk/netapp/arm-netapp/src/models/poolsMappers.ts
sdk/netapp/arm-netapp/src/models/snapshotPoliciesMappers.ts
sdk/netapp/arm-netapp/src/models/snapshotsMappers.ts
sdk/netapp/arm-netapp/src/models/vaultsMappers.ts
sdk/netapp/arm-netapp/src/models/volumesMappers.ts
sdk/netapp/arm-netapp/src/operations/accounts.ts
sdk/netapp/arm-netapp/src/operations/backupPolicies.ts
sdk/netapp/arm-netapp/src/operations/backups.ts
sdk/netapp/arm-netapp/src/operations/pools.ts
sdk/netapp/arm-netapp/src/operations/snapshotPolicies.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1268

arm-netapp-release

---

sdk/communication/communication-common/review/communication-common.api.md
sdk/communication/communication-common/src/credential/clientArguments.ts
sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/test/identifierModelSerializer.spec.ts
sdk/communication/communication-common/tsconfig.json

git issue: https://github.com/Azure/azure-sdk-for-js/issues/13723

[Communication] - Linter - Fixing some linter warnings in the common package

---

sdk/core/abort-controller/CHANGELOG.md

[abort-controller] Update release date

---

sdk/communication/communication-sms/test/smsClient.spec.ts
sdk/communication/communication-sms/test/utils/recordedClient.ts
sdk/communication/communication-sms/tsconfig.json

Git issue: https://github.com/Azure/azure-sdk-for-js/issues/13723

[Communication] - Linter - Fixing some linter warnings in sms package

---

sdk/core/core-https/review/core-https.api.md
sdk/core/core-https/src/defaultHttpsClient.browser.ts
sdk/core/core-https/src/defaultHttpsClient.ts
sdk/core/core-https/src/index.ts
sdk/core/core-https/src/nodeHttpsClient.ts
sdk/core/core-https/src/policies/exponentialRetryPolicy.ts
sdk/core/core-https/src/xhrHttpsClient.ts

- Fix typo in exponentialRetryPolicyName constant.
- Make sure concrete HttpsClient types stay hidden.

[core-https] Fix review comments from #13716

---

common/tools/add-identity-mgmt-lib.js

Fixes the script to be truly package-agnostic.

Fix add-identity-mgmt-lib

---

sdk/appplatform/arm-appplatform/LICENSE.txt
sdk/appplatform/arm-appplatform/package.json
sdk/appplatform/arm-appplatform/src/appPlatformManagementClientContext.ts
sdk/appplatform/arm-appplatform/src/models/index.ts
sdk/appplatform/arm-appplatform/src/models/mappers.ts

released for issue: https://github.com/Azure/sdk-release-request/issues/1298

arm-appplatform-release

---

common/config/rush/pnpm-lock.yaml

This PR contains changes to the lock file from running `rush update --full`.
We should be doing this once a month at the very least

rush update --full

---

sdk/eventgrid/eventgrid/README.md

Fixes minor typos in both prose and some of the example code (I
validated that the checked in samples were still correct, we just had
no coverage for the code in the README.md)
Fixes #13995

[EventGrid] Fix README.md issues

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/test/internal/session.spec.ts
sdk/cosmosdb/cosmos/test/internal/unit/inMemoryCollectionRoutingMap.spec.ts
sdk/cosmosdb/cosmos/test/internal/unit/platform.spec.ts
sdk/cosmosdb/cosmos/test/internal/unit/smartRoutingMapProvider.spec.ts
sdk/cosmosdb/cosmos/test/public/common/MockClientContext.ts
sdk/cosmosdb/cosmos/test/public/common/MockQueryIterator.ts
sdk/cosmosdb/cosmos/test/public/common/TestData.ts
sdk/cosmosdb/cosmos/test/public/common/TestHelpers.ts
sdk/cosmosdb/cosmos/test/public/common/setup.ts
sdk/cosmosdb/cosmos/test/public/functional/authorization.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/container.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/database.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/globalEndpointManager.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/offer.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/permission.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/plugin.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/spatial.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/sproc.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/ttl.spec.ts
sdk/cosmosdb/cosmos/test/public/functional/user.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/aggregateQuery.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/crossPartition.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/encoding.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/failover.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/multiregion.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/proxy.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/queryMetrics.spec.ts
sdk/cosmosdb/cosmos/test/public/integration/split.spec.ts

Fixes linting issues in cosmos tests.

[Cosmos] Fix linting issues in tests

---

sdk/anomalydetector/ai-anomaly-detector/README.md
sdk/attestation/attestation/README.md
sdk/core/core-amqp/README.md
sdk/core/core-lro/README.md
sdk/digitaltwins/digital-twins-core/README.md
sdk/eventgrid/eventgrid/README.md
sdk/eventhub/event-hubs/README.md
sdk/eventhub/eventhubs-checkpointstore-blob/README.md
sdk/formrecognizer/ai-form-recognizer/README.md
sdk/metricsadvisor/ai-metrics-advisor/README.md
sdk/mixedreality/mixedreality-authentication/README.md
sdk/search/search-documents/README.md
sdk/servicebus/service-bus/README.md
sdk/template/template/README.md
sdk/textanalytics/ai-text-analytics/README.md

We might have introduced the inconsistency for some libraries while copying
content from other languages.

[template] Make README Logging section consistent

---

sdk/storage/storage-file-datalake/README.md

To fix issue https://github.com/Azure/azure-sdk-for-js/issues/13998

Update Storage File Data Lake Readme

---

sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeHealthcareEntities.js
sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeHealthcareEntities.ts
sdk/textanalytics/ai-text-analytics/src/analyzeHealthcareEntitiesResult.ts

Fix a tiny issue in samples and add the `@internal` tag on a newly added internal function.

[Text Analytics] Tiny edits

---

sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorAdministrationClient.ts
sdk/metricsadvisor/ai-metrics-advisor/src/metricsAdvisorClient.ts

Use internal tag for private methods and fields

---

sdk/metricsadvisor/ai-metrics-advisor/README.md

To fix issue https://github.com/Azure/azure-sdk-for-js/issues/13996

Update Metrics Advisor Readme

---

sdk/communication/communication-chat/src/credential/communicationTokenCredentialPolicy.ts
sdk/communication/communication-chat/src/signaling/signalingClient.browser.ts
sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/review/communication-common.api.md
sdk/communication/communication-common/src/autoRefreshTokenCredential.ts
sdk/communication/communication-common/src/communicationTokenCredential.ts
sdk/communication/communication-common/src/credential/clientArguments.ts
sdk/communication/communication-common/src/credential/communicationAccessKeyCredentialPolicy.ts
sdk/communication/communication-common/src/credential/communicationAuthPolicy.ts
sdk/communication/communication-common/src/credential/connectionString.ts
sdk/communication/communication-common/src/identifierModelSerializer.ts
sdk/communication/communication-common/src/index.ts
sdk/communication/communication-common/test/communicationTokenCredential.spec.ts
sdk/communication/communication-common/test/identifierModelSerializer.spec.ts
sdk/communication/communication-common/tsdoc.json
sdk/communication/communication-identity/README.md
sdk/communication/communication-identity/review/communication-identity.api.md
sdk/communication/communication-identity/src/communicationIdentityClient.ts

Applying APIView feedback.
Addresses #13448 (communication-administration with remaining @internal will be deleted soon)

[communication-common] Add options bag for getToken function, mark @hidden where applicable

---

sdk/storage/storage-blob/package.json
sdk/test-utils/perfstress/README.md
sdk/test-utils/perfstress/package.json
sdk/test-utils/perfstress/runAllTests.sh

- Also delete obsolete command in storage-blob

[Perf] Rename perfstress-test to perf-test

---

sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/test/utils/recordedClient.ts
sdk/communication/communication-identity/CHANGELOG.md
sdk/communication/communication-identity/README.md
sdk/communication/communication-identity/review/communication-identity.api.md
sdk/communication/communication-identity/src/communicationIdentityClient.ts
sdk/communication/communication-identity/test/communicationIdentityClient.spec.ts
sdk/communication/communication-identity/test/utils/mockHttpClients.ts
sdk/communication/communication-identity/test/utils/testCommunicationIdentityClient.ts

[communication-identity] Rename createUserWithToken to createUserAndToken

---

sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts

By adding a line to the `analyzeSentiment` docstring about OM. Fixes https://github.com/Azure/azure-sdk-for-js/issues/11970 after I talked to @maririos that this should be enough for now.

[Text Analytics] Increase discoverability for OM

---

sdk/core/abort-controller/CHANGELOG.md

[abort-controller] prepare for 1.0.4 release

---

sdk/metricsadvisor/ai-metrics-advisor/review/ai-metrics-advisor.api.md
sdk/metricsadvisor/ai-metrics-advisor/src/generated/generatedClientContext.ts
sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/index.ts
sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/mappers.ts
sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/parameters.ts
sdk/metricsadvisor/ai-metrics-advisor/src/models.ts
sdk/metricsadvisor/ai-metrics-advisor/src/transforms.ts
sdk/metricsadvisor/ai-metrics-advisor/swagger/README.md

- undo changes related to extensible enums
- fixes https://github.com/Azure/azure-sdk-for-js/issues/13917

Fix enums that were gone after moving to V6 SDK code generator

---

sdk/deviceupdate/ci.yml
sdk/deviceupdate/iot-device-update/package.json

Enable Release for the package

[Device Update] Enable Release

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/package.json
sdk/tables/data-tables/src/utils/constants.ts

- Generated from the prepare-release script
- If you want to open a manual PR for your package, let me know - will close this

update version for @azure/data-tables

---

sdk/cosmosdb/cosmos/src/client/Item/Items.ts

Fixing the small typo in issue 14163.

---

sdk/textanalytics/ai-text-analytics/samples/javascript/beginAnalyzeHealthcareEntities.js
sdk/textanalytics/ai-text-analytics/samples/typescript/src/beginAnalyzeHealthcareEntities.ts
sdk/textanalytics/ai-text-analytics/src/lro/health/operation.ts
sdk/textanalytics/ai-text-analytics/test/public/apiKey.spec.ts

Patching the poller for healthcare in the same way done for the analyze here https://github.com/Azure/azure-sdk-for-js/pull/14143.

[Text Analytics] Fix the poller for healthcare

---

sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

Setting the release date in CHANGELOG in preparation for tomorrow's release

[KeyVault] - Update changelog dates for KeyVault Keys and Secrets

---

sdk/eventhub/event-hubs/CHANGELOG.md

[event-hubs] prepare for 5.5.0-beta.1 release

---

sdk/storagecache/arm-storagecache/package.json
sdk/storagecache/arm-storagecache/src/models/ascOperationsMappers.ts
sdk/storagecache/arm-storagecache/src/models/cachesMappers.ts
sdk/storagecache/arm-storagecache/src/models/index.ts
sdk/storagecache/arm-storagecache/src/models/mappers.ts
sdk/storagecache/arm-storagecache/src/models/operationsMappers.ts
sdk/storagecache/arm-storagecache/src/models/skusMappers.ts
sdk/storagecache/arm-storagecache/src/models/storageTargetsMappers.ts
sdk/storagecache/arm-storagecache/src/models/usageModelsMappers.ts
sdk/storagecache/arm-storagecache/src/operations/storageTargets.ts
sdk/storagecache/arm-storagecache/src/storageCacheManagementClientContext.ts

release for issue : https://github.com/Azure/sdk-release-request/issues/1347

arm-storagecache-release

---

sdk/operationalinsights/arm-operationalinsights/LICENSE.txt
sdk/operationalinsights/arm-operationalinsights/package.json
sdk/operationalinsights/arm-operationalinsights/src/models/index.ts
sdk/operationalinsights/arm-operationalinsights/src/models/mappers.ts
sdk/operationalinsights/arm-operationalinsights/src/operationalInsightsManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1149

arm-operationalinsights-release

---

.github/CODEOWNERS

Also added an update for Key Vault.

Update on the owners of Identity

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

Now that [core v2](https://www.npmjs.com/package/@azure/core-rest-pipeline/v/1.0.0-beta.2) has been released, we can release! This PR updates date in changelog.

[Text Analytics] Prepare for 5.1.0-beta.5 release

---

sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_can_send_a_sms_message.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_can_send_a_sms_message_to_multiple_recipients.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_can_send_a_sms_message_with_options_passed_in.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_sends_a_new_message_each_time_send_is_called.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_an_invalid_number.json
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_a_sms_message.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_a_sms_message_to_multiple_recipients.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_a_sms_message_with_options_passed_in.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_sends_a_new_message_each_time_send_is_called.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_an_invalid_number.js
sdk/communication/communication-sms/recordings/node/smsclientwithtoken_playbacklive/recording_can_send_a_sms_when_url_and_token_credential_are_provided.js
sdk/communication/communication-sms/test/smsClient.mocked.spec.ts
sdk/communication/communication-sms/test/smsClient.spec.ts
sdk/communication/communication-sms/test/utils/recordedClient.ts

Toll free numbers don't reserve the 555 prefix, and even then it's only reserved from 555-0100 to 555-0199
Changed our fake numbers so that we don't accidentally point to harmful content

[Communication] Replace fake phone numbers with faker number

---

sdk/core/core-client/src/serializationPolicy.ts
sdk/core/core-client/src/serviceClient.ts
sdk/core/core-client/test/serializationPolicy.spec.ts
sdk/core/core-http/src/serviceClient.ts

so that they can properly override existing headers.

[core-client] set custom headers after serializing headers

---

sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-keys/samples/javascript/purgeAllKeys.js

To fix issue https://github.com/Azure/azure-sdk-for-js/issues/14001

Update Key Vault Keys Readme And Sample

---

eng/tools/versioning/set-dev.js

Semver parsing  is failing when dependency requirement is "dev" and this is causing set dev version process to fail for few packages. Fix is to skip Semver parsing when version requirement is "dev"

Setting dev version is failing for Keyvault packages

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md

Update release dates and entries in CHANGELOG

[core v2] prepare for GA release

---

sdk/communication/communication-sms/README.md
sdk/communication/communication-sms/samples/javascript/README.md
sdk/communication/communication-sms/samples/typescript/README.md

Added a link to the SMS Event Handling quickstart to showcase how to view delivery reports

[communication] link to sms event quickstart

---

.github/CODEOWNERS

I am happy about this. Thank you @ramya-rao-a for the opportunity 🙏

Adding myself on the code-owners of core-auth

---

sdk/core/core-amqp/src/errors.ts
sdk/eventhub/event-hubs/test/internal/node/packageInfo.spec.ts
sdk/eventhub/event-hubs/test/public/utils/receivedMessagesTester.ts
sdk/servicebus/service-bus/rollup.base.config.js
sdk/servicebus/service-bus/test/internal/smoketest.spec.ts
sdk/servicebus/service-bus/test/stress/scenarioLongRunning.ts
sdk/servicebus/service-bus/test/stress/scenarioPeekMessages.ts
sdk/servicebus/service-bus/test/stress/stressTestsBase.ts
sdk/servicebus/service-bus/test/stress/utils.ts
sdk/servicebus/service-bus/tsconfig.json

This PR has changes from running `rushx format` on the below 3 packages
- `@azure/service-bus`
- `@azure/event-hubs`
- `@azure/core-amqp`
This is a follow up for #13983

Run format for SB, EH and Core AMQP

---

sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
sdk/eventgrid/eventgrid/src/cloudEventDistrubtedTracingEnricherPolicy.ts
sdk/eventgrid/eventgrid/src/eventGridAuthenticationPolicy.ts
sdk/eventgrid/eventgrid/test/cloudEventDistributedTracingEnricherPolicy.spec.ts
sdk/keyvault/keyvault-secrets/test/internal/challengeBasedAuthenticationPolicy.spec.ts
sdk/tables/data-tables/src/TablesSharedKeyCredentialPolicy.ts

This PR has changes from running `rushx format` on the below packages. Since the changes were tiny, decided to create 1 single PR :)
- App Config
- Event Grid
- Key Vault
- Tables
This is a follow up for #13983

[AppConfig, EventGrid, KeyVault, Tables] Run format

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/review/communication-chat.api.md
sdk/communication/communication-chat/src/chatClient.ts
sdk/communication/communication-chat/src/chatThreadClient.ts
sdk/communication/communication-chat/src/models/mappers.ts
sdk/communication/communication-chat/src/models/options.ts
sdk/communication/communication-chat/src/models/requests.ts
sdk/communication/communication-chat/src/signaling/signalingClient.browser.ts
sdk/communication/communication-chat/test/chatClient.spec.ts
sdk/communication/communication-chat/test/chatThreadClient.spec.ts

1. Update signaling package
2. Move participants to options
3. Fixes some small comments from this PR [Communication Chat Preview 5](https://github.com/Azure/azure-sdk-for-js/pull/14222)

[Communication] Update Signaling Package to 1.0.0-beta.3

---

sdk/storage/arm-storage/package.json
sdk/storage/arm-storage/src/models/blobContainersMappers.ts
sdk/storage/arm-storage/src/models/blobInventoryPoliciesMappers.ts
sdk/storage/arm-storage/src/models/blobServicesMappers.ts
sdk/storage/arm-storage/src/models/deletedAccountsMappers.ts
sdk/storage/arm-storage/src/models/encryptionScopesMappers.ts
sdk/storage/arm-storage/src/models/fileServicesMappers.ts
sdk/storage/arm-storage/src/models/fileSharesMappers.ts
sdk/storage/arm-storage/src/models/index.ts
sdk/storage/arm-storage/src/models/managementPoliciesMappers.ts
sdk/storage/arm-storage/src/models/mappers.ts
sdk/storage/arm-storage/src/models/objectReplicationPoliciesOperationsMappers.ts
sdk/storage/arm-storage/src/models/privateEndpointConnectionsMappers.ts
sdk/storage/arm-storage/src/models/privateLinkResourcesMappers.ts
sdk/storage/arm-storage/src/models/queueMappers.ts
sdk/storage/arm-storage/src/models/queueServicesMappers.ts
sdk/storage/arm-storage/src/models/storageAccountsMappers.ts
sdk/storage/arm-storage/src/models/tableOperationsMappers.ts
sdk/storage/arm-storage/src/models/tableServicesMappers.ts
sdk/storage/arm-storage/src/storageManagementClientContext.ts

release for issue : https://github.com/Azure/sdk-release-request/issues/1295

arm-storage-release

---

sdk/core/core-rest-pipeline/CHANGELOG.md

Prepping for hotfix release to deliver #14359. I'm open to doing this on Monday if folks think this is too late in the day to ship now.

[core-rest-pipeline] Release 1.0.1 hotfix

---

sdk/graphrbac/graph/README.md
sdk/graphrbac/graph/package.json
sdk/graphrbac/graph/src/graphRbacManagementClientContext.ts

This PR adds the appropriate notice in the readme for the graph package to convey the deprecation of the AAD Graph APIs and next steps
Resolves #13626

[Graph] Add service deprecation notice

---

common/tools/eslint-plugin-azure-sdk/ci.yml
eng/pipelines/eslint-plugin-regression.yml
eng/pipelines/templates/steps/analyze.yml
eng/pipelines/templates/steps/run-eslint.yml

Add new pipeline to verify ES lint regression

Move ESlint step to template and add new pipeline to verify all packages

---

eng/tools/publish-to-npm.ps1

Add a new parameter to support skipping diff check to allow force pushing a dev version package.

Add option to skip diff check for dev version package

---

sdk/containerregistry/container-registry/package.json
sdk/containerregistry/container-registry/samples/javascript/containerRegistryClient.js

[ContainerRegistry] Skip smoke tests

---

sdk/keyvault/keyvault-admin/README.md
sdk/keyvault/keyvault-admin/samples/javascript/accessControlHelloWorld.js
sdk/keyvault/keyvault-admin/samples/javascript/backupRestoreHelloWorld.js
sdk/keyvault/keyvault-admin/samples/javascript/backupSelectiveRestore.js
sdk/keyvault/keyvault-admin/samples/typescript/package.json
sdk/keyvault/keyvault-admin/samples/typescript/src/accessControlHelloWorld.ts
sdk/keyvault/keyvault-admin/samples/typescript/src/backupRestoreHelloWorld.ts
sdk/keyvault/keyvault-admin/samples/typescript/src/backupSelectiveRestore.ts
sdk/keyvault/keyvault-keys/README.md

Taking a pass at README and samples, and comparing them against dotnet, there were a few things
we need to address before we GA in May. I'll do another pass closer to GA but during this pass:
- Add information about Managed HSM in README
- Add instructions on how to activate a managed HSM
- Update all the links and add links where necessary
Resolves #10948 #11182

[KeyVault] - README and samples review

---

eng/scripts/Language-Settings.ps1

Cleanup eng\scripts\Language-Settings.ps1

---

sdk/communication/communication-administration/package.json
sdk/communication/communication-chat/package.json
sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-common/package.json
sdk/communication/communication-identity/package.json
sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-sms/package.json

* Update the package version to GA (1.0.0)
* Update the changelog

[Communication] Update Common Version for GA release

---

sdk/containerservice/arm-containerservice/package.json
sdk/containerservice/arm-containerservice/src/containerServiceClientContext.ts
sdk/containerservice/arm-containerservice/src/models/index.ts
sdk/containerservice/arm-containerservice/src/models/mappers.ts

release for issue : https://github.com/Azure/sdk-release-request/issues/1322

arm-containerservice-release

---

sdk/communication/communication-administration/src/phoneNumber/shims.d.ts
sdk/communication/communication-administration/src/phoneNumber/utils.browser.ts
sdk/communication/communication-chat/src/models/mappers.ts
sdk/communication/communication-sms/src/utils/smsUtils.ts
sdk/communication/communication-sms/test/smsClient.spec.ts

Related to https://github.com/Azure/azure-sdk-for-js/issues/13723
This PR has changes from running the `lint:fix` script on all the communication packages

[Communication] Run lint:fix

---

sdk/search/search-documents/test/public/node/searchIndexerClient.spec.ts
sdk/search/search-documents/test/public/utils/setup.ts

Remove Test case that uses existing production endpoint.

Removed Testcases with refs to existing endpoint

---

sdk/servicebus/service-bus/karma.conf.js
sdk/servicebus/service-bus/package.json

**Issue https://github.com/Azure/azure-sdk-for-js/issues/14437**

[Service Bus] Update browser test files in karma conf

---

sdk/identity/identity/CHANGELOG.md

This PR updates the Identity changelog with the below in mind
- Group changes that apply to specific credentials
- Move important changes up
- Move "non features" to "other changes"
- General re-structuring of text

Restructuring the changelog

---

sdk/servicebus/service-bus/package.json

Addresses https://github.com/Azure/azure-sdk-for-js/pull/14438#discussion_r599881099

[Service Bus] Clean command - Consolidate to "dist*"

---

sdk/communication/communication-chat/test/chatClient.spec.ts

Remove the line that is stopping notifications during notification tests :) Also remove uneccessary await

Remove stop notifications in chat live test

---

sdk/identity/identity/CHANGELOG.md

Thanks to @ramya-rao-a for catching this!

[Identity] AuthenticationRequired mentioned in the CHANGELOG

---

eng/pipelines/templates/stages/platform-matrix.json

Resolves https://github.com/Azure/azure-sdk-for-js/issues/14274

Add node 15 to live test matrix

---

.github/CODEOWNERS

Updating code owner for Digital Twins based on @anthonyvercolano' suggestion

Adding Vishnu as code owner for Digital Twins

---

sdk/communication/communication-sms/package.json
sdk/communication/communication-sms/test/smsClient.spec.ts
sdk/communication/communication-sms/test/smsClientWithToken.spec.ts

This PR fixes the remaining linter errors in the communication-sms package and allows future errors to break the build to enable us to catch them in time
Related to #13723

[Communication] Make sms pkg lint err free

---

sdk/appconfiguration/app-configuration/test/internal/http.spec.ts
sdk/appconfiguration/app-configuration/test/internal/package.spec.ts
sdk/appconfiguration/app-configuration/test/public/auth.spec.ts
sdk/appconfiguration/app-configuration/test/public/etags.spec.ts
sdk/appconfiguration/app-configuration/test/public/index.readonlytests.spec.ts
sdk/appconfiguration/app-configuration/test/public/index.spec.ts
sdk/appconfiguration/app-configuration/test/public/throwOrNotThrow.spec.ts

Fix no-invalid-this linter errors in the app config package
Related to #10774

[App Config] Fix no-invalid-this linter errors

---

CONTRIBUTING.md
common/tools/dev-tool/package.json
common/tools/dev-tool/src/commands/samples/tsToJs.ts

And remove the dependency on the eslint plugin.

[Dev-tool] Use prettier configs from path

---

eng/tools/versioning/VersionUtils.js

- Pass down changelogPath to Update-Changelog Script
- Should resolve https://github.com/Azure/azure-sdk-for-js/issues/11589

Prep for adding changelogpath to update changelog call

---

sdk/communication/communication-chat/samples/javascript/messageOperations.js
sdk/communication/communication-chat/samples/javascript/participantsOperations.js
sdk/communication/communication-chat/samples/javascript/threadOperations.js

Failed run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=810851&view=logs&j=9d5db22d-3d98-5076-6ada-6891876c8311&t=f34c9ad1-d8b4-531c-bef0-543e511e1962
Run against this branch passed:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=811166&view=logs&j=f3570516-c8fe-5ce9-92b2-b737df25d5ea

[communication-chat] Fix smoke tests issue with using export in JS samples

---

sdk/servicebus/service-bus/CHANGELOG.md

Updated Changelog for 7.0.4, prepping for release

[Service Bus] Changelog for 7.0.4

---

sdk/cosmosdb/arm-cosmosdb/package.json
sdk/cosmosdb/arm-cosmosdb/src/cosmosDBManagementClientContext.ts
sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1407

arm-cosmosdb-release

---

sdk/resourcegraph/arm-resourcegraph/package.json
sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts
sdk/resourcegraph/arm-resourcegraph/src/resourceGraphClient.ts
sdk/resourcegraph/arm-resourcegraph/src/resourceGraphClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1413

arm-resourcegraph-release

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-secrets/CHANGELOG.md

In preparation for next week's release, update the release dates and put the previous versions
in the correct sorted order.

[KeyVault] - Update release date for all packages

---

sdk/search/search-documents/src/searchClient.ts
sdk/search/search-documents/src/searchIndexClient.ts
sdk/search/search-documents/src/searchIndexerClient.ts

@xirzec This PR is to update the version in the search-documents SDK.
Please review and approve it.

Update Version value in Search SDK

---

sdk/digitaltwins/digital-twins-core/.nycrc.json

[Digital Twins Core] add nycrc to enable code coverage in live test pipeline

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/monitor/monitor-opentelemetry-exporter/package.json

Updating to latest releases
https://github.com/open-telemetry/opentelemetry-js/releases

 Updating OpenTelemetry dependencies for Azure Monitor Exporter

---

sdk/textanalytics/ai-text-analytics/README.md

Fixes minor issues in the readme file for text analytics and increases consistency.

[Text Analytics] Improve README.md

---

sdk/keyvault/keyvault-admin/CHANGELOG.md
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-admin/src/constants.ts
sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts

Increment package version after release of azure-keyvault-admin

Increment package version after release of azure-keyvault-admin

---

sdk/containerregistry/container-registry/README.md

- enable NPM package link
- hide SDK API docs link as they are not yet available
- add comments on endpoint format
- remove byPage() from example
- Remove sentence from template

[ContainerRegistry] Fix README

---

sdk/metricsadvisor/perf-tests/ai-metrics-advisor/package.json

- Fixing the dependencies and dev-dependencies for perf-tests for metrics advisor

[Metrics- advisor] Fix dependencies and dev-dependencies for perf tests

---

sdk/digitaltwins/digital-twins-core/package.json
sdk/digitaltwins/digital-twins-core/review/digital-twins-core.api.md
sdk/digitaltwins/digital-twins-core/src/digitalTwinsClient.ts
sdk/digitaltwins/digital-twins-core/test/public/testComponents.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testDigitalTwins.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testEventRoutes.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testModels.spec.ts
sdk/digitaltwins/digital-twins-core/test/public/testRelationships.spec.ts

[Digital Twins Core] address linter errors

---

sdk/communication/communication-chat/README.md

Fix Readme issue:
https://github.com/Azure/azure-sdk-for-js/issues/14572

[Communication]Fix chat readme

---

sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_can_send_an_sms_message_to_multiple_recipients.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.json
sdk/communication/communication-sms/recordings/browsers/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_an_invalid_number.json
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_an_sms_message.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_an_sms_message_to_multiple_recipients.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_can_send_an_sms_message_with_options_passed_in.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_sends_a_new_message_each_time_send_is_called.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.js
sdk/communication/communication-sms/recordings/node/smsclient_playbacklive/recording_throws_an_exception_when_sending_from_an_invalid_number.js
sdk/communication/communication-sms/recordings/node/smsclientwithtoken_playbacklive/recording_can_send_an_sms_when_url_and_token_credential_are_provided.js
sdk/communication/communication-sms/test/smsClient.spec.ts

Update test we now get 401 instead of 404 for attempting to call with numbers not owned by a resource

[communication] change test expected error code

---

sdk/attestation/attestation/LICENSE
sdk/attestation/attestation/test/utils/helpers.ts

- renames the license file to drop the txt extension and updates the year
- fix comment typo
Fixes https://github.com/Azure/azure-sdk-for-js/issues/13136

[Attestation] Address feedback

---

eng/pipelines/templates/stages/archetype-js-release.yml

Enable retain runs after tagging.

Retain runs that release.

---

eng/pipelines/templates/stages/archetype-js-release.yml

Quick fix to retain-runs path.

---

eng/pipelines/templates/stages/archetype-js-release.yml

Revise the condition for the integration stage to just rely on SetDevVersion.

Revise stage condition.

---

sdk/network/arm-network/package.json
sdk/network/arm-network/src/models/index.ts
sdk/network/arm-network/src/models/mappers.ts
sdk/network/arm-network/src/networkManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1417

arm-network-release

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/samples/MultiRegionWrite/ConflictWorker.ts
sdk/cosmosdb/cosmos/samples/MultiRegionWrite/MultiRegionWriteScenario.ts
sdk/cosmosdb/cosmos/samples/MultiRegionWrite/logger.ts
sdk/cosmosdb/cosmos/samples/MultiRegionWrite/package.json
sdk/cosmosdb/cosmos/src/client/Conflict/Conflict.ts
sdk/cosmosdb/cosmos/src/client/Container/Container.ts

Also makes some changes to make the MultiRegionWriterWorker more consistently successful
Unfortunately adding a test proves quite difficult as we need to reliably force a conflict without potential for a loop in CI

[Cosmos] Adds partition Key parameter to conflict delete

---

sdk/core/core-http/src/util/constants.ts
sdk/identity/identity/recordings/node/devicecodecredential/recording_allows_setting_disableautomaticauthentication.js
sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_and_allows_the_customization_of_the_prompt_callback.js
sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_with_default_values.js
sdk/identity/identity/recordings/node/devicecodecredential/recording_authenticates_with_provided_values.js
sdk/identity/identity/recordings/node/devicecodecredential/recording_supports_tracing.js
sdk/identity/identity/recordings/node/devicecodecredential_internal/recording_authenticates_silently_after_the_initial_request.js
sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_accepts_tokencachepersistenceoptions.js
sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_allows_passing_an_authenticationrecord_to_avoid_further_manual_authentications.js
sdk/identity/identity/recordings/node/devicecodecredential_internal_persistent_tests/recording_authenticates_silently_with_tokencachepersistenceoptions.js
sdk/identity/identity/test/msalTestUtils.ts

Somehow the playback is failing too often in the CI for this test.
This didn't fail on the local.
@sadasant and I suspect that the issue is caused because of the small interval.
Attempting to increase the interval and see if that fixes things for core-ci.

[Identity] Increase the interval from 0.1 to 1 seconds for playback

---

eng/pipelines/templates/steps/analyze.yml

This reverts commit b301b9c8403315561f7b2f9efffd87001c09cf53
and fixes #14893.

Re-enable verify-samples template

---

sdk/core/core-http/docs/architectureOverview.md
sdk/core/core-http/samples/gotHttpClient.ts
sdk/core/core-http/tsconfig.json

for demo purpose. It uses `got` npm package to send request.
Fixes #6485

[core-http] Add a custom HttpClient sample

---

.github/CODEOWNERS

CODEOWNERS tests.yml:  @danieljurek -> @benbp

---

eng/tools/analyze-deps/package-lock.json
eng/tools/analyze-deps/package.json

to address CVE-2021-23369
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23369

[eng tools] upgrade handlebars version to 4.7.7

---

sdk/keyvault/keyvault-admin/README.md

This PR updates our README to add the necessary information about role assignments and the recommendations. 
Since being an administrator is not sufficient to perform key operations it's worth mentioning that other roles are needed
to support key operations.
This PR is basically a port of https://github.com/Azure/azure-sdk-for-net/pull/20359 since the steps are the same.
Resolves #14866

[KeyVault] - Update README with role assignment recommendations

---

sdk/communication/communication-sms/test/public/smsClient.mocked.spec.ts
sdk/communication/communication-sms/test/public/utils/recordedClient.ts

min/max testing currently has a bug and we need this workaround otherwise min tests will fail

[communication] add workaround for SMS min testing

---

sdk/monitor/monitor-opentelemetry-exporter/src/export/trace.ts
sdk/monitor/monitor-opentelemetry-exporter/src/platform/nodejs/persist/fileSystemPersist.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/export/trace.test.ts
sdk/monitor/monitor-opentelemetry-exporter/test/unit/platform/nodejs/persist/fileSystemPersist.test.ts

Only retry valid codes when 206 response is returned from Breeze

Adding cleanup process for older temp files

---

sdk/anomalydetector/ai-anomaly-detector/samples/v3/javascript/sample_multivariate_detection.js

Add a sample for multivariate anomaly detection.

Add multivariate sample

---

eng/pipelines/templates/jobs/smoke.tests.yml

Add Node 16 to smoke test matrix

---

sdk/core-rest/core-client/CHANGELOG.md
sdk/documenttranslator/ai-document-translator-rest/CHANGELOG.md

Update changelog dates for release

[DocumentTranslator] Update changelog dates

---

eng/pipelines/templates/variables/globals.yml

- Pipelines
- js - core - ci
- master: https://dev.azure.com/azure-sdk/public/_build/results?buildId=857103&view=results
- PR: https://dev.azure.com/azure-sdk/public/_build/results?buildId=857105&view=results
- Verified all packages are bitwise-identical
- js - storage - ci
- master: https://dev.azure.com/azure-sdk/public/_build/results?buildId=857110&view=results
- PR: https://dev.azure.com/azure-sdk/public/_build/results?buildId=857111&view=results
- Verified all packages are bitwise-identical
- js - storage-blob - tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=857116
- js - keyvault-secrets - tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=857118
- js - smoke-tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=857121&view …

Upgrade default NodeVersion from 12 to 14

---

sdk/identity/identity/src/credentials/managedIdentityCredential/appServiceMsi2017.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/arcMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/cloudShellMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/fabricMsi.ts
sdk/identity/identity/src/credentials/managedIdentityCredential/imdsMsi.ts

This PR improves the logging of the ManagedIdentityCredential after feedback from @maorleger ✨

[Identity] Improving logging in the ManagedIdentityCredential

---

sdk/communication/communication-identity/karma.conf.js
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_creates_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_creates_a_user_and_gets_a_token_in_a_single_request.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_creates_a_user_and_token.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_deletes_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_gets_a_token_for_a_user_multiple_scopes.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_gets_a_token_for_a_user_single_scope.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive/recording_successfully_revokes_tokens_issued_for_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_creates_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_creates_a_user_and_gets_a_token_in_a_single_request.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_creates_a_user_and_token.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_deletes_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_gets_a_token_for_a_user_multiple_scopes.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_gets_a_token_for_a_user_single_scope.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad/recording_successfully_revokes_tokens_issued_for_a_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad_error_cases_/recording_throws_an_error_when_attempting_to_delete_an_invalid_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad_error_cases_/recording_throws_an_error_when_attempting_to_issue_a_token_for_an_invalid_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad_error_cases_/recording_throws_an_error_when_attempting_to_issue_a_token_without_any_scopes.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_aad_error_cases_/recording_throws_an_error_when_attempting_to_revoke_a_token_from_an_invalid_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_error_cases_/recording_throws_an_error_when_attempting_to_delete_an_invalid_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_error_cases_/recording_throws_an_error_when_attempting_to_issue_a_token_for_an_invalid_user.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_error_cases_/recording_throws_an_error_when_attempting_to_issue_a_token_without_any_scopes.json
sdk/communication/communication-identity/recordings/browsers/communicationidentityclient_playbacklive_error_cases_/recording_throws_an_error_when_attempting_to_revoke_a_token_from_an_invalid_user.json
sdk/communication/communication-identity/test/public/communicationIdentityClient.spec.ts
sdk/communication/communication-identity/test/public/utils/recordedClient.ts

Using the ClientSecretCredential enables us to run these live tests in the browser so we no longer have to skip them :)
Also, good job for the factory methods/helper functions making refactoring a breeze!

[communication] communication-identity - enable aad browser tests 

---

sdk/web-pubsub/web-pubsub/review/web-pubsub.api.md
sdk/web-pubsub/web-pubsub/src/hubClient.ts

To be consistent with other languages

Change getAuthToken to support roles and ttl instead of claims

---

sdk/communication/communication-sms/recordings/browsers/smsclient_playbackrecord_when_sending_sms/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.json
sdk/communication/communication-sms/recordings/node/smsclient_playbackrecord_aad_when_sending_sms/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.js
sdk/communication/communication-sms/recordings/node/smsclient_playbackrecord_when_sending_sms/recording_throws_an_exception_when_sending_from_a_number_you_dont_own.js
sdk/communication/communication-sms/test/public/suites/smsClient.send.ts

This re-enables the error code check now that the error code is returning the correct value

[communication] SMS - re-enable error code check in live test

---

sdk/communication/communication-phone-numbers/CHANGELOG.md
sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-phone-numbers/src/utils/constants.ts

Releasing GA first version of phonenumbers JS package.

[PhoneNumbers][JS] Updating package version to 1.0.0

---

sdk/communication/communication-phone-numbers/tests.yml
sdk/communication/communication-sms/tests.yml

Reverts Azure/azure-sdk-for-js#15022

[Communication] - Tests - revert adding back in subscription id 

---

eng/common/scripts/ChangeLog-Operations.ps1
sdk/communication/communication-sms/CHANGELOG.md
sdk/core/core-crypto/CHANGELOG.md
sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/test-utils/perfstress/CHANGELOG.md
sdk/web-pubsub/web-pubsub-express/CHANGELOG.md
sdk/web-pubsub/web-pubsub/CHANGELOG.md

- Added dates to changelog to make sure they are sorted correctly.

Fix Delinquent Changelogs

---

sdk/storage/storage-file-datalake/package.json
sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_for_directory_should_work_for_permissions_m_e_o_p.js
sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_should_work_with_agentobjectid_preauthorizedagentobjectid.js
sdk/storage/storage-file-datalake/recordings/node/sas_generation_nodejs_only_for_delegation_sas/recording_generateuserdelegationsas_should_work_with_correlationid.js
sdk/storage/storage-file-datalake/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_file.js
sdk/storage/storage-file-datalake/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_file_for_20191212.js
sdk/storage/storage-file-datalake/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_filesystem_with_all_configurations.js
sdk/storage/storage-file-datalake/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_generateuserdelegationsas_should_work_for_filesystem_with_minimum_parameters.js

and re-generate recordings for affected tests.

[storage-file-datalake][test] upgrade to identity v2

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-amqp/package.json
sdk/eventhub/event-hubs/CHANGELOG.md
sdk/eventhub/event-hubs/package.json
sdk/servicebus/service-bus/package.json

Prepares `@azure/core-amqp` v2.3.0 and `@azure/event-hubs` v5.5.1 for release.
/cc @ramya-rao-a

[core-amqp][event-hubs] prepare for release

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/identity/identity/test/manual/package.json
sdk/identity/perf-tests/identity/package.json
sdk/quantum/quantum-jobs/samples/package.json
sdk/storage/storage-blob/samples/javascript/package.json

Identity beta.2 breaks browser bundles, so switching to beta.3 all over.

Use 2.0.0-beta.3 of Identity instead of beta 1 or 2

---

sdk/communication/communication-chat/README.md
sdk/communication/communication-identity/README.md
sdk/communication/communication-phone-numbers/README.md

This PR:
resolves #15074 
resolves #15075 
resolves #15076

[communication] Address readme issues

---

sdk/documenttranslator/ai-document-translator-rest/README.md

[DocumentTranslator] Fix Sample links

---

sdk/communication/CONTRIBUTING.md

Same as the contribution guides we have added for the other platforms.

[Communication] - Contribution - Introducing contribution guide

---

sdk/search/perf-tests/search-documents/package.json
sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/package.json
sdk/search/search-documents/src/constants.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/searchServiceClientContext.ts

This PR is a version update PR for the search-documents SDK release for May 21. 
@xirzec Please review and approve the PR.

Version Update Change for search-documents May 21

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-util/CHANGELOG.md

[core] add conventional headings to group changes

---

common/config/rush/pnpm-lock.yaml

- Result of running "rush update --recheck"
- Fixes error when running "rush update"

Add missing dependency from @azure/core-http to @rollup/plugin-replace

---

sdk/core/ci.yml

This adds core-util as an artifact to be published by the core release pipeline

[core] enable publishing core-util

---

sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md
sdk/confidentialledger/confidential-ledger-rest/package.json
sdk/core-rest/core-client/CHANGELOG.md
sdk/core-rest/core-client/package.json
sdk/core-rest/core-client/src/constants.ts
sdk/documenttranslator/ai-document-translator-rest/package.json
sdk/purview/purview-catalog-rest/package.json
sdk/purview/purview-scanning-rest/package.json

* Bumping version number and update dependants.
* Update changelog

[rest-core-client]Bump version and update changelog

---

.github/CODEOWNERS

Welcome, Will! 🌞
Also, Maor mentioned to me he really wanted to take another direction, so I'd rather not automatically bother him with every Identity PR!

[Identity] Adding Will to the Identity code owners

---

sdk/confidentialledger/confidential-ledger-rest/CHANGELOG.md

[Confidential Ledger] Update changelog for beta.2

---

SUPPORT.md

- There was incorrect link with locale merged in which caused the aggregate pipeline to fail
Pipeline not getting triggered on PR so manually queued for verification - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=892031&view=results

remove locale from support.md

---

sdk/storage/storage-file-datalake/test/node/highlevel.node.spec.ts

Fix a test issue in environment where buffer supports 4GB at largest.

Fix a test issue in environment where buffer supports 4GB at largest.

---

sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/utils/constants.ts
sdk/storage/storage-blob/swagger/README.md

[storage-blob]Support version 2020-08-04 in storage-blob package.

[storage-blob]Support version 2020-08-04 in storage-blob package.

---

sdk/communication/communication-sms/test/public/utils/assertHelpers.ts

ensure that we check the repetability result was received on success

[communication] tests - add repeatability result check

---

.github/CODEOWNERS

and add an entry for /sdk/core/core-rest/

[core] update CODEOWNERS

---

sdk/core/core-client/src/serializationPolicy.ts
sdk/core/core-client/test/serviceClient.spec.ts

This PR is to fix the issue reported in the issue https://github.com/Azure/azure-sdk-for-js/issues/15273. A sample of the specific issue has been provided in the `spec` file itself. 
@xirzec @jeremymeng Please review and approve the PR.

Code to catch the missing mandatory parameter

---

sdk/storage/test-resources.json

Add test resource config

---

sdk/storage/storage-file-datalake/test/filesystemclient.spec.ts

Skip test cases for unsupported features.

Skip test cases for unsupported features.

---

sdk/core/core-client/src/urlHelpers.ts
sdk/core/core-client/test/serviceClient.spec.ts

This PR is very similar to the PR https://github.com/Azure/azure-sdk-for-js/pull/15274. But, this PR deals with queryParameters (the previous one dealt with header parameters).
@xirzec @jeremymeng Please review and approve the PR.

Code to catch the missing mandatory parameter in query

---

sdk/textanalytics/ai-text-analytics/samples/v5/javascript/beginAnalyzeActions.js
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/beginAnalyzeActions.ts

I just forgot to publish the latest changes to dev samples.

[Text Analytics] Update JS samples

---

sdk/resourcegraph/arm-resourcegraph/package.json
sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts
sdk/resourcegraph/arm-resourcegraph/src/models/parameters.ts
sdk/resourcegraph/arm-resourcegraph/src/operations/operations.ts
sdk/resourcegraph/arm-resourcegraph/src/resourceGraphClient.ts
sdk/resourcegraph/arm-resourcegraph/src/resourceGraphClientContext.ts

release for issue; https://github.com/Azure/sdk-release-request/issues/1481

Arm resourcegraph release

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_diacritics_nfc.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_diacritics_nfd.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_wit_skin_tone_modifier.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_korean_nfc.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_korean_nfd.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_zalgo.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_diacritics_nfc.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_diacritics_nfd.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_emoji_with_skin_tone_modifier.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_family_emoji_wit_skin_tone_modifier.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_korean_nfc.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_korean_nfd.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_fast_tests_string_encoding_textelement_v8/recording_zalgo.js
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/util.ts
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

And rename `TextElements_v8` to `TextElement_v8`.

[Text Analytics] Prepare release

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

Related to the last item in https://github.com/Azure/azure-sdk-for-js/issues/14234.

[Dev tool]Add node-version argument that could be multiple

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md

This PR updates the core-client and core-rest-pipeline packages. The latest code fixes contain bug fixes for these packages.
@ramya-rao-a Please review and approve the PR.

Changelog Modification for core-client and core-rest-pipeline

---

sdk/containerregistry/container-registry/README.md
sdk/containerregistry/container-registry/package.json
sdk/containerregistry/container-registry/test/public/containerRegistryClient.spec.ts
sdk/containerregistry/container-registry/test/public/repositoryAndArtifact.spec.ts

Remove a temporary workaround of service issue where deleted resource is still cached when response is returned. Resolves #14675

[ContainerRegistry] Minor fix after beta.2

---

eng/pipelines/templates/steps/analyze.yml

PR to utilize common template to publish artifact.

Update analyze step to use common publish artifact with retry

---

sdk/iot/ci.yml

[iot-modelsrepository] add ci.yml

---

sdk/keyvault/keyvault-certificates/CHANGELOG.md
sdk/keyvault/keyvault-certificates/review/keyvault-certificates.api.md
sdk/keyvault/keyvault-certificates/src/identifier.ts
sdk/keyvault/keyvault-certificates/src/index.ts
sdk/keyvault/keyvault-certificates/src/transformations.ts
sdk/keyvault/keyvault-certificates/test/public/identifier.spec.ts
sdk/keyvault/keyvault-keys/CHANGELOG.md
sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
sdk/keyvault/keyvault-keys/src/cryptography/remoteCryptographyProvider.ts
sdk/keyvault/keyvault-keys/src/identifier.ts
sdk/keyvault/keyvault-keys/src/index.ts
sdk/keyvault/keyvault-keys/src/transformations.ts
sdk/keyvault/keyvault-keys/test/public/identifier.spec.ts
sdk/keyvault/keyvault-secrets/CHANGELOG.md
sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
sdk/keyvault/keyvault-secrets/src/identifier.ts
sdk/keyvault/keyvault-secrets/src/index.ts
sdk/keyvault/keyvault-secrets/src/transformations.ts
sdk/keyvault/keyvault-secrets/test/public/identifier.spec.ts

Exposing the identifier parsers and aligning their names with other languages.

[Key Vault] Exposing the Identifier parsers, and aligning the names

---

sdk/tables/data-tables/src/models.ts

[data-tables] Fixing a typo in the doc comment

---

sdk/core/core-rest-pipeline/src/nodeHttpClient.ts
sdk/core/core-rest-pipeline/src/policies/redirectPolicy.ts
sdk/core/core-rest-pipeline/test/node/getBodyLength.spec.ts

This PR is to merge the Code Changes from the already merged PR: https://github.com/Azure/azure-sdk-for-js/pull/15314/. Since this branch will be going for a hot fix release soon, I want to include these changes also to it. Then, I can use the hot fix version in the V6 SDK generator's preview release. 
@xirzec Please review and approve the PR.
@ramya-rao-a FYI......

Fix UTF-8 String length & DELETE Request Body

---

common/tools/add-identity-mgmt-lib.js

Because some operations do not take arguments and some take other arguments.
Here are examples of using the updated script:
[compute](https://github.com/Azure/azure-sdk-for-js/pull/15392)
[consumption](https://github.com/Azure/azure-sdk-for-js/pull/15393)

[Add Identity Script] Detect operation argument initialization statements

---

sdk/core/core-http/src/util/sanitizer.ts
sdk/core/core-http/src/util/utils.ts
sdk/core/core-http/test/sanitizerTests.ts
sdk/core/core-rest-pipeline/CHANGELOG.md
sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/src/constants.ts
sdk/core/core-rest-pipeline/src/util/helpers.ts
sdk/core/core-rest-pipeline/src/util/sanitizer.ts
sdk/core/core-rest-pipeline/test/sanitizer.spec.ts

This PR cherrypicks the changes in #15426 and updates the release notes for 1.0.4.

[core-rest-pipeline] Cherry-pick PR #15426 to hotfix branch

---

common/tools/add-identity-mgmt-lib.js

Just to be consistent with the bullet point list above it.

[Add Identity Script] Fix indentation

---

sdk/iot/iot-modelsrepository/src/fetcherHTTP.ts
sdk/iot/iot-modelsrepository/test/node/integration/index.spec.ts

Typescript let this one through... but needed to adjust the API so we are sure we are handling the no options scenario properly.

Add test and fix for no options API

---

sdk/iot/iot-modelsrepository/CHANGELOG.md
sdk/iot/iot-modelsrepository/package.json
sdk/iot/iot-modelsrepository/src/constants.ts

Releasing Hotfix for bug in API.

Release PR for 5.28.2021 IoT ModelsRepository

---

sdk/videoanalyzer/video-analyzer-edge/CHANGELOG.md
sdk/videoanalyzer/video-analyzer-edge/README.md
sdk/videoanalyzer/video-analyzer-edge/package.json

- Fixed capitalization
- Removed old terminology

[AVA] Changes to ReadMe

---

sdk/datadog/arm-datadog/package.json
sdk/datadog/arm-datadog/src/microsoftDatadogClientContext.ts
sdk/datadog/arm-datadog/src/models/index.ts
sdk/datadog/arm-datadog/src/models/mappers.ts
sdk/datadog/arm-datadog/src/operations/monitors.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1603

Arm datadog release

---

sdk/core/core-rest-pipeline/CHANGELOG.md

Release date for @azure/core-rest-pipeline 1.1.0-beta.3
Reviews appreciated!

[core-rest-pipeline] 1.1.0-beta.3 release date

---

sdk/documenttranslator/ai-document-translator-rest/README.md

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/15471

Fix Ai Document Translator Readme Issue

---

sdk/web-pubsub/web-pubsub-express/README.md

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/15470

Fix Web Pubsub Express Readme Issue

---

sdk/textanalytics/ai-text-analytics/README.md

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/15472

Fix Ai Text Analytics Readme Issue

---

sdk/datadog/arm-datadog/README.md
sdk/datadog/arm-datadog/package.json
sdk/datadog/arm-datadog/src/microsoftDatadogClient.ts
sdk/datadog/arm-datadog/src/microsoftDatadogClientContext.ts

Reverts Azure/azure-sdk-for-js#15558

Revert "arm-datadog-v4"

---

common/config/rush/pnpm-lock.yaml

This PR is the clone of https://github.com/Azure/azure-sdk-for-js/pull/15541 with one modification as suggested by the comment here: https://github.com/Azure/azure-sdk-for-js/pull/15541#issuecomment-854266673
Four security vulnerabilities have been reported in our repository. In order to fix them, I have followed the steps provided in our Component Governance one note and creating this PR.
The Security Vulnerabilities could be found [here](https://dev.azure.com/azure-sdk/internal/_componentGovernance/101977?_a=alerts&typeId=1588279&alerts-view-option=active). Out of the 4 security vulnerabilities, this PR will fix 3 of them. The Critical vulnerability regarding the jsrsasign package will be handled seperately.
@richardpark-msft Please review and approve. 

Fix Security Vulnerabilities

---

README.md

Add Gitter community channel for azure-sdk-for-js

Add Gitter community channel

---

sdk/containerregistry/container-registry/README.md
sdk/containerregistry/container-registry/samples-dev/anonymousListTags.ts
sdk/containerregistry/container-registry/samples-dev/containerRegistryClient.ts
sdk/containerregistry/container-registry/samples-dev/deleteImages.ts
sdk/containerregistry/container-registry/samples-dev/repositoryAndArtifact.ts
sdk/containerregistry/container-registry/samples-dev/setImageProperties.ts
sdk/containerregistry/container-registry/samples/v1/javascript/README.md
sdk/containerregistry/container-registry/samples/v1/javascript/anonymousListTags.js
sdk/containerregistry/container-registry/samples/v1/javascript/containerRegistryClient.js
sdk/containerregistry/container-registry/samples/v1/javascript/deleteImages.js
sdk/containerregistry/container-registry/samples/v1/javascript/package.json
sdk/containerregistry/container-registry/samples/v1/javascript/repositoryAndArtifact.js
sdk/containerregistry/container-registry/samples/v1/javascript/setImageProperties.js
sdk/containerregistry/container-registry/samples/v1/typescript/README.md
sdk/containerregistry/container-registry/samples/v1/typescript/package.json
sdk/containerregistry/container-registry/samples/v1/typescript/src/anonymousListTags.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/containerRegistryClient.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/deleteImages.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/repositoryAndArtifact.ts
sdk/containerregistry/container-registry/samples/v1/typescript/src/setImageProperties.ts

This builds on top of PR #15289

[ContainerRegistry] Add more champion scenario samples

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-datalake/review/storage-file-datalake.api.md
sdk/storage/storage-file-datalake/src/generated/src/models/index.ts
sdk/storage/storage-file-datalake/src/generated/src/models/mappers.ts
sdk/storage/storage-file-datalake/src/models.ts
sdk/storage/storage-file-datalake/swagger/README.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md

[storage]Preparing for STG77 GA

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
sdk/textanalytics/ai-text-analytics/swagger/README.md

Fixes https://github.com/Azure/azure-sdk-for-js/issues/15310
This will make sync and async methods on par feature-wise.

[Text Analytics] add categoriesFilter to RecognizePiiEntitiesAction 

---

common/config/rush/pnpm-lock.yaml
sdk/schemaregistry/schema-registry-avro/package.json

- upgrade identity version for schema registry avro

upgrade identity version for schema registry avro

---

common/tools/add-identity-mgmt-lib.js

To match the updated support policy.

[Add Identity Script] Update supported environments

---

.github/CODEOWNERS

Adding @dw511214992 as code owner for mgmt plane packages as he has been working with @qiaozha in this area

Adding Wei as code owner for mgmt plane packages

---

sdk/core/core-rest-pipeline/package.json
sdk/core/core-rest-pipeline/samples-dev/node-sample.ts
sdk/core/core-rest-pipeline/samples/v1/javascript/README.md
sdk/core/core-rest-pipeline/samples/v1/javascript/node-sample.js
sdk/core/core-rest-pipeline/samples/v1/javascript/package.json
sdk/core/core-rest-pipeline/samples/v1/typescript/README.md
sdk/core/core-rest-pipeline/samples/v1/typescript/package.json
sdk/core/core-rest-pipeline/samples/v1/typescript/src/node-sample.ts
sdk/core/core-rest-pipeline/samples/v1/typescript/tsconfig.json
sdk/core/core-rest-pipeline/tsconfig.json

of making a GET request using the default Http client.
Fixes https://github.com/Azure/azure-sdk-for-js/issues/15013

[core-rest-pipeline] Add a simple sample

---

sdk/communication/communication-network-traversal/package.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.json
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.js
sdk/communication/communication-network-traversal/test/public/utils/recordedClient.ts

Update @azure/identity version to 2.0.0-beta.4
Adding new recordings.

Update @azure/identity version to 2.0.0-beta.4

---

sdk/netapp/arm-netapp/README.md
sdk/netapp/arm-netapp/package.json
sdk/netapp/arm-netapp/src/azureNetAppFilesManagementClient.ts
sdk/netapp/arm-netapp/src/azureNetAppFilesManagementClientContext.ts
sdk/netapp/arm-netapp/src/models/backupsMappers.ts
sdk/netapp/arm-netapp/src/models/index.ts
sdk/netapp/arm-netapp/src/models/mappers.ts
sdk/netapp/arm-netapp/src/models/netAppResourceMappers.ts
sdk/netapp/arm-netapp/src/models/parameters.ts
sdk/netapp/arm-netapp/src/operations/accountBackups.ts
sdk/netapp/arm-netapp/src/operations/backupPolicies.ts
sdk/netapp/arm-netapp/src/operations/backups.ts
sdk/netapp/arm-netapp/src/operations/netAppResource.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1663

Arm netapp release

---

sdk/communication/communication-identity/package.json
sdk/communication/communication-phone-numbers/package.json
sdk/communication/communication-sms/package.json

Updating our azure identity version to incorporate the fixes from https://github.com/Azure/azure-sdk-for-js/pull/15676/files

[communication] update to identity 2.0.0-beta.4

---

sdk/synapse/synapse-artifacts/package.json
sdk/synapse/synapse-artifacts/recordings/browsers/bigdatapools/recording_should_get_a_bigdatapool_by_name.json
sdk/synapse/synapse-artifacts/recordings/browsers/bigdatapools/recording_should_list_bigdatapools.json
sdk/synapse/synapse-artifacts/recordings/browsers/dataflow/recording_should_create_dataflow.json
sdk/synapse/synapse-artifacts/recordings/browsers/dataflow/recording_should_delete_dataflow.json
sdk/synapse/synapse-artifacts/recordings/browsers/dataflow/recording_should_get_dataflow.json
sdk/synapse/synapse-artifacts/recordings/browsers/dataflow/recording_should_list_dataflows.json
sdk/synapse/synapse-artifacts/recordings/browsers/dataflow/recording_should_rename_dataflow.json
sdk/synapse/synapse-artifacts/recordings/browsers/integrationruntimes/recording_should_get_integrationruntimes.json
sdk/synapse/synapse-artifacts/recordings/browsers/integrationruntimes/recording_should_list_integrationruntimes.json
sdk/synapse/synapse-artifacts/recordings/browsers/library/recording_should_create_library.json
sdk/synapse/synapse-artifacts/recordings/browsers/library/recording_should_delete_library.json
sdk/synapse/synapse-artifacts/recordings/browsers/library/recording_should_get_library.json
sdk/synapse/synapse-artifacts/recordings/browsers/library/recording_should_list_library.json
sdk/synapse/synapse-artifacts/recordings/node/bigdatapools/recording_should_get_a_bigdatapool_by_name.js
sdk/synapse/synapse-artifacts/recordings/node/bigdatapools/recording_should_list_bigdatapools.js
sdk/synapse/synapse-artifacts/recordings/node/dataflow/recording_should_create_dataflow.js
sdk/synapse/synapse-artifacts/recordings/node/dataflow/recording_should_delete_dataflow.js
sdk/synapse/synapse-artifacts/recordings/node/dataflow/recording_should_get_dataflow.js
sdk/synapse/synapse-artifacts/recordings/node/dataflow/recording_should_list_dataflows.js
sdk/synapse/synapse-artifacts/recordings/node/dataflow/recording_should_rename_dataflow.js
sdk/synapse/synapse-artifacts/recordings/node/integrationruntimes/recording_should_get_integrationruntimes.js
sdk/synapse/synapse-artifacts/recordings/node/integrationruntimes/recording_should_list_integrationruntimes.js
sdk/synapse/synapse-artifacts/recordings/node/library/recording_should_create_library.js
sdk/synapse/synapse-artifacts/recordings/node/library/recording_should_delete_library.js
sdk/synapse/synapse-artifacts/recordings/node/library/recording_should_get_library.js
sdk/synapse/synapse-artifacts/recordings/node/library/recording_should_list_library.js

* Updating identity version
* Regenerate recordings

[Synapse Artifacts] Update identity version ad re do recordings

---

sdk/deviceupdate/iot-device-update/package.json

update identity version to 2.0.0-beta.4 for iot-device-update

update identity version to 2.0.0-beta.4 for iot-device-update

---

sdk/identity/identity/test/manual-integration/AzureFunctions/IdentityTest/local.settings.json
sdk/template/template/package.json
sdk/template/template/recordings/browsers/aad_configurationclient_functional_tests/recording_predetermined_setting_has_expected_value.json
sdk/template/template/recordings/node/aad_configurationclient_functional_tests/recording_predetermined_setting_has_expected_value.js
sdk/template/template/test/public/configurationClient.spec.ts

- Updated version of identity upgraded in dev-dep of template

template identity version updated

---

sdk/core/core-http/CHANGELOG.md

This PR prepares for a patch release scheduled on Monday, June 14th.

[core-http] Prepare for v1.2.6 release

---

sdk/identity/identity/src/msal/browserFlows/msalAuthCode.ts
sdk/identity/identity/src/msal/utils.ts

I was using this tool from Node.js and from the browser, and I had forgotten to adjust the message depending on the platform using it. This fixes it!

[Identity] Fixed wrong log on Node.js

---

eng/.docsettings.yml
sdk/core/abort-controller/README.md
sdk/core/core-amqp/README.md
sdk/core/core-auth/README.md
sdk/core/logger/README.md

Fixes #14726 
Fixes #14716 
Fixes #14715 
Fixes #14714

[core] Fix missing readme headers

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/karma.conf.js
sdk/monitor/monitor-query/sample.env
sdk/monitor/monitor-query/samples-dev/metricsQuery.ts
sdk/monitor/monitor-query/samples/v1/javascript/metricsQuery.js
sdk/monitor/monitor-query/samples/v1/javascript/package.json
sdk/monitor/monitor-query/samples/v1/javascript/sample.env
sdk/monitor/monitor-query/samples/v1/typescript/package.json
sdk/monitor/monitor-query/samples/v1/typescript/sample.env
sdk/monitor/monitor-query/samples/v1/typescript/src/metricsQuery.ts
sdk/monitor/monitor-query/test.env
sdk/monitor/monitor-query/test/public/logsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/metricsQueryClient.spec.ts
sdk/monitor/monitor-query/test/public/shared/testShared.ts
sdk/monitor/test-resources.json

Getting live tests running (test-resources.json).

[monitor-query] Adding live tests for monitor-query and update changelog for release

---

eng/.docsettings.yml

Fixes #14728
Test utils is an internal package, need not follow readme template

Test utils is an internal package, need not follow readme template

---

sdk/iot/iot-modelsrepository/CHANGELOG.md
sdk/iot/iot-modelsrepository/package.json
sdk/iot/iot-modelsrepository/src/utils/constants.ts

Increment package version after release of azure-iot-modelsrepository

Increment package version after release of azure-iot-modelsrepository

---

sdk/core/core-client/CHANGELOG.md

The Management Team is waiting for an update in the core-client to be used for their management packages migration using the `@autorest/typescript` package. So, I am planning to release the fix today.
@jeremymeng Please approve the PR. 

Update core-client changelog

---

sdk/network/arm-network/README.md
sdk/network/arm-network/package.json
sdk/network/arm-network/src/models/index.ts
sdk/network/arm-network/src/models/mappers.ts
sdk/network/arm-network/src/networkManagementClient.ts
sdk/network/arm-network/src/networkManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1611

Arm network v4

---

sdk/identity/ci.yml
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/identity/identity-vscode/test/public/node/visualStudioCodeCredential.spec.ts

This should allow our pipelines to pick these packages up for publication.

[identity] Add publication metadata for extension pacakges

---

sdk/eventgrid/arm-eventgrid/README.md
sdk/eventgrid/arm-eventgrid/package.json
sdk/eventgrid/arm-eventgrid/src/eventGridManagementClient.ts
sdk/eventgrid/arm-eventgrid/src/eventGridManagementClientContext.ts
sdk/eventgrid/arm-eventgrid/src/models/domainTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/domainsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/eventChannelsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/eventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/extensionTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/index.ts
sdk/eventgrid/arm-eventgrid/src/models/mappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerNamespacesMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerRegistrationsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerTopicEventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/partnerTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/privateEndpointConnectionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/systemTopicEventSubscriptionsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/systemTopicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/topicTypesMappers.ts
sdk/eventgrid/arm-eventgrid/src/models/topicsMappers.ts
sdk/eventgrid/arm-eventgrid/src/operations/domainTopics.ts
sdk/eventgrid/arm-eventgrid/src/operations/domains.ts
sdk/eventgrid/arm-eventgrid/src/operations/partnerRegistrations.ts
sdk/eventgrid/arm-eventgrid/src/operations/privateEndpointConnections.ts
sdk/eventgrid/arm-eventgrid/src/operations/privateLinkResources.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1688

arm-eventgrid-release

---

eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/steps/build.yml

Make sure documentation is present before attempting to copy it.

Fix pipeline error

---

samples/cors/ts/README.md
samples/frameworks/electron/ts/README.md
sdk/keyvault/keyvault-admin/README.md
sdk/keyvault/keyvault-certificates/README.md
sdk/keyvault/keyvault-keys/README.md
sdk/keyvault/keyvault-secrets/README.md

This PR is a follow up from #16011 for the feedback from @jeremymeng 
A few missing periods and spaces, but this lead me to find that I had missed updating the other KV readmes in #16011

Update KV readmes with support policy

---

sdk/quantum/quantum-jobs/package.json
sdk/quantum/quantum-jobs/recordings/node/quantum_job_lifecycle/recording_test_get_providers_status.js
sdk/quantum/quantum-jobs/recordings/node/quantum_job_lifecycle/recording_test_get_quotas.js
sdk/quantum/quantum-jobs/recordings/node/quantum_job_lifecycle/recording_test_quantum_job_lifecycle.js
sdk/quantum/quantum-jobs/test/utils/testAuthentication.ts

This is to address the issue https://github.com/Azure/azure-sdk-for-js/issues/15710. 
@KarishmaGhiya Please review and approve the PR. Thanks

Update identity to 2.0.0-beta.4 for quantum jobs

---

sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/generated/src/appConfigurationContext.ts

[App Config] changelog and update versions for GA

---

sdk/core/core-auth/CHANGELOG.md
sdk/core/core-auth/package.json

- bump core-auth to 1.3.2 for release

bump core-auth

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-blob/recordings/browsers/containerclient/recording_listblobsflat_with_includedeletedwithversions.json
sdk/storage/storage-blob/recordings/node/containerclient/recording_listblobsflat_with_includedeletedwithversions.js
sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/generated/src/models/parameters.ts
sdk/storage/storage-blob/src/generated/src/storageClientContext.ts
sdk/storage/storage-blob/src/generatedModels.ts
sdk/storage/storage-blob/swagger/README.md
sdk/storage/storage-blob/test/containerclient.spec.ts

Add support for list deleted root blob With versions

Add support for list deleted root blob With versions

---

sdk/identity/identity-cache-persistence/CHANGELOG.md
sdk/identity/identity-vscode/CHANGELOG.md
sdk/identity/identity/CHANGELOG.md

We’re releasing these betas tomorrow :)

[Identity] Release date for all of the Identity packages

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

[Text Analytics] Update release date

---

sdk/web-pubsub/web-pubsub/CHANGELOG.md

I promise I know what year it is.

[web-pubsub] Fix release date

---

sdk/keyvault/keyvault-keys/CHANGELOG.md

Remove empty section to fix the release pipeline

[KeyVault] - Remove empty changelog entry

---

sdk/textanalytics/ai-text-analytics/samples/v5/javascript/README.md
sdk/textanalytics/ai-text-analytics/samples/v5/javascript/beginAnalyzeHealthcareEntities.js
sdk/textanalytics/ai-text-analytics/samples/v5/javascript/package.json
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/README.md
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/package.json
sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/recognizePii.ts

Now that v5.1.0 has been released! And manually edit JS one to not use TS syntax. We should consider using babel for these things.

[Text Analytics] Publish samples

---

sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/common/constants.ts

We want to avoid changing the public API surface until major releases, cc @xirzec

[Cosmos] Adds back deprecated constant

---

eng/pipelines/aggregate-reports.yml
sdk/keyvault/keyvault-admin/platform-matrix.json
sdk/keyvault/keyvault-keys/platform-matrix.json

Update Ubuntu VM image from 18 to 20

Update ubuntu 18 to ubuntu 20

---

sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts

Copying this test from main to ensure the target fix is tested.

[Identity] [Hotfix] IMDS MSI 503 test

---

sdk/communication/communication-network-traversal/CHANGELOG.md
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential.json
sdk/communication/communication-network-traversal/recordings/browsers/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.json
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive/recording_successfully_gets_a_turn_credential.js
sdk/communication/communication-network-traversal/recordings/node/communicationnetworkingclient_playbacklive_aad/recording_successfully_gets_a_turn_credential.js
sdk/communication/communication-network-traversal/review/communication-network-traversal.api.md
sdk/communication/communication-network-traversal/samples-dev/getRelayConfiguration.ts
sdk/communication/communication-network-traversal/src/communicationRelayClient.ts
sdk/communication/communication-network-traversal/src/generated/src/models/index.ts
sdk/communication/communication-network-traversal/src/generated/src/models/mappers.ts
sdk/communication/communication-network-traversal/src/generated/src/models/parameters.ts
sdk/communication/communication-network-traversal/src/generated/src/networkRelayRestClientContext.ts
sdk/communication/communication-network-traversal/src/generated/src/operations/communicationNetworkTraversal.ts
sdk/communication/communication-network-traversal/src/index.ts
sdk/communication/communication-network-traversal/swagger/README.md
sdk/communication/communication-network-traversal/test/public/communicationNetworkTraversalClient.spec.ts

Update to new API version and add new recordings,
Adding new auto generated code and updating the recordings.

Update to new API version and add new recordings

---

sdk/keyvault/test-resources-post.ps1

[KeyVault] - Use PowerShell Cmdlets for Managed HSM deployment

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-rest-pipeline/CHANGELOG.md

Fix Changelogs

---

sdk/postgresql/arm-postgresql/README.md
sdk/postgresql/arm-postgresql/package.json
sdk/postgresql/arm-postgresql/src/models/parameters.ts
sdk/postgresql/arm-postgresql/src/operations/checkNameAvailability.ts
sdk/postgresql/arm-postgresql/src/operations/configurations.ts
sdk/postgresql/arm-postgresql/src/operations/databases.ts
sdk/postgresql/arm-postgresql/src/operations/firewallRules.ts
sdk/postgresql/arm-postgresql/src/operations/locationBasedPerformanceTier.ts
sdk/postgresql/arm-postgresql/src/operations/logFiles.ts
sdk/postgresql/arm-postgresql/src/operations/operations.ts
sdk/postgresql/arm-postgresql/src/operations/recoverableServers.ts
sdk/postgresql/arm-postgresql/src/operations/replicas.ts
sdk/postgresql/arm-postgresql/src/operations/serverAdministrators.ts
sdk/postgresql/arm-postgresql/src/operations/serverBasedPerformanceTier.ts
sdk/postgresql/arm-postgresql/src/operations/serverParameters.ts
sdk/postgresql/arm-postgresql/src/operations/servers.ts
sdk/postgresql/arm-postgresql/src/operations/virtualNetworkRules.ts
sdk/postgresql/arm-postgresql/src/postgreSQLManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1761

arm-postgresql-release

---

sdk/eventgrid/eventgrid/CHANGELOG.md
sdk/eventgrid/eventgrid/review/eventgrid.api.md
sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
sdk/eventgrid/eventgrid/src/generated/models/index.ts
sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
sdk/eventgrid/eventgrid/src/index.ts
sdk/eventgrid/eventgrid/src/predicates.ts
sdk/eventgrid/eventgrid/swagger/README.md

Update to the latest data-plane version and regenerate.

[EventGrid] System Events Updates for June

---

sdk/core/core-lro/CHANGELOG.md

I will merge this PR on Monday.

[core-lro] Prepare release

---

sdk/core/core-lro/CHANGELOG.md

To make release pipeline happy: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1003995&view=logs&j=955f8928-b92a-5505-73b3-a960730226e3&t=bba8fdf1-ad66-5f90-36c7-5ad0331e73a8

[core-lro] Fix changelog

---

sdk/communication/communication-network-traversal/CHANGELOG.md

Update release date

---

sdk/containerinstance/arm-containerinstance/README.md
sdk/containerinstance/arm-containerinstance/package.json
sdk/containerinstance/arm-containerinstance/src/containerInstanceManagementClientContext.ts
sdk/containerinstance/arm-containerinstance/src/operations/containerGroups.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1786

arm-containerinstance-release

---

sdk/signalr/arm-signalr/README.md
sdk/signalr/arm-signalr/package.json
sdk/signalr/arm-signalr/rollup.config.js
sdk/signalr/arm-signalr/src/models/index.ts
sdk/signalr/arm-signalr/src/models/mappers.ts
sdk/signalr/arm-signalr/src/models/parameters.ts
sdk/signalr/arm-signalr/src/operations/operations.ts
sdk/signalr/arm-signalr/src/operations/signalR.ts
sdk/signalr/arm-signalr/src/operations/signalRPrivateEndpointConnections.ts
sdk/signalr/arm-signalr/src/operations/signalRPrivateLinkResources.ts
sdk/signalr/arm-signalr/src/operations/signalRSharedPrivateLinkResources.ts
sdk/signalr/arm-signalr/src/operations/usages.ts
sdk/signalr/arm-signalr/src/signalRManagementClient.ts
sdk/signalr/arm-signalr/src/signalRManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1711

arm-signalr-release

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/tsconfig.json

https://github.com/Azure/azure-sdk-for-js/issues/15670

[Cosmos] Enable ES2017

---

sdk/communication/communication-network-traversal/CHANGELOG.md
sdk/communication/communication-network-traversal/package.json

Updating @azure-identity version to a version that has been released.
Update date of release.

Update Identity version to a version that is released.

---

sdk/attestation/attestation/samples-dev/attestEnclaves.ts
sdk/attestation/attestation/samples-dev/utils/utf8.ts

While preparing for the API review today, I realized that I was missing samples for the Attest API, which seemed kinda important :).
So they've now been added.

Added missing sample

---

sdk/appconfiguration/app-configuration/package.json
sdk/appconfiguration/app-configuration/review/app-configuration.api.md
sdk/appconfiguration/app-configuration/rollup.base.config.js
sdk/appconfiguration/app-configuration/src/appConfigCredential.ts
sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
sdk/appconfiguration/app-configuration/src/internal/helpers.ts
sdk/appconfiguration/app-configuration/src/models.ts
sdk/appconfiguration/app-configuration/src/policies/throttlingRetryPolicy.ts
sdk/appconfiguration/app-configuration/test/internal/node/throttlingRetryPolicy.spec.ts
sdk/appconfiguration/app-configuration/test/internal/package.spec.ts
sdk/appconfiguration/app-configuration/test/internal/throttlingRetryPolicyTests.spec.ts
sdk/appconfiguration/app-configuration/test/internal/tracingHelpers.spec.ts
sdk/appconfiguration/app-configuration/test/public/featureFlag.spec.ts
sdk/appconfiguration/app-configuration/test/public/index.spec.ts
sdk/appconfiguration/app-configuration/test/public/secretReference.spec.ts
sdk/appconfiguration/app-configuration/test/public/utils/testHelpers.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/10774

[App Config] Fix linter errors

---

sdk/communication/communication-common/CHANGELOG.md
sdk/communication/communication-network-traversal/CHANGELOG.md
sdk/communication/communication-network-traversal/README.md
sdk/communication/communication-network-traversal/package.json

Update dependencies to versions that are released

Update dependencies to versions that are released

---

sdk/postgresql/arm-postgresql-flexible/package.json
sdk/postgresql/arm-postgresql-flexible/src/operations/checkNameAvailability.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/configurations.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/databases.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/firewallRules.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/getPrivateDnsZoneSuffix.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/locationBasedCapabilities.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/operations.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/servers.ts
sdk/postgresql/arm-postgresql-flexible/src/operations/virtualNetworkSubnetUsage.ts
sdk/postgresql/arm-postgresql-flexible/src/postgreSQLManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1790

arm-postgresql-flexibleserver-release

---

.github/CODEOWNERS
rush.json
sdk/core/core-client-rest/package.json
sdk/eventgrid/eventgrid/README.md

EventGrid: Fix broken link
Purview: Update rush.json to have `client`
core-client-rest: Fix types path in package.json
Update CODEOWNERS

Fix multiple pipeline failures

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md

Update release date for storage packages

Update release date for storage packages

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md

Update changelogs for storage packages.

Update changelogs for storage packages.

---

sdk/search/search-documents/test/public/node/searchClient.spec.ts

Remove one test that is causing CI failure.

Removed speller test

---

sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-queue/CHANGELOG.md

Update changelog to add release date.

Update changelog to add release date.

---

documentation/next-generation-quickstart.md

Relative links can break, and they seem to be breaking in our Link verification pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1024617

Fixing relative link

---

sdk/web-pubsub/web-pubsub/samples-dev/directMessage.ts
sdk/web-pubsub/web-pubsub/samples/v1/javascript/directMessage.js
sdk/web-pubsub/web-pubsub/samples/v1/typescript/src/directMessage.ts

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/16667
@lilyjma ,@ramya-rao-a ,@nickzhums ,@bterlson and @jongio for notification.

Fix Web Pubsub Sample Issue

---

documentation/MIGRATION-guide-for-next-generation-management-libraries.md

Relative links break our link verification step

Fix relative link in migration guide

---

sdk/attestation/attestation/review/attestation.api.md
sdk/attestation/attestation/src/attestationAdministrationClient.ts
sdk/attestation/attestation/src/index.ts
sdk/attestation/attestation/src/models/attestationToken.ts
sdk/attestation/attestation/test/public/attestationTokenTests.spec.ts

Addressed the current set of API review feedback items.

Final API review feedback

---

common/config/rush/pnpm-lock.yaml
sdk/anomalydetector/ai-anomaly-detector/CHANGELOG.md
sdk/anomalydetector/ai-anomaly-detector/package.json
sdk/anomalydetector/ai-anomaly-detector/src/generated/anomalyDetectorContext.ts

Update dependency on @azure/identity and fix package metadata for bot

[AnomalyDetector] Update identity dependency

---

sdk/core/abort-controller/CHANGELOG.md
sdk/core/abort-controller/package.json
sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json
sdk/core/core-rest-pipeline/CHANGELOG.md

Reviewed the commit history for the core packages and made updates to changelogs to reflect the changes while prepping for the August release
@joheredi will be following up for the core packages needed for LLC

Aug release changelog updates for core packages

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/package.json
sdk/monitor/monitor-query/src/constants.ts

- Manually ran the increment version script to override this PR - https://github.com/Azure/azure-sdk-for-js/pull/16263/files

increment monitor-query version

---

sdk/communication/communication-identity/package.json
sdk/communication/communication-phone-numbers/package.json
sdk/compute/arm-compute/package.json
sdk/core/core-lro/CHANGELOG.md
sdk/formrecognizer/ai-form-recognizer/package.json
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/managedapplications/arm-managedapplications/package.json
sdk/metricsadvisor/ai-metrics-advisor/package.json
sdk/network/arm-network/package.json
sdk/remoterendering/mixed-reality-remote-rendering/package.json
sdk/resources/arm-resources/package.json
sdk/storage/arm-storage/package.json
sdk/storage/storage-blob-changefeed/package.json
sdk/storage/storage-blob/package.json
sdk/synapse/synapse-artifacts/package.json
sdk/textanalytics/ai-text-analytics/package.json

- Updates the changelog release date to August 5th for core-lro
- Update the dependency on core-lro to v2.2.0 in all packages since text analytics need the feature released in that particular version
- Also fixes failure in text analytics's min testing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1031466&view=logs&j=6080fc5e-b925-535b-661b-682a75b9c63c&t=fb3c5c16-3368-568d-f84b-95063797a6a3

[core-lro] Prepare for release on August 5th

---

.scripts/common.ts
eng/pipelines/dataplane-ci.yml
eng/pipelines/dataplane-pr.yml

Add pipelines for track1 data plane packages. Copy of old mgmt pipelines with shortened list of triggers.

Create pipelines for data plane track1 package

---

sdk/batch/batch/package.json
sdk/batch/batch/src/batchServiceClientContext.ts

Version bump got missed in #16679

Version update for Azure Batch package

---

sdk/iot/iot-modelsrepository/README.md

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/16097
@lilyjma , @ramya-rao-a , @YoDaMa and @jongio for notification.

Fix Iot Modelsrepository Readme Issue

---

eng/pipelines/dataplane-pr.yml
sdk/graphrbac/graph/package.json
sdk/graphrbac/graph/src/graphRbacManagementClientContext.ts

1. Add VM image
2. @azure/graph 5.0.3 was released from feature/v4 unintentionally. Updating the version here to 5.0.3 on main as well so new data plane pipeline for track1 package will not attempt to release 5.0.2 due to version conflict against version on npm.

Update vm image for track1 pipeline job

---

sdk/keyvault/keyvault-certificates/README.md

Resolves #16100
@lilyjma , @ramya-rao-a , @AlexGhiondea , @maorleger and @jongio for notification.

Fix Azure Keyvault Certificate Readme Issue

---

sdk/core/core-client-lro-rest/CHANGELOG.md
sdk/core/core-client-paging-rest/CHANGELOG.md
sdk/core/core-client-rest/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md

Updating changelog dates for
@Azure/core-xml
@azure-rest/core-client-paging
@azure-rest/core-client-lro

Update Aug core changelog

---

sdk/textanalytics/ai-text-analytics/README.md

to add an entry about extractive summarization

[Text Analytics] Edit readme

---

sdk/core/ci.yml
sdk/core/core-client-lro-rest/CHANGELOG.md

Missed adding the new package to ci.yml adding it to enable release and update changelog

Add core-rest-client-lro to artifacts

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

[Text Analytics] Update changelog

---

sdk/monitor/monitor-query/CHANGELOG.md
sdk/monitor/monitor-query/README.md

Follow up for this - https://github.com/Azure/azure-sdk-for-js/pull/16791#issuecomment-895029743

Add samples link for multiple workspaces

---

eng/scripts/Language-Settings.ps1

See https://github.com/Azure/azure-sdk-for-js/issues/16809

Add @azure/batch to packge exclusions

---

sdk/tables/data-tables/CHANGELOG.md

Had some empty sections and a duplicate entry

[Tables] Fix changelog

---

sdk/identity/identity/CHANGELOG.md

I forgot to remove this empty section in the changelog file!

[Identity] Removed empty changelog section

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md

This blocked our release after approving it.

[formrecognizer] Fix CHANGELOG

---

sdk/synapse/synapse-access-control/CHANGELOG.md
sdk/synapse/synapse-access-control/package.json
sdk/synapse/synapse-access-control/src/accessControlClientContext.ts
sdk/synapse/synapse-access-control/swagger/README.md
sdk/synapse/synapse-artifacts/CHANGELOG.md
sdk/synapse/synapse-artifacts/package.json
sdk/synapse/synapse-artifacts/src/artifactsClientContext.ts
sdk/synapse/synapse-artifacts/swagger/README.md
sdk/synapse/synapse-managed-private-endpoints/CHANGELOG.md
sdk/synapse/synapse-managed-private-endpoints/package.json
sdk/synapse/synapse-managed-private-endpoints/src/managedPrivateEndpointsClientContext.ts
sdk/synapse/synapse-managed-private-endpoints/swagger/README.md
sdk/synapse/synapse-spark/CHANGELOG.md
sdk/synapse/synapse-spark/package.json
sdk/synapse/synapse-spark/src/sparkClientContext.ts
sdk/synapse/synapse-spark/swagger/README.md

Update versions and fix package metadata that prevented the bot to update

Update synapse versions

---

sdk/cosmosdb/cosmos/CHANGELOG.md
sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/review/cosmos.api.md
sdk/cosmosdb/cosmos/src/ClientContext.ts
sdk/cosmosdb/cosmos/src/client/Item/Items.ts
sdk/cosmosdb/cosmos/src/utils/batch.ts
sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts

[Cosmos] Adds transactional batch

---

common/config/rush/common-versions.json

Add core-paging@^1.2.0-alpha to common-versions.json

---

eng/tools/versioning/set-dev.js

Update version dependency for dev

---

sdk/core/core-lro/samples/typescript/samplesClient.ts

Fix issue https://github.com/Azure/azure-sdk-for-js/issues/15071
@jongio, @ramya-rao-a, @joshfree, @deyaaeldeen  for notification.

Fix Azure Core LRO Sample Issues

---

eng/scripts/Language-Settings.ps1

Failing because of https://github.com/Azure/azure-sdk-for-js/issues/16932

Pin @azure/arm-appservice

---

CONTRIBUTING.md

Adds this requirement to our CONTRIBUTING guide per discussions in #15940.
Closes #15940

Add C++ toolchain requirement to CONTRIBUTING.md

---

sdk/schemaregistry/schema-registry/CHANGELOG.md

[Schema Registry] Add release date to changelog

---

common/config/rush/common-versions.json

Update dependency exception to new format until dev version script is updated

Update temp work around for dev exception

---

sdk/purview/purview-scanning-rest/README.md

[Purview] Fix scanning url in README.MD

---

documentation/next-generation-quickstart.md
sdk/identity/identity/test/public/browser/usernamePasswordCredential.spec.ts

[CredScan] replace password value with a replacement value

---

sdk/keyvault/keyvault-keys/samples-dev/keyRotation.ts

Purposely not generating the camera-ready samples as this has not GA'd yet

[KeyVault] - Add Key Rotation sample

---

eng/scripts/Language-Settings.ps1

Update Lanuage-Settings.ps1 to use exclusions for @azure/arm-keyvault and @azure/arm-sql

Update Lanuage-Settings.ps1 to use exclusions 

---

common/scripts/install-run.js
rush.json

for the fix to jszip security issue in older versions of rush: https://github.com/microsoft/rushstack/issues/2836

Bump rushVersion to 5.51.1

---

sdk/cosmosdb/cosmos/CHANGELOG.md

[Cosmos] 3.13.1 Adds date to changelog

---

sdk/cosmosdb/cosmos/CHANGELOG.md

remove empty changelog sections

[Cosmos] 3.13.1

---

sdk/keyvault/test-resources.json

In order to get live test deployments of MHSM healthy again

[KeyVault] - Update region for MHSM deployment

---

.github/CODEOWNERS

As discussed in https://github.com/Azure/azure-sdk-tools/issues/1099, usage of glob patterns does not work for our bot. So adding codeowner for each of the mgmt plane package. I copied the list from https://github.com/Azure/azure-sdk-for-js/blob/feature/v4/eng/pipelines/mgmt-ci.yml
This was done in the main branch in #17060
Repeating it in the feature/v4 branch as this branch is used to make updates to the older versions of the mgmt plane packages

Update CODEOWNERS for every mgmt package in feature/v4 branch

---

common/config/rush/pnpm-lock.yaml
common/tools/dev-tool/package.json
sdk/cosmosdb/cosmos/package.json

as part of the weekly rotation responsibility

Run `rush update --full` 2021-08-23

---

eng/pipelines/aggregate-reports.yml
eng/pipelines/weekly_automation.yml

New pipeline to run rush update full weekly

New pipeline to run weekly JS automation

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/src/constants.ts
sdk/communication/communication-chat/src/generated/src/chatApiClientContext.ts
sdk/communication/communication-chat/swagger/README.md

Update signaling client, release date, version for hotfix 1.1.0-beta.2

Update signaling client, release date, version

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/samples/javascript/README.md
sdk/communication/communication-chat/samples/typescript/README.md
sdk/communication/communication-chat/src/constants.ts
sdk/communication/communication-chat/src/generated/src/chatApiClientContext.ts
sdk/communication/communication-identity/samples/javascript/README.md
sdk/communication/communication-identity/samples/typescript/README.md
sdk/communication/communication-phone-numbers/samples/javascript/README.md
sdk/communication/communication-phone-numbers/samples/typescript/README.md
sdk/communication/communication-sms/samples/javascript/README.md
sdk/communication/communication-sms/samples/typescript/README.md

Fix broken link in samples readme caused by samples -> samples/v1 move

Hotfix/communication chat 1.0.1

---

sdk/core/core-paging/CHANGELOG.md
sdk/core/core-paging/package.json

Let's release today to get `getPagedAsyncIterator` out.

[core-paging] update changelog

---

sdk/schemaregistry/schema-registry-avro/review/schema-registry-avro.api.md
sdk/schemaregistry/schema-registry-avro/samples-dev/schemaRegistryAvroSample.ts
sdk/schemaregistry/schema-registry-avro/src/schemaRegistryAvroSerializer.ts

Updates the public surface to match what the crew agreed on.

[Schema Registry Avro] Align public API

---

sdk/storage/storage-blob/review/storage-blob.api.md
sdk/storage/storage-blob/src/ContainerClient.ts
sdk/storage/storage-blob/src/models.ts
sdk/storage/storage-blob/src/utils/utils.common.ts
sdk/storage/storage-blob/test/containerclient.spec.ts
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts
sdk/storage/storage-blob/test/node/blockblobclient.spec.ts
sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/Clients.ts
sdk/storage/storage-file-share/src/generatedModels.ts
sdk/storage/storage-file-share/src/models.ts
sdk/storage/storage-file-share/src/utils/utils.common.ts
sdk/storage/storage-file-share/test/node/fileclient.spec.ts

Resolve API review comments: Not expose ListFilesIncludeType which is only internal used.

Resolve API review comments: Not expose ListFilesIncludeType which is only internal used.

---

sdk/eventgrid/eventgrid/README.md

Fix issue #17370.
@ramya-rao-a , @jameszliao-msft , @lmazuel and @xirzec for notification.

Fix Event Grid Readme Issue

---

sdk/identity/identity/CHANGELOG.md
sdk/identity/identity/review/identity.api.md
sdk/identity/identity/src/credentials/chainedTokenCredential.ts
sdk/identity/identity/test/public/chainedTokenCredential.spec.ts

This PR reverts: https://github.com/Azure/azure-sdk-for-js/pull/16683
@g2vinay reported that the customer was ok with logging.
Feedback appreciated 👍

[Identity] Revert selected credential

---

sdk/schemaregistry/schema-registry-avro/test/schemaRegistryAvroSerializer.spec.ts
sdk/schemaregistry/schema-registry/review/schema-registry.api.md
sdk/schemaregistry/schema-registry/src/conversions.ts
sdk/schemaregistry/schema-registry/src/models.ts
sdk/schemaregistry/schema-registry/test/schemaRegistry.spec.ts

After a discussion with the service team today.

[Schema Registry] Trim down Schema Properties

---

sdk/monitor/monitor-query/README.md

Fix issue #17371.
@ramya-rao-a , @scottaddie , @joshfree and @KarishmaGhiya for notification.

Fix Monitor Query Readme Issue

---

documentation/Bundling.md
samples/Bundling/rollup/js/package.json
samples/Bundling/rollup/ts/package.json

[sample] - remove unnecessary OTel exports in doc

---

eng/scripts/cleanup-npm-next-tag.ps1

Missed correcting log level in previous PR.

Fix Log error when running cleanup tags

---

common/config/rush/pnpm-lock.yaml
sdk/attestation/attestation/package.json
sdk/core/core-amqp/package.json
sdk/eventhub/event-hubs/package.json
sdk/schemaregistry/schema-registry-avro/package.json
sdk/servicebus/service-bus/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/17088

upgrade buffer to v6

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
sdk/textanalytics/ai-text-analytics/package.json
sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md

https://github.com/Azure/azure-sdk-for-js/pull/17421#issuecomment-910923108 explains that we should start from the leaves when upgrading the api-extractor so this PR does so for text analytics.

[Text Analytics] Upgrade api-extractor

---

sdk/synapse/synapse-managed-private-endpoints/CHANGELOG.md
sdk/synapse/synapse-managed-private-endpoints/recordings/browsers/synapse_managed_private_endpoints/recording_should_list_endpoints.json
sdk/synapse/synapse-managed-private-endpoints/recordings/node/synapse_managed_private_endpoints/recording_should_list_endpoints.js
sdk/synapse/synapse-managed-private-endpoints/review/synapse-managed-private-endpoints.api.md
sdk/synapse/synapse-managed-private-endpoints/src/managedPrivateEndpointsClientContext.ts
sdk/synapse/synapse-managed-private-endpoints/src/models/index.ts
sdk/synapse/synapse-managed-private-endpoints/src/models/mappers.ts
sdk/synapse/synapse-managed-private-endpoints/src/models/parameters.ts
sdk/synapse/synapse-managed-private-endpoints/src/operations/managedPrivateEndpoints.ts
sdk/synapse/synapse-managed-private-endpoints/swagger/README.md

Re-generate with swagger `2020-12-01`

[Synapse] Re-generate Managed Private Endpoints

---

sdk/containerregistry/container-registry/CHANGELOG.md

[ContainerRegistry] prepare CHANGELOG for September release

---

eng/scripts/Language-Settings.ps1

Docs generation succeeded @10.0.1

Readd @azure/batch to automated onboarding 

---

sdk/identity/identity/CHANGELOG.md

We’ll be releasing Identity 2.0.0-beta.6 tomorrow 🎉

[Identity] 2.0.0-beta.6 release date

---

eng/scripts/Language-Settings.ps1

Remove @azure/schema-registry-avro from docs onboarding until issue is addressed https://github.com/Azure/azure-sdk-for-js/issues/17550

Remove @azure/schema-registry-avro from docs onboarding

---

sdk/test-utils/recorder/CHANGELOG.md
sdk/test-utils/recorder/package.json
sdk/test-utils/recorder/src/utils/index.ts
sdk/test-utils/recorder/test/utils.spec.ts

I know this is an edge case, but it’s also a performance improvement 😄
Fixes #14353

[Recorder v1] Fixed edge case double replacements

---

sdk/storage/storage-queue/CHANGELOG.md

Update changelog for storage-queue

Update changelog for storage-queue

---

sdk/identity/identity/CHANGELOG.md

Woops! 😝 It went over our heads 😱

[Identity] Removed duplicated changelog line

---

common/config/rush/common-versions.json
rush.json

This PR sets `ensureConsistentVersions` to false and removes the `allowedAlternativeVersions` section as per #17586

Set ensureConsistentVersions  to false

---

sdk/operationalinsights/loganalytics/README.md

To show how to use `tokenAudience` property.

Add client credential login sample

---

.github/CODEOWNERS

Updating codeowners for communication packages as per offline discussions
@LuChen-Microsoft, @miguhern, @petrsvihlik, @AriZavala2, @RoyHerrod,
Please note that you are now the code owner for one of the communication packages
@DominikMe @0rland0Wats0n @ankitarorabi
I have removed you from the code ownership. Let me know if you want to be added back.
cc @Juancamilor

Update codeowners for communication packages

---

sdk/monitor/monitor-query/README.md

Clean up for GA and align the README with the other 3 Tier 1 languages

Final consistency review of Monitor Query README

---

sdk/identity/identity/samples/AzureIdentityExamples.md

- change of "require" to "import"
- change the china cloud link

improvements to identity samples

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json

Update signaling package version for signaling package dependency update.

Update signaling package version

---

sdk/mixedreality/mixed-reality-authentication/CHANGELOG.md
sdk/mixedreality/mixed-reality-authentication/src/generated/mixedRealityStsRestClientContext.ts

- This change prepares the Azure Mixed Reality Authentication package for an initial beta release.

Prepare Mixed Reality Authentication for initial beta release

---

eng/scripts/Language-Settings.ps1

Connected issues have been closed, containerized builds succeed and produce outputs.

Readd @azure/arm-keyvault and @azure/arm-sql to docs

---

sdk/test-utils/perfstress/CHANGELOG.md
sdk/test-utils/perfstress/src/options.ts
sdk/test-utils/perfstress/src/utils.ts

Fixes https://github.com/Azure/azure-sdk-for-js/issues/17769

[Perf Framework] Fix 0 passed as an option

---

common/tools/eslint-plugin-azure-sdk/docs/rules/ts-doc-internal.md
eng/guardian-tools/policheck/PolicheckExclusions.xml
eng/pipelines/aggregate-reports.yml
sdk/appconfiguration/app-configuration/CHANGELOG.md
sdk/cognitiveservices/cognitiveservices-contentmoderator/src/operations/textModeration.ts
sdk/identity/identity/CHANGELOG.md
sdk/servicebus/service-bus/CHANGELOG.md

- Start compliance stage in the aggregate report pipeline.
- Add PoliCheck tool to the compliance stage.

Add PoliCheck tool to aggregate report pipeline

---

.github/CODEOWNERS
common/tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-engine-is-present.md
common/tools/eslint-plugin-azure-sdk/tests/rules/ts-package-json-engine-is-present.ts

The tests and docs need to be updated to match the current node support behavior that has been recently updated from v8 to v12.

[ESLint Plugin] Fix tests

---

sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClientContext.ts
sdk/datafactory/arm-datafactory/src/models/index.ts
sdk/datafactory/arm-datafactory/src/models/mappers.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/1995

datafactory-track1

---

.github/CODEOWNERS

Adding specific code owners for communication/azure-communication-phonenumbers and communication/azure-communication-sms.

Update codeowners for communication SMS & Phone Numbers

---

eng/pipelines/aggregate-reports.yml

- Add PoliCheck to CI run.
- Update policheck steps to use common template.

Add policheck to CI run, update policheck steps with common template

---

sdk/cosmosdb/cosmos/README.md

@anieljurek - Thanks! PR as suggested. 
related "https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1286#issuecomment-931566160"

Typo "Typescript"→"TypeScript"

---

sdk/schemaregistry/schema-registry/README.md

[Schema Registry] Edit readme

---

sdk/servicebus/service-bus/CHANGELOG.md

[Service Bus] Release 7.3.1-beta.1 

---

sdk/synapse/synapse-spark/CHANGELOG.md
sdk/synapse/synapse-spark/review/synapse-spark.api.md
sdk/synapse/synapse-spark/src/models/index.ts
sdk/synapse/synapse-spark/src/operations/sparkBatch.ts
sdk/synapse/synapse-spark/src/operations/sparkSessionOperations.ts
sdk/synapse/synapse-spark/src/operationsInterfaces/sparkSessionOperations.ts
sdk/synapse/synapse-spark/swagger/README.md

Regenerate with latest release tag package-spark-2020-12-01. To pickup latest changes in the service definition and autorest typescript generator.

[Synapse Spark] Regenerate with latest release tag package-spark-2020-12-01

---

.github/CODEOWNERS

Add entry for video-analyzer-edge in code owners file so that future PRs get labelled & assigned

Add entry for video-analyzer-edge in code owners file

---

sdk/identity/identity/samples/AzureIdentityExamples.md

Nikitha Udaykumar has been helping me test the OnBehalfOfCredential, and through her feedback, I am making this PR to improve our related samples.
Feedback appreciated 🙏

[Identity] OBO sample improvement

---

sdk/web-pubsub/web-pubsub/review/web-pubsub.api.md
sdk/web-pubsub/web-pubsub/src/groupClient.ts

Fix https://github.com/Azure/azure-webpubsub/issues/284

Fix group interface missing closeAllConnections issue

---

sdk/textanalytics/ai-text-analytics/CHANGELOG.md

TA is being released today to align with Ignite.

[Text Analytics] Prepare v5.2.0-beta.2 release

---

sdk/core/core-http/CHANGELOG.md

Update date and bug fix entries.

[core-http] prepare CHANGELOG for 2021 November release

---

eng/scripts/Language-Settings.ps1
eng/tools/versioning/set-version.js

Required for https://github.com/Azure/azure-sdk-tools/issues/1542

Add ReplaceLatestEntryTitle parameter for updating changelog

---

sdk/web-pubsub/web-pubsub-express/src/cloudEventsDispatcher.ts
sdk/web-pubsub/web-pubsub-express/test/validate.spec.ts

Fix https://github.com/Azure/azure-webpubsub/issues/258

Fix issue that the preflight response should hide server detail

---

sdk/core/core-client-rest/CHANGELOG.md

Update changelog for November Release

[core-client-rest] Prepare beta.8 release

---

sdk/appconfiguration/app-configuration/sample-react/package.json
sdk/identity/identity-cache-persistence/package.json
sdk/identity/identity-vscode/package.json
sdk/keyvault/keyvault-admin/package.json
sdk/keyvault/keyvault-certificates/package.json
sdk/keyvault/keyvault-certificates/samples/v4/javascript/package.json
sdk/keyvault/keyvault-certificates/samples/v4/typescript/package.json
sdk/keyvault/keyvault-keys/package.json
sdk/keyvault/keyvault-keys/samples/v4/typescript/package.json
sdk/keyvault/keyvault-secrets/package.json
sdk/keyvault/keyvault-secrets/samples/v4/javascript/package.json
sdk/keyvault/keyvault-secrets/samples/v4/typescript/package.json
sdk/monitor/monitor-query/package.json
sdk/monitor/monitor-query/samples/v1/javascript/package.json
sdk/monitor/monitor-query/samples/v1/typescript/package.json
sdk/monitor/perf-tests/monitor-query/package.json
sdk/network/arm-network/package.json
sdk/remoterendering/mixed-reality-remote-rendering/package.json
sdk/web-pubsub/web-pubsub/package.json

Fixes https://github.com/Azure/azure-sdk-for-js/issues/14581

Identity v2 update - remaining packages

---

common/config/rush/pnpm-lock.yaml
sdk/storage/perf-tests/storage-blob/package.json
sdk/storage/perf-tests/storage-file-share/package.json
sdk/storage/storage-blob/CHANGELOG.md
sdk/storage/storage-file-datalake/CHANGELOG.md
sdk/storage/storage-file-share/CHANGELOG.md
sdk/storage/storage-file-share/package.json
sdk/storage/storage-file-share/src/AccountSASSignatureValues.ts
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/utils/constants.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-queue/CHANGELOG.md
sdk/storage/storage-queue/package.json
sdk/storage/storage-queue/recordings/node/shared_access_signature_sas_generation_nodejs_only/recording_queueserviceclientgenerateaccountsasurl_with_previous_version_should_work.js
sdk/storage/storage-queue/src/AccountSASSignatureValues.ts
sdk/storage/storage-queue/src/generated/src/models/parameters.ts
sdk/storage/storage-queue/src/generated/src/storageClientContext.ts
sdk/storage/storage-queue/src/utils/constants.ts
sdk/storage/storage-queue/swagger/README.md
sdk/storage/storage-queue/test/node/sas.spec.ts

Prepare for STG79 features preview release.

Prepare for STG79 features preview release.

---

sdk/search/search-documents/CHANGELOG.md
sdk/search/search-documents/review/search-documents.api.md
sdk/search/search-documents/src/generated/data/models/index.ts
sdk/search/search-documents/src/generated/data/models/mappers.ts
sdk/search/search-documents/src/generated/data/models/parameters.ts
sdk/search/search-documents/src/generated/data/operations/documents.ts
sdk/search/search-documents/src/generated/data/searchClientContext.ts
sdk/search/search-documents/src/generated/service/models/index.ts
sdk/search/search-documents/src/generated/service/models/mappers.ts
sdk/search/search-documents/src/index.ts
sdk/search/search-documents/src/indexModels.ts
sdk/search/search-documents/src/serviceModels.ts
sdk/search/search-documents/src/serviceUtils.ts
sdk/search/search-documents/swagger/Data.md
sdk/search/search-documents/swagger/Service.md

Some new changes have come in for the search-documents SDK today and wanted to be included in this November release. 
@xirzec Please review and approve. Thanks

Release 11.3.0-beta.5 of search-documents SDK

---

sdk/tables/data-tables/CHANGELOG.md
sdk/tables/data-tables/recordings/browsers/batch_operations_sasconnectionstring/recording_should_support_empty_partition_and_row_keys.json
sdk/tables/data-tables/recordings/browsers/batch_operations_tokencredential/recording_should_support_empty_partition_and_row_keys.json
sdk/tables/data-tables/recordings/browsers/tableclient_sasconnectionstring_createentity_getentity_and_delete/recording_should_createentity_empty_partition_and_row_keys.json
sdk/tables/data-tables/recordings/browsers/tableclient_tokencredential_createentity_getentity_and_delete/recording_should_createentity_empty_partition_and_row_keys.json
sdk/tables/data-tables/recordings/node/batch_operations_sasconnectionstring/recording_should_support_empty_partition_and_row_keys.js
sdk/tables/data-tables/recordings/node/batch_operations_tokencredential/recording_should_support_empty_partition_and_row_keys.js
sdk/tables/data-tables/recordings/node/tableclient_sasconnectionstring_createentity_getentity_and_delete/recording_should_createentity_empty_partition_and_row_keys.js
sdk/tables/data-tables/recordings/node/tableclient_tokencredential_createentity_getentity_and_delete/recording_should_createentity_empty_partition_and_row_keys.js
sdk/tables/data-tables/src/TableClient.ts
sdk/tables/data-tables/test/public/tableclient.spec.ts
sdk/tables/data-tables/test/public/transaction.spec.ts

Empty string are valid values for partitionKey and rowKey. Remove checks form update and upsert methods.

[Tabes] Allow empty strings as partition and row keys

---

sdk/servicebus/service-bus/CHANGELOG.md
sdk/servicebus/service-bus/package.json
sdk/servicebus/service-bus/src/util/constants.ts

[Service Bus] Releasing 7.4.0

---

sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md

I neglected to add a changelog entry, so this PR fixes that.

[ai-form-recognizer] Updated CHANGELOG for release

---

sdk/web-pubsub/web-pubsub/CHANGELOG.md

This is to make the release CI pipeline happy.

[Web-Pubsub] Update WPS changelog for beta 4.

---

sdk/schemaregistry/schema-registry/CHANGELOG.md

Fixes date format in changelog entry.

[Schema Registry] Fix release date

---

sdk/schemaregistry/schema-registry-avro/CHANGELOG.md

[Schema Registry Avro] Prepare release

---

sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/recordings/browsers/schemaregistryclient/recording_allows_schema_names_with_dots_in_them.json
sdk/schemaregistry/schema-registry/recordings/node/schemaregistryclient/recording_allows_schema_names_with_dots_in_them.js
sdk/schemaregistry/schema-registry/samples-dev/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/generated/models/index.ts
sdk/schemaregistry/schema-registry/src/generated/models/mappers.ts
sdk/schemaregistry/schema-registry/src/generated/models/parameters.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schema.ts
sdk/schemaregistry/schema-registry/src/generated/operations/schemaGroupsOperations.ts
sdk/schemaregistry/schema-registry/src/generated/operationsInterfaces/schema.ts
sdk/schemaregistry/schema-registry/swagger/README.md
sdk/schemaregistry/schema-registry/test/public/schemaRegistry.spec.ts

The swagger parameter pattern for schema names was not correct after discussion with @hmlam so this PR regenerates the client from the fixed swagger in https://github.com/Azure/azure-rest-api-specs/pull/16738 and adds a test case.

[Schema Registry] Fix schema name validation

---

sdk/communication/communication-common/src/credential/communicationAccessKeyCredentialPolicy.ts

For some reason, these changes fell from this [PR](https://github.com/Azure/azure-sdk-for-js/pull/18147/files#diff-d55778891162a78b6115425acc93e87f46b6d3396a0418d523fb0b44f8621127)
Re-adding them here.

ReAdding changes for common hmac policy

---

sdk/monitor/monitor-query/README.md

- Fixes https://github.com/Azure/azure-sdk-for-js/issues/18388

update readme for monitor query with sample fix

---

eng/scripts/Language-Settings.ps1

Add better logging to GetExistingPackageVersions

---

sdk/network/arm-network/package.json
sdk/network/arm-network/src/models/index.ts
sdk/network/arm-network/src/models/mappers.ts
sdk/network/arm-network/src/networkManagementClientContext.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2202

network-track1

---

sdk/schemaregistry/schema-registry-avro/package.json
sdk/schemaregistry/schema-registry-avro/samples/v1/javascript/package.json
sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/package.json
sdk/schemaregistry/schema-registry/CHANGELOG.md
sdk/schemaregistry/schema-registry/package.json
sdk/schemaregistry/schema-registry/samples/v1/javascript/schemaRegistrySample.js
sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts
sdk/schemaregistry/schema-registry/src/generated/generatedSchemaRegistryClientContext.ts
sdk/schemaregistry/schema-registry/swagger/README.md

[Schema Registry] Post-release stuff

---

common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts

[dev-tool] drop node10 support in samples run

---

sdk/test-utils/perf/CHANGELOG.md
sdk/test-utils/perf/src/options.ts
sdk/test-utils/perf/src/tests.ts

[Perf Framework] Throw on invalid argument

---

sdk/test-utils/perf/CHANGELOG.md
sdk/test-utils/perf/src/options.ts
sdk/test-utils/perf/test/options.spec.ts

[Perf Framework] Respect option longName when provided

---

sdk/formrecognizer/ai-form-recognizer/tests.yml

The preview API is having some transient issues in production regions.

[ai-form-recognizer] Update test region.

---

eng/pipelines/templates/steps/run-eslint.yml

Run unit tests in ES lint plugin as part of PR pipeline for ES lint.

Run unit tests in eslint plugin

---

sdk/containerservice/arm-containerservice/package.json
sdk/containerservice/arm-containerservice/src/containerServiceClientContext.ts
sdk/containerservice/arm-containerservice/src/models/agentPoolsMappers.ts
sdk/containerservice/arm-containerservice/src/models/index.ts
sdk/containerservice/arm-containerservice/src/models/mappers.ts
sdk/containerservice/arm-containerservice/src/operations/agentPools.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2246

containerservice-track1

---

sdk/confluent/arm-confluent/README.md
sdk/confluent/arm-confluent/package.json
sdk/confluent/arm-confluent/src/confluentManagementClient.ts
sdk/confluent/arm-confluent/src/confluentManagementClientContext.ts
sdk/confluent/arm-confluent/src/models/index.ts
sdk/confluent/arm-confluent/src/models/parameters.ts
sdk/confluent/arm-confluent/src/operations/marketplaceAgreements.ts
sdk/confluent/arm-confluent/src/operations/validations.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2214

confluent-track1

---

sdk/core/core-client/src/base64.ts

Follow up after: https://github.com/Azure/azure-sdk-for-js/pull/17315/files/912ccd63b585ff935ccd1da1121da32503dca47d#r758714263

[core-client] Added internal flag on decodeStringToString

---

sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_health/recording_all_documents_have_errors.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/aad_textanalyticsclient_lros_health/recording_big_document_causes_a_warning.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_lros_health/recording_all_documents_have_errors.json
sdk/textanalytics/ai-text-analytics/recordings/browsers/apikey_textanalyticsclient_lros_health/recording_big_document_causes_a_warning.json
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_health/recording_all_documents_have_errors.js
sdk/textanalytics/ai-text-analytics/recordings/node/aad_textanalyticsclient_lros_health/recording_big_document_causes_a_warning.js
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_lros_health/recording_all_documents_have_errors.js
sdk/textanalytics/ai-text-analytics/recordings/node/apikey_textanalyticsclient_lros_health/recording_big_document_causes_a_warning.js
sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts

The service started recently to accept big documents in the health feature so this PR updates the tests accordingly.

[Text Analytics] Update tests

---

sdk/textanalytics/ai-text-analytics/src/azureKeyCredentialPolicy.ts
sdk/textanalytics/ai-text-analytics/src/textAnalyticsResult.ts
sdk/textanalytics/ai-text-analytics/src/util.ts
sdk/textanalytics/ai-text-analytics/test/public/utils/recordedClient.ts

With the aid of [ts-prune](https://www.npmjs.com/package/ts-prune).

[Text Analytics] Cleaning house

---

sdk/textanalytics/ai-text-analytics/README.md

Fix issue #18882
@ramya-rao-a , @meeraharidasa , @mayurid and @deyaaeldeen for notification.

Fix Azure Text Analytics Readme Issue

---

sdk/cosmosdb/cosmos/package.json
sdk/cosmosdb/cosmos/samples-dev/ChangeFeed.ts
sdk/cosmosdb/cosmos/samples-dev/ItemManagement.ts
sdk/cosmosdb/cosmos/src/CosmosClientOptions.ts
sdk/cosmosdb/cosmos/src/common/constants.ts
sdk/cosmosdb/cosmos/test/public/functional/client.spec.ts
sdk/cosmosdb/cosmos/writeSDKVersion.js

- fix failed integration tests ( mainly because of the constant "REPLACE_SDK_VERSION")

fix integration tests - v3.15.0

---

sdk/servicebus/service-bus/test/stress/app/src/serviceBusStressTester.ts

Attempting to fix the build failure at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1222959&view=logs&j=d5b9c885-e689-5427-4411-f21620650b06&t=338eaa54-a319-574f-a78b-a661012b9e81

[Stress Tests] error as Error - Fix build failure

---

sdk/storage/storage-file-share/recordings/browsers/fileserviceclient_premium/recording_premium_share_getproperties.json
sdk/storage/storage-file-share/recordings/node/fileserviceclient_premium/recording_premium_share_getproperties.js
sdk/storage/storage-file-share/review/storage-file-share.api.md
sdk/storage/storage-file-share/src/generated/src/models/index.ts
sdk/storage/storage-file-share/src/generated/src/models/mappers.ts
sdk/storage/storage-file-share/src/generated/src/models/parameters.ts
sdk/storage/storage-file-share/src/generated/src/storageClientContext.ts
sdk/storage/storage-file-share/src/generatedModels.ts
sdk/storage/storage-file-share/swagger/README.md
sdk/storage/storage-file-share/test/fileserviceclient.spec.ts

Premium File - Updated for new bandwidth limits

Premium File - Updated for new bandwidth limits

---

sdk/web-pubsub/web-pubsub/README.md

Fix https://github.com/Azure/azure-sdk-for-js/issues/18881

Fix readme issues

---

sdk/communication/communication-sms/README.md

- Fix broken links in aggregate reports pipeline.

Fixed broken link

---

sdk/cosmosdb/cosmos/samples-dev/Bulk.ts
sdk/cosmosdb/cosmos/samples-dev/ItemManagement.ts
sdk/cosmosdb/cosmos/samples/v3/javascript/Bulk.js
sdk/cosmosdb/cosmos/samples/v3/javascript/ItemManagement.js
sdk/cosmosdb/cosmos/samples/v3/typescript/src/Bulk.ts
sdk/cosmosdb/cosmos/samples/v3/typescript/src/ItemManagement.ts

- This PR adds some sample code for JSON Patch.
- The sample code is added in Item Management part and Bulk part

Samples: Adds JSON Patch API to samples

---

sdk/core/core-client/review/core-client.api.md
sdk/core/core-client/src/interfaces.ts
sdk/core/core-http/src/serializer.ts

After updating the undocumented entries on core-http on #18755 , @xirzec spotted that core-client was also missing some comments.

[core-client] Aligning the serializer comments based on core-http

---

sdk/keyvault/keyvault-certificates/samples-dev/helloWorld.ts
sdk/keyvault/keyvault-certificates/samples/v4/javascript/helloWorld.js
sdk/keyvault/keyvault-certificates/samples/v4/typescript/src/helloWorld.ts

Trying to fix build failures with this new PR

Key Vault Certificates - hello world sample

---

dataplane.code-workspace

Add code spell checker to recommended extensions

---

sdk/metricsadvisor/ai-metrics-advisor/README.md

Corrected couple of places that looked a bit odd to me.

Minor corrections in metricadvisor readme.

---

sdk/core/core-amqp/src/ConnectionContextBase.ts
sdk/core/core-amqp/src/auth/tokenProvider.ts
sdk/core/core-amqp/src/cbs.ts
sdk/core/core-amqp/src/connectionConfig/connectionConfig.ts
sdk/core/core-amqp/src/errors.ts
sdk/core/core-amqp/src/requestResponseLink.ts
sdk/core/core-amqp/src/retry.ts
sdk/core/core-amqp/src/util/utils.ts
sdk/core/core-amqp/test/cbs.spec.ts
sdk/core/core-amqp/test/config.spec.ts
sdk/core/core-amqp/test/errors.spec.ts
sdk/core/core-amqp/test/lock.spec.ts
sdk/core/core-amqp/test/message.spec.ts
sdk/core/core-amqp/test/requestResponse.spec.ts
sdk/core/core-amqp/test/retry.spec.ts
sdk/core/core-amqp/test/tokenProvider.spec.ts
sdk/core/core-amqp/test/utils/createConnectionStub.ts

This PR is working in conjunction with other PRs to fix individual sections of the azure codebase with respect to the new ```sort-imports``` rule, as indicated in #9252 
In this PR, I have fixed all files under ```sdk/core/core-amqp```.

[sort-imports] update ```core-amqp``` with respect to ```sort-imports``` rule

---

sdk/core/core-auth/test/index.spec.ts

In this PR, I have fixed all files under ```sdk/core/core-auth```.

[sort-imports] update ```core-auth``` with respect to ```sort-imports``` rule

---

documentation/next-generation-quickstart.md

Fix a typo in next-generation-quickstart.md

---

.github/CODEOWNERS

/cc @lilyjma @ramya-rao-a 
This creates the source of truth for the bot configuration in this file.

Update the file with the bot configuration

---

eng/pipelines/templates/steps/analyze.yml

- Scope Verification of readmes to the service being run.

Scope Verify Readme run to the ServiceDirectory for the pipeline being run.

---

sdk/mixedreality/mixed-reality-authentication/src/mixedRealityStsClient.ts
sdk/mixedreality/mixed-reality-authentication/src/models/auth.ts
sdk/mixedreality/mixed-reality-authentication/test/mixedRealityStsClient.spec.ts
sdk/mixedreality/mixed-reality-authentication/test/utils/recordedClient.ts

In this PR, I have fixed all files under ```sdk/mixedreality/mixed-reality-authentication```.

[sort-imports] update ```mixed-reality-authentication``` with respect to ```sort-imports``` rule

---

common/config/rush/pnpm-lock.yaml
rush.json

As concluded in #16912, removing the `@azure/event-processor-host` from rush.json

Remove event-processor-host from rush.json

---

sdk/core/abort-controller/README.md
sdk/identity/identity/samples/AzureIdentityExamples.md

Update main based on the `master` branch accidentally created.
The history in `master` goes to August 20th and then has a sudden break until two commits, one in October 20th, and another one on December 6th. I’m assuming commits before October 20th are not needed, since otherwise I would have expected us to need this update a lot earlier.
This PR includes changes from:
- https://github.com/Azure/azure-sdk-for-js/commit/d4428c6fa2419e8df0d893768c9504433ec82edc
- https://github.com/Azure/azure-sdk-for-js/commit/b063605642fbf431661660ae248639f203f82650

Updating main based on master

---

sdk/appconfiguration/app-configuration/CHANGELOG.md

To release 1.3.1 version of `@azure/app-configuration`
Helps resolving #18957

[App Config] Changelog for 1.3.1

---

common/config/rush/pnpm-lock.yaml
sdk/identity/identity-cache-persistence/CHANGELOG.md
sdk/identity/identity-cache-persistence/package.json

[identity-cache-persistence] Upgrading MSAL extensions

---

.github/CODEOWNERS

Since he has been working on perf and recorder frameworks. 🔥

Update CODEOWNERS - Add Timo for test-utils

---

common/config/rush/pnpm-lock.yaml
sdk/communication/communication-chat/CHANGELOG.md
sdk/communication/communication-chat/package.json
sdk/communication/communication-chat/review/communication-chat.api.md
sdk/communication/communication-chat/src/chatClient.ts
sdk/communication/communication-chat/src/models/events.ts

expose API to subscribe to realTimeNotificationConnected and realTimeNotificationDisconnected event

Expose API to subscribe to trouter status event

---

common/config/rush/pnpm-lock.yaml
sdk/storage/storage-file-datalake/package.json

Upgrade to execa 6.0.0 in storage-file-datalake package.

Upgrade to execa 6.0.0 in storage-file-datalake package.

---

common/config/rush/pnpm-lock.yaml
sdk/mixedreality/mixed-reality-authentication/karma.conf.js
sdk/mixedreality/mixed-reality-authentication/package.json
sdk/mixedreality/mixed-reality-authentication/src/mixedRealityStsClient.ts
sdk/mixedreality/mixed-reality-authentication/src/models/auth.ts
sdk/mixedreality/mixed-reality-authentication/src/models/mappers.ts
sdk/mixedreality/mixed-reality-authentication/src/tracing.ts
sdk/mixedreality/mixed-reality-authentication/test/mixedRealityStsClient.spec.ts
sdk/mixedreality/mixed-reality-authentication/test/utils/recordedClient.ts

Solves: https://github.com/Azure/azure-sdk-for-js/issues/9329 for packages under `sdk/mixedreality`.

Update prettier dev-dependency to v2.5.1 in Mixed Reality

---

sdk/storage/MigrationGuide.md

Add a summary migration guide document to link to detailed migration guides for each separating storage SDKs.

[storage]Add a summary migrationguide for storage sdks.

---

sdk/core/core-http/CHANGELOG.md

- update release date
- clean up headers

[core-http] prepare CHANGELOG for 2020 Jan release

---

sdk/core/core-client/README.md

fixes #19732 
@ramya-rao-a , @joshfree and @jeremymeng for notification.

Fix Azure Core Client Readme Issue

---

sdk/identity/identity/migration-v1-v2.md

- Fixes - https://github.com/Azure/azure-sdk-for-js/issues/19020

update the sub-link on migration-guide

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

As discussed, I have created the PR Template to ensure that the PRs have enough details that will help the reviewers to gain more knowledge about the issue and our project.
@ramya-rao-a Please review and approve the template

Created the PR Template

---

sdk/compute/arm-compute/CHANGELOG.md
sdk/compute/arm-compute/LICENSE
sdk/compute/arm-compute/_meta.json
sdk/compute/arm-compute/package.json
sdk/compute/arm-compute/review/arm-compute.api.md
sdk/compute/arm-compute/src/computeManagementClient.ts
sdk/compute/arm-compute/src/models/index.ts
sdk/compute/arm-compute/src/models/mappers.ts
sdk/compute/arm-compute/src/models/parameters.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2337

compute-track2

---

sdk/metricsadvisor/ai-metrics-advisor/README.md

- Fixes https://github.com/Azure/azure-sdk-for-js/issues/19016 and https://github.com/Azure/azure-sdk-for-js/issues/19017

[Metrics Advisor] update the readme for more clarity

---

sdk/datafactory/arm-datafactory/CHANGELOG.md
sdk/datafactory/arm-datafactory/LICENSE
sdk/datafactory/arm-datafactory/_meta.json
sdk/datafactory/arm-datafactory/package.json
sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
sdk/datafactory/arm-datafactory/src/models/index.ts
sdk/datafactory/arm-datafactory/src/models/mappers.ts

release for issue: https://github.com/Azure/sdk-release-request/issues/2344

datafactory-track2

---

eng/pipelines/templates/steps/build.yml
eng/pipelines/templates/variables/globals.yml

Related to Azure/azure-sdk-tools#2273

Generate Manifests alongside build artifacts

---

eng/pipelines/templates/steps/build.yml

Splitting out the artifact to make it its own thing.

Manifest Generation Update

---

sdk/cosmosdb/cosmos/CHANGELOG.md

Update Cosmos CHANGELOG.md 

---

.github/CODEOWNERS
sdk/instrumentation/ci.yml
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/.eslintrc.json
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumentation.browser.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumentation.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/instrumenter.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/spanWrapper.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/instrumenter.spec.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/spanWrapper.spec.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/util/testSpan.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/test/public/util/testTracer.ts
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/tests.yml

- Skip samples in CI
- Add CODEOWNERS entry and label
- Update the artifact name to fix CI
- Fix lint errors
We will be adding samples in #19854, but until we are able to we should disable
them in CI.

[Instrumentation] - Add CODEOWNERS and filter samples from pipeline

---

sdk/core/core-tracing/package.json
sdk/core/core-tracing/samples-dev/basicTracing.ts
sdk/core/core-tracing/samples/v1/javascript/README.md
sdk/core/core-tracing/samples/v1/javascript/basicTracing.js
sdk/core/core-tracing/samples/v1/javascript/package.json
sdk/core/core-tracing/samples/v1/typescript/README.md
sdk/core/core-tracing/samples/v1/typescript/package.json
sdk/core/core-tracing/samples/v1/typescript/src/basicTracing.ts
sdk/core/core-tracing/samples/v1/typescript/tsconfig.json
sdk/core/core-tracing/tsconfig.json

Resolves #19738
When upgrading to the new @azure/core-tracing APIs, developers will need a
sample demonstrating how to add tracing to their client libraries.
In this PR, we're adding a simple sample demonstrating the most common scenarios
using a fake client.

[core] - Add tracing sample

---

sdk/remoterendering/mixed-reality-remote-rendering/package.json
sdk/remoterendering/mixed-reality-remote-rendering/src/constants.ts
sdk/remoterendering/mixed-reality-remote-rendering/src/generated/remoteRenderingRestClientContext.ts
sdk/remoterendering/mixed-reality-remote-rendering/swagger/README.md

`@azure/mixed-reality-remote-rendering`
None.
`@azure/mixed-reality-remote-rendering` depends on `@azure/mixed-reality-remote-rendering`. Updated the dependency version to the latest: `1.0.0-beta.2`.
No, this PR is only for a small change in 
**Provide a list of …

Update @azure/mixed-reality-authentication version dependency

---

sdk/servicebus/perf-tests/service-bus-track-1/README.md
sdk/servicebus/perf-tests/service-bus-track-1/test/index.spec.ts
sdk/servicebus/perf-tests/service-bus-track-1/test/receiveBatch.spec.ts
sdk/servicebus/perf-tests/service-bus-track-1/test/sbBase.spec.ts
sdk/servicebus/perf-tests/service-bus-track-1/test/sendBatch.spec.ts
sdk/servicebus/perf-tests/service-bus/README.md
sdk/servicebus/perf-tests/service-bus/test/receiveBatch.spec.ts

- `@azure-tests/perf-service-bus-track-1`
- #18982
Add a test for receiveBatch using the track 1 service bus SDK in line with what we already have for the track 2 SDK
**Provide a list of related PRs** _(if any)_
- #18811

[Perf tests/service-bus-track-1] Add batch receive perf tests for Service Bus Track 1

---

.github/CODEOWNERS

Move ownership of remoterendering from Malcolm Tyrell to Florian Born due to team restructuring
**Command used to generate this PR:**_(Applicable only to SDK release request PRs)_

Move ownership of remoterendering to Florian Born

---

sdk/communication/communication-chat/package.json

**Command used to generate this PR:**_(Applicable only to SDK release request PRs)_

Not expose src and tests folder in types

---

CONTRIBUTING.md

None, only the CONTRIBUTING.md file at root level.
None, this came out as part of a discussion I had with @ramya-rao-a, where we concluded what is written in the next point.
After going through the core libraries documentation and the differences between core V1 and V2, I concluded that this information is helpful for new team members and any other person who wants to contribute to the repo. In this PR, a mention about the existence of the core libraries and a reference to learn more about them is included in the contributing guide.
**If there are more than one possible design, why …

Add core client libraries info in the contributing guide

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md

Updated PR Template
@maorleger Please review and approve.

Updated PR Template

---

.github/CODEOWNERS

[AnomalyDetector] Add Code Owners

---

sdk/storage/storage-queue/package.json

[storage]Enable storage-queue sample execution

[storage]Enable storage-queue sample execution

---

sdk/formrecognizer/test-resources.json

@azure/ai-form-recognizer
https://github.com/Azure/azure-sdk-for-js/issues/17577
Originally, @benbp created an issue to ensure that the `@azure/search-documents` tests has to be updated to handle sovereign cloud endpoints dynamically. This was completed in https://github.com/Azure/azure-sdk-for-js/pull/20058. In this PR @ramya-rao-a has [instructed](https://github.com/Azure/azure-sdk-for-js/pull/20058#issuecomment-1021667276) to do similar changes for Form Recognizer package. This PR has been created to address that.
The Code changes are straightforward and does not involve any complicated design.
No. The code change is to update the JSON file related to tests. No separate tests are required.
1. https://github.com/Azure/azure-sdk-for-js/issues/17577
2. …

[@azure/ai-form-recognizer] Update EndPoints in Form Recognizer

---

sdk/metricsadvisor/ai-metrics-advisor/README.md

@azure/ai-metrics-advisor
Fixes #19026
Added prerequisites for additional details about data sources and their requirements to be used by Metrics advisor and how to onboard them to data feeds and complete the data ingestion.

[Metrics Advisor] update the instructions to make sources more clear for a user

---

sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/README.md
sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md

[opentelemetry] - Update CHANGELOG for release

---

samples/cors/ts/README.md

N/A
N/A
Updates link to feedback.azure.com for the feature request to have the KeyVault API support CORS.
N/A
N/A, documentation

Update feedback link in CORS sample

---

sdk/core/core-client/CHANGELOG.md
sdk/core/core-client/package.json
sdk/core/core-rest-pipeline/CHANGELOG.md

Changelog updates and fixing a min-version issue with the new core-client.

[core-client] [core-rest-pipeline] Prepare core packages for February Release

---

rush.json
sdk/digitaltwins/dtdl-parser/CHANGELOG.md

Update changelog for February release.

[@azure/dtdl-parser] Update changelog for release

---

sdk/core/core-amqp/CHANGELOG.md
sdk/core/core-xml/CHANGELOG.md

@azure/core-amqp, @azure/core-xml

[core-amqp,core-xml] update CHANGELOG for Feb 2022 releases

---

eng/scripts/check-external-dependency.ps1

Updated issue description for automatically filed issues for required external package upgrade to include instruction on how to upgrade package dependency.
Added additional label to when current package version is deprecated.

Include instructions to upgrade package dependency in auto filed issues

---

sdk/test-utils/recorder/MIGRATION.md

Came as part of the feedback while working on https://github.com/Azure/azure-sdk-for-js/issues/19859 - migration tasks

[Recorder] Migration guide enhancements

---

eng/common/scripts/Helpers/Metadata-Helpers.ps1
eng/common/scripts/Update-DocsMsMetadata.ps1

Reverts Azure/azure-sdk-for-js#20198

Revert "Sync eng/common directory with azure-sdk-tools for PR 2673"

---

sdk/keyvault/keyvault-secrets/samples-dev/helloWorld.ts
sdk/keyvault/keyvault-secrets/samples/v4/javascript/helloWorld.js
sdk/keyvault/keyvault-secrets/samples/v4/typescript/src/helloWorld.ts

Key Vault secret - comment

---

sdk/identity/identity/CHANGELOG.md

I’m thinking on releasing v2.0.2 of Identity today, early enough before we begin to add beta features.
Here’s the changelog: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/CHANGELOG.md#202-unreleased
Feedback appreciated 🙂

[Identity] Release date for 2.0.2

---

sdk/identity/identity/CHANGELOG.md

[Identity] I forgot to remove this empty section from the changelog
So I couldn’t release it 😅
Removing so I can release it 🙂

[Identity] I forgot to remove this empty section from the changelog

---

.github/CODEOWNERS

Adds @HarshaNalluru to the code owners for Form Recognizer.

[ai-form-recognizer] Update CODEOWNERS

---

sdk/eventhub/event-hubs/src/eventHubProducerClient.ts

`@azure/event-hub`
https://github.com/Azure/azure-sdk-for-js/issues/14400
Improving documentation around batching as mentioned in #14400
We can further update the code snippet used to showcase batching, but I am trying to go with minimal changes in this PR for now
No. Just doc changes

Call out caveats when using sendBatch() & createBatch()

---

sdk/communication/communication-chat/CHANGELOG.md

Update changelog for release

---

sdk/test-utils/recorder/MIGRATION.md

Remove unneeded dev dependencies in package.json

[Recorder] Minor update to migration guide

---

sdk/tables/data-tables/samples-dev/generateTableSAS.ts
sdk/tables/data-tables/samples/v12/javascript/generateTableSAS.js
sdk/tables/data-tables/samples/v12/typescript/src/generateTableSAS.ts
sdk/tables/data-tables/samples/v13/javascript/generateTableSAS.js
sdk/tables/data-tables/samples/v13/typescript/src/generateTableSAS.ts

fixes #20078
@ramya-rao-a , @mario-guerra @annatisch and @joheredi for notification.

Fix Azure Tables Sample Issue

---

sdk/cognitiveservices/cognitiveservices-formrecognizer/README.md
sdk/cognitiveservices/cognitiveservices-textanalytics/README.md

Readme files for `@azure/cognitiveservices-formrecognizer` and `@azure/cognitiveservices-textanalytics`
None
Folks landing on the readme pages for older SDKs should be pointed to the new ones
We also need to deprecate the package which will be done later
N/A
None
N/A

Add deprecation note for T1 formrecognizer, textanalytics

---

.github/CODEOWNERS
sdk/keyvault/ci.mgmt.yml
sdk/keyvault/ci.yml

We are going to separate the pipeline of dataplane and mgmt, and this PR is a POC.

separate pipeline for keyvault

---

sdk/storage/storage-file-datalake/samples-dev/dataLakeServiceClient.ts

[storage-file-datalake]Fix sample running failure for datalake package.

[storage-file-datalake]Fix sample running failure for datalake package.

---

sdk/eventhub/event-hubs/src/eventHubBufferedProducerClient.ts
sdk/eventhub/event-hubs/test/internal/bufferedProducerUnitTests.spec.ts

#18671 
Add a background loop that check and update partition ids periodically.

[EventHubs] periodically update partition ids 

---

sdk/test-utils/recorder/MIGRATION.md

Some more updates to improve experience

[Recorder] Update MIGRATION.md

---

sdk/batch/batch/CHANGELOG.md

NA
https://msazure.visualstudio.com/AzureBatch/_workitems/edit/12945448/
As part of the JS Batch Data Plane SDK release, I noticed there was no CHANGELOG file.
NA
NA. No new functionality was included nor modified.

Added CHANGELOG to Azure Batch SDK data plane directory

---

sdk/storage/storage-blob/CHANGELOG.md

[storage]Update changelog

---

sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_appendblockfromurl__destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_appendblockfromurl__source_bear_token_and_destination_account_key.js
sdk/storage/storage-blob/recordings/node/appendblobclient_nodejs_only/recording_appendblockfromurl__source_sas_and_destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/blobclient_nodejs_only/recording_synccopyfromurl__destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/blobclient_nodejs_only/recording_synccopyfromurl__source_bearer_token_and_destination_account_key.js
sdk/storage/storage-blob/recordings/node/blobclient_nodejs_only/recording_synccopyfromurl__source_sas_and_destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_uploadpagesfromurl__destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_uploadpagesfromurl__source_bear_token_and_destination_account_key.js
sdk/storage/storage-blob/recordings/node/pageblobclient_nodejs_only/recording_uploadpagesfromurl__source_sas_and_destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_stageblockfromurl__destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_stageblockfromurl__source_bear_token_and_destination_account_key.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_stageblockfromurl__source_sas_and_destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_syncuploadfromurl__destination_bearer_token.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_syncuploadfromurl__source_bear_token_and_destination_account_key.js
sdk/storage/storage-blob/recordings/node/syncuploadfromurl/recording_syncuploadfromurl__source_sas_and_destination_bearer_token.js
sdk/storage/storage-blob/test/node/appendblobclient.spec.ts
sdk/storage/storage-blob/test/node/blobclient.spec.ts
sdk/storage/storage-blob/test/node/blockblobclient.spec.ts
sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
sdk/storage/storage-blob/test/node/sas.spec.ts
sdk/storage/storage-blob/test/utils/index.ts

Enable test cases for before released preview features.

[Storage] Enable test cases for before released preview features.

---

sdk/identity/identity/CHANGELOG.md

[Identity] Forgot to define the release date on the CHANGELOG.md

---

eng/js.gdnbaselines
eng/pipelines/aggregate-reports.yml

This is pre-requisite of PR:
https://github.com/Azure/azure-sdk-tools/pull/2775/files
We are ready to use credscan stable version. Put existing issues into baseline. Team will work on baseline file.
Current Use Version: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1372486&view=results
The stable version to use: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1375759&view=results

Update aggregate-report to use common credscan yml and update baseline

---

eng/CredScanSuppression.json
eng/pipelines/templates/jobs/ci.yml

The identity ci complains about the the `password` variable. Reports to credscan team, and wait for them to long term fix. This is a short term fix.

Suppress the password in short term
